content=["<dl>",
"<dt><a href='#Section0'>Crohn's disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Signs and symptoms are similar to those of UC so it is difficult to differentiate between these 2 types of inflammatory bowel disease by history and physical examination alone. However, Crohn's disease often has perianal involvement, rectal sparing, and a tendency to form fistulae.",
"<br><strong>Test:</strong> Endoscopy and biopsy. Distinguished from UC by inflammation that extends deep to the muscularis mucosae, the presence of granulomata (in about 35% to 50% of cases), and a relative lack of depletion of goblet cells on histology. Crohn's disease can affect the upper GI tract including the small bowel, so a more extensive GI work-up is often necessary in cases of diagnostic uncertainty.Serology: about 70% of patients with UC have positive perinuclear antineutrophil cytoplasmic antibodies, and approximately 70% of patients with Crohn's disease have positive anti-Saccharomyces cerevisiae antibody. [21]</p>",
"</dd>",
"<dt><a href='#Section1'>Indeterminate colitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> In the 10% to 15% of patients with inflammatory bowel disease involving only the colon, Crohn's disease cannot be distinguished from UC and a diagnosis of indeterminate colitis is made.Indeterminate colitis evolves in most patients to a definite diagnosis of UC or Crohn's disease on follow-up.",
"<br><strong>Test:</strong> Endoscopy and biopsy.Serological markers may help.</p>",
"</dd>",
"<dt><a href='#Section2'>Radiation colitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients have a history of receiving radiotherapy.",
"<br><strong>Test:</strong> Endoscopy and biopsy; histological findings support this diagnosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Infectious colitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History of recent exposure or travel.Usually self-limiting.",
"<br><strong>Test:</strong> Stool culture/biopsy.</p>",
"</dd>",
"<dt><a href='#Section4'>Diverticulitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Older age, fever, nausea, diarrhoea, or constipation.",
"<br><strong>Test:</strong> Leukocytosis, CT scan. Sigmoidoscopy and barium studies contraindicated in acute diverticulitis due to risk of perforation.</p>",
"</dd>",
"<dt><a href='#Section5'>Irritable bowel syndrome</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Lower abdominal pain and bloating associated with alteration of bowel habits and abdominal discomfort relieved with defecation.",
"<br><strong>Test:</strong> Patients have an absence of abnormal laboratory test, and normal levels of inflammatory markers. Endoscopy and biopsies are normal.</p>",
"</dd>",
"<dt><a href='#Section6'>Mesenteric ischaemia/ischaemic colitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Older age, history of cardiovascular disease.",
"<br><strong>Test:</strong> CT scan/endoscopy. Typical finding is thickening of the bowel wall in a segmental pattern.Endoscopic findings include pale mucosa with petechial bleeding. Bluish haemorrhagic nodules may be seen representing submucosal bleeding; these correspond to 'thumbprints' seen on radiographic studies.</p>",
"</dd>",
"<dt><a href='#Section7'>Vasculitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Abdominal pain, bloody stool. Systemic symptoms (fever, malaise, weight loss), vasculitis skin rash.",
"<br><strong>Test:</strong> Biopsy shows vasculitis pattern (leukocytoclastic, necrotising).</p>",
"</dd>",
"<dt><a href='#Section8'>Prolonged use of cathartics</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> History of use.",
"<br><strong>Test:</strong> Melanosis coli on endoscopy.</p>",
"</dd>",
"</dl>"].join("\n");