content=["<dl>",
"<dt><a href='#Section0'>Stable angina</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Pain occurs only in context of exertion or emotional stress, not worsening over time, and relieved by nitrates or rest.",
"<br><strong>Test:</strong> ECG may be normal in the absence of pain but may show ST depression during episodes of angina or on stress testing.</p>",
"</dd>",
"<dt><a href='#Section1'>Non-ST elevation myocardial infarction</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Clinical presentation may be indistinguishable.",
"<br><strong>Test:</strong> ECG may be normal or show ST depression or T wave inversion. Cardiac biomarkers (troponin, CK, CK-MB) are raised.</p>",
"</dd>",
"<dt><a href='#Section2'>ST-elevation myocardial infarction</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Clinical presentation may be indistinguishable.",
"<br><strong>Test:</strong> ECG shows persistent ST elevation in 2 or more leads. Cardiac biomarkers (troponin, CK, CK-MB) are raised.</p>",
"</dd>",
"<dt><a href='#Section3'>Congestive heart failure</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Breathlessness, orthopnoea, tachycardia, and peripheral oedema are usually predominant. Chest pain may occur if coronary perfusion is poor.",
"<br><strong>Test:</strong> Echocardiogram shows reduced left ventricular ejection fraction or signs of diastolic dysfunction. CXR may show congestion, cardiomegaly, or pleural effusion.</p>",
"</dd>",
"<dt><a href='#Section4'>Chest wall pain</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Onset often insidious and may be history of repetitive movement or minor trauma. Pain may be reproduced on palpation or movement. Not improved with rest or nitrates but may be relieved by local injection of lidocaine.",
"<br><strong>Test:</strong> CXR or bone scan may show skeletal pathology such as rib fracture, osteoarthritis, or metastatic tumour. Diagnosis of soft tissue lesions is clinical.</p>",
"</dd>",
"<dt><a href='#Section5'>Pericarditis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Recent MI, renal failure, chest irradiation, or associated connective tissue disease.Pain relieved by sitting up and leaning forwards and is worse when lying supine. If pleuropericarditis, the pain may be worse or present only on inspiration.Pericardial rub may be heard.",
"<br><strong>Test:</strong> ECG: concave ST elevation in all leads except aVR; PR segment depression.Echocardiogram may show minimal pericardial effusion, but is frequently normal.</p>",
"</dd>",
"<dt><a href='#Section6'>Myocarditis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> May be preceded by viral infection.Symptoms of myocarditis include chest pain (which may be pleuritic as a result of concomitant pericarditis), palpitations, fatigue, or signs of heart failure (e.g., peripheral oedema, increasing dyspnoea, and weight gain).",
"<br><strong>Test:</strong> ECG may show evidence of pericarditis or myopericarditis (ST elevation or nonspecific ST-T changes). Other findings include arrhythmias or conduction disturbances.Echocardiogram is helpful in excluding other causes of heart failure (e.g., valvular heart disease).Troponin levels are elevated in up to one third of cases.Serum viral antibody titres may suggest recent viral infection, but testing is rarely indicated in the diagnosis of viral myocarditis or any dilated cardiomyopathy, owing to its low specificity and the delay of rising viral titres, which would have no impact on therapeutic decisions.Anti-myosin scanning helps in diagnosis and when compared with endomyocardial biopsy shows a sensitivity of 83% and a specificity of 53%.MRI shows an area of delayed hyper-enhancement that does not match a coronary artery territory.Endomyocardial biopsy is necessary to establish a confirmed diagnosis of myocarditis. Histological criteria for myocarditis are well established. [43]  However, routine biopsy for establishing diagnosis of myocarditis is rarely helpful clinically, since histological diagnosis seldom has an impact on therapeutic strategies, unless giant cell myocarditis is suspected.</p>",
"</dd>",
"<dt><a href='#Section7'>Aortic dissection</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> History of hypertension, or Marfan's or Ehlers-Danlos syndrome. Occasionally precipitated by pregnancy.Severe tearing chest pain radiating between shoulder blades.Unequal pulses, inter-arm differential BP, diastolic murmur of aortic regurgitation.",
"<br><strong>Test:</strong> CXR: may show wide mediastinum.CT chest or trans-oesophageal echo: visualisation of luminal flap will confirm the dissection.</p>",
"</dd>",
"<dt><a href='#Section8'>Pulmonary embolism</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Recent surgery, immobilisation, prolonged air travel, or cancer.Acute shortness of breath, pleuritic chest pain, or syncope.Hypoxia, cyanosis, elevated jugular venous pressure with hypotension, and clear lung fields.",
"<br><strong>Test:</strong> ECG: sinus tachycardia, right bundle branch block, S1Q3T3 pattern.CXR: oligaemic and hyper-lucent lung fields, wedge-shaped infarct if pulmonary infarction.V/Q scan: pulmonary embolism is likely when an area of ventilation is not perfused.</p>",
"</dd>",
"<dt><a href='#Section9'>Pleuritis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Recent viral infection or prodrome of infection.Chest pain worse with inspiration.Audible pleuritic rub.",
"<br><strong>Test:</strong> CXR: may show resolving pneumonia.</p>",
"</dd>",
"<dt><a href='#Section10'>Pneumothorax</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Underlying lung disease, trauma, or recent procedures (such as insertion of central venous line).Acute chest pain with shortness of breath.If large, will lead to tracheal deviation, hyper-resonance, and decreased air entry.",
"<br><strong>Test:</strong> CXR: collapsed lung.</p>",
"</dd>",
"<dt><a href='#Section11'>Perforated abdominal viscus</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> History of previous peptic ulcer disease, diverticulitis, or recent bowel biopsy.Typically presents with abdominal pain. Chest pain is referred but may be mistaken for cardiac origin.Abdominal examination shows localised tenderness and, in cases of peritonitis, generalised tenderness.",
"<br><strong>Test:</strong> Erect CXR and abdominal series: gas under the diaphragm.CT abdomen: confirm the presence of free gas within the abdomen and peritoneal cavity.</p>",
"</dd>",
"</dl>"].join("\n");