content=["<dl>",
"<dt><a href='#Section0'>Adenomyosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Distinguished by uterine biopsy and subsequent histopathological examination.Imaging with pelvic ultrasonography and MRI are also helpful. [52]</p>",
"</dd>",
"<dt><a href='#Section1'>Endometrial polyp</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Sonohysterography typically shows a well-circumscribed isoechoic polypoid mass with stalk contained within the endometrial stripe. [27] View imageT2-weighted MRI images may show decreased signal intensity compared with endometrium. [43]</p>",
"</dd>",
"<dt><a href='#Section2'>Endometrial hyperplasia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Endometrial biopsy, and dilatation and curettage, provide differentiation. [53]</p>",
"</dd>",
"<dt><a href='#Section3'>Endometrial carcinoma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Because of the high prevalence of uterine fibroids in the general female population, a substantial number of patients with endometrial carcinoma will present with abnormal vaginal bleeding or discharge in association with uterine fibroids. [29]",
"<br><strong>Test:</strong> Endometrial sampling: an abnormal endometrial biopsy would show either precursor histology for endometrial carcinoma (simple/complex hyperplasia or simple atypical/complex atypical hyperplasia) or frank endometrial carcinoma. [29]Dilatation and curettage: persistence of irregular vaginal bleeding despite a negative endometrial biopsy should be pursued by dilatation and curettage. [31]</p>",
"</dd>",
"<dt><a href='#Section4'>Uterine sarcoma (leiomyosarcoma, endometrial stromal sarcoma, mixed mesodermal tumour)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Rapid growth of the tumour may be present in uterine sarcomas.",
"<br><strong>Test:</strong> No test can reliably diagnose uterine sarcoma.Serial MRI can identify rapid uterine growth and show characteristics associated with sarcomas such as indistinct borders and invasion into contiguous organs. [43]</p>",
"</dd>",
"<dt><a href='#Section5'>Pregnancy</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms of pregnancy (e.g., morning sickness) and missed menstrual period are associated with abdominal expansion over a few weeks.On examination, uterine enlargement due to pregnancy usually presents as soft, regular, globular pelvic-abdominal mass with its height coinciding with expected gestational age calculated from the last menstrual period.",
"<br><strong>Test:</strong> Pelvic ultrasonography visualises the pregnancy sac. [52]The urine or blood beta-hCG pregnancy test is positive. Pregnancy tests usually become positive about 26 to 30 days after the first day of the last menstrual period. Serum beta-hCG test is considered positive if levels are above 5 mIU/mL.</p>",
"</dd>",
"<dt><a href='#Section6'>Ovarian cancer</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Ovarian cancer is differentiated by rapid tumour growth associated with atypical age for leiomyoma (e.g., post-menopausal women not on hormone replacement therapy), rapid weight loss, or ascites.",
"<br><strong>Test:</strong> Pelvic ultrasonography and MRI are useful first-line investigations. MRI may show characteristic low-signal intensity on T2-weighted images seen with uterine fibroids, may show surrounding tissue invasion, and can more exactly define the origin of pelvic masses (uterine versus adnexal). [54]Surgery and histopathological examination provide differentiation. [52]</p>",
"</dd>",
"<dt><a href='#Section7'>Tumours of the GI tract and urinary system, lymphomas, and bone tumours</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> These serious conditions are differentiated by rapid tumour growth associated with atypical age for leiomyoma (e.g., post-menopausal women not on hormone replacement therapy), surrounding tissue invasion, rapid weight loss, or ascites.",
"<br><strong>Test:</strong> Pelvic ultrasonography and MRI are useful first-line investigations.Surgery and histopathological examination provide differentiation. [52]</p>",
"</dd>",
"</dl>"].join("\n");      