content=["<dl>",
"<dt><a href='#Section0'>Depression</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Depression is a risk factor for cognitive decline.Severe depression can sometimes be mistaken for dementia. However, much more commonly depression is seen as a feature in patients with established dementia.",
"<br><strong>Test:</strong> Cognitive tests and depression rating scales identify symptoms of depression.Brain CT and MRI: lack of vascular lesions is supportive.</p>",
"</dd>",
"<dt><a href='#Section1'>Alzheimer's disease (AD)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Onset of cognitive symptoms before stroke onset (stroke can convert those with sub-clinical AD), lack of clear interval events, gradual course, and rapid forgetting. In many cases, patients probably have a mixed dementia, a combination of AD and vascular disease.",
"<br><strong>Test:</strong> Cognitive testing, brain MRI, PET scan. Lack of vascular lesions on brain MRI supports mainly AD. PET scan shows parieto-temporal hypometabolism and patchy vascular change.</p>",
"</dd>",
"<dt><a href='#Section2'>Mild cognitive impairment (MCI)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> State of mild memory decline without loss of social or occupational functioning.",
"<br><strong>Test:</strong> Cognitive screening can identify mild memory complaints. Cognitive impairment not severe enough to meet full DSM-IV-TR criteria for vascular dementia supports the diagnosis of MCI.</p>",
"</dd>",
"<dt><a href='#Section3'>Lewy body dementia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Vivid visual hallucinations, autonomic instability, and Parkinson's features (shuffling gait, bradykinesia, and falls) are characteristic.Rapid eye movement sleep disorder may be present.",
"<br><strong>Test:</strong> No reliable or valid differentiating test.Brain pathology demonstrates the presence of round, eosinophilic, intraneuronal inclusions called Lewy bodies. Neuropathological findings include neurofibrillary tangles, amyloid plaques, and Lewy neuritis.</p>",
"</dd>",
"<dt><a href='#Section4'>Normal pressure hydrocephalus</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Gait disturbance and incontinence may be present as well as dementia.",
"<br><strong>Test:</strong> CT scan and MRI show large non-obstructive dilated ventricles without brain atrophy or vascular lesions.</p>",
"</dd>",
"</dl>"].join("\n");