content=["<dl>",
"<dt><a href='#Section0'>Encephalitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients with viral meningitis have normal cerebral function. Abnormal cerebral function such as altered behaviour, or speech or motor disorders, particularly when seen in association with fever, suggests a diagnosis of encephalitis.",
"<br><strong>Test:</strong> Encephalitis is a clinical diagnosis. The CSF profile will be similar to that seen in viral meningitis but the aetiological agents are sometimes different.</p>",
"</dd>",
"<dt><a href='#Section1'>Meningitis, bacterial</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating symptoms and signs.",
"<br><strong>Test:</strong> Typical CSF in acute bacterial meningitis will show a neutrophilic pleocytosis, elevated CSF protein, and decreased CSF glucose. Bacteria may be seen on Gram stain. An aseptic profile is seen in meningitis due to syphilis, Lyme disease, rickettsia, and brucellosis. However, CSF or blood culture may yield an aetiological agent such as meningococcus.</p>",
"</dd>",
"<dt><a href='#Section2'>Drug-induced meningitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating symptoms and signs.NSAIDs, trimethoprim/sulfamethoxazole, amoxicillin, ranitidine are culprit drugs.",
"<br><strong>Test:</strong> This is a diagnosis of exclusion. CSF typically shows a neutrophilic pleocytosis. Symptoms resolve once the offending drug is stopped.</p>",
"</dd>",
"<dt><a href='#Section3'>Tuberculous meningitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Presentation is usually more chronic with a prodromal period of general malaise and fever preceding meningitis.",
"<br><strong>Test:</strong> Presents with a lymphocytic pleocytosis.CSF protein is usually markedly elevated; CSF glucose is depressed.Diagnosis rests on positive microscopy or culture.CXR may be abnormal.</p>",
"</dd>",
"<dt><a href='#Section4'>Cryptococcal meningitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Presentation is often insidious with onset of headache and fever over weeks or months. A rash resembling molluscum contagiosum may be present in disseminated cryptococcal disease.",
"<br><strong>Test:</strong> Testing CSF for cryptococcal antigen has a sensitivity of almost 100% for cryptococcal meningitis.In HIV-positive patients the fungal burden is high, leading to high CSF pressures. The CSF leukocyte count may be low. An India ink stain or cryptococcal antigen is usually positive.HIV-negative patients have higher CSF leukocyte counts and the India ink stain is positive in only half of cases.</p>",
"</dd>",
"</dl>"].join("\n");