content=["<dl>",
"<dt><a href='#Section0'>Primary hyperparathyroidism</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There may be a FHx of hyperparathyroidism. Most patients are asymptomatic. However, symptoms include fatigue, poor sleep, anxiety, depression, memory loss, bone pain, and constipation.Although rare, physical examination of the neck may identify a hard, dense, firm mass suggestive of parathyroid carcinoma. [65]  An eye examination may demonstrate signs such as band keratopathy (a deposition of calcium just inside the iris).",
"<br><strong>Test:</strong> Elevated serum calcium, elevated intact PTH, and a low-normal or low fasting serum phosphate level.</p>",
"</dd>",
"<dt><a href='#Section1'>Multiple myeloma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms and signs are non-specific and commonly include bone pain and anaemia. Weight loss can also occur.",
"<br><strong>Test:</strong> Elevated serum calcium, low level of intact PTH and 1,25-dihydroxyvitamin D.Bone x-ray shows lytic bone lesions, characteristic of multiple myeloma.Gamma globulin assessment defines the disorder as well.Serum creatinine and urea levels are abnormal in 50% of multiple myeloma patients.Serum and urine protein electrophoresis is diagnostic of multiple myeloma.</p>",
"</dd>",
"<dt><a href='#Section2'>Fibromyalgia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> A chronic pain syndrome diagnosed by the presence of widespread body pain (front and back, right and left, both sides of the diaphragm) for at least 3 months, in addition to tenderness (digital palpation at an approximate force of 4 kg) of at least 11 out of 18 designated tender point sites as defined by the American College of Rheumatology 1990 classification criteria. [66]",
"<br><strong>Test:</strong> Clinical diagnosis.Normal serum 25-hydroxyvitamin D.</p>",
"</dd>",
"<dt><a href='#Section3'>Chronic fatigue syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Characterised by persistent fatigue and other associated symptoms (e.g., musculoskeletal pain, sleep disruption, memory impairments) lasting for 6 months or longer. The fatigue is not related to other medical conditions, disease processes, or identifiable biological causes. Sleep, rest, and activity restriction do not improve symptoms.Patients may present with a low-grade fever, tender lymph nodes, muscle pain/joint stiffness on palpation, tachycardia, hyperventilation, and/or orthostatic hypotension.",
"<br><strong>Test:</strong> Clinical diagnosis.Normal serum 25-hydroxyvitamin D.</p>",
"</dd>",
"<dt><a href='#Section4'>Paget's disease</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Usually asymptomatic, but may present with severe pain in long bones and, although unusual, in some facial areas.",
"<br><strong>Test:</strong> Normal serum calcium and a markedly elevated serum alkaline phosphatase (due to increased bone remodelling in the Pagetic bone).On x-ray there is a mottled appearance and gross deformities of bone may be seen, such as enlargement of the skull and bowing of the femur or tibia.</p>",
"</dd>",
"<dt><a href='#Section5'>Hypophosphatasia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> An autosomal-recessive disorder that radiographically resembles rickets.It is an inborn error of metabolism in which activity of tissue-nonspecific (liver/bone/kidney) alkaline phosphatase is deficient. [61]",
"<br><strong>Test:</strong> Defined by low serum alkaline phosphatase activity.Large quantities of phosphoethanolamine are found in the urine.</p>",
"</dd>",
"<dt><a href='#Section6'>Metaphyseal dysostoses</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Includes Jansen's and Schmid's types of metaphyseal dysostosis and Pyle's disease.Bowing of the legs, short stature, and a waddling gait. [61]",
"<br><strong>Test:</strong> Absence of abnormalities of low serum levels of calcium and phosphate, alkaline phosphatase activity, or vitamin D metabolites.</p>",
"</dd>",
"<dt><a href='#Section7'>Blount's syndrome</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Condition that causes osteochondrosis of the tibia, resulting in bowing of the legs. May be related to obesity.",
"<br><strong>Test:</strong> Absence of abnormalities of low serum levels of calcium and phosphate, alkaline phosphatase activity, or vitamin D metabolites.</p>",
"</dd>",
"</dl>"].join("\n");