content=["<dl>",
"<dt><a href='#Section0'>Systemic vasculitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Vasculitis may present similarly including presence of constitutional symptoms but also with low-grade fever.",
"<br><strong>Test:</strong> Examination of inflammatory blood markers (ESR, C-reactive protein, and others) might suggest an inflammatory disorder such as vasculitis, as opposed to scurvy, in which inflammatory markers should be normal in the absence of concomitant infection. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section1'>Haematological malignancy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Dermatological findings about the lower legs and ankles are less likely.",
"<br><strong>Test:</strong> Examination of FBC or peripheral blood smear should be normal in scurvy but might suggest leukaemia/lymphoma in the appropriate context. Bone marrow biopsy would be further supportive evidence. Radionuclide bone scan should be unremarkable despite possible abnormal MRI findings. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section2'>Meningococcaemia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Associated with fever or meningismus.",
"<br><strong>Test:</strong> FBC may be consistent with infection in this condition but should only reveal anaemia in patients with scurvy.Cultures of blood or cerebrospinal fluid may yield meningococcus. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section3'>Gonococcaemia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Associated with fever or meningismus.",
"<br><strong>Test:</strong> FBC may be consistent with infection in this condition but should only reveal anaemia in patients with scurvy.Blood cultures may yield gonococcus. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section4'>Rocky Mountain spotted fever</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Associated with fever or meningismus.",
"<br><strong>Test:</strong> Specific tests for Rocky Mountain spotted fever are unreliable early in the disease. An indirect fluorescent antibody test completed after the first 5 days of symptoms is diagnostic. Before treatment, a skin biopsy can establish a diagnosis as well. A rickettsial blood culture is only available in research centres but is highly accurate. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section5'>Ecthyma gangrenosum</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Associated with fever or meningismus.",
"<br><strong>Test:</strong> FBC may be consistent with infection in this condition but should only reveal anaemia in patients with scurvy. If systemic symptoms are present, a blood culture for pseudomonas should be completed. Also, a Gram stain and culture on soft tissue or drainage to identify pseudomonas or other water bacteria is warranted. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section6'>Child abuse or other blunt trauma</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs and symptoms.",
"<br><strong>Test:</strong> Radiographic findings may aid in diagnosis as abuse cases often show fractures at varying stages of healing. On x-ray, scurvy shows irregularities and microfractures at the metaphysis and growth plate of the knee and wrist. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section7'>Disseminated intravascular coagulation</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Associated with fever or severe hypotension. However, these may be symptoms of scurvy with concomitant infection.",
"<br><strong>Test:</strong> FBC may be consistent with infection in this condition but should only reveal anaemia in scurvy. In early DIC, PT and PTT may be prolonged, platelet count low, with elevated D-dimer and plasma degradation products, and reduced plasma factors V and VIII. Later in disease, PT, PTT, and plasma factors normalise, with consistently high D-dimer and plasma degradation products. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section8'>Idiopathic thrombotic purpura</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs and symptoms.",
"<br><strong>Test:</strong> Scurvy is associated with normal platelet count. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section9'>Thrombotic thrombocytopenic purpura</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs and symptoms.",
"<br><strong>Test:</strong> Scurvy is associated with normal platelet count. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section10'>Aspirin overdose</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> History should differentiate.",
"<br><strong>Test:</strong> The plasma salicylate concentration of 724 to 2172 micromol/L (10 to 30 mg/dL or 100 to 300 microgram/mL) determines aspirin usage and a level above 2896 micromol/L (above 40 mg/dL or 400 microgram/mL) indicates toxicity. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section11'>Cryoglobulinaemia</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Cryoglobulinaemia often displays erythematous macules or purpuric papules of the lower extremities and bloody crusts and ulcers. Raynaud's phenomenon may be present as well.",
"<br><strong>Test:</strong> Laboratory demonstration of serum cryoglobulins indicates cryoglobulinaemia. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section12'>Waldenstrom's macroglobulinaemia</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs and symptoms.",
"<br><strong>Test:</strong> A bone marrow smear shows a specific pattern (10% or greater WBCs with plasma cell differentiation with intertrabecular pattern) in Waldenstrom's macroglobulinaemia. Serum IgM level is high as well. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section13'>Autoerythrocyte sensitisation</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Autoerythrocyte sensitisation is associated with extreme emotional stress.",
"<br><strong>Test:</strong> Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section14'>Ehlers-Danlos syndrome</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Diagnosis suggested by joint laxity.",
"<br><strong>Test:</strong> Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section15'>Osteogenesis imperfecta</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Blue sclera and propensity for fractures.",
"<br><strong>Test:</strong> Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section16'>Pseudoxanthoma elasticum</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs and symptoms.",
"<br><strong>Test:</strong> Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section17'>Systemic amyloidoses</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs and symptoms.",
"<br><strong>Test:</strong> Diagnosis is established by biopsy of an affected organ; microscopy with polarised light reveals green birefringence with Congo red staining; other microscopical techniques may yield similar results. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section18'>Henoch-Schonlein purpura</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> Pruritus.",
"<br><strong>Test:</strong> Anaemia is rare in Henoch-Schonlein purpura. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section19'>Goodpasture's syndrome</a></dt>",
"<dd id='Section19'>",
"<p><strong>Sign & Symptoms:</strong> There may be pulmonary and renal involvement.",
"<br><strong>Test:</strong> Elevated anti-neutrophil cytoplasmic antibodies are not found in scurvy. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section20'>Polyarteritis nodosa</a></dt>",
"<dd id='Section20'>",
"<p><strong>Sign & Symptoms:</strong> MI and ulcers may be seen.",
"<br><strong>Test:</strong> Elevated anti-neutrophil cytoplasmic antibodies are not found in scurvy. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section21'>Menkes' disease</a></dt>",
"<dd id='Section21'>",
"<p><strong>Sign & Symptoms:</strong> Features include white hair colour, early retardation in growth, developmental delay, seizures, and focal cerebral and cerebellar degeneration. Perhaps the only genetic syndrome to be mistaken for scurvy.",
"<br><strong>Test:</strong> Menkes' heterozygotic carriers may have similar changes in long bone metaphyses. [32]  Low serum copper (&lt;11micromol/L; &lt;70 mg/dL) and serum ceruloplasmin (&lt;200 mg/L) are found in Menkes'. On microscopical examination of hair, a specific finding of pili torti is found in Menkes' as well. Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"<dt><a href='#Section22'>Acquired limp or limb pain in a child</a></dt>",
"<dd id='Section22'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs and symptoms.",
"<br><strong>Test:</strong> Normal serum, leukocyte, and whole blood ascorbic acid levels help rule out scurvy.</p>",
"</dd>",
"</dl>"].join("\n");