content=["<dl>",
"<dt><a href='#Section0'>Alcohol intoxication</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> A high blood alcohol level can confirm alcohol intoxication but does not exclude co-existent Wernicke's encephalopathy, because the clinical symptoms and signs overlap.",
"<br><strong>Test:</strong> Blood alcohol level above 100 mg/dL in alcohol intoxication.</p>",
"</dd>",
"<dt><a href='#Section1'>Alcohol withdrawal</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients with delirium tremens present with tachycardia, hypertension, agitation, diaphoresis, mydriasis, hallucinations, and seizures.",
"<br><strong>Test:</strong> This is a clinical diagnosis; there are no specific differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section2'>Viral encephalitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients typically present with any combination of cognitive impairment, altered sensorium, seizures, fever, or focal neurological deficits.",
"<br><strong>Test:</strong> The findings of CSF analysis, which typically shows a pleocytosis and elevated CSF protein.In certain viral encephalitides, abnormal MRI and EEG findings help to distinguish them from Wernicke's encephalopathy.</p>",
"</dd>",
"<dt><a href='#Section3'>Miller-Fisher syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients typically present with ophthalmoplegia, ataxia, and reduced or absent reflexes.Mental status is rarely affected in this condition unless complications of respiratory failure or autonomic insufficiency ensue.It is usually preceded by a viral illness.",
"<br><strong>Test:</strong> Anti-GQ1b or -GT1b antibodies are positive in serum, and CSF analysis shows cyto-albuminological dissociation. Nerve conduction studies may show evidence of axonal loss and prolonged F-waves.</p>",
"</dd>",
"<dt><a href='#Section4'>Bickerstaff brainstem encephalitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients typically present with diplopia, ataxia, and altered sensorium.",
"<br><strong>Test:</strong> MRI shows high-intensity T2 abnormalities in the brainstem, cerebellum, and thalamus. Anti-GQ1b antibodies are positive in serum. CSF shows elevated protein and a lymphocytic pleocytosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Top-of-the-basilar syndrome (paramedian thalamic infarction) or deep cerebral venous thromboses</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients present with the acute onset of neurological deficits that are typically maximal at onset. The symptoms and signs can mimic those of Wernicke's encephalopathy.",
"<br><strong>Test:</strong> MRI with diffusion accompanied by angiographic evidence of vascular occlusion in a person with vascular risk factors helps to distinguish this from Wernicke's encephalopathy.</p>",
"</dd>",
"<dt><a href='#Section6'>Primary CNS lymphoma</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> In some patients, primary CNS lymphoma has a predilection to spread along periventricular pathways, and its clinical manifestations may mimic those of Wernicke's encephalopathy.",
"<br><strong>Test:</strong> CSF may show positive cytology, flow cytometry, or positive EBV viral PCR. The typical lesions of Wernicke's encephalopathy are symmetric; CNS lymphoma is typically asymmetric with accompanying necrosis.</p>",
"</dd>",
"<dt><a href='#Section7'>Toxic encephalopathies</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Unless there is a witness to the intoxication, or the patient is known to have access to offending medications or toxins, the presenting symptoms and signs are difficult to distinguish from those of Wernicke's encephalopathy.Offending drugs and toxins include phenytoin, aspirin, carbamazepine, phenobarbital, benzodiazepines, methyl bromide, methanol, ethylene glycol.",
"<br><strong>Test:</strong> A urine drug and volatile toxicology screen should be done in all patients presenting with altered sensorium in whom a clear aetiology is not identified after initial evaluation.</p>",
"</dd>",
"<dt><a href='#Section8'>Metabolic encephalopathies</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Hepatic and uraemic encephalopathies can cause varying degrees of cognitive dysfunction.",
"<br><strong>Test:</strong> A comprehensive metabolic panel, blood-gas analyses, and serum ammonia can help to distinguish these from Wernicke's encephalopathy.</p>",
"</dd>",
"</dl>"].join("\n");