content=["<dl>",
"<dt><a href='#Section0'>Viral hepatitis B</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients with viral hepatitis may have a history of a febrile illness or blood transfusion, but otherwise the symptoms and signs may be identical.",
"<br><strong>Test:</strong> Hepatitis B antigen positive.</p>",
"</dd>",
"<dt><a href='#Section1'>Viral hepatitis C</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients with viral hepatitis may have a history of a febrile illness or blood transfusion, but otherwise the symptoms and signs may be identical.",
"<br><strong>Test:</strong> Hepatitis C antibody positive.</p>",
"</dd>",
"<dt><a href='#Section2'>Haemochromatosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients with haemochromatosis may present with other features such as diabetes, skin pigmentation, arthritis, impotence in males, and cardiac enlargement with or without symptoms and signs of heart failure.",
"<br><strong>Test:</strong> Iron parameters and liver biopsy are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section3'>Alpha-1 antitrypsin deficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients with alpha-1 antitrypsin deficiency may have chronic lung disease such as emphysema occurring earlier than expected (in the 40- to 50-year-old age group) as well as liver disease.",
"<br><strong>Test:</strong> Tests show that enzyme is deficient.</p>",
"</dd>",
"<dt><a href='#Section4'>Auto-immune hepatitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have other associated auto-immune conditions and will respond to steroid therapy. However, Wilson's disease should be excluded before this diagnosis is assumed.",
"<br><strong>Test:</strong> Patients may have a positive auto-antibody screen including ANA, primarily in a homogenous pattern, anti-smooth muscle antibody, anti-liver-kidney microsomal antibody, and others.</p>",
"</dd>",
"<dt><a href='#Section5'>Steatohepatitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients with steatohepatitis tend to be obese with clinical features of hepatitis. Wilson's disease should be excluded before this diagnosis is assumed.",
"<br><strong>Test:</strong> Fatty liver and inflammation on biopsy.</p>",
"</dd>",
"<dt><a href='#Section6'>Alcoholic cirrhosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have a history and signs of alcohol excess. Wilson's disease should be excluded before this diagnosis is assumed, even if the patient drinks.",
"<br><strong>Test:</strong> None.</p>",
"</dd>",
"<dt><a href='#Section7'>Haemolytic anaemia</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> If hepatic bouts are severe in Wilson's disease then haemolysis may occur. Haemolysis in the presence of liver disease in a person aged &lt;40 years should prompt testing for Wilson's disease.",
"<br><strong>Test:</strong> Tests for alternative causes of haemolytic anaemia, including Coombs antibody, haemoglobin electrophoresis for HbS, and auto-antibody screening for auto-immune diseases, are used to determine the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section8'>Essential tremor</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Tremor with no other neurological symptoms of a movement disorder. May have positive family history.Wilson's disease should be excluded before you make this diagnosis especially in all patients aged &lt;40 years and in many aged &lt;50 years.",
"<br><strong>Test:</strong> None.</p>",
"</dd>",
"<dt><a href='#Section9'>Parkinson's disease</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Parkinson's disease usually occurs in older people (&gt;50 years), but the movement disorders are often identical. The diagnosis of Parkinson's disease is made on history and neurological examination.",
"<br><strong>Test:</strong> None.</p>",
"</dd>",
"<dt><a href='#Section10'>Psychiatric disease</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Psychiatric disease unrelated to Wilson's disease will not be accompanied by features of Wilson's disease. Wilson's disease patients with primary psychiatric disease are more likely to have early childhood problems, and these patients almost always have Kayser-Fleischer rings.",
"<br><strong>Test:</strong> None.</p>",
"</dd>",
"</dl>"].join("\n");