content=["<dl>",
"<dt><a href='#Section0'>Cutis laxa</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Rare, inherited, or acquired connective tissue disorder characterised by degenerative changes in the elastic fibres resulting in loose, pendulous skin.Skin is sagging, redundant, and stretchable, with reduced elastic recoil.Internal organs are frequently involved. Pulmonary diseases such as pulmonary emphysema, cor pulmonale, and right-sided heart failure are often seen. Cardiovascular abnormalities include aortic aneurysm and pulmonary artery multiple branch stenosis.",
"<br><strong>Test:</strong> Clinical differentiation is usually sufficient.Cultured cutis laxa dermal fibroblasts: increased elastolytic activity compared with healthy skin.Skin biopsy: changes in the quantity or morphology of elastin with characteristic fragmentation or loss of elastic fibres and possible abnormal cross-linking of elastin.</p>",
"</dd>",
"<dt><a href='#Section1'>Werner's syndrome (progeria or pangeria)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Characteristic clinical signs include short stature (&lt;1.60 m), thin skin, muscle atrophy, wrinkling of the skin and ageing of the face, a scleroderma-like appearance, loss of subcutaneous fat, loss of hair, and nail dystrophy.Cataracts occur between 20 to 40 years of age. Osteoporosis, diabetes mellitus, neoplasias, hyperthyreosis, pituitary dysfunction, arteriosclerosis, soft-tissue calcification, hypogonadism or agonadism, and premature menopause are the most common features of the disease.",
"<br><strong>Test:</strong> Biopsy: histological examination of the skin and subcutaneous tissue reveals thinning of the epidermis, loss of rete ridges, dermal fibrosis, and replacement of the subcutaneous fat with newly synthesised hyalinised collagen.</p>",
"</dd>",
"<dt><a href='#Section2'>Xeroderma pigmentosum</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Rare autosomal disorder characterised by photosensitivity, pigmentary changes, premature skin ageing, and malignant tumour development due to a cellular hypersensitivity to UV radiation. [44]",
"<br><strong>Test:</strong> Biopsy: initial histological findings include hyperkeratosis and increased melanin pigment in the basal cell layer, elongation and atrophy of the rete ridges, and chronic inflammatory infiltrate in the upper dermis. Atrophy, hyperkeratosis, hyperpigmentation, and telangiectasias are more marked in the later stages. Architectural disorder and atypia are noted at the epidermis, and the dermis may be elastotic.</p>",
"</dd>",
"</dl>"].join("\n");