content=["<dl>",
"<dt><a href='#Section0'>Gram-negative sepsis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms and signs may be similar. Absence of painful buboes in gram-negative sepsis. Secondary septicaemic plague after pneumonic plague is associated with haemoptysis and pleuritic chest pain.",
"<br><strong>Test:</strong> Blood cultures positive for gram-negative bacilli other than Yersinia pestis.</p>",
"</dd>",
"<dt><a href='#Section1'>Bacterial pneumonia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Less abrupt onset. Pneumonic plague may cause outbreaks but is now thought to be less contagious than was previously believed. [4]  [29]",
"<br><strong>Test:</strong> Sputum or blood culture positive for respiratory pathogens other than Y pestis.</p>",
"</dd>",
"<dt><a href='#Section2'>Cat scratch disease</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Indolent course without significant systemic features.",
"<br><strong>Test:</strong> Positive serology for Bartonella henselae.</p>",
"</dd>",
"<dt><a href='#Section3'>Bacterial lymphadenitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Lymphadenitis due to streptococci or staphylococci may be associated with lymphangitis or cellulitis. Lymph nodes are more likely to be fluctuant.",
"<br><strong>Test:</strong> Blood cultures or other clinical samples positive for Staphylococcus aureus or streptococcal species.</p>",
"</dd>",
"<dt><a href='#Section4'>Mycobacterial infection</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Clinical course is indolent. Lymphadenitis tends to be non-tender.",
"<br><strong>Test:</strong> Positive cultures for Mycobacterium species.</p>",
"</dd>",
"<dt><a href='#Section5'>Tularaemia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Glandular, typhoidal, and pneumonic presentations may be difficult to distinguish clinically from plague.The 2 conditions co-exist in many endemic areas worldwide.",
"<br><strong>Test:</strong> Positive cultures for Francisella tularensis (laboratory is informed if tularaemia suspected).Positive serology for F tularensis.</p>",
"</dd>",
"<dt><a href='#Section6'>Rocky Mountain spotted fever and other ricketssial infections</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> A more indolent course is typical with less systemic toxicity. Headache is often a prominent feature. Generalised rash is frequent, which may be petechial or maculopapular.",
"<br><strong>Test:</strong> Rickettsial infection may be confirmed serologically.</p>",
"</dd>",
"<dt><a href='#Section7'>Infectious diarrhoea (yersiniosis)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Differential diagnosis is broad, as various bacteria, parasites, and viruses cause diarrhoea.",
"<br><strong>Test:</strong> Presence of specific infectious agent on stool or serological testing.</p>",
"</dd>",
"<dt><a href='#Section8'>Acute appendicitis (yersiniosis)</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Absence of diarrhoea and/or bloody stools. Usually right lower quadrant tenderness.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"</dl>"].join("\n");