content=["<dl>",
"<dt><a href='#Section0'>Oesophageal carcinoma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Dysphagia is mainly for solids, although difficulty in swallowing liquids develops with advanced disease.Weight loss may be severe.",
"<br><strong>Test:</strong> Barium swallow and endoscopy will show oesophageal obstruction by the tumour.</p>",
"</dd>",
"<dt><a href='#Section1'>Reflux oesophagitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Can give rise to dysphagia through inflammatory swelling or a fibrotic peptic stricture, or even in the absence of endoscopic abnormalities.The patient will usually also report heartburn and/or regurgitation in addition to dysphagia.",
"<br><strong>Test:</strong> Endoscopy will show reflux oesophagitis, with or without a peptic stricture. A hiatus hernia may be present below the stricture.Barium swallow has low sensitivity for oesophagitis but will show up strictures and hiatus hernias. Gastro-oesophageal reflux will be demonstrated.Lower oesophageal pH studies will demonstrate pathological gastro-oesophageal reflux.</p>",
"</dd>",
"<dt><a href='#Section2'>Connective tissue disorders (e.g., systemic sclerosis)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Muscle and joint pain, Raynaud's phenomenon, skin changes (e.g., rash, skin swelling or thickening).",
"<br><strong>Test:</strong> Antinuclear antibodies, rheumatoid factor, creatine kinase, and ESR are useful initial screening tests for connective tissue pathology.</p>",
"</dd>",
"<dt><a href='#Section3'>Oesophageal spasm</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Chest pain is often more prominent than dysphagia, which tends to be intermittent.",
"<br><strong>Test:</strong> Manometry shows high-amplitude oesophageal contractions rather than the aperistalsis usually seen in achalasia.</p>",
"</dd>",
"<dt><a href='#Section4'>Eosinophilic oesophagitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Presents with intermittent dysphagia, often in young men with history of atopy.",
"<br><strong>Test:</strong> Oesophageal biopsy shows eosinophilic infiltration (&gt;15 eosinophils per high-power field).</p>",
"</dd>",
"<dt><a href='#Section5'>Pseudoachalasia (or secondary achalasia)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Underlying malignancy that mimics idiopathic achalasia.Patients tend to be older, duration of symptoms shorter, [17]  and weight loss greater and more rapid.Dysphagia is clinically indistinguishable.",
"<br><strong>Test:</strong> Gastroscopic biopsy of gastro-oesophageal junction and cardia may demonstrate malignancy.Findings at endoscopy, barium swallow, and manometry may be indistinguishable from achalasia.</p>",
"</dd>",
"<dt><a href='#Section6'>Chagas' disease</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Endemic to Latin America; multiple-organ involvement probably causing atonic colon, myocarditis, and Romana sign; swelling of the eyelids in acute disease.",
"<br><strong>Test:</strong> Microscopic examination of fresh blood showing presence of Trypanosoma cruzi.PCR for precise identification of trypanosome subtype.Giemsa staining of thick and thin blood films detects parasite.</p>",
"</dd>",
"</dl>"].join("\n");