content=["<dl>",
"<dt><a href='#Section0'>Arthritis of cervical spine</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Pain with passive neck movement, or crepitus, may occur with or without acquired torticollis.",
"<br><strong>Test:</strong> Degenerative skeletal changes on MRI of the neck.</p>",
"</dd>",
"<dt><a href='#Section1'>Neck mass</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Visible or palpable mass, limited passive ROM.",
"<br><strong>Test:</strong> Mass visualised on neck MRI.</p>",
"</dd>",
"<dt><a href='#Section2'>Cerebral mass, lesion or infarct</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Neurological abnormalities (e.g., hemiparesis, asymmetrical reflexes, cognitive and/or personality changes).",
"<br><strong>Test:</strong> Mass lesion or infarct visualised on brain MRI.</p>",
"</dd>",
"<dt><a href='#Section3'>Posterior fossa mass</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms provoked by neck extension, prominent headache, nausea and vomiting, dizziness.",
"<br><strong>Test:</strong> Posterior fossa mass visualised on brain MRI.</p>",
"</dd>",
"<dt><a href='#Section4'>Retropharyngeal abscess</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Systemic signs of infection, dysphagia.",
"<br><strong>Test:</strong> Enhancing mass on neck MRI.</p>",
"</dd>",
"<dt><a href='#Section5'>Parkinsonian syndromes</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Bradykinesia and rigidity beyond neck area, tremor, gait abnormality, postural instability, autonomic instability.",
"<br><strong>Test:</strong> Differentiated by clinical examination findings only.</p>",
"</dd>",
"<dt><a href='#Section6'>Huntington's disease</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Hyper-kinetic movements involving other body parts and/or cognitive and behavioural symptoms.Suggestive FHx.",
"<br><strong>Test:</strong> Detection of 36 or more cysteine/arginine/guanine repeats in the Huntington's disease gene.</p>",
"</dd>",
"<dt><a href='#Section7'>Tic disorder</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Abnormal neck movements accompanied by frequent tics such as blinking, ocular deviations, or sniffing.",
"<br><strong>Test:</strong> Differentiated by clinical history and exam findings only. Tics are usually preceeded by premonitory urge followed by release of tension with performance.</p>",
"</dd>",
"<dt><a href='#Section8'>Dopa-responsive dystonia</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Childhood onset.Responds therapeutically to a trial of levodopa.",
"<br><strong>Test:</strong> Differentiated by clinical examination findings only.</p>",
"</dd>",
"<dt><a href='#Section9'>Trochlear nerve palsy</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Extra-ocular movements limited.Diplopia corrected by abnormal head posture.",
"<br><strong>Test:</strong> Differentiated by clinical history and exam findings only.</p>",
"</dd>",
"<dt><a href='#Section10'>Primary torsion dystonia (DYT-1)</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Onset before fourth decade.Generalised dystonia.",
"<br><strong>Test:</strong> Presence of DYT-1 gene mutation.</p>",
"</dd>",
"<dt><a href='#Section11'>Wilson's disease</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Accompanying neuropsychiatric abnormalities.Kayser-Fleischer rings present on slit-lamp examination.",
"<br><strong>Test:</strong> Low serum ceruloplasmin, increased urinary copper excretion, mutation in ATP7B gene.</p>",
"</dd>",
"<dt><a href='#Section12'>Psychogenic dystonia</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Suggestive symptoms include previous somatisation, abrupt onset, secondary gain and absence of sensory trick.Psychogenic dystonia is rare and should be diagnosed with caution.",
"<br><strong>Test:</strong> Differentiated by clinical examination findings only.</p>",
"</dd>",
"</dl>"].join("\n");