content=["<dl>",
"<dt><a href='#Section0'>Smallpox</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Has more prominent fever and more noticeable constitutional symptoms than varicella.Greatest number of lesions are on face and extremities (centrifugal distribution), and lesions present at the same stage in development. [57]",
"<br><strong>Test:</strong> PCR test for smallpox will be positive.PCR test for varicella-zoster virus (VZV) will be negative.Review history of recent smallpox vaccine or other possible exposures. Since natural transmission has been eradicated, new cases would more likely occur through laboratory exposure or as an act of bioterroism. If smallpox is considered a possible diagnosis, immediate consultation should be sought and the patient should be placed in immediate isolation (standard, contact, and airborne). The patient should not be permitted to leave isolation until smallpox has been excluded as a diagnostic possibility. Consultation with local health departments is also highly recommended.</p>",
"</dd>",
"<dt><a href='#Section1'>Herpes zoster infection (shingles)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Commonly presents in adulthood, particularly after the age of 60.Rash typically follows a dermatomal distribution of a cranial nerve or dorsal root ganglion.",
"<br><strong>Test:</strong> Varicella zoster is a clinical diagnosis based on examination of the rash and history of exposure. Differentiating tests are not usually indicated.</p>",
"</dd>",
"<dt><a href='#Section2'>Herpes simplex virus infection</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Usually affects the mucous membranes of the oral or genital region but skin infections, usually localised, can also be observed.",
"<br><strong>Test:</strong> Laboratory tests positive for herpes simplex virus (HSV) 1 or HSV 2.</p>",
"</dd>",
"<dt><a href='#Section3'>Stevens-Johnson syndrome/toxic epidermal necrolysis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Lesions can look like targets initially but eventually become flaccid blisters.A large proportion of patients also present with diffuse erythema (erythroderma) and a significant number of patients complain of pain in involved areas.Blisters can become confluent and are associated with a positive Nikolsky sign (epidermal layer easily sloughs off when pressure is applied to the affected area). [58]",
"<br><strong>Test:</strong> Patients often have a history of exposure to an agent (medication) associated with the condition.Skin biopsy can be helpful; however, most often the diagnosis is made on clinical presentation. [59]</p>",
"</dd>",
"<dt><a href='#Section4'>Monkeypox</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Recent travel to Africa or recent exposure to exotic pets is likely to be present. [60]Lesions present in similar stages (monomorphic) and are found on the palms and soles of the feet.Also associated with lymphadenopathy, which is rarely found in varicella. [61]",
"<br><strong>Test:</strong> PCR test for monkeypox will be positive.</p>",
"</dd>",
"</dl>"].join("\n");