content=["<dl>",
"<dt><a href='#Section0'>Dry eyes</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically a chronic condition of adults; occurs in women more than men; usually bilateral with minimal discharge or eyelash matting; minimal injection; no discharge or lymphadenopathy. [38]  [39]  [40]  [41]  [42]  [43]",
"<br><strong>Test:</strong> Punctate staining of the cornea with fluorescein dye; Schirmer's tests with &lt;10 mm; tear break-up time &lt;10 seconds.</p>",
"</dd>",
"<dt><a href='#Section1'>Blepharitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typically a chronic condition of adults; women more than men; usually bilateral with minimal discharge or eyelash matting; minimal injection; no discharge or lymphadenopathy; presence of meibomian gland dysfunction, eyelid margin telangiectatic vessels; collarets along the lashes. [38]  [39]  [40]  [41]  [42]  [43]",
"<br><strong>Test:</strong> Tear break-up time &lt;10 seconds.</p>",
"</dd>",
"<dt><a href='#Section2'>Episcleritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Unilateral more common than bilateral; typically segmental injection; no discharge or eyelid matting; minimal discomfort. [38]  [39]  [40]  [41]  [42]  [43]",
"<br><strong>Test:</strong> No definitive tests; recurrent, bilateral, or persistent cases require blood tests to rule out a systemic inflammatory disease.</p>",
"</dd>",
"<dt><a href='#Section3'>Contact lens overwear</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History of sleeping in contacts; multiple recurrences; light sensitivity. [38]  [39]  [40]  [41]  [42]  [43]",
"<br><strong>Test:</strong> No definitive tests.</p>",
"</dd>",
"<dt><a href='#Section4'>Iritis (uveitis)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Pain and light sensitivity more pronounced than irritation; unilateral more common than bilateral. [38]  [39]  [40]  [41]  [42]  [43]Red and white blood cells, as well as flare (effect caused by an increase in the protein content of the aqueous) usually seen with slit-lamp examination.",
"<br><strong>Test:</strong> No definitive tests; recurrent, bilateral, or persistent cases require blood tests to rule out a systemic inflammatory disease.</p>",
"</dd>",
"<dt><a href='#Section5'>Acute angle-closure glaucoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Adult typically older than 40 years; nausea and vomiting may be be present as well as a deep, dull, periocular headache; unilateral; pain associated with decreased vision; mid-dilated, unreactive pupil; presence of an afferent pupillary defect. [38]  [39]  [40]  [41]  [42]  [43]",
"<br><strong>Test:</strong> Marked elevation in intraocular pressure (normal &lt;22 mmHg); thin corneas (pachymetry &lt;520); afferent pupillary defect.</p>",
"</dd>",
"</dl>"].join("\n");