content=["<dl>",
"<dt><a href='#Section0'>Benign prostatic hyperplasia (BPH)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with a gradual reduction in urinary flow, hesitancy, frequency, and nocturia. May also present with acute retention of urine.",
"<br><strong>Test:</strong> Clinical diagnosis with negative urinalysis. Histological examination of the prostate reveals BPH.</p>",
"</dd>",
"<dt><a href='#Section1'>Prostate cancer</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May present with similar symptoms to BPH (e.g., reduced urinary flow, frequency, and nocturia). Advanced cases may present with signs of metastatic disease, including bone pain.",
"<br><strong>Test:</strong> Serum PSA elevated and may be extremely high in advanced disease.Histological examination of the prostate reveals prostatic carcinoma.</p>",
"</dd>",
"<dt><a href='#Section2'>Urinary tract infection</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually do not have symptoms of bladder outflow obstruction unless they have coexisting BPH or prostatic malignancy.",
"<br><strong>Test:</strong> None. Urine cultures may be positive in acute prostatitis and UTIs.</p>",
"</dd>",
"<dt><a href='#Section3'>Bladder cancer</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with haematuria (either frank or microscopic). Patients may also complain of dysuria and urinary frequency.",
"<br><strong>Test:</strong> Urinalysis typically with haematuria, though may be negative (e.g., diluted urine sample).Cystoscopic examination of the bladder demonstrates the presence of a tumour.</p>",
"</dd>",
"<dt><a href='#Section4'>Colorectal cancer</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with a change in bowel habit and, in some patients, rectal bleeding. Patients may also present with weight loss.",
"<br><strong>Test:</strong> Endoscopic examination of the rectum and colon demonstrates the presence of a tumour.The tumour may also be demonstrated on imaging (e.g., barium enema).</p>",
"</dd>",
"<dt><a href='#Section5'>Epididymitis/orchitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with scrotal/testicular pain and symptoms of dysuria and frequency.",
"<br><strong>Test:</strong> Clinical diagnosis. Colour duplex ultrasonography may show enlarged and hyperaemic epididymis.</p>",
"</dd>",
"</dl>"].join("\n");