content=["<dl>",
"<dt><a href='#Section0'>Acute exacerbation of CHF</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> A history of cardiac disease, acute myocardial ischaemia or infarction, or a known low ejection fraction suggests cardiogenic pulmonary oedema, as do an S3 and elevated neck veins on physical examination.",
"<br><strong>Test:</strong> CXR: heart failure is suggested by an enlarged cardiac silhouette, a vascular pedicle width &gt;70 mm, central infiltrates, and Kerley B lines.Brain natriuretic peptide (BNP) levels &gt;500 nanograms/L (&gt;500 picograms/mL) also suggest cardiogenic oedema.Echocardiography and measurement of the pulmonary artery occlusion pressure (PAOP) may be needed if the history and physical and laboratory tests do not rule out cardiogenic pulmonary oedema.</p>",
"</dd>",
"<dt><a href='#Section1'>Bilateral pneumonia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> A history of fever and cough with or without sputum production.Patients may have pleuritic chest discomfort.",
"<br><strong>Test:</strong> CXR. Severe pneumonia with bilateral infiltrates mimics the radiographic appearance of ALI/ARDS.PaO2. If patients do not have severe hypoxaemia with their pneumonia, they do not have ALI/ARDS.</p>",
"</dd>",
"<dt><a href='#Section2'>Acute interstitial pneumonia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Onset is usually subacute, over days to weeks.Patients are previously healthy, with the lung disease not related to a systemic illness.Some authors have termed this disease idiopathic ALI/ARDS. [19]",
"<br><strong>Test:</strong> Meets all the clinical criteria for ALI/ARDS.Best differentiated by history.</p>",
"</dd>",
"<dt><a href='#Section3'>Diffuse alveolar haemorrhage</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Associated with bleeding from the small vessels of the airways (capillaritis) and seen in many conditions, ranging from autoimmune to mitral valve diseases.Almost always a reversible form of respiratory failure, once the underlying cause is known.",
"<br><strong>Test:</strong> A syndrome of hypoxia with infiltrates on CXR.The hallmark is finding sequentially bloodier aliquots of fluid during serial bronchoalveolar lavage.Serological tests to look for autoimmune diseases may help to differentiate from ALI/ARDS. [19]</p>",
"</dd>",
"<dt><a href='#Section4'>Acute eosinophilic pneumonia</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Presents as mild to severe pneumonia in previously healthy people.Patients have an excellent response to IV corticosteroids. [21]",
"<br><strong>Test:</strong> The hallmark of this disease is increased numbers of eosinophils (upwards of 50%) on bronchoalveolar lavage.</p>",
"</dd>",
"<dt><a href='#Section5'>Hypersensitivity pneumonitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> A pneumonitis after inhalation of an organic antigen.Patients present with infiltrates and a pneumonia syndrome that is clinically indistinguishable from ALI/ARDS if severe.Differentiated from ALI/ARDS by clinical history of an inhalational allergen, usually of avian origin.Corticosteroids may be beneficial. [19]",
"<br><strong>Test:</strong> No differentiating investigations.</p>",
"</dd>",
"<dt><a href='#Section6'>Post-obstructive pulmonary oedema</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Acute pulmonary oedema after removal of an upper airway obstruction, most commonly caused by laryngospasm.Causes an acute respiratory failure often requiring mechanical ventilation with varying levels of PEEP.The keys to differentiation are the history of upper airway obstruction, post-surgical development, and the rapid resolution of symptoms. [22]",
"<br><strong>Test:</strong> No differentiating investigations.</p>",
"</dd>",
"</dl>"].join("\n");