content=["<dl>",
"<dt><a href='#Section0'>Allergic rhinitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Ocular and/or nasal pruritus.Sneezing.Rhinorrhoea.Headache, purulent discharge, and facial pain/pressure are less common.",
"<br><strong>Test:</strong> Allergen skin-prick testing: wheal and flare reaction after specific allergen is introduced into the skin is 3 mm larger than negative (saline) control.In vitro-specific IgE determination: specific allergen response. [18]</p>",
"</dd>",
"<dt><a href='#Section1'>Non-allergic rhinitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Heterogenous group of nasal diseases that has nasal congestion as a common factor.History of pregnancy, barometric changes, food-associated symptoms, or hypothyroidism.",
"<br><strong>Test:</strong> Diagnosis is clinical: there are no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section2'>Migraine</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> History of migraine.Sensitivity to light or noise.Aura.Nausea.Symptoms decrease if sitting/lying in a quiet, dark room.Absence of purulent nasal discharge.",
"<br><strong>Test:</strong> Diagnosis is clinical: there are no differentiating tests. Radiological tests may exclude features of acute bacterial sinusitis.</p>",
"</dd>",
"<dt><a href='#Section3'>Adenoiditis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to differentiate in paediatric population as both conditions have similar symptoms.",
"<br><strong>Test:</strong> Nasal flexible endoscopy can be used to determine the source of infection, either from the adenoids or from the sinuses.</p>",
"</dd>",
"<dt><a href='#Section4'>Rhinosporidiosis and rhinoscleroma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Numbness of nasal cavity and face.Lack of expected bleeding of nasal cavity when traumatised during physical examination.Necrosis of nasal mucosa.",
"<br><strong>Test:</strong> Rigid nasal endoscopy should be performed without anaesthesia and decongestant of the nasal cavity, to evaluate for lack of sensation or bleeding when endoscope is pressed against nasal mucosa.</p>",
"</dd>",
"</dl>"].join("\n");