content=["<dl>",
"<dt><a href='#Section0'>Acute mesenteric adenitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Usually presents in children with a recent history of upper respiratory infection.Pain in the abdomen is usually diffuse with tenderness not localised to the right lower quadrant.Guarding may be present, but rigidity is usually absent.Generalised lymphadenopathy may be noted.",
"<br><strong>Test:</strong> There is no specific test to confirm the diagnosis.Relative lymphocytosis in WBC differential counts is suggestive.Negative ultrasound or CT findings help exclude other diagnoses.</p>",
"</dd>",
"<dt><a href='#Section1'>Viral gastroenteritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Common in children; caused by viruses, bacteria, or toxin.Characterised by profuse watery diarrhoea, nausea, and vomiting.Crampy abdominal pain often precedes the diarrhoea, and no localising signs are present.If caused by typhoid fever, intestinal perforation may cause localised abdominal pain and/or generalised and rebound tenderness. In this scenario, associated maculopapular rash, inappropriate bradycardia, and leukopenia will differentiate from appendicitis.",
"<br><strong>Test:</strong> No specific test unless due to typhoid (Salmonella typhi from stool or blood will confirm the diagnosis).</p>",
"</dd>",
"<dt><a href='#Section2'>Meckel's diverticulitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Usually asymptomatic.Only 20% of the patients present with diverticulitis, and 50% of this group are aged &lt;10 years. [40]Clinical presentation of diverticulitis is similar to acute appendicitis.",
"<br><strong>Test:</strong> Technetium pertechnetate scan may show the enhancement of diverticulum if gastric mucosa is present.</p>",
"</dd>",
"<dt><a href='#Section3'>Intussusception</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Occurs in young children (aged &lt;2 years).Sudden onset of colicky pain; between episodes of pain the child is calm.A sausage-shaped mass may be palpable in the right lower quadrant.",
"<br><strong>Test:</strong> Barium enema may demonstrate the intussusception with a coil-spring sign at the point of bowel invagination.</p>",
"</dd>",
"<dt><a href='#Section4'>Crohn's disease</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Young adult with fever, nausea, vomiting, diarrhoea, right lower quadrant pain, and localised tenderness.",
"<br><strong>Test:</strong> CT scan may show intra-abdominal abscess.Contrast study of the small bowel and colon may show stricture or a series of ulcers and fissures (cobblestone appearance) of mucosa.</p>",
"</dd>",
"<dt><a href='#Section5'>Peptic ulcer disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May or may not have a history of peptic ulcer disease.Pain is abrupt, severe in intensity, and may be localised to right lower quadrant.",
"<br><strong>Test:</strong> Erect CXR and abdominal x-ray may show free air under the diaphragm</p>",
"</dd>",
"<dt><a href='#Section6'>Right-sided ureteric stone</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Pain is usually colicky in nature and severe in intensity. May be referred to the labia, scrotum, or penis and associated with haematuria.Fever usually absent.",
"<br><strong>Test:</strong> Urinalysis positive for blood.Leukocytosis usually absent.Abdominal x-rays or tomogram may show calcified stone.Pyelography and CT scan without oral and IV contrast confirm the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section7'>Cholecystitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Pain and tenderness are usually in the right upper quadrant. In one third of patients the gallbladder can be palpable. [41]",
"<br><strong>Test:</strong> Abdominal ultrasound shows thick wall with peri-cholecystitis collection, and tenderness is present over gallbladder area (Murphy's sign).Hepatobiliary iminodiacetic acid scan will show non-visualisation of gallbladder at &gt;4 hours.</p>",
"</dd>",
"<dt><a href='#Section8'>Urinary tract infection</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Pain and tenderness is usually in suprapubic area associated with burning micturition.Acute right-sided pyelonephritis may present with fever, chills, and tenderness at the right costovertebral angle.",
"<br><strong>Test:</strong> Urine microscopy and culture confirm presence of bacteria.</p>",
"</dd>",
"<dt><a href='#Section9'>Primary peritonitis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Most patients present with abrupt abdominal pain, fever, distension, and rebound tenderness.History of advanced cirrhosis or nephrosis.",
"<br><strong>Test:</strong> CT scan may show fluid in the abdomen.Peritoneal fluid shows &gt;500/microlitre count and &gt;25% polymorphonuclear leukocytosis.</p>",
"</dd>",
"<dt><a href='#Section10'>Pelvic inflammatory disease</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Occurs in females usually aged between 20 and 40 years.Presents with bilateral lower quadrant tenderness, usually within 5 days of the last menstrual period.Purulent discharge from cervical os.",
"<br><strong>Test:</strong> Endocervical swab may confirm the pelvic inflammatory disease due to Chlamydia trachomatis. [42]</p>",
"</dd>",
"<dt><a href='#Section11'>Ruptured Graafian follicle (mittelschmerz)</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Mid-menstrual cycle, brief period of lower abdominal pain not usually associated with nausea and vomiting and fever.Tenderness is usually diffused not localised.",
"<br><strong>Test:</strong> Clinical diagnosis. No investigation indicated.</p>",
"</dd>",
"<dt><a href='#Section12'>Ectopic pregnancy</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Female within childbearing age presents with missed menstrual period, right lower quadrant pain, or pelvic pain with some degree of vaginal bleeding or spotting. Cervical motion tenderness may be present on pelvic examination.",
"<br><strong>Test:</strong> HCG hormone level is high in serum and in urine.Ultrasound reveals presence of mass in fallopian tubes.</p>",
"</dd>",
"<dt><a href='#Section13'>Ovarian torsion</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Female with right lower quadrant pain. Occasionally presents with mass in the right lower quadrant.",
"<br><strong>Test:</strong> Ultrasonography shows ovarian cyst and decreased blood flow.</p>",
"</dd>",
"</dl>"].join("\n");