content=["<dl>",
"<dt><a href='#Section0'>Non-traumatic neck pain</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No history of trauma.May have symptoms of secondary infection (pain with fever, tachycardia), neoplasia (unrelenting pain, especially at night), or inflammation (e.g., arthritides) or have no identifiable aetiology.Infective aetiologies include meningitis, vertebral osteomyelitis, and epidural abscess.Neoplastic lesions can be primary or metastatic, and any patient with a prior history of cancer should be evaluated for recurrence before cancer can be ruled out as a cause of the neck pain.Patients with osteoarthritis and rheumatoid arthritis may have signs and symptoms of arthritis in other joints.",
"<br><strong>Test:</strong> C-spine x-ray: cancer - single or multiple lesions with bony destruction; osteoarthritis - cervical spondylosis or normal.C-spine MRI: cancer - single or multiple lesions with bony destruction; infection - infected areas of bone (vertebral osteomyelitis) or signs of abscess (epidural abscess).CT scan: signs of meningitis.Bone scan: metastatic neoplastic lesions in the spine.Erythrocyte sedimentation rate, c-reactive protein: elevated in infection, malignancy, or inflammatory arthritis.Full blood count: elevated white blood cell count in infection.Herpes zoster immunohistochemistry: positive in varicella virus.</p>",
"</dd>",
"<dt><a href='#Section1'>Degenerative cervical spine disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No history of trauma.Symptoms may be similar to those associated with neck trauma and include axial neck pain and neurological complications such as radiculopathy and myelopathy.",
"<br><strong>Test:</strong> C-spine x-ray: presence of degenerative joint disease or degenerative disc disease.Cervical MRI: bone destruction, spinal cord or nerve compression, intradural or epidural process.</p>",
"</dd>",
"<dt><a href='#Section2'>Acquired torticollis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> No history of trauma.Involuntary twisting or deviation of the neck, abnormal head posture, presence of sensory trick (patient can resolve symptoms by touching neck or face), normal neurological examination.",
"<br><strong>Test:</strong> C-spine x-ray: usually normal.MRI brain and C-spine: usually normal. If chronic, may have cervical muscle asymmetry and nerve root compression.</p>",
"</dd>",
"</dl>"].join("\n");