content=["<dl>",
"<dt><a href='#Section0'>Primary adrenal insufficiency</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Features associated with elevations of ACTH, such as mucosal or cutaneous hyperpigmentation, may be present.Stigmata of autoimmune disorders (e.g., vitiligo) associated with autoimmune adrenal insufficiency may be present.Cushingoid features such as moon facies, dorsocervical fat pad, centripetal obesity, or striae are absent.No history of exogenous corticosteroid use.May be a history of tuberculosis or anticoagulant use.",
"<br><strong>Test:</strong> Hyperkalaemia may be present.Serum ACTH is high.Urine screen for exogenous corticosteroids is negative.Computed tomography of adrenals may show infiltrative or haemorrhagic disease.</p>",
"</dd>",
"<dt><a href='#Section1'>Pituitary compression, tumour, head trauma, and surgery (non-Cushing's)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Headaches and visual loss may occur.Cushingoid features such as moon facies, dorsocervical fat pad, centripetal obesity, or striae will be absent.Patient may have a history of head trauma or surgery affecting the pituitary.",
"<br><strong>Test:</strong> Computed tomography or magnetic resonance imaging may show compression.Urine screen for exogenous corticosteroids is negative.</p>",
"</dd>",
"<dt><a href='#Section2'>Corticosteroid withdrawal syndrome</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Poorly understood. Characterised by a variety of vague symptoms such as fatigue, abdominal pain, and myalgias, which are very similar to those of adrenal insufficiency.However, when adrenal function is evaluated, these patients demonstrate normal adrenal function and reserve. They are therefore not in danger of adrenal crisis if corticosteroids are discontinued, but many are reluctant to taper treatment. Appropriate action requires a great deal of discussion between patient and physician. There are no well-controlled studies of corticosteroid withdrawal syndrome.",
"<br><strong>Test:</strong> ACTH or other stimulation tests show normal adrenal reserve.If testing shows no evidence of adrenal insufficiency, symptoms are likely due to corticosteroid withdrawal syndrome.</p>",
"</dd>",
"</dl>"].join("\n");