content=["<dl>",
"<dt><a href='#Section0'>Sympathomimetic intoxication</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Several drug intoxications can produce a sympathomimetic response which may include hypertension, tachycardia, elevated body temperature and sweating.",
"<br><strong>Test:</strong> Qualitative drug screen.</p>",
"</dd>",
"<dt><a href='#Section1'>Hepatic encephalopathy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients present with sleep disturbances and/or neurological symptoms like bradykinesia, asterixis, or focal neurological symptoms.",
"<br><strong>Test:</strong> Abnormal LFT, abnormal chemistry panel (from use of medications in chronic liver disease resulting in low sodium or low potassium) or increase in ammonia levels.</p>",
"</dd>",
"<dt><a href='#Section2'>Encephalitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually present with abnormalities of the brain parenchyma, which may include but not limited to hemiparesis, sensory, or other motor deficits, and altered mental status.",
"<br><strong>Test:</strong> Lumbar puncture, blood cultures, and FBC to assess leukocytosis or leukopenia; electrolyte panel for abnormal electrolytes like hyponatraemia. PCR and serology testing can be done based on suspected pathogens.</p>",
"</dd>",
"<dt><a href='#Section3'>Meningitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Fever, nuchal rigidity, and change in mental status are common features although not all patients present with this triad. Other features include but not limited to photophobia, skin rash, or cranial nerve palsies.",
"<br><strong>Test:</strong> Lumbar puncture, blood cultures, and FBC to assess leukocytosis or leukopenia; electrolyte panel for abnormal electrolytes like hyponatraemia.</p>",
"</dd>",
"<dt><a href='#Section4'>Hypoglycaemia</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms include but are not limited to tremor, anxiety, palpitations, and neuroglycopenic symptoms, such as drowsiness, fatigue, headache, and loss of consciousness.",
"<br><strong>Test:</strong> Symptoms commonly occur when blood glucose levels fall below 55 mg/dL and cognitive dysfunction can be seen in normal subjects at levels below 50 mg/dL. [16]  [17]</p>",
"</dd>",
"<dt><a href='#Section5'>Wernicke's encephalopathy</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Likely clinical features are mental confusion, gait ataxia, and ophthalmoplegia.",
"<br><strong>Test:</strong> There are no tests that are available in the emergency setting. Routine workup for acute delirium should be done to rule out other causes.CT or MRI may help to exclude other causes and show lesions in midbrain and periventricular region. Diagnostic imaging should not be used to decide treatment for Wernicke's encephalopathy in an emergency setting. [18]  [19]</p>",
"</dd>",
"<dt><a href='#Section6'>Schizophrenia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Onset is usually insidious and is preceded by social withdrawal, lack of interest, poor hygiene, and bizarre thinking. Onset is usually in early adulthood. [20]",
"<br><strong>Test:</strong> Laboratory tests are not specific to diagnosis of schizophrenia and the accepted criteria for diagnosis come from Diagnostic and statistical manual for mental disorders, fourth edition test revision (DSM-IV-TR).</p>",
"</dd>",
"<dt><a href='#Section7'>Benzodiazepine withdrawal</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms are more subtle and depend on the half-life of the medication. The onset may vary from 2 days to a week. Symptoms include panic attacks, tremors, hallucinations, delusions, seizures, and hypothermia. [21]",
"<br><strong>Test:</strong> This is a clinical diagnosis and no laboratory test is used to identify this syndrome.</p>",
"</dd>",
"<dt><a href='#Section8'>Opioid withdrawal</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms vary from mild drug craving to abdominal cramps, tachycardia, tachypnoea, and elevated blood pressure. [21]",
"<br><strong>Test:</strong> This is a clinical diagnosis and no laboratory test is used to identify this syndrome.</p>",
"</dd>",
"<dt><a href='#Section9'>Anticholinergic poisoning</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> History of anticholinergic ingestion or no prior history of alcohol abuse. Symptoms include elevated heart rate, dry skin, increased temperature, agitation, and delirium. [21]",
"<br><strong>Test:</strong> Toxicological screening is not very helpful in anticholinergic poisoning.</p>",
"</dd>",
"<dt><a href='#Section10'>Thyrotoxicosis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Is more common in women in early adulthood and is characterised by heat intolerance, muscle weakness, proptosis, and lid lag that helps to distinguish from other diseases. Nervousness, gastrointestinal hypermotility, hair loss, and cardiovascular manifestations are common. [22]",
"<br><strong>Test:</strong> Low levels of thyroid-stimulating hormone (TSH) and elevated T3 and T4 in Graves' disease and elevated T3 in T3 toxicosis. A radioactive iodine scan is helpful in identifying the pattern of uptake in the thyroid gland.</p>",
"</dd>",
"<dt><a href='#Section11'>Head injury</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Patient or witness report of injury; may be loss of consciousness, amnesia, and obvious signs of trauma; may also be evidence of alcohol intoxication, so high level of suspicion of trauma recommended in these patients. [23]",
"<br><strong>Test:</strong> Urine toxicology screen will indicate if the subject has been drinking; however, it may not exclude a diagnosis of head injury. CT scan can be diagnostic.</p>",
"</dd>",
"<dt><a href='#Section12'>Somatisation disorders</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Somatic symptoms in a patient with no medical findings (e.g., pseudoseizures which may mimic alcohol withdrawal seizures).Usually associated with anxiety or affective disorders. [24]  [25]",
"<br><strong>Test:</strong> There are no diagnostic tests for distinguishing these conditions. The distinction is best made in consultation with a psychiatrist.</p>",
"</dd>",
"</dl>"].join("\n");