content=["<dl>",
"<dt><a href='#Section0'>Refractive error with no amblyopia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Many refractive errors, most often myopia and astigmatism, cause unilateral or bilateral decreased vision but do not cause amblyopia. If a child's visual acuity immediately normalises with the appropriate refractive correction, the cause of decreased vision is refractive error alone, and not refractive amblyopia.Children with refractive error may squint to create a pinhole effect and improve vision, and myopic children will see better at near than at distance.In amblyopia, vision does not improve with squinting, nor does it improve at a particular testing distance.",
"<br><strong>Test:</strong> Complete examination by an ophthalmologist (or optometrist).</p>",
"</dd>",
"<dt><a href='#Section1'>Functional visual impairment</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with bilateral decreased visual acuity at a time when a child experiences stress, such as the birth of a new sibling, divorce, or loss of a loved one.A child with functional visual impairment will not show amblyogenic risk factors such as strabismus, significant refractive error, or media opacities, and the child should have an otherwise normal ophthalmological exam.",
"<br><strong>Test:</strong> Complete examination by an ophthalmologist (or optometrist).</p>",
"</dd>",
"<dt><a href='#Section2'>CNS pathology affecting visual pathways</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Abnormal colour vision and visual field defects.",
"<br><strong>Test:</strong> Complete examination by an ophthalmologist (or optometrist), brain and orbital MRI with gadolinium enhancement.</p>",
"</dd>",
"</dl>"].join("\n");