content=["<dl>",
"<dt><a href='#Section0'>Cocaine overdose</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Toxicity from amfetamines cannot be readily distinguished clinically from cocaine toxicity, but the management in both cases is essentially the same. The prevalence of ischaemic chest pain and CVA in cocaine intoxication is higher.",
"<br><strong>Test:</strong> Urine drug screen will differentiate cocaine from amfetamines.</p>",
"</dd>",
"<dt><a href='#Section1'>Serotonin syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Hx of drug use, prescription or illicit, with proclivity to serotonin interaction (e.g., serotonin-reuptake inhibitors, metoclopramide, sumatriptan, lithium, and dextromethorphan). Anxiety, agitation, delirium, restlessness, and disorientation; bilateral Babinski's signs; neuromuscular findings are typically more pronounced in the lower extremities.",
"<br><strong>Test:</strong> Non-specific laboratory findings, including an elevated WBC count, elevated creatine kinase, and decreased serum bicarbonate concentration. Level for suspected agent causing interaction (if available) may be diagnostic.</p>",
"</dd>",
"<dt><a href='#Section2'>Withdrawal of gamma-hydroxybutyrate or its analogues</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Gamma-hydroxybutyrate (GHB) is an illicit chemical that has become a major cause of drug-related comas in the US and other countries. GHB withdrawal tends to cause mild autonomic dysfunction with severe CNS symptoms. [44]",
"<br><strong>Test:</strong> GHB and its analogues are not detected on standard drug screens and are rapidly cleared from the urine (75-100 mg/kg may be undetectable in the urine by 12 hours after administration). [44]  [45]  May require process of elimination of known illicit drug usage.</p>",
"</dd>",
"<dt><a href='#Section3'>Psychosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May be drug-induced or exacerbation of pre-existing condition and difficult to discern exactly, but differentiating these is not a contra-indication to urgent sedation and symptomatic therapy.",
"<br><strong>Test:</strong> A period of sedation and behavioural control followed by a more extensive history will allow reassessment after the acute drug effects have worn off.</p>",
"</dd>",
"<dt><a href='#Section4'>Alcoholism</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Commonplace, chronic in nature, malnutrition, hepatomegaly, jaundice, and ascites.",
"<br><strong>Test:</strong> Carbohydrate-deficient transferrin confirms diagnosis but is not widely available. Serum alcohol &gt;22,440 micromol/L (200 mg/dL) with limited impairment can indicate tolerance to the effects of alcohol but does not diagnose dependence.</p>",
"</dd>",
"<dt><a href='#Section5'>Hypoglycaemia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Hx of diabetes and insulin therapy, or oral hypoglycaemic agents.",
"<br><strong>Test:</strong> Documentation of blood glucose &lt;3.3 mmol/L (60 mg/dL) with accompanying symptoms is crucial to diagnosing clinically significant hypoglycaemia.</p>",
"</dd>",
"<dt><a href='#Section6'>Sedative or hypnotic withdrawal</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Hx of prolonged use or high doses, discontinued in the previous 1 to 6 days. Hyperthermia not a prominent feature. Older people more at risk. Usually a longer period of onset.",
"<br><strong>Test:</strong> Toxicology screening may identify the agent.</p>",
"</dd>",
"<dt><a href='#Section7'>Antimuscarinic syndrome</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Rather than the diaphoresis of amfetamine toxicity, a patient with antimuscarinic syndrome has dry mucosal membranes and hot, red, and dry skin. Older men are likely to have urinary retention. Voluntary admission of ingestion of anticholinergic agents, antihistamines, antispasmodic agents, some antidepressants (especially tricyclic antidepressants), ophthalmic cycloplegics, or some plant derivatives including belladonna and Datura species.",
"<br><strong>Test:</strong> Toxicology screening may identify the agent.</p>",
"</dd>",
"<dt><a href='#Section8'>Alcohol withdrawal</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Hx of chronically high alcohol intake followed by abrupt withdrawal may be elicited. Hypertension, tachycardia, and agitation become more severe within hours to several days.",
"<br><strong>Test:</strong> Toxicology screening may identify the agent. Other indicators are high gamma-GT on liver function tests and macrocytosis on FBC.</p>",
"</dd>",
"<dt><a href='#Section9'>Heat stroke</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Hx of exposure to extreme heat, especially with physical exertion; hot, flushed, and dry skin; variable amounts of sweating may occur, but usually less than expected with amfetamine toxicity. Prostration, exhaustion much more common than agitation and rage.",
"<br><strong>Test:</strong> Concentrated urine, haemoconcentration with decreased coagulation, and thrombocytopenia. Elevated WBC count and core body temperature, usually negative drug and alcohol screens.</p>",
"</dd>",
"<dt><a href='#Section10'>Subarachnoid haemorrhage</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Sudden severe headache, often described as worst headache of life, with nausea, vomiting, and photophobia, meningismus, intra-ocular haemorrhages, or focal findings.",
"<br><strong>Test:</strong> Subarachnoid haemorrhage identifiable on CT or MRI. LP with blood may indicate cerebral bleeding or traumatic spinal tap. Cerebral angiography confirms the presence of aneurysms.</p>",
"</dd>",
"<dt><a href='#Section11'>Phaeochromocytoma</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Hx of similar attacks with headache in the absence of drug abuse.",
"<br><strong>Test:</strong> Urinary catecholamines are elevated, or elevated metanephrines, with normal serum T4.</p>",
"</dd>",
"<dt><a href='#Section12'>Thyrotoxic crisis</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Hx of thyrotoxicosis in the past, may be precipitated by amfetamine or other sympathomimetic ingestion.",
"<br><strong>Test:</strong> Elevated levels of T3, T4 and free T4, hyperglycaemia, leukocytosis, and anaemia.</p>",
"</dd>",
"<dt><a href='#Section13'>Encephalitis</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Fever, headache, lethargy, and altered mental status; immunocompromised state, motor and sensory deficits, or focal neurological findings; seizures.",
"<br><strong>Test:</strong> CT head (non-contrast) normal or subtly abnormal, hypodense lesions, and mild mass effect prominent later; CSF for cell count and for Gram stain, bacterial culture diagnostic with identification of organism.</p>",
"</dd>",
"<dt><a href='#Section14'>Meningitis</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Headache, lethargy, and altered mental status; immunocompromised state, fever, meningismus, and lethargy, seizures.",
"<br><strong>Test:</strong> CT head (non-contrast) normal; CSF for Gram stain, bacterial culture diagnostic with identification and recovery of organism.</p>",
"</dd>",
"</dl>"].join("\n");