content=["<dl>",
"<dt><a href='#Section0'>Cocaine abuse</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Signs and symptoms are similar but shorter in duration.Half-life of cocaine is about 1 hour, but that of methamfetamine is 12 hours.",
"<br><strong>Test:</strong> Confirmation with gas chromatography and mass spectroscopy (GC/MS) analysis. Considered the most specific and sensitive test. Will determine the exact compounds and presence of metabolites.A number of compounds (trazodone, ranitidine, ritodrine, chlorpromazine, and promethazine) can give false-positive results for methamfetamine with screening assays such as enzyme-multiplied immunoassay. Mebeverine, doxepin, and its metabolite n-desmethyldoxepin can cause false-positive results if a fluorescence polarisation assay is used. GC/MS does not have this problem.Some drugs are metabolised to amfetamines. Selegiline is metabolised to L-amfetamine and L-methamfetamine and causes a false-positive GC/MS result. Quantitative isomer analysis can distinguish the L from R isomer. Clobenzorex, an anorectic medication from Mexico, is metabolised to D-amfetamine, giving positive screening, GC/MS confirmation, and qualitative isomer analysis.</p>",
"</dd>",
"<dt><a href='#Section1'>Malignant HTN</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Usually a history of HTN and a lack of CNS stimulation, which is common in amfetamine toxicity.",
"<br><strong>Test:</strong> A negative urine toxicology test differentiates a hypertensive crisis from a drug-abuse symptom.</p>",
"</dd>",
"<dt><a href='#Section2'>Anticholinergic drug exposure</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> History of ingestion with absent or decreased bowel sounds and dry mucous membranes, not present with amfetamine use.",
"<br><strong>Test:</strong> A negative urine toxicology screen with a positive screen for anticholinergics provides differentiation.A positive response to the cholinesterase inhibitor physostigmine test suggests anticholinergic drug use.</p>",
"</dd>",
"<dt><a href='#Section3'>Neuroleptic malignant syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May be a history of neuroleptic exposure.May respond to bromocriptine.",
"<br><strong>Test:</strong> Urine toxicology screen is negative for amfetamines, unless there is concomitant amfetamine use.</p>",
"</dd>",
"<dt><a href='#Section4'>Malignant hyperthermia</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of recent general anaesthesia or receipt of muscle blockers.May be FHx of similar episodes.Responds to dantrolene sodium.",
"<br><strong>Test:</strong> Urine toxicology screen is negative for amfetamines, unless there is concomitant amfetamine use.</p>",
"</dd>",
"<dt><a href='#Section5'>Phaeochromocytoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Paroxysmal symptoms without a history of drug abuse.",
"<br><strong>Test:</strong> Characterised by recurrent hypertensive episodes with negative urine toxicology screens.Suggested by marked elevation of unconjugated catecholamines, metanephrines, and vanillylmandelic acid in the 24-hour urine collection test.</p>",
"</dd>",
"<dt><a href='#Section6'>Schizophrenia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> History of psychiatric illness and previous neuroleptic treatment without drug abuse.",
"<br><strong>Test:</strong> Urine toxicology screen is negative for amfetamines, unless there is concomitant amfetamine use.</p>",
"</dd>",
"<dt><a href='#Section7'>Depression</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> History of previous episodes of depression often with previous antidepressant therapy.",
"<br><strong>Test:</strong> Urine toxicology screen for amfetamines is negative, unless there is concomitant amfetamine use.</p>",
"</dd>",
"<dt><a href='#Section8'>Paranoid schizophrenia</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> History of previous psychiatric illness without drug abuse.",
"<br><strong>Test:</strong> Urine toxicology for amfetamines is negative, unless there is concomitant amfetamine use.</p>",
"</dd>",
"</dl>"].join("\n");