content=["<dl>",
"<dt><a href='#Section0'>Hypertrophic cardiomyopathy (HCM)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Clinically difficult to distinguish HCM from amyloidosis.",
"<br><strong>Test:</strong> Echo meets diagnostic criteria for HCM, such as asymmetric septal hypertrophy.Doppler echo with strain to exclude features of amyloidosis does not show the typical restrictive filling changes seen in amyloidosis.MRI can help distinguish between the 2 syndromes.</p>",
"</dd>",
"<dt><a href='#Section1'>Membranous glomerulopathy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Clinically similar presentation in patients who present with nephrotic syndrome.",
"<br><strong>Test:</strong> Renal biopsy does not stain with Congo red.</p>",
"</dd>",
"<dt><a href='#Section2'>Monoclonal gammopathy of undetermined significance (MGUS)-associated neuropathy</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients do not have significant degrees of proteinuria, hepatomegaly, or cardiomyopathy.",
"<br><strong>Test:</strong> Sural nerve biopsy does not stain with Congo red.</p>",
"</dd>",
"<dt><a href='#Section3'>Multiple myeloma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Bone pain and symptoms of anaemia and renal failure.",
"<br><strong>Test:</strong> Plain x-rays show lytic bone lesions, compression fractures, diffuse osteoporosis.Low Hb.Renal impairment.</p>",
"</dd>",
"</dl>"].join("\n");