content=["<dl>",
"<dt><a href='#Section0'>Ovarian cancer</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Anorexia and weight loss.Lack of muscle bulking.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Pelvic ultrasound shows presence of solid, complex, septated, multiloculated mass and high blood flow.CT scan shows peritoneal thickening, enlarged lymph nodes, ascites, omental thickening, or liver metastases.</p>",
"</dd>",
"<dt><a href='#Section1'>Adrenal neoplasm</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.MRI of abdomen/pelvis typically appears hyper-intense to the liver on T2-weighted images because of their high water content.Appear on CT scan as inhomogeneous masses, often with a central area of low attenuation that represents haemorrhage or necrosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Congenital adrenal hyperplasia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents in infancy.No hx of taking anabolic steroids in patients with late-onset disease.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Elevated serum 17-hydroxyprogesterone demonstrates deficiency of 21-hydroxylase.</p>",
"</dd>",
"<dt><a href='#Section3'>Polycystic ovarian syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Hyper-androgenism.Body is obese and pear shaped.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Pelvic ultrasound shows polycystic ovaries.Glucose tolerance test shows insulin resistance.</p>",
"</dd>",
"<dt><a href='#Section4'>Precocious puberty</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Lack of masculinisation effects (ovarian and central precocious puberty).Lack of feminisation effects (testicular and central precocious puberty).",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Gonadotrophin-dependent precocious puberty tends to have both elevated LH and elevated FSH, both of which increase after taking exogenous GnRH.Gonadotrophin-independent precocious puberty patients have low levels of FSH and LH, and these hormones do not rise after GnRH dosing.</p>",
"</dd>",
"<dt><a href='#Section5'>Anorexia nervosa</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May co-exist with steroid abuse.No hx of taking anabolic steroids.Patients often believe they are overweight.Lack of muscle bulking.Low daily calorie count.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.</p>",
"</dd>",
"<dt><a href='#Section6'>Cushing's syndrome</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Hx of intake of glucocorticoids.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Elevated serum cortisol level.High 24-hour urine cortisol excretion.Positive dexamethasone suppression test (persistently high cortisol after giving dexamethasone).</p>",
"</dd>",
"<dt><a href='#Section7'>Drug-induced hirsutism</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Hx of taking drugs known to cause hirsutism including minoxidil, phenytoin, danazol, or diazoxide.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Gas chromatography/mass spectrometry detection of exogenous drugs may confirm diagnosis.</p>",
"</dd>",
"<dt><a href='#Section8'>Drug-induced jaundice</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Hx of taking drugs known to cause jaundice including oral contraceptives, ethanol, or isoniazid.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Gas chromatography/mass spectrometry detection of exogenous drugs may confirm diagnosis.</p>",
"</dd>",
"<dt><a href='#Section9'>Haemolytic anaemia</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Symptoms develop rapidly.Tachycardia and pallor.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Decreased haemoglobin level and haematocrit with high reticulocyte count.Increased serum bilirubin concentration.</p>",
"</dd>",
"<dt><a href='#Section10'>Hepatitis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Hx of sharing needles, intercourse with infected partner, or travel exposure (viral hepatitis).Hx of taking drugs/toxins known to cause hepatitis including paracetamol, valproate, troglitazone, mushrooms, pennyroyal, or carbon tetrachloride (drug-induced hepatitis).",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Elevated indirect bilirubin.Positive hepatitis serology.Toxicology testing may detect drugs or other substances that induce hepatitis (drug-induced hepatitis).</p>",
"</dd>",
"<dt><a href='#Section11'>Cirrhosis</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Hx of chronic alcohol ingestion.Liver feels firm and nodular on examination.Ascites.Splenomegaly.Clubbing.Spider angiomata.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Liver biopsy demonstrates architectural distortion of the liver parenchyma with formation of regenerative nodules.Prolonged prothrombin time and decreased platelet count.</p>",
"</dd>",
"<dt><a href='#Section12'>Hepatic malignancy</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.Anorexia and weight loss.Lack of muscle bulking.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Liver biopsy demonstrates malignancy.</p>",
"</dd>",
"<dt><a href='#Section13'>Cholelithiasis</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> No hx of taking anabolic steroids.",
"<br><strong>Test:</strong> Negative urine test for anabolic steroids.Gallstones occasionally seen on plain x-ray or CT, and reliably identified with ultrasound.</p>",
"</dd>",
"<dt><a href='#Section14'>Abuse of other ergogenic compounds</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Hx of taking alternative ergogenic compound; patients may also currently use, or have previously used, anabolic steroids. [38]Other ergogenic compounds include oestrogen-receptor blockers (e.g., tamoxifen, clomifene, raloxifene, toremifene, droloxifene), aromatase inhibitors (e.g., aminoglutethimide, testolactone, atamestane, exemestane, anastrozole, letrozole, vorozole), oestrogen precursors (e.g., dehydroepiandrosterone [DHEA], androstenedione), and the gonadotrophins (e.g., LH, hCG). [38]",
"<br><strong>Test:</strong> Specific mass spectrometry testing is required to identify these compounds. [38]</p>",
"</dd>",
"</dl>"].join("\n");