content=["<dl>",
"<dt><a href='#Section0'>Septic shock</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Absence of previous allergic reactions, lack of allergen exposure, slower onset, fever, and other signs of localised infection often differentiate septic shock from anaphylaxis.",
"<br><strong>Test:</strong> Increased WBC count and increased temperature.CXR with a pulmonary infiltrate is suggestive of underlying pneumonia as source of infection.</p>",
"</dd>",
"<dt><a href='#Section1'>Cardiogenic shock</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Age, risk factors for CAD, previous angina episodes, absence of an allergic history, no indication of allergen exposure, typical cardiac signs and symptoms (such as chest pain on exercise) help to distinguish. Severe anaphylactic reactions can trigger cardiac events.",
"<br><strong>Test:</strong> Elevated cardiac enzymes (CK and troponin). ECG may show signs of myocardial ischaemia (elevated ST segments or flipped T waves). CXR may show signs of CHF (e.g., pulmonary oedema, changes in the cardiac silhouette).</p>",
"</dd>",
"<dt><a href='#Section2'>Hypovolaemic shock</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Water or fluid loss occurs via heat exposure, profuse sweating, significant blood loss, vomiting, and diarrhoea. Patients report thirst and a drop in urinary output. Anaphylaxis is a form of hypovolaemic shock secondary to intravascular fluid shifts. Establishing an alternative cause of hypovolaemia will differentiate from anaphylaxis.",
"<br><strong>Test:</strong> A drop in haematocrit suggests blood loss.A serum urea/creatinine ratio &gt;20 suggests volume depletion.</p>",
"</dd>",
"<dt><a href='#Section3'>Vasovagal reaction</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> The characteristic feature is hypotension, with pallor, weakness, nausea, vomiting, and diaphoresis. The sudden onset, the cardiovascular collapse, and unconsciousness are all also typical of anaphylaxis.May be differentiated by the lack of cutaneous manifestations, the absent allergic history, and the presence of bradycardia instead of the tachycardia, even though either can be absent or misleading.",
"<br><strong>Test:</strong> There is no differentiating test.</p>",
"</dd>",
"<dt><a href='#Section4'>Asthma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Absence of allergen exposure, or of cutaneous or digestive findings, and a hx of previous asthma episodes help to differentiate. A rapid onset is suggestive of anaphylaxis and should at least trigger referral to higher-level medical care.",
"<br><strong>Test:</strong> There is no differentiating test.</p>",
"</dd>",
"<dt><a href='#Section5'>Acute COPD exacerbation</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Absence of allergen exposure, or of cutaneous or digestive findings, and a hx of established chronic lung disease help to differentiate.",
"<br><strong>Test:</strong> There is no differentiating test.</p>",
"</dd>",
"<dt><a href='#Section6'>Hereditary angio-oedema</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Characterised by recurrent episodes of slowly progressing angio-oedema of the skin, mucosa, and submucosal tissue. There is no urticaria, hypotension, or history of allergen exposure as in anaphylaxis. FHx is positive.",
"<br><strong>Test:</strong> Deficiency or underactivity of the C1 esterase inhibitor enzyme.Serum complement C4 and CH50 are low.</p>",
"</dd>",
"<dt><a href='#Section7'>Vocal cord dysfunction syndrome</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Cutaneous signs, digestive findings, hypotension, and allergen exposure are not present.",
"<br><strong>Test:</strong> Pharyngeal endoscopy by an ENT consultant will not show laryngeal oedema but instead vocal cord adduction.</p>",
"</dd>",
"<dt><a href='#Section8'>Foreign body aspiration</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> No allergen exposure, no cutaneous or digestive findings, but a hx of foreign body aspiration differentiate this diagnosis.",
"<br><strong>Test:</strong> Imaging and bronchoscopy are used to locate and document the foreign body. If the object inhaled is radio-opaque (e.g., a small coin), a plain radiograph of the chest may show its location.</p>",
"</dd>",
"<dt><a href='#Section9'>Monosodium glutamate (MSG) ingestion</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> In reaction to MSG exposure, the following MSG symptom complex may occur. One or more of the following are present: burning sensation in the back of the neck, forearms, and chest; numbness in the back of the neck, radiating to the arms and back; tingling, warmth, and weakness in the face, temples, upper back, neck, and arms; facial pressure or tightness; chest pain; headache; nausea; rapid heartbeat; bronchospasm; drowsiness; and weakness. No urticaria, angio-oedema, or hypotension occurs.",
"<br><strong>Test:</strong> Serum histamine levels and mast cell tryptase are not elevated.</p>",
"</dd>",
"<dt><a href='#Section10'>Carcinoid syndrome</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> On examination, there is an associated right heart murmur.",
"<br><strong>Test:</strong> Urinalysis will show high levels of hydroxy indole acetic acid.</p>",
"</dd>",
"<dt><a href='#Section11'>Postmenopausal hot flushes</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Flush appears several times a day and lasts for 4 to 5 minutes. There are no respiratory tract symptoms and no hypotension.",
"<br><strong>Test:</strong> There is no differentiating test.</p>",
"</dd>",
"<dt><a href='#Section12'>Red man syndrome</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> This syndrome usually appears within 4 to 10 minutes after start or soon after the completion of a vancomycin infusion. It is characterised by flushing and/or an erythematous rash that affects the face, neck, and upper torso. Hypotension and angio-oedema may also occur, but less frequently.",
"<br><strong>Test:</strong> There is no differentiating test.</p>",
"</dd>",
"<dt><a href='#Section13'>Panic disorder</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> In some, functional stridor develops as a result of forced adduction of the vocal cords; however, there is no urticaria, angio-oedema, or hypotension.",
"<br><strong>Test:</strong> There is no differentiating test.</p>",
"</dd>",
"<dt><a href='#Section14'>Scombrotoxic food poisoning</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms resemble IgE-mediated food allergy, but most prominent on upper torso and face. Erythematous rash, but no urticaria noted. Resolves untreated within 12 hours.",
"<br><strong>Test:</strong> Skin test to suspected seafood is negative. Histamine level in consumed fish elevated.</p>",
"</dd>",
"</dl>"].join("\n");     