content=["<dl>",
"<dt><a href='#Section0'>Diffuse alopecia areata</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> This is a non-scarring, autoimmune, inflammatory hair loss, which is typically characterised by circumscribed and asymmetrical areas of baldness.The scalp is the most common site affected.Diagnosis is suggested by findings of short broken-off (exclamation-point) hairs, pitted nails and a history of periodic regrowth of hair. [19]",
"<br><strong>Test:</strong> Histopathology of a scalp biopsy is characterised by an increased number of catagen and telogen follicles, and the presence of lymphocytic and eosinophilic infiltrates in the peribulbar region.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute telogen effluvium</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> An increased shedding of normal hairs.Alopecia is diffuse.There is a history of physical stressor (high fever, surgery, pregnancy, rapid weight loss, nutritional deficiencies, haemorrhage, or hormonal dysfunction such as thyroid dysfunction) or offending medication use beginning approximately 3 to 5 months prior to onset of shedding.Diffuse hair loss on the scalp with sometimes short regrowing frontal hair, although overall hair density appears normal to minimally decreased.",
"<br><strong>Test:</strong> Hair pull test is usually positive. View imageScalp biopsy does not show miniaturised hair follicles and may appear almost normal except for a variable increase in the proportion of telogen follicles.</p>",
"</dd>",
"<dt><a href='#Section2'>Chronic telogen effluvium</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> This is an idiopathic, abrupt onset of generalised diffuse shedding of telogen hairs from the scalp that may persist up to several years.Occurs more commonly in women.May be distinguished from acute telogen effluvium by its long fluctuating course.Frontoparietal hair loss or widening of the central part is not present, but the disease may be accompanied by bitemporal recession.Women typically present without visible reduction in scalp hair density.The hair loss appears to be self-limiting and does not cause baldness.",
"<br><strong>Test:</strong> Hair pull test is positive only in the active early hair loss phases, but negative in longstanding hair loss. Histopathological evaluation of a scalp biopsy shows a normal-appearing scalp skin.</p>",
"</dd>",
"<dt><a href='#Section3'>Anagen effluvium</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Anagen hair loss is associated with any damage to the hair follicle that impairs its mitotic activity. Usually occurs after exposure to antineoplastic chemotherapeutic agents that cause immediate interference with hair-shaft formation and shedding of already formed anagen hairs. [19]",
"<br><strong>Test:</strong> Hair pull test will be positive.Predominantly anagen hairs present on microscopic examination of biopsy specimen.</p>",
"</dd>",
"<dt><a href='#Section4'>Polycystic ovary syndrome (PCOS)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients may present with weight gain, irregular menstruation, infertility and/or hirsutism. Associated symptoms or features are acne and androgenetic alopecia.",
"<br><strong>Test:</strong> Standard diagnostic tests are pelvic ultrasound, although not all women have ovarian cysts, and an androgen profile (total and free testosterone, DHEA-sulphate and sex hormone binding globulin).</p>",
"</dd>",
"<dt><a href='#Section5'>Cushing's syndrome</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients may complain of weight gain presenting as moon face, truncal obesity and buffalo hump. Associated findings are hirsutism, facial flushing, haematomas and striae distensae.",
"<br><strong>Test:</strong> Standard screening tests show elevated 24-hour urine free cortisol levels, late-night salivary cortisol, or lack of suppression on overnight dexamethasone test. High-and low-dose dexamethasone suppression may further identify ACTH-dependent or -independent Cushing's syndrome.</p>",
"</dd>",
"<dt><a href='#Section6'>Hyperprolactinaemia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Woman may present with oligomenorrhoea or amenorrhoea. Men may present with sexual dysfunction, headache and/or visual field defects. Galactorrhoea may be an associated finding in both men and women.",
"<br><strong>Test:</strong> Screening test shows elevated serum prolactin levels.</p>",
"</dd>",
"<dt><a href='#Section7'>Thyroid dysfunction</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Patients with hypothyroidism may present with cold intolerance, fatigue, weight gain, constipation, goiter and/or depression. Associated findings are dry coarse hair and skin.Patients with hyperthyroidism may present with weight loss, increased appetite, heat intolerance, irritability, fatigue and/or cardiac symptoms such as palpitations.Patients with autoimmune disorder may also present with pretibial myxoedema and/or exophthalmus.",
"<br><strong>Test:</strong> Serum test for TSH shows elevated levels in patients with primary hypothyroidism and low or suppressed levels in patients with primary hyperthyroidism.</p>",
"</dd>",
"<dt><a href='#Section8'>Iron deficiency</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms may include progressive fatigue, pallor, dyspnoea, and pica. Associated findings are hair loss and brittle nails.",
"<br><strong>Test:</strong> Standard screening tests reveal microcytic anaemia, low serum iron and ferritin levels and high iron binding capacity.</p>",
"</dd>",
"</dl>"].join("\n");