content=["<dl>",
"<dt><a href='#Section0'>Lateral ankle ligament tear (anterior talofibular ligament and calcaneofibular ligament)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Minimal lateral malleolar posterior bony tenderness. There may be a positive anterior drawer sign of the ankle or increased talar tilt depending on extent of the tear. Uncommonly there is significant deformity to the ankle.",
"<br><strong>Test:</strong> Plain x-rays will not identify a fracture.MRI examination or musculoskeletal ultrasound may show oedema with or without a tear to the lateral ankle ligaments (anterior talofibular ligament and calcaneofibular ligament).</p>",
"</dd>",
"<dt><a href='#Section1'>Achilles tendon rupture</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No malleolar tenderness. There may be a gap in the Achilles tendon and a positive Thompson's test.",
"<br><strong>Test:</strong> Plain x-rays demonstrate no fracture and an MRI or musculoskeletal ultrasound of the Achilles tendon will demonstrate a tear.</p>",
"</dd>",
"<dt><a href='#Section2'>Talar fracture</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There may be no malleolar tenderness. There may be a deformity to the ankle and hindfoot.",
"<br><strong>Test:</strong> Plain x-rays demonstrate a fracture of the talus.</p>",
"</dd>",
"<dt><a href='#Section3'>Syndesmotic disruption</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There may be no malleolar tenderness. External rotation test and calf squeeze test may demonstrate pain in the syndesmosis. [20]",
"<br><strong>Test:</strong> Plain x-rays demonstrate no fracture but may show tibiofibular widening.</p>",
"</dd>",
"</dl>"].join("\n");