content=["<dl>",
"<dt><a href='#Section0'>Osteoarthritis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Presents with mechanical pain typically becoming worse at the end of the day and after activity, with no morning symptoms.May occur after lifting or bending.The history differentiates mechanical back pain from inflammatory back pain.",
"<br><strong>Test:</strong> Radiographs of the back may demonstrate degenerative disc disease or the presence of osteophytes.</p>",
"</dd>",
"<dt><a href='#Section1'>Diffuse idiopathic skeletal hyperostosis (DISH)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with mechanical symptoms.Age of onset may help differentiate this condition from AS, as onset tends to be in the 50- to 75-year age group.",
"<br><strong>Test:</strong> In DISH there are flowing osteophytes along the anterior margin of the vertebra in the presence of normal vertebral bodies and discs on x-ray. [75]</p>",
"</dd>",
"<dt><a href='#Section2'>Psoriatic arthritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Part of the spondyloarthropathy group.Tends to present in the 35- to 45-year age group. No sex bias.Sacroiliitis may be unilateral.History of psoriasis.Dactylitis more common.",
"<br><strong>Test:</strong> Hand and foot x-rays may reveal erosive disease.</p>",
"</dd>",
"<dt><a href='#Section3'>Reactive arthritis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually recall a specific infection: for example, a non-gonococcal urethritis or gastroenteritis.Dactylitis and skin manifestations occur more frequently than in AS.May present with keratoderma blennorrhagica, conjunctivitis, or urethral discharge.",
"<br><strong>Test:</strong> Pelvic x-rays may demonstrate unilateral sacroiliitis.</p>",
"</dd>",
"<dt><a href='#Section4'>Inflammatory bowel-related arthritis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Hx Crohn's disease or ulcerative colitis.No sex bias.Peripheral joint involvement common.May have evidence of erythema nodosum or pyoderma gangrenosum.",
"<br><strong>Test:</strong> Only 30% HLA-B27-positive.May have unilateral sacroiliitis.</p>",
"</dd>",
"<dt><a href='#Section5'>Infection (e.g., discitis)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients are usually systemically ill with fever, anorexia, and rigors accompanying back pain.",
"<br><strong>Test:</strong> Focal spinal abnormalities on x-ray or MRI.Elevated inflammatory markers.</p>",
"</dd>",
"<dt><a href='#Section6'>Vertebral fracture</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> May co-exist with AS.Presents as episodic spinal pain.",
"<br><strong>Test:</strong> Focal spinal abnormalities on x-ray or MRI.</p>",
"</dd>",
"<dt><a href='#Section7'>Bony metastases</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Systemic clues such as weight loss, melaena, alternating bowel habits, prostate symptoms, breast mass.",
"<br><strong>Test:</strong> Radiographs more likely to show vertebral collapse or metastatic deposits.</p>",
"</dd>",
"<dt><a href='#Section8'>Onchronotic arthropathy</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Rare syndromes, which present in the 3rd and 4th decades with lower back and hip stiffness that can mimic AS.",
"<br><strong>Test:</strong> Presence of homogentisic acid in the blood and urine.</p>",
"</dd>",
"</dl>"].join("\n");