content=["<dl>",
"<dt><a href='#Section0'>Acute coronary syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Chest pain is typically pressing.There may be a history of prior exertional chest pain.",
"<br><strong>Test:</strong> ECG and troponin T may indicate myocardial infarction or ischaemia.ST segment depression may occur in acute dissection, but ST elevation rare.</p>",
"</dd>",
"<dt><a href='#Section1'>Pericarditis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Chest pain typically pleuritic.",
"<br><strong>Test:</strong> ECG typically shows diffuse ST elevation.</p>",
"</dd>",
"<dt><a href='#Section2'>Aortic aneurysm</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Stable (non-dissecting and non-leaking) aneurysms are asymptomatic. Diagnosis is usually incidental to workup for another entity.",
"<br><strong>Test:</strong> CT scan of the chest does not show dissection.</p>",
"</dd>",
"<dt><a href='#Section3'>Musculoskeletal pain</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Pain may be reproducible on palpation of the affected area.",
"<br><strong>Test:</strong> CT scan of the chest does not show dissection.</p>",
"</dd>",
"<dt><a href='#Section4'>Pulmonary embolus</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Dyspnoea, hypoxia and pleuritic chest pain.There may be evidence of deep vein thrombosis, for example, calf swelling or tenderness.",
"<br><strong>Test:</strong> CT scan of the chest shows pulmonary embolus.</p>",
"</dd>",
"<dt><a href='#Section5'>Mediastinal tumour</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Possible cough or haemoptysis.",
"<br><strong>Test:</strong> CT scan of the chest shows evidence of tumour.</p>",
"</dd>",
"</dl>"].join("\n");