content=["<dl>",
"<dt><a href='#Section0'>Aortic sclerosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> The murmur of aortic sclerosis is usually less than grade 2 and the aortic closure sound is usually physiologically split. Signs and symptoms of heart failure or chest pain should prompt an echocardiogram but cannot by themselves reliably distinguish the 2 conditions.",
"<br><strong>Test:</strong> Transthoracic Doppler echo will demonstrate no significant pressure gradient (&lt;5 mmHg) across the aortic valve with aortic sclerosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Ischaemic heart disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> AS and CAD frequently co-exist and it is difficult to determine their relative contributions to cardiac complaints when both are present in the same patient.In practice, for patients with severe AS and concomitant CAD, both are treated at the time of surgery.",
"<br><strong>Test:</strong> In ischaemic heart disease, common ECG findings include Q waves in contiguous leads, and the echocardiogram often shows segments of the myocardium with abnormal systolic thickening or wall motion abnormalities.In AS, Q waves are absent in the ECG; regional wall motion abnormalities are absent on the echocardiogram; and coronary arteries are normal upon cardiac catheterisation.</p>",
"</dd>",
"<dt><a href='#Section2'>Hypertrophic cardiomyopathy (HCM)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> HCM is a heterogeneous disease that can produce subvalvular stenosis and a murmur that is identical to AS.Hand gripping and squatting manoeuvres are helpful in distinguishing HCM from AS. These manoeuvres do not greatly affect the intensity of the murmur of AS; however, hand gripping, which increases afterload, will soften the HCM murmur. Standing up after squatting will decrease cardiac return and ventricular preload, which increases the murmur of HCM.",
"<br><strong>Test:</strong> Typical echocardiography findings include asymmetric hypertrophy with the septal wall most prominently affected. Dynamic obstruction is observed at the subvalvular level, and calcification of the valve is often absent, especially in younger patients. [19]</p>",
"</dd>",
"</dl>"].join("\n");