content=["<dl>",
"<dt><a href='#Section0'>radiation injury</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of radiation exposure to marrow-bearing areas.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>chemotherapy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of chemotherapy.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>HIV infection</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> History of HIV risk factors or opportunistic infections.",
"<br><strong>Test:</strong> HIV testing positive.</p>",
"</dd>",
"<dt><a href='#Section3'>vitamin B12 deficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Dietary history of deficiency.Intestinal disease or resection.Neurological abnormalities.",
"<br><strong>Test:</strong> Serum B12 levels below lower limit of normal; macrocytic anaemia; megaloblastic changes in bone marrow cells.</p>",
"</dd>",
"<dt><a href='#Section4'>folate deficiency</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Dietary history of deficiency.Intestinal disease or resection.",
"<br><strong>Test:</strong> Folate levels below lower limit of normal; macrocytic anaemia; megaloblastic changes in bone marrow cells.</p>",
"</dd>",
"<dt><a href='#Section5'>hypothyroidism</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May be asymptomatic, or may present with low energy, weight gain despite poor appetite, and changes in hair and skin texture.",
"<br><strong>Test:</strong> TSH elevated, and free T4 low.</p>",
"</dd>",
"<dt><a href='#Section6'>systemic lupus erythematosus</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Classically, butterfly rash, joint pains.",
"<br><strong>Test:</strong> SLE and some other connective tissue disorders can cause pancytopenia through an autoimmune mechanism.Positive ANA and anti-double-stranded DNA can help diagnose SLE.Marrow usually cellular or fibrotic, although rarely may also be hypocellular.</p>",
"</dd>",
"<dt><a href='#Section7'>TB and atypical mycobacterial infections</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> May include cough, lymphadenopathy, weight loss.",
"<br><strong>Test:</strong> Acid-fast bacilli stain or mycobacterial culture from an involved site can diagnose these infections.Bone marrow is not hypocellular (and may show granulomata in TB).</p>",
"</dd>",
"<dt><a href='#Section8'>ehrlichiosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Severe headache, myalgias, fever, chills.",
"<br><strong>Test:</strong> Bone marrow not hypocellular.Ehrlichiosis IgG titre elevated.</p>",
"</dd>",
"<dt><a href='#Section9'>Legionella infection</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Fever, myalgia, malaise, cough initially dry then becomes productive.",
"<br><strong>Test:</strong> Urine legionella antigen positive.Bone marrow not hypocellular.</p>",
"</dd>",
"<dt><a href='#Section10'>overwhelming sepsis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Fever or hypothermia. Hypotension. Poor peripheral perfusion. Multiorgan failure.",
"<br><strong>Test:</strong> Blood cultures positive.Bone marrow not hypocellular.</p>",
"</dd>",
"<dt><a href='#Section11'>hypocellular myelodysplastic syndrome (MDS)</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> May have no differentiating clinical features.Might have history of exposure to leukaemogenic agents (e.g., alkylating agents, topoisomerase II inhibitors, and radiation).Can be complication of AA.",
"<br><strong>Test:</strong> The following features of the bone marrow examination may suggest MDS: [13]1) prominent dysplasia on marrow or peripheral blood examination (particularly in the myeloid and megakaryocyte lineages; AA can often show some erythroid dysplasia)2) circulating blasts or an increased number of marrow blasts (or CD34+ cells on immunohistochemical staining)3) presence of an increased proportion of ringed sideroblasts in the marrow4) marrow fibrosis5) cytogenetic abnormalities (especially abnormalities of chromosome 5 or 7, trisomy 8, 20q-, trisomy 21 or complex karyotypes), but AA can also be associated with cytogenetic abnormalities.</p>",
"</dd>",
"<dt><a href='#Section12'>hypocellular acute myelogenous leukaemia (AML)</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Constitutional and often related to cytopenias: weakness, low energy, pallor, easy bruising, easy bleeding.",
"<br><strong>Test:</strong> Peripheral blood smear may show blasts.Bone marrow examination reveals abnormal cell population.</p>",
"</dd>",
"<dt><a href='#Section13'>multiple myeloma</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Often asymptomatic. May have symptoms related to cytopenias: weakness, low energy, pallor, easy bruising, easy bleeding.",
"<br><strong>Test:</strong> Monoclonal urine Ig spike.Careful bone marrow examination reveals abnormal cell population.</p>",
"</dd>",
"<dt><a href='#Section14'>non-Hodgkin's lymphomas</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> May have lymphadenopathy, night sweats, weight loss, or anorexia.May have symptoms related to cytopenias: weakness, low energy, pallor, easy bruising, easy bleeding.",
"<br><strong>Test:</strong> Bone marrow examination reveals abnormal cell population.</p>",
"</dd>",
"<dt><a href='#Section15'>Hodgkin's lymphoma</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> May have lymphadenopathy.May have night sweats, weight loss, anorexia.May have symptoms related to cytopenias: weakness, low energy, pallor, easy bruising, easy bleeding.",
"<br><strong>Test:</strong> Bone marrow examination reveals abnormal cell population, usually clonal.Characteristic Reed-Sternberg cells may be seen on bone marrow biopsy.</p>",
"</dd>",
"<dt><a href='#Section16'>carcinoma metastatic to marrow</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Primary tumour is usually apparent by the time metastasis causes pancytopenia.",
"<br><strong>Test:</strong> Metastatic cells in bone marrow.</p>",
"</dd>",
"<dt><a href='#Section17'>hypocellular acute lymphoblastic leukaemia (ALL)</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> May present with features of pancytopenia; hypocellular ALL occurs in 1% to 2% of childhood ALL.",
"<br><strong>Test:</strong> CBC shows pancytopenia with neutropenia more pronounced than thrombocytopenia.Peripheral blood smear may show blasts.Bone marrow examination reveals abnormal cell population and may show increased reticulin.</p>",
"</dd>",
"<dt><a href='#Section18'>Hairy cell leukaemia</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms of pancytopenia, often with splenomegaly.",
"<br><strong>Test:</strong> CBC shows pancytopenia but with accompanying monocytopenia.</p>",
"</dd>",
"<dt><a href='#Section19'>anorexia nervosa or prolonged starvation</a></dt>",
"<dd id='Section19'>",
"<p><strong>Sign & Symptoms:</strong> Underweight.",
"<br><strong>Test:</strong> Bone marrow may show hypocellularity with gelatinous transformation, loss of fat cells, and presence of increased ground substance on haematoxylin and eosin staining.</p>",
"</dd>",
"</dl>"].join("\n");