content=["<dl>",
"<dt><a href='#Section0'>Mucormycosis and other zygomycoses (e.g., phycomycosis, basidiobolomycosis)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Paranasal sinuses and pulmonary symptoms are more common.Presence of black necrotic lesions of the nasal mucosa and hard palate.Rapid spread of involvement without regard to anatomical plane, with hypo-aesthetic skin patches.Zygomycoses are common in patients with (poorly controlled) diabetes with sino-orbital or rhinocerebral involvement.",
"<br><strong>Test:</strong> Culture and histopathology of tissue and specimens. [81]  While Zygomycetes appear as broad, non-septate hyphae with branches occurring at right angles, Aspergillus appears as narrower, septate hyphae with frequent acute-angle branching. Often, these 2 entities may be difficult to distinguish. Blood cultures are negative in zygomycosis as with aspergillosis.No serological test is available.Radiological appearance is similar to that of aspergillosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Fusariosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Common in patients with severe, prolonged neutropenia; the disease may begin at a site of trauma or with onychomycosis.Fever and myalgia are common.Skin lesions occur in 60% to 80% of infections.Less commonly, other filamentous fungi may produce lesions indistinguishable from aspergillosis.",
"<br><strong>Test:</strong> Blood cultures are frequently positive. [82]Tissue cultures help to distinguish the pathogens; histologically Fusarium resembles Aspergillus.No serological test is available.Radiological features and host characteristics are similar to those of aspergillosis. [82]</p>",
"</dd>",
"<dt><a href='#Section2'>Scedosporiosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May involve lungs, bones, joints, and CNS.In the compromised host, fever, erythematous raised lesions involving the skin, and brain involvement are common.Less commonly, other filamentous fungi may produce lesions indistinguishable from aspergillosis.",
"<br><strong>Test:</strong> Tissue cultures help to distinguish the pathogens; histologically, Scedosporium resemble Aspergillus.No serological test is available.Radiological features and host characteristics are similar to those of aspergillosis. [82]</p>",
"</dd>",
"<dt><a href='#Section3'>Nocardiosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs or symptoms.",
"<br><strong>Test:</strong> As the host characteristics and clinical/radiological features are similar, culture/histology of the lesion (skin, lung nodule, brain mass/abscess) is required for diagnosis. [83]  Histologically, Nocardia appears as gram-positive, branching, slender, filamentous organisms (acid-fast smear positive). Not infrequently, respiratory secretions or aspirate from abscess may reveal the organism.Rarely, standard blood cultures are positive with prolonged incubation.</p>",
"</dd>",
"<dt><a href='#Section4'>Mycobacterial infection</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Cough, sputum production, and fever may be prominent.Country of origin and contact hx for tuberculosis may increase suspicion for Mycobacterium tuberculosis infection.Atypical Mycobacteria, such as Mycobacterium avium, may present with respiratory symptoms, particularly in patients with chronic lung disease.",
"<br><strong>Test:</strong> Nodules and cavities on CXR or chest CT scan may be seen.Respiratory secretions (sputum, bronchoalveolar lavage (BAL) fluid) are helpful for diagnosis.Occasionally, biopsy of involved lungs for mycobacterial stain and culture is needed.</p>",
"</dd>",
"<dt><a href='#Section5'>Pneumonia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Due to bacteria such as Pseudomonas aeruginosa, may present with clinical features similar to those of aspergillosis.Fever, sputum production, cough, and shortness of breath are prominent.",
"<br><strong>Test:</strong> Gram stain and bacterial cultures if available, or BAL fluid, are useful for diagnosis.Blood cultures may be positive.CT-guided needle aspiration of the pulmonary lesion may be required for diagnosis.</p>",
"</dd>",
"<dt><a href='#Section6'>Endocarditis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Systemic bacterial infections may secondarily involve the lung and present with features of pneumonia.",
"<br><strong>Test:</strong> Gram stain and bacterial cultures if available, or BAL fluid, are useful for diagnosis.Blood cultures may be positive.CT-guided needle aspiration of the pulmonary lesion may be required.</p>",
"</dd>",
"<dt><a href='#Section7'>Sepsis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Systemic bacterial infections may secondarily involve the lung and present with features of pneumonia.",
"<br><strong>Test:</strong> Gram stain and bacterial cultures if available, or BAL fluid, are useful for diagnosis.Blood cultures may be positive.CT-guided needle aspiration of the pulmonary lesion may be required.</p>",
"</dd>",
"<dt><a href='#Section8'>Pulmonary embolism</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Underlying predisposing condition such as immobility/prolonged bed rest, hypercoagulability, or venous thrombosis of the lower extremities/pelvis.Pleuritic chest pain and shortness of breath may be the dominant symptoms. Fever, cough, and sputum production are less common. Pleural rub may be present.",
"<br><strong>Test:</strong> CXR or chest CT scan of chest typically shows wedge-shaped, peripheral pulmonary emboli/infarcts, at times mimicking findings of aspergillosis; however, multiple nodules, 'halo sign', and cavities are generally not seen.</p>",
"</dd>",
"<dt><a href='#Section9'>Malignancy</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Lymphoma involving the lung, and other malignancies, primary or metastatic in lungs, may mimic pulmonary aspergillosis. Clinical features may be indistinguishable.",
"<br><strong>Test:</strong> Comparison of serially obtained CXR/CT scans of chest is extremely helpful to distinguish pre-existing malignancy from recent pulmonary aspergillosis.Biopsy of the lesion is required for definitive diagnosis.Anecdotal data suggest that PET-CT scan may be useful to distinguish malignancy from an opportunistic process.</p>",
"</dd>",
"<dt><a href='#Section10'>Allergic bronchopulmonary aspergillosis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Hx of allergic asthma, hx of cystic fibrosis; increased shortness of breath and wheeze",
"<br><strong>Test:</strong> CXR is usually undertaken early in the work-up of chest symptoms. Skin testing, serology testing, and high-resolution CT of the chest are usually performed.</p>",
"</dd>",
"</dl>"].join("\n");