content=["<dl>",
"<dt><a href='#Section0'>Cystic fibrosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Chronic, sometimes productive cough with a possible family history of CF.Nasal polyposis at or before 12 years of age and symptoms related to other organ involvement, such as diarrhoea, malabsorption, or failure to thrive.",
"<br><strong>Test:</strong> Sweat chloride testing: level of sweat chloride &gt;67 mEq/L.Consider repeat testing.</p>",
"</dd>",
"<dt><a href='#Section1'>Chronic rhinosinusitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May present with nocturnal cough and dyspnoea from post-nasal discharge.May co-exist with asthma.",
"<br><strong>Test:</strong> Anterior rhinoscopy or nasal endoscopy may show inflammation, purulent discharge, oedema, or frank polyps.CT may show opacification of involved sinuses, mucosal thickening, air-fluid levels, or anatomic abnormalities.</p>",
"</dd>",
"<dt><a href='#Section2'>Tracheomalacia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms are usually positionally dependent and occur within the first weeks or months of life.Expiratory stridor and a barking brassy cough, wheezing respiratory distress with additional breath sound at the end of expiration (the bagpipe sign) are accompanied by the occasional extension of the neck with breathing, inspiratory stridor, episodes of holding of breath, anoxia, recurrent respiratory infections, retraction of intercostal and subcostal muscles, failure to thrive, and respiratory and cardiac arrest. [41]",
"<br><strong>Test:</strong> The sensitivity of plain x-rays is 62%, using microlaryngoscopy and bronchoscopy as the reference standards.In addition to CXR, barium oesophagography is useful for evaluating associated disease processes, such as tracheo-oesophageal fistula and reflux disease.</p>",
"</dd>",
"<dt><a href='#Section3'>Vascular ring</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Wheezing, shortness of breath, occasional stridor.",
"<br><strong>Test:</strong> CT chest with contrast: double aortic arch, abnormal take-off of the innominate artery, anomaly of left pulmonary artery, right aortic arch, aberrant right subclavian, enlarged pulmonary veins. [41]</p>",
"</dd>",
"<dt><a href='#Section4'>Foreign body aspiration</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Wheezing, shortness of breath, occasional stridor are common.If the foreign body is in the peripheral airway, localised one-sided wheezing or collapse of the distal lung tissue is found.",
"<br><strong>Test:</strong> CXR, CT chest, or bronchoscopy shows the foreign body.</p>",
"</dd>",
"<dt><a href='#Section5'>Vocal cord dysfunction</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Inspiratory and expiratory wheezing is often difficult to differentiate.Should be considered in steroid-resistant asthma patients, but may be co-existent with asthma.",
"<br><strong>Test:</strong> Direct visualisation of the vocal cords with rhinolaryngoscopy during a spell. Inspiratory flow volume loop is helpful when abnormal (flattened).</p>",
"</dd>",
"<dt><a href='#Section6'>Alpha-1 antitrypsin deficiency</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Wheezing, resistant to management.May have family history of parents or grandparents dying of lung disease.",
"<br><strong>Test:</strong> Testing for the alpha-1 antitrypsin phenotype.</p>",
"</dd>",
"<dt><a href='#Section7'>COPD</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> History of smoking.Dyspnoea occurs with or without wheezing and coughing.Examination may show barrel chest, hyper-resonance to percussion, and distant breath sounds.",
"<br><strong>Test:</strong> PFTs with residual volume (RV), total lung capacity (TLC), and a flow volume loop with bronchodilator showing an obstructive pattern with an increase in TLC and RV and a reduction in forced expiratory flow at one second (FEV1), FEV1/forced vital capacity (FVC) ratio with no response to bronchodilator.CXR showing hyper-inflation of the lungs.</p>",
"</dd>",
"<dt><a href='#Section8'>Bronchiectasis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Dyspnoea, cough, and wheezing and, if severe, recurrent pulmonary infections.",
"<br><strong>Test:</strong> High-resolution CT chest: dilated airways, bronchial wall thickening.Can occasionally be seen on CXR.</p>",
"</dd>",
"<dt><a href='#Section9'>Pulmonary embolism</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Patients have a wide variety of presentations but most common is shortness of breath and pleuritic pain.",
"<br><strong>Test:</strong> Pulmonary angiogram is the preferred test, but carries risks.An acceptable alternate test is CT angiogram of the lung, which, if not available, can be replaced with the less sensitive V/Q scan.</p>",
"</dd>",
"<dt><a href='#Section10'>Congestive heart failure</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> History of CAD or uncontrolled HTN.Exam shows dependent oedema, elevated jugular venous pressure, and basal pulmonary crepitations.",
"<br><strong>Test:</strong> CXR may show increased alveolar markings, fluid in fissures, and pleural effusions.Echocardiogram: reduced left ventricular ejection fraction.</p>",
"</dd>",
"<dt><a href='#Section11'>Common variable immunodeficiency</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> History of recurrent, usually sinopulmonary, infections.",
"<br><strong>Test:</strong> Serum IgG level &lt;5g/L (500 mg/dL).</p>",
"</dd>",
"</dl>"].join("\n");