content=["<dl>",
"<dt><a href='#Section0'>Myopia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Any uncorrected myopia can cause reduced visual acuity and should, therefore, be included in the differential diagnoses of blurred vision. It is impossible to distinguish the different causes of blurred vision by history taking and visual acuity testing alone. [33]",
"<br><strong>Test:</strong> Retinoscopy can easily distinguish between simple myopia, in which neutralisation of the reflex is obtained in all meridians by the same dioptric power, and astigmatism, where different dioptric powers are required in different meridians. [24]</p>",
"</dd>",
"<dt><a href='#Section1'>Hyperopia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Any uncorrected hyperopia can cause reduced visual acuity and should, therefore, be included in the differential diagnoses of blurred vision. It is impossible to distinguish the different conditions merely by history taking and visual acuity testing. [33]",
"<br><strong>Test:</strong> Retinoscopy can easily distinguish between simple hyperopia, in which neutralisation of the reflex is obtained in all meridians by the same dioptric power, and astigmatism, where different dioptric powers are required in different meridians. [24]</p>",
"</dd>",
"<dt><a href='#Section2'>Cataract</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Cataract is characterised by painless, progressive blurred vision, but it is also associated with other complaints such as difficulty seeing in bright sunlight and glare from incoming headlights at night, which are not common in astigmatism. [34]",
"<br><strong>Test:</strong> Cataract can be easily diagnosed and graded using slit lamp biomicroscopy. The presence of cataract does not rule out co-existing astigmatism and therefore refraction also should be determined. [34]</p>",
"</dd>",
"<dt><a href='#Section3'>Strabismus</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Certain types of strabismus are associated with diplopia, which may be interpreted as blurred vision. In some cases, but not all, the misalignment of the eyes is obvious to the observer or is reported by the patient's relatives. [34]",
"<br><strong>Test:</strong> Strabismus can be diagnosed by cover-uncover test, in which an occluder is used for alternate covering of the eyes in order to detect an obvious or a hidden eye deviation. The presence of strabismus does not rule out co-existing astigmatism, and therefore refraction should also be determined. [34]</p>",
"</dd>",
"<dt><a href='#Section4'>Age-related macular degeneration (AMD)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Gradual blurring of vision in person &gt;50 years old must raise the suspicion for AMD. As the degeneration progresses, the patient may also complain of metamorphopsia (straight lines appear curved or wavy) and scotomas. [34]",
"<br><strong>Test:</strong> The diagnosis can be achieved by a thorough fundus examination and confirmed by fluorescein angiography. [34]</p>",
"</dd>",
"</dl>"].join("\n");