content=["<dl>",
"<dt><a href='#Section0'>Seborrhoeic dermatitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Characteristic greasy scale that is not pruritic. Often affects cheeks on face, scalp, extremities and trunk. Unlike atopic dermatitis, the nappy area is often affected.",
"<br><strong>Test:</strong> Clinical exam is the best tool to differentiate between these lesions.</p>",
"</dd>",
"<dt><a href='#Section1'>Irritant contact dermatitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Common in nappy area, face, and extensor surfaces in children resulting from exposure to irritating substances. Typically less pruritic than atopic dermatitis.",
"<br><strong>Test:</strong> Elimination of irritant will result in clinical improvement.Patch testing may be positive for relevant irritant.May be limited role for skin biopsy (e.g., patch tests are negative, chronic disease, uncertain diagnosis), which can identify whether contact dermatitis is present, but does not distinguish irritant from allergic contact dermatitis.</p>",
"</dd>",
"<dt><a href='#Section2'>Allergic contact dermatitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Well-circumscribed erythematous lesions, often with spongiotic papules, vesicles, and crusting. Lesions are usually pruritic. Eruptions are due to contact with specific allergen, and removal of offending agent results in resolution of symptoms.",
"<br><strong>Test:</strong> Elimination of allergic stimuli results in resolution of dermatitis.Patch testing may be positive for relevant allergen.May be limited role for skin biopsy (e.g., patch tests are negative, chronic disease, uncertain diagnosis), which can identify whether contact dermatitis is present, but does not distinguish irritant from allergic contact dermatitis.</p>",
"</dd>",
"<dt><a href='#Section3'>Scabies</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Severe pruritus, particularly at night. In addition to papules or vesicles, burrows may be evident and will help to make the diagnosis. The wrists, ankles, palms, soles, interdigital spaces, axilla, waist and groin are the most commonly affected sites. Patients will often report similar symptoms in family members or other close contacts. [3]",
"<br><strong>Test:</strong> Microscopy may reveal mites, eggs or scybala (mite faeces).</p>",
"</dd>",
"<dt><a href='#Section4'>Psoriasis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Well-circumscribed, erythematous lesions with silver scale that show a predilection for extensor surfaces, particularly elbows and knees. The nail pitting seen in psoriasis has smaller pits and is more common than that seen in patients with atopic dermatitis.",
"<br><strong>Test:</strong> This is usually a clinical diagnosis. No laboratory testing is typically necessary to distinguish between atopic dermatitis and psoriasis. If the diagnosis is uncertain, there may be a limited role for skin biopsy which may not always reveal the classic features of psoriasis.</p>",
"</dd>",
"<dt><a href='#Section5'>Mycosis fungoides</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> The initial stages of mycosis fungoides (cutaneous T cell lymphoma) may look similar to atopic dermatitis. Erythematous plaques in random distribution are common and scale is often present. As opposed to patients with atopic dermatitis, patients with mycosis fungoides tend to be older at the time of diagnosis, with an average age of 50 years.",
"<br><strong>Test:</strong> Skin biopsy is necessary to make the diagnosis of mycosis fungoides.</p>",
"</dd>",
"</dl>"].join("\n");