content=["<dl>",
"<dt><a href='#Section0'>Atypical autism (or autistic spectrum disorder [ASD] or pervasive developmental disorder not otherwise specified [PDDNOS])</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Children have an autistic spectrum disorder (ASD), but do no't meet ICD-10 or DSM-IV criteria for autism (e.g., children might not have language delay, or have significant enough social communication difficulties to meet criteria for the core disorder).",
"<br><strong>Test:</strong> The clinical history, standardised interview, and observational tools help a clinician come to a conclusion about whether a child has autism, or another form of ASD.</p>",
"</dd>",
"<dt><a href='#Section1'>Asperger's syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> People with Asperger's syndrome have social, communication, and repetitive domain difficulties but have no language delay and have average or above average IQ.Asperger's syndrome tends to be associated with age-appropriate language abilities (although language is usually used in an unusual way, for example, precise, pedantic speech).",
"<br><strong>Test:</strong> The clinical history, standardised interviews, and observational tools help a clinician come to a conclusion.</p>",
"</dd>",
"<dt><a href='#Section2'>Other causes of learning difficulties/mental retardation</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients do not seem to the specialist to meet criteria for autism, autism spectrum disorder, or Asperger's syndrome and may have one of many other neurodevelopmental disorders underlying their difficulties.In some children, a unifying diagnosis cannot be identified.",
"<br><strong>Test:</strong> The clinical history, standardised interviews, and observational tools help a clinician come to a conclusion.</p>",
"</dd>",
"<dt><a href='#Section3'>ADHD</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients have problems with attention and hyperactivity.Children do not have the same degree of social communication difficulties as children with autism.The early developmental history is of hyperactivity rather than features of autism",
"<br><strong>Test:</strong> The clinical history, standardised interviews, and observational tools help a clinician come to a conclusion.</p>",
"</dd>",
"</dl>"].join("\n");