content=["<dl>",
"<dt><a href='#Section0'>Insect or spider bite</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Other arthropod assaults may be difficult to differentiate and are the primary consideration in the differential diagnosis.Fleas: usually lower legs.Mosquitoes: patient is aware of bite.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Urticaria</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have a hx of previous urticaria and/or recent exposure to trigger factor (e.g., drug or food).Lesions of urticaria due to other causes tend to be more blanchable and of shorter duration than urticarial bed bug bites",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Scabies</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Hx of exposure to another individual with scabies.Presents as eczematous papules and patches; some lesions may become nodular; keratotic thickening can be seen on the hands.Sites of predilection are the interdigital spaces, umbilicus, groin, and axillae.Burrows (intact tunnel with a tiny dark dot, the mite, at the end) may be seen in the interdigital web spaces.",
"<br><strong>Test:</strong> Skin scraping may reveal scabies mites, eggs, and scybala (faeces) on microscopic examination. [5]</p>",
"</dd>",
"<dt><a href='#Section3'>Dermatitis herpetiformis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hx of coeliac disease (90% of patients).A recurrent, extremely pruritic condition; typically presents with grouped (herpetiform) erythematous papules, vesicles, and excoriations distributed symmetrically on the chest, elbows, knees, lower back, and buttocks",
"<br><strong>Test:</strong> Skin biopsy for direct immunofluorescence shows IgA in the upper dermis arranged in a granular pattern. [20]</p>",
"</dd>",
"</dl>"].join("\n");