content=["<dl>",
"<dt><a href='#Section0'>Aphthous stomatitis (recurrent)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Only oral ulcers, none of the other manifestations.",
"<br><strong>Test:</strong> None.</p>",
"</dd>",
"<dt><a href='#Section1'>Crohn's disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Genital ulcers and eye involvement less common.Rectal or anal pathology more common.",
"<br><strong>Test:</strong> Colonoscopy and biopsy show Crohn's disease findings.</p>",
"</dd>",
"<dt><a href='#Section2'>Ulcerative colitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Genital ulcers and eye involvement less common.Rectal or anal pathology more common.",
"<br><strong>Test:</strong> Colonoscopy and biopsy consistent with ulcerative colitis.</p>",
"</dd>",
"<dt><a href='#Section3'>Herpes simplex infection</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Oral ulcers may be on the outer part of the lips, not just the mucosal surface.",
"<br><strong>Test:</strong> Cultures and serology for herpes are positive.</p>",
"</dd>",
"<dt><a href='#Section4'>Necrotising vasculitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Renal and lung vasculitic involvement possible, unlike Behcet's syndrome.",
"<br><strong>Test:</strong> Positive anti-neutrophil cytoplasmic antibodies possible.</p>",
"</dd>",
"<dt><a href='#Section5'>Seronegative spondyloarthropathies</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Psoriasis, sacroiliac involvement, and penile lesions possible.",
"<br><strong>Test:</strong> HLA-B27 associated.</p>",
"</dd>",
"<dt><a href='#Section6'>Acne vulgaris</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Distribution of lesions less facial and more truncal and on limbs.",
"<br><strong>Test:</strong> None.</p>",
"</dd>",
"<dt><a href='#Section7'>Erythema nodosum</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Nodular lesions on limbs, self-resolving, may be painful. No oral or genital ulcers.",
"<br><strong>Test:</strong> None. Behcet's syndrome is a cause of erythema nodosum.</p>",
"</dd>",
"<dt><a href='#Section8'>Superficial thrombophlebitis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> No oral or genital ulcers.",
"<br><strong>Test:</strong> Duplex ultrasound reveals non-compressible vessel.</p>",
"</dd>",
"<dt><a href='#Section9'>Rheumatoid arthritis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Mucocutaneous ulcers should be absent.",
"<br><strong>Test:</strong> RF-positive.</p>",
"</dd>",
"</dl>"].join("\n");