content=["<dl>",
"<dt><a href='#Section0'>Tumour</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There may be progressive facial paralysis, a parotid mass, local pain, primary cancer elsewhere in the body, tinnitus, or ipsilateral eighth nerve-type hearing loss.",
"<br><strong>Test:</strong> MRI may demonstrate benign or malignant mass lesion along the facial nerve, or in the internal auditory canal and/or cerebellopontine angle (acoustic neuroma/meningioma), parotid, or temporal bone.</p>",
"</dd>",
"<dt><a href='#Section1'>Facial nerve injury</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> There is a hx of trauma or surgery (e.g., parotidectomy).",
"<br><strong>Test:</strong> High-resolution CT of the temporal bone detects temporal bone fracture or facial nerve lesion.</p>",
"</dd>",
"<dt><a href='#Section2'>Lyme disease</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There may be fever, headache, fatigue, arthritis, skin rash (erythema migrans), hx of tick bites or exposure, or location in an endemic area.",
"<br><strong>Test:</strong> ELISA or indirect fluorescent antibody titres to Borrelia burgdorferi are elevated.Confirmation is by Western blot assay.</p>",
"</dd>",
"<dt><a href='#Section3'>Middle ear disease and complications</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There may be fever, pain, ear discharge, or underlying immune compromise.",
"<br><strong>Test:</strong> Otoscopy is abnormal in acute or chronic otitis media. High-resolution CT of the temporal bone may detect evidence of mastoiditis, petrositis, or basilar skull osteomyelitis.</p>",
"</dd>",
"<dt><a href='#Section4'>Herpes zoster oticus (Ramsay Hunt syndrome)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Blisters are present on the auricular concha of the pinna.",
"<br><strong>Test:</strong> Wound scrapings may yield multinucleated giant cells, known as Tzanck cells.Serology may be helpful (enzyme immunoassay in acute and convalescent serum) to confirm rising varicella zoster virus titres.</p>",
"</dd>",
"<dt><a href='#Section5'>Rosenthal-Melkersson syndrome</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> There are recurrently swollen lips or face and fissured/geographic tongue.",
"<br><strong>Test:</strong> There are no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section6'>Heerfordt's syndrome</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Fever, anterior uveitis, and parotid gland enlargement are present.",
"<br><strong>Test:</strong> CXR suggests sarcoidosis. Ophthalmological examination confirms uveitis. There may be non-caseating granulomas in the parotid.</p>",
"</dd>",
"<dt><a href='#Section7'>Stroke</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> There are signs and symptoms of other neurological dysfunction.Forehead movement is spared.",
"<br><strong>Test:</strong> MRI or head CT scan shows evidence of stroke.</p>",
"</dd>",
"</dl>"].join("\n");