content=["<dl>",
"<dt><a href='#Section0'>Meniere's disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There is associated hearing loss, tinnitus, and aural fullness that is often exacerbated during an episode of vertigo.Recurrent episodes of vertigo last for minutes to hours and are not provoked by positional changes. [1]  [35]",
"<br><strong>Test:</strong> Audiogram will demonstrate a sensorineural hearing loss, usually unilateral and initially worse in the low frequencies.</p>",
"</dd>",
"<dt><a href='#Section1'>Vestibular neuronitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Often a single episode of persistent vertigo lasting for days. The vertigo can be exacerbated by any positional change, unlike the specific head movements that induce BPPV attacks.May be preceded by a non-specific viral infection. [1]  [35]",
"<br><strong>Test:</strong> Little or no nystagmus or vertigo during Dix-Hallpike testing.</p>",
"</dd>",
"<dt><a href='#Section2'>Labyrinthitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Often a single episode of persistent vertigo lasting for days. The vertigo can be exacerbated by any positional change, unlike the specific head movements that induce BPPV attacks.May be preceded by a non-specific viral infection. Hearing loss is present in viral labyrinthitis. [1]  [35]",
"<br><strong>Test:</strong> Little or no nystagmus or vertigo during Dix-Hallpike testing.Audiogram testing will demonstrate sensorineural hearing loss in cases of labyrinthitis.</p>",
"</dd>",
"<dt><a href='#Section3'>Perilymphatic fistula</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Is accompanied by hearing loss, tinnitus, and aural fullness.",
"<br><strong>Test:</strong> A positive fistula test (vertigo, with or without nystagmus, induced by change in ear canal pressure) can aid diagnosis of perilymphatic fistula.</p>",
"</dd>",
"<dt><a href='#Section4'>Central disorders (e.g., migraines, multiple sclerosis, posterior fossa tumours, ischaemic processes)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> BPPV is a peripheral form of vertigo and should not present with or be diagnosed in the presence of neurological symptoms suggestive of a central disorder. Headaches, visual symptoms (double vision, visual field defects, visual loss), other sensory abnormalities such as paraesthesias or deficits, and motor abnormalities all suggest a central aetiology.Vertigo not precipitated by specific head movements.Central disorders can mimic BPPV attacks; however, symptoms tend to have a more gradual onset and to be less severe and less transient. [1]  [35]",
"<br><strong>Test:</strong> During Dix-Hallpike testing for posterior canal BPPV, the nystagmus may not fade away or fatigue, lacks a torsional (rotatory) component, and can be purely vertical. [1]  [35]CT and/or MRI scans of the head can aid diagnosis of many central disorders that may mimic BPPV.</p>",
"</dd>",
"</dl>"].join("\n");