content=["<dl>",
"<dt><a href='#Section0'>Melkersson-Rosenthal's syndrome (fissured tongue)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Triad of presence of significant lip enlargement (granulomatous cheilitis) and intermittent seventh (facial) nerve palsy in association with the fissured tongue. However, the triad of symptoms do not all have to be present at a given time.",
"<br><strong>Test:</strong> Tongue biopsy may exhibit presence of non-caseating granulomas.</p>",
"</dd>",
"<dt><a href='#Section1'>Oral hairy leukoplakia (hairy tongue)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Painless white plaques along the lateral tongue borders. History of HIV or immunosuppression. [8]",
"<br><strong>Test:</strong> Tongue biopsy with immunostaining of the specimen for Epstein-Barr virus (EBV), the causative agent for oral hairy leukoplakia.</p>",
"</dd>",
"<dt><a href='#Section2'>Mucosal candidiasis (hairy/geographic tongue)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> White patches resemble milk curds and when wiped off reveal a raw erythematous and sometimes bleeding base.",
"<br><strong>Test:</strong> Cytology with potassium hydroxide preparation for diagnosis of candidal organisms.</p>",
"</dd>",
"<dt><a href='#Section3'>Contact stomatitis (geographic tongue)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> The presence of perioral and lip dermatitis may aid in making the diagnosis. Also the patient may report an inciting factor such as mouthwashes, toothpastes, dental materials, and gum.",
"<br><strong>Test:</strong> Patch testing for contact allergen. RAST (radioallergosorbent test) for specific immunoglobulin E (IgE) for food and latex allergy.</p>",
"</dd>",
"</dl>"].join("\n");