content=["<dl>",
"<dt><a href='#Section0'>Dry eye syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> May present with symptoms similar to those of blepharitis.Fluorescein staining in dry eye syndrome typically involves the interpalpebral zone. In blepharitis the lower third of the cornea is more commonly involved.Slit lamp findings of collarettes and capped meibomian glands are more suggestive of blepharitis.",
"<br><strong>Test:</strong> Schirmer's test shows reduced tear production.Tear film break-up time is decreased.These tear film abnormalities are also common in blepharitis but would generally have debris and saponification of the tear film in addition.</p>",
"</dd>",
"<dt><a href='#Section1'>Chalazion</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Focal tenderness or nodule on eyelid caused by blocked glands.Commonly also a sign of associated underlying blepharitis.",
"<br><strong>Test:</strong> Lid biopsy shows lipogranulomatous inflammation--histiocytes and multi-nucleated giant cells enveloping optically clear spaces.Lymphocytes, plasma cells, and neutrophils may also be present.</p>",
"</dd>",
"<dt><a href='#Section2'>Squamous cell carcinoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Unilateral lid changes, lid architecture distortion including ulceration, lash changes or loss. [26]",
"<br><strong>Test:</strong> Lid biopsy shows atypical squamous cells forming nests and strands, infiltrating the dermis, with desmoplastic fibrous tissue reaction.</p>",
"</dd>",
"<dt><a href='#Section3'>Basal cell carcinoma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Unilateral lid changes, pearly nodule with telangiectasis, lash changes or loss, lid architecture distortion.",
"<br><strong>Test:</strong> Lid biopsy shows peripheral palisading basal cells.</p>",
"</dd>",
"<dt><a href='#Section4'>Sebaceous cell carcinoma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Unilateral lid changes, recurrent or non-resolving chalazion, lid architecture distortion, lash changes or loss. [26]",
"<br><strong>Test:</strong> Lid biopsy shows nests with central necrosis, foamy cytoplasm.</p>",
"</dd>",
"</dl>"].join("\n");