content=["<dl>",
"<dt><a href='#Section0'>Locally invasive breast cancer</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> More commonly presents as a breast lump with or without nipple inversion, discharge, or tenderness.",
"<br><strong>Test:</strong> Mammographic microcalcifications may be pure ductal carcinoma in situ (DCIS) or have an invasive component, which can be detected on excisional biopsy. [35]Lesions are not confined to the duct but have invaded surrounding tissue.</p>",
"</dd>",
"<dt><a href='#Section1'>Atypical hyperplasia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to distinguish clinically, as asymptomatic.",
"<br><strong>Test:</strong> Atypical hyperplasia on pathology.</p>",
"</dd>",
"<dt><a href='#Section2'>Fibroadenoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Presents as a breast lump on examination.If lump is palpable, it is typically freely mobile.",
"<br><strong>Test:</strong> Mammographic calcifications that are large, are round, have sharp edges, and are diffuse are typically benign. [35]</p>",
"</dd>",
"<dt><a href='#Section3'>Breast cyst</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Most commonly presents as a breast lump and tenderness.May occur in association with menstrual cycle.",
"<br><strong>Test:</strong> Mammographic calcifications that are large, are round, have sharp edges, and are diffuse are typically benign. [35]</p>",
"</dd>",
"</dl>"].join("\n");