content=["<dl>",
"<dt><a href='#Section0'>Schizophrenia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Period of psychosis lasts for &gt;1 month. Diagnosis based on patient hx and FHx and medical records.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Delusional disorder</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Period of psychosis lasts for &gt;1 month. Diagnosis based on patient hx and FHx and medical records.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Major depressive disorder with psychotic features</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Period of psychosis lasts for &gt;1 month. Diagnosis based on patient hx and FHx and medical records.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Recent substance use</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Report from patient or family of recent substance use. Physical examination findings may be consistent with effects of substance.",
"<br><strong>Test:</strong> Blood and/or urine toxicology: positive for specific substance/s.</p>",
"</dd>",
"<dt><a href='#Section4'>Seizure disorder</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of seizures.",
"<br><strong>Test:</strong> EEG: typical findings according to seizure type.MRI and CT brain scan: may demonstrate causative neurological lesions.</p>",
"</dd>",
"<dt><a href='#Section5'>Syphilis (quaternary)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> History of sexual contact with infected person.CNS involvement: may be associated with cranial nerve palsy, stroke, dementia, sensory loss, Argyll Robertson pupil.",
"<br><strong>Test:</strong> Serum and CSF: VDRL, RPR, Treponema pallidum haemagglutination (TPHA), FTA positive.</p>",
"</dd>",
"<dt><a href='#Section6'>Sarcoidosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> CNS involvement: may be associated with palsies of cranial and peripheral nerves, seizures, meningitis (granulomatous). Pituitary involvement can cause diabetes insipidus.Pulmonary features include dyspnoea and cough.",
"<br><strong>Test:</strong> Serum ACE activity: increased.MRI and CT brain scan: space-occupying lesions.CXR: bihilar lymphadenopathy, pulmonary infiltrates.</p>",
"</dd>",
"<dt><a href='#Section7'>Lung cancer</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> CNS metastases: focal neurological signs.Paraneoplastic syndrome: can include neuropathy, myopathy, cerebellar degeneration.Pulmonary features include dyspnoea, cough, haemoptysis.",
"<br><strong>Test:</strong> MRI and CT brain scan brain: metastasesCXR and CT chest scan: mass, coin lesions, pleural effusion, hilar lymphadenopathy.</p>",
"</dd>",
"<dt><a href='#Section8'>Thyrotoxicosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Signs include tachycardia, tremor, thyroid enlargement.",
"<br><strong>Test:</strong> TSH: reduced.Free T4 and free T3: elevated.</p>",
"</dd>",
"<dt><a href='#Section9'>Head trauma</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> History of head trauma. May be accompanied by focal neurological signs.",
"<br><strong>Test:</strong> MRI and CT brain scan: may demonstrate focal sequelae of trauma such as haematoma, skull fracture, cerebral oedema.</p>",
"</dd>",
"</dl>"].join("\n");