content=["<dl>",
"<dt><a href='#Section0'>Bacterial pneumonia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Pneumonia is much less common in this age group than bronchiolitis.Infants with pneumonia generally have higher fever (&ge;40&deg;C) than with bronchiolitis.Wheezing is not a common finding in pneumonia.",
"<br><strong>Test:</strong> An FBC may demonstrate leukocytosis and neutrophilia.The presence of infiltration on chest x-ray would increase the suspicion of pneumonia.</p>",
"</dd>",
"<dt><a href='#Section1'>Chlamydia pneumoniae pneumonia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> The mothers may have a history of vaginal chlamydial infection.Most infants with C pneumoniae infection have a history of neonatal conjunctivitis.The clinical course of C pneumoniae pneumonia is usually subacute and not associated with upper respiratory tract infection.Patients are usually afebrile. The cough of C pneumoniae has a distinctive staccato-like quality. Crackles are more common than wheezes in C pneumoniae.",
"<br><strong>Test:</strong> Eosinophilia is a feature of C pneumoniae that is not seen in bronchiolitis.C pneumoniae can be diagnosed by culture or antigen detection from nasopharyngeal secretions.</p>",
"</dd>",
"<dt><a href='#Section2'>Cystic fibrosis (CF)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> CF is usually associated with symptoms and signs of pancreatic insufficiency, such as steatorrhoea, failure to thrive, and fat-soluble-vitamin deficiencies.A FHx of CF is common in affected infants.CF lung disease usually presents as chronic cough.It is insidious in onset and not associated with upper respiratory tract symptoms.",
"<br><strong>Test:</strong> Measurement of sweat chloride by quantitative pilocarpine iontophoresis will be elevated (&gt;60 mmol/L) in almost all infants with CF.</p>",
"</dd>",
"<dt><a href='#Section3'>Laryngotracheobronchitis (croup)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> A viral infection of the upper airways, often caused by parainfluenza virus.Characterised by fever, inspiratory stridor, and a barking cough.Symptoms often worsen at night.",
"<br><strong>Test:</strong> Diagnosis is usually clinical.Sub-glottic narrowing may be seen on an AP neck radiograph; however, this investigation is rarely indicated.</p>",
"</dd>",
"</dl>"].join("\n");