content=["<dl>",
"<dt><a href='#Section0'>Medial meniscopathy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with anserine bursitis.McMurray test: usually positive in meniscal disease and negative in bursitis. Patient lies supine; leg is rotated on the thigh with the knee fully flexed. The physician grasps the patient's foot. The leg is flexed to 90&deg; while the foot is maintained first in full internal rotation and then rotated in full external rotation. A click occurs and the patient feels pain if a meniscal tear is present.Apley grind test: usually positive in meniscal disease and negative in bursitis. Patient lies prone; foot is rotated externally and knee flexed to 90&deg;. Foot rotated internally and knee extended. The tibia is then compressed into the knee joint while externally rotating the foot. If this increases the pain, test is positive, indicating meniscal damage.Bounce home test: usually positive in meniscal disease and negative in bursitis. With the patient lying supine, the surgeon grasps the foot and completely flexes the knee. The knee is then passively allowed to extend. The knee should extend completely or bounce home into extension with a sharp endpoint. Test is positive when full extension cannot be attained.",
"<br><strong>Test:</strong> MRI: shows a meniscal tear, communicating with its superior and/or inferior surfaces or inner margin, on &gt;1 slice. Meniscal subluxation is defined as protrusion over the edge of the tibial plateau seen at the level of the body of the meniscus.</p>",
"</dd>",
"<dt><a href='#Section1'>Medial compartment osteoarthritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with anserine bursitis.Medial knee osteoarthritis is defined as pain or stiffness for most days of the preceding month and osteophytes at the medial joint margin of the tibiofemoral joint.",
"<br><strong>Test:</strong> Weight-bearing radiographs of the knees: shows medial joint space narrowing, osteophytes, subchondral bone cysts, and sclerosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Baker's cyst</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with anserine bursitis.Often asymptomatic. The cyst may rupture or leak, causing swelling and pain in the popliteal region.",
"<br><strong>Test:</strong> Ultrasound scan: demonstrates a fluid-filled cystic mass in the popliteal region.MRI: shows an oval-shaped, fluid-filled, well-defined mass posterior to the knee joint.</p>",
"</dd>",
"<dt><a href='#Section3'>Medial collateral ligament damage</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with anserine bursitis.Valgus stress test is usually positive in medial collateral ligament disease and negative in bursitis. The patient lies supine. The physician places one hand on the lateral aspect of the knee joint and the other hand on the medial aspect of the distal tibia. A valgus stress is applied with the leg flexed to 30&deg;. If the knee joint abducts more than the uninjured leg, the test is positive.",
"<br><strong>Test:</strong> MRI scan: shows increased signal within the ligament itself without an associated knee joint effusion (unless there is another injury such as an associated ACL tear or patellar dislocation).</p>",
"</dd>",
"<dt><a href='#Section4'>Soft-tissue infection</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Clinically similar to any bursitis, with pain, erythema, and swelling. May have spreading cellulitis.",
"<br><strong>Test:</strong> MRI: a reticulated pattern of abnormal signal intensity in the subcutaneous tissue on both T1-weighted and fluid-sensitive sequences. When intravenous contrast is administered, the subcutaneous tissues will have a reticulated pattern of enhancement. Non-infective oedema may have similar signal characteristics but without enhancement.X-ray/CT: fasciitis is an infection of the deep or superficial fascia. Soft-tissue gas is a suggestive feature of necrotising fasciitis.</p>",
"</dd>",
"<dt><a href='#Section5'>Local bone tissue tumours</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Can be clinically similar to any local bursitis, with pain, swelling, and erythema.",
"<br><strong>Test:</strong> X-ray: abnormal bone mass can be readily identified. Further imaging may not be required.MRI: useful to delineate anatomical boundaries and may demonstrate soft-tissue involvement.Bone scan: normally shows increased uptake, although some tumours show decreased uptake. Done in combination with x-ray or MRI.</p>",
"</dd>",
"<dt><a href='#Section6'>Spinal stenosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with subtrochanteric bursitis.Neurogenic claudication: pain extending from the back into the buttocks and thigh, and sometimes into the lower leg. The pain is exacerbated by lumbar extension and improves with lumbar flexion.A sensory or motor deficit is present in about half of patients with symptomatic lumbar stenosis.Romberg's manoeuvre: patient stands with eyes closed and is observed for imbalance. This may reveal a wide-based gait and unsteadiness, reflecting involvement of proprioceptive fibres in the posterior columns.",
"<br><strong>Test:</strong> X-ray: narrowing may occur in the central spinal canal, in the area under the facet joints (subarticular stenosis), or more laterally, in the neural foramina. Can demonstrate the extent of disc-space narrowing, end-plate sclerosis, and facet-joint hypertrophy. The neural foramina may reveal osteophytes, suggesting foraminal stenosis.MRI/CT: can confirm the presence of spinal stenosis, as a reduction in the cross-sectional area of the central canal and neural foramina.</p>",
"</dd>",
"<dt><a href='#Section7'>Lumbar radiculopathy</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with subtrochanteric bursitis.A sharp or dull, burning pain in the back, radiating into the leg (sciatica).Pain is exacerbated by bending forwards or sitting and relieved by lying down and sometimes by walking. Typical presentation is pain and sensory loss.Tests of Lasegue, Wasserman, and Valsalva are usually positive in lumbar radiculopathy and negative in bursitis.Lasegue test: usually positive in lumbar radiculopathy and negative in bursitis. With the patient lying supine, the surgeon flexes the leg to 90&deg; at the hip and knee. The knee is slowly extended, which produces radiating pain.Wasserman test: usually positive in lumbar radiculopathy and negative in bursitis. The patient lies prone and the physician slowly extends the hip. Accentuation of pain in the anterior thigh suggests a high lumbar (L2, L3) radiculopathy.Valsalva test: usually positive in lumbar radiculopathy and negative in bursitis. This manoeuvre increases intrathecal pressure, which accentuates radicular pain in the presence of spinal nerve compression and inflammation.",
"<br><strong>Test:</strong> MRI: reveals structure of the lumbosacral spine and nerve roots. Imaging results need to be interpreted in the context of clinical symptoms and signs.Needle electromyography: can diagnose compressive and non-compressive radiculopathies and provides a measure of severity of radiculopathic disease.</p>",
"</dd>",
"<dt><a href='#Section8'>Osteoarthritis of the hip</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with subtrochanteric bursitis.Hip pain or stiffness in the groin and hip region on most days of the preceding month.Often a loss of internal rotation initially.",
"<br><strong>Test:</strong> X-ray: shows femoral or acetabular osteophytes and/or axial joint space narrowing.</p>",
"</dd>",
"<dt><a href='#Section9'>Osteonecrosis of the hip</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with subtrochanteric bursitis.Hip pain and/or stiffness in the groin and hip region.",
"<br><strong>Test:</strong> X-ray: can demonstrate advanced stages of osteonecrosis characterised by sclerosis, lucency, and flattening of the femoral head.MRI: shows subchondral lesions of variable signal intensity outlined by a low-signal rim on T1-weighted images along the anterosuperior aspect of the femoral head. A more specific sign is the double-line sign (an outer low-intensity rim and an inner high-intensity band) on T2-weighted images.</p>",
"</dd>",
"<dt><a href='#Section10'>Stress fracture of the hip</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with subtrochanteric bursitis.Hip pain and/or stiffness in the groin and hip region.",
"<br><strong>Test:</strong> X-ray: may demonstrate a stress fracture, but this is often missed on plain films.MRI: is the most sensitive modality to detect and characterise stress fracture of the hip.</p>",
"</dd>",
"<dt><a href='#Section11'>Rotator cuff tendinopathy</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable from subacromial bursitis. Many patients with a rotator cuff tendinopathy have a subacromial bursitis as well.",
"<br><strong>Test:</strong> MRI: shows an increased signal within the tendon of the rotator cuff.</p>",
"</dd>",
"<dt><a href='#Section12'>Rotator cuff lesions</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Often clinically indistinguishable from subacromial bursitis. Many patients with rotator cuff tendinopathy have an associated subacromial (subdeltoid) bursitis. Usually, weakness accompanies pain. Pain with preserved strength is more suggestive of bursitis or tendinopathy.",
"<br><strong>Test:</strong> MRI: shows an interruption of the signal within the tendon of the rotator cuff.</p>",
"</dd>",
"<dt><a href='#Section13'>Calcific tendinopathy of the rotator cuff or Achilles tendon</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable from subacromial/retrocalcaneal bursitis.",
"<br><strong>Test:</strong> X-ray: may show presence of a calcific deposit within the tendon of the rotator cuff or Achilles tendon.Ultrasound: can detect calcifications in the Achilles tendon as hyperechoic areas casting acoustic shadowing.MRI: demonstrates presence of a calcific deposit within the tendon.</p>",
"</dd>",
"<dt><a href='#Section14'>Superior labrum anterior to posterior (SLAP) lesions of the long head of the biceps tendon</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Often clinically indistinguishable from subacromial bursitis.O'Brien test: a positive result suggests an SLAP lesion. The arm is flexed to 90&deg; with the elbow extended. The arm is adducted by 10&deg; and the thumb pointed towards the floor. Downward pressure is applied by the examiner. The palm is then supinated and the procedure repeated. The test is considered positive if pain is elicited with the first manoeuvre and reduced or eliminated on supination.Speed test: a positive result suggests an SLAP lesion. The patient flexes his/her shoulder against resistance while the elbow is extended and forearm supinated. The test is positive when pain is localised to the bicipital groove. [15]",
"<br><strong>Test:</strong> MRI: shows the presence of increased signal within the labrum extending to its surface. If contrast is used, it may be taken up into the labrum.</p>",
"</dd>",
"<dt><a href='#Section15'>Subluxation of the long head of the biceps tendon</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable from subacromial bursitis but often associated with an injury to the subscapularis, which might be detected with the belly-press test or the lift-off test.Belly-press test: the patient presses the abdomen with the flat of the hand and attempts to keep the arm in maximal internal rotation. If subscapularis is impaired, the elbow drops back behind the trunk.Lift-off test: patients with subscapularis rupture will be unable to lift the dorsum of their hand off their back.",
"<br><strong>Test:</strong> MRI: shows the presence of a subluxated long head of the biceps tendon.</p>",
"</dd>",
"<dt><a href='#Section16'>Tendinopathy of the long head of the biceps tendon</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable from subacromial bursitis.",
"<br><strong>Test:</strong> MRI: shows the presence of increased signal within the long head of the biceps tendon.</p>",
"</dd>",
"<dt><a href='#Section17'>Haglund's deformity</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with, or exist along with, retrocalcaneal bursitis.The pain generally emanates from the posterior aspect of the heel and is aggravated by active or passive motion.",
"<br><strong>Test:</strong> Lateral x-ray: prominent posteriosuperior calcaneal process. The ossification is in the most proximal extent of the insertion of the tendon or as a spur off the superior portion of the calcaneus.Haglund's syndrome is a triad of insertional tendinopathy of the Achilles tendon, retrocalcaneal bursitis, and Haglund's deformity.</p>",
"</dd>",
"<dt><a href='#Section18'>Tendinopathy of the main body of the Achilles tendon</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with retrocalcaneal bursitis.Pain and swelling is localised around the tendon.",
"<br><strong>Test:</strong> Ultrasound: most commonly focal or diffuse thickening of the Achilles tendon with focal hypoechoic areas.MRI: features include morphological findings of a fusiform tendon shape, anteroposterior tendon thickening, and convex bulging of the anterior tendon margin. Areas of increased signal within the tendon on T2-weighted sequences are thought to represent more severe areas of collagen disruption and partial tearing.</p>",
"</dd>",
"<dt><a href='#Section19'>Sever's lesion</a></dt>",
"<dd id='Section19'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with retrocalcaneal bursitis.Pain at the heel, which frequently occurs before or during the peak growth spurt.",
"<br><strong>Test:</strong> Lateral x-ray of the ankle: may show avulsion of the calcaneal apophysis. Can be normal despite significant apophysitis.</p>",
"</dd>",
"<dt><a href='#Section20'>Pronator syndrome</a></dt>",
"<dd id='Section20'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with olecranon bursitis.Anterior elbow pain or proximal volar forearm pain. May occur with repetitive pronation and gripping activities.Tinel's sign over the anterior cubital fossa may be present.Sensory deficits in the radial three and a half digits of the hand on the affected side may be present.",
"<br><strong>Test:</strong> Electromyography: can help to delineate the severity of damage to the median nerve.</p>",
"</dd>",
"<dt><a href='#Section21'>Lateral epicondylitis (tennis elbow)</a></dt>",
"<dd id='Section21'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with olecranon bursitis.Tenderness to palpation over the origin of the extensor carpi radialis brevis tendon.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section22'>Posterior interosseous nerve syndrome</a></dt>",
"<dd id='Section22'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with olecranon bursitis.Tenderness at the lateral epicondyle and distally at the site of the arcade of Frohse. Often pain reproducible with resisted supination and extension of the middle finger.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section23'>Medial epicondylitis (golfer's elbow)</a></dt>",
"<dd id='Section23'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with olecranon bursitis.Tenderness to palpation just anterior to the medial epicondyle.Resisted wrist flexion and forearm pronation while the patient's elbow is in extension reproduces symptoms.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section24'>Ulnar collateral ligament injury</a></dt>",
"<dd id='Section24'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with olecranon bursitis.Valgus stress of the elbow reproduces the symptoms.",
"<br><strong>Test:</strong> MRI and CT arthrography are both 100% sensitive for diagnosing complete tears.</p>",
"</dd>",
"<dt><a href='#Section25'>Cubital tunnel syndrome</a></dt>",
"<dd id='Section25'>",
"<p><strong>Sign & Symptoms:</strong> May be confused with olecranon bursitis.Flexion at the elbow may reproduce or exacerbate symptoms. May have tenderness over the ulnar nerve posterior to the medial epicondyle. Tinel's sign is often positive in this location.",
"<br><strong>Test:</strong> X-ray of elbow: can detect osteophytes in the cubital tunnel.EMG may help to localise the lesion.</p>",
"</dd>",
"<dt><a href='#Section26'>Posterolateral elbow instability</a></dt>",
"<dd id='Section26'>",
"<p><strong>Sign & Symptoms:</strong> Lateral pivot shift test evaluates the lateral collateral ligament complex. Patient lies down and arm is internally rotated and supinated; the elbow is flexed as axial and valgus pressure is applied. Very uncomfortable in an awake patient.",
"<br><strong>Test:</strong> X-ray elbow: may show fractures, loose bodies, or osteochondritis dessicans.MRI may reveal injury to the lateral collateral ligament complex.</p>",
"</dd>",
"</dl>"].join("\n");