content=["<dl>",
"<dt><a href='#Section0'>Osteoarthritis (OA)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> OA of the first carpometacarpal joint may be associated with CTS, and CTS must be excluded as the two commonly co-exist.Painful, stiff thumb joint, often worse in the evening. Tenderness and crepitus on examination.",
"<br><strong>Test:</strong> Diagnosis is clinical.EMG will be normal (unless CTS co-exists).</p>",
"</dd>",
"<dt><a href='#Section1'>Stroke, acute</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Often there is sensory and motor loss in a cortical-type pattern (i.e., whole hand or limb, worse distally) or spinal segmental pattern. Ipsilateral face and/or leg may also be affected.",
"<br><strong>Test:</strong> EMG studies show a completely normal peripheral nervous system.MRI or CT scan may show abnormalities in CNS (brain or spinal cord).</p>",
"</dd>",
"<dt><a href='#Section2'>C6 radiculopathy</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Sudden onset of severe unilateral neck pain radiating to shoulder/arm/scapula. Associated with weakness (mainly shoulder movements and elbow flexion) and numbness predominantly of the dorsal aspect of first and second fingers and lateral aspect of forearm. Decreased or absent biceps and brachioradialis reflexes.",
"<br><strong>Test:</strong> EMG will show normal median nerve studies (including sensory responses to first and second fingers) and lateral antebrachial cut nerve studies.On EMG needle examination there will be denervation in C6 paraspinal muscles and C6 innervated arm/shoulder muscles.MRI of cervical spine will show abnormality such as a herniated disc or osteophyte impinging on the C6 nerve root (CT will be similar except not as sensitive).</p>",
"</dd>",
"<dt><a href='#Section3'>C7 radiculopathy</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Sudden onset of severe unilateral neck pain radiating to shoulder/arm/scapula. Associated with weakness (mainly elbow, wrist, and finger extensors) and numbness predominantly of dorsal aspect of third finger. Decreased or absent triceps reflex.",
"<br><strong>Test:</strong> EMG will show normal median nerve studies (including sensory responses to third finger).On EMG needle examination there will be denervation in C7 paraspinal muscles and C7 innervated arm/shoulder muscles.MRI of cervical spine will show abnormality such as a herniated disc or osteophyte impinging on the C7 nerve root (CT will be similar except not as sensitive).</p>",
"</dd>",
"<dt><a href='#Section4'>Ulnar neuropathy</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Sensory symptoms are on the medial aspect of the hand, distal forearm, and fourth and fifth fingers. Abduction of the first dorsal interosseous and fifth abductor digiti minimi is weak. There is no weakness of the thumb. More commonly it is the non-dominant hand that is affected.",
"<br><strong>Test:</strong> EMG will show normal median nerve studies and abnormalities in the ulnar nerve, most probably across the elbow region.</p>",
"</dd>",
"<dt><a href='#Section5'>Amyotrophic lateral sclerosis/motor neuron disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Muscle weakness and atrophy is widespread, progressive, and involves more than just median nerve-innervated muscles. Fasciculations are usually prominent. There may be bulbar symptoms. There should be no sensory and no bowel/bladder complaints.",
"<br><strong>Test:</strong> EMG shows normal sensory nerves. Motor nerve studies and needle EMG shows widespread acute or chronic denervation even in clinically normal muscles and very proximal muscles (e.g., tongue, paraspinals).</p>",
"</dd>",
"<dt><a href='#Section6'>De Quervain's tenosynovitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Pain on movement of thumb and/or wrist; commonly occurs in both wrists and worsens on heavy lifting.Hardening and thickening of the radial styloid may be indicative.",
"<br><strong>Test:</strong> EMG will be normal (unless CTS co-exists). Degenerative or inflammatory joint conditions may be seen on plain x-ray or CT scans.</p>",
"</dd>",
"<dt><a href='#Section7'>Lateral epicondylitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Pain in the lateral elbow and lateral forearm, due to over-use (e.g., tennis). The patient is tender around the lateral epicondyle.May be associated with CTS.",
"<br><strong>Test:</strong> Typically clinical diagnosis; MRI may be confirmatory of extensor carpi radialis brevis degeneration.EMG will be normal (unless CTS co-exists).</p>",
"</dd>",
"<dt><a href='#Section8'>Rotator cuff tendonitis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Pain associated with arm movement, especially reaching; pain in shoulder at night.Tenderness on palpation around the shoulder.May be associated with CTS.",
"<br><strong>Test:</strong> MRI may demonstrate inflammation and exclude a tear in the rotator cuff.EMG will be normal (unless CTS co-exists).</p>",
"</dd>",
"<dt><a href='#Section9'>Polyneuropathy</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Classically patients complain of symmetrical stocking and glove loss of sensation (worse in the feet) with or without mild weakness distally. Distal reflexes are usually reduced or absent.However, there are many forms of polyneuropathy that do not follow this pattern and can present asymmetrically, affecting hands more than feet or motor more than sensory.Polyneuropathy seems to worsen pre-existing entrapment neuropathies (CTS in particular), and so polyneuropathy patients can present purely with CTS symptoms.",
"<br><strong>Test:</strong> EMG shows widespread symmetrical, length-dependent neuropathic changes without focal abnormalities in the median nerve across the wrist segment.Screens for polyneuropathy may show diabetes or excess alcohol use (2 of the most common causes in the developed world).Liver, renal, thyroid, haematological, and metabolic functions are usually also checked, together with vitamin screen (B12 in particular) and protein electrophoresis (myeloma). Depending also on clinical findings, screens for vasculitis, connective tissue disease, and other paraneoplastic conditions may also be obtained.</p>",
"</dd>",
"<dt><a href='#Section10'>Brachial plexopathies</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Most but by no means all have a history of trauma and are unilateral. Usually easily distinguished from CTS by more widespread motor and sensory symptoms and signs beyond median nerve territory.True neurogenic thoracic outlet syndrome causes weakness in a median nerve territory. The sensory loss, however, is in the medial forearm, hand, and fingers.",
"<br><strong>Test:</strong> EMG shows widespread neuropathy in a truncal, cordal, or mixed pattern.MRI may show increased signal intensity in parts of the plexus and in denervated muscles. The cervical spine and cord is usually normal.</p>",
"</dd>",
"<dt><a href='#Section11'>Proximal median neuropathies</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Numbness extends across the thenar eminence (palmar branch), and weakness includes forearm pronation (pronator teres) and wrist flexion (flexor carpi radialis). Usually unilateral.",
"<br><strong>Test:</strong> EMG shows neuropathic changes in the palmar branch of the median nerve and in the pronator teres and flexor carpi radialis. There is no focal slowing in the median nerve across the carpal tunnel.</p>",
"</dd>",
"<dt><a href='#Section12'>Multiple sclerosis (MS)</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> In MS the sensory/motor loss may vary over time and place. Distinguishing features, if present, may include optic neuritis, constitutional symptoms, and neurogenic symptoms (bowel/bladder).",
"<br><strong>Test:</strong> EMG studies show a normal peripheral nervous system. MRI or CT scan may show abnormalities in CNS (brain or spinal cord).</p>",
"</dd>",
"</dl>"].join("\n");