content=["<dl>",
"<dt><a href='#Section0'>Refractive error</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Vision improves to normal with a correct spectacle prescription.",
"<br><strong>Test:</strong> Testing of vision with a pinhole will help indicate whether a change in glasses will improve vision without surgery.</p>",
"</dd>",
"<dt><a href='#Section1'>Dry eye</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May be an abnormal-appearing tear film.",
"<br><strong>Test:</strong> Using a drop of fluorescein and calculating the tear break-up time provides a guide to the degree of stability of the pre-ocular tear film and the likelihood of dry eye. Results with dry eye are likely to be abnormal (&lt;7 seconds).</p>",
"</dd>",
"<dt><a href='#Section2'>Glaucoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Possible decrease in peripheral vision.",
"<br><strong>Test:</strong> Intra-ocular pressure measurement may reveal increased pressure.Visual field testing may reveal field defects.A large cup-to-disc ratio on ophthalmoscopy.</p>",
"</dd>",
"<dt><a href='#Section3'>Epiretinal membrane</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Distorted or wavy vision.",
"<br><strong>Test:</strong> Fundus examination: evidence of epiretinal membrane or puckering of the macula.</p>",
"</dd>",
"<dt><a href='#Section4'>Macular oedema</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Blurred or distorted vision.",
"<br><strong>Test:</strong> Fundus examination: evidence of oedema.</p>",
"</dd>",
"<dt><a href='#Section5'>Retinal detachment</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Flashes of light and numerous little floaters. This may precede a 'curtain' coming over the vision. The patient should be checked for an afferent pupillary defect.",
"<br><strong>Test:</strong> Fundus examination: evidence of tears, vitreous haemorrhage, or detachment.</p>",
"</dd>",
"<dt><a href='#Section6'>Optic neuritis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Decreased or patchy vision in one eye, pain on eye movement, or decreased colour vision.Often associated with a diagnosis of multiple sclerosis.",
"<br><strong>Test:</strong> MRI is the most important test to evaluate the optic nerve and to look for any evidence of white matter changes in the brain, especially if the fundus appears normal on physical examination.Defects on visual acuity and colour vision testing.</p>",
"</dd>",
"<dt><a href='#Section7'>Vitreous haemorrhage</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> May be a history of trauma or poorly controlled diabetes mellitus.A sudden decrease in vision or large patchy areas of blurry vision.",
"<br><strong>Test:</strong> Visual acuity reduced on testing.On dilated fundus examination, there may be evidence of blood in the vitreous.</p>",
"</dd>",
"<dt><a href='#Section8'>Age-related macular degeneration</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Wavy vision or a central area of vision that is blurry.",
"<br><strong>Test:</strong> Fundus examination: may be signs of wet or dry macular degeneration, such as drusen (retinal metabolic by-products that are normally removed) or sub-retinal fluid.</p>",
"</dd>",
"<dt><a href='#Section9'>Infectious or inflammatory causes of decrease in visual acuity</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms and signs are specific to each individual diagnosis.A complete examination should be performed to find any possible underlying cause of vision loss.",
"<br><strong>Test:</strong> Fundus examination is required. Other investigations depend on the symptoms and signs detected and the suspected diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");