content=["<dl>",
"<dt><a href='#Section0'>Cerebral aneurysm</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Aneurysmal haemorrhage typically presents with sudden-onset severe headache.",
"<br><strong>Test:</strong> CT head distinguishes subarachnoid blood from intracerebral haemorrhage. However, both cerebral aneurysms and AVMs may cause both types of haemorrhage.MRI and/or angiogram distinguish the underlying pathology.</p>",
"</dd>",
"<dt><a href='#Section1'>Cavernous haemangioma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Most frequently present with seizures. haemorrhages tend to be small and their effects depend on their location. They are rarely the source of significant intracerebral haemorrhages.",
"<br><strong>Test:</strong> MRI distinguishes from AVM unless haematoma obliterates the underlying lesion.The 'popcorn' MRI appearance of cavernous malformations is pathognomonic.</p>",
"</dd>",
"<dt><a href='#Section2'>Dural arteriovenous fistula</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Frequently cause pulsatile tinnitus, and a bruit can often be heard over the fistula. AV fistulas tend to present with symptoms of raised intracranial pressure secondary to increased cerebral venous pressure such as headaches and visual impairment. Haemorrhage is less common.",
"<br><strong>Test:</strong> Direct visualisation of the fistula on MRI and angiogram.</p>",
"</dd>",
"<dt><a href='#Section3'>Hypertensive intracerebral haemorrhage</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Known hx of hypertension.",
"<br><strong>Test:</strong> Cerebral angiography excludes AVM.</p>",
"</dd>",
"<dt><a href='#Section4'>Developmental venous anomaly</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs/symptoms.",
"<br><strong>Test:</strong> MRI and cerebral angiography can differentiate this from an AVM.</p>",
"</dd>",
"<dt><a href='#Section5'>Intracerebral haemorrhage from drug abuse</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Hx of drug use (cocaine, amphetamines, ecstasy) immediately before onset of symptoms.",
"<br><strong>Test:</strong> May or may not be associated with an underlying AVM.Cerebral angiography is recommended to exclude an underlying lesion.</p>",
"</dd>",
"<dt><a href='#Section6'>Intracerebral haemorrhage from anticoagulation</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Hx of anticoagulant therapy. Excessive cutaneous bruising and ecchymoses may suggest over-anticoagulation. Vascular lesions cannot be completely excluded simply because of hx of anticoagulant therapy.",
"<br><strong>Test:</strong> Coagulation profile should be sought.Cerebral angiography may be required to exclude an underlying AVM (e.g., patients who are over-anticoagulated may still bleed from an unrecognised AVM).</p>",
"</dd>",
"<dt><a href='#Section7'>Amyloid angiopathy</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Older patients. Hx of cognitive decline or seizures.",
"<br><strong>Test:</strong> No specific tests are available to diagnose amyloid angiopathy, which is usually a diagnosis of exclusion. On CT imaging, lobar haemorrhages with superficial location and cortical involvement, with or without local extension to the subarachnoid and intraventricular spaces, suggest cerebral amyloid angiopathy-related haemorrhage.</p>",
"</dd>",
"</dl>"].join("\n");