content=["<dl>",
"<dt><a href='#Section0'>Arteriovenous malformation</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Subacute presentation.Presents more often with seizures.",
"<br><strong>Test:</strong> Diagnostic cerebral angiography and/or MRI of the brain will show an arteriovenous malformation.</p>",
"</dd>",
"<dt><a href='#Section1'>Hypertensive intra-cerebral haemorrhage</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Age &gt;55 years.Hx of hypertension.Headache with focal neurological deficit.",
"<br><strong>Test:</strong> Diagnostic cerebral angiography will be normal.CT or MRI of the brain will show a focal haematoma more typical for a hypertensive haemorrhage.</p>",
"</dd>",
"<dt><a href='#Section2'>Cerebral venous sinus thrombosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Middle-aged woman.Subacute presentation.May have known hypercoagulable state.Papilloedema seen on examination.",
"<br><strong>Test:</strong> Diagnostic cerebral angiography will show slow arteriovenous transit if there is venous hypertension, and a flow defect in a major sinus.Pattern of haemorrhage on CT or MRI will be adjacent to cortical vein or sinus.</p>",
"</dd>",
"<dt><a href='#Section3'>Traumatic subarachnoid haemorrhage</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Older patient with a fall.Headache usually less severe.",
"<br><strong>Test:</strong> CT or MRI will show haemorrhage focused along the bony contour, sometimes with an associated skull fracture.</p>",
"</dd>",
"<dt><a href='#Section4'>Haemorrhagic tumour</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Hx of primary malignancy, particularly lung or renal carcinoma.",
"<br><strong>Test:</strong> CT or MRI may show a mass with surrounding haemorrhage.A thrombosed aneurysm may produce surrounding oedema and haemorrhage mimicking a mass.</p>",
"</dd>",
"</dl>"].join("\n");