content=["<dl>",
"<dt><a href='#Section0'>Spinal muscular atrophy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Several subtypes. Patient is floppy at birth and exhibits progressive weakness. There is no spasticity, but patients may develop contractures.",
"<br><strong>Test:</strong> DNA testing is available for most subtypes.Muscle biopsy shows changes consistent with denervation, but no fibrosis.Muscle enzymes are normal.Electromyography reveals fascicular degeneration, fibrillation, repetitive discharge, excessive polyphasic potentials, but is not necessary for diagnosis.MRI reveals muscle loss in lower extremities, but is primarily a research tool.</p>",
"</dd>",
"<dt><a href='#Section1'>Muscular dystrophy/myopathy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No spasticity, but patients can develop contractures. There are various subtypes, including Duchenne's, Becker's, and limb girdle.Child may be weak at birth or may have apparent normal development until approximately 3 years of age followed by a progressive loss of function and muscle weakness. There may be a positive family history.Examination reveals a positive Gowers' sign with regression of walking ability.Becker's type is less debilitating and manifests later in childhood. Limb girdle type may not present until late teens or 20s.",
"<br><strong>Test:</strong> Muscle biopsy reveals degeneration of cells, reductions in numbers of cells, and inflamed cells. Histochemical testing is possible for specific proteins.Muscle enzymes are elevated.EMG identifies muscle as opposed to nerve disease and nerve conduction studies are normal.DNA testing is available for many but not all subtypes.</p>",
"</dd>",
"<dt><a href='#Section2'>Familial/primary dystonia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Onset of muscular deformity occurs after several years of normal development.Presents with sustained periods of muscle contraction and dystonia but without development of contractures. There may be abrupt and violent movements; patients may even sit on their limbs.Positive family history.",
"<br><strong>Test:</strong> Molecular genetic testing is available.</p>",
"</dd>",
"<dt><a href='#Section3'>Myelodysplasia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Usually non-spastic. Associated spinal defect and a lack of sensation below a relatively specific spinal segment makes diagnosis obvious.",
"<br><strong>Test:</strong> Ultrasound and x-rays may be used to identify spine/spinal cord defects.</p>",
"</dd>",
"<dt><a href='#Section4'>Familial (hereditary) spastic paraparesis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Family history; progressive disease.",
"<br><strong>Test:</strong> Hereditary spastic paraparesis type 4 (SPG4) is the single most common dominantly inherited paraparesis, representing approximately 40% of cases. Genetic consultation may therefore be helpful.</p>",
"</dd>",
"<dt><a href='#Section5'>Spinal stenosis/tethered cord</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Progressive neurological disease with worsening of the underlying neurology.",
"<br><strong>Test:</strong> MRI of spinal canal reveals the abnormality.</p>",
"</dd>",
"<dt><a href='#Section6'>Brain tumour</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Initial development can be normal. Presents acutely with headache, raised intracranial pressure, seizures, and focal neurological deficits.Occasionally coexists with cerebral palsy.",
"<br><strong>Test:</strong> MRI reveals a space-occupying lesion.</p>",
"</dd>",
"</dl>"].join("\n");