content=["<dl>",
"<dt><a href='#Section0'>Syphilis infection</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Ulcers are typically solitary, indurated, and painless.Causes painless inguinal lymphadenopathy, which is usually bilateral.May occur with Haemophilus ducreyi in a mixed infection.More commonly associated with systemic symptoms such as fever and rash. [7]  [12]Condyloma latum is accompanied by a rash.",
"<br><strong>Test:</strong> RPR test is positive.RPR test is non-specific and must be confirmed by serology for Treponema pallidum.</p>",
"</dd>",
"<dt><a href='#Section1'>HSV infection</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Lesions form vesicles.Ulcers are shallower than chancroid lesions with a clean base.Lymphadenopathy is usually bilateral and not fluctuant.May occur with H ducreyi in a mixed infection.More commonly associated with systemic symptoms such as fever, headache, and malaise. [5]  [7]  [10]  [12]",
"<br><strong>Test:</strong> Herpes DNA detected by PCR, positive herpes culture, or positive Tzanck smear of lesion biopsy.View image</p>",
"</dd>",
"<dt><a href='#Section2'>Lymphogranuloma venereum</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Tender inguinal lymphadenopathy without associated genital ulcerations.Lesions, if present, are painless. [12]  [48]",
"<br><strong>Test:</strong> Culture or PCR from bubo aspirate positive for Chlamydia trachomatis.</p>",
"</dd>",
"<dt><a href='#Section3'>Granuloma inguinale</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Genital ulcers are painless. [12]  [15]Lymphadenitis is unusual.",
"<br><strong>Test:</strong> Ulcer scraping or biopsy positive for Klebsiella granulomatis (also known as Calymmatobacterium granulomatis).</p>",
"</dd>",
"<dt><a href='#Section4'>Traumatic ulceration</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of trauma is usually present. [12]Unlikely to cause bubo formation.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section5'>Squamous cell carcinoma of the skin</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> No distinguishing characteristics.",
"<br><strong>Test:</strong> PCR, culture, and serology for infections are negative.Biopsy of the lesion provides definitive diagnosis.</p>",
"</dd>",
"<dt><a href='#Section6'>Behcet's syndrome</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Oral lesions are more common.Systemic symptoms such as fever, arthralgias, uveitis, and abdominal pain are common. [12]",
"<br><strong>Test:</strong> Pathergy test is positive, leading to pustule formation within 48 hours.</p>",
"</dd>",
"<dt><a href='#Section7'>Cutaneous drug reaction</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Recent history of antibiotic use or chemotherapy. [12]",
"<br><strong>Test:</strong> Skin biopsy is diagnostic.</p>",
"</dd>",
"<dt><a href='#Section8'>Crohn's disease</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Patients have predominantly peri-anal lesions.More likely to have systemic symptoms, such as fever, diarrhoea, weight loss, and abdominal pain.Inguinal lymphadenopathy is uncommon. [12]",
"<br><strong>Test:</strong> Colonoscopy and biopsy are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section9'>Gonorrhoea infection</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Not associated with genital ulcers.More commonly associated with systemic symptoms such as fever, rash, and arthritis. [12]",
"<br><strong>Test:</strong> Gram stain-positive for gram-negative diplococci.Culture positive for Neisseria gonorrhoeae.Nucleic acid amplification test positive for N gonorrhoeae. [12]  [48]</p>",
"</dd>",
"<dt><a href='#Section10'>Urinary tract infections in men</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Not associated with genital ulcers or inguinal lymphadenopathy. [12]More likely to have fever and abdominal/flank pain.",
"<br><strong>Test:</strong> Positive urine culture.</p>",
"</dd>",
"<dt><a href='#Section11'>Urinary tract infections in women</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Not associated with genital ulcers or inguinal lymphadenopathy. [12]More likely to have fever and abdominal/flank pain.",
"<br><strong>Test:</strong> Positive urine culture.</p>",
"</dd>",
"</dl>"].join("\n");