content=["<dl>",
"<dt><a href='#Section0'>Hepatocellular carcinoma (HCC)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients generally present with symptoms of advancing cirrhosis, with jaundice, ascites, asterixis, pedal oedema, periumbilical collateral veins, and possibly alcoholic stigmata. There may be a history of variceal bleeding and episodes of hepatic encephalopathy.",
"<br><strong>Test:</strong> The same imaging modalities are used.HCC is the more likely diagnosis if the lesion is peripheral and cirrhotic parenchyma is present, but ultimately it will be pathology that distinguishes between the two tumours.</p>",
"</dd>",
"<dt><a href='#Section1'>Ampullary carcinoma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Presents with many of the same features as cholangiocarcinoma, with jaundice, pruritus, anorexia, weight loss, and a distended, palpable gallbladder.Patients may have diarrhoea, which is not commonly associated with cholangiocarcinoma.",
"<br><strong>Test:</strong> Diagnosis of ampullary lesion is made using ERCP; however, confirmation of malignancy requires histological examination.</p>",
"</dd>",
"<dt><a href='#Section2'>Pancreatic carcinoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> A characteristic feature is significant weight loss. Patients may also experience epigastric or back pain, which is not commonly seen with cholangiocarcinoma.",
"<br><strong>Test:</strong> The same imaging modalities are used. It may be clear from CT or MRI that the tumour is arising from the body of the pancreas, but more difficult to distinguish if the tumour is arising from the head of the pancreas. Ultimately it is the histology that will distinguish between the two tumours.</p>",
"</dd>",
"<dt><a href='#Section3'>Choledocholithiasis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Gallstones in the common bile duct (CBD) can present with signs and symptoms of obstructive jaundice. In addition, the presence of gallstones in the CBD and cystic duct obstruction can mimic Courvoisier's sign (presents with enlarged gallbladder, which would be similar to an obstruction secondary to tumour in the bile duct). Gallstones in the gallbladder can cause no symptoms.",
"<br><strong>Test:</strong> ERCP will definitively diagnose and treat this condition.</p>",
"</dd>",
"<dt><a href='#Section4'>Cholangitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> This typically presents as a triad of fever, RUQ pain, and jaundice.Although a common cause for the infection can be gallstones in the common bile duct, the infection can also be superimposed upon obstruction caused by a tumour.",
"<br><strong>Test:</strong> Clinical diagnosis of a consequence of biliary obstruction regardless of cause.WBC count is elevated and imaging (CT, MRCP, ERCP) demonstrates biliary obstruction.Blood cultures may be positive for aetiological organism.</p>",
"</dd>",
"</dl>"].join("\n");