content=["<dl>",
"<dt><a href='#Section0'>Other infectious diarrhoea</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Many causes of infectious diarrhoea will be impossible to differentiate from cholera, especially in the early stages of disease or mild cases.Bloody diarrhoea is suspicious for Shigella or enterohaemorrhagic Escherichia coli.",
"<br><strong>Test:</strong> Stool culture is the standard, but some techniques (e.g., for Campylobacter) are difficult and not performed in the developing world.PCR for toxins help distinguish enterohaemorrhagic E coli.</p>",
"</dd>",
"<dt><a href='#Section1'>Amoebic dysentery</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Volume of diarrhoea rarely exceeds 1 litre/hour for adults.Bloody diarrhoea common.",
"<br><strong>Test:</strong> Fresh stool microscopy shows amebae ingesting red blood cells.</p>",
"</dd>",
"<dt><a href='#Section2'>Strongyloides</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Rare to have large-volume stool loss.",
"<br><strong>Test:</strong> Stool microscopy for eggs and live parasites requires training and good equipment to detect Strongyloides stercoralis.</p>",
"</dd>",
"<dt><a href='#Section3'>Giardiasis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Giardiasis often causes offensive, yellow, sulphur-scented stools.Rare to have large-volume stool loss.",
"<br><strong>Test:</strong> Stool microscopy for eggs and live parasites requires training and good equipment to detect Giardia.</p>",
"</dd>",
"<dt><a href='#Section4'>VIPoma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Volume of diarrhoea rarely exceeds 1 litre/hour.Chronic history.Much rarer than cholera.",
"<br><strong>Test:</strong> Fasting gut hormone analysis confirms diagnosis.Negative stool culture for cholera.</p>",
"</dd>",
"<dt><a href='#Section5'>Tubulovillous adenoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Volume of diarrhoea rarely exceeds 1 litre/hour.Chronic history of diarrhoea.Much rarer than cholera.",
"<br><strong>Test:</strong> Colonoscopy and biopsy of lesions shows adenoma.Negative stool culture for cholera.</p>",
"</dd>",
"<dt><a href='#Section6'>Food poisoning</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Volume of diarrhoea rarely exceeds 1 litre/hour.",
"<br><strong>Test:</strong> Stool white blood cell count may help differentiate invasive or inflammatory diarrhoea.Stool culture may help isolate specific pathogens.</p>",
"</dd>",
"</dl>"].join("\n");