content=["<dl>",
"<dt><a href='#Section0'>Leukemoid reaction</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features.",
"<br><strong>Test:</strong> High WBC count resolves once underlying condition is treated.</p>",
"</dd>",
"<dt><a href='#Section1'>Benign neutrophilic leukocytosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features.",
"<br><strong>Test:</strong> Fluorescent in situ hybridisation (FISH): negative for BCR-ABL fusion gene.</p>",
"</dd>",
"<dt><a href='#Section2'>Atypical CML</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features.",
"<br><strong>Test:</strong> FISH: negative for BCR-ABL fusion gene.</p>",
"</dd>",
"<dt><a href='#Section3'>Chronic myelomonocytic leukaemia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features.",
"<br><strong>Test:</strong> Bone marrow examination: dysplastic changes in the myeloid lineage.Peripheral blood smear: wide range of immature granulocytes and monocytosis.FISH: negative for the BCR-ABL fusion gene. May be positive for PDG-FR beta fusion gene. [13]</p>",
"</dd>",
"<dt><a href='#Section4'>Essential thrombocytosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> More indolent clinical course.Unlikely to transform into acute leukaemias.",
"<br><strong>Test:</strong> Bone marrow examination: megakaryocytic hyperplasia.FISH: negative for BCR-ABL, positive for JAK2 mutation. [14]FBC: high platelet count.</p>",
"</dd>",
"<dt><a href='#Section5'>Ph+ acute lymphoblastic leukaemia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Much more rapid disease course.Patients often present with anaemia and thrombocytopenia. B symptoms are common (e.g., fever, night sweats, and weight loss).",
"<br><strong>Test:</strong> Peripheral blood smear-blasts.Bone marrow examination and flow cytometry should show predominance of immature B lymphocytes.FISH: positive for 190-kDa BCR-ABL fusion. [1]</p>",
"</dd>",
"</dl>"].join("\n");