content=["<dl>",
"<dt><a href='#Section0'>Non-cocaine sympathomimetic overdose</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to distinguish clinically from cocaine poisoning, but the management is similar.The onset of effects is slower and the duration of action longer, especially when ingested orally.Dysrhythmias due to sodium channel effects do not occur. [9]",
"<br><strong>Test:</strong> Cocaine urine assay is negative.Urine immunoassay may identify presence of phencyclidine or amfetamines.Gas chromatography-mass spectrometry can identify many individual sympathomimetics.</p>",
"</dd>",
"<dt><a href='#Section1'>Alcohol, sedative or hypnotic withdrawal</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Social history may elicit the diagnosis.Alcohol withdrawal becomes more severe as time passes, whereas cocaine-poisoned patients improve as drug is metabolised.",
"<br><strong>Test:</strong> The CAGE questionnaire [18]  or Michigan Alcoholism Screening Test (MAST) [19]  may be helpful in identifying alcohol dependence.A conscious patient with an ethanol concentration &gt;21.7 or 43.4 mmol/L (&gt;100 or 200 mg/dL) suggests tolerance, but does not establish the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Anticholinergic syndrome</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Anticholinergic toxicity can present with tachycardia, hyperthermia, mydriasis, and agitation.Skin is dry, not diaphoretic; bowel sounds are decreased or absent; and urinary retention is present.Treatment is similar to that of cocaine overdose.",
"<br><strong>Test:</strong> Urine drug screen will detect the anticholinergic drug.</p>",
"</dd>",
"<dt><a href='#Section3'>Thyroid storm</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> A history of hyperthyroidism suggests the diagnosis.The onset of symptoms is much more insidious and the duration is much longer.Hypertension is less frequently seen.",
"<br><strong>Test:</strong> Thyroid studies suggest the diagnosis (elevated triiodothyronine, thyroxine, free T4, decreased TSH).</p>",
"</dd>",
"<dt><a href='#Section4'>Phaeochromocytoma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Extremely rare.Usually associated with history of hypertension and attacks are usually accompanied by a headache.Symptoms are longer lasting and recurrent.",
"<br><strong>Test:</strong> Fractionated plasma metanephrine is 97% sensitive and 85% specific for phaeochromocytoma. [20]</p>",
"</dd>",
"<dt><a href='#Section5'>Infection</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> History of exposure to cocaine is absent and a history of infection is usually present.",
"<br><strong>Test:</strong> Symptoms respond to empiric treatment of the infection (e.g. antibiotics).Chest x-ray, urinalysis, or lumbar puncture may reveal the source and cause of the infection.</p>",
"</dd>",
"<dt><a href='#Section6'>Hypoglycaemia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Cannnot be clinically distinguished from cocaine overdose as autonomic (adrenergic) features overlap.",
"<br><strong>Test:</strong> Bedside serum glucose is diagnostic.</p>",
"</dd>",
"</dl>"].join("\n");