content=["<dl>",
"<dt><a href='#Section0'>Tuberculosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms, signs of tuberculosis and of coccidioidomycosis may be similar. For patients with suspected tuberculosis, no residence in or travel to endemic area for coccidioidomycosis is needed for diagnosis.Tuberculosis has an indolent onset and symptoms are unremitting until proper treatment is begun.",
"<br><strong>Test:</strong> Mycobacterial culture of sputum or other sites of clinical involvement will yield positive culture for Mycobacterium tuberculosis.Chest x-ray may show chronic infiltrate, fibrosis, cavities, and retraction, often upper lobe.</p>",
"</dd>",
"<dt><a href='#Section1'>Non-tuberculous pulmonary mycobacterial infections</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No residence in or travel to endemic area for coccidioidomycosis needed for diagnosis.Onset of symptoms may be acute, but often indolent.",
"<br><strong>Test:</strong> Mycobacterial culture of sputum or other sites of clinical involvement will yield positive culture.</p>",
"</dd>",
"<dt><a href='#Section2'>Histoplasmosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Residence in or travel to an area endemic for histoplasmosis (Mississippi and Ohio river valleys).Fifty percent to 90% of patients have self-limited or asymptomatic pulmonary infection not requiring treatment. [23]  Other symptoms include dry cough, chest pain, sweating, fever, and weight loss.",
"<br><strong>Test:</strong> Fungal culture will grow Histoplasma capsulatum.Biopsy shows characteristic organism with fungal stains.Histoplasma urine and serum antigen positivity.Histoplasma antibody assays may be positive. [23]</p>",
"</dd>",
"<dt><a href='#Section3'>Blastomycosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Residence in or travel to an area endemic for blastomycosis (southeastern and south-central states, especially bordering on the Mississippi or Ohio rivers). [24]Symptoms include cough, fever, night sweats, weight loss, chest pain, and dyspnoea.",
"<br><strong>Test:</strong> Culture of sputum or bronchoalveolar lavage fluid.Histopathology of biopsied specimens. [24]</p>",
"</dd>",
"</dl>"].join("\n");