content=["<dl>",
"<dt><a href='#Section0'>Flat warts</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Flesh-coloured, flat-topped, slightly raised papules.Usually multiple and found on extremities or face.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section1'>Palmoplantar warts</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Palmoplantar warts are endophytic and occasionally tender, with scale and black dots on the surface, and commonly found on palms and soles.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section2'>Seborrhoeic keratosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are greyish-brown stuck-on scaly papules with white pseudocysts and a smooth or rough surface.Many are present in the same skin area and persist indefinitely.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section3'>Acquired digital fibrokeratoma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Lesions occur on the digit, and have a firm, smooth surface.There are no tiny black dots on the surface.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section4'>Clavus</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Lesions occur on the digit in the areas of friction and over bony prominences and have a firm, rough surface.There are no tiny black dots on the surface.",
"<br><strong>Test:</strong> Skin biopsy shows hyperkeratosis and parakeratosis with central epidermal atrophy, plus peripheral acanthosis and possible perivascular infiltrates of the upper dermis.</p>",
"</dd>",
"<dt><a href='#Section5'>Callus</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Lesions occur on the digit in the areas of friction and over bony prominences and have a firm, rough surface.There are no tiny black dots on the surface.",
"<br><strong>Test:</strong> Skin biopsy shows hyperkeratosis.</p>",
"</dd>",
"<dt><a href='#Section6'>Squamous cell carcinoma</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Non-healing, enlarging hyperkeratotic papule that becomes inflamed and tender.",
"<br><strong>Test:</strong> Skin biopsy shows parakeratosis, atypical keratinocytes with or without koilocytes.There may be clusters of atypical keratinocytes invading the basement membrane to form small clusters in the papillary or reticular dermis.</p>",
"</dd>",
"<dt><a href='#Section7'>HPV-related Bowen&rsquo;s disease</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Non-healing, enlarging hyperkeratotic papule that becomes inflamed and tender. May occur around the nail apparatus, as well as on other skin sites.",
"<br><strong>Test:</strong> Skin biopsy shows parakeratosis, atypical keratinocytes with or without koilocytes.There may be clusters of atypical keratinocytes invading the basement membrane to form small clusters in the papillary or reticular dermis.</p>",
"</dd>",
"<dt><a href='#Section8'>Lichen planus</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Usually widely spread and pruritic rash.",
"<br><strong>Test:</strong> Skin biopsy shows features characteristic of each lichen planus.</p>",
"</dd>",
"<dt><a href='#Section9'>Epidermal naevus</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Pruritic plaques",
"<br><strong>Test:</strong> Skin biopsy shows features characteristic of each epidermal naevus.</p>",
"</dd>",
"<dt><a href='#Section10'>Melanocytic naevus</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Generally brown or tan in colour.There are no tiny black dots on the surface.",
"<br><strong>Test:</strong> Skin biopsy shows features characteristic of melanocytic naevus.</p>",
"</dd>",
"<dt><a href='#Section11'>Melanoma</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Lesions often have irregular outline, diameter greater than 6 mm, and colour variegation.",
"<br><strong>Test:</strong> Skin biopsy shows features characteristic of melanoma.</p>",
"</dd>",
"<dt><a href='#Section12'>Molluscum contagiosum</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Lesions appear as umbilicated, pearl-like, smooth papules.At least one third develop symptoms of local erythema, swelling, or pruritus.Seen particularly in immunocompromised patients.",
"<br><strong>Test:</strong> Haematoxyllin and eosin staining shows Henderson Patterson bodies, the definitive histological feature of molluscum contagiosum.</p>",
"</dd>",
"<dt><a href='#Section13'>Tuberculosis verrucosa cutis</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Wart-like papule with a subtle inflammatory rim at trauma-prone sites, such as hands and digits, as well as lower extremities in children. Lesions enlarge gradually, often in a serpiginous manner, to form a reddish-brown verrucous plaque. Central areas may become fluctuant with pus and keratinaceous debris. After several years, the plaques may heal spontaneously. [3]",
"<br><strong>Test:</strong> Histology shows acute inflammation in the epidermis, pseudoepitheliomatous hyperplasia, microabcesses in the upper dermis, sparce granulomatous foci, and occasional bacilli. [3]</p>",
"</dd>",
"</dl>"].join("\n");