content=["<dl>",
"<dt><a href='#Section0'>Viral gastroenteritis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Usually insidious onset, accompanied by fever and other constitutional signs and symptoms. Self-limiting. Commonly caused by rotaviruses, noroviruses, and certain adenoviruses.",
"<br><strong>Test:</strong> Viral stool culture: positive for causative organism.</p>",
"</dd>",
"<dt><a href='#Section1'>Bacterial gastroenteritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Usually accompanied by ingestion of spoiled food contaminated with staphylococcus, salmonella, campylobacter, or other bacterial pathogens.",
"<br><strong>Test:</strong> Stool culture and culture of suspected food: positive for causative organism.</p>",
"</dd>",
"<dt><a href='#Section2'>Acute myocardial infarction</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May be difficult to differentiate clinically.History of CAD, presence of cardiac risk factors.",
"<br><strong>Test:</strong> ECG: ischaemic changes.Cardiac enzymes: elevated.</p>",
"</dd>",
"<dt><a href='#Section3'>Epilepsy</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May have known history of seizures.",
"<br><strong>Test:</strong> EEG: epileptiform activity or focal, localising abnormality.</p>",
"</dd>",
"<dt><a href='#Section4'>Cyanide poisoning</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> May be difficult to differentiate clinically (chronic cassava or prunus seed ingestion can cause cyanide toxicity). History of occupational exposure.Cherry-red colour to lips and skin. May rarely smell bitter almonds on breath. Hypotension.",
"<br><strong>Test:</strong> ABG: acidosis, elevated lactate.</p>",
"</dd>",
"<dt><a href='#Section5'>Paracetamol poisoning</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> History of deliberate overdose or chronic ingestion. May cause various degrees of liver injury including fulminant hepatic failure and hepatorenal syndrome.",
"<br><strong>Test:</strong> Serum acetaminophen levels: may be elevated.</p>",
"</dd>",
"</dl>"].join("\n");