content=["<dl>",
"<dt><a href='#Section0'>Hayfever (allergic rhinitis)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Rhinitis occurs in response to exposure to specific allergens.Chronic fluctuating course, according to allergen exposure and seasonal pattern.The presence of sore throat would make a common cold more likely.Other features of atopy suggestive of condition.",
"<br><strong>Test:</strong> Allergen skin patch testing and in vitro specific IgE determination are diagnostic tests.</p>",
"</dd>",
"<dt><a href='#Section1'>Chronic sinusitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms longer than 6 weeks. Usually diagnosed with the aid of radiological studies. Common clinical characteristics of chronic sinusitis include hyposmia or anosmia.More commonly characterised by chronic inflammation than a bacterial infection, especially in adults.",
"<br><strong>Test:</strong> Sinus CT scans are abnormal in sufferers of chronic sinusitis.</p>",
"</dd>",
"<dt><a href='#Section2'>Streptococcal tonsillitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Use of the McIsaac score can help to discriminate; a score of 2 or 3 should lead to obtaining a throat swab. [18]Tender anterior cervical glands, tonsillar swelling or exudates, absence of cough, temperature is greater than 38&deg;C (&gt;100.4&deg;F), and age under 15 years.",
"<br><strong>Test:</strong> A positive throat culture for streptococcus confirms the diagnosis in most cases.</p>",
"</dd>",
"<dt><a href='#Section3'>Acute sinusitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Acute disease often due to an infectious cause.Usually clinically diagnosed and may present with nasal congestion, cough, discoloured nasal mucous, and facial pressure/pain.Facial tenderness is a rare and unreliable sign; however, reproducible pain on percussion of frontal and maxillary sinuses strongly indicates acute bacterial sinusitis.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section4'>Infectious mononucleosis (mono)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Often subclinical in young children.Well-described syndrome with maculopapular rash, fatigability, fever, laryngitis, and malaise.Hepatosplenomegaly common.",
"<br><strong>Test:</strong> Lymphocytosis on FBC.Positive heterophile antibody test usually diagnostic; may be false-negative in early stages of the illness.EBV antibody titres can help differentiate acute and chronic forms of EBV infection.</p>",
"</dd>",
"<dt><a href='#Section5'>Influenza</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Fever, headache, muscle aches, and malaise are predominant features.Symptoms more severe than URTI.Fever greater than 38&deg;C (&gt;100.4&deg;F) suggestive in adults.May lead to prolonged period of absenteeism/inactivity.Can lead to severe complications in elderly and immunocompromised.",
"<br><strong>Test:</strong> Viral culture, direct immunofluorescent-antibody staining, and reverse transcriptase-PCR are recognised tests.</p>",
"</dd>",
"<dt><a href='#Section6'>H1N1 influenza ('swine fl')</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Causes clinical features typical of influenza (fever, cough, sore throat, muscle aches, malaise), usually in a community where H1N1 swine influenza is circulating or in someone who has travelled to such a community.",
"<br><strong>Test:</strong> Viral culture, direct immunofluorescent-antibody staining, and reverse transcriptase-PCR will detect influenza virus. The most definitive means of identifying H1N1 influenza A virus is specific real-time reverse transcriptase-PCR testing that can be performed at specialist laboratories. It can be done directly on patient specimens (e.g., nasopharyngeal swab or aspirate, nasal wash and swab, or tracheal aspirate) or on cultured virus from patient specimens.</p>",
"</dd>",
"<dt><a href='#Section7'>Pertussis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Initial upper respiratory symptoms may give way several weeks later to an increased severity of cough, with paroxysmal coughing first increasing in frequency, then remaining constant for several weeks. There may be inspiratory whooping and post-tussive vomiting. Inspiratory stridor may be heard on auscultation.",
"<br><strong>Test:</strong> Evidence of Bordetella pertussis from nasopharyngal swabs or aspirates.</p>",
"</dd>",
"<dt><a href='#Section8'>Diphtheria</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> May be a history of exposure or travel to endemic area.Sore throat and low-grade fever (usually &lt;39&deg;C [&lt;102&deg;F]) followed by dysphagia, dysphonia, dyspnoea, and a croupy cough if there is extension of the pseudomembrane and/or involvement of the posterior pharyngeal and laryngeal nerves.Grey-brown pseudomembrane may form over the tonsils and/or pharynx after 2 to 5 days of sore throat. Without treatment, it can thicken and spread. Neck swelling and lymphadenopathy may cause characteristic bull-neck appearance.",
"<br><strong>Test:</strong> Microscopy and cultures from nose and throat swabs, taken when possible from beneath the pseudomembrane, positive for Corynebacterium diphtheriae.</p>",
"</dd>",
"<dt><a href='#Section9'>Meningococcal disease</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> May present with non-specific respiratory signs/symptoms.As the illness develops, thirst, respiratory distress, a petechial rash, peripheral vasoconstriction, altered consciousness, photophobia, hypotonia, neck stiffness, seizures, and tachycardia may be present.In infants, a bulging fontanelle and a characteristic high-pitched cry may occur.A positive Kernig's or Brudzinski's sign indicates meningeal inflammation and is suggestive of meningitis; is present only in a minority of patients.",
"<br><strong>Test:</strong> Isolation of Neisseria meningitidis from a sterile body site (blood, CSF, joint, pleural fluid, pericardial fluid, or aspiration or biopsy of a purpuric lesion) is the definitive test for diagnosis of invasive meningococcal infections.</p>",
"</dd>",
"<dt><a href='#Section10'>HIV seroconversion illness</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Between 50% and 90% of HIV-infected individuals develop an acute clinical illness that typically occurs 2 to 4 weeks after exposure to HIV.Often recognised in retrospect since features are non-specific.Onset is acute and lasts up to 2 weeks.Common symptoms are a glandular fever-type illness with fever, malaise, myalgia, pharyngitis, headaches, diarrhoea, neuralgia or neuropathy, lymphadenopathy, maculopapular rash, and mucocutaneous ulceration.",
"<br><strong>Test:</strong> Humoral immunodeficiency shows low immunoglobulin levels. Cellular immunodeficiency indicates T-cell dysfunction and/or HIV.</p>",
"</dd>",
"</dl>"].join("\n");