content=["<dl>",
"<dt><a href='#Section0'>shock</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Shock can be clinically indistinguishable from abdominal compartment syndrome (ACS) and significant overlap exists, since patients develop ACS from excess fluid resuscitation given to treat hypovolaemic or septic shock.",
"<br><strong>Test:</strong> Intra-abdominal pressure (IAP) is normal.</p>",
"</dd>",
"<dt><a href='#Section1'>acute tubular necrosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Acute tubular necrosis is clinically indistinguishable from ACS, although may have a history of exposure to nephrotoxic agents.This condition can also occur as a complication of ACS.",
"<br><strong>Test:</strong> The IAP is normal.Urinalysis may show granular casts.Renal biopsy shows characteristic features.</p>",
"</dd>",
"<dt><a href='#Section2'>acute renal failure</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Renal failure is clinically indistinguishable from ACS.The condition presents with oliguria in many of the same patient populations that are at increased risk for ACS.It can also occur as a complication of ACS.",
"<br><strong>Test:</strong> The IAP is normal.Renal ultrasound shows dilated renal calyces (suggesting obstruction) or reduced corticomedullary differentiation.Renal biopsy reveals intra-renal causes.</p>",
"</dd>",
"<dt><a href='#Section3'>adult respiratory distress syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients have cough with expectoration of frothy pulmonary oedema.Basilar or diffuse rales are present on chest auscultation.Patients generally require higher levels of oxygen and/or PEEP to maintain oxygen saturation &gt;90% than patients with ACS.",
"<br><strong>Test:</strong> IAP is normal or mildly elevated (due to pressure transmission from torso to abdomen).Chest x-ray shows contusion and new bi-lateral interstitial infiltrates suggestive of pulmonary oedema.</p>",
"</dd>",
"</dl>"].join("\n");