content=["<dl>",
"<dt><a href='#Section0'>Severe/moderate traumatic brain injury</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Observed loss of consciousness lasting &gt;30 minutes, post-traumatic amnesia lasting &gt;24 hours. [4]  [3]  Other differentiating features may include cervical spine injury, skull fracture, and intra-cranial bleed.Glasgow Coma Scale score 12 or under. [4]  [3]",
"<br><strong>Test:</strong> Positive CT/MRI results can be used in the semi-acute phase, especially in cases of worsening symptoms, to rule out structural damage, including skull fracture and other intra-cranial abnormalities (mid-line shift, haemorrhaging).</p>",
"</dd>",
"<dt><a href='#Section1'>Depression</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Physical symptoms may be similar, but there is no precipitating head injury.Can be confirmed on history taking. [4]  Screening questionnaires can be used.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section2'>General trauma or injury to the body not involving the head</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Physical symptoms may be similar, but there is no precipitating head injury.Can be confirmed on history taking and physical examination. [4]",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section3'>Headache disorders</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> These can include trauma-induced migraines. Although similar in symptomatology, headache disorders are a different disorder in pre-morbid cases, and in trauma-induced cases require the inclusion of a neurologist or physiatrist for proper management.Can be confirmed on history taking. [4]",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"</dl>"].join("\n");