content=["<dl>",
"<dt><a href='#Section0'>Addison's disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients with Addison's disease tend to have symptoms of muscle weakness and fatigue. CAH does not exhibit these signs and symptoms.",
"<br><strong>Test:</strong> In Addison's disease, an ACTH stimulation test will show a poor or absent cortisol response. Other adrenal hormones also do not exhibit a stimulated response.</p>",
"</dd>",
"<dt><a href='#Section1'>Gender identity disorder</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients with gender identity disorder have confusion and anxiety about their gender and tend to feel they were assigned the wrong sex. Also, cross-dressing is common. These symptoms are not associated with CAH.",
"<br><strong>Test:</strong> Laboratory tests tend to be normal in gender identity disorder, whereas CAH shows abnormal response to the ACTH stimulation test.</p>",
"</dd>",
"<dt><a href='#Section2'>Familial glucocorticoid syndrome</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients with familial glucocorticoid syndrome may present with pallor, sweating, palpitations, hunger, visual changes, or mental status changes, symptoms not shared by CAH.",
"<br><strong>Test:</strong> Patients with familial glucocorticoid syndrome have normal blood chemistry, but classical CAH shows a hyponatraemic, hyperkalaemic, metabolic acidosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Renal salt-wasting</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Renal salt-wasting is associated with a history of diuretic use and/or uncontrolled diabetes mellitus, not typically shared by patients with CAH.",
"<br><strong>Test:</strong> In renal salt-wasting, 17-hydroxyprogesterone is normal and in CAH this is high.</p>",
"</dd>",
"</dl>"].join("\n");