content=["<dl>",
"<dt><a href='#Section0'>Conjunctivitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with a red eye and discharge but without significant pain, photophobia, or changes in vision.No history of trauma.",
"<br><strong>Test:</strong> No definitive test but generally lacks fluorescein uptake on eye examination.</p>",
"</dd>",
"<dt><a href='#Section1'>Corneal laceration with globe perforation</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Full-thickness lacerations result in a ruptured globe that allows aqueous humour to escape the anterior chamber. The cornea may appear flattened and the pupil may become asymmetric.",
"<br><strong>Test:</strong> Fluorescein applied to a full-thickness lesion changes colour as it is diluted with aqueous humour and streams away from the wound.</p>",
"</dd>",
"<dt><a href='#Section2'>Corneal ulceration and ulcerative keratitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Typically develop over days and have signs of corneal infiltration on examination. Corneal infiltration is a white hazy infiltrate underlying a corneal defect and spreading to adjacent stroma.View image A dendritic pattern may be seen with herpes infection.",
"<br><strong>Test:</strong> An ophthalmologist can scrape the cornea with a sterile spatula or blade and send the sample for smear, cultures, and sensitivity. Gram and Giemsa staining identifies the micro-organisms.</p>",
"</dd>",
"<dt><a href='#Section3'>Acute angle-closure glaucoma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Abrupt onset without antecedent trauma, often with severe headache, nausea, and vomiting.Patients typically report alterations in vision with haloes around lights. The eye may have vascular congestion, corneal oedema, and a dilated, unresponsive pupil. Visual acuity is often reduced.",
"<br><strong>Test:</strong> Tonometry: confirms elevated intraocular pressure; &gt;21 mmHg is abnormal.Gonioscopy: trabecular meshwork is not visible, as it is obscured by the peripheral iris.Slit lamp examination: reveals a shallow anterior chamber and a large optic cup, narrowing of the neuroretinal rim, splinter haemorrhage, and nerve fibre loss.</p>",
"</dd>",
"<dt><a href='#Section4'>Anterior uveitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Similar clinical presentation but with no hx of trauma. Pain is usually dull.",
"<br><strong>Test:</strong> Slit lamp examination may reveal signs of protein and WBCs in the anterior chamber (cells and flare), hypopyon or a fluid level of pus, and anterior synechia where the iris adheres to the cornea.FBC, CRP, and ESR are raised as non-specific markers of inflammation.Serum ACE is elevated in patients with sarcoidosis. If the patient is taking angiotensin-converting enzyme (ACE) inhibitors, medication lowers ACE levels.ANAs are positive in patients with juvenile idiopathic arthritis.</p>",
"</dd>",
"<dt><a href='#Section5'>UV keratitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients describe some form of excessive UV exposure such as welding, significant sun exposure (solar eclipses or snow fields), or use of suntanning beds.Onset of symptoms is typically 6 to 12 hours after exposure, and the eye appears injected.",
"<br><strong>Test:</strong> Fluorescein staining reveals diffuse superficial punctate epithelial irregularities referred to as superficial punctate keratitis.</p>",
"</dd>",
"<dt><a href='#Section6'>Acanthamoeba keratitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> In developed countries, almost always occurs in wearers of contact lenses, though it can also be associated with polluted water or other factors. Often associated with difficulty removing a contact lens.Causes severe pain that is often discordant with the ocular findings.Frequently associated with a ring-shaped infiltrate surrounding a central ulcer.",
"<br><strong>Test:</strong> Definitive diagnosis is by Giemsa stain and culture of a corneal scraping, or identification of Acanthamoeba DNA with polymerase chain reaction.</p>",
"</dd>",
"</dl>"].join("\n");