content=["<dl>",
"<dt><a href='#Section0'>Acute coronary syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Severe chest pain-associated dyspnoea, nausea, and diaphoresis. The chest pain may be intermittent and precipitated by exertion.Risk factors for cardiovascular disease (e.g., FHx, hypertension, hyperlipidaemia, diabetes, and smoking) are usually present.",
"<br><strong>Test:</strong> ECG may reveal ST elevation and cardiac enzymes may be elevated. [16]</p>",
"</dd>",
"<dt><a href='#Section1'>Pleuritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Associated dyspnoea and shortness of breath.Decreased breath sounds on auscultation and dullness on percussion.",
"<br><strong>Test:</strong> Chest x-ray may show an effusion.</p>",
"</dd>",
"<dt><a href='#Section2'>Pulmonary embolism</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Risk factors for thromboembolic disease (e.g., FHx, smoking, OCP use, prolonged immobilisation, or limb trauma).Associated dyspnoea. Haemoptysis may be present. Physical examination may reveal signs of right ventricular dysfunction (e.g., distended neck veins, systolic murmur over left-lower sternal edge, loud pulmonary component of S2). [17]",
"<br><strong>Test:</strong> Elevated d-dimer.CT angiogram showing arterial clot or perfusion/ventilation scan showing mismatch.</p>",
"</dd>",
"<dt><a href='#Section3'>Rib fracture</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hx of trauma and tenderness over the rib.",
"<br><strong>Test:</strong> Rib fracture visible on rib-view plain x-rays.</p>",
"</dd>",
"<dt><a href='#Section4'>Sternal or clavicular fracture</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Hx of trauma, tenderness over sternum or clavicle.",
"<br><strong>Test:</strong> Clavicular or sternal fracture visible on plain x-rays.</p>",
"</dd>",
"<dt><a href='#Section5'>Pneumothorax</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Hx of sudden-onset dyspnoea and pleuritic chest pain.Decreased chest-wall movement, hyperresonance to percussion, and decreased or absent breath sounds. [18]",
"<br><strong>Test:</strong> Chest x-ray shows a thin, visceral pleural line displaced from the chest wall. [18]</p>",
"</dd>",
"<dt><a href='#Section6'>Gastro-oesophageal reflux disease</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms of heartburn and regurgitation.",
"<br><strong>Test:</strong> A therapeutic trial of antacid or proton pump inhibitors may produce improvement.Twenty-four-hour ambulatory pH monitoring may reveal intra-oesophageal pH &lt;4 more than 4% of the time. [19]</p>",
"</dd>",
"<dt><a href='#Section7'>Panic disorder</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Sudden-onset anxiety, feeling faint, and palpitations. [20]Recurrent, discrete period of intense fear/discomfort. [21]",
"<br><strong>Test:</strong> Clinical diagnosis requiring formal psychiatric assessment.</p>",
"</dd>",
"<dt><a href='#Section8'>Generalised anxiety disorder</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Hx of worry present most of the time for &gt;6 months.May have a FHx of anxiety. [22]",
"<br><strong>Test:</strong> Clinical diagnosis requiring formal psychiatric assessment.</p>",
"</dd>",
"<dt><a href='#Section9'>Depression</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Lack of interest in activities and depressed affect for &gt;2 months, insomnia, feelings of worthlessness, excessive guilt, fatigue, poor concentration, and suicidal ideation. [23]",
"<br><strong>Test:</strong> Clinical diagnosis requiring formal psychiatric assessment.</p>",
"</dd>",
"<dt><a href='#Section10'>Underlying malignancy</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Weight loss, fever, and malaise may be present. There may be local swelling and pain may persist despite treatment. [24]  [25]",
"<br><strong>Test:</strong> Chest CT scan showing a mass and/or destruction of the bones and the costochondral joints.</p>",
"</dd>",
"<dt><a href='#Section11'>Seronegative spondyloarthropathies</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Associated conditions such as psoriasis, inflammatory bowel disease, or sexually transmitted disease.Insidious onset of low-back pain, worse in the morning or after rest. The pain lasts &ge;30 minutes and improves with activity.Sacroiliitis may present with bilateral or unilateral buttock pain radiating to the thigh.Physical examination may reveal peripheral inflammatory arthritis, limitation of lumbar-spine movement in frontal and sagittal planes, decreased chest expansion, and anterior uveitis. [26]",
"<br><strong>Test:</strong> Sacroiliac joint x-ray showing indistinct joints, bony erosions, sclerosis, and widening of the joint space.Spinal x-ray showing marginal vertebral body erosions, vertebral body squaring, and syndesmophytes between vertebrae. [26]Radiographic evidence of peripheral erosive arthritis, especially in the case of psoriatic arthritis.Disease-specific evaluation such as dermatology consultation for psoriasis, gastroenterological evaluation, and colonoscopy and/or endoscopy for inflammatory bowel disease.</p>",
"</dd>",
"<dt><a href='#Section12'>Fibromyalgia</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Widespread body pain.More than 11 of 18 defined tender points are tender upon palpation. [27]",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");