content=["<dl>",
"<dt><a href='#Section0'>Pituitary adenoma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Rare in children and adolescents, although quite common in adults.Rarely extend into (as opposed to compressing) the third ventricle and rarely cause hydrocephalus.May be hormone secreting with symptoms consistent with prolactinoma, Cushing's disease, or acromegaly.",
"<br><strong>Test:</strong> MRI/CT: tumour arises from sella with suprasellar extension, or is confined to sella (unlike most craniopharyngiomas) and is nearly always solid and enhancing.Endocrine tests show elevated hormones (dependent upon tumour type).Histopathology provides definitive diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Diaphragmatic meningioma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Rare in children and adolescents, more common in older adults.May be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> MRI/CT: homogenous enhancement, enhancing dural 'tail', bony hyperostosis.Histopathology provides definitive diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Chiasmatic epidermoid</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Paramidline tumours seen in children and young adults.May be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> MRI/CT: lesion off midline, cystic, show restricted water movement.Histopathology provides definitive diagnosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Chiasmatic glioma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Most common in infants and children; often seen in association with neurofibromatosis type 1.May be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> MRI/CT: intra-axial tumour of the optic chiasm or nerve, usually non-cystic and may or may not enhance.Histopathology provides definitive diagnosis.</p>",
"</dd>",
"<dt><a href='#Section4'>Rathke's pouch cyst, pars intermedia cyst</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Uncommon benign embryological malformation.May be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Histopathology provides definitive diagnosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Primary germ cell neoplasm</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> A malignant CNS neoplasm seen in children, adolescents, and young adults.May be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Elevated serum and CSF onco-fetal proteins (alpha-fetal protein or beta-human chorionic gonadotrophin).Histopathology provides definitive diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");