content=["<dl>",
"<dt><a href='#Section0'>Tuberculosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Epidemiological data showing high local prevalence of TB.As cryptococcosis is characterised by a similar latent infection with lymph node complex to that seen in TB, there are no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Sputum microscopy: presence of acid-fast bacilli.Smear culture: detection of mycobacteria using Ziehl-Neelsen stain to show acid-fast bacilli.Tuberculin skin testing with Mantoux skin test: positive result denoted by reaction of &ge;15 mm of induration in populations at low risk of TB exposure or reactivation, &ge;10 mm in individuals with an increased probability of recent infection or conditions (other than HIV or pharmacological immunosuppression) that increase the risk of TB, and &ge;5 in the immunosuppressed. A negative test, particularly in patients with CD4 counts &lt;300 cells/microlitre, does not rule out active or latent infection.In vitro interferon gamma release assays: high level of interferon-gamma production is indicative of TB infection.</p>",
"</dd>",
"<dt><a href='#Section1'>Primary or metastatic CNS neoplasm</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> CNS manifestations of cryptococcosis can be mistaken for primary or metastatic neoplasms, as the signs and symptoms for both conditions are similar.The immunological state of the patient may lead to a suspicion of cryptococcosis of the CNS.",
"<br><strong>Test:</strong> Neuroimaging: CT or MRI of the brain show presence of primary or metastatic tumour(s).Tissue biopsy: histological examination shows malignant cells.</p>",
"</dd>",
"<dt><a href='#Section2'>Skin manifestations of systemic infections</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Skin manifestations of cryptococcosis can mimic those of other systemic infections, including Histoplasma capsulatum, Coccidioides immitis, and Penicillium marneffei.Signs and symptoms are similar to those of cryptococcosis, but the immunological state of the patient may lead to a suspicion of cryptococcal-associated skin lesions.",
"<br><strong>Test:</strong> Skin biopsy with culture and histology: positive for specific organism.</p>",
"</dd>",
"<dt><a href='#Section3'>Opportunistic infections</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> AIDS patients, especially those with CD4 counts &lt;200 cells/microlitre, are at risk of opportunistic infection with Pneumocystis jirovecii, Toxoplasma, Histoplasma, Coccidioides, Candida, Cytomegalovirus, and Mycobacterium avium complex.Signs and symptoms are similar to those of cryptococcosis.",
"<br><strong>Test:</strong> Microscopy and culture of sputum/bronchoalveolar lavage sample: positive for specific organism.Immunofluorescent, Gomori methenamine, or Wright-Giemsa staining of sputum/bronchoalveolar lavage: positive for Pneumocystis jirovecii.</p>",
"</dd>",
"</dl>"].join("\n");