content=["<dl>",
"<dt><a href='#Section0'>Atopic dermatitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of atopy and lack of lesions with active inflammatory border with central clearing. Lesions in flexural folds of neck, arms, and legs. Chronic and relapsing, often since childhood.",
"<br><strong>Test:</strong> Diagnosis is clinical. Potassium hydroxide (KOH) microscopy is infrequently done, and rarely fungal culture or biopsy may be undertaken to exclude diagnosis of dermatophyte infection.</p>",
"</dd>",
"<dt><a href='#Section1'>Dyshidrotic dermatitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Sudden eruption of pruritic, small intradermal vesicles on hands and feet. There may be hx of contact irritants: for example, nickel.",
"<br><strong>Test:</strong> Diagnosis is clinical. KOH microscopy is infrequently done, and rarely fungal culture or biopsy may be undertaken to exclude diagnosis of dermatophyte infection.</p>",
"</dd>",
"<dt><a href='#Section2'>Lichen simplex chronicus</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Leather-like, hyperpigmented patches that are pruritic and chronically rubbed, producing a leathery change in affected skin.",
"<br><strong>Test:</strong> Diagnosis is clinical. KOH microscopy is infrequently done, and rarely fungal culture or biopsy may be undertaken to exclude diagnosis of dermatophyte infection.</p>",
"</dd>",
"<dt><a href='#Section3'>Psoriasis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> FHx of psoriasis, presence of characteristic silvery plaque and lesions located on extensor surface of elbows and knees will aid in diagnosis. View image Pitting of nails may be mistaken for tinea unguium. Clinical differentiation will usually suffice for tinea capitis, unguium, or corporis.",
"<br><strong>Test:</strong> KOH microscopy is infrequently done, and rarely fungal culture or biopsy may be undertaken to exclude dermatophyte infection.</p>",
"</dd>",
"<dt><a href='#Section4'>Trichotillomania</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of obsessive habit of twisting hair with fingers. Usually no inflammatory changes in scalp, and broken hairs are of different lengths.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Traction alopecia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> History of tightly braided hair styles. Broken hairs with patchy alopecia. Usually no scaling and inflammation of scalp.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section6'>Alopecia areata</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Complete rather than patchy hair loss.",
"<br><strong>Test:</strong> Diagnosis is clinical. Skin bx will confirm diagnosis.</p>",
"</dd>",
"<dt><a href='#Section7'>Erythema chronicum migrans</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Rapidly enlarging and reddening, single or multiple bull's eye lesions on trunk. History of tick exposure or associated symptoms of Lyme disease.",
"<br><strong>Test:</strong> Occasionally, KOH microscopy is required to distinguish this from tinea corporis. Antibody titres or skin bx for diagnosis of Lyme disease.</p>",
"</dd>",
"<dt><a href='#Section8'>Pityriasis versicolor</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Hypopigmented truncal lesions in dark-skinned individuals, darker than normal colour with scaling in light-skinned individuals; commonly, below neck level.",
"<br><strong>Test:</strong> Clinical differentiation usually sufficient; occasionally KOH microscopy is required to distinguish this from tinea corporis.Ultraviolet light from Wood lamp shows a pale yellow-white fluorescence.</p>",
"</dd>",
"<dt><a href='#Section9'>Pseudofolliculitis barbae</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Hyperpigmented nodules in beard area with incurving hairs in patients with dark skin.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section10'>Seborrhoeic dermatitis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Greasy and scaly area in scalp (with scaling but no hair loss, i.e., dandruff) and erythema in the nasolabial folds and occasionally central chest.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section11'>Acne rosacea</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Acneiform eruption with erythema and easy blushing in nasal and malar area.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section12'>Discoid lupus erythematosus</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Malar rash, sun sensitivity.",
"<br><strong>Test:</strong> Skin bx is confirmatory.</p>",
"</dd>",
"<dt><a href='#Section13'>Contact dermatitis</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Pattern of eruption, intense pruritus, erythema, and occasional vesicular eruption.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section14'>Candidal intertrigo</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Usually uniformly red without central clearing or sparing of scrotum; satellite lesions.View image",
"<br><strong>Test:</strong> Clinical differentiation usually sufficient from tinea cruris; responds to all topical therapies recommended for tinea cruris.</p>",
"</dd>",
"<dt><a href='#Section15'>Erythrasma</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Uniformly brown and scaly, with no active edge; groin or axillae.",
"<br><strong>Test:</strong> Fluoresces a brilliant coral red under Wood lamp.</p>",
"</dd>",
"<dt><a href='#Section16'>Friction blisters of feet</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Absence of interdigital maceration or moccasin pattern of scaling; bulla primarily at points of contact with ill-fitting foot wear; acute in onset.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section17'>Onychogryphosis</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> Long-standing thickening of toenails in which a hyperkeratotic, mis-shapen nail develops over months to years. Easily mistaken for tinea unguium, this change occurs in older adults where vascular disease and diabetes may play a role. Recurrent trauma (such as that caused by ill-fitting shoes) may play a role.",
"<br><strong>Test:</strong> KOH microscopy of nail scrapings, fungal culture, or nail biopsy may be necessary to distinguish from tinea unguium; both conditions may co-exist.</p>",
"</dd>",
"</dl>"].join("\n");