content=["<dl>",
"<dt><a href='#Section0'>Psychogenic polydipsia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Clinical signs and symptoms may be similar.",
"<br><strong>Test:</strong> Following water deprivation test, urine osmolality will exceed serum osmolality.</p>",
"</dd>",
"<dt><a href='#Section1'>Diabetes mellitus</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Clinical signs and symptoms may be similar.Patients may have hx of existing diabetes mellitus (DM).However, it should be recognised that DM and DI (central or nephrogenic) can co-exist, and that DM may be a risk factor for central DI.",
"<br><strong>Test:</strong> Fasting glucose and HbA1c are elevated.Following water deprivation test, urine osmolality will exceed serum osmolality.</p>",
"</dd>",
"<dt><a href='#Section2'>Hyperaldosteronism</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms of hypokalaemia are generally present. These include muscle weakness, paraesthesias, muscle cramps, nocturia, polyuria, and palpitations.Other non-specific symptoms include lethargy, difficulty concentrating, and mood disturbances such as irritability, anxiety, and depression.",
"<br><strong>Test:</strong> Serum potassium is low.Plasma renin activity (PRA) may be abnormally low (&lt;1 nanogram/mL/hour), and the plasma aldosterone concentration (PAC):plasma renin activity (PRA) ratio may be greatly elevated (&gt;30 to 50; normal ratio is between 4 and 10).</p>",
"</dd>",
"<dt><a href='#Section3'>Diuretics</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Clinical signs and symptoms may be similar.Hx of diuretic use.",
"<br><strong>Test:</strong> Serum potassium is low; urine potassium may be elevated.Following water deprivation test, urine osmolality will exceed serum osmolality.</p>",
"</dd>",
"<dt><a href='#Section4'>Hyperosmolar hyperglycaemic state</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Clinical signs and symptoms may be similar.",
"<br><strong>Test:</strong> Plasma glucose &gt;33.3 mmol/L (&gt;600 mg/dL).Following water deprivation test, urine osmolality will exceed serum osmolality.</p>",
"</dd>",
"</dl>"].join("\n");