content=["<dl>",
"<dt><a href='#Section0'>Uraemia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Various signs associated with the primary cause for end-stage renal disease (ESRD) may be present.May co-exist with DN.",
"<br><strong>Test:</strong> Abnormal urea, creatinine, GFR consistent with ESRD.</p>",
"</dd>",
"<dt><a href='#Section1'>Cyanocobalamin deficiency</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Poor nutrition, alcoholism, certain drugs (e.g., trimethoprim, methotrexate, phenytoin), pernicious anaemia, atrophic gastritis, malabsorption, or infection with Helicobacter pylori more likely to be present.Patients are more likely to be older (&gt;65 years).",
"<br><strong>Test:</strong> FBC reveals macrocytic anaemia.Reduced serum vitamin B12 levels.</p>",
"</dd>",
"<dt><a href='#Section2'>Hypothyroidism</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Fatigue, cold intolerance, weight gain, constipation, myalgia, menstrual irregularities, delayed relaxation of deep tendon reflexes, bradycardia (if severe).",
"<br><strong>Test:</strong> TSH elevated in primary hypothyroidism.Free serum T4 may be low.</p>",
"</dd>",
"<dt><a href='#Section3'>Acute intermittent porphyria</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Abdominal pain, vomiting, muscle weakness, constipation, fever, diarrhoea, sensory loss, seizures, tachycardia, hypertension may all occur.Abdominal pain is severe and more typical than in DN.",
"<br><strong>Test:</strong> Elevated aminolevulinic acid, porphobilinogen.</p>",
"</dd>",
"<dt><a href='#Section4'>Chronic high alcohol intake</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Signs of malnutrition, Wernicke encephalopathy, and Korsakoff amnestic syndrome may be present.",
"<br><strong>Test:</strong> Severe cases present with associated anaemia, thiamine deficiency, and deranged LFTs.</p>",
"</dd>",
"<dt><a href='#Section5'>Heavy metal poisoning</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May present with a peripheral neuropathy that frequently manifests with extensor weakness, or wrist/ankle drop, due to an axonal degeneration, primarily affecting motor nerves.Abdominal pain ('lead colic'), constipation, joint pains, muscle aches, headache, anorexia, decreased libido, difficulty concentrating and deficits in short-term memory, anaemia, nephropathy, and other symptoms and signs in various combinations.",
"<br><strong>Test:</strong> Abnormally high blood levels of lead or other metals.</p>",
"</dd>",
"<dt><a href='#Section6'>Drug-induced neuropathy</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Diabetes less likely and drug history likely to include a drug that is known to be a risk for development of neuropathy, such as (in descending order of likelihood of association) antivirals, antibacterials, antineoplastic and immunosuppressants, and cardiovascular, CNS, GI, and metabolism agents.History may include the following specific drugs suspected of causing neuropathies: stavudine, didanosine, lamivudine, thalidomide, ritonavir, zalcitabine, and amiodarone.",
"<br><strong>Test:</strong> No differentiating investigations.</p>",
"</dd>",
"<dt><a href='#Section7'>Chronic inflammatory demyelinating neuropathy (CIDP)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> People with diabetes may develop features of CIDP.Severe, predominantly motor neuropathy that is progressive in nature. Features progress despite optimal glycaemic control.",
"<br><strong>Test:</strong> May be difficult to differentiate.Nerve conduction studies show a combination of slowed conduction velocities, prolonged distal latencies, prolonged F-wave latencies, and conduction block in &ge;1 nerves.Nerve biopsies demonstrate increased numbers of macrophages.Unusually high CSF protein.</p>",
"</dd>",
"<dt><a href='#Section8'>Sarcoidosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Various signs, including fever, skin signs (e.g., erythema nodosum), joint and/or eye lesions.",
"<br><strong>Test:</strong> Chest x-ray may show bilateral hilar lymphadenopathy and pulmonary reticular opacities.Biopsies of accessible lesions are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section9'>Leprosy</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Travel to or residence in endemic countries.Nerves commonly involved include the ulnar and median (claw hand), the common peroneal (foot drop), the posterior tibial (claw toes and plantar insensitivity), facial, radial cutaneous, and great auricular.",
"<br><strong>Test:</strong> Skin smear is positive for acid fast bacilli (AFB).Biopsy of lesions reveal the presence of AFB plus other associated signs.</p>",
"</dd>",
"<dt><a href='#Section10'>Polyarteritis nodosa (PAN)</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Systemic symptoms (e.g., fatigue, weakness, fever, arthralgias) and signs (e.g., hypertension, renal insufficiency, neurological dysfunction, abdominal pain) of multisystem involvement more likely.",
"<br><strong>Test:</strong> There is no diagnostic laboratory test for PAN.Basic laboratory tests help ascertain the extent of organs affected and their degree of involvement.</p>",
"</dd>",
"<dt><a href='#Section11'>Amyloidosis</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Muscle weakness and enlargement due to amyloid infiltration (myopathy), disorders of the joints (arthropathy), and lesions of bone (osteopathy) more likely to be present.",
"<br><strong>Test:</strong> Presence of a paraprotein in the serum (as an M protein on protein immunoelectrophoresis or immunofixation) or urine (as monoclonal light chains) in approximately 90% cases.</p>",
"</dd>",
"<dt><a href='#Section12'>Dysproteinaemias and paraproteinaemias</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Possibly no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Presence of a monoclonal protein in the serum or urine.</p>",
"</dd>",
"<dt><a href='#Section13'>Paraneoplastic syndrome</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Varies, based on primary aetiology.History of a primary neoplastic condition.",
"<br><strong>Test:</strong> Varies, based on primary aetiology.</p>",
"</dd>",
"<dt><a href='#Section14'>Leukaemias and lymphomas</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms and signs vary but may include anaemia, fever, weight loss, and lymphadenopathy.",
"<br><strong>Test:</strong> Abnormal blood cell count and bone marrow aspirate.Specific abnormalities are diverse depending on the type of leukemia or lymphoma present.</p>",
"</dd>",
"<dt><a href='#Section15'>Hereditary neuropathies (e.g., Charcot-Marie-Tooth disease)</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Both motor and sensory nerve manifestations are more common with distal leg weakness, foot deformities (pes cavus, hammer toes), and sensory deficits.",
"<br><strong>Test:</strong> Genetic testing is diagnostic.</p>",
"</dd>",
"<dt><a href='#Section16'>Psychophysiological disorder</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> May also present with pains and paresthesias but without neurological deficit.There is no sensory loss.",
"<br><strong>Test:</strong> Specific psychological evaluations help to confirm the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section17'>Multiple system atrophy/Shy-Drager syndrome</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> May present with symptoms and signs of autonomic neuropathy, as in DN.May also have parkinsonism, varying degrees of dysautonomia, cerebellar involvement, and pyramidal signs.",
"<br><strong>Test:</strong> An excellent response to dopaminergic therapy is an important supportive feature for establishing the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section18'>Riley-Day syndrome</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> Progressive sensorimotor neuropathy but sympathetic autonomic dysfunction is responsible for most clinical manifestations (i.e., orthostatic hypotension, swallowing dysfunction, GI motility dysfunction, bladder dysfunction, decreased or absent tearing, pupil dilation, hypohidrosis, and episodic hyperhidrosis).",
"<br><strong>Test:</strong> Genetic evaluation is sensitive and specific for the diagnosis: a truncated form of I kappa B kinase complex associated protein (IKBKAP) mutation on chromosome 9q31.</p>",
"</dd>",
"<dt><a href='#Section19'>Autonomic neuropathy: idiopathic orthostatic hypotension</a></dt>",
"<dd id='Section19'>",
"<p><strong>Sign & Symptoms:</strong> Severe postural dizziness and weakness.",
"<br><strong>Test:</strong> Reduction of systolic BP of at least 20 mmHg, or diastolic BP of at least 10 mmHg, within the first 3 minutes of standing.</p>",
"</dd>",
"<dt><a href='#Section20'>Guillain-Barre syndrome</a></dt>",
"<dd id='Section20'>",
"<p><strong>Sign & Symptoms:</strong> Progressive, fairly symmetrical muscle weakness accompanied by absent or depressed deep tendon reflexes.Weakness can vary from mild difficulty with walking to nearly complete paralysis of all extremity, facial, respiratory, and bulbar muscles.",
"<br><strong>Test:</strong> Albuminocytological dissociation in CSF (i.e., elevated protein with a normal WBC count), present in 80% to 90% patients at 1 week after onset of symptoms.</p>",
"</dd>",
"<dt><a href='#Section21'>Myasthenia gravis</a></dt>",
"<dd id='Section21'>",
"<p><strong>Sign & Symptoms:</strong> Fluctuating degree and variable combination of weakness in ocular, bulbar, limb, and respiratory muscles.",
"<br><strong>Test:</strong> Antibodies against acetylcholine receptors or receptor associated proteins are present.Tensilon test, ice pack test, repetitive nerve stimulation studies, and single-fibre electromyography assist in confirmation of the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section22'>Degenerative spinal disk disease</a></dt>",
"<dd id='Section22'>",
"<p><strong>Sign & Symptoms:</strong> May present with symptoms and signs of a femoral neuropathy, including asymmetrical pain weakness and sensory loss.",
"<br><strong>Test:</strong> MRI demonstrates specific vertebral disk pathology.</p>",
"</dd>",
"<dt><a href='#Section23'>Femoral neuropathy: intrinsic spinal cord mass lesion</a></dt>",
"<dd id='Section23'>",
"<p><strong>Sign & Symptoms:</strong> May present with symptoms and signs of a femoral neuropathy, including asymmetrical pain, weakness, and sensory loss.",
"<br><strong>Test:</strong> MRI demonstrates the spinal cord mass.</p>",
"</dd>",
"<dt><a href='#Section24'>Cauda equina lesions</a></dt>",
"<dd id='Section24'>",
"<p><strong>Sign & Symptoms:</strong> May present with symptoms and signs of a femoral neuropathy, including weakness and sensory loss.",
"<br><strong>Test:</strong> Diagnosis usually confirmed by MRI.</p>",
"</dd>",
"<dt><a href='#Section25'>Carotid aneurysm</a></dt>",
"<dd id='Section25'>",
"<p><strong>Sign & Symptoms:</strong> May present with symptoms and signs of a cranial neuropathy, including diplopia and Bell palsy.",
"<br><strong>Test:</strong> Magnetic resonance angiography and CT angiography confirm diagnosis.</p>",
"</dd>",
"<dt><a href='#Section26'>Mononeuropathy multiplex: vasculitis</a></dt>",
"<dd id='Section26'>",
"<p><strong>Sign & Symptoms:</strong> May present with symptoms and signs including nerve damage in &ge;2 named nerves in separate parts of the body.Wrist drop, for example, is caused by infarction of the radial nerve, and foot drop by damage to either the sciatic or peroneal nerve.",
"<br><strong>Test:</strong> Vasculitis and lymphocytic infiltrates on nerve biopsies.</p>",
"</dd>",
"<dt><a href='#Section27'>Acromegaly</a></dt>",
"<dd id='Section27'>",
"<p><strong>Sign & Symptoms:</strong> Very slow onset over decades.Typical clinical phenotype, including acral and soft tissue overgrowth; enlargement of jaw, nose, frontal bones, hands, and feet; articular overgrowth.",
"<br><strong>Test:</strong> Abnormal IGF-1 levels.Pituitary MRI may reveal pituitary tumour.</p>",
"</dd>",
"<dt><a href='#Section28'>Coagulopathies</a></dt>",
"<dd id='Section28'>",
"<p><strong>Sign & Symptoms:</strong> May present with haemorrhages or thrombosis.",
"<br><strong>Test:</strong> Abnormal platelets, prothrombin time, D-dimer, fibrinogen, fibrin degradation products.</p>",
"</dd>",
"</dl>"].join("\n");