content=["<dl>",
"<dt><a href='#Section0'>Beta-blocker toxicity</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Hypotension, possible depressed mental status.",
"<br><strong>Test:</strong> ECG (slow ventricular rate, AV nodal blockade with associated dysrhythmias).Blood glucose: hypoglycaemia.</p>",
"</dd>",
"<dt><a href='#Section1'>Calcium-channel blocker toxicity</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Hypotension, usually normal mental status.",
"<br><strong>Test:</strong> ECG (slow ventricular rate, AV nodal blockade with associated dysrhythmias).Blood glucose: hyperglycaemia.</p>",
"</dd>",
"<dt><a href='#Section2'>Clonidine toxicity</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Hypotension, bradycardia, lethargy. Occasionally responsive to naloxone.",
"<br><strong>Test:</strong> Normal or therapeutic serum digoxin concentration.</p>",
"</dd>",
"<dt><a href='#Section3'>Hypothermia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hypothermia, cool extremities, hypotension, ventricular dysrhythmias with rapid ventricular response.",
"<br><strong>Test:</strong> Normal or therapeutic serum digoxin concentration.</p>",
"</dd>",
"<dt><a href='#Section4'>Pesticide toxicity</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Salivation, lacrimation, urination, and bronchorrhoea.",
"<br><strong>Test:</strong> Normal or therapeutic serum digoxin concentration.</p>",
"</dd>",
"<dt><a href='#Section5'>Ischemic heart disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Hypotension, bradycardia, chest pain or discomfort, history of exertional dyspnoea with angina or anginal equivalent.",
"<br><strong>Test:</strong> Normal or therapeutic serum digoxin concentration.</p>",
"</dd>",
"<dt><a href='#Section6'>Acute MI</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Chest discomfort and/or pain, dyspnoea, vomiting, pain characteristic of cardiac aetiology, bradycardia, hypotension.",
"<br><strong>Test:</strong> Normal or therapeutic serum digoxin concentration.</p>",
"</dd>",
"<dt><a href='#Section7'>Elevated intracranial pressure</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Altered mental status, hypertension, sinus bradycardia (but could possibly have other bradycardic rhythms).",
"<br><strong>Test:</strong> Normal or therapeutic serum digoxin concentration.</p>",
"</dd>",
"<dt><a href='#Section8'>Hyperkalaemia</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Patients with hyperkalaemia due to other aetiologies (e.g., diminished potassium excretion, excessive endogenous potassium load, pseudohyperkalaemia, redistribution from within cells into plasma) are typically awake and not lethargic.Patients with chronic renal insufficiency may present with lethargy and with any number of other non-specific complaints. Patients with hyperkalaemia may also present as completely asymptomatic.",
"<br><strong>Test:</strong> Normal or therapeutic serum digoxin concentration.</p>",
"</dd>",
"<dt><a href='#Section9'>Hypothyroidism</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Cold intolerance, fatigue, depression, thinning of hair, lethargy, or abnormal menstrual cycle.",
"<br><strong>Test:</strong> Elevated TSH and decreased T4 levels are useful in the diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");