content=["<dl>",
"<dt><a href='#Section0'>Streptococcus pyogenes pharyngitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Rapid onset with prominent sore throat and fever.Headache and gastrointestinal symptoms are frequent.Red throat and enlarged tonsils covered by yellow or blood-tinged exudate.Enlarged and tender cervical lymphadenopathy.Some patients have a fine papular rash with circum-oral pallor and strawberry tongue (scarlet fever). [23]",
"<br><strong>Test:</strong> Positive throat culture is the definitive test for Streptococcus pyogenes diagnosis.Rapid antigen detection tests can confirm the presence of group A streptococci carbohydrate antigen on a throat swab within minutes. However, the sensitivity of these tests ranges between 70% and 90% compared with blood agar plate culture.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute epiglottitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Acute fulminating course of high fever, sore throat, and rapidly progressing respiratory obstruction.Drooling is usually present, and patient maintains hyperextended neck in attempt to maintain open airways. [23]",
"<br><strong>Test:</strong> Direct visualisation of the epiglottis shows cherry-red swollen area.A lateral x-ray of soft tissue of the neck shows enlarged epiglottitis protruding from the anterior wall of the hypopharynx (thumb sign).</p>",
"</dd>",
"<dt><a href='#Section2'>Infectious mononucleosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Prominent tonsillar enlargement with exudate and cervical lymphadenopathy.Hepatomegaly and splenomegaly usually present.Rash and generalised fatigue occur as part of infectious mononucleosis syndrome. [23]",
"<br><strong>Test:</strong> Positive heterophil antibody test or positive serological test.</p>",
"</dd>",
"<dt><a href='#Section3'>Acute necrotising ulcerative gingivitis (Vincent's angina)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Periodontal disease associated with spirochaetes and fusobacteria.Necrosis and ulceration of the gingiva between the teeth, with adherent greyish pseudomembrane covering the gingiva.Fever, malaise, and lymphadenopathy. [25]",
"<br><strong>Test:</strong> Dark-field microscopy of debris from the pseudomembrane shows spirochaetes.</p>",
"</dd>",
"<dt><a href='#Section4'>Staphylococcal or streptococcal impetigo</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Typically affects the skin of the face or of extremities that have been traumatised.Tiny vesicles or pustules form initially and develop into small blisters that rupture, forming a honey-coloured, crusted plaque.Little or no pain. No surrounding erythema, and constitutional symptoms are generally absent. [21]",
"<br><strong>Test:</strong> Bacteriological culture or microscopy shows staphylococci or streptococci.</p>",
"</dd>",
"</dl>"].join("\n");