content=["<dl>",
"<dt><a href='#Section0'>Systemic lupus erythematosus (SLE)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Skin manifestations are a common presentation of SLE. The photosensitive malar or butterfly rash is characteristic. This erythematous rash extends from the cheeks over the bridge of the nose, sparing the nasolabial folds. It can be painful and pruritic, usually lasts a few days, heals without scarring, but often recurs after sun exposure.For a diagnosis of SLE, &ge;4 of the following 11 criteria are required: [12]  1) malar rash, 2) discoid rash, 3) photosensitivity, 4) oral ulcers, 5) arthritis, 6) serositis, 7) renal disorder, 8) neurological disorder, 9) haematological disorder, 10) immunological disorder, 11) ANA.",
"<br><strong>Test:</strong> High-titre ANA, anti-double-stranded DNA antibodies, and anti-ribonucleoprotein antibodies are strongly suggestive.</p>",
"</dd>",
"<dt><a href='#Section1'>Subacute cutaneous lupus erythematosus (SCLE)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> SCLE lesions begin as small, erythematous, slightly scaly papules that evolve into either psoriasiform (papulosquamous) or annular forms. The lesions typically have erythematous crusted margins, usually sparing the face and mostly affecting the neck, arms, and upper torso.Although telangiectasia may be seen, permanent pigment changes and scarring are absent.",
"<br><strong>Test:</strong> Findings on skin biopsy are similar to those of DLE, except that basement membrane thickening is generally absent or minimal.</p>",
"</dd>",
"<dt><a href='#Section2'>Psoriasis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are red, inflamed, silvery-white scaly and circumscribed papules and plaques on elbows, knees, extensor limbs, and scalp. Psoriatic nails have a pitted surface and/or hypertrophic (subungual) changes.",
"<br><strong>Test:</strong> Skin biopsy findings include intra-epidermal spongiform pustules and Munro neutrophilic microabscess within the stratum corneum.</p>",
"</dd>",
"<dt><a href='#Section3'>Polymorphous light eruption (PMLE)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Considered an exclusively photo-triggered dermatosis that can express several clinical forms. PMLE lesions are usually itchy papules, eczematous plaques, or vesicles, often with associated urticaria, and develop within 24 hours of sun exposure.",
"<br><strong>Test:</strong> Skin biopsy shows oedema in the upper part of the dermis.</p>",
"</dd>",
"<dt><a href='#Section4'>Rosacea</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Common chronic disorder of the skin characterised by redness, flushing, and other cutaneous findings that often include telangiectasias, roughened skin, rhinophyma, and general inflammation that can resemble acne.Typically affects the convexities of the central face, including the nose, cheeks, eyelids, and forehead. Papules and/or pustules occur in crops.",
"<br><strong>Test:</strong> Skin biopsy shows non-specific granulomatous or lymphohistiocytic infiltrate. Associated oedema, telangiectasias, and sebaceous hyperplasia may also be present.</p>",
"</dd>",
"<dt><a href='#Section5'>Lichen planopilaris</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Refers to lichen planus of the hair follicles. Presents with alopecia associated with hyperkeratotic papules and perifollicular erythema.Typical lichen planus lesions affecting skin, nails, and buccal mucosa may also be present.",
"<br><strong>Test:</strong> Skin biopsy shows lichenoid lymphocyte infiltrates under epidermis.</p>",
"</dd>",
"</dl>"].join("\n");