content=["<dl>",
"<dt><a href='#Section0'>Severe liver failure</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Most common differential diagnosis and a known underlying cause of DIC. [1]  [2]  [4]Absence of symptoms and signs related to thrombosis in the patients without DIC.",
"<br><strong>Test:</strong> LFTs: elevated; varies depending on aetiology.INR &gt;1.5.Fibrin degradation products (FDPs), D-dimer test, and platelet count may help to differentiate this from DIC.FDPs: normal level; D-dimer test: negative.</p>",
"</dd>",
"<dt><a href='#Section1'>Heparin-induced thrombocytopenia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Hx of use of heparin in association with low platelet count, plus absence of triggering factors for DIC",
"<br><strong>Test:</strong> Heparin aggregation study: presence of platelet aggregation when exposed to heparin (caused by antibodies to platelet factor 4).FBC: low platelet count; FDPs: normal level; D-dimer test: negative.</p>",
"</dd>",
"<dt><a href='#Section2'>Idiopathic purpura fulminans</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Purpuric skin lesions that characteristically have well-demarcated borders.Usually associated with sepsis and is a known underlying cause of DIC.The idiopathic variety is often confined to the skin.",
"<br><strong>Test:</strong> FDPs and D-dimer test may help to exclude DIC, but many patients will develop DIC.FDPs: normal level; D-dimer test: negative.</p>",
"</dd>",
"<dt><a href='#Section3'>Vitamin K deficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Positive symptoms and signs of bleeding, but negative symptoms and signs of thrombosis.Associated with a poor diet (e.g., bulimic anorexia, alcoholism) and conditions that affect GI absorption (e.g., cystic fibrosis, inflammatory bowel disease, primary biliary cirrhosis).",
"<br><strong>Test:</strong> Vitamin K level: decreased.INR: elevated.FDPs: normal level; D-dimer test: negative.</p>",
"</dd>",
"<dt><a href='#Section4'>HELLP syndrome</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Usually occurs after 28 weeks' gestation in pregnant women; can also occur postpartum.Key clinical picture: severe pregnancy-induced hypertension, elevated liver enzymes, and low platelets.Also a known underlying cause of DIC, but negative symptoms and signs of thrombosis.",
"<br><strong>Test:</strong> FBC: low platelets, anaemia may be present.LFTs: elevated ALT and AST.FDPs: normal level; D-dimer test: negative (unless has progressed to DIC).Coombs' test: positive.</p>",
"</dd>",
"</dl>"].join("\n");