content=["<dl>",
"<dt><a href='#Section0'>Red eye</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Signs and symptoms may be very similar to dry eye.",
"<br><strong>Test:</strong> There are no specific tests to differentiate between dry eye and red eye. Dry eye should always be considered in the differential diagnosis of red eye.</p>",
"</dd>",
"<dt><a href='#Section1'>Primary Sjogren's syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Symptomatic dry mouth and fatigue as well as dry eyes.Oral symptoms can be determined with positive responses to at least one of the following questions: Have you had a daily feeling of dry mouth for more than 3 months? Have you had recurrently or persistently swollen salivary glands as an adult? Do you frequently drink liquids to aid in swallowing dry food? [1]",
"<br><strong>Test:</strong> Salivary function tests show sialectasia (salivary duct dilatation) and delayed or absent secretion of labelled saliva. [1]FBC results show anaemia in 25% of patients. [1]Serology reveals antibodies to Ro (Sjogren's syndrome antigen A [SSA]) or La (Sjogren's syndrome antigen B [SSB]) antigens, or both are present in serum. [1]</p>",
"</dd>",
"<dt><a href='#Section2'>Secondary Sjogren's syndrome</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients with symptomatic dry mouth and fatigue as well as dry eye may have histories and examination findings that point to other underlying connective tissue disorders. For example, rheumatoid arthritis, systemic lupus erythematosus, systemic sclerosis, and/or mixed connective tissue disorder.Oral symptoms can be determined with positive responses to at least one of the following questions: Have you had a daily feeling of dry mouth for more than 3 months? Have you had recurrently or persistently swollen salivary glands as an adult? Do you frequently drink liquids to aid in swallowing dry food? [1]",
"<br><strong>Test:</strong> Salivary function tests show sialectasia (salivary duct dilatation) and delayed or absent secretion of labelled saliva. [1]FBC results show anaemia in 75% of patients. [1]Serology reveals antibodies to Ro (SSA) or La (SSB) antigens, or both are present in serum. [1]</p>",
"</dd>",
"<dt><a href='#Section3'>Meibomian gland dysfunction</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Past ocular and/or medical history may indicate meibomian gland dysfunction.Scalp changes including seborrhoeic dermatitis and/or flaking/greasy skin may be present.",
"<br><strong>Test:</strong> Slit-lamp tests reveal unstable tear film with rapid tear break-up time.</p>",
"</dd>",
"</dl>"].join("\n");