content=["<dl>",
"<dt><a href='#Section0'>Miscarriage</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Includes anembryonic gestation, threatened abortion, incomplete abortion, complete abortion, missed abortion.Often presents with vaginal bleeding in the first trimester, accompanied by abdominal discomfort secondary to uterine contractions.History may yield disappearance of pregnancy symptoms such as breast tenderness and nausea.",
"<br><strong>Test:</strong> Ultrasound shows intrauterine pregnancy or products of conception.Pelvic examination may note dilation of the cervix, as well as presence of tissue at the cervical os.Consecutive serum chorionic gonadotrophin levels often do not rise appropriately (66% in 48 hours), and progesterone levels often &lt;15.9 nmol/L (&lt;5 ng/mL).</p>",
"</dd>",
"<dt><a href='#Section1'>Acute appendicitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Anorexia and periumbilical pain followed by nausea, RLQ pain, and vomiting.",
"<br><strong>Test:</strong> Ultrasound sensitivity of 85% to 90% and specificity of 92% to 96%; may show appendix with outer diameter &gt;6 mm, no compressibility, lack of peristalsis, or periappendiceal fluid.WBC count &gt;10,000 cells/mm^3.</p>",
"</dd>",
"<dt><a href='#Section2'>Ovarian torsion</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Sudden onset, severe, unilateral lower abdominal pain that worsens intermittently over many hours.Peritoneal signs are often absent.",
"<br><strong>Test:</strong> Ovarian enlargement secondary to impaired venous and lymphatic drainage is the most common sonographical finding in ovarian torsion.Absence of arterial blood flow may also be used for diagnostic purposes, but this is often absent in the early stages of torsion.</p>",
"</dd>",
"<dt><a href='#Section3'>PID or tubo-ovarian abscess</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Lower abdominal tenderness on palpation, adnexal tenderness, and cervical motion tenderness.May also have oral temperature &gt;38.4&deg;C (101&deg;F) and abnormal cervical or vaginal discharge.",
"<br><strong>Test:</strong> Although rare in pregnancy, can occur in the first 12 weeks of gestation before the decidua seals off the uterus from ascending bacteria.WBC count often &gt;10,000 cells/mm^3.Ultrasound not used in uncomplicated PID, but is a valuable adjunct in diagnosis of tubo-ovarian abscess.</p>",
"</dd>",
"<dt><a href='#Section4'>Ruptured corpus luteal cyst or follicle</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Non-specific nausea, vomiting, low grade fever, and pelvic pain, which is often sharp, intermittent, sudden in onset, and severe.At times the ruptured cyst may lead to profuse bleeding and result in haemorrhagic shock.",
"<br><strong>Test:</strong> Doppler ultrasonography usually diagnostic, especially when transvaginal and transabdominal modalities are used together.</p>",
"</dd>",
"<dt><a href='#Section5'>Nephrolithiasis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Classically writhing in pain, pacing about, and unable to lie still, in contrast to a patient with peritoneal irritation, who remains motionless to minimise discomfort.Often presents with unilateral or bilateral flank pain.",
"<br><strong>Test:</strong> Haematuria (presence of &gt;1 RBC/hpf) and pyuria (&gt;5 WBC/hpf on a centrifuged specimen) common.Due to potential risks to the fetus, the only imaging modalities used in pregnant women are ultrasonography (direct visualisation of the stone, hydroureter &gt;6 mm in diameter, and perirenal urinoma suggesting calyceal rupture) and MRI (if ultrasound is non-diagnostic).</p>",
"</dd>",
"<dt><a href='#Section6'>UTI</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Dysuria with accompanying urinary urgency, frequency, and abdominal discomfort along the surface of the bladder.",
"<br><strong>Test:</strong> May have pyuria (&gt;5 WBC/hpf on a centrifuged specimen).Presence of nitrites is highly specific for a UTI, but its absence should not exclude the diagnosis.In all pregnant women with suspected UTI, urine culture must be obtained because the infection increases risk of pre-term labour and pregnancy loss.</p>",
"</dd>",
"</dl>"].join("\n");