content=["<dl>",
"<dt><a href='#Section0'>Pneumonia, bacterial or viral</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Cough is productive.",
"<br><strong>Test:</strong> Chest x-ray usually shows areas of consolidation (increased radiodensity), whereas in human monocytotropic/monocytic ehrlichiosis (HME) and human granulocytotropic/granulocytic anaplasmosis (HGA), chest x-ray might show interstitial pneumonitis simulating a viral infection.Viral infections are ruled out based on specific laboratory tests (i.e., antigen detection, serology, PCR).</p>",
"</dd>",
"<dt><a href='#Section1'>Gastroenteritides, bacterial or viral</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Nausea, vomiting, and diarrhoea are more prominent.",
"<br><strong>Test:</strong> Direct examination of stool may demonstrate polymorphonuclear neutrophils and/or blood.Stool cultures and antigen detection confirm diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Cholecystitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Right upper quadrant pain is usually localised.",
"<br><strong>Test:</strong> Right upper quadrant abdominal ultrasound may show inflammation and dilatation of ducts in the area of the gallbladder.</p>",
"</dd>",
"<dt><a href='#Section3'>Sepsis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Positive blood cultures.</p>",
"</dd>",
"<dt><a href='#Section4'>Rocky Mountain spotted fever</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Frequency of rash is much higher.",
"<br><strong>Test:</strong> Positive PCR or immunofluorescence antibody assay specific for rickettsial DNA.</p>",
"</dd>",
"<dt><a href='#Section5'>Thrombotic thrombocytopenic purpura</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Thrombocytopenia and a purpuric rash.",
"<br><strong>Test:</strong> Peripheral smears show schistocytes.Serum shows elevated lactate dehydrogenase.</p>",
"</dd>",
"<dt><a href='#Section6'>Babesiosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Jaundice is more frequent due to haemolysis.Can coexist with human granulocytotropic/granulocytic anaplasmosis (HGA) and/or Lyme disease. All 3 aetiological agents are transmitted by the same tick vector.",
"<br><strong>Test:</strong> Diagnosed in the acute phase by observing typical intraerythrocytic parasites in peripheral blood smear.PCR is available at research laboratories and is positive for Babesia microti DNA/RNA.Serological diagnosis is possible in convalescent period. Antibodies against B microti present.</p>",
"</dd>",
"<dt><a href='#Section7'>Malaria infection</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Travel history to endemic areas. Presence of cyclical fevers.Jaundice is more frequent due to haemolysis.",
"<br><strong>Test:</strong> Diagnosed in the acute phase by observing typical intraerythrocytic parasites in peripheral blood smear.</p>",
"</dd>",
"<dt><a href='#Section8'>T-cell lymphoma</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Lymphadenopathy is not short lived.",
"<br><strong>Test:</strong> Circulating lymphocytes do not start decreasing by third week of illness.Tests for clonality: T-cell receptor re-arrangements. However, in sporadic cases, lymphocytosis is severe enough to cause false-positives with this test, and follow-up testing is indicated.</p>",
"</dd>",
"<dt><a href='#Section9'>Typhoid infection</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> May be difficult to distinguish; however, gastrointestinal symptoms are more frequent.",
"<br><strong>Test:</strong> Blood and/or stool cultures positive for Salmonella enterica serovar S typhi or S paratyphi.</p>",
"</dd>",
"<dt><a href='#Section10'>Lyme disease</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Presence of erythema migrans.Can coexist with human granulocytotropic/granulocytic anaplasmosis (HGA) and/or babesiosis. All 3 aetiological agents are transmitted by the same tick vector.",
"<br><strong>Test:</strong> Serological diagnosis is possible in convalescent period. Antibodies against  Borrelia  present.Western immunoblotting shows presence of Lyme-specific IgM and IgG.PCR positive for Borrelia.</p>",
"</dd>",
"</dl>"].join("\n");