content=["<dl>",
"<dt><a href='#Section0'>Pneumonia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs or symptoms.",
"<br><strong>Test:</strong> CXR: consolidation without associated effusion.</p>",
"</dd>",
"<dt><a href='#Section1'>Uncomplicated parapneumonic effusion</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs or symptoms.",
"<br><strong>Test:</strong> Pleural fluid: serous in appearance.Gram stain and culture: negative.Pleural fluid pH: &gt;7.2. [2]</p>",
"</dd>",
"<dt><a href='#Section2'>Lung abscess</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Cough productive of foul-smelling sputum.",
"<br><strong>Test:</strong> CXR: cavitating lung lesion with air-fluid level.Contrast-enhanced thoracic CT: demonstrates thick-walled irregular cavity with indistinct boundary between abscess and normal lung, vessels may be visible passing through the abscess. [19]</p>",
"</dd>",
"<dt><a href='#Section3'>Malignant pleural effusion</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Longer history of symptoms.Past medical history of cancer which may be known to be metastatic.Caution is required as malignancy and infected pleural effusions can co-exist.",
"<br><strong>Test:</strong> Pleural fluid pH in both malignant and infected effusions: &lt;7.2.Thoracentesis pleural fluid cytology: may demonstrate malignant cells.CXR: may demonstrate primary tumour.Thoracic ultrasound: may demonstrate pleural thickening and nodularity.CT scan: findings suggestive of malignant pleural effusion are pleural thickening extending onto the mediastinum, circumferential pleural thickening, nodularity, and pleural thickening &gt;1 cm.</p>",
"</dd>",
"<dt><a href='#Section4'>Chylothorax</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> No infective symptoms.",
"<br><strong>Test:</strong> Pleural fluid: remains milky in appearance when centrifuged, in empyema debris settles out on centrifuge.Pleural fluid: triglycerides &gt;110 mg/dL, levels of 50 to 110 mg/dL should be followed by lipoprotein analysis for the detection of chylomicrons.</p>",
"</dd>",
"<dt><a href='#Section5'>Oesophageal rupture</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Recent history of vomiting or retching. [1]",
"<br><strong>Test:</strong> Pleural fluid: contains food debris and amylase of salivary origin.CXR: may show hydropneumothorax.CT scan: may demonstrate oesophageal wall thickening, mediastinal widening, and a pleural space gas-liquid level.Oral contrast-enhanced CT: may show contrast within the mediastinum.Oesophagram with gastrograffin: reveals the location of rupture.</p>",
"</dd>",
"<dt><a href='#Section6'>Haemothorax</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> History of anticoagulation or bleeding diathesis.Close temporal relationship with thoracic trauma or iatrogenic intervention in the pleural space.Caution is required as a haemothorax may become secondarily infected.",
"<br><strong>Test:</strong> Pleural fluid: frankly bloody.Pleural fluid haematocrit: &gt;50% of peripheral blood haematocrit.</p>",
"</dd>",
"</dl>"].join("\n");