content=["<dl>",
"<dt><a href='#Section0'>Aseptic meningitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Headache, neck stiffness, and fever with no altered mental status (maybe mild somnolence) or focal neurological signs.Frequently meningitis and encephalitis co-exist (meningoencephalitis).",
"<br><strong>Test:</strong> MRI evidence of meningeal enhancement, with no evidence of brain parenchymal involvement.</p>",
"</dd>",
"<dt><a href='#Section1'>Encephalopathy (toxic/metabolic)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> A multitude of metabolic factors and remote infections can cause brain parenchymal dysfunction without structural damage to the brain.Frequently encountered in hospital/nursing-home settings.Altered mental status and even focal neurological signs (hypoglycaemia) can be seen with both conditions, and there are no specific clinical differentiating features.",
"<br><strong>Test:</strong> Normal CSF analysis, normal MRI, EEG-diffuse slowing, triphasic waves.</p>",
"</dd>",
"<dt><a href='#Section2'>Status epilepticus</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features, and status epilepticus is not uncommonly seen in patients with encephalitis so can be considered a clinical feature of this disease.In cases that are clearly not due to encephalitis (MRI, CSF negative), the patient frequently has a known seizure disorder with sub-therapeutic levels of medications.",
"<br><strong>Test:</strong> EEG - evidence of ongoing seizure activity.</p>",
"</dd>",
"<dt><a href='#Section3'>CNS vasculitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features. Headaches and focal neurological signs can be seen.",
"<br><strong>Test:</strong> Differentiated by MRI, angiography, and biopsy.MRI - evidence of multiple small strokes, usually cortical.Angiography - can be normal, but frequently a typical angiographic appearance of multi-segment narrowing/beading of the vessels is noted.Definitive diagnosis sometimes requires brain and meningeal biopsy, which will show evidence of inflammation (i.e., presence of inflammatory cells such as lymphocytes in the vessel wall and surrounding the blood vessel, along with structural alterations of the involved vessels).</p>",
"</dd>",
"<dt><a href='#Section4'>Pseudomigraine with pleocytosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Acute confusion, psychosis, and focal neurological deficits in association with migraine headache is seen in some migraine patients, [22]  and in familial hemiplegic migraine. [23]  These are suggestive of but not specific to migraine. [9]",
"<br><strong>Test:</strong> CSF - elevated WBC count with no evidence of infection.</p>",
"</dd>",
"<dt><a href='#Section5'>Malignant hypertension</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> High blood pressure, headaches, altered mental status, and visual symptoms can be seen.",
"<br><strong>Test:</strong> Elevated BP (usually &gt;220/110 mmHg). But may be sudden acute elevations even at lower blood pressure.Differentiated by fundoscopy, CT, and MRI.Fundus examination - papilloedema and haemorrhage.CT usually normal, but occasionally hypodense lesions seen over occipital lobes.MRI: T2 and fluid attenuated inversion recovery (FLAIR) hyperintense lesions over the occipital lobes (usually asymmetric). Increased diffusion on diffusion-weighted imaging (with apparent diffusion coefficient maps showing increased diffusion) is also seen. The term 'posterior reversible leukoencephalopathy' is also used to describe the MRI changes.</p>",
"</dd>",
"<dt><a href='#Section6'>Intracranial tumours and cysts</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features.A variety of clinical presentations, such as headache worse on awakening, altered mental status, seizures, and focal neurological deficits, are seen with intracranial neoplasms.",
"<br><strong>Test:</strong> CT and MRI imaging of the brain (preferably MRI) can help to diagnose these conditions. Biopsy - required in some cases to make a definitive diagnosis. Biopsy results are specific to the underlying tumour.</p>",
"</dd>",
"<dt><a href='#Section7'>Intracranial bleeds</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features. Headache, altered mental status, seizures, and focal neurological deficits can be seen.",
"<br><strong>Test:</strong> CT and MRI can clearly demonstrate acute intracranial bleeds. In subarachnoid haemorrhage, LP may show xanthochromia and no change in the number of RBC from tube 1 to tube 4.</p>",
"</dd>",
"<dt><a href='#Section8'>Traumatic brain injury</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> A history of head injury is frequently obtained, but can be unavailable in someone who is found unresponsive.Headache, varying degrees of altered mental status, and focal neurological findings can be seen.There are no specific clinical differentiating features.",
"<br><strong>Test:</strong> CT and MRI will reveal various intracranial bleeds that are associated with head injury; concussions have normal imaging findings; diffuse axonal damage can be seen as signal abnormality in MRI images.</p>",
"</dd>",
"<dt><a href='#Section9'>Ischaemic strokes</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features.Sudden onset of focal neurological deficits, altered mental status, seizures, and headaches.Certain strokes, such as those involving the posterior cerebral artery, basilar artery, and anterior cerebral artery, can present with an encephalopathic clinical picture.It is important to note that ischaemic stroke can also occur as a complication of some cases of encephalitis.",
"<br><strong>Test:</strong> CT scan - low attenuation in the involved areas.MRI - diffusion-weighted imaging evidence of decreased diffusion is characteristic of acute ischaemic stroke. FLAIR and T2 hyperintense lesions are seen in subacute cases.</p>",
"</dd>",
"<dt><a href='#Section10'>Mitochondrial encephalopathy lactic acidosis and stroke-like episodes (MELAS)</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific clinical differentiating features. Hearing loss, encephalopathy, seizures, stroke-like episodes, and presence of lactic acidosis are characteristic clinical features.",
"<br><strong>Test:</strong> Lactate - elevatedMRI - T2 hyperintense signal in territory not conforming to major vascular regions. Diffusion weighted imaging evidence of increased diffusion.Genetic test - mitochondrial DNA point mutations (A3243G mutation in 80% of cases).Muscle biopsy - ragged red fibres on modified Gomori trichrome stain.</p>",
"</dd>",
"<dt><a href='#Section11'>Mycoplasma pneumoniae infection</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Hx cough, fever, dyspnoea, sputum production. Elevated respiratory rate, crackles, and dullness to percussion may be found on examination. [24]",
"<br><strong>Test:</strong> Chest x-ray may show consolidation. Blood culture or PCR (blood) may detect Mycoplasma pneumoniae.</p>",
"</dd>",
"<dt><a href='#Section12'>Human granulocytic anaplasmosis</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Hx tick bite, fever, and chills. Rash may be present on examination. [25]",
"<br><strong>Test:</strong> Peripheral blood smear may show intragranulocytic inclusions. Indirect fluorescent antibody assay may be positive for Anaplasma pagocytophilum. [25]</p>",
"</dd>",
"<dt><a href='#Section13'>Progressive multifocal leukoencephalopathy</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Hx immunosuppression (e.g., AIDS, organ transplant). May have limb weakness, gait disorders, speech disorder, or visual impairment.Physical examination may reveal ataxia, cranial nerve palsies, paralysis of limbs, and speech disturbances. [26]",
"<br><strong>Test:</strong> CSF PCR may show JC virus.</p>",
"</dd>",
"<dt><a href='#Section14'>Inborn errors of metabolism</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Hx parental consanguinity, early neonatal death, maternal acute fatty liver of pregnancy and HELLP syndrome (elevated liver enzymes and low platelets) in pregnancy. May be lethargic and irritable with poor feeding. Physical examination may reveal jaundice, cataracts, hepatosplenomegaly, abnormal muscle tone, dysmorphism (e.g., coarse facial features), and abnormal body odour. May present with life-threatening encephalopathy. [27]  [28]",
"<br><strong>Test:</strong> Serum ammonia may be elevated (urea cycle defect, organic acidaemias). Arterial blood gas can show a metabolic acidosis with elevated anion gap. Urine orotic acid is low in carbamyl phosphate synthetase deficiency and elevated in ornithine transcarbamylase deficiency. [28]</p>",
"</dd>",
"<dt><a href='#Section15'>Bacterial/fungal meningitis</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Hx headache, neck stiffness, photophobia, and fever.Hx immunosuppression may be present in fungal meningitis.Physical examination may reveal fever, neck stiffness, and focal neurological abnormalities.",
"<br><strong>Test:</strong> Bacterial meningitis: CSF shows elevated WBC often with neutrophil predominance, elevated protein, and low glucose. Gram stain and PCR may reveal the causative organism. [29]  CSF culture may demonstrate fungal growth.</p>",
"</dd>",
"</dl>"].join("\n");