content=["<dl>",
"<dt><a href='#Section0'>Adenomyosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms may be identical to those of endometriosis.",
"<br><strong>Test:</strong> Pre-operative MRI findings may show diffuse or focal widening of the junctional zone (inner myometrium), islands of endometrial tissue or cystic dilation of glands or haemorrhage, linear striations radiating out from the endometrium into the myometrium, mass within the myometrium (adenomyoma).Laparoscopy may reveal a normal pelvis or concurrent endometriosis.Histopathological evaluation of the uterus after hysterectomy shows endometrial glands/stroma in the myometrium.</p>",
"</dd>",
"<dt><a href='#Section1'>Interstitial cystitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms primarily localised to the bladder, such as urinary frequency and urgency. Patients complain of pain with a full bladder that is relieved upon voiding.Diffuse chronic pain and dyspareunia are common and often indistinguishable from endometriosis.",
"<br><strong>Test:</strong> Cystoscopy with hydrodistention shows glomerulations (pinpoint mucosal haemorrhages) and Hunner ulcers as distention medium is released.Potassium chloride sensitivity test: after instilling a dilute solution of potassium chloride into the bladder with a catheter, the patient will note a change in urinary urgency and frequency scores.</p>",
"</dd>",
"<dt><a href='#Section2'>Pelvic inflammatory disease</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Fever, nausea, acute pain along with malodorous vaginal discharge and cervical motion tenderness/adnexal tenderness is typical for acute PID.Chronic PID may be indistinguishable from endometriosis.",
"<br><strong>Test:</strong> Cervical cultures for Neisseria gonorrhoea or Chlamydia trachomatis may be positive.Pelvic ultrasonography may show complex adnexal masses as distinguished from homogeneous, low-level echoes typically seen with endometrioma.</p>",
"</dd>",
"<dt><a href='#Section3'>Irritable bowel syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Change in bowel habits (alternating constipation and diarrhoea; bloating) may help differentiate. Dyschezia more typical of endometriosis.",
"<br><strong>Test:</strong> Diagnosis is usually clinical and based on an absence of ultrasound, MRI or laparoscopic findings of endometriosis.</p>",
"</dd>",
"<dt><a href='#Section4'>Ovarian cyst (benign)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> May be asymptomatic with an incidental pelvic mass or present with acute rather than chronic pain.",
"<br><strong>Test:</strong> Transvaginal ultrasound (TVUS): enlarged ovary with a simple or complex cystic structure emanating from the ovary as distinguished from homogeneous, low-level echoes typically seen with endometrioma. Ultrasound is ideal for differentiating liquid from solid material.</p>",
"</dd>",
"<dt><a href='#Section5'>Ovarian cancer, epithelial</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Typical symptoms represent advanced-stage cancer, and include weight gain despite lack of appetite, increased abdominal girth and altered bowel habits.Endometriosis may be an uncommon risk factor for developing epithelial ovarian cancer.",
"<br><strong>Test:</strong> TVUS: complex adnexal mass (solid and cystic) with multiple loculations or thick septa; ascites. Most patients present with advanced-stage disease.Histopathology: there are many cell types and various stains can be used to verify/differentiate.</p>",
"</dd>",
"<dt><a href='#Section6'>Pelvic floor tension myalgia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> May be unable to differentiate clinically.Clinically patients have chronic pelvic pain and dyspareunia (or inability to have intercourse due to spasm and pain).An experienced clinician can elicit focal spasm and tenderness on pelvic and rectovaginal examination.",
"<br><strong>Test:</strong> No diagnostic test available. Lack of positive findings on other investigations.</p>",
"</dd>",
"<dt><a href='#Section7'>Neuropathic pain</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Burning, shock-like pain associated with paraesthesia or dysaesthesia.",
"<br><strong>Test:</strong> No diagnostic test available. Lack of positive findings on other investigations.</p>",
"</dd>",
"<dt><a href='#Section8'>Uterine fibroids</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Many are asymptomatic, but often present with heavy and/or irregular menstrual bleeding.Pelvic examination may show an enlarged, nodular pelvic mass that can vary in size and shape.",
"<br><strong>Test:</strong> TVUS: concentric, solid, hypoechoic (dark) mass or masses within the endometrium (sub-mucosal), myometrium (intramural) or external (sub-serosal). Small fibroids may be isoechoic, but if calcified, fibroids can also appear hyperechoic (bright).</p>",
"</dd>",
"</dl>"].join("\n");