content=["<dl>",
"<dt><a href='#Section0'>Radial tunnel syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Radial tunnel syndrome is also associated with repetitive activities. [45]A history of acute trauma may be elucidated during the initial patient interview.Patients will experience pain localised over the radial neck approximately 4 finger-breadths distal to the lateral epicondyle.This pain may be exacerbated by pronation of the forearm with the elbow extended, resisted supination, and extension of the long fingers. [45]  [46]",
"<br><strong>Test:</strong> Both radial tunnel syndrome and lateral epicondylitis are primarily a clinical diagnosis.Physical examination will assist in differentiation by location of pain and exacerbation of symptoms with long finger extension.</p>",
"</dd>",
"<dt><a href='#Section1'>Radial capitellar plica</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Differentiated from lateral epicondylitis by passive flexion of the elbow while pronating and supinating the forearm. [34]This manoeuvre produces snapping or popping at the radial head. The snapping with this forearm manoeuvre does not occur with epicondylitis, and is highly suggestive of a plica.A history of trauma along with this finding on examination is highly suggestive.",
"<br><strong>Test:</strong> Usually differentiated from epicondylitis by findings on clinical examination.</p>",
"</dd>",
"<dt><a href='#Section2'>Osteoarthritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Osteoarthritis of the elbow is usually associated with a previous history of traumatic injury.Patients with osteoarthritis will report chronic pain, stiffness, mechanical symptoms, and weakness. [47]",
"<br><strong>Test:</strong> Radiographic studies in early disease may depict a preserved joint space in the radial capitellar and ulnohumeral joints. Advanced disease may demonstrate a complete loss of joint space and the presence of intra-articular loose bodies. [48]</p>",
"</dd>",
"<dt><a href='#Section3'>Primary ligamentous instability</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Damage to the ulnar collateral ligament may produce symptoms similar to those of medial epicondylitis due to repetitive valgus loading of the elbow. [18]On physical examination, patients with ulnar collateral ligament injury will have valgus instability with the elbow at 30 degrees of flexion. [18]",
"<br><strong>Test:</strong> Radiographic studies of the elbow may demonstrate an avulsion fracture of the sublime tubercle, as well as attenuation versus tear of the ligament when MRI is employed. [49]</p>",
"</dd>",
"<dt><a href='#Section4'>Cubital tunnel syndrome</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients with ulnar nerve entrapment (most commonly at the cubital tunnel posterior to the medial epicondyle) will report a history of medial-sided pain, numbness in the ulnar distribution, and hand weakness. [18]  [50]During physical examination a positive Tinel's sign may be induced above or below the medial epicondyle. This finding is consistent with ulnar nerve entrapment at the elbow. [18]",
"<br><strong>Test:</strong> Primarily differentiated by physical examination.Patients with findings consistent with ulnar nerve entrapment may benefit from an EMG and nerve conduction evaluation to determine the extent of nerve damage and assess the zone of compression. [51]</p>",
"</dd>",
"</dl>"].join("\n");