content=["<dl>",
"<dt><a href='#Section0'>Clavicle or humeral fracture</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Fractures can be associated with brachial plexus birth palsy (BPBP) but may be exclusive.Pseudoparalysis, which is a voluntary restriction or inhibition of motion not due to actual muscular paralysis, may appear clinically similar to BPBP.Crepitance will be noted at the fracture site, and return of normal function will be rapid (2-3 weeks) if no nerves have been injured.",
"<br><strong>Test:</strong> Radiographs are diagnostic of fractures in this area.</p>",
"</dd>",
"<dt><a href='#Section1'>Septic arthritis of the shoulder or proximal humeral osteomyelitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Paralysis developing late (not present at birth) should be suspected as possible infection.Pain with movement of the shoulder is suggestive of infection, although it could also be suggestive of fracture.",
"<br><strong>Test:</strong> Laboratory tests (full blood count with differential, erythrocyte sedimentation rate, and c-reactive protein) may suggest infection. Ultrasound or MRI will confirm effusion or bony involvement. Bone aspiration: positive culture is diagnostic of osteomyelitis.</p>",
"</dd>",
"<dt><a href='#Section2'>Spinal cord or brachial plexus tumour</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Paralysis developing after birth without signs of infection or with supraclavicular mass is suggestive of a tumour.",
"<br><strong>Test:</strong> Imaging (MRI or CT scan) is diagnostic of spinal cord or brachial plexus tumours.</p>",
"</dd>",
"<dt><a href='#Section3'>Parsonage-Turner syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients presenting with brachial plexus dysfunction after a viral illness may have this syndrome.Paralysis develops suddenly after a period of shoulder pain and is unrelated to birth.",
"<br><strong>Test:</strong> No differentiating tests are available because this is a diagnosis of exclusion. MRI of the cervical spine and shoulder and EMG nerve conduction studies of the affected extremity may be performed to localise possible site of injury with BPBP and to help to rule out other causes of sudden paralysis.</p>",
"</dd>",
"</dl>"].join("\n");