content=["<dl>",
"<dt><a href='#Section0'>Lymphoma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There may be no difference in signs and symptoms.Constitutional symptoms and widespread lymphadenitis are more common in lymphoma.TB lymphadenitis is most commonly found in the cervical or supraclavicular regions.",
"<br><strong>Test:</strong> Chest x-ray may show abnormalities consistent with prior pulmonary TB in about 25% of patients with TB lymphadenitis.FNA will usually be able to diagnose TB lymphadenitis; if this is non-diagnostic, excisional biopsy must be performed.</p>",
"</dd>",
"<dt><a href='#Section1'>Non-tuberculous mycobacteria lymphadenitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> There may be no difference in signs and symptoms.TB lymphadenitis predominates in patients older than 12 years and non-tuberculous mycobacteria (NTM) is more common in children younger than 12 years of age.TB lymphadenitis predominates in women of Asian background from TB-endemic areas. [1]",
"<br><strong>Test:</strong> Chest x-ray may show abnormalities consistent with prior pulmonary TB in about 25% of patients with TB lymphadenitis.In an adult with acid-fast bacilli (AFB) or caseating granulomas on FNA, empiric therapy for TB can be started. This is also true if a child has epidemiological risk factors for TB, pending results of culture.In a child with presumed NTM, the diagnosis must be proved with culture results. [20]  [67]</p>",
"</dd>",
"<dt><a href='#Section2'>Sarcoidosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Features of sarcodiosis, such as intrathoracic lymphadenopathy and arthralgias, may be present. A careful review of epidemiological risk factors for TB can be performed.",
"<br><strong>Test:</strong> Tuberculin skin testing (TST) will usually be negative with sarcoidosis and chest x-ray may have findings more consistent with TB or sarcoidosis.Granulomas are non-caseating in sarcoidosis, although it is not diagnostic.AFB may be seen on FNA in TB lymphadenitis. Culture for AFB is negative in sarcoidosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Malignant pleural effusion</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There may be no difference in signs and symptoms.",
"<br><strong>Test:</strong> TST may be negative in up to 40% of patients with pleural TB.CT scan of the chest may show findings more consistent with malignancy (particularly if primary bronchogenic) or with pulmonary TB. A search for a primary in metastatic disease may also diagnose the aetiology (e.g., in an effusion due to metastatic breast or ovarian cancer). Cytological evaluation of the pleural effusion may diagnose a malignant effusion.Pleural biopsy may reveal granulomas, AFB, or malignant pathology.Video-assisted thoracic surgery (VATS) differentiates between an effusion-caused TB and those caused by malignancy.</p>",
"</dd>",
"<dt><a href='#Section4'>Cryptococcal meningitis, other fungal CNS infections, neurosyphilis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> The differential diagnosis of TB meningitis includes disease processes that cause a subacute to chronic meningitis and a lymphocyte-predominant pleocytosis.Cranial nerve abnormalities are more common in TB.",
"<br><strong>Test:</strong> CSF analysis is the key to making the diagnosis.AFB and fungal stain and cultures are usually diagnostic.Nucleic acid amplification test (NAAT) of CSF may also help in diagnosis.An elevated adenosine deaminase (ADA) may support the diagnosis of TB. [68]TST has poor sensitivity with CNS TB (approximately 50%). [43]</p>",
"</dd>",
"<dt><a href='#Section5'>Inflammatory bowel disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> There may be no difference in signs and symptoms.The presence of epidemiological risk factors for TB, a positive TST, or chest x-ray findings consistent with TB all support TB as the aetiology.The presence of ascites is more consistent with a diagnosis of TB enteritis.",
"<br><strong>Test:</strong> Colonoscopy with biopsy is the best method for diagnosis, with a sensitivity of up to 80%.The presence of mesenteric lymphadenopathy with central necrosis is suggestive of TB. [59]</p>",
"</dd>",
"<dt><a href='#Section6'>Peritoneal carcinomatosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Epidemiological risk factors may be present in patients with TB.",
"<br><strong>Test:</strong> Cytological analysis of ascites identifies patients with malignant ascites.CT scan may identify a primary neoplasm.</p>",
"</dd>",
"<dt><a href='#Section7'>Spontaneous bacterial peritonitis (SBP)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> In patients with a history of cirrhosis and epidemiological risk factors for TB, a high index of suspicion must be maintained for TB peritonitis.Symptoms are more chronic in those with TB enteritis.",
"<br><strong>Test:</strong> Patients with TB peritonitis usually have ascites with a low serum-ascitic albumin gradient (SAAG) and lymphocytes &gt;30%. However, cirrhotics may have peritoneal TB with a low protein and PMNs &gt;250/mL, mimicking SBP.In TB peritonitis, CT scan may reveal abdominal lymphadenopathy.Differentiating tests include NAAT, ADA, AFB culture, and peritoneal biopsy.</p>",
"</dd>",
"<dt><a href='#Section8'>Fever of unknown origin (FUO)</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> There may be no difference in signs and symptoms.The presence of epidemiological risk factors for TB or coexistence of pulmonary TB may help diagnosis.",
"<br><strong>Test:</strong> EPTB, especially disseminated disease, may be responsible for FUO. TST will usually be negative. Diagnosis may require transbronchial, liver, or bone marrow biopsies.</p>",
"</dd>",
"</dl>"].join("\n");