content=["<dl>",
"<dt><a href='#Section0'>Chest wall pain</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Pain of chest wall origin is constant and non-cyclical.May be related to physical activity.On examination, the pain is elicited upon palpation of the chest wall by carefully displacing the breast tissue.",
"<br><strong>Test:</strong> Clinical differentiation usually suffices.</p>",
"</dd>",
"<dt><a href='#Section1'>Costochondritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Pain over the anteromedial aspect of the chest wall, over the costochondral cartilaginous junction.",
"<br><strong>Test:</strong> Clinical differentiation usually suffices.</p>",
"</dd>",
"<dt><a href='#Section2'>Fibroadenoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> More often occurs in younger women who have a well-circumscribed palpable breast mass.",
"<br><strong>Test:</strong> Biopsy of breast mass reveals fibroadenoma.</p>",
"</dd>",
"<dt><a href='#Section3'>Breast cancer</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May present with a palpable mass, often firm to palpation.Presence of skin retraction or fixation to the chest wall should raise the suspicion of breast cancer.",
"<br><strong>Test:</strong> Biopsy of breast mass reveals breast cancer and type.</p>",
"</dd>",
"<dt><a href='#Section4'>Intracystic papilloma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> May be able to feel small lump under nipple on examination.",
"<br><strong>Test:</strong> Breast biopsy is required for a definitive diagnosis and to rule out cancer.Ultrasound, ductogram, and cytological examination of discharge for malignant cells are also useful.</p>",
"</dd>",
"</dl>"].join("\n");