content=["<dl>",
"<dt><a href='#Section0'>Membranous nephropathy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There are no distinguishing clinical features.",
"<br><strong>Test:</strong> Light microscopy of renal biopsy specimen reveals thickened capillary walls with patent capillary lumina. Subepithelial deposits are seen and trichrome stain reveals spikes. Immunofluorescence microscopy reveals positive granular capillary wall staining for IgG, with C3 and both kappa and lambda light chains.</p>",
"</dd>",
"<dt><a href='#Section1'>Minimal change disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Responsible for most cases of nephrotic syndrome in children.Almost always associated with nephrotic syndrome at the onset of disease.",
"<br><strong>Test:</strong> Electron microscopy of renal biopsy specimen shows diffuse podocyte effacement. Light and immunofluorescence microscopy are normal.</p>",
"</dd>",
"<dt><a href='#Section2'>Amyloidosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Orthostatic hypotension and peripheral neuropathy often present.Can affect the heart, causing jugular venous distension and breathlessness.Periorbital purpura with eyelid petechiae is a specific sign.",
"<br><strong>Test:</strong> Serum or urine electrophoresis reveals monoclonal protein.Light microscopy of renal biopsy specimen reveals glomerular amyloid deposits with positive Congo red staining under polarised light. Electron microscopy reveals deposition of protein fibrils.</p>",
"</dd>",
"<dt><a href='#Section3'>Diabetic nephropathy</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hx of diabetes is present.Other features of diabetic tissue disease may be noted such as diabetic retinopathy on ophthalmoscopy.",
"<br><strong>Test:</strong> Renal biopsy reveals classic Kimmelstiel lesions (nodular glomerular intercapillary lesions) in 10% to 50% of cases. Arteriolar lesions with hyaline material involving both afferent and efferent vessels are prominent.</p>",
"</dd>",
"<dt><a href='#Section4'>Membranoproliferative glomerulonephritis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Associated with autoimmune diseases (SLE, Sjogren's), hepatitis C, endocarditis. May present with nephrotic syndrome. Glomerular haematuria may also be present. Complement levels may be low; cryoglobulins may be present.",
"<br><strong>Test:</strong> Light microscopy of renal biopsy specimen reveals a range of glomerular appearances from hypercellularity to sclerosis and mesangial expansion. Double contouring of the basement membrane ('tram-track' appearance) can be seen with silver stain. Dense deposits are seen in some types of the disease.</p>",
"</dd>",
"<dt><a href='#Section5'>Light chain deposition disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Liver and cardiac involvement in 25% of patients.Renal failure is rapid.",
"<br><strong>Test:</strong> Light microscopy of renal biopsy specimen shows nodular glomerulopathy with distortion of the glomerular architecture by deposition of amorphous, eosinophilic material.Immunofluorescence microscopy reveals monotypic light chains in the glomeruli.Electron microscopy reveals subendothelial deposits in the glomerulus and outer aspect of tubular basement membrane.</p>",
"</dd>",
"</dl>"].join("\n");