content=["<dl>",
"<dt><a href='#Section0'>Acute viral syndromes</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Very difficult to differentiate; lack of exposure to specific foods or absence of specific behaviours may help in differentiating.",
"<br><strong>Test:</strong> Occasionally, acute viral serology, in particular IgM, (presence or rise from baseline) may help diagnose specific viruses.</p>",
"</dd>",
"<dt><a href='#Section1'>Inflammatory bowel disease (IBD)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Initial presentation may be acute and mimic inflammatory diarrhoea caused by invasive pathogens.Protracted course together with systemic symptoms may help differentiate.",
"<br><strong>Test:</strong> Colonoscopy with biopsies and IBD serological markers helps in differentiation.</p>",
"</dd>",
"<dt><a href='#Section2'>Food allergies/intolerance</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> History of exposure to certain foods known to cause intolerance or allergies (milk, lactose, gluten) and relapsing symptoms with challenge.",
"<br><strong>Test:</strong> Coeliac markers are positive in most patients with gluten intolerance.Hydrogen breath test helps in diagnosing lactose intolerance.Colonoscopy and biopsies help in diagnosing milk allergies.</p>",
"</dd>",
"<dt><a href='#Section3'>Irritable bowel syndrome (IBS)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Total duration of symptoms should be more than 6 months with specific criteria of combination of abdominal bloating or pain relieved by defection and association with change in stool frequency and/or consistency without evidence of alarm signs or symptoms.Physical examination reveals a healthy non-toxic appearance without evidence of dehydration.",
"<br><strong>Test:</strong> All imaging and laboratory tests are usually within normal range.</p>",
"</dd>",
"<dt><a href='#Section4'>Microscopic colitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Typically present in older persons, long duration symptoms and lack of haematochezia or blood in stool.",
"<br><strong>Test:</strong> Colonoscopy revealing normal appearing mucosa and biopsies sowing lymphocytic infiltrates and/or thickened collagenous layer are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section5'>Acute appendicitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Localised right lower quadrant pain and peritoneal irritation are classic (guarding).",
"<br><strong>Test:</strong> CT scan of the abdomen is diagnostic.Elevated serum and urine WBCs.</p>",
"</dd>",
"<dt><a href='#Section6'>Acute cholecystitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Localised pain in RUQ and a positive Murphy sign are classic symptoms.",
"<br><strong>Test:</strong> Ultrasound showing gallbladder wall thickening, elevated alkaline phosphatase, bilirubin ALT and AST when biliary obstruction is present (choledocholithiasis).</p>",
"</dd>",
"<dt><a href='#Section7'>Acute pancreatitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Epigastric pain radiating to the back, history of excessive alcohol consumption in alcohol induced pancreatitis may help.",
"<br><strong>Test:</strong> Elevated serum amylase and lipase and CT scan findings are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section8'>Acute hepatitis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Jaundice is usually present.Risk factors for acute hepatitis B and C include unprotected sex and IV drug use.History of excessive alcohol consumption in alcoholic hepatitis.History of hepatotoxic medication use or overdose in drug induced hepatitis.Neurological signs and Kayser-Fleischer ring in Wilson's disease.",
"<br><strong>Test:</strong> Serology for acute hepatitis (acute hepatitis panel), serological markers of autoimmune hepatitis, serum ceruloplasmin, drugs level in particular acetaminophen can help.When leukopaenia and thrombocytopaenia present, tick-born/rickettsial infections (Rocky Mountain spotted fever and Ehrlichia) are considered.</p>",
"</dd>",
"<dt><a href='#Section9'>Malabsorption syndromes</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Chronic symptoms and significant malnourishment, history of intestinal surgery and extraintestinal manifestations of malnourishment and malabsorption are usually present.",
"<br><strong>Test:</strong> Stool alpha antitrypsin, low serum prealbumin, albumin and total protein, multiple vitamins and elements deficiency.</p>",
"</dd>",
"<dt><a href='#Section10'>Bowel obstruction</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Abdominal distention and pain and history of abdominal surgery.Lack of history suggestive of food poisoning.",
"<br><strong>Test:</strong> Distended bowel loops and air-fluid levels on acute abdominal series plain films. However, food poisoning may be associated with ileus and functional obstruction and same imaging findings.</p>",
"</dd>",
"<dt><a href='#Section11'>Radiation enteritis</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Patients have a history of receiving radiation therapy.",
"<br><strong>Test:</strong> Endoscopy and biopsy; histological findings support this diagnosis.</p>",
"</dd>",
"<dt><a href='#Section12'>Mesenteric ischaemia</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Occlusive or nonocclusive (the latter causes more chronic symptoms mainly postprandial).",
"<br><strong>Test:</strong> CT scan/endoscopy. Typical finding is thickening of the bowel wall in a segmental pattern.Endoscopic findings include pale mucosa with petechial bleeding. Bluish haemorrhagic nodules may be seen representing submucosal bleeding; these correspond to thumbprints seen on radiographic studies.</p>",
"</dd>",
"<dt><a href='#Section13'>Medication and drugs side-effects/toxicity</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> History of drugs ingestion/use.",
"<br><strong>Test:</strong> Urine and serum screen, blood drug level.</p>",
"</dd>",
"<dt><a href='#Section14'>Diverticulitis</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Leukocytosis and fever in an older patient.",
"<br><strong>Test:</strong> CT scan/WBC.</p>",
"</dd>",
"<dt><a href='#Section15'>Systemic vasculitis</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Multisystem involvement (skin, joints, blood) and chronic presentation.",
"<br><strong>Test:</strong> Biopsy shows vasculitis pattern (leukocytoclastic, necrotising).</p>",
"</dd>",
"</dl>"].join("\n");     