content=["<dl>",
"<dt><a href='#Section0'>Atopic dermatitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Pruritic, morbilliform, or maculopapular eruptions.",
"<br><strong>Test:</strong> Selected allergens evaluated for specific IgE based on history.Rash in the predilection sites for atopic dermatitis within 1 hour of an oral challenge. [37]</p>",
"</dd>",
"<dt><a href='#Section1'>Urticaria</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Appearance not necessarily related to food ingestion (e.g., penicillins, sulphonamides, muscle relaxants, diuretics, NSAIDs).Erythematous oedematous lesions on any part of the body.Typically pruritic, although occasionally painful or burning sensation reported.Dissipates within 24 hours leaving no residual markings.Up to 40% of cases of urticaria have associated angio-oedema (swelling of the deeper layers of the subdermis).Foods are not the cause of chronic urticaria (lasting &gt;6 weeks).",
"<br><strong>Test:</strong> Lack of response to in vitro IgE testing or skin prick testing.Foods are not the cause of chronic urticaria (lasting &gt;6 weeks).</p>",
"</dd>",
"<dt><a href='#Section2'>Auriculotemporal syndrome</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Recurrent episodes of facial flushing, sweating along the distribution of the auriculotemporal nerve.Occurs in response to gustatory stimuli. [38]",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section3'>Acute asthma exacerbation in children</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Fatigue, dyspnoea, exercise intolerance, aesthete body type, and wheezing, but seldom the only symptoms and signs. [39]",
"<br><strong>Test:</strong> Pulmonary function testing with diminished FEV1.Greater likelihood of progression to irreversible obstructive airway disease.</p>",
"</dd>",
"<dt><a href='#Section4'>Acute asthma exacerbation in adults</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Dyspnoea; may be precipitated by allergens, cold, or exercise; wheezing reversible on administration of bronchodilators.",
"<br><strong>Test:</strong> Pulmonary function testing with diminished FEV1.Greater likelihood of progression to irreversible obstructive airway disease.</p>",
"</dd>",
"<dt><a href='#Section5'>Food-induced pulmonary haemosiderosis (Heiner's syndrome)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Recurrent pneumonia associated with pulmonary infiltrates, haemosiderosis, GI blood loss, iron deficiency anaemia, and failure to thrive. [2]In infants, most often caused by non-IgE-mediated hypersensitivity to cows' milk.",
"<br><strong>Test:</strong> High titres of precipitating IgG antibodies to bovine milk proteins. [16]Chest x-ray with pulmonary infiltrates. [16]Symptoms improve with removal of cows' milk from the diet.</p>",
"</dd>",
"<dt><a href='#Section6'>Tracheo-oesophageal fistula</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Neonates.Regurgitation of feeding.Aspiration and pneumonia.",
"<br><strong>Test:</strong> Chest x-ray with air-distended oesophageal atretic pouch; the nasogastric tube coiled in this pouch.Also, excessive dilation of stomach as a result of fistula communication. [40]</p>",
"</dd>",
"<dt><a href='#Section7'>Pollen food syndrome (oral allergy syndrome)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Oropharyngeal pruritus and angio-oedema of the lips, oral mucosa, and soft palate. [41]Symptoms not likely to progress to systemic anaphylaxis.",
"<br><strong>Test:</strong> Double-blind placebo-controlled food challenge.Skin prick testing or in vitro assays with suspected fresh fruit or vegetable.Causative allergens in fruits and vegetables have homologous proteins to pollens of grasses, trees, and weeds. [41]</p>",
"</dd>",
"<dt><a href='#Section8'>Food protein-induced enterocolitis syndrome</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Manifests in the first few months of life. Projectile vomiting, diarrhoea, and failure to thrive. [16]Associated with ingestion of cows' milk or soya protein.Similar syndrome presents in older infants and children as a result of egg, wheat, rice, oat, peanut, nuts, chicken, turkey, and fish sensitivity. Shellfish sensitivity may be causative in adults.",
"<br><strong>Test:</strong> Oral food challenge will lead to vomiting within 1 to 4 hours after ingestion (caution: may cause severe hypotension).Elevation in peripheral blood neutrophils. [23]</p>",
"</dd>",
"<dt><a href='#Section9'>Food protein-induced colitis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Presents in first few months of life. [16]Infants with isolated finding of blood in the stool.",
"<br><strong>Test:</strong> Stool positive for blood in infants.</p>",
"</dd>",
"<dt><a href='#Section10'>Eosinophilic oesophagitis/gastroenteritis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Postprandial nausea, gastro-oesophageal reflux, vomiting, abdominal pain, and early satiety. Weight loss and failure to thrive in children. [16]",
"<br><strong>Test:</strong> Oesophageal or gastric biopsy shows dense eosinophilic infiltrates. [16]</p>",
"</dd>",
"<dt><a href='#Section11'>Gastroenteritis in children</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Persistent diarrhoea lasting from 1 to 8 days.Usually accompanied by fever.",
"<br><strong>Test:</strong> Presence of faecal lymphocytes.Microscopy and stool culture positive for causative organisms.Elevated WBC if sepsis; blood cultures positive for causative organisms.Clostridium difficile toxin present (i.e., in patients with recent prolonged antibiotic use).</p>",
"</dd>",
"<dt><a href='#Section12'>Gastroenteritis in adults</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Persistent diarrhoea lasting from 1 to 8 days. Usually accompanied by fever.",
"<br><strong>Test:</strong> Presence of faecal lymphocytes.Microscopy and stool culture positive for causative organisms.Elevated WBC if sepsis; blood cultures positive for causative organisms.Clostridium difficile toxin present (i.e., in patients with recent prolonged antibiotic use).</p>",
"</dd>",
"<dt><a href='#Section13'>Irritable bowel syndrome</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Recurrent abdominal pain or discomfort that is associated with a change in stool frequency or form.Mild and poorly localised tenderness in the RLQ and/or LLQ.",
"<br><strong>Test:</strong> Diagnosis is clinical and by exclusion of other causes (e.g., Crohn's disease, ulcerative colitis).</p>",
"</dd>",
"<dt><a href='#Section14'>Crohn's disease</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> FHx of Crohn's disease; more common in white people than in black or Asian people; age 15 to 40 years or 60 to 80 years.Crampy or constant abdominal pain with non-bloody, intermittent diarrhoea.Perianal lesions (e.g., skin tags, fistulae, abscesses, scarring) may be present.",
"<br><strong>Test:</strong> Abdominal radiography with small bowel or colonic dilation; calcification; sacroiliitis; intra-abdominal abscesses.CT and MRI with skip lesions, bowel wall thickening, surrounding inflammation, abscess, fistulae.Bowel biopsy histology demonstrates transmural non-caseating granulomas.</p>",
"</dd>",
"<dt><a href='#Section15'>Ulcerative colitis</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Diarrhoea and haematochezia.Cramps, anorexia, weight loss, mild anaemia, malaise, and low-grade or intermittent fever. [42]",
"<br><strong>Test:</strong> Abdominal radiography with dilated colon, intra-abdominal free air, perforation.Colonic biopsy histology of acute and chronic inflammation with polymorphonuclear leukocytes infiltrating the submucosa. [42]</p>",
"</dd>",
"<dt><a href='#Section16'>Hiatal hernia</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Intolerance to spicy or acidic foods, particularly with recumbency and after retiring for the evening.Mid-epigastric to lower thoracic discomfort relieved with prolonged sitting position or elevation of head of bed.Specific lack of cutaneous or respiratory symptoms.",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Upper GI series with gastric cardia herniated 2 cm above the hiatus.</p>",
"</dd>",
"<dt><a href='#Section17'>Pyloric stenosis</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> Vomiting, failure to thrive.Pyloric mass. [43]",
"<br><strong>Test:</strong> Abdominal ultrasound with pyloric thickness &gt;4 mm or an overall pyloric length &gt;14 mm. [43]</p>",
"</dd>",
"<dt><a href='#Section18'>Hirschsprung's disease</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> Abdominal distention and stool retention.Toxic megacolon, peritonitis, perforation.",
"<br><strong>Test:</strong> Barium enema demonstrates segmental narrowing with ballooning of the proximal part of the bowel.Rectal/colon biopsy absence of ganglion cells.</p>",
"</dd>",
"<dt><a href='#Section19'>Pancreatic insufficiency (e.g., cystic fibrosis)</a></dt>",
"<dd id='Section19'>",
"<p><strong>Sign & Symptoms:</strong> Chronic diarrhoea.Steatorrhoea.",
"<br><strong>Test:</strong> Elevated sweat chloride levels (&gt;60 mmol/L) in cystic fibrosis.</p>",
"</dd>",
"<dt><a href='#Section20'>Gastro-oesophageal reflux disease</a></dt>",
"<dd id='Section20'>",
"<p><strong>Sign & Symptoms:</strong> Heartburn.Hiatal hernia and advancing age.Acidic reflux into oral cavity.Absence of cutaneous or respiratory involvement.",
"<br><strong>Test:</strong> Diagnosis is clinical.A therapeutic trial of a proton-pump inhibitor can serve for both diagnosis and initial treatment.</p>",
"</dd>",
"<dt><a href='#Section21'>Cholecystitis</a></dt>",
"<dd id='Section21'>",
"<p><strong>Sign & Symptoms:</strong> RUQ or epigastric abdominal pain. [44]  Pain may radiate to the right shoulder or back and is usually steady and severe.Associated symptoms: nausea, vomiting, and anorexia.Often a history of fatty food ingestion about 1 hour or more before initial onset of pain.",
"<br><strong>Test:</strong> Elevated leukocytes with a left shift on FBC.Ultrasound or cholescintigraphy may be needed to confirm the diagnosis. [44]</p>",
"</dd>",
"<dt><a href='#Section22'>Coeliac disease</a></dt>",
"<dd id='Section22'>",
"<p><strong>Sign & Symptoms:</strong> Persistent diarrhoea with gluten ingestion.Presence of dermatitis herpetiformis.",
"<br><strong>Test:</strong> Low Hb and microcytic red cells on FBC.Immunoglobulin A-tissue transglutaminase (IgA-tTG) titre above normal for laboratory.Endomysial antibody (EMA) titre elevated.Biopsy of the small bowel helpful when positive, but a negative result does not rule out the disease.Human leukocyte antigen DQ2DQ8 testing is highly sensitive (90% to 95%) for coeliac disease but not very specific.</p>",
"</dd>",
"<dt><a href='#Section23'>Food poisoning (e.g., Clostridium botulinum, Staphylococcus aureus, Escherichia coli)</a></dt>",
"<dd id='Section23'>",
"<p><strong>Sign & Symptoms:</strong> Abdominal pain, nausea, vomiting.Fever may appear from 1 to 72 hours after ingestion. [43]",
"<br><strong>Test:</strong> Faecal leukocytes present and stool culture grows organism.Blood cultures grow organism.</p>",
"</dd>",
"<dt><a href='#Section24'>Alcohol overdose</a></dt>",
"<dd id='Section24'>",
"<p><strong>Sign & Symptoms:</strong> In early acute intoxication, euphoria, giddiness, and loss of inhibitions. [30]  Nausea, vomiting, abdominal pain, facial flushing, ataxia, and diminished reflexes.In late acute intoxication, CNS depression becomes generalised, leading to ataxia, nystagmus, slurred speech, and sedation. May progress to coma, loss of protective airway reflexes, autonomic dysfunction, hypothermia, death.",
"<br><strong>Test:</strong> With acute intoxication an elevated blood alcohol level is detectable.</p>",
"</dd>",
"<dt><a href='#Section25'>Lactose intolerance</a></dt>",
"<dd id='Section25'>",
"<p><strong>Sign & Symptoms:</strong> Typically 8 to 15 years of age.Crampy abdominal pain, bloating, and acidic diarrhoea. [45]",
"<br><strong>Test:</strong> Trial elimination diet therapeutic.Positive hydrogen breath test, defined as a rise in breath hydrogen &gt;20 ppm within 90 minutes of ingestion of 50 g of lactose. [45]</p>",
"</dd>",
"<dt><a href='#Section26'>Toxic reactions (e.g., scombroid poisoning, ciguatera poisoning, saxitoxin)</a></dt>",
"<dd id='Section26'>",
"<p><strong>Sign & Symptoms:</strong> Cutaneous symptoms of prolonged flush in the absence of urticaria.Several people dining from the same meal may experience symptoms. [16]",
"<br><strong>Test:</strong> Normal serum tryptase and elevated histamine. [16]May have normal serum tryptase and histamine in IgE-mediated responses.</p>",
"</dd>",
"<dt><a href='#Section27'>Accidental contamination (pesticide or antibiotics)</a></dt>",
"<dd id='Section27'>",
"<p><strong>Sign & Symptoms:</strong> Excessive salivation, lacrimation, bronchorrhoea, urinary and faecal incontinence, and vomiting. [46]",
"<br><strong>Test:</strong> Atropine (1 to 2 mg intravenously as a single dose) is given as a therapeutic trial in all suspected cases or when diagnosis is in doubt. Lack of anticholinergic response is positive test.Plasma cholinesterase and RBC cholinesterase used to confirm diagnosis.Specific IgE may be present with inadvertent allergy to antibiotic ingested.</p>",
"</dd>",
"<dt><a href='#Section28'>Fungal toxins (e.g., aflatoxins, trichothecenes, ergots)</a></dt>",
"<dd id='Section28'>",
"<p><strong>Sign & Symptoms:</strong> Fever, malaise, vomiting, and jaundice. [47]",
"<br><strong>Test:</strong> Absence of specific IgE.</p>",
"</dd>",
"<dt><a href='#Section29'>Caffeine overdose</a></dt>",
"<dd id='Section29'>",
"<p><strong>Sign & Symptoms:</strong> Overdose may lead to agitation, vasoconstriction, tremor, and hypertension. [46]",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section30'>Theobromine (e.g., tea, chocolate) intoxication</a></dt>",
"<dd id='Section30'>",
"<p><strong>Sign & Symptoms:</strong> Nausea, vomiting, anxiety, nervousness, and insomnia are evident in mild intoxication. Seizures occur in severe poisonings. [46]",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section31'>Serotonin (e.g., banana, tomato) overdose</a></dt>",
"<dd id='Section31'>",
"<p><strong>Sign & Symptoms:</strong> Diarrhoea, headache, and fatigue if ingested in large amounts. [48]",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section32'>Food phobias/aversions</a></dt>",
"<dd id='Section32'>",
"<p><strong>Sign & Symptoms:</strong> May mimic adverse food reactions.",
"<br><strong>Test:</strong> Absence of specific IgE.Double-blind placebo-controlled food challenge (DBPCFC).Symptoms are not reproducible with DBPCFC. [16]</p>",
"</dd>",
"</dl>"].join("\n");