content=["<dl>",
"<dt><a href='#Section0'>Asthma exacerbation</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Wheezing is paroxysmal, intermittent, usually diffuse, and decreases after bronchodilators. Wheezing is polyphonic, characterised by many different pitches. Cough is more prominent in asthma than in foreign body aspiration, and is triggered by exercise, cold, sleep, and allergens; there is a personal and/or family history of atopy or asthma. [33]",
"<br><strong>Test:</strong> Chest x-ray shows peribronchial cuffing and hyper-inflation, but does not rule out foreign body aspiration. Pulmonary function tests usually show reversible obstructive ventilatory impairment. [33]</p>",
"</dd>",
"<dt><a href='#Section1'>Cystic fibrosis with exacerbation</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Wheezing presents early in life; poor weight gain, diarrhoea, and recurrent sinus and pulmonary infections; nasal examination may reveal polyps. Cough is productive and 'wet,' suggesting a suppurative process such as bronchiectasis; there may be a family history of bronchiectasis. [33]",
"<br><strong>Test:</strong> Sweat chloride test; chest x-ray may reveal bronchiectasis, but CT scan is more sensitive. [34]</p>",
"</dd>",
"<dt><a href='#Section2'>Acute COPD exacerbation</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Wheezing is diffuse, associated with increased mucous production and progressive dyspnoea.",
"<br><strong>Test:</strong> Chest x-ray shows peribronchial cuffing and hyper-inflation, but does not rule out foreign body aspiration. Pulmonary function tests reveal obstructive ventilatory impairment.</p>",
"</dd>",
"<dt><a href='#Section3'>Croup</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Seen in children from 6 months to 4 years old. [35]  The cough is characteristically described as having a barky, seal-like pattern and is often accompanied by stridor and chest wall or sternal in-drawing. Symptoms are typically worse at night, and increase with agitation.",
"<br><strong>Test:</strong> Diagnosis made on clinical grounds. Subglottic oedema may be seen on x-ray or at laryngoscopy, if performed.</p>",
"</dd>",
"<dt><a href='#Section4'>Epiglottitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patient may have high fever, sore throat, dysphonia, muffled voice, drooling, and dysphagia, in addition to stridor and dyspnoea. [35]  The child may assume the 'tripod position' - sitting up with the neck extended and leaning forwards with the jaw thrust out.",
"<br><strong>Test:</strong> Lateral neck x-ray can show the swollen epiglottis and aryepiglottic folds 'thumb sign', but should be done only in case of doubt and after the airway is secured. [35]</p>",
"</dd>",
"<dt><a href='#Section5'>Central airway obstruction</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Wheezing is slowly progressive and unilateral in cases of obstruction distal to the main carina. Neonatal onset of cough suggests congenital tracheobronchomalacia. [33]  [36]",
"<br><strong>Test:</strong> Chest x-ray may show tracheal or bronchial narrowing; chest CT scan provides details about the mediastinum, and is able to localise and quantify the degree of airway obstruction. [36]</p>",
"</dd>",
"<dt><a href='#Section6'>Infectious pneumonia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Fever, rales, tachypnoea, and cough productive of frothy or purulent sputum may occur if infection supervenes after foreign body aspiration.",
"<br><strong>Test:</strong> Chest x-ray may show lobar consolidation.</p>",
"</dd>",
"</dl>"].join("\n");