content=["<dl>",
"<dt><a href='#Section0'>Staphylococcal skin lesions</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Distinct pustules, subcutaneous abscesses, purulent purpura often present in this condition. [1]",
"<br><strong>Test:</strong> Blood culture: positive for staphylococcal infection.Aspiration and microscopy: reveals staphylococci and polymorphonuclear leukocytes. [1]</p>",
"</dd>",
"<dt><a href='#Section1'>Erysipelas</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of recent pharyngitis. Infants and older people are usually affected. Pruritus and burning are present before the dermatosis. [1]  Sharply delineated, painful lesion with a bright red, oedematous, indurated (peau d'orange) appearance. Bullae only in 5% of cases.",
"<br><strong>Test:</strong> Antistreptococcal antibodies may be detectable.</p>",
"</dd>",
"<dt><a href='#Section2'>Cellulitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Absence of purple or red bullous lesions, absence of crepitus, intact sensation distal to the affected area, and comparatively slow spread. Systemic toxicity (e.g., renal failure, hypotension, and acidosis) usually absent with cellulitis.",
"<br><strong>Test:</strong> Serous discharge may be expressed on compression of the wound margins, and streptococci can be identified on a Gram-stained smear. [1]Imaging studies (radiography, CT, and MRI): absence of the gas, fascial enhancement, and soft-tissue oedema characteristic of gangrene.</p>",
"</dd>",
"<dt><a href='#Section3'>Insect bites</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History of insect or spider bite, or suitable clinical scenario. The bite of the brown recluse spider (Loxosceles reclusa) can produce a necrotising skin lesion that resembles infectious gangrenous cellulitis. Fever is not commonly present, but the occurrence of fever and chills 24 to 48 hours after the bite enhances the mimicry. [1]",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");