content=["<dl>",
"<dt><a href='#Section0'>Carpal tunnel syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Paraesthesia in the thumb, index, and long finger typically worse at night (patients with ganglion cysts rarely describe paraesthesia). This may awaken the patient from sleep. With advanced cases, weakness of the hand and difficulties with fine motor tasks may become evident.Physical examination can reproduce the symptoms of paraesthesias by direct compression of the median nerve at the volar wrist crease or placing the patient in a position of wrist flexion for up to 1 minute. Typically, a Tinel sign is present with tapping over the median nerve at the wrist.",
"<br><strong>Test:</strong> Electromyelographic evaluation will show focal slowing of conduction velocity in the median sensory nerves across the carpal tunnel; prolongation of the median distal motor latency; possible decreased amplitude of median sensory and/or motor nerves.</p>",
"</dd>",
"<dt><a href='#Section1'>Lipoma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Does not trans-illuminate. Mass usually not entirely spherical.",
"<br><strong>Test:</strong> Aspiration does not yield any fluid.Ultrasound demonstrates a non-cystic mass.MRI demonstrates a well-circumscribed mass with increased signal intensity on T1-weighted image.</p>",
"</dd>",
"<dt><a href='#Section2'>Giant cell tumour of the tendon sheath</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Mass is more solid and does not trans-illuminate. Mass is fixed to the underlying tendon sheath and is therefore is less mobile than a ganglion cyst.",
"<br><strong>Test:</strong> Aspiration does not yield fluid.MRI or ultrasound confirms solid tumour located adjacent to tendon sheath.</p>",
"</dd>",
"<dt><a href='#Section3'>Tenosynovitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Diffuse swelling and bogginess of the tenosynovium overlying the tendons. Usually tracks along the tendon in a longitudinal fashion, not a discrete mass. Can have transverse band-like pattern across the wrist.",
"<br><strong>Test:</strong> Aspiration does not yield any fluid.MRI demonstrates increased fluid uptake along the tendons, not a well-defined cystic structure.</p>",
"</dd>",
"<dt><a href='#Section4'>Carpal instability</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Disruption of the normal carpal kinematics usually preceded by trauma to the wrist. Can result in a change in lunate position where the proximal pole of the scaphoid can be palpated. No trans-illumination, compressibility, or movement of the mass on examination.",
"<br><strong>Test:</strong> Radiographs demonstrate a dorsally or volarly angulated lunate with regards to the capitate, and a widening of the scapholunate or lunotriquetral joint space.</p>",
"</dd>",
"<dt><a href='#Section5'>Osteoarthritis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Usually pre-existing arthritic conditions, typically of the scaphotrapeziotrapezoid joint.Palpable hard, firm, non-cystic, non-mobile mass which does not trans-illuminate.",
"<br><strong>Test:</strong> PA and lateral view radiographs of the wrist show degenerative changes (osteophyte or arthritic surfaces of the scaphotrapeziotrapezoid joint).</p>",
"</dd>",
"<dt><a href='#Section6'>Radial artery aneurysm</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Mass may be pulsatile and a thrill palpated. Does not trans-illuminate.",
"<br><strong>Test:</strong> Aspiration may yield arterial blood and is not recommended.Ultrasound with Doppler flow will demonstrate blood flow within the structure.</p>",
"</dd>",
"<dt><a href='#Section7'>Posterior interosseous nerve neuroma</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Mass not as freely mobile (anchored to posterior interosseous nerve in posterior aspect of the wrist) and does not trans-illuminate.",
"<br><strong>Test:</strong> Aspiration does not yield any fluid.Ultrasound demonstrates non-cystic mass.MRI demonstrates mass without increased signal intensity on T2-weighted image.</p>",
"</dd>",
"<dt><a href='#Section8'>Soft tissue sarcoma</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Typically not well circumscribed nor as freely mobile (can be difficult to distinguish given the varied presentation of sarcomas).",
"<br><strong>Test:</strong> Referral to specialised centre recommended for aspiration or biopsy.MRI helps determine lesion location and varied characteristics. May show ring enhancement or varied signal intensity.</p>",
"</dd>",
"<dt><a href='#Section9'>Osteosarcoma</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Typically not well circumscribed or mobile (can be difficult to distinguish given the varied presentation of sarcomas).",
"<br><strong>Test:</strong> Referral to specialised centre recommended for aspiration or biopsy.MRI helps determine lesion location and varied characteristics. May show ring enhancement or varied signal intensity.</p>",
"</dd>",
"<dt><a href='#Section10'>Septic arthritis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with an erythematous, warm, swollen joint. There is pain associated with minimal motion of the radiocarpal joint. An effusion can often be detected.",
"<br><strong>Test:</strong> Difficult to differentiate from crystalline arthropathy without joint aspiration.White cell count, ESR, and C-reactive protein levels usually elevated.Joint aspiration will yield purulent material with increased neutrophil count and typically bacteria on Gram stain and culture.</p>",
"</dd>",
"<dt><a href='#Section11'>Crystalline arthropathy</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents with an erythematous, warm, swollen joint. There is pain associated with motion of the radiocarpal joint. An effusion can often be detected.",
"<br><strong>Test:</strong> Difficult to differentiate from septic arthritis without joint aspirationUric acid levels usually elevated. Aspiration of the joint will yield crystals on polarised microscopic examination.</p>",
"</dd>",
"<dt><a href='#Section12'>Old trauma</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Previous history of injury of the wrist or carpus may cause malunited fractures with palpable deformity or ligament disruptions resulting in carpal instability.",
"<br><strong>Test:</strong> PA and lateral view radiographs of the wrist help detect previous traumatic events. Bony malunion of fractures, degenerative disease, or signs of carpal instability may be present.</p>",
"</dd>",
"</dl>"].join("\n");