content=["<dl>",
"<dt><a href='#Section0'>Oral lichen planus</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> A chronic inflammatory mucocutaneous disease which commonly manifests on the gingiva and is characterised by red, non-swollen gingivae with painful atrophic/ulcerative lesions. White papular, reticular, and plaque-type lesions, usually asymptomatic, may also be found as the only sign of gingival involvement or occur at the periphery of the atrophic lesions. It is generally nonresponsive to routine oral hygiene procedures. It may also develop on oral mucosa (50%-70% of cases), other mucosal surfaces and on skin of extremities. [30]  Oral lesions may occur in the absence of skin lesions.View imageView image",
"<br><strong>Test:</strong> Direct immunofluorescence is negative for all auto-antibodies but positive for fibrinogen fluorescence outlining the basement membrane zone with irregular extensions into the superficial lamina propria (shaggy appearance). [31]Histopathology reveals a dense lymphocytic infiltrate with possible possible changes to the epithelium.</p>",
"</dd>",
"<dt><a href='#Section1'>Pemphigoid</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> A group of chronic, mucocutaneous autoimmune disorders in which autoantibodies are directed towards components of the basement membrane and characterised by bullae and blisters that rupture leaving superficial, painful, persistent ulcerations. The average age of onset is 50 to 60 years. Since healing may occassionally leave scars, ocular involvement may lead to conjunctival scarring and blindness. The oral lesions usually do not result in scarring. If only mucous membranes are affected, the term mucous membrane pemphigoid (MMP) is used. [32]  Gingival involvement is characterised by the clinical pattern known as desquamative gingivitis or by localised bullous formation quickly evolving into painful and persisting erosions. [30] View image",
"<br><strong>Test:</strong> Linear band of IgG, C3, and sometimes other immunoglobulins as well as fibrin at the basement membrane zone. [33]  [34]Indirect immunofluorescence (IIF) is negative, but salt-split-skin IIF is positive in up to 50% of the cases. [35]</p>",
"</dd>",
"<dt><a href='#Section2'>Pemphigus</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> A group of autoimmune diseases characterised by formation of intraepithelial bullae in skin and mucous membranes. The average age of onset is 50 years and it is rarely seen in children. A positive Nikolsky sign is seen (top layers of skin slide over lower layers when rubbed). The typical oral lesions are chronic, superficial, ragged, irregular, painful erosions. Gingival involvement usually appears in the form of desquamative gingivitis. Since the bulla formation is located in the spinous cell layer, the chance of finding an intact bulla on the oral mucosa is quite small. Lesions may develop on mucosal surfaces earlier than they develop on the skin, although skin lesions are more common. Conjunctival involvement is uncommon and, unlike pemphigoid, the ocular lesions of pemphigus do not produce scarring. [32] View image",
"<br><strong>Test:</strong> Direct immunofluorescence is positive for intercellular IgG and C3 between epithelial cells; no linear reactivity along basement membrane zone. IIF is positive. [33]  [34]</p>",
"</dd>",
"<dt><a href='#Section3'>Lupus erythematosus</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Oral mucosal lesions resemble erosive lichen planus with erosions and striae but also demonstrate atrophy with fine white stippling not seen in erosive lichen planus. [32]  Systemic lupus erythematosus may also give rise to gingival ulceration and increased plaque-related gingivitis secondary to Sjogren's syndrome.View image Can give rise to desquamative gingivitis.",
"<br><strong>Test:</strong> Direct immunofluorescence is positive for IgM, IgG, and/or C3 in a shaggy or granular band at the basement membrane zone. [36]  Serum ANAs and antidouble-stranded DNA usually occur in SLE.</p>",
"</dd>",
"<dt><a href='#Section4'>Desquamative gingivitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> A clinical reaction pattern produced by several disorders that involve the gingiva. This pattern is characterised by an extensive desquamation and/or erosion of the affected gingival, particularly in the buccal aspect of anterior teeth. Often marginal gingival is unaffected in the absence of plaque accumulation. [32]",
"<br><strong>Test:</strong> Biopsy reveals in about 80% of cases features that are diagnostic of mucous membrane pemphigoid and oral lichen planus. Less frequently biopsy shows features that are diagnostic of pemphigus vulgaris, linear IgA disease, epidermolysis bullosa acquisita, systemic lupus erythematosus, chronic ulcerative stomatitis, and paraneoplastic pemphigus. [37]</p>",
"</dd>",
"<dt><a href='#Section5'>Drug-associated gingival enlargement</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients have a 1- to 3-month minimum history of therapy with phenytoin, cyclosporine, or calcium-channel blockers such as nifedipine and less commonly amlodipine, verapamil, felodipine, and diltiazem. [38]  Gingiva is often of normal colour with enlargement ranging from focal to extensive enlargement that covers most of the teeth and may impair mastication of food. In the presence of secondary inflammation caused by dental plaque, the gingiva may be reddened, puffy, and painful.View imageView image",
"<br><strong>Test:</strong> Diagnosis is by clinical oral exam and review of medical history. Treatment options are usually oral hygiene maintenance, gingival surgery and rarely substituting an acceptable alternative drug.</p>",
"</dd>",
"<dt><a href='#Section6'>Primary herpetic gingivostomatitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Primary herpetic gingivostomatitis has a bimodal age distribution of 2 to 3 years and &gt;60 years. [32]  Clusters of small vesicles coalesce to form blisters that rupture to leave painful mucosal ulcerations. The gingivae are enlarged, very erythematous, and painful. The gingival features can be in a form similar to necrotising ulcerative gingivitis, but gingival lesions are less severe and without significant haemorrhage. More significantly, other mucosal surfaces are likely involved with clusters of painful ruptured vesicles.View image Affected patients may be febrile, have cervical lymphadenopathy and occassionally skin rashes.",
"<br><strong>Test:</strong> No specific tests are needed. Cytological smear may confirm viral inclusions. The disease is self-limiting, lasting up to 2 weeks in immunocompetent patients. Recurrence suggests immunodeficiency.</p>",
"</dd>",
"<dt><a href='#Section7'>Allergic reactions</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Allergic reactions occasionally occur after the use of mouthwashes, toothpastes, or chewing gums. The allergens responsible for such reactions may be flavour additives (e.g., cinammon) or preservatives, or may be contained in materials or drugs used by dentists or in foods, natural products, or lipsticks. [30]  Clinically, the allergic reaction appears as a swollen red area, sometimes with painful ulcerations or white striae. This disorder can affect other mucosal surfaces where the allergen makes contact. Plasma cell gingivitis is a distinctive form of allergic reaction characterised by a dense inflammatory infiltrate consisting predominantly of plasma cells. [32] View image",
"<br><strong>Test:</strong> Withdrawal of suspected offending agent brings relief within 1 week. [39]  [40]Patch testing may be useful. [41]</p>",
"</dd>",
"<dt><a href='#Section8'>Leukaemia</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Leukemia presents in the oral cavity with spontaneous hemorrhage, petechiae and possible pain. [32]  Gingival enlargement is most likely with acute myeloid leukaemia. Ulcers may be present on the gingival and the mucosal surfaces. Gingival manifestations are more common in acute than chronic leukaemia. View image",
"<br><strong>Test:</strong> Full blood count and blood film will usually establish the leukaemic type.</p>",
"</dd>",
"<dt><a href='#Section9'>Primary and metastatic carcinoma</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Most gingival carcinomas, both primary and metastatic, present with localised exophytic masses rather than diffuse pseudo-inflammatory changes generally associated with gingivitis.View imageView image",
"<br><strong>Test:</strong> Radiology and biopsy. Primary gingival carcinoma usually shows squamous epithelial carcinoma; findings for metastatic disease are indicative of the primary carcinoma.</p>",
"</dd>",
"<dt><a href='#Section10'>HIV linear gingivitis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> HIV linear gingivitis is characterised by a distinct 2- to 3-mm linear band of pronounced erythema along the gingival margin directly adjacent to the teeth that does not respond to conventional oral hygiene procedures. [32]",
"<br><strong>Test:</strong> No specific diagnostic test. Non-response to standard therapy is suggestive. Confirm HIV status. Some cases are associated with candidiasis.</p>",
"</dd>",
"<dt><a href='#Section11'>Foreign body gingivitis</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Gingival inflammation associated with foreign bodies located in the connective tissue deep to the sulcular epithelium. It often presents as a red or combined red-white lesion frequently misdiagnosed as oral lichen planus. Pain or sensitivity is a common finding and the lesion does not resolve with optimisation of oral hygiene. Foreign bodies can originate from a wide variety of dental materials. [32]",
"<br><strong>Test:</strong> Diagnosis is from history and clinical features.Biopsy demonstrates a non-specific pattern of chronic or subacute mucositis and a foreign body (but in some cases the foreign material may be too fine to be detected).When granulomatous inflammation is microscopically found (approximately 20% of cases) and a foreign body is not detected, the clinician must search for signs and symptoms of granulomatous diseases (Crohn&rsquo;s disease, sarcoidosis, tuberculosis, orofacial granulomatosis). [32]</p>",
"</dd>",
"<dt><a href='#Section12'>Orofacial granulomatosis</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> An idiopathic disorder due to an abnormal immune reaction. Lips are frequently affected and show a non-tender, persistent enlargement. The tongue may develop fissures, oedema, erosions, paraesthesia, and taste alteration. Gingival lesions present as swelling and slight eythema mimicking plaque-related gingivitis, or as painful erosions. [30]",
"<br><strong>Test:</strong> Biopsy reveals a non-specific granulomatous inflammation associated with negative stains for organisms and no foreign body. Local and systemic granulomatous diseases must be considered in the differential diagnosis.</p>",
"</dd>",
"<dt><a href='#Section13'>Pyostomatitis vegetans</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> A relatively rare, pustular disorder of the oral mucosa associated with inflammatory bowel diseases, particularly ulcerative colitis or Crohn&rsquo;s disease. The typical lesions of this disorder are multiple, painless, yellow-white, vegetative mucosal folds and microabscesses, which may be present on both gingival and oral mucosa. [32]",
"<br><strong>Test:</strong> Biopsy reveals an acantholytic appearance of the epithelium due to the presence of numerous eosinophils, often forming intraepithelial microabscesses.Direct immunofluorescence rules out chronic bullous oral diseases.</p>",
"</dd>",
"<dt><a href='#Section14'>Linear IgA disease</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Oral lesions present as desquamative gingivitis alone or in association with vesicles, painful erosions, and ulceration. [42]  Lesions affect the hard and soft palates, tonsillar pillars, buccal mucosa, tongue, and gingiva. Oral lesions occur always in the presence of skin lesions. [43]",
"<br><strong>Test:</strong> Direct immunofluorescence is characterised by linear deposition of IgA along the dermoepidermal basement membrane zone. [32]  Circulating antibasement membrane IgA may be detected using IIF in approximately 30% of patients.Exclusive oral lesions showing linear IgA staining at the basement membrane zone should be considered mucous membrane pemphigoid not linear IgA disease. [44]</p>",
"</dd>",
"<dt><a href='#Section15'>Wegener's granulomatosis</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Oral involvement is rare. [32]  When present, it is considered an early sign of disease. Characteristic lesions include dramatic gingival hyperplasia with short bulbous, friable, and haemorrhagic projections beginning in the interdental papillae, commonly referred to as 'strawberry gingivitis'. The upper gingivae are the most commonly affected site in the mouth.",
"<br><strong>Test:</strong> Biopsy shows leukocytoclastic vasculitis. [45]  In oral biopsies, due to the paucity of large vessels, vasculitis may be difficult to demonstrate. Gingival biopsy specimens usually show prominent vascularity with extensive red blood cell extravasation. [32]Circulating perinuclear antineutrophil cytoplasm (p-ANCA) or cytoplasmic antineutrophil cytoplasm (c-ANCA) antibody may be detected.Indirect immunofluorescence (IIF) is positive for cytoplasmic antineutrophil cytoplasm antibody (c-ANCA). A positive reaction for proteinase 3, the major antigen for c-ANCA that resides in the azurophilic granules of neutrophils, is needed to confirm the positive IIF for c-ANCA. [46]</p>",
"</dd>",
"<dt><a href='#Section16'>Erythema multiforme</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Acute onset of symmetrically distributed cutaneous target lesions often accompanied by mucous membrane involvement. [32]  Gingival involvement is extremely rare but may give rise to desquamative gingivitis and/or gingival ulceration. Patients may have a recent history of HSV infection, mycoplasma infection, drug therapy (e.g., anticonvulsives and antibiotics) or immunisation.View image",
"<br><strong>Test:</strong> Histopathology is rarely helpful as the features are usually non-specific. Hence diagnosis is based on clinical features and exclusion of other vesiculo-erosive disorders. [47]</p>",
"</dd>",
"<dt><a href='#Section17'>Agranulocytosis</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> Gingiva appears as necrotising ulcerative gingivitis, but patient has a history of exposure to drugs that cause decreased granulocyte production, such as anticancer chemotherapeutic agents, or a history of congenital disease associated with decreased levels of granulocyte-specific colony-stimulating factor (G-CSF). Malaise, fever, pharyngitis, and painful stomatitis may accompany necrotic, punched-out ulcerations of multiple mucosal surfaces.",
"<br><strong>Test:</strong> Discontinuation of the suspect drug leading to resolution within 2 weeks may be diagnostic.FBC shows granulocytopenia (&lt;0.5 X10^9/L or &lt;500 cells/mm^3) and normal erythrocytes and platelets. [32]</p>",
"</dd>",
"<dt><a href='#Section18'>Histoplasmosis</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> Very rare. Oral lesions may occur with disseminated form of the disease in older or immunocompromised patients. [32]  They appear as chronic ulcers with firm rolled margins and may resemble oral carcinoma of the gingiva.",
"<br><strong>Test:</strong> Biopsy reveals granulomatous inflammation with periodic acid-Schiff and Gomori methenamine silver-positive fungi, morphologically consistent with Histoplasma capsulatum infection. [48]Non-culture methods include zymogen-based colorimetric assays to detect (13)-beta-D-glucan and molecular methods to detect fungal DNA.</p>",
"</dd>",
"<dt><a href='#Section19'>Cyclic neutropenia</a></dt>",
"<dd id='Section19'>",
"<p><strong>Sign & Symptoms:</strong> Cyclic neutropenia is a rare haematological disorder seen in children as a uniformly episodic fever, cervical lymphadenopathy, pharyngitis, and mucosal ulcerations that are most severe in the gingiva. [32]  The average cycle length is 21 &plusmn; 3 days, with a range of 14 to 40 days. Alveolar bone loss (from maxillary or mandibular bones) and tooth mobility may develop.",
"<br><strong>Test:</strong> Sequential FBCs show neutrophil counts &lt;0.5 X10^9/L (500/mm^3 or 500/microlitre) for 3 to 5 days during 3 successive cycles. [32]</p>",
"</dd>",
"</dl>"].join("\n");