content=["<dl>",
"<dt><a href='#Section0'>Nephrolithiasis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually have severe pain in addition to haematuria. The site and radiation of pain depend on the position of the stone.",
"<br><strong>Test:</strong> Urinalysis shows haematuria, but no dysmorphic RBCs or casts. IV pyelogram or renal ultrasound reveals the stone.</p>",
"</dd>",
"<dt><a href='#Section1'>Bladder cancer</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Important cause of painless haematuria. Patients are older and mostly have a history of smoking.",
"<br><strong>Test:</strong> Urinalysis shows haematuria, but no dysmorphic RBCs or casts. Diagnosis is made by cystoscopy and biopsy of the lesion.</p>",
"</dd>",
"<dt><a href='#Section2'>Renal cancer</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> A triad of flank pain, fever, and haematuria is typical. Many cases are detected incidentally when a CT is done for other purposes.",
"<br><strong>Test:</strong> Urinalysis shows haematuria, but no dysmorphic RBCs or casts. Imaging by CT would reveal a renal mass.</p>",
"</dd>",
"<dt><a href='#Section3'>Pre- or post-renal failure</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients present with vague generalised symptoms (fatigue, loss of appetite, and nausea) besides those of the underlying aetiology.",
"<br><strong>Test:</strong> Urinalysis does not reveal dysmorphic RBCs or casts. Fractional excretion of sodium is &lt;1% in azotaemia (abnormal levels of nitrogen-containing compounds in the blood) due to pre-renal causes.Renal imaging (ultrasound or CT) shows obstructive uropathy.</p>",
"</dd>",
"</dl>"].join("\n");