content=["<dl>",
"<dt><a href='#Section0'>Chlamydia infection</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There are no history or physical examination features that can distinguish between these organisms except for disseminated infection, which is unique to gonorrhoea.Chlamydia is around 10 times more common than gonorrhoea in young populations. [4]  [25] Chlamydia does not seem to be efficient at colonising the pharynx and is less likely to be found there. In men having sex with men, Chlamydia is the most common cause of rectal infections. [45]A specific form of genital ulcers and proctitis (lymphogranuloma venereum or LGV) is also caused by Chlamydia from a less common strain of C trachomatis.",
"<br><strong>Test:</strong> The absence of diplococcus on microscopic examination with sufficient WBC for a diagnosis of urethritis is suggestive of Chlamydia. Commercial nucleic acid amplification test (NAAT) is usually a coupled test combining both gonorrhoea and Chlamydia, therefore an ideal way to give a definite pathogenic diagnosis.Diagnosis of Chlamydia of the pharynx or rectum is by culture or with NAAT if available.Diagnosis of LGV is suggested from high titres of chlamydial antibodies, NAAT positive for Chlamydia, and the typical clinical presentation.</p>",
"</dd>",
"<dt><a href='#Section1'>Trichomonas</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Trichomonas vaginalis is a common STD and is generally under-reported. A recent survey of young Americans found an overall prevalence of 2.3%. [43]  Common symptoms (e.g., vaginal discharge and itching) are not sufficient to distinguish gonorrhoea from trichomonas.T vaginalis is often diagnosed after failure of treatment for urethritis, in cases with negative tests for gonorrhoea and Chlamydia.",
"<br><strong>Test:</strong> T vaginalis can be diagnosed by wet preparation from vaginal or urethral discharge but this technique has low sensitivity. Culture is the most efficacious test, but newer NAATs are becoming available and will allow more rapid diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Other infectious causes of urethritis, cervicitis, PID, and epididymitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Other microorganisms, which are sexually transmitted but not easily diagnosed, may cause both cervicitis and urethritis. These include atypical herpes simplex recurrences, Mycoplasma genitalium, and Ureaplasma urealyticum.PID may also be caused by a mixture of organisms.Epididymitis may be caused by enteric gram-negative organism, especially with a history of insertive anal sex or in older men (&gt;35 years). [2]There are no specific differentiating features between these other infectious agents and gonorrhoea.",
"<br><strong>Test:</strong> No commercial tests are available for M genitalium or U urealyticum.Suggestive symptoms with a positive antibody test to HSV-2 and repeated negative test results for other aetiologies suggest HSV infection.Urinary culture of gram-negative organisms may be positive in cases of epididymitis.</p>",
"</dd>",
"<dt><a href='#Section3'>Candidal vaginitis or bacterial vaginosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Does not usually involve the upper genital tract and is caused by yeast species or a disruption in normal bacterial flora (bacterial vaginosis). These types of vaginitis are not sexually transmitted.Presents as vaginal discharge, odour, and irritation.",
"<br><strong>Test:</strong> Wet mount microscopic examination, cultures, or smears may show Candida.In bacterial vaginosis, clue cells may be seen on wet mount and amine whiff test may be positive.</p>",
"</dd>",
"<dt><a href='#Section4'>Urinary tract infection, female</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Common. Symptoms include dysuria, haematuria, and urgency. Left untreated the ascending infection may result in pyelonephritis with flank pain and fever.",
"<br><strong>Test:</strong> Mid-stream urine culture positive for causative infectious agent.</p>",
"</dd>",
"<dt><a href='#Section5'>Urinary tract infection, male</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms include dysuria, haematuria, and urgency. Left untreated the ascending infection may result in pyelonephritis with flank pain and fever.",
"<br><strong>Test:</strong> Mid-stream urine culture positive for causative infectious agent.</p>",
"</dd>",
"</dl>"].join("\n");