content=["<dl>",
"<dt><a href='#Section0'>Churg-Strauss syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Asthma, prominent gastrointestinal and cardiac involvement.",
"<br><strong>Test:</strong> Significant (&gt;10% of peripheral WBC count) peripheral eosinophilia or tissue eosinophilia.</p>",
"</dd>",
"<dt><a href='#Section1'>Microscopic polyangiitis (MPA)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Usually an absence of upper respiratory tract features.",
"<br><strong>Test:</strong> Biopsy reveals a lack of granulomatous inflammation. Note a positive perinuclear (pANCA) versus cytoplasmic ANCA (cANCA) alone cannot be used to distinguish GPA from MPA.</p>",
"</dd>",
"<dt><a href='#Section2'>Classic polyarteritis nodosa (cPAN)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Absence of upper or lower respiratory tract involvement.",
"<br><strong>Test:</strong> No glomerulonephritis on renal biopsy.ANCA testing negative.</p>",
"</dd>",
"<dt><a href='#Section3'>Cryoglobulinaemic vasculitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> More than 90% of cases are associated with hepatitis C infection.Absence of upper respiratory tract features. Lung involvement rare.",
"<br><strong>Test:</strong> Positive for presence of cryoglobulins in the serum.Rheumatoid factor positive.Reduced serum C4 complement, with normal C3.ANCA testing negative.May show positive serology for hepatitis C (rarely other viruses).Renal biopsy shows mesangioproliferative glomerulonephritis.</p>",
"</dd>",
"<dt><a href='#Section4'>Henoch-Schonlein purpura (HSP)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Absence of upper respiratory tract features (although prior history of upper respiratory tract infection common in HSP). Lung involvement uncommon.",
"<br><strong>Test:</strong> ANCA testing negative.Skin or renal biopsy shows IgA deposition on immunofluorescence in HSP.</p>",
"</dd>",
"<dt><a href='#Section5'>SLE and other connective tissue diseases (CTDs)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Photosensitive rashes.Alopecia.Features of serositis of pleura, pericardium, or peritoneum.High prevalence of ocular and oral sicca symptoms related to reduced tear and saliva production.Raynaud phenomenon.",
"<br><strong>Test:</strong> Complete blood count typically shows leukopenia and thrombocytopenia.Positive antinuclear antibody (ANA) and anti-double stranded DNA antibody or antibodies against extractable nuclear antigens, favour connective tissue diseases. However, they may show false-positive results for ANCA (by immunoflourescence).</p>",
"</dd>",
"<dt><a href='#Section6'>Sarcoidosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Erythema nodosum.Uveitis.Lymphadenopathy.Splenomegaly.",
"<br><strong>Test:</strong> Chest imaging shows hilar adenopathy.Tissue biopsy shows well-formed non-caseating granuloma without vasculitis.ANCA testing negative.</p>",
"</dd>",
"<dt><a href='#Section7'>Systemic infections (e.g., endocarditis, sepsis, bacterial, fungal, or mycobacterial infections)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Presence of a heart murmur warrants exclusion of endocarditis.",
"<br><strong>Test:</strong> Blood cultures positive in endocarditis/sepsis.Echocardiography shows valvular vegetations characteristic of infective endocarditis.Positive autoantibodies, reduced serum complement, immune complex deposition on tissue biopsy, may be seen in endocarditis.Positive tuberculin skin testing seen in tuberculosis.Staining and culture of biological specimens (e.g., sputum, bronchoalveolar lavage fluid) or tissue biopsy specimens (e.g., lung biopsy) positive for microorganisms.Individuals with systemic infections may have false-positive ANCA result.</p>",
"</dd>",
"<dt><a href='#Section8'>Goodpasture's syndrome (anti-glomerular basement membrane antibody disease)</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> The presentation of pulmonary haemorrhage and glomerulonephritis is clinically indistinguishable from GPA.The presence of involvement in other sites (e.g., upper respiratory tract) argues against a diagnosis of anti-GBM antibody disease.",
"<br><strong>Test:</strong> Anti-GBM antibodies positive. Note that a small minority of patients with anti-GBM antibody disease may have a positive ANCA.Lung biopsy fails to show granulomatous inflammation in anti-GBM antibody disease.Lung or renal biopsy shows evidence of (linear) immune deposits in anti-GBM antibody disease.</p>",
"</dd>",
"<dt><a href='#Section9'>Cocaine abuse</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> History of illicit drug use.Cocaine use is associated with perforation of oro-nasal structures including the hard palate.Perforation of structures other than the nasal septum and the lamina papyracea are very rarely seen in GPA.",
"<br><strong>Test:</strong> Urine screening for cocaine.Cocaine users may be cANCA and proteinase 3 antibody (anti-PR3) positive, but may be distinguished from GPA by positive human neutrophil elastase antibody testing.</p>",
"</dd>",
"<dt><a href='#Section10'>Medication-induced vasculitis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> History of relevant medication use (e.g., propylthiouracil, minocycline).",
"<br><strong>Test:</strong> Usually pANCA positive; may also have antibodies to myeloperoxidase (MPO).</p>",
"</dd>",
"<dt><a href='#Section11'>Primary or secondary pulmonary malignancy</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> A patient with pulmonary malignancy would tend not to have symptoms or signs related to extrapulmonary vasculitis, such as ocular, musculoskeletal, or otorhinolaryngeal manifestations.",
"<br><strong>Test:</strong> Chest imaging findings may be indistinguishable from GPA.Biopsy may allow definitive diagnosis. If a transbronchial biopsy is non-diagnostic, open lung biopsy is required.</p>",
"</dd>",
"<dt><a href='#Section12'>Non-Hodgkin's Lymphoma</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Usually features palpable lymphadenopathy and/or hepatosplenomegaly (unusual in GPA).May also be associated with cutaneous leukocytoclastic vasculitis or, less commonly, other forms of vasculitis.Natural killer cell lymphomas may lead to midline destructive lesions, mimicking upper airway involvement with GPA.",
"<br><strong>Test:</strong> Lymphoma may rarely be associated with a positive ANCA test.Tissue biopsy (e.g., lymph node) required for definitive diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");