content=["<dl>",
"<dt><a href='#Section0'>Annular lichen planus</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Flat-topped, shiny, violaceous plaques with irregular white streaks called Wickham's striae that may also be seen in mouth and gums. [17]",
"<br><strong>Test:</strong> Skin biopsy: liquefaction degeneration of the basal layer, band-like mononuclear infiltrate of the epidermis, and Civatte' bodies at dermo-epidermal junction.</p>",
"</dd>",
"<dt><a href='#Section1'>Dermatophyte infections</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typically unilateral lesions on the fingers associated with an intense pruritus.Worsened by the application of a topical corticosteroid.",
"<br><strong>Test:</strong> Skin scrapings sent for mycology show positive result for dermatophytic infection.</p>",
"</dd>",
"<dt><a href='#Section2'>Mycosis fungoides</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Generalised or solitary patches or plaques. Can be non-specific in appearance. Very itchy. Long natural history. [14]",
"<br><strong>Test:</strong> Skin biopsy: band-like and patchy infiltrate of atypical lymphocytes (mycosis cells) and positive T-cell rearrangement studies.</p>",
"</dd>",
"<dt><a href='#Section3'>Insect bites</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Can resemble a papule.Patient may recall insect bite or have relevant travel history.",
"<br><strong>Test:</strong> Skin biopsy: dermal infiltrate predominantly eosinophilic.</p>",
"</dd>",
"<dt><a href='#Section4'>Rheumatoid nodule</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Tends to occur over bony prominences.Presence of classic features of rheumatoid arthritis, such as hand deformity.",
"<br><strong>Test:</strong> Rheumatoid factor: usually positive if nodules present.</p>",
"</dd>",
"<dt><a href='#Section5'>Cutaneous sarcoidosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May be indistinguishable clinically, as can present in many ways. [18]",
"<br><strong>Test:</strong> CXR: bihilar lymphadenopathy.Serum calcium and angiotensin-converting enzyme levels elevated.Skin biopsy: large islands of epithelioid cells, few giant cells, and occasionally fibrinoid necrosis.</p>",
"</dd>",
"<dt><a href='#Section6'>Perforating collagen disorders</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Rare. Start as very small lesions and grow over a few weeks into papules.Intensely pruritic.Have a keratinous plug. [19]",
"<br><strong>Test:</strong> Serum urea, creatinine, LFTs, and serum glucose levels may be elevated, as renal failure and diabetes can be associated with the perforating collagen disorders.Skin biopsy: transepidermal elimination of collagen.</p>",
"</dd>",
"<dt><a href='#Section7'>Soft-tissue sarcoma</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> May be indistinguishable clinically.Typically a solitary lump that may have been present for some time.Gradually increasing in size.",
"<br><strong>Test:</strong> Core needle biopsy confirms diagnosis.</p>",
"</dd>",
"<dt><a href='#Section8'>Necrobiosis lipoidica</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to distinguish clinically, but patient is likely to have diabetes mellitus (type 1 or 2). Telangiectasia visible centrally.Tender to palpation.",
"<br><strong>Test:</strong> Skin biopsy: inflammatory reaction around destroyed collagen, characteristic appearance.</p>",
"</dd>",
"<dt><a href='#Section9'>Erythema migrans</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Typical bull's-eye appearance, enlarging area of erythema with central clearing. May have joint pain, fever, and fatigue suggestive of Lyme disease.",
"<br><strong>Test:</strong> Blood test for antibodies to Borrelia burgdorferi but may not be present in the first week after infection.</p>",
"</dd>",
"</dl>"].join("\n");