content=["<dl>",
"<dt><a href='#Section0'>Idiopathic short stature</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No organic cause.Applies to healthy children with a height more than 2 standard deviation scores (SDS) below the mean for age and sex.",
"<br><strong>Test:</strong> Normal GH provocation tests.No other associated pituitary hormone deficiency.Normal MRI of pituitary.</p>",
"</dd>",
"<dt><a href='#Section1'>Constitutional delay in growth</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Growth deceleration during the first 2 years followed by a normal growth velocity, with acceleration late in adolescence, leading to a final height that is close to the target height.More frequent in boys; either parent may have been a 'late bloomer'.Patients have a delayed pubertal development.",
"<br><strong>Test:</strong> Delayed bone age.Normal baseline laboratory evaluation.</p>",
"</dd>",
"<dt><a href='#Section2'>Familial short stature</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients are born an adequate size for gestational age.Steady growth below the 5th percentile until reaching a final height that is appropriate for their target height.Puberty is not delayed, and patients are proportionate.",
"<br><strong>Test:</strong> Clinical diagnosis.Normal bone age.</p>",
"</dd>",
"<dt><a href='#Section3'>Small for gestational age</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Includes patients who are born small for gestational age and have not caught up in height by the age of 2 years but who are otherwise healthy.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section4'>Hypothyroidism</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Most thyroid disorders occur more frequently in girls.May be congenital or acquired.Symptoms include lethargy, fatigue, excessive sleepiness, temperature dysregulation, menstrual abnormalities, and weight gain.Secondary hypothyroidism may co-exist with GHD.",
"<br><strong>Test:</strong> Low free T4 and elevated TSH in primary hypothyroidism.Low free T4 and low TSH in TSH deficiency (pituitary or secondary hypothyroidism).</p>",
"</dd>",
"<dt><a href='#Section5'>Turner's syndrome</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Characteristic features include ovarian dysgenesis, hearing loss, aortic valve and/or renal abnormalities, and delayed or arrested puberty.Presents only in girls.",
"<br><strong>Test:</strong> Chromosomal abnormality 45 XO, 46/45 XX/XO.</p>",
"</dd>",
"<dt><a href='#Section6'>Noonan's syndrome</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Short stature with dysmorphic features, congenital heart defects (e.g., pulmonary valve stenosis), and learning problems.",
"<br><strong>Test:</strong> Clinical diagnosis.Genetic testing: may be positive for a mutation in the PTPN11/SOS1/KRAS/RAF1 genes.</p>",
"</dd>",
"<dt><a href='#Section7'>Russell-Silver syndrome</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Children born small for gestational age with dysmorphism (triangular face, clinodactyly, asymmetry).Feeding problems, hypoglycaemia.",
"<br><strong>Test:</strong> Clinical diagnosis.Genetic testing may reveal maternal uniparental disomy for chromosome 7 (mUPD7) or loss of methylation at 11p15.</p>",
"</dd>",
"<dt><a href='#Section8'>Prader-Willi syndrome</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Marked hyperphagia, obesity, and learning difficulties.",
"<br><strong>Test:</strong> Deletion of the paternal copy of HBII-85 snoRNAs on chromosome 15q11-13; example of genetic imprinting disorder.</p>",
"</dd>",
"<dt><a href='#Section9'>DiGeorge syndrome</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Cardiac defects, cleft palate, immune deficiency, hypocalcaemia, and learning difficulties. Also called velocardiofacial syndrome.",
"<br><strong>Test:</strong> Submicroscopic deletion in chromosome 22q11.2.</p>",
"</dd>",
"<dt><a href='#Section10'>Failure to thrive</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Any chronic medical condition can lead to short stature with or without poor weight gain and failure to thrive. Common conditions include chronic heart disease (congenital or acquired), asthma (moderate or severe), cystic fibrosis, coeliac disease, inflammatory bowel disease (Crohn's disease and ulcerative colitis), juvenile idiopathic arthritis, chronic renal failure, any chronic malignancy, and poorly controlled diabetes mellitus.",
"<br><strong>Test:</strong> Clinical diagnosis.Specific laboratory test will reveal disease.</p>",
"</dd>",
"<dt><a href='#Section11'>Skeletal dysplasia</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Achondroplasia, hypochondroplasia, and osteogenesis imperfecta present with disproportionate short stature; dysmorphic features may be present.",
"<br><strong>Test:</strong> Skeletal survey reveals abnormality.</p>",
"</dd>",
"<dt><a href='#Section12'>Rickets</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Disproportionate short stature, rachitic rosary, bow legs.",
"<br><strong>Test:</strong> Vitamin D is low.Elevated alkaline phosphate.</p>",
"</dd>",
"<dt><a href='#Section13'>GH resistance</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Insensitivity or resistance to GH results in insulin-like growth factor 1 (IGF1) deficiency and extreme short stature.Difficult to distinguish from GHD clinically.",
"<br><strong>Test:</strong> Normal or elevated basal GH levels.Exaggerated GH response after provocation.IGF generation test reveals the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section14'>Craniopharyngioma</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Acquired cause of GHD.Rare, suprasellar, cystic tumour that develops from the nests of epithelium derived from Rathke's pouch, an embryonic precursor of the anterior pituitary.Presents with headaches, diplopia, raised intracranial pressure, and pituitary dysfunction.Endocrine dysfunction is variable but typically includes combined pituitary hormone deficiencies and may present pre- or postoperatively. Treatment includes surgery with or without radiotherapy.",
"<br><strong>Test:</strong> MRI brain reveals the solid/cystic suprasellar mass.Pituitary tests show variable pituitary hormone deficiencies.</p>",
"</dd>",
"<dt><a href='#Section15'>Child abuse</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Acquired cause of a reversible GHD.Children who have been subjected to abuse and neglect present with short stature and a characteristic behavioural pattern that includes hyperphagia, bizarre eating habits that mimic organic compulsive eating disorders, vomiting, and polydipsia.",
"<br><strong>Test:</strong> Normalisation of GH levels on provocation testing after removal from the stressful environment. [24]  [51]</p>",
"</dd>",
"</dl>"].join("\n");  