content=["<dl>",
"<dt><a href='#Section0'>Anaemia due to blood loss</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History and physical examination will often identify source of blood loss.",
"<br><strong>Test:</strong> Normal haptoglobin, bilirubin, and LDH.Microcytic anaemia. Iron deficiency.Faecal occult blood test may be positive.</p>",
"</dd>",
"<dt><a href='#Section1'>Underproduction anaemia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Due to decreased RBC production from multiple causes, such as bone marrow failure (myelofibrosis, myelodysplastic syndrome, myelosuppression, aplastic anaemia), anaemia of chronic disease, and deficiency states (iron, vitamin B12, folate). Clinical evaluation depends on underlying cause.",
"<br><strong>Test:</strong> Reticulocyte count is low, signs of haemolysis typically absent.</p>",
"</dd>",
"<dt><a href='#Section2'>Transfusion reaction</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Acute reactions occur during or immediately following blood transfusion.Symptoms of acute reactions may include: chills; fever; headache; pallor; pain along the infusion site; abdomen, back or chest pain. Signs of acute reactions may include: pruritus; flushing; dyspnoea; urticaria; hypotension; haemoglobinuria; wheezing; and stridor.There may be a history of prior exposures to foreign red-cell antigen following pregnancy, previous transfusion, or organ transplantation with delayed haemolytic transfusion reactions. Symptoms and signs occur days to weeks following a transfusion, and include: pallor; jaundice; haemoglobinuria; purpura; bleeding (DIC).",
"<br><strong>Test:</strong> Direct antiglobulin (Coombs) test may be positive and serum haptoglobin low, as for haemolysis generally.Visual inspection of post-transfusion sample may show pink-to-red colour.Testing may show ABO incompatibility between recipient and donor.In cases of anaphylactic reaction, serum IgA levels may be low and anti-IgA antibodies may be positive.</p>",
"</dd>",
"</dl>"].join("\n");