content=["<dl>",
"<dt><a href='#Section0'>Thrombotic thrombocytopenic purpura (TTP)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Although this has historically been described as presenting with a higher incidence of neurological symptoms and a lesser degree of renal failure than HUS, there is so much overlap between the two that some experts recommend treating them as a single entity. [2]  The seminal discovery of low levels of the von Willebrand cleaving enzyme, ADAMTS13, in many patients with presentations typical of TTP but not those with typical of HUS suggests that there are distinct pathophysiological mechanisms involved. [31]",
"<br><strong>Test:</strong> Levels of the von Willebrand cleaving enzyme, ADAMTS13, whose deficiency is implicated in the pathogenesis of TTP, are more consistently low in TTP than in HUS, [30]  but this has not yet been translated into clinical practice decisions. [2]</p>",
"</dd>",
"<dt><a href='#Section1'>Malignant hypertension</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> This can have pathological features of thrombotic microangiopathy with similar characteristics to those of HUS; therefore, consideration of malignant hypertension as a differential diagnosis is required. [2]  The distinguishing feature is a significantly elevated blood pressure. [32]",
"<br><strong>Test:</strong> Platelet counts are generally normal in malignant hypertension. [32]</p>",
"</dd>",
"<dt><a href='#Section2'>Vasculitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> A pre-existing diagnosis or a history of symptoms suggestive of a rheumatological condition mandates that vasculitis be considered in the diagnosis. However, there are many overlapping features between SLE and TTP/HUS, and since the two can co-exist, a distinction between them is generally not possible. [33]",
"<br><strong>Test:</strong> Serological tests of underlying condition may be positive, but there are no tests to differentiate the cause of HUS.</p>",
"</dd>",
"<dt><a href='#Section3'>Catastrophic antiphospholipid syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> This condition can present in a way that is indistinguishable from TTP/HUS. [34]  [35]",
"<br><strong>Test:</strong> Antiphospholipid antibodies can be helpful in suggesting a diagnosis. However, even if these are positive, plasma exchange is often recommended in patients with manifestations of severe disease. [35]</p>",
"</dd>",
"<dt><a href='#Section4'>Disseminated intravascular coagulation</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients with DIC have a higher likelihood of bleeding manifestations and often have obvious predisposing causes, such as sepsis.",
"<br><strong>Test:</strong> The peripheral smear in a patient with DIC generally has fewer schistocytes. Coagulation parameters are typically abnormal in patients with DIC, whereas they are normal in patients with TTP/HUS.</p>",
"</dd>",
"<dt><a href='#Section5'>Pre-eclampsia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Distinguishing between the various causes of thrombocytopenia that present in the peri- and post-partum period can be difficult if not impossible. [21]  [22]  HUS tends to present post-partum, which distinguishes it from pre-eclampsia.",
"<br><strong>Test:</strong> The peripheral smear in patients with TTP/HUS generally has more schistocytes than are seen in pre-eclampsia.</p>",
"</dd>",
"<dt><a href='#Section6'>HELLP syndrome</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> HUS tends to present post-partum, which distinguishes it from HELLP (haemolysis, elevated liver enzyme levels, and a low platelet count) syndrome.",
"<br><strong>Test:</strong> The peripheral smear in patients with TTP/HUS generally has more schistocytes than are seen in HELLP syndrome.</p>",
"</dd>",
"</dl>"].join("\n");