content=["<dl>",
"<dt><a href='#Section0'>Anal fissure</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Anal fissures are associated with painful bleeding on defecation and possibly a sentinel skin tag (sometimes reported by the patient as a &ldquo;painful haemorrhoid&rdquo;). Fissures are seen as linear tears in the anal mucosae, most commonly in the posterior midline of the anal canal.",
"<br><strong>Test:</strong> Physical examination.</p>",
"</dd>",
"<dt><a href='#Section1'>Crohn's disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Crohn's disease affecting the large bowel can present with rectal bleeding and is associated with diarrhoea rather than constipation. Family history of inflammatory bowel disease is often present.",
"<br><strong>Test:</strong> Endoscopy findings highly variable, depending on disease activity. Characteristically shows 'skip areas' with areas of disease with intervening areas of normal mucosa. Usually most severe in the cecum and right colon, with rectum often spared.</p>",
"</dd>",
"<dt><a href='#Section2'>Ulcerative colitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Ulcerative colitis commonly presents with rectal bleeding and is associated with diarrhoea rather than constipation. Family history of inflammatory bowel disease is often present.",
"<br><strong>Test:</strong> Endoscopy reveals diffuse inflammation and ulceration in cases of acute ulcerative colitis.</p>",
"</dd>",
"<dt><a href='#Section3'>Colorectal cancer</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History of altered bowel habits, anaemia, colonic polyps, and positive family history suggest colorectal cancer.",
"<br><strong>Test:</strong> Endoscopy may reveal mass, stricture, and obstruction. Blood tests commonly reveal anaemia.</p>",
"</dd>",
"<dt><a href='#Section4'>Anal fistula</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Commonly bleeding with a history of a preceding abscess, with continued intermittent bloody/purulent drainage. Visualised as a punctuate opening on the anal margin adjacent to the anal canal.",
"<br><strong>Test:</strong> Physical examination.</p>",
"</dd>",
"</dl>"].join("\n");