content=["<dl>",
"<dt><a href='#Section0'>Iron overload from chronic transfusion</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of chronic transfusion would help differentiate.",
"<br><strong>Test:</strong> Patients with iron overload from chronic transfusion are much more likely to be anaemic at the time of diagnosis; therefore, an FBC is recommended.</p>",
"</dd>",
"<dt><a href='#Section1'>Dysmetabolic hyperferritinaemia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Common syndrome that presents in patients with metabolic syndrome (obesity, hypertension, hyperlipidaemia, type 2 diabetes mellitus, and hyperuricaemia) and high ferritin levels.",
"<br><strong>Test:</strong> Can present with an raised serum ferritin, low transferrin saturation, mild hepatic iron overload on biopsy or MRI (lower than expected when compared with serum ferritin), and mixed iron deposition in both hepatocytes and macrophages on liver biopsy.</p>",
"</dd>",
"<dt><a href='#Section2'>Hereditary aceruloplasminaemia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Very rare yet familial. Can be associated with diabetes and often is associated with a neurological syndrome (extrapyramidal syndrome, cerebellar ataxia, retinal degeneration, and dementia).",
"<br><strong>Test:</strong> These patients have marked elevation of the serum ferritin (without evidence of inflammation), but have low transferrin saturation and can have severe hepatic iron overload. The diagnosis requires documentation of undetectable levels of serum ceruloplasmin.</p>",
"</dd>",
"<dt><a href='#Section3'>Excessive iron supplementation</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History of excessive iron supplementation, especially with excessive vitamin C supplementation.",
"<br><strong>Test:</strong> These patients would not have a homozygous gene mutation associated with hereditary haemochromatosis.</p>",
"</dd>",
"<dt><a href='#Section4'>Chronic hepatitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of risk factors for hepatitis",
"<br><strong>Test:</strong> Patients would have hepatitis panels consistent with chronic viral hepatitis (especially hepatitis C) and would not have homozygous mutations consistent with hereditary haemochromatosis. [33]</p>",
"</dd>",
"</dl>"].join("\n");