content=["<dl>",
"<dt><a href='#Section0'>ischaemic stroke</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms occur suddenly.In ischaemic stroke, patients do not exhibit GI symptoms (N/V) or headache typically.",
"<br><strong>Test:</strong> Acute haemorrhage appears bright due to hyperattenuation of the x-ray beams. In contrast, ischaemic infarct appears as hypoattenuation (darkness), although may not appear for many hours after stroke onset.</p>",
"</dd>",
"<dt><a href='#Section1'>hypertensive encephalopathy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> HTN significantly above patient's baseline BP associated with headache, decreased consciousness or cognitive abnormalities, visual changes or loss, and signs of increased intracranial pressure.",
"<br><strong>Test:</strong> Cerebral oedema on CT or MRI.</p>",
"</dd>",
"<dt><a href='#Section2'>hypoglycaemia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Sweating, tremor, hunger, confusion, and ultimately a decreased level of consciousness.May have known history of diabetes mellitus and insulin use or medical conditions associated with hypoglycaemia.",
"<br><strong>Test:</strong> Low serum glucose on blood chemistry.</p>",
"</dd>",
"<dt><a href='#Section3'>complicated migraine</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Repetitive history of similar events preceding aura; headache in a marching pattern.",
"<br><strong>Test:</strong> MRI shows no evidence of infarction.</p>",
"</dd>",
"<dt><a href='#Section4'>seizure disorder</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> A history of seizures and/or a witnessed seizure followed by postictal deficits.",
"<br><strong>Test:</strong> EEG results may identify seizure activity.MRI shows no evidence of infarction.</p>",
"</dd>",
"<dt><a href='#Section5'>conversion and somatisation disorders</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Neurological signs and symptoms do not fit a vascular territory. No cranial nerve deficits.Additionally, conversion disorder displays multiple signs that are neurologically inconsistent.",
"<br><strong>Test:</strong> CT and MRI show no evidence of infarction or haemorrhage in conversion disorder.</p>",
"</dd>",
"</dl>"].join("\n");