content=["<dl>",
"<dt><a href='#Section0'>Viral upper respiratory tract infection</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Sinus congestion, rhinorrhoea.Rhinorrhoea and sinus congestion are not features of hantavirus infection.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Influenza pneumonia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Influenza is commonly associated with upper airway symptoms.",
"<br><strong>Test:</strong> Influenza antigen testing and respiratory virus cultures are positive for influenza.</p>",
"</dd>",
"<dt><a href='#Section2'>Mycoplasma pneumoniae pneumonia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Dry, persistent cough. Bullous myringitis may be present.Clinical response to appropriate antibiotic therapy.",
"<br><strong>Test:</strong> Serum cold agglutinins may be positive in Mycoplasma infection.</p>",
"</dd>",
"<dt><a href='#Section3'>Chlamydia pneumoniae pneumonia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Upper respiratory symptoms and gradual onset of the infection.Clinical response to appropriate antibiotic therapy.",
"<br><strong>Test:</strong> Positive culture for C pneumoniae.Serological tests for C pneumoniae can be diagnostic.</p>",
"</dd>",
"<dt><a href='#Section4'>Histoplasmosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Histoplasma capsulatum proliferates in soil contaminated with bird or bat droppings. Exposure is commonly associated with cave exploration, close proximity to chicken roosts, demolition, and excavation. High concentration aerosol inocula can cause a diffuse pneumonia.May be clinically indistinguishable.",
"<br><strong>Test:</strong> Positive culture and antigen testing.</p>",
"</dd>",
"<dt><a href='#Section5'>Coccidioidomycosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Fungal pneumonia caused by Coccidioides immitis may be clinically indistinguishable.May have associated rash.",
"<br><strong>Test:</strong> Positive serology for coccidioidomycosis.</p>",
"</dd>",
"<dt><a href='#Section6'>Leptospirosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Conjunctival suffusion, hepatic involvement, most commonly a self-limiting illness.Clinical response to appropriate antibiotic therapy.",
"<br><strong>Test:</strong> Leptospirosis serological testing positive.</p>",
"</dd>",
"<dt><a href='#Section7'>Psittacosis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> History of exposure to domesticated or commercially raised birds, mammals, and exotic imported birds.Splenomegaly is occasionally present.Clinical response to appropriate antibiotic therapy.",
"<br><strong>Test:</strong> The diagnosis may be made serologically from paired sera for psittacosis-antibodies.</p>",
"</dd>",
"<dt><a href='#Section8'>Q fever pneumonia</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Caused by Coxiella burnetii infection (commonly of livestock and domestic animals) and exposure to contaminated soil or dust.May be clinically indistinguishable.",
"<br><strong>Test:</strong> Immunofluorescence assay (IFA) of infected tissue is positive.</p>",
"</dd>",
"<dt><a href='#Section9'>ARDS</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> May be clinically indistinguishable.",
"<br><strong>Test:</strong> Both ARDS and hantavirus cardiopulmonary syndrome (HCPS) produce diffuse air space disease on CXR. Experienced radiologists may be able to distinguish between the 2 syndromes after viewing serial x-rays. [41]</p>",
"</dd>",
"<dt><a href='#Section10'>Myocardial infarction</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Distinguishable by lack of fever.",
"<br><strong>Test:</strong> ECG changes of acute ischaemia, and elevated levels of troponin and CK.</p>",
"</dd>",
"<dt><a href='#Section11'>Bacterial sepsis</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> May be clinically indistinguishable, but history and examination may reveal primary source of infection.",
"<br><strong>Test:</strong> Blood cultures are usually positive in bacterial sepsis.Haemodynamic measurements demonstrate increased peripheral vascular resistance (PVR) with hantavirus infection versus decreased PVR in septic shock.</p>",
"</dd>",
"<dt><a href='#Section12'>Plague</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> High fevers, purple skin patches, vomiting, seizures, shock.",
"<br><strong>Test:</strong> Blood, urine, sputum, and fluid from buboes or other lesions to identify bacteria.CXR will show patchy areas in the lungs in pneumonic plague.</p>",
"</dd>",
"<dt><a href='#Section13'>Rickettsial disease</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Recent tick exposure; triad of fever, maculopapular or petechiae rash, and headache.",
"<br><strong>Test:</strong> Indirect IFA: titre &ge;1:64.Serum electrolytes: low sodium; elevated urea.</p>",
"</dd>",
"<dt><a href='#Section14'>Pneumocystis jiroveci pneumonia</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> History of prior Pneumocystis pneumonia, HIV-positive, oropharyngeal candidiasis, recurrent bacterial pneumonia, weight loss.",
"<br><strong>Test:</strong> CXR: bilateral symmetrical interstitial infiltrates.Induced sputum: positive for Pneumocystis.</p>",
"</dd>",
"</dl>"].join("\n");