content=["<dl>",
"<dt><a href='#Section0'>Delirium</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Altered attention level.Not typically associated with elevated core temperature, although patients with heat stroke may have delirium in addition to pyrexia.",
"<br><strong>Test:</strong> Diagnostic distinction is typically based on clinical examination.Significant abnormalities from laboratory investigations are lacking.</p>",
"</dd>",
"<dt><a href='#Section1'>Meningitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Headache, fever, nuchal rigidity, occasional CNS alteration.",
"<br><strong>Test:</strong> LP is generally abnormal in patients with meningitis.</p>",
"</dd>",
"<dt><a href='#Section2'>Diabetic ketoacidosis (DKA)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Altered level of consciousness or alertness, hyperventilation, myriad other non-specific systemic symptoms.",
"<br><strong>Test:</strong> Plasma glucose is typically severely elevated in patients with DKA; ketones in urine.</p>",
"</dd>",
"<dt><a href='#Section3'>Hyperthyroidism</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Common signs include tachycardia, exophthalmos, hyper-reflexia.Symptoms are typically of more insidious onset in patients with hyperthyroidism.",
"<br><strong>Test:</strong> TSH is low; elevated T3 and T4.</p>",
"</dd>",
"<dt><a href='#Section4'>Neuroleptic malignant syndrome (NMS)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Generally preceded by a typical event, such as receiving anaesthetic agents.Responsive to dantrolene.",
"<br><strong>Test:</strong> Diagnosis is clinical; elevated CK.</p>",
"</dd>",
"<dt><a href='#Section5'>Drug toxicity</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Medicine/drug overdose may present with hyperthermia but not be associated with elevated ambient temperature or physical activity.Often there is a history of drug use or of recent ingestion.Drugs commonly associated include cocaine, phencyclidines, and salicylates.",
"<br><strong>Test:</strong> Blood assays positive for the ingested agent.</p>",
"</dd>",
"<dt><a href='#Section6'>Delirium tremens</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> May present with hyperthermia but not be associated with elevated ambient temperature or physical activity.Typically associated with history of alcohol abuse without recent ingestion. Often there is a clinical history of prior withdrawal symptoms.",
"<br><strong>Test:</strong> LFTs may be elevated.</p>",
"</dd>",
"</dl>"].join("\n");