content=["<dl>",
"<dt><a href='#Section0'>Acute hepatitis A virus (HAV) infection</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Serum laboratory test will be positive for HAV-IgM antibody.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute hepatitis C virus (HCV) infection</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Serum laboratory test will be positive for HCV antibody, and RNA-PCR will be positive for hepatitis C. Typically, symptomatic acute HCV patients will show very high ALT, AST, and bilirubin.</p>",
"</dd>",
"<dt><a href='#Section2'>Chronic HCV infection</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Patients may have normal or elevated LFTs with positive serum HCV antibody and HCV RNA-PCR.</p>",
"</dd>",
"<dt><a href='#Section3'>Hepatitis D virus (HDV) co-infection with HBV</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms. Patient may have sudden rise in hepatic panel.",
"<br><strong>Test:</strong> Serum hepatitis D RNA and hepatitis D IgM antibody will be positive.</p>",
"</dd>",
"<dt><a href='#Section4'>Acute hepatitis E virus (HEV) infection</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms and signs can be identical to other acute viral hepatitis. It is most common in pregnant women in developing countries with a hot climate.",
"<br><strong>Test:</strong> Serum HEV antibody (IgM) will be positive, including serum HEV RNA-PCR.</p>",
"</dd>",
"<dt><a href='#Section5'>Cytomegalovirus (CMV) hepatitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May have history of immunocompromise including organ transplant.",
"<br><strong>Test:</strong> Positive serum CMV-IgM antibody and CMV DNA PCR.</p>",
"</dd>",
"<dt><a href='#Section6'>Epstein Barr virus (EBV) hepatitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Patients typically can experience fever, fatigue, pharyngitis, malaise, myalgia, and lymphadenopathy (particularly posterior cervical chain).",
"<br><strong>Test:</strong> Positive Monospot test and serum heterophile antibody. Serum EBV-IgM antibody and EBV DNA-PCR are positive.</p>",
"</dd>",
"<dt><a href='#Section7'>Herpes Simplex virus (HSV) hepatitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Patient may be immunosuppressed or pregnant but can also be immunocompetent. Patients may present as acute viral hepatitis with or without liver failure.",
"<br><strong>Test:</strong> Serum HSV IgM antibody and HSV DNA-PCR are positive.</p>",
"</dd>",
"<dt><a href='#Section8'>Acute alcoholic hepatitis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms. History of moderate or heavy alcohol use.",
"<br><strong>Test:</strong> Negative serological tests for viral hepatitis. AST level is higher than ALT, with elevated gamma glutamyl transferase. Liver biopsy may show steatosis, ballooning hepatocytes, Mallory hyaline, lobular neutrophilic infiltration, with or without pericellular fibrosis.</p>",
"</dd>",
"<dt><a href='#Section9'>Drug- or toxin-induced hepatitis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms. There may be a history of exposure to hepatotoxic drugs or toxins.",
"<br><strong>Test:</strong> Liver biopsy may show the features of hepatocellular, cholestatic, or mixed pattern of injury, including cholestasis.</p>",
"</dd>",
"<dt><a href='#Section10'>Autoimmune hepatitis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms.",
"<br><strong>Test:</strong> There may be increased levels of serum globulin, antinuclear antibody, antismooth muscle antibody, liver/kidney microsomal antibodies, and/or antibodies against soluble liver antigen/liver pancreas antigen. Liver histology may show interface hepatitis with plasma cell infiltrates.</p>",
"</dd>",
"<dt><a href='#Section11'>Biliary obstruction</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms associated with biliary obstruction may include RUQ pain, fever/chills, jaundice, pruritus, nausea, and vomiting.",
"<br><strong>Test:</strong> Ultrasound, CT scan, or MRI cholangiography may show dilatation of biliary tract. In case of malignant obstruction, a mass may be seen in the liver.</p>",
"</dd>",
"<dt><a href='#Section12'>Metastatic liver diseases</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Patients may be asymptomatic or have symptoms and signs of malignancy of other primary sites, including biliary obstructive features.",
"<br><strong>Test:</strong> CT scan or MRI of abdomen may show one or more metastatic masses in the liver</p>",
"</dd>",
"<dt><a href='#Section13'>Acute ischaemic hepatitis</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have symptoms of ischaemia such as acute heart failure, shock, or sepsis.",
"<br><strong>Test:</strong> ECG may show features of myocardial ischaemia or infarction. CXR and echocardiogram may show features of congestive heart failure. Doppler ultrasound of liver may show portal vein thrombosis or acute occlusion of hepatic artery.</p>",
"</dd>",
"<dt><a href='#Section14'>Budd-Chiari syndrome</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Doppler ultrasound may show hepatic vein thrombosis or inferior vena caval thrombosis.</p>",
"</dd>",
"<dt><a href='#Section15'>Acute fatty liver of pregnancy</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Pregnant patient may present with jaundice.",
"<br><strong>Test:</strong> Diagnosis of exclusion of other diseases with characteristic symptoms and signs in pregnant patients.</p>",
"</dd>",
"<dt><a href='#Section16'>Wilson's disease</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Increased urinary copper, decreased serum ceruloplasmin, and Kayser-Fleischer rings on slit lamp eye examination.</p>",
"</dd>",
"<dt><a href='#Section17'>Haemochromatosis</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differences in signs and symptoms.",
"<br><strong>Test:</strong> High iron saturation (&gt;45% transferrin saturation) and haemochromatosis gene mutations. Liver biopsy shows iron deposition in hepatocytes.</p>",
"</dd>",
"</dl>"].join("\n");