content=["<dl>",
"<dt><a href='#Section0'>Pre-renal azotaemia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of GI haemorrhage, intense diarrhoea, aggressive diuretic therapy, or excessive paracentesis.",
"<br><strong>Test:</strong> Therapeutic trial of intravenous fluid results in improvement in renal function.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute tubular necrosis - ischaemic</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Underlying condition that causes hypotension, such as prolonged pre-renal azotaemia, hypovolaemia resulting in hypotension, or sepsis; or ischaemia due to vascular disease.",
"<br><strong>Test:</strong> Sodium &lt;10 mmol/L (&lt;10 mEq/L); urine osmolarity &gt; plasma osmolarity; protein &lt;500 mg/dL.</p>",
"</dd>",
"<dt><a href='#Section2'>Acute tubular necrosis - nephrotoxic</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> History of recent use of nephrotoxic agents such as gentamicin or NSAIDs, or exposure to radiocontrast agents.",
"<br><strong>Test:</strong> Urine sodium generally &gt;40 mmol/L (40 mEq/L).</p>",
"</dd>",
"<dt><a href='#Section3'>Obstructive renal nephropathy</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms depend on cause.Acute obstruction, such as renal calculi or acute papillary necrosis, presents with severe pain and haematuria.Chronic obstruction, such as prostatic hypertrophy, may be asymptomatic.",
"<br><strong>Test:</strong> Renal ultrasonography shows hydronephrosis and hydroureter.</p>",
"</dd>",
"<dt><a href='#Section4'>Glomerulonephritis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Particularly in the setting of cirrhosis due to hepatitis B or C.",
"<br><strong>Test:</strong> Proteinuria (&gt;500 mg/dL).RBC and red cell casts in urine.May have cryoglobulinaemia if viral hepatitis.Renal biopsy changes consistent with glomerulonephritis.</p>",
"</dd>",
"</dl>"].join("\n");