content=["<dl>",
"<dt><a href='#Section0'>Chronic hepatitis B</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Hepatitis B surface antigen test is positive.Hepatitis C antibody test is negative.</p>",
"</dd>",
"<dt><a href='#Section1'>Alcoholic liver disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> There may be symptoms of alcohol dependency, but these are not diagnostic.",
"<br><strong>Test:</strong> Hepatitis C antibody test is negative.</p>",
"</dd>",
"<dt><a href='#Section2'>Steatohepatitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Ultrasound may show fatty liver.Hepatitis C antibody test is negative.Liver biopsy shows steatohepatitis.</p>",
"</dd>",
"<dt><a href='#Section3'>Haemochromatosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There may be no differentiating signs or symptoms, but some patients with advanced disease may also have features of cardiomyopathy, arthritis, or diabetes.",
"<br><strong>Test:</strong> Iron indices are abnormal (but a caution is that patients with advanced liver disease of any aetiology, particularly those with cirrhosis, may have very elevated ferritin and transferrin saturations). A genetic test for the haemochromatosis gene (C282Y mutation) may be helpful to differentiate.</p>",
"</dd>",
"<dt><a href='#Section4'>Other chronic liver diseases</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have a history or physical findings suggestive of metabolic, auto-immune, or drug-induced liver disease.",
"<br><strong>Test:</strong> Hepatitis C antibody test is negative.Blood chemistries or serologies, toxicology screen, or liver biopsy may confirm an alternate diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");