content=["<dl>",
"<dt><a href='#Section0'>Syphilis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Characterised by a single non-tender ulcer as opposed to a painful ulcer.",
"<br><strong>Test:</strong> A positive non-treponemal test: for example, rapid plasma reagin/Venereal Disease Research Laboratories titre or darkfield microscopy result.</p>",
"</dd>",
"<dt><a href='#Section1'>Chancroid</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Characterised by a single deep ulcer, which is painful, as opposed to multiple painful ulcers with herpes.",
"<br><strong>Test:</strong> The presence of Haemophilus ducreyi on culture or PCR differentiates.</p>",
"</dd>",
"<dt><a href='#Section2'>Lymphogranuloma venereum</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There is a lack of vesicles, with single or few ulcers and unilateral lymphadenopathy.",
"<br><strong>Test:</strong> A positive chlamydia trachomatis culture and genotyping for serovars L1 to L3 help differentiate.</p>",
"</dd>",
"<dt><a href='#Section3'>Contact dermatitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs and symptoms.",
"<br><strong>Test:</strong> Negative for HSV testing.</p>",
"</dd>",
"<dt><a href='#Section4'>Beh&ccedil;et's disease</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Oral, eye, genital involvement. Patients with Behcet&rsquo;s may also have oral ulcers and uveitis.",
"<br><strong>Test:</strong> Negative for HSV testing.</p>",
"</dd>",
"<dt><a href='#Section5'>Rheumatological disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Exclusive oral involvement more likely.",
"<br><strong>Test:</strong> Elevated ESR and/or positive rheumatic factor titre, ANA titre.</p>",
"</dd>",
"<dt><a href='#Section6'>Crohn's disease</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Exclusive oral involvement more likely in addition to GI symptoms presence.",
"<br><strong>Test:</strong> Evidence on colonoscopy.</p>",
"</dd>",
"<dt><a href='#Section7'>Ulcerative colitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Exclusive oral involvement more likely.",
"<br><strong>Test:</strong> Positive for ANA and evidence on colonoscopy.</p>",
"</dd>",
"<dt><a href='#Section8'>Scabies</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> May have disseminated skin involvement.",
"<br><strong>Test:</strong> Skin scraping for mites.</p>",
"</dd>",
"<dt><a href='#Section9'>Fixed drug eruption</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> History of medicine use.",
"<br><strong>Test:</strong> No differentiating test is available.</p>",
"</dd>",
"<dt><a href='#Section10'>Squamous cell carcinoma</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Non-healing ulcerative lesions present.",
"<br><strong>Test:</strong> Skin biopsy reveals carcinoma.</p>",
"</dd>",
"<dt><a href='#Section11'>Shingles on buttocks or lower extremities, or periorally</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Vesicles or pustules on an erythematous base present in both shingles and genital herpes. However, shingles typically erupts in a dermatomal distribution, with multiple lesions found over a wide distribution in a single dermatome, without extension over the midline.",
"<br><strong>Test:</strong> PCR of vesicular or pustular fluid for varcella-zoster.</p>",
"</dd>",
"</dl>"].join("\n");