content=["<dl>",
"<dt><a href='#Section0'>Acne vulgaris</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically occurs on the face, chest, and back. Morphology of lesions can be indistinguishable from HS lesions. However, acne vulgaris rarely results in draining sinus tracts. [1]",
"<br><strong>Test:</strong> No distinguishing tests.</p>",
"</dd>",
"<dt><a href='#Section1'>Crohn's disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Fistulas and sinus tracts are usually perianal in distribution. Patients may experience gastrointestinal symptoms, such as bloody diarrhoea, abdominal cramps, and lower abdominal pain. [1]",
"<br><strong>Test:</strong> Endoscopy and biopsy will show inflammation with disruption of crypt architecture; non-caseating granulomas may be present.The presence of granulomas on skin biopsy is suggestive but not diagnostic of cutaneous Crohn's disease.</p>",
"</dd>",
"<dt><a href='#Section2'>Psoriasis, inverse type</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are usually macerated red patches rather than discrete abscesses or nodules. [1]",
"<br><strong>Test:</strong> Skin biopsy may demonstrate classic findings of psoriasis: regular acanthosis, parakeratosis, and hypogranulosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Epidermal inclusion cyst</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents as a solitary lesion, which usually has a visible punctum at the surface. Inflammation is common. [1]",
"<br><strong>Test:</strong> Excisional biopsy is diagnostic and therapeutic.</p>",
"</dd>",
"<dt><a href='#Section4'>Furunculosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Presents as a solitary abscess often with a collarette of fine scale that is caused by Staphylococcus species. More often presents after abrasion of the skin or in immunocompromised patients. [1]",
"<br><strong>Test:</strong> Bacterial culture will demonstrate pathogenic bacteria, often MRSA.</p>",
"</dd>",
"<dt><a href='#Section5'>Lymphogranuloma venereum</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Sexually transmitted disease caused by Chlamydia trachomatis. Typically presents as a suppurative inguinal adenitis with pronounced lymphadenopathy that shows a characteristic groove sign. [1]",
"<br><strong>Test:</strong> Complement fixation test will show a titre &gt;1:64 or a 4-fold rise between acute and convalescent specimens. However, a complement fixation with a high titre in the absence of symptoms does not confirm lymphogranuloma venereum, and a low titre does not exclude it.</p>",
"</dd>",
"<dt><a href='#Section6'>Squamous cell carcinoma</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Usually ulcerated. May be a complication of HS.",
"<br><strong>Test:</strong> Skin biopsy will show evidence of malignancy with foci of keratinisation and formation of squamous whorls, where the neoplastic cells tightly wrap around each other.</p>",
"</dd>",
"</dl>"].join("\n");