content=["<dl>",
"<dt><a href='#Section0'>Meconium-plug syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> The expulsion of a plug of meconium with resolution of symptoms and the absence of other signs characteristic of Hirschsprung's disease help establish the diagnosis.",
"<br><strong>Test:</strong> Contrast enema can be both diagnostic and therapeutic.Air mixed with meconium show up as a soap bubble or calcification-like appearance on radiographs.</p>",
"</dd>",
"<dt><a href='#Section1'>Cystic fibrosis (meconium ileus)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Manifested by a clinical picture consistent with intestinal obstruction, with the child frequently exhibiting respiratory symptoms.A family history of cystic fibrosis may be noted.",
"<br><strong>Test:</strong> The absence of air-fluid levels in an upright abdominal film and the ground-glass appearance of the lower abdomen are characteristic radiographic signs.</p>",
"</dd>",
"<dt><a href='#Section2'>Small left colon syndrome</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms usually improve following contrast enema and resolve after several weeks.The mother is frequently diabetic.",
"<br><strong>Test:</strong> Contrast enema demonstrates a rather narrow left colon to the level of the splenic flexure.</p>",
"</dd>",
"<dt><a href='#Section3'>Hypothyroidism</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Colonic ileus and abdominal distension.The abdominal distension will accompany bradycardia, disinterest in eating, and other signs associated with hypothyroidism.",
"<br><strong>Test:</strong> TSH is elevated in primary hypothyroidism.</p>",
"</dd>",
"<dt><a href='#Section4'>Cerebral injury</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Colonic ileus and abdominal distension.A history of birth trauma can make one suspicious of this cause of ileus.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section5'>Chronic constipation</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> The proximal colon is huge and full of inspissated faecal material.Children usually become symptomatic after the sixth month of life; they neither vomit nor become seriously ill.Patients have overflow incontinence or encopresis, a constant, chronic soiling without evidence of neuromuscular disturbance.The rectum is impacted with stool.",
"<br><strong>Test:</strong> Rectal examination in these children reveals a severe faecal impaction just above the anal canal.Contrast enema shows a reverse pattern of dilation. In idiopathic constipation, the rectosigmoid is enormous and the proximal colon is normal caliber.</p>",
"</dd>",
"<dt><a href='#Section6'>Distal small bowel atresia or stenosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Abdominal distension and bilious vomiting.",
"<br><strong>Test:</strong> Plain x-ray often shows evidence of an intestinal atresia.Contrast enema will show a microcolon.</p>",
"</dd>",
"</dl>"].join("\n");