content=["<dl>",
"<dt><a href='#Section0'>Tardive dyskinesia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically does not have a family history.Can occur in patients treated with antipsychotic medicines or metoclopramide. [32]Tends to have a distinct oral, buccal, and lingual predominance, with speech and swallowing relatively unaffected.Motor impersistence not seen.Not progressive.",
"<br><strong>Test:</strong> The distinction between tardive dyskinesia and Huntington's disease is primarily clinical.In the unlikely event it is needed, CAG repeat testing is normal.Referral to a movement disorders consultant would typically be more cost effective.</p>",
"</dd>",
"<dt><a href='#Section1'>Dentatorubro-pallidoluysian atrophy (DRPLA)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> More common in Asian people but otherwise may be phenotypically indistinguishable from Huntington's disease. [33]In juvenile or early-onset cases, myoclonic epilepsy is a finding highly suggestive of DRPLA.In black patients, DRPLA may manifest without myoclonic epilepsy.",
"<br><strong>Test:</strong> CAG repeat testing is normal, but testing for the gene for DRPLA (atrophin-1) will be positive.In black patients, MRI may demonstrate globus pallidus micro-calcifications with demyelination in the centrum semiovale (Haw River syndrome).</p>",
"</dd>",
"<dt><a href='#Section2'>Neuroacanthocytosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Often has associated areflexia and distal amyotrophy with greater prominence of oral and lingual chorea with tics and tongue biting. [34]May be phenotypically indistinguishable from Huntington's disease but inheritance is autosomal recessive.",
"<br><strong>Test:</strong> CAG repeat testing is normal.Acanthocytes may be present on the peripheral blood smear, but repeated tests or dilution may be needed to discover them.It is helpful to direct the laboratory to comment specifically on RBC morphology.Creatine kinase is often elevated.The genetic abnormality is a frame shift mutation in the gene coding for chorein.</p>",
"</dd>",
"<dt><a href='#Section3'>Benign hereditary chorea</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> An autosomal dominant disorder tending to be one of fairly early onset with very slow progression, without cognitive dysfunction or the other disabling features of Huntington's disease. [35]  [36]Atypical features, with some functional impairment, may occur.",
"<br><strong>Test:</strong> CAG repeat testing is normal.An abnormality can be found in the gene coding for thyroid transcription factor 1 (TTF1).</p>",
"</dd>",
"<dt><a href='#Section4'>McLeod syndrome (or McLeod myopathy)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> X-linked disorder; may be indistinguishable from Huntington's disease. [37]May have the additional features of axonal motor neuropathy, myopathy, cardiomyopathy, and anaemia.",
"<br><strong>Test:</strong> FBC testing reveals acanthocytes, haemolytic anaemia.Serum creatine kinase is elevated.There is an abnormality in the gene XK (Kell erythrocyte antigen).CAG repeat testing is normal.</p>",
"</dd>",
"<dt><a href='#Section5'>Spinocerebellar ataxia 17</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Tends to have more prominent ataxia but may be clinically indistinguishable from Huntington's disease. [38]  [39]",
"<br><strong>Test:</strong> Genetic tests for SCA 17 reveal a CAG repeat disorder affecting the TATA binding protein.CAG repeat testing is normal.</p>",
"</dd>",
"<dt><a href='#Section6'>Huntington's disease-like-1 (HDL1)</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> A familial prion disorder that can be phenotypically indistinguishable from Huntington's disease. [40]",
"<br><strong>Test:</strong> CAG repeat testing for Huntington's disease is normal.Genetic testing reveals a PRNP gene mutation.Cerebellar atrophy and multi-centric plaques that stain with antiprion antibodies may be found at autopsy.</p>",
"</dd>",
"<dt><a href='#Section7'>Huntington's disease-like-2 (HDL2)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Seen primarily in black patients.Phenotypically identical to Huntington's disease. [38]",
"<br><strong>Test:</strong> CAG repeat testing for Huntington's disease is normal but a CAG/CTG repeat disorder is found in the gene for junctophilin-3.</p>",
"</dd>",
"<dt><a href='#Section8'>Huntington's disease-like-3 (HDL3)</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Phenotypically similar to Huntington's disease. [41]  [42]",
"<br><strong>Test:</strong> CAG repeat testing for Huntington's disease is normal.The gene for HDL3 is not known.</p>",
"</dd>",
"<dt><a href='#Section9'>Neurodegeneration with brain iron accumulation (NBIA; Hallervorden Spatz syndrome)</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Autosomal recessive disorder. [43]May be phenotypically indistinguishable from Huntington's disease.",
"<br><strong>Test:</strong> MRI scan shows a characteristic hypointense globus pallidus with foci of hyperintensity ('eye of the tiger' sign).CAG repeat testing is normal.PANK2 (pantothenate kinase) mutations are present on genetic testing.</p>",
"</dd>",
"<dt><a href='#Section10'>Neuroferritinopathy (NBIA2)</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> May be phenotypically indistinguishable from Huntington's disease. [44]Tends to have more facial action dystonia and more asymmetry of findings.",
"<br><strong>Test:</strong> MRI shows a T2 signal loss in the basal ganglia.Serum ferritin may be decreased.CAG repeat testing is normal; mutations for the ferritin light chain (FTL) are present.</p>",
"</dd>",
"<dt><a href='#Section11'>Hyperthyroid chorea</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Chorea and behavioural abnormalities may be manifestations of thyrotoxicosis. [45]",
"<br><strong>Test:</strong> Elevated thyroid function tests will be seen.CAG repeat testing is normal.</p>",
"</dd>",
"<dt><a href='#Section12'>Chorea gravidarum</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Typically, this is a manifestation of the first trimester of pregnancy, is non-hereditary, is of acute onset, and is not associated with other features of Huntington's disease. [46]",
"<br><strong>Test:</strong> Pregnancy testing is positive.</p>",
"</dd>",
"<dt><a href='#Section13'>Sydenham chorea</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Typically seen in children or young adults. [47]Sub-acute, sometimes asymmetrical in onset, non-hereditary, and post-infectious.",
"<br><strong>Test:</strong> Antistreptolysin O titres are elevated.</p>",
"</dd>",
"<dt><a href='#Section14'>Lupus cerebritis</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Rarely, chorea and/or cognitive impairment may be manifestations of CNS lupus erythematosus. [48]It is not associated with other features of Huntington's disease.",
"<br><strong>Test:</strong> ANA titres are elevated.</p>",
"</dd>",
"<dt><a href='#Section15'>Antiphospholipid antibody syndrome</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> May cause chorea in some patients and sometimes begins asymmetrically. [49]It is not associated with other features of Huntington's disease.",
"<br><strong>Test:</strong> Antiphospholipid antibodies are detected.</p>",
"</dd>",
"<dt><a href='#Section16'>Wilson's disease (hepatolenticular degeneration)</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Associated with a progressive (usually non-choreiform) movement disorder, psychiatric and cognitive deficits, and progressive hepatic dysfunction. [50]Resembles juvenile Huntington's disease.",
"<br><strong>Test:</strong> CAG repeat testing is normal.Serum ceruloplasmin is decreased. Serum and urine copper abnormalities, Kayser-Fleischer rings, and MRI abnormalities are readily apparent.In early cases serum ceruloplasmin may be in the low-normal range.</p>",
"</dd>",
"</dl>"].join("\n");