content=["<dl>",
"<dt><a href='#Section0'>Inguinal hernia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> An incarcerated inguinal hernia may be difficult to distinguish from a hydrocele.",
"<br><strong>Test:</strong> A groin ultrasound will show abnormal ballooning of the anteroposterior diameter of the inguinal canal. Occasionally, a segment of omentum (fat) or a segment of the bowel is seen.</p>",
"</dd>",
"<dt><a href='#Section1'>Testicular cancer</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> These will usually be solid, firm masses that are not transilluminated. However, tumours may have reactive hydroceles surrounding them, and these will be transilluminated.",
"<br><strong>Test:</strong> Scrotal ultrasound will confirm the diagnosis. [17]  Testicular tumour markers, such as alpha-fetoprotein or beta-hCG, may also be used to indicate tumour activity.</p>",
"</dd>",
"<dt><a href='#Section2'>Epididymitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Clinically the patient has pain and tenderness in the scrotum, and local inflammatory changes can be seen. [18]",
"<br><strong>Test:</strong> Colour Doppler ultrasonography will confirm the diagnosis. [2]</p>",
"</dd>",
"<dt><a href='#Section3'>Epididymo-orchitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Scrotal tenderness and swelling. Clinically, the patient has pain and tenderness in the scrotum, and local inflammatory changes can be seen. [18]",
"<br><strong>Test:</strong> Color Doppler ultrasonography will confirm the diagnosis. [2]</p>",
"</dd>",
"<dt><a href='#Section4'>Epididymal cyst</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Scrotal mass that can be transilluminated. The position of the cyst helps the diagnosis. The cyst can be palpated separately from the testis, lying posterior and superior to it. [18]",
"<br><strong>Test:</strong> Scrotal ultrasound may assist in making the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Scrotal oedema</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Thickening of the scrotal wall.",
"<br><strong>Test:</strong> Diagnosis is best made by scrotal examination. Scrotal ultrasound may be beneficial. [17]</p>",
"</dd>",
"<dt><a href='#Section6'>Testicular torsion</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Extreme tenderness, elevation of the testis, loss of landmarks, and absence of a cremasteric reflex are characteristic signs of torsion.",
"<br><strong>Test:</strong> Color Doppler ultrasonography will confirm the diagnosis. [2]  [9]</p>",
"</dd>",
"<dt><a href='#Section7'>Varicocele</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Palpation of enlarged veins during Valsalva manoeuvre is diagnostic on physical examination.",
"<br><strong>Test:</strong> Physical examination is diagnostic, but colour Doppler ultrasonography can be used for confirmation. [2]  [9]</p>",
"</dd>",
"</dl>"].join("\n");