content=["<dl>",
"<dt><a href='#Section0'>Viral pneumonia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Viral pneumonias typically lasts a week or so. Acute HP lasts only a few days and recurs with each additional exposure. Ordinarily, a person should not have repeated episodes of viral pneumonia.",
"<br><strong>Test:</strong> Bronchoalveolar lavage of both HP and viral pneumonia will demonstrate increased CD8+ cells; molecular diagnosis can identify common viral causes of pneumonia such as influenza A and B; respiratory syncytial virus; parainfluenza 1, 2, and 3; picornavirus; coronavirus; and adenovirus.</p>",
"</dd>",
"<dt><a href='#Section1'>Sarcoidosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Stage III can resemble chronic HP; HP does not have extrapulmonary manifestations.",
"<br><strong>Test:</strong> Sarcoidosis tends to have an increased CD4/CD8 ratio following bronchoalveolar lavage.Biopsy may be necessary to differentiate.</p>",
"</dd>",
"<dt><a href='#Section2'>Bronchiolitis obliterans</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Can resemble chronic HP.",
"<br><strong>Test:</strong> The diffusing lung capacity of carbon monoxide (DLCO) is normal and the PFTs are of the obstructive pattern.</p>",
"</dd>",
"<dt><a href='#Section3'>Usual interstitial pneumonia (UIP)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> There are no differentiating signs or symptoms.",
"<br><strong>Test:</strong> Bronchoalveolar lavage in UIP should not show a lymphocytosis, and the histology of chronic HP tends to be bronchocentric with increased inflammation and occasional granulomata. [29]  [30]  [31]</p>",
"</dd>",
"<dt><a href='#Section4'>Desquamative interstitial pneumonia</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients are usually smokers or have an associated connective tissue disease.",
"<br><strong>Test:</strong> Bronchoalveolar lavage may show an increase in brown macrophages, and sometimes neutrophils. HP tends to have lymphocytosis. [32]</p>",
"</dd>",
"<dt><a href='#Section5'>Pneumoconioses</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients should have appropriate exposure history (mineral dust or a metal).",
"<br><strong>Test:</strong> CXR not likely to demonstrate only fibrosis; there may be pleural calcification (asbestosis) or eggshell calcification of hilar lymph nodes (silicosis).Neutrophils and causative dust particles may be found in bronchoalveolar lavage.</p>",
"</dd>",
"<dt><a href='#Section6'>Silo filler's lung</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> May appear similar to acute HP; generally symptoms last longer as they are caused by chemical inhalation toxicity; occurs on first exposure as sensitisation is not required.",
"<br><strong>Test:</strong> Bronchiolar lavage tends to demonstrate increased neutrophils, as opposed to lymphocytosis.</p>",
"</dd>",
"<dt><a href='#Section7'>Organic toxic dust syndrome</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> May appear similar to acute HP; generally symptoms last longer as they are caused by chemical inhalation toxicity; occurs on first exposure as sensitisation is not required.",
"<br><strong>Test:</strong> Bronchoalveolar lavage tends to demonstrate increased neutrophils, as opposed to lymphocytosis.</p>",
"</dd>",
"<dt><a href='#Section8'>Metal fume fever</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> May appear similar to acute HP; generally symptoms last longer as they are caused by zinc oxide or magnesium oxide; occurs on first exposure as sensitisation is not required.",
"<br><strong>Test:</strong> Bronchoalveolar lavage tends to demonstrate increased neutrophils, as opposed to lymphocytosis.</p>",
"</dd>",
"</dl>"].join("\n");