content=["<dl>",
"<dt><a href='#Section0'>Hypovitaminosis D</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Poor diet, short gut, lack of sunlight, malabsorption or other mechanism leading to fat-soluble vitamin deficiency.",
"<br><strong>Test:</strong> The best differentiating test is a low or inappropriately normal PTH with hypoparathyroidism, and elevated PTH with hypovitaminosis D.Plasma 25-hydroxyvitamin D3 normal range 10 to 68 nanogram/mL (24.9-169.5 nanomol/L).Serum 1,25-dihydroxyvitamin D3 (active form), normal range 25 to 45 picogram/mL (60-108 picomol/L).</p>",
"</dd>",
"<dt><a href='#Section1'>Hypomagnesaemia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Hypocalcaemia symptoms out of proportion to calcium deficiency.Hypomagnesaemia may be the sole cause of hypocalcaemia or may aggravate relative hypoparathyroidism.",
"<br><strong>Test:</strong> Serum magnesium low. Serum calcium may be normal or low.</p>",
"</dd>",
"<dt><a href='#Section2'>Hypoproteinaemia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May be asymptomatic. If severe, may have third spacing of fluid (oedema, anasarca, ascites).",
"<br><strong>Test:</strong> Low serum protein (normal value 55-80 g/L [5.5-8.0 g/dL]) and albumin (normal 35-55 g/L [3.5-5.5 g/dL]).About half of the total calcium is bound to serum protein, largely to albumin. If albumin is low, total calcium will be low, although there may be no physiologic deficiency. For US units (calcium in mg/dL; albumin in g/dL), the formula for corrected serum calcium is (0.8 x (normal albumin - patient&rsquo;s albumin)) + serum calcium. For SI units (calcium in mmol/L; albumin in g/L), the formula for corrected serum calcium is (0.02 x (normal albumin - patient&rsquo;s albumin)) + serum calcium. However, formulae used to calculate corrected calcium only provide an approximation, and this measurement may not be reliable for the critically ill patients. [9]  [10]  Measurement of ionised calcium is preferred.Physiological calcium may be directly measured by checking ionised calcium.</p>",
"</dd>",
"<dt><a href='#Section3'>Respiratory alkalosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hyperventilation may be organic (anxiety, compensatory) or may be iatrogenic (mechanical ventilation).",
"<br><strong>Test:</strong> Normal serum calcium despite symptoms. ABG shows high pH and low PaCO2 consistent with hyperventilation. Intravenous calcium will temporarily alleviate symptoms but the response in hyperventilation will be brief.</p>",
"</dd>",
"<dt><a href='#Section4'>Renal failure</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms may be related to diminished clearance rate for renally cleared medication; at end stage, oliguria or anuria, pruritus, mental status changes, volume overload.",
"<br><strong>Test:</strong> PTH is usually elevated in hypocalcaemia due to renal disease.Elevated serum urea, creatinine.Serum phosphorus is usually high in renal failure rather than low as in hypoparathyroidism.</p>",
"</dd>",
"</dl>"].join("\n");