content=["<dl>",
"<dt><a href='#Section0'>Pituitary macro-adenoma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Headache and bi-temporal hemianopia symptoms related to other pituitary hormonal deficiencies; for example, weight loss and nausea due to adrenal insufficiency, or cold intolerance and constipation due to hypothyroidism.",
"<br><strong>Test:</strong> Low LH and FSH levels with pituitary macro-adenoma.Possible low TSH, growth hormone and cortisol levels.MRI of the pituitary reveals pituitary lesion.</p>",
"</dd>",
"<dt><a href='#Section1'>Prolactinoma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Headache, bi-temporal hemianopia, and occasional galactorrhoea.",
"<br><strong>Test:</strong> MRI of the pituitary reveals pituitary lesion.Serum prolactin elevated.</p>",
"</dd>",
"<dt><a href='#Section2'>Hyperprolactinaemia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Galactorrhoea may be present.Headache may be present if hyperprolactinaemia is secondary to prolactinoma.",
"<br><strong>Test:</strong> Elevated prolactin levels. Hypothyroidism and medicines such as dopamine antagonists should be excluded.</p>",
"</dd>",
"<dt><a href='#Section3'>Depression</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Depression resulting in reduced libido.Psychogenic erectile dysfunction.",
"<br><strong>Test:</strong> With depression, hormonal tests may be normal.Normal early morning erections will still occur if erectile dysfunction is psychogenic.</p>",
"</dd>",
"</dl>"].join("\n");