content=["<dl>",
"<dt><a href='#Section0'>Specific antibody deficiency</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Clinical features of lesser severity.",
"<br><strong>Test:</strong> Immunoglobulins: normal.Specific antimicrobial antibodies after immunisation: low.</p>",
"</dd>",
"<dt><a href='#Section1'>Hyposplenism</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May be hx of splenectomy, sickle cell disease, coeliac disease (also common in IgA deficiency).",
"<br><strong>Test:</strong> FBC: thrombocytosis, Howell-Jolly bodies.Abdominal ultrasound: absence of or small spleen.</p>",
"</dd>",
"<dt><a href='#Section2'>Complement deficiency</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Complement (C)3 deficiency predisposes to pyogenic infection; C5b-9 deficiency predisposes to meningococcal and gonococcal infection.",
"<br><strong>Test:</strong> Complement function testing: reduced.Complement component: reduced.</p>",
"</dd>",
"<dt><a href='#Section3'>Mannose-binding lectin deficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Many patients are asymptomatic. Typically more common in infancy and in the presence of another immunosuppressive factor (e.g., after transplantation).",
"<br><strong>Test:</strong> Mannose-binding lectin (MBL) levels: reduced.Genetic testing: MBL deficiency genotype.</p>",
"</dd>",
"<dt><a href='#Section4'>Cystic fibrosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Positive FHx of cystic fibrosis. Infants and children with untreated pancreatic insufficiency may have voracious appetites and never seem satiated. Approximately 10% to 20% of newborns may have delayed passage of meconium or even bowel obstruction with meconium. In males, examination of the scrotum may reveal bilateral absence of the vas deferens.",
"<br><strong>Test:</strong> Sweat test: positive (sweat chloride &ge;60 mmol/L [&ge;60 mEq]).Immunoreactive trypsinogen test: positive.Genetic testing: presence of 2 disease-causing mutations.</p>",
"</dd>",
"<dt><a href='#Section5'>Anatomical anomalies of sinuses/lungs</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Other known congenital defects.",
"<br><strong>Test:</strong> CT chest and sinuses: abnormalities visible such as obstructive bronchial lesions (e.g., neoplasms in older patients).</p>",
"</dd>",
"</dl>"].join("\n");