content=["<dl>",
"<dt><a href='#Section0'>Non-specific interstitial pneumonia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> More commonly associated with collagen vascular disease; therefore, patients may have skin, joint, or other systemic manifestations.",
"<br><strong>Test:</strong> More ground-glass opacities on chest CT, absence of honeycombing.Presence of auto-antibodies if secondary to an underlying connective tissue disease. [45]</p>",
"</dd>",
"<dt><a href='#Section1'>Cryptogenic organising pneumonia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Formerly called bronchiolitis obliterans-organising pneumonia or BOOP; more commonly associated with prior infection or collagen vascular disease.Systemic manifestation of weight loss, fever, joint symptoms, and rash are more common. [46]",
"<br><strong>Test:</strong> Patchy consolidation, isolated nodules, or infiltrative reticulation on chest CT. [46]</p>",
"</dd>",
"<dt><a href='#Section2'>Acute interstitial pneumonia (AIP)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Occurs over weeks in a previously healthy individual, often with 'influenza-like' prodrome.AIP is rare and frequently progresses to hypoxaemia and respiratory failure. [44]",
"<br><strong>Test:</strong> Chest imaging demonstrates diffuse bilateral ground glass or frank alveolar filling pattern. [45]</p>",
"</dd>",
"<dt><a href='#Section3'>Respiratory bronchiolitis-associated interstitial lung disease</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Similar respiratory symptoms.Affects people who smoke. [44]",
"<br><strong>Test:</strong> Diffuse fine nodular or reticular changes on chest CT. [45]Combined obstruction and restriction on PFTs. [1]</p>",
"</dd>",
"<dt><a href='#Section4'>Desquamative interstitial pneumonia</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Rare, affects people who smoke, sub-acute illness, no scarring fibrosis. [1]",
"<br><strong>Test:</strong> Diffuse ground-glass opacities on CT.Restrictive pattern on PFTs. [45]</p>",
"</dd>",
"<dt><a href='#Section5'>Lymphoid interstitial pneumonia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Often secondary to Sjogren's syndrome, HIV, or a dysproteinaemia, so patients may have signs/symptoms of those diseases.",
"<br><strong>Test:</strong> Nodules, ground-glass opacities, reticulation, and thin-walled cysts may be present on CT. [45]</p>",
"</dd>",
"<dt><a href='#Section6'>Connective tissue disease-associated IPF</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Skin, joint, or other serological abnormalities will be present. [47]Rash may be present.",
"<br><strong>Test:</strong> May have less 'typical' chest CT with less peripheral predominance.Presence of autoantibodies related to connective tissue.</p>",
"</dd>",
"<dt><a href='#Section7'>Drug-related pulmonary fibrosis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Respiratory symptoms similar to those of IPF will be related to exposure to medications such as amiodarone, nitrofurantoin, and bleomycin, which are thought to cause pulmonary fibrosis.",
"<br><strong>Test:</strong> Chest CT and PFTs are non-specific.</p>",
"</dd>",
"<dt><a href='#Section8'>Asbestosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> History of asbestos exposure.Physical findings will be normal in pleural disease unless the pleural thickening is diffuse or there is a benign pleural effusion. In these cases, breath sounds will be diminished on auscultation and dullness to percussion may be present.",
"<br><strong>Test:</strong> Pleural plaques may be present on chest imaging; ferruginous bodies can be found on biopsy. [47]</p>",
"</dd>",
"<dt><a href='#Section9'>Hypersensitivity pneumonitis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Respiratory symptoms are typically associated with acute exposure to causal antigen such as bacteria or mould in silage or hay.",
"<br><strong>Test:</strong> Presence of IgG antibodies in the blood to the causal antigen, a ground-glass appearance on high-resolution CT, and granulomas on lung biopsy.</p>",
"</dd>",
"<dt><a href='#Section10'>Sarcoidosis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Extra-pulmonary involvement.By comparison with IPF, younger patients affected.",
"<br><strong>Test:</strong> Lymphadenopathy is more evident on chest imaging. [47]</p>",
"</dd>",
"<dt><a href='#Section11'>Langerhans' cell histiocytosis</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Rare disease.History of smoking and spontaneous pneumothorax.",
"<br><strong>Test:</strong> Cystic disease with nodules in upper- and mid-lung zones on chest CT.</p>",
"</dd>",
"<dt><a href='#Section12'>Lymphangioleiomyomatosis</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Rare disease.Pre-menopausal women are affected; spontaneous pneumothorax is common.",
"<br><strong>Test:</strong> Thin-walled cystic disease throughout the lung; combined obstruction and restriction on PFTs.</p>",
"</dd>",
"</dl>"].join("\n");