content=["<dl>",
"<dt><a href='#Section0'>Mechanical bowel obstruction</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Localised pain; symptoms start acutely.",
"<br><strong>Test:</strong> Shares many of the same signs and symptoms as ileus, so differentiating can be challenging. Obstructive series shows step-wise air-fluid levels and very dilated loops of small bowel.CT scan shows a transition zone (dilated loops leading up to collapsed loops of bowel), and oral contrast does not reach distal to the point of obstruction.</p>",
"</dd>",
"<dt><a href='#Section1'>Pseudo-obstruction (Ogilvie's syndrome)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Crampy abdominal pain, anorexia. Typically seen in bed-bound, older, or chronically ill patients with polypharmacy. [41]  [42]",
"<br><strong>Test:</strong> X-rays show isolated large bowel dilatation.CT scan or gastrograffin enema will show no evidence of mechanical obstruction.</p>",
"</dd>",
"<dt><a href='#Section2'>Gastroenteritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Hx should indicate a likely gastroenteritis, along with symptoms of diarrhoea. It is generally self-limited.A patient with no risk factors for ileus who is also having diarrhoea is likely to have gastroenteritis.",
"<br><strong>Test:</strong> Clinical diagnosis. Further testing may be non-specific and unhelpful.</p>",
"</dd>",
"<dt><a href='#Section3'>Pancreatitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Acute abdominal pain.",
"<br><strong>Test:</strong> Elevated amylase and lipase.May have gall stones on RUQ ultrasound.Abdominal CT scan shows diffuse or segmental enlargement of the pancreas with irregular contour and obliteration of the peri-pancreatic fat, necrosis, or pseudocysts.</p>",
"</dd>",
"<dt><a href='#Section4'>Acute cholecystitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Pain in the epigastrum and right upper quadrant of the abdomen.",
"<br><strong>Test:</strong> Distended gallbladder, thickened gallbladder wall, and presence of gall stones on RUQ ultrasound.Abdominal CT scan shows gallbladder wall inflammation; linear high density areas in peri-cholecystic fat tissue.</p>",
"</dd>",
"<dt><a href='#Section5'>Bowel perforation</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Severe abdominal pain, fever.",
"<br><strong>Test:</strong> Abdominal x-ray demonstrates free intraperitoneal air.A CT scan demonstrates bowel perforation.</p>",
"</dd>",
"<dt><a href='#Section6'>Intra-abdominal abscess</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Fever, anorexia, crampy abdominal pain and tenderness.",
"<br><strong>Test:</strong> A CT scan demonstrates abscess.</p>",
"</dd>",
"<dt><a href='#Section7'>Peritonitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Pain and tenderness of the abdominal wall. Hx and physical examination to evaluate for risk factors and elicit signs of peritonitis.",
"<br><strong>Test:</strong> A CT scan demonstrates peritonitis.</p>",
"</dd>",
"<dt><a href='#Section8'>Intestinal pneumatosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Diarrhoea, bloody stools, abdominal pain.",
"<br><strong>Test:</strong> A CT scan demonstrates pneumatosis.</p>",
"</dd>",
"</dl>"].join("\n");