content=["<dl>",
"<dt><a href='#Section0'>Herpes simplex</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Monomorphic grouped vesicles.",
"<br><strong>Test:</strong> Viral PCR.Viral direct immunofluorescence swab or viral culture and Tzanck prep when PCR unavailable.</p>",
"</dd>",
"<dt><a href='#Section1'>Varicella</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Widespread vesicles at different stages.Oral mucosa may be affected.",
"<br><strong>Test:</strong> Viral PCR.Viral direct immunofluorescence swab or viral culture and Tzanck prep when PCR unavailable.</p>",
"</dd>",
"<dt><a href='#Section2'>Dermatophytosis (Tinea corporis, Tinea capitis)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Peripheral scale.Central clearing.Crusting infrequent except in scalp kerion.Bullous dermatophytosis commonly occurs on the instep of the foot.",
"<br><strong>Test:</strong> Microscopy of skin scrapings and fungal culture.</p>",
"</dd>",
"<dt><a href='#Section3'>Candida</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Satellite lesions.Affected areas are usually more confluent.",
"<br><strong>Test:</strong> Bacteriology swab for culture.</p>",
"</dd>",
"<dt><a href='#Section4'>Discoid dermatitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Pruritus invariably present.Very fine circular scaling or vesicles.",
"<br><strong>Test:</strong> Skin biopsy confirmatory.</p>",
"</dd>",
"<dt><a href='#Section5'>Pemphigus vulgaris</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Larger superficial blisters may be seen early. Seen more commonly in older patients.Prominent mucosal involvement.",
"<br><strong>Test:</strong> Skin biopsy confirmatory.Immunofluorescence helpful.</p>",
"</dd>",
"<dt><a href='#Section6'>Stevens-Johnson syndrome</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Involvement of the conjunctiva.Patient systemically ill.",
"<br><strong>Test:</strong> Skin biopsy confirmatory.</p>",
"</dd>",
"<dt><a href='#Section7'>Bullous erythema multiforme</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Target lesions with violaceous centre.Patient uncomfortable.",
"<br><strong>Test:</strong> Skin biopsy confirmatory.</p>",
"</dd>",
"<dt><a href='#Section8'>Dermatitis herpetiformis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Multiple vesicles grouped on the lower back and around the elbows and knees.Intensely pruritic vesicles.",
"<br><strong>Test:</strong> Skin biopsy confirmatory.</p>",
"</dd>",
"</dl>"].join("\n");