content=["<dl>",
"<dt><a href='#Section0'>Group A streptococcal pharyngitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Epstein Barr virus (EBV) pharyngitis may be clinically indistinguishable from streptococcal pharyngitis.",
"<br><strong>Test:</strong> Throat culture for group A streptococcus is positive.However, 3% to 30% of patients with IM may have positive throat culture for group A streptococcus, and differentiating carrier state from true streptococcal infection in patients with IM can be challenging. [37]  [38]  If EBV is strongly suspected, routine throat culture is not necessary.Antibiotics should be used only for uncommon cases of true concomitant streptococcal infection, after the throat culture confirmation of group A streptococci. Unnecessary use of ampicillin, amoxicillin, or beta-lactams frequently results in a rash in patients with IM.</p>",
"</dd>",
"<dt><a href='#Section1'>Hepatitis A</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Presents with fever, abdominal pain, jaundice, and malaise. Hepatomegaly is common. Eyelid oedema, pharyngitis, adenopathy, splenomegaly, and atypical lymphocytosis are usually absent with hepatitis A.",
"<br><strong>Test:</strong> Aminotransferases (ALT/AST) elevated 10 fold or greater.Positive hepatitis A serology.Heterophile antibody negative.</p>",
"</dd>",
"<dt><a href='#Section2'>Acute HIV infection</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Early HIV infection can cause an acute illness with fever, malaise, lymphadenopathy, and maculopapular, blanching rash.Less prominent pharyngitis; more frequent rash; presence of diarrhoea with HIV.",
"<br><strong>Test:</strong> Plasma viral load test (PVL) is positive.ELISA HIV test may be positive. However, often negative in the acute infection, and IM may cause false-positive result.</p>",
"</dd>",
"<dt><a href='#Section3'>Adenovirus</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Coryza, cough, pneumonia, conjunctivitis, diarrhoea are typically present in adenovirus infection.",
"<br><strong>Test:</strong> Nasopharyngeal swab for culture of respiratory viruses is positive for adenovirus.</p>",
"</dd>",
"<dt><a href='#Section4'>Human herpes virus-6</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Common febrile illness of early childhood; disease course is characterized by 3 to 5 days of fever followed by a typical exanthem of rose-pink macules and papules that appear with defervescence on the trunk, neck, proximal extremities, and occasionally on the face . Prolonged febrile mononucleosis syndrome in adults. Prolonged febrile mononucleosis syndrome in adults.",
"<br><strong>Test:</strong> Anti-HHV-6 IgM and IgG positive.</p>",
"</dd>",
"<dt><a href='#Section5'>Cytomegalovirus infection</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Infection in healthy individuals can be asymptomatic or symptoms may resemble mononucleosis syndrome (fever, malaise, pharyngitis). Physical exam may show lymphadenopathy and splenomegaly.",
"<br><strong>Test:</strong> Aminotransferases or alkaline phosphatase are frequently elevated; CMV serology is the most accessible test in the community setting and often sufficient for diagnosis in immunocompetent individuals. Viral culture, PCR, or pp65 antigen detection may be used if available.</p>",
"</dd>",
"<dt><a href='#Section6'>Herpes simplex virus-1</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Exudative pharyngitis, gingivostomatitis, odynophagia.",
"<br><strong>Test:</strong> Viral throat culture, PCR.</p>",
"</dd>",
"</dl>"].join("\n");