content=["<dl>",
"<dt><a href='#Section0'>Undescended testis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Presence of a groin mass. Underdeveloped hemiscrotum with absent testis on the affected side.Inguinal hernia is associated with fully developed hemiscrotum and the bulge in the groin is associated with expansible cough impulse.",
"<br><strong>Test:</strong> Groin ultrasound scan is able to detect an undescended testis from an inguinal hernia. Other tests such as CT scan of the mass and MRI scan, are equally sensitive.</p>",
"</dd>",
"<dt><a href='#Section1'>Lymphadenopathy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> An enlarged lymph node may be associated with a history of trauma, infection or malignancy. It is not associated with cough impulse. Lymphadenopathy, like strangulated hernia, may be tender but, unlike hernia, one can get above the mass and it may be mobile.",
"<br><strong>Test:</strong> Groin ultrasound scan may show internal echo on sonogram in cases of lymphadenopathy, whereas hernia may show abnormal ballooning of the anteroposterior diameter of the inguinal canal.</p>",
"</dd>",
"<dt><a href='#Section2'>Femoral hernia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Distinguishing between femoral and inguinal hernia is difficult. Femoral hernias are more common in females and more prone to strangulation. It is often preceded by a history of recent weight loss.",
"<br><strong>Test:</strong> Anatomical localisation by ultrasound, CT or MRI will show a femoral hernia lateral and below the pubic tubercle. An inguinal hernia is superomedial to the pubic tubercle.</p>",
"</dd>",
"<dt><a href='#Section3'>Femoral aneurysm</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Differentiated from inguinal hernia by the presence of pulsatile mass.",
"<br><strong>Test:</strong> Femoral artery aneurysm may be distinguished from inguinal hernia by a Doppler or Duplex scan that reveals blood flow.</p>",
"</dd>",
"<dt><a href='#Section4'>Psoas abscess</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> May present with back pain and fever. Recent history of foreign travel or contact with someone with chronic cough, weight loss and night sweats are not uncommon.",
"<br><strong>Test:</strong> MRI and CT scan will show an abscess as an inflammatory mass within the psoas muscle.</p>",
"</dd>",
"<dt><a href='#Section5'>Saphena varix</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Dilated great saphenous vein close to the saphenofemoral junction because of incompetent saphenofemoral valve. Often, there are signs elsewhere of varicosity. Typically it is soft, compressible and, like inguinal hernia, it disappears on lying supine. It is also associated with a cough impulse and a fluid thrill.",
"<br><strong>Test:</strong> Doppler or Duplex scan will show blood flow.</p>",
"</dd>",
"<dt><a href='#Section6'>Vaginal hydrocele</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> This is the most common form of primary hydrocele. Although rare in children, it is common in middle age to old age. In this, the hydrocele surrounds the testicle and is not in communication with the peritoneal cavity. Testis and epididymis are not easily defined. The ability to get above the swelling is the key differentiating feature. Often, it transilluminates brilliantly.",
"<br><strong>Test:</strong> Investigation is usually not required.</p>",
"</dd>",
"<dt><a href='#Section7'>Encysted hydrocele of the spermatic cord</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> This is a rare form of hydrocele in which the hydrocele that is separated from the peritoneal cavity and testis is associated with the spermatic cord. Its presence may be confirmed clinically by pulling down on the testicle and seeing the lump follow.",
"<br><strong>Test:</strong> Investigation is usually not required.</p>",
"</dd>",
"<dt><a href='#Section8'>Lipoma of the spermatic cord</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Lipoma of the cord is often difficult to distinguish clinically from hernia. Clinically, it is soft to touch.",
"<br><strong>Test:</strong> Ultrasound shows an echogenic solid mass.</p>",
"</dd>",
"<dt><a href='#Section9'>Spermatocele</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Cyst attached to the head of the epididymis. Smooth and able to get above it on examination. Often transilluminates.",
"<br><strong>Test:</strong> Investigation is usually not required.</p>",
"</dd>",
"<dt><a href='#Section10'>Hydrocele of canal of Nuck</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> In females, if the processus vaginalis remains patent, it extends into the labium majus and is known as the canal of Nuck. It may easily be confused with inguinal hernia.",
"<br><strong>Test:</strong> Ultrasound shows a well-defined, cystic, hypoechogenic mass.</p>",
"</dd>",
"</dl>"].join("\n");