content=["<dl>",
"<dt><a href='#Section0'>Cellulitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Hx of previous episodes of cellulitis; ulcer or wound; dermatosis; tinea pedis interdigitalis; lymphedoema; venous insufficiency or chronic leg oedema.",
"<br><strong>Test:</strong> FBC: elevated WBC.Blood cultures: positive.Purulent focus culture: positive.</p>",
"</dd>",
"<dt><a href='#Section1'>Periorbital and orbital cellulitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Hx of previous sinus infection, lack of Haemophilus influenzae type b vaccination; stye or chalazion; recent eye trauma.",
"<br><strong>Test:</strong> FBC: elevated WBC.Blood cultures: positive.Microbiology eye swab: positive.</p>",
"</dd>",
"<dt><a href='#Section2'>Abscess</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Red, tender, fluctuant mass; fever; purulent drainage.",
"<br><strong>Test:</strong> Incision and drainage yields pus/necrotic material. Culture can identify infectious organism.</p>",
"</dd>",
"<dt><a href='#Section3'>Necrotising fasciitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hx of immunosuppression due to chronic illness (e.g., diabetes mellitus, alcoholism); cutaneous trauma or ulcerative skin conditions; varicella zoster infections; hospitalisation.",
"<br><strong>Test:</strong> FBC: elevated WBC.Urea and creatinine: elevated.Sodium: normal or reduced.Serum creatinine phosphokinase: elevated.Blood cultures: positive.ABG analysis: hypoxaemia and acidosis.</p>",
"</dd>",
"<dt><a href='#Section4'>Folliculitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Recent hx of immersion in spa water; darkly pigmented male with curly hair; recent hx of shaving; umbilicated flesh-coloured papules.",
"<br><strong>Test:</strong> Gram stain: gram-positive cocci typical of Staphylococcus aureus infection.Potassium hydroxide preparation: presence of hyphal forms suggestive of dermatophyte infection.</p>",
"</dd>",
"<dt><a href='#Section5'>Basal cell carcinoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Hx of UV radiation, sun exposure, x-ray exposure, arsenic exposure, xeroderma pigmentosa, Gorlin-Goltz syndrome, or transplant.Papules with associated telangiectasias; plaques, nodules, and tumours with rolled borders; small crusts and non-healing wounds; non-healing scabs; pearly papules or plaques. Unlike bites and stings, these lesions do not appear acutely.",
"<br><strong>Test:</strong> Shave/punch biopsy: growth of nest(s) of varying size and shape.</p>",
"</dd>",
"<dt><a href='#Section6'>Squamous cell carcinoma of the skin</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Hx of UV exposure, older age, immunosuppression, fair skin, human papillomavirus, hereditary skin conditions, exposure to ionising radiation/arsenic/tar, actinic keratosis, male sex. Unlike bites and stings, these lesions do not appear acutely.Erythematous papules or plaques; thin flesh-coloured or erythematous plaques/dome-shaped nodules; exophytic, fungating verrucous nodules or plaques.",
"<br><strong>Test:</strong> Biopsy: keratinocyte atypia.</p>",
"</dd>",
"<dt><a href='#Section7'>Kaposi's sarcoma</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> HIV infection; immunosuppressive therapy; transplantation, Central African ethnicity (e.g., from Uganda, Malawi, Zambia, Zimbabwe); human herpesvirus-8 infection.Skin lesions may be multifocal, asymmetrically distributed, non-pruritic, varying in size (ranging from several millimetres to centimetres in diameter) and colour (pink, red, purple, brown, or blue), papular, nodular, plaque-like, bullous-like, fungating with skin ulceration and secondary infection, indurated (woody), or hyperkeratotic.",
"<br><strong>Test:</strong> HIV test: positive.Biopsy: characteristic vascular lesion.</p>",
"</dd>",
"<dt><a href='#Section8'>Local trauma</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Hx of trauma.",
"<br><strong>Test:</strong> X-ray: may show evidence of trauma.</p>",
"</dd>",
"<dt><a href='#Section9'>Intra-abdominal processes (differential of black widow spider bite)</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Abdominal tenderness with guarding or rebound tenderness. Bowel sounds may be absent.May have risk factors for mesenteric ischaemia, gastroenteritis, bowel obstruction, etc.",
"<br><strong>Test:</strong> X-ray: may show dilated bowel loops.FBC may be elevated in infectious process. Lactate may be elevated in mesenteric ischaemia.Ultrasound/CT/MRI may show pathology.</p>",
"</dd>",
"<dt><a href='#Section10'>Compartment syndrome of the abdomen</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Hx of excessive fluid resuscitation (&gt;5 L in 24 hours), massive blood transfusion (&gt;10 units in 24 hours), recent abdominal infection (especially peritonitis), haemoperitoneum, ileus, abdominal distention, oliguria.",
"<br><strong>Test:</strong> Trans-bladder measurement of intra-abdominal pressure: elevated.ABG analysis: metabolic acidosis or mixed metabolic and respiratory acidosis.</p>",
"</dd>",
"<dt><a href='#Section11'>Compartment syndrome of extremities</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Hx of trauma, bleeding disorder, compression support, thermal injury, intravenous infusion, venous obstruction, sports playing. Loss of muscle function, pain, pressure (tightness), paraesthesia, pulselessness, pallor, paralysis.",
"<br><strong>Test:</strong> Compartment pressure: differential pressure &le;20 mmHg.Serum creatinine kinase: elevated.Urine myoglobin: elevated.</p>",
"</dd>",
"<dt><a href='#Section12'>Muscle spasm</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Episodic occurrence. Hx of muscle strain or trauma.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section13'>Migraine</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> FHx of migraine. Risk factors include childhood motion sickness; caffeine intake; high altitude; female gender; menstruation; divorced, widowed, or separated; obesity; habitual snoring; stressful life events; overuse of headache medications; lack of sleep.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section14'>Subarachnoid haemorrhage</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> Hx of hypertension, smoking, or autosomal dominant polycystic kidney disease; FHx of subarachnoid haemorrhage; photophobia; altered mental status.",
"<br><strong>Test:</strong> CT head: hyper-dense areas in the basal cisterns, major fissures and sulci.Lumbar puncture: bloody CSF (xanthochromia).</p>",
"</dd>",
"<dt><a href='#Section15'>Acute myocardial infarction</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Cardiac risk factors, chest pain, SOB, nausea, diaphoresis, eliciting factors.",
"<br><strong>Test:</strong> ECG: ischaemic changes.Cardiac enzymes: positive.</p>",
"</dd>",
"<dt><a href='#Section16'>Toxic plant ingestion</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Hx of recent ingestion of plant matter.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section17'>Organophosphate poisoning</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> Hx of recent ingestion of insecticides; distinctive odour; incontinence; visual disturbances.",
"<br><strong>Test:</strong> Atropine therapeutic trial: lack of anticholinergic effects.Plasma cholinesterase: reduced activity.</p>",
"</dd>",
"<dt><a href='#Section18'>Shock</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> May be cardiogenic, septic, or hypovolaemic.Hx of recent MI, recent surgery or immobilisation, severe infection, or haemorrhage.",
"<br><strong>Test:</strong> Lactate &gt;2 mmol/L (&gt;18 mg/dL) is suggestive of tissue hypoperfusion.ABG analysis: pH &lt;7.35 indicates acidosis.</p>",
"</dd>",
"<dt><a href='#Section19'>Acute asthma</a></dt>",
"<dd id='Section19'>",
"<p><strong>Sign & Symptoms:</strong> Hx of viral infection, exposure to cigarette smoke, exposure to allergens, atopic eczema, environmental irritants, GORD, use of oral corticosteroids, or non-compliance to asthma medication.",
"<br><strong>Test:</strong> PEFR: &lt;60% of predicted value if severe.</p>",
"</dd>",
"<dt><a href='#Section20'>Acute COPD</a></dt>",
"<dd id='Section20'>",
"<p><strong>Sign & Symptoms:</strong> Hx of bacterial infection; viral infection; exposure to pollutants; change in weather.",
"<br><strong>Test:</strong> CXR: hyper-inflation, flattened diaphragm, bullae, and a small vertical heart.ABG analysis: respiratory acidosis and compensatory metabolic alkalosis.</p>",
"</dd>",
"<dt><a href='#Section21'>Foreign body aspiration</a></dt>",
"<dd id='Section21'>",
"<p><strong>Sign & Symptoms:</strong> Sudden-onset stridor or choking; hx of foreign body in mouth (especially in young children).",
"<br><strong>Test:</strong> CXR may show air-trapping and hyper-expanded lung field.</p>",
"</dd>",
"<dt><a href='#Section22'>Viral syndrome</a></dt>",
"<dd id='Section22'>",
"<p><strong>Sign & Symptoms:</strong> Fever, chills, myalgias, upper respiratory infection symptoms, GI symptoms.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section23'>Drug reaction</a></dt>",
"<dd id='Section23'>",
"<p><strong>Sign & Symptoms:</strong> Usually diffuse rash developing after beginning new medication.",
"<br><strong>Test:</strong> Symptom improvement after removal of drug.</p>",
"</dd>",
"<dt><a href='#Section24'>Atopy</a></dt>",
"<dd id='Section24'>",
"<p><strong>Sign & Symptoms:</strong> Recurrent sensitivity reactions following certain exposures.",
"<br><strong>Test:</strong> Allergy testing: positive.</p>",
"</dd>",
"<dt><a href='#Section25'>Chemical exposure or sensitivity</a></dt>",
"<dd id='Section25'>",
"<p><strong>Sign & Symptoms:</strong> Hx of recent exposure.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");