content=["<dl>",
"<dt><a href='#Section0'>Duodenal atresia/web</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Duodenal atresia is usually not associated with abdominal pain, physiological perturbation, or metabolic acidosis. Any of these signs should press urgent action towards diagnosis and treatment of volvulus.",
"<br><strong>Test:</strong> On plain x-ray in a newborn with bilious vomiting, the presence of bowel gas beyond the duodenum suggests either midgut volvulus or type 1 duodenal atresia; therefore, an upper GI series should be done to differentiate between them.</p>",
"</dd>",
"<dt><a href='#Section1'>Intussusception</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> The incidence of intussusception increases sharply at 5 months when volvulus is beginning to decrease in incidence.Bilious vomiting is delayed or secondary if present at all in the presentation of intussusception as opposed to volvulus.Intussusception is typically distinguished by periods of sudden abdominal pain followed by complete cessation. These continue to return as equally sharp in waves, until the intussusception is reduced.",
"<br><strong>Test:</strong> Ultrasound identifies intussusception in most cases.Contrast enema (with air or barium) is thereafter used to confirm the diagnosis and reduce the intussusceptum.</p>",
"</dd>",
"<dt><a href='#Section2'>Gastro-oesophageal reflux</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Malrotation without volvulus may cause intermittent non-bilious vomiting that appears identical to reflux, and the two cannot be distinguished by history or physical examination.",
"<br><strong>Test:</strong> Upper GI contrast series definitively clarifies malrotation.</p>",
"</dd>",
"<dt><a href='#Section3'>Non-specific symptoms</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> It is important to consider that malrotation without volvulus is diagnosed for a wide variety of complaints that lead to a contrast study, including diarrhoea, constipation, anorexia, irritability, apnoea, lethargy, failure to thrive, blood in stool, and fever. [11]",
"<br><strong>Test:</strong> Upper GI contrast series definitively clarifies malrotation.</p>",
"</dd>",
"</dl>"].join("\n");