content=["<dl>",
"<dt><a href='#Section0'>Iron deficiency anaemia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Anaemia is rare with lead poisoning, except for high-level exposure. Iron deficiency is usually related to dietary deficiency or blood loss. Responds to iron supplementation with correction of anaemia.",
"<br><strong>Test:</strong> Iron store measured by serum iron, iron-binding capacity, transferrin, ferritin, or bone marrow indicates iron deficiency.</p>",
"</dd>",
"<dt><a href='#Section1'>Non-lead peripheral neuropathy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> No hx of lead exposure.Faster rates of symptom progression.",
"<br><strong>Test:</strong> Low blood lead level.Blood/urine testing may reveal other toxicants.Appropriate cultures and serology reveal infectious causes.Positive immune markers for chronic inflammatory and immune diseases.Characteristic nerve conduction study/EMG findings for neurological syndromes.</p>",
"</dd>",
"<dt><a href='#Section2'>Arsenic poisoning</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May have neuropathy with skin lesions, including keratoses.May have hx of exposure to arsenic.",
"<br><strong>Test:</strong> Hair arsenic.24-hour urine collection for arsenic during chelation therapy.</p>",
"</dd>",
"<dt><a href='#Section3'>Encephalitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> No hx of lead exposure.May have hx of exposure to NSAIDs, antibiotics, antivirals, immunomodulators, or anticonvulsants.Lead encephalopathy often has prominent cerebellar signs, depressed sensorium, and seizures.",
"<br><strong>Test:</strong> Low blood lead level.Detection of Plasmodium in peripheral blood smear or detection of bacterial and viral infections in blood, throat, and sputum cultures.CT/MRI scanning reveals characteristic findings of the underlying cause.Analysis and culture of CSF reveals characteristic findings, infections, and infection- or paraneoplastic-related antibodies.</p>",
"</dd>",
"</dl>"].join("\n");