content=["<dl>",
"<dt><a href='#Section0'>Hypertrophic lichen planus</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Localised to the shins and may be surrounded by smaller, more typical lesions of lichen planus with a polygonal border and overlying Wickham striae.",
"<br><strong>Test:</strong> Skin biopsy demonstrates acanthosis and, often, irregular psoriasiform epidermal hyperplasia similar to LSC, but with additional band-like lymphocytic infiltrates and evidence of vacuolar change.</p>",
"</dd>",
"<dt><a href='#Section1'>Hypertrophic actinic keratoses</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are typically smaller than those of LSC, located on sun-exposed areas of skin, more erythematous, and associated with greater overlying hyperkeratosis. They can be painful and are rarely associated with pruritus unless in the presence of secondary LSC.",
"<br><strong>Test:</strong> Skin biopsy demonstrates non-full thickness keratinocyte atypia, but lesions on the dorsum of the hand may show histological features of associated secondary LSC.</p>",
"</dd>",
"<dt><a href='#Section2'>Squamous cell carcinoma of the skin</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are located on sun-exposed areas of skin, are more erythematous, often have thick overlying hyperkeratosis, and may be painful but not pruritic.",
"<br><strong>Test:</strong> Skin biopsy demonstrates keratinocyte atypia with evidence of dermal invasion.</p>",
"</dd>",
"<dt><a href='#Section3'>Psoriasis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Symmetrical eruption not associated with the intense pruritus of LSC. Lesions are more erythematous with silvery scales and no evidence of lichenification.",
"<br><strong>Test:</strong> Skin biopsy demonstrates regular psoriasiform epidermal hyperplasia, with confluent overlying parakeratosis and loss of the granular cell layer.</p>",
"</dd>",
"<dt><a href='#Section4'>Warts</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Can occur at any body site but are most commonly located on the palms and soles. Lesions are characterised by a verrucous surface with black dots and interruption of skin lines and are not associated with the intense pruritus of LSC.",
"<br><strong>Test:</strong> Skin biopsy demonstrates verrucous epidermal hyperplasia with in-toeing of the rete ridges, tiers or parakeratosis, and occasional koilocytic change.</p>",
"</dd>",
"<dt><a href='#Section5'>Scabies</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Often a diffuse eruption with a dermatitic appearance. No burrows or scabetic nodules present on the genitalia.",
"<br><strong>Test:</strong> Skin biopsy demonstrates an intense inflammatory infiltrate extending into the deep dermis and associated with increased numbers of eosinophils.Skin scrapings reveal intact mites, eggs, or scybala.</p>",
"</dd>",
"<dt><a href='#Section6'>Pemphigoid nodularis (bullous pemphigoid resembling prurigo nodularis)</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Diffuse blisters and urticarial lesions.",
"<br><strong>Test:</strong> Skin biopsy demonstrates subepidermal blistering with increased eosinophils.Direct immunofluorescence studies demonstrate band-like deposition of IgG and C3 along the dermal-epidermal junction.</p>",
"</dd>",
"<dt><a href='#Section7'>Mycosis fungoides</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are localised to areas of the body covered by a bathing suit and are more atrophic in appearance than those of LSC.",
"<br><strong>Test:</strong> Skin biopsy demonstrates a band-like infiltrate of T lymphocytes along the dermal-epidermal junction with scant epidermal spongiosis and epidermotropism.PCR, of a skin biopsy specimen, for T-cell gene rearrangement demonstrates a monoclonal T-cell population, which is diagnostic for the condition.</p>",
"</dd>",
"</dl>"].join("\n");