content=["<dl>",
"<dt><a href='#Section0'>Other bacterial meningitides</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There is no sign or symptom that securely differentiates listeriosis from other causes of CNS infection.Nuchal rigidity is more common in meningitis due to pathogens other than Listeria. [1]  [6]",
"<br><strong>Test:</strong> CSF Gram stain, CSF culture and blood culture are the tests of choice.Streptococcus pneumoniae, Neisseria meningitidis and Haemophilus influenzae are common causes of community-acquired bacterial meningitis.</p>",
"</dd>",
"<dt><a href='#Section1'>Other brain abscesses</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> There is no sign or symptom that securely differentiates listeriosis from other causes of CNS infection.",
"<br><strong>Test:</strong> Culture and Gram stain will typically differentiate other organisms. Additionally, blood cultures are frequently positive in listeriosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Viral gastroenteritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Viral gastroenteritis may be accompanied by upper respiratory symptoms.A history of consumption of foods suspicious for listeriosis may be absent.",
"<br><strong>Test:</strong> Stool tests are negative for Listeria.</p>",
"</dd>",
"<dt><a href='#Section3'>Other bacterial gastroenteritides</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Social history, food-consumption history, travel history, incubation period, history of alimentary tract contamination, presence of dysentery, sporadic or epidemic cases are used to differentiate the causes clinically. Presenting signs and symptoms may be similar to listeriosis. In Shigella infection, stool may contain blood or pus.",
"<br><strong>Test:</strong> Stool tests or serologies may be positive for organisms such as Campylobacter jejuni, Salmonella, or Shigella.</p>",
"</dd>",
"<dt><a href='#Section4'>Toxoplasmosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of consumption of raw meat or having a house cat.Unexplained fever and generalised lymphadenitis.",
"<br><strong>Test:</strong> Serology for IgM and IgG antibodies against Toxoplasma gondii may be present.Microscopy of an infected lymph node may confirm toxoplasmosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Sarcoidosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May affect any organ, but erythema nodosum is a more specific presentation for sarcoidosis.",
"<br><strong>Test:</strong> Chest radiography may show bilateral enlargement of hilar lymph nodes.Biopsy of lymph node or affected tissue may show granulomas without central necrosis.Hypercalciuria may be present.</p>",
"</dd>",
"<dt><a href='#Section6'>Vasculitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Systemic symptoms or signs may be similar, rendering diagnosis difficult.",
"<br><strong>Test:</strong> Biopsy of affected organ may show thrombosis and inflammation of any size of vasculature and invasion of vessel wall by inflammatory cells.</p>",
"</dd>",
"<dt><a href='#Section7'>Septic abortion</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> There are no distinguishing features compared to other causes.Fever and rigors in pregnant women and bacteraemia due to any site of infection may cause chorioamnionitis, fetal sepsis, and death.",
"<br><strong>Test:</strong> Blood, placenta, amniotic fluid cultures will determine the underlying aetiological organism.</p>",
"</dd>",
"</dl>"].join("\n");