content=["<dl>",
"<dt><a href='#Section0'>Neoplasm (primary or metastatic lung cancer, lymphoma)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Malignancy is associated with a low-grade fever, absence of leukocytosis, minimal systemic complaints, absence of factors that predispose to gastric content aspiration, no response to antibiotics within 10 days, and a deteriorating course. [32]  Haemoptysis is commonly associated with bronchogenic carcinoma.",
"<br><strong>Test:</strong> CXR: less ground-glass infiltrate surrounding the cavity. View imageSputum cytology: may show malignant cells.CT chest and bronchoscopy: confirm the obstructing lesion.</p>",
"</dd>",
"<dt><a href='#Section1'>Tuberculosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of exposure to a tuberculosis-infected patient.Systemic symptoms of fatigue, malaise, anorexia, and weight loss, as well as a low-grade fever with night sweats, are prominent.",
"<br><strong>Test:</strong> CXR: cavity is usually located in the upper lobes. View imageSputum smear and culture in Lowenstein-Jensen media: positive for acid-fast bacilli.CT chest: cavitating lesions typically in the upper lobes and usually accompanied by parenchymal infiltrates. Tree-in-bud pattern may be present.</p>",
"</dd>",
"<dt><a href='#Section2'>Cavitating pneumonia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Acute, often fulminant infection. Duration of illness before recognition is usually short. Causative organisms include Staphylococcus aureus, Klebsiella pneumoniae, Streptococcus pyogenes, and Pseudomonas species.",
"<br><strong>Test:</strong> CXR: multiple cavities are usually present. Pleural effusion and empyema are common findings.</p>",
"</dd>",
"<dt><a href='#Section3'>Loculated empyema</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> On respiratory exam, dullness to percussion, decreased breath sounds, and reduced vocal resonance are usually found.",
"<br><strong>Test:</strong> CT chest: empyema appears lenticular in shape, and has a thin wall with smooth luminal margins and a smooth exterior wall. It forms obtuse angles with the chest wall, and shows signs of compression of the uninvolved lung. Separate pleural layers are also seen. [37]</p>",
"</dd>",
"<dt><a href='#Section4'>Fungal infection</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of travel to or residence in an endemic area, or occupational exposure.More prevalent in patients with impaired cell-mediated immunity (e.g., AIDS, transplant immunosuppression, malignancies) or granulocytopenia.",
"<br><strong>Test:</strong> Demonstration of typical yeast in fluid or tissue specimens.Culture of pulmonary secretions: positive for fungus.Serological tests: positive for Coccidioides, Histoplasma, or Blastomyces.CXR: typical air crescent sign surrounding the fungus ball in aspergilloma.Aspergillus precipitins: positive in aspergilloma.Serum total IgE and serum-specific IgE to Aspergillus fumigatus allergen: typically elevated in allergic bronchopulmonary aspergillosis and occasionally in aspergilloma.</p>",
"</dd>",
"<dt><a href='#Section5'>Nocardiosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Typically occurs in immunocompromised patients with impaired cell-mediated immunity (e.g., AIDS, transplant immunosuppression, malignancies).",
"<br><strong>Test:</strong> Gram's and acid-fast staining and culture of pulmonary secretions: positive for Nocardia.</p>",
"</dd>",
"<dt><a href='#Section6'>Actinomycosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Manifestations of cutaneous actinomycosis with nodular lesions that tend to form fistulae may be present.",
"<br><strong>Test:</strong> Diagnosis is based on identification of characteristic sulphur granules in pus.Gram's and periodic acid-Schiff staining of histological specimens: presence of actinomycotic colonies.Anaerobic culture of pulmonary secretions: positive for Actinomyces.</p>",
"</dd>",
"<dt><a href='#Section7'>Granulomatosis with polyangiitis (Wegener's)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Upper respiratory tract and renal involvement are common. Ocular, cutaneous, musculoskeletal, and neurological manifestations are usually present.",
"<br><strong>Test:</strong> Positive anti-neutrophil cytoplasmic antibody combined with positive specific proteinase 3 antibody testing by enzyme immunoassay.Urinalysis: haematuria and proteinuria.</p>",
"</dd>",
"<dt><a href='#Section8'>Rheumatoid lung nodule</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Symmetrical arthritis of the small joints of the hands and feet with morning stiffness are common manifestations.",
"<br><strong>Test:</strong> CXR: pulmonary nodules with cavitation usually located in the upper lobe (Caplan's syndrome).Rheumatoid factor: positive.Anti-cyclic citrullinated peptide antibody: positive.</p>",
"</dd>",
"</dl>"].join("\n");