content=["<dl>",
"<dt><a href='#Section0'>Chronic venous insufficiency</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Damage to the peripheral venous system can lead to lower extremity oedema, usually without significant foot involvement.Pain, ulceration, pitting oedema, pigment changes, and a negative Stemmer's sign are present on clinical evaluation. [28]  [4]",
"<br><strong>Test:</strong> Duplex ultrasound: reversed flow; valve closure time &gt;0.5 second indicates reflux.</p>",
"</dd>",
"<dt><a href='#Section1'>Deep vein thrombosis (DVT)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May be history of prior DVT, prolonged immobility, or hyper-coaguable state.Usually presents with erythema, warmth, and pain of affected limb.",
"<br><strong>Test:</strong> Duplex ultrasound: presence of a thrombus within the vein.</p>",
"</dd>",
"<dt><a href='#Section2'>Lipoedema</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Almost always affects pubertal females; typically bilateral and involves the lower extremities while sparing the feet.Physical examination usually reveals limb tenderness, presence of a malleolar fat pad, and a negative Stemmer's sign. [2]  [36]  [37]",
"<br><strong>Test:</strong> Normal lymphoscintigraphy.MRI scan of affected extremity shows bilateral subcutaneous fat hypertrophy with sparing of the distal extremity.</p>",
"</dd>",
"<dt><a href='#Section3'>Obesity</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Morbid obesity results in diffuse, excess adipose tissue and therefore patients may have symmetrically enlarged legs secondary to fat deposition.",
"<br><strong>Test:</strong> Normal CT or MRI scan.Normal lymphoscintigraphy. [36]</p>",
"</dd>",
"<dt><a href='#Section4'>Congestive heart failure (CHF)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Characterised by generalised pitting oedema that responds to elevation and diuretics. Because CHF is a systemic illness, extremity oedema is typically bilateral, unlike lymphoedema, which is usually unilateral.Additional symptoms include fatigue, light-headedness, poor exercise capacity, and shortness of breath. [4]",
"<br><strong>Test:</strong> ECG may show evidence of underlying CAD, left ventricular hypertrophy, or atrial enlargement. May be conduction abnormalities and abnormal QRS duration.Chest x-ray may reveal pulmonary vascular congestion (vascular redistribution, Kerley's B lines), cardiomegaly (increased cardiothoracic ratio), or pleural effusion (usually right-sided but often bilateral).Echocardiogram confirms the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Hypoalbuminaemia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Renal failure and protein-losing enteropathies cause generalised pitting oedema through reduced intravascular osmotic pressure.Decreased production of protein in hepatic failure similarly leads to generalised pitting oedema.Oedema is therefore bilateral, unlike many patients with lymphoedema, who have one affected extremity.",
"<br><strong>Test:</strong> Low serum protein, low serum albumin, low serum pre-albumin. [4]</p>",
"</dd>",
"<dt><a href='#Section6'>Malignancy</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Malignant lesions, including lymphangiosarcoma, angiosarcoma, and sarcoma, should be considered when rapid swelling, weight loss, malaise, or pain occurs.",
"<br><strong>Test:</strong> MRI scan and tissue biopsy of affected site confirms the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section7'>Klippel-Trenaunay syndrome</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Combined lymphatic, venous, and capillary malformation of an extremity with overgrowth. [1]",
"<br><strong>Test:</strong> MRI shows lateral embryonal subcutaneous vein and other venous anomalies. Unlike lymphoedema, malformation involves tissues below muscle fascia.</p>",
"</dd>",
"<dt><a href='#Section8'>Haemihypertrophy</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Idiopathic enlargement of an extremity is usually a diagnosis of exclusion. [1]",
"<br><strong>Test:</strong> Normal lymphoscintigram. MRI does not show any pathology, only enlarged subcutis, muscle, and bone.</p>",
"</dd>",
"</dl>"].join("\n");