content=["<dl>",
"<dt><a href='#Section0'>Cystic fibrosis (CF)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Thick mucous secretions affect lung and gastrointestinal functioning. Patients often present with failure to thrive and recurrent respiratory tract infections.Men with isolated congenital bilateral absence of vas deferens (CBAVD) with no other clinical signs of CF have a mutation in the CF transmembrane regulator gene in 80% of the cases. [8]  If the diagnosis of CBAVD is made, the female partner should be screened for CF.",
"<br><strong>Test:</strong> Neonatal screening for CF is done in many countries.Sweat testing measures the amount of sodium chloride in the sweat. There is excessive loss in CF.Genetic testing is available, but testing is not available for all known gene mutations.</p>",
"</dd>",
"<dt><a href='#Section1'>Primary hypogonadism</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Testes no longer produce testosterone, resulting in impotence, gynaecomastia, decreased beard and body hair, small testes, and infertility.",
"<br><strong>Test:</strong> Low testosterone level. Elevated FSH and LH.</p>",
"</dd>",
"<dt><a href='#Section2'>Hypopituitarism</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Partial or complete loss of the functioning of the anterior pituitary gland. If the FSH and LH production is affected, male patients may present with impotence, decreased beard and body hair, small testes, and infertility.",
"<br><strong>Test:</strong> May have decreased LH and FSH.MRI of the pituitary fossa may show a pituitary or hypothalamic lesion.</p>",
"</dd>",
"<dt><a href='#Section3'>Pituitary adenoma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> A prolactin-producing tumour results in impotence, headaches, and visual disturbance. Galactorrhoea may rarely be present.",
"<br><strong>Test:</strong> Prolactin levels are elevated.MRI shows a tumour in the pituitary gland.</p>",
"</dd>",
"<dt><a href='#Section4'>Klinefelter's syndrome</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Men have small testes, gynaecomastia, incomplete androgenisation, and infertility due to severe oligozoospermia or complete azoospermia. [12]",
"<br><strong>Test:</strong> Chromosomal analysis shows XXY.</p>",
"</dd>",
"<dt><a href='#Section5'>Kartagener's syndrome</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Also known as immotile cilia syndrome. Ciliary dyskinesia affects the respiratory tract and spermatozoa. Patients may have a long history of sinusitis, recurrent ear infections, chronic bronchitis, or bronchiectasis.",
"<br><strong>Test:</strong> Diagnosis confirmed on mucosal histological specimen and electron microscopy.</p>",
"</dd>",
"<dt><a href='#Section6'>Varicocele</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Dilation of the veins of the pampiniform plexus of the scrotum. They occur commonly on the left side. The patient should be examined while standing.",
"<br><strong>Test:</strong> Colour Doppler ultrasound will confirm backflow of blood in the spermatic veins.</p>",
"</dd>",
"</dl>"].join("\n");