content=["<dl>",
"<dt><a href='#Section0'>Mantle cell lymphoma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable.",
"<br><strong>Test:</strong> Biopsy specimen shows absence of transformed blasts; expression of CD5, IgD, and nuclear cyclin D1 present on immunohistochemistry, CD23 is negative; t(11;14) demonstrated with cytogenetic testing.</p>",
"</dd>",
"<dt><a href='#Section1'>Small lymphocytic lymphoma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typical clinical features include painless lymphadenopathy, with or without B symptoms. Gastrointestinal disease is uncommon.",
"<br><strong>Test:</strong> Immunohistochemistry shows CD5 and CD23 positivity, while CD10 is negative. The usual cytogenetic abnormalities are del13q14 or trisomy 12.Morphologically, the tumour is also composed of small B cells, but lymphoepithelial lesions and plasma cells are lacking; the presence of CD5 on B cells is a distinguishing feature.Bone marrow biopsy usually demonstrates bone marrow involvement.</p>",
"</dd>",
"<dt><a href='#Section2'>Follicular lymphoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> This condition almost always presents with nodal disease. Extra-nodal disease is uncommon.Most patients have widespread disease at presentation, enlarged lymph nodes, and splenomegaly. Occasionally can present with palpable masses in the abdomen and abdominal pain or GI bleeding.",
"<br><strong>Test:</strong> Immunohistochemistry shows CD10 and BCL6 positive tumour cells in and between the follicles.Bone marrow biopsy usually demonstrates bone marrow involvement.</p>",
"</dd>",
"<dt><a href='#Section3'>Diffuse large B-cell lymphoma</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms are aggressive, with abdominal pain, vomiting, and haematemesis occurring more commonly than with gastric MALT lymphoma.",
"<br><strong>Test:</strong> Immunohistochemistry reveals medium- to large-sized tumour cells that are CD19-, CD20-, and CD79a-positive with a high proliferative index.</p>",
"</dd>",
"<dt><a href='#Section4'>Peptic ulcer disease</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable.",
"<br><strong>Test:</strong> Monoclonality may be demonstrated using immunoglobulin gene rearrangement studies in the absence of gastric MALT lymphoma, or precede the development of gastric MALT lymphoma.</p>",
"</dd>",
"<dt><a href='#Section5'>Hashimoto's thyroiditis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Causes hypothyroidism that is usually insidious in onset, with signs and symptoms slowly progressing over months to years.Some of the common symptoms of hypothyroidism include cold intolerance, voice hoarseness and pressure symptoms in the neck from thyroid enlargement, slowed movement and loss of energy, menstrual irregularities (typically menorrhagia, infertility, and loss of libido), depression, dementia, and other psychiatric disturbances, as well as memory loss.",
"<br><strong>Test:</strong> Elevated TSH with low free T4 levels; antithyroid peroxidase (anti-TPO) and antithyroglobulin (anti-Tg) antibodies are positive in the majority of cases.</p>",
"</dd>",
"<dt><a href='#Section6'>Lymphoepithelial sialadenitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable.",
"<br><strong>Test:</strong> Biopsy of the salivary glands shows a spectrum of histopathological features including: 1) fully benign lymphoid infiltrate, with or without an associated lymphoid follicular structure, without immunoglobulin (Ig) light chain restriction in B-cells, and without any features of aggressive behaviour; 2) lymphoproliferative lesions, with or without areas of Ig light chain restriction in B-cells, with the usual presence of centrocyte-like cells. A more or less pronounced lymphoepithelial aggressiveness may be present without definite evidence of malignancy.B-cell clones are detected in over 50% of cases by molecular genetic methods but this does not correlate with morphological or clinical evidence of overt lymphoma.</p>",
"</dd>",
"</dl>"].join("\n");