content=["<dl>",
"<dt><a href='#Section0'>benign melanocytic naevi</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Benign melanocytic naevi tend to be smaller than melanomas, with an absence of colour variegation or marked asymmetry/border irregularity and no clinical features of regression (loss of colour with a bluish-white veiled appearance). In addition, benign melanocytic naevi do not change or demonstrate spontaneous ulceration or bleeding such as that seen in melanoma.",
"<br><strong>Test:</strong> Difference in appearance on dermatoscopic evaluation. The diagnostic test is skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section1'>seborrhoeic keratosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Seborrhoeic keratoses demonstrate a waxy, 'stuck on', often hyperkeratotic appearance, with surface horned cysts.",
"<br><strong>Test:</strong> Difference in appearance on dermatoscopic evaluation, with presence of horned cysts and hairpin-shaped blood vessels in seborrhoeic keratoses.The diagnostic test is skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section2'>pigmented basal cell carcinoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Basal cell carcinoma will have a pearly appearance with less pigmentation than a typical malignant melanoma.In addition, there are prominent branching telangiectatic vessels in basal cell carcinoma.",
"<br><strong>Test:</strong> Difference in appearance on dermatoscopic evaluation, with leaf-like areas of pigmentation and arborising blood vessels in pigmented basal cell carcinoma.The diagnostic test is skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section3'>pigmented actinic keratosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Pigmented actinic keratoses demonstrate more hyperkeratosis and erythema than melanoma, with less pigmentation, and tend to be somewhat smaller in size.Pain may be associated with pigmented actinic keratoses.",
"<br><strong>Test:</strong> The diagnostic test is skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section4'>dermatofibroma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Dermatofibroma demonstrates skin dimpling on palpation and a scar-like appearance, and is typically localised to the extremities only.",
"<br><strong>Test:</strong> Dermatoscopy displays a difference in appearance, with a central scar-like area present in dermatofibroma. [59]The diagnostic test is skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section5'>subungual haematoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Instead of a longitudinal band, often associated with a subungual melanoma, a subungual haematoma appears as reddish-black globules of pigment that grow out distally as the nail grows.In addition, the patient may be able to give a history of prior trauma.Subungual melanoma may demonstrate pigmentation extending onto the proximal nail fold (Hutchinson's sign), unlike a subungual haematoma.",
"<br><strong>Test:</strong> Difference in appearance on dermatoscopic evaluation, with presence of homogenous brownish-red pigment with multiple globules and an absence of melanin granules. [60]  Scrapings of pigment can be tested with a urinalysis strip to detect blood. [61]  However, tumours such as melanoma may be associated with subungual bleeding. [62]The diagnostic test is skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section6'>intracorneal haematoma</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Haemorrhage in the stratum corneum may be accompanied by a history of trauma.",
"<br><strong>Test:</strong> The pigment can be pared away with a number 15 scalpel blade.</p>",
"</dd>",
"<dt><a href='#Section7'>tinea nigra</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Superficial infection of the stratum corneum that typically appears on the palmar surface of the hands or feet. Usually not itchy. More homogenous pigmentation is seen than in malignant melanoma.",
"<br><strong>Test:</strong> The pigment can be pared away with a number 15 scalpel blade. Skin scrapings show septate hyphae on KOH microscopic examination.</p>",
"</dd>",
"<dt><a href='#Section8'>pyogenic granuloma</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> A lobular haemangioma most commonly seen in children. A mucosal form (usually affecting the maxillary mucosa or the inner nose) is commonly seen in pregnant women.A new lesion is typically bright red in colour, which pales to a fleshy pink colour with time.",
"<br><strong>Test:</strong> The diagnostic test is skin biopsy.</p>",
"</dd>",
"</dl>"].join("\n");