content=["<dl>",
"<dt><a href='#Section0'>Exogenous ochronosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Skin hyperpigmentation associated with use of the bleaching agent hydroquinone. It is caused by the deposition of polymerised homogentisic acid in the skin.Historically, this condition follows use of hydroquinone products, and distribution correlates with areas of medicine application.Most commonly seen in people with Fitzpatrick type V or VI skin who have used hydroquinone-containing preparations of &gt;3% concentration for months to years, and who have had significant UV light exposure without the use of photoprotection.",
"<br><strong>Test:</strong> Skin biopsy shows golden-yellow to brown deposition of pigment in the dermis.</p>",
"</dd>",
"<dt><a href='#Section1'>Post-inflammatory hyperpigmentation</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Hyperpigmentation of skin that was previously inflamed due to dermatitis.Diagnosis is typically made on history of erythema, pruritus, and dermatitis preceding the hyperpigmentation.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section2'>Phototoxic reaction</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Seen in patients exposed to systemic or topical medicines or cosmetics, and then UV radiation.Disease usually begins abruptly, in contrast to melasma, which develops gradually.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section3'>Riehl melanosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Facial hyperpigmented contact dermatitis due to the use of facial cosmetics. [15]Typically distribution is patchier than classic melasma and resolves when offending agent is discontinued.",
"<br><strong>Test:</strong> Patch testing can be done to look for reaction to components of cosmetics.</p>",
"</dd>",
"<dt><a href='#Section4'>Erythema dyschromicum perstans</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Also called ashy dermatosis. Most frequently seen in Hispanic people and can be seen at any age.Clinically, it presents as multiple blue-grey macules on the neck, chest, and sometimes the face.The colour and distribution, as well as the lack of association with UV light exposure, help to differentiate it from melasma. [16]",
"<br><strong>Test:</strong> Skin biopsy is non-specific, but can show some cell death at the dermal-epidermal junction, as well as pigment incontinence. [16]</p>",
"</dd>",
"</dl>"].join("\n");