content=["<dl>",
"<dt><a href='#Section0'>Fox-Fordyce disease (apocrine miliaria)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Intensely pruritic papules in adult women localised to the axillae, groin, pubic region, and areola.No relationship to heavy sweating, heat, humidity, occlusion, sunburn, or febrile illness and no associated anhidrosis.Papules are folliculocentric and flesh-coloured to brown with no erythema or vesiculation. [26]",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Biopsy demonstrates follicular plugging with no involvement of the eccrine duct. [26]</p>",
"</dd>",
"<dt><a href='#Section1'>Primary varicella infection</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Eruption of macules followed by vesicles on an inflammatory base, mainly on the trunk, face, and oral mucosa that go through stages, unlike miliaria. Lesions are in all stages of development (macules, papules, vesicle, ulcers, and crusts) simultaneously. [27]Eruption is highly contagious, unlike miliaria, and often occurs in epidemics among young nonimmunised or previously unexposed children.Eruption has no relationship to heat, humidity, or occlusive clothing.",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Tzanck smear shows multinucleated giant cells in a herpetic viral infection. These would be absent in miliaria.Positive viral direct immunofluorescence (DIF)/viral culture or skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section2'>Disseminated varicella-zoster infection</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Eruption of vesicles, similar to primary varicella infection, often in immunocompromised, older, or debilitated patients.Often dermatomal distribution with many non-dermatomal vesicles.Patients are often systemically ill and may have involvement of the lungs, liver, or CNS. [28]",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Tzanck smear shows multi-nucleated giant cells in a herpetic viral infection. These would be absent in miliaria.Positive viral DIF/viral culture or skin biopsy.</p>",
"</dd>",
"<dt><a href='#Section3'>Acne vulgaris</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Folliculocentric papules, pustules, and comedones that can involve the chest and back only but more often also involve the face. Lesions of miliaria are always non-folliculocentric and lack comedones.",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Biopsy demonstrates folliculocentric acute and chronic inflammation.</p>",
"</dd>",
"<dt><a href='#Section4'>Folliculitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Folliculocentric pustules that may be associated with occlusive clothing and heat/humidity. Lesions of miliaria are always non-folliculocentric.",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Biopsy demonstrates folliculocentric acute inflammation.</p>",
"</dd>",
"<dt><a href='#Section5'>Steatocystoma multiplex</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Multiple 2- to 6-mm yellowish cystic papules on the upper trunk, upper arms, and axillae that contain a yellow oily material.Unrelated to heat, humidity, or occlusion and often familial (demonstrating an autosomal-dominant mode of inheritance) though sporadic cases are common. [29]",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Biopsy demonstrates a cyst lined by epithelium with a crenulated inner lining and sebaceous lobules in the outer wall.</p>",
"</dd>",
"<dt><a href='#Section6'>Transient acantholytic dermatosis (Grover's disease)</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Eruption of pruritic non-folliculocentric erythematous papulovesicles on the trunk most commonly in adult males.Although related to heat and sweating, Grover's disease tends to be much more persistent, never has a clear vesicular appearance like miliaria crystallina, and is never associated with anhidrosis. [30]",
"<br><strong>Test:</strong> Can be difficult to distinguish from miliaria rubra.Biopsy demonstrates epidermal acantholysis with dyskeratosis, corps ronds, and corps grains.</p>",
"</dd>",
"<dt><a href='#Section7'>Erythema toxicum neonatorum</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Common eruption in healthy full-term newborns in the 2nd or 3rd day of life. Diffuse eruption of folliculocentric pustules on an erythematous base involving the face, trunk, and proximal extremities. [31]  Miliaria, in contrast, rarely involves the face and is never folliculocentric.",
"<br><strong>Test:</strong> Diagnosis is primarily clinical.Smear from a pustule stained with Giemsa demonstrating eosinophils is diagnostic.Biopsy demonstrates subcorneal pustules in the vicinity of a hair follicle, filled with eosinophils.</p>",
"</dd>",
"<dt><a href='#Section8'>Transient neonatal pustular melanosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Eruption of 1 to 3 mm non-folliculocentric flaccid fragile pustules in newborns that resolve with hyperpigmentation.Most commonly occurs on the chin, neck, forehead, back, and buttocks and most common in dark-skinned infants. [31]",
"<br><strong>Test:</strong> Diagnosis is primarily clinical. Smear from a pustule stained with Giemsa demonstrating mostly neutrophils is diagnostic.Biopsy demonstrates an intra- or sub-corneal collection of neutrophils.</p>",
"</dd>",
"<dt><a href='#Section9'>Bullous staphylococcal impetigo</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Eruption of bullae, most commonly in newborn infants, on any body surface. At first, constitutional symptoms are absent. However, eventually fever or a sub-normal temperature may develop.In adults, the eruption commonly involves the axillae, groin, or hands with large fragile bullae that rupture to weepy or crusted lesions. [32]",
"<br><strong>Test:</strong> Gram stain and bacterial culture demonstrating Staphylococcus aureus are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section10'>Cutaneous candidiasis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Eruption of red moist patches surrounded by a thin fringe of epidermis ('collarette' scale) with associated surrounding satellite erythematous papules and pustules. Occurs most frequently between folds in the groin, genitals, upper axillae and, in infants, in folds in the nappy area.In the newborn period can occur as a congenital eruption of erythematous macules that progress to pustules that rupture and heal with desquamation. The eruption is often associated with premature rupture of membranes and Candida albicans infection of the birth canal. [33]  Unlike congenital miliaria crystallina, the lesions are pustules and not clear vesicles.",
"<br><strong>Test:</strong> Potassium hydroxide (KOH) preparation demonstrating budding yeast and pseudohyphae are diagnostic.Can also confirm with fungal culture demonstrating growth of C albicans.</p>",
"</dd>",
"<dt><a href='#Section11'>Herpes simplex</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> In most cases, there is a high fever above 38&deg;C (100.4&deg;F).Vesicles are small and oval, on an erythematous base and grouped together.",
"<br><strong>Test:</strong> A Tzanck smear of vesicle fluid shows multi-nucleated giant cells.View imageA direct fluorescent antigen test for herpes simplex virus can also be done.</p>",
"</dd>",
"</dl>"].join("\n");