content=["<dl>",
"<dt><a href='#Section0'>Ectopic pregnancy/heterotopic pregnancy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Atypical symptoms that can be missed include iliac fossa or suprapubic pain, unexplained pallor, tachycardia, or syncope.Positive findings on examination are adnexal tenderness or suggestion of haemoperitoneum.An early intra-uterine pregnancy may co-exist with an ectopic pregnancy.",
"<br><strong>Test:</strong> Trans-vaginal ultrasound scan is diagnostic, depending on the site of the extra-uterine pregnancy and the index of suspicion.Serial measurements of serum beta hCG and a single measure of progesterone may help distinguish between early viable, poor prognosis or ectopic gestation. [62]Scan reveals an empty uterine cavity, a complex or cystic adnexal mass with or without free fluid in the pouch of Douglas.If in doubt, laparoscopy can confirm the diagnosis and will show a distended, reddish fallopian tube.</p>",
"</dd>",
"<dt><a href='#Section1'>Hydatidiform mole</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Uterine size is much larger than expected for gestational age.Pregnancy symptoms are marked.Very rarely, the patient might have passed some molar, grape-like tissue.",
"<br><strong>Test:</strong> Trans-vaginal ultrasound will reveal the classic snow storm appearance.</p>",
"</dd>",
"<dt><a href='#Section2'>Partial hydatidiform mole</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Uterine size is much larger than expected for gestational age.Pregnancy symptoms are marked.",
"<br><strong>Test:</strong> Ultrasound may reveal a fetus, with an extensive but unusual-looking placenta.</p>",
"</dd>",
"<dt><a href='#Section3'>Cystitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Suprapubic pain with dysuria and fever.Some patients present with haematuria.",
"<br><strong>Test:</strong> Urine microscopy and culture confirms the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section4'>Pregnancy co-existing with a bleeding cervical polyp</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> May be suspected from appearances of the ecto-cervix on speculum examination.",
"<br><strong>Test:</strong> Confirmed after an ultrasound scan, or by spontaneous avulsion of the polyp.</p>",
"</dd>",
"</dl>"].join("\n");