content=["<dl>",
"<dt><a href='#Section0'>Aortic valve disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Aortic ejection clicks occur earlier in systole than in MVP, best heard to the right of the upper sternum. Click timing not affected by dynamic manoeuvres.",
"<br><strong>Test:</strong> Echocardiogram is diagnostic for bicuspid aortic valve disease as there is a characteristic opening motion of the aortic valve in this condition.</p>",
"</dd>",
"<dt><a href='#Section1'>Pulmonic valve disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Pulmonic ejection clicks occur earlier in systole than in MVP, best heard to the left of the upper sternum. Click timing not affected by dynamic manoeuvres.",
"<br><strong>Test:</strong> Echocardiogram is diagnostic for pulmonic valvular disease as abnormal motion or Doppler findings associated with this valve are evident.</p>",
"</dd>",
"<dt><a href='#Section2'>Atrial myxoma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May have symptoms of weight loss, fever, malaise. Examination may reveal a diastolic tumour plop or diastolic murmur similar to mitral stenosis.",
"<br><strong>Test:</strong> Heterogeneous masses, may be sessile, typically in left atrium. Transoesophageal echocardiogram may yield more detail than transthoracic echocardiogram. Laboratory evaluation may reveal leukocytosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Ischaemia-related mitral regurgitation (MR)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History reveals previous MI. Examination features are similar to MVP-related regurgitant murmurs. May be late systolic or holosystolic, which can mimic severe MVP-related MR. Absence of click.",
"<br><strong>Test:</strong> ECG reveals previous infarction. Echocardiogram findings may delineate papillary muscle and left ventricular akinesis or dyskinesis. The posterior mitral valve leaflet shows restricted motion as compared with the excess motion seen in MVP.</p>",
"</dd>",
"<dt><a href='#Section4'>Rheumatic heart disease-related MR</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of group A streptococcal pharyngitis followed by migratory large-joint arthritis, fever, rash, and subcutaneous nodules. Rheumatic heart disease typically follows 1-2 decades later. Examination features are similar to MVP-related regurgitant murmurs. Usually holosytolic, which can mimic severe MVP-related MR. Absence of click.",
"<br><strong>Test:</strong> ECG may show heart block. Echocardiogram is diagnostic with evidence of restricted motion of both leaflets. A degree of stenosis of the mitral valve with doming of the valve as it opens commonly accompanies the regurgitation.</p>",
"</dd>",
"<dt><a href='#Section5'>Infective endocarditis affecting mitral valve</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Fever, chills, sweats, weight loss, Osler nodes, subungual haemorrhages, Janeway lesions, Roth spots, petechiae.",
"<br><strong>Test:</strong> Vegetations on echocardiography, typically on the atrial side of the valve. Transoesophageal echocardiogram may be more sensitive than transthoracic echocardiogram. Leukocytosis, anaemia, elevated ESR, microscopic haematuria may be seen.</p>",
"</dd>",
"<dt><a href='#Section6'>Tricuspid valve prolapse</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> While tricuspid prolapse may also produce a mid-systolic click sound, it is best heard at the lower left sternal border, or occasionally on the lower right parasternal area. Timing between the S1 and a tricuspid click often increases after inspiration or other manoeuvres that increase right ventricular return.",
"<br><strong>Test:</strong> Echocardiogram is diagnostic but tricuspid valve prolapse and MVP frequently co-exist, whereas isolated tricuspid valve prolapse is rare.</p>",
"</dd>",
"</dl>"].join("\n");