content=["<dl>",
"<dt><a href='#Section0'>Aspergillosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs or symptoms especially in pulmonary disease, except presence of accompanying sinus disease, makes aspergillosis less likely.",
"<br><strong>Test:</strong> Histopathology in aspergillosis demonstrates narrow (2.5-4.5 micrometres) septate hyphae, branching at an acute angle of 45&deg;.Positive serum galactomannan assay may favour the diagnosis of aspergillosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Bacterial sinusitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable from mucormycosis in the initial stages, but typically responds to antibacterial therapy and lacks necrotic eschar.",
"<br><strong>Test:</strong> Sinus puncture with culture may be indicated when standard antibiotics have failed, however, this is considered controversial.</p>",
"</dd>",
"<dt><a href='#Section2'>Bacterial peri-orbital cellulitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs and symptoms in the initial stages, but more commonly lacks risk factors, has history of trauma, and responds to antibacterial therapy.",
"<br><strong>Test:</strong> Blood/eye swab cultures: positive for bacterial culture.</p>",
"</dd>",
"<dt><a href='#Section3'>Sinus lymphomas</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> B-cell or T-cell lymphomas may have presence of lymphadenopathy elsewhere in the body.",
"<br><strong>Test:</strong> Histopathology of biopsy is crucial and demonstrates atypical cells consistent with lymphoma.</p>",
"</dd>",
"<dt><a href='#Section4'>Wegener's granulomatosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> May have renal failure and systemic manifestations of vasculitis in addition to sinus symptoms similar to mucormycosis.",
"<br><strong>Test:</strong> Blood test: positive anti-neutrophil cytoplasmic antibodies (ANCA) may help in diagnosis of Wegener's granulomatosis, but a negative ANCA test does not rule it out. In addition, Wegener's granulomatosis and mucormycosis can co-exist, especially in a patient treated with immunosuppressants for Wegener's granulomatosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Bacterial brain abscess</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs and symptoms.",
"<br><strong>Test:</strong> Aspiration and culture of abscess fluid is positive for bacteria.</p>",
"</dd>",
"<dt><a href='#Section6'>Ecthyma gangrenosum</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Necrotic-appearing lesions on the skin, sometimes with surrounding erythema, occurring typically in the presence of pseudomonal sepsis. Similar host populations are vulnerable.",
"<br><strong>Test:</strong> Culture of lesions is positive for bacteria.</p>",
"</dd>",
"<dt><a href='#Section7'>Fusariosis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Patients with fusariosis have a high incidence of skin lesions as a manifestation of disseminated disease in &gt;50% to 60%, as opposed to &lt;5% to 10% in mucormycosis. [24]Lesions are clinically indistinguishable from mucormycosis.",
"<br><strong>Test:</strong> High incidence of positive blood cultures (&gt;50% of patients) as opposed to rare positive blood cultures in mucormycosis (&lt;5%). [24]</p>",
"</dd>",
"</dl>"].join("\n");