content=["<dl>",
"<dt><a href='#Section0'>Tetany</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Produces a characteristic motor posture known as carpopedal spasm.Hypocalcaemic tetany: tingling begins around the mouth and in the peripheral extremities then increases in intensity and spreads proximally. A sensation of spasm or tension follows the same pattern as the tingling, eventually producing a tonic spasm. If severe, proximal and paraspinal muscles may be involved. Laryngeal muscles are commonly involved early. On examination, positive Troussea's sign and Chvostek's sign are suggestive of neural hyperexcitability.",
"<br><strong>Test:</strong> Typical clinical findings with an associated electrolyte abnormality (either hypocalcaemia, hypomagnesaemia, or alkalosis).There may also be hypokalaemia or hyperkalaemia.Electromyogram findings: individual motor units discharge independently at a rate of 5 to 25 Hz (each discharge is a group of &ge;2 identical potentials).</p>",
"</dd>",
"<dt><a href='#Section1'>Tetanus</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Primary symptoms are muscular rigidity and spasms. Trismus and dysphagia are typical.The spasms, which are extremely painful, are caused by sudden, involuntary contractions of opposing muscles that last for only a few seconds but occur repeatedly for minutes.Spasms are localised or generalised and can be triggered by sensory stimuli, movement, or emotion.In some cases, spasms are severe enough to cause muscle injury or to fracture bones.",
"<br><strong>Test:</strong> Diagnosed clinically.No specific change found in blood, urine, or cerebrospinal fluid (CSF).No specific confirmatory laboratory test (absence of serum tetanus toxin or a negative result from clostridial culture testing does not rule out infection).</p>",
"</dd>",
"<dt><a href='#Section2'>Occupational cramps</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Muscular contractions without pain.A type of dystonia and not cramp.Task specific, arising due to repetitive or skilled use of a body part (e.g., hands [hairstylists, musicians, court reporters], mouth [musicians playing wind instruments]).Begin in adulthood. [79]",
"<br><strong>Test:</strong> No distinguishing tests.</p>",
"</dd>",
"<dt><a href='#Section3'>Neuromyotonia (e.g., Isaac's syndrome)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Predisposes to true muscle cramps.However, other clinical manifestations of this disorder of continuous muscle fibre activity are usually even more prominent.All cases of neuromyotonia have visible continuous muscle twitching (myokymia).Abnormal limb posturing, identical to carpal or pedal spasm, are characteristic and may be persistent or intermittent.There is difficulty in relaxing the muscle (which differs from true myotonia), a lack of percussion myotonia, and increased rather than decreased stiffness with continued activity.In children and young adults it progresses insidiously.",
"<br><strong>Test:</strong> Associated with the presence of serum antibodies to voltage-gated potassium channels.</p>",
"</dd>",
"<dt><a href='#Section4'>Continuous muscle fibre activity syndromes (not neuromyotonia)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Slow muscle relaxation after contraction as well as non-muscular findings (autonomic findings e.g., hyperhidrosis, hypersalivation, and hyperlacrimation).May be associated with autoimmune phenomena such as myasthenia gravis and thymoma. [80]",
"<br><strong>Test:</strong> Electromyogram demonstrates myokymic and neuromyokymic discharges.Autoantibodies to antigens on peripheral motor neurons and autonomic fibres.</p>",
"</dd>",
"<dt><a href='#Section5'>Multiple sclerosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Characterised by affective disorders (depression, primarily), optic neuritis, nystagmus, facial myokymia, vertigo, reduced sensory function, spasticity, paraplegia, exaggerated deep tendon reflexes, gait imbalance, slurred speech, sphincter and sexual dysfunction, heat sensitivity, Lhermitte's sign (electric-shock-like sensation occurring on cervical flexion, radiating down the back and the legs), cognitive impairment, and fatigue. [81]",
"<br><strong>Test:</strong> Magnetic resonance imaging shows white matter lesions.CSF analysis: oligoclonal bands and elevated CSF immunoglobulin (Ig)G and IgG synthesis rate may be present.Somatosensory, visual evoked, and brainstem auditory evoked potentials are prolonged.</p>",
"</dd>",
"<dt><a href='#Section6'>Dystrophinopathies (e.g., Duchenne's or Becker's muscular dystrophy)</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> May be a family history of the condition.Loss of ability to walk by about 12 years old (Duchenne's).Contractures of hips, knees, ankles. Severe scoliosis. [78]",
"<br><strong>Test:</strong> DNA studies may detect deletion of dystrophin gene.Abnormal electrocardiogram due to degeneration and fibrosis of posterolateral aspect of left ventricular wall.Echocardiogram may show abnormal valve and wall motion, cardiomyopathy.Serum creatine kinase levels are markedly increased.Electromyogram may reveal myopathic changes.Muscle biopsy may show variation in fibre sizes, fibrosis, and basophilic and hyaline fibres in groups.</p>",
"</dd>",
"<dt><a href='#Section7'>Myotonic dystrophies</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Myotonia is characterised by slowing in the relaxation of muscles after voluntary contraction or electrical stimulation.Dystrophies characterised by weakness of hand, feet, neck muscles, hollowing of temples due to masseter and temporalis atrophy.Shoulder, hip, leg weakness can lead to repeated falls.Demonstration of myotonia by sharp percussion of muscle with reflex hammer or after firm voluntary contraction.Cardiomyopathy; excessive daytime somnolence and cataracts. [78]",
"<br><strong>Test:</strong> DNA studies may detect mutations of myotonic muscular dystrophy protein kinase (DMPK) gene.Muscle biopsy may show variability in fibre size, fibrosis, and ring fibres.Electromyogram may show myotonic discharges (repetitive firing of muscle fibres at 20 to 80 Hz with waxing/waning of the amplitude/frequency).</p>",
"</dd>",
"<dt><a href='#Section8'>Satoyoshi's syndrome</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Alopecia, diarrhoea, endocrinopathy with amenorrhoea, and secondary skeletal abnormalities, in addition to painful muscle spasms. [82]Syndrome usually develops between 6 and 15 years of age, with alopecia and leg spasms initially.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section9'>Brody's disease</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Difficulty with walking and climbing stairs.Enhanced fatigueability during exercise.Painless contractures (stiffness) during exercise.Increased exercise intolerance in cold environment. [83]  [84]  [85]",
"<br><strong>Test:</strong> Muscle biopsy may be sent for analysis of microsomal calcium uptake, which shows a significant decrease compared with controls.Electromyogram shows impaired relaxation of agonist muscles, with substantial electrical activity of antagonist muscles at the same time.DNA analysis detects deficiency of gene for sarcoplasmic reticulum adenosine triphosphate-dependent calcium pump.</p>",
"</dd>",
"<dt><a href='#Section10'>Swartz-Jampel syndrome</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Facial malformations (microstomia, micrognathia, retrognathia, short palpebral fissures, low-set ears, short neck).Musculoskeletal signs, including myopathy, myotonia, muscle hypertrophy, restricted joint mobility, kyphosis, scoliosis, pectus carinatum, anterior bowing of long bones.Areflexia or hyporeflexia, cognitive dysfunction. [86]",
"<br><strong>Test:</strong> DNA analysis for gene causing abnormal proteoglycan of basement membranes.</p>",
"</dd>",
"<dt><a href='#Section11'>Restless legs syndrome</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Urge to move legs with or without paraesthesiae when relaxing or attempting to sleep. Resolves when patient begins activity. [87]  Associated muscle hardening is not usually present with restless legs syndrome.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section12'>Growing pains</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Not associated with palpable/visible hardening of muscle usually seen with cramps.Most common sites of pain are shins and calves.Pain lasts between a few minutes and a few hours.Occurs at night and usually disappears by the morning. [88]",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"</dl>"].join("\n");