content=["<dl>",
"<dt><a href='#Section0'>Spinal stenosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Numbness, weakness in lower extremities, pain radiating to buttock and leg (especially if the pain radiates beyond the knees), and neurogenic claudication. Spinal stenosis is often bilateral.",
"<br><strong>Test:</strong> Lumbar MRI, CT, or myelography shows spinal canal narrowing.EMG shows elevated insertional activity, fibrillation/sharp waves, and lower recruitment.</p>",
"</dd>",
"<dt><a href='#Section1'>Radiculopathy/sciatica</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Numbness, weakness in lower extremities, pain radiating to buttock and leg (especially if the pain radiates beyond the knees). Radiculopathy/sciatica is often unilateral.",
"<br><strong>Test:</strong> Abnormal or asymmetrical patellar, hamstring, or ankle reflex.Positive straight-leg raise test.Lumbar MRI or myelography shows disc protrusions or foraminal narrowing that impinges on nerve root(s).Lumbar CT shows foraminal narrowing; may not be able to see acute herniation because nerves or disc not visible.EMG shows elevated insertional activity, fibrillation/sharp waves, and lower recruitment.</p>",
"</dd>",
"<dt><a href='#Section2'>Cauda equina syndrome</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Signs and symptoms include GI/GU incontinence or retention, saddle anaesthesia, and sudden unexplained bilateral lower-extremity weakness.",
"<br><strong>Test:</strong> MRI is the best test to show compression of cauda equina.If urinary retention is absent the likelihood of cauda equina is &lt;1/10,000. [47]</p>",
"</dd>",
"<dt><a href='#Section3'>Spinal neoplasia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May be suspected when nocturnal pain and weight loss occurs, particularly if LBP does not improve after 4 to 6 weeks of conservative treatment.",
"<br><strong>Test:</strong> Spine x-ray may demonstrate lysis of the vertebral body or posterior elements; metastases may cause destruction of the pedicle resulting in the winking owl sign.Spine MRI may show either a lytic or blastic lesion with varying T2 signal intensity.ESR may be elevated.Bone scan can identify area of turnover possibly representing primary or metastatic disease.</p>",
"</dd>",
"<dt><a href='#Section4'>Abscess, osteomyelitis, or septic discitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients may present with recent urinary tract or skin infection, immunosuppression, or fever.",
"<br><strong>Test:</strong> MRI can identify abscess, osteomyelitis, or discitis.ESR and C-reactive protein may be elevated.</p>",
"</dd>",
"<dt><a href='#Section5'>Ankylosing or psoriatic spondylitis, or Reiter disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Morning stiffness lasting &gt;60 minutes, improvement of symptoms with physical activity, and awakening at night due to LBP may suggest these inflammatory arthritides.",
"<br><strong>Test:</strong> A positive Schober's test showing a lack of spinal flexibility suggests ankylosing spondylitis, though this is non-specific.ESR and C-reactive protein levels may be elevated.A positive result for the human leukocyte antigen (HLA)-B27 test suggests these conditions.Pelvic and spine x-ray can show sacroilitis and bamboo spine.</p>",
"</dd>",
"<dt><a href='#Section6'>Spinal compression fracture</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Spine tenderness on palpation, particularly in older patients with a history of steroid treatment and/or osteoporosis.",
"<br><strong>Test:</strong> Lumbosacral x-ray can show fractures.Spine CT can more clearly define bony pathology.</p>",
"</dd>",
"<dt><a href='#Section7'>Abdominal aortic aneurysm</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Pain typically presents as sudden onset of intermittent or continuous abdominal pain, radiating to the back; patient may collapse.",
"<br><strong>Test:</strong> Ultrasound/CT of the abdomen can show the presence of abdominal aortic aneurysm.</p>",
"</dd>",
"<dt><a href='#Section8'>Nephrolithiasis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Pain typically radiates towards the groin in these cases.",
"<br><strong>Test:</strong> CT urogram and renal ultrasound results are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section9'>Pyelonephritis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Patients may present with costovertebral angle (CVA) tenderness and urinary symptoms of dysuria, frequency, and hesitancy; flank pain may radiate to back; fever, chills, fatigue may be present.",
"<br><strong>Test:</strong> Positive urinalysis and/or urine culture.</p>",
"</dd>",
"<dt><a href='#Section10'>Sacroiliac (SI) pathology</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> In addition to LBP, pain is also common in the buttocks and upper thighs.",
"<br><strong>Test:</strong> Tenderness to palpation at the SI joint and positive result for the FABER (flexion, abduction, and external rotation) and Gaenslen's (maximal hip flexion plus contralateral hip extension) tests may suggest SI joint dysfunction.Pelvic and lumbar spine x-ray can show sclerotic changes and joint widening.Pelvic and lumbar spine CT can show sclerosis, spurring, and subluxation.</p>",
"</dd>",
"</dl>"].join("\n");