content=["<dl>",
"<dt><a href='#Section0'>Polycythaemia vera</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Aquagenic pruritus (itching after a shower), plethora.",
"<br><strong>Test:</strong> RBC mass and plasma volume elevated.</p>",
"</dd>",
"<dt><a href='#Section1'>Essential thrombocythaemia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Erythromelalgia, ocular migraine.",
"<br><strong>Test:</strong> Peripheral blood leukoerythroblastosis in primary myelofibrosis (PMF).</p>",
"</dd>",
"<dt><a href='#Section2'>Chronic myelogenous leukaemia (CML)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Bone marrow aspiration and biopsy with flow cytometry and cytogenetic analysis, BCR-ABL fusion signal by fluorescence in situ hybridisation or PCR.</p>",
"</dd>",
"<dt><a href='#Section3'>Myelodysplastic syndrome (MDS)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Absence of splenomegaly.",
"<br><strong>Test:</strong> Bone marrow aspiration and biopsy with flow cytometry and cytogenetic analysis: dysplastic bone marrow with variable degrees of peripheral blood cytopenia (with or without monocytosis) suggests MDS.</p>",
"</dd>",
"<dt><a href='#Section4'>Mast cell disease</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Dermatographia or skin rash.",
"<br><strong>Test:</strong> Serum tryptase level: elevated.</p>",
"</dd>",
"<dt><a href='#Section5'>Malignant histiocytosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> May be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Bone marrow aspirate and biopsy: infiltration by malignant histiocytes.</p>",
"</dd>",
"<dt><a href='#Section6'>Acute myelogenous leukaemia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms (constitutional, bleeding, infections) are more acute. Moderate to massive splenomegaly is less common than in PMF.",
"<br><strong>Test:</strong> Bone marrow aspiration and biopsy: bone marrow hypercellularity and infiltration by blasts; blasts &gt;20%, Auer rods, morphological description of type of blast.Immunophenotyping and molecular studies: blasts express surface antigens and molecular markers that help to identify their specific lineage.Peripheral blood smear: blasts on blood film, presence of Auer rods.</p>",
"</dd>",
"<dt><a href='#Section7'>Acute lymphocytic leukaemia</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms (constitutional, bleeding, infections) are more acute. Moderate to massive splenomegaly is less common than in PMF.",
"<br><strong>Test:</strong> Bone marrow aspiration and biopsy: bone marrow hypercellularity and infiltration by lymphoblasts.Immunophenotyping and molecular studies: blasts express surface antigens and molecular markers that help to identify their specific lineage.Peripheral blood smear: leukemic lymphoblasts.</p>",
"</dd>",
"<dt><a href='#Section8'>Hairy-cell leukaemia</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Lymphocytosis and absence of monocytes.",
"<br><strong>Test:</strong> Bone marrow aspiration and biopsy: presence of hairy cells in the bone marrow, presence of reticulin fibres.Flow cytometry and cytogenetic analysis: positive.Peripheral blood smear: presence of hairy cells.</p>",
"</dd>",
"<dt><a href='#Section9'>Hodgkin's lymphoma</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Lymphadenopathy more common in lymphomas.",
"<br><strong>Test:</strong> Lymph node biopsy: Hodgkin's cells within an appropriate background cellular milieu.</p>",
"</dd>",
"<dt><a href='#Section10'>Non-Hodgkin's lymphoma</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Lymphadenopathy more common in lymphomas.",
"<br><strong>Test:</strong> Lymph node biopsy: positive for non-Hodgkin's lymphoma.</p>",
"</dd>",
"<dt><a href='#Section11'>Multiple myeloma</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms of hyperviscosity and bone pain.",
"<br><strong>Test:</strong> Serum and urine protein electrophoresis (SPEP and UPEP): paraprotein spike (IgG &gt;35 g/L [&gt;3.5 g/dL or 3500 mg/dL] or IgA &gt;20 g/L [&gt;2.0 g/dL or 2000 mg/dL]) and light chain urinary excretion &gt;1 g/day); hypogammaglobulinaemia.Serum and urine immunofixation assay (IFE): increased concentrations of free light chain.</p>",
"</dd>",
"<dt><a href='#Section12'>Hyperparathyroidism</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> May be no differences in signs and symptoms.",
"<br><strong>Test:</strong> High-normal to elevated calcium, decreased vitamin D, high-normal to elevated PTH.</p>",
"</dd>",
"<dt><a href='#Section13'>Renal osteodystrophy</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> May be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Urea, creatinine: elevated.Radiological studies: osteopenia.</p>",
"</dd>",
"<dt><a href='#Section14'>Vitamin D deficiency</a></dt>",
"<dd id='Section14'>",
"<p><strong>Sign & Symptoms:</strong> May be no differences in signs and symptoms.",
"<br><strong>Test:</strong> Decreased vitamin D levels.</p>",
"</dd>",
"<dt><a href='#Section15'>Systemic lupus erythematosus (SLE)</a></dt>",
"<dd id='Section15'>",
"<p><strong>Sign & Symptoms:</strong> Skin, joint, and mucosal manifestations of SLE.",
"<br><strong>Test:</strong> Positive ANA, and anti-double-stranded DNA.</p>",
"</dd>",
"<dt><a href='#Section16'>HIV Infection</a></dt>",
"<dd id='Section16'>",
"<p><strong>Sign & Symptoms:</strong> Opportunistic infections.",
"<br><strong>Test:</strong> Anti-HIV antibody: positive.CD4 count: decreased CD4 count.Presence of HIV viral load.</p>",
"</dd>",
"<dt><a href='#Section17'>Tuberculosis</a></dt>",
"<dd id='Section17'>",
"<p><strong>Sign & Symptoms:</strong> Cough and haemoptysis.",
"<br><strong>Test:</strong> Positive tuberculin skin testing, abnormal CXR, and positive microbiological tests.</p>",
"</dd>",
"<dt><a href='#Section18'>Metastatic cancer in the bone marrow</a></dt>",
"<dd id='Section18'>",
"<p><strong>Sign & Symptoms:</strong> May be no differences in signs and symptoms.",
"<br><strong>Test:</strong> CT scans, bone survey, tumour markers: indicate metastatic spread.</p>",
"</dd>",
"</dl>"].join("\n");