content=["<dl>",
"<dt><a href='#Section0'>Untreated sleep apnoea</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients often snore, snort, gasp for air, or choke during sleep.Features pre-disposing to sleep apnoea, such as large neck circumference, high body mass index, crowded oropharynx, glossomegaly.",
"<br><strong>Test:</strong> Polysomnogram (PSG) plus positive airway pressure (PAP) titration.PSG shows loud snoring, elevated arousal index and an apnoea-hypopnoea index of &ge;5.PAP (continuous PAP or bi-level PAP) titration: a progressive increase in PAP level eliminates the apnoeas, hypopnoeas, and snoring; improves arousal index; and normalises the oxygenation and/or flow contour.</p>",
"</dd>",
"<dt><a href='#Section1'>Periodic limb movements of sleep</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Excessive daytime somnolence (EDS) in the absence of cataplexy, hypnagogic/hypnopompic hallucinations, and sleep paralysis.",
"<br><strong>Test:</strong> PSG usually shows periodic limb movement index &gt;20.</p>",
"</dd>",
"<dt><a href='#Section2'>Restless legs syndrome (RLS)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Typical symptoms in adults and children &gt;12 years old include an urge to move the legs. Usually accompanied or caused by uncomfortable sensations in the legs. [1]  [2]Symptoms begin or worsen during periods of inactivity, are worse at night, and are partially or totally relieved by movement.Children may present with a biological parent with RLS.",
"<br><strong>Test:</strong> No need for PSG, unless to exclude other conditions.Distinguished by typical clinical presentation. Children may have a polysomnographic periodic leg movement index &gt;5/hour of sleep.</p>",
"</dd>",
"<dt><a href='#Section3'>Behaviourally induced insufficient sleep syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Sleep hx, patients report getting better after oversleeping or catching up sleep.Lack of features of narcolepsy.",
"<br><strong>Test:</strong> Diagnosis is clinical. No differentiating test.</p>",
"</dd>",
"<dt><a href='#Section4'>Hypersomnia due to medicines</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Hx of medicine use.Temporal association of symptoms with use of medicine.",
"<br><strong>Test:</strong> No need for PSG, unless to exclude other conditions.Challenge/withdraw/re-challenge.</p>",
"</dd>",
"<dt><a href='#Section5'>Hypersomnia due to known physiological condition</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Medical hx (e.g., hydrocephalus).",
"<br><strong>Test:</strong> Diagnosis is clinical. No differentiating test.</p>",
"</dd>",
"<dt><a href='#Section6'>Hypersomnia associated with psychiatric conditions</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Psychiatric history, for example, of depression or of anxiety.",
"<br><strong>Test:</strong> Treatment of underlying condition solves the EDS.</p>",
"</dd>",
"<dt><a href='#Section7'>Idiopathic hypersomnia</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Naps do not improve EDS and are typically unrefreshing; long habitual sleep duration in some patients; sleep inertia or &ldquo;drunkenness&rdquo; (inability or extreme difficulty in morning awakening).Lack of features of narcolepsy.",
"<br><strong>Test:</strong> Diagnosis of exclusion.Can include short or long habitual sleep duration.PSG and multiple sleep latency test (MSLT) often needed to exclude other conditions.MSLT finds shortened sleep latency with (usually) &lt;2 sleep-onset rapid eye movement periods.</p>",
"</dd>",
"<dt><a href='#Section8'>Kleine-Levin syndrome</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Recurrent episodes of EDS of 2 to 14 days' duration, at least yearly and associated with behavioural changes but normal cognition, alertness, and behaviour between the attacks.Lack of features of narcolepsy.",
"<br><strong>Test:</strong> Diagnosis is clinical. No differentiating test.</p>",
"</dd>",
"<dt><a href='#Section9'>Menstrual-related hypersomnia</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Occurs exclusively in women.Episodes start after menarche, last up to 1 week, occur almost monthly, with rapid resolution at the time of the menses.Lack of features of narcolepsy.",
"<br><strong>Test:</strong> Diagnosis is clinical. No differentiating test.Hypersomnia responds to hormonal therapy.</p>",
"</dd>",
"</dl>"].join("\n");