content=["<dl>",
"<dt><a href='#Section0'>Melanoma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Tends to be &gt;6 mm, more irregularly bordered, more asymmetrical, haphazardly multi-coloured, with pink, red, white, brown, black, and blue components. [5]  Referral to a dermatologist is encouraged if the clinician has any doubts in distinguishing a nevus from a melanoma. Excluding malignant change in nevi or de novo melanoma may be challenging, especially when distinguishing from dysplastic or Clark's nevi.",
"<br><strong>Test:</strong> Dermatoscopy: ramified streaks of asymmetrical pigment, black pepper-grain dots, bulbar pseudopods, blue-whitish veils, depigmented areas, multi-coloured pattern, milky red globules, irregular hairpin vessels, ulceration, asymmetrical follicular openings, and rhomboid structures on the face. [30] View imageHistopathology: loss of organised nested melanocytes, and an increase in single melanocytes, often in a pagetoid pattern in the epidermis, with pleomorphism, cytological atypia, and mitotic figures.</p>",
"</dd>",
"<dt><a href='#Section1'>Seborrhoeic keratosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Waxy, 'stuck-on' papules, often multiple, that increase in number over the age of 30 years.",
"<br><strong>Test:</strong> Dermatoscopy: comedo-like follicular pseudo-openings; horny pseudocysts, fissures, and crypts, fingerprint-like patterns, uniform hairpin vessels, and pigment pseudo-network on the face. [30]Histopathology can also distinguish.</p>",
"</dd>",
"<dt><a href='#Section2'>Solar lentigo</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Flat, brown macules and patches on sun-damaged skin.",
"<br><strong>Test:</strong> Dermatoscopy: moth-eaten borders with an even brown reticular pattern.Histopathology can also distinguish.</p>",
"</dd>",
"<dt><a href='#Section3'>Simple lentigo</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Small, flat, brown macules clinically very similar to junctional nevi, found on non-sun-damaged skin.",
"<br><strong>Test:</strong> Dermatoscopy: small, evenly pigmented, brown, reticular pattern.Histopathology can also distinguish.</p>",
"</dd>",
"<dt><a href='#Section4'>Ephelis (freckle)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Multiple flat, light-brown, sun-exposed macules, usually on the face, upper back, dorsal arms, and chest.",
"<br><strong>Test:</strong> History and physical examination can usually distinguish.Dermatoscopy: similar to a solar lentigo but smaller in size.Histopathology can also distinguish.</p>",
"</dd>",
"<dt><a href='#Section5'>Cafe-au-lait macule</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Small-to-large, flat, brown homogenous macules or patches with a well-defined and regular border, present since birth and unchanged, with exception of growth proportional to the person.",
"<br><strong>Test:</strong> History and physical examination can usually distinguish.Histopathology can also distinguish.</p>",
"</dd>",
"<dt><a href='#Section6'>Pigmented basal cell carcinoma (BCC)</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Arising on sun-exposed skin, the pigmented variant of BCC has irregular blue-grey pigment, tends to be asymmetrical, and may be ill-defined.",
"<br><strong>Test:</strong> Dermatoscopy: structureless areas; maple leaf-type structures; branch-like telangiectasias; large, ovoid, blue-greyish nests; radial areas; and ulceration. [30]Histopathology can also distinguish.</p>",
"</dd>",
"<dt><a href='#Section7'>Dermatofibroma</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> A firm, dome-shaped, often hyperpigmented or pink papule, often on the lower extremities of young adults, and thought to be induced by trauma (e.g., insect bite).",
"<br><strong>Test:</strong> Dermatoscopy: central white, scar-like area with pigment at the periphery.Histopathology can also distinguish.</p>",
"</dd>",
"<dt><a href='#Section8'>Haemangioma</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> A red-to-purple, dome-shaped, soft papule.",
"<br><strong>Test:</strong> Dermatoscopy: blood-filled, red-blue lacunae.Histopathology can also distinguish.</p>",
"</dd>",
"</dl>"].join("\n");