content=["<dl>",
"<dt><a href='#Section0'>Alcohol intoxication</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of recent alcohol ingestion.Alcoholic breath and clinically significant maladaptive behavioural changes during or following alcohol ingestion.Lack of co-ordination and unsteady gait.Nystagmus.Impaired attention.Coma.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Blood alcohol levels give an indicator of the level of alcohol in the blood.</p>",
"</dd>",
"<dt><a href='#Section1'>Sedative intoxication</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of recent sedative ingestion.Hostility or mood swings.Poor judgement.Inappropriate sexual behaviour.Lack of co-ordination.Inattention.Blackouts.Extreme sluggishness.Stupor.Coma.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Toxicology screen will show presence of the suspected drug in a blood or urine sample.</p>",
"</dd>",
"<dt><a href='#Section2'>Anticholinergic intoxication</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> History of recent anticholinergic ingestion.Rapid onset of alteration in mood, cognition, and perception in the presence of a clear sensorium.Dry flushed skin.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.If a specific anticholinergic agent is suspected, blood levels should be measured to confirm diagnosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Phencyclidine (PCP) intoxication</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History of recent PCP use.Involuntary rapid movements of the eyes, vertically or horizontally.Palpitations.Drooling.Hyperthermia.Reduced response to pain.Increased alertness.Lack of muscle coordination.Disordered thinking or impaired judgement.Schizophrenic-like psychoses.Coma.Features of rhabdomyolysis (asymptomatic or present with generalized malaise or dark urine).",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Toxicology screen will show presence of PCP in a blood or urine sample.Serum CK: more than 5 times normal if rhabdomyolysis is present.</p>",
"</dd>",
"<dt><a href='#Section4'>Brain injury</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of brain injury.Altered sensorium.Neurological deficits may or may not be present.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Injury seen on MRI or CT brain.</p>",
"</dd>",
"<dt><a href='#Section5'>Hepatic encephalopathy</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Usually secondary to an underlying medical illness.Altered consciousness.Confusion secondary to hepatic dysfunction.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Elevated LFTs.</p>",
"</dd>",
"<dt><a href='#Section6'>Uraemia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Usually a manifestation of underlying medical illness such as renal failure.Headache.Skin discoloration.Pruritus.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Fluid, electrolyte, and hormone imbalances, and metabolic abnormalities, will be present, which develop in parallel with deterioration of renal function.FBC, urinalysis, urine culture and colony count, serum and urine osmolality, chemistry panel, sedimentation rate, arterial blood gas analysis, blood volume, cystoscopy, and retrograde pyelography should be ordered.Additional studies include abdominal CT scan, ultrasonography, and renal biopsy.Results of these tests will be specific to the underlying medical illness causing uraemia.</p>",
"</dd>",
"<dt><a href='#Section7'>Hypoglycaemia</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Abnormal behaviour such as the inability to complete routine tasks.Visual disturbances.Palpitations.Tremors.Anxiety.Coma and seizures are uncommon.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Random serum blood glucose level &lt;4.4 mmol/L (&lt;80 mg/dL).</p>",
"</dd>",
"<dt><a href='#Section8'>Diabetic ketoacidosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Life-threatening condition secondary to diabetes mellitus.Sluggishness and extreme tiredness.Polydipsia and polyuria.Acetone breath.Hyperventilation.Agitation.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Serum glucose level usually &gt;13.9 mmol/L (&gt;250 mg/dL) (although it is usually much higher).Blood pH level &lt;7.3.Serum bicarbonate level &lt;18 mmol/L (&lt;18 mEq/L).Elevated anion gap.</p>",
"</dd>",
"<dt><a href='#Section9'>Alcohol or sedative withdrawal</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Anxiety or irritability.Emotional volatility or agitation.Depression.Palpitations.Clammy skin.Tremors.Delirium tremens (a state of confusion and hallucinations).Convulsions.Blackouts.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Toxicology screen will show presence of the suspected sedative in a blood or urine sample.Blood alcohol levels give an indicator of the level of alcohol in the blood.Elevated LFTs.</p>",
"</dd>",
"<dt><a href='#Section10'>Anxiety</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Usually precipitated by high stress.Headache.Palpitations.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Clinical confirmation of diagnosis by a psychiatrist.</p>",
"</dd>",
"<dt><a href='#Section11'>Depression</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Decreased interest and loss of energy.Sadness.Feelings of guilt.Decreased concentration.Appetite changes.Psychomotor retardation or agitation.Suicidal intent/ideation.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Clinical confirmation of diagnosis by a psychiatrist.</p>",
"</dd>",
"<dt><a href='#Section12'>Hyperthyroidism</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Palpitations.Heat intolerance.Nervousness.Amenorrhoea.Fatigue.Tremors.Warm moist skin.Staring gaze.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Thyroid stimulating hormone (TSH) levels will be decreased along with increased T3 and T4 levels.Sometimes an iodine uptake scan is done to locate the cause of the hyperactive thyroid.</p>",
"</dd>",
"<dt><a href='#Section13'>Phaeochromocytoma</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Palpitations.Anxiety.Diaphoresis.Pallor.",
"<br><strong>Test:</strong> Urine toxicology negative for opioids.Elevated serum or urine catecholamines and metanephrines.Neuroimaging (MRI or CT) helps to localise the tumour.Serum glucose level may be elevated.</p>",
"</dd>",
"</dl>"].join("\n");