content=["<dl>",
"<dt><a href='#Section0'>Chemical burns</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> May be asymptomatic.May be a history of contact with chemical agent, most commonly from topical use of aspirin for toothache.White plaques cannot be scraped off.After elimination of the aetiological factor, lesions will resolve in 7 to 14 days.",
"<br><strong>Test:</strong> Smear examination and periodic acid-Schiff staining will be negative for yeast forms or hyphae.</p>",
"</dd>",
"<dt><a href='#Section1'>Reactive keratosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are usually asymptomatic.May be able to identify a source of chronic irritation (e.g., a faulty dental restoration, an ill-fitting denture, or parafunctional habits such as bruxism or chronic cheek biting).",
"<br><strong>Test:</strong> Definitive diagnosis is always through biopsy and histological evaluation of the lesion.</p>",
"</dd>",
"<dt><a href='#Section2'>Hairy leukoplakia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are asymptomatic.",
"<br><strong>Test:</strong> Definitive diagnosis is through biopsy and histological evaluation of the lesion.In situ hybridisation technique demonstrates the presence of EBV in the tissue.</p>",
"</dd>",
"<dt><a href='#Section3'>Plaque-type lichen planus</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are usually asymptomatic.There may be other lichenoid lesions in other areas of the skin.",
"<br><strong>Test:</strong> Definitive diagnosis is through biopsy and histological evaluation of the lesion.Immunofluorescence staining of the tissue sample may provide additional evidence for the diagnosis, although it is infrequently performed.</p>",
"</dd>",
"<dt><a href='#Section4'>Erosive lichen planus</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are painful, but mostly when eating, whereas erythematous candidiasis may be associated with constant burning pain.Mucosal erosions and lichenoid lesions elsewhere on the skin may be present.",
"<br><strong>Test:</strong> Definitive diagnosis is through biopsy and histological evaluation of the lesion and immunofluorescence staining of the tissue sample if additional diagnostic information is necessary.</p>",
"</dd>",
"<dt><a href='#Section5'>Pre-malignant leukoplakia and carcinoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are usually asymptomatic unless the expansion of malignancy encroaches on anatomical relationship between tissues.Regional lymph nodes may be enlarged.",
"<br><strong>Test:</strong> Definitive diagnosis is through biopsy and histological evaluation of the lesion.Imaging techniques such as x-ray or CT are useful to determine local invasion of carcinoma.</p>",
"</dd>",
"<dt><a href='#Section6'>Thermal burns</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are usually painful but difficult to distinguish from erythematous candidiasis based on symptoms.Lesions are often local, and adequate history may indicate an incidence of burn with food.Lesions resolve in 7 to 14 days with no intervention.",
"<br><strong>Test:</strong> No differentiating tests required.</p>",
"</dd>",
"<dt><a href='#Section7'>Migratory glossitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Lesions are usually asymptomatic.In patients who do complain of discomfort, burning is associated with eating spicy or sour food or alcohol-containing liquids, whereas symptomatic erythematous candidiasis is associated with constant burning.Atrophic zones of migratory glossitis are commonly patchy and are usually surrounded by elevated hyperkeratotic margins.",
"<br><strong>Test:</strong> In the absence of clinically distinguishable features, histological examination of the tissue may be necessary.</p>",
"</dd>",
"</dl>"].join("\n");   