content=["<dl>",
"<dt><a href='#Section0'>Neurally mediated (vasovagal) syncope</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Premonitory symptoms such as sweating and nausea are typical of neurally mediated (vasovagal) syncope, but do not occur in patients with chronic autonomic failure.Symptoms of neurally mediated syncope are intermittent and frequently occur with specific triggers (e.g., blood drawing, prolonged standing). In between episodes, blood pressure responses are normal, and symptoms are not related to standing, eating, or physical exercise.",
"<br><strong>Test:</strong> In the tilt-table test, the blood pressure is initially maintained until, after a variable period, it falls abruptly, often in association with a drop in heart rate. In contrast, in orthostatic hypotension the fall in blood pressure occurs immediately upon head-up tilt, and is usually progressive.The autonomic response to the Valsalva manoeuvre is normal; in contrast, in autonomic failure there is lack of blood pressure overshoot after release of the strain.</p>",
"</dd>",
"<dt><a href='#Section1'>Vertigo</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Vertigo is the result of vestibular or cerebellar pathology, but it may be confused with the dizziness or light-headedness of orthostatic hypotension.",
"<br><strong>Test:</strong> Neurological examination reveals cerebellar ataxia or nystagmus. Vestibular testing with electronystagmography shows abnormal responses.</p>",
"</dd>",
"<dt><a href='#Section2'>Non-specific falls in older people</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Gait imbalance and falls are common in older people and may be the result of impaired postural reflexes, reduced visual acuity, or orthopaedic problems, and may be confused with orthostatic hypotension. These can be assessed by physical examination, including a full neurological examination.",
"<br><strong>Test:</strong> Neurological examination showing gait imbalance or abnormal postural reflexes.</p>",
"</dd>",
"<dt><a href='#Section3'>Psychogenic syncope (pseudo-syncope)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Periods of unresponsiveness due to psychiatric disorders can easily be confused with syncope. A psychiatric evaluation is required to determine the cause.",
"<br><strong>Test:</strong> There are no distinguishing tests.</p>",
"</dd>",
"</dl>"].join("\n");