content=["<dl>",
"<dt><a href='#Section0'>Osteochondral fracture</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Acute onset of pain following a traumatic event. May be associated with a large haemarthrosis.",
"<br><strong>Test:</strong> Aspiration of the knee will demonstrate the presence of a haemarthrosis. X-rays or other advanced imaging including CT scan or MRI may demonstrate the osteochondral fragment.</p>",
"</dd>",
"<dt><a href='#Section1'>Meniscal tear</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May or may not be associated with traumatic event. Point of maximal tenderness will be along the joint line as opposed to femoral condyle. Pain with deep knee flexion will be posterior as opposed to pain in osteochondritis dissecans, which will move anteriorly with deep flexion.",
"<br><strong>Test:</strong> X-rays will be normal with no evidence of osteochondritis dissecans. MRI may demonstrate the presence of a meniscal tear.</p>",
"</dd>",
"<dt><a href='#Section2'>Septic arthritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Effusion and synovitis will be present. May be associated with systemic signs of infection, including fever or chills. The joint may appear erythematous with increased warmth. Range of motion will be severely limited secondary to pain.",
"<br><strong>Test:</strong> X-rays may appear normal with acute infection. FBC, ESR, and CRP should be ordered if possibility of infection exists. Aspiration with synovial fluid analysis for cell count, crystals, culture, and glucose level should be performed to rule out infection if infection remains a possibility.</p>",
"</dd>",
"<dt><a href='#Section3'>Bone contusion</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Joint pain following traumatic injury. Presence of effusion is unlikely. Close examination will reveal the point of maximal tenderness is over the bone as opposed to the articular surface. Mechanical symptoms will not be present.",
"<br><strong>Test:</strong> X-ray examination will be normal. MRI will demonstrate the bone contusion with oedema in the region of injury.</p>",
"</dd>",
"<dt><a href='#Section4'>Soft tissue contusion</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Pain will be superficial. No effusion present. No mechanical symptoms. Tenderness will not be in the region of the articular surface, but in the overlying soft tissue.",
"<br><strong>Test:</strong> Radiographs will be normal. MRI, if ordered, will demonstrate oedema in the soft tissue overlying the joint.</p>",
"</dd>",
"<dt><a href='#Section5'>Panner's disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Impaired blood supply to capitellum growth plate. Occurs in children between the ages of 5 and 12 years.",
"<br><strong>Test:</strong> X-rays show radiolucency of the subarticular surfaces.</p>",
"</dd>",
"</dl>"].join("\n");