content=["<dl>",
"<dt><a href='#Section0'>Multiple myeloma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Bone pain and symptoms of anaemia and renal failure.",
"<br><strong>Test:</strong> Urine electrophoresis reveals Bence Jones proteinuria; serum electrophoresis reveals monoclonal gammopathy.</p>",
"</dd>",
"<dt><a href='#Section1'>Osteomalacia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to differentiate clinically.",
"<br><strong>Test:</strong> PTH levels elevated; bone biopsy standard for confirmation of poor mineralisation.</p>",
"</dd>",
"<dt><a href='#Section2'>Chronic kidney disease-bone and mineral disorder</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to differentiate clinically. May have known history of renal failure. May present with bone pain and diminished muscular strength.",
"<br><strong>Test:</strong> Serum creatinine and PTH elevated.</p>",
"</dd>",
"<dt><a href='#Section3'>Primary hyperparathyroidism</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May be signs of hypercalcaemia, including anorexia, nausea, constipation, and abdominal pain.Often asymptomatic.",
"<br><strong>Test:</strong> Serum PTH elevated.</p>",
"</dd>",
"<dt><a href='#Section4'>Metastatic bone malignancy</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> May have known history of cancer.Symptoms of bone pain after minor injury may be the same as in cases of osteoporosis, but may also occur in atypical locations.",
"<br><strong>Test:</strong> DXA may be normal.CT may show presence of tumour.Bone scan shows multiple hot spots.Definitive test is bone biopsy and appropriate investigations to determine primary.</p>",
"</dd>",
"<dt><a href='#Section5'>Vertebral deformities</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Difficult to differentiate clinically.",
"<br><strong>Test:</strong> Spinal deformities such as osteoarthritis and scoliosis may be mistaken for osteoporotic vertebral fractures. [3]X-ray and further imaging may be required for diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");