content=["<dl>",
"<dt><a href='#Section0'>Seizures (nocturnal)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Nocturnal frontal lobe seizures may be accompanied by incontinence, tongue-biting, tonic-clonic movements, and drooling. All these features are atypical in the parasomnias.Seizures may occur when the patient is awake or asleep; parasomnias are almost always related to sleep. [4]  [25]  [44]  [50]  [51]  [52]",
"<br><strong>Test:</strong> Polysomnography (PSG) with expanded electroencephalographic (EEG) measurements: EEG demonstrates abnormal electrical activity consistent with the diagnosis of epilepsy.</p>",
"</dd>",
"<dt><a href='#Section1'>Narcolepsy</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> May present with similar features to recurrent isolated sleep paralysis.Typically has other symptoms, including cataplexy (sudden focal or generalised loss of muscle tone in the body, brought about by strong emotional experiences), hypnagogic or hypnopompic hallucinations at sleep onset or awakening, and irresistible sleep attacks. [53]  [54]  [55]  [56]  [57]  [58]",
"<br><strong>Test:</strong> Multiple sleep latency tests in narcolepsy demonstrate a mean sleep latency of &lt;8 minutes and &ge;2 sleep-onset rapid eye movement (REM) periods (SOREPS). [12]</p>",
"</dd>",
"<dt><a href='#Section2'>Periodic limb movement disorder (PLMD)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Parents may report that the child makes rhythmic limb movements during sleep (although not an accurate predictor of periodic limb movement disorder diagnostic index, or PLMS-I).",
"<br><strong>Test:</strong> Polysomnography (PSG) with leg electromyography (assessment enhanced using split-screen, video-polysomnographic analysis): demonstrates typical features. [48]  [49]</p>",
"</dd>",
"</dl>"].join("\n");