content=["<dl>",
"<dt><a href='#Section0'>Autoimmune haemolytic anaemia, warm antibody type</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Splenomegaly is often present.",
"<br><strong>Test:</strong> The direct antiglobulin (Coombs) test is usually positive.Spherocytes may be present on blood film.Cells lacking GPI-anchored proteins are not present.</p>",
"</dd>",
"<dt><a href='#Section1'>Microangiopathic haemolytic anaemia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> A reason for microangiopathy (cancer, hypertension, haemangioma, haemolytic uremic syndrome, thrombotic thrombocytopenic purpura) is usually present.",
"<br><strong>Test:</strong> Blood film shows schistocytes.Cells lacking GPI-anchored proteins are not present.</p>",
"</dd>",
"<dt><a href='#Section2'>Paroxysmal cold haemoglobinuria</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Haemoglobinuria follows exposure to cold. In children, often occurs 2 weeks after a viral infection or immunisation.",
"<br><strong>Test:</strong> Donath-Landsteiner (bithermic haemolysis) test may be positive.Direct Coombs test may be positive with anti-C3d.Cells lacking GPI-anchored proteins are not present.</p>",
"</dd>",
"<dt><a href='#Section3'>Myoglobinuria</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Evidence of muscle breakdown (pain, hx of trauma, drug hx, etc) present",
"<br><strong>Test:</strong> Urinary pigment is myoglobin.Serum creatine kinase is increased, as is serum alanine aminotransferase and aspartate aminotransferase.Cells lacking GPI-anchored proteins are not present.</p>",
"</dd>",
"<dt><a href='#Section4'>Abdominal thrombosis (portal, hepatic veins, mesenteric veins or arteries, renal veins)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> From asymptomatic to bouts of abdominal pain, diminished bowel sounds, ascites/varices, bowel perforation, or renal failure. Signs and symptoms depend on the thrombosed vessel.",
"<br><strong>Test:</strong> Cells lacking GPI-anchored proteins are not present.Testing for other sources of thrombosis may be positive</p>",
"</dd>",
"</dl>"].join("\n");