content=["<dl>",
"<dt><a href='#Section0'>Ectopic pregnancy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Lower abdominal pain, adnexal tenderness, fever and other symptoms of acute abdomen (nausea, vomiting, diarrhoea) may be present. May resemble severe case of PID. PID can exist concurrently with ectopic pregnancy.",
"<br><strong>Test:</strong> Positive pregnancy test will guide search for ectopic pregnancy: hCG hormone level is high in serum and urine.Ultrasound reveals an empty uterus and may show a mass in the fallopian tubes.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute appendicitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Nausea and vomiting occurs in most patients with acute appendicitis. Cervical motion tenderness will occur in about 25% of women with appendicitis while this sign is usually present in all patients with PID.",
"<br><strong>Test:</strong> Abdominal ultrasound: aperistaltic or non-compressible structure with outer diameter &gt;6mm; sensitivity for diagnosis of acute appendicitis is 75%-90%. [19]Abdominal and pelvic CT scan: abnormal appendix (diameter &gt;6 mm) identified or calcified appendicolith seen in association with periappendiceal inflammation; sensitivity for diagnosis of acute appendicitis is 87%-98%. [19]Laparoscopy confirms diagnosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Ovarian cyst complications (ruptured ovarian cyst, ovarian cyst torsion, haemorrhagic ovarian cyst)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Ruptured ovarian cyst: rupture usually spontaneous, can follow history of trauma or sexual intercourse; mild chronic lower abdominal discomfort may suddenly intensify. On examination peritoneal signs (guarding, rebound tenderness, rigid abdomen) may be present in lower abdomen and pelvis; adnexal size unremarkable due to collapsed cyst.Ovarian cyst torsion: may present with sudden, acute, unilateral, lower quadrant abdominal pain, severe and colicky in nature; two thirds of patients have nausea and vomiting. Low-grade fever, usually correlates with necrosis; tender adnexal mass palpated in 90%; localised peritoneal irritation.Haemorrhagic ovarian cyst: presents with localised abdominal pain, nausea and vomiting. On examination florid septic or hypovolaemic shock may be present; abdominal tenderness can signify overt peritonitis; pelvic mass may be palpated.",
"<br><strong>Test:</strong> Pelvic ultrasound confirms diagnosis.</p>",
"</dd>",
"<dt><a href='#Section3'>Endometriosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Adnexal enlargement, cervical stenosis or lateral displacement of uterus; cyclic pain that is exacerbated by onset of menses and during the luteal phase; or dyspareunia. Cyclic pain is not a feature of PID.",
"<br><strong>Test:</strong> Transvaginal ultrasound may show ovarian endometrioma or evidence of deep pelvic endometriosis such as uterosacral ligament involvement.Laparoscopy confirms diagnosis by direct visualisation of peritoneal implants with biopsy-confirmed endometrial glands or stroma outside of uterine cavity.</p>",
"</dd>",
"<dt><a href='#Section4'>Non-PID causes of vaginal discharge</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Vulvovaginal symptoms: discharge, itching, burning, dyspareunia. Vulvovaginal symptoms may or may not present in PID because upper tract disease may exist in the absence of symptoms of vaginitis.",
"<br><strong>Test:</strong> Vaginal discharge tested by wet mount or genetic probe or urethral swab identifies causative organism.</p>",
"</dd>",
"<dt><a href='#Section5'>Myofascial pain syndrome</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Tenderness confined to 1 anatomic region. Region may be lower abdomen and pelvis. Does not have associated PID features of fever, elevated WBC count, elevated ESR, vaginal discharge and/or positive Neisseria gonorrhoeae and Chlamydia cultures, and adnexal, or cervical tenderness.",
"<br><strong>Test:</strong> Palpation of trigger points produces reproducible pain.</p>",
"</dd>",
"</dl>"].join("\n");