content=["<dl>",
"<dt><a href='#Section0'>Familial benign pemphigus (Hailey-Hailey disease)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Does not involve the oral mucosa. Characterised by a dermatitis with superficial erosions primarily in flexural areas of the groin, axilla, and neck.FHx usually exists because of the autosomal dominant mode of inheritance, but onset after the age of 30 years is not uncommon.",
"<br><strong>Test:</strong> The skin biopsy demonstrates no immunoreactants with direct immunofluorescence (DIF) staining. Routine histology is similar to that for pemphigus.</p>",
"</dd>",
"<dt><a href='#Section1'>Bullous pemphigoid (BP)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Primarily an autoimmune disease of older people, characterised by tense blisters of the skin, and rarely involves the oral mucosa.Often pruritic and the primary lesion is an urticarial plaque that forms vesicles.Aggressive BP can mimic pemphigus vulgaris (PV). Clinically, the tense blisters of BP differ from those of pemphigus.",
"<br><strong>Test:</strong> BP is distinguished by DIF staining of perilesional skin. A discrete linear band of immunofluorescent staining to IgG, C3, or both is seen along the dermal-epidermal junction.</p>",
"</dd>",
"<dt><a href='#Section2'>Linear IgA bullous dermatosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> This condition clinically mimics BP.",
"<br><strong>Test:</strong> Distinguished from pemphigus and BP by its unique DIF staining profile. A discrete linear band of immunofluorescent staining to IgA, C3, or both is seen along the dermal-epidermal junction.</p>",
"</dd>",
"<dt><a href='#Section3'>Epidermolysis bullosa acquisita (EBA)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Autoimmune skin disease characterised by tense blisters and fragile skin. Distinguished by the presence of significant scarring. The autoantibody of EBA is directed against type VII collagen, so considerable scarring can occur with this disease.Skin fragility is also prominent, particularly of areas that are exposed to minor trauma, such as the hands, elbows, and knees.",
"<br><strong>Test:</strong> EBA is distinguished by DIF staining of perilesional skin. A discrete broad linear band of immunofluorescent staining to IgG, C3, or both is seen along the dermal-epidermal junction.EBA can be differentiated from BP through the use of salt-split skin staining, in which immunoreactants to IgG, C3, or both are found on the base of the artifactual blister.</p>",
"</dd>",
"<dt><a href='#Section4'>Erythema multiforme (EM)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Autoinflammatory skin disease associated with HSV infection, certain medications, and other infections. The classic lesion is a targetoid plaque that is often painful.Constitutional symptoms of fever, lethargy, and myalgia are not uncommon.EM can cause blisters, but when it does, it often causes more tense blisters that are easily distinguishable from pemphigus lesions.",
"<br><strong>Test:</strong> Patients with paraneoplastic pemphigus (PNP) can have lesions that clinically and histologically resemble EM. Often DIF staining is needed in these cases. In EM, DIF staining shows an interface dermatitis with immunofluorescent staining of apoptotic keratinocytes. In PNP, DIF staining can resemble PV or BP, or both, but also has deposition of fibrin in the lamina propria (also seen in lichen planus).</p>",
"</dd>",
"<dt><a href='#Section5'>Aphthous stomatitis (ulcers)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Aphthous ulcers are well-demarcated ulcers that occur in the mouth and genital region. They are often painful. They have a self-limited course, lasting 3 to 7 days, can recur, and are associated with stress and fatigue. In contrast, PV is a chronic condition that tends to progress without treatment. The erosions of PV are often not painful early in their course.",
"<br><strong>Test:</strong> The histology of aphthous ulcers is characterised by an infiltrate of lymphocytes, macrophages, and neutrophils in the base of the ulcer. The small vessels and the surrounding epithelium are often involved.</p>",
"</dd>",
"<dt><a href='#Section6'>Behcet's disease</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> The cutaneous manifestation of Behcet's disease that resembles PV is the presence of aphthous ulcers. However, Behcet's is characterised by involvement of other organs that include the eye, central nervous system, GI tract, and GU system.The aphthous ulcers of Behcet's are distinct from the lesions of pemphigus because they appear as punched-out ulcers rather than shallow erosions and blisters. Behcet's may show pathergy (i.e., lesions may develop at sites of minor trauma, e.g., sterile needle prick).",
"<br><strong>Test:</strong> The primary lesion of Behcet's, an aphthous ulcer, is distinguished from pemphigus because it has a distinct pathology. In addition, the pathology of Behcet's can involve the skin vasculature as well as the fat.</p>",
"</dd>",
"<dt><a href='#Section7'>Herpetic stomatitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> HSV-1 and HSV-2 cause blisters of the mouth, lips, and skin. HSV-2 is commonly associated with sexual transmission and involves the genital area. HSV-1 more commonly involves the mouth, but also the skin, particularly at sites of minor skin trauma or in patients with eczema (atopic dermatitis).Herpetic stomatitis is due to infection with HSV. The vesicles are often fragile and have a scalloped border.",
"<br><strong>Test:</strong> The presence of HSV on culture or by either a Tzanck smear or a direct fluorescence antibody test differentiates this disease from pemphigus.</p>",
"</dd>",
"<dt><a href='#Section8'>Oral lichen planus (LP)</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Lichen planus is an autoimmune cutaneous disease that involves the skin, mucosa, and hair follicles.When lichen planus involves the mouth, it is often erosive. It is more common on the buccal mucosa but can also involve the gingiva and lips.Oral lichen planus can resemble the erosions of pemphigus, but typically it also has a lichenoid appearance with a net-like reticulated pattern.",
"<br><strong>Test:</strong> Routine histology and DIF staining of skin or mucosa differentiate lichen planus from pemphigus. In lichen planus, a band of lymphocytes is seen along the dermal-epidermal junction with accompanying apoptosis of basal keratinocytes and saw-toothing of the dermal papillae.DIF findings show staining of apoptotic keratinocytes and a distinct pattern of fibrin staining along the dermal-epidermal junction that extends into the lamina propria.</p>",
"</dd>",
"<dt><a href='#Section9'>Stevens-Johnson syndrome (SJS)</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> A variant of erythema multiforme that involves a large percentage of the cutaneous body surface area and the mucosa. It is a medical emergency often requiring admission to a burn centre.It is frequently associated with the ingestion of a drug or a recent infection.It progresses rapidly, and patients report painful skin. Constitutional symptoms of fever and lymphadenopathy are often present.",
"<br><strong>Test:</strong> Routine haematoxylin and eosin staining of fixed or frozen skin can diagnose the condition.Necrosis of the basal keratinocytes with extension into the superficial dermis and epidermis is seen. DIF findings are non-specific, often demonstrating numerous apoptotic keratinocytes but no distinctive immunofluorescent pattern as seen in pemphigus, BP, or LP.</p>",
"</dd>",
"<dt><a href='#Section10'>Toxic epidermal necrolysis (TEN)</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> A variant of erythema multiforme that involves a large percentage of the cutaneous body surface area and the mucosa. It is a medical emergency often requiring admission to a burn centre.It is frequently associated with the ingestion of a drug or a recent infection.It progresses rapidly, and patients report painful skin. Constitutional symptoms of fever and lymphadenopathy are often present.",
"<br><strong>Test:</strong> Routine haematoxylin and eosin staining of fixed or frozen skin can diagnose the condition.Necrosis of the basal keratinocytes with extension into the superficial dermis and epidermis is seen. DIF findings are non-specific, often demonstrating numerous apoptotic keratinocytes but no distinctive immunofluorescent pattern as seen in pemphigus, BP, or LP.</p>",
"</dd>",
"</dl>"].join("\n");