content=["<dl>",
"<dt><a href='#Section0'>Myocardial infarction or ischaemia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Chest pain is described as pressure-like, heavy, squeezing, and responsive to glyceryl trinitrate. There is generally no variation with respiration or positional changes. Duration of pain is minutes to hours, rather than hours to days.Pericardial friction rub is generally absent (unless there is associated pericarditis). [5]  [10]  [1]",
"<br><strong>Test:</strong> ECG may show convex ST elevations in the distribution of coronary arteries; Q waves may be present; PR segment depression is rare; inverted T waves when ST segments are still elevated. Significant elevation of serum troponin and cardiac enzymes present if myocardial damage.</p>",
"</dd>",
"<dt><a href='#Section1'>Pulmonary embolism</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Chest pain can be anterior, posterior, or lateral in location. It is in phase with respiration (no chest pain when the patient ceases breathing) and is not positional in nature.Pericardial friction rub is rarely present.A pleural friction rub can be detected in 3% of patients. [5]  [7]  [10]  [1]",
"<br><strong>Test:</strong> ECG may show ST-segment elevations limited to leads III, aVF, and V1; no PR depressions; Q waves in leads III and/or aVF; inverted T waves in leads II; aVF, anterior precordial leads while ST segments are elevated.</p>",
"</dd>",
"<dt><a href='#Section2'>Pneumonia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Associated with cough and fever. Note that the presence of pneumonia may also be related to the presence of concomitant pericarditis.",
"<br><strong>Test:</strong> Chest x-ray may show evidence of infiltrates.The absence of concomitant ECG findings supporting pericarditis excludes significant pericardial involvement.</p>",
"</dd>",
"<dt><a href='#Section3'>Pneumothorax</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Many of the signs and symptoms may overlap including sudden onset shortness of breath, tachycardia, and chest pain. Pericarditis pain may be more positional in nature.Physical examination reveals absence of breath sounds, generally unilaterally.Tracheal deviation may also be present.",
"<br><strong>Test:</strong> Chest x-ray confirms lung collapse.</p>",
"</dd>",
"<dt><a href='#Section4'>Costochondritis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> There is reproducible tenderness with palpation of the costochondral junctions. The pain is exacerbated by moving the trunk.Physical examination is otherwise normal.",
"<br><strong>Test:</strong> Normal ECG.Echocardiography shows no evidence of pericardial involvement.</p>",
"</dd>",
"</dl>"].join("\n");