content=["<dl>",
"<dt><a href='#Section0'>Upper respiratory infection</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Lack of whooping-type cough. [2]  [3]  [4]  [1]  [33]",
"<br><strong>Test:</strong> Culture: negative result for B pertussis</p>",
"</dd>",
"<dt><a href='#Section1'>Community-acquired pneumonia (CAP)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Lack of whooping-type cough. [2]  [3]  [4]  [1]  [33]Fever, history of productive cough, history of respiratory disease (e.g., asthma). Signs of pneumonia on auscultation.",
"<br><strong>Test:</strong> Culture negative result for B pertussis or positive for pathogens associated with community-acquired pneumonia (e.g.,  Chlamydia pneumoniae,  Mycoplasma pneumoniae). [2]  [3]  [4]  [1]  [20]  [33]CXR may show evidence of infiltrates in primary CAP or if patient develops pneumonia as a complication of pertussis. CXR is normal in uncomplicated pertussis.</p>",
"</dd>",
"<dt><a href='#Section2'>Respiratory syncytial viral (RSV) infection</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Extremes of age (infants and elderly), history of prematurity in infants, coryza, conjunctivitis, sinus/ear involvement, wheezing, dyspnoea, use of accessory muscles of respiration. History of community outbreak. Lack of whooping-type cough. [2]  [3]  [4]  [1]  [33]",
"<br><strong>Test:</strong> Culture: negative result for B pertussis.RSV infection diagnosis can be made by virus isolation, detection of viral antigens, detection of viral RNA, demonstration of a rise in serum antibodies, or a combination of these approaches. Most clinical laboratories use antigen detection assays to diagnose infection.</p>",
"</dd>",
"</dl>"].join("\n");