content=["<dl>",
"<dt><a href='#Section0'>Anxiety and panic attacks</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Careful history-taking is required to differentiate these conditions from a phaeochromocytoma.It is important to assess the patient's mental state, and enquire about phobias and other psychiatric conditions.Panic attacks and anxiety are often situational, whereas symptoms associated with a phaeochromocytoma are episodic in nature.",
"<br><strong>Test:</strong> Diagnosis is clinical.These patients will not have biochemical evidence of hypercatecholaminaemia when they are not having a panic attack.</p>",
"</dd>",
"<dt><a href='#Section1'>Essential or intractable HTN</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> The presence of symptoms such as headache, palpitations, and diaphoresis are all suggestive for a phaeochromocytoma, especially in the setting of HTN.",
"<br><strong>Test:</strong> Phaeochromocytomas can usually be ruled out with measurement of urine metanephrines, normetanephrines, and catecholamines.Paroxysmal, drug-resistant HTN is more suggestive for a phaeochromocytoma. In contrast, essential HTN is drug-responsive and easier to treat.</p>",
"</dd>",
"<dt><a href='#Section2'>Hyperthyroidism</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> May mimic a phaeochromocytoma as it is also associated with diaphoresis, palpitations, tremors, and weight loss.",
"<br><strong>Test:</strong> Depressed TSH levels support a diagnosis of hyperthyroidism in the setting of an elevated free thyroxine level.Urinary work-up studies for a phaeochromocytoma would be negative.</p>",
"</dd>",
"<dt><a href='#Section3'>Consumption of illicit substances</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Certain recreational drugs such as cocaine and amphetamines can cause symptoms similar to those of a phaeochromocytoma.",
"<br><strong>Test:</strong> Toxicology may be useful if drug abuse is suspected as catecholamine and metabolite levels may be acutely raised after consumption of these substances, making it difficult to distinguish from a phaeochromocytoma.</p>",
"</dd>",
"<dt><a href='#Section4'>Carcinoid syndrome</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> This syndrome is characterised by periods of intense flushing usually associated with diarrhoea, cramping, pulmonary wheezing, and tricuspid valve and pulmonary valve abnormalities.Carcinoid tumours are characteristically associated with a skin flush; in contrast, phaeochromocytomas are associated with pallor.",
"<br><strong>Test:</strong> Carcinoid is diagnosed by increased urinary secretion of 5-hydroxyindole acetic acid, as well as a biopsy of the tumour.</p>",
"</dd>",
"<dt><a href='#Section5'>Cardiac arrhythmias</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Can also present with symptoms similar to those caused by a phaeochromocytoma: namely, palpitations.Rarely, an underlying phaeochromocytoma may actually be the precipitant of an arrhythmia (e.g., SVT, ventricular fibrillation).",
"<br><strong>Test:</strong> Negative ECG/telemetry/Holter monitoring while the patient is symptomatic can rule out this diagnosis.Catecholamines and metanephrines will be high in a phaeochromocytoma and normal in patients with an isolated arrhythmia.</p>",
"</dd>",
"<dt><a href='#Section6'>Menopause</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms of the menopause may mimic a phaeochromocytoma.Patients commonly complain of perfuse sweating and flushing.In contrast, patients with a phaeochromocytoma have profuse sweating associated with pallor.",
"<br><strong>Test:</strong> Catecholamines and their metabolites are not elevated during the menopause.</p>",
"</dd>",
"<dt><a href='#Section7'>Pre-eclampsia</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Typically, presents beyond 20 weeks of pregnancy; therefore, usually not a likely differential in most patients.Phaeochromocytomas present a rare diagnostic and therapeutic challenge in the pregnant woman. [18]Pre-eclampsia is associated with oedema, which is not a feature of a phaeochromocytoma.",
"<br><strong>Test:</strong> Pre-eclampsia patients have proteinuria and usually an elevated blood uric acid; these values are normal in patients with a phaeochromocytoma.Catecholamines and metanephrines will be high in a phaeochromocytoma and normal in patients with pre-eclampsia.</p>",
"</dd>",
"</dl>"].join("\n");           