content=["<dl>",
"<dt><a href='#Section0'>Photo-allergic reaction</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of potential photo-allergic substances, both topical (e.g., UV filters, such as PABA [para-aminobenzoic acid], cinnamates, artificial scents) and systemic medicines, such as antidepressants, antihypertensive medicine, antiphlogistics, or antibiotics.Typical clinical signs include irregular erythema, papulovesicles, infiltration with scaling, and crusts.The clinical manifestation resembles that of an allergic contact dermatitis, but confined to UV-exposed areas. Some dissemination may occur. The typical symptom is itching. View image",
"<br><strong>Test:</strong> Photo-patch testing demonstrates a delayed reaction, with a slowly increasing (crescendo) inflammatory/eczematous reaction.</p>",
"</dd>",
"<dt><a href='#Section1'>Phototoxic reaction</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typical clinical signs are an amplified sunburn reaction and a positive history for phototoxic agents, both topical (e.g., tar, psoralens, giant hogweed, certain perfumes) and systemic medicines, such as antidepressants, diuretics, antiphlogistics, psoralens, or antibiotics (especially, tetracycline).Typical symptoms are stinging and burning, even pain. View imageIn PLE there is usually only itching.",
"<br><strong>Test:</strong> Photo-patch testing demonstrates a sharply delineated, immediate, or delayed reaction, with a slowly decreasing (decrescendo) reaction.</p>",
"</dd>",
"<dt><a href='#Section2'>Chronic actinic dermatitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Persistent light reaction, actinic reticuloid, or chronic photosensitive dermatitis are synonyms. [37]  [38]  [39]Typically UV-B-induced (while PLE is more commonly UV-A-induced). Symptoms evolve over several days (like PLE), but persist for many weeks and form thick plaques, eczematous lesions with scaling and erosions, and lichenification. View image",
"<br><strong>Test:</strong> Single photoprovocation on previously non-UV-exposed skin causes induction of a persistent dermatitis (within 72 hours).Skin biopsy and histopathological examination show spongiotic changes in the epidermis with uneven epidermal hyperplasia, crusts, and individual necrotic keratinocytes. The dermo-epidermal junction shows vacuolar alteration accompanied by a pronounced perivascular lymphocytic and sometimes also eosinophilic infiltration around the superficial and deep plexus.</p>",
"</dd>",
"<dt><a href='#Section3'>Solar urticaria</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Clinical signs consist of urticaria on UV-exposed sites that disappear quickly. The urticarial variant of PLE might resemble this presentation; however, skin lesions are visible for a few days in PLE.",
"<br><strong>Test:</strong> Single photoprovocation on previously non-UV-exposed skin demonstrates immediate (up to 1 hour) induction of urticarial patches. Visible or infrared light might be part of the induction spectrum. If conventional tests are negative, exposure to natural sunlight may be considered. [40]</p>",
"</dd>",
"<dt><a href='#Section4'>Erythema exudativum multiforme</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Photosensitive variants of erythema exudativum multiforme are rare but difficult to distinguish from the erythema exudativum multiforme type of PLE. [4]  Typically, a concurrent infection with herpes simplex virus is present together with intensive UV exposure, which elicits symptoms. [4]",
"<br><strong>Test:</strong> Diagnosis is clinical</p>",
"</dd>",
"<dt><a href='#Section5'>Systemic lupus erythematosus</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Typical signs involve the delayed appearance of erythematous plaques on UV-exposed sites that persist over a prolonged period of time (weeks).Typical symptoms are stinging and burning. Skin lesions disappear within a few days (after avoiding UV exposure). View image",
"<br><strong>Test:</strong> Repetitive photoprovocation on previously non-UV-exposed predilection sites (upper arms, shoulders). Induction of typical skin lesions might take time (several days up to 3 weeks) and require several weeks for remission. [41]Skin biopsy and histopathological examination with immunofluorescence shows atrophic changes in the epidermis with vacuolar degeneration, band-like infiltration of immunoglobulins, and complement along the basal membrane (positive direct immunofluorescence; absent in PLE).ANA, anti-Ro (SS-A), and anti-La (SS-B) tests should be obtained. In PLE they are negative.</p>",
"</dd>",
"<dt><a href='#Section6'>Lymphocytic infiltration</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Clinical signs include persistent plaques and papules, similar to PLE. [42]  Signs persists longer than PLE.",
"<br><strong>Test:</strong> Repetitive photoprovocation on previously non-UV-exposed predilection sites leads to the induction of typical skin lesions within a few days.Histopathological examination shows similar signs to PLE, but but with no sub-epidermal oedema.</p>",
"</dd>",
"</dl>"].join("\n");