content=["<dl>",
"<dt><a href='#Section0'>Pregnancy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of unprotected intercourse.",
"<br><strong>Test:</strong> Serum or urine hCG: positive.</p>",
"</dd>",
"<dt><a href='#Section1'>Polycystic ovary syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Slowly progressive symptoms, obesity, hirsutism, acne, deepening of voice, male pattern hair growth or loss, oily skin, weight gain, oligoanovulatory cycles to amenorrhoea (if peripubertal onset, may present with delayed menarche), history of premature pubarche, androgenic alopecia, acanthosis nigricans, increased waist-hip ratio, and clitoromegaly.",
"<br><strong>Test:</strong> Serum hCG: negative; serum FSH: normal; serum oestradiol: normal to elevated; serum AMH: elevated; serum TSH: normal; serum prolactin: normal; serum dehydroepiandrosterone sulfate (DHEAS): elevated; total serum testosterone: elevated, marked elevation suggests ovarian/adrenal tumour; pelvic ultrasound: polycystic ovaries, variable endometrial stripe.</p>",
"</dd>",
"<dt><a href='#Section2'>Anorexia nervosa</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Low BMI (10% less than ideal body weight), normal secondary sexual characteristics, normal external and internal genitalia.",
"<br><strong>Test:</strong> Serum hCG: negative; serum FSH: low to normal (FSH assays have wide ranges, depending not only on cycle time but also on patient age); serum oestradiol: low; serum AMH: low to normal; serum TSH: normal; serum prolactin: normal; pelvic ultrasound: thin endometrial stripe.</p>",
"</dd>",
"<dt><a href='#Section3'>Strenuous exercise</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Weight loss, anorexia, sleep disturbances, dry skin, prescription drugs, normal secondary sexual characteristics, and normal external and internal genitalia.",
"<br><strong>Test:</strong> Low BMI (10% less than ideal body weight); serum hCG: negative; serum FSH: low to normal (FSH assays have wide ranges, depending not only on cycle time but also on patient age); serum oestradiol: low; serum TSH: normal; serum prolactin: normal; pelvic ultrasound: thin endometrial stripe.</p>",
"</dd>",
"<dt><a href='#Section4'>Emotional or physical stress</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Weight loss, anorexia, sleep disturbances, dry skin, prescription drugs, normal secondary sexual characteristics, and normal external and internal genitalia.",
"<br><strong>Test:</strong> Low BMI (10% less than ideal body weight); serum hCG: negative; serum FSH: low to normal (FSH assays have wide ranges, depending not only on cycle time but also on patient age); serum oestradiol: low; serum TSH: normal; serum prolactin: normal; pelvic ultrasound: thin endometrial stripe.</p>",
"</dd>",
"<dt><a href='#Section5'>Sheehan's syndrome</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Severe obstetric haemorrhage, hypotension, and shock with postpartum panhypopituitarism (after volume and blood resuscitation), nausea, vomiting, lethargy, failure to breastfeed, slowed mental function, fatigue, weight loss, delayed symptoms of hypothyroidism, postural hypotension, loss of axillary and pubic hair, adrenal crisis (with skin depigmentation), rapidly involuting breasts, and periorbital oedema.",
"<br><strong>Test:</strong> Serum hCG: negative; serum FSH: low; serum oestradiol: low; serum TSH: low; serum T4: low; serum prolactin: low; serum growth hormone: low; serum ACTH: low to normal; serum sodium: may be low; serum cortisol (morning): may be low; MRI brain: sella empty or filled with CSF, pituitary gland may be small; pelvic ultrasound: thin to variable endometrial stripe.</p>",
"</dd>",
"<dt><a href='#Section6'>Androgen-producing ovarian tumour</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Rapidly progressive symptoms, obesity, hirsutism, acne, deepening voice, male pattern hair growth or loss, oily skin, weight gain, oligoanovulatory cycles to amenorrhoea; androgenic alopecia, clitoromegaly, male pattern hair growth, increased muscle mass.",
"<br><strong>Test:</strong> MRI abdomen and pelvis would show an ovarian mass; free serum testosterone: elevated; total serum testosterone: elevated (&lt;200 nanograms/dL [&lt;6.94 nanomol/L]); serum DHEAS: normal; serum FSH, LH, TSH, and prolactin: normal; serum oestradiol: normal to elevated.</p>",
"</dd>",
"<dt><a href='#Section7'>Hyperprolactinaemia</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Galactorrhoea (some patients), headache or visual disturbances (prolactinoma); may present with oligomenorrhoea if prolactin levels are not extremely elevated; visual field deficit (some patients).",
"<br><strong>Test:</strong> MRI brain may show pituitary tumour; serum prolactin: elevated; &gt;100 nanograms/mL is highly suggestive of prolactinoma; serum FSH and LH: low to normal; serum oestradiol: low.</p>",
"</dd>",
"<dt><a href='#Section8'>Medication-induced amenorrhoea</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Antipsychotic medications are known to increase the risk of hyperprolactinaemia and menstrual irregularities due to lessened inhibition by dopamine.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section9'>Congenital adrenal hyperplasia (non-classic)</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Presents in late childhood to early adult life; obesity, hirsutism, acne, weight gain, history of premature pubarche; androgenic alopecia.",
"<br><strong>Test:</strong> Serum 17-hydroxyprogesterone (17-OHP) fasting levels &gt;200 nanograms/dL (&gt;6.06 nanomol/L); total serum testosterone: elevated; free serum testosterone: elevated; serum DHEAS: elevated; serum FSH, LH, TSH, and prolactin: normal; serum oestradiol: normal to elevated.</p>",
"</dd>",
"<dt><a href='#Section10'>Primary amenorrhoea</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Lack of menses by age 15 years in a patient with appropriate development of secondary sexual characteristics, or absent menses by age 13 years and no other pubertal maturation.",
"<br><strong>Test:</strong> Assessment begins with clinical features (assessment of breast development and hair patterns), FSH testing, and presence or absence of normal female reproductive tract on ultrasound. At times, a karyotype and/or serum testosterone measurements may be helpful.</p>",
"</dd>",
"<dt><a href='#Section11'>Turner's syndrome</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Physical features include short stature, webbed neck, cubitus valgus (increased carrying angle of arms), and lack of sexual development at puberty.",
"<br><strong>Test:</strong> Karyotype of Turner's syndrome is 45,XO.</p>",
"</dd>",
"<dt><a href='#Section12'>Asherman's syndrome</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Amenorrhoea or light, but regular, periods.No signs of hypo-oestrogenism.History of endometrial curettage or severe post-partum haemorrhage.",
"<br><strong>Test:</strong> Transvaginal ultrasound, saline sono-contrast sonography, or hysteroscopy shows scar formation.</p>",
"</dd>",
"<dt><a href='#Section13'>Hypothyroidism</a></dt>",
"<dd id='Section13'>",
"<p><strong>Sign & Symptoms:</strong> Frequently insidious onset of fatigue, goitre, exophthalmos, lid lag, bradycardia, or skin changes.",
"<br><strong>Test:</strong> Low free T4, elevated TSH.</p>",
"</dd>",
"</dl>"].join("\n");