content=["<dl>",
"<dt><a href='#Section0'>Essential HTN</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs or symptoms.",
"<br><strong>Test:</strong> Aldosterone/renin ratio will be normal if performed off interfering medicines. May be elevated if patient receiving medicines (such as beta-blockers) that cause false positives, in which case test should be repeated after such medicines are withdrawn for at least 2 (and preferably 4) weeks.A normal ratio in a patient receiving medications that can cause false positives makes PA highly unlikely.In a minority of cases of PA, there is unprovoked hypokalaemia.</p>",
"</dd>",
"<dt><a href='#Section1'>Thiazide-induced hypokalaemia in patient with essential HTN</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of use of thiazides.",
"<br><strong>Test:</strong> Aldosterone/renin ratio will be normal after correcting hypokalaemia and withdrawing thiazide for at least 6 weeks. [59]</p>",
"</dd>",
"<dt><a href='#Section2'>Secondary HTN</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Known renal artery stenosis, history of arterial disease elsewhere, or risk factors for atherosclerosis (e.g., smoking, diabetes, and hyperlipidaemia).",
"<br><strong>Test:</strong> Aldosterone/renin ratio will be normal or low. [58]  [59]Imaging studies will demonstrate renal artery stenosis or reninoma.</p>",
"</dd>",
"<dt><a href='#Section3'>Liddle's syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Family history of Liddle's syndrome.Usually presents in childhood.",
"<br><strong>Test:</strong> Although patients are usually hypokalaemic and have suppressed renin levels, aldosterone levels are also low and the ratio usually is normal. [82]  [59]</p>",
"</dd>",
"<dt><a href='#Section4'>Syndrome of apparent mineralocorticoid excess</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Family history of this syndrome. Hereditary form usually presents in childhood.History of excessive consumption of liquorice, which can lead to an acquired form.",
"<br><strong>Test:</strong> Although patients are usually hypokalaemic and have suppressed renin levels, aldosterone levels are also low and the ratio usually is normal. Urinary free cortisol/cortisone ratio is elevated. [82]  [59]</p>",
"</dd>",
"<dt><a href='#Section5'>Hypertensive forms of congenital adrenal hyperplasia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Family history of congenital adrenal hyperplasia due to 11beta-hydroxylase or 17alpha-hydroxylase deficiency.Usually presents in childhood.History of either virilisation (in the case of 11beta-hydroxylase deficiency) or feminisation (in the case of 17alpha-hydroxylase deficiency).",
"<br><strong>Test:</strong> Although patients are usually hypokalaemic and have suppressed renin levels, aldosterone levels are also low and the aldosterone/renin ratio usually is normal.In 11beta-hydroxylase deficiency, plasma cortisol and corticosterone are low, whereas basal or ACTH-stimulated levels of deoxycorticosterone and 11-deoxycortisol are elevated.In 17alpha-hydroxylase deficiency, plasma levels of 17alpha-hydroxyprogesterone, 11-deoxycortisol, and cortisol are reduced, whereas gonadotrophins (LH and FSH) are increased. [82]  [59]</p>",
"</dd>",
"<dt><a href='#Section6'>Primary glucocorticoid resistance</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Family history of this syndrome (but can be acquired).May be associated with androgenisation.",
"<br><strong>Test:</strong> Although patients are usually hypokalaemic and have suppressed renin levels, aldosterone levels are also low and the aldosterone/renin ratio usually is normal.Associated with increased ACTH and cortisol levels, and resistance of cortisol to adrenal suppression by dexamethasone, in the absence of clinical stigmata of Cushing's syndrome. [82]  [59]</p>",
"</dd>",
"<dt><a href='#Section7'>Ectopic ACTH syndrome</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Clinical findings of underlying tumour.",
"<br><strong>Test:</strong> Although patients are usually hypokalaemic and have suppressed renin levels, aldosterone levels are also low and the aldosterone/renin ratio usually is normal.Evidence of underlying tumour on imaging studies.Cortisol and ACTH levels elevated and non-suppressible with high-dose dexamethasone. [82]  [59]</p>",
"</dd>",
"<dt><a href='#Section8'>Activating mutations of the mineralocorticoid receptor</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Family history of this syndrome.Exacerbation of HTN and development of hypokalaemia during pregnancy.",
"<br><strong>Test:</strong> Although patients are usually hypokalaemic and have suppressed renin levels, aldosterone levels are also low and the aldosterone/renin ratio usually is normal. [82]  [59]</p>",
"</dd>",
"<dt><a href='#Section9'>Pseudohypoaldosteronism type II</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Family history of this syndrome.",
"<br><strong>Test:</strong> Although renin levels are usually suppressed and aldosterone/renin ratio is often elevated, plasma potassium levels are elevated. [82]  [59]</p>",
"</dd>",
"</dl>"].join("\n");