content=["<dl>",
"<dt><a href='#Section0'>Pseudo-pseudohypoparathyroidism</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients have Albright's hereditary osteodystrophy without symptoms or signs of PTH hormone resistance.",
"<br><strong>Test:</strong> Serum calcium and PTH are normal.Normal response to exogenous PTH as measured by urine cAMP and urine phosphorous.Paternal inheritance of causative GNAS mutations (GNAS is the gene that codes for the guanine nucleotide-binding protein Gs-alpha).</p>",
"</dd>",
"<dt><a href='#Section1'>Primary hypoparathyroidism</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of prior thyroid gland surgery, multiple transfusions, or Wilson's disease.Morphological features of DiGeorge syndrome may be present (hypertelorism, micrognathia, short philtrum with fish-mouth appearance, anti-mongoloid slant, telecanthus with short palpebral fissures).Deafness or blindness suggestive of mitochondrial disease.May be associated with mental retardation and delayed development.",
"<br><strong>Test:</strong> Parathyroid hormone levels are low with low serum calcium and 25-hydroxyvitamin D levels.Serum magnesium may be low or elevated.</p>",
"</dd>",
"<dt><a href='#Section2'>Secondary hyperparathyroidism</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have chronic kidney disease with fatigue, anorexia, dyspnoea, and oedema.Patients with vitamin D deficiency may have signs of rickets.",
"<br><strong>Test:</strong> Serum creatinine is elevated with elevated PTH levels produced by decreased calcium and decreased 25-hydroxyvitamin D levels.</p>",
"</dd>",
"<dt><a href='#Section3'>Vitamin D deficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms and signs of rickets: hypotonia, bone pain and tenderness, muscle weakness, bow legs and knob knees, Harrison's groove, pigeon deformity of the chest, and kyphoscoliosis.",
"<br><strong>Test:</strong> Low 25-hydroxyvitamin D levels are diagnostic.</p>",
"</dd>",
"<dt><a href='#Section4'>Fanconi's syndrome</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Causes include sickle cell disease or chemotherapy identified in the history.",
"<br><strong>Test:</strong> High urine calcium excretion without elevation of serum phosphate.Generalised aminoaciduria and glucosuria.The response of urinary cAMP and phosphate to human PTH (hPTH) is normal.</p>",
"</dd>",
"<dt><a href='#Section5'>Fluorosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms of bone pain.",
"<br><strong>Test:</strong> Serum phosphorous is low to normal.Patients have increased bone density.The response of urinary cAMP and phosphate to hPTH is normal.</p>",
"</dd>",
"<dt><a href='#Section6'>Osteopetrosis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Family history of osteopetrosis is present.The infantile form produces growth retardation, failure to thrive, and nasal stuffiness due to malformation of the mastoid and paranasal sinus.Skull deformities can produce cranial nerve entrapment or hydrocephalus.The adult form is milder and may be asymptomatic, or produce increased susceptibility to fractures.Nerve damage produced by bone fractures can cause blindness, facial paralysis, or deafness.",
"<br><strong>Test:</strong> Serum phosphorous is low to normal.Patients have abnormally high bone density.The response of urinary cAMP and phosphate to hPTH is normal.</p>",
"</dd>",
"<dt><a href='#Section7'>Osteosclerosis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> No distinguishing clinical features.",
"<br><strong>Test:</strong> Serum phosphorous is low to normal.Patients have abnormally high bone density.The response of urinary cAMP and phosphate to hPTH is normal.</p>",
"</dd>",
"<dt><a href='#Section8'>Familial brachydactyly</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Isolated abnormalities of the hand.",
"<br><strong>Test:</strong> X-ray reveals shortening of the middle phalanx of all digits.Serum calcium and phosphorous are normal.The response of urinary cAMP and phosphate to hPTH is normal.</p>",
"</dd>",
"<dt><a href='#Section9'>Prader-Willi syndrome</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Patients have poor muscle tone and hyperphagia with a constant feeling of hunger.",
"<br><strong>Test:</strong> Genetic testing identifies the causative mutations on chromosome 15.Serum calcium and phosphate levels are normal.The response of urinary cAMP and phosphate to hPTH is normal.</p>",
"</dd>",
"<dt><a href='#Section10'>Acrodysostosis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Features of the head and face include brachycephaly, a hypoplastic 'pug' nose, maxillary hypoplasia, an open mouth, and epicanthal folds.",
"<br><strong>Test:</strong> Serum calcium and phosphate levels are normal.The response of urinary cAMP and phosphate to hPTH is normal.</p>",
"</dd>",
"<dt><a href='#Section11'>Turner's syndrome</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Diagnostic morphological features include low-set or malrotated ears, down-sloping eyes, ptosis or hooded eyes, and low posterior hairline. A high-arched palate is also seen.",
"<br><strong>Test:</strong> Karyotype reveals 10% or more of the cells with complete or partial loss of a sex chromosome.</p>",
"</dd>",
"</dl>"].join("\n");