content=["<dl>",
"<dt><a href='#Section0'>Pseudopterygium</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Most often hx of previous infective, chemical, thermal, or traumatic injury to the cornea.May occur at multiple locations and is not restricted to the 3 and 9 o'clock (interpalpebral) positions.",
"<br><strong>Test:</strong> Slit-lamp examination: reveals lesion to be adhesion of a fold of conjunctiva, which has occurred as a response to a previous peripheral corneal ulcer/inflammation.Lesion typically only fixed at its apex to the cornea so that a probe may be passed underneath its body at the limbus, while a true pterygium adheres to the underlying cornea throughout its length. Thinning of the underlying cornea may be seen at its head.</p>",
"</dd>",
"<dt><a href='#Section1'>Pingueculum</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Does not encroach on the cornea.",
"<br><strong>Test:</strong> Slit-lamp examination: reveals exact extent and nature of lesion. A pingueculum is limited to limbus and conjunctiva and does not encroach onto the cornea.</p>",
"</dd>",
"<dt><a href='#Section2'>Marginal keratitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Associated with blepharitis. Infiltrate on corneal surface is separated by a clear zone from the limbus. Occur at 2, 4, 8, and 10 o'clock position. Does not have typical pterygium shape. Often superior and inferior.",
"<br><strong>Test:</strong> Corneal swab/scraping: microscopy and culture positive for infecting organism, but infecting organisms are often not detected, as many cases are due to an inflammatory reaction to staphylococcal proteins.</p>",
"</dd>",
"<dt><a href='#Section3'>Corneal micropannus</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hx of trachoma or lack of corneal oxygenation due to excessive contact lens wear.",
"<br><strong>Test:</strong> Slit-lamp examination: reveals encroachment of fine blood vessels onto corneal surface.</p>",
"</dd>",
"<dt><a href='#Section4'>Conjunctival carcinoma in sit</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Rare. Does not have typical pterygium shape. Not restricted to the 3 and 9 o'clock (interpalpebral) positions and can occur at any position on the cornea.",
"<br><strong>Test:</strong> Slit-lamp examination: gelatinous-appearing mass.Biopsy: cytological features of a squamous cell carcinoma, but the basal membrane of the epithelium remains intact.</p>",
"</dd>",
"<dt><a href='#Section5'>Squamous cell carcinoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Rare. Does not have typical pterygium shape. Not restricted to the 3 and 9 o'clock (interpalpebral) positions and can occur at any position on the cornea. May arise from a pterygium, carcinoma in situ, or de novo.",
"<br><strong>Test:</strong> Slit-lamp examination: surface may appear keratinised and friable.Biopsy: well-differentiated squamous cell carcinoma with invasion of the basal membrane.</p>",
"</dd>",
"</dl>"].join("\n");