content=["<dl>",
"<dt><a href='#Section0'>Benign renal cyst</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically asymptomatic.",
"<br><strong>Test:</strong> Bosniak classification on imaging: low score (if questionable, interval change on imaging and/or pathology is distinguishing). [58]</p>",
"</dd>",
"<dt><a href='#Section1'>Ureteric cancer</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Gross haematuria more common.",
"<br><strong>Test:</strong> Ureteroscopy: ureteric mass.</p>",
"</dd>",
"<dt><a href='#Section2'>Bladder cancer</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Gross haematuria more common. Dysuria.",
"<br><strong>Test:</strong> Urine cytology: positive in up to 90% of patients with carcinoma in situ or high-grade tumours; positive in &lt;33% of patients with low-grade transitional cell cancer.</p>",
"</dd>",
"<dt><a href='#Section3'>Upper urinary tract urothelial tumour</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Gross haematuria more common.",
"<br><strong>Test:</strong> Gross pathology: transitional cell carcinoma histology.Cystoscopy: central renal mass (pelvis). [46]MRI: central pelvic /urethral location of mass.</p>",
"</dd>",
"<dt><a href='#Section4'>Angiomyolipoma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable.Often too small to present with palpable masses, and usually asymptomatic. May grow to cause pain and haematuria.",
"<br><strong>Test:</strong> CT/MRI: small (&lt;1 cm); characteristic features (particular fat distribution). If questionable on imaging, and especially if 1-3 cm in size, percutaneous biopsy indicated. [58]</p>",
"</dd>",
"<dt><a href='#Section5'>Oncocytoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Clinically indistinguishable.Typically asymptomatic; often small.",
"<br><strong>Test:</strong> CT/MRI: small (1-3 cm), may have characteristic features (almost always solid, and non-enhancing). If questionable on imaging, percutaneous biopsy may be indicated. [58]</p>",
"</dd>",
"<dt><a href='#Section6'>Secondary metastases</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms consistent with other primary tumours may point towards secondary metastatic renal lesions. Symptoms from local disease burden less likely (the masses are generally smaller but multifocal). [57]",
"<br><strong>Test:</strong> Presence of non-renal malignancy on any diagnostic test with non-enhancing renal masses makes metastases more likely, but if no progression of non-renal primary cancer is documented, there is less chance of renal metastases. [57]  [61]</p>",
"</dd>",
"<dt><a href='#Section7'>Congenital renal parenchymal abnormalities</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Often no distinguishing symptoms or signs.",
"<br><strong>Test:</strong> CT and MRI (especially the latter) can usually help distinguish.</p>",
"</dd>",
"<dt><a href='#Section8'>Renal infarction</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Clinical history of vascular risk factors may raise suspicion of infarction (especially poorly controlled hypertension/hypertensive crisis).",
"<br><strong>Test:</strong> MRI: assesses kidney and determines likelihood of infarction.Magnetic resonance angiogram (MRA): assesses local vessels.</p>",
"</dd>",
"<dt><a href='#Section9'>Renal infection</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Clinical history of fever or sepsis.",
"<br><strong>Test:</strong> FBC: leukocytosis.Blood culture: bacteraemia. Urine culture: bacteriuria.Serial imaging (CT/MRI) may be needed to ensure resolution of renal mass after treatment for infection.</p>",
"</dd>",
"</dl>"].join("\n");