content=["<dl>",
"<dt><a href='#Section0'>Human metapneumovirus</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Produces a clinical syndrome that closely mimics respiratory syncytial virus (RSV). May be indistinguishable by clinical findings. [66]",
"<br><strong>Test:</strong> Viral cultures and polymerase chain reaction (PCR) have been developed but are not yet widely available.</p>",
"</dd>",
"<dt><a href='#Section1'>Influenza virus</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Accounts for 1% to 24% of bronchiolitis. [65]  [67]  [68]  Closely mimics RSV in presentation. Fever frequently &gt;38.9&deg;C (&gt;101.9&deg;F). Coryza frequently present. Greater frequency of pneumonia than with RSV.",
"<br><strong>Test:</strong> Chest x-ray (CXR) may show infiltrates.Rapid testing by immunoassay or viral neuraminidase detection: positive for influenza virus.Enzyme-linked immunosorbent assay (ELISA): positive for influenza virus.</p>",
"</dd>",
"<dt><a href='#Section2'>Parainfluenza virus</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Accounts for 10% to 30% of bronchiolitis. Parainfluenza type 3 closely mimics RSV in presentation. Presence of coryza is associated with parainfluenza infection.",
"<br><strong>Test:</strong> ELISA and PCR testing: positive for parainfluenza virus.Viral culture: positive for parainfluenza virus (standard test).</p>",
"</dd>",
"<dt><a href='#Section3'>Bacterial pneumonia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Bacterial infections are not associated with wheeze and generally cause higher fevers than RSV. [57]Fever &gt;40&deg;C (&gt;103.9&deg;F).",
"<br><strong>Test:</strong> CXR: infiltrateWhite blood cell count: elevated with left shift suggests an active bacterial process.</p>",
"</dd>",
"</dl>"].join("\n");