content=["<dl>",
"<dt><a href='#Section0'>Ischaemic optic neuropathy</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Ischaemic optic neuropathy is infrequently associated with intra-retinal haemorrhages and retinal thickening.",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section1'>Retinal detachment (RD)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually report photopsias and/or floaters.Examination demonstrates an RD.",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section2'>Choroidal neovascularisation (CNV)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Examination demonstrates sub-retinal or sub-retinal pigment epithelium haemorrhage in addition to signs of diseases associated with CNV (e.g., age-related macular degeneration, pathological myopia, ocular histoplasmosis).Intra-retinal and vitreous haemorrhages are infrequently related to CNV.",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section3'>Central retinal artery occlusion</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Venous pathology, intra-retinal haemorrhages, and macular oedema infrequently seen on examination.Affected retina is whitened.Cilioretinal artery sparing and/or foveal sparing may be seen.",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section4'>Branch retinal artery occlusion</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Venous pathology, intra-retinal haemorrhages, and macular oedema infrequently seen on examination.Affected region of retina is whitened.",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section5'>Ophthalmic artery occlusion</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Venous pathology, intra-retinal haemorrhages, and macular oedema infrequently seen on examination.Entire retina is whitened.",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section6'>Cerebral vascular accident</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Infrequently associated with any posterior segment findings.Usually associated with other neurological signs (e.g., extremity numbness or weakness, slurred speech, confusion).",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section7'>Optic neuritis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Frequently associated with pain and infrequently associated with retinal haemorrhages and thickening that are restricted to a single quadrant.",
"<br><strong>Test:</strong> Clinical diagnosis; no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section8'>Diabetic retinopathy</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Examination demonstrates micro-aneurysms, haemorrhages, and neovascularisation that occur on both sides of the horizontal raphe in the absence of collateral vessels.Cotton-wool spots and nerve fibre layer haemorrhages are less frequent in diabetic retinopathy than in RVO.",
"<br><strong>Test:</strong> Fluorescein angiogram less likely to show leakage from the optic nerve head. Areas of non-perfusion are multi-focal and not limited to a single quadrant as in RVO.</p>",
"</dd>",
"<dt><a href='#Section9'>Ocular ischaemic syndrome</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Carotid occlusive disease may be present in patient's medical history. Retinal haemorrhages and neovascularisation tend to be in the mid-periphery.Ocular ischaemic syndrome usually either unilateral or, at least, significantly asymmetrical.",
"<br><strong>Test:</strong> Fluorescein angiogram demonstrates delayed choroidal filling. Delayed venous filling, if present, is not limited to a single quadrant.</p>",
"</dd>",
"<dt><a href='#Section10'>Radiation retinopathy</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> History of radiotherapy to head, orbits, or globes.Examination demonstrates micro-aneurysms, haemorrhages, and neovascularisation that occur on both sides of the horizontal raphe in the absence of collateral vessels.",
"<br><strong>Test:</strong> Fluorescein angiogram does not demonstrate delayed venous filling.</p>",
"</dd>",
"<dt><a href='#Section11'>Sickle cell retinopathy</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> History of sickle cell or sickle thalassaemia disease.Areas of neovascularisation tend to be peripheral, 'sea-fan' shaped, and self-limited.",
"<br><strong>Test:</strong> Fluorescein angiogram does not demonstrate delayed venous filling.</p>",
"</dd>",
"<dt><a href='#Section12'>Hypertensive retinopathy</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Attenuated arterioles, arteriovenous crossing changes seen throughout the fundus, but not necessarily associated with increased venous tortuosity, dilation, and retinal thickening.",
"<br><strong>Test:</strong> Fluorescein angiogram does not demonstrate delayed venous filling.</p>",
"</dd>",
"</dl>"].join("\n");