content=["<dl>",
"<dt><a href='#Section0'>Head injury</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> No specific clinical differentiating features.Hx of head injury is frequently obtained, but can be unavailable in someone who is found unresponsive.",
"<br><strong>Test:</strong> CT and MRI will reveal various intracranial bleeds that are associated with head injury; concussions have normal imaging findings; diffuse axonal damage can be seen as signal abnormality in MRI images.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute bacterial meningitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Persistent irritability and lethargy, prolonged postictal obtunded consciousness, skin rash, bulging fontanel, and nuchal rigidity.",
"<br><strong>Test:</strong> Typical CSF abnormalities are pleocytosis, elevated protein, low glucose level, and positive culture.</p>",
"</dd>",
"<dt><a href='#Section2'>Viral meningitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Fever, headache, and neck stiffness are common. Nausea, vomiting, and photophobia can also occur.",
"<br><strong>Test:</strong> CSF lymphocytic pleocytosis.Glucose is normal or high.Gram stain and bacterial culture are negative; viral culture and PCR may be positive.</p>",
"</dd>",
"<dt><a href='#Section3'>Viral encephalitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Prodromal upper respiratory symptoms with fever and malaise, followed by headache, stiff neck, and seizure.Skin rash also common.",
"<br><strong>Test:</strong> LP may show pleocytosis and increased protein but is sometimes normal.Culture is negative for bacteria.Results of viral studies are positive (i.e., HSV, varicella).</p>",
"</dd>",
"<dt><a href='#Section4'>Ingestion of toxic substances</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Hx of ingestion of ethanol, methanol, ethylene glycol (constituent of automobile antifreeze), or propylene glycol (diluent in many intravenous medications such as lorazepam) is present.",
"<br><strong>Test:</strong> Serum toxicology screen will identify the ingested substance.</p>",
"</dd>",
"<dt><a href='#Section5'>Paracetamol overdose</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Hx of chronic paracetamol ingestion or paracetamol overdose is present.Clinical signs include confusion, tinnitus, hyperventilation, and pulmonary oedema.",
"<br><strong>Test:</strong> Urine and serum paracetamol levels will be positive, but not necessarily in the toxic range.</p>",
"</dd>",
"<dt><a href='#Section6'>Salicylate poisoning</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Hx of chronic salicylate ingestion or salicylate overdose is present.",
"<br><strong>Test:</strong> Serum salicylate levels will be elevated.</p>",
"</dd>",
"<dt><a href='#Section7'>Diabetic ketoacidosis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually have a hx of preexisting diabetes.May present with polyuria and polydipsia.",
"<br><strong>Test:</strong> Plasma glucose 13.9 mmol/L (&gt;250 mg/dL).Venous pH &lt;7.3.HCO3 &lt;15 mmol/L; anion gap &gt;12.Presence of serum ketones or betahydroxybutyrate.</p>",
"</dd>",
"<dt><a href='#Section8'>Urea cycle disorders</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Hx or FHx of metabolic defect.Typically present with recurrent hypoglycaemia.",
"<br><strong>Test:</strong> Enzyme assay or mutation analysis will be positive for a urea cycle disorder.</p>",
"</dd>",
"<dt><a href='#Section9'>Type 1 glycogen storage disease</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Hx or FHx of metabolic defect.Typically present with recurrent hypoglycaemia.May show evidence of growth retardation, with hepatomegaly and protuberant abdomen.",
"<br><strong>Test:</strong> Mutation analysis will be positive for GSD I mutations.</p>",
"</dd>",
"<dt><a href='#Section10'>Primary carnitine deficiency</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Hx or FHx of metabolic defect.Typically present with recurrent hypoglycaemia.",
"<br><strong>Test:</strong> Enzyme assay will be positive for a carnitine deficiency.</p>",
"</dd>",
"<dt><a href='#Section11'>Fatty acid oxidation disorders</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Hx or FHx of metabolic defect.Hx or FHx of recurrent hypoglycaemic episodes.Frequently presents with lethargy/coma, hepatosplenomegaly. May also present with vomiting, feeding difficulties, cardiomegaly, developmental delay, seizures, ataxia. [13]",
"<br><strong>Test:</strong> Plasma and urine analysis of carnitine and acyl-carnitine levels reveals disorder.Additional plasma and fibroblast studies ordered through genetics consultation.</p>",
"</dd>",
"</dl>"].join("\n");