content=["<dl>",
"<dt><a href='#Section0'>Psoriatic arthritis (PsA)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Commonly involves small joints of the hands and feet but is less often symmetric. Fewer than 5 joints are commonly affected (oligoarthritis). Unlike RA, the distal interphalangeal (DIP) joints may be involved in psoriatic arthritis.Psoriasis is present in &gt;90% of PsA patients and it is unusual in RA patients.",
"<br><strong>Test:</strong> PsA is for the most part seronegative, even though there are patients with low levels of rheumatoid factor (RF) diagnosed with PsA because of presence of psoriasis.Skin biopsy of suspicious lesions can show psoriasis, supporting the diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Infectious arthritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Mostly in the form of reactive arthritis, symmetric hand and feet arthritis can be seen after viral/bacterial infections.",
"<br><strong>Test:</strong> Most resolve within 6 weeks and leave no long-term effects.</p>",
"</dd>",
"<dt><a href='#Section2'>Gout</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Small percentage of gout patients present with polyarticular gout, and can mimic RA. Tophi and high levels of uric acid are specific for gout and very rare in RA. In addition, erosions seen in gout where the tophi have eroded into the bone are different from the erosions seen in RA.",
"<br><strong>Test:</strong> Serum uric acid &gt;416 micromols/L (&gt;7 mg/dL), urate crystals from the joint aspirate or tophus. Tophus eroding into the joint in gout is more destructive and much larger; RA erosions are more limited to cartilage-bone interface and tend to be smaller.</p>",
"</dd>",
"<dt><a href='#Section3'>Systemic lupus erythematosus</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> SLE can have polyarthritis in the small joints of the hands and feet as a presenting manifestation. The main difference is that SLE arthritis is usually non-deforming.",
"<br><strong>Test:</strong> A wide range of autoantibodies seen in SLE help differentiate the two conditions. High antinuclear antibody (ANA) titre, anti-extractable nuclear antigen (ENA) autoantibodies are seen rarely in RA.On radiographs, erosions are not typically seen in the joints of SLE patients.</p>",
"</dd>",
"<dt><a href='#Section4'>Osteoarthritis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Prevalence increases with age. The most commonly affected joints are the knee, hip, hands, and lumbar and cervical spine. Patients present with joint pain and stiffness that is typically worse with activity.",
"<br><strong>Test:</strong> Radiographs show loss of joint space, subchondral sclerosis, and osteophytes.</p>",
"</dd>",
"</dl>"].join("\n");