content=["<dl>",
"<dt><a href='#Section0'>Measles</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically accompanied by a prodrome of cough, coryza and conjunctivitis and an enanthem consisting of grey-white papules on the buccal mucosa (Koplik spots).The exanthem is an erythematous maculopapular eruption that spreads cephalocaudally and usually begins to clear within 1 week. [11]",
"<br><strong>Test:</strong> Diagnosis is usually clinical, based on physical examination and history.Virus isolation can be obtained from a nasopharyngeal swab using a serological assay for measles-specific antibodies. [11]</p>",
"</dd>",
"<dt><a href='#Section1'>Enterovirus</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> The exanthem associated with enterovirus (especially echovirus) is a non-specific, maculopapular, erythematous eruption.Enterovirus often presents as aseptic meningitis.Other enteroviruses may present with herpangina or vesicular lesions.Primary differentiation is made based on history, but can be difficult. [12]",
"<br><strong>Test:</strong> PCR or rising serological titres may be used for enterovirus identification in serious cases.In many uncomplicated cases, history and physical examination are sufficient. [12]</p>",
"</dd>",
"<dt><a href='#Section2'>EBV</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> The exanthem is a non-specific, maculopapular, erythematous eruption.The primary differentiation is made based on history.The eruption of EBV often presents after administration of ampicillin or other antibiotic therapy. [13]",
"<br><strong>Test:</strong> Acute EBV is usually diagnosed with a positive heterophile test (Monospot).Atypical lymphocytes are common on examination of a peripheral smear.EBV-specific antibodies are used in patients with a negative Monospot or in cases with atypical symptoms. [13]</p>",
"</dd>",
"<dt><a href='#Section3'>Rubella</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Presents with a non-specific exanthem of rose-pink macules that spread cephalocaudally.Joint involvement is common, as is tender cervical, occipital and/or posterior auricular lymphadenopathy. [11]",
"<br><strong>Test:</strong> Serology will detect antirubella IgM or a 4-fold increase in antirubella IgG antibodies. [11]</p>",
"</dd>",
"<dt><a href='#Section4'>Meningococcaemia</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Seizures, fever and signs of encephalopathy can mimic meningococcaemia.Usually associated with a rapidly progressing purpuric eruption and meningeal signs.",
"<br><strong>Test:</strong> Cultures of CSF and blood yield meningococcus.</p>",
"</dd>",
"</dl>"].join("\n");