content=["<dl>",
"<dt><a href='#Section0'>Dubin-Johnson syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Clinically similar, no differentiating symptoms or signs.",
"<br><strong>Test:</strong> Liver pigmentation present. In Rotor's syndrome (RS), the liver has a normal appearance.Failure to visualise the gall bladder on oral cholecystography. [4]Total urinary coproporphyrin excretion is either normal or moderately increased, but &gt;80% is excreted as coproporphyrin I. [4]  [8]  In RS, the proportion is much lower at approximately 65%.</p>",
"</dd>",
"<dt><a href='#Section1'>Gilbert's syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Most common in males. [13]",
"<br><strong>Test:</strong> Presence of unconjugated hyperbilirubinaemia in serum and urine. [13]</p>",
"</dd>",
"<dt><a href='#Section2'>Crigler-Najjar syndrome (type I and II)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Diagnosed usually during the neonatal period.More intense jaundice.",
"<br><strong>Test:</strong> Presence of unconjugated hyperbilirubinaemia in serum and urine. [13]</p>",
"</dd>",
"<dt><a href='#Section3'>Extra-hepatic biliary obstruction</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Pruritus.Acholic stools.",
"<br><strong>Test:</strong> Elevated alkaline phosphatase.Elevated gamma-GT.</p>",
"</dd>",
"<dt><a href='#Section4'>Familial intra-hepatic cholestasis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Pruritus.Age usually &lt;1 year.",
"<br><strong>Test:</strong> Elevated bile acids.Abnormal LFTs.</p>",
"</dd>",
"<dt><a href='#Section5'>Benign recurrent intra-hepatic cholestasis (BRIC)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Recurrent attacks of cholestasis lasting several days to months.Each episode preceded by intense pruritus and malaise, lassitude, and sometimes diarrhoea.Pale stools during the episode.Weight loss due to steatorrhoea.",
"<br><strong>Test:</strong> LFTs during an episode reflect cholestasis with elevated serum bile acids and alkaline phosphatase.Biopsy specimens during an attack show bile plugs within the ducts.Between attacks liver histology is normal apart from mild portal zone fibrosis. [16]</p>",
"</dd>",
"<dt><a href='#Section6'>Drug-induced hepatotoxicity</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> History of exposure to a known hepatotoxic agent or drug causing cholestasis (e.g., isoniazid, halothane, alpha-methyl dopa, erythromycin, chlorpromazine, oestrogens/oral contraceptives, ciclosporin, haloperidol).",
"<br><strong>Test:</strong> Abnormal LFTs.</p>",
"</dd>",
"</dl>"].join("\n");