content=["<dl>",
"<dt><a href='#Section0'>Measles (rubeola)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Measles is a more severe illness. Erythematous or brownish morbilliform rash spreads from the head and neck downwards and persists for 3 to 7 days. Coryza, cough, and conjunctivitis are usual.A pathognomonic enanthem (Koplik's spots) occurs early in the disease. View imageView image Complications are common, particularly in immunocompromised and malnourished people.",
"<br><strong>Test:</strong> Positive serum measles anti-IgM antibody is the preferred test (sensitivity 83% to 89%, specificity 87% to 100%). [18]  [19]Significant rise in serum measles anti-IgG antibody in paired acute and convalescent specimens.Isolation of measles virus from throat, nasopharynx, blood, or urine (usually processed by public health and reference laboratories only).</p>",
"</dd>",
"<dt><a href='#Section1'>Roseola infantum (HHV-6, HHV-7, exanthem subitum, sixth disease)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Typically affects children &lt;2 years of age. [20]  Coryza, conjunctivitis, and cervical or occipital lymphadenopathy may precede 3 to 7 days of high fever and irritability. Development of an erythematous or pinkish maculopapular rash coincides with the resolution of fever and persists for hours to several days. Febrile seizures occur in 10% to 15%.",
"<br><strong>Test:</strong> Anti-IgG antibody seroconversion between paired acute and convalescent specimens is the preferred test. [21]  Increases in serum-specific antibody occur with viral reactivation. Specific serum IgM testing is not reliable. HHV-6 and HHV-7 are serologically cross-reactive.Positive HHV-6/HHV-7 nucleic acid amplification from serum or plasma (sensitivity 90% to 100%, specificity 100%). Cannot distinguish acute infection from reactivation. [22]Isolation of virus from peripheral blood (usually processed by public health and reference laboratories only).</p>",
"</dd>",
"<dt><a href='#Section2'>Scarlet fever (group A Streptococcus pyogenes)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Most common in school-age children. Usually associated with streptococcal pharyngitis, but occasionally complicates skin and soft-tissue infection.Pharyngitis, anterior cervical adenopathy, and fever precede a confluent erythematous blanching 'sandpaper' rash that begins on the trunk and behind the ears and is accentuated in flexural creases. Rash resolves with desquamation in 3 to 8 days.Other features include an erythematous-coated 'strawberry' tongue, circumoral pallor, and Pastia's lines (linear erythematous lesions in skinfolds, particularly elbows and axillae). View image",
"<br><strong>Test:</strong> Group A streptococcal rapid antigen testing is 60% to 85% sensitive and 90% to 100% specific. [23]  Negative results should be confirmed by throat culture.Isolation of group A streptococcus from throat culture on blood agar is 80% to 98% sensitive and 100% specific.</p>",
"</dd>",
"<dt><a href='#Section3'>Erythema infectiosum (parvovirus B19, fifth disease)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Most common in children. Mild systemic symptoms and/or fever are followed in 7 to 10 days by a distinctive erythematous facial rash with a 'slapped cheek' appearance.An erythematous lacy maculopapular rash may also appear on the trunk and spread peripherally to the arms and thighs. Occasionally the rash may be atypical and indistinguishable from that of rubella. Arthralgias and arthritis are more common with increasing age. View image",
"<br><strong>Test:</strong> Positive serum antiparvovirus B19 IgM is the preferred test in immunocompetent people (90% sensitive, 99% specific). [24]Nucleic acid amplification of parvovirus B19 DNA from serum or plasma is more sensitive, but may remain positive for up to 9 months after acute infection. [25]</p>",
"</dd>",
"<dt><a href='#Section4'>Enteroviral infections (echovirus, coxsackievirus)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Incidence is highest in infants and young children and in the summer and early autumn. Most common presentation is a non-specific febrile illness. Neurological and GI symptoms and stomatitis may be prominent.",
"<br><strong>Test:</strong> Nucleic acid amplification of enteroviral RNA from blood or CSF is the most rapid and sensitive test. [26]Isolation of enterovirus from stool, rectal swabs, throat, blood, CSF, or urine.Sensitivity and specificity vary, depending on the type of virus, site of infection, and time at which specimens are obtained.</p>",
"</dd>",
"<dt><a href='#Section5'>West Nile virus</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Incidence highest in summer, coinciding with mosquito activity. Fever is generally higher than that observed with rubella, and headache, myalgias, and weakness are more prominent.A diffuse erythematous maculopapular or morbilliform rash, which spares the palms and soles, is more common in children than adults. Neuro-invasive disease occurs in 0.3% to 1.0% of patients.",
"<br><strong>Test:</strong> Specific IgM by antibody capture ELISA is &gt;95% sensitive and 83% to 99% specific after the first week of illness, but may persist for &gt;1 year. [27]Fourfold increase in virus-specific serum antibody titres. Cross-reactivity with other arboviruses may occur. Positive results should be confirmed by virus-specific IgG.Isolation of virus from CSF or serum.Virus-specific IgM in CSF or amplification of viral nucleic acid from CSF (neuro-invasive disease).</p>",
"</dd>",
"<dt><a href='#Section6'>Secondary syphilis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> A generalised polymorphous maculopapular rash begins on the trunk and typically involves the palms and soles. Other common manifestations include condyloma lata, mucosal lesions, and generalised lymphadenopathy.Fever and other constitutional symptoms are not prominent. Clinical manifestations resolve spontaneously or with treatment over several weeks to months. View image",
"<br><strong>Test:</strong> Positive VDRL, RPR tests are 100% sensitive and 93% to 99% specific. [28]Results should be confirmed by a specific treponemal test (FTA-ABS, 100% sensitive and 94% to 100% specific).Identification of spirochaetes by dark-field examination of scrapings from moist mucocutaneous lesions.</p>",
"</dd>",
"<dt><a href='#Section7'>Infectious mononucleosis (Epstein-Barr virus)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> High fever, exudative pharyngitis, cervical or generalised lymphadenopathy, hepatosplenomegaly, and an atypical lymphocytosis are common in adolescents and adults.Periorbital oedema is frequently observed early in infection. Children are more likely to be asymptomatic or have a mild form of illness. A polymorphous rash, usually on the trunk and arms, occurs in up to 20% of cases. Rash is more common in patients treated with ampicillin and other penicillins. Sometimes conjunctival haemorrhage may be seen. View imageView image",
"<br><strong>Test:</strong> Positive antiviral capsid antigen (VCA) IgM antibodies are detectable in the second week of illness and disappear over several months. Anti-VCA IgG antibody is also detectable early in infection and persists for life, whereas anti-EBV-associated nuclear antigen (EBNA) antibody develops weeks to months after infection. The presence of anti-VCA Ab and absence of anti-EBNA Ab are diagnostic of acute infection (sensitivity 95% to 100%, specificity 86% to 100%). [29]Heterophile antibody testing (monospot) is sensitive (81% to 95%) and specific (98% to 100%) in school-age children and adults, but is insensitive in young children.</p>",
"</dd>",
"<dt><a href='#Section8'>Kawasaki's syndrome</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Occurs almost exclusively in children &lt;8 years of age. Prominent features are a persistent high fever, bulbar conjunctivitis, erythematous changes of the mouth and pharynx, and dry, cracked lips, swelling and pain of the hands and feet, and cervical lymphadenopathy.Irritability, abdominal pain, diarrhoea, and vomiting are common. Peri-ungual desquamation may be noted in the second week of the illness. Coronary and other arterial aneurysms may develop 1 to 4 weeks after the onset of illness.",
"<br><strong>Test:</strong> No specific diagnostic test is available.Suggestive laboratory and diagnostic imaging findings include sterile pyuria, hepatitis, CSF pleocytosis, pericardial effusion, gall bladder hydrops, and coronary artery abnormalities.</p>",
"</dd>",
"<dt><a href='#Section9'>Cutaneous drug reactions</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Medications commonly associated with cutaneous reactions include antibiotics and anticonvulsants. Many drug-induced rashes have characteristic features (erythema multiforme, urticaria). View image",
"<br><strong>Test:</strong> Clinical diagnosis based on exposure history, resolution after withdrawal of the implicated drug, and exclusion of other potential causes. Eosinophilia is suggestive, but not diagnostic, of cutaneous drug reactions.</p>",
"</dd>",
"<dt><a href='#Section10'>Juvenile rheumatoid arthritis</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Systemic-onset juvenile rheumatoid arthritis commonly affects children and adolescents. Children are often ill-looking. Typically there are daily high-spiking fevers that, in the absence of therapy, persist for weeks to months.The rash is evanescent, salmon-coloured, and linear and typically involves the trunk and extremities. The presence of the rash often coincides with fever. Mild hepatosplenomegaly and myalgias (or muscle tenderness) are common. Serositis may occur.Many patients develop a chronic synovitis of &ge;1 joints, but the onset of joint involvement may be delayed.",
"<br><strong>Test:</strong> There is no definitive laboratory test. Leukocytosis, thrombocytosis, anaemia, elevated ESR, and elevated serum ferritin concentrations are suggestive.</p>",
"</dd>",
"</dl>"].join("\n");