content=["<dl>",
"<dt><a href='#Section0'>Diabetic ketoacidosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Hx of diabetes associated with sub-optimal insulin therapy. Recent or current acute medical illness may be the precipitating factor.Common symptoms include abdominal pain associated with polyuria, polyphagia, and polydipsia.",
"<br><strong>Test:</strong> Blood glucose &gt;13.9 mmol/L (&gt;250 mg/dL) with presence of acidosis and ketonaemia.</p>",
"</dd>",
"<dt><a href='#Section1'>Dementia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> More common among the older population. May be FHx of Alzheimer's dementia or personal hx of cerebrovascular accident.Cognitive decline usually more gradual.",
"<br><strong>Test:</strong> Head CT or MRI scan shows hippocampal volume loss in cases of Alzheimer's, vascular, and Lewy body dementia; slowing of background rhythm on EEG is common finding of Alzheimer's and Lewy body dementia.</p>",
"</dd>",
"<dt><a href='#Section2'>Paracetamol overdose</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Hx of repeated non-prescription analgesic use for pain relief may be present.Acute paracetamol overdose produces few clinically useful findings on physical examination, particularly during the first 12 hours.Poisoning may cause various degrees of liver injury, including fulminant hepatic failure and hepatorenal syndrome. Initial coma and severe metabolic acidosis are rare.",
"<br><strong>Test:</strong> Serum paracetamol concentration may be positive.</p>",
"</dd>",
"<dt><a href='#Section3'>Toxic alcohol ingestion (ethanol, ethylene glycol, methanol, or isopropyl alcohol)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hx of chronic alcohol consumption may suggest ethanol toxicity. Hepatomegaly and signs of chronic liver disease may be present (spider nevi, leukonychia, palmar erythema, bruising, jaundice, scratch marks).Hx of automobile anti-freeze or brake fluid ingestion in a confused patient with signs of metabolic acidosis (e.g., Kussmaul's respirations) suggests ethylene glycol poisoning.Methanol toxicity is suggested by blindness or diminished visual acuity and optic neuritis on funduscopic examination. In addition, seizures can occur and signs of metabolic acidosis may be present (e.g., Kussmaul's respirations).Gait disturbances, dizziness, and confusion are common features of isopropyl alcohol ingestion. Hypothermia and hypotension may result from ingestion of large doses. [16]",
"<br><strong>Test:</strong> Serum toxicology screen (ethanol, methanol, ethylene glycol, isopropyl alcohol): positive; presence of osmolar gap, and an anion gap; [17]  elevated serum lactate.</p>",
"</dd>",
"<dt><a href='#Section4'>Lactic acidosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Hx of possible underlying cause: tissue hypoperfusion, diabetes, medication (e.g., metformin, paraldehyde), genetic defects (e.g., MELAS syndrome: mitochondrial encephalopathy, lactic acidosis, and stroke-like episodes).May have physical findings relating to underlying cause.",
"<br><strong>Test:</strong> Wide anion-gap metabolic acidosis together with elevated serum lactate level confirms diagnosis.</p>",
"</dd>",
"<dt><a href='#Section5'>Iron toxicity</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Hx of anaemia may be present (exposure to iron tablets and/or repeated blood transfusions pose risk of toxicity).GI effects are common and include nausea, vomiting, diarrhoea, and abdominal pain.",
"<br><strong>Test:</strong> Elevated serum iron level.</p>",
"</dd>",
"</dl>"].join("\n");