content=["<dl>",
"<dt><a href='#Section0'>Osteoarthritis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Known history of osteoarthritis.Many joints symptomatic to a similar degree.",
"<br><strong>Test:</strong> Synovial fluid aspirate will not reveal micro-organisms.</p>",
"</dd>",
"<dt><a href='#Section1'>Psoriatic arthritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Known history of inflammatory arthritis and psoriasis or family history of psoriasis.Many joints symptomatic to a similar degree.",
"<br><strong>Test:</strong> Synovial fluid aspirate will not reveal micro-organisms.</p>",
"</dd>",
"<dt><a href='#Section2'>Rheumatoid arthritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Known history of rheumatoid arthritis.Many joints symptomatic to a similar degree.",
"<br><strong>Test:</strong> Synovial fluid aspirate will not reveal micro-organisms.</p>",
"</dd>",
"<dt><a href='#Section3'>Gout</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Known history.",
"<br><strong>Test:</strong> Synovial fluid polarising microscopy will reveal urate crystals.</p>",
"</dd>",
"<dt><a href='#Section4'>Pseudogout</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Known history.",
"<br><strong>Test:</strong> Synovial fluid polarising microscopy will reveal pyrophosphate crystals.</p>",
"</dd>",
"<dt><a href='#Section5'>Haemarthrosis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Known history of a bleeding diathesis.",
"<br><strong>Test:</strong> Joint aspiration will reveal blood.</p>",
"</dd>",
"<dt><a href='#Section6'>Trauma</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> History of trauma to the affected joint.",
"<br><strong>Test:</strong> Joint aspiration may reveal blood.</p>",
"</dd>",
"<dt><a href='#Section7'>Bursitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Examination will reveal that the swelling is external to the joint. The joint itself will move freely and painlessly.",
"<br><strong>Test:</strong> If the joint is aspirated no fluid will be obtained.</p>",
"</dd>",
"<dt><a href='#Section8'>Cellulitis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Examination will reveal erythematous skin overlying the joint. The joint itself will be unrestricted.",
"<br><strong>Test:</strong> If the joint is aspirated no fluid will be obtained.</p>",
"</dd>",
"<dt><a href='#Section9'>Tuberculosis, extrapulmonary</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> There may be a history of immunocompromise, origin from an endemic area, or insidious onset of symptoms.",
"<br><strong>Test:</strong> Synovial biopsy may show positive mycobacterial smears or cultures.</p>",
"</dd>",
"<dt><a href='#Section10'>Lyme disease</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> There may be a history of erythema migrans or tick bite.",
"<br><strong>Test:</strong> Lyme titre may be positive.</p>",
"</dd>",
"</dl>"].join("\n");