content=["<dl>",
"<dt><a href='#Section0'>DiGeorge syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Abnormal development of the 3rd and 4th pharyngeal pouch, which includes the thymus.Spectrum of immune dysregulation varies, although a severe form results in severe T-cell lymphopenia.Associated defects commonly include palatal abnormalities, distinct facies, hypothyroidism, hypoparathyroidism, and cardiac defects. [11]",
"<br><strong>Test:</strong> Confirmation requires deletion of 22Q11.2 by fluorescence in situ hybridisation (FISH) or DNA microarray on genetic testing. [17]</p>",
"</dd>",
"<dt><a href='#Section1'>Omenn's syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Considered a form of SCID. [11]Symptoms include eosinophilia, rash, and enlarged spleen and lymph nodes.",
"<br><strong>Test:</strong> Flow cytometry will usually demonstrate increased CD4+CD45RO+ T cells (memory T cells) and markedly decreased CD4+CD45RA+ T cells (naive T cells).Molecular diagnosis requires identifying mutations in genes associated with this disorder such as hypomorphic mutations in recombination activating genes (RAG1 and RAG2), Artemis, and other genes.</p>",
"</dd>",
"<dt><a href='#Section2'>Bare lymphocyte syndrome (BLS)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms include sinopulmonary infections and granulomatous skin lesions.",
"<br><strong>Test:</strong> Flow cytometry shows decreases in the number of CD4+ T cells, CD8 T cells, and a lack of major histocompatibility complex (MHC)-I or MHC-II expression. [11]</p>",
"</dd>",
"<dt><a href='#Section3'>Zeta chain-associated protein (ZAP) 70 deficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Autosomal-recessive condition characterised by a lack of CD8+ T cells. Patients have normal numbers of CD4+ T cells, although they often have defects in function due to the role of ZAP 70 in TCR signalling. [11]Considered a subset of SCID.Some patients have been described with palpable lymphadenopathy and normal thymic shadow. [11]",
"<br><strong>Test:</strong> Flow cytometry shows decreased CD8+ T cells with normal B cells and normal NK cells.Confirmation of this diagnosis requires DNA sequence analysis of ZAP 70 gene.</p>",
"</dd>",
"<dt><a href='#Section4'>NF-kappa-B essential modulator (NEMO)</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Also called hypohidrotic ectodermal dysplasia with immune deficiency.Characterised by deficiencies in T-cell proliferation and abnormalities in NK cell cytotoxicity. [18]Symptoms include abnormal development of hair, teeth, and sweat glands.Patients are susceptible to mycobacterial and streptococcal infections.",
"<br><strong>Test:</strong> Diagnosis is confirmed by mutation analysis. The underlying genetic defect is in the NEMO (I-kappa kappa gamma), which is involved in the activation of NF-kappa B. [11]</p>",
"</dd>",
"<dt><a href='#Section5'>Hyper IgM syndrome (HIGM syndrome)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Presents in an identical manner to SCID.",
"<br><strong>Test:</strong> Flow cytometry may show normal T-cell numbers.Serum IgM may be normal or elevated with reductions in IgG and IgA.Diagnosis confirmed with genetic studies, which show mutation in either CD40 or CD40 ligand (CD40L).</p>",
"</dd>",
"<dt><a href='#Section6'>HIV-1</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Maternal history of HIV-1 infection.Presents in an identical manner to SCID.",
"<br><strong>Test:</strong> HIV PCR confirms diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");