content=["<dl>",
"<dt><a href='#Section0'>Active Crohn's disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Can be distinguished from short gut syndrome (SGS) by the presence of signs such as rash or joint pains.The distinction is important as active Crohn's disease is treated very differently from SGS.",
"<br><strong>Test:</strong> Endoscopy shows mucosal inflammation and ulceration, typical findings of active Crohn's disease.C-reactive protein and ESR may be elevated but are not specific.</p>",
"</dd>",
"<dt><a href='#Section1'>Coeliac disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Dermatitis herpetiformis is a characteristic rash that, when present, is almost always associated with coeliac disease.Symptoms of coeliac disease recede when patients are placed on a gluten-free diet.",
"<br><strong>Test:</strong> Immunoglobulin A-tissue transglutaminase shows elevated titres in coeliac disease.Small bowel biopsy is diagnostic and shows characteristic intra-epithelial lymphocytes, villous atrophy and crypt hyperplasia.</p>",
"</dd>",
"<dt><a href='#Section2'>Small bowel malignancy</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> No differentiating signs or symptoms. Patients with Crohn's disease are at risk for GI malignancy, which can present with similar symptoms of diarrhoea, weight loss, and fatigue.",
"<br><strong>Test:</strong> CT enterography or endoscopy is likely to reveal a small bowel tumour.</p>",
"</dd>",
"<dt><a href='#Section3'>Bacterial over-growth</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> No clear differentiating signs or symptoms. Patients with bacterial over-growth often have symptoms of diarrhoea, weight loss, and malabsorption similar to SGS. More common in patients without an ileocaecal valve. Bacterial over-growth in the context of SBS has been poorly studied.",
"<br><strong>Test:</strong> An empiric trial of antibiotics as a diagnostic test is commonly performed. [18]A positive hydrogen breath test is indicative of bacterial over-growth. [18]</p>",
"</dd>",
"<dt><a href='#Section4'>Anorexia nervosa</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Weight loss and malnutrition can be a consequence of a lack of appropriate food intake. A careful dietary history is required to eliminate this possibility.Anorexia nervosa can be distinguished by a history of psychiatric illness, a predominance of nausea, loss of appetite, or night-time diarrhoea.",
"<br><strong>Test:</strong> Stool laxative testing to identify laxative abuse.Direct observation of oral intake.</p>",
"</dd>",
"</dl>"].join("\n");