content=["<dl>",
"<dt><a href='#Section0'>Hip fractures</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> History of significant trauma.",
"<br><strong>Test:</strong> X-ray shows increased soft tissue shadow and displacement of the epiphysis in any direction.</p>",
"</dd>",
"<dt><a href='#Section1'>Avascular necrosis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Age of onset typically seen at 30 to 50 years.Features of underlying disorder may be present (e.g., SLE, Cushing's disease).Can result from slipped capital femoral epiphysis in its own right.",
"<br><strong>Test:</strong> In initial stages, MRI may show decreased intensity for both T1- and T2-weighted images.</p>",
"</dd>",
"<dt><a href='#Section2'>Legg-Calve-Perthes' disease</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Clinical features often similar to slipped capital femoral epiphysis (e.g., onset of pain, limp, restricted range of motion).",
"<br><strong>Test:</strong> Plain x-rays may show sclerosis, cysts, or collapse of the femoral head.MRI shows high signal intensity on T2-weighted images and low signal intensity on T1-weighted images in the subchondral region.</p>",
"</dd>",
"<dt><a href='#Section3'>Hip dysplasia</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Caused by intra-uterine loss of contact between the fetal femoral head and acetabulum.May range from mild, asymptomatic cases to severe dysplasia with congenital hip dislocation.Moderate-to-severe dysplasia may predispose to early osteoarthritis, labral tear, or impingement, and present with findings secondary to one or more of these conditions.Patients with congenital dislocation have shortening of the involved leg and decreased hip range of motion.",
"<br><strong>Test:</strong> Shallow, more vertically oriented acetabulum seen on plain films.</p>",
"</dd>",
"<dt><a href='#Section4'>Osteomyelitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Typically chronic or acute-on-chronic presentation with vague pain complaints.May have at-rest or night pain.Constitutional symptoms (fevers, chills, malaise) often present.Unremarkable hip examination possible if infectious process involves pelvis.",
"<br><strong>Test:</strong> Elevated WBC, CRP, and ESR.Blood cultures may be positive for infective organism.Plain film x-rays may show changes consistent with chronic osteomyelitis in some cases.MRI associated with higher sensitivity and specificity in select patients.MRI shows increased signal intensity on T2-weighted images and intra-osseous/sub-periosteal abscess.</p>",
"</dd>",
"<dt><a href='#Section5'>Septic arthritis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Severe pain with weight-bearing activities.May be accompanied by fevers, chills, and malaise.Resting position of hip flexion, abduction, and external rotation to relieve pain.Pain with passive range of motion on examination.",
"<br><strong>Test:</strong> Plain x-rays may show increased joint space.Joint effusion seen on ultrasound.Joint aspiration for synovial fluid analysis and culture may yield positive culture.</p>",
"</dd>",
"<dt><a href='#Section6'>Groin pain/pull</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Pain on adduction, direct tenderness in groin.",
"<br><strong>Test:</strong> Tenderness directly over the groin and adductor tendons; no external rotation deformity.</p>",
"</dd>",
"<dt><a href='#Section7'>Ankylosing spondylitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Spondyloarthropathy typically seen in young-to-middle-aged men.Hip joint involvement is common, often bilateral.Symptoms (stiffness, pain) are worse in the morning and improve during the course of the day.Low back and sacroiliac joints are also frequently affected.",
"<br><strong>Test:</strong> Plain film x-rays of the hip and pelvis may demonstrate irregularities of the sacroiliac joints with erosive/sclerotic changes.Classic bamboo-spine appearance seen on spinal x-ray.</p>",
"</dd>",
"<dt><a href='#Section8'>Stress fractures</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> History may indicate overuse injury (e.g., endurance athlete or military recruit).",
"<br><strong>Test:</strong> X-rays show oedema or stress reaction in the region of the femoral neck.</p>",
"</dd>",
"</dl>"].join("\n");