content=["<dl>",
"<dt><a href='#Section0'>Ileus</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Less crampy abdominal pain; in association with other cause (e.g., postoperative, systemic infection, medications).",
"<br><strong>Test:</strong> CT scan shows passage of contrast throughout the small bowel and into the rectum.</p>",
"</dd>",
"<dt><a href='#Section1'>Infectious gastroenteritis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Vomiting, typically nonbilious.",
"<br><strong>Test:</strong> X-ray shows gas throughout abdomen; stool cultures may be positive for viruses or bacteria.</p>",
"</dd>",
"<dt><a href='#Section2'>Large bowel obstruction</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Very distended abdomen; constipation progressing to obstipation.",
"<br><strong>Test:</strong> X-ray shows a very dilated colon.</p>",
"</dd>",
"<dt><a href='#Section3'>Intestinal pseudo-obstruction</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Chronic condition; constipation; often associated with administration of neurologic medications.",
"<br><strong>Test:</strong> X-ray and CT show gas throughout abdomen; massively dilated intestine.</p>",
"</dd>",
"<dt><a href='#Section4'>Appendicitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Pain in right lower quadrant with nausea; vomiting (nonbilious).",
"<br><strong>Test:</strong> Ultrasound and CT may confirm diagnosis in most cases.</p>",
"</dd>",
"<dt><a href='#Section5'>Pancreatitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Steady pain in the upper abdomen; nonbilious vomiting; back pain.",
"<br><strong>Test:</strong> Increased amylase; CT scan shows inflamed pancreas.</p>",
"</dd>",
"</dl>"].join("\n");