content=["<dl>",
"<dt><a href='#Section0'>Upper airway resistance syndrome (UARS)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Fragmented sleep results in increased subjective and objective daytime sleepiness. Few clinical centres measure respiratory effort using oesophageal probes and therefore UARS is probably an under-diagnosed condition. [1]",
"<br><strong>Test:</strong> UARS applies to individuals with increased inspiratory efforts (as identified by oesophageal pressure measurements) with frequent arousals, as measured from EEG during diagnostic overnight polysomnography (PSG), but without overt apnoeas and hypopnoeas.</p>",
"</dd>",
"<dt><a href='#Section1'>Obstructive sleep apnoea (OSA)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients and partners often give a history of cessation of breathing for 10 seconds or more, as well as choking and gasping episodes. They are often obese and have excessive daytime somnolence.",
"<br><strong>Test:</strong> A sleep study will diagnose OSA (apnoea-hypopnoea index (AHI) of &gt;5).Pulse oximetry is a useful screening test but may miss mild and moderate OSA.Polysomnography is the definitive method of sleep study. [1]</p>",
"</dd>",
"<dt><a href='#Section2'>Stridor</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Occurs during wakefulness. May be relevant history of tumour, inhaled foreign body, neck surgery causing laryngeal nerve injury, or retro-pharyngeal abscess.",
"<br><strong>Test:</strong> Laryngoscopy: may reveal source of upper airways obstruction.</p>",
"</dd>",
"<dt><a href='#Section3'>Sleep-related groaning (catathrenia)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Rare. Expiratory vocalisation during sleep that has a different vocal quality from expiratory snoring.",
"<br><strong>Test:</strong> Sleep studies with special sound recording device: allows differentiation of snoring from other types of noise.</p>",
"</dd>",
"</dl>"].join("\n");