content=["<dl>",
"<dt><a href='#Section0'>Peripheral vascular disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> An important differential diagnosis is claudication from vascular insufficiency, as both conditions tend to affect older patients. Leg pain of vascular claudication is usually cramping, begins distally, and progresses proximally. Patients with vascular insufficiency will not report improvement of symptoms with lumbar flexion. Patients with vascular claudication will have more difficulty walking uphill due to increased demand for oxygen, while those with spinal stenosis often find it easier, since they flex forwards when walking uphill.Peripheral circulation should be evaluated in patients with decreased pedal pulses, trophic skin changes, or any other sign of arterial insufficiency.",
"<br><strong>Test:</strong> MRI typically does not show radiographical signs of lumbar stenosis.Lower limb duplex ultrasonography and angiography will confirm vascular insufficiency.</p>",
"</dd>",
"<dt><a href='#Section1'>Lumbosacral intervertebral disc herniation</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Disc herniations generally cause unilateral radiculopathy (i.e. pain and numbness in a specific dermatome, occasionally weakness in a muscle group) rather than neurogenic claudication. Onset is generally acute. Straight leg raise is often positive. Disc herniation is generally more common in younger patients (30 to 60 years old).",
"<br><strong>Test:</strong> MRI shows paracentral, lateral, or foraminal disc herniation with no, or insignificant, narrowing of the spinal canal.</p>",
"</dd>",
"<dt><a href='#Section2'>Spinal compression fracture</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> With thoracolumbar compression fracture, pain usually occurs in the mid or upper back. Patients give history of trauma, prolonged steroid use, or osteoporosis in older population (pathological osteoporotic fracture).Neurogenic claudication does not occur unless there is retropulsion of fracture fragments at the level of the cauda equina. Rarely do patients develop thoracic radiculopathy or myelopathy from retropulsion of fracture fragments at the level of the spinal cord.",
"<br><strong>Test:</strong> Plain x-rays, CT, or MRI demonstrate fracture.</p>",
"</dd>",
"<dt><a href='#Section3'>Metastatic disease of the spine</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> May be a history of prostate, breast, lung, kidney, thyroid, or other malignancy and/or unexplained weight loss. Back pain is often the predominant symptom and is usually worse at night. Patients often are unable to find a position of comfort. Pain from metastatic disease may be out of proportion to the usual back pain associated with degenerative changes.Back pain and neurological symptoms are present for a relatively short duration (days to a few months). Neurological symptoms are more common than in lumbar stenosis and may include significant muscle weakness, paraplegia, and bladder and bowel dysfunction.",
"<br><strong>Test:</strong> Plain x-rays, CT, or MRI show vertebral body and/or pedicle disruption at one or more spinal levels.</p>",
"</dd>",
"<dt><a href='#Section4'>Vertebral osteomyelitis or discitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> High-risk patients include intravenous drug users, patients on haemodialysis, and those with diabetes. More common in immunosuppressed patients and those with HIV, in whom a skin infection or UTI may lead to spinal osteomyelitis. Patient should be asked about history of recent infection and weight loss.Neurological deficits can occur if an epidural abscess develops, but neurogenic claudication does not. Back pain is the predominant symptom.",
"<br><strong>Test:</strong> Plain x-rays reveal loss of disc space and erosion of cortical end plate margins.MRI of the involved vertebral body and disc space shows hypointensity in T1 signal and hyperintensity in T2 signal. Affected areas enhance with gadolinium contrast.WBC count, C-reactive protein levels, and erythrocyte sedimentation rate may be elevated.Blood cultures are positive in less than 50% of patients.CT-guided biopsy is the diagnostic study of choice.</p>",
"</dd>",
"<dt><a href='#Section5'>Primary spinal, intradural, or intramedullary tumour</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Primary spinal tumours are rare. Pain from intramedullary tumours is worse at night or when the patient is lying down (compression from venous stasis), and conservative treatment fails to relieve the pain.Neurological symptoms from cord or cauda equina compression are more common than in patients with spinal stenosis.",
"<br><strong>Test:</strong> Plain x-rays, CT, or MRI show evidence of the tumour.</p>",
"</dd>",
"<dt><a href='#Section6'>Ankylosing spondylitis</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Usually seen in men and in younger patients (onset at age 30 to 40 years). Causes morning back stiffness, hip pain and swelling (caused by large joint arthritis). It is not relieved with rest and improves with exercise.",
"<br><strong>Test:</strong> Plain x-rays, CT, or MRI show the classic picture of a 'bamboo spine' (i.e., multi-level spinal fusion). Sacroiliac joints may be obliterated on plain x-rays.Test for HLA-B27 antigen is positive.</p>",
"</dd>",
"<dt><a href='#Section7'>Trochanteric bursitis and degenerative arthritis of the hip</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Pain radiates to the lateral aspect of the thigh in about 20% to 40% (pseudoradiculopathy) but rarely extends to the posterior thigh or below the knee. Numbness and paraesthesiae are not dermatomal in distribution. Walking may trigger pain but, unlike in neurogenic claudication, pain is also triggered when the patient lies on the affected side. Symptoms are often unilateral. With trochanteric bursitis, there is significant localised tenderness over the greater trochanter, and Patrick's test is positive (external rotation of the hip increases pain).",
"<br><strong>Test:</strong> Plain x-rays, CT, or MRI may show signs of hip arthropathy in the absence of evidence of significant lumbar stenosis. MRI may also demonstrate inflammatory changes along the trochanteric region.</p>",
"</dd>",
"<dt><a href='#Section8'>Diabetic neuropathy</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> History of long-standing diabetes. Pain in the feet is in a non-dermatomal, stocking distribution. The pain is described as burning, constant, and not related to activity. The sole of the foot is usually tender to pressure from the examiner's thumb. Bladder dysfunction might be present because of autonomic neuropathy.",
"<br><strong>Test:</strong> EMG shows characteristic findings of multiple axonal sensory mononeuropathies.</p>",
"</dd>",
"<dt><a href='#Section9'>Epidural abscess</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Presentation can be non-specific. Fever, malaise, and back pain are the most consistent early symptoms. May be local tenderness, with or without neurological deficit. Abscess can develop from contiguous spread from osteodiscitis, haematogenous spread, or from direct inoculation from injection, surgery, or penetrating trauma.",
"<br><strong>Test:</strong> MRI with gadolinium contrast demonstrates epidural abscess.WBC, ESR, and CRP may be elevated.Blood cultures may be positive.</p>",
"</dd>",
"<dt><a href='#Section10'>Degenerative disc/facet joint pain</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> In the abscence of stenosis, degenerative changes affecting the disc and facet joint can cause back pain that radiates to the buttocks and posterior thighs. Flexion exacerbates pain from a degenerative disc, while extension aggravates facet joint symptoms. Pain is mechanical rather than claudicatory or radicular.",
"<br><strong>Test:</strong> Plain radiographs show loss of disc height and degenerative changes.MRI shows loss of disc hydration and height and facet joint degeneration without neural element compression.</p>",
"</dd>",
"</dl>"].join("\n");