content=["<dl>",
"<dt><a href='#Section0'>Spine segmental dysgenesis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> A sporadic disorder characterised by congenital acute-angle kyphosis or kyphoscoliosis that is localised to a spinal segment, usually in the thoracolumbar or upper lumbar spine. [63]The spine is normal above and below the affected area and neurological impairment is due to congenital hypoplasia or absence of roots at the segment rather than to cord tethering.",
"<br><strong>Test:</strong> Plain x-rays will show vertebral anomalies such as hemivertebrae.MRI spine documents the specific spine and cord pathology such as vertebrae fusions or hemivertebrae, split cord, nerve malpositions, and low-lying cord.</p>",
"</dd>",
"<dt><a href='#Section1'>Caudal regression syndrome (sacral agenesis)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> A rare disorder associated with maternal diabetes that affects the sacral or lumbosacral spine.Patients typically have sparing of sensation and characteristic sacral anomalies.",
"<br><strong>Test:</strong> Plain x-rays and MRI spine will show the characteristic bony defects.</p>",
"</dd>",
"<dt><a href='#Section2'>Multiple vertebral segmentation disorder</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Autosomal recessive disorder characterised by short trunk dwarfism, multiple segmentation anomalies of the vertebral column, and costal anomalies.",
"<br><strong>Test:</strong> Plain x-rays and MRI spine identify the dystrophic vertebrae, and/or multiple fused vertebrae, kyphosis, split cord, syrinx, and dystrophic cord.</p>",
"</dd>",
"<dt><a href='#Section3'>VACTERL (vertebral abnormalities, anal atresia, cardiac abnormalities, tracheo-oesophageal fistula and/or oesophageal atresia, renal agenesis, and dysplasia and limb defects)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> A non-random association of multiple mid-line congenital anomalies including vertebral, anal, and cardiac defects, tracheo-oesophageal fistula, renal anomalies, and limb anomalies.",
"<br><strong>Test:</strong> Plain x-rays will show bony defects.Barium enema identifies fistulas and imperforate anus.Echocardiography reveals cardiac anomalies.Renal ultrasound will identify hydronephrosis and associated renal anomalies.MRI identifies characteristic spine and cord malformations.</p>",
"</dd>",
"</dl>"].join("\n");