content=["<dl>",
"<dt><a href='#Section0'>Psychogenic non-epileptic status epilepticus (SE)</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Defined as prolonged or repeated episodes of psychogenic non-epileptic seizures.May present as violent motor events mimicking generalised convulsive SE (more common) or subtle unresponsive events mimicking non-convulsive SE (less common).Physical signs that may favour psychogenic non-epileptic SE are persistent eye closure, variable degree of responsiveness, asynchronous and discontinuous motor activity, pelvic thrusting, absence of postictal state, and prolonged attack duration. A prior psychiatric history also favours the diagnosis of psychogenic non-epileptic SE.",
"<br><strong>Test:</strong> The only method to differentiate epileptic from non-epileptic SE is video-EEG. Video-EEG recording of a psychogenic non-epileptic event will be normal.</p>",
"</dd>",
"<dt><a href='#Section1'>Delirium</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> This acute state of cognitive and perceptual decline can mimic non-convulsive SE. In its broader definition, it may include all states of altered awareness or confusion that are commonly referred to as encephalopathy.Encephalopathy may be secondary to metabolic, toxic, or infectious causes.",
"<br><strong>Test:</strong> Distinction between non-convulsive SE and encephalopathy may be a challenging task, even for a well-trained epileptologist. EEG patterns are often confusing, especially in the case of metabolic encephalopathies such as hepatic or renal.Laboratory findings such as high liver aminotransferases or ammonia in conjunction with clinical and EEG judgement may help in reaching the correct diagnosis.Performing EEGs on patients with acute mental changes is strongly recommended.</p>",
"</dd>",
"<dt><a href='#Section2'>Coma</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Defined as a state of absent cognitive and motor responsiveness.Non-convulsive SE can be mistakenly diagnosed as coma. [8]  The distinction is crucial, since coma is usually irreversible, whereas non-convulsive SE is often treatable.",
"<br><strong>Test:</strong> EEG may be very helpful in distinguishing coma from non-convulsive SE. However, certain periodic EEG patterns can be difficult to differentiate from ictal patterns. Such EEG patterns are commonly seen in hepatic or post-anoxic coma.Performing EEGs on all patients with a presumed diagnosis of coma is highly recommended.</p>",
"</dd>",
"</dl>"].join("\n");