content=["<dl>",
"<dt><a href='#Section0'>Pseudostrabismus</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Facial features (e.g., epicanthal folds, wide nasal bridge, eyelid abnormalities) may falsely convey the impression of ocular misalignment.This is most common in young children and in the Asian population.",
"<br><strong>Test:</strong> Hirschberg test: shows centred corneal light reflexes in the absence of true manifest strabismus.Cover test: negative.Uncover test: negative.</p>",
"</dd>",
"<dt><a href='#Section1'>Blurred vision</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Some patients complain of double vision when in fact the vision is actually not clear.",
"<br><strong>Test:</strong> Blurred vision persists when one eye is covered.In contrast, the double vision caused by strabismus is binocular (present only when both eyes are open).</p>",
"</dd>",
"<dt><a href='#Section2'>Monocular diplopia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Refractive errors; may cause a 'ghost image'.",
"<br><strong>Test:</strong> Monocular diplopia persists when one eye is covered.In contrast, the double vision caused by strabismus is binocular (present only when both eyes are open).Symptoms corrected with spectacles or contact lenses.</p>",
"</dd>",
"<dt><a href='#Section3'>Convergence insufficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients complain of eye strain after reading or near work.",
"<br><strong>Test:</strong> On examination there is large exophoria (latent outward deviation) when looking at near objects, and decreased amplitudes of fusional convergence.Convergence insufficiency is the only disorder that responds to treatment with orthoptic exercises.</p>",
"</dd>",
"</dl>"].join("\n");