content=["<dl>",
"<dt><a href='#Section0'>Pseudohyponatraemia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Many patients are asymptomatic. Symptoms, if present, depend on the nature and severity of the underlying cause.Possible symptoms or signs of poorly controlled diabetes (polyuria, polydipsia) may be present if hyperglycaemia is the cause.Eruptive xanthoma may be seen in patients with severe hyperlipidaemia.Patients with hyperproteinaemia may show signs of multiple myeloma or other rarer causes.",
"<br><strong>Test:</strong> Suspicion is raised if measurement of serum glucose, lipids, and protein reveals one of these to be elevated.Elevated serum glucose: diagnosis is confirmed if calculation of the corrected serum sodium value reveals a normal sodium level. The equation for SI units is: corrected sodium (mmol/L) = measured sodium (mmol/L) + 0.016{(glucose [mmol/L] x 18)-100}. The equation for conventional units is: corrected sodium (mEq/L) = measured sodium (mEq/L) + 0.016 [glucose (mg/dL) - 100].Elevated serum lipid level, particularly triglyceride: normal serum osmolarity confirms diagnosis.Elevated serum protein, particularly, globulin (multiple myeloma): normal serum osmolarity confirms diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Hypovolaemia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of poor oral intake, vomiting, diarrhoea, or diuretic use help to distinguish hypovolaemia from SIADH.Evidence of dry mucous membranes, skin tenting, and flat neck veins can accompany hypovolaemia, although clinical assessment is poor at predicting volume status. [10]",
"<br><strong>Test:</strong> Central venous pressure (CVP) &lt;8.Urine sodium &lt;20 mmol/L (20 mEq/L).Elevation in serum sodium with a diagnostic trial of 1 to 2 L of normal saline infusion.</p>",
"</dd>",
"<dt><a href='#Section2'>Cerebral salt-wasting</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> There is a history of intracranial bleed or trauma.",
"<br><strong>Test:</strong> Volume depletion (CVP &lt;8) with a urine Na &gt;120 mmol/L (120 mEq/L). [11]Fractional excretion of urea &lt;30%. [12]Continued high urine sodium despite hypertonic saline or water restriction.</p>",
"</dd>",
"<dt><a href='#Section3'>Hypervolaemia (e.g., CHF, cirrhosis, pregnancy)</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Dyspnoea, pulmonary oedema, elevated jugular venous pressure, ascites, lower extremity oedema.",
"<br><strong>Test:</strong> CVP elevated.Urine sodium &lt;40 mmol/L (40 mEq/L).</p>",
"</dd>",
"<dt><a href='#Section4'>Psychogenic polydipsia</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> There may be a psychiatric history or excess fluid intake elicited during history.",
"<br><strong>Test:</strong> Urine osmolality &lt;100 mmol/kg H2O (&lt;100 mOsm/kg H2O).24-hour urine osmoles &gt;600 mmol (mOsm &gt;600 mOsm).</p>",
"</dd>",
"<dt><a href='#Section5'>Poor solute intake (e.g., beer potomania, low-protein diet)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Beer drinking or malnourished patients with poor dietary solute intake and high water intake. Low solute excretion limits water excretion causing water retention.",
"<br><strong>Test:</strong> Urine osmolality &lt;100 mmol/kg H2O (&lt;100 mOsm/kg H2O).24-hour urine osmoles &lt;300 mmol (&lt;300 mOsm).</p>",
"</dd>",
"<dt><a href='#Section6'>Renal failure</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Hypertension; oedema may be present.",
"<br><strong>Test:</strong> Elevated creatinine.</p>",
"</dd>",
"<dt><a href='#Section7'>Addison's disease</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Pigmentation of skin and mucosa, weight loss, hypotension.",
"<br><strong>Test:</strong> Low cortisol levels.Responds to steroid administration.</p>",
"</dd>",
"<dt><a href='#Section8'>Hypothyroidism</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Dry coarse skin, myxoedema, hair loss, weight gain.",
"<br><strong>Test:</strong> High TSH and low serum thyroid hormone levels.Responds to treatment with thyroid hormone.</p>",
"</dd>",
"</dl>"].join("\n");