content=["<dl>",
"<dt><a href='#Section0'>Central nervous system tuberculoma</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patients are normally febrile.There may also be signs of tuberculosis elsewhere (e.g., chronic cough, haemoptysis, bone pain).",
"<br><strong>Test:</strong> Western blot negative.CT and MRI may show ring-enhancing lesions.</p>",
"</dd>",
"<dt><a href='#Section1'>Amoebic abscess</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients are usually febrile with elevated erythrocyte sedimentation rates.",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"<dt><a href='#Section2'>Migraine</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually have unilateral motor or sensory signs and headache.",
"<br><strong>Test:</strong> Stool examination and western blot negative.</p>",
"</dd>",
"<dt><a href='#Section3'>Epilepsy</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually experience premonitory sensations (fear, epigastric sensation, d&eacute;j&agrave; vu, jamais vu).",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"<dt><a href='#Section4'>Gastroenteritis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients may be febrile with associated vomiting.",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"<dt><a href='#Section5'>Brain tumour</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients have focal neurological deficits according to location.",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"<dt><a href='#Section6'>Liver metastases</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Patients may be jaundiced with ascites.",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"<dt><a href='#Section7'>Cholecystitis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have positive Murphy's signs with right shoulder pain.",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"<dt><a href='#Section8'>Sarcoidosis</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Patients may have erythema nodosum, chronic fatigue, and/or arthralgia.",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"<dt><a href='#Section9'>Alcohol abuse</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually demonstrate evidence of alcohol withdrawal including hallucinations and tremor.",
"<br><strong>Test:</strong> Western blot negative.</p>",
"</dd>",
"</dl>"].join("\n");