content=["<dl>",
"<dt><a href='#Section0'>Sinusitis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Sinusitis pain to palpation is localised to the para-nasal and frontal sinuses.TMJ syndrome usually involves the TMJ region and possibly the temporal regions.",
"<br><strong>Test:</strong> Otoscopic examination may reveal an abnormality such as effusion or obstruction.Evaluation is best performed by a dentist when dental pathology is suspected.</p>",
"</dd>",
"<dt><a href='#Section1'>Chronic headache</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Joint clicking is absent.Pain is not cyclic.",
"<br><strong>Test:</strong> There are no differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section2'>Dental pain</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Hot/cold testing of teeth indicates extreme sensitivity.Tapping the tooth elicits pain.Joint clicking is absent.",
"<br><strong>Test:</strong> Dental x-rays may reveal peri-apical pathology.Evaluation is best performed by a dentist when dental pathology suspected.</p>",
"</dd>",
"<dt><a href='#Section3'>SLE</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Clinical manifestations of SLE may be present including malar rash or discoid lupus (thick, red, scaly patches on the skin).Small joints of the hand and wrist are usually affected, although any joint is at risk.Other presenting features include pericarditis, myocarditis, and endocarditis; pulmonary manifestations; autoimmune hepatitis; and glomerulonephritis.",
"<br><strong>Test:</strong> Markers of systemic disease: anaemia, thrombocytopenia, neutropenia, deranged LFTs.Positive antinuclear antibody and anti-extractable nuclear antigen on serological testing.</p>",
"</dd>",
"<dt><a href='#Section4'>Rheumatoid arthritis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Patients with rheumatoid arthritis may have other joint involvement, particularly symmetrical small joint polyarthritis in the hands, chiefly affecting the metatarsophalangeal joints and sparing the distal interphalangeal joints.Patients with acute rheumatoid arthritis may also feel generally unwell with fatigue and low mood.",
"<br><strong>Test:</strong> In rheumatoid arthritis, ESR and C-reactive protein (CRP) are abnormal and rheumatoid factor and anticyclic citrullinated (anti-CCP) antibodies are positive.Typical rheumatoid arthritis erosive changes are seen on x-ray, MRI, or ultrasound.</p>",
"</dd>",
"<dt><a href='#Section5'>Giant cell arteritis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Patients typically have pain and tenderness over the temporal artery, which may occur with amaurosis fugax and loss of vision.Pain resolves within 3 days of high-dose corticosteroid treatment.",
"<br><strong>Test:</strong> Duplex scanning of temporal arteries may reveal thickening of the arterial wall.Sedimentation rate &gt;100 mm/hour.CRP is usually elevated.Biopsy shows giant cell arteritis.</p>",
"</dd>",
"<dt><a href='#Section6'>Neuralgias</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Joint clicking is usually absent.Facial pain is elicited by touching a trigger point.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"</dl>"].join("\n");