content=["<dl>",
"<dt><a href='#Section0'>Rotator cuff tear</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Shoulder pain; more common in patients &gt;40 years of age. Focal weakness on examination.",
"<br><strong>Test:</strong> Positive MRI findings.</p>",
"</dd>",
"<dt><a href='#Section1'>Osgood-Schlatter's disease</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Common cause of knee pain in active youth: boys aged 13 to 14 years old; girls aged 10 to 11 years old. Focal tenderness, swelling, and bump formation over the tibial tubercle.",
"<br><strong>Test:</strong> X-ray: may be normal; often demonstrates enlarged tibial tubercle, sometimes with fragmentation of the apophysis.</p>",
"</dd>",
"<dt><a href='#Section2'>Sinding-Larsen-Johansson disease</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Knee pain; typically affects younger patients (that is, pre-teen or early teenage) during periods of rapid bone growth. Affects boys more than girls. Focal tenderness to palpation in the inferior pole of the patella on examination.",
"<br><strong>Test:</strong> X-ray: may be normal or may demonstrate calcification at the inferior pole of the patella.</p>",
"</dd>",
"<dt><a href='#Section3'>Retrocalcaneal bursitis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Posterior heel pain anterior to the Achilles' tendon, just superior to its insertion. Dorsiflexion aggravates the pain. Positive 2-finger squeeze test on examination. View image",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section4'>Subcutaneous tendo-Achilles' bursitis (Haglund's deformity or 'pump bump')</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Pain in the superficial bursa between the Achilles' tendon and skin, usually caused by ill-fitting shoes with rigid heel backs. Prominence on the lateral aspect of the posterosuperior calcaneus is tender to touch on examination.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"</dl>"].join("\n");