content=["<dl>",
"<dt><a href='#Section0'>Musculoskeletal lower back pain</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Patient may have history of obesity, stress, and psychiatric comorbidities; previous lower back pain; or prior treatment for lower back pain.Absence of red flag symptoms (recent significant trauma, or milder trauma in age &gt;50 years; unexplained weight loss; immunosuppression; history of cancer; IV drug use; prolonged use of corticosteroids; osteoporosis; age &gt;70 years; focal neurological deficit with progressive or disabling symptoms; or duration of lower back pain &gt;6 weeks). [44]Sensory, motor, and deep tendon reflexes within normal limits.",
"<br><strong>Test:</strong> Plain x-rays: normal.MRI/CT spine: absence of disc herniation and spinal stenosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute cervical spine trauma</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> History of neck injury or pain, or radiculopathy. Sudden onset of radicular symptoms after trauma. Head strike with or without loss of consciousness.",
"<br><strong>Test:</strong> Cervical x-ray: ligamentous instability may be seen in the form of excessive (&gt;2 mm) anterior or posterior vertebral body translation relative to the vertebra below; avulsion or teardrop fracture may be seen at the anterior vertebral body; fractures of atlas (C1) and axis (C2) are known even in relatively lower energy events, including hangman fracture of the axis; in more severe injury mechanisms (particularly with airbag deployment), unilateral and even bilateral facet luxation may be present with or without fracture.</p>",
"</dd>",
"<dt><a href='#Section2'>Degenerative cervical spine disease</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Cervical spondylosis is associated with increasing age (&gt;40 years), and there may be a family history or history of trauma, myofascial strain, or cervical surgery.Spontaneous onset of neck pain. Cervical muscle pain and spasm. Headache or occipital pain.",
"<br><strong>Test:</strong> Cervical x-ray: presence of degenerative joint disease or degenerative disc disease, fracture, or instability.Cervical MRI: bone destruction, spinal cord or nerve compression, intradural or epidural process.</p>",
"</dd>",
"<dt><a href='#Section3'>Osteoporosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Risk factors include: older age (women &gt;50; men &gt;65); predominantly female gender; white ancestry; FHx of hip fracture; prior fracture.History of low-impact injury.Examination findings: loss of height, kyphosis.",
"<br><strong>Test:</strong> Dual-energy x-ray absorptiometry (DXA): score of &le;-2.5 indicates osteoporosis; T-score &le;-2.5 with fragility fracture(s) indicates severe (or established) osteoporosis.X-ray: can reveal osteopenia.Quantitative CT: shows reduced trabecular bone density.</p>",
"</dd>",
"<dt><a href='#Section4'>Spinal osteosarcoma</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Rare. Worsening pain over weeks or months. Mass or swelling found on examination.",
"<br><strong>Test:</strong> X-ray: radiolucent lesion with areas of mottled radiodensity and ill-defined margins.</p>",
"</dd>",
"<dt><a href='#Section5'>Metastatic bone disease</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> History of cancer.History of low-impact injury.",
"<br><strong>Test:</strong> CT/MRI/MRI FLAIR (fluid-attenuated inversion recovery): detection of tumour.</p>",
"</dd>",
"</dl>"].join("\n");