content=["<dl>",
"<dt><a href='#Section0'>Carpal tunnel syndrome</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Pain and numbness primarily in the wrists; night-time worsening of symptoms.",
"<br><strong>Test:</strong> Electrodiagnostic testing showing focal slowing of conduction velocity in the median sensory nerves across the carpal tunnel.</p>",
"</dd>",
"<dt><a href='#Section1'>Cubital tunnel syndrome</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Pain and numbness primarily in the elbow through the ring and little fingers.",
"<br><strong>Test:</strong> Electrodiagnostic testing showing motor conduction velocity across the elbow is &lt;50 m/second.</p>",
"</dd>",
"<dt><a href='#Section2'>Herniated cervical intervertebral disc</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Pain in upper extremities, specifically the back, radiating down through the buttocks and legs, possibly with muscle spasms. [39]",
"<br><strong>Test:</strong> MRI cervical spine showing herniation of cervical intervertebral disc.</p>",
"</dd>",
"<dt><a href='#Section3'>Ruptured cervical disc</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Pain down medial aspect of the arm.",
"<br><strong>Test:</strong> MRI cervical spine showing herniation of cervical intervertebral disc contents.</p>",
"</dd>",
"<dt><a href='#Section4'>Cervical spondylosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Stiffness in upper neck, loss of bladder or bowel control, urinary or bowel retention.",
"<br><strong>Test:</strong> Cervical spine x-ray showing cervical spondylitic degeneration.</p>",
"</dd>",
"<dt><a href='#Section5'>Vascular occlusion, embolism, or insufficiency</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Severe chest pain.",
"<br><strong>Test:</strong> Angiogram showing narrowing or occlusion of affected vessel.</p>",
"</dd>",
"<dt><a href='#Section6'>Coronary artery disease</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Chest pain.",
"<br><strong>Test:</strong> Coronary angiogram showing narrowing or occlusion of affected vessel.</p>",
"</dd>",
"<dt><a href='#Section7'>Myocardial infarction</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Severe chest pain, dyspnoea, pallor, diaphoresis, and cardiogenic shock.",
"<br><strong>Test:</strong> ECG in ST-elevation MI: ST-segment elevation &gt;1 mm in 2 or more anatomically contiguous leads or new left bundle branch block; ECG in non-ST-elevation MI: non-specific changes; ST-segment depression or T-wave inversion.</p>",
"</dd>",
"<dt><a href='#Section8'>Angina pectoris</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Chest pressure or squeezing promoted by exercise or emotional stress.",
"<br><strong>Test:</strong> ECG showing non-specific changes; ST-segment depression or T-wave inversion.</p>",
"</dd>",
"<dt><a href='#Section9'>Primary Raynaud's phenomenon</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Blue or purple colour in hands or fingers.",
"<br><strong>Test:</strong> Diagnosis is clinical.</p>",
"</dd>",
"<dt><a href='#Section10'>Superior pulmonary sulcus carcinoma</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Severe chest pain.",
"<br><strong>Test:</strong> CT chest demonstrating superior pulmonary sulcus carcinoma.</p>",
"</dd>",
"<dt><a href='#Section11'>Superior sulcus tumour</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Shoulder and elbow pain. [40]",
"<br><strong>Test:</strong> CT chest demonstrating tumour. [41]</p>",
"</dd>",
"</dl>"].join("\n");