content=["<dl>",
"<dt><a href='#Section0'>Meniere's disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Presents with a quadrad of symptoms: tinnitus, episodic vertigo lasting 15 minutes to 24 hours, unilateral aural fullness, and hearing loss.In most cases only one ear is involved, but the condition is bilateral in 10% to 30% of cases. [28]",
"<br><strong>Test:</strong> Clinical diagnosis.Audiometry usually reveals unilateral sensorineural hearing loss.</p>",
"</dd>",
"<dt><a href='#Section1'>Acoustic neuroma (schwannoma)</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Benign tumour that commonly arises from the vestibular nerve.As the tumour grows it compresses the cochlear and vestibular nerves, usually causing unilateral hearing loss, tinnitus, and dizziness. Can also interfere with the trigeminal nerve, causing facial numbness.If the tumour becomes large, it will eventually compress the fourth ventricle and cause hydrocephalus and life-threatening brainstem compression.",
"<br><strong>Test:</strong> MRI is necessary to rule out acoustic neuroma in patients with subjective unilateral tinnitus, asymmetrical audiogram, and normal ear examination.</p>",
"</dd>",
"<dt><a href='#Section2'>Glomus tumour</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Glomus tympanicum tumours arise from the cochlear promontory and are usually visible otoscopically as a red, pulsatile mass behind an intact tympanic membrane.Glomus jugulare tumours arise from paraganglia in the adventitia of the jugular bulb. When a glomus jugulare tumour is confined to the jugular fossa, otoscopic examination is normal.Both types of glomus tumour can cause pulsatile tinnitus in 60% of patients. [3]",
"<br><strong>Test:</strong> Small glomus tympanicum tumours are best seen on high-resolution computer tomography (HRCT) scans.The earliest abnormality detectable on cross-sectional images of a glomus jugulare tumour is erosion of the lateral and anterior walls of the osseous jugular fossa on HRCT scan.</p>",
"</dd>",
"<dt><a href='#Section3'>Dehiscent jugular bulb</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Most common cause of diagnosable pulsatile tinnitus. [3]Jugular bulb is the dilation of upper jugular vein between the sigmoid sinus and the jugular vein at the junction. A high-riding jugular bulb is above the level of the floor of the external auditory canal or tympanic annulus.A dehiscent high jugular bulb is visible at otoscopy as a smooth, bluish mass. [29]",
"<br><strong>Test:</strong> Visible on MR angiography.Thin-section bone algorithm CT scans demonstrate the anatomy of temporal bone better and help in the diagnosis. [29]</p>",
"</dd>",
"<dt><a href='#Section4'>Otosclerosis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> The hard, mineralised bones of the inner ear turn into a more vascular and immature bone, resulting in excessive bone growth and fixation of the stapes at the oval window.Eventually leads to conductive hearing loss.Approximately 90% of people with otosclerosis are unaware of their hearing loss and do not seek treatment when the loss is mild. Tinnitus is present in 75% of patients with otosclerosis and is characterised by a broad-band hissing sound, humming sound, or discrete tones.",
"<br><strong>Test:</strong> Conductive hearing loss on audiometry.</p>",
"</dd>",
"<dt><a href='#Section5'>Otitis media</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Associated with fever, earache, nausea, vomiting, or tinnitus.Diagnosed by otoscopy and visualisation of red, bulging tympanic membrane. Decreased movement of tympanic membrane is the main diagnostic factor of otitis media.",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section6'>Myoclonus</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Tensor and levator veli palatine, salpingopharyngeus, and superior constrictor muscle myoclonus are all causes of objective tinnitus.Myoclonus of these muscles leads to rhythmic involuntary jerking movements of soft palate and causes tinnitus that has a clicking nature. [3]  [7]",
"<br><strong>Test:</strong> Clinical diagnosis.</p>",
"</dd>",
"<dt><a href='#Section7'>Multiple sclerosis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Demyelinating disease of the central nervous system. Tinnitus, with or without hearing loss, has been reported during exacerbation of the disease by a minority of patients.",
"<br><strong>Test:</strong> MRI of the brain with gadolinium confirms white matter lesions.</p>",
"</dd>",
"<dt><a href='#Section8'>Patulous eustachian tube</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Usually occurs after adenoidectomy or weight loss.Causes clicking sounds with swallowing, aural fullness, autophony.Head-hanging relieves the symptoms due to dilation of veins. [3]",
"<br><strong>Test:</strong> Diagnosed by otomicroscopy that shows movement of tympanic membrane with respiration.</p>",
"</dd>",
"<dt><a href='#Section9'>Cerebrovascular disease</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Tinnitus occurs if there is turbulence of the blood flow in a narrow or abnormal artery.Aneurysms, atherosclerosis, and aberrance of carotid artery can result in pulsatile, objective tinnitus.Atherosclerosis of carotid artery can be suspected in patients with risk factors such as hyperlipidaemia, hypertension, diabetes, and smoking.Audible carotid bruit on physical examination.Aberrant carotid artery may be visualised in the mesotympanum as a red or white mass that does not blanch with pneumo-otoscopy.",
"<br><strong>Test:</strong> Diagnosed on duplex ultrasonography.CT scan can also show the aberrant carotid artery.</p>",
"</dd>",
"<dt><a href='#Section10'>Arteriovenous malformation (AVM)</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Dural AVMs occasionally present with pulsatile tinnitus.Audible bruits can be heard by auscultation of the retroauricular region.",
"<br><strong>Test:</strong> Diagnosed on MRI and MR angiography (MRA).Carotid angiography should be considered if no disease was found on MRA and clinical suspicion is high. [3]</p>",
"</dd>",
"<dt><a href='#Section11'>Dural arteriovenous fistula (AVF)</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Present with pulsatile tinnitus in 65% of patients in association with visual changes, headache, or mental status change. [30]",
"<br><strong>Test:</strong> Diagnosed on MRA or carotid angiography. [3]</p>",
"</dd>",
"<dt><a href='#Section12'>Salicylate overdose</a></dt>",
"<dd id='Section12'>",
"<p><strong>Sign & Symptoms:</strong> Ingestion of about 150 mg/kg of salicylate produces mild toxicity, and &gt;500 mg/kg of this drug is lethal.Presents with acute onset of tachypnoea, tachycardia, hypotension, seizure, encephalopathy that may progress to coma.Auditory symptoms of tinnitus and deafness.Tinnitus occurs when serum salicylate concentration exceeds 30 mg/dL.",
"<br><strong>Test:</strong> Elevated serum levels of salicylate.</p>",
"</dd>",
"</dl>"].join("\n");