content=["<dl>",
"<dt><a href='#Section0'>Infectious mononucleosis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> More common in slightly older age group (adolescents) and, unlike acute tonsillitis, does not resolve after 1 week.It is associated with generalised lymphadenopathy, splenomegaly, and hepatomegaly, and persistent weight loss and fatigue.Rarely, the swelling of the pharyngeal tissues may become so significant as to impair breathing.",
"<br><strong>Test:</strong> Heterophile antibody testing is most commonly used to diagnose infectious mononucleosis. However, it has only moderate sensitivity, particularly in the first week of symptoms; sensitivity is even lower in children than it is in adults. [13]</p>",
"</dd>",
"<dt><a href='#Section1'>Epiglottitis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> A child with epiglottitis will have a muffled voice and will be drooling; there may be stridor and difficulty in breathing.",
"<br><strong>Test:</strong> On suspicion of epiglottitis, it is important not to spend time performing blood tests or even attempting to examine the child's throat: prompt consultation with a paediatric anaesthetist to secure the airway is crucial.</p>",
"</dd>",
"<dt><a href='#Section2'>Peri-tonsillar abscess (quinsy)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Causes more severe symptoms, including trismus, a muffled voice, a displaced uvula, and an enlarged, displaced tonsil, with swelling of the peri-tonsillar region.",
"<br><strong>Test:</strong> The diagnosis is based on examination of the oropharynx and is confirmed on needle aspiration of pus from the peri-tonsillar swelling.</p>",
"</dd>",
"<dt><a href='#Section3'>Retropharyngeal abscess</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Symptoms may be similar to those of a severe sore throat.However, the symptoms do not resolve after a few days, and there may be trismus or visible neck swelling.",
"<br><strong>Test:</strong> Exclusion is made on the basis of lateral neck x-ray, or neck CT or ultrasound.</p>",
"</dd>",
"<dt><a href='#Section4'>Gonococcal pharyngitis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Adolescent and adult patients with a history of oral-genital sex.",
"<br><strong>Test:</strong> Throat culture (in Thayer-Martin medium) of Neisseria gonorrhoeae.</p>",
"</dd>",
"<dt><a href='#Section5'>Diphtheria</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Examination of the oropharynx reveals the typical grey-green membrane.Serosanguineous nasal discharge will be noted.Patient will not have been immunised against diphtheria.",
"<br><strong>Test:</strong> Microbiology showing Corynobacterium diphtheriae.</p>",
"</dd>",
"<dt><a href='#Section6'>HIV infection</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Patients with primary HIV infection are more likely to have generalised lymphadenopathy, weight loss, and malaise, and to have risk factors for HIV infection.",
"<br><strong>Test:</strong> Diagnosis is made by a positive HIV test.</p>",
"</dd>",
"</dl>"].join("\n");