content=["<dl>",
"<dt><a href='#Section0'>Metatarsus primus varus</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Isolated adducted first metatarsal.Normal alignment of lateral border of foot.Vertical skin crease at the tarsometatarsal joint on the medial side of the foot.",
"<br><strong>Test:</strong> Foot x-rays. Angulation of the first metatarsal bone towards the midline of the body.</p>",
"</dd>",
"<dt><a href='#Section1'>Positional calcaneovalgus</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Identified at birth.Ankle dorsiflexed with mild subtalar joint eversion.Ankle dorsiflexion is flexible.",
"<br><strong>Test:</strong> Clinical diagnosis. Routine imaging studies not necessary.</p>",
"</dd>",
"<dt><a href='#Section2'>Hip dysplasia</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Hip abduction and symmetry should be assessed to rule out hip dysplasia.",
"<br><strong>Test:</strong> Anteroposterior pelvic x-ray may demonstrate dysplasia of the hip.</p>",
"</dd>",
"<dt><a href='#Section3'>Congenital femoral deficiency</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> A spectrum of congenital isolated limb deficiency with a short femur in an otherwise normal child.The affected thigh is shorter than the contralateral thigh, and the leg may be shorter.",
"<br><strong>Test:</strong> Anteroposterior pelvic x-ray and anteroposterior x-ray of the lower extremities.Femoral deficiency ranges from mild shortening to total absence of the proximal femur, and apparent discontinuity between the femoral neck and shaft. Typified by valgus and external rotation deformity of the knee, hip abduction and flexion contracture associated with fibular hemimelia, and absence of the cruciate ligaments of the knee.</p>",
"</dd>",
"</dl>"].join("\n");