content=["<dl>",
"<dt><a href='#Section0'>Non-toxic causes of wide complex tachycardia</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Absence of a history of a toxic ingestion should prompt consideration of non-toxic causes.Successful cardioversion with treatment suggests a non-toxic cause; tachycardia due to an ingested toxin usually persists.",
"<br><strong>Test:</strong> A widened QRS in conjunction with a rightward vector of the terminal 40 msec of the frontal plane QRS suggests a toxic ingestion due to sodium channel toxicity. This is most easily identified as a widened (&gt;1 mm) and enlarged (&gt;1 mm) R wave in a VR and S wave in I and L. Non-toxic causes produce other patterns.Administration of sodium bicarbonate to push the arterial pH to between 7.45 and 7.55 narrows the QRS complex in sodium channel blocker toxicity. A lack of response excludes sodium channel blocker toxicity.Drug screen and drug levels are negative.</p>",
"</dd>",
"<dt><a href='#Section1'>Non-toxic causes of status epilepticus</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> A known diagnosis of epilepsy, with poor compliance to medication.Other non-toxic causes are suggested by sudden-onset severe headache (intracranial haemorrhage), unilateral weakness (stroke), or fever (febrile seizure or CNS infection).",
"<br><strong>Test:</strong> Toxic and non-toxic seizures usually respond to benzodiazepines. Seizures also respond to sodium channel anticonvulsants such as phenytoin.Drug screen and drug levels are negative.</p>",
"</dd>",
"<dt><a href='#Section2'>Non-toxic causes of anion gap metabolic acidosis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Clinical distinction is difficult.Absence of a history of a toxic ingestion or features specific to particular ingestions (e.g., vision or hearing loss, severe hypertension, recurrent seizures) should prompt consideration of non-toxic causes.History of type 1 diabetes with a recent illness or sub-optimal insulin therapy should prompt consideration of diabetic ketoacidosis.",
"<br><strong>Test:</strong> Drug screen and drug levels are negative.Hyperglycaemia with ketosis should prompt consideration of diabetic ketoacidosis.Elevated serum urea and creatinine should prompt consideration of both toxic and non-toxic causes of renal failure.</p>",
"</dd>",
"<dt><a href='#Section3'>Non-toxic causes of altered mental status</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Non-toxic causes suggested by history of head trauma (intracranial bleeding), focal neurological signs (stroke), chest pain (MI), fever with symptoms of infection (sepsis or any acute systemic infection), or abdominal pain with tenderness.",
"<br><strong>Test:</strong> No response to therapeutic trial of antidotes.Drug screen and drug levels are negative.</p>",
"</dd>",
"<dt><a href='#Section4'>Volume depletion in children</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Clinical evidence of excessive GI losses, haemorrhage, diabetic ketoacidosis with polyuria, burns, heat stroke, fever, heavy exercise, anaphylaxis, sepsis, small-bowel obstruction, or ascites.Signs of dehydration.",
"<br><strong>Test:</strong> Tachycardia is common.BP may be slightly high (early stage) or low (late stage).Drug screen and drug levels are negative.</p>",
"</dd>",
"<dt><a href='#Section5'>Non-toxic causes of hypertension</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Absence of signs of central agitation or features of the antimuscarinic toxidrome suggests a non-toxic cause.Absence of fever.",
"<br><strong>Test:</strong> Drug screen and drug levels are negative.</p>",
"</dd>",
"<dt><a href='#Section6'>Non-toxic causes of fever</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Absence of features of sympathomimetic or antimuscarinic toxidromes, and absence of hyperreflexia, myoclonus, or rigidity, may suggest a non-toxic cause.Clinical features of an underlying infection, inflammatory disorder, or malignancy.",
"<br><strong>Test:</strong> Drug screen and drug levels are negative.</p>",
"</dd>",
"<dt><a href='#Section7'>Non-toxic causes of bradycardia</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Absence of features of the cholinergic toxidrome, or of beta-blocker (peripheral shutdown with hypoglycaemia) or calcium-channel blocker toxicity (peripheral vasodilation with hyperglycaemia), may suggest a non-toxic cause.Absence of a history of a toxic ingestion.",
"<br><strong>Test:</strong> Drug screen and drug levels are negative.Bradycardia responds to normal dose atropine.</p>",
"</dd>",
"<dt><a href='#Section8'>Inhalation injury</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> History of exposure to a residential fire, workplace fire or explosion, or a chemical leak.Similar symptoms to other patients at site of exposure.Respiratory symptoms, including cough, dyspnoea, and tachypnoea.Cyanosis, facial burns, hoarseness, dysphonia, or stridor.",
"<br><strong>Test:</strong> Hypoxaemia on pulse oximetry.Increased carboxyhaemoglobin levels in carbon monoxide poisoning.Air trapping, atelectasis, and airspace opacity on CXR.</p>",
"</dd>",
"<dt><a href='#Section9'>Snakebites</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> History of snakebite, with fang marks, local redness, tenderness, pain, and swelling at wound site.Weakness, dizziness, and perioral tingling or numbness are suggestive of envenomation.There may also be bleeding and extensive swelling.",
"<br><strong>Test:</strong> No distinguishing tests.</p>",
"</dd>",
"<dt><a href='#Section10'>Insect or spider bites and stings</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> History of insect or spider bite or sting with pain, itching, or rash at the site of the bite.Clinical features of anaphylaxis.Pain, muscle cramps, diaphoresis, tremors, paraesthesias, nausea/vomiting, and headache suggest a black widow spider bite.",
"<br><strong>Test:</strong> No distinguishing tests.</p>",
"</dd>",
"</dl>"].join("\n");