content=["<dl>",
"<dt><a href='#Section0'>Graves' disease</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Exophthalmos or pretibial myxoedema may be present.Onset and symptoms often more dramatic than for toxic nodule.",
"<br><strong>Test:</strong> Thyroid scan shows diffuse uptake.Often there is evidence of thyroid auto-immunity (i.e., positive thyroid peroxidase antibodies), although this is not diagnostic.TSH receptor antibodies are positive, but rarely required for diagnosis.</p>",
"</dd>",
"<dt><a href='#Section1'>Toxic multinodular goitre</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients usually &gt;40 to 50 years of age.Apathetic hyperthyroidism more likely, with weight loss, mood change or atrial fibrillation alone.",
"<br><strong>Test:</strong> Scan shows areas of both increased and decreased uptake, indicating nonfunctioning and functioning nodules. [1] View image Uptake often normal.</p>",
"</dd>",
"<dt><a href='#Section2'>Thyrotoxic phase of painless lymphocytic thyroiditis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Most often occurs post-partum.",
"<br><strong>Test:</strong> Absent or low uptake on I-123 scan. Often there is evidence of thyroid auto-immunity (i.e., positive thyroid peroxidase antibodies), although this is not diagnostic.</p>",
"</dd>",
"<dt><a href='#Section3'>Thyrotoxic phase of subacute granulomatous thyroiditis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Associated with anterior neck pain and tenderness.",
"<br><strong>Test:</strong> Absent or low uptake on I-123 scan.ESR raised.</p>",
"</dd>",
"<dt><a href='#Section4'>Iodine-induced hyperthyroidism</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> History of an iodine load (from iodinated radiographic contrast, amiodarone, or a change in diet) in the setting of autonomous nodular thyroid disease (the Jod-Basedow phenomenon).",
"<br><strong>Test:</strong> Low uptake on I-123 scan.24-hour urine iodine high.</p>",
"</dd>",
"<dt><a href='#Section5'>Marine-Lenhart's syndrome (nodular Graves' disease)</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Exophthalmos or pretibial myxoedema may be present.",
"<br><strong>Test:</strong> Thyroid scan shows diffuse uptake with a cold rather than hot area in the region of the palpable nodule. The nodule appears hot on scan only following treatment for Graves' disease. [22]</p>",
"</dd>",
"<dt><a href='#Section6'>Functional follicular thyroid cancer</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Very rare.There may be bulky metastatic disease or cervical lymphadenopathy.",
"<br><strong>Test:</strong> Total body scan shows uptake of radioactive iodine over metastases.</p>",
"</dd>",
"<dt><a href='#Section7'>Thyroidal haemiagenesis plus Graves' disease</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Very rare.Exophthalmos or pretibial myxoedema may be present.",
"<br><strong>Test:</strong> Ultrasound shows absence of the contra-lateral lobe. [23]</p>",
"</dd>",
"</dl>"].join("\n");