content=["<dl>",
"<dt><a href='#Section0'>Colonic pseudo-obstruction</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Typically seen in the elderly when hospitalised for a severe illness.Patients may give history of chronic constipation.No systemic manifestations.",
"<br><strong>Test:</strong> Absence of an elevated WBC count and metabolic abnormalities.Contrast enema will confirm the diagnosis and exclude mechanical causes in most cases.</p>",
"</dd>",
"<dt><a href='#Section1'>Acute mesenteric ischaemia</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Patients may give history of risk factors for acute mesenteric ischaemia, including coronary artery disease, hypertension, diabetes, smoking, and hyper-cholesterolaemia.Diffuse abdominal pain with systemic manifestations, but abdominal distention is often absent.",
"<br><strong>Test:</strong> Abdominal film findings are often normal in the presence of acute mesenteric ischaemia.CT scan will show signs of bowel wall ischaemia including bowel wall thickening, thumb printing, and pneumatosis.</p>",
"</dd>",
"<dt><a href='#Section2'>Large bowel obstruction</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> A history of constipation may be present.Signs of systemic toxicity are absent in the early stages.There may be a palpable abdominal mass on clinical examination suggesting an underlying malignancy or diverticular mass.",
"<br><strong>Test:</strong> Gaseous distention of the large bowel on plain abdominal film; 'kidney bean' shape seen in volvulus.Contrast enema shows obstruction to contrast at site of lesion; 'bird's beak' appearance seen in volvulus.</p>",
"</dd>",
"<dt><a href='#Section3'>Hirschsprung's disease</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Diagnosed in infancy or early childhood.Abdominal distention that is usually not accompanied by abdominal pain.Increased anal sphincter tone and presence of constipation, which may be relieved with digital rectal examination.",
"<br><strong>Test:</strong> Abdominal films characteristically reveal rectal and distal large bowel dilatation with collapsed proximal large and small bowel.Absence of ganglion cells on rectal biopsy.</p>",
"</dd>",
"</dl>"].join("\n");