content=["<dl>",
"<dt><a href='#Section0'>Transfusion-associated sepsis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Clinically difficult to distinguish from immune-mediated transfusion reaction.",
"<br><strong>Test:</strong> Direct antiglobulin test, inspection of plasma specimen rule out haemolysis.Gram stain may be positive.Blood culture from patient and remainder of blood transfusion component may grow culprit organism. Caused by bacterial contamination of transfused component.Associated with platelets (bacterial contamination in 1/1000 to1/2000 units) more than other transfused components. [20]  [21]</p>",
"</dd>",
"<dt><a href='#Section1'>Non-immune-mediated haemolysis</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Occurs rarely.Presents acutely, with haemoglobinuria (red urine).",
"<br><strong>Test:</strong> Direct antiglobulin test is usually normal, differentiating this from immune-mediated haemolysis.This, along with inspection of plasma specimen and repeat patient blood-typing, rules out immune-mediated patient haemolysis.Component should be evaluated for haemolysis. Caused by mechanical destruction of red cells as a result of improper storage temperatures, inappropriate syringe size, or damage from roller pumps. Transfusion blood should be transfused with normal saline. Hypotonic fluids such as D5W cause osmotic haemolysis of red cells. Uncommonly, patients receive blood from donors with pre-existing red-cell membrane disorders that are predisposed to haemolysis, triggering a reaction similar to an immune haemolytic reaction.</p>",
"</dd>",
"<dt><a href='#Section2'>Transfusion-associated circulatory overload</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Findings of volume overload such as jugular venous distension.",
"<br><strong>Test:</strong> Differentiation from transfusion-related acute lung injury (TRALI) requires determination of whether pulmonary oedema is cardiogenic (overload) or non-cardiogenic (TRALI). Elevated brain natriuretic peptide, central venous pressure, or pulmonary artery wedge pressure suggest volume overload.</p>",
"</dd>",
"</dl>"].join("\n");