content=["<dl>",
"<dt><a href='#Section0'>Overdose of sodium channel blockers</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> The history of suicidal overdose is often the same. History of use of sodium channel blockers: e.g., class 1a antiarrythmics (quinidine, procainamide, disopyramide), class 1c antiarrythmics (flecainide, propafenone), and local anaesthetics.The degree of toxicity is often the only clue to the diagnosis of TCA overdose as these patients tend to be more seriously ill and decline more rapidly.",
"<br><strong>Test:</strong> No specific diagnostic test. Differentiating among these sodium channel blockers is often difficult. Response to sodium bicarbonate therapy may also be similar. They may produce diagnostic ECGs that appear comparable.</p>",
"</dd>",
"<dt><a href='#Section1'>Conditions causing right axis ECG deviation</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> With bronchospasm or large pulmonary embolus, no anticholinergic signs are present.Structural heart disease is not associated with anticholinergic signs either.",
"<br><strong>Test:</strong> In the case of bronchospasm or a large pulmonary embolus, sinus tachycardia should be present but not QRS prolongation.Healthy children may also have persistent right ventricular forces, which produce a similar axis shift without QRS widening.Consider other clinical parameters to differentiate these diagnoses. In these conditions, patients do not respond to sodium bicarbonate therapy.</p>",
"</dd>",
"<dt><a href='#Section2'>Anticholinergic overdose</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> The signs and symptoms produced by all agents are similar. Examples include atropine and antihistamines (e.g., diphenhydramine), antipscyhotics, and antispasmodics. Again, a seriously ill and rapidly declining patient may be the only clue that a TCA is involved.",
"<br><strong>Test:</strong> No specific diagnostic test. As with differentiating among sodium channel blockers, differentiating among potential anticholinergics becomes difficult.</p>",
"</dd>",
"</dl>"].join("\n");