content=["<dl>",
"<dt><a href='#Section0'>Cardiac tumours</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> There are no specific differentiating signs/symptoms.",
"<br><strong>Test:</strong> Echocardiogram will often show tumours and differentiate cause.</p>",
"</dd>",
"<dt><a href='#Section1'>SLE</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Malar rash, arthritis/arthralgias, pancytopenia, photosensitivity, renal involvement, alopecia, or Raynaud's phenomenon.",
"<br><strong>Test:</strong> ANA, anti-dsDNA or anti-Sm antibodies may be positive in SLE.</p>",
"</dd>",
"<dt><a href='#Section2'>Constrictive pericarditis (CP)</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Usually have a previous history of tuberculosis, pericarditis, cardiac surgery, mantle radiation, chest trauma, or connective tissue disease. Murmurs are rare with CP and jugular venous pulsations are less prominent.",
"<br><strong>Test:</strong> Calcification of pericardium sometimes seen on CXR.Echocardiogram shows only mildly enlarged atrium and normal tricuspid valve without a gradient.Cardiac catheterisation reveals absence of tricuspid valve gradient and classic haemodynamic findings of CP.</p>",
"</dd>",
"<dt><a href='#Section3'>Restrictive cardiomyopathy</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> History is usually unremarkable. Systolic murmurs of mitral and tricuspid regurgitation are most common. Diastolic murmurs are less common. Jugular venous pulsations can be prominent.",
"<br><strong>Test:</strong> Echocardiogram shows severe bi-atrial enlargement in the absence of significant AV valve gradient. Valve can sometimes be thickened, but shortened chordae and commissural fusion are rarely discovered.Cardiac catheterisation reveals classic findings of restrictive cardiomyopathy without tricuspid valve gradient.</p>",
"</dd>",
"</dl>"].join("\n");