content=["<dl>",
"<dt><a href='#Section0'>Gastroenteritis</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> More prominent watery or bloody diarrhoea.If systemic manifestations are present, they usually occur concomitantly with the gastrointestinal manifestations, rather than following them.",
"<br><strong>Test:</strong> Stool sample: cultures positive for Salmonella, Shigella, or Campylobacter; presence of white cells or lactoferrin.</p>",
"</dd>",
"<dt><a href='#Section1'>Respiratory or gastrointestinal viral infections</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Myalgia and fever are common, but are usually associated with other respiratory (cough, coryza) or gastrointestinal (vomiting, diarrhoea) manifestations.Outbreaks of viral infections are more common and widespread than those of trichinellosis.",
"<br><strong>Test:</strong> Viral antigens and cultures: positive in nasopharyngeal and bronchial samples in respiratory infections; positive in stool sample in gastrointestinal infections.</p>",
"</dd>",
"<dt><a href='#Section2'>Glomerulonephritis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> In addition to fever, eosinophilia, and peri-orbital oedema, this condition causes haematuria and/or proteinuria, and renal failure.",
"<br><strong>Test:</strong> Urinalysis: presence of protein, blood, leukocytes, RBC casts, and dysmorphic RBCs.Serum creatinine: elevated.Urea: elevated.Kidney biopsy: shows inflammation, cellular proliferation, basement membrane thickening, fibrosis, and epithelial cell changes, and is confirmatory.</p>",
"</dd>",
"<dt><a href='#Section3'>Anaphylaxis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Hyper-acute presentation.Peri-orbital oedema is normally accompanied by swelling of other mucosae (angio-oedema), hives, and possible respiratory distress.",
"<br><strong>Test:</strong> There are no confirmatory diagnostic tests.Diagnosis is based on the clinical presentation and presence of a trigger factor.</p>",
"</dd>",
"<dt><a href='#Section4'>Polymyositis and dermatomyositis</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Clinical course is more chronic.Symmetric proximal muscle weakness is more common than myalgia.Peri-orbital oedema may occur, but the rash in dermatomyositis is not transient.",
"<br><strong>Test:</strong> EMG: short-duration, low-amplitude poly-phasic units on voluntary activation and increased spontaneous activity with fibrillations, complex repetitive discharges, and positive sharp waves.Muscle biopsy: shows lymphocytic infiltrates, fibre atrophy, and necrosis, and (with electromyography results) is confirmatory.Auto-antibodies: ANA, anti-Jo-1 antibodies, anti-SRP antibodies, and antibodies to Mi-2 may be positive.</p>",
"</dd>",
"<dt><a href='#Section5'>Peri-orbital cellulitis</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Eyelids are red and painful.Fever may be present, but there is no myalgia.",
"<br><strong>Test:</strong> There are no confirmatory diagnostic tests.Diagnosis is usually clinical.Blood cultures may occasionally be positive.</p>",
"</dd>",
"<dt><a href='#Section6'>Parasitoses</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Several helminthic infections such as schistosomiasis, toxocariasis, and fascioliasis cause eosinophilia and may be confused with trichinellosis in the early stages.",
"<br><strong>Test:</strong> Stool sample: presence of ova or parasite.Serum antibodies: may be positive for each specific parasite.</p>",
"</dd>",
"<dt><a href='#Section7'>Infective endocarditis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Causes fever (more persistent than in trichinellosis), myalgia, and splinter haemorrhages.Cardiac murmur is invariably present.Other embolic or immune manifestations may be present.",
"<br><strong>Test:</strong> Echocardiogram: mobile vegetations on heart valves.Blood cultures: positive.</p>",
"</dd>",
"<dt><a href='#Section8'>Eosinophilia-myalgia syndrome</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Eosinophilia, myalgia, and cutaneous manifestations (rashes, pruritus) are common.May occur in outbreaks and is usually associated with the consumption of L-tryptophan.",
"<br><strong>Test:</strong> There are no confirmatory diagnostic tests.</p>",
"</dd>",
"<dt><a href='#Section9'>Leptospirosis</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Bi-phasic disease beginning with fevers, myalgia, rash, and gastrointestinal manifestations after contact with animal urine or faeces.Followed by second phase with meningitis, liver, and renal failure.",
"<br><strong>Test:</strong> Blood cultures: positive for Leptospira species.ELISA: positive for antibodies against Leptospira species.PCR: positive for Leptospira species.</p>",
"</dd>",
"</dl>"].join("\n");