content=["<dl>",
"<dt><a href='#Section0'>Dental caries</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Well localised to a single tooth.",
"<br><strong>Test:</strong> Intra-oral x-rays.</p>",
"</dd>",
"<dt><a href='#Section1'>Dental fracture</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Localised to &ge;1 teeth; may be provoked by biting.",
"<br><strong>Test:</strong> Intra-oral x-rays.</p>",
"</dd>",
"<dt><a href='#Section2'>Mandibular osteomyelitis</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Typically continuous pain along mandible with associated swelling. History of fever, malaise, purulent discharge, mobile teeth.",
"<br><strong>Test:</strong> Intra-oral x-rays.</p>",
"</dd>",
"<dt><a href='#Section3'>Temporomandibular joint syndrome</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Often bilateral, jaw opening may be restricted.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section4'>Migraine</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Presence of preceding aura. Associated with photophobia, nausea.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section5'>Glossopharyngeal neuralgia</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> Pain is in the distribution of the glossopharyngeal nerve, classically oropharyngeal and otic.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section6'>Post-herpetic neuralgia</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Typically presents as continuous pain in distribution of upper division of trigeminal nerve (V1). Patient often has tactile allodynia.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"<dt><a href='#Section7'>Temporal arteritis</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> Pain is often continuous, can be bilateral, and may be associated with jaw claudication, visual changes, and anorexia.",
"<br><strong>Test:</strong> ESR, temporal artery biopsy (gold standard).</p>",
"</dd>",
"<dt><a href='#Section8'>Atypical facial pain</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Often is bilateral and/or exceeds the confines of a trigeminal distribution.",
"<br><strong>Test:</strong> Diagnosis is made with formal neuropsychological evaluation.</p>",
"</dd>",
"<dt><a href='#Section9'>Trigeminal autonomic cephalgias (e.g., cluster headache, short-lasting unilateral neuralgiform headache attacks with conjunctival injection and tearing [SUNCT] syndrome, chronic paroxysmal hemicrania)</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Often have prominent autonomic features (e.g., conjunctival injection, lacrimation, nasal congestion, rhinorrhoea, ptosis). Pain associated with cluster headaches, typically retro-orbital. [21]",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"</dl>"].join("\n");