content=["<dl>",
"<dt><a href='#Section0'>Parasitic infections:  Strongyloides, Isosporiasis, Giardia lambia, Entamoeba histolytica</a></dt>",
"<dd id='Section0'>",
"<p><strong>Sign & Symptoms:</strong> Parasitic infections often presents with the same signs and symptoms as tropical sprue (TS).Malabsorption in TS is generally more profound and typically involves micro-nutrients such as folate.",
"<br><strong>Test:</strong> Stool microscopy may reveal ova and parasites.Stool and/or serum antigen testing for specific parasites may be positive.Giardiasis may feature some degree of villous blunting in the proximal small bowel as seen in TS; other infections do not.</p>",
"</dd>",
"<dt><a href='#Section1'>Bacterial infections:  Shigella,  Salmonella, Escherichia coli</a></dt>",
"<dd id='Section1'>",
"<p><strong>Sign & Symptoms:</strong> Bacterial infections typically lead to an acute presentation.GI and constitutional symptoms such as diarrhoea, abdominal pain, and fever are more severe.Diarrhoea may be bloody, which is not seen in TS.",
"<br><strong>Test:</strong> Stool should be cultured for the presence of these micro-organisms.</p>",
"</dd>",
"<dt><a href='#Section2'>HIV enteropathy</a></dt>",
"<dd id='Section2'>",
"<p><strong>Sign & Symptoms:</strong> Chronic diarrhoea, weight loss, abdominal cramps, anal pain, fevers.Diffuse abdominal tenderness, hepatosplenomegaly, lymphadenopathy.",
"<br><strong>Test:</strong> HIV test is positive.Can mimic the histological small-bowel findings that are seen in TS.</p>",
"</dd>",
"<dt><a href='#Section3'>Tuberculosis</a></dt>",
"<dd id='Section3'>",
"<p><strong>Sign & Symptoms:</strong> Can closely mimic the clinical signs and symptoms of TS.Features of systemic disease may be present.",
"<br><strong>Test:</strong> Staining for mycobacterium of bowel tissue positive.Blood, biopsy, or sputum samples may show mycobacterial infection.Can mimic the histological small bowel findings that are seen in TS.</p>",
"</dd>",
"<dt><a href='#Section4'>Whipple's disease</a></dt>",
"<dd id='Section4'>",
"<p><strong>Sign & Symptoms:</strong> Can closely mimic the clinical signs and symptoms of TS.Arthralgia/adenopathy may be present.",
"<br><strong>Test:</strong> Small-bowel biopsy may culture periodic acid-Schiff-positive macrophage inclusions.</p>",
"</dd>",
"<dt><a href='#Section5'>Small-bowel lymphoma</a></dt>",
"<dd id='Section5'>",
"<p><strong>Sign & Symptoms:</strong> In immunoproliferative small intestinal disease (IPSID), GI/constitutional symptoms such as abdominal pain, fever, and chills predominate over features of malabsorption.",
"<br><strong>Test:</strong> Small-bowel biopsy may be histologically distinguishable.</p>",
"</dd>",
"<dt><a href='#Section6'>Crohn's disease</a></dt>",
"<dd id='Section6'>",
"<p><strong>Sign & Symptoms:</strong> Profound malabsorption not commonly seen. Bloody diarrhoea common.Disease course waxes and wanes while TS more commonly features an indolent progression.",
"<br><strong>Test:</strong> Colonoscopy with intubation of the terminal ileum may reveal macroscopical features (gross mucosal erythema and ulceration) not seen in TS.Abdominopelvic CT and/or upper GI series with small bowel follow may reveal strictures and fistulae.</p>",
"</dd>",
"<dt><a href='#Section7'>Coeliac sprue (CS)</a></dt>",
"<dd id='Section7'>",
"<p><strong>Sign & Symptoms:</strong> More commonly affects white people of European descent.No acute period of diarrhoea with CS.",
"<br><strong>Test:</strong> IgA antibodies positive in CS.Anti-endomysial antibodies should also be positive.Biopsies indistinguishable.Therapeutic trial of folic acid: TS responds.Gluten-free diet: CS responds.</p>",
"</dd>",
"<dt><a href='#Section8'>Scleroderma</a></dt>",
"<dd id='Section8'>",
"<p><strong>Sign & Symptoms:</strong> Upper GI symptoms such as heartburn and dysphagia more common.Features of malabsorption unlikely unless concomitant small-intestinal bacterial overgrowth present.Likely to manifest classic skin changes; evidence of interstitial lung disease and renal involvement common.",
"<br><strong>Test:</strong> Antinuclear antibodies are present in about 95% of patients.Topoisomerase I antibodies and anticentromere antibodies often present in limited disease.</p>",
"</dd>",
"<dt><a href='#Section9'>Small-intestinal bacterial overgrowth</a></dt>",
"<dd id='Section9'>",
"<p><strong>Sign & Symptoms:</strong> Can complicate altered intestinal anatomy (e.g., blind loops following surgery), scleroderma, or disordered intestinal motility, as well as patients with no underlying disorders.Features of malabsorption, particularly folic acid deficiency, not as common as in TS.",
"<br><strong>Test:</strong> No villous atrophy on small-bowel biopsy as is seen in TS.No evidence of multiple micro- and macro-nutrient deficiencies as seen in TS.</p>",
"</dd>",
"<dt><a href='#Section10'>Pancreatic insufficiency</a></dt>",
"<dd id='Section10'>",
"<p><strong>Sign & Symptoms:</strong> Often manifests signs/symptoms of malabsorption including diarrhoea, steatorrhoea, and fat-soluble hypovitaminosis, but signs/symptoms of protein, carbohydrate, folic acid, and vitamin B deficiencies not present.",
"<br><strong>Test:</strong> No evidence of megaloblastic anaemia, abnormal D-xylose testing, or hypoproteinaemia.</p>",
"</dd>",
"<dt><a href='#Section11'>Tropical enteropathy (TE)</a></dt>",
"<dd id='Section11'>",
"<p><strong>Sign & Symptoms:</strong> Closely resembles TS; often viewed as a sub-clinical form of the disease.TE found in same endemic areas.Associated with the malabsorption of multiple micro- and macro-nutrients.Rarely causes the symptoms that typify TS.TE does not respond as predictably to treatment with folic acid and antibiotics.Malabsorption seen in TE resolves after 6 to 12 months spent in temperate climate.",
"<br><strong>Test:</strong> No differentiating tests.</p>",
"</dd>",
"</dl>"].join("\n");