interactions["abacavir-lamivudine,epzicom"]=["abacavir-lamivudine,epzicom", {"a": {"avonex": "2",
 "arava": "3",
 "alcohol": "1",
 "amprenavir": "1",
 "agenerase": "1",
 "alcohol and dextrose injections usp hypertonic": "1",
 "avonex prefilled syringe": "2",
 "atripla": "2",
 "aptivus": "2",
 "antabuse": "1",
 "aquachloral supprettes": "1",
 "alcohol 5% in dextrose 5%": "1"}, "c": {"chlorzoxazone": "1",
 "chlorpromazine": "1",
 "clofarabine": "2",
 "copegus": "2",
 "chloral hydrate": "1",
 "cotrim": "1",
 "co-trimoxazole": "1",
 "clolar": "2",
 "cotrim ds": "1",
 "cotrim pediatric": "1"}, "b": {"bactrim iv": "1",
 "bactrim pediatric": "1",
 "bactrim": "1",
 "baraclude": "2",
 "bactrim ds": "1",
 "bethaprim pediatric": "1",
 "betaseron": "2",
 "black cohosh": "2",
 "bethaprim": "1"}, "e": {"ethyl alcohol": "1",
 "efavirenz": "2",
 "entecavir": "2",
 "ethanol": "1",
 "efavirenz/emtricitabine/tenofovir": "2",
 "embeda": "2",
 "extavia": "2",
 "eze ds": "1"}, "d": {"dehydrated alcohol": "1",
 "dolophine": "2",
 "disulfiram": "1",
 "depade": "2"}, "f": {"folex pfs": "2"}, "i": {"isoniazid/rifampin": "1",
 "isoniazid": "1",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "isonarif": "1",
 "interferon alfa-2b/ribavirin": "2",
 "isoniazid/pyrazinamide/rifampin": "1"}, "h": {"hivid": "2"}, "m": {"methadose": "2",
 "menopause support": "2",
 "morphine/naltrexone": "2",
 "methadone diskets": "2",
 "methadone": "2",
 "methotrexate": "2",
 "methotrexate lpf sodium": "2"}, "l": {"leflunomide": "3",
 "lorzone": "1"}, "o": {"ormazine": "1"}, "n": {"naltrexone": "2",
 "nydrazid": "1"}, "p": {"parafon forte dsc": "1",
 "primsol": "1",
 "paraflex": "1",
 "proloprim": "1"}, "s": {"strifon fort": "1",
 "sulfatrim pediatric": "1",
 "septra": "1",
 "smz-tmp ds": "1",
 "sulfamethoxazole/trimethoprim": "1",
 "sustiva": "2",
 "somnote": "1",
 "septra ds": "1",
 "septra iv": "1",
 "sulfatrim": "1"}, "r": {"rheumatrex dose pack": "2",
 "ribapak": "2",
 "ribatab": "2",
 "revia": "2",
 "ribasphere": "2",
 "rebif": "2",
 "rifater": "1",
 "rebetol": "2",
 "rifamate": "1",
 "rebetron": "2",
 "relaxazone": "1",
 "remular": "1",
 "ribavirin": "2",
 "remular-s": "1"}, "u": {"uroplus ds": "1",
 "uroplus": "1"}, "t": {"tabloid": "2",
 "trexall": "2",
 "trimethoprim": "1",
 "tipranavir": "2",
 "thioguanine": "2",
 "trimpex": "1",
 "thorazine": "1"}, "v": {"virazole": "2",
 "vivitrol": "2"}, "z": {"zalcitabine": "2"}}];