interactions["abarelix"]=["abarelix", {"a": {"adriamycin rdf": "2",
 "aldroxicon i": "2",
 "almacone": "2",
 "azithromycin dose pack": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "amoxapine": "2",
 "alfuzosin": "2",
 "albuterol/ipratropium": "2",
 "acetaminophen/propoxyphene": "2",
 "adriamycin": "2",
 "alamag": "2",
 "alamag plus": "2",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "aloxi": "2",
 "anhydrous calcium iodide/isoproterenol": "2",
 "allens junior cough": "2",
 "aer witch hazel": "2",
 "advair diskus": "2",
 "ascriptin": "2",
 "aventyl hydrochloride": "2",
 "arformoterol": "2",
 "asenapine": "2",
 "adenocard": "2",
 "anergan 50": "2",
 "apokyn": "2",
 "adapin": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "artemether/lumefantrine": "3",
 "ascriptin maximum strength": "2",
 "aspir-mox": "2",
 "amitriptyline": "2",
 "adeno-jec": "2",
 "agoral": "2",
 "adenoscan": "2",
 "aqualax forte": "2",
 "aspir-mox ib": "2",
 "avelox i.v.": "3",
 "arsenic trioxide": "3",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "accuneb": "2",
 "aralen hydrochloride": "2",
 "acid reducer + antacid dual action": "2",
 "albuterol": "2",
 "anafranil": "2",
 "allanderm-t": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "arcapta": "2",
 "airet": "2",
 "almacone-2": "2",
 "azithromycin/trovafloxacin": "2",
 "aldroxicon ii": "2",
 "apo-go": "2",
 "alophen": "2",
 "advair hfa": "2",
 "astemizole": "2",
 "anzemet": "3",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "apo-go pen": "2",
 "avelox": "3",
 "aspirin buffered": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "alupent": "2",
 "aralen": "2",
 "arthritis pain formula": "2",
 "azithromycin": "2",
 "antinaus 50": "2",
 "amiodarone": "3",
 "apomorphine": "2",
 "adenosine": "2",
 "aralen phosphate": "2",
 "adriamycin pfs": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "asendin": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2"}, "c": {"combivent": "2",
 "coartem": "3",
 "cascara sagrada/magnesium hydroxide": "2",
 "compro": "2",
 "chocolaxed": "2",
 "celexa": "3",
 "cipro": "2",
 "cotrim ds": "1",
 "compazine spansule": "2",
 "carter's little pills": "2",
 "citrate of magnesia": "2",
 "cotrim pediatric": "1",
 "codeine/promethazine": "2",
 "cascara sagrada": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "caprelsa": "3",
 "cordarone iv": "3",
 "ciprofloxacin": "2",
 "corvert": "3",
 "cephulac": "2",
 "cipro i.v.": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "cholac": "2",
 "clozapine synthon": "3",
 "clomipramine": "2",
 "citalopram": "3",
 "castor oil": "2",
 "ceo-two": "2",
 "cerubidine": "2",
 "chloroquine": "2",
 "chlorpromazine": "2",
 "chronulac": "2",
 "cipro cystitis pack": "2",
 "clopine": "3",
 "codeine phosphate-promethazine hcl": "2",
 "cotrim": "1",
 "cordarone": "3",
 "complera": "2",
 "co-trimoxazole": "1",
 "clarithromycin": "2",
 "clozaril": "3",
 "constilac": "2",
 "citroma": "2",
 "cipro xr": "2",
 "combivent respimat": "2",
 "compazine": "2",
 "correctol": "2",
 "cascara sagrada/phenolphthalein": "2",
 "constulose": "2",
 "casanthranol": "2",
 "colax": "2",
 "colace glycerin suppositories": "2",
 "chronulac syrup": "2",
 "clozapine": "3",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "crizotinib": "3",
 "clearlax": "2",
 "cardioquin": "3",
 "caroid laxative": "2",
 "casanthranol/docusate": "2",
 "codeine/phenylephrine/promethazine": "2",
 "cisapride": "3"}, "b": {"bactrim iv": "1",
 "black draught": "2",
 "biaxin xl": "2",
 "bisolax": "2",
 "bethaprim pediatric": "1",
 "bisacodyl uniserts": "2",
 "bricanyl": "2",
 "bronkometer": "2",
 "bisa-plex": "2",
 "biaxin": "2",
 "budesonide/formoterol": "2",
 "brethine": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "2",
 "bisac-evac": "2",
 "balsam peru/castor oil/trypsin topical": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "2",
 "brovana": "2",
 "bisacodyl": "2",
 "bisco-lax": "2",
 "bactrim": "1",
 "bactrim pediatric": "1",
 "balacet": "2",
 "bitolterol": "2",
 "bronkosol": "2",
 "balsam peru/castor oil topical": "2",
 "bandi s15": "2",
 "bisacodyl/magnesium citrate": "2",
 "bethaprim": "1",
 "boots cough syrup 3 months plus": "2",
 "betapace af": "3",
 "bepridil": "3",
 "bisa-lax": "2",
 "brethaire": "2",
 "bactrim ds": "1",
 "betapace": "3"}, "e": {"ery-tab": "2",
 "endep": "2",
 "emtricitabine/rilpivirine/tenofovir": "2",
 "evalose": "2",
 "ex-lax gentle strength": "2",
 "eribulin": "2",
 "evac-q-kwik": "2",
 "etrafon": "2",
 "ex-lax gentle nature": "2",
 "epirubicin": "2",
 "ex-lax ultra": "2",
 "erythrocin lactobionate": "2",
 "emulsoil": "2",
 "e.e.s.-400 filmtab": "2",
 "edurant": "2",
 "espotabs": "2",
 "emblon": "2",
 "ex-lax": "2",
 "e.e.s.-400": "2",
 "ex-lax maximum relief formula": "2",
 "eryc": "2",
 "e-mycin": "2",
 "ezogabine": "2",
 "ex-lax chocolated": "2",
 "ex-lax milk of magnesia": "2",
 "erythrocin": "2",
 "eryped": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "eskalith": "2",
 "erythromycin/sulfisoxazole": "2",
 "e.e.s. granules": "2",
 "erythrocin stearate filmtab": "2",
 "eskalith-cr": "2",
 "eryzole": "2",
 "ex-lax regular strength pills": "2",
 "enulose": "2",
 "e s p": "2",
 "e.e.s.-200": "2",
 "etrafon forte": "2",
 "elavil": "2",
 "erythrocot": "2",
 "evac-u-gen": "2",
 "erythromycin": "2",
 "ellence": "2",
 "ex-lax extra gentle": "2"}, "d": {"dioctolose": "2",
 "darvon compound 32": "2",
 "doxepin": "2",
 "doxil": "2",
 "dr caldwell laxative": "2",
 "dual action complete": "2",
 "di-gel lemon": "2",
 "disopyramide": "3",
 "dss plus": "2",
 "doxorubicin liposomal": "2",
 "darvocet-n 100": "2",
 "darvon-n": "2",
 "di-gel": "2",
 "dofetilide": "3",
 "dsmc compound plain": "2",
 "ducodyl": "2",
 "dulcolax bowel cleansing": "2",
 "duo-medihaler": "2",
 "docusate/senna": "2",
 "doculax": "2",
 "dextromethorphan/promethazine": "2",
 "definity": "2",
 "docu soft plus": "2",
 "daunoxome": "2",
 "darvon": "2",
 "dextromethorphan/quinidine": "3",
 "doculax plus": "2",
 "duo-vil": "2",
 "degarelix": "2",
 "dok plus": "2",
 "droperidol/fentanyl": "3",
 "doxidan softgel laxative plus stool softener": "2",
 "dolasetron": "3",
 "dasatinib": "2",
 "daunorubicin": "2",
 "diocto-c": "2",
 "docucal-p": "2",
 "diflucan": "2",
 "darvon compound-65": "2",
 "dulcolax": "2",
 "diocto-k plus": "2",
 "desipramine": "2",
 "dermuspray": "2",
 "di-gel mint": "2",
 "dialose plus": "2",
 "doc-q-lax": "2",
 "daunorubicin liposomal": "2",
 "dulera": "2",
 "droperidol": "3",
 "dulcolax laxative": "2",
 "doxidan tablet": "2",
 "dulcogen": "2",
 "dolophine": "3",
 "dulcolax milk of magnesia": "2",
 "duphalac": "2",
 "doxorubicin": "2",
 "docusate/phenolphthalein": "2",
 "duoneb": "2",
 "darvocet-n 50": "2",
 "dosaflex": "2",
 "doxidan": "2",
 "dronedarone": "3",
 "denzapine": "3",
 "darvocet a500": "2"}, "g": {"gentlax": "2",
 "glycerin/witch hazel topical": "2",
 "glycolax": "2",
 "gentlax s": "2",
 "glycerin/phenol topical": "2",
 "gantanol": "1",
 "gelusil": "2",
 "gemifloxacin": "2",
 "gentle laxative": "2",
 "glycerin suppositories maximum strength": "2",
 "gen lax": "2",
 "gatifloxacin": "3",
 "generlac": "2",
 "granulex": "2",
 "glycerin": "2",
 "glycerol": "2",
 "granumed": "2",
 "gentlax tablet": "2",
 "genox": "2",
 "geodon": "3",
 "gavilax": "2",
 "genasoft plus": "2",
 "granisetron": "2",
 "granisol": "2",
 "grepafloxacin": "3",
 "granulderm": "2"}, "f": {"first mouthwash blm": "2",
 "fletchers castoria": "2",
 "femilax": "2",
 "formoterol": "2",
 "femintrol": "2",
 "fematrol": "2",
 "fanapt": "3",
 "foradil aerolizer": "2",
 "flecainide": "2",
 "fleet glycerin suppositories pediatric": "2",
 "fast acting mylanta": "2",
 "fluconazole": "2",
 "feen-a-mint": "2",
 "fazaclo": "3",
 "floxin": "2",
 "firmagon": "2",
 "feminine lax": "2",
 "factive": "2",
 "fleet prep kit 1": "2",
 "fleet prep kit 3": "2",
 "fleet prep kit 2": "2",
 "fleet liquid glycerin suppositories": "2",
 "fortovase": "3",
 "fleet bisacodyl": "2",
 "fluphenazine": "2",
 "formoterol/mometasone": "2",
 "fletchers child laxative cherry": "2",
 "fluothane": "2",
 "fluticasone/salmeterol": "2",
 "floxin iv": "2",
 "fareston": "3",
 "fleet glycerin suppositories adult": "2"}, "i": {"ilosone": "2",
 "inapsine": "3",
 "isuprel mistometer": "2",
 "indacaterol": "2",
 "idamycin": "2",
 "isoproterenol": "2",
 "idamycin pfs": "2",
 "isuprel hcl": "2",
 "invega": "2",
 "istodax": "2",
 "imipramine": "2",
 "ibutilide": "3",
 "idarubicin": "2",
 "invirase": "3",
 "innovar": "3",
 "isuprel": "2",
 "invega sustenna": "2",
 "innerclean": "2",
 "isoetharine": "2",
 "isoproterenol/phenylephrine": "2",
 "iloperidone": "3"}, "h": {"halfan": "3",
 "haloperidol": "3",
 "halofantrine": "3",
 "halflytely and bisacodyl": "2",
 "halothane": "2",
 "heptalac": "2",
 "haldol decanoate": "3",
 "haley's m-o": "2",
 "hemorrhoidal hygiene pads": "2",
 "halaven": "2",
 "hismanal": "2",
 "haldol": "3",
 "hygenic cleansing pad": "2"}, "k": {"kaletra": "2",
 "ketek": "2",
 "kytril": "2",
 "kondremul with phenolphtalein": "2",
 "kristalose": "2",
 "ketek pak": "2"}, "m": {"metaproterenol": "2",
 "mylagen": "2",
 "mylanta": "2",
 "mellaril-s": "3",
 "mylagen-ii": "2",
 "magic bullet": "2",
 "methotrimeprazine": "2",
 "maalox": "2",
 "mesoridazine": "3",
 "milantex": "2",
 "moxifloxacin": "3",
 "magnesium hydroxide/mineral oil": "2",
 "milk of magnesia": "2",
 "mylanta fast acting": "2",
 "meperidine/promethazine": "2",
 "medi-pad": "2",
 "modane plus": "2",
 "my-o-den": "2",
 "medihaler-iso": "2",
 "maalox advanced maximum strength": "2",
 "mintox maximum strength": "2",
 "milantex maximum strength": "2",
 "mineral oil/phenolphthalein": "2",
 "mylanta supreme": "2",
 "methdilazine": "2",
 "mylanta ultimate strength": "2",
 "magaant": "2",
 "mi-acid ii": "2",
 "maalox plus": "2",
 "methadone diskets": "3",
 "mintox plus": "2",
 "maalox max": "2",
 "medilax": "2",
 "mylanta maximum strength": "2",
 "multaq": "3",
 "mintox extra strength": "2",
 "m-phen": "2",
 "metaprel": "2",
 "mepergan": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "maxair": "2",
 "maalox antacid antigas regular strength": "2",
 "masanti ds": "2",
 "mintox": "2",
 "mepergan fortis": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "mefloquine": "2",
 "maalox advanced regular strength": "2",
 "maalox max wild berry": "2",
 "mellaril": "3",
 "mylanta ultra": "2",
 "meprozine": "2",
 "miralax": "2",
 "methadose": "3",
 "maldroxal plus": "2",
 "masanti": "2",
 "maxair autohaler": "2",
 "mintox tablets": "2",
 "magnesium citrate": "2",
 "modane": "2",
 "maxaquin": "2",
 "mylanta ds fast acting": "2",
 "maprotiline": "2",
 "mylanta gelcap": "2",
 "methadone": "3",
 "mi-acid double strength": "2",
 "maalox hrf": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "maalox tc": "2",
 "mi-acid": "2"}, "l": {"ludiomil": "2",
 "lactulose": "2",
 "lomefloxacin": "2",
 "levofloxacin": "2",
 "levaquin": "2",
 "lariam": "2",
 "lithium": "2",
 "levomethadyl acetate": "3",
 "lithonate": "2",
 "lopinavir/ritonavir": "2",
 "largon": "2",
 "levitra": "2",
 "limbitrol ds": "2",
 "loso prep bowel cleansing system": "2",
 "levaquin leva-pak": "2",
 "laxative gentle suppositories": "2",
 "laxacin": "2",
 "lapatinib": "2",
 "lithobid": "2",
 "liquiprep": "2",
 "lorelco": "2",
 "lithotabs": "2",
 "limbitrol": "2",
 "levoprome": "2",
 "levalbuterol": "2"}, "o": {"orap": "3",
 "optase": "2",
 "ormazine": "2",
 "optison": "2",
 "octycine": "2",
 "osmoglyn": "2",
 "orlaam": "3",
 "ondansetron": "2",
 "ofloxacin": "2"}, "n": {"noroxin": "2",
 "nilotinib": "3",
 "norpace": "3",
 "nebupent": "2",
 "norfloxacin": "2",
 "norpace cr": "3",
 "natures remedy": "2",
 "neoloid": "2",
 "noxafil": "2",
 "nolvadex": "2",
 "nolvadex d": "2",
 "nuedexta": "3",
 "norpramin": "2",
 "nexavar": "2",
 "norisodrine with calcium iodine": "2",
 "nortriptyline": "2",
 "nexterone": "3"}, "q": {"quin-release": "3",
 "quinidex extentabs": "3",
 "quinora": "3",
 "quinidine": "3",
 "qm-260": "2",
 "quinaglute dura-tabs": "3",
 "quin-g": "3",
 "quetiapine": "2",
 "quinine": "2",
 "qualaquin": "2"}, "p": {"peg3350": "2",
 "pediazole": "2",
 "proventil": "2",
 "procainamide": "3",
 "pce dispertab": "2",
 "pharmorubicin rdf": "2",
 "proair hfa": "2",
 "polyethylene glycol 3350": "2",
 "prolixin": "2",
 "phenadoz": "2",
 "phenergan vc": "2",
 "psyllium/senna": "2",
 "probucol": "2",
 "prulet": "2",
 "peri-dos": "2",
 "phillips' haleys m-o": "2",
 "prochlorperazine": "2",
 "protriptyline": "2",
 "pepcid complete": "2",
 "pitressin": "2",
 "phenylephrine/promethazine": "2",
 "promethazine with codeine": "2",
 "phenazine 50": "2",
 "permitil": "2",
 "prolixin enanthate": "2",
 "pseudoephedrine/terfenadine": "2",
 "phenoject-50": "2",
 "paliperidone": "2",
 "pirbuterol": "2",
 "phenolphthalein": "2",
 "pentam 300": "2",
 "promethazine with dm": "2",
 "promethazine vc with codeine": "2",
 "proderm": "2",
 "propoxyphene compound 65": "2",
 "phenolax": "2",
 "procot": "2",
 "posaconazole": "2",
 "procan sr": "3",
 "pentamidine": "2",
 "pro-med": "2",
 "perdiem overnight": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "promethazine vc": "2",
 "pharmorubicin pfs": "2",
 "perforomist": "2",
 "phillips gel": "2",
 "pc-cap": "2",
 "palonosetron": "2",
 "pp-cap": "2",
 "proventil hfa": "2",
 "pedia-lax liquid glycerin suppositories": "2",
 "pamelor": "2",
 "perdiem": "2",
 "pimozide": "3",
 "pentacarinat": "2",
 "promethazine vc plain": "2",
 "prograf": "2",
 "promazine": "2",
 "pedia-lax glycerin suppositories": "2",
 "perestan": "2",
 "pedia-lax quick dissolve strips": "2",
 "purge": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "pazopanib": "2",
 "pronestyl-sr": "3",
 "promethazine vc w/codeine": "2",
 "propoxyphene": "2",
 "phenergan fortis": "2",
 "pentam": "2",
 "proquin xr": "2",
 "purelax": "2",
 "pronestyl": "3",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "pacerone": "3",
 "pedia-lax chewable tablets": "2",
 "perphenazine": "2",
 "peri-ds": "2",
 "propulsid": "3",
 "promethazine with dextromethorphan": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenazopyridine/sulfamethoxazole": "1",
 "perflutren": "2",
 "promethegan": "2",
 "procanbid": "3",
 "promethazine hcl with codeine": "2",
 "prolixin decanoate": "2",
 "potassium bitartrate/sodium bicarbonate": "2",
 "propafenone": "2",
 "peri-colace": "2",
 "phenergan with dextromethorphan": "2",
 "potiga": "2",
 "prevpac": "2",
 "propiomazine": "2",
 "phillips' milk of magnesia": "2"}, "s": {"senna-gen": "2",
 "smz-tmp ds": "1",
 "senna": "2",
 "sani-clens": "2",
 "sparine": "2",
 "saquinavir": "3",
 "sunitinib": "2",
 "septra ds": "1",
 "seroquel": "2",
 "seroquel xr": "2",
 "senokot": "2",
 "sinequan": "2",
 "senexon-s": "2",
 "senna s": "2",
 "senokot child": "2",
 "seldane": "2",
 "senolax": "2",
 "sulfamethoxazole": "1",
 "sulfimycin": "2",
 "saphris": "2",
 "sennaprompt": "2",
 "sparfloxacin": "3",
 "staxyn": "2",
 "senna concentrate": "2",
 "sennalax-s": "2",
 "septra iv": "1",
 "sotalol hydrochloride af": "3",
 "sulfatrim": "1",
 "seldane-d": "2",
 "soltamox": "2",
 "surmontil": "2",
 "senokot s": "2",
 "sani-pads with aloe": "2",
 "sutent": "2",
 "senosol-x": "2",
 "sorine": "3",
 "stelazine": "2",
 "senokotxtra": "2",
 "strong caps": "2",
 "symbicort": "2",
 "silenor": "2",
 "sunmark clearlax": "2",
 "senosol-ss": "2",
 "senexon": "2",
 "serentil": "3",
 "sani-supp": "2",
 "sancuso": "2",
 "sulfamethoxazole/trimethoprim": "1",
 "sotalol": "3",
 "sulfatrim pediatric": "1",
 "sorafenib": "2",
 "serevent diskus": "2",
 "senosol": "2",
 "septra": "1",
 "salmeterol": "2",
 "senna plus": "2",
 "senna lax": "2",
 "senokot direct relief": "2",
 "sprycel": "2"}, "r": {"risperdal m-tab": "2",
 "royvac bowel evacuant": "2",
 "rilpivirine": "2",
 "raxar": "3",
 "rythmol": "2",
 "revina nlt": "2",
 "robimycin": "2",
 "risperdal consta": "2",
 "ranexa": "2",
 "ritodrine": "2",
 "rulox plus": "2",
 "risperidone": "2",
 "rythmol sr": "2",
 "rulox 1": "2",
 "rolaids multi-symptom": "2",
 "rolaids regular strength": "2",
 "ravin": "2",
 "rulox": "2",
 "ranolazine": "2",
 "risperdal": "2",
 "rolaids extra strength": "2",
 "romidepsin": "2",
 "respirol": "2"}, "u": {"urban": "2",
 "uni-lan": "2",
 "uni-lan ii": "2",
 "ulcerease": "2",
 "uroxatral": "2",
 "unilax": "2",
 "uroplus": "1",
 "uni-cenna": "2",
 "uprima": "2",
 "urban ds": "2",
 "uroplus ds": "1"}, "t": {"tofranil": "2",
 "tasigna": "3",
 "tamoxifen": "2",
 "tamoxifen hexal": "2",
 "tizanidine": "2",
 "tornalate": "2",
 "terbutaline": "2",
 "trycet": "2",
 "trisenox": "3",
 "thioridazine": "3",
 "trifluoperazine": "2",
 "tucks": "2",
 "tequin": "3",
 "trimipramine": "2",
 "trilafon": "2",
 "trimeprazine": "2",
 "triflupromazine": "2",
 "triavil": "2",
 "thiethylperazine": "2",
 "tamone": "2",
 "tums dual action": "2",
 "terfenadine": "2",
 "tempo": "2",
 "torecan": "2",
 "tofranil-pm": "2",
 "temaril": "2",
 "toremifene": "3",
 "tamofen": "2",
 "tbc": "2",
 "tridate": "2",
 "tixylix baby syrup": "2",
 "tambocor": "2",
 "tamosin": "2",
 "telithromycin": "2",
 "tequin teqpaq": "3",
 "tacaryl": "2",
 "tacrolimus": "2",
 "telavancin": "2",
 "tamoxen": "2",
 "tetrabenazine": "2",
 "tikosyn": "3",
 "thorazine": "2",
 "tykerb": "2"}, "w": {"wygesic": "2"}, "v": {"venelex": "2",
 "ventolin": "2",
 "vivactil": "2",
 "v-gan-50": "2",
 "veracolate": "2",
 "vasolex": "2",
 "vasopressin": "2",
 "ventolin hfa": "2",
 "votrient": "2",
 "vascor": "3",
 "voriconazole": "2",
 "volmax": "2",
 "vicks formula 44 custom care throat spray": "2",
 "vemurafenib": "3",
 "vardenafil": "2",
 "vospire er": "2",
 "vibativ": "2",
 "v-gan-25": "2",
 "vandetanib": "3",
 "vanatrip": "2",
 "vfend": "2"}, "y": {"yutopar": "2"}, "x": {"xopenex": "2",
 "xopenex hfa": "2",
 "xenaderm": "2",
 "x-prep": "2",
 "xalkori": "3",
 "xopenex concentrate": "2",
 "xenazine": "2"}, "z": {"zagam respipac": "3",
 "zmax": "2",
 "zanaflex": "2",
 "zofran": "2",
 "zelboraf": "3",
 "zagam": "3",
 "zofran odt": "2",
 "ziprasidone": "3",
 "zaponex": "3",
 "zuplenz": "2",
 "zithromax": "2"}}];