interactions["abiraterone"]=["abiraterone", {"4": {"40 winks": "2"}, "a": {"aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "atrohist pediatric capsule": "2",
 "agenerase": "2",
 "andecon pediatric drops": "2",
 "acetaminophen/dextromethorphan/doxylamine": "2",
 "allertan": "2",
 "acetaminophen/chlorpheniramine/pseudoephedrine": "2",
 "allerx pe": "2",
 "accuhist la": "2",
 "atuss-12 dx": "2",
 "alka-seltzer plus cold &amp; flu": "2",
 "atrohist pediatric": "2",
 "acetaminophen/dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "amdry-c": "2",
 "aspirin/diphenhydramine": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "acetaminophen/chlorpheniramine/guaifenesin/phenylpropanolamine": "2",
 "antispas": "2",
 "aler-dryl": "2",
 "aspirin/oxycodone": "2",
 "ambi 40/1000/60": "2",
 "acetaminophen/dextromethorphan/guaifenesin/phenylpropanolamine": "2",
 "advil pm": "2",
 "all-nite multi-symptom cold/flu relief": "2",
 "acetaminophen/dextromethorphan/guaifenesin/phenylephrine": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "alka-seltzer plus night cold formula liquid": "2",
 "ambenyl": "2",
 "a-g tussin": "2",
 "aventyl hydrochloride": "2",
 "ambi 80/780/40": "2",
 "alahist dm": "2",
 "allfen cdx": "2",
 "ah-chew": "2",
 "accuhist drops": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "atropine/chlorpheniramine/hyoscyamine/pseudoephedrine/scopolamine": "2",
 "alka-seltzer plus flu/body": "2",
 "anamine": "2",
 "alka-seltzer plus flu formula": "2",
 "adderall xr": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenyltoloxamine": "2",
 "ambifed-g dm": "2",
 "acetaminophen/chlorpheniramine/phenylpropanolamine": "2",
 "aricept odt": "1",
 "actifed cold and allergy": "2",
 "avonex": "2",
 "ambi 40 /400 /20": "2",
 "atomoxetine": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "ambi 60/580/30": "2",
 "allerest maximum strength": "2",
 "alka-seltzer plus cold &amp; cough formula liquid": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "alahist lq": "2",
 "ammonium chloride/chlorpheniramine/dextromethorphan/ephedrine/ipecac/phenylephrine": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "anhydrous calcium iodide/codeine": "2",
 "andehist dm nr": "2",
 "anaplex dmx": "2",
 "acetaminophen/dextromethorphan/guaifenesin/pseudoephedrine": "2",
 "albatussin pediatric drops": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/pseudoephedrine": "2",
 "acetaminophen/dextromethorphan/doxylamine/phenylephrine": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "accuhist pdx syrup": "2",
 "allerest sinus": "2",
 "aerokid": "2",
 "avonex prefilled syringe": "2",
 "atripla": "2",
 "accesspak for hiv pep expanded with viracept": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "altarussin dm": "2",
 "alka-seltzer plus mucus &amp; congestion": "2",
 "acetaminophen/diphenhydramine/pseudoephedrine": "2",
 "ah-chew ii": "2",
 "arava": "3",
 "anatuss": "2",
 "alacol dm": "2",
 "acetaminophen/dextromethorphan/phenylephrine": "2",
 "allergy dn pe": "2",
 "anergan 50": "2",
 "adrenocot": "2",
 "aricept": "1",
 "acetaminophen/chlorpheniramine": "2",
 "ah-chew ultra tannate": "2",
 "allfen dm": "2",
 "ambifed dm": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "all-nite cold": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "allermax": "2",
 "ambophen": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/scopolamine": "2",
 "atuss hd": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "alka-seltzer plus night cold formula liquid gels": "2",
 "alkabel-sr": "2",
 "advil allergy sinus": "2",
 "acetaminophen/dextromethorphan/pseudoephedrine": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "anaplex dm": "2",
 "allergy multi-symptom relief": "2",
 "aldex-ct": "2",
 "atuss hs": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "atrohist plus": "2",
 "allergia-c": "2",
 "alka-seltzer plus cold &amp; cough formula liquid gels": "2",
 "accuhist dm pediatric drops": "2",
 "aerohist plus": "2",
 "allanhist pdx syrup": "2",
 "alka-seltzer plus day non-drowsy cold formula liquid gels": "2",
 "allfen cd": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "aller-chlor": "2",
 "allerest headache strength": "2",
 "allerest pe": "2",
 "allergy sinus maximum strength": "2",
 "alka-seltzer plus cold": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "acetaminophen/dextromethorphan/diphenhydramine": "2",
 "accuhist pdx drops": "2",
 "allergy relief": "2",
 "acetaminophen/dextromethorphan": "2",
 "acetaminophen/caffeine/chlorpheniramine/phenylpropanolamine": "2",
 "abilify": "2",
 "acetaminophen/oxycodone": "2",
 "allerx dose pack": "2",
 "aquatab dm": "2",
 "ala-hist": "2",
 "alka-seltzer plus day &amp; night cold formula (night cold) liquid gels": "2",
 "acetaminophen/brompheniramine/dextromethorphan/pseudoephedrine": "2",
 "anacin p.m. aspirin free": "2",
 "alka-seltzer plus cold formula": "2",
 "antispasmodic": "2",
 "alka-seltzer pm": "2",
 "adapin": "2",
 "alka-seltzer plus day &amp; night cold formula (day cold) liquid gels": "2",
 "acetaminophen/codeine": "2",
 "alumadrine": "2",
 "allergy dn ii": "2",
 "aller-chlor decongestant": "2",
 "alka-seltzer plus severe sinus congestion &amp; cough": "2",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "aspirin/carisoprodol/codeine": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "ala-hist d": "2",
 "amphetamine/dextroamphetamine": "2",
 "allerfrin with codeine": "2",
 "allerx pe dose pack": "2",
 "anafranil": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/guaifenesin": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/phenylpropanolamine/scopolamine": "2",
 "antrocol": "2",
 "atuss ms": "2",
 "aceta w/ codeine": "2",
 "allergy dn": "2",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "acetaminophen pm extra strength": "2",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/pseudoephedrine": "2",
 "aldex dm": "2",
 "ambi 600/1000/30": "2",
 "arm allergy relief": "2",
 "ambifed-g cd": "2",
 "ahist": "2",
 "albatussin pediatric": "2",
 "aripiprazole": "2",
 "allerx df dose pack": "2",
 "adderall": "2",
 "allan tannate pediatric": "2",
 "altaryl": "2",
 "aerohist": "2",
 "airacof": "2",
 "actifed allergy day/night": "2",
 "acetaminophen/chlorpheniramine/phenylephrine": "2",
 "acetaminophen/propoxyphene": "2",
 "anaplex": "2",
 "allres ds": "2",
 "allerest 12 hour": "2",
 "alphen expectorant": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/phenylephrine": "2",
 "allepak": "2",
 "acetaminophen/dextromethorphan/doxylamine/pseudoephedrine": "2",
 "ah-chew ultra": "2",
 "accuhist dm pediatric syrup": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "ambenyl-d": "2",
 "acetaminophen/dextromethorphan/phenylpropanolamine": "2",
 "ambifed-g cdx": "2",
 "atropine/phenobarbital": "2",
 "altarussin cf": "2",
 "adrenocot la": "2",
 "atuss dm": "2",
 "atuss dr": "2",
 "atuss ds": "2",
 "ana-kit": "2",
 "acta-tabs pe": "2",
 "aldex gs dm": "2",
 "acutuss dm pediatric": "2",
 "atazanavir": "2",
 "anatuss dm": "2",
 "acetaminophen/tramadol": "2",
 "amprenavir": "2",
 "atuss-12 dm": "2",
 "aspirin/codeine": "2",
 "allanhist pdx drops": "2",
 "allergy am-pm dose pack": "2",
 "allerx df": "2",
 "amphetamine": "2",
 "acetaminophen/diphenhydramine": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "andehist dm nr syrup": "2",
 "ala-hist ac": "2",
 "ambifed cd": "2",
 "amilon": "2",
 "advil children's allergy sinus": "2",
 "anextuss": "2",
 "anamine td": "2",
 "allerx": "2",
 "anti-tuss dm": "2",
 "aler-tab": "2",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "2",
 "abilify discmelt": "2",
 "ambifed cdx": "2"}, "c": {"cycofed expectorant": "2",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "chlordex gp": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "compro": "2",
 "chlorpheniramine/hydrocodone/phenylephrine": "2",
 "cerebyx": "2",
 "chlorpheniramine/methscopolamine/phenylpropanolamine": "2",
 "chemdal expectorant": "2",
 "colrex compound": "2",
 "cycofed pediatric expectorant": "2",
 "cold multi-symptom severe": "2",
 "chlor-mal": "2",
 "combigan": "2",
 "comtrex allergy sinus night and day": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "coldcough pd": "2",
 "calcidrine": "2",
 "coricidin d": "2",
 "clorfed ii": "2",
 "c-phed tannate": "2",
 "crixivan": "2",
 "congestant": "2",
 "chlor-trimeton decongestant": "2",
 "coreg": "2",
 "chlor-mes": "2",
 "cpm-pe-msc": "2",
 "children's triacting daytime": "2",
 "chlor-phenit": "2",
 "colfed-a": "2",
 "chlorgest hd": "2",
 "contact cold and sore throat": "2",
 "combunox": "2",
 "cold &amp; cough pe multi-symptom": "2",
 "comtrex non-drowsy": "2",
 "cordron-dm nr": "2",
 "chlorpheniramine/hydrocodone": "2",
 "chlorpheniramine/guaifenesin/phenylephrine": "2",
 "cydec-dm syrup": "2",
 "chlorex a": "2",
 "chemdal hd plus": "2",
 "coldtuss-dr": "2",
 "codral cold and flu + cough day and night": "2",
 "chlorafed": "2",
 "coricidin hbp nighttime multi-symptom cold": "2",
 "coricidin hbp day &amp; night multi-symptom cold": "2",
 "codimal ph": "2",
 "comtrex nighttime flu therapy": "2",
 "co-histine expectorant": "2",
 "creo-terpin": "2",
 "cheracol with codeine": "2",
 "codimal dm": "2",
 "cough &amp; cold relief": "2",
 "cheratussin dac": "2",
 "c.p.m.": "2",
 "curaler": "2",
 "chlorphen": "2",
 "codeprex": "2",
 "cytuss hc": "2",
 "cough syrup dm": "2",
 "cold medicine plus": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "ceron": "2",
 "children's nyquil": "2",
 "cp dec-dm drops": "2",
 "contac 12 hour": "2",
 "clozapine": "2",
 "chlor-mes d": "2",
 "comtrex day and night": "2",
 "clear cough pm multi-symptom": "2",
 "capital w/codeine": "2",
 "cvs allergy &amp; cold": "2",
 "cough-x cough relief": "2",
 "codimal-la half": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "comtrex sinus and nasal": "2",
 "creomulsion pediatric": "2",
 "cheratussin ac": "2",
 "cyndal hd": "2",
 "codeine/phenylephrine": "2",
 "c-tanna 12": "2",
 "coldex": "2",
 "carb pse 12 dm": "2",
 "chlorpheniramine/phenylpropanolamine": "2",
 "chlorpheniramine/dextromethorphan/pseudoephedrine": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "codimal-la": "2",
 "children's tylenol plus cold and allergy": "2",
 "chlornade": "2",
 "comhist la": "2",
 "codafen": "2",
 "cough formula-dm": "2",
 "codeine/promethazine": "2",
 "codafed": "2",
 "compazine spansule": "2",
 "cough-x": "2",
 "comtrex allergy sinus": "2",
 "carvedilol": "2",
 "c-phed dm": "2",
 "carbetapentane/diphenhydramine": "2",
 "cp dec dm": "2",
 "carbetapentane/chlorpheniramine/phenylephrine": "2",
 "comtrex cold and flu maximum strength liquid": "2",
 "codegest expectorant": "2",
 "c phen": "2",
 "c phen drops": "2",
 "codeine/pseudoephedrine": "2",
 "coreg cr": "2",
 "coldmist dm": "2",
 "c-phen dm drops": "2",
 "coricidin hbp maximum strength flu": "2",
 "contac complete cough, cold &amp; flu extra strength": "2",
 "comtrex cold and flu maximum strength tablet": "2",
 "complete allergy": "2",
 "clofarabine": "2",
 "carbetapentane/chlorpheniramine/ephedrine/phenylephrine": "2",
 "colrex": "2",
 "chlordrine sr": "2",
 "chlorpheniramine/hydrocodone/pseudoephedrine": "2",
 "chlor-mes jr": "2",
 "clopine": "2",
 "chlorpheniramine/phenindamine/phenylpropanolamine": "2",
 "cp dec drops": "2",
 "comtrex cold and flu maximum strength": "2",
 "creomulsion children": "2",
 "chlorphedrin sr": "2",
 "clozaril": "2",
 "cpm-pse dm drops": "2",
 "chlorpheniramine/phenylephrine/pyrilamine": "2",
 "comtrex non drowsy liquigel": "2",
 "carbaphen 12": "2",
 "ceron drops": "2",
 "chlorex-a 12": "2",
 "compazine": "2",
 "corfen-dm": "2",
 "cotab ax": "2",
 "coldamine": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "clozapine synthon": "2",
 "chlorcyclizine/codeine": "2",
 "c-hist-sr": "2",
 "carbetapentane/chlorpheniramine": "2",
 "chlorpheniramine/dextromethorphan/guaifenesin/phenylephrine": "2",
 "conivaptan": "2",
 "chlorpheniramine/guaifenesin/pseudoephedrine": "2",
 "comtrex severe cold &amp; sinus": "2",
 "chlor-trimeton sinus": "2",
 "cough formula m multi-symptom": "2",
 "capital with codeine suspension": "2",
 "cocet plus": "2",
 "calm-aid": "2",
 "clarithromycin": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "c-phen dm": "2",
 "contac cold and flu maximum strength": "2",
 "children's triacting": "2",
 "cosopt": "2",
 "co-histine dh": "2",
 "cold head congestion": "2",
 "chest congestion relief dm": "2",
 "chlortox": "2",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "coricidin hbp chest congestion &amp; cough": "2",
 "chlorpheniramine": "2",
 "carbinoxamine/dextromethorphan/pseudoephedrine": "2",
 "cydec-dm drops": "2",
 "coryza-dm": "2",
 "clorfed": "2",
 "comtrex maximum strength cold relief": "2",
 "clomipramine": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "contac severe cold and flu non drowsy": "2",
 "cordron-hc nr": "2",
 "chlorpromazine": "2",
 "chlorafed hs timecelles": "2",
 "codehist dh": "2",
 "contac day and night allergy": "2",
 "chlor-trimeton allergy sr": "2",
 "carbaxef-dm": "2",
 "chemdal hd": "2",
 "cordron-dm": "2",
 "codahistine expectorant": "2",
 "capmist dm": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "chemtussin hc": "2",
 "cepacol dual relief sore throat + cough spray": "2",
 "calmylin": "2",
 "coricidin hbp cold &amp; flu": "2",
 "comhist": "2",
 "chlo-amine": "2",
 "chlorpheniramine/codeine": "2",
 "chlorpheniramine/phenylephrine/phenyltoloxamine": "2",
 "coricidin hbp cough &amp; cold": "2",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "condrin": "2",
 "carbamazepine": "2",
 "cyndal expectorant": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "chlorpheniramine/dextromethorphan/phenylephrine": "2",
 "ceron-dm": "2",
 "chlorpheniramine/phenylephrine": "2",
 "contac severe cold and flu maximum stength": "2",
 "comtrex cold &amp; cough": "2",
 "chlor-trimeton allergy decongestant sr": "2",
 "creomulsion cough/cold/allergy": "2",
 "chlorphen hd": "2",
 "cheracol plus": "2",
 "chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "cvs allergy &amp; sinus headache": "2",
 "c-phed dpd tann": "2",
 "cardec": "2",
 "children's triacting night time": "2",
 "codahistine-dh elixir": "2",
 "chlorpheniramine/epinephrine": "2",
 "cerose dm": "2",
 "chlorpheniramine/dextromethorphan/guaifenesin/methscopolamine/phenylephrine": "2",
 "cp-tannic": "2",
 "chlorpheniramine/methscopolamine/phenylephrine": "2",
 "contac cough": "2",
 "codal-dm syrup": "2",
 "chlorafed timecelles": "2",
 "childrens tylenol cold plus cough": "2",
 "certuss-d": "2",
 "carbodex dm drops": "2",
 "chlorpheniramine/dextromethorphan": "2",
 "clolar": "2",
 "codeine/phenylephrine/promethazine": "2",
 "cevimeline": "2",
 "codafed pediatric": "2",
 "centergy dm": "2",
 "cheracol-d": "2",
 "counteract pm extra strength": "2",
 "cardec dm": "2",
 "carbatrol": "2",
 "contac cold+flu maximum strength": "2",
 "cymbalta": "2",
 "chlortan": "2",
 "comtrex cold &amp; cough day night": "2",
 "covangesic": "2",
 "cocet": "2",
 "calmylin 4": "2",
 "conal": "2",
 "cp dec": "2",
 "comtussin hc": "2",
 "chlorpheniramine/methscopolamine": "2",
 "comtrex nighttime cold &amp; cough": "2",
 "cold &amp; cough childrens": "2",
 "chlor trimeton allergy decongestant": "2",
 "cotabflu": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "contac day and night cold and flu": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/phenyltoloxamine": "2",
 "carbodex dm syrup": "2",
 "chlorpheniramine/ephedrine/guaifenesin": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "cycofed": "2",
 "carboxine dm": "2",
 "ceron-dm drops": "2",
 "chlorpheniramine/methscopolamine/pseudoephedrine": "2",
 "cardec drops": "2",
 "chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "comtrex allergy sinus maximum strength": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "codeine/guaifenesin": "2",
 "chlor-trimeton": "2",
 "cardec dm drops": "2",
 "cosopt pf": "2",
 "carbofed dm syrup": "2",
 "chlorpheniramine/dextromethorphan/methscopolamine": "2",
 "codeine phosphate-promethazine hcl": "2",
 "compoz nighttime sleep aid": "2",
 "comtrex cold and cough maximum strength": "2",
 "covonia bronchial balsam": "2",
 "chardonna-2": "2",
 "chlorpheniramine/guaifenesin/methscopolamine/phenylephrine": "2",
 "carbinoxamine/dextromethorphan/phenylephrine": "2",
 "codituss dm": "2",
 "chlorpheniramine/pseudoephedrine": "2",
 "cordron-12 dm": "2",
 "creomulsion": "2",
 "carbofed dm drops": "2",
 "chlorpheniramine/guaifenesin/hydrocodone/pseudoephedrine": "2",
 "comtrex flu therapy": "2",
 "chlortan d": "2",
 "codimal": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "coricidin night time cold relief": "2",
 "contac severe cold/flu no-drowsiness": "2",
 "codeine": "2",
 "coldcough syrup": "2",
 "cepacol sore throat + cough relief": "2",
 "cophene no 2": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "coughtuss": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "cotab a": "2",
 "codeine/pseudoephedrine/triprolidine": "2",
 "cordron-hc": "2",
 "carboxine 12 dm": "2",
 "conzip": "2"}, "b": {"bellaphen-s": "2",
 "bromatane dx": "2",
 "benadryl-d allergy plus sinus": "2",
 "biaxin xl": "2",
 "bitex liquid": "2",
 "brovex cbx": "2",
 "benahist-50": "2",
 "biaxin": "2",
 "brom tann": "2",
 "bidex-a": "2",
 "bromaxefed dm rf syrup": "2",
 "benaphen plus": "2",
 "brompheniramine/dextromethorphan/guaifenesin/phenylpropanolamine": "2",
 "bayer pm": "2",
 "bromaline dm": "2",
 "brovex peb dm": "2",
 "benylin dm": "2",
 "bromodiphenhydramine/codeine": "2",
 "buckleys mixture": "2",
 "balminil dm + decongestant": "2",
 "bel-phen-ergot": "2",
 "bystolic": "2",
 "babee cof": "2",
 "benadryl": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "bisolvon dry junior": "2",
 "benzocaine/dextromethorphan": "2",
 "biospec dmx": "2",
 "benadryl allergy plus cold": "2",
 "brovex pb cx": "2",
 "brovex cb": "2",
 "brompheniramine/dextromethorphan/pseudoephedrine": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "benadryl children's allergy and sinus": "2",
 "balacall dm": "2",
 "brovex pse dm": "2",
 "benadryl allergy sinus": "2",
 "biotussin dac": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "buckley's mixture cough suppressant": "2",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "betaseron": "2",
 "brompheniramine/chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "bromatan-dm": "2",
 "benadryl allergy": "2",
 "balacet": "2",
 "bromhist-pdx": "2",
 "biocotron": "2",
 "bellaspas": "2",
 "balminil dm + expectorant sugar free": "2",
 "benadryl allergy plus sinus headache": "2",
 "black cohosh": "2",
 "brovex psb dm": "2",
 "boceprevir": "2",
 "bromtuss dm": "2",
 "bromtann/dm tann/pse tann": "2",
 "baycadron": "2",
 "bellamine": "2",
 "bel-tabs": "2",
 "belix": "2",
 "beldin": "2",
 "brompheniramine/dextromethorphan/guaifenesin/phenylephrine": "2",
 "bisolvon dry": "2",
 "bromfed dm": "2",
 "benylin dm-d": "2",
 "bromhist-dm drops": "2",
 "benahist-10": "2",
 "benylin expectorant": "2",
 "banophen": "2",
 "benylin multi-symptom": "2",
 "barbidonna": "2",
 "bromanate dx cough": "2",
 "bromatan plus": "2",
 "benadryl severe allergy &amp; sinus headache": "2",
 "brovex pb dm": "2",
 "betimol": "2",
 "bydramine": "2",
 "balminil dm + decongestant + expectorant": "2",
 "brompheniramine/codeine": "2",
 "bromadine-dm": "2",
 "brometane dx": "2",
 "bp allergy dm": "2",
 "brompheniramine/diphenhydramine": "2",
 "bromtapp-dm": "2",
 "benylin dm-d-e": "2",
 "brompheniramine/dextromethorphan/phenylephrine": "2",
 "broncotron-d": "2",
 "bromph dm": "2",
 "brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "bronkotuss": "2",
 "bellergal-s": "2",
 "banaril": "2",
 "bellalphen": "2",
 "bellamine s": "2",
 "b-tuss": "2",
 "broncopectol": "2",
 "bellatal er": "2",
 "benadryl severe allergy plus sinus headache": "2",
 "blocadren": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "brexin la": "2",
 "brovex pse dm tablets": "2",
 "ben-tann": "2",
 "bronkids": "2",
 "brontex": "2",
 "biodec dm": "2",
 "benoject-50": "2",
 "bidex-dmi": "2",
 "bromplex dm": "2",
 "biohist la": "2",
 "balminil dm": "2",
 "balminil cough and flu sugar free": "2",
 "brovex pb c": "2",
 "bromphenex dm": "2",
 "bromhist-dm": "2",
 "bellamor": "2",
 "bellahist-d la": "2",
 "benadryl children's allergy": "2",
 "brompheniramine/dextromethorphan/guaifenesin/pseudoephedrine": "2",
 "brimonidine/timolol ophthalmic": "2",
 "bpm pe dm": "2",
 "brompheniramine/codeine/pseudoephedrine": "2",
 "bellatal": "2",
 "bromophed-dx": "2",
 "brontuss": "2",
 "bromdex d": "2",
 "benadryl cold": "2",
 "bp allergy jr": "2"}, "e": {"efasin-hd plus": "2",
 "ed chlorped": "2",
 "endacon dm": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "e.e.s.-400": "2",
 "endacof-ac": "2",
 "ed chlor-tan": "2",
 "endodan": "2",
 "endacof-pd": "2",
 "eryped": "2",
 "erythromycin/sulfisoxazole": "2",
 "exefen-dmx": "2",
 "execlear-dm": "2",
 "endocet": "2",
 "esocor p": "2",
 "embeda": "2",
 "eperbel-s": "2",
 "extendryl sr": "2",
 "endal hd": "2",
 "extendryl dm": "2",
 "execlear-c": "2",
 "erythrocot": "2",
 "evoxac": "2",
 "exo-tuss": "2",
 "erythromycin": "2",
 "endacof-c": "2",
 "elixiral": "2",
 "ez iii": "2",
 "excedrin pm": "2",
 "efasin-hd": "2",
 "endacon": "2",
 "endal expectorant": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "endal cd": "2",
 "e s p": "2",
 "e.e.s.-200": "2",
 "etrafon forte": "2",
 "endagen-hd": "2",
 "execof er": "2",
 "equetro": "2",
 "epitol": "2",
 "extendryl seniors": "2",
 "efavirenz": "2",
 "emtricitabine/nelfinavir/tenofovir": "2",
 "effexor xr": "2",
 "endacof-dc": "2",
 "ed a-hist": "2",
 "extendryl jr": "2",
 "erythrocin lactobionate": "2",
 "e.e.s.-400 filmtab": "2",
 "endacof-dm": "2",
 "equitan pediatric": "2",
 "e-mycin": "2",
 "endocodone": "2",
 "ex-tuss": "2",
 "eth-oxydose": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "efasin expectorant sf": "2",
 "eryzole": "2",
 "effective strength cough syrup": "2",
 "echotuss-hc": "2",
 "extuss la": "2",
 "endotuss expectorant": "2",
 "exetuss-dm": "2",
 "enablex": "2",
 "enditussin expectorant": "2",
 "endotuss-hd": "2",
 "ery-tab": "2",
 "ed a-hist dm": "2",
 "ed a-hist la": "2",
 "endacof pd drops": "2",
 "entre-s": "2",
 "etrafon": "2",
 "exratuss": "2",
 "ed dm": "2",
 "ex-histine": "2",
 "emblon": "3",
 "endal-hd plus": "2",
 "e.e.s. granules": "2",
 "eryc": "2",
 "elixsure cough": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "effexor": "2",
 "extavia": "2",
 "erythrocin": "2",
 "equate allergy &amp; sinus headache": "2",
 "erythrocin stearate filmtab": "2",
 "ed-tuss hc": "2",
 "enplus-hd": "2",
 "exefen-dm": "2",
 "empirin with codeine": "2",
 "equi-nade": "2",
 "ed-tlc": "2",
 "extendryl chews": "2",
 "ed chlorped d": "2"}, "d": {"dytan-d": "2",
 "deconex dm": "2",
 "desyrel": "2",
 "drymax": "2",
 "drotuss-cp": "2",
 "delavirdine": "2",
 "dynahist er": "2",
 "donatussin dm suspension": "2",
 "donnatal": "2",
 "duravent da": "2",
 "duratan forte": "2",
 "duradryl chewable": "2",
 "dimetane dc": "2",
 "detrol": "1",
 "dextromethorphan/pheniramine/phenylephrine": "2",
 "duradex": "2",
 "diphenydramine quick melt": "2",
 "deconhist la": "2",
 "duraphen forte": "2",
 "dutasteride/tamsulosin": "2",
 "durahist pe": "2",
 "drixoral cough/sore throat": "2",
 "drituss dm": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine": "2",
 "dicopanol": "2",
 "dexbrompheniramine/dextromethorphan/pseudoephedrine": "2",
 "dry cough": "2",
 "dextromethorphan/quinidine": "2",
 "dextromethorphan/doxylamine": "2",
 "delsym night time multi-symptom": "2",
 "dexchlorpheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "day relief cold and flu": "2",
 "dextromethorphan/pseudoephedrine": "2",
 "duralex": "2",
 "diphendryl": "2",
 "demi-cof": "2",
 "dimetapp children's long acting cough plus cold": "2",
 "dextromethorphan/guaifenesin/phenylpropanolamine": "2",
 "despec nr drops": "2",
 "ditussin-hc": "2",
 "diphenhydramine": "2",
 "dorcol childrens cough": "2",
 "dexchlorpheniramine/dextromethorphan/pseudoephedrine": "2",
 "dytan-dm": "2",
 "da ii": "2",
 "drihist": "2",
 "donatussin pediatric": "2",
 "doans pm": "2",
 "dazidox": "2",
 "dec-chlorphen drops": "2",
 "detuss": "2",
 "duraflu": "2",
 "decadron with xylocaine": "2",
 "duradex forte": "2",
 "dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "dextromethorphan": "2",
 "donnatal extentabs": "2",
 "dextromethorphan/phenylephrine/pyrilamine": "2",
 "duraganidin nr": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "dextromethorphan hbr adult formula": "2",
 "diabetic tussin night time formula": "2",
 "dph": "2",
 "dexamethasone/lidocaine": "2",
 "dextromethorphan/guaifenesin/potassium guaiacolsulfonate": "2",
 "darvon compound 32": "2",
 "dalalone la": "2",
 "dmax pediatric drops": "2",
 "dacex-a": "2",
 "dexone": "2",
 "dura-vent/a": "2",
 "duohist dh": "2",
 "dihistine dh": "2",
 "dehistine": "2",
 "desoxyn": "2",
 "drize": "2",
 "dex-tuss": "2",
 "dallergy pse": "2",
 "dimacol": "2",
 "dihistine": "2",
 "duratuss dm 12": "2",
 "dexodryl": "2",
 "duratan dm": "2",
 "dristan cold multi symptom formula": "2",
 "diphenhydramine/phenylephrine": "2",
 "diphenmax": "2",
 "despec-pd": "2",
 "dallergy pe": "2",
 "dec-chlorphen dm drops": "2",
 "dexacort phosphate in turbinaire": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "deconsal dm tannate": "2",
 "daytime cold &amp; flu": "2",
 "dextromethorphan/phenylephrine": "2",
 "diphedryl": "2",
 "dynatuss": "2",
 "diphenyl": "2",
 "donatussin": "2",
 "dutoprol": "2",
 "donnapine": "2",
 "doxepin": "2",
 "dexall": "2",
 "dm cold and cough": "2",
 "dacex-pe": "2",
 "dimetapp children's multi-symptom cold &amp; flu": "2",
 "darifenacin": "2",
 "diphen af": "2",
 "dicomal-ph": "2",
 "di-delamine": "2",
 "dihydro-pe": "2",
 "dicel": "2",
 "d-tann": "2",
 "dexacort-la": "2",
 "duotan": "2",
 "diphenhydramine/tripelennamine topical": "2",
 "dexcon-pe": "2",
 "dimaphen dm": "2",
 "delsym 12 hour cough relief": "2",
 "dmax": "2",
 "dexatrex d": "2",
 "dytan": "2",
 "de-chlor hc": "2",
 "dexamethasone": "2",
 "duravent": "2",
 "decohistine dh": "2",
 "dilantin": "2",
 "diphen": "2",
 "dmax pediatric": "2",
 "dihydro-cp": "2",
 "duragal-s": "2",
 "durahistine dm": "2",
 "delhistine dm": "2",
 "daytime non-drowsy": "2",
 "diphenylin": "2",
 "drixoral cough &amp; congestion liquid caps": "2",
 "delsym children's night time cough &amp; cold": "2",
 "despec drops": "2",
 "duraphen dm": "2",
 "demazin": "2",
 "dytan-at": "2",
 "dallergy jr": "2",
 "deproist with codeine": "2",
 "decohistine expectorant": "2",
 "dexasone": "2",
 "dm-pe-chlor": "2",
 "durafed": "2",
 "duo-vil": "2",
 "dura-ron dm": "2",
 "duratuss da": "2",
 "deconamine": "2",
 "deconex dmx": "2",
 "darvon-n": "2",
 "dexcon-dm": "2",
 "duratuss dm": "2",
 "duradryl sr": "2",
 "dihistine expectorant": "2",
 "duradryl jr": "2",
 "diphenadryl": "2",
 "d-tann at": "2",
 "despec dm syrup": "2",
 "duradryl": "2",
 "diphenhydramine/guaifenesin": "2",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "darvon": "2",
 "dytan-hc": "2",
 "da chewable": "2",
 "dexi-tuss": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "dexasone la": "2",
 "duratan pe": "2",
 "dynahist-er pediatric": "2",
 "dexchlorpheniramine/dextromethorphan/phenylephrine": "2",
 "donatussin dm syrup": "2",
 "dec-chlorphen": "2",
 "dexamethasone intensol": "2",
 "dryphen": "2",
 "darvon compound-65": "2",
 "dextromethorphan/guaifenesin": "2",
 "desipramine": "2",
 "dec-chlorphen dm": "2",
 "duratuss ac 12": "2",
 "decadron phosphate, injectable": "2",
 "duravent dpb": "2",
 "desyrel dividose": "2",
 "duadacin": "2",
 "dextromethorphan/phenylpropanolamine": "2",
 "daytime liquicap": "2",
 "decadron": "2",
 "denaze": "2",
 "d-tal": "2",
 "de-sone la": "2",
 "duraphen ii dm": "2",
 "d-amine-sr": "2",
 "d-tann hc": "2",
 "donepezil": "1",
 "dextromethorphan/guaifenesin/pseudoephedrine": "2",
 "dexacort phosphate in respihaler": "2",
 "dihistine expectorant with codeine": "2",
 "dcp drops": "2",
 "duramax": "2",
 "deconsal c expectorant": "2",
 "denzapine": "2",
 "de-congestine": "2",
 "dalalone dp": "2",
 "dynatuss ex": "2",
 "d-tann dm": "2",
 "dorzolamide/timolol ophthalmic": "2",
 "daytime cold and flu relief": "2",
 "dexalone": "2",
 "day time multi symptom": "2",
 "dicel dm": "2",
 "d-tann cd": "2",
 "diphentann-d": "2",
 "delsym 12 hour cough relief for children &amp; adults": "2",
 "dimetapp children's cold &amp; cough": "2",
 "desoxyn gradumet": "2",
 "darvocet-n 100": "2",
 "decadron-la": "2",
 "dextromethorphan/doxylamine/pseudoephedrine": "2",
 "dytuss": "2",
 "de-chlor hd": "2",
 "dimetapp toddler's drops decongestant plus cough": "2",
 "d-tann ct": "2",
 "detrol la": "1",
 "dallergy er": "2",
 "diabetic tuss dm": "2",
 "dextromethorphan/potassium guaiacolsulfonate": "2",
 "dormin": "2",
 "de-chlor dr": "2",
 "drysec": "2",
 "dexacorten": "2",
 "dexfenfluramine": "2",
 "dmax syrup": "2",
 "dexacen-4": "2",
 "duradal hd": "2",
 "dextromethorphan/promethazine": "2",
 "depade": "2",
 "dimetapp children's nighttime flu": "2",
 "dur-tann dm": "2",
 "dimetane dx": "2",
 "diphenhist": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diabetic tussin c": "2",
 "decahist-dm": "2",
 "deconomed sr": "2",
 "de-chlor dm": "2",
 "daytime cold": "2",
 "donatussin dm drops": "2",
 "diphenmax d": "2",
 "drihist sr": "2",
 "dallergy dm": "2",
 "decaject la": "2",
 "delsym night time cough &amp; cold": "2",
 "deconsal dm": "2",
 "durahist": "2",
 "dur-tann forte": "2",
 "dura-tap/pd": "2",
 "donnaphen": "2",
 "dexodryl suspension": "2",
 "diphen cough": "2",
 "dexone la": "2",
 "dallergy drops": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "delsym": "2",
 "duotan dm": "2",
 "diphenhydramine/ibuprofen": "2",
 "duloxetine": "2",
 "dalalone": "2",
 "donatussin dm": "2",
 "diphenhydramine/pseudoephedrine": "2",
 "dex pc": "2",
 "dexpak taperpak": "2",
 "deconamine sr": "2",
 "decongestant cold formula": "2",
 "decongex-3": "2",
 "dextromethorphan/guaifenesin/phenylephrine": "2",
 "dytan-cd": "2",
 "dristan dm": "2",
 "despec dm": "2",
 "darvocet-n 50": "2",
 "dytan-cs": "2",
 "decaject": "2",
 "dacex-dm": "2",
 "darvocet a500": "2"}, "g": {"genahist": "2",
 "guiadrine dm": "2",
 "guaifen-c": "2",
 "gg-dm sr": "2",
 "guaifenesin dm": "2",
 "guiatuss dm": "2",
 "guaiasorb cough medicine": "2",
 "g-phen dm": "2",
 "guaifen ac": "2",
 "guaitussin ac": "2",
 "gendecon": "2",
 "gencold": "2",
 "guaifenex dm rx": "2",
 "genapap pm": "2",
 "genatuss dm": "2",
 "guiatuss dac": "2",
 "genacol maximum strength": "2",
 "guiatuss ac": "2",
 "guiatussin with codeine": "2",
 "gelpirin-ccf": "2",
 "guiadex dm": "2",
 "guaifen dm nr": "2",
 "guiadrine dx": "2",
 "guaifenesin dm sr": "2",
 "guiatuss clear": "2",
 "guai-co": "2",
 "gani-tuss nr": "2",
 "galantamine": "2",
 "guiatussin dac": "2",
 "guai-dex": "2",
 "gua pc": "2",
 "gestuss-hc": "2",
 "giltuss ped-c": "2",
 "guiatussin-cf": "2",
 "giltuss tr": "2",
 "guaphen ii dm": "2",
 "glydeine": "2",
 "guaifen dm": "2",
 "guiatuss cf": "2",
 "gani-tuss-dm nr": "2",
 "guaifenesin dac liquid": "2",
 "genamin": "2",
 "gg/dm": "2",
 "genox": "3",
 "guaifenex dm": "2",
 "guiaphen hd": "2",
 "gdp-ex": "2",
 "gelhist pediatric": "2",
 "glycotuss-dm": "2",
 "genrx tramadol": "2",
 "guaphen forte": "2",
 "genelan nf": "2",
 "guiatussin-dm": "2",
 "guaiatussin ac": "2",
 "guaifen dac": "2",
 "guiat clear dm": "2",
 "genaphed plus": "2",
 "guaiatussin dac": "2",
 "guiacough dm": "2"}, "f": {"fiorinal with codeine iii": "2",
 "flu &amp; severe cold &amp; cough daytime powder": "2",
 "folex pfs": "2",
 "flomax": "2",
 "fazaclo": "2",
 "fiorinal with codeine": "2",
 "fioricet with codeine": "2",
 "fluvoxamine": "2",
 "flecainide": "2",
 "fedahist": "2",
 "fedahist timecaps": "2",
 "fenfluramine": "2",
 "fenesin dm": "2",
 "fedahist gyrocaps": "2",
 "fiortal with codeine": "2",
 "flutabs": "2",
 "floricet with codeine": "2",
 "fenesin dm ir": "2",
 "fluoxetine": "2",
 "fluoxetine/olanzapine": "2",
 "father john's medicine plus": "2",
 "fortovase": "2",
 "fosamprenavir": "2",
 "fosphenytoin": "2",
 "fenex-dm": "2",
 "fluphenazine": "2"}, "i": {"iobid dm": "2",
 "isoniazid/rifampin": "2",
 "innopran xl": "2",
 "indinavir": "2",
 "invirase": "2",
 "iophen-c nr": "2",
 "incivek": "2",
 "ibuprofen/oxycodone": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "imipramine": "2",
 "inderide la": "2",
 "iofen-dm nf": "2",
 "itraconazole": "2",
 "inderide": "2",
 "iophen dm nr": "2",
 "isophen-df": "2",
 "ilosone": "2",
 "inderal la": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "isonarif": "2",
 "iophen dm": "2",
 "iohist dm": "2",
 "istalol": "2",
 "iotussin hc": "2",
 "inderal": "2",
 "iophen": "2",
 "iodal hd": "2",
 "ipsatol cough formula": "2"}, "h": {"humibid cs": "2",
 "hydron pcs": "2",
 "haloperidol": "2",
 "hydro-tussin dhc": "2",
 "halotussin dac": "2",
 "headache formula pm": "2",
 "highland dm": "2",
 "histalet forte": "2",
 "histinex hc": "2",
 "halotussin dm sugar free": "2",
 "hydrocodone hd": "2",
 "hydro-tuss dm": "2",
 "hyrexin": "2",
 "hydrochlorothiazide/propranolol": "2",
 "hydrochlorothiazide/timolol": "2",
 "hydrocodone gf": "2",
 "hydrocof-hc": "2",
 "hydro-pc ii plus": "2",
 "ht tuss dm": "2",
 "histade cr": "2",
 "highland hc": "2",
 "hold": "2",
 "hytan": "2",
 "hista-vent pse": "2",
 "hot lemon cough and colds relief dm": "2",
 "hayfebrol liquid": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hista-vadrin": "2",
 "hydrocodone cp": "2",
 "hexatussin": "2",
 "hyphen-hd": "2",
 "hydramine compound": "2",
 "histacol dm pediatric syrup": "2",
 "halotussin dm": "2",
 "humibid dm": "2",
 "hydro-dp": "2",
 "h-c tussive": "2",
 "hycomine compound": "2",
 "hista-vent da": "2",
 "heb allergy": "2",
 "histussin hc liquid": "2",
 "halotussin ac": "2",
 "hydramine": "2",
 "histatab ph": "2",
 "hydrotuss hc": "2",
 "haldol decanoate": "2",
 "hi-tuss hc": "2",
 "histinex pv": "2",
 "hyosophen": "2",
 "histex": "2",
 "humigen dm": "2",
 "histafed la": "2",
 "histade": "2",
 "haponal": "2",
 "histatan": "2",
 "histalet": "2",
 "hydro-pc ii": "2",
 "histadecdm": "2",
 "humibid dm pediatric": "2",
 "histatab plus": "2",
 "histacol bd drops": "2",
 "hydramine cough syrup": "2",
 "histinex dm": "2",
 "histatab": "2",
 "hyphed": "2",
 "hexadrol": "2",
 "hydron cp": "2",
 "hold dm": "2",
 "hyoscyamine/phenobarbital": "2",
 "headache relief pm": "2",
 "haldol": "2",
 "histadec": "2"}, "k": {"kolephrin": "2",
 "kaletra": "2",
 "kg-dal hd plus": "2",
 "kidcare cough and cold": "2",
 "kophane": "2",
 "ketek": "2",
 "kronofed-a-jr": "2",
 "kg hist dm": "2",
 "kg-fed pediatric expectorant": "2",
 "kg-tussin": "2",
 "kg-dal hd": "2",
 "ketoconazole": "2",
 "kolephrin gg/dm": "2",
 "kronofed-a": "2",
 "kg-fed expectorant": "2",
 "klerist-d": "2",
 "kita la tos": "2",
 "ketek pak": "2",
 "kg-fed": "2"}, "j": {"jack &amp; jill thin strips cough": "2",
 "jalyn": "2",
 "jaycof-hc": "2"}, "m": {"m-end wc": "2",
 "maxifed cdx": "2",
 "m-oxy": "2",
 "mexitil": "2",
 "mytussin dm": "2",
 "myphetane dc": "2",
 "magnacet": "2",
 "myphetane dx": "2",
 "mintex dm": "2",
 "m-phen": "2",
 "maldec-dm": "2",
 "mescolor": "2",
 "mar-cof bp": "2",
 "m-clear": "2",
 "medent dm": "2",
 "m-clear wc": "2",
 "metozolv odt": "2",
 "midodrine": "2",
 "morphine/naltrexone": "2",
 "mindal dm": "2",
 "midol pm": "2",
 "maxi-tuss dm": "2",
 "mucinex children's multi-symptom cold": "2",
 "methotrexate": "2",
 "maxiflu dm": "2",
 "mucus relief complete": "2",
 "maxifed-g cdx": "2",
 "maxichlor pse dm": "2",
 "methamphetamine": "2",
 "mapap cough &amp; sinus formula": "2",
 "medent-dmi": "2",
 "metoclopramide": "2",
 "maxiphen dm": "2",
 "mycobutin": "2",
 "meprozine": "2",
 "mucinex cough for kids": "2",
 "mucus relief plus": "2",
 "maxiphen-g dm": "2",
 "m-end pe": "2",
 "mudrane": "2",
 "maxi-tuss sa": "2",
 "maxifed cd": "2",
 "mintab dm": "2",
 "multi symptom cough and cold": "2",
 "mardrops-dx": "2",
 "medidex la": "2",
 "mapap pm": "2",
 "mytussin ac": "2",
 "mesehist dm": "2",
 "maxiflu cd": "2",
 "mintuss ms": "2",
 "maxiphen cd": "2",
 "maxifed-g cd": "2",
 "mucinex dm": "2",
 "mellaril-s": "3",
 "myphetane dx cough": "2",
 "monafed dm": "2",
 "myhist-pd": "2",
 "mintex": "2",
 "mucus relief cough": "2",
 "mexiletine": "2",
 "mepergan": "2",
 "mucobid dm": "2",
 "medent c": "2",
 "maxiphen cdx": "2",
 "mastussin dm": "2",
 "menopause support": "2",
 "maxi-tuss hcx": "2",
 "metoprolol succinate er": "2",
 "maxiflu cdx": "2",
 "maxiphen adt": "2",
 "m-end dmx": "2",
 "metoprolol": "2",
 "muco-fen dm": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "maxi-tuss hc": "2",
 "m-end dm": "2",
 "methotrimeprazine": "2",
 "mapap cold formula": "2",
 "mudrane gg": "2",
 "methotrexate lpf sodium": "2",
 "meperidine/promethazine": "2",
 "myhist-dm": "2",
 "miles nervine": "2",
 "muco-fen 800 dm": "2",
 "mucus relief dm": "2",
 "maxichlor peh dm": "2",
 "mytussin dac": "2",
 "motrin pm": "2",
 "maxifed dm": "2",
 "mepergan fortis": "2",
 "maprotiline": "2",
 "maxolon": "2",
 "mellaril": "3",
 "mintuss dr": "2",
 "med-rx dm": "2",
 "medidex": "2",
 "maxifed dmx": "2",
 "methdilazine": "2",
 "mesoridazine": "2"}, "l": {"little colds multi-symptom": "2",
 "ludiomil": "2",
 "luminal": "2",
 "liquitussin hc syrup": "2",
 "linhist-l.a.": "2",
 "liquituss r-dm": "2",
 "liquicough dm": "2",
 "levsin with phenobarbital": "2",
 "little colds decongestant/cough": "2",
 "liquiphed dm": "2",
 "liquihistine dm": "2",
 "lohist-dm": "2",
 "liquicough hc": "2",
 "levoprome": "2",
 "luvox": "2",
 "leflunomide": "3",
 "luvox cr": "2",
 "lortuss dm": "2",
 "lopinavir/ritonavir": "2",
 "largon": "2",
 "legatrin pm": "2",
 "lopressor": "2",
 "lotussin dm": "2",
 "lopressor hct": "2",
 "lemohist plus": "2",
 "lufyllin-epg": "2",
 "lohist-d": "2",
 "lexuss 210 liquid": "2",
 "lexiva": "2",
 "liqui-allergy": "2",
 "liquihistine cs": "2"}, "o": {"orap": "3",
 "ornade spansules": "2",
 "orvaten": "2",
 "oleptro": "2",
 "ormazine": "2",
 "oxyir": "2",
 "oxydose": "2",
 "omnihist ii la": "2",
 "oxycet": "2",
 "oxycontin": "2",
 "omnihist l.a.": "2",
 "oxycodone": "2",
 "orlenta": "2",
 "or-phen-ade": "2",
 "ordrine": "2",
 "oxamniquine": "2",
 "oxecta": "2",
 "oxyfast": "2"}, "n": {"neo dm drops": "2",
 "nytol": "2",
 "nuedexta": "2",
 "nolvadex d": "3",
 "narvox": "2",
 "nucodine": "2",
 "nebivolol": "2",
 "nohist": "2",
 "novahistine expectorant": "2",
 "nolamine": "2",
 "novafed a": "2",
 "nu-med": "2",
 "nizoral": "2",
 "neo dm syrup": "2",
 "novahistine dm": "2",
 "novahistine dh": "2",
 "nalex-a": "2",
 "naldecon": "2",
 "norpramin": "2",
 "nucodine pediatric": "2",
 "nuco-tuss pediatric expectorant": "2",
 "norel dm": "2",
 "nasatuss": "2",
 "nalphen dx pediatric": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "naldecon-cx adult": "2",
 "nohist pe": "2",
 "nohist ext": "2",
 "nyquil cold medicine": "2",
 "notuss-nxd": "2",
 "neutrahist drops": "2",
 "notuss-pe": "2",
 "nohist-dmx": "2",
 "norvir": "2",
 "nyquil multi-symptom": "2",
 "naldelate": "2",
 "neocitran thin strips cough": "2",
 "nytol caplet": "2",
 "naldecon-dx childrens": "2",
 "novahistine dm expectorant with decongestant": "2",
 "nalgest": "2",
 "naldelate dx childrens": "2",
 "nelfinavir": "2",
 "notuss-ac": "2",
 "neotuss plus": "2",
 "notuss-nx": "2",
 "nortuss-de": "2",
 "novahistine": "2",
 "notuss": "2",
 "nd clear": "2",
 "novagest with codeine": "2",
 "nucochem": "2",
 "nalex a 12": "2",
 "night time pain": "2",
 "nalex ac": "2",
 "nasohist-dm": "2",
 "nortriptyline": "2",
 "nohist plus": "2",
 "nasotuss": "2",
 "nucosef dm": "2",
 "nucofed pediatric expectorant": "2",
 "naltrexone": "2",
 "nolvadex": "3",
 "nucodine expectorant": "2",
 "neo ac": "2",
 "nyquil": "2",
 "novasus": "2",
 "nohist-a": "2",
 "notuss-forte": "2",
 "nalspan": "2",
 "nuco-tuss expectorant": "2",
 "neo hc": "2",
 "nohist-pdx": "2",
 "nasohist pediatric": "2",
 "nalgestic pediatric": "2",
 "nalphen dx childrens": "2",
 "nohist plus jr": "2",
 "norel sd": "2",
 "nalspan senior dx": "2",
 "norel sr": "2",
 "nighttime cough": "2",
 "nervine": "2",
 "norvir soft gelatin": "2",
 "naldecon senior dx": "2",
 "novadyne dh": "2",
 "neutrahist pdx drops": "2",
 "non-pseudo cold relief": "2",
 "ny-tannic": "2",
 "novahistine elixir": "2",
 "naldecon-dx adult": "2",
 "notuss-dc": "2",
 "nalphen": "2",
 "nalex-a sr": "2",
 "nuhist": "2",
 "novahistine dmx": "2",
 "non-drowsy super strength contac complete": "2",
 "naldelate dx pediatric": "2",
 "nucofed expectorant": "2",
 "nightime sleepaid": "2",
 "nucofed": "2",
 "novadyne expectorant": "2",
 "nalda-relief pediatric": "2",
 "naldecon-dx pediatric": "2",
 "neocitran non drowsy extra strength cold and flu": "2",
 "nefazodone": "2",
 "naldecon dx liquigel": "2"}, "q": {"qdall": "2",
 "qual-tussin pediatric": "2",
 "qv-allergy": "2",
 "quartuss dm": "2",
 "quad tuss pediatric": "2",
 "quad tann pediatric": "2",
 "q-tussin cf": "2",
 "quad tann": "2",
 "q-v tussin": "2",
 "q-dryl a/f": "2",
 "quadrapax": "2",
 "quartuss": "2",
 "quenalin": "2",
 "quadratuss": "2",
 "qual-tussin": "2",
 "quindal hd": "2",
 "q-bid dm": "2",
 "q-hist la": "2",
 "quadrinal": "2",
 "q-tussin dm": "2",
 "quindal hd plus": "2",
 "q-dryl": "2",
 "quelidrine": "2",
 "qc cough/cold": "2",
 "q-tapp dm": "2",
 "quad-tuss": "2"}, "p": {"pseudo cough": "2",
 "pediatan": "2",
 "poly-tussin ac": "2",
 "poly-histine cs": "2",
 "pse brom dm": "2",
 "pyrichlor pe": "2",
 "pediazole": "2",
 "pediacon dx": "2",
 "phendal-hd": "2",
 "pe-hist dm": "2",
 "phlemex forte": "2",
 "pse allergy dm": "2",
 "pedituss": "2",
 "pindolol": "2",
 "pertussin cs childrens": "2",
 "phenhist expectorant": "2",
 "pcm": "2",
 "phrenilin with caffeine and codeine": "2",
 "propiomazine": "2",
 "pyrroxate": "2",
 "protuss dm": "2",
 "phenylhistine expectorant": "2",
 "phenaphen with codeine": "2",
 "pardryl": "2",
 "prolixin": "2",
 "pdm gg": "2",
 "pd-hist d": "2",
 "phenadoz": "2",
 "pediahist dm drops": "2",
 "phenergan vc": "2",
 "phenflu dm": "2",
 "poly tan dm": "2",
 "poly dm": "2",
 "pseudo dm gg": "2",
 "prochlorperazine": "2",
 "protid": "2",
 "p-hist dm drops": "2",
 "phenylephrine/promethazine": "2",
 "promethazine with codeine": "2",
 "pseudodine c": "2",
 "phenylhistine dh": "2",
 "phenazine 50": "2",
 "permitil": "2",
 "protuss tablet": "2",
 "pediacare children's allergy": "2",
 "poly histine dm": "2",
 "prohistine dm": "2",
 "pediatex hc": "2",
 "paxil": "2",
 "percodan": "2",
 "phenytek": "2",
 "pediacof": "2",
 "pb-hyos": "2",
 "pseudo max dmx": "2",
 "pondimin": "2",
 "phlemgesic": "2",
 "percogesic extra strength": "2",
 "primethasone": "2",
 "polytine cs": "2",
 "percocet 10/325": "2",
 "pseudoephedrine plus": "2",
 "pediatex-ct": "2",
 "proamatine": "2",
 "promethazine with dm": "2",
 "percodan-demi": "2",
 "promethazine vc with codeine": "2",
 "pediox chewable": "2",
 "poly cs": "2",
 "phenadex": "2",
 "p chlor gg": "2",
 "protriptyline": "2",
 "prehist d": "2",
 "pedia relief": "2",
 "percocet 2.5/325": "2",
 "panmist dm": "2",
 "poly hist pd": "2",
 "pseudo carb dm": "2",
 "profen ii dm liquid": "2",
 "promethazine vc w/codeine": "2",
 "pancof": "2",
 "pd-cof": "2",
 "phenytoin sodium, prompt": "2",
 "prolex dm": "2",
 "pd-hist d drops": "2",
 "percolone": "2",
 "poly-tussin hd": "2",
 "phena-s 12": "2",
 "profen ii dm": "2",
 "primlev": "2",
 "pediatex-dm": "2",
 "pro-clear": "2",
 "p-v-tussin syrup": "2",
 "pexeva": "2",
 "pro-med": "2",
 "pseudogest-dm": "2",
 "phena-s": "2",
 "p-hist": "2",
 "pseudocot-c": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "pharbechlor": "2",
 "promethazine vc": "2",
 "pancof-pd": "2",
 "phenylhistine dh expectorant": "2",
 "propoxyphene compound 65": "2",
 "pertussin es": "2",
 "pcm-la": "2",
 "percocet 5/325": "2",
 "prozac weekly": "2",
 "propranolol": "2",
 "poly hist dm": "2",
 "phenflu cdx": "2",
 "pc-cap": "2",
 "prozac": "2",
 "pediacare children's multi-symptom cold": "2",
 "percocet 10/650": "2",
 "priftin": "2",
 "pseudochlor": "2",
 "pp-cap": "2",
 "phlemex": "2",
 "pain relief pm extra strength": "2",
 "pamelor": "2",
 "pediahist dm": "2",
 "pediacare children's allergy &amp; cold": "2",
 "pimozide": "3",
 "pce dispertab": "2",
 "promethazine vc plain": "2",
 "percocet 7.5/325": "2",
 "pd-cof drops": "2",
 "promazine": "2",
 "pseudo cm tr": "2",
 "prolixin enanthate": "2",
 "pain reliever pm": "2",
 "polytine dm": "2",
 "procot": "2",
 "percocet": "2",
 "prohist dm": "2",
 "panatuss dxp": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "phenoject-50": "2",
 "propoxyphene": "2",
 "profen forte dm": "2",
 "paroxetine": "2",
 "pse carb dm drops": "2",
 "pedia relief infant": "2",
 "p chlor dm": "2",
 "phenergan fortis": "2",
 "pcm allergy": "2",
 "pse carbinoxamine dm": "2",
 "phenobarbital": "2",
 "pyril dm": "2",
 "poly-tussin": "2",
 "pharbedryl": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "prohist": "2",
 "paxil cr": "2",
 "pbm allergy": "2",
 "pediatex 12 dm": "2",
 "pediahist dm syrup": "2",
 "prop-a-hist": "2",
 "perloxx": "2",
 "poly-vent dm": "2",
 "promethazine with dextromethorphan": "2",
 "primatuss 4": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenabid dm": "2",
 "pro-red ac": "2",
 "p-tann d": "2",
 "phenchlor tannate pediatric": "2",
 "promethegan": "2",
 "pertussin dm": "2",
 "promethazine hcl with codeine": "2",
 "prolixin decanoate": "2",
 "poly-tussin dm": "2",
 "phenflu cd": "2",
 "phenytoin": "2",
 "pharbetol pm": "2",
 "pediatan d": "2",
 "phena-plus": "2",
 "pediacare children's long-acting cough": "2",
 "percocet 7.5/500": "2",
 "propafenone": "2",
 "phlemex-pe": "2",
 "primalev": "2",
 "phenylhistine": "2",
 "percogesic original strength": "2",
 "phanatuss": "2",
 "phenergan with dextromethorphan": "2",
 "prevpac": "2",
 "perphenazine": "2",
 "polyhist nc": "2"}, "s": {"s-pak dm": "2",
 "solurex": "2",
 "sympak pdx": "2",
 "saquinavir": "2",
 "sildec-pe dm": "2",
 "sleep": "2",
 "sildec-pe drops": "2",
 "st. joseph cough suppressant": "2",
 "scot-tussin senior": "2",
 "sudal-12": "2",
 "sudogest sinus &amp; allergy": "2",
 "sonahist-dm": "2",
 "siltussin-dm das-na": "2",
 "sudogest cold &amp; allergy": "2",
 "scot-tussin diabetic": "2",
 "snooze fast": "2",
 "suphedrine plus": "2",
 "sporanox pulsepak": "2",
 "soltamox": "3",
 "suda-tussin dm": "2",
 "sleep tab ii": "2",
 "scot-tussin dm cough chasers": "2",
 "sympak dm": "2",
 "spec-t sore throat/cough suppressant": "2",
 "sinus &amp; allergy pe": "2",
 "suttar sf": "2",
 "stelazine": "2",
 "sudafed pe cold &amp; cough": "2",
 "serentil": "2",
 "sudal-12 chewable": "2",
 "sinutab maximum strength caplets": "2",
 "strepsils cough": "2",
 "siltussin dm": "2",
 "sudafed cough syrup": "2",
 "sympak ii": "2",
 "sudafed pe children's cold &amp; cough": "2",
 "sudal dm": "2",
 "sulfimycin": "2",
 "selfemra": "2",
 "serzone": "2",
 "su-tuss dm": "2",
 "sleepinal": "2",
 "sominex pain relief formula": "2",
 "sildec-pe": "2",
 "sleep-ettes": "2",
 "sudafed pe severe cold": "2",
 "severe cold multi-sympton": "2",
 "sustiva": "2",
 "sominex maximum strength caplet": "2",
 "solfoton": "2",
 "sinulin": "2",
 "simplet": "2",
 "st. john's wort": "2",
 "somnicaps": "2",
 "siladryl das": "2",
 "sudatex-dm": "2",
 "sudafed sinus nighttime plus pain": "2",
 "sucrets cough": "2",
 "sominex": "2",
 "sinarest": "2",
 "scopohist-pe": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "sympak": "2",
 "simuc-dm": "2",
 "sarafem": "2",
 "sparine": "2",
 "strepsils cough relief": "2",
 "sudogest plus": "2",
 "siladryl": "2",
 "sutan-dm": "2",
 "sudahist": "2",
 "scopohist syrup": "2",
 "sinucon": "2",
 "sleep-ettes d": "2",
 "silphen dm": "2",
 "sildec-pe dm drops": "2",
 "spastrin": "2",
 "soma compound with codeine": "2",
 "s-t forte 2": "2",
 "suphenamine-sr": "2",
 "simply sleep": "2",
 "scot-tussin allergy": "2",
 "surmontil": "2",
 "siltussin dm das cough formula": "2",
 "suttar-2": "2",
 "sildec dm": "2",
 "sinutuss dm": "2",
 "solurex la": "2",
 "stahist": "2",
 "sinutab ex-strength": "2",
 "siladryl allergy": "2",
 "sleep tabs": "2",
 "s-pack dm": "2",
 "sudafed cough": "2",
 "sinucon pediatric": "2",
 "sporanox": "2",
 "scot-tussin dm": "2",
 "sleepwell 2-nite": "2",
 "sleep-eze-3": "2",
 "suclor": "2",
 "sudafed pe nighttime cold": "2",
 "spasmolin": "2",
 "silphen cough": "2",
 "sinequan": "2",
 "siltussin-dm das-na maximum strength": "2",
 "symbyax": "2",
 "spasquid": "2",
 "safetussin cd": "2",
 "scopohist": "2",
 "sudafed pe sinus &amp; allergy": "2",
 "strattera": "2",
 "sonahist": "2",
 "singlet": "2",
 "servira": "2",
 "sinarest extra strength": "2",
 "silenor": "2",
 "siladyl sa": "2",
 "safetussin pm": "2",
 "statuss": "2",
 "sinapils": "2",
 "sudal-12 tannate": "2",
 "safetussin 30 dm": "2",
 "syn-rx dm": "2",
 "sinodec": "2",
 "suphedrine pe": "2"}, "r": {"rhinaclear": "2",
 "relcof pse": "2",
 "risperdal m-tab": "2",
 "robitussin-ac": "2",
 "robafen cf": "2",
 "robitussin-dac": "2",
 "robichem dm": "2",
 "ricobid nr": "2",
 "rescon-ed": "2",
 "ricobid h": "2",
 "robitussin peak cold multi-symptom cold": "2",
 "ranexa": "1",
 "resaid": "2",
 "rhinolar": "2",
 "ru-tuss": "2",
 "ry-tann": "2",
 "robitussin night time cough &amp; cold": "2",
 "relacon-dm": "2",
 "resperal": "2",
 "relcof pe": "2",
 "rifampin": "2",
 "rynatan pediatric": "2",
 "rhinatate pediatric": "2",
 "rynatuss": "2",
 "relasin-hc": "2",
 "robafen pediatric cough &amp; cold": "2",
 "rondex-dm": "2",
 "roxicet": "2",
 "rhinogesic": "2",
 "rindal hd plus": "2",
 "razadyne": "2",
 "rescriptor": "2",
 "robitussin lingering cold long-acting cough": "2",
 "ru-tuss expectorant": "2",
 "rhinatate-nf": "2",
 "redur-pcm": "2",
 "rhinolar-ex 12": "2",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "reglan": "2",
 "rybix odt": "2",
 "rhinosyn-dm": "2",
 "roxicodone": "2",
 "relahist-dm": "2",
 "rolatuss": "2",
 "ryna-cx": "2",
 "relcof dn pe": "2",
 "rybix": "2",
 "robitussin night time cough, cold &amp; flu": "2",
 "robitussin children's cough long-acting": "2",
 "ri-tussin dm": "2",
 "rythmol sr": "2",
 "rhinacon a": "2",
 "rifater": "2",
 "robimycin": "2",
 "ru-tuss 800 dm": "2",
 "relera": "2",
 "r-tannamine": "2",
 "robitussin children's cough &amp; cold cf": "2",
 "rythmol": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "roxicodone intensol": "2",
 "reme tussin dm": "2",
 "ru-hist forte": "2",
 "ru-tuss dm": "2",
 "robitussin cold cough and flu": "2",
 "rynatan-s pediatric": "2",
 "relacon-dm nr": "2",
 "rifadin iv": "2",
 "rescon-dm": "2",
 "robitussin coughgels long-acting": "2",
 "rondex drops": "2",
 "rifadin": "2",
 "respa sa": "2",
 "relcof cpm": "2",
 "robitussin cough &amp; chest congestion dm": "2",
 "rhinolar-ex": "2",
 "rheumatrex dose pack": "2",
 "rondec-dm": "2",
 "rondec": "2",
 "ryna liquid": "2",
 "re2+30": "2",
 "rondex": "2",
 "relasin dm": "2",
 "razadyne er": "2",
 "rifabutin": "2",
 "robitussin children's cough &amp; cold long-acting": "2",
 "robafen cough liquidgels": "2",
 "r-tannate pediatric": "2",
 "relcof dn pse": "2",
 "r-tannate": "2",
 "robitussin dx cough control": "2",
 "risperdal consta": "2",
 "re-drylex jr": "2",
 "robitussin peak cold nighttime nasal relief": "2",
 "recofen d": "2",
 "rentamine": "2",
 "robitussin cough &amp; cold d": "2",
 "robitussin peak cold maximum strength cough + chest congestion dm": "2",
 "robitussin cough &amp; chest congestion sugar-free dm": "2",
 "resperal-dm": "2",
 "robafen dm": "2",
 "risperidone": "2",
 "recofen plus": "2",
 "robitussin allergy &amp; cough": "2",
 "relacon-hc": "2",
 "robichem ac": "2",
 "rindal hpd": "2",
 "roxiprin": "2",
 "r-tannamine pediatric": "2",
 "rinate pediatric": "2",
 "relcof c": "2",
 "ranolazine": "1",
 "respa-ar": "2",
 "ricotuss": "2",
 "rynatuss pediatric": "2",
 "rondex-dm drops": "2",
 "respivent df": "2",
 "rinade-bid": "2",
 "rondamine dm": "2",
 "rescon": "2",
 "robitussin peak cold cough + chest congestion dm": "2",
 "relacon lax": "2",
 "ralix": "2",
 "reme hist dm": "2",
 "robitussin cough &amp; cold long-acting": "2",
 "rynatan": "2",
 "revia": "2",
 "robafen ac": "2",
 "robitussin lingering cold long-acting coughgels": "2",
 "rimactane": "2",
 "rindal-hd": "2",
 "romilar ac": "2",
 "rolatuss-sr": "2",
 "rhinosyn-x": "2",
 "ryzolt": "2",
 "respa-dm": "2",
 "rebif": "2",
 "ryneze": "2",
 "relacon-hc nr": "2",
 "rhinatate": "2",
 "ritonavir": "2",
 "robitussin cough &amp; chest congestion dm max": "2",
 "robitussin cough &amp; cold cf": "2",
 "robitussin peak cold sugar-free cough + chest congestion dm": "2",
 "roxilox": "2",
 "re dcp drops": "2",
 "robitussin cough long-acting": "2",
 "respa c&amp;c": "2",
 "reminyl": "2",
 "robafen dm clear": "2",
 "refenesen chest congestion relief dm": "2",
 "r-tanna": "2",
 "re-pb hyos elixir": "2",
 "risperdal": "2",
 "rhinosyn-dmx": "2",
 "rapiflux": "2",
 "reyataz": "2",
 "rentamine pediatric": "2",
 "ryna-c": "2",
 "redux": "2"}, "u": {"uni-hist pdx drops": "2",
 "ultram": "2",
 "ultram odt": "2",
 "unisom sleepmelts": "2",
 "uni-tann": "2",
 "ultram er": "2",
 "uni decon": "2",
 "uni-hist pdx syrup": "2",
 "url-tannate": "2",
 "ultracet": "2",
 "uni-hist dm pediatric syrup": "2",
 "uni multihist dm": "2",
 "uni-cof": "2",
 "uni-tann cs": "2",
 "uni tussin cf": "2",
 "url-tannate pediatric": "2",
 "uni tuss hc": "2",
 "uni-hist dm pediatric drops": "2",
 "unisom with pain relief": "2",
 "uni-tricof hc": "2",
 "uni-tann d": "2",
 "unisom sleepgels": "2",
 "uni-tuss dm": "2"}, "t": {"theraflu warming relief daytime severe cough &amp; cold": "2",
 "tussionex pennkinetic": "2",
 "tusso-dm": "2",
 "toprol-xl": "2",
 "tussiden c": "2",
 "tamoxifen": "3",
 "tussi-bid": "2",
 "tussend": "2",
 "tramadol": "2",
 "tekral": "2",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "tussafed-la": "2",
 "tussex": "2",
 "tussin-v": "2",
 "triaminic softchews cough &amp; sore throat": "2",
 "tylenol cold severe congestion daytime": "2",
 "tusnel-dm pediatric drops": "2",
 "telzir": "2",
 "tannate pd-dm": "2",
 "tolterodine": "1",
 "touro cc-ld": "2",
 "tanafed-dm": "2",
 "tavist-da": "2",
 "timolol ophthalmic": "2",
 "tussi-organidin dm-s nr": "2",
 "tramal sr": "2",
 "tussi-organidin dm nr": "2",
 "trituss-a drops": "2",
 "tamsulosin": "2",
 "tussafed-ex": "2",
 "tusnel pediatric": "2",
 "tylenol plus children's flu": "2",
 "tusnel ped-c": "2",
 "trihist-cs": "2",
 "tanamine": "2",
 "timoptic": "2",
 "tavist nighttime allergy": "2",
 "trital dm": "2",
 "tussin pediatric cold and cough": "2",
 "tri-gestan s": "2",
 "triaminic thin strips long acting cough": "2",
 "torecan": "2",
 "thiethylperazine": "2",
 "theraflu thin strips daytime cold and cough": "2",
 "t- koff": "2",
 "tussizone-12 rf": "2",
 "tricodene forte": "2",
 "tylenol cold head congestion daytime": "2",
 "tuss tan": "2",
 "tylenol severe allergy": "2",
 "tranquil nighttime sleep aid": "2",
 "tussall": "2",
 "temaril": "2",
 "tylenol cold head congestion severe": "2",
 "tussafed-ex drops": "2",
 "tussplex dm": "2",
 "tricodene nn": "2",
 "tusdec-dm": "2",
 "tylenol with codeine #2": "2",
 "tegretol": "2",
 "troleandomycin": "2",
 "tylenol cold multi-symptom severe": "2",
 "tanafed": "2",
 "tylenol sore throat nighttime": "2",
 "triaminic long acting cough": "2",
 "tl-hist dm": "2",
 "therahist": "2",
 "triaminic softchews cough &amp; runny nose": "2",
 "tylenol cold multi-symptom daytime": "2",
 "tussi-organidin-dm": "2",
 "triple tannate pediatric": "2",
 "tanamine pediatric": "2",
 "theraflu flu &amp; cough": "2",
 "touro dm": "2",
 "tridal": "2",
 "tuss-ds": "2",
 "tustan 12s": "2",
 "topcare cough and sore throat": "2",
 "tussi-organidin nr": "2",
 "tramedo": "2",
 "trituss-er": "2",
 "tylenol cough and sore throat daytime": "2",
 "tussive hc": "2",
 "triant-hc": "2",
 "tri-tannate": "2",
 "triotann-s pediatric": "2",
 "tritan": "2",
 "tylenol cold head congestion nighttime": "2",
 "tussi-12": "2",
 "thioguanine": "2",
 "twilite": "2",
 "thioridazine": "3",
 "trifluoperazine": "2",
 "tabloid": "2",
 "theraflu thin strips cough": "2",
 "trexall": "2",
 "trihist dm": "2",
 "tylenol cold multi-symptom nighttime": "2",
 "tylenol with codeine": "2",
 "tylenol pm": "2",
 "trituss-a": "2",
 "theraflu max-d severe cold &amp; flu": "2",
 "tricof": "2",
 "trionate": "2",
 "trazodone": "2",
 "tussar sf": "2",
 "triotann-s": "2",
 "tussirex": "2",
 "time-hist qd": "2",
 "tamone": "3",
 "triaminic multi-symptom fever": "2",
 "tl-hist cm": "2",
 "tussafed": "2",
 "trituss": "2",
 "tramapap": "2",
 "theodrine": "2",
 "tanahist-d": "2",
 "tofranil-pm": "2",
 "tenar dm": "2",
 "threamine dm": "2",
 "tricodene pediatric": "2",
 "tylenol cold": "2",
 "tusana-d": "2",
 "tanoral": "2",
 "tuss tan pediatric": "2",
 "tanahist-pd": "2",
 "timolide": "2",
 "total allergy": "2",
 "tuss-hc": "2",
 "triphenicol": "2",
 "tylenol allergy complete nighttime": "2",
 "triaminic cold &amp; allergy": "2",
 "telithromycin": "2",
 "tanoral pediatric": "2",
 "timoptic-xe": "2",
 "trital sr": "2",
 "tylenol cough &amp; severe congestion daytime": "2",
 "tannic-12 s": "2",
 "tylenol with codeine #3": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "telaprevir": "2",
 "timoptic ocudose": "2",
 "tusnel-a": "2",
 "thorazine": "2",
 "triac": "2",
 "triaminic day time cold &amp; cough": "2",
 "triaminic-d multi-symptom cold": "2",
 "tanafed dmx": "2",
 "timolol": "2",
 "touro cc": "2",
 "tuss-dm": "2",
 "triaminic softchews cold and allergy": "2",
 "trycet": "2",
 "theraflu warming relief sinus &amp; cold": "2",
 "tylenol plus children's cold &amp; cough": "2",
 "tussicaps": "2",
 "theraflu multi-symptom severe cold": "2",
 "topco allergy": "2",
 "theraflu nighttime severe cold &amp; cough caplets": "2",
 "theraflu warming relief caplets nighttime multi-symptom cold": "2",
 "tylenol allergy sinus": "2",
 "theraflu cold &amp; cough": "2",
 "tl-hist cd": "2",
 "tri tann pediatric": "2",
 "tannate pediatric": "2",
 "tusstat": "2",
 "triplex ad": "2",
 "triflupromazine": "2",
 "tannate 12 s": "2",
 "triavil": "2",
 "theraflu thin strips multi symptom": "2",
 "tusso-dmr": "2",
 "tanacof dm": "2",
 "teldrin": "2",
 "trimeprazine": "2",
 "tusso-c": "2",
 "theraflu flu, cold and cough powder": "2",
 "tusscidin dm": "2",
 "tamofen": "3",
 "timolide 10-25": "2",
 "tedrigen": "2",
 "tylenol plus children's cough &amp; sore throat": "2",
 "tylenol with codeine #4": "2",
 "tusso-xr": "2",
 "theraflu daytime severe cold &amp; cough": "2",
 "tussin cf": "2",
 "tambocor": "2",
 "tylenol severe cold &amp; flu night time": "2",
 "tussin cough and cold": "2",
 "tanni-hist 12 rf": "2",
 "tylenol cold multi-symptom nighttime liquid": "2",
 "tylenol plus children's multi-symptom cold": "2",
 "tussin cough": "2",
 "triaminic night time cold &amp; cough": "2",
 "tandur dm": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "tri-vent dpc": "2",
 "tricodene sf": "2",
 "tegretol xr": "2",
 "t-tanna dm": "2",
 "time-hist": "2",
 "tannate-12": "2",
 "tl-dex dm": "2",
 "tofranil": "2",
 "triafed &amp; codeine": "2",
 "tussar dm": "2",
 "tylenol allergy multi-symptom": "2",
 "tamoxifen hexal": "3",
 "tolu-sed dm": "2",
 "tusscough dhc": "2",
 "tylenol sinus congestion &amp; pain nighttime": "2",
 "triplex dm": "2",
 "tylenol cold head congestion day and night": "2",
 "tussall-er": "2",
 "trifed c": "2",
 "triaminic thin strips day time cold &amp; cough": "2",
 "triaminic cough &amp; sore throat": "2",
 "tao": "2",
 "tussi-organidin-s nr": "2",
 "tusnel diabetic": "2",
 "tramahexal sr": "2",
 "trilafon": "2",
 "triaminic": "2",
 "tussar-2": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "trimipramine": "2",
 "tylox": "2",
 "tylenol plus children's cough &amp; runny nose": "2",
 "tussirex sugar free": "2",
 "tussi-12s": "2",
 "t-tussin dm": "2",
 "triall": "2",
 "tussinol for dry coughs": "2",
 "tussinate": "2",
 "tylenol cold &amp; flu severe": "2",
 "tussin dm": "2",
 "trikof-d": "2",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tramal": "2",
 "tussidin dm": "2",
 "triaminicin": "2",
 "tetra tannate pediatric": "2",
 "tri-hist pediatric": "2",
 "tricom": "2",
 "triotann": "2",
 "tylenol plus children's cold": "2",
 "triotann pediatric": "2",
 "tussidex": "2",
 "triacin c": "2",
 "tylenol cough &amp; sore throat nightime": "2",
 "tannate dmp-dex": "2",
 "tamosin": "3",
 "tylenol cold &amp; cough daytime": "2",
 "tannate v dm": "2",
 "trux-adryl": "2",
 "tacaryl": "2",
 "theraflu warming relief caplets daytime multi-symptom cold": "2",
 "tylenol cold non-drowsy gelcaps": "2",
 "theraflu (pseudoephedrine) daytime severe cold": "2",
 "tylenol cold &amp; cough nighttime": "2",
 "tri-dec": "2",
 "triaminic thin strips cough &amp; runny nose": "2",
 "tamoxen": "3",
 "tri-tannate pediatric": "2",
 "tylenol allergy multi-symptom nighttime": "2",
 "tuss-pd": "2",
 "tricodene sugar free": "2",
 "triaminic thin strips allergy": "2",
 "tussin pediatric": "2"}, "w": {"welltuss hc": "2",
 "we allergy": "2",
 "wygesic": "2",
 "wal-nadol pm extra strength": "2",
 "wal-finate": "2",
 "west-decon m": "2",
 "west-decon": "2"}, "v": {"vivactil": "2",
 "ventuss syrup": "2",
 "vanex-hd": "2",
 "vicks nyquil cold &amp; flu relief": "2",
 "vicks dayquil cold &amp; flu relief": "2",
 "vaprisol": "2",
 "vicks nyquil cough": "2",
 "v-tan dm": "2",
 "vansil": "2",
 "vfend": "2",
 "vicks nyquil multi-symptom": "2",
 "v-gan-50": "2",
 "vanex forte": "2",
 "viracept": "2",
 "visrx dose pack": "2",
 "vicks formula 44 custom care chesty cough": "2",
 "viratan-dm": "2",
 "vicks children's nyquil": "2",
 "vicks 44d": "2",
 "vicks dayquil daytime cold/flu": "2",
 "valu-dryl": "2",
 "vopac": "2",
 "vicks 44m pediatric": "2",
 "vicks dayquil cough": "2",
 "vanex forte-r": "2",
 "viravan-pdm": "2",
 "voriconazole": "2",
 "vicks formula 44 custom care dry cough suppressant": "2",
 "vicks dayquil cold &amp; flu symptom relief plus vitamin c": "2",
 "v-gan-25": "2",
 "venlafaxine": "2",
 "viravan-dm": "2",
 "vicks pediatric formula 44e cough &amp; chest congestion relief": "2",
 "victrelis": "2",
 "vicks nyquil cold &amp; flu symptom relief plus vitamin c": "2",
 "vicks formula 44d cough &amp; sinus congestion relief": "2",
 "vicks formula 44": "2",
 "vicks pediatric formula 44m cough &amp; cold relief": "2",
 "vicks formula 44 custom care congestion": "2",
 "vanacof cd": "2",
 "vicks formula 44 custom care cough &amp; cold pm": "2",
 "visken": "2",
 "vivitrol": "2"}, "y": {"y-cof dm": "2"}, "x": {"xirahistdm": "2",
 "x-hist dm": "2",
 "xiratuss": "2",
 "xolox": "2",
 "xiral sr": "2"}, "z": {"zotex-12": "2",
 "z-tuss ac": "2",
 "zodryl ac": "2",
 "zotex pediatric": "2",
 "zamadol": "2",
 "zema pak": "2",
 "zutripro": "2",
 "zotex lax": "2",
 "z-cof lax": "2",
 "z-cof 12dm": "2",
 "zotex dmx": "2",
 "z-cof 12": "2",
 "z-cof 8dm": "2",
 "zodryl dac": "2",
 "zodryl dec": "2",
 "zydol": "2",
 "z-cof dm": "2",
 "zotex-ex": "2",
 "z-tuss 2": "2",
 "zaponex": "2",
 "z-dex": "2",
 "zotex-dm": "2",
 "z-dex 12 d": "2",
 "zotex-c": "2",
 "z-cof hc": "2",
 "zotex-12d": "2",
 "z-cof la": "2",
 "z-tuss dm": "2",
 "zotex": "2"}}];