interactions["acetaminophen-oxycodone,magnacet"]=["acetaminophen-oxycodone,magnacet", {"1": {"12 hour cold": "2"}, "4": {"40 winks": "2"}, "a": {"alacol": "2",
 "alumadrine": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "alfenta": "2",
 "accuhist la": "2",
 "aphedrid": "2",
 "acetaminophen/dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "akineton": "2",
 "acetaminophen/chlorpheniramine/guaifenesin/phenylpropanolamine": "2",
 "antispas": "2",
 "amethia": "1",
 "asenapine": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "acuflex": "2",
 "acetaminophen/dexbrompheniramine/pseudoephedrine": "2",
 "ambien cr": "2",
 "accesspak for hiv pep expanded with kaletra": "3",
 "alka-seltzer plus night cold formula liquid": "2",
 "a-g tussin": "2",
 "alahist dm": "2",
 "amidrine": "2",
 "amitriptyline/perphenazine": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "anamine td": "2",
 "anamine": "2",
 "atacand hct": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "anturol": "2",
 "azatadine/pseudoephedrine": "2",
 "all-nite cold": "2",
 "atacand": "2",
 "anhydrous calcium iodide/codeine": "2",
 "acetaminophen/butalbital": "2",
 "allergy dn ii": "2",
 "acetaminophen/pamabrom/pyrilamine": "2",
 "accuhist pdx syrup": "2",
 "amyl nitrite/sodium nitrite/sodium thiosulfate": "2",
 "avonex prefilled syringe": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "acetaminophen/diphenhydramine/pseudoephedrine": "2",
 "aliskiren/valsartan": "2",
 "allergy dn pe": "2",
 "anergan 50": "2",
 "alprazolam": "2",
 "acetaminophen/chlorpheniramine": "2",
 "anaspaz": "2",
 "apresoline": "2",
 "allermax": "2",
 "afeditab cr": "2",
 "aceta-gesic": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "amobarbital": "2",
 "aldex-ct": "2",
 "atropine/pralidoxime": "2",
 "aridex-d pediatric": "2",
 "allfen cx": "2",
 "acetylcarbromal": "2",
 "aridex": "2",
 "allfen cd": "2",
 "amlodipine/benazepril": "2",
 "a-spas s/l": "2",
 "acetaminophen/caffeine/chlorpheniramine/phenylpropanolamine": "2",
 "albatussin": "2",
 "aldoril d50": "2",
 "allerx dose pack": "2",
 "amobarbital/secobarbital": "2",
 "avinza": "2",
 "alyacen 1/35": "1",
 "adalat": "2",
 "altavera": "1",
 "advil pm": "2",
 "alka-seltzer plus day &amp; night cold formula (night cold) liquid gels": "2",
 "ami-rax": "2",
 "aller-chlor decongestant": "2",
 "actidose plus sorbitol": "2",
 "apresazide": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/guaifenesin": "2",
 "atarax": "2",
 "arfonad": "2",
 "atuss ms": "2",
 "apo-go": "2",
 "allergy dn": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/pseudoephedrine": "2",
 "ala-hist pe": "2",
 "aripiprazole": "2",
 "actifed cold and sinus": "2",
 "atropine/chlorpheniramine/hyoscyamine/pseudoephedrine/scopolamine": "2",
 "amoxapine": "2",
 "actifed allergy day/night": "2",
 "alphagan": "2",
 "allres ds": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/phenylephrine": "2",
 "active carbon": "2",
 "accuhist dm pediatric syrup": "2",
 "acetaminophen/phenyltoloxamine": "2",
 "allent": "2",
 "amiloride/hydrochlorothiazide": "2",
 "atuss dm": "2",
 "atuss dr": "2",
 "atuss ds": "2",
 "alesse": "1",
 "acutuss dm pediatric": "2",
 "amlodipine/olmesartan": "2",
 "atrogen": "2",
 "allergy am-pm dose pack": "2",
 "aprodine": "2",
 "allerx df": "2",
 "andehist": "2",
 "ambifed cd": "2",
 "amilon": "2",
 "alleroff": "2",
 "americet": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "anolor 300": "2",
 "allfen c": "2",
 "abilify discmelt": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "allertan": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "atrohist pediatric": "2",
 "accuhist pediatric": "2",
 "amitriptyline": "2",
 "avonex": "2",
 "allerfrim": "2",
 "ambenyl": "2",
 "atrosept": "2",
 "atrofed": "2",
 "aspirin/phenyltoloxamine": "2",
 "amlodipine/telmisartan": "2",
 "andehist nr syrup": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "ali-flex": "2",
 "actagen": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenyltoloxamine": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "alenaze-d": "2",
 "amlodipine/atorvastatin": "2",
 "allergy relief d": "2",
 "allerest maximum strength": "2",
 "alka-seltzer plus cold &amp; cough formula liquid": "2",
 "acetaminophen/pseudoephedrine/triprolidine": "2",
 "accuretic": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/pseudoephedrine": "2",
 "acetaminophen/dextromethorphan/doxylamine/phenylephrine": "2",
 "a-spaz": "2",
 "arbinoxa": "2",
 "ah-chew ii": "2",
 "arava": "3",
 "alcohol": "3",
 "alacol dm": "2",
 "all day allergy-d": "2",
 "amethyst": "1",
 "anturane": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "aldex an chewable": "2",
 "alka-seltzer plus night cold formula liquid gels": "2",
 "alkabel-sr": "2",
 "ambi 1000/5": "2",
 "alka-seltzer plus cold &amp; cough formula liquid gels": "2",
 "asendin": "2",
 "allercon": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "a-phedrin": "2",
 "allerx": "2",
 "aldoril 25": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "allergy relief": "2",
 "allres d": "2",
 "acetaminophen/dichloralphenazone/isometheptene mucate": "2",
 "aquatab c": "2",
 "atropine/edrophonium": "2",
 "acetaminophen/doxylamine/pseudoephedrine": "2",
 "alka-seltzer plus cold formula": "2",
 "antispasmodic": "2",
 "alka-seltzer pm": "2",
 "apokyn": "2",
 "aspirin/diphenhydramine": "2",
 "acetaminophen/codeine": "2",
 "antrocol": "2",
 "allerhist-d": "2",
 "antiflex": "2",
 "aspirin/carisoprodol/codeine": "2",
 "allanhist pdx drops": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "allerfrin with codeine": "2",
 "allerx pe dose pack": "2",
 "anafranil": "2",
 "atuss-12 dm": "2",
 "anti-diarrheal": "2",
 "aceta w/ codeine": "2",
 "aldactazide": "2",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "aldex dm": "2",
 "allerhist-1": "2",
 "arm allergy relief": "2",
 "allergia-c": "2",
 "aerohist": "2",
 "airacof": "2",
 "atenolol/chlorthalidone": "2",
 "asthmacon": "2",
 "apri": "1",
 "anaplex": "2",
 "acetaminophen/dextromethorphan/doxylamine/pseudoephedrine": "2",
 "azelastine nasal": "2",
 "alagesic lq": "2",
 "ana-kit": "2",
 "acta-tabs pe": "2",
 "aventyl hydrochloride": "2",
 "aspirin/codeine": "2",
 "aspirin/pentazocine": "2",
 "alcohol 5% in dextrose 5%": "3",
 "acetaminophen/diphenhydramine": "2",
 "amlodipine/valsartan": "2",
 "atropen": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "2",
 "atropine/difenoxin": "2",
 "andecon pediatric drops": "2",
 "acetaminophen/brompheniramine/phenylpropanolamine": "2",
 "abiraterone": "2",
 "acetaminophen/chlorpheniramine/pseudoephedrine": "2",
 "allerx pe": "2",
 "amdry-d": "2",
 "azurette": "1",
 "amdry-c": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/scopolamine": "2",
 "allergy multi-symptom relief": "2",
 "aspirin/meprobamate": "2",
 "aler-dryl": "2",
 "aldactone": "2",
 "allres-g": "2",
 "amytal sodium": "2",
 "amylase/cellulase/hyoscyamine/lipase/phenyltoloxamine/protease": "2",
 "allfen cdx": "2",
 "accuhist drops": "2",
 "aldoril 15": "2",
 "allerfrin": "2",
 "aldex an": "2",
 "acetaminophen/chlorpheniramine/phenylpropanolamine": "2",
 "apraclonidine ophthalmic": "2",
 "acetaminophen/caffeine/pyrilamine": "2",
 "aerokid": "2",
 "atripla": "2",
 "aquachloral supprettes": "2",
 "actedril": "2",
 "aspirin/methocarbamol": "2",
 "ambophen": "2",
 "arcet": "2",
 "a-tan 12x": "2",
 "allanhist pdx syrup": "2",
 "anaplex dm": "2",
 "alagesic": "2",
 "apo-go pen": "2",
 "atrohist plus": "2",
 "altafed": "2",
 "aerohist plus": "2",
 "astelin": "2",
 "apagesic": "2",
 "alfuzosin": "2",
 "attapulgite": "2",
 "abilify": "2",
 "actidose with sorbitol": "2",
 "acetaminophen/brompheniramine/dextromethorphan/pseudoephedrine": "2",
 "anacin p.m. aspirin free": "2",
 "adapin": "2",
 "actidose-aqua advance": "2",
 "altace": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "allres pd": "2",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "acetaminophen/brompheniramine/pseudoephedrine": "2",
 "actifed": "2",
 "acetaminophen/propoxyphene": "3",
 "amlodipine": "2",
 "aplenzin": "3",
 "actacin": "2",
 "acetaminophen/phenyltoloxamine/salicylamide": "2",
 "alfentanil": "2",
 "acetaminophen pm extra strength": "2",
 "accuhist dm pediatric drops": "2",
 "ambifed-g cd": "2",
 "acetaminophen/caffeine/phenyltoloxamine": "2",
 "allerx df dose pack": "2",
 "altaryl": "2",
 "alpain": "2",
 "acetaminophen/chlorpheniramine/phenylephrine": "2",
 "allerest 12 hour": "2",
 "allepak": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "anaplex hd": "2",
 "anabar": "2",
 "astramorph pf": "2",
 "amyl nitrite": "2",
 "allerphed": "2",
 "atnaa": "2",
 "amethia lo": "1",
 "aquazide h": "2",
 "amturnide": "2",
 "aldex d": "2",
 "aldoril d30": "2",
 "akineton hcl": "2",
 "abacavir/lamivudine/zidovudine": "1",
 "andehist dm nr syrup": "2",
 "alvimopan": "3",
 "aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "atrohist pediatric capsule": "2",
 "acetaminophen/dextromethorphan/doxylamine": "2",
 "ammonium chloride/chlorpheniramine/dextromethorphan/ephedrine/ipecac/phenylephrine": "2",
 "alka-seltzer plus cold &amp; flu": "2",
 "amrix": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "actidose-aqua": "2",
 "accuhist pdx drops": "2",
 "artemether/lumefantrine": "2",
 "azatadine": "2",
 "all-nite multi-symptom cold/flu relief": "2",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "2",
 "aldoril": "2",
 "alenaze-d nr": "2",
 "ah-chew": "2",
 "ambien": "2",
 "activated charcoal": "2",
 "adgan": "2",
 "actifed cold and allergy": "2",
 "andec-tr": "2",
 "alka-seltzer plus flu formula": "2",
 "alyacen 7/7/7": "1",
 "antrizine": "2",
 "atridine": "2",
 "aridex-d": "2",
 "alesse-21": "1",
 "acetaminophen/clemastine/pseudoephedrine": "2",
 "alahist lq": "2",
 "atropine/diphenoxylate": "2",
 "alesse-28": "1",
 "aranelle": "1",
 "andehist dm nr": "2",
 "anaplex dmx": "2",
 "allerest sinus": "2",
 "acebutolol": "2",
 "ambifed-g cdx": "2",
 "avapro": "2",
 "advil children's allergy sinus": "2",
 "ah-chew ultra tannate": "2",
 "atenolol": "2",
 "altatapp": "2",
 "accupril": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "anoquan": "2",
 "atuss hd": "2",
 "aller-chlor": "2",
 "advil allergy sinus": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "atuss hs": "2",
 "andec": "2",
 "astepro": "2",
 "aceon": "2",
 "avalide": "2",
 "apomorphine": "2",
 "aspirin/butalbital/caffeine": "2",
 "anisindione": "1",
 "allerest pe": "2",
 "allergy sinus maximum strength": "2",
 "alka-seltzer plus cold": "2",
 "acetaminophen/dextromethorphan/diphenhydramine": "2",
 "alidrin": "2",
 "alprazolam intensol": "2",
 "amlobenz": "2",
 "ala-hist": "2",
 "amiloride": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "artane": "2",
 "adalat cc": "2",
 "allan tannate pediatric": "2",
 "all day allergy children's": "2",
 "axocet": "2",
 "ala-hist ac": "2",
 "azor": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "alphagan p": "2",
 "ahist": "2",
 "ampicillin/probenecid": "1",
 "aspirin/caffeine/propoxyphene": "3",
 "antivert": "2",
 "acetaminophen/pentazocine": "2",
 "ala-hist d": "2",
 "atropine/phenobarbital": "2",
 "aspirin/carisoprodol": "2",
 "alphen expectorant": "2",
 "ah-chew ultra": "2",
 "all day allergy": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "atreza": "2",
 "atropine": "2",
 "azilsartan medoxomil": "2",
 "acetaminophen/tramadol": "3",
 "aspirin/butalbital": "2",
 "ativan": "2",
 "alcohol and dextrose injections usp hypertonic": "3",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/phenylpropanolamine/scopolamine": "2",
 "aliskiren/amlodipine": "2",
 "allerx-d": "2",
 "allerest headache strength": "2",
 "aviane": "1",
 "aler-tab": "2",
 "ambifed cdx": "2"}, "c": {"cesamet": "2",
 "carboxine-pse": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "c-tanna 12d": "2",
 "catapres": "2",
 "chlor-mal": "2",
 "capozide 50/25": "2",
 "carbetapentane/phenylephrine/phenylpropanolamine/potassium guaiacolsulfonate": "2",
 "calcidrine": "2",
 "c-phed tannate": "2",
 "charcoaid-g": "2",
 "carbetapentane/phenylephrine": "2",
 "colfed-a": "2",
 "chlophedianol/chlorcyclizine": "2",
 "chlorthalidone/reserpine": "2",
 "citalopram": "2",
 "compound 374": "2",
 "capoten": "2",
 "corzide 40/5": "2",
 "chlophedianol/guaifenesin": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "clozapine": "2",
 "carbetapentane/diphenhydramine": "2",
 "capital w/codeine": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "cheratussin ac": "2",
 "colchicine/probenecid": "1",
 "cocet plus": "2",
 "codimal-la": "2",
 "children's tylenol plus cold and allergy": "2",
 "codeine/promethazine": "2",
 "cardizem la": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "careone acid reducer": "1",
 "cold &amp; cough childrens": "2",
 "cymbalta": "2",
 "compazine spansule": "2",
 "carbidopa/entacapone/levodopa": "2",
 "carboxine 12d": "2",
 "cycofed pediatric expectorant": "2",
 "care one sleep aid": "2",
 "chlordinium": "2",
 "combivir": "1",
 "candesartan/hydrochlorothiazide": "2",
 "carbetapentane/chlorpheniramine/ephedrine/phenylephrine": "2",
 "cinacalcet": "2",
 "chlor-mes jr": "2",
 "carbodex dm drops": "2",
 "cordron-dm": "2",
 "carduran": "2",
 "carbic-d": "2",
 "ceron drops": "2",
 "clorazepate": "2",
 "cydec-dm drops": "2",
 "cotabflu": "2",
 "cyproheptadine": "2",
 "centussin dhc": "2",
 "chlophedianol/triprolidine": "2",
 "comtrex severe cold &amp; sinus": "2",
 "camrese": "1",
 "carbinoxamine/methscopolamine/pseudoephedrine": "2",
 "clonidine": "2",
 "cyclafem 7/7/7": "1",
 "compro": "2",
 "chlor-mes": "2",
 "co-histine dh": "2",
 "carbinoxamine/phenylephrine": "2",
 "cycofed expectorant": "2",
 "chlophedianol/dexchlorpheniramine/pseudoephedrine": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "cardec dm": "2",
 "chlorafed hs timecelles": "2",
 "codehist dh": "2",
 "carbaphen 12": "2",
 "carbetapentane/guaifenesin/phenylephrine": "2",
 "chlorpheniramine/codeine": "2",
 "chemtussin hc": "2",
 "chlorthalidone": "2",
 "charcoal": "2",
 "chlorpromazine": "2",
 "coldec-tr": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "chlor-trimeton allergy decongestant sr": "2",
 "chlophedianol/phenylephrine/triprolidine": "2",
 "cheracol plus": "2",
 "capozide 50/15": "2",
 "chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "carbetapentane": "2",
 "codeprex": "2",
 "codahistine-dh elixir": "2",
 "chlorpheniramine/epinephrine": "2",
 "charcodote": "2",
 "childrens tylenol cold plus cough": "2",
 "chlophedianol/dexbrompheniramine/phenylephrine": "2",
 "chlorpheniramine/dextromethorphan": "2",
 "chlorzoxazone": "2",
 "codeine/phenylephrine/promethazine": "2",
 "charcoal/sorbitol": "2",
 "carisoprodol compound": "2",
 "chlormezanone": "2",
 "cocet": "2",
 "cystemms-v": "2",
 "cimetidine": "2",
 "comtussin hc": "2",
 "captopril": "2",
 "condrin": "2",
 "carbatab-12": "2",
 "carbodex dm syrup": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "cp-tannic": "2",
 "cordron-d": "2",
 "cardec drops": "2",
 "covera-hs": "2",
 "cytuss hc": "2",
 "cardec dm drops": "2",
 "carboxine": "2",
 "charcoal plus ds": "2",
 "chlorpheniramine/dextromethorphan/methscopolamine": "2",
 "cordron-12 dm": "2",
 "codituss dh": "2",
 "codituss dm": "2",
 "clevidipine": "2",
 "carbofed dm drops": "2",
 "chlorphenesin": "2",
 "codimal": "2",
 "capozide 25/25": "2",
 "coricidin night time cold relief": "2",
 "cydec": "2",
 "comtrex flu therapy": "2",
 "coumadin": "1",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "comtrex acute head cold": "2",
 "creomulsion pediatric": "2",
 "colrex compound": "2",
 "cryselle": "1",
 "coricidin hbp maximum strength flu": "2",
 "colidrops": "2",
 "corzall": "2",
 "chemdal hd plus": "2",
 "carbiset": "2",
 "c.p.m.": "2",
 "chlorafed": "2",
 "coughtuss": "2",
 "cardizem sr": "2",
 "celecoxib": "2",
 "codimal dm": "2",
 "cheratussin dac": "2",
 "cydec-dm syrup": "2",
 "calan sr": "2",
 "contac 12 hour": "2",
 "carbetapentane/phenylephrine/pyrilamine": "2",
 "carozide": "2",
 "c-tanna 12": "2",
 "coldex": "2",
 "cetirizine": "2",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "ceron": "2",
 "celexa": "2",
 "chlornade": "2",
 "codafen": "2",
 "corzall plus": "2",
 "certuss": "2",
 "coldec": "2",
 "carbetaplex": "2",
 "codafed": "2",
 "clemastine/phenylpropanolamine": "2",
 "cleviprex": "2",
 "comtrex cold and flu maximum strength liquid": "2",
 "char-flo with sorbitol": "2",
 "codegest expectorant": "2",
 "carba-xp": "2",
 "catapres-tts": "2",
 "comtrex allergy sinus": "2",
 "colrex": "2",
 "candesartan": "2",
 "cp dec drops": "2",
 "chlorphedrin sr": "2",
 "complete sinus relief": "2",
 "clozaril": "2",
 "chlorpheniramine/phenylephrine/pyrilamine": "2",
 "carbaxef-dm": "2",
 "capacet": "2",
 "chlorcyclizine/codeine": "2",
 "cascor": "2",
 "chlorpheniramine/guaifenesin/pseudoephedrine": "2",
 "curaler": "2",
 "comtan": "2",
 "c-phen dm": "2",
 "chlo tuss": "2",
 "contac cold and flu maximum strength": "2",
 "carbetapentane/pyrilamine": "2",
 "carbetapentane/phenylephrine/potassium guaiacolsulfonate": "2",
 "carbinoxamine/dextromethorphan/pseudoephedrine": "2",
 "coryza-dm": "2",
 "clorfed": "2",
 "chemdal hd": "2",
 "c-hist-sr": "2",
 "capozide 25/15": "2",
 "clomipramine": "2",
 "carbatuss": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "coldtuss-dr": "2",
 "carbomix": "2",
 "cophene-x": "2",
 "childrens kaopectate": "2",
 "chlorpheniramine/dextromethorphan/phenylephrine": "2",
 "ceron-dm": "2",
 "contac severe cold and flu maximum stength": "2",
 "creomulsion cough/cold/allergy": "2",
 "cetiri d": "2",
 "cold medicine plus": "2",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "cardec": "2",
 "coricidin hbp cold &amp; flu": "2",
 "codal-dm syrup": "2",
 "cardura xl": "2",
 "cycofed": "2",
 "cuvposa": "2",
 "clolar": "2",
 "counteract pm extra strength": "2",
 "captopril/hydrochlorothiazide": "2",
 "chlortan": "2",
 "comtrex nighttime cold &amp; cough": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/phenyltoloxamine": "2",
 "contac 12 hour allergy": "2",
 "carboxine dm": "2",
 "chlorpheniramine/methscopolamine/pseudoephedrine": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "clobazam": "2",
 "clonazepam": "2",
 "comtrex cold and flu maximum strength tablet": "2",
 "chardonna-2": "2",
 "carbinoxamine/dextromethorphan/phenylephrine": "2",
 "carb pseudo-tan": "2",
 "cardene iv": "2",
 "clindex": "2",
 "chlortan d": "2",
 "capozide": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine": "2",
 "coldcough syrup": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "cotab a": "2",
 "celebrex": "2",
 "carbinoxamine/pseudoephedrine": "2",
 "chloral hydrate": "2",
 "combigan": "2",
 "charcoaid 2000": "2",
 "cardec-s": "2",
 "coryza-d": "2",
 "cordron-d nr": "2",
 "chem mart nasal decongestant capsule": "2",
 "cotab ax": "2",
 "cholestyramine": "1",
 "charcoal/simethicone": "2",
 "cpm-pe-msc": "2",
 "c phen": "2",
 "cardene sr": "2",
 "cordron-dm nr": "2",
 "chlorpheniramine/hydrocodone": "2",
 "cesia": "1",
 "cough formula m multi-symptom": "2",
 "coricidin hbp day &amp; night multi-symptom cold": "2",
 "corlopam": "1",
 "comtrex nighttime flu therapy": "2",
 "co-histine expectorant": "2",
 "cheracol with codeine": "2",
 "charcotabs": "2",
 "coreg cr": "2",
 "comtrex allergy sinus night and day": "2",
 "comfort pac with cyclobenzaprine": "2",
 "carbacot": "2",
 "cardene": "2",
 "clear cough pm multi-symptom": "2",
 "codimal-la half": "2",
 "cycloset": "2",
 "chlordiazepoxide/clidinium": "2",
 "cardizem": "2",
 "chlorthalidone/clonidine": "2",
 "coldec d": "2",
 "chlorpheniramine/phenylephrine/phenyltoloxamine": "2",
 "chlorpheniramine/dextromethorphan/pseudoephedrine": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "1",
 "calan": "2",
 "c-phed dm": "2",
 "charcotrace": "2",
 "clorpres": "2",
 "combiflex": "2",
 "chlorpheniramine/methscopolamine/phenylpropanolamine": "2",
 "cp dec dm": "2",
 "chlordrine sr": "2",
 "chlorpheniramine/hydrocodone/pseudoephedrine": "2",
 "clorfed ii": "2",
 "clopine": "2",
 "chlo tuss ex": "2",
 "comtrex cold and flu maximum strength": "2",
 "carbinoxamine": "2",
 "chlorex-a 12": "2",
 "compazine": "2",
 "corfen-dm": "2",
 "charcocaps": "2",
 "clidinium": "2",
 "carbetapentane/guaifenesin": "2",
 "chlordiazepoxide/methscopolamine": "2",
 "corzall-pe": "2",
 "cystex": "1",
 "codeine/phenylephrine": "2",
 "cyclessa": "1",
 "cordron-hc nr": "2",
 "cp dec": "2",
 "comhist": "2",
 "chlo-amine": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "carbamazepine": "2",
 "cyndal expectorant": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "chlophedianol/chlorcyclizine/pseudoephedrine": "2",
 "carvedilol": "2",
 "chlorpheniramine/phenylephrine": "2",
 "chlorphen hd": "2",
 "cvs allergy &amp; sinus headache": "2",
 "codimal ph": "2",
 "children's triacting night time": "2",
 "cyndal hd": "2",
 "coldamine": "2",
 "carbetapentane/pseudoephedrine": "2",
 "caziant": "1",
 "chlorpheniramine/dextromethorphan/guaifenesin/methscopolamine/phenylephrine": "2",
 "chlor-trimeton decongestant": "2",
 "certuss-d": "2",
 "chlorpheniramine/phenindamine/phenylpropanolamine": "2",
 "codafed pediatric": "2",
 "cafgesic forte": "2",
 "cephadyn": "2",
 "carbatrol": "2",
 "carbetapentane/guaifenesin/pseudoephedrine": "2",
 "covangesic": "2",
 "cardura": "2",
 "comtrex allergy sinus maximum strength": "2",
 "contac day and night cold and flu": "2",
 "cholestyramine light": "1",
 "cellulase/hyoscyamine/pancrelipase/phenyltoloxamine": "2",
 "chlordex gp": "2",
 "chlorgest hd": "2",
 "cyanide antidote kit": "2",
 "codeine/guaifenesin": "2",
 "camreselo": "1",
 "cartia xt": "2",
 "corzide 80/5": "2",
 "codeine phosphate-promethazine hcl": "2",
 "comhist la": "2",
 "cystospaz": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "carbetapentane/carbinoxamine/phenylephrine": "2",
 "canges-hc nr": "2",
 "codeine": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "codral cold and flu + cough day and night": "2",
 "carboxine 12 dm": "2",
 "cordron nr": "2",
 "cordron-hc": "2",
 "coricidin d": "2",
 "coricidin hbp cough &amp; cold": "2",
 "chlorpheniramine/hydrocodone/phenylephrine": "2",
 "cozaar": "2",
 "cerebyx": "2",
 "chemdal expectorant": "2",
 "carbosorb x": "2",
 "coldcough pd": "2",
 "c phen drops": "2",
 "cetirizine/pseudoephedrine": "2",
 "congestant": "2",
 "chlor-phenit": "2",
 "chlophedianol/pseudoephedrine": "2",
 "codahistine expectorant": "2",
 "cardizem cd": "2",
 "cogentin": "2",
 "chlorpheniramine/guaifenesin/phenylephrine": "2",
 "chlorex a": "2",
 "carbinoxamine/hydrocodone/pseudoephedrine": "2",
 "coricidin hbp nighttime multi-symptom cold": "2",
 "cyclafem 1/35": "1",
 "chlorphen": "2",
 "corgard": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "cp dec-dm drops": "2",
 "chlor-mes d": "2",
 "comtrex sinus and nasal": "2",
 "caduet": "2",
 "clonidine er": "2",
 "carb pse 12 dm": "2",
 "charcoaid": "2",
 "carbinoxamine/hydrocodone/phenylephrine": "2",
 "chlorpheniramine": "2",
 "cafgesic": "2",
 "carboxine-d": "2",
 "carbetapentane/chlorpheniramine/phenylephrine": "2",
 "codeine/pseudoephedrine": "2",
 "codal-dh syrup": "2",
 "c-phen dm drops": "2",
 "complete allergy": "2",
 "clofarabine": "2",
 "carbetapentane/dexchlorpheniramine/phenylephrine": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "clozapine synthon": "2",
 "centergy dm": "2",
 "carbetapentane/chlorpheniramine": "2",
 "chlorpheniramine/dextromethorphan/guaifenesin/phenylephrine": "2",
 "cafatine pb": "2",
 "chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "chlordiazepoxide": "2",
 "chlor-trimeton sinus": "2",
 "cytuss-hc nr": "2",
 "capital with codeine suspension": "2",
 "calm-aid": "2",
 "cyclobenzaprine": "2",
 "children's nyquil": "2",
 "chlortox": "2",
 "chlorpheniramine/phenylpropanolamine": "2",
 "comtrex day and night": "2",
 "cognex": "1",
 "comtrex maximum strength cold relief": "2",
 "cardizem monovial": "2",
 "clofera": "2",
 "cpm-pse dm drops": "2",
 "cantil": "2",
 "chlor-trimeton allergy sr": "2",
 "chlophedianol/guaifenesin/phenylephrine": "2",
 "canges-hc": "2",
 "cvs allergy &amp; cold": "2",
 "carbetapentane/pseudoephedrine/pyrilamine": "2",
 "corzide": "2",
 "cerose dm": "2",
 "chlorpheniramine/methscopolamine/phenylephrine": "2",
 "chlorafed timecelles": "2",
 "compoz nighttime sleep aid": "2",
 "chlophedianol/guaifenesin/pseudoephedrine": "2",
 "carbetaplex ts": "2",
 "coartem": "2",
 "children's zyrtec": "2",
 "contac day and night allergy": "2",
 "comtrex cold &amp; cough day night": "2",
 "conjugated estrogens/meprobamate": "2",
 "cordron-12 d": "2",
 "conal": "2",
 "cophene no 2": "2",
 "chlorpheniramine/methscopolamine": "2",
 "contac cold+flu maximum strength": "2",
 "chlor trimeton allergy decongestant": "2",
 "carisoprodol": "2",
 "celontin": "2",
 "chlorpheniramine/ephedrine/guaifenesin": "2",
 "ceron-dm drops": "2",
 "clemastine": "2",
 "chlor-trimeton": "2",
 "carbofed dm syrup": "2",
 "carbatuss-cl": "2",
 "chlorpheniramine/guaifenesin/methscopolamine/phenylephrine": "2",
 "chlorpheniramine/pseudoephedrine": "2",
 "cystospaz-m": "2",
 "chlorpheniramine/guaifenesin/hydrocodone/pseudoephedrine": "2",
 "combiflex es": "2",
 "coreg": "2",
 "chlophedianol": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "codeine/pseudoephedrine/triprolidine": "2",
 "conzip": "3"}, "b": {"bellaphen-s": "2",
 "betaxolol": "2",
 "bromatane dx": "2",
 "benadryl-d allergy plus sinus": "2",
 "brompheniramine/hydrocodone/phenylephrine": "2",
 "brovex-d": "2",
 "bismarex": "2",
 "benzacot": "2",
 "brevibloc": "2",
 "bromfenex pd": "2",
 "bromfenex pe": "2",
 "b-vex d": "2",
 "benahist-50": "2",
 "bromaline": "2",
 "brompheniramine/chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "brom tann": "2",
 "busulfex": "2",
 "bystolic": "2",
 "bromaxefed dm rf syrup": "2",
 "benaphen plus": "2",
 "brompheniramine/dextromethorphan/guaifenesin/phenylpropanolamine": "2",
 "biofed-pe": "2",
 "benzthiazide": "2",
 "buproban": "3",
 "by-ache": "2",
 "brovex pb": "2",
 "brovex pd": "2",
 "bayer pm": "2",
 "bromaline dm": "2",
 "bromph hd": "2",
 "brovex peb dm": "2",
 "balsam peru/benzyl benzoate/bismuth resorcin/bismuth subgallate/zinc oxide": "2",
 "bromodiphenhydramine/codeine": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "bromfenex": "2",
 "benicar hct": "2",
 "bromfed": "2",
 "buspirone": "2",
 "bitex liquid": "2",
 "brovex hc": "2",
 "bemote": "2",
 "bel-phen-ergot": "2",
 "bromocriptine": "2",
 "butisol sodium": "2",
 "butabarbital": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "benadryl": "2",
 "bpm pe hc": "2",
 "belladonna tincture": "2",
 "brovex": "2",
 "betapace af": "2",
 "bumetanide": "2",
 "berkley and jensen acid reducer maximum strength": "1",
 "belladonna/butabarbital": "2",
 "briellyn": "1",
 "b-vex pd": "2",
 "benadryl allergy plus cold": "2",
 "bumex": "2",
 "brovex pb cx": "2",
 "betapace": "2",
 "bromfed-pd capsules": "2",
 "bromplex hd": "2",
 "bidhist-d": "2",
 "brompheniramine/dextromethorphan/pseudoephedrine": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "brom tann pe": "2",
 "benadryl children's allergy and sinus": "2",
 "balacall dm": "2",
 "brovex ct": "2",
 "benadryl allergy sinus": "2",
 "biotussin dac": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "budeprion": "3",
 "butrans": "2",
 "bromax": "2",
 "bromhist-pdx": "2",
 "beyaz": "1",
 "budeprion sr": "3",
 "byclomine": "2",
 "bismuth subgallate": "2",
 "banaril": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "brontex": "2",
 "betaseron": "2",
 "bromatan-dm": "2",
 "bidil": "2",
 "bicarsim": "2",
 "benadryl allergy": "2",
 "bentyl": "2",
 "balacet": "3",
 "bonine": "2",
 "bellaspas": "2",
 "brompheniramine/hydrocodone/pseudoephedrine": "2",
 "benadryl allergy plus sinus headache": "2",
 "butorphanol": "2",
 "black cohosh": "2",
 "brovex psb dm": "2",
 "bromfenex pe pediatric": "2",
 "benemid": "1",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bromtann/dm tann/pse tann": "2",
 "busulfan": "2",
 "bicarsim forte": "2",
 "banflex": "2",
 "bellamine": "2",
 "bepridil": "2",
 "beflex": "2",
 "bel-tabs": "2",
 "belix": "2",
 "beldin": "2",
 "bromaphen": "2",
 "bendroflumethiazide": "2",
 "brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "benicar": "2",
 "bendroflumethiazide/nadolol": "2",
 "bromfed dm": "2",
 "bupropion": "3",
 "bromhist-dm drops": "2",
 "busodium": "2",
 "bismatrol": "2",
 "brompheniramine": "2",
 "benahist-10": "2",
 "brompheniramine/dextromethorphan/guaifenesin/pseudoephedrine": "2",
 "brovex cb": "2",
 "balziva": "1",
 "brevital sodium": "2",
 "brimonidine ophthalmic": "2",
 "brompheniramine/phenylpropanolamine": "2",
 "bromhist-nr": "2",
 "banophen": "2",
 "benylin multi-symptom": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "brovex pse dm": "2",
 "bromanate dx cough": "2",
 "brompheniramine/chlophedianol/pseudoephedrine": "2",
 "be-flex plus": "2",
 "betatan": "2",
 "buprenex": "2",
 "benadryl severe allergy &amp; sinus headache": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "butex forte": "2",
 "buprenorphine/naloxone": "3",
 "brovex pb dm": "2",
 "brimonidine/timolol ophthalmic": "2",
 "bydramine": "2",
 "brompheniramine/diphenhydramine": "2",
 "benztropine": "2",
 "brompheniramine/codeine": "2",
 "brompheniramine/phenylephrine": "2",
 "bromadine-dm": "2",
 "brometane dx": "2",
 "b &amp; o supprettes": "2",
 "bismuth subsalicylate": "2",
 "bp allergy dm": "2",
 "biperiden": "2",
 "bromtapp-dm": "2",
 "bismatrol maximum strength": "2",
 "budeprion xl": "3",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "2",
 "brompheniramine/dextromethorphan/phenylephrine": "2",
 "bromaxefed rf syrup": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "brompheniramine/dextromethorphan/guaifenesin/phenylephrine": "2",
 "bidhist": "2",
 "bromph dm": "2",
 "b-vex": "2",
 "bp poly-650": "2",
 "brovex sr": "2",
 "bronkotuss": "2",
 "bellergal-s": "2",
 "benzocaine/trimethobenzamide": "2",
 "bellalphen": "2",
 "bromcomp hc": "2",
 "bismuth subnitrate/calcium hydroxide": "2",
 "brovex psb": "2",
 "bromaphedrine d": "2",
 "bellamine s": "2",
 "b-tuss": "2",
 "bilberry/evening primrose/flax": "1",
 "broncopectol": "2",
 "buspar": "2",
 "bellatal er": "2",
 "benadryl severe allergy plus sinus headache": "2",
 "bpm pe": "2",
 "blocadren": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "benazepril/hydrochlorothiazide": "2",
 "brexin la": "2",
 "brovex pse dm tablets": "2",
 "benzoic acid/methenamine/sodium salicylate": "1",
 "ben-tann": "2",
 "bronkids": "2",
 "bupap": "2",
 "bromhist pediatric": "2",
 "biodec dm": "2",
 "bisoprolol": "2",
 "belcomp-pb": "2",
 "brovex pse": "2",
 "brevicon": "1",
 "brovex adt": "2",
 "butalbital compound": "2",
 "belladonna": "2",
 "bromplex dm": "2",
 "betavent": "2",
 "brovex peb": "2",
 "biohist la": "2",
 "baclofen": "2",
 "brovex pb c": "2",
 "bromphenex dm": "2",
 "bromhist-dm": "2",
 "benoject-50": "2",
 "bellamor": "2",
 "bellahist-d la": "2",
 "benadryl children's allergy": "2",
 "bromhist pediatric drops": "2",
 "buprenorphine": "2",
 "belladonna/opium": "2",
 "butibel": "2",
 "butalbital": "2",
 "barbidonna": "2",
 "bromtuss dm": "2",
 "brompheniramine/phenylephrine/phenylpropanolamine": "2",
 "brompheniramine/pseudoephedrine": "2",
 "bpm pe dm": "2",
 "brompheniramine/codeine/pseudoephedrine": "2",
 "bellatal": "2",
 "bromophed-dx": "2",
 "bucet": "2",
 "brovex cbx": "2",
 "bromdex d": "2",
 "benadryl cold": "2",
 "brompheniramine/carbetapentane/phenylephrine": "2",
 "bp allergy jr": "2"}, "e": {"efasin-hd plus": "2",
 "escitalopram": "2",
 "endep": "2",
 "ed chlorped": "2",
 "ethinyl estradiol/levonorgestrel": "1",
 "ephedrine/phenobarbital/theophylline": "2",
 "enpresse": "1",
 "exall": "2",
 "eprosartan": "2",
 "ed chlor-tan": "2",
 "ex-tuss": "2",
 "estrostep fe": "1",
 "endacof-pd": "2",
 "enflurane": "2",
 "ethinyl estradiol/etonogestrel": "1",
 "esocor p": "2",
 "embeda": "2",
 "eperbel-s": "2",
 "exforge hct": "2",
 "extendryl pse": "2",
 "extendryl sr": "2",
 "elavil": "2",
 "endal hd": "2",
 "extendryl dm": "2",
 "extendryl": "2",
 "execlear-c": "2",
 "esidrix": "2",
 "ergocomp-pb": "2",
 "edarbi": "2",
 "exo-tuss": "2",
 "esgic": "2",
 "endacof hc": "2",
 "ethinyl estradiol": "1",
 "ed-spaz": "2",
 "ethinyl estradiol/norgestrel": "1",
 "elixiral": "2",
 "emoquette": "1",
 "estinyl": "1",
 "edarbyclor": "2",
 "ez iii": "2",
 "extendryl gcp": "2",
 "ethosuximide": "2",
 "excedrin pm": "2",
 "ezogabine": "2",
 "efasin-hd": "2",
 "enalapril/felodipine": "2",
 "eszopiclone": "2",
 "endal expectorant": "2",
 "esmolol": "2",
 "exforge": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ethinyl estradiol/norethindrone": "1",
 "equaline heartburn relief": "1",
 "ephedrine/hydroxyzine/theophylline": "2",
 "endal cd": "2",
 "ethanol": "3",
 "esimil": "2",
 "etrafon forte": "2",
 "exna": "2",
 "endagen-hd": "2",
 "e-caff p-b": "2",
 "equetro": "2",
 "enalapril/hydrochlorothiazide": "2",
 "equaline acid reducer": "2",
 "endolor": "2",
 "epitol": "2",
 "ergocaf-pb": "2",
 "extendryl seniors": "2",
 "efavirenz": "2",
 "enlon-plus": "2",
 "endacof-ac": "2",
 "ethyl alcohol": "3",
 "extendryl pem": "2",
 "effexor xr": "2",
 "endacof-dc": "2",
 "ed a-hist": "2",
 "extendryl jr": "2",
 "equate sleep aid": "2",
 "endacof-dh": "2",
 "epidrin": "2",
 "endacof-dm": "2",
 "equitan pediatric": "2",
 "ed-flex": "2",
 "edluar": "2",
 "excof": "2",
 "excof-sf": "2",
 "entereg": "3",
 "ethinyl estradiol/norgestimate": "1",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "3",
 "eskalith": "2",
 "efasin expectorant sf": "2",
 "entacapone": "2",
 "ezchar": "2",
 "eskalith-cr": "2",
 "empirin with codeine": "2",
 "effective strength cough syrup": "2",
 "exall-d": "2",
 "echotuss-hc": "2",
 "endotuss expectorant": "2",
 "enalapril": "2",
 "ethotoin": "2",
 "equagesic": "2",
 "enablex": "2",
 "enditussin expectorant": "2",
 "endotuss-hd": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "equaline sleep aid": "2",
 "entre-b": "2",
 "exjade": "2",
 "ed a-hist dm": "2",
 "ezide": "2",
 "ed a-hist la": "2",
 "ethinyl estradiol/ethynodiol": "1",
 "endacof pd drops": "2",
 "entre-s": "2",
 "etrafon": "2",
 "exratuss": "2",
 "ed dm": "2",
 "esgic-plus": "2",
 "ethinyl estradiol/norelgestromin": "1",
 "endafed": "2",
 "estazolam": "2",
 "ex-histine": "2",
 "endal-hd plus": "2",
 "equanil": "2",
 "endacof-c": "2",
 "ex-dec-tr": "2",
 "ent": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "effexor": "2",
 "extavia": "2",
 "expectuss": "2",
 "equate allergy &amp; sinus headache": "2",
 "evening primrose oil": "1",
 "ed-tuss hc": "2",
 "enplus-hd": "2",
 "ethrane": "2",
 "ezol": "2",
 "ergocaffpb": "2",
 "equi-nade": "2",
 "evening primrose": "1",
 "ed-tlc": "2",
 "extendryl chews": "2",
 "eze ds": "2",
 "eucarbon": "2",
 "ed chlorped d": "2"}, "d": {"diovan": "2",
 "dayhist-d": "2",
 "desflurane": "2",
 "demi-regroton": "2",
 "doloral": "2",
 "diphenydramine quick melt": "2",
 "dexchlorpheniramine/methscopolamine/pseudoephedrine": "2",
 "durahist pe": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine": "2",
 "delsym night time multi-symptom": "2",
 "dexchlorpheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "di-delamine": "2",
 "desogestrel/ethinyl estradiol": "1",
 "duratan dm": "2",
 "diltiazem hydrochloride sr": "2",
 "divalproex sodium": "2",
 "duodote": "2",
 "da ii": "2",
 "di-spaz": "2",
 "dayhist-1": "2",
 "dimetapp children's long acting cough plus cold": "2",
 "diphenadryl": "2",
 "detuss": "2",
 "ditropan xl": "2",
 "dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "depakote er": "2",
 "dolgic": "2",
 "de-chlor mr": "2",
 "dytan-at": "2",
 "dolmar": "2",
 "drixoral": "2",
 "drize": "2",
 "dibenzyline": "2",
 "duravent": "2",
 "dilatrate-sr": "2",
 "dicyclomine": "2",
 "dallergy pe": "2",
 "diphenhydramine/ibuprofen": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "darifenacin": "2",
 "doxepin topical": "2",
 "diphenhydramine/tripelennamine topical": "2",
 "dimaphen dm": "2",
 "droperidol": "2",
 "dmax pediatric": "2",
 "decon-a": "2",
 "delsym children's night time cough &amp; cold": "2",
 "diphenmax d": "2",
 "duratuss da": "2",
 "duogesic": "2",
 "darpaz": "2",
 "duradryl jr": "2",
 "duradryl": "2",
 "dytan": "2",
 "d-hist d": "2",
 "depakote": "2",
 "dibrom": "2",
 "dimaphen elixir": "2",
 "diabetic tussin c": "2",
 "dryphen": "2",
 "dec-chlorphen dm": "2",
 "dytan-d": "2",
 "durahist d": "2",
 "depakote sprinkles": "2",
 "dailyhist-1": "2",
 "delhist d": "2",
 "deconsal c expectorant": "2",
 "dexchlorpheniramine/methscopolamine/phenylephrine": "2",
 "de-congestine": "2",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "dicyclocot": "2",
 "dimetapp children's cold &amp; cough": "2",
 "dronabinol": "2",
 "deconsal ct tannate": "2",
 "detrol la": "2",
 "diasorb": "2",
 "dantrolene": "2",
 "drysec": "2",
 "dilantin": "2",
 "drixoral sinus": "2",
 "disobrom": "2",
 "dimetapp children's nighttime flu": "2",
 "dicomal-dh": "2",
 "deponit": "2",
 "drihist sr": "2",
 "duomine": "2",
 "dynacirc cr": "2",
 "dasetta 7/7/7": "1",
 "dur-tann dm": "2",
 "demadex iv": "2",
 "dmax pediatric drops": "2",
 "dexophed": "2",
 "duramorph pf": "2",
 "dutoprol": "2",
 "donnatal": "2",
 "depade": "2",
 "durabac forte": "2",
 "dicopanol": "2",
 "donatussin max": "2",
 "diphenhydramine/guaifenesin": "2",
 "donnatal extentabs": "2",
 "drixoral cold/flu": "2",
 "desmopressin": "2",
 "dantrium intravenous": "2",
 "dec-chlorphen drops": "2",
 "diltzac": "2",
 "dixaphedrine": "2",
 "duraclon": "2",
 "donatussin pediatric": "2",
 "doans pm": "2",
 "ddavp nasal": "2",
 "diabetic tussin night time formula": "2",
 "demulen 1/35": "1",
 "darvon compound 32": "3",
 "diar-aid": "2",
 "drexophed sr": "2",
 "dacex-a": "2",
 "dihistine dh": "2",
 "dehistine": "2",
 "duravent da": "2",
 "doxazosin": "2",
 "dristan cold multi symptom formula": "2",
 "despec-pd": "2",
 "dura-ron dm": "2",
 "deconsal dm tannate": "2",
 "diphenyl": "2",
 "delsym night time cough &amp; cold": "2",
 "dexall": "2",
 "dramamine ii": "2",
 "dimetapp children's multi-symptom cold &amp; flu": "2",
 "diaqua-2": "2",
 "drotuss-cp": "2",
 "dolobid": "1",
 "dmax": "2",
 "d-tann at": "2",
 "diphen": "2",
 "dilacor xr": "2",
 "deprizine": "1",
 "dyrenium": "2",
 "drymax": "2",
 "dimetane extentab": "2",
 "darvon-n": "3",
 "delta-lutin": "2",
 "digex": "2",
 "demulen": "1",
 "darvon": "3",
 "dicumarol": "1",
 "diltia xt": "2",
 "duratan pe": "2",
 "dec-chlorphen": "2",
 "doxylamine/pseudoephedrine": "2",
 "depodur": "2",
 "darvon compound-65": "3",
 "dimetapp children's cold &amp; allergy": "2",
 "diazepam intensol": "2",
 "di-gon ii": "2",
 "desyrel dividose": "2",
 "donnagel": "2",
 "d-tal": "2",
 "d-tann hc": "2",
 "dexmedetomidine": "2",
 "diphedryl": "2",
 "dcp drops": "2",
 "decohistine dh": "2",
 "d-tann cd": "2",
 "doxytex": "2",
 "darvocet-n 100": "3",
 "digex nf": "2",
 "dytuss": "2",
 "dexfenfluramine": "2",
 "diazepam": "2",
 "disophrol": "2",
 "dicel dm": "2",
 "duravent dpb": "2",
 "donatussin dm drops": "2",
 "drocon-cs": "2",
 "diprivan": "2",
 "dolgic lq": "2",
 "dallergy drops": "2",
 "duotan dm": "2",
 "duloxetine": "2",
 "dmax syrup": "2",
 "desvenlafaxine": "2",
 "disposable enema": "3",
 "dilt-xr": "2",
 "darvocet a500": "3",
 "diastat": "2",
 "demadex": "2",
 "dimetapp allergy": "2",
 "durabac": "2",
 "detrol": "2",
 "duramorph": "2",
 "dynahist er": "2",
 "dalgan": "2",
 "diltiazem hydrochloride cd": "2",
 "diovan hct": "2",
 "desihist sa": "2",
 "dexbrompheniramine/dextromethorphan/pseudoephedrine": "2",
 "dextromethorphan/doxylamine": "2",
 "devrom": "2",
 "demi-cof": "2",
 "dolgic plus": "2",
 "drixoral cold and allergy": "2",
 "duradryl chewable": "2",
 "dilomine": "2",
 "drihist": "2",
 "diacetazone": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "dph": "2",
 "duragal-s": "2",
 "dex-tuss": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "1",
 "drixoral cold and flu": "2",
 "diphenmax": "2",
 "duralex": "2",
 "dec-chlorphen dm drops": "2",
 "duratuss cs": "2",
 "doxepin": "2",
 "darcalma": "2",
 "dihydro-pe": "2",
 "diltiazem hydrochloride xt": "2",
 "diltiazem hydrochloride xr": "2",
 "ddavp rhinal tube": "2",
 "dexbrompheniramine/pseudoephedrine": "2",
 "dm cold and cough": "2",
 "dologesic": "2",
 "de-chlor hd": "2",
 "de-chlor hc": "2",
 "dyazide": "2",
 "diaqua": "2",
 "demazin": "2",
 "dime time extended release": "2",
 "duradrin": "2",
 "deconamine": "2",
 "drixomed": "2",
 "dynex vr": "2",
 "dytan-hc": "2",
 "diastat acudial": "2",
 "da chewable": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "diucardin": "2",
 "diastat pediatric": "2",
 "duratuss ac 12": "2",
 "depacon": "2",
 "denaze": "2",
 "dura-ron": "2",
 "diazoxide": "2",
 "dasetta": "1",
 "dolophine": "2",
 "diphentann-d": "2",
 "dihistine expectorant with codeine": "2",
 "deserpidine/hydrochlorothiazide": "2",
 "dynatuss": "2",
 "dexbrompheniramine/pyrilamine": "2",
 "dexbrompheniramine/hydrocodone/phenylephrine": "2",
 "d-tann ct": "2",
 "dibent": "2",
 "duradal hd": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "2",
 "dimetane dx": "2",
 "diphenhist": "2",
 "dalmane": "2",
 "dallergy dm": "2",
 "donatussin": "2",
 "deconsal dm": "2",
 "doloral sirop": "2",
 "donnaphen": "2",
 "dexodryl suspension": "2",
 "di-bromm": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "ddavp": "2",
 "dimetapp elixir": "2",
 "dytan-cd": "2",
 "ditropan": "2",
 "dytan-cs": "2",
 "dexbrompheniramine/phenylephrine": "2",
 "dytan-dm": "2",
 "desyrel": "2",
 "driminate ii": "2",
 "doral": "2",
 "dizac": "2",
 "deconhist la": "2",
 "dezocine": "2",
 "dutasteride/tamsulosin": "2",
 "dolsed": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "1",
 "duraxin": "2",
 "dehydrated alcohol": "3",
 "d-tann dm": "2",
 "demulen 1/50": "1",
 "ditussin-hc": "2",
 "diphenhydramine": "2",
 "decahist-dm": "2",
 "dicel cd": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "dynacirc": "2",
 "depakene": "2",
 "dura-vent/a": "2",
 "duohist dh": "2",
 "dallergy pse": "2",
 "deconsal ct": "2",
 "dihistine": "2",
 "dexodryl": "2",
 "desogen": "1",
 "dasetta 1/35": "1",
 "decongex-3": "2",
 "dramamine less drowsy": "2",
 "diltiazem": "2",
 "dicel": "2",
 "d-tann": "2",
 "duotan": "2",
 "duralutin": "2",
 "droperidol/fentanyl": "2",
 "delhistine d": "2",
 "d-vert": "2",
 "dihydro-cp": "2",
 "delhistine dm": "2",
 "diphendryl": "2",
 "diphenylin": "2",
 "deproist with codeine": "2",
 "decohistine expectorant": "2",
 "dm-pe-chlor": "2",
 "durafed": "2",
 "duo-vil": "2",
 "deferasirox": "2",
 "dexphen m": "2",
 "dihistine expectorant": "2",
 "dolorex": "2",
 "diarrest": "2",
 "diuretic ap-es": "2",
 "dexbrompheniramine/phenylephrine/pyrilamine": "2",
 "dynahist-er pediatric": "2",
 "donatussin syrup": "2",
 "donnamar": "2",
 "desipramine": "2",
 "duadacin": "2",
 "dormin": "2",
 "d-amine-sr": "2",
 "dicomal-ph": "2",
 "doxadura": "2",
 "denzapine": "2",
 "dallergy jr": "2",
 "drospirenone/ethinyl estradiol": "1",
 "diphen af": "2",
 "drixoral allergy sinus": "2",
 "dextromethorphan/doxylamine/pseudoephedrine": "2",
 "durahistine dm": "2",
 "dallergy er": "2",
 "de-chlor dr": "2",
 "dexaphen sa": "2",
 "duradryl sr": "2",
 "doxylamine": "2",
 "deconomed sr": "2",
 "de-chlor dm": "2",
 "dantrium": "2",
 "darvocet-n 50": "3",
 "duraganidin nr": "2",
 "durahist": "2",
 "dimetane decongestant": "2",
 "diphenhydramine/phenylephrine": "2",
 "dura-tap/pd": "2",
 "diphen cough": "2",
 "diamode": "2",
 "donatussin dm": "2",
 "dex pc": "2",
 "dextromethorphan/phenylephrine/pyrilamine": "2",
 "deconamine sr": "2",
 "dristan cold maximum strength": "2",
 "diphenhydramine/pseudoephedrine": "2"}, "g": {"genahist": "2",
 "gabitril": "2",
 "guaifenesin/phenylephrine/pyrilamine": "2",
 "guaifen-c": "2",
 "glydeine": "2",
 "gencold": "2",
 "gablofen": "2",
 "guanethidine": "2",
 "guaifen ac": "2",
 "guaitussin ac": "2",
 "gendecon": "2",
 "genora 0.5/35": "1",
 "generess fe": "1",
 "genapap pm": "2",
 "gastrinex": "2",
 "guiatuss dac": "2",
 "genacol maximum strength": "2",
 "gralise": "2",
 "gildess fe 1.5/30": "1",
 "glycopyrrolate": "2",
 "guiatussin with codeine": "2",
 "gelpirin-ccf": "2",
 "geone": "2",
 "g-1": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylpropanolamine/pyrilamine": "2",
 "gianvi": "1",
 "guai-co": "2",
 "gani-tuss nr": "2",
 "gentex lq": "2",
 "guiatussin dac": "2",
 "genasec": "2",
 "gua pc": "2",
 "gildess fe 1/20": "1",
 "gestuss-hc": "2",
 "giltuss ped-c": "2",
 "ginkgo biloba": "2",
 "genac": "2",
 "gleevec": "2",
 "guiatuss ac": "2",
 "guaifenesin dac liquid": "2",
 "genamin": "2",
 "gastrosed": "2",
 "guanethidine/hydrochlorothiazide": "2",
 "geodon": "2",
 "gelhist pediatric": "2",
 "gelnique": "2",
 "ginkgo": "2",
 "genrx tramadol": "3",
 "genora 1/35": "1",
 "genora 1/50": "1",
 "genelan nf": "2",
 "guaiatussin ac": "2",
 "guaifen dac": "2",
 "gentex 30": "2",
 "genaphed plus": "2",
 "gabarone": "2",
 "guaiatussin dac": "2",
 "guiaphen hd": "2",
 "gabapentin": "2"}, "f": {"flexeril": "2",
 "fiortal": "2",
 "fleet enema": "3",
 "furosemide": "2",
 "fedahist gyrocaps": "2",
 "fiorinal with codeine iii": "2",
 "fesoterodine": "2",
 "flextra plus": "2",
 "flatulex": "2",
 "flomax": "2",
 "fleet ez-prep": "3",
 "fazaclo": "2",
 "fiorinal with codeine": "2",
 "fleet phospho soda": "3",
 "fortabs": "2",
 "flurazepam": "2",
 "fiorinal": "2",
 "fioricet with codeine": "2",
 "flutuss hc": "2",
 "fenoldopam": "1",
 "femcet": "2",
 "fosinopril": "2",
 "flextra-650": "2",
 "fedahist": "2",
 "fedahist timecaps": "2",
 "fenfluramine": "2",
 "felodipine": "2",
 "femhrt": "1",
 "flavoxate": "2",
 "fiortal with codeine": "2",
 "fosphenytoin": "2",
 "furazolidone": "3",
 "fluoxetine": "2",
 "flexon": "2",
 "fluoxetine/olanzapine": "2",
 "flexoject": "2",
 "fleet prep kit 1": "3",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "fanatrex": "2",
 "fluphenazine": "2",
 "father john's medicine plus": "2",
 "fexmid": "2",
 "felbamate": "2",
 "fleet enema extra": "3",
 "forfivo xl": "3",
 "fiormor": "2",
 "floricet with codeine": "2",
 "fospropofol": "2",
 "fioricet": "2",
 "fanapt": "2",
 "flextra-ds": "2",
 "forane": "2",
 "fluvoxamine": "2",
 "flextra": "2",
 "fluothane": "2",
 "farbital": "2",
 "fast sleep": "2",
 "furoxone": "3",
 "felbatol": "2",
 "folex pfs": "2",
 "femcon fe": "1",
 "fosinopril/hydrochlorothiazide": "2",
 "fiorpap": "2",
 "flumezide": "2"}, "i": {"isosorbide mononitrate": "2",
 "isordil": "2",
 "isradipine": "2",
 "imodium a-d": "2",
 "isoniazid/rifampin": "2",
 "indapamide": "2",
 "iohexol": "3",
 "innopran xl": "2",
 "invega": "2",
 "isovue-370": "3",
 "imatinib": "2",
 "irbesartan": "2",
 "iophen-c nr": "2",
 "iohist d": "2",
 "isdn": "2",
 "isordil tembids": "2",
 "inderal la": "2",
 "inapsine": "2",
 "imdur": "2",
 "isoniazid": "2",
 "imodium multi-symptom relief": "2",
 "iso-acetazone": "2",
 "isocom": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isovue-300": "3",
 "isocet": "2",
 "imipramine": "2",
 "inderide la": "2",
 "isoptin": "2",
 "isovue-200": "3",
 "imodium": "2",
 "intermezzo": "2",
 "iofed pd": "2",
 "inderide": "2",
 "isophen-df": "2",
 "insta-char": "2",
 "innovar": "2",
 "insta-char with sorbitol": "2",
 "isovue-m-300": "3",
 "iopidine": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "iopamidol-370": "3",
 "isordil titradose": "2",
 "ide-cet": "2",
 "isonarif": "2",
 "iopamidol": "3",
 "iohist dm": "2",
 "isosorbide dinitrate": "2",
 "isoflurane": "2",
 "infumorph": "2",
 "iloperidone": "2",
 "iofed": "2",
 "isocarboxazid": "3",
 "isovue-128": "3",
 "ismelin": "2",
 "isovue-m-200": "3",
 "iotussin hc": "2",
 "isoptin sr": "2",
 "inderal": "2",
 "iophen": "2",
 "isovue-250": "3",
 "invega sustenna": "2",
 "introvale": "1",
 "isoptin iv": "2",
 "idenal": "2",
 "ismo": "2",
 "isochron": "2",
 "iodal hd": "2",
 "imotil": "2",
 "ida": "2",
 "isoditrate": "2",
 "ib-stat": "2"}, "h": {"hydro-reserp": "2",
 "histex hc": "2",
 "hycodan": "2",
 "headache formula pm": "2",
 "histatab ph": "2",
 "histinex hc": "2",
 "hydrocodone hd": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydrap-es": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "hyomax sr": "2",
 "hydrocodone/phenylephrine/pyrilamine": "2",
 "hydrodiuril": "2",
 "hyoscyamine/phenyltoloxamine": "2",
 "hydrophed": "2",
 "hydrocodone gf": "2",
 "hyflex-ds": "2",
 "hyomax sl": "2",
 "hyflex-650": "2",
 "histine-d": "2",
 "hydroserpine 1": "2",
 "hyophen": "2",
 "hista-vent da": "2",
 "histussin hc liquid": "2",
 "hydrochlorothiazide/propranolol": "2",
 "histex ie": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "hyosyne": "2",
 "hydrotuss hc": "2",
 "hista-tabs": "2",
 "hydroxypropyl chitosan/terbinafine topical": "2",
 "hydra-zide": "2",
 "histade": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrocodone/pseudoephedrine/triprolidine": "2",
 "hydrochlorothiazide/reserpine": "2",
 "histadecdm": "2",
 "hydramine cough syrup": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "hydralazine/isosorbide dinitrate": "2",
 "hytrin": "2",
 "hydrocof-hc": "2",
 "homatropine/hydrocodone": "2",
 "hydropres-25": "2",
 "hyoscyamine/phenobarbital": "2",
 "histadec": "2",
 "hydron pcs": "2",
 "histalet forte": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hyzaar": "2",
 "helidac": "2",
 "hydrochlorothiazide/methyldopa": "2",
 "hyzine": "2",
 "hyomax ft": "2",
 "hydropres-50": "2",
 "histade cr": "2",
 "hydrochlorothiazide/moexipril": "2",
 "horizant": "2",
 "h-c tussive-nr": "2",
 "hyospaz": "2",
 "hista-vent pse": "2",
 "hycomal dh": "2",
 "hygroton": "2",
 "hista-vadrin": "2",
 "histacol dm pediatric syrup": "2",
 "hydromet": "2",
 "hydromide": "2",
 "hycomine compound": "2",
 "hydro par": "2",
 "hydroxy compound": "2",
 "halothane": "2",
 "hi-tuss hc": "2",
 "histinex pv": "2",
 "histex": "2",
 "histex pd": "2",
 "hydroxyprogesterone": "2",
 "hydro-pc ii": "2",
 "hyoscyamine": "2",
 "histafed la": "2",
 "headache relief pm": "2",
 "hyosol": "2",
 "hyoscyamine/methenamine": "2",
 "hyphed": "2",
 "halotussin dac": "2",
 "hyrexin": "2",
 "hyosophen": "2",
 "hyomax dt": "2",
 "halcion": "2",
 "hydroflumethiazide": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hydrocodone cp": "2",
 "hydropane": "2",
 "hyphen-hd": "2",
 "hyperstat iv": "2",
 "haldol decanoate": "2",
 "hydrotropine": "2",
 "hydro-dp": "2",
 "h-c tussive": "2",
 "highland dm": "2",
 "heb allergy": "2",
 "halotussin ac": "2",
 "hyomax": "2",
 "histatab": "2",
 "hydroserp": "2",
 "hydrochlorothiazide/timolol": "2",
 "hydroflumethiazide/reserpine": "2",
 "histatan": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hydrophene dh": "2",
 "hydro-pc ii plus": "2",
 "histafed": "2",
 "hydron cp": "2",
 "hydro-tussin cbx": "2",
 "hydrochlorothiazide": "2",
 "histacol bd drops": "2",
 "haldol": "2",
 "hhr": "2",
 "haloperidol": "2",
 "histinex dm": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "histex sr": "2",
 "hyprogesterone": "2",
 "hydramine compound": "2",
 "highland hc": "2",
 "hydroserpine": "2",
 "hydrochlorothiazide/losartan": "2",
 "hydralazine": "2",
 "healthstream activated charcoal": "2",
 "hayfebrol liquid": "2",
 "hexatussin": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hylutin": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hyco-dh": "2",
 "histex ct": "2",
 "hydroxyzine": "2",
 "hyperstat": "2",
 "hydro-tussin dhc": "2",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "histalet": "2",
 "histatab d": "2",
 "histatab plus": "2",
 "histussin hc syrup": "2",
 "hytan": "2",
 "hydramine": "2",
 "histamaxd": "2",
 "hydrocodone/pheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "hydralazine plus": "2",
 "halazepam": "2"}, "k": {"kadian": "2",
 "k-pek": "2",
 "kophane": "2",
 "klonopin wafer": "2",
 "k-pec": "2",
 "kaopectate": "2",
 "kg-fed expectorant": "2",
 "kapectolin": "2",
 "kaopectate ii": "2",
 "keppra xr": "2",
 "kg-fed": "2",
 "kaopectate anti-diarrheal upset stomach reliever": "2",
 "kidcare cough and cold": "2",
 "kaolin/pectin": "2",
 "karbons": "2",
 "kemstro": "2",
 "kg-dal hd": "2",
 "klonopin": "2",
 "ketamine": "2",
 "k-tan": "2",
 "kao-pulgite": "2",
 "klerist-d": "2",
 "kao-spen": "2",
 "kg hist dm": "2",
 "kelnor 1/35": "1",
 "kg-dal hd plus": "2",
 "ka-pec": "2",
 "kao-tin advanced formula": "2",
 "kao-tin bismuth subsalicylate formula": "2",
 "kg-fed pediatric expectorant": "2",
 "kronofed-a": "2",
 "kolephrin": "2",
 "kaolin": "2",
 "kerlone": "2",
 "ketalar": "2",
 "kaopectate 1-d": "2",
 "kao-paverin": "2",
 "kaletra": "3",
 "kg-tussin": "2",
 "kariva": "1",
 "kapvay": "2",
 "kava": "2",
 "kaodene nn suspension": "2",
 "kronofed-a-jr": "2",
 "kaopectate extra strength": "2",
 "kaopectate caplets": "2",
 "kg-hist d": "2",
 "k-tan 4": "2",
 "kemadrin": "2",
 "kaopek": "2",
 "k-c suspension": "2",
 "keppra": "2"}, "j": {"jolessa": "1",
 "jl bragg's medicinal charcoal": "2",
 "jenest": "1",
 "jaycof-hc": "2",
 "j-tan pd": "2",
 "junel 1.5/30": "1",
 "j-tan d sr": "2",
 "jantoven": "1",
 "jevantique": "1",
 "j-tand pd": "2",
 "junel fe 1/20": "1",
 "jinteli": "1",
 "j-cof dhc": "2",
 "jalyn": "2",
 "junel fe 1.5/30": "1",
 "j-tan": "2",
 "j-tan d hc": "2",
 "junel 1/20": "1",
 "jenloga": "2",
 "j-tan d": "2"}, "m": {"m-end wc": "2",
 "meridia": "2",
 "morphine sulfate er": "2",
 "myolin": "2",
 "maxifed cdx": "2",
 "meni-d": "2",
 "myci spray": "2",
 "marinol": "2",
 "miradon": "1",
 "micardis hct": "2",
 "marlissa": "1",
 "magsal": "2",
 "mestranol/norethindrone": "1",
 "maldemar": "2",
 "mhp-a": "2",
 "myphetane dc": "2",
 "midazolam": "2",
 "maolate": "2",
 "ms/s": "2",
 "methadone diskets": "2",
 "migracet-pb": "2",
 "myphetane dx": "2",
 "makena": "2",
 "mintex dm": "2",
 "momentum": "2",
 "minizide": "2",
 "morphine lp epidural": "2",
 "m-phen": "2",
 "methscopolamine/pseudoephedrine": "2",
 "mephobarbital": "2",
 "maldec-dm": "2",
 "moduretic": "2",
 "medicoal": "2",
 "major-gesic": "2",
 "mephenytoin": "2",
 "mescolor": "2",
 "mirapex": "2",
 "mar-cof bp": "2",
 "morphine liposomal": "2",
 "microgestin 1/20": "1",
 "monopril": "2",
 "m-clear": "2",
 "menopause support": "2",
 "metozolv odt": "2",
 "meclicot": "2",
 "migrin-a": "2",
 "mirtazapine": "2",
 "myogesic": "2",
 "morphine/naltrexone": "2",
 "mykrox": "2",
 "minoxidil": "2",
 "metahistine d": "2",
 "mirapex er": "2",
 "midol pm": "2",
 "motrin pm": "2",
 "metoprolol succinate er": "2",
 "multihistamine-d": "2",
 "mintuss ms": "2",
 "motion-time": "2",
 "montecough": "2",
 "matzim la": "2",
 "marplan": "3",
 "methotrexate": "2",
 "molindone": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "3",
 "mysoline": "2",
 "morphine sulfate sr": "2",
 "min-ovral 28": "1",
 "msir": "2",
 "metoclopramide": "2",
 "min-ovral 21": "1",
 "micardis": "2",
 "maxifed-g cdx": "2",
 "microzide": "2",
 "midamor": "2",
 "maxichlor pse dm": "2",
 "milnacipran": "2",
 "methscopolamine/phenylephrine": "2",
 "myhist-dm": "2",
 "mapap cough &amp; sinus formula": "2",
 "mag-phen": "2",
 "monoket": "2",
 "mycobutin": "2",
 "microgestin 1.5/30": "1",
 "motofen": "2",
 "methoxyflurane": "2",
 "midol pms": "2",
 "m-hist td": "2",
 "medent c": "2",
 "metolazone": "2",
 "methadose": "2",
 "metaxalone": "2",
 "morphine rapi-ject": "2",
 "max hc": "2",
 "maldec": "2",
 "mircette": "1",
 "medi-sleep": "2",
 "microgestin fe 1/20": "1",
 "mio-rel": "2",
 "morphine sulfate ir": "2",
 "maxi-tuss sa": "2",
 "mygracet": "2",
 "maxifed cd": "2",
 "ms contin": "2",
 "mepenzolate": "2",
 "margesic": "2",
 "mobigesic": "2",
 "mapap pm": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "mesehist dm": "2",
 "maxiflu cd": "2",
 "mintuss mr": "2",
 "mintex hc": "2",
 "maxiphen cd": "2",
 "meclizine": "2",
 "minitran": "2",
 "migrapap": "2",
 "maxifed-g cd": "2",
 "mesantoin": "2",
 "mellaril-s": "2",
 "myphetane dx cough": "2",
 "minotal": "2",
 "mitride": "2",
 "micrainin": "2",
 "meprobamate": "2",
 "myhist-pd": "2",
 "mitran": "2",
 "mintex": "2",
 "mononessa": "1",
 "mintex pse": "2",
 "mepergan": "2",
 "methsuximide": "2",
 "migrazone": "2",
 "medigesic": "2",
 "mytussin ac": "2",
 "midchlor": "2",
 "mibefradil": "2",
 "meprozine": "2",
 "mebaral": "2",
 "menstrual complete": "2",
 "migratine": "2",
 "matulane": "3",
 "morphitec": "2",
 "m-clear wc": "2",
 "methenamine/sodium biphosphate": "3",
 "moduretic 5-50": "2",
 "maxi-tuss hcx": "2",
 "maxzide-25": "2",
 "migquin": "2",
 "maxiflu cdx": "2",
 "methocarbamol": "2",
 "microgestin fe 1.5/30": "1",
 "maxiphen adt": "2",
 "menstrual pms": "2",
 "m-end dmx": "2",
 "metoprolol": "2",
 "milontin": "2",
 "minipress": "2",
 "m-end pe": "2",
 "micomp-pb": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "medivert": "2",
 "maxi-tuss hc": "2",
 "mb-tab": "2",
 "methohexital": "2",
 "m-end dm": "2",
 "myelo-kit": "3",
 "maxiphen cdx": "2",
 "modicon": "1",
 "mudrane gg": "2",
 "myophen": "2",
 "midol pms maximum strength": "2",
 "methotrexate lpf sodium": "2",
 "meperidine/promethazine": "2",
 "maxzide": "2",
 "miltown": "2",
 "midrin": "2",
 "marten-tab": "2",
 "metrizamide": "3",
 "miles nervine": "2",
 "monopril hct": "2",
 "minirin": "2",
 "myleran": "2",
 "maxichlor peh dm": "2",
 "m-eslon": "2",
 "mytussin dac": "2",
 "mavik": "2",
 "myzilra": "1",
 "methdilazine": "2",
 "marax df": "2",
 "migrex": "2",
 "mepergan fortis": "2",
 "maprotiline": "2",
 "midol maximum strength menstrual": "2",
 "maalox total relief": "2",
 "mudrane": "2",
 "myphetapp": "2",
 "m-end": "2",
 "marax": "2",
 "maxolon": "2",
 "mellaril": "2",
 "mintuss dr": "2",
 "methscopolamine": "2",
 "morphine": "2",
 "moban": "2",
 "multihistamine-d ped": "2",
 "m o s": "2",
 "mooredec": "2",
 "msp-blu": "2",
 "moexipril": "2",
 "methadone": "2",
 "mesoridazine": "2",
 "maximum strength stress": "2",
 "marpres": "2"}, "l": {"lyrica": "2",
 "lusedra": "2",
 "loperamide": "2",
 "lo loestrin fe": "1",
 "lisinopril": "2",
 "levsin sl": "2",
 "liquitussin hc syrup": "2",
 "lodrane liquid": "2",
 "lasix": "2",
 "lessina": "1",
 "leena": "1",
 "lamisil": "2",
 "levonest": "1",
 "loestrin 1/20": "1",
 "l-all 12": "2",
 "librax": "2",
 "low-ogestrel-21": "1",
 "loperamide/simethicone": "2",
 "low-ogestrel-28": "1",
 "lithobid": "2",
 "luvox": "2",
 "levocetirizine": "2",
 "lamictal": "2",
 "lufyllin-epg": "2",
 "liqui-char": "2",
 "lexuss 210 liquid": "2",
 "loestrin 21 1/20": "1",
 "lortuss lq": "2",
 "lodrane d": "2",
 "loestrin fe 1.5/30": "1",
 "linhist-l.a.": "2",
 "loqua": "2",
 "lamivudine/zidovudine": "1",
 "levall-12": "2",
 "lodrane ld": "2",
 "lohist-dm": "2",
 "lobac": "2",
 "loestrin 24 fe": "1",
 "lodrane 12d": "2",
 "librium": "2",
 "leflunomide": "3",
 "lorzone": "2",
 "lomanate": "2",
 "lo/ovral": "1",
 "lopinavir/ritonavir": "3",
 "levlen": "1",
 "levlite": "1",
 "loestrin 21 1.5/30": "1",
 "lohist-d": "2",
 "lithotabs": "2",
 "levsinex sr": "2",
 "liqui-allergy": "2",
 "liqui-minic infant": "2",
 "lodrane 24d": "2",
 "l-all 12 nf": "2",
 "lodrane": "2",
 "la nasal decongestant": "2",
 "lunesta": "2",
 "loxitane": "2",
 "levsin": "2",
 "lohist-12": "2",
 "liqui-char with sorbitol": "2",
 "levsin with phenobarbital": "2",
 "luminal": "2",
 "lorazepam intensol": "2",
 "locholest": "1",
 "losartan": "2",
 "lindane topical": "2",
 "levetiracetam": "2",
 "lodrane xr": "2",
 "lutera": "1",
 "levsinex": "2",
 "lotensin hct": "2",
 "lamictal xr": "2",
 "lortuss dm": "2",
 "lioresal": "2",
 "largon": "2",
 "liraglutide": "1",
 "lamotrigine": "2",
 "lamictal cd": "2",
 "loxitane im": "2",
 "legatrin pm": "2",
 "lopressor": "2",
 "lomocot": "2",
 "lo-aqua": "2",
 "lybrel": "1",
 "lodrane 24": "2",
 "lexxel": "2",
 "lactobacillus acidophilus/methscopolamine": "2",
 "laniroif": "2",
 "loxapine": "2",
 "liqui-histine-d": "2",
 "lo/ovral-28": "1",
 "latuda": "2",
 "leader allerhist": "2",
 "ludiomil": "2",
 "levall": "2",
 "lomotil": "2",
 "lagesic": "2",
 "lotrel": "2",
 "liquituss r-dm": "2",
 "levrix": "2",
 "lodrane 12 hour": "2",
 "lonox": "2",
 "lexapro": "2",
 "lioresal intrathecal": "2",
 "liquiphed dm": "2",
 "loniten": "2",
 "loestrin fe 1/20": "1",
 "liquihistine dm": "2",
 "lozol": "2",
 "liquicough hc": "2",
 "labetalol": "2",
 "lithium": "2",
 "lorazepam": "2",
 "limbitrol": "2",
 "lohist-pd": "2",
 "luvox cr": "2",
 "lithonate": "2",
 "loryna": "1",
 "locholest light": "1",
 "linezolid": "2",
 "lohist-12d": "2",
 "levbid": "2",
 "limbitrol ds": "2",
 "levora": "1",
 "lurasidone": "2",
 "loxitane c": "2",
 "logen": "2",
 "lopressor hct": "2",
 "loseasonique": "1",
 "lamictal odt": "2",
 "liquihistine cs": "2",
 "lemohist plus": "2"}, "o": {"onfi": "2",
 "orphengesic": "2",
 "orphengesic forte": "2",
 "oreticyl forte": "2",
 "oxytrol": "2",
 "orsythia": "1",
 "oratuss": "2",
 "omnipaque 240 redi-unit": "3",
 "ortho-novum 1/35": "1",
 "omnihist l.a.": "2",
 "ortho tri-cyclen lo": "1",
 "ortho-novum 1/50": "1",
 "oxybutynin": "2",
 "omnipaque 180 redi-unit": "3",
 "ormazine": "2",
 "ortho-novum 7/7/7": "1",
 "ortho evra": "1",
 "omnipaque 350": "3",
 "oraverse": "2",
 "ogestrel-28": "1",
 "omnipaque 210": "3",
 "orbivan": "2",
 "omnipaque 140": "3",
 "osmoprep": "3",
 "optimum charcoal": "2",
 "omnipaque 180": "3",
 "orfro": "2",
 "ortho tri-cyclen": "1",
 "ornade spansules": "2",
 "ocella": "1",
 "oreticyl 25": "2",
 "orphenadrine": "2",
 "ovcon 35 fe": "1",
 "oms": "2",
 "ovral": "1",
 "ortho-novum 10/11": "1",
 "or-phen-ade": "2",
 "ordrine": "2",
 "orphenate": "2",
 "oxcarbazepine": "2",
 "ogestrel": "1",
 "orap": "2",
 "optimine": "2",
 "oratuss 12": "2",
 "olanzapine": "2",
 "oleptro": "2",
 "oramorph sr": "2",
 "olmesartan": "2",
 "oreticyl 50": "2",
 "ortho-cept": "1",
 "ovcon 35": "1",
 "omnihist ii la": "2",
 "omnipaque flexipak": "3",
 "ovcon 50": "1",
 "oretic": "2",
 "ovral-28": "1",
 "olopatadine nasal": "2",
 "orlenta": "2",
 "oxazepam": "2",
 "ortho cyclen": "1",
 "omnipaque 300": "3",
 "omnipaque 240": "3"}, "n": {"neo dm drops": "2",
 "nyquil multi-symptom": "2",
 "necon 0.5/35": "1",
 "nytol": "2",
 "norethin 1/35 e": "1",
 "nitroglycerin": "2",
 "necon 10/11": "1",
 "nucodine": "2",
 "nardil": "3",
 "nitroprusside": "2",
 "nebivolol": "2",
 "nohist": "2",
 "novahistine expectorant": "2",
 "nolamine": "2",
 "nulev": "2",
 "nitrek": "2",
 "nu-med": "2",
 "necon 7/7/7": "1",
 "neo dm syrup": "2",
 "nelova 10/11": "1",
 "novahistine dh": "2",
 "nalex-a": "2",
 "naldecon": "2",
 "norpramin": "2",
 "nucodine pediatric": "2",
 "navogan": "2",
 "nuco-tuss pediatric expectorant": "2",
 "norel dm": "2",
 "nasatuss": "2",
 "nitrodisc": "2",
 "nitro td patch-a": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "nelova 0.5/35": "1",
 "nitroglyn e-r": "2",
 "norel la": "2",
 "naloxone": "3",
 "naldecon-cx adult": "2",
 "neupro": "2",
 "nohist ext": "2",
 "novadyne expectorant": "2",
 "nalfed pd": "2",
 "nyquil cold medicine": "2",
 "notuss-nxd": "2",
 "nitropress": "2",
 "neutrahist drops": "2",
 "notuss-pe": "2",
 "neo-diaral": "2",
 "nohist-dmx": "2",
 "norvir": "3",
 "nalgest": "2",
 "necon 1/35": "1",
 "nitrocot": "2",
 "nitro-dur": "2",
 "naldelate": "2",
 "normodyne": "2",
 "nalbuphine": "2",
 "norflex": "2",
 "nucofed pediatric expectorant": "2",
 "notuss-forte": "2",
 "nytol caplet": "2",
 "nitrogard": "2",
 "norflex injectable": "2",
 "nordette-28": "1",
 "notuss-ac": "2",
 "nordette-21": "1",
 "neotuss plus": "2",
 "notuss-nx": "2",
 "nonbac": "2",
 "nalgestic pediatric": "2",
 "naloxone/pentazocine": "3",
 "notuss": "2",
 "nortrel 1/35": "1",
 "nitrong": "2",
 "nd clear": "2",
 "niravam": "2",
 "nucochem": "2",
 "nelova 1/35": "1",
 "nucynta er": "2",
 "nitro-bid": "2",
 "naturetin": "2",
 "night time pain": "2",
 "nalex ac": "2",
 "norvir soft gelatin": "3",
 "nasohist-dm": "2",
 "nortriptyline": "2",
 "norethin 1/50 m": "1",
 "nucynta": "2",
 "nicardipine": "2",
 "nortrel 0.5/35": "1",
 "nohist plus": "2",
 "nasotuss": "2",
 "nitrolingual pumpspray": "2",
 "nydrazid": "2",
 "naltrexone": "2",
 "nohist pe": "2",
 "norinyl 1+35": "1",
 "nacon": "2",
 "novafed a": "2",
 "nifediac cc": "2",
 "nitro-bid iv": "2",
 "nucodine expectorant": "2",
 "necon 1/50": "1",
 "norvasc": "2",
 "neo ac": "2",
 "nimodipine": "2",
 "nyquil": "2",
 "novasus": "2",
 "nohist-a": "2",
 "navane": "2",
 "nalspan": "2",
 "nuco-tuss expectorant": "2",
 "nitrostat tablets": "2",
 "nexiclon xr": "2",
 "neo hc": "2",
 "nohist-pdx": "2",
 "nitroquick": "2",
 "nasohist pediatric": "2",
 "nembutal": "2",
 "neurontin": "2",
 "nohist plus jr": "2",
 "nifedical xl": "2",
 "norinyl 1+50": "1",
 "norel sd": "2",
 "nadolol": "2",
 "novahistine": "2",
 "norel sr": "2",
 "nortrel 7/7/7": "1",
 "ny-tannic": "2",
 "nighttime cough": "2",
 "nelova 1/50 m": "1",
 "nubain": "2",
 "nervine": "2",
 "nifedipine": "2",
 "naturetin-10": "2",
 "novadyne dh": "2",
 "nitrostat": "2",
 "neutrahist pdx drops": "2",
 "nisoldipine": "2",
 "nolahist": "2",
 "novahistine elixir": "2",
 "nitro-time": "2",
 "notuss-dc": "2",
 "nalphen": "2",
 "nalex-a sr": "2",
 "narcan": "3",
 "nuhist": "2",
 "nytol maximum strength": "2",
 "nitrol": "2",
 "norgesic": "2",
 "nalfed": "2",
 "novagest with codeine": "2",
 "nitrous oxide": "2",
 "nitro-par": "2",
 "nucofed expectorant": "2",
 "nightime sleepaid": "2",
 "norit": "2",
 "nucofed": "2",
 "nitrol appli-kit": "2",
 "nitromist": "2",
 "nuvaring": "1",
 "nalex a 12": "2",
 "nimotop": "2",
 "nabilone": "2",
 "nalda-relief pediatric": "2",
 "norgesic forte": "2",
 "naturetin-5": "2",
 "nefazodone": "2",
 "nordette": "1",
 "nembutal sodium": "2"}, "q": {"q flex": "2",
 "q-tapp": "2",
 "quinaretic": "2",
 "qdall": "2",
 "qual-tussin pediatric": "2",
 "qv-allergy": "2",
 "quetiapine": "2",
 "quartuss dm": "2",
 "questran light": "1",
 "quad tuss pediatric": "2",
 "quad tann pediatric": "2",
 "quasense": "1",
 "quinapril": "2",
 "quad tann": "2",
 "questran": "1",
 "q-v tussin": "2",
 "q-dryl a/f": "2",
 "quadrapax": "2",
 "quartuss": "2",
 "quenalin": "2",
 "quadratuss": "2",
 "quadra-hist d": "2",
 "qual-tussin": "2",
 "quindal hd": "2",
 "quazepam": "2",
 "q-hist la": "2",
 "quarzan": "2",
 "quadrinal": "2",
 "quindal hd plus": "2",
 "q-dryl": "2",
 "quadra-hist d pediatric": "2",
 "quelidrine": "2",
 "qc cough/cold": "2",
 "q-gesic": "2",
 "q-tapp dm": "2",
 "quad-tuss": "2"}, "p": {"prozac weekly": "2",
 "pediatan": "2",
 "phenagesic": "2",
 "pulmari-gp": "2",
 "prehist d": "2",
 "pyrroxate": "2",
 "phosenamine": "2",
 "poly-tussin ac": "2",
 "phrenilin forte": "2",
 "pamprin maximum pain": "2",
 "poly-histine cs": "2",
 "pse brom dm": "2",
 "phosphasal": "2",
 "pse carbinoxamine dm": "2",
 "phendal-hd": "2",
 "pe-hist dm": "2",
 "prohist lq": "2",
 "pegvisomant": "2",
 "prohist dm": "2",
 "pyrelle hb": "2",
 "pse allergy dm": "2",
 "poly hist cb": "2",
 "pediatex 12": "2",
 "pedituss": "2",
 "promacet": "2",
 "paral": "2",
 "pharmagesic": "2",
 "pepto-bismol": "2",
 "procardia": "2",
 "phenhist expectorant": "2",
 "pcm": "2",
 "p-tex": "2",
 "proglycem": "2",
 "phenergan vc": "2",
 "primatuss 4": "2",
 "paxipam": "2",
 "primidone": "2",
 "procot": "2",
 "phenylhistine expectorant": "2",
 "pseubrom": "2",
 "phenaphen with codeine": "2",
 "promethazine vc": "2",
 "pulmari": "2",
 "prolixin decanoate": "2",
 "pardryl": "2",
 "palgic": "2",
 "pepto diarrhea control": "2",
 "promethazine with dm": "2",
 "probenecid and colchicine": "1",
 "pyril mal phenyl hcl": "2",
 "pseudox m": "2",
 "prohistine-d": "2",
 "pink bismuth": "2",
 "phenurone": "2",
 "pd-hist d": "2",
 "phenadoz": "2",
 "pediahist dm drops": "2",
 "phenabid dm": "2",
 "polythiazide/prazosin": "2",
 "procarbazine": "3",
 "prodrox": "2",
 "pbz": "2",
 "poly dm": "2",
 "pediatex td": "2",
 "prochlorperazine": "2",
 "protid": "2",
 "percy medicine": "2",
 "p-hist dm drops": "2",
 "phenylephrine/promethazine": "2",
 "promethazine with codeine": "2",
 "promethazine vc plain": "2",
 "phenylhistine dh": "2",
 "phenazine 50": "2",
 "portia": "1",
 "pentobarbital": "2",
 "permitil": "2",
 "prosed ds": "2",
 "protuss tablet": "2",
 "pediacare children's allergy": "2",
 "phenylgesic": "2",
 "prohistine dm": "2",
 "parnate": "3",
 "paxil": "2",
 "phenoject-50": "2",
 "phosphate laxative": "3",
 "procardia xl": "2",
 "premesyn pms": "2",
 "phenytek": "2",
 "pediacof": "2",
 "pro-banthine": "2",
 "paliperidone": "2",
 "pb-hyos": "2",
 "parafon forte dsc": "2",
 "pondimin": "2",
 "pseudodine c": "2",
 "posicor": "2",
 "phendacof plus": "2",
 "propoxyphene": "3",
 "percogesic extra strength": "2",
 "poly hist dhc": "2",
 "polytine cs": "2",
 "pentazocine": "2",
 "probenecid": "1",
 "pediatex-ct": "2",
 "pseudoephedrine/pyrilamine": "2",
 "paramethadione": "2",
 "promethazine hcl with codeine": "2",
 "poly-d": "2",
 "poly hist dm": "2",
 "promethazine vc with codeine": "2",
 "pediox chewable": "2",
 "poly cs": "2",
 "pristiq": "2",
 "pyrichlor pe": "2",
 "pedia-lax enema": "3",
 "pediatex 12d": "2",
 "p chlor gg": "2",
 "prosom": "2",
 "phentolamine": "2",
 "prevalite": "1",
 "pediox": "2",
 "phenoxybenzamine": "2",
 "pyrilamine": "2",
 "poly-tussin hd": "2",
 "poly hist pd": "2",
 "pse allergy": "2",
 "pseudo carb dm": "2",
 "peganone": "2",
 "pancof": "2",
 "pd-cof": "2",
 "phencarb gg": "2",
 "phenytoin sodium, prompt": "2",
 "penthrane": "2",
 "propiomazine": "2",
 "permax": "2",
 "pd-hist d drops": "2",
 "phenaz plus": "2",
 "phenelzine": "3",
 "phena-s 12": "2",
 "pharmacia carbosorb": "2",
 "pediatex-dm": "2",
 "pro-clear": "2",
 "p-v-tussin syrup": "2",
 "pyridium plus": "2",
 "pexeva": "2",
 "polythiazide/reserpine": "2",
 "pediatan d": "2",
 "phenacemide": "2",
 "pro-med": "2",
 "pentothal": "2",
 "phena-s": "2",
 "p-hist": "2",
 "pseudocot-c": "2",
 "propranolol": "2",
 "propacet 100": "3",
 "phenergan vc with codeine": "2",
 "paraldehyde": "2",
 "pharbechlor": "2",
 "polytine d": "2",
 "propantheline": "2",
 "pancof-pd": "2",
 "phenylhistine dh expectorant": "2",
 "pseudocot-t": "2",
 "pepto-bismol maximum strength": "2",
 "pyril d": "2",
 "poly hist forte": "2",
 "pcm-la": "2",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "prohist cd": "2",
 "parepectolin": "2",
 "pms relief": "2",
 "phenflu cdx": "2",
 "pc-cap": "3",
 "prozac": "2",
 "prazosin": "2",
 "prinivil": "2",
 "prinzide": "2",
 "pediatex": "2",
 "poly hist hc": "2",
 "pseudochlor": "2",
 "pp-cap": "3",
 "pindolol": "2",
 "peptic relief": "2",
 "phenazoforte plus": "2",
 "pyril tann-12": "2",
 "pseubrom-pd": "2",
 "proben-c": "1",
 "pregabalin": "2",
 "pseudoephedrine/triprolidine": "2",
 "poly-histine-d": "2",
 "pyrlex": "2",
 "pain relief pm extra strength": "2",
 "pamelor": "2",
 "pediahist dm": "2",
 "pediacare children's allergy &amp; cold": "2",
 "phenylephrine/pyrilamine": "2",
 "pimozide": "2",
 "pediatex-d": "2",
 "procyclidine": "2",
 "perindopril": "2",
 "patanase": "2",
 "preven ec": "1",
 "palgic-dc": "2",
 "poly-histine": "2",
 "pd-cof drops": "2",
 "promazine": "2",
 "pseudo cm tr": "2",
 "previfem": "1",
 "pro-red ac": "2",
 "phrenilin": "2",
 "poly tan": "2",
 "pediatex hc": "2",
 "polytine dm": "2",
 "paraflex": "2",
 "philith": "1",
 "pbz-sr": "2",
 "poly histine dm": "2",
 "prudoxin": "2",
 "panatuss dxp": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "pseudacarb": "2",
 "pamine forte": "2",
 "poly-tussin dhc": "2",
 "plendil": "2",
 "propoven": "2",
 "paroxetine": "2",
 "pse carb dm drops": "2",
 "pmb": "2",
 "p chlor dm": "2",
 "phenergan fortis": "2",
 "pamine fq": "2",
 "pcm allergy": "2",
 "pannaz": "2",
 "phenobarbital": "2",
 "pyril dm": "2",
 "percogesic": "2",
 "prolixin enanthate": "2",
 "poly-tussin": "2",
 "pharbedryl": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "pheniramine/phenylpropanolamine/pyrilamine": "2",
 "polythiazide": "2",
 "prohist": "2",
 "pseudo carb": "2",
 "pain reliever pm": "2",
 "prosed ec": "2",
 "palgic-d": "2",
 "pergolide": "2",
 "phenyl 7.5/6mg": "2",
 "pediatex 12 dm": "2",
 "pediahist dm syrup": "2",
 "pamine": "2",
 "prop-a-hist": "2",
 "perphenazine": "2",
 "prialt": "2",
 "parlodel": "2",
 "promethazine with dextromethorphan": "2",
 "precedex": "2",
 "pramipexole": "2",
 "paxil cr": "2",
 "pannaz s": "2",
 "p-tann d": "2",
 "phenindamine": "2",
 "pheniramine/phenylpropanolamine/phenyltoloxamine/pyrilamine": "2",
 "phenchlor tannate pediatric": "2",
 "promethegan": "2",
 "pseudoephedrine plus": "2",
 "poly tan d": "2",
 "propoxyphene compound 65": "3",
 "phensuximide": "2",
 "poly-tussin dm": "2",
 "phenflu cd": "2",
 "phenytoin": "2",
 "pharbetol pm": "2",
 "paxarel": "2",
 "paradione": "2",
 "primrose oil": "1",
 "pheniramine/phenyltoloxamine/pyrilamine": "2",
 "phena-plus": "2",
 "pyrlex cb": "2",
 "poly tan dm": "2",
 "protriptyline": "2",
 "propofol": "2",
 "phenyl 15/12mg": "2",
 "pyrlex pd": "2",
 "pamprin multi-symptom menstrual relief": "2",
 "prolixin": "2",
 "pheniramine/phenyltoloxamine/pseudoephedrine/pyrilamine": "2",
 "palgic ds": "2",
 "phenylhistine": "2",
 "prominol": "2",
 "percogesic original strength": "2",
 "pbm allergy": "2",
 "phenergan with dextromethorphan": "2",
 "potiga": "2",
 "promethazine hcl and codeine phosphate": "2",
 "periactin": "2",
 "phenylephrine/triprolidine": "2",
 "polyhist nc": "2",
 "pharmadrine": "2",
 "prohist cf": "2",
 "promethazine vc w/codeine": "2"}, "s": {"sronyx": "1",
 "safyral": "1",
 "stomach relief": "2",
 "saluron": "2",
 "sudogest sinus &amp; allergy": "2",
 "sertraline": "2",
 "sleep aid tablets": "2",
 "sildec-pe dm": "2",
 "stalevo 150": "2",
 "sleep": "2",
 "sildec-pe drops": "2",
 "sibutramine": "2",
 "stalevo": "2",
 "solotuss": "2",
 "sonahist-dm": "2",
 "subutex": "2",
 "sudogest cold &amp; allergy": "2",
 "serathide": "2",
 "sufentanil": "2",
 "snooze fast": "2",
 "sprintec": "1",
 "suphedrine plus": "2",
 "staflex": "2",
 "scopace": "2",
 "sudal-12 chewable": "2",
 "siltane": "2",
 "sleep tab ii": "2",
 "stavzor": "2",
 "sympak dm": "2",
 "sonata": "2",
 "sinutab ex-strength": "2",
 "symtan a": "2",
 "stelazine": "2",
 "scot-tussin original": "1",
 "serentil": "2",
 "stress maximum strength": "2",
 "sotalol hydrochloride af": "2",
 "sildec-pe": "2",
 "somnote": "2",
 "seasonale": "1",
 "sinutab maximum strength caplets": "2",
 "siladryl": "2",
 "sal-tropine": "2",
 "solifenacin": "2",
 "sympak ii": "2",
 "stalevo 100": "2",
 "soma": "2",
 "symax duotab": "2",
 "suttar-2": "2",
 "salutensin-demi": "2",
 "solia": "1",
 "sevoflurane": "2",
 "sildec": "2",
 "sojourn": "2",
 "somavert": "2",
 "selfemra": "2",
 "serzone": "2",
 "suttar sf": "2",
 "sleepinal": "2",
 "skelaxin": "2",
 "sabril": "2",
 "suprane": "2",
 "sominex pain relief formula": "2",
 "salutensin": "2",
 "suprep": "3",
 "shellcap pd": "2",
 "seconal sodium": "2",
 "sanctura": "2",
 "sleep-ettes": "2",
 "sudafed pe severe cold": "2",
 "stalevo 75": "2",
 "ser-ap-es": "2",
 "sudal-12": "2",
 "sunmark sleep aid": "2",
 "sustiva": "2",
 "skelex": "2",
 "sominex maximum strength caplet": "2",
 "solfoton": "2",
 "sinulin": "2",
 "simplet": "2",
 "sanctura xr": "2",
 "somnicaps": "2",
 "savella": "2",
 "siladryl das": "2",
 "stalevo 200": "2",
 "sudafed sinus nighttime plus pain": "2",
 "scopolamine": "2",
 "sominex": "2",
 "sinarest": "2",
 "scopohist-pe": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "seradex-la": "2",
 "sympak": "2",
 "sympak pdx": "2",
 "sarafem": "2",
 "sparine": "2",
 "sulfinpyrazone": "2",
 "sudogest plus": "2",
 "sunmark acid reducer maximum strength": "1",
 "seroquel": "2",
 "seroquel xr": "2",
 "secobarbital": "2",
 "syeda": "1",
 "sudahist": "2",
 "scopohist syrup": "2",
 "sinucon": "2",
 "sleep-ettes d": "2",
 "sildec-pe dm drops": "2",
 "spastrin": "2",
 "soma compound with codeine": "2",
 "s-t forte 2": "2",
 "suphenamine-sr": "2",
 "simply sleep": "2",
 "spasdel": "2",
 "scot-tussin allergy": "2",
 "surmontil": "2",
 "sildec dm": "2",
 "sedapap": "2",
 "sodium salicylate": "1",
 "suprep bowel prep kit": "3",
 "stomax": "2",
 "sleep-eze-3": "2",
 "sufenta": "2",
 "stahist": "2",
 "sinus &amp; allergy pe": "2",
 "statuss green": "2",
 "silodosin": "2",
 "siladryl allergy": "2",
 "sleep tabs": "2",
 "sildenafil": "2",
 "spironolactone": "2",
 "sinucon pediatric": "2",
 "serpex": "2",
 "stimate": "2",
 "sular": "2",
 "scot-tussin dm": "2",
 "sleepwell 2-nite": "2",
 "symax sr": "2",
 "seradex": "2",
 "soma compound": "2",
 "sectral": "2",
 "suclor": "2",
 "sudal-12 tannate": "2",
 "seconal": "2",
 "sudafed pe nighttime cold": "2",
 "statex": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "symax sl": "2",
 "saphris": "2",
 "spasmolin": "2",
 "silphen cough": "2",
 "sinequan": "2",
 "serpazide": "2",
 "suboxone": "3",
 "symbyax": "2",
 "spasquid": "2",
 "stalevo 50": "2",
 "symax fastab": "2",
 "scopohist": "2",
 "strifon fort": "2",
 "stalevo 125": "2",
 "sudafed pe sinus &amp; allergy": "2",
 "sonahist": "2",
 "sotalol": "2",
 "sorine": "2",
 "stadol": "2",
 "singlet": "2",
 "servira": "2",
 "sinarest extra strength": "2",
 "silenor": "2",
 "siladyl sa": "2",
 "safetussin pm": "2",
 "sorbitrate": "2",
 "sodium oxybate": "3",
 "sudatrate": "2",
 "statuss": "2",
 "sensipar": "2",
 "serax": "2",
 "sinapils": "2",
 "shellcap": "2",
 "sinadrin plus": "2",
 "sinodec": "2",
 "seconal sodium pulvules": "2",
 "seasonique": "1"}, "r": {"rhinaclear": "2",
 "ropivacaine/sufentanil": "2",
 "relcof pse": "2",
 "re-tann": "2",
 "robitussin-ac": "2",
 "re-drylex": "2",
 "robitussin-dac": "2",
 "respi-tann g": "2",
 "ricobid nr": "2",
 "reclipsen": "1",
 "robitussin children's cough &amp; cold long-acting": "2",
 "rescon-ed": "2",
 "requip": "2",
 "ricobid h": "2",
 "regroton": "2",
 "rondameth": "2",
 "resaid": "2",
 "rhinolar": "2",
 "ru-tuss": "2",
 "ry-tann": "2",
 "robitussin night time cough &amp; cold": "2",
 "resperal": "2",
 "relcof pe": "2",
 "rifampin": "2",
 "ryna-12s": "2",
 "rhinatate pediatric": "2",
 "ryna-12x": "2",
 "remular": "2",
 "rynatuss": "2",
 "relasin-hc": "2",
 "rynesa 12s": "2",
 "rhinabid pd": "2",
 "rondex-dm": "2",
 "ranitidine": "1",
 "re all 12": "2",
 "robaxin-750": "2",
 "rhinogesic": "2",
 "rindal hd plus": "2",
 "relera": "2",
 "regurin": "2",
 "rhinatate-nf": "2",
 "redur-pcm": "2",
 "ryna-12": "2",
 "requip follow on pack": "2",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "reglan": "2",
 "rybix odt": "3",
 "rhinosyn-dm": "2",
 "relahist-dm": "2",
 "rolatuss": "2",
 "rms": "2",
 "respahist ii": "2",
 "ramipril": "2",
 "rybix": "3",
 "robitussin night time cough, cold &amp; flu": "2",
 "requip starter pack": "2",
 "rauzide": "2",
 "rhinacon a": "2",
 "requip starter kit": "2",
 "rhinoflex 650": "2",
 "rifater": "2",
 "renese-r": "2",
 "risperdal m-tab": "2",
 "ropinirole": "2",
 "remifentanil": "2",
 "r-tannamine": "2",
 "rifamate": "2",
 "reme tussin dm": "2",
 "respa br": "2",
 "respi-tann": "2",
 "rhinabid": "2",
 "robaxin": "2",
 "rynatan-s pediatric": "2",
 "rentamine pediatric": "2",
 "rifadin iv": "2",
 "rescon-dm": "2",
 "r-tannic-s a/d": "2",
 "rhinolar-ex 12": "2",
 "rifadin": "2",
 "ralix": "2",
 "respa sa": "2",
 "restoril": "2",
 "relcof cpm": "2",
 "rhinoflex": "2",
 "robinul forte": "2",
 "robaxisal": "2",
 "rhinolar-ex": "2",
 "rheumatrex dose pack": "2",
 "rondec-dm": "2",
 "rondec": "2",
 "re2+30": "2",
 "rondex": "2",
 "ryna liquid": "2",
 "ru-hist forte": "2",
 "rifabutin": "2",
 "remeron": "2",
 "rondamine": "2",
 "r-tannate pediatric": "2",
 "relcof dn pse": "2",
 "retrovir": "1",
 "respi-tann pd": "2",
 "r-tannate": "2",
 "ru-tuss with hydrocodone": "2",
 "requip xl": "2",
 "rescudose": "2",
 "re-drylex jr": "2",
 "robitussin peak cold nighttime nasal relief": "2",
 "risperdal consta": "2",
 "ru-vert-m": "2",
 "ritifed": "2",
 "rentamine": "2",
 "r-tanna": "2",
 "ryna-cx": "2",
 "resperal-dm": "2",
 "rheaban maximum strength": "2",
 "relcof dn pe": "2",
 "risperidone": "2",
 "robitussin allergy &amp; cough": "2",
 "relacon-hc": "2",
 "robichem ac": "2",
 "rindal hpd": "2",
 "roxanol 100": "2",
 "r-tannamine pediatric": "2",
 "regitine": "2",
 "rinate pediatric": "2",
 "relcof c": "2",
 "ranitidine bismuth citrate": "1",
 "respa-ar": "2",
 "ricotuss": "2",
 "rynatuss pediatric": "2",
 "rondex-dm drops": "2",
 "respivent df": "2",
 "rinade-bid": "2",
 "rondamine dm": "2",
 "rescon": "2",
 "revatio": "2",
 "reme hist dm": "2",
 "rectiv": "2",
 "rynatan": "2",
 "revia": "2",
 "robafen ac": "2",
 "rimactane": "2",
 "rondex drops": "2",
 "relaxazone": "2",
 "robitussin cough &amp; cold long-acting": "2",
 "rindal-hd": "2",
 "romilar ac": "2",
 "remular-s": "2",
 "rolatuss-sr": "2",
 "remeron soltab": "2",
 "ryzolt": "3",
 "rolatuss with hydrocodone": "2",
 "rebif": "2",
 "ry-t-12": "2",
 "ryneze": "2",
 "rotigotine": "2",
 "relacon-hc nr": "2",
 "rhinatate": "2",
 "ritonavir": "3",
 "repreve": "2",
 "ridifed": "2",
 "re dcp drops": "2",
 "respivent-d": "2",
 "respa c&amp;c": "2",
 "ryna-c": "2",
 "rapaflo": "2",
 "re-pb hyos elixir": "2",
 "repan": "2",
 "risperdal": "2",
 "roxanol": "2",
 "respahist": "2",
 "rapiflux": "2",
 "rynatan pediatric": "2",
 "roxanol-t": "2",
 "relagesic": "2",
 "renese": "2",
 "redux": "2",
 "robinul": "2"}, "u": {"uretron": "2",
 "uticap": "2",
 "ultrabrom pd": "2",
 "urimax": "2",
 "uni-hist pdx drops": "2",
 "urotrol": "2",
 "unit-tex 10/120 er": "2",
 "ultram": "3",
 "ultram odt": "3",
 "utrona": "2",
 "uprima": "2",
 "unit-hist drops": "2",
 "uritact ds": "2",
 "unisom sleepmelts": "2",
 "urimar-t": "2",
 "uni-multihist d ped": "2",
 "urispas": "2",
 "ultram er": "3",
 "uni decon": "2",
 "unisom sleeptabs": "2",
 "uni-hist pdx syrup": "2",
 "uni all 12": "2",
 "url-tannate": "2",
 "urised": "2",
 "uni-perr": "2",
 "ustell": "2",
 "uta": "2",
 "ultracet": "3",
 "utira": "2",
 "univasc": "2",
 "uni-hist dm pediatric syrup": "2",
 "up and up all day allergy relief d": "2",
 "urapine": "2",
 "uretron ds": "2",
 "unisom sleepgels": "2",
 "uni-tann": "2",
 "uni multihist dm": "2",
 "utrona-c": "2",
 "uni serp": "2",
 "uritin": "2",
 "uni-cof": "2",
 "ultiva": "2",
 "usept": "2",
 "urisedamine": "2",
 "urisym": "2",
 "urogesic blue": "3",
 "url-tannate pediatric": "2",
 "unipres": "2",
 "uni tuss hc": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uni-hist dm pediatric drops": "2",
 "ultrabrom": "2",
 "uroxatral": "2",
 "unisom with pain relief": "2",
 "urelief plus": "2",
 "urelle": "2",
 "uni-tricof hc": "2",
 "up and up anti-diarrheal solution": "2",
 "uni-tann cs": "2",
 "uni-tann d": "2",
 "uni-tuss dm": "2",
 "ultane": "2",
 "utira-c": "2",
 "uro-phosphate": "3",
 "uribel": "2",
 "ultane pen": "2",
 "uniretic": "2"}, "t": {"tussionex pennkinetic": "2",
 "tripohist": "2",
 "toprol-xl": "2",
 "telmisartan": "2",
 "thiopental": "2",
 "trizivir": "1",
 "tussend": "2",
 "tizanidine": "2",
 "tramadol": "3",
 "tekral": "2",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "tencet": "2",
 "terazosin": "2",
 "tri-sudo": "2",
 "talwin nx": "3",
 "tussiden c": "2",
 "tolterodine": "2",
 "tylenol with codeine #2": "2",
 "tanafed-dm": "2",
 "tavist-da": "2",
 "tri-sprintec": "1",
 "tramal sr": "3",
 "trituss-a drops": "2",
 "tylenol severe cold &amp; flu night time": "2",
 "tranylcypromine": "3",
 "tylenol with codeine #4": "2",
 "triptifed": "2",
 "tylenol plus children's flu": "2",
 "tritec": "1",
 "teldrin": "2",
 "tekamlo": "2",
 "trital dm": "2",
 "trinalin repetabs": "2",
 "tri-gestan s": "2",
 "tridil": "2",
 "torecan": "2",
 "thiethylperazine": "2",
 "tavist-1": "2",
 "t- koff": "2",
 "tetra-mag": "2",
 "tricodene forte": "2",
 "trihexyphenidyl": "2",
 "tri-tannate": "2",
 "trospium": "2",
 "tranquil nighttime sleep aid": "2",
 "teveten hct": "2",
 "tenormin": "2",
 "tussall": "2",
 "temaril": "2",
 "trileptal": "2",
 "trihexane": "2",
 "tacrine": "1",
 "tricodene nn": "2",
 "tylenol sinus congestion &amp; pain nighttime": "2",
 "talacen": "2",
 "tegretol": "2",
 "tavist-d": "2",
 "tanafed": "2",
 "trinessa lo": "1",
 "tylenol sore throat nighttime": "2",
 "trihist-d": "2",
 "tl-hist dm": "2",
 "therahist": "2",
 "triaminic softchews cough &amp; runny nose": "2",
 "theomax df": "2",
 "triotann-s": "2",
 "tigan": "2",
 "topiragen": "2",
 "tanamine pediatric": "2",
 "theraflu flu &amp; cough": "2",
 "tranxene sd": "2",
 "trandolapril/verapamil": "2",
 "triphasil-28": "1",
 "tridal": "2",
 "tetrabenazine": "2",
 "tustan 12s": "2",
 "tussi-organidin nr": "2",
 "tramedo": "3",
 "triafed": "2",
 "travel-ease": "2",
 "tenoretic": "2",
 "trimethobenzamide": "2",
 "tylenol plus children's multi-symptom cold": "2",
 "tussive hc": "2",
 "triant-hc": "2",
 "tuss-ds": "2",
 "tussirex": "2",
 "transderm-scop": "2",
 "triotann-s pediatric": "2",
 "tritan": "2",
 "tavist allergy": "2",
 "tears again hydrate": "1",
 "tussi-12": "2",
 "touro allergy": "2",
 "thioguanine": "2",
 "trandate": "2",
 "tolcapone": "2",
 "tussizone-12 rf": "2",
 "terbinex with eco formula": "2",
 "thioridazine": "2",
 "tripohist d": "2",
 "trifluoperazine": "2",
 "tannate 12d s": "2",
 "tranxene": "2",
 "teveten": "2",
 "tebamide": "2",
 "tabloid": "2",
 "tripelennamine": "2",
 "triazolam": "2",
 "trexall": "2",
 "trihist dm": "2",
 "triphed": "2",
 "tri-vent dpc": "2",
 "tenoretic 50": "2",
 "thalitone": "2",
 "tylenol pm": "2",
 "trituss-a": "2",
 "tri-norinyl": "1",
 "tricof": "2",
 "talwin": "2",
 "tussplex dm": "2",
 "trazodone": "2",
 "tussar sf": "2",
 "tribenzor": "2",
 "tussigon": "2",
 "time-hist qd": "2",
 "triaminic multi-symptom fever": "2",
 "tiazac": "2",
 "tl-hist cm": "2",
 "tylenol sinus day/night convenience pack": "2",
 "tussafed": "2",
 "tussin-v": "2",
 "two-dyne": "2",
 "tramapap": "3",
 "theodrine": "2",
 "tanahist-d": "2",
 "tofranil-pm": "2",
 "tri-histine": "2",
 "terbinafine": "2",
 "topiramate": "2",
 "time-hist": "2",
 "tusana-d": "2",
 "tanoral": "2",
 "tuss tan pediatric": "2",
 "tanahist-pd": "2",
 "timolide": "2",
 "total allergy": "2",
 "tuss-hc": "2",
 "triphenicol": "2",
 "trivora": "1",
 "tylenol allergy complete nighttime": "2",
 "touro a&amp;h": "2",
 "triaminic cold &amp; allergy": "2",
 "tri-previfem": "1",
 "tanoral pediatric": "2",
 "thalomid": "2",
 "tannihist-12d": "2",
 "threamine dm": "2",
 "tylenol cold multi-symptom nighttime": "2",
 "trandolapril": "2",
 "temazepam": "2",
 "tri-levlen": "1",
 "triphasil-21": "1",
 "tuinal": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "tricom": "2",
 "triad": "2",
 "tri-lo-sprintec": "1",
 "tylenol sinus nighttime": "2",
 "talwin compound": "2",
 "triac": "2",
 "tuss-pd": "2",
 "triaminic-d multi-symptom cold": "2",
 "thiothixene": "2",
 "timolol": "2",
 "tofranil": "2",
 "tylenol cold": "2",
 "tridione": "2",
 "tanabid sr": "2",
 "triaminic softchews cold and allergy": "2",
 "trycet": "3",
 "theraflu warming relief sinus &amp; cold": "2",
 "tavist": "2",
 "tebamide pediatric": "2",
 "tussicaps": "2",
 "toviaz": "2",
 "topamax sprinkle": "2",
 "theraflu nighttime severe cold &amp; cough caplets": "2",
 "theraflu warming relief caplets nighttime multi-symptom cold": "2",
 "tylenol allergy sinus": "2",
 "tl-hist cd": "2",
 "tylenol with codeine #3": "2",
 "tenoretic 100": "2",
 "tri tann pediatric": "2",
 "triban": "2",
 "tannate pediatric": "2",
 "tri-legest fe": "1",
 "tranxene t-tab": "2",
 "triflupromazine": "2",
 "triquilar 28": "1",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tannate 12 s": "2",
 "transderm-nitro": "2",
 "triprolidine": "2",
 "triquilar 21": "1",
 "triplex ad": "2",
 "triavil": "2",
 "theraflu thin strips multi symptom": "2",
 "triposed": "2",
 "tapentadol": "2",
 "tanamine": "2",
 "tagamet": "2",
 "trimeprazine": "2",
 "trancopal": "2",
 "trisofed": "2",
 "theraflu flu, cold and cough powder": "2",
 "trac tabs 2x": "2",
 "triamterene": "2",
 "timolide 10-25": "2",
 "tedrigen": "2",
 "tylenol cold head congestion nighttime": "2",
 "trimethadione": "2",
 "tavist nighttime allergy": "2",
 "tylenol with codeine": "2",
 "triphasil": "1",
 "trihist-cs": "2",
 "tussi-12d s": "2",
 "tusso-zmr": "2",
 "tylenol allergy multi-symptom nighttime": "2",
 "tanni-hist 12 rf": "2",
 "tencon": "2",
 "tylenol cold multi-symptom nighttime liquid": "2",
 "topamax": "2",
 "tylenol cough &amp; sore throat nightime": "2",
 "triaminic night time cold &amp; cough": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "tasmar": "2",
 "tusso-c": "2",
 "trimal dh": "2",
 "tricodene sf": "2",
 "tegretol xr": "2",
 "t-tanna dm": "2",
 "terrell": "2",
 "tannate-12": "2",
 "trital sr": "2",
 "taladine": "1",
 "tanacof-xr": "2",
 "tenake": "2",
 "tavist allergy/sinus/headache": "2",
 "triaprin": "2",
 "triafed &amp; codeine": "2",
 "tussar dm": "2",
 "tarka": "2",
 "trivora-28": "1",
 "tylenol allergy multi-symptom": "2",
 "trionate": "2",
 "tilia fe": "1",
 "triplex dm": "2",
 "tylenol cold head congestion day and night": "2",
 "tussall-er": "2",
 "trifed c": "2",
 "tussi-organidin-s nr": "2",
 "tramahexal sr": "3",
 "tri-hydroserpine": "2",
 "trexbrom": "2",
 "triofed": "2",
 "triotann": "2",
 "tussi-12d": "2",
 "trilafon": "2",
 "triaminic": "2",
 "tussar-2": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "trimipramine": "2",
 "torsemide": "2",
 "tylenol plus children's cough &amp; runny nose": "2",
 "tussirex sugar free": "2",
 "tussi-12s": "2",
 "tannic-12 s": "2",
 "twynsta": "2",
 "triall": "2",
 "tylenol severe allergy": "2",
 "tussplex": "2",
 "ticon": "2",
 "tussinate": "2",
 "tuss tan": "2",
 "taztia xt": "2",
 "tekturna hct": "2",
 "tramal": "3",
 "tusstat": "2",
 "triaminicin": "2",
 "tetra tannate pediatric": "2",
 "tri-hist pediatric": "2",
 "twilite": "2",
 "tri-vent hc": "2",
 "triple tannate pediatric": "2",
 "tri-legest": "1",
 "tiagabine": "2",
 "tylenol plus children's cold": "2",
 "triotann pediatric": "2",
 "tusso-zr": "2",
 "tylenol cold &amp; cough nighttime": "2",
 "triacin c": "2",
 "tamsulosin": "2",
 "trihexy": "2",
 "triacin": "2",
 "teczem": "2",
 "tagamet hb": "2",
 "tannate v dm": "2",
 "thalidomide": "2",
 "trux-adryl": "2",
 "tacaryl": "2",
 "trinessa": "1",
 "tusscough dhc": "2",
 "thorazine": "2",
 "triaminic thin strips cough &amp; runny nose": "2",
 "tri-tannate pediatric": "2",
 "topco allergy": "2",
 "tusdec-dm": "2",
 "trimethaphan camsylate": "2",
 "tricodene sugar free": "2",
 "triaminic thin strips allergy": "2"}, "w": {"welltuss hc": "2",
 "wellbutrin xl": "3",
 "we allergy": "2",
 "wellbutrin sr": "3",
 "warfarin": "1",
 "wygesic": "3",
 "wal-nadol pm extra strength": "2",
 "wal-zyr d": "2",
 "wal-finate": "2",
 "west-decon m": "2",
 "wellbutrin": "3",
 "west-decon": "2"}, "v": {"vazotan": "2",
 "vivactil": "2",
 "vitoxapap": "2",
 "vaseretic": "2",
 "ventuss syrup": "2",
 "vanex-hd": "2",
 "viravan-s": "2",
 "vilazodone": "2",
 "vazotab": "2",
 "vanatab dx": "2",
 "vazobid-pd": "2",
 "valsartan": "2",
 "vistaril": "2",
 "vazobid": "2",
 "vascor": "2",
 "vasotuss hc": "2",
 "v-tan dm": "2",
 "voriconazole": "2",
 "verelan pm": "2",
 "vigabatrin": "2",
 "vfend": "2",
 "veltane": "2",
 "vanspar": "2",
 "vi-atro": "2",
 "v-gan-50": "2",
 "vasotec": "2",
 "vetuss hc syrup": "2",
 "vanex forte": "2",
 "viravan-p": "2",
 "visrx dose pack": "2",
 "versed": "2",
 "v-cof": "2",
 "vanacof dx": "2",
 "vicks children's nyquil": "2",
 "viagra": "2",
 "vestura": "1",
 "verelan": "2",
 "vanacof": "2",
 "valerian root": "2",
 "visken": "2",
 "vazotuss hc": "2",
 "venlafaxine": "2",
 "vanatrip": "2",
 "velivet": "1",
 "vicks 44m pediatric": "2",
 "vopac": "2",
 "vazol": "2",
 "vanex forte-r": "2",
 "vazol-d": "2",
 "vicks nyquil multi-symptom": "2",
 "verapamil": "2",
 "viravan-pdm": "2",
 "valu-dryl": "2",
 "vicks nyquil cold &amp; flu relief": "2",
 "vicks formula 44 custom care cough &amp; cold pm": "2",
 "vemurafenib": "2",
 "valerian": "2",
 "viravan-t": "2",
 "v-gan-25": "2",
 "v-tann": "2",
 "viibryd": "2",
 "viravan-dm": "2",
 "viratan-dm": "2",
 "valium": "2",
 "vanadom": "2",
 "vicks nyquil cold &amp; flu symptom relief plus vitamin c": "2",
 "visvex": "2",
 "vesicare": "2",
 "vistazine": "2",
 "vicks nyquil cough": "2",
 "vicks pediatric formula 44m cough &amp; cold relief": "2",
 "valproic acid": "2",
 "v-hist": "2",
 "vivitrol": "2",
 "vi-sudo": "2",
 "valturna": "2",
 "valrelease": "2",
 "vanacof cd": "2",
 "vaseretic 10-25": "2",
 "visicol": "3",
 "vistra": "2",
 "vaseretic 5-12.5": "2",
 "vanacof g": "2",
 "victoza": "1"}, "y": {"yaz": "1",
 "yasmin": "1",
 "y-cof dm": "2"}, "x": {"xirahist": "2",
 "x-hist dm": "2",
 "xanax xr": "2",
 "xiratuss": "2",
 "xanax": "2",
 "xirahistdm": "2",
 "xyzal": "2",
 "x-hist": "2",
 "xiral sr": "2",
 "xpect-at": "2",
 "xyrem": "3",
 "xenazine": "2"}, "z": {"zotex-12": "2",
 "zyvox": "2",
 "zantac 150 efferdose": "1",
 "zymine dxr": "2",
 "zovia 1/50": "1",
 "zyban": "3",
 "z-tuss ac": "2",
 "zolpimist": "2",
 "zodryl ac": "2",
 "zyprexa": "2",
 "zyprexa intramuscular": "2",
 "zflex": "2",
 "zarah": "1",
 "zantac 25 mg efferdose": "1",
 "zovia 1/35": "1",
 "zantac 300": "1",
 "zutripro": "2",
 "zantac efferdose": "1",
 "zantac": "1",
 "zyrtec hives": "2",
 "zelboraf": "2",
 "zeosa": "1",
 "zymine-d": "2",
 "zgesic": "2",
 "zymine": "2",
 "zonalon": "2",
 "zebeta": "2",
 "zolpidem": "2",
 "zestril": "2",
 "zymine hc": "2",
 "zenchent": "1",
 "zantac geldose": "1",
 "zymine xr": "2",
 "zodryl dac": "2",
 "zyrtec-d": "2",
 "zamadol": "3",
 "zantac 75": "1",
 "zebutal": "2",
 "zodryl dec": "2",
 "zantac 300 geldose": "1",
 "zydol": "3",
 "zotex-pe": "2",
 "zarontin": "2",
 "zaleplon": "2",
 "z-tuss 2": "2",
 "ziprasidone": "2",
 "zaponex": "2",
 "zyrtec-d 12 hour": "2",
 "zyprexa zydis": "2",
 "zestoretic": "2",
 "zenchent fe": "1",
 "zotex-dm": "2",
 "zanaflex": "2",
 "zyrtec": "2",
 "z-dex 12 d": "2",
 "ziconotide": "2",
 "zotex-c": "2",
 "zotex-d": "2",
 "zantac 150": "1",
 "zonegran": "2",
 "zonisamide": "2",
 "zoloft": "2",
 "zidovudine": "1",
 "z-cof hc": "2",
 "zotex-12d": "2",
 "zaroxolyn": "2",
 "zytiga": "2",
 "zyprexa relprevv": "2",
 "zetran": "2",
 "ziac": "2",
 "zovia": "1"}}];