interactions["acetaminophen-caffeine-magnesium-salicylate,kneerelief"]=["acetaminophen-caffeine-magnesium-salicylate,kneerelief", {"a": {"anaspaz": "1",
 "aspirin/hydrocodone": "1",
 "anacin": "1",
 "aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "1",
 "aminophylline/amobarbital/ephedrine": "2",
 "aspir-low": "1",
 "aluminum hydroxide": "2",
 "adoxa ck": "2",
 "aristocort": "2",
 "azulfidine": "2",
 "atacand hct": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "2",
 "allerx pe": "1",
 "aspirtab": "1",
 "accuhist la": "1",
 "atelvia": "2",
 "abciximab": "2",
 "ascriptin enteric": "1",
 "apidra solostar": "2",
 "alendronate/cholecalciferol": "2",
 "akineton": "1",
 "amdry-c": "1",
 "argatroban": "2",
 "aspirin/carisoprodol": "1",
 "aspirin/chlorpheniramine/phenylephrine": "1",
 "antispas": "2",
 "amethia": "1",
 "acid gone antacid": "2",
 "aldactone": "1",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "actidose-aqua": "2",
 "aspirin/oxycodone": "1",
 "anturol": "1",
 "alu-tab": "2",
 "amytal sodium": "2",
 "aspir-mox": "2",
 "azdone": "1",
 "agrylin": "2",
 "aristopak": "2",
 "amylase/cellulase/hyoscyamine/lipase/phenyltoloxamine/protease": "1",
 "alcalak": "2",
 "adult strength": "1",
 "aspergum": "1",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aspirin/caffeine/orphenadrine": "1",
 "aciphex": "1",
 "ah-chew": "1",
 "amlodipine/telmisartan": "2",
 "aricept": "1",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "activated charcoal": "2",
 "alimta": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "alternagel": "2",
 "amphojel": "2",
 "alor 5/500": "1",
 "arixtra 5 mg/dose": "3",
 "alka-seltzer plus flu formula": "1",
 "amlobenz": "2",
 "acetohexamide": "2",
 "azopt": "3",
 "avidoxy dk": "2",
 "aspirin buffered": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "1",
 "alyacen 7/7/7": "1",
 "atropine/edrophonium": "1",
 "alodox": "2",
 "aminosyn ii with electrolytes": "2",
 "amlodipine/atorvastatin": "2",
 "amikacin": "2",
 "allerx dose pack": "1",
 "azilect": "2",
 "atazanavir": "1",
 "asbron g": "2",
 "adoxa tt": "2",
 "alesse-21": "1",
 "arthritis pain": "1",
 "aspirin/methocarbamol": "1",
 "asacol": "2",
 "alkets": "2",
 "atropine/diphenoxylate": "1",
 "alka-seltzer heartburn relief": "2",
 "alesse-28": "1",
 "aricept odt": "1",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "acetaminophen/aspirin": "1",
 "a-hydrocort": "2",
 "accuretic": "2",
 "acetaminophen/butalbital": "2",
 "angiomax": "2",
 "ami-lac": "2",
 "aerolate iii": "2",
 "allergy dn ii": "1",
 "a-spaz": "1",
 "aminosyn ii 4.25%-dextrose 25%,electrolyte,ca": "2",
 "atenolol": "1",
 "asenapine": "2",
 "aerokid": "1",
 "amturnide": "2",
 "avonex prefilled syringe": "2",
 "aspirin/caffeine": "1",
 "amdry-d": "1",
 "accesspak for hiv pep expanded with viracept": "3",
 "achromycin v": "2",
 "atrohist plus": "1",
 "anistreplase": "2",
 "aspir-mox ib": "2",
 "aspir 81": "1",
 "ah-chew ii": "1",
 "aminosyn ii 3.5%-dextrose 25%,electrolytes,ca": "2",
 "alcohol": "3",
 "aliskiren/valsartan": "2",
 "advicor": "1",
 "acetaminophen/aspirin/caffeine": "1",
 "allergy dn pe": "1",
 "atropine/difenoxin": "1",
 "adrenocot": "2",
 "arixtra 10 mg/dose": "3",
 "aminosyn ii 4.25%-dextrose 20%,electrolyte,ca": "2",
 "adlone-40": "2",
 "avidoxy": "2",
 "acid gone": "2",
 "arixtra": "3",
 "aspirin/meprobamate": "1",
 "anturane": "2",
 "axocet": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "accupril": "2",
 "apresoline": "2",
 "aliskiren/amlodipine": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "arixtra 7.5 mg/dose": "3",
 "amikin": "2",
 "ari sodium iodide (i123) 1-12 mbq": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/scopolamine": "1",
 "anoquan": "2",
 "avandaryl": "2",
 "allerx df dose pack": "1",
 "avapro": "2",
 "aldroxicon ii": "2",
 "a-methapred": "2",
 "acetocot": "2",
 "alka-seltzer wake-up call!": "1",
 "aggrenox": "2",
 "alkabel-sr": "2",
 "arcet": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "actidose with sorbitol": "2",
 "amobarbital": "2",
 "alagesic": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "abbokinase": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "alka-mints": "2",
 "amitone": "2",
 "almacone-2": "2",
 "ascriptin maximum strength": "2",
 "aluminum hydroxide/mineral oil": "2",
 "aceon": "2",
 "aerohist plus": "1",
 "avalide": "2",
 "atacand": "2",
 "alka-seltzer lemon-lime": "2",
 "acetylsalicylic acid": "1",
 "aspirin/butalbital/caffeine": "2",
 "aspircaf": "1",
 "amlodipine/benazepril": "2",
 "aminosyn with electrolytes sulfite-free": "2",
 "anisindione": "2",
 "adenocard": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2",
 "aspiritab": "1",
 "atropine/chlorpheniramine/hyoscyamine/pseudoephedrine/scopolamine": "1",
 "aldroxicon i": "2",
 "a-spas s/l": "1",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "azor": "2",
 "azmacort": "2",
 "aspirin/caffeine/dihydrocodeine": "1",
 "ala-tet": "2",
 "ami-rax": "2",
 "anacin advanced headache formula": "1",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "aspirin/pentazocine": "1",
 "amobarbital/secobarbital": "2",
 "angeliq": "2",
 "aspirin low strength": "1",
 "alenic alka tablet": "2",
 "aspirin/diphenhydramine": "1",
 "abacavir/lamivudine/zidovudine": "1",
 "actonel with calcium": "2",
 "alyacen 1/35": "1",
 "antabuse": "1",
 "acid gone extra strength": "2",
 "altavera": "1",
 "antispasmodic": "2",
 "alka-seltzer plus cold formula": "1",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "alka-seltzer pm": "1",
 "atnaa": "1",
 "aluminum carbonate": "2",
 "acetazolamide": "3",
 "alka-seltzer original": "2",
 "actidose-aqua advance": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "1",
 "ascriptin": "2",
 "altace": "2",
 "artane": "1",
 "alosetron": "2",
 "antrocol": "2",
 "amoxicillin/clarithromycin/lansoprazole": "1",
 "amphadase": "1",
 "alkums": "2",
 "asacol hd": "2",
 "aspirin": "1",
 "actidose plus sorbitol": "2",
 "ancobon": "2",
 "adlone-80": "2",
 "aclasta": "2",
 "aspirin/calcium carbonate": "2",
 "allerx pe dose pack": "1",
 "anafranil": "2",
 "aspirin/carisoprodol/codeine": "1",
 "aristospan": "2",
 "apidra": "2",
 "alcohol and dextrose injections usp hypertonic": "3",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/phenylpropanolamine/scopolamine": "1",
 "amlodipine": "2",
 "aerolate sr": "2",
 "aquaphyllin": "2",
 "aspirin/dipyridamole": "2",
 "acuprin 81": "1",
 "aggrastat": "2",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "aerolate jr": "2",
 "atrosept": "1",
 "allergy dn": "1",
 "anacin max strength": "1",
 "aminosyn with electrolytes": "2",
 "aspirin/pravastatin": "1",
 "accesspak for hiv pep expanded with kaletra": "3",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "adbeon": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "1",
 "azilsartan medoxomil": "2",
 "amikin pediatric": "2",
 "aspirin/phenyltoloxamine": "1",
 "ah-chew ultra tannate": "1",
 "ampicillin/probenecid": "1",
 "actisite": "2",
 "alteplase": "2",
 "adenosine": "2",
 "alu-cap": "2",
 "aerohist": "1",
 "aspirin/pseudoephedrine": "1",
 "acetaminophen/aspirin/phenylpropanolamine": "1",
 "aspirin/caffeine/salicylamide": "1",
 "almacone": "2",
 "atripla": "3",
 "atenolol/chlorthalidone": "1",
 "asthmacon": "2",
 "aristocort for injection": "2",
 "alendronate": "2",
 "apriso": "2",
 "apri": "1",
 "alamag": "2",
 "alamag plus": "2",
 "acebutolol": "1",
 "avonex": "2",
 "ardeparin": "2",
 "active carbon": "2",
 "allepak": "1",
 "ari sodium iodide (i123) 100-750 mbq": "2",
 "ah-chew ultra": "1",
 "acid relief": "2",
 "abbokinase open-cath": "2",
 "alagesic lq": "2",
 "azithromycin/trovafloxacin": "2",
 "aranelle": "1",
 "aspirin/diphenhydramine/phenylpropanolamine": "1",
 "atropine/phenobarbital": "2",
 "anagrelide": "2",
 "arthritis pain formula": "2",
 "adrenocot la": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "apresazide": "2",
 "adefovir": "3",
 "alesse": "1",
 "atreza": "1",
 "atropine": "1",
 "adeno-jec": "2",
 "adenoscan": "2",
 "amlodipine/olmesartan": "2",
 "alka-seltzer gold": "2",
 "amethyst": "1",
 "avelox i.v.": "2",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "asmalix": "2",
 "aredia": "2",
 "acid reducer + antacid dual action": "2",
 "aspirin lite coat": "1",
 "aspirin/butalbital": "2",
 "amethia lo": "1",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "1",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "2",
 "accesspak for hiv pep basic": "3",
 "aspirin/codeine": "1",
 "alka-seltzer extra strength": "2",
 "akineton hcl": "1",
 "acova": "2",
 "alenic alka": "2",
 "allergy am-pm dose pack": "1",
 "arava": "3",
 "activase": "2",
 "allerx df": "1",
 "aloh-gel": "2",
 "alcohol 5% in dextrose 5%": "3",
 "avelox": "2",
 "amlodipine/valsartan": "2",
 "allerx-d": "1",
 "atropen": "1",
 "aldactazide": "1",
 "adoxa": "2",
 "atropine/pralidoxime": "1",
 "aminosyn ii with electrolytes sulfite-free": "2",
 "actonel": "2",
 "arthritis foundation pain reliever": "1",
 "azulfidine en-tabs": "2",
 "aspirin/caffeine/propoxyphene": "1",
 "americet": "2",
 "aviane": "1",
 "anolor 300": "2",
 "azurette": "1",
 "amaryl": "2"}, "c": {"calcitab": "2",
 "cvs extra strength headache relief": "1",
 "calcijex": "2",
 "cardene sr": "2",
 "cozaar": "2",
 "cerebyx": "2",
 "cystospaz-m": "1",
 "citric acid/simethicone/sodium bicarbonate": "2",
 "carbosorb x": "2",
 "cyclafem 7/7/7": "1",
 "capozide 50/25": "2",
 "calcium carbonate/fluoride": "2",
 "clexane forte": "2",
 "coryza-d": "1",
 "cascara sagrada/magnesium hydroxide": "2",
 "calcarb with d": "2",
 "chem mart nasal decongestant capsule": "2",
 "cipro i.v.": "2",
 "cholestyramine": "1",
 "charcoal/simethicone": "2",
 "charcoaid-g": "2",
 "cpm-pe-msc": "1",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "clozapine synthon": "1",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "cardizem cd": "1",
 "cinobac": "2",
 "cartia xt": "1",
 "cogentin": "1",
 "citric acid/potassium citrate/sodium citrate": "2",
 "cuprimine": "2",
 "cortisone": "2",
 "clopidogrel": "2",
 "clexane": "2",
 "citalopram": "2",
 "canasa": "2",
 "capoten": "2",
 "cholecalciferol": "2",
 "corzide 40/5": "1",
 "cardizem sr": "1",
 "calcium oyster shell": "2",
 "covera-hs": "2",
 "citra ph": "2",
 "charcotabs": "2",
 "calcid": "2",
 "coumadin": "2",
 "coreg cr": "1",
 "celestone phosphate": "2",
 "corgard": "1",
 "cinoxacin": "2",
 "calan sr": "2",
 "cardene": "2",
 "clozapine": "1",
 "chlor-mes d": "1",
 "clopine": "1",
 "chloromag": "2",
 "chlorpheniramine/methscopolamine/phenylpropanolamine": "1",
 "cardizem": "1",
 "cotolone": "2",
 "caduet": "2",
 "citric acid/glucono-delta-lactone/magnesium carbonate topical": "2",
 "carisoprodol compound": "1",
 "cholecalciferol/genistein/zinc chelazome": "2",
 "cytra-2": "2",
 "charcoaid": "2",
 "celexa": "2",
 "cipro": "2",
 "carimune nf": "3",
 "charcoaid 2000": "2",
 "citracal + d": "2",
 "cardizem la": "1",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "calan": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "calcium carbonate/simethicone": "2",
 "careone acid reducer": "1",
 "caltrate colon health": "2",
 "cortenema": "2",
 "clofarabine": "2",
 "char-flo with sorbitol": "2",
 "charcotrace": "2",
 "citrocarbonate": "2",
 "chlordinium": "1",
 "citracal calcium gummies": "2",
 "ceo-two": "2",
 "chlordiazepoxide/clidinium": "1",
 "citracal regular 250 mg + d": "2",
 "cortifoam": "2",
 "canasa pac": "2",
 "candesartan/hydrochlorothiazide": "2",
 "ciprofloxacin": "2",
 "candesartan": "2",
 "calcifediol": "2",
 "complera": "3",
 "clozaril": "1",
 "calcium carbonate/risedronate": "2",
 "citrolith": "2",
 "cyclessa": "1",
 "cipro xr": "2",
 "caltrate 600+d": "2",
 "capacet": "2",
 "charcocaps": "2",
 "cell-u-jec": "2",
 "clidinium": "1",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "carlson d": "2",
 "chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "1",
 "citracal regular": "2",
 "colidrops": "1",
 "cipro cystitis pack": "2",
 "commit": "1",
 "calcium carbonate/magnesium carbonate": "2",
 "chlordiazepoxide/methscopolamine": "1",
 "carbinoxamine/methscopolamine/pseudoephedrine": "1",
 "colchicine/probenecid": "1",
 "citrus calcium with vitamin d": "2",
 "calciferol": "2",
 "chlorpropamide": "2",
 "chlor-mes": "1",
 "cystex": "1",
 "cytogam": "3",
 "cosopt": "3",
 "calderol": "2",
 "cytra-k": "2",
 "calcitrate with d": "2",
 "calcio del mar": "2",
 "caltrate 600 with d plus soy": "2",
 "cortone acetate": "2",
 "cardizem monovial": "1",
 "cyclafem 1/35": "1",
 "cantil": "1",
 "combivir": "1",
 "capozide 25/15": "2",
 "clomipramine": "2",
 "cal-gest": "2",
 "calcium carbonate": "2",
 "cathflo activase": "2",
 "calcet": "2",
 "caltro with vitamin d": "2",
 "charcoal": "2",
 "carteolol": "1",
 "cymbalta": "2",
 "cimetidine": "1",
 "carimune": "3",
 "carbomix": "2",
 "citracal maximum": "2",
 "coreg": "1",
 "cal oys": "2",
 "clinalog": "2",
 "carbamazepine": "2",
 "cidomycin": "2",
 "clinacort": "2",
 "carvedilol": "1",
 "cafatine pb": "2",
 "clinimix e sulfite free": "2",
 "capozide 50/15": "2",
 "cesia": "1",
 "chewable calcium with vitamin d": "2",
 "cyclosporine": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "cartrol": "1",
 "coldamine": "1",
 "caziant": "1",
 "chlorpheniramine/dextromethorphan/guaifenesin/methscopolamine/phenylephrine": "1",
 "cidofovir": "3",
 "chlorpheniramine/methscopolamine/phenylephrine": "1",
 "charcodote": "2",
 "calci mix": "2",
 "cuvposa": "1",
 "clolar": "2",
 "celestone soluspan": "2",
 "cytra-3": "2",
 "charcoal/sorbitol": "2",
 "cephadyn": "2",
 "carbatrol": "2",
 "captopril/hydrochlorothiazide": "2",
 "citracal petites": "2",
 "calcium oyster": "2",
 "calcidol": "2",
 "cystemms-v": "1",
 "citric acid/sodium citrate": "2",
 "calcarb": "2",
 "captopril": "2",
 "chlorpheniramine/methscopolamine": "1",
 "calcium acetate/magnesium carbonate": "2",
 "citrate-phos-dex": "2",
 "cholestyramine light": "1",
 "calcium/vitamin d": "2",
 "cellulase/hyoscyamine/pancrelipase/phenyltoloxamine": "1",
 "cope": "1",
 "calcium concentrate": "2",
 "celestone": "2",
 "chlorpheniramine/methscopolamine/pseudoephedrine": "1",
 "colocort": "2",
 "cryselle": "1",
 "corzide": "1",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "cytomegalovirus immune globulin": "3",
 "calvite p": "2",
 "camreselo": "1",
 "colazal": "2",
 "charcoal plus ds": "2",
 "citracal plus bone density builder": "2",
 "corzide 80/5": "1",
 "chlorpheniramine/dextromethorphan/methscopolamine": "1",
 "citracal plus heart health": "2",
 "chardonna-2": "2",
 "chlorpheniramine/guaifenesin/methscopolamine/phenylephrine": "1",
 "cystospaz": "1",
 "citracal slow release 1200": "2",
 "calcitriol": "2",
 "calcium 600 d": "2",
 "citric acid/potassium citrate": "2",
 "camrese": "1",
 "cort-k": "2",
 "cardene iv": "2",
 "clindex": "1",
 "capozide": "2",
 "capozide 25/25": "2",
 "cosopt pf": "3",
 "calcium liquid softgel": "2",
 "cortef": "2",
 "cholecalciferol/genistein/zinc glycinate": "2",
 "corlopam": "1",
 "caltrate gummy bites": "2",
 "caltrate": "2",
 "caltro": "2",
 "calci-chew": "2",
 "chooz": "2"}, "b": {"bellaphen-s": "2",
 "betaxolol": "1",
 "balsalazide": "2",
 "butisol sodium": "2",
 "buffasal": "1",
 "brevibloc": "1",
 "brinzolamide ophthalmic": "3",
 "brompheniramine/chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "1",
 "busulfex": "2",
 "bystolic": "1",
 "bicitra": "2",
 "bayer am": "1",
 "bufferin": "1",
 "baros": "2",
 "bayer pm": "1",
 "bayer aspirin extra strength plus": "1",
 "b c powder arthritis strength": "1",
 "benicar hct": "2",
 "bemote": "1",
 "bel-phen-ergot": "2",
 "bronchial": "2",
 "bayer women's aspirin with calcium": "1",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "butabarbital": "2",
 "bisoprolol/hydrochlorothiazide": "1",
 "belladonna tincture": "1",
 "betapace af": "1",
 "berkley and jensen acid reducer maximum strength": "1",
 "belladonna/butabarbital": "2",
 "bayer children's aspirin": "1",
 "briellyn": "1",
 "bumex": "1",
 "betapace": "1",
 "b3-500-gr": "1",
 "b c powder": "1",
 "bayer extra strength back &amp; body": "1",
 "beta-phos/ac": "2",
 "bydureon": "2",
 "bayer aspirin": "1",
 "buffered aspirin": "1",
 "beyaz": "2",
 "baraclude": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "betaseron": "2",
 "bidil": "2",
 "bicarsim": "2",
 "bentyl": "1",
 "bellaspas": "2",
 "black cohosh": "2",
 "betamethasone": "2",
 "benemid": "1",
 "boniva": "2",
 "butex forte": "2",
 "bivalirudin": "2",
 "bicarsim forte": "2",
 "baycadron": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bellamine": "2",
 "bepridil": "2",
 "basaljel": "2",
 "bel-tabs": "2",
 "belladonna": "1",
 "bio-melatonin": "1",
 "belladonna/opium": "1",
 "bendroflumethiazide/nadolol": "1",
 "broncodur": "2",
 "babybig": "3",
 "bayer advanced aspirin": "1",
 "balziva": "1",
 "brevital sodium": "2",
 "bc headache": "1",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "broncomar gg": "2",
 "busulfan": "2",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bayer aspirin with heart advantage": "1",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "2",
 "bexxartherapeutic": "3",
 "bisoprolol": "1",
 "butalbital": "2",
 "biperiden": "1",
 "bayer aspirin regimen": "1",
 "bendamustine": "2",
 "bellergal-s": "2",
 "bellalphen": "2",
 "byclomine": "1",
 "bronkodyl": "2",
 "bellamine s": "2",
 "bell/ans": "2",
 "bufferin low dose": "1",
 "bexxar dosimetric": "3",
 "bellatal er": "2",
 "benztropine": "1",
 "blocadren": "1",
 "belladonna/ergotamine/phenobarbital": "2",
 "bayer women's low dose plus calcium": "2",
 "benazepril/hydrochlorothiazide": "2",
 "benzoic acid/methenamine/sodium salicylate": "1",
 "b-3-50": "1",
 "bupap": "2",
 "b &amp; o supprettes": "1",
 "belcomp-pb": "2",
 "brilinta": "2",
 "brevicon": "1",
 "butalbital compound": "2",
 "bumetanide": "1",
 "buffex": "1",
 "byetta": "2",
 "botulism immune globulin": "3",
 "benazepril": "2",
 "bellamor": "2",
 "bellahist-d la": "1",
 "bufferin arthritis strength": "1",
 "bufferin extra strength": "1",
 "bexxar": "3",
 "bc fast pain relief": "1",
 "busodium": "2",
 "benicar": "2",
 "butibel": "2",
 "barbidonna": "2",
 "bellatal": "2",
 "bucet": "2",
 "bubbli-pred": "2",
 "brodspec": "2"}, "e": {"eplerenone": "2",
 "escitalopram": "2",
 "ecotrin maximum strength": "1",
 "effient": "3",
 "effervescent pain relief": "2",
 "ephedrine/guaifenesin/theophylline": "2",
 "ergocalciferol": "2",
 "equilet": "2",
 "ethinyl estradiol/levonorgestrel": "1",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "eprosartan": "2",
 "endodan": "1",
 "emtet-500": "2",
 "emagrin": "1",
 "ethinyl estradiol/etonogestrel": "1",
 "excedrin menstrual complete": "1",
 "epoprostenol": "2",
 "entaprin": "1",
 "embeda": "2",
 "eperbel-s": "2",
 "exforge hct": "2",
 "extendryl pse": "1",
 "enoxaparin": "2",
 "extendryl dm": "1",
 "extendryl": "1",
 "ergocomp-pb": "2",
 "edarbi": "2",
 "equibron g": "2",
 "esgic": "2",
 "ecotrin adult low strength": "1",
 "e-z-gas ii": "2",
 "ethinyl estradiol": "1",
 "ed-spaz": "1",
 "easprin": "1",
 "elixiral": "2",
 "edecrin": "1",
 "emoquette": "1",
 "estinyl": "1",
 "edarbyclor": "2",
 "epsom salt": "2",
 "eloxatin": "2",
 "excedrin migraine": "1",
 "enalapril/felodipine": "2",
 "ethinyl estradiol/norgestrel": "1",
 "ecpirin": "1",
 "esmolol": "1",
 "exforge": "2",
 "ethacrynic acid": "1",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ethinyl estradiol/norethindrone": "1",
 "equaline heartburn relief": "1",
 "entecavir": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "ed-bron g": "2",
 "ethanol": "3",
 "eltrombopag": "2",
 "eminase": "2",
 "e-caff p-b": "2",
 "equetro": "2",
 "enpresse": "1",
 "equaline acid reducer": "1",
 "endolor": "2",
 "esomeprazole/naproxen": "1",
 "ergocaf-pb": "2",
 "extendryl seniors": "1",
 "efavirenz": "2",
 "enlon-plus": "1",
 "ecotrin": "1",
 "ethyl alcohol": "3",
 "emtricitabine/rilpivirine/tenofovir": "3",
 "extendryl pem": "1",
 "emtricitabine/nelfinavir/tenofovir": "3",
 "effexor xr": "2",
 "extendryl sr": "1",
 "extendryl jr": "1",
 "enfamil d-vi-sol": "2",
 "exenatide": "2",
 "extra strength mylanta calci tabs": "2",
 "excedrin back &amp; body": "1",
 "esomeprazole": "1",
 "ex-tuss": "1",
 "ethinyl estradiol/ethynodiol": "1",
 "ethinyl estradiol/norgestimate": "1",
 "entercote": "1",
 "etidronate": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "3",
 "eskalith": "2",
 "ezchar": "2",
 "eskalith-cr": "2",
 "empirin with codeine": "1",
 "emtricitabine/tenofovir": "3",
 "estrostep fe": "1",
 "enalapril": "2",
 "equagesic": "1",
 "ex-lax milk of magnesia": "2",
 "enablex": "1",
 "eprosartan/hydrochlorothiazide": "2",
 "elixophyllin": "2",
 "exjade": "3",
 "excedrin extra strength": "1",
 "enoxacin": "2",
 "ethotoin": "2",
 "epitol": "2",
 "esgic-plus": "2",
 "elixophyllin ki": "2",
 "ex-histine": "1",
 "efavirenz/emtricitabine/tenofovir": "3",
 "effexor": "2",
 "extra strength bayer": "1",
 "extavia": "2",
 "ethinyl estradiol/norelgestromin": "1",
 "elixophyllin gg": "2",
 "ezol": "2",
 "empirin": "1",
 "extendryl chews": "1",
 "ergocaffpb": "2",
 "exubera": "2",
 "excedrin": "1",
 "eptifibatide": "2",
 "eucarbon": "2"}, "d": {"diovan": "2",
 "didanosine": "2",
 "depoject-80": "2",
 "diastat": "1",
 "delta d3": "2",
 "duetact": "2",
 "dipyridamole": "2",
 "di-gel": "2",
 "demadex": "1",
 "detrol": "1",
 "deconhist la": "1",
 "doryx": "2",
 "denzapine": "1",
 "durahist pe": "1",
 "dep medalone 80": "2",
 "diltiazem hydrochloride cd": "1",
 "diovan hct": "2",
 "dolsed": "1",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "drize": "1",
 "dehydrated alcohol": "3",
 "demulen 1/50": "1",
 "donnatal extentabs": "2",
 "desogestrel/ethinyl estradiol": "1",
 "dewees carminative": "2",
 "dolgic plus": "2",
 "diamox sequels": "3",
 "divalproex sodium": "2",
 "duodote": "1",
 "ditropan": "1",
 "di-gel mint": "2",
 "dical captabs": "2",
 "depmedalone": "2",
 "da ii": "1",
 "di-spaz": "1",
 "dilomine": "1",
 "dexilant": "1",
 "dalteparin": "2",
 "ditropan xl": "1",
 "dicarbosil": "2",
 "decadron with xylocaine": "2",
 "diltzac": "1",
 "depakote er": "2",
 "diamox": "3",
 "dolgic": "2",
 "drotrecogin alfa": "3",
 "dynacirc": "2",
 "dabigatran": "2",
 "dexamethasone/lidocaine": "2",
 "dolmar": "2",
 "darvon compound 32": "1",
 "dalalone la": "2",
 "depakene": "2",
 "dehistine": "1",
 "delta-lutin": "2",
 "damason-p": "1",
 "duradryl chewable": "1",
 "duravent": "1",
 "dallergy pse": "1",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "1",
 "dorzolamide ophthalmic": "3",
 "desogen": "1",
 "d3-5": "2",
 "dasetta 1/35": "1",
 "dallergy pe": "1",
 "dexacort phosphate in turbinaire": "2",
 "dizac": "1",
 "dynacin": "2",
 "diuretic ap-es": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "darcalma": "1",
 "deferiprone": "2",
 "doxycycline/omega-3 polyunsaturated fatty acids": "2",
 "diltiazem hydrochloride xt": "1",
 "drospirenone/estradiol": "2",
 "diltiazem hydrochloride xr": "1",
 "dexchlorpheniramine/methscopolamine/pseudoephedrine": "1",
 "darifenacin": "1",
 "diaqua-2": "1",
 "dymelor": "2",
 "deltasone": "2",
 "diltiazem": "1",
 "duradryl jr": "1",
 "dolobid": "1",
 "dexacort-la": "2",
 "dipentum": "2",
 "duralutin": "2",
 "dexamethasone": "2",
 "durahist d": "1",
 "didronel": "2",
 "dilacor xr": "1",
 "dexlansoprazole": "1",
 "doxy 100": "2",
 "dihydroxyaluminum sodium carbonate": "2",
 "deprizine": "1",
 "dexchlorpheniramine/methscopolamine/phenylephrine": "1",
 "doxercalciferol": "2",
 "duragal-s": "2",
 "drymax": "1",
 "dalalone dp": "2",
 "dexodryl": "1",
 "dexasone": "2",
 "donnatal": "2",
 "dutoprol": "1",
 "dual action complete": "2",
 "deferasirox": "3",
 "doxy-caps": "2",
 "dical-d": "2",
 "doxycycline": "2",
 "dexone": "2",
 "darpaz": "1",
 "d3-50": "2",
 "doxy-d": "2",
 "daranide": "3",
 "dexphen m": "1",
 "doxy 200": "2",
 "drihist": "1",
 "delta-cortef": "2",
 "duradryl": "1",
 "digex": "1",
 "dihydrotachysterol": "2",
 "d-hist d": "1",
 "demulen": "1",
 "depakote": "2",
 "diastat acudial": "1",
 "da chewable": "1",
 "diltia xt": "1",
 "dexasone la": "2",
 "duratan pe": "1",
 "dasatinib": "3",
 "diabinese": "2",
 "demeclocycline": "2",
 "depen": "2",
 "dasetta": "1",
 "dicumarol": "2",
 "darvon compound-65": "1",
 "donnamar": "1",
 "dulcolax milk of magnesia": "2",
 "drihist sr": "1",
 "desirudin": "3",
 "decadron phosphate, injectable": "2",
 "depacon": "2",
 "d400": "2",
 "depo-medrol": "2",
 "decadron": "2",
 "denaze": "1",
 "d-tal": "2",
 "de-sone la": "2",
 "donepezil": "1",
 "dexacort phosphate in respihaler": "2",
 "duravent da": "1",
 "diazepam intensol": "1",
 "didronel iv": "2",
 "dht intensol": "2",
 "dichlorphenamide": "3",
 "depen titratabs": "2",
 "depopred": "2",
 "dicyclocot": "1",
 "dorzolamide/timolol ophthalmic": "3",
 "drospirenone/ethinyl estradiol": "2",
 "drisdol": "2",
 "di-gel lemon": "2",
 "dexamethasone intensol": "2",
 "diastat pediatric": "1",
 "diabeta": "2",
 "decadron-la": "2",
 "duralone": "2",
 "digex nf": "1",
 "detrol la": "1",
 "dexfenfluramine": "2",
 "dallergy er": "1",
 "d2000": "2",
 "diazepam": "1",
 "drysec": "1",
 "dexacorten": "2",
 "demadex iv": "1",
 "dibent": "1",
 "danaparoid": "2",
 "depakote sprinkles": "2",
 "depade": "2",
 "duradryl sr": "1",
 "doxycycline/salicylic acid topical": "2",
 "dht": "2",
 "dialume": "2",
 "d 1000 iu": "2",
 "demulen 1/35": "1",
 "decaject la": "2",
 "dicyclomine": "1",
 "diltiazem hydrochloride sr": "1",
 "durahist": "1",
 "dexacen-4": "2",
 "dolgic lq": "2",
 "donnaphen": "2",
 "dexodryl suspension": "1",
 "dexone la": "2",
 "disulfiram": "1",
 "dicalphos plus d": "2",
 "dalalone": "2",
 "dynacirc cr": "2",
 "dexpak taperpak": "2",
 "dilantin": "2",
 "dasetta 7/7/7": "1",
 "declomycin": "2",
 "desvenlafaxine": "2",
 "disposable enema": "3",
 "dilt-xr": "1",
 "duloxetine": "2",
 "decaject": "2"}, "g": {"glyburide": "2",
 "gildess fe 1.5/30": "1",
 "guaifenesin/theophylline": "2",
 "gammar iv": "3",
 "goodys headache powders": "1",
 "glynase prestab": "2",
 "genprin": "1",
 "gaviscon regular strength tablets": "2",
 "glycron": "2",
 "genace": "1",
 "glimepiride/rosiglitazone": "2",
 "gaviscon regular strength liquid": "2",
 "genora 0.5/35": "1",
 "gaviscon extra strength liquid": "2",
 "gelusil": "2",
 "generess fe": "1",
 "gastrinex": "1",
 "glipizide": "2",
 "genasan": "1",
 "gengraf": "2",
 "gemifloxacin": "2",
 "glycopyrrolate": "1",
 "glyceryl t": "2",
 "glipizide xl": "2",
 "genaton": "2",
 "gas-x with maalox extra strength": "2",
 "g-1": "2",
 "gamimune n 10%": "3",
 "gaviscon extra relief formula": "2",
 "gennin-fc": "1",
 "goody's extra-strength headache powders": "1",
 "gianvi": "2",
 "goody's body pain": "1",
 "glipizide/metformin": "2",
 "gamimune": "3",
 "giazo": "2",
 "gammaplex": "3",
 "gatifloxacin": "2",
 "gammar-p i.v.": "3",
 "gamunex-c": "3",
 "gildess fe 1/20": "1",
 "genacote": "1",
 "goodys extra strength": "1",
 "geone": "2",
 "gleevec": "2",
 "gas-x with maalox": "2",
 "glynase": "2",
 "glucotrol": "2",
 "gamunex": "3",
 "glucotrol xl": "2",
 "gastrosed": "1",
 "gaviscon-2": "2",
 "gammagard s/d": "3",
 "gelnique": "1",
 "gamimune n 5%": "3",
 "genora 1/35": "1",
 "genora 1/50": "1",
 "gentamicin": "2",
 "glauctabs": "3",
 "glimepiride": "2",
 "glucovance": "2",
 "glyburide/metformin": "2",
 "gaviscon extra strength tablets": "2",
 "garamycin": "2",
 "grepafloxacin": "2",
 "gammagard": "3",
 "glimepiride/pioglitazone": "2",
 "genaton chewable": "2"}, "f": {"flolan": "2",
 "fondaparinux": "3",
 "first mouthwash blm": "2",
 "fiortal": "2",
 "fentanyl/ropivacaine": "1",
 "furosemide": "1",
 "flucytosine": "2",
 "fiorinal with codeine iii": "2",
 "folex pfs": "3",
 "flatulex": "2",
 "fleet ez-prep": "3",
 "fazaclo": "1",
 "fiorinal with codeine": "2",
 "fleet phospho soda": "3",
 "fortabs": "2",
 "florinef acetate": "2",
 "fiorinal": "2",
 "fioricet with codeine": "2",
 "fluvoxamine": "2",
 "fasprin": "1",
 "fenoldopam": "1",
 "femcet": "2",
 "fosinopril": "2",
 "florinef": "2",
 "fleet enema": "3",
 "femhrt": "1",
 "felodipine": "2",
 "fast acting mylanta": "2",
 "fenfluramine": "2",
 "flumist": "3",
 "flavoxate": "1",
 "floxin": "2",
 "fiortal with codeine": "2",
 "flebogamma": "3",
 "fosphenytoin": "2",
 "fosamax": "2",
 "flo-pred": "2",
 "fluoxetine": "2",
 "fluoxetine/olanzapine": "2",
 "factive": "2",
 "fleet prep kit 1": "3",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "fludrocortisone": "2",
 "fragmin": "2",
 "fleet enema extra": "3",
 "fosamax plus d": "2",
 "ferriprox": "2",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiormor": "2",
 "fosteum": "2",
 "florical": "2",
 "folotyn": "2",
 "farbital": "2",
 "fiv-asa": "2",
 "floxin iv": "2",
 "freamine iii with electrolytes": "2",
 "femcon fe": "1",
 "fosinopril/hydrochlorothiazide": "2",
 "fiorpap": "2"}, "i": {"isradipine": "2",
 "iletin ii lente pork": "2",
 "influenza virus vaccine, h1n1, live": "3",
 "iodine i 131 tositumomab": "3",
 "inderide": "1",
 "irbesartan": "2",
 "insulin inhalation, rapid acting": "2",
 "insta-char with sorbitol": "2",
 "insulin glargine": "2",
 "iletin lente": "2",
 "insulin lispro": "2",
 "integrilin": "2",
 "innohep": "2",
 "insulin zinc extended": "2",
 "iprivask": "3",
 "insulin isophane": "2",
 "inderal la": "1",
 "introvale": "1",
 "isoniazid": "2",
 "icar prenatal chewable calcium": "2",
 "isoptin": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isocet": "2",
 "imipramine": "2",
 "iloprost": "2",
 "iletin regular": "2",
 "inderide la": "1",
 "iodotope": "2",
 "insulin aspart": "2",
 "insulin aspart protamine": "2",
 "influenza virus vaccine, live, trivalent": "3",
 "iveegam en": "3",
 "iletin nph": "2",
 "insta-char": "2",
 "isoniazid/rifampin": "2",
 "innopran xl": "1",
 "immune globulin intravenous": "3",
 "isoptin sr": "2",
 "insulin zinc": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "inspra": "2",
 "insulin lispro/insulin lispro protamine": "2",
 "ide-cet": "2",
 "insulin detemir": "2",
 "insulin isophane/insulin regular": "2",
 "insulin aspart/insulin aspart protamine": "2",
 "immune globulin intravenous and subcutaneous": "3",
 "in-111 zevalin": "3",
 "isonarif": "2",
 "insulin regular": "2",
 "iosopan": "2",
 "insulin glulisine": "2",
 "insulin purified regular pork": "2",
 "inderal": "1",
 "insulin purified nph pork": "2",
 "insulin pork mix": "2",
 "iletin ii nph pork": "2",
 "ibritumomab": "3",
 "iletin ii regular pork": "2",
 "isoptin iv": "2",
 "insulin lente pork": "2",
 "idenal": "2",
 "insulin": "2",
 "ibandronate": "2",
 "ib-stat": "1",
 "insulin lispro protamine": "2",
 "imatinib": "2"}, "h": {"hydeltrasol": "2",
 "hyophen": "1",
 "hycodan": "1",
 "hylenex": "1",
 "histatab ph": "1",
 "humulin 70/30 pen": "2",
 "hydrochlorothiazide/spironolactone": "1",
 "hydrap-es": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "hyomax sr": "1",
 "hyoscyamine/methenamine": "1",
 "hyoscyamine/phenyltoloxamine": "1",
 "hydrophed": "2",
 "heparin sodium": "2",
 "hyomax sl": "1",
 "hista-vent da": "1",
 "hydrochlorothiazide/propranolol": "1",
 "hydrochlorothiazide/lisinopril": "2",
 "hyosyne": "1",
 "hydase": "1",
 "haley's m-o": "2",
 "hydromide": "1",
 "hydra-zide": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hycamtin": "1",
 "hydralazine/isosorbide dinitrate": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hexadrol": "2",
 "homatropine/hydrocodone": "1",
 "hyoscyamine/phenobarbital": "2",
 "hyzaar": "2",
 "helidac": "2",
 "hydrocortisone": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "1",
 "hyomax ft": "1",
 "hylutin": "2",
 "hydrochlorothiazide/moexipril": "2",
 "halflytely and bisacodyl": "2",
 "hyospaz": "1",
 "hista-vent pse": "1",
 "hydromet": "1",
 "humulin l": "2",
 "humulin n": "2",
 "hydroxy compound": "2",
 "humalog mix 75/25": "2",
 "humulin u": "2",
 "hydroxyprogesterone": "2",
 "heparin": "2",
 "hyoscyamine": "1",
 "hyosol": "1",
 "hectorol": "2",
 "hyaluronidase": "1",
 "hyosophen": "2",
 "hyomax dt": "1",
 "humulin 50/50": "2",
 "hydrochlorothiazide/metoprolol": "1",
 "hydropane": "1",
 "humalog": "2",
 "hydrotropine": "1",
 "humulin r": "2",
 "habitrol": "1",
 "hydrochlorothiazide/irbesartan": "2",
 "humalog mix 50/50": "2",
 "halfprin": "1",
 "histatab": "1",
 "humalog mix 50/50 pen": "2",
 "hydrochlorothiazide/timolol": "1",
 "hepsera": "3",
 "hyomax": "1",
 "heartline": "1",
 "humalog mix 75/25 kwikpen": "2",
 "hhr": "2",
 "hyprogesterone": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "heartburn antacid extra strength": "2",
 "hydrocortone phosphate": "2",
 "hytakerol": "2",
 "hydrochlorothiazide/losartan": "2",
 "hydralazine": "2",
 "healthstream activated charcoal": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydeltra-tba": "2",
 "humalog kwikpen": "2",
 "humulin n pen": "2",
 "humalog mix 50/50 kwikpen": "2",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "hydrocortone": "2",
 "histatab d": "1",
 "health aid melatonin": "1",
 "humulin 70/30": "2",
 "humalog mix 75/25 pen": "2",
 "hydralazine plus": "2",
 "humalog pen": "2"}, "k": {"ken-jec 40": "2",
 "kenalog-10": "2",
 "kionex": "2",
 "kayexalate": "2",
 "kabikinase": "2",
 "kelnor 1/35": "1",
 "kalexate": "2",
 "key-pred": "2",
 "karbons": "2",
 "k-lyte ds": "2",
 "kerlone": "1",
 "kenaject-40": "2",
 "k-lyte": "2",
 "kapidex": "1",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "ketorolac": "3",
 "kinlytic": "2",
 "kariva": "1",
 "kantrex": "2",
 "kanamycin": "2",
 "kemadrin": "1"}, "j": {"jolessa": "1",
 "jl bragg's medicinal charcoal": "2",
 "jenest": "1",
 "jinteli": "1",
 "junel 1.5/30": "1",
 "jantoven": "2",
 "jevantique": "1",
 "junel fe 1/20": "1",
 "junel fe 1.5/30": "1",
 "junel 1/20": "1"}, "m": {"meridia": "2",
 "morphine/naltrexone": "2",
 "min-ovral 21": "1",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine/varicella virus vaccine": "2",
 "medrol dosepak": "2",
 "miradon": "2",
 "maoson": "2",
 "magdelay": "2",
 "maalox advanced maximum strength": "2",
 "magnesium oxide": "2",
 "mestranol/norethindrone": "1",
 "mesasal enteric coated": "2",
 "maldemar": "1",
 "mhp-a": "1",
 "mi-acid ii": "2",
 "methacort 40": "2",
 "migracet-pb": "2",
 "magaldrate plus suspension": "2",
 "medique pain-off": "1",
 "magnesium carbonate": "2",
 "mephobarbital": "2",
 "magaldrate": "2",
 "monocal": "2",
 "medicoal": "2",
 "mephenytoin": "2",
 "mescolor": "1",
 "methylcotolone": "2",
 "maalox advanced maximum strength chewable": "2",
 "microgestin 1/20": "1",
 "maalox max wild berry": "2",
 "monopril": "2",
 "millipred dp": "2",
 "methacort 80": "2",
 "medicort": "2",
 "mylagen-ii": "2",
 "maggel": "2",
 "matzim la": "1",
 "methenamine/sodium biphosphate": "3",
 "methylcotol": "2",
 "motofen": "1",
 "mag-sr": "2",
 "mag-200": "2",
 "mylagen": "2",
 "maalox max quick dissolve": "2",
 "methylprednisolone": "2",
 "minitabs": "1",
 "maalox": "2",
 "monodox": "2",
 "midol traditional": "1",
 "milantex": "2",
 "myzilra": "1",
 "magnesium hydroxide/mineral oil": "2",
 "millipred": "2",
 "methotrexate": "3",
 "mintox": "2",
 "mylanta maximum strength": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "2",
 "my-o-den": "2",
 "mysoline": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "min-ovral 28": "1",
 "milk of magnesia": "2",
 "mi-acid double strength": "2",
 "magaant": "2",
 "micardis": "2",
 "medrol": "2",
 "milnacipran": "2",
 "methscopolamine/phenylephrine": "1",
 "mintox extra strength": "2",
 "makena": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "masanti ds": "2",
 "mag-carb": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "marlissa": "1",
 "maalox advanced regular strength": "2",
 "mylanta ultra": "2",
 "magnebind 200": "2",
 "milantex maximum strength": "2",
 "maldroxal plus": "2",
 "methohexital": "2",
 "microgestin 1.5/30": "1",
 "micronase": "2",
 "magnesium sulfate": "2",
 "meticorten": "2",
 "melatonin time release": "1",
 "methylpred dp": "2",
 "mircette": "1",
 "micomp-pb": "2",
 "microgestin fe 1/20": "1",
 "maalox junior relief chewable": "2",
 "maximum d3": "2",
 "mygracet": "2",
 "mepenzolate": "1",
 "margesic": "2",
 "mintox plus": "2",
 "maalox regular strength": "2",
 "medidex la": "2",
 "metaglip": "2",
 "migralex": "1",
 "mesantoin": "2",
 "mintox maximum strength": "2",
 "mylanta supreme": "2",
 "minotal": "2",
 "micrainin": "1",
 "maalox plus": "2",
 "mag-ox": "2",
 "mononessa": "1",
 "metformin/repaglinide": "2",
 "mag-caps": "2",
 "medigesic": "2",
 "maalox quick dissolve extra strength": "2",
 "myrac": "2",
 "mebaral": "2",
 "mylanta ultimate strength": "2",
 "micardis hct": "2",
 "marblen": "2",
 "methazolamide": "3",
 "mylanta child": "2",
 "modicon": "1",
 "maalox children's relief": "2",
 "mylanta ds fast acting": "2",
 "menopause support": "2",
 "maxaquin": "2",
 "masanti": "2",
 "metoprolol succinate er": "1",
 "magnebind 300": "2",
 "microgestin fe 1.5/30": "1",
 "medi-seltzer": "1",
 "momentum": "1",
 "metoprolol": "1",
 "masanti supreme": "2",
 "magnaprin": "2",
 "mag-ox 400": "2",
 "maalox tc": "2",
 "mi-acid": "2",
 "mylanta": "2",
 "minocin": "2",
 "methscopolamine/pseudoephedrine": "1",
 "medralone": "2",
 "medipred": "2",
 "moxifloxacin": "2",
 "m-prednisolone": "2",
 "mudrane gg": "2",
 "medralone 80": "2",
 "melatonin": "1",
 "mylanta fast acting": "2",
 "methotrexate lpf sodium": "3",
 "msp-blu": "1",
 "mintezol": "2",
 "marten-tab": "2",
 "mag-oxide": "2",
 "monopril hct": "2",
 "methylprednisolone dose pack": "2",
 "myleran": "2",
 "maalox max": "2",
 "mylanta gelcap": "2",
 "magnesium chloride": "2",
 "mavik": "2",
 "mibefradil": "1",
 "maalox antacid antigas regular strength": "2",
 "marax df": "2",
 "mesalamine": "2",
 "medique medi-seltzer": "2",
 "mudrane": "2",
 "mzm": "3",
 "minocycline": "2",
 "marax": "2",
 "methscopolamine": "1",
 "medidex": "2",
 "mintox tablets": "2",
 "magaldrate/simethicone": "2",
 "mag 64": "2",
 "moexipril": "2",
 "maalox hrf": "2",
 "marpres": "2"}, "l": {"litecoat aspirin": "1",
 "losospan plus": "2",
 "lo loestrin fe": "1",
 "lisinopril": "2",
 "levsin sl": "1",
 "lovenox hp": "2",
 "lidocaine/sodium bicarbonate": "2",
 "lexiscan": "2",
 "levatol": "1",
 "lasix": "1",
 "lessina": "1",
 "lovenox": "2",
 "levonest": "1",
 "loestrin 1/20": "1",
 "librax": "1",
 "levaquin leva-pak": "2",
 "low-ogestrel-21": "1",
 "low-ogestrel-28": "1",
 "lithobid": "2",
 "losartan": "2",
 "lufyllin-epg": "2",
 "lidocaine/oxytetracycline": "2",
 "lente iletin ii": "2",
 "liqui-char": "2",
 "levlen": "1",
 "loestrin 21 1/20": "1",
 "loestrin fe 1.5/30": "1",
 "lamivudine/zidovudine": "1",
 "liquid pred": "2",
 "lantus opticlik cartridge": "2",
 "levaquin": "2",
 "losospan": "2",
 "liqui-dual citra": "2",
 "leflunomide": "3",
 "lomanate": "1",
 "lialda": "2",
 "lantus solostar": "2",
 "levlite": "1",
 "leader nicotine polacrilex": "1",
 "levemir": "2",
 "loestrin 21 1.5/30": "1",
 "lithotabs": "2",
 "levsinex sr": "1",
 "liqui-allergy": "1",
 "loestrin 24 fe": "1",
 "lantus": "2",
 "levsin": "1",
 "lowsium plus": "2",
 "lomefloxacin": "2",
 "liqui-char with sorbitol": "2",
 "levsin with phenobarbital": "2",
 "lowsium": "2",
 "luminal": "2",
 "locholest": "1",
 "lovastatin/niacin": "1",
 "lutera": "1",
 "levora": "1",
 "levsinex": "1",
 "lotensin hct": "2",
 "liraglutide": "1",
 "lopressor": "1",
 "lomocot": "1",
 "lo-aqua": "1",
 "lybrel": "1",
 "lexxel": "2",
 "lactobacillus acidophilus/methscopolamine": "1",
 "laniroif": "2",
 "lo/ovral-28": "1",
 "lepirudin": "2",
 "lomotil": "1",
 "lotrel": "2",
 "low dose asa": "1",
 "levacet": "1",
 "lonox": "1",
 "lexapro": "2",
 "lansoprazole": "1",
 "lortab asa": "1",
 "levofloxacin": "2",
 "loestrin fe 1/20": "1",
 "labetalol": "1",
 "lithium": "2",
 "luvox": "2",
 "luvox cr": "2",
 "lotronex": "2",
 "lithonate": "2",
 "loryna": "2",
 "locholest light": "1",
 "levbid": "1",
 "lansoprazole/naproxen": "1",
 "leena": "1",
 "logen": "1",
 "lopressor hct": "1",
 "loseasonique": "1",
 "lotensin": "2",
 "lo/ovral": "1"}, "o": {"orinase": "2",
 "orasone": "2",
 "orphengesic forte": "1",
 "oracit": "2",
 "oxytrol": "1",
 "oyst cal": "2",
 "orphengesic": "1",
 "o-cal-d": "2",
 "ortho-novum 1/50": "1",
 "ortho-novum 1/35": "1",
 "omnihist l.a.": "1",
 "oysco 500 with d": "2",
 "omesec": "1",
 "omeprazole/sodium bicarbonate": "2",
 "oysco d with calcium": "2",
 "oraxyl": "2",
 "oxybutynin": "1",
 "oyster calcium": "2",
 "os-cal 500": "2",
 "ortho-novum 7/7/7": "1",
 "os-cal 500 + extra d": "2",
 "ortho evra": "1",
 "oracea": "2",
 "oxytetracycline/phenazopyridine/sulfamethizole": "2",
 "oxytetracycline": "2",
 "ogestrel-28": "1",
 "os-cal 500 + d": "2",
 "ovral-28": "1",
 "orbivan": "2",
 "oyster": "2",
 "omeprazole": "1",
 "oyst cal 500": "2",
 "oyster shell": "2",
 "oxaliplatin": "2",
 "osmoprep": "3",
 "optimum charcoal": "2",
 "oyster shell calcium 500": "2",
 "oyster-d": "2",
 "oyster cal": "2",
 "ortho tri-cyclen": "1",
 "ocella": "2",
 "ovcon 35 fe": "1",
 "oysco d": "2",
 "ovral": "1",
 "ocudox": "2",
 "ortho-novum 10/11": "1",
 "olsalazine": "2",
 "oyster shell calcium with vitamin d": "2",
 "ofloxacin": "2",
 "orapred": "2",
 "ogestrel": "1",
 "orap": "2",
 "oyster shell calcium": "2",
 "ortho tri-cyclen lo": "1",
 "octagam": "3",
 "orsythia": "1",
 "olmesartan": "2",
 "ovcon 35": "1",
 "ortho-cept": "1",
 "oyst-cal-d": "2",
 "osteocit d plus": "2",
 "omnihist ii la": "1",
 "ovcon 50": "1",
 "os-cal": "2",
 "oystercal-d": "2",
 "orapred odt": "2",
 "oxazepam": "1",
 "ortho cyclen": "1",
 "oyster cal 500": "2",
 "orgaran": "2",
 "oysco 500": "2"}, "n": {"novolog mix 70/30 flexpen": "2",
 "necon 0.5/35": "1",
 "nicoderm cq": "1",
 "nicotinex": "1",
 "nexium": "1",
 "necon 10/11": "1",
 "niacin": "1",
 "nicolar": "1",
 "nebivolol": "1",
 "novolog flexpen": "2",
 "nicotrol ns": "1",
 "nulev": "1",
 "neggram": "2",
 "novolin n innolet": "2",
 "necon 7/7/7": "1",
 "nutridox convenience kit": "2",
 "nelova 10/11": "1",
 "novolin r penfill": "2",
 "norit": "2",
 "neut": "2",
 "niacin/simvastatin": "1",
 "norfloxacin": "2",
 "norel sd": "1",
 "nateglinide": "2",
 "nelova 0.5/35": "1",
 "novolog mix 70/30": "2",
 "novolin 70/30 penfill": "2",
 "normiflo": "2",
 "novolog mix 50/50": "2",
 "nicotine": "1",
 "nuvaring": "1",
 "nohist pe": "1",
 "nohist ext": "1",
 "novolog mix 70/30 penfill": "2",
 "nexium iv": "1",
 "norgesic forte": "1",
 "nicotinic acid": "1",
 "necon 1/35": "1",
 "normodyne": "1",
 "nicotrol inhaler": "1",
 "novolin l": "2",
 "novolin n": "2",
 "nicorette ds": "1",
 "netromycin": "2",
 "nicorelief": "1",
 "nordette-28": "1",
 "nordette-21": "1",
 "noroxin": "2",
 "nonbac": "2",
 "nelova 1/35": "1",
 "nicotrol td": "1",
 "nicorette": "1",
 "niaspan": "1",
 "nebcin": "2",
 "norethin 1/35 e": "1",
 "niacor b3": "1",
 "norethin 1/50 m": "1",
 "nicardipine": "2",
 "nortrel 0.5/35": "1",
 "nohist plus": "1",
 "nph insulin": "2",
 "naropin novaplus": "1",
 "naropin polyamp": "1",
 "naltrexone": "2",
 "nydrazid": "2",
 "novolog penfill": "2",
 "nacon": "1",
 "novolin 70/30 innolet": "2",
 "nalidixic acid": "2",
 "necon 1/50": "1",
 "norvasc": "2",
 "neoral": "2",
 "nimodipine": "2",
 "nephro calci": "2",
 "nico-400": "1",
 "nembutal sodium": "2",
 "nembutal": "2",
 "nohist plus jr": "1",
 "norinyl 1+50": "1",
 "nicobid tempules": "1",
 "novolin n penfill": "2",
 "nadolol": "1",
 "novolog": "2",
 "nortrel 7/7/7": "1",
 "nortrel 1/35": "1",
 "nelova 1/50 m": "1",
 "nisoldipine": "2",
 "norwich aspirin": "1",
 "novolin r innolet": "2",
 "norgesic": "1",
 "niacor": "1",
 "niacin sr": "1",
 "nebcin pediatric": "2",
 "novolin 70/30": "2",
 "netilmicin": "2",
 "nephrox": "2",
 "norinyl 1+35": "1",
 "nimotop": "2",
 "novolin r": "2",
 "neptazane": "3",
 "nordette": "1",
 "naropin": "1",
 "naropin sdv": "1"}, "q": {"quibron": "2",
 "quibron 300": "2",
 "quasense": "1",
 "quinapril": "2",
 "questran light": "1",
 "qv-allergy": "1",
 "quinaretic": "2",
 "questran": "1",
 "quibron-t/sr": "2",
 "quarzan": "1",
 "quadrinal": "2",
 "q-b": "2",
 "quadrapax": "2",
 "quibron-t": "2"}, "p": {"pyridium plus": "2",
 "phosphasal": "1",
 "phillips' cramp-free": "2",
 "pentasa": "2",
 "predicort-50": "2",
 "phrenilin forte": "2",
 "preven ec": "1",
 "parenteral nutrition solution w/electrolytes": "2",
 "predacort 50": "2",
 "protonix iv": "1",
 "prevacid naprapac 375": "1",
 "pyrelle hb": "2",
 "plavix": "2",
 "prevacid solutab": "1",
 "pradaxa": "2",
 "promacet": "2",
 "pharmagesic": "2",
 "pindolol": "1",
 "pantoprazole": "1",
 "pcm": "1",
 "prograf": "3",
 "predcor": "2",
 "periostat": "2",
 "proquin xr": "2",
 "prednisolone": "2",
 "prednicot": "2",
 "pepto children's": "2",
 "probenecid and colchicine": "1",
 "panmycin": "2",
 "propoxyphene compound 65": "1",
 "prevacid naprapac": "1",
 "potassium citrate": "2",
 "prelone": "2",
 "phillips' haleys m-o": "2",
 "pepcid complete": "2",
 "predate-50": "2",
 "prasugrel": "3",
 "pentobarbital": "2",
 "prevpac": "1",
 "prosed ds": "1",
 "protuss tablet": "1",
 "pedia-lax enema": "3",
 "paxil": "2",
 "percodan": "1",
 "phosphate laxative": "3",
 "phenytek": "2",
 "potassium citrate/sodium citrate": "2",
 "pb-hyos": "2",
 "pondimin": "2",
 "pralatrexate": "2",
 "predicort rp": "2",
 "primethasone": "2",
 "propranolol": "1",
 "prevacid naprapac 500": "1",
 "posture-d h/p": "2",
 "percodan-demi": "1",
 "pristiq": "2",
 "prednicen-m": "2",
 "polycitra-k": "2",
 "primatene dual action": "2",
 "posicor": "1",
 "potassium bicarbonate/sodium bicarbonate": "2",
 "prevalite": "1",
 "pc-cap": "1",
 "peganone": "2",
 "prevacid otc": "1",
 "polygam s/d": "3",
 "pemetrexed": "2",
 "penbutolol": "1",
 "phenytoin sodium, prompt": "2",
 "protonix": "1",
 "previfem": "1",
 "phenaz plus": "2",
 "pharmacia carbosorb": "2",
 "p-a-c analgesic": "1",
 "pamidronate": "2",
 "pexeva": "2",
 "prodrox": "2",
 "potassium iodide/theophylline": "2",
 "privigen": "3",
 "prilosec": "1",
 "proben-c": "1",
 "pro-banthine": "1",
 "propantheline": "1",
 "pri-cortin 50": "2",
 "persantine": "2",
 "pcm-la": "1",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "persantine iv": "2",
 "prandimet": "2",
 "potassium bicarbonate/potassium citrate": "2",
 "phosenamine": "1",
 "prozac": "2",
 "prinivil": "2",
 "prinzide": "2",
 "p-a-c": "1",
 "penetrex": "2",
 "predaject-50": "2",
 "prevacid 24hr": "1",
 "phenazoforte plus": "2",
 "predacorten": "2",
 "phenytoin": "2",
 "pannaz": "1",
 "penicillamine": "2",
 "pimozide": "2",
 "prevacid": "1",
 "perindopril": "2",
 "probenecid": "1",
 "pseudo cm tr": "1",
 "paricalcitol": "2",
 "phrenilin": "2",
 "predalone 50": "2",
 "panglobulin nf": "3",
 "philith": "1",
 "potassium acetate/potassium bicarbonate/potassium citrate": "2",
 "procyclidine": "1",
 "panasal 5/500": "1",
 "pamine forte": "1",
 "pediapred": "2",
 "plendil": "2",
 "paroxetine": "2",
 "polycitra-lc": "2",
 "pamine fq": "1",
 "pcm allergy": "1",
 "phenobarbital": "2",
 "primidone": "2",
 "paxil cr": "2",
 "prosed ec": "1",
 "pedia-lax chewable tablets": "2",
 "pamine": "1",
 "prandin": "2",
 "pseudox m": "1",
 "pred-ject-50": "2",
 "promacta": "2",
 "prozac weekly": "2",
 "painaid": "1",
 "pannaz s": "1",
 "polycitra": "2",
 "portia": "1",
 "prednisone": "2",
 "potassium bitartrate/sodium bicarbonate": "2",
 "prominol": "2",
 "pylera": "2",
 "prilosec otc": "1",
 "proquad": "2",
 "prevacid iv": "1",
 "pentothal": "2",
 "pamprin max menstrual pain relief": "1",
 "pravigard pac": "1",
 "prehist d": "1",
 "prostep": "1",
 "procalamine": "2",
 "panglobulin": "3",
 "poly-citra k crystals": "2",
 "phillips' milk of magnesia": "2"}, "s": {"sronyx": "1",
 "saleto": "1",
 "solurex": "2",
 "sertraline": "2",
 "syprine": "2",
 "sulfazine": "2",
 "surpass": "2",
 "streptokinase": "2",
 "slo-phyllin": "2",
 "symax fastab": "1",
 "sibutramine": "2",
 "sulfamag": "2",
 "sloprin": "1",
 "sympak pdx": "1",
 "sprintec": "1",
 "streptase": "2",
 "sodium lactate": "2",
 "sodium citrate": "2",
 "st. joseph aspirin": "1",
 "scopace": "1",
 "stavzor": "2",
 "sympak dm": "1",
 "scot-tussin original": "2",
 "sotalol hydrochloride af": "1",
 "selestoject": "2",
 "stanback fast pain relief": "1",
 "seasonale": "1",
 "st. joseph 81 mg chewable aspirin": "1",
 "starlix": "2",
 "sal-tropine": "1",
 "solodyn": "2",
 "sympak ii": "1",
 "sandimmune": "2",
 "slow-mag": "2",
 "symax duotab": "1",
 "super calcium": "2",
 "solu-cortef": "2",
 "selfemra": "2",
 "sandoglobulin": "3",
 "st. joseph 81 mg aspirin enteric safety-coated": "1",
 "safyral": "2",
 "solu-phyllin gg": "2",
 "sparfloxacin": "2",
 "slo-phyllin 80": "2",
 "seconal sodium": "2",
 "sanctura": "1",
 "solifenacin": "1",
 "sodium iodide i-123": "2",
 "ser-ap-es": "2",
 "synalgos-dc": "1",
 "simcor": "1",
 "sustiva": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "sanctura xr": "1",
 "savella": "2",
 "supac": "1",
 "sprix": "3",
 "suprep": "2",
 "scopolamine": "1",
 "surpass extra strength": "2",
 "scopohist-pe": "1",
 "sympak": "1",
 "slo-phyllin 125": "2",
 "sarafem": "2",
 "sulfinpyrazone": "2",
 "sunmark acid reducer maximum strength": "1",
 "solurex la": "2",
 "scopohist syrup": "1",
 "sodium bicarbonate/tartaric acid": "2",
 "spastrin": "2",
 "soma compound with codeine": "1",
 "slo-phyllin gg": "2",
 "sterapred ds": "2",
 "serathide": "2",
 "salofalk": "2",
 "solu-medrol": "2",
 "spasdel": "1",
 "sodium edecrin": "1",
 "slo-niacin": "1",
 "sedapap": "2",
 "sodium salicylate": "1",
 "soma compound": "1",
 "suprep bowel prep kit": "2",
 "stahist": "1",
 "stanback analgesic": "1",
 "serax": "1",
 "seasonique": "1",
 "sulfasalazine": "2",
 "solia": "1",
 "spironolactone": "1",
 "serpex": "2",
 "sular": "2",
 "sterapred": "2",
 "symax sr": "1",
 "sedecal d": "2",
 "sgard": "1",
 "slo-bid gyrocaps": "2",
 "septopal": "2",
 "sprycel": "3",
 "seconal": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "symax sl": "1",
 "sumycin 250": "2",
 "saphris": "2",
 "spasmolin": "2",
 "sirolimus": "3",
 "serpazide": "2",
 "symbyax": "2",
 "spasquid": "2",
 "sumycin": "2",
 "scopohist": "1",
 "skelid": "2",
 "sodium polystyrene sulfonate": "2",
 "sotalol": "1",
 "sorine": "1",
 "servira": "2",
 "sodium acetate": "2",
 "sodium bicarbonate": "2",
 "sudatrate": "1",
 "syeda": "2",
 "sodium bicarbonate/sodium citrate": "2",
 "sectral": "1",
 "sodium iodide-i-131": "2",
 "sinodec": "1",
 "streptomycin": "2",
 "seconal sodium pulvules": "2"}, "r": {"rhinaclear": "1",
 "ri-mag": "2",
 "relcof pse": "1",
 "re-drylex": "1",
 "rowasa sulfite free": "2",
 "repaglinide": "2",
 "ron-acid plus": "2",
 "reclipsen": "1",
 "riopan plus": "2",
 "renacidin irrgiation": "2",
 "retavase": "2",
 "rolaids extra strength softchews": "2",
 "retavase half-kit": "2",
 "rolaids extra strength plus gas relief softchews": "2",
 "relcof pe": "1",
 "rifampin": "1",
 "riluzole": "1",
 "rolaids regular strength": "2",
 "robitet 500": "2",
 "requip": "2",
 "risacal-d": "2",
 "ranitidine": "1",
 "regurin": "1",
 "riopan plus 2": "2",
 "ron acid": "2",
 "redur-pcm": "1",
 "risedronate": "2",
 "requip follow on pack": "2",
 "rheumatrex dose pack": "3",
 "relion/novolin r": "2",
 "relcof dn pe": "1",
 "raxar": "2",
 "requip starter pack": "2",
 "reclast": "2",
 "respigam": "3",
 "requip starter kit": "2",
 "rifater": "2",
 "renacidin": "2",
 "ropinirole": "2",
 "relion novolin n": "2",
 "rifamate": "2",
 "rulox 1": "2",
 "ralix": "1",
 "rifadin iv": "1",
 "rifadin": "1",
 "rapamune": "3",
 "relcof cpm": "1",
 "robinul forte": "1",
 "robaxisal": "1",
 "respiratory syncytial virus immune globulin": "3",
 "relion novolin 70/30 innolet": "2",
 "rabeprazole": "1",
 "riopan": "2",
 "rilutek": "1",
 "relcof dn pse": "1",
 "retrovir": "1",
 "refludan": "2",
 "rocaltrol": "2",
 "requip xl": "2",
 "re-drylex jr": "1",
 "ramipril": "2",
 "ru-tuss": "1",
 "regadenoson": "2",
 "roxiprin": "1",
 "reopro": "2",
 "remodulin": "2",
 "rowasa": "2",
 "ranitidine bismuth citrate": "1",
 "rolaids extra strength": "2",
 "respa-ar": "1",
 "rivaroxaban": "2",
 "rhinolar": "1",
 "respivent df": "1",
 "rescon": "1",
 "revia": "2",
 "rulox plus": "2",
 "rimactane": "1",
 "rolatuss-sr": "1",
 "relion/novolin 70/30": "2",
 "rebif": "2",
 "respbid": "2",
 "ryneze": "1",
 "reteplase": "2",
 "riopan plus double strength": "2",
 "repreve": "2",
 "rhinocaps": "1",
 "ropivacaine/sufentanil": "1",
 "ropivacaine": "1",
 "respivent-d": "1",
 "rolaids multi-symptom": "2",
 "rasagiline": "2",
 "rulox": "2",
 "re-pb hyos elixir": "2",
 "repan": "2",
 "rapiflux": "2",
 "reyataz": "1",
 "redux": "2",
 "robinul": "1"}, "u": {"uretron": "1",
 "urimax": "1",
 "ursinus": "1",
 "urocit-k": "2",
 "utira": "1",
 "utrona-c": "1",
 "utrona": "1",
 "ultra mylanta calci tabs": "2",
 "upcal d": "2",
 "urised": "1",
 "uro blue": "1",
 "urban ds": "2",
 "uni-dur": "2",
 "uni-lan ii": "2",
 "uro-mag": "2",
 "urimar-t": "1",
 "urotrol": "1",
 "uretron ds": "1",
 "uritact ds": "1",
 "univasc": "2",
 "urisedamine": "1",
 "urban": "2",
 "uni-lan": "2",
 "urobiotic-250": "2",
 "u-tri-lone": "2",
 "urapine": "1",
 "uni serp": "2",
 "uritin": "1",
 "urelief plus": "2",
 "uta": "1",
 "usept": "1",
 "urispas": "1",
 "uni bronchial": "2",
 "urisym": "1",
 "urogesic blue": "3",
 "unipres": "2",
 "uracil": "2",
 "uritact-ec": "1",
 "uniphyl": "2",
 "urokinase": "2",
 "uticap": "1",
 "ustell": "1",
 "urelle": "1",
 "utira-c": "1",
 "uro-phosphate": "3",
 "uribel": "1",
 "uniretic": "2"}, "t": {"theolair-sr": "2",
 "terramycin": "2",
 "ticlid": "2",
 "toprol-xl": "1",
 "telmisartan": "2",
 "thiopental": "2",
 "trizivir": "1",
 "tizanidine": "3",
 "trusopt": "3",
 "theocon": "2",
 "tencet": "2",
 "theomax df": "2",
 "tricitrasol": "2",
 "titralac plus liquid": "2",
 "tetracap": "2",
 "theo-dur": "2",
 "tobi": "2",
 "tri-sprintec": "1",
 "tri-k": "2",
 "tol-tab": "2",
 "titralac plus": "2",
 "tekamlo": "2",
 "tricitrates": "2",
 "tobramycin": "2",
 "ticagrelor": "2",
 "telbivudine": "2",
 "terramycin im": "2",
 "theoclear-80": "2",
 "trihexyphenidyl": "1",
 "trivaris": "2",
 "trospium": "1",
 "teveten hct": "2",
 "tenormin": "1",
 "trihexane": "1",
 "tussirex sugar free": "2",
 "treprostinil": "2",
 "tegretol": "2",
 "trinessa lo": "1",
 "theophylline ki": "2",
 "toradol im": "3",
 "tetracon": "2",
 "trandolapril/verapamil": "2",
 "triphasil-28": "1",
 "triphasil-21": "1",
 "tenoretic": "1",
 "trilog": "2",
 "toradol": "3",
 "tums freshers": "2",
 "theoclear la-260": "2",
 "theolate": "2",
 "trientine": "2",
 "thioguanine": "2",
 "trandate": "1",
 "tositumomab": "3",
 "tri-hydroserpine": "2",
 "torsemide": "1",
 "teveten": "2",
 "tums dual action": "2",
 "tabloid": "2",
 "ticlopidine": "2",
 "theo g": "2",
 "theo-dur sprinkles": "2",
 "tolterodine": "1",
 "tums extra strength 750": "2",
 "tenoretic 50": "1",
 "tri-norinyl": "1",
 "toradol iv/im": "3",
 "travasol with electrolytes dual chamber": "2",
 "tussirex": "2",
 "tolbutamide": "2",
 "trivora-28": "1",
 "tiazac": "1",
 "tempo": "2",
 "theodrine": "2",
 "tofranil-pm": "2",
 "theovent": "2",
 "tirofiban": "2",
 "tolinase": "2",
 "truvada": "3",
 "timolide": "1",
 "twin-k": "2",
 "trivora": "1",
 "tyvaso": "2",
 "tnkase": "2",
 "treanda": "2",
 "tiludronate": "2",
 "triesence": "2",
 "tri-buffered aspirin": "1",
 "triamonide 40": "2",
 "talwin compound": "1",
 "therapy bayer": "1",
 "theo-24": "2",
 "theolair": "2",
 "timolol": "1",
 "tyzeka": "2",
 "theobid": "2",
 "tromethamine": "2",
 "tri-previfem": "1",
 "tristoject": "2",
 "tequin": "2",
 "tramacort-d": "2",
 "trandolapril": "2",
 "tenecteplase": "2",
 "titralac": "2",
 "tenoretic 100": "1",
 "triphasil": "1",
 "transderm-scop": "1",
 "tri-legest fe": "1",
 "triquilar 28": "1",
 "triamcinolone ophthalmic": "2",
 "triquilar 21": "1",
 "t-phyl": "2",
 "tenofovir": "3",
 "theoclear la-130": "2",
 "trilone": "2",
 "teczem": "2",
 "tagamet": "1",
 "tuinal": "2",
 "trac tabs 2x": "1",
 "trovan": "2",
 "theo-time": "2",
 "timolide 10-25": "1",
 "tedrigen": "2",
 "tija": "2",
 "tham": "2",
 "theophyll-gg": "2",
 "tinzaparin": "2",
 "triam-forte": "2",
 "tequin teqpaq": "2",
 "tencon": "2",
 "tums plus": "2",
 "tums ultra 1000": "2",
 "triamcot": "2",
 "triam-a": "2",
 "theocap": "2",
 "travasol with electrolytes": "2",
 "taladine": "1",
 "tri-lo-sprintec": "1",
 "tenake": "2",
 "tofranil": "2",
 "triaprin": "2",
 "theophylline": "2",
 "trovafloxacin": "2",
 "tarka": "2",
 "tums regular strength": "2",
 "tilia fe": "1",
 "theo-x": "2",
 "topotecan": "1",
 "trinessa": "1",
 "tolazamide": "2",
 "tussigon": "1",
 "truxophyllin": "2",
 "tums kids": "2",
 "tritec": "1",
 "triall": "1",
 "tri-levlen": "1",
 "taztia xt": "1",
 "thiabendazole": "2",
 "triamcinolone": "2",
 "tribenzor": "2",
 "time-hist qd": "1",
 "theochron": "2",
 "tetracycline": "2",
 "tri-legest": "1",
 "twynsta": "2",
 "theomar gg": "2",
 "triad": "2",
 "tums smoothies": "2",
 "trihexy": "1",
 "tac 3": "2",
 "tagamet hb": "1",
 "tegretol xr": "2",
 "tacrolimus": "3",
 "trexall": "3",
 "two-dyne": "2"}, "w": {"wellesse liquid calcium with vitamin d": "2",
 "wydase": "1",
 "warfarin": "2",
 "wellesse vitamin d3": "2",
 "we allergy": "1"}, "v": {"venoglobulin-s 10%": "3",
 "vitrase": "1",
 "videx": "2",
 "vascor": "2",
 "valsartan": "2",
 "varicella virus vaccine": "2",
 "victoza": "1",
 "vibra-tabs": "2",
 "verelan pm": "2",
 "vi-atro": "1",
 "vemurafenib": "2",
 "vasotec": "2",
 "vilazodone": "2",
 "visrx dose pack": "1",
 "vimovo": "1",
 "velivet": "1",
 "varivax": "2",
 "vestura": "2",
 "verelan": "2",
 "viread": "3",
 "valturna": "2",
 "verapamil": "2",
 "vitamin d2": "2",
 "vibramycin": "2",
 "vespro melatonin": "1",
 "veletri": "2",
 "venlafaxine": "2",
 "viibryd": "2",
 "velosulin br": "2",
 "valium": "1",
 "veripred 20": "2",
 "vitamin d3": "2",
 "vistide": "3",
 "vesicare": "1",
 "ventavis": "2",
 "valproic acid": "2",
 "vaseretic": "2",
 "videx ec": "2",
 "venoglobulin-s 5%": "3",
 "valrelease": "1",
 "vaseretic 10-25": "2",
 "visicol": "3",
 "vivitrol": "2",
 "vaseretic 5-12.5": "2",
 "visken": "1",
 "vanquish": "1"}, "y": {"ysp aspirin": "1",
 "y-90 zevalin": "3",
 "yasmin": "2",
 "yaz": "2"}, "x": {"xiral sr": "1",
 "xarelto": "2",
 "xigris": "3"}, "z": {"zagam respipac": "2",
 "zovia 1/50": "1",
 "zarah": "2",
 "zantac 25 mg efferdose": "1",
 "zoledronic acid": "2",
 "zantac 300": "1",
 "zema pak": "2",
 "zantac efferdose": "1",
 "zantac": "1",
 "zelboraf": "2",
 "zeosa": "1",
 "zero-order release": "1",
 "zebeta": "1",
 "zovia 1/35": "1",
 "zantac geldose": "1",
 "zorprin": "1",
 "zegerid otc": "2",
 "zantac 75": "1",
 "zebutal": "2",
 "zometa": "2",
 "zevalin": "3",
 "zagam": "2",
 "zaponex": "1",
 "zestoretic": "2",
 "zenchent fe": "1",
 "zanaflex": "3",
 "zantac 150 efferdose": "1",
 "zenchent": "1",
 "zegerid": "1",
 "zantac 150": "1",
 "zoloft": "2",
 "zidovudine": "1",
 "zestril": "2",
 "zantac 300 geldose": "1",
 "zemplar": "2",
 "zetran": "1",
 "ziac": "1",
 "zovia": "1"}}];