interactions["acetaminophen-salicylamide,frenadol"]=["acetaminophen-salicylamide,frenadol", {"a": {"anaspaz": "1",
 "aspirin/hydrocodone": "2",
 "anacin": "2",
 "aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "aspergum": "2",
 "aristocort": "2",
 "atacand hct": "2",
 "allerx pe": "1",
 "aspirtab": "2",
 "accuhist la": "1",
 "amdry-d": "1",
 "ascriptin enteric": "2",
 "apidra solostar": "2",
 "alendronate/cholecalciferol": "2",
 "akineton": "1",
 "amdry-c": "1",
 "argatroban": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/scopolamine": "1",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "antispas": "2",
 "amethia": "1",
 "aspir-low": "2",
 "aldactone": "1",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "actidose-aqua": "2",
 "aspirin/oxycodone": "2",
 "amytal sodium": "2",
 "aspir-mox": "2",
 "accesspak for hiv pep expanded with kaletra": "3",
 "amylase/cellulase/hyoscyamine/lipase/phenyltoloxamine/protease": "1",
 "aspiritab": "2",
 "ah-chew ultra tannate": "1",
 "aspirin/caffeine/orphenadrine": "2",
 "aspirin/phenyltoloxamine": "2",
 "ah-chew": "1",
 "amlodipine/telmisartan": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "activated charcoal": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "amethyst": "1",
 "alor 5/500": "2",
 "alka-seltzer plus flu formula": "2",
 "arthritis pain formula": "2",
 "acetohexamide": "2",
 "aspirin buffered": "2",
 "alimta": "2",
 "alyacen 7/7/7": "1",
 "aranelle": "1",
 "anturol": "1",
 "amlobenz": "2",
 "aspirin/pravastatin": "2",
 "alesse-21": "1",
 "arthritis pain": "2",
 "aspirin/methocarbamol": "2",
 "asacol": "2",
 "atropine/diphenoxylate": "1",
 "alesse-28": "1",
 "aspirin/pentazocine": "2",
 "atacand": "2",
 "acetaminophen/aspirin": "2",
 "a-hydrocort": "2",
 "accuretic": "2",
 "acetaminophen/butalbital": "2",
 "angiomax": "2",
 "amikacin": "2",
 "allergy dn ii": "1",
 "a-spaz": "1",
 "atrohist plus": "1",
 "azmacort": "2",
 "aerokid": "1",
 "avonex prefilled syringe": "2",
 "aspirin/caffeine": "2",
 "aristopak": "2",
 "accesspak for hiv pep expanded with viracept": "3",
 "aspir 81": "2",
 "ah-chew ii": "1",
 "arava": "3",
 "alcohol": "3",
 "aliskiren/valsartan": "2",
 "acetaminophen/aspirin/caffeine": "2",
 "allergy dn pe": "1",
 "atropine/difenoxin": "1",
 "adrenocot": "2",
 "azulfidine": "2",
 "adlone-40": "2",
 "adult strength": "2",
 "atropine/pralidoxime": "1",
 "anturane": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "accupril": "2",
 "apresoline": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "amikin": "2",
 "anoquan": "2",
 "avandaryl": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "avapro": "2",
 "arcet": "2",
 "a-methapred": "2",
 "acetocot": "2",
 "alka-seltzer wake-up call!": "2",
 "aggrenox": "2",
 "alkabel-sr": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "actidose with sorbitol": "2",
 "amobarbital": "2",
 "alagesic": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "alka-seltzer original": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "aspirin/meprobamate": "2",
 "ascriptin maximum strength": "2",
 "aceon": "2",
 "aerohist plus": "1",
 "avalide": "2",
 "alka-seltzer lemon-lime": "2",
 "acetylsalicylic acid": "2",
 "aspirin/butalbital/caffeine": "2",
 "aspircaf": "2",
 "amlodipine/benazepril": "2",
 "anisindione": "2",
 "atropine/chlorpheniramine/hyoscyamine/pseudoephedrine/scopolamine": "1",
 "a-spas s/l": "1",
 "aspirin/caffeine/dihydrocodeine": "2",
 "anacin advanced headache formula": "2",
 "allerx dose pack": "1",
 "amobarbital/secobarbital": "2",
 "angeliq": "2",
 "actonel with calcium": "2",
 "alyacen 1/35": "1",
 "aspir-mox ib": "2",
 "atropine/edrophonium": "1",
 "altavera": "1",
 "alka-seltzer plus cold formula": "2",
 "antispasmodic": "2",
 "alka-seltzer pm": "2",
 "aspirin/diphenhydramine": "2",
 "actidose-aqua advance": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "altace": "2",
 "artane": "1",
 "antrocol": "2",
 "anacin max strength": "2",
 "atelvia": "2",
 "asacol hd": "2",
 "aspirin": "2",
 "actidose plus sorbitol": "2",
 "ancobon": "2",
 "adlone-80": "2",
 "aclasta": "2",
 "aspirin/calcium carbonate": "2",
 "allerx pe dose pack": "1",
 "atreza": "1",
 "aristospan": "2",
 "apidra": "2",
 "alcohol and dextrose injections usp hypertonic": "3",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/phenylpropanolamine/scopolamine": "1",
 "axocet": "2",
 "aspirin/dipyridamole": "2",
 "acuprin 81": "2",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "azor": "2",
 "atrosept": "1",
 "allergy dn": "1",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "azdone": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "adbeon": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "amikin pediatric": "2",
 "ampicillin/probenecid": "1",
 "aspirin/carisoprodol/codeine": "2",
 "allerx df dose pack": "1",
 "aerohist": "1",
 "aspirin/pseudoephedrine": "2",
 "acetaminophen/aspirin/phenylpropanolamine": "2",
 "aspirin/caffeine/salicylamide": "2",
 "atripla": "3",
 "asthmacon": "2",
 "aristocort for injection": "2",
 "alendronate": "2",
 "apri": "1",
 "aspirin/carisoprodol": "2",
 "avonex": "2",
 "ardeparin": "2",
 "active carbon": "2",
 "allepak": "1",
 "ah-chew ultra": "1",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "alagesic lq": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "atropine/phenobarbital": "2",
 "adrenocot la": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "apresazide": "2",
 "adefovir": "3",
 "alesse": "1",
 "atropine": "1",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "amlodipine/olmesartan": "2",
 "azilsartan medoxomil": "2",
 "atnaa": "1",
 "aredia": "2",
 "aspirin lite coat": "2",
 "aspirin/butalbital": "2",
 "amethia lo": "1",
 "ascriptin": "2",
 "accesspak for hiv pep basic": "3",
 "aspirin/codeine": "2",
 "alka-seltzer extra strength": "2",
 "akineton hcl": "1",
 "acova": "2",
 "allergy am-pm dose pack": "1",
 "aspirin low strength": "2",
 "abacavir/lamivudine/zidovudine": "1",
 "allerx df": "1",
 "alcohol 5% in dextrose 5%": "3",
 "amlodipine/valsartan": "2",
 "allerx-d": "1",
 "atropen": "1",
 "aldactazide": "1",
 "apriso": "2",
 "actonel": "2",
 "arthritis foundation pain reliever": "2",
 "azulfidine en-tabs": "2",
 "americet": "2",
 "aviane": "1",
 "anolor 300": "2",
 "azurette": "1",
 "amaryl": "2"}, "c": {"cvs extra strength headache relief": "2",
 "calcium carbonate/risedronate": "2",
 "cozaar": "2",
 "cerebyx": "2",
 "cystospaz-m": "1",
 "cardoxin": "2",
 "carbosorb x": "2",
 "capozide 50/25": "2",
 "charcoaid 2000": "2",
 "clexane forte": "2",
 "coryza-d": "1",
 "chem mart nasal decongestant capsule": "2",
 "cholestyramine": "1",
 "charcoal/simethicone": "2",
 "charcoaid-g": "2",
 "cpm-pe-msc": "1",
 "cogentin": "1",
 "cortisone": "2",
 "clexane": "2",
 "canasa": "2",
 "capoten": "2",
 "corlopam": "1",
 "cyclafem 1/35": "1",
 "charcotabs": "2",
 "cort-k": "2",
 "celestone phosphate": "2",
 "cyclosporine": "2",
 "chlor-mes d": "1",
 "combivir": "1",
 "cotolone": "2",
 "colchicine/probenecid": "1",
 "carisoprodol compound": "2",
 "charcoaid": "2",
 "carimune nf": "3",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "1",
 "celestone": "2",
 "careone acid reducer": "1",
 "cortenema": "2",
 "clofarabine": "2",
 "char-flo with sorbitol": "2",
 "charcotrace": "2",
 "chlordinium": "1",
 "chlorpheniramine/methscopolamine/phenylpropanolamine": "1",
 "cortifoam": "2",
 "canasa pac": "2",
 "candesartan/hydrochlorothiazide": "2",
 "candesartan": "2",
 "complera": "3",
 "cyclessa": "1",
 "capacet": "2",
 "charcocaps": "2",
 "cell-u-jec": "2",
 "clidinium": "1",
 "cafatine pb": "2",
 "chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "1",
 "chlordiazepoxide/methscopolamine": "1",
 "colidrops": "1",
 "cyclafem 7/7/7": "1",
 "chlorpropamide": "2",
 "chlor-mes": "1",
 "cystex": "1",
 "cytogam": "3",
 "cortone acetate": "2",
 "cantil": "1",
 "capozide 25/15": "2",
 "carimune": "3",
 "charcoal": "2",
 "chlorpheniramine/methscopolamine": "1",
 "carbomix": "2",
 "clinalog": "2",
 "carbamazepine": "2",
 "cidomycin": "2",
 "clinacort": "2",
 "capozide 50/15": "2",
 "cesia": "1",
 "coldamine": "1",
 "caziant": "1",
 "chlorpheniramine/dextromethorphan/guaifenesin/methscopolamine/phenylephrine": "1",
 "cidofovir": "3",
 "chlorpheniramine/methscopolamine/phenylephrine": "1",
 "charcodote": "2",
 "cuvposa": "1",
 "clolar": "2",
 "celestone soluspan": "2",
 "charcoal/sorbitol": "2",
 "cephadyn": "2",
 "carbatrol": "2",
 "captopril/hydrochlorothiazide": "2",
 "cystemms-v": "1",
 "cimetidine": "1",
 "captopril": "2",
 "chlordiazepoxide/clidinium": "1",
 "cholestyramine light": "1",
 "cellulase/hyoscyamine/pancrelipase/phenyltoloxamine": "1",
 "cope": "2",
 "chlorpheniramine/methscopolamine/pseudoephedrine": "1",
 "colocort": "2",
 "cryselle": "1",
 "cytomegalovirus immune globulin": "3",
 "camreselo": "1",
 "colazal": "2",
 "charcoal plus ds": "2",
 "chlorpheniramine/dextromethorphan/methscopolamine": "1",
 "chardonna-2": "2",
 "chlorpheniramine/guaifenesin/methscopolamine/phenylephrine": "1",
 "cystospaz": "1",
 "camrese": "1",
 "clindex": "1",
 "capozide": "2",
 "capozide 25/25": "2",
 "cortef": "2",
 "carbinoxamine/methscopolamine/pseudoephedrine": "1",
 "coumadin": "2"}, "b": {"bellaphen-s": "2",
 "balsalazide": "2",
 "butisol sodium": "2",
 "briellyn": "1",
 "brompheniramine/chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "1",
 "busulfex": "2",
 "brevital sodium": "2",
 "bufferin": "2",
 "bayer pm": "2",
 "bayer aspirin extra strength plus": "2",
 "b c powder arthritis strength": "2",
 "benicar hct": "2",
 "bemote": "1",
 "bel-phen-ergot": "2",
 "bayer women's aspirin with calcium": "2",
 "buffasal": "2",
 "butabarbital": "2",
 "belladonna tincture": "1",
 "berkley and jensen acid reducer maximum strength": "1",
 "belladonna/butabarbital": "2",
 "bayer children's aspirin": "2",
 "bumex": "1",
 "b c powder": "2",
 "bayer extra strength back &amp; body": "2",
 "beta-phos/ac": "2",
 "bayer aspirin": "2",
 "buffered aspirin": "2",
 "beyaz": "2",
 "baraclude": "2",
 "botulism immune globulin": "3",
 "betaseron": "2",
 "bidil": "2",
 "bicarsim": "2",
 "bentyl": "1",
 "bellaspas": "2",
 "black cohosh": "2",
 "betamethasone": "2",
 "benemid": "1",
 "boniva": "2",
 "butex forte": "2",
 "bivalirudin": "2",
 "bicarsim forte": "2",
 "baycadron": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bellamine": "2",
 "bufferin low dose": "2",
 "bel-tabs": "2",
 "belladonna": "1",
 "belladonna/opium": "1",
 "babybig": "3",
 "bayer advanced aspirin": "2",
 "balziva": "1",
 "bayer am": "2",
 "bc headache": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "busulfan": "2",
 "bayer aspirin with heart advantage": "2",
 "budesonide/formoterol": "2",
 "b &amp; o supprettes": "1",
 "butalbital": "2",
 "biperiden": "1",
 "bayer aspirin regimen": "2",
 "bellergal-s": "2",
 "bellalphen": "2",
 "byclomine": "1",
 "bellamine s": "2",
 "bellatal er": "2",
 "benztropine": "1",
 "belladonna/ergotamine/phenobarbital": "2",
 "bayer women's low dose plus calcium": "2",
 "benazepril/hydrochlorothiazide": "2",
 "benzoic acid/methenamine/sodium salicylate": "1",
 "bupap": "2",
 "belcomp-pb": "2",
 "bufferin extra strength": "2",
 "brevicon": "1",
 "butalbital compound": "2",
 "bumetanide": "1",
 "buffex": "2",
 "budesonide": "2",
 "benazepril": "2",
 "bellamor": "2",
 "bellahist-d la": "1",
 "bufferin arthritis strength": "2",
 "bc fast pain relief": "2",
 "busodium": "2",
 "benicar": "2",
 "butibel": "2",
 "barbidonna": "2",
 "bellatal": "2",
 "bucet": "2",
 "bubbli-pred": "2"}, "e": {"eplerenone": "2",
 "ecotrin maximum strength": "2",
 "effervescent pain relief": "2",
 "embeda": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "eprosartan": "2",
 "endodan": "2",
 "emagrin": "2",
 "ethinyl estradiol/etonogestrel": "1",
 "excedrin menstrual complete": "2",
 "entaprin": "2",
 "ethinyl estradiol/levonorgestrel": "1",
 "exforge hct": "2",
 "extendryl pse": "1",
 "enoxaparin": "2",
 "extendryl dm": "1",
 "extendryl": "1",
 "ergocomp-pb": "2",
 "edarbi": "2",
 "esgic": "2",
 "ecotrin adult low strength": "2",
 "ethinyl estradiol": "1",
 "ed-spaz": "1",
 "easprin": "2",
 "elixiral": "2",
 "edecrin": "1",
 "ethinyl estradiol/ethynodiol": "1",
 "estinyl": "1",
 "edarbyclor": "2",
 "eloxatin": "2",
 "excedrin migraine": "2",
 "enalapril/felodipine": "2",
 "ethinyl estradiol/norgestrel": "1",
 "ecpirin": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "ethacrynic acid": "1",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ethinyl estradiol/norethindrone": "1",
 "equaline heartburn relief": "1",
 "entecavir": "2",
 "ethanol": "3",
 "e-caff p-b": "2",
 "equetro": "2",
 "enpresse": "1",
 "equaline acid reducer": "1",
 "endolor": "2",
 "epitol": "2",
 "ergocaf-pb": "2",
 "extendryl seniors": "1",
 "efavirenz": "2",
 "enlon-plus": "1",
 "ecotrin": "2",
 "ethyl alcohol": "3",
 "emtricitabine/rilpivirine/tenofovir": "3",
 "extendryl pem": "1",
 "emtricitabine/nelfinavir/tenofovir": "3",
 "extendryl sr": "1",
 "extendryl jr": "1",
 "entocort ec": "2",
 "excedrin back &amp; body": "2",
 "ex-tuss": "1",
 "ethinyl estradiol/norgestimate": "1",
 "entercote": "2",
 "etidronate": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "3",
 "ezchar": "2",
 "empirin with codeine": "2",
 "emtricitabine/tenofovir": "3",
 "estrostep fe": "1",
 "enalapril": "2",
 "equagesic": "2",
 "enablex": "1",
 "exforge": "2",
 "exjade": "3",
 "excedrin extra strength": "2",
 "emoquette": "1",
 "ethotoin": "2",
 "esgic-plus": "2",
 "ethinyl estradiol/norelgestromin": "1",
 "ex-histine": "1",
 "efavirenz/emtricitabine/tenofovir": "3",
 "eperbel-s": "2",
 "extra strength bayer": "2",
 "extavia": "2",
 "ezol": "2",
 "empirin": "2",
 "ergocaffpb": "2",
 "exubera": "2",
 "excedrin": "2",
 "extendryl chews": "1",
 "eucarbon": "2"}, "d": {"diovan": "2",
 "depakote sprinkles": "2",
 "duradryl chewable": "1",
 "demadex": "1",
 "detrol": "1",
 "deconhist la": "1",
 "duetact": "2",
 "durahist pe": "1",
 "dep medalone 80": "2",
 "diovan hct": "2",
 "dolsed": "1",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "drize": "1",
 "dehydrated alcohol": "3",
 "demulen 1/50": "1",
 "donnatal extentabs": "2",
 "desogestrel/ethinyl estradiol": "1",
 "dolgic plus": "2",
 "divalproex sodium": "2",
 "duodote": "1",
 "ditropan": "1",
 "depmedalone": "2",
 "da ii": "1",
 "di-spaz": "1",
 "dilomine": "1",
 "dalteparin": "2",
 "ditropan xl": "1",
 "decadron with xylocaine": "2",
 "drospirenone/estradiol": "2",
 "depakote er": "2",
 "dolgic": "2",
 "dabigatran": "2",
 "dexamethasone/lidocaine": "2",
 "dolmar": "2",
 "darvon compound 32": "2",
 "dalalone la": "2",
 "depakene": "2",
 "dehistine": "1",
 "delta-lutin": "2",
 "damason-p": "2",
 "duravent": "1",
 "dallergy pse": "1",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "1",
 "desogen": "1",
 "dicyclomine": "1",
 "dasetta 1/35": "1",
 "dexpak taperpak": "2",
 "dexacort phosphate in turbinaire": "2",
 "diuretic ap-es": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "darcalma": "1",
 "digitek": "2",
 "dexchlorpheniramine/methscopolamine/pseudoephedrine": "1",
 "darifenacin": "1",
 "diaqua-2": "1",
 "dymelor": "2",
 "deltasone": "2",
 "duradryl jr": "1",
 "dolobid": "1",
 "dexacort-la": "2",
 "dipentum": "2",
 "duralutin": "2",
 "dexamethasone": "2",
 "didronel": "2",
 "deprizine": "1",
 "dasetta": "1",
 "duragal-s": "2",
 "drymax": "1",
 "dalalone dp": "2",
 "dexodryl": "1",
 "dexasone": "2",
 "donnatal": "2",
 "deferasirox": "3",
 "dexone": "2",
 "darpaz": "1",
 "dexphen m": "1",
 "drihist": "1",
 "delta-cortef": "2",
 "duradryl": "1",
 "digex": "1",
 "d-hist d": "1",
 "demulen": "1",
 "depakote": "2",
 "donnamar": "1",
 "da chewable": "1",
 "dexasone la": "2",
 "duratan pe": "1",
 "diabinese": "2",
 "duradryl sr": "1",
 "dicumarol": "2",
 "darvon compound-65": "2",
 "drihist sr": "1",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "depacon": "2",
 "durahist d": "1",
 "depo-medrol": "2",
 "decadron": "2",
 "denaze": "1",
 "d-tal": "2",
 "de-sone la": "2",
 "dexacort phosphate in respihaler": "2",
 "duravent da": "1",
 "didronel iv": "2",
 "dexchlorpheniramine/methscopolamine/phenylephrine": "1",
 "depopred": "2",
 "dicyclocot": "1",
 "drospirenone/ethinyl estradiol": "2",
 "duralone": "2",
 "dexamethasone intensol": "2",
 "diabeta": "2",
 "decadron-la": "2",
 "digex nf": "1",
 "detrol la": "1",
 "dallergy er": "1",
 "drysec": "1",
 "dexacorten": "2",
 "demadex iv": "1",
 "dibent": "1",
 "danaparoid": "2",
 "dexacen-4": "2",
 "depade": "2",
 "digoxin": "2",
 "demulen 1/35": "1",
 "decaject la": "2",
 "durahist": "1",
 "dolgic lq": "2",
 "donnaphen": "2",
 "dexodryl suspension": "1",
 "dexone la": "2",
 "dalalone": "2",
 "dallergy pe": "1",
 "dilantin": "2",
 "dasetta 7/7/7": "1",
 "decaject": "2"}, "g": {"glyburide": "2",
 "gildess fe 1.5/30": "1",
 "gammar iv": "3",
 "goodys headache powders": "2",
 "glynase prestab": "2",
 "genprin": "2",
 "glycron": "2",
 "genace": "2",
 "glimepiride/rosiglitazone": "2",
 "genora 0.5/35": "1",
 "generess fe": "1",
 "gastrinex": "1",
 "glipizide": "2",
 "goody's body pain": "2",
 "gengraf": "2",
 "goody's extra-strength headache powders": "2",
 "glycopyrrolate": "1",
 "glipizide xl": "2",
 "geone": "2",
 "g-1": "2",
 "gamimune n 10%": "3",
 "gennin-fc": "2",
 "gianvi": "2",
 "glipizide/metformin": "2",
 "gamimune": "3",
 "giazo": "2",
 "gammaplex": "3",
 "gammar-p i.v.": "3",
 "gamunex-c": "3",
 "gildess fe 1/20": "1",
 "genacote": "2",
 "goodys extra strength": "2",
 "gleevec": "2",
 "glynase": "2",
 "glucotrol": "2",
 "genasan": "2",
 "glucotrol xl": "2",
 "gastrosed": "1",
 "gammagard s/d": "3",
 "gelnique": "1",
 "gamimune n 5%": "3",
 "genora 1/35": "1",
 "genora 1/50": "1",
 "gentamicin": "2",
 "glimepiride": "2",
 "glucovance": "2",
 "glyburide/metformin": "2",
 "garamycin": "2",
 "gamunex": "3",
 "gammagard": "3",
 "glimepiride/pioglitazone": "2"}, "f": {"fiortal": "2",
 "furosemide": "1",
 "flucytosine": "2",
 "fiorinal with codeine iii": "2",
 "folex pfs": "2",
 "flatulex": "2",
 "fiorinal with codeine": "2",
 "fortabs": "2",
 "florinef acetate": "2",
 "fiorinal": "2",
 "fioricet with codeine": "2",
 "fasprin": "2",
 "fenoldopam": "1",
 "femcet": "2",
 "fosinopril": "2",
 "femhrt": "1",
 "florinef": "2",
 "fragmin": "2",
 "flavoxate": "1",
 "fiv-asa": "2",
 "flebogamma": "3",
 "fosphenytoin": "2",
 "fosamax": "2",
 "flo-pred": "2",
 "flumist": "3",
 "fludrocortisone": "2",
 "fosamax plus d": "2",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiormor": "2",
 "farbital": "2",
 "fiortal with codeine": "2",
 "femcon fe": "1",
 "fosinopril/hydrochlorothiazide": "2",
 "fiorpap": "2"}, "i": {"iletin ii lente pork": "2",
 "influenza virus vaccine, h1n1, live": "3",
 "innopran xl": "1",
 "irbesartan": "2",
 "insulin inhalation, rapid acting": "2",
 "insulin pork mix": "2",
 "insulin regular": "2",
 "iletin lente": "2",
 "insulin lispro": "2",
 "innohep": "2",
 "insulin zinc extended": "2",
 "insulin isophane": "2",
 "inderal la": "1",
 "introvale": "1",
 "isoniazid": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isocet": "2",
 "insulin glargine": "2",
 "iletin regular": "2",
 "inderide la": "1",
 "iletin nph": "2",
 "insulin aspart": "2",
 "insulin aspart protamine": "2",
 "influenza virus vaccine, live, trivalent": "3",
 "inderide": "1",
 "insta-char": "2",
 "isoniazid/rifampin": "2",
 "insta-char with sorbitol": "2",
 "immune globulin intravenous": "3",
 "insulin zinc": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "inspra": "2",
 "insulin lispro/insulin lispro protamine": "2",
 "ide-cet": "2",
 "insulin detemir": "2",
 "insulin isophane/insulin regular": "2",
 "insulin aspart/insulin aspart protamine": "2",
 "immune globulin intravenous and subcutaneous": "3",
 "isonarif": "2",
 "iveegam en": "3",
 "insulin glulisine": "2",
 "insulin purified regular pork": "2",
 "inderal": "1",
 "insulin purified nph pork": "2",
 "iletin ii nph pork": "2",
 "iletin ii regular pork": "2",
 "insulin lente pork": "2",
 "idenal": "2",
 "insulin": "2",
 "ibandronate": "2",
 "ib-stat": "1",
 "insulin lispro protamine": "2",
 "imatinib": "2"}, "h": {"hydeltrasol": "2",
 "hhr": "2",
 "hyophen": "1",
 "hycodan": "1",
 "hyzaar": "2",
 "hydrochlorothiazide/moexipril": "2",
 "humulin u": "2",
 "histatab ph": "1",
 "hydrocortisone": "2",
 "humulin 70/30 pen": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "hyoscyamine/phenyltoloxamine": "1",
 "hyprogesterone": "2",
 "hydrocortone phosphate": "2",
 "hyomax dt": "1",
 "hydrochlorothiazide/spironolactone": "1",
 "hyomax ft": "1",
 "hylutin": "2",
 "hyomax sr": "1",
 "hydrap-es": "2",
 "hyomax": "1",
 "hydrochlorothiazide/losartan": "2",
 "hydralazine": "2",
 "hyospaz": "1",
 "humulin 50/50": "2",
 "hista-vent pse": "1",
 "hyoscyamine/methenamine": "1",
 "healthstream activated charcoal": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "1",
 "hydropane": "1",
 "hydrochlorothiazide/olmesartan": "2",
 "humalog": "2",
 "heparin sodium": "2",
 "hydromet": "1",
 "hydrotropine": "1",
 "hyomax sl": "1",
 "hydroxyprogesterone": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydeltra-tba": "2",
 "humulin l": "2",
 "humulin n": "2",
 "hista-vent da": "1",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "1",
 "hydrochlorothiazide/propranolol": "1",
 "hydralazine plus": "2",
 "hyosyne": "1",
 "humalog mix 50/50": "2",
 "humalog mix 50/50 kwikpen": "2",
 "halfprin": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "histatab": "1",
 "hydromide": "1",
 "humalog mix 50/50 pen": "2",
 "hydra-zide": "2",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrocortone": "2",
 "humulin r": "2",
 "heparin": "2",
 "humalog mix 75/25": "2",
 "hyoscyamine": "1",
 "hepsera": "3",
 "histatab d": "1",
 "hydralazine/isosorbide dinitrate": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hyosophen": "2",
 "humulin n pen": "2",
 "hexadrol": "2",
 "humulin 70/30": "2",
 "humalog mix 75/25 pen": "2",
 "heartline": "2",
 "hyosol": "1",
 "homatropine/hydrocodone": "1",
 "humalog kwikpen": "2",
 "humalog pen": "2",
 "hyoscyamine/phenobarbital": "2",
 "humalog mix 75/25 kwikpen": "2"}, "k": {"kelnor 1/35": "1",
 "ken-jec 40": "2",
 "kenalog-10": "2",
 "kariva": "1",
 "kantrex": "2",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "karbons": "2",
 "key-pred": "2",
 "kanamycin": "2",
 "kemadrin": "1",
 "kenaject-40": "2",
 "ketorolac": "3"}, "j": {"jolessa": "1",
 "jl bragg's medicinal charcoal": "2",
 "jenest": "1",
 "jinteli": "1",
 "junel 1.5/30": "1",
 "jantoven": "2",
 "jevantique": "1",
 "junel fe 1/20": "1",
 "junel fe 1.5/30": "1",
 "junel 1/20": "1"}, "m": {"morphine/naltrexone": "2",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine/varicella virus vaccine": "2",
 "medrol dosepak": "2",
 "miradon": "2",
 "micardis": "2",
 "marlissa": "1",
 "mestranol/norethindrone": "1",
 "mesasal enteric coated": "2",
 "maldemar": "1",
 "mhp-a": "1",
 "methacort 40": "2",
 "migracet-pb": "2",
 "momentum": "2",
 "methscopolamine/pseudoephedrine": "1",
 "mephobarbital": "2",
 "medicoal": "2",
 "mephenytoin": "2",
 "mescolor": "1",
 "methylcotolone": "2",
 "monopril": "2",
 "millipred dp": "2",
 "methacort 80": "2",
 "medicort": "2",
 "methylcotol": "2",
 "motofen": "1",
 "migralex": "2",
 "methylprednisolone": "2",
 "minitabs": "2",
 "midol traditional": "2",
 "millipred": "2",
 "methotrexate": "2",
 "mysoline": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "min-ovral 28": "1",
 "min-ovral 21": "1",
 "mononessa": "1",
 "medi-seltzer": "2",
 "methscopolamine/phenylephrine": "1",
 "micardis hct": "2",
 "microgestin 1.5/30": "1",
 "methohexital": "2",
 "micronase": "2",
 "methylpred dp": "2",
 "mircette": "1",
 "microgestin fe 1/20": "1",
 "mygracet": "2",
 "mepenzolate": "1",
 "margesic": "2",
 "medidex la": "2",
 "metaglip": "2",
 "mesantoin": "2",
 "minotal": "2",
 "micrainin": "2",
 "metformin/repaglinide": "2",
 "msp-blu": "1",
 "mebaral": "2",
 "modicon": "1",
 "menopause support": "2",
 "microgestin fe 1.5/30": "1",
 "medrol": "2",
 "medique pain-off": "2",
 "magnaprin": "2",
 "micomp-pb": "2",
 "medralone": "2",
 "medipred": "2",
 "m-prednisolone": "2",
 "mudrane gg": "2",
 "medralone 80": "2",
 "methotrexate lpf sodium": "2",
 "medigesic": "2",
 "marten-tab": "2",
 "meticorten": "2",
 "monopril hct": "2",
 "myleran": "2",
 "microgestin 1/20": "1",
 "mavik": "2",
 "myzilra": "1",
 "makena": "2",
 "mesalamine": "2",
 "medique medi-seltzer": "2",
 "mudrane": "2",
 "methscopolamine": "1",
 "medidex": "2",
 "methylprednisolone dose pack": "2",
 "moexipril": "2",
 "marpres": "2"}, "l": {"litecoat aspirin": "2",
 "lovenox": "2",
 "lantus": "2",
 "loestrin fe 1.5/30": "1",
 "lomotil": "1",
 "luminal": "2",
 "lotrel": "2",
 "lufyllin-epg": "2",
 "levsin": "1",
 "low dose asa": "2",
 "lamivudine/zidovudine": "1",
 "lo/ovral-28": "1",
 "logen": "1",
 "levacet": "2",
 "loestrin fe 1/20": "1",
 "liqui-char with sorbitol": "2",
 "lo loestrin fe": "1",
 "lisinopril": "2",
 "levsin with phenobarbital": "2",
 "levsin sl": "1",
 "lybrel": "1",
 "liquid pred": "2",
 "lovenox hp": "2",
 "lantus opticlik cartridge": "2",
 "lortab asa": "2",
 "lialda": "2",
 "locholest": "1",
 "losartan": "2",
 "lonox": "1",
 "levsinex": "1",
 "lanoxin": "2",
 "loestrin 24 fe": "1",
 "lotensin": "2",
 "lutera": "1",
 "leflunomide": "3",
 "lasix": "1",
 "lotensin hct": "2",
 "lessina": "1",
 "loryna": "2",
 "locholest light": "1",
 "leena": "1",
 "levonest": "1",
 "loestrin 1/20": "1",
 "levbid": "1",
 "liraglutide": "1",
 "librax": "1",
 "levsinex sr": "1",
 "levora": "1",
 "lantus solostar": "2",
 "low-ogestrel-21": "1",
 "lomocot": "1",
 "lomanate": "1",
 "lo-aqua": "1",
 "lanoxicaps": "2",
 "levlite": "1",
 "lexxel": "2",
 "lactobacillus acidophilus/methscopolamine": "1",
 "loseasonique": "1",
 "levemir": "2",
 "laniroif": "2",
 "loestrin 21 1.5/30": "1",
 "low-ogestrel-28": "1",
 "lo/ovral": "1",
 "lente iletin ii": "2",
 "liqui-char": "2",
 "levlen": "1",
 "lepirudin": "2",
 "liqui-allergy": "1",
 "loestrin 21 1/20": "1"}, "o": {"orinase": "2",
 "orasone": "2",
 "orphengesic forte": "2",
 "oxybutynin": "1",
 "oxytrol": "1",
 "orphengesic": "2",
 "ortho-novum 1/50": "1",
 "ortho-novum 1/35": "1",
 "omnihist l.a.": "1",
 "ortho-novum 7/7/7": "1",
 "ortho evra": "1",
 "ogestrel-28": "1",
 "orbivan": "2",
 "oxaliplatin": "2",
 "optimum charcoal": "2",
 "ortho tri-cyclen": "1",
 "ocella": "2",
 "ovcon 35 fe": "1",
 "ovral": "1",
 "ortho-novum 10/11": "1",
 "olsalazine": "2",
 "orapred": "2",
 "ogestrel": "1",
 "ortho tri-cyclen lo": "1",
 "octagam": "3",
 "orsythia": "1",
 "olmesartan": "2",
 "ovcon 35": "1",
 "ortho-cept": "1",
 "omnihist ii la": "1",
 "ovcon 50": "1",
 "ovral-28": "1",
 "orapred odt": "2",
 "oxazepam": "1",
 "ortho cyclen": "1",
 "orgaran": "2"}, "n": {"nebcin": "2",
 "norethin 1/35 e": "1",
 "nuvaring": "1",
 "novolog mix 70/30 flexpen": "2",
 "nohist pe": "1",
 "necon 0.5/35": "1",
 "nohist ext": "1",
 "norethin 1/50 m": "1",
 "novolog": "2",
 "nortrel 0.5/35": "1",
 "necon 10/11": "1",
 "norwich aspirin": "2",
 "nohist plus": "1",
 "novolog mix 70/30 penfill": "2",
 "nph insulin": "2",
 "norgesic forte": "2",
 "novolog flexpen": "2",
 "naltrexone": "2",
 "nydrazid": "2",
 "norgesic": "2",
 "necon 1/35": "1",
 "novolog penfill": "2",
 "nacon": "1",
 "nulev": "1",
 "novolin 70/30 innolet": "2",
 "novolin n innolet": "2",
 "nebcin pediatric": "2",
 "necon 7/7/7": "1",
 "necon 1/50": "1",
 "nelova 10/11": "1",
 "novolin r penfill": "2",
 "neoral": "2",
 "novolin r innolet": "2",
 "novolin n": "2",
 "novolin 70/30": "2",
 "norit": "2",
 "netromycin": "2",
 "novolin l": "2",
 "nordette-28": "1",
 "netilmicin": "2",
 "nembutal": "2",
 "nordette-21": "1",
 "norinyl 1+35": "1",
 "nohist plus jr": "1",
 "norinyl 1+50": "1",
 "nonbac": "2",
 "novolin r": "2",
 "norel sd": "1",
 "novolin n penfill": "2",
 "novolog mix 50/50": "2",
 "nateglinide": "2",
 "nelova 0.5/35": "1",
 "nordette": "1",
 "novolog mix 70/30": "2",
 "nortrel 7/7/7": "1",
 "novolin 70/30 penfill": "2",
 "normiflo": "2",
 "nembutal sodium": "2",
 "nelova 1/35": "1",
 "nortrel 1/35": "1",
 "nelova 1/50 m": "1"}, "q": {"quasense": "1",
 "quinapril": "2",
 "questran light": "1",
 "qv-allergy": "1",
 "quinaretic": "2",
 "questran": "1",
 "quarzan": "1",
 "quadrinal": "2",
 "quadrapax": "2"}, "p": {"pyridium plus": "2",
 "phosphasal": "1",
 "pentasa": "2",
 "predicort-50": "2",
 "probenecid and colchicine": "1",
 "preven ec": "1",
 "predacort 50": "2",
 "pyrelle hb": "2",
 "pradaxa": "2",
 "promacet": "2",
 "prinzide": "2",
 "pcm": "1",
 "prograf": "3",
 "pulmicort nebuamp": "2",
 "predcor": "2",
 "primidone": "2",
 "prednicot": "2",
 "phrenilin forte": "2",
 "prelone": "2",
 "predate-50": "2",
 "pentobarbital": "2",
 "prosed ds": "1",
 "protuss tablet": "1",
 "probenecid": "1",
 "percodan": "2",
 "phenytek": "2",
 "pb-hyos": "2",
 "prominol": "2",
 "pulmicort flexhaler": "2",
 "predicort rp": "2",
 "primethasone": "2",
 "percodan-demi": "2",
 "prednicen-m": "2",
 "prehist d": "1",
 "prevalite": "1",
 "pc-cap": "2",
 "peganone": "2",
 "pri-cortin 50": "2",
 "polygam s/d": "3",
 "pemetrexed": "2",
 "phenytoin sodium, prompt": "2",
 "previfem": "1",
 "phenaz plus": "2",
 "pharmacia carbosorb": "2",
 "p-a-c analgesic": "2",
 "pamidronate": "2",
 "prodrox": "2",
 "pentothal": "2",
 "privigen": "3",
 "proben-c": "1",
 "pro-banthine": "1",
 "propantheline": "1",
 "propoxyphene compound 65": "2",
 "pcm-la": "1",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "propranolol": "1",
 "phosenamine": "1",
 "prinivil": "2",
 "pharmagesic": "2",
 "p-a-c": "2",
 "predaject-50": "2",
 "phenazoforte plus": "2",
 "pulmicort turbuhaler": "2",
 "predacorten": "2",
 "phenytoin": "2",
 "pannaz": "1",
 "perindopril": "2",
 "pulmicort respules": "2",
 "pseudo cm tr": "1",
 "phrenilin": "2",
 "predalone 50": "2",
 "panglobulin nf": "3",
 "philith": "1",
 "procyclidine": "1",
 "panasal 5/500": "2",
 "pamine forte": "1",
 "pediapred": "2",
 "prosed ec": "1",
 "prandimet": "2",
 "pamine fq": "1",
 "pcm allergy": "1",
 "phenobarbital": "2",
 "prednisolone": "2",
 "pamine": "1",
 "prandin": "2",
 "pseudox m": "1",
 "pred-ject-50": "2",
 "painaid": "2",
 "pannaz s": "1",
 "portia": "1",
 "prednisone": "2",
 "proquad": "2",
 "pamprin max menstrual pain relief": "2",
 "pravigard pac": "2",
 "panglobulin": "3"}, "s": {"solifenacin": "1",
 "supac": "2",
 "sandimmune": "2",
 "saleto": "2",
 "sodium edecrin": "1",
 "st. joseph aspirin": "2",
 "sympak pdx": "1",
 "symax duotab": "1",
 "sulfinpyrazone": "2",
 "septopal": "2",
 "solia": "1",
 "sunmark acid reducer maximum strength": "1",
 "solu-cortef": "2",
 "seconal": "2",
 "spasmolin": "2",
 "symax sl": "1",
 "sandoglobulin": "3",
 "soma compound with codeine": "2",
 "sloprin": "2",
 "symbicort": "2",
 "safyral": "2",
 "sympak": "1",
 "spastrin": "2",
 "symax fastab": "1",
 "sirolimus": "3",
 "st. joseph 81 mg aspirin enteric safety-coated": "2",
 "sterapred ds": "2",
 "symax sr": "1",
 "serathide": "2",
 "soma compound": "2",
 "solurex": "2",
 "serpazide": "2",
 "salofalk": "2",
 "sudatrate": "1",
 "seconal sodium": "2",
 "scopohist": "1",
 "skelid": "2",
 "scopohist syrup": "1",
 "scopace": "1",
 "sympak dm": "1",
 "sprintec": "1",
 "ser-ap-es": "2",
 "sympak ii": "1",
 "st. joseph 81 mg chewable aspirin": "2",
 "sustiva": "2",
 "sedapap": "2",
 "sulfasalazine": "2",
 "servira": "2",
 "stavzor": "2",
 "sodium salicylate": "1",
 "sronyx": "1",
 "solu-medrol": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "solurex la": "2",
 "sanctura xr": "1",
 "streptomycin": "2",
 "stahist": "1",
 "stanback analgesic": "2",
 "scot-tussin original": "1",
 "serax": "1",
 "syeda": "2",
 "synalgos-dc": "2",
 "starlix": "2",
 "seasonique": "1",
 "sprix": "3",
 "sanctura": "1",
 "selestoject": "2",
 "stanback fast pain relief": "2",
 "spironolactone": "1",
 "spasdel": "1",
 "spasquid": "2",
 "seasonale": "1",
 "scopolamine": "1",
 "serpex": "2",
 "sinodec": "1",
 "sulfazine": "2",
 "sal-tropine": "1",
 "sterapred": "2",
 "scopohist-pe": "1",
 "seconal sodium pulvules": "2"}, "r": {"rescon": "1",
 "rheumatrex dose pack": "2",
 "retrovir": "1",
 "relcof pse": "1",
 "rhinaclear": "1",
 "revia": "2",
 "re-drylex": "1",
 "relcof dn pe": "1",
 "repaglinide": "2",
 "respiratory syncytial virus immune globulin": "3",
 "rowasa sulfite free": "2",
 "rimactane": "1",
 "reclipsen": "1",
 "relion novolin 70/30 innolet": "2",
 "rolatuss-sr": "1",
 "reclast": "2",
 "relion/novolin 70/30": "2",
 "relcof dn pse": "1",
 "rebif": "2",
 "rifater": "2",
 "refludan": "2",
 "re-drylex jr": "1",
 "ryneze": "1",
 "respa-ar": "1",
 "relion/novolin r": "2",
 "robinul": "1",
 "ramipril": "2",
 "rhinocaps": "2",
 "relion novolin n": "2",
 "rifamate": "2",
 "relcof pe": "1",
 "respivent-d": "1",
 "rowasa": "2",
 "ru-tuss": "1",
 "respigam": "3",
 "roxiprin": "2",
 "repan": "2",
 "re-pb hyos elixir": "2",
 "ranitidine": "1",
 "ranitidine bismuth citrate": "1",
 "rhinolar": "1",
 "ralix": "1",
 "rifadin iv": "1",
 "rifampin": "1",
 "robaxisal": "2",
 "regurin": "1",
 "rifadin": "1",
 "rapamune": "3",
 "rivaroxaban": "2",
 "redur-pcm": "1",
 "relcof cpm": "1",
 "respivent df": "1",
 "risedronate": "2",
 "robinul forte": "1"}, "u": {"uretron": "1",
 "urimax": "1",
 "ursinus": "2",
 "utrona-c": "1",
 "utira-c": "1",
 "urised": "1",
 "uritact ds": "1",
 "urispas": "1",
 "urimar-t": "1",
 "urotrol": "1",
 "uretron ds": "1",
 "utira": "1",
 "univasc": "2",
 "urisedamine": "1",
 "utrona": "1",
 "u-tri-lone": "2",
 "urapine": "1",
 "uni serp": "2",
 "uritin": "1",
 "urelief plus": "2",
 "uta": "1",
 "usept": "1",
 "urisym": "1",
 "urogesic blue": "1",
 "unipres": "2",
 "uro blue": "1",
 "uritact-ec": "1",
 "uticap": "1",
 "ustell": "1",
 "urelle": "1",
 "uribel": "1",
 "uniretic": "2"}, "t": {"ticlid": "2",
 "telmisartan": "2",
 "thiopental": "2",
 "trizivir": "1",
 "tencet": "2",
 "tobi": "2",
 "tussigon": "1",
 "tolterodine": "1",
 "tol-tab": "2",
 "tramacort-d": "2",
 "tobramycin": "2",
 "telbivudine": "2",
 "trihexyphenidyl": "1",
 "trivaris": "2",
 "trospium": "1",
 "teveten hct": "2",
 "trihexane": "1",
 "tegretol": "2",
 "trinessa lo": "1",
 "toradol im": "3",
 "trivora-28": "1",
 "triphasil-28": "1",
 "triphasil-21": "1",
 "trilog": "2",
 "toradol": "3",
 "transderm-scop": "1",
 "thioguanine": "2",
 "tri-hydroserpine": "2",
 "torsemide": "1",
 "teveten": "2",
 "tabloid": "2",
 "ticlopidine": "2",
 "triamcinolone ophthalmic": "2",
 "tri-sprintec": "1",
 "tri-norinyl": "1",
 "toradol iv/im": "3",
 "time-hist qd": "1",
 "trandolapril/verapamil": "2",
 "theodrine": "2",
 "tolinase": "2",
 "triphasil": "1",
 "trivora": "1",
 "tri-levlen": "1",
 "triesence": "2",
 "tri-buffered aspirin": "2",
 "tri-lo-sprintec": "1",
 "talwin compound": "2",
 "therapy bayer": "2",
 "tyzeka": "2",
 "truvada": "3",
 "tri-previfem": "1",
 "tristoject": "2",
 "trandolapril": "2",
 "tri-legest fe": "1",
 "triquilar 28": "1",
 "triquilar 21": "1",
 "tenofovir": "3",
 "trilone": "2",
 "teczem": "2",
 "tagamet": "1",
 "tuinal": "2",
 "trac tabs 2x": "1",
 "tedrigen": "2",
 "tinzaparin": "2",
 "triam-forte": "2",
 "tencon": "2",
 "triamcot": "2",
 "triam-a": "2",
 "taladine": "1",
 "triamonide 40": "2",
 "tenake": "2",
 "triaprin": "2",
 "tarka": "2",
 "tilia fe": "1",
 "triamcinolone": "2",
 "trinessa": "1",
 "tolazamide": "2",
 "tritec": "1",
 "triall": "1",
 "tiludronate": "2",
 "tribenzor": "2",
 "tolbutamide": "2",
 "tri-legest": "1",
 "twynsta": "2",
 "triad": "2",
 "trihexy": "1",
 "tac 3": "2",
 "tagamet hb": "1",
 "tegretol xr": "2",
 "tacrolimus": "3",
 "trexall": "2",
 "two-dyne": "2"}, "w": {"warfarin": "2",
 "we allergy": "1"}, "v": {"venoglobulin-s 10%": "3",
 "valsartan": "2",
 "varicella virus vaccine": "2",
 "victoza": "1",
 "vi-atro": "1",
 "vemurafenib": "2",
 "vasotec": "2",
 "visrx dose pack": "1",
 "velivet": "1",
 "varivax": "2",
 "vestura": "2",
 "viread": "3",
 "valturna": "2",
 "vistide": "3",
 "velosulin br": "2",
 "veripred 20": "2",
 "vesicare": "1",
 "valproic acid": "2",
 "vaseretic": "2",
 "venoglobulin-s 5%": "3",
 "vaseretic 10-25": "2",
 "vivitrol": "2",
 "vaseretic 5-12.5": "2",
 "vanquish": "2"}, "y": {"ysp aspirin": "2",
 "yasmin": "2",
 "yaz": "2"}, "x": {"xiral sr": "1",
 "xarelto": "2"}, "z": {"zantac 150 efferdose": "1",
 "zovia 1/50": "1",
 "zarah": "2",
 "zantac 25 mg efferdose": "1",
 "zoledronic acid": "2",
 "zantac 300": "1",
 "zema pak": "2",
 "zantac 75": "1",
 "zantac": "1",
 "zelboraf": "2",
 "zeosa": "1",
 "zero-order release": "2",
 "zovia 1/35": "1",
 "zantac geldose": "1",
 "zorprin": "2",
 "zantac efferdose": "1",
 "zebutal": "2",
 "zometa": "2",
 "zestoretic": "2",
 "zenchent fe": "1",
 "zenchent": "1",
 "zantac 150": "1",
 "zidovudine": "1",
 "zestril": "2",
 "zantac 300 geldose": "1",
 "zovia": "1"}}];