interactions["albendazole,albenza"]=["albendazole,albenza", {"a": {"ari sodium iodide (i123) 100-750 mbq": "2",
 "antispas": "2",
 "amprenavir": "2",
 "agenerase": "2",
 "atropine/phenobarbital": "2",
 "antispasmodic": "2",
 "armodafinil": "1",
 "adrenocot": "1",
 "adrenocot la": "1",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "antrocol": "2",
 "alemtuzumab": "2",
 "alkabel-sr": "2",
 "atripla": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "accesspak for hiv pep expanded with viracept": "2",
 "anestacaine": "1",
 "accesspak for hiv pep expanded with kaletra": "2",
 "aprepitant": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "ari sodium iodide (i123) 1-12 mbq": "2"}, "c": {"chirocaine": "1",
 "carbatrol": "2",
 "cartia xt": "2",
 "cerebyx": "2",
 "cimetidine": "1",
 "cardizem la": "2",
 "cardizem monovial": "2",
 "cardizem cd": "2",
 "cladribine novaplus": "2",
 "cladribine": "2",
 "conivaptan": "2",
 "clopine": "3",
 "chardonna-2": "2",
 "cardizem sr": "2",
 "clozaril": "3",
 "ceftriaxone/lidocaine": "1",
 "carbamazepine": "2",
 "clozapine synthon": "3",
 "clozapine": "3",
 "cytovene": "2",
 "cardizem": "2",
 "campath": "2"}, "b": {"bendamustine": "2",
 "bellaphen-s": "2",
 "bellatal er": "2",
 "baycadron": "1",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "bellamor": "2",
 "bellatal": "2",
 "bellaspas": "2",
 "bel-tabs": "2",
 "bellamine s": "2",
 "bosentan": "2",
 "bel-phen-ergot": "2",
 "boceprevir": "2",
 "bexarotene": "1",
 "barbidonna": "2",
 "biltricide": "1"}, "e": {"exjade": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "equaline acid reducer": "1",
 "equetro": "2",
 "efavirenz": "2",
 "emtricitabine/nelfinavir/tenofovir": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "epitol": "2",
 "emend 3-day": "2",
 "emend 2-day": "2",
 "elixiral": "2",
 "emend": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "eperbel-s": "2",
 "epinephrine/lidocaine": "1",
 "emend for injection": "2",
 "etravirine": "2"}, "d": {"dexamethasone/lidocaine": "1",
 "dexasone": "1",
 "dronedarone": "2",
 "donnatal": "2",
 "dalalone la": "1",
 "dexone la": "1",
 "deferasirox": "2",
 "dexamethasone intensol": "1",
 "decadron-la": "1",
 "dilocaine": "1",
 "dexone": "1",
 "dentipatch": "1",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "dexpak taperpak": "1",
 "dexacorten": "1",
 "dexacort phosphate in turbinaire": "1",
 "diltiazem hydrochloride cd": "2",
 "dexacen-4": "1",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "diltiazem hydrochloride xt": "2",
 "diltia xt": "2",
 "dexasone la": "1",
 "decadron": "1",
 "dasatinib": "2",
 "decaject la": "1",
 "donnatal extentabs": "2",
 "diltiazem": "2",
 "diltiazem hydrochloride sr": "2",
 "dexacort-la": "1",
 "donnaphen": "2",
 "diltzac": "2",
 "decadron phosphate, injectable": "1",
 "dexamethasone": "1",
 "dalalone": "1",
 "d-tal": "2",
 "de-sone la": "1",
 "decadron with xylocaine": "1",
 "dilacor xr": "2",
 "dilantin": "2",
 "diltiazem hydrochloride xr": "2",
 "dexacort phosphate in respihaler": "1",
 "duragal-s": "2",
 "dilt-xr": "2",
 "dalalone dp": "1",
 "denzapine": "3",
 "decaject": "1"}, "g": {"ganciclovir": "2",
 "grepafloxacin": "2"}, "f": {"fosphenytoin": "2",
 "fluvoxamine": "2",
 "fosaprepitant": "2",
 "fortovase": "2",
 "fosamprenavir": "2",
 "fazaclo": "3"}, "i": {"invirase": "2",
 "intelence": "2",
 "itraconazole": "2",
 "incivek": "2",
 "iodotope": "2"}, "h": {"haponal": "2",
 "hyosophen": "2",
 "hyoscyamine/phenobarbital": "2",
 "hexadrol": "1"}, "k": {"ketek": "2",
 "kaletra": "2",
 "ketek pak": "2"}, "m": {"medidex": "1",
 "mudrane gg": "2",
 "mibefradil": "2",
 "matzim la": "2",
 "medidex la": "1",
 "modafinil": "1",
 "mudrane": "2",
 "multaq": "2"}, "l": {"lidoject 2": "1",
 "levsin with phenobarbital": "2",
 "lidoject 1": "1",
 "lufyllin-epg": "2",
 "luminal": "2",
 "lapatinib": "2",
 "l-caine": "1",
 "luvox cr": "2",
 "levobupivacaine": "1",
 "lopinavir/ritonavir": "2",
 "lidosite": "1",
 "leustatin": "2",
 "lidocaine": "1",
 "lidocaine/sodium bicarbonate": "1",
 "lidocaine/oxytetracycline": "1",
 "luvox": "2",
 "lexiva": "2"}, "o": {"oxcarbazepine": "2"}, "n": {"norvir soft gelatin": "2",
 "nilotinib": "2",
 "norvir": "2",
 "noxafil": "2",
 "nelfinavir": "2",
 "nuvigil": "1",
 "nervocaine": "1"}, "q": {"quadrinal": "2",
 "quadrapax": "2"}, "p": {"phenytoin": "2",
 "primethasone": "1",
 "posicor": "2",
 "posaconazole": "2",
 "priftin": "2",
 "phenobarbital": "2",
 "provigil": "1",
 "prograf": "2",
 "phenytek": "2",
 "pb-hyos": "2",
 "praziquantel": "1",
 "phenytoin sodium, prompt": "2"}, "s": {"sodium iodide-i-131": "2",
 "stelara": "2",
 "sporanox": "2",
 "sodium iodide i-123": "2",
 "solurex": "1",
 "spasmolin": "2",
 "sustiva": "2",
 "saquinavir": "2",
 "spastrin": "2",
 "solurex la": "1",
 "sirolimus": "2",
 "servira": "2",
 "sprycel": "2",
 "solfoton": "2",
 "spasquid": "2",
 "sporanox pulsepak": "2"}, "r": {"ritonavir": "2",
 "rifapentine": "2",
 "raxar": "2",
 "rapamune": "2",
 "rocephin im convenience kit": "1",
 "re-pb hyos elixir": "2"}, "u": {"uad caine": "1",
 "ustekinumab": "2"}, "t": {"tegretol": "2",
 "teczem": "2",
 "tagamet hb": "1",
 "tasigna": "2",
 "terramycin im": "1",
 "telithromycin": "2",
 "tracleer": "2",
 "tegretol xr": "2",
 "theodrine": "2",
 "tagamet": "1",
 "tacrolimus": "2",
 "tiazac": "2",
 "telzir": "2",
 "treanda": "2",
 "trileptal": "2",
 "targretin": "1",
 "telaprevir": "2",
 "tedrigen": "2",
 "truxacaine": "1",
 "taztia xt": "2",
 "tykerb": "2"}, "v": {"viracept": "2",
 "valcyte": "2",
 "voriconazole": "2",
 "vaprisol": "2",
 "vfend": "2",
 "valganciclovir": "2",
 "victrelis": "2"}, "x": {"xylocaine-mpf": "1",
 "xylocaine-mpf-epinephrine": "1",
 "xylocaine hcl for spinal": "1",
 "xylocaine hcl": "1",
 "xylocaine duo-trach kit": "1",
 "xylocaine with epinephrine": "1",
 "xylocaine hcl with epinephrine": "1",
 "xylocaine dental cartridges": "1",
 "xylocaine with epinephrine dental cartridges": "1"}, "z": {"zema pak": "1",
 "zaponex": "3"}}];