interactions["alefacept,amevive"]=["alefacept,amevive", {"a": {"adriamycin rdf": "2",
 "azathioprine": "2",
 "a-hydrocort": "2",
 "alkeran": "2",
 "anti-thymocyte globulin": "2",
 "afinitor": "2",
 "aristocort": "2",
 "adriamycin": "2",
 "acthib with dpt (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "atgam (lymphocyte immune globulin, anti-thy (equine))": "2",
 "aristopak": "2",
 "arzerra": "2",
 "aqua gem-e": "1",
 "aqua-e": "1",
 "abraxane": "2",
 "acth": "2",
 "arava": "2",
 "acthrel": "2",
 "adrucil": "2",
 "adrenocot": "2",
 "adrenocot la": "2",
 "asparaginase escherichia coli": "2",
 "acam2000": "3",
 "adlone-40": "2",
 "acthib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "adcetris": "2",
 "afluria": "2",
 "azasan": "2",
 "aplisol": "2",
 "azacitidine": "2",
 "acthar": "2",
 "adlone-80": "2",
 "actemra": "2",
 "arcalyst": "2",
 "arranon": "2",
 "aristospan": "2",
 "adacel": "2",
 "aplitest": "2",
 "a-methapred": "2",
 "acetocot": "2",
 "adalimumab": "2",
 "abacavir/lamivudine/zidovudine": "2",
 "azmacort": "2",
 "aquasol e": "1",
 "altretamine": "2",
 "agriflu": "2",
 "abatacept": "2",
 "attenuvax": "3",
 "adbeon": "2",
 "anthrax vaccine adsorbed": "2",
 "aristocort for injection": "2",
 "alemtuzumab": "2",
 "alimta": "2",
 "aquavite-e": "1",
 "anakinra": "2",
 "amino-opti-e": "1",
 "aldesleukin": "2",
 "adriamycin pfs": "2",
 "alpha e": "1"}, "c": {"cortrosyn": "2",
 "cerubidine": "2",
 "cervarix": "2",
 "cisplatin": "2",
 "cholecalciferol/genistein/zinc chelazome": "1",
 "cortone acetate": "2",
 "cytarabine": "2",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/zinc sulfate": "1",
 "cimzia": "2",
 "cyclophosphamide": "2",
 "cosyntropin": "2",
 "comvax (haemophilus b conjugate (prp-omp) vaccine/hepatitis b pediatric vaccine)": "2",
 "cat's claw": "1",
 "cellcept": "2",
 "canakinumab": "2",
 "celestone": "2",
 "cytoxan": "2",
 "cytoxan lyophilized": "2",
 "cosmegen": "2",
 "cotolone": "2",
 "chlorambucil": "2",
 "combivir": "2",
 "camptosar": "2",
 "colocort": "2",
 "cholera vaccine": "2",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/selenium/zinc sulfate": "1",
 "cladribine novaplus": "2",
 "cladribine": "2",
 "capecitabine": "2",
 "cortisone": "2",
 "cortifoam": "2",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/selenium/sodium iodide/zinc sulfate": "1",
 "clofarabine": "2",
 "cabazitaxel": "2",
 "cytosar-u": "2",
 "carboplatin novaplus": "2",
 "carboplatin": "2",
 "clinalog": "2",
 "corticorelin": "2",
 "candida skin test": "2",
 "clinacort": "2",
 "coccidioidin skin test": "2",
 "candin": "2",
 "cort-k": "2",
 "conte-pak-4": "1",
 "corticotropin": "2",
 "cyclosporine": "2",
 "celestone phosphate": "2",
 "cell-u-jec": "2",
 "cortef": "2",
 "candida albicans extract": "2",
 "cholecalciferol/genistein/zinc glycinate": "1",
 "carmustine": "2",
 "cortenema": "2",
 "centrum singles-vitamin e": "1",
 "ceenu": "2",
 "cytosar": "2",
 "certolizumab": "2",
 "clolar": "2",
 "celestone soluspan": "2",
 "campath": "2"}, "b": {"bexxar dosimetric": "2",
 "basiliximab": "2",
 "bexxartherapeutic": "2",
 "beta-phos/ac": "2",
 "bioflavonoids/zinc glycinate": "1",
 "busulfan": "2",
 "busulfex": "2",
 "belatacept": "2",
 "budesonide/formoterol": "2",
 "brentuximab": "2",
 "benlysta": "2",
 "bleomycin": "2",
 "blenoxane": "2",
 "budesonide": "2",
 "belimumab": "2",
 "bexxar": "2",
 "betamethasone": "2",
 "boostrix": "2",
 "biavax ii": "3",
 "biothrax": "2",
 "bendamustine": "2",
 "baycadron": "2",
 "bexarotene": "2",
 "bcg": "3",
 "bubbli-pred": "2",
 "bicnu": "2"}, "e": {"e-400 clear": "1",
 "elspar": "2",
 "e pherol": "1",
 "e-gems": "1",
 "etanercept": "2",
 "efalizumab": "2",
 "engerix-b pediatric": "2",
 "etoposide": "2",
 "etopophos": "2",
 "echinacea": "1",
 "eloxatin": "2",
 "enbrel": "2",
 "eribulin": "2",
 "everolimus": "2",
 "e-600": "1",
 "ergamisol": "2",
 "epirubicin": "2",
 "ellence": "2",
 "engerix-b": "2",
 "entocort ec": "2"}, "d": {"dexamethasone/lidocaine": "2",
 "dexasone": "2",
 "dacogen": "2",
 "dalalone la": "2",
 "doxil": "2",
 "dexone la": "2",
 "dexacen-4": "2",
 "daptacel": "2",
 "daunorubicin": "2",
 "dexamethasone intensol": "2",
 "diphtheria and tetanus toxoids/pertussis, acellular": "2",
 "doxorubicin liposomal": "2",
 "decadron-la": "2",
 "diphtheria toxoid/hepatitis b pediatric vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "diphtheria toxoid/tetanus toxoid": "2",
 "decavac": "2",
 "dexone": "2",
 "diphtheria toxoid/haemophilus b conjugate": "2",
 "delta-cortef": "2",
 "dexpak taperpak": "2",
 "dexacorten": "2",
 "dexacort phosphate in turbinaire": "2",
 "dep medalone 80": "2",
 "daclizumab": "2",
 "daunoxome": "2",
 "denosumab": "2",
 "diphtheria-tetanus toxoids, pediatric": "2",
 "dexamethasone": "2",
 "dexasone la": "2",
 "decadron": "2",
 "dasatinib": "2",
 "decaject la": "2",
 "deltasone": "2",
 "diphtheria toxoid/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "dryvax": "3",
 "dactinomycin": "2",
 "duralone": "2",
 "dexacort-la": "2",
 "docefrez": "2",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "dtic-dome": "2",
 "docetaxel": "2",
 "depo-medrol": "2",
 "droxia": "2",
 "daunorubicin liposomal": "2",
 "dalalone": "2",
 "diphtheria toxoid/pertussis, whole cell/tetanus toxoid": "2",
 "de-sone la": "2",
 "decadron with xylocaine": "2",
 "dacarbazine": "2",
 "depmedalone": "2",
 "diphtheria toxoid/pertussis, acellular/tetanus toxoid": "2",
 "doxorubicin": "2",
 "dexacort phosphate in respihaler": "2",
 "denileukin diftitox": "2",
 "depopred": "2",
 "decitabine": "2",
 "dalalone dp": "2",
 "decaject": "2"}, "g": {"gilenya": "2",
 "gemzar": "2",
 "gemcitabine": "2",
 "gliadel": "2",
 "gengraf": "2",
 "galzin": "1",
 "golimumab": "2",
 "gleevec": "2",
 "gardasil": "2",
 "gemtuzumab": "2"}, "f": {"fingolimod": "2",
 "fluzone intradermal": "2",
 "fludarabine": "2",
 "folex pfs": "2",
 "flushield": "2",
 "florinef acetate": "2",
 "fluvirin": "2",
 "florinef": "2",
 "floxuridine": "2",
 "flulaval": "2",
 "fluzone high-dose": "2",
 "flo-pred": "2",
 "fluorouracil": "2",
 "flumist": "3",
 "fludara": "2",
 "fludrocortisone": "2",
 "fluogen": "2",
 "fluarix": "2",
 "fudr": "2",
 "folotyn": "2",
 "fluzone": "2",
 "fosteum": "1"}, "i": {"influenza virus vaccine, h1n1, live": "3",
 "iodine i 131 tositumomab": "2",
 "idamycin pfs": "2",
 "ipol": "2",
 "imatinib": "2",
 "idamycin": "2",
 "ixempra": "2",
 "ifex": "2",
 "infliximab": "2",
 "influenza virus vaccine, live, trivalent": "3",
 "ixiaro": "2",
 "ifosfamide": "2",
 "influenza virus vaccine, inactivated": "2",
 "imuran": "2",
 "ixabepilone": "2",
 "influenza virus vaccine, h1n1, inactivated": "2",
 "in-111 zevalin": "2",
 "ifosfamide/mesna": "2",
 "ilaris": "2",
 "ibritumomab": "2",
 "idarubicin": "2",
 "irinotecan": "2",
 "imovax rabies": "2",
 "ifex/mesnex": "2",
 "infanrix": "2",
 "istodax": "2"}, "h": {"hydeltrasol": "2",
 "hepatitis a pediatric vaccine": "2",
 "histolyn-cyl": "2",
 "human papillomavirus vaccine": "2",
 "histoplasmin diluted": "2",
 "hydrocortisone": "2",
 "hydrocortone phosphate": "2",
 "havrix pediatric": "2",
 "haemophilus b conjugate": "2",
 "hibtiter (haemophilus b conjugate (hboc) vaccine)": "2",
 "hydrocortone": "2",
 "hydroxyurea": "2",
 "hepatitis b adult vaccine": "2",
 "hexalen": "2",
 "hydeltra-tba": "2",
 "hepatitis b pediatric vaccine": "2",
 "histoplasmin": "2",
 "h.p. acthar gel": "2",
 "hepatitis a adult vaccine/hepatitis b adult vaccine": "2",
 "hepatitis a adult vaccine": "2",
 "halaven": "2",
 "hiberix (haemophilus b conjugate (prp-t) vaccine)": "2",
 "havrix": "2",
 "hycamtin": "2",
 "humira": "2",
 "herceptin": "2",
 "hexadrol": "2",
 "hydrea": "2"}, "k": {"key-pred": "2",
 "kenalog-10": "2",
 "kineret": "2",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "ken-jec 40": "2",
 "kinrix": "2",
 "kenaject-40": "2"}, "j": {"je-vax": "2",
 "jakafi": "2",
 "japanese encephalitis virus vaccine sa14-14-2": "2",
 "jevtana": "2",
 "japanese encephalitis virus vaccine nakayama": "2"}, "m": {"multitrace-4 pediatric": "1",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine": "3",
 "mumps virus vaccine": "3",
 "mutamycin": "2",
 "multiple trace element neonatal": "1",
 "methylprednisolone": "2",
 "meruvax ii": "3",
 "medralone": "2",
 "medidex la": "2",
 "medipred": "2",
 "m-prednisolone": "2",
 "multe-pak-5": "1",
 "menomune": "2",
 "medralone 80": "2",
 "methotrexate": "2",
 "multitrace-5 concentrate": "1",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine/varicella virus vaccine": "3",
 "measles virus vaccine": "3",
 "medrol dosepak": "2",
 "mumps skin test antigen": "2",
 "multitrace-5": "1",
 "medralone 40": "2",
 "med-jec-40": "2",
 "myfortic": "2",
 "methotrexate lpf sodium": "2",
 "mylocel": "2",
 "mumps virus vaccine/rubella virus vaccine": "3",
 "mycophenolic acid": "2",
 "micro-zn": "1",
 "meticorten": "2",
 "multitrace-4": "1",
 "methylprednisolone dose pack": "2",
 "mte-5 concentrated": "1",
 "menomune a/c/y/w-135": "2",
 "mar-zinc": "1",
 "meningococcal conjugate vaccine": "2",
 "melphalan": "2",
 "millipred": "2",
 "mechlorethamine": "2",
 "methacort 40": "2",
 "mercaptopurine": "2",
 "multe-pak-4": "1",
 "methylpred dp": "2",
 "m-m-r ii": "3",
 "mylotarg": "2",
 "mumpsvax": "3",
 "menactra": "2",
 "multitrace-4 concentrate": "1",
 "mte-6": "1",
 "multitrace-4 neonatal": "1",
 "mono-vacc test": "2",
 "mustargen": "2",
 "methylcotolone": "2",
 "mixed respiratory vaccine": "2",
 "m-r-vax ii": "3",
 "matulane": "2",
 "meningococcal polysaccharide vaccine": "2",
 "multitest cmi": "2",
 "mte-4 concentrated": "1",
 "millipred dp": "2",
 "menveo": "2",
 "medidex": "2",
 "methacort 80": "2",
 "mithracin": "2",
 "myleran": "2",
 "mrv": "2",
 "medicort": "2",
 "mitoxantrone": "2",
 "mycophenolate mofetil": "2",
 "mitomycin": "2",
 "muromonab-cd3": "2",
 "medrol": "2",
 "measles virus vaccine/rubella virus vaccine": "3",
 "methylcotol": "2",
 "msta mumps skin test antigen": "2",
 "mte-7": "1",
 "mte-4": "1",
 "mte-5": "1",
 "multiple trace element": "1"}, "l": {"lyme disease vaccine": "2",
 "liquid pred": "2",
 "lymphocyte immune globulin, anti-thy": "2",
 "leflunomide": "2",
 "lenalidomide": "2",
 "leukeran": "2",
 "limbrel 250": "1",
 "lamivudine/zidovudine": "2",
 "linezolid": "2",
 "leustatin": "2",
 "lymerix": "2",
 "levamisole": "2",
 "liquid pedvaxhib (haemophilus b conjugate (prp-omp) vaccine)": "2",
 "limbrel 500": "1",
 "lomustine": "2"}, "o": {"orasone": "2",
 "ofatumumab": "2",
 "orencia": "2",
 "ontak": "2",
 "orthoclone okt3": "2",
 "orazinc": "1",
 "oforta": "2",
 "orapred odt": "2",
 "orimune": "3",
 "oxaliplatin": "2",
 "oncovin": "2",
 "onxol": "2",
 "orapred": "2"}, "n": {"nilotinib": "2",
 "nulojix": "2",
 "novantrone": "2",
 "nelarabine": "2",
 "neutrexin": "2",
 "neosar": "2",
 "natalizumab": "3",
 "navelbine": "2",
 "nutr-e-sol": "1",
 "neotrace-4": "1",
 "neoral": "2",
 "nipent": "2"}, "p": {"pentostatin": "2",
 "pedtrace-4": "1",
 "paclitaxel protein-bound": "2",
 "predicort-50": "2",
 "pneumovax 23": "2",
 "prolia": "2",
 "plicamycin": "2",
 "purinethol": "2",
 "pedte-pak-4": "1",
 "pneumococcal 7-valent vaccine": "2",
 "pedvaxhib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "pulmicort flexhaler": "2",
 "pralatrexate": "2",
 "pediarix": "2",
 "predicort rp": "2",
 "primethasone": "2",
 "poliovirus vaccine, live, trivalent": "3",
 "predaject-50": "2",
 "pneumococcal 23-polyvalent vaccine": "2",
 "pneumococcal 13-valent vaccine": "2",
 "pred-ject-50": "2",
 "pulmicort turbuhaler": "2",
 "pharmorubicin rdf": "2",
 "pulmicort nebuamp": "2",
 "phytase/zinc citrate": "1",
 "predcor": "2",
 "plague vaccine": "2",
 "predacorten": "2",
 "prednicen-m": "2",
 "platinol": "2",
 "prednisolone": "2",
 "prednisone": "2",
 "prednicot": "2",
 "provenge": "2",
 "prograf": "2",
 "pte-5": "1",
 "pte-4": "1",
 "pulmicort respules": "2",
 "proleukin": "2",
 "pri-cortin 50": "2",
 "poliovirus vaccine, inactivated": "2",
 "pemetrexed": "2",
 "predalone 50": "2",
 "proquad": "3",
 "paraplatin": "2",
 "prelone": "2",
 "paclitaxel": "2",
 "procarbazine": "2",
 "prevnar": "2",
 "prevnar 13": "2",
 "pentacel (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid)": "2",
 "platinol-aq": "2",
 "pediapred": "2",
 "predacort 50": "2",
 "predate-50": "2",
 "pharmorubicin pfs": "2"}, "s": {"spherulin": "2",
 "sandimmune": "2",
 "staphage lysate": "2",
 "solurex": "2",
 "symbicort": "2",
 "simulect": "2",
 "stelara": "2",
 "sterapred ds": "2",
 "simponi": "2",
 "smallpox vaccine": "3",
 "sirolimus": "2",
 "skin test antigens, multiple": "2",
 "sipuleucel-t": "2",
 "selestoject": "2",
 "solu-cortef": "2",
 "sclavo test-ppd": "2",
 "solurex la": "2",
 "streptozocin": "2",
 "sterapred": "2",
 "solu-medrol": "2",
 "sprycel": "2"}, "r": {"rheumatrex dose pack": "2",
 "rituxan": "2",
 "recombivax hb dialysis formulation": "2",
 "rotateq": "3",
 "rotashield": "3",
 "recombivax hb adult": "2",
 "retrovir": "2",
 "raptiva": "2",
 "rubella virus vaccine": "3",
 "rabies vaccine, human diploid cell": "2",
 "rotavirus vaccine": "3",
 "ruxolitinib": "2",
 "rapamune": "2",
 "rotarix": "3",
 "rabavert": "2",
 "rituximab": "2",
 "rilonacept": "2",
 "recombivax hb pediatric/adolescent": "2",
 "recombivax hb": "2",
 "romidepsin": "2",
 "remicade": "2",
 "rabies vaccine, purified chick embryo cell": "2",
 "revlimid": "2"}, "u": {"u-tri-lone": "2",
 "uracil mustard": "2",
 "ustekinumab": "2"}, "t": {"tripedia": "2",
 "trilog": "2",
 "trihibit (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "tasigna": "2",
 "trizivir": "2",
 "tetanus toxoid adsorbed": "2",
 "treanda": "2",
 "thymoglobulin (anti-thymocyte globulin (rabbit))": "2",
 "thioguanine": "2",
 "tuberculin tine test": "2",
 "tramacort-d": "2",
 "trastuzumab": "2",
 "temozolomide": "2",
 "tositumomab": "2",
 "taxol": "2",
 "tubersol": "2",
 "tuberculin purified protein derivative": "2",
 "triam-a": "2",
 "tabloid": "2",
 "tetanus toxoid": "2",
 "thiotepa": "2",
 "trexall": "2",
 "taxotere": "2",
 "theracys": "3",
 "tristoject": "2",
 "tetanus toxoid for booster use only": "2",
 "tice bcg": "3",
 "typhoid vaccine, inactivated": "2",
 "trichophyton allergenic extracts": "2",
 "te anatoxal berna": "2",
 "triamcinolone": "2",
 "trilone": "2",
 "teniposide": "2",
 "tetramune (diphtheria toxoid/haemophilus b conjugate (hboc) vaccine/pertussis, whole cell/tetanus toxoid)": "2",
 "trichophyton skin test": "2",
 "tarabine pfs": "2",
 "toposar": "2",
 "twinrix": "2",
 "targretin": "2",
 "tysabri": "3",
 "typhim vi": "2",
 "trace metals": "1",
 "tac 3": "2",
 "triam-forte": "2",
 "thalidomide": "2",
 "thalomid": "2",
 "trimetrexate": "2",
 "torisel": "2",
 "triamcot": "2",
 "tacrolimus": "2",
 "topotecan": "2",
 "tocilizumab": "2",
 "thioplex": "2",
 "tice bcg vaccine": "3",
 "typhoid vaccine, live": "3",
 "triamonide 40": "2",
 "tetanus-diphtheria toxoids, adult": "2",
 "temodar": "2",
 "temsirolimus": "2"}, "v": {"vaqta pediatric": "2",
 "veripred 20": "2",
 "vita-plus e natural": "1",
 "velban": "2",
 "vepesid": "2",
 "vitamin e": "1",
 "vinblastine": "2",
 "vincristine": "2",
 "varivax": "3",
 "vivotif berna vaccine": "3",
 "vaqta": "2",
 "varicella virus vaccine": "3",
 "vincasar pfs": "2",
 "verazinc": "1",
 "vidaza": "2",
 "vumon": "2",
 "vivotif berna": "3",
 "vinorelbine": "2"}, "y": {"yellow fever vaccine": "3",
 "y-90 zevalin": "2",
 "yf-vax": "3"}, "x": {"xeloda": "2",
 "xgeva": "2"}, "z": {"zortress": "2",
 "zema pak": "2",
 "zoster vaccine live": "3",
 "zostavax": "3",
 "zincate": "1",
 "zenapax": "2",
 "zinc-220": "1",
 "zinc chloride": "1",
 "zinc acetate": "1",
 "zinc 50 mg pink": "1",
 "zinc sulfate": "1",
 "zevalin": "2",
 "zanosar": "2",
 "zinc cr": "1",
 "zinca-pak": "1",
 "zyvox": "2",
 "zytaze": "1",
 "zinc gluconate": "1",
 "zidovudine": "2"}}];             