interactions["alendronate,fosamax"]=["alendronate,fosamax", {"5": {"50 + companion": "2"}, "a": {"ascorbic acid/ferrous sulfate": "2",
 "aspirin/hydrocodone": "2",
 "anacin": "2",
 "aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "aluminum hydroxide": "2",
 "ascorbic acid/iron polysaccharide": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "ascriptin enteric": "2",
 "advil liqui-gels": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "aflaxen": "2",
 "aspir-low": "2",
 "antioxidant formula": "2",
 "aspirin/oxycodone": "2",
 "advil pm": "2",
 "alu-tab": "2",
 "aspir-mox": "2",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "2",
 "aspergum": "2",
 "alcalak": "2",
 "adult strength": "2",
 "atabex ec": "2",
 "apatate forte": "2",
 "acid reducer + antacid dual action": "2",
 "azdone": "2",
 "ascomp with codeine": "2",
 "apetimar with iron": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "amphojel": "2",
 "alor 5/500": "2",
 "argesic-sa": "2",
 "alka-seltzer plus flu formula": "2",
 "almora": "2",
 "aminatal plus new formula": "2",
 "addaprin": "2",
 "anaflex": "2",
 "aspirin buffered": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "aminatal plus": "2",
 "amikacin": "2",
 "anemagen fa": "2",
 "aspirin/pravastatin": "2",
 "advil cold and sinus liqui-gels": "2",
 "anhydrous calcium iodide/codeine": "2",
 "acetaminophen/aspirin": "2",
 "all day pain relief": "2",
 "accuretic": "2",
 "anaprox": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "alka-seltzer plus immunity complex": "2",
 "aspirin/caffeine": "2",
 "abc to z": "2",
 "aspirin/carisoprodol": "2",
 "aspir 81": "2",
 "alka-seltzer extra strength": "2",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "2",
 "advil children's allergy sinus": "2",
 "acetaminophen/aspirin/caffeine": "2",
 "aleve": "2",
 "alenic alka tablet": "2",
 "acid gone antacid": "2",
 "acid gone": "2",
 "anemagen": "2",
 "arthritis pain": "2",
 "aminate": "2",
 "ami-lac": "2",
 "accupril": "2",
 "aspirin/methocarbamol": "2",
 "arthriten": "2",
 "allbee-c 800 with iron": "2",
 "amikin": "2",
 "a-g profen": "2",
 "aldroxicon ii": "2",
 "aminatal plus one": "2",
 "alka-seltzer wake-up call!": "2",
 "aggrenox": "2",
 "arthritis pain formula": "2",
 "advil allergy sinus": "2",
 "attapulgite": "2",
 "alka-seltzer original": "2",
 "aspirin/pseudoephedrine": "2",
 "alka-mints": "2",
 "amitone": "2",
 "abc plus senior": "2",
 "ascriptin maximum strength": "2",
 "aluminum hydroxide/mineral oil": "2",
 "amigesic": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "aminate with 90 mg iron": "2",
 "alka-seltzer lemon-lime": "2",
 "advil children's cold": "2",
 "aspirin/butalbital/caffeine": "2",
 "arthropan": "2",
 "aspirin/meprobamate": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2",
 "aldroxicon i": "2",
 "advance care plus": "2",
 "advil migraine": "2",
 "all day relief": "2",
 "anacin advanced headache formula": "2",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "aquadeks": "2",
 "advil infant's concentrated drops": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "actiprofen": "2",
 "actonel with calcium": "2",
 "acid gone extra strength": "2",
 "alka-seltzer plus cold formula": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "alka-seltzer pm": "2",
 "aluminum carbonate": "2",
 "aspirin/diphenhydramine": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "acetaminophen/salicylamide": "2",
 "anacin max strength": "2",
 "apetigen-plus": "2",
 "alkums": "2",
 "aspirin/carisoprodol/codeine": "2",
 "aspirin": "2",
 "acetaminophen/aspirin/phenylpropanolamine": "2",
 "acid relief": "2",
 "aquadeks pediatric": "2",
 "aspirin/calcium carbonate": "2",
 "advanced am/pm": "2",
 "aleve-d sinus &amp; cold": "2",
 "almacone-2": "2",
 "antioxid caplets": "2",
 "acuprin 81": "2",
 "anemagen forte": "2",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "acetaminophen/phenyltoloxamine/salicylamide": "2",
 "advil junior strength": "2",
 "alternagel": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "avail calcium intensive": "2",
 "amikin pediatric": "2",
 "axid ar": "1",
 "anaprox-ds": "2",
 "aspiritab": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "alu-cap": "2",
 "ascriptin": "2",
 "almacone": "2",
 "actron": "2",
 "axid": "1",
 "ami-natal plus one improved": "2",
 "alamag": "2",
 "alamag plus": "2",
 "aspirin/phenyltoloxamine": "2",
 "arthrotec": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "anabar": "2",
 "advil": "2",
 "aspirtab": "2",
 "anhydrous calcium iodide/isoproterenol": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "aspircaf": "2",
 "atrosept": "2",
 "ascorbic acid/ferrous fumarate": "2",
 "antioxidant ultra formula": "2",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "acetylsalicylic acid": "2",
 "alkets": "2",
 "adeks": "2",
 "acid controller original strength": "1",
 "aspirin/butalbital": "2",
 "anemagen ob": "2",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "2",
 "aspirin/codeine": "2",
 "advil cold and sinus": "2",
 "aspirin/pentazocine": "2",
 "alenic alka": "2",
 "ansaid": "2",
 "aspirin low strength": "2",
 "aspir-mox ib": "2",
 "aloh-gel": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "aspirin lite coat": "2",
 "advil children's": "2",
 "aspirin/caffeine/salicylamide": "2",
 "arthritis foundation pain reliever": "2",
 "axid pulvules": "1",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "aspirin/dipyridamole": "2"}, "c": {"calcitab": "2",
 "cvs extra strength headache relief": "2",
 "calcium carbonate/risedronate": "2",
 "certa-vite senior plus lutein": "2",
 "calcifolic-d": "2",
 "choline salicylate/magnesium salicylate": "2",
 "citracal kosher": "2",
 "centratex": "2",
 "cal-nate": "2",
 "century senior": "2",
 "citrate of magnesia": "2",
 "calcium carbonate/fluoride": "2",
 "corvite free": "2",
 "calcidrine": "2",
 "carbonyl iron": "2",
 "calcarb with d": "2",
 "calcionate": "2",
 "citracal regular": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "centavite": "2",
 "concept dha": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "conte-pak-4": "2",
 "combunox": "2",
 "cafgesic": "2",
 "citracal petites": "2",
 "childrens ibuprofen berry": "2",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/selenium/sodium iodide/zinc sulfate": "2",
 "choline magnesium trisalicylate": "2",
 "cmt": "2",
 "cavan-heme ob": "2",
 "cyanocobalamin/folic acid/pyridoxine/strontium gluconate": "2",
 "calcium oyster shell": "2",
 "celecoxib": "2",
 "calcid": "2",
 "co natal fa": "2",
 "corvita 150": "2",
 "corvite 150": "2",
 "century-vite": "2",
 "cavan folate": "2",
 "chloromag": "2",
 "cap-profen": "2",
 "centrum kids": "2",
 "crm": "2",
 "citric acid/glucono-delta-lactone/magnesium carbonate topical": "2",
 "citranatal harmony": "2",
 "cholecalciferol/genistein/zinc chelazome": "2",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/zinc sulfate": "2",
 "centrum silver": "2",
 "calcium phosphate, tribasic": "2",
 "calcium gluconate": "2",
 "chromagen ob": "2",
 "citracal + d": "2",
 "citracal prenatal rx": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "caltrate plus": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "carafate": "2",
 "centrum performance": "2",
 "careone acid reducer": "1",
 "caltrate colon health": "2",
 "centrum silver men's": "2",
 "comfort pac with naproxen": "2",
 "complete-rf": "2",
 "citracal plus bone density builder": "2",
 "cerovite senior": "2",
 "chromium gtf": "2",
 "certagen senior with lutein": "2",
 "citracal calcium gummies": "2",
 "citracal regular 250 mg + d": "2",
 "calcium carbonate/simethicone": "2",
 "centrum special energy": "2",
 "centrum silver women's": "2",
 "calafol rx": "2",
 "combi rx": "2",
 "certavite with antioxidants": "2",
 "combiflex es": "2",
 "circavite t": "2",
 "calcium lactate": "2",
 "centrum specialist vision": "2",
 "cerovite junior": "2",
 "caltrate 600+d": "2",
 "central": "2",
 "calcium glycerophosphate": "2",
 "caromega": "2",
 "centrum silver ultra women's": "2",
 "cezin-s": "2",
 "children's motrin": "2",
 "cal-g": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "citracal maximum": "2",
 "caltrate 600 plus": "2",
 "calcium carbonate/magnesium carbonate": "2",
 "corvite": "2",
 "copper": "2",
 "citrus calcium with vitamin d": "2",
 "clinoril": "2",
 "chromagen": "2",
 "certagen senior": "2",
 "citracal prenatal 90+dha": "2",
 "cystex": "2",
 "central-vite": "2",
 "centrum cardio": "2",
 "chromium picolinate": "2",
 "contrin": "2",
 "centrum": "2",
 "combiflex": "2",
 "centrum special heart": "2",
 "calcitrate with d": "2",
 "citracal plus magnesium": "2",
 "calcio del mar": "2",
 "caltrate 600 with d plus soy": "2",
 "completenate": "2",
 "cataflam": "2",
 "century": "2",
 "carenatal dha": "2",
 "chromatinic": "2",
 "centrum silver ultra men's": "2",
 "cal-gest": "2",
 "caldolor": "2",
 "certavite": "2",
 "calcet": "2",
 "caltro with vitamin d": "2",
 "conison": "2",
 "cimetidine": "1",
 "calcium carbonate": "2",
 "centrum jr with extra calcium": "2",
 "cf vite": "2",
 "cal oys": "2",
 "cenogen ultra": "2",
 "cidomycin": "2",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/selenium/zinc sulfate": "2",
 "cavan ec dha plus": "2",
 "cr-gtf": "2",
 "chewable calcium with vitamin d": "2",
 "cal-glu": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "calciquid": "2",
 "citranatal assure": "2",
 "choline salicylate": "2",
 "chem-sol": "2",
 "calci mix": "2",
 "citranatal dha": "2",
 "concept ob": "2",
 "cafgesic forte": "2",
 "complete natal dha": "2",
 "calcifol": "2",
 "chromagen forte": "2",
 "calcarb": "2",
 "cascara sagrada/magnesium hydroxide": "2",
 "cholecalciferol/genistein/zinc glycinate": "2",
 "calcium oyster": "2",
 "conceptionxr msf": "2",
 "cystemms-v": "2",
 "clusimar": "2",
 "carisoprodol compound": "2",
 "companion multi": "2",
 "citranatal rx": "2",
 "calcium, magnesium and zinc": "2",
 "calcium acetate/magnesium carbonate": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "complete a-z": "2",
 "cerovite liquid": "2",
 "calcium/vitamin d": "2",
 "copper gluconate": "2",
 "cope": "2",
 "certa-vite": "2",
 "calcium concentrate": "2",
 "certavite with lutein": "2",
 "caltrate 600+d plus minerals": "2",
 "caffeine/magnesium salicylate": "2",
 "cavan-folate dha": "2",
 "compete": "2",
 "citranatal b-calm": "2",
 "calvite p": "2",
 "calphron": "2",
 "calphosan": "2",
 "corvite fe": "2",
 "celebrex": "2",
 "chromagen fa": "2",
 "chelated magnesium": "2",
 "calcium glycerophosphate/calcium lactate": "2",
 "citracal plus heart health": "2",
 "centrum ultra men's": "2",
 "citracal slow release 1200": "2",
 "corvita": "2",
 "calcium 600 d": "2",
 "calcium acetate": "2",
 "citracal prenatal + dha": "2",
 "complete natal": "2",
 "citroma": "2",
 "calcium glubionate": "2",
 "calcium liquid softgel": "2",
 "citranatal 90 dha": "2",
 "conceptionxr rhf": "2",
 "certagen": "2",
 "centrum ultra women's": "2",
 "cavan one": "2",
 "calcium citrate": "2",
 "caltrate gummy bites": "2",
 "caltrate": "2",
 "caltro": "2",
 "cerovite advanced formula": "2",
 "calci-chew": "2",
 "cambia": "2",
 "chooz": "2",
 "calcet plus": "2"}, "b": {"b c powder": "2",
 "berocca plus": "2",
 "bayer extra strength back &amp; body": "2",
 "by-ache": "2",
 "bayer advanced aspirin": "2",
 "bee-zee": "2",
 "bc headache": "2",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "bioflavonoids/zinc glycinate": "2",
 "bugs bunny complete": "2",
 "bufferin": "2",
 "be-flex plus": "2",
 "buffered aspirin": "2",
 "betamed": "2",
 "bonisara": "2",
 "bayer aspirin with heart advantage": "2",
 "bisacodyl/magnesium citrate": "2",
 "biotin forte with zinc": "2",
 "butalbital compound": "2",
 "bayer am": "2",
 "bromfenac": "2",
 "bifera": "2",
 "bextra": "2",
 "berkley and jensen acid controller maximum strength": "1",
 "beelith": "2",
 "becomax rx": "2",
 "bumetanide": "2",
 "bayer pm": "2",
 "bayer aspirin extra strength plus": "2",
 "b c powder arthritis strength": "2",
 "b-plex plus minerals": "2",
 "buffex": "2",
 "bayer women's low dose plus calcium": "2",
 "bayer aspirin": "2",
 "bugs bunny with iron chewable": "2",
 "b-nexa": "2",
 "bufferin arthritis strength": "2",
 "buffasal": "2",
 "bufferin extra strength": "2",
 "bc fast pain relief": "2",
 "bladder 2.2": "2",
 "biferarx": "2",
 "bayer women's aspirin with calcium": "2",
 "berplex plus": "2",
 "bayer aspirin regimen": "2",
 "bacmin": "2",
 "bp multinatal plus chewables": "2",
 "bright beginnings": "2",
 "basaljel": "2",
 "bayer select backache pain formula": "2",
 "bayer children's aspirin": "2",
 "bumex": "2",
 "bufferin low dose": "2",
 "berkley and jensen acid reducer maximum strength": "1"}, "e": {"equi-natal plus": "2",
 "eliphos": "2",
 "ecotrin": "2",
 "ecotrin maximum strength": "2",
 "excedrin extra strength": "2",
 "easprin": "2",
 "ecee plus": "2",
 "exjade": "3",
 "elppa daily": "2",
 "evac-q-kwik": "2",
 "ellis tonic sherry": "2",
 "edecrin": "2",
 "equilet": "2",
 "edge ob": "2",
 "equicyte plus": "2",
 "ec-naprosyn": "2",
 "excedrin back &amp; body": "2",
 "elite ob with dha": "2",
 "encora": "2",
 "ed-flex": "2",
 "elemental iron": "2",
 "elite ob 400": "2",
 "excedrin migraine": "2",
 "endodan": "2",
 "eldercaps": "2",
 "extra strength bayer": "2",
 "ex-lax milk of magnesia": "2",
 "etodolac": "2",
 "extra strength mylanta calci tabs": "2",
 "entercote": "2",
 "ecpirin": "2",
 "equagesic": "2",
 "emagrin": "2",
 "entaprin": "2",
 "equi-natal z": "2",
 "ethacrynic acid": "2",
 "empirin with codeine": "2",
 "equi-cyte f": "2",
 "ed cyte f": "2",
 "equi-natal rx": "2",
 "empirin": "2",
 "eye health formula": "2",
 "equi-natal m": "2",
 "elemental iron-90": "2",
 "equi-natal care": "2",
 "essentia": "2",
 "equaline heartburn relief": "1",
 "excedrin": "2",
 "ezfe": "2",
 "equaline acid reducer": "1",
 "elon matrix 5000 complete": "2",
 "esomeprazole/naproxen": "2",
 "eldertonic": "2",
 "equi-roca plus": "2",
 "equinatal 90": "2",
 "embrex 600": "2",
 "effervescent pain relief": "2",
 "ecotrin adult low strength": "2",
 "excedrin menstrual complete": "2"}, "d": {"darvon compound 32": "2",
 "duet dha": "2",
 "dialyvite 3000": "2",
 "disney winnie the pooh gummies": "2",
 "duexis": "2",
 "doans pills extra strength": "2",
 "dual action complete": "2",
 "deferasirox": "3",
 "daypro": "2",
 "dical-d": "2",
 "daily multiple for women 50+": "2",
 "diclofenac": "2",
 "damason-p": "2",
 "daily-vite weight control": "2",
 "dolsed": "2",
 "duet chewable": "2",
 "disalcid": "2",
 "darpaz": "2",
 "demadex": "2",
 "daily multiple for women": "2",
 "diflunisal": "2",
 "durabac forte": "2",
 "diasorb": "2",
 "dualvit ob": "2",
 "durabac": "2",
 "dialyvite 800 with zinc": "2",
 "dialyvite 5000": "2",
 "daily multi-vitamins with minerals": "2",
 "dristan sinus": "2",
 "demadex iv": "2",
 "diarrest": "2",
 "diurex": "2",
 "disney winnie the pooh complete": "2",
 "disney winnie the pooh with extra c": "2",
 "duet dha ec": "2",
 "darcalma": "2",
 "doan's pills": "2",
 "di-gon ii": "2",
 "daily multiple for men 50+": "2",
 "dialume": "2",
 "diatx zn": "2",
 "dolobid": "2",
 "di-gel lemon": "2",
 "diaqua-2": "2",
 "duract": "2",
 "diavite plus": "2",
 "dewees carminative": "2",
 "dialyvite 800 ultra d": "2",
 "darvon compound-65": "2",
 "duraxin": "2",
 "dulcolax milk of magnesia": "2",
 "dermavite": "2",
 "di-gel mint": "2",
 "dical captabs": "2",
 "dolomite": "2",
 "didanosine": "2",
 "decagen": "2",
 "duet dha complete": "2",
 "dialyvite with zinc rx": "2",
 "doans pm": "2",
 "dicalphos plus d": "2",
 "daily combo": "2",
 "donnagel": "2",
 "docusate/ferrous fumarate": "2",
 "dicarbosil": "2",
 "diatx fe": "2",
 "dayalets plus iron": "2",
 "diphenhydramine/ibuprofen": "2",
 "dihydroxyaluminum sodium carbonate": "2",
 "deprizine": "1",
 "dolorex": "2",
 "diclofenac/misoprostol": "2",
 "dulcolax bowel cleansing": "2",
 "dewitt's pain reliever": "2",
 "di-gel": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "duet dha with ferrazone": "2",
 "daily-vite with iron": "2",
 "duet": "2",
 "dialyvite": "2",
 "docosavit": "2"}, "g": {"gevrabon": "2",
 "gentle iron": "2",
 "gold age liquid vitamins and minerals": "2",
 "genpril": "2",
 "gevratonic": "2",
 "genprin": "2",
 "gaviscon regular strength tablets": "2",
 "good sense children's vitamins with iron": "2",
 "genace": "2",
 "gaviscon regular strength liquid": "2",
 "gaviscon extra strength liquid": "2",
 "gelusil": "2",
 "goody's extra-strength headache powders": "2",
 "geri-tonic": "2",
 "generix-t": "2",
 "goody's body pain": "2",
 "gas-x with maalox extra strength": "2",
 "gesticare dha dr": "2",
 "gynovite": "2",
 "gaviscon extra relief formula": "2",
 "glutofac-mx": "2",
 "gennin-fc": "2",
 "glutofac-zx": "2",
 "goodys headache powders": "2",
 "gesticare dha": "2",
 "genaton": "2",
 "geravim": "2",
 "garfield vitamin with iron": "2",
 "galzin": "2",
 "geritol extend": "2",
 "genacote": "2",
 "goodys extra strength": "2",
 "gas-x with maalox": "2",
 "garfield complete vitamins": "2",
 "genasan": "2",
 "geritol complete": "2",
 "gaviscon-2": "2",
 "geri-tabs": "2",
 "geritol": "2",
 "gesticare": "2",
 "gentamicin": "2",
 "gerivite liquid": "2",
 "gaviscon extra strength tablets": "2",
 "garamycin": "2",
 "generet-500 with folic acid": "2",
 "genaton chewable": "2"}, "f": {"fluxid": "1",
 "fer-iron": "2",
 "femiron multi with iron": "2",
 "ferro-caps": "2",
 "folgard os": "2",
 "ferrex 150 forte": "2",
 "ferrocite plus": "2",
 "fiorinal": "2",
 "ferrous fumarate": "2",
 "fasprin": "2",
 "ferrovite fa": "2",
 "foltrin": "2",
 "fetrin": "2",
 "ferrex-150": "2",
 "foltabs plus dha": "2",
 "ferrous fumarate/folic acid": "2",
 "ferrocite": "2",
 "ferra t.d. caps": "2",
 "ferrocite f": "2",
 "ferrous ds": "2",
 "ferralet": "2",
 "fe-tinic 150 forte": "2",
 "famotidine": "1",
 "fruity chews with iron": "2",
 "femecal ob": "2",
 "foltabs prenatal plus dha": "2",
 "ferrousal": "2",
 "ferocon": "2",
 "folbecal": "2",
 "ferrex 28": "2",
 "ferbee": "2",
 "fero-gradumet filmtab": "2",
 "ferretts ips": "2",
 "fe-stool": "2",
 "ferro-time": "2",
 "ferrex pc forte": "2",
 "first mouthwash blm": "2",
 "fer-gen-sol": "2",
 "ferrous sulfate": "2",
 "fiorinal with codeine iii": "2",
 "ferotrinsic": "2",
 "folivan-prx dha": "2",
 "femecal ob plus dha": "2",
 "folcaps omega 3": "2",
 "folivan-ec dha": "2",
 "feldene": "2",
 "ferus pic-150": "2",
 "fast acting mylanta": "2",
 "ferro-sequels": "2",
 "fe 50": "2",
 "ferosul": "2",
 "fosfree": "2",
 "fortabs": "2",
 "fenoprofen": "2",
 "ferralet 90": "2",
 "femnatal": "2",
 "foltabs": "2",
 "foli-iron": "2",
 "ferro-dss": "2",
 "frenadol": "2",
 "ferretts": "2",
 "fosrenol": "2",
 "florical": "2",
 "femiron": "2",
 "feosol": "2",
 "femtabs": "2",
 "folivan-ob": "2",
 "formula b plus": "2",
 "ferocyl": "2",
 "fiortal": "2",
 "ferra-td": "2",
 "ferate": "2",
 "fem-natal": "2",
 "fe-40": "2",
 "ferrous fumarate/folic acid/iron polysaccharide": "2",
 "ferrous fumarate/iron polysaccharide": "2",
 "ferragen": "2",
 "ferrovite forte": "2",
 "folivan-plus": "2",
 "folcaps care one": "2",
 "ferra-cap": "2",
 "feostat": "2",
 "feratab": "2",
 "famotidine/ibuprofen": "2",
 "furosemide": "2",
 "ferrex 150 plus": "2",
 "fe caps": "2",
 "folpace rx": "2",
 "fumasorb": "2",
 "ferrogels forte": "2",
 "foltabs 90 plus dha": "2",
 "ferrous gluconate": "2",
 "flintstones gummies": "2",
 "feosol iron": "2",
 "fero-grad-500": "2",
 "farbital": "2",
 "ferrimin 150": "2",
 "fosteum": "2",
 "ferotrin": "2",
 "ferrospace": "2",
 "flintstones with iron chewable": "2",
 "fe c tab plus": "2",
 "ferrets": "2",
 "fe-tinic 150": "2",
 "ferro-bob": "2",
 "fergon": "2",
 "folbee plus cz": "2",
 "foltabs prenatal": "2",
 "flintstones with calcium": "2",
 "feosol caplet": "2",
 "folivan-f": "2",
 "fiorinal with codeine": "2",
 "feogen": "2",
 "fero-folic 500": "2",
 "folitab 500": "2",
 "fiortal with codeine": "2",
 "formula twenty-one": "2",
 "ferrex 150 forte plus": "2",
 "flintstones complete": "2",
 "ferroflex-150 forte": "2",
 "folcal dha": "2",
 "flurbiprofen": "2",
 "feocyte": "2",
 "ferrovite": "2",
 "ferro basic": "2",
 "fiormor": "2",
 "fumatinic": "2",
 "ferraplus": "2",
 "fer-in-sol": "2",
 "ferrous sulfate/folic acid": "2"}, "i": {"iron polysaccharide": "2",
 "i-l-x": "2",
 "icaps lutein &amp; omega-3": "2",
 "iromin g": "2",
 "ircon-fa": "2",
 "ibuprofen": "2",
 "icaps tr": "2",
 "ibuprofen pmr": "2",
 "idenal": "2",
 "iberet liquid": "2",
 "iron gluconate": "2",
 "ibuprofen/oxycodone": "2",
 "i-vite": "2",
 "icar prenatal chewable calcium": "2",
 "i-sense": "2",
 "icaps plus": "2",
 "irofol": "2",
 "inatal advance": "2",
 "intrinsitinic": "2",
 "ibudone": "2",
 "ibuprofen/pseudoephedrine": "2",
 "icaps mv": "2",
 "icare prenatal rx": "2",
 "integra f": "2",
 "icar-c plus": "2",
 "icar-c plus sr": "2",
 "indocin": "2",
 "iberet-500": "2",
 "iferex 150 forte": "2",
 "indocin iv": "2",
 "iron sulfate": "2",
 "inatal ultra": "2",
 "irospan 24/6": "2",
 "ibu-200": "2",
 "iron protein succinylate": "2",
 "iberet-folic-500": "2",
 "iro-plex": "2",
 "icar": "2",
 "icaps areds": "2",
 "icar prenatal": "2",
 "iron fumarate": "2",
 "iberet": "2",
 "icaps": "2",
 "icaps with lutein and zeaxan": "2",
 "iferex 150": "2",
 "iosopan": "2",
 "ibc 500": "2",
 "integra plus": "2",
 "iron-150": "2",
 "iron chews": "2",
 "indocin sr": "2",
 "i-vite protect": "2",
 "i-l-x and b12": "2",
 "indomethacin": "2",
 "infanate dha": "2",
 "ibu-tab": "2",
 "ibu-4": "2",
 "i-fol plus": "2",
 "ibu-6": "2",
 "ibu-8": "2",
 "integra": "2",
 "ibu": "2",
 "ircon": "2",
 "i-sense occushield": "2"}, "h": {"hyophen": "2",
 "hemocyte-f": "2",
 "hemocyte plus": "2",
 "hemocyte-c": "2",
 "hemocyte": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "heartburn antacid extra strength": "2",
 "heme iron polypeptide/iron polysaccharide": "2",
 "hydrocodone/ibuprofen": "2",
 "hematogen fa": "2",
 "hemocyte-f elixir": "2",
 "hematogen forte": "2",
 "hemaspan": "2",
 "haltran": "2",
 "hytinic": "2",
 "hi-nate 90": "2",
 "hematinic plus": "2",
 "heme iron polypeptide": "2",
 "halfprin": "2",
 "haley's m-o": "2",
 "hematinic with folic acid": "2",
 "heartburn relief": "1",
 "hair booster": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hematogen": "2",
 "heartline": "2",
 "high potency": "2",
 "hemax": "2"}, "k": {"kaodene nn suspension": "2",
 "kneerelief": "2",
 "ka-pec": "2",
 "kalcinate": "2",
 "kantrex": "2",
 "kao-spen": "2",
 "kao-tin advanced formula": "2",
 "k-pec": "2",
 "kaolin/pectin": "2",
 "kaopectate caplets": "2",
 "kaolin": "2",
 "ketoprofen": "2",
 "kanamycin": "2",
 "kao-pulgite": "2",
 "kapectolin": "2",
 "kaopek": "2",
 "k-c suspension": "2",
 "kolnatal dha": "2",
 "ketorolac": "2"}, "m": {"mylanta ar": "1",
 "mynatal ultracap": "2",
 "maxivision eye formula": "2",
 "martinic": "2",
 "maxivision whole body formula": "2",
 "marthritic": "2",
 "maternity": "2",
 "multivitamin, prenatal": "2",
 "mynatal rx": "2",
 "maoson": "2",
 "magdelay": "2",
 "maalox advanced maximum strength": "2",
 "magnesium oxide": "2",
 "magsal": "2",
 "milantex maximum strength": "2",
 "magnebind 400 rx": "2",
 "mhp-a": "2",
 "mi-acid ii": "2",
 "maxinate": "2",
 "mynatal": "2",
 "mykidz iron": "2",
 "my-a-multi": "2",
 "mynate 90 plus": "2",
 "mylanta ultra": "2",
 "magaldrate plus suspension": "2",
 "multi-betic": "2",
 "medique pain-off": "2",
 "midol extended relief": "2",
 "magnesium carbonate": "2",
 "mynatal z": "2",
 "magaldrate": "2",
 "multivitamin with iron": "2",
 "monocal": "2",
 "m-vit": "2",
 "multi-nate dha": "2",
 "mag-g": "2",
 "maalox advanced maximum strength chewable": "2",
 "motrin infant drops": "2",
 "multilex": "2",
 "mylanta fast acting": "2",
 "maalox max wild berry": "2",
 "myferon 150 forte": "2",
 "motrin childrens cold": "2",
 "mylagen-ii": "2",
 "maggel": "2",
 "magan": "2",
 "mobic": "2",
 "myogesic": "2",
 "midol maximum strength cramp formula": "2",
 "mte-6": "2",
 "mte-7": "2",
 "mte-4": "2",
 "mag-sr": "2",
 "mission prenatal hp": "2",
 "mynatal pn forte": "2",
 "mynatal plus": "2",
 "maxaron forte": "2",
 "mag-200": "2",
 "mylagen": "2",
 "maalox max quick dissolve": "2",
 "multiple trace element neonatal": "2",
 "myadec": "2",
 "minitabs": "2",
 "maalox": "2",
 "midol traditional": "2",
 "milantex": "2",
 "midol ib": "2",
 "multe-pak-5": "2",
 "magnesium hydroxide/mineral oil": "2",
 "magonate natal": "2",
 "multi-nate 30 kit": "2",
 "mission prenatal": "2",
 "multifol": "2",
 "multi-delyn with iron": "2",
 "mefenamic acid": "2",
 "mi-acid double strength": "2",
 "mag-phen": "2",
 "mag-tab sr": "2",
 "magaant": "2",
 "maternity vitamin low iron": "2",
 "mte-4 concentrated": "2",
 "mediplex ultra": "2",
 "mar-zinc": "2",
 "maternity-90": "2",
 "magnesiocard": "2",
 "magonate tablets": "2",
 "mintox extra strength": "2",
 "multitrace-4 pediatric": "2",
 "mg plus protein": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "masanti ds": "2",
 "multifol plus": "2",
 "multitrace-4 concentrate": "2",
 "mag-carb": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "multi vita bets and fluoride and iron": "2",
 "mycifradin": "2",
 "megavite rx": "2",
 "maginex ds": "2",
 "maalox advanced regular strength": "2",
 "multigen": "2",
 "marnatal-f": "2",
 "mte-5": "2",
 "magnebind 200": "2",
 "mission prenatal rx": "2",
 "maldroxal plus": "2",
 "magnesium gluconate": "2",
 "mono-gesic": "2",
 "mynatal fc": "2",
 "mylanta supreme": "2",
 "maxivision eye &amp; body formula": "2",
 "milk of magnesia": "2",
 "multi-nate 30": "2",
 "motrin": "2",
 "magnesium salicylate": "2",
 "maalox junior relief chewable": "2",
 "mi-c-t": "2",
 "mag-sr with calcium": "2",
 "multigen folic": "2",
 "mintox plus": "2",
 "mobigesic": "2",
 "maalox regular strength": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "mykidz iron 10": "2",
 "multiple trace element": "2",
 "migralex": "2",
 "motrin ib": "2",
 "magnesium aspartate": "2",
 "magnesium amino acids chelate": "2",
 "maternal 90": "2",
 "mintox maximum strength": "2",
 "multiret folic 500": "2",
 "maginex": "2",
 "mst": "2",
 "multivitamin with iron and fluoride": "2",
 "micrainin": "2",
 "meclofenamate": "2",
 "maalox plus": "2",
 "meloxicam": "2",
 "mag-ox": "2",
 "myferon 150": "2",
 "multi-nate 30 dha": "2",
 "multinatal plus": "2",
 "mag-caps": "2",
 "msp-blu": "2",
 "maalox quick dissolve extra strength": "2",
 "multigen plus": "2",
 "multi-nate dha extra": "2",
 "multitrace-4 neonatal": "2",
 "mylanta ultimate strength": "2",
 "marblen": "2",
 "maxivision ocular formula": "2",
 "mylanta child": "2",
 "maalox children's relief": "2",
 "multitrace-5 concentrate": "2",
 "mylanta ds fast acting": "2",
 "motrin ib sinus": "2",
 "masanti": "2",
 "magnebind 300": "2",
 "magnesium citrate": "2",
 "mult-ferr folic": "2",
 "medi-seltzer": "2",
 "momentum": "2",
 "mol-iron": "2",
 "multe-pak-4": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "mag-ox 400": "2",
 "maalox tc": "2",
 "mi-acid": "2",
 "motrin cold and flu": "2",
 "multilex-t/m+minerals": "2",
 "mylanta": "2",
 "magaldrate/simethicone": "2",
 "multitrace-4": "2",
 "magtrate": "2",
 "mykidz iron fl": "2",
 "menadol": "2",
 "multi-day plus minerals": "2",
 "micro-zn": "2",
 "magna-c-7 forte": "2",
 "marnatal-f plus": "2",
 "mens pack": "2",
 "mobidin": "2",
 "mynatal pn": "2",
 "mag-oxide": "2",
 "motrin sinus headache": "2",
 "mte-5 concentrated": "2",
 "myvitalife": "2",
 "maalox max": "2",
 "multivitamin with minerals": "2",
 "magnesium chloride": "2",
 "mylanta maximum strength": "2",
 "motrin pm": "2",
 "mission prenatal fa": "2",
 "motrin migraine pain": "2",
 "maalox antacid antigas regular strength": "2",
 "mintox": "2",
 "magonate": "2",
 "maternity plus beta carotene": "2",
 "medique medi-seltzer": "2",
 "motrin junior strength": "2",
 "multibret folic 500": "2",
 "motrin childrens": "2",
 "multitrace-5": "2",
 "materna": "2",
 "mintox tablets": "2",
 "magnesium lactate": "2",
 "meclomen": "2",
 "mag 64": "2",
 "mylanta gelcap": "2",
 "magmin": "2",
 "multi-day with calcium and extra iron": "2",
 "maalox hrf": "2"}, "l": {"litecoat aspirin": "2",
 "losospan plus": "2",
 "lanthanum carbonate": "2",
 "lodine": "2",
 "low dose asa": "2",
 "lowsium plus": "2",
 "levacet": "2",
 "leader naproxen sodium": "2",
 "lydia e. pinkham": "2",
 "lodine xl": "2",
 "lysiplex plus": "2",
 "lortab asa": "2",
 "livitrinsic-f": "2",
 "limbrel 250": "2",
 "losospan": "2",
 "lobac": "2",
 "lasix": "2",
 "l-tonic": "2",
 "lowsium": "2",
 "lansoprazole/naproxen": "2",
 "loso prep bowel cleansing system": "2",
 "lactocal-f": "2",
 "lydia pinkham": "2",
 "lo-aqua": "2",
 "limbrel 500": "2",
 "liquiprep": "2",
 "laniroif": "2",
 "leg-gesic": "2",
 "leader acid reducer": "1"}, "o": {"orphengesic": "2",
 "obegyn": "2",
 "ob complete with dha": "2",
 "one-a-day within": "2",
 "opti-gen": "2",
 "oyst cal": "2",
 "o-cal-d": "2",
 "optinate": "2",
 "ob complete premier": "2",
 "oysco 500 with d": "2",
 "oyster-d": "2",
 "oysco d with calcium": "2",
 "orphengesic forte": "2",
 "os-cal": "2",
 "ob natal one": "2",
 "obtrex dha": "2",
 "oystercal-d": "2",
 "orudis": "2",
 "ocuvite preservision": "2",
 "one daily with minerals": "2",
 "ocuvite": "2",
 "one tab daily with minerals": "2",
 "one-a-day vitacraves": "2",
 "oxaprozin": "2",
 "os-cal 500 + d": "2",
 "optimum magnesium gluconate": "2",
 "one-a-day max": "2",
 "one-a-day weightsmart": "2",
 "oyster cal": "2",
 "oyst cal 500": "2",
 "occuplex": "2",
 "ocuvite extra": "2",
 "one tab daily with iron": "2",
 "oyster cal 500": "2",
 "oyster shell calcium 500": "2",
 "ob-20": "2",
 "one-a-day women": "2",
 "os-cal 500": "2",
 "oysco d": "2",
 "optivite pmt": "2",
 "oruvail": "2",
 "oyster shell calcium": "2",
 "ob complete": "2",
 "ostiva": "2",
 "one-a-day men 50 plus": "2",
 "o-cal prenatal": "2",
 "oyster": "2",
 "one-a-day women 50 plus": "2",
 "os-cal ultra": "2",
 "orudis kt": "2",
 "oyster shell": "2",
 "ob complete 400": "2",
 "obnate 90": "2",
 "oyst-cal-d": "2",
 "optilets-m-500": "2",
 "osteocit d plus": "2",
 "oyster calcium": "2",
 "orazinc": "2",
 "oyster shell calcium with vitamin d": "2",
 "one-a-day men pro edge": "2",
 "obtrex": "2",
 "ocuvite lutein": "2",
 "os-cal 500 + extra d": "2",
 "oysco 500": "2",
 "o-cal fa": "2"}, "n": {"nutrispire": "2",
 "natalcare advanced": "2",
 "naprosyn": "2",
 "natalcare pic forte": "2",
 "natelle prefer": "2",
 "nexcede": "2",
 "nu-iron v": "2",
 "natalcare": "2",
 "niferex-pn": "2",
 "naprelan": "2",
 "nicotinamide zcf": "2",
 "neevo": "2",
 "nutrinate": "2",
 "natelle-ez": "2",
 "nata 29 ob": "2",
 "niferex elixir": "2",
 "natacaps": "2",
 "novastart": "2",
 "nanovm": "2",
 "natelle one": "2",
 "nephro-fer": "2",
 "niferex": "2",
 "novaferrum": "2",
 "nata 29 prenatal": "2",
 "novasal": "2",
 "nestabs rx": "2",
 "neoprofen": "2",
 "natalcare glosstabs": "2",
 "nu-iron plus": "2",
 "neo-tab": "2",
 "nuprin backache caplet": "2",
 "nestabs fa": "2",
 "natelle": "2",
 "neomycin": "2",
 "nu-iron": "2",
 "norgesic forte": "2",
 "nu-iron 150": "2",
 "natafolic-ob": "2",
 "nestabs": "2",
 "natalcare rx": "2",
 "netromycin": "2",
 "nizatidine": "1",
 "natelle one dha": "2",
 "new advanced formula prenatal z": "2",
 "niferex-150 forte": "2",
 "norisodrine with calcium iodine": "2",
 "natatab fa": "2",
 "niferex-150": "2",
 "nutiifac zx": "2",
 "nebcin": "2",
 "natarex": "2",
 "nalfon": "2",
 "novanatal": "2",
 "natatab rx": "2",
 "nuprin": "2",
 "natalins rx": "2",
 "nephro calci": "2",
 "niferex gold": "2",
 "neevo dha": "2",
 "naproxen sodium ds": "2",
 "nephro-fer rx": "2",
 "natelle c": "2",
 "neotrace-4": "2",
 "natatab cfe": "2",
 "nephro-vite with fe": "2",
 "niferex pn forte": "2",
 "natalcare advanced-rf": "2",
 "nic 750": "2",
 "natalcare plus": "2",
 "neo-fradin": "2",
 "neo-forte": "2",
 "naproxen/sumatriptan": "2",
 "norwich aspirin": "2",
 "natachew": "2",
 "natelle plus with dha": "2",
 "natafolic-pn": "2",
 "norgesic": "2",
 "nature's blend theratrum complete tablets 50 plus": "2",
 "natalfirst": "2",
 "naproxen": "2",
 "nebcin pediatric": "2",
 "nicomide": "2",
 "nabumetone": "2",
 "nexa select with dha": "2",
 "nestabs cbf": "2",
 "neo-calglucon": "2",
 "netilmicin": "2",
 "nephrox": "2",
 "norlac rx": "2",
 "nutravance": "2",
 "natalcare pic": "2",
 "natalcare cfe 60": "2",
 "natalcare three": "2",
 "naproxen/pseudoephedrine": "2",
 "natafort": "2",
 "natalins": "2",
 "nephron-fa": "2",
 "nicazel": "2"}, "q": {"quinapril": "2",
 "q-profen": "2",
 "quinaretic": "2"}, "p": {"phosphasal": "2",
 "poly iron forte": "2",
 "pr natal 440": "2",
 "phillips' cramp-free": "2",
 "phosenamine": "2",
 "paire ob plus dha": "2",
 "prenatal low iron": "2",
 "pepcid ac maximum strength": "1",
 "pamprin all day relief": "2",
 "panritis forte": "2",
 "pan ob forte": "2",
 "prenatal mtr with selenium": "2",
 "primacare": "2",
 "prevacid naprapac": "2",
 "polysaccharide iron": "2",
 "proferrin-es": "2",
 "pr natal 400 ec": "2",
 "prenatabs cbf": "2",
 "poly vitamin with fluoride with iron": "2",
 "prenafirst": "2",
 "pepto children's": "2",
 "poly-vi-sol with iron drops": "2",
 "prenatal-u": "2",
 "propoxyphene compound 65": "2",
 "preterna": "2",
 "posture": "2",
 "pnv-total": "2",
 "prenate plus": "2",
 "prenatabs fa": "2",
 "painaid": "2",
 "phillips' haleys m-o": "2",
 "pamprin cramp menstrual pain relief": "2",
 "pramilet fa": "2",
 "pnv-dha plus": "2",
 "promar": "2",
 "poly-vi-sol with iron": "2",
 "primacare advantage": "2",
 "prelief": "2",
 "prenate dha": "2",
 "prenate 90": "2",
 "pms balance": "2",
 "percodan": "2",
 "previte rx": "2",
 "pedte-pak-4": "2",
 "phoslo gelcap": "2",
 "prenavite fc": "2",
 "prosteon": "2",
 "prenatabs obn": "2",
 "prenatal mr 90": "2",
 "prostate 2.4": "2",
 "prevacid naprapac 500": "2",
 "prenatal rx": "2",
 "prenatal 1 plus 1": "2",
 "posture-d h/p": "2",
 "prenate essential": "2",
 "percodan-demi": "2",
 "poly-vi-flor with iron": "2",
 "premesis rx": "2",
 "par-f": "2",
 "pepcid ac chewable tablets": "1",
 "pte-5": "2",
 "pte-4": "2",
 "prefera ob plus dha": "2",
 "prenatal multivitamins": "2",
 "pnv select": "2",
 "pepcid complete": "2",
 "prenate gt": "2",
 "prenate elite plus iron": "2",
 "precare conceive": "2",
 "prenate ultra": "2",
 "prosed ds": "2",
 "pruet dha": "2",
 "prenatal rx 1": "2",
 "precare": "2",
 "p-a-c analgesic": "2",
 "poly iron 150 forte": "2",
 "phoslyra": "2",
 "prenexa": "2",
 "prosight": "2",
 "pedtrace-4": "2",
 "pepcid": "1",
 "prefera ob-one": "2",
 "prenatal z advanced formula": "2",
 "prenate elite": "2",
 "pr natal 400": "2",
 "profe": "2",
 "parepectolin": "2",
 "prenate advance": "2",
 "pepcid rpd": "1",
 "pc-cap": "2",
 "prenatal s": "2",
 "pruvate 21/7": "2",
 "p-a-c": "2",
 "procycle multi vitamin with minerals": "2",
 "ponstel": "2",
 "piroxicam": "2",
 "prenatal h": "2",
 "preque 10": "2",
 "prenatal ad": "2",
 "prenatabs rx": "2",
 "prenavite": "2",
 "phenylbutazone": "2",
 "phoslo": "2",
 "panasal 5/500": "2",
 "prenatal plus with 27 mg iron": "2",
 "prenatal plus": "2",
 "prenacare": "2",
 "prenatal mr 90 fe": "2",
 "prenatal elite": "2",
 "prosed ec": "2",
 "pre-h-cal": "2",
 "prenexa with dha": "2",
 "poly iron": "2",
 "pepcid oral suspension": "1",
 "precare premier": "2",
 "preferaob": "2",
 "prenatal plus with beta-carotene": "2",
 "protegra softgel": "2",
 "pedia-lax chewable tablets": "2",
 "phluorivit with iron": "2",
 "prenate advanced formula": "2",
 "prenavite pc": "2",
 "prenazyme 1+1": "2",
 "pepcid ac": "1",
 "phytase/zinc citrate": "2",
 "prenaplus": "2",
 "prevacid naprapac 375": "2",
 "pronemia": "2",
 "pr natal 430": "2",
 "prenate essential dha": "2",
 "pnv-dha": "2",
 "preservision": "2",
 "prenatal plus iron": "2",
 "pepcid ac maximum strength tablets": "1",
 "pamprin max menstrual pain relief": "2",
 "pravigard pac": "2",
 "probarimin qt": "2",
 "proferrin-forte": "2",
 "primacare one": "2",
 "prenatal 19": "2",
 "phillips' milk of magnesia": "2"}, "s": {"sele-pak": "2",
 "sesame st. vitamins plus iron": "2",
 "saleto": "2",
 "surbex-750 with zinc": "2",
 "suplevit": "2",
 "se-care conceive": "2",
 "sourcecf abdek": "2",
 "senetonic": "2",
 "surpass": "2",
 "slow release iron": "2",
 "senilezol": "2",
 "sourcecf chewables": "2",
 "saleto-800": "2",
 "selenium": "2",
 "stuartnatal plus": "2",
 "sloprin": "2",
 "support 500": "2",
 "st. joseph aspirin": "2",
 "slow fe with folic acid": "2",
 "sss": "2",
 "scot-tussin original": "2",
 "selepen": "2",
 "sudafed 12 hour pressure+pain": "2",
 "stanback fast pain relief": "2",
 "stuartnatal plus 3": "2",
 "st. joseph 81 mg chewable aspirin": "2",
 "strovite advance": "2",
 "slow-mag": "2",
 "sucralfate": "2",
 "super calcium": "2",
 "salsalate": "2",
 "stress formula with zinc": "2",
 "saleto-d": "2",
 "se-natal 16": "2",
 "synalgos-dc": "2",
 "saleto-600": "2",
 "stresstabs with zinc": "2",
 "se-care": "2",
 "sourcecf multivitamins with a,b,d,e &amp; k plus zinc": "2",
 "se-natal 19": "2",
 "select-ob+dha": "2",
 "sulindac": "2",
 "seton et-ec": "2",
 "sprix": "2",
 "se-tan dha": "2",
 "surpass extra strength": "2",
 "saleto-200": "2",
 "strovite": "2",
 "spectravite senior": "2",
 "simron": "2",
 "sunmark acid reducer maximum strength": "1",
 "sourcecf pediatric drops": "2",
 "strovite plus": "2",
 "stuart prenatal with beta carotene": "2",
 "sedecal d": "2",
 "support": "2",
 "se-natal 90": "2",
 "soma compound with codeine": "2",
 "sourcecf softgels": "2",
 "sodium edecrin": "2",
 "sss tonic": "2",
 "sodium salicylate": "2",
 "soma compound": "2",
 "stanback analgesic": "2",
 "strongstart": "2",
 "seton et": "2",
 "select-ob": "2",
 "st. joseph 81 mg aspirin enteric safety-coated": "2",
 "se-plete dha": "2",
 "stress 600 with zinc": "2",
 "strovite advance+d": "2",
 "super theravite-m": "2",
 "super high vitamins and minerals": "2",
 "spectravite cardio health": "2",
 "salflex": "2",
 "siderol": "2",
 "septopal": "2",
 "sine-aid ib": "2",
 "stresstabs with iron": "2",
 "saleto-400": "2",
 "se-natal one": "2",
 "se-vate": "2",
 "salsitab": "2",
 "stress formula with iron": "2",
 "sesame st vitamins complete": "2",
 "sodium thiosalicylate": "2",
 "selenium tr": "2",
 "sunkist child chewable with iron": "2",
 "supac": "2",
 "strovite one": "2",
 "strovite forte": "2",
 "surbex-750 with iron": "2",
 "slow fe": "2",
 "streptomycin": "2"}, "r": {"robaxisal": "2",
 "ri-mag": "2",
 "re fac-x": "2",
 "renate": "2",
 "repliva 21/7": "2",
 "royvac bowel evacuant": "2",
 "re dualvit f": "2",
 "ron-acid plus": "2",
 "re ob plus dha": "2",
 "rexavite 150": "2",
 "rolaids regular strength": "2",
 "rx support heartburn and acid reflux": "2",
 "ru-lets m 500": "2",
 "rexolate": "2",
 "rulox": "2",
 "re ob 90 plus dha": "2",
 "req49+": "2",
 "rofecoxib": "2",
 "riopan plus": "2",
 "renacidin irrgiation": "2",
 "resource optisource": "2",
 "riopan": "2",
 "re dualvit plus": "2",
 "renacidin": "2",
 "risanoid plus": "2",
 "renaplex": "2",
 "riopan plus double strength": "2",
 "rolaids extra strength softchews": "2",
 "renatabs with iron": "2",
 "renate dha extra": "2",
 "rheaban maximum strength": "2",
 "rolaids extra strength plus gas relief softchews": "2",
 "recal d": "2",
 "rhinocaps": "2",
 "rulox 1": "2",
 "rolaids multi-symptom": "2",
 "rightstep": "2",
 "renate dha": "2",
 "roxiprin": "2",
 "reprexain": "2",
 "risacal-d": "2",
 "rovin-nv dha": "2",
 "reocyte plus": "2",
 "rulox plus": "2",
 "ranitidine": "1",
 "ranitidine bismuth citrate": "1",
 "ridactate": "2",
 "rovin-nv": "2",
 "rufen": "2",
 "rolaids extra strength": "2",
 "rhinogesic": "2",
 "rexavite 150 forte": "2",
 "renax": "2",
 "recal fol d": "2",
 "riopan plus 2": "2",
 "ron acid": "2",
 "relafen": "2",
 "renax 5.5": "2"}, "u": {"uretron": "2",
 "urimax": "2",
 "unicap with iron": "2",
 "ursinus": "2",
 "utrona-c": "2",
 "udamin": "2",
 "utrona": "2",
 "ultra mylanta calci tabs": "2",
 "upcal d": "2",
 "unicap senior": "2",
 "urban ds": "2",
 "uritact ds": "2",
 "uni-lan ii": "2",
 "uro-mag": "2",
 "urimar-t": "2",
 "ultra-natal": "2",
 "urised": "2",
 "utira": "2",
 "unicomplex m": "2",
 "uni-fac zx": "2",
 "urban": "2",
 "uni-lan": "2",
 "ultimatecare one": "2",
 "uretron ds": "2",
 "urapine": "2",
 "udamin sp": "2",
 "uritin": "2",
 "usept": "2",
 "uni-daily plus iron": "2",
 "urisym": "2",
 "ultimatecare combo": "2",
 "uni kar plus c sr": "2",
 "uta": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "ultimatecare one nf": "2",
 "unicap t": "2",
 "uni-thera m with beta carotene": "2",
 "ustell": "2",
 "ultra natalcare": "2",
 "urelle": "2",
 "unicap m": "2",
 "ultimatecare advance": "2",
 "utira-c": "2",
 "uribel": "2"}, "t": {"tobramycin": "2",
 "tolectin 600": "2",
 "titralac plus liquid": "2",
 "tobi": "2",
 "theracal d4000": "2",
 "titralac plus": "2",
 "triveen-one": "2",
 "triadvance": "2",
 "tetra-mag": "2",
 "tums extra strength 750": "2",
 "thera-m enhanced": "2",
 "thera-m": "2",
 "trilisate": "2",
 "tolectin ds": "2",
 "theralith xr": "2",
 "trimagen": "2",
 "therobec plus": "2",
 "tums regular strength": "2",
 "theragran hematinic": "2",
 "theravim m": "2",
 "t-lite": "2",
 "toradol": "2",
 "taron-prx plus dha": "2",
 "trinsicon": "2",
 "trinatal rx": "2",
 "tolectin": "2",
 "tri-vi-flor with iron": "2",
 "torsemide": "2",
 "tums dual action": "2",
 "tab-a-vite maximum": "2",
 "tozal": "2",
 "tricare dha one": "2",
 "tandem ob": "2",
 "toradol iv/im": "2",
 "trigels f": "2",
 "tempo": "2",
 "tricare": "2",
 "tridate": "2",
 "trihemic 600": "2",
 "trimagen fa": "2",
 "tums ultra 1000": "2",
 "t-gran plus minerals": "2",
 "triferex 150 forte": "2",
 "tri-buffered aspirin": "2",
 "tricon": "2",
 "tri-vi-sol with iron": "2",
 "talwin compound": "2",
 "therapy bayer": "2",
 "tl icon": "2",
 "tusal": "2",
 "theracal rapid repletion": "2",
 "tl g-fol os": "2",
 "tl-fol 500": "2",
 "tums freshers": "2",
 "ternamar": "2",
 "tums smoothies": "2",
 "theracal d2000": "2",
 "titralac": "2",
 "thera-vite m": "2",
 "tolfrinic": "2",
 "tagamet": "1",
 "tandem": "2",
 "trac tabs 2x": "2",
 "tandem dha": "2",
 "tums plus": "2",
 "tricosal": "2",
 "tab-a-vite weightslim": "2",
 "taron forte": "2",
 "therems m": "2",
 "tandem f": "2",
 "therems h": "2",
 "taladine": "1",
 "therapeutic-m": "2",
 "taron-c dha": "2",
 "tri rx": "2",
 "taron-bc": "2",
 "theragran-m": "2",
 "theragener-m": "2",
 "tandem plus": "2",
 "trimesis rx": "2",
 "theragener-h": "2",
 "tab-a-vite womens formula": "2",
 "tolmetin": "2",
 "tab-a-vite with iron": "2",
 "tums kids": "2",
 "tritec": "1",
 "tri vites with fluoride and iron": "2",
 "toradol im": "2",
 "trinate": "2",
 "taron-ec calc dha pack": "2",
 "triveen-prx rnf": "2",
 "thera hematinic": "2",
 "trace metals": "2",
 "tagamet hb": "1",
 "treximet": "2",
 "trimagen forte": "2"}, "w": {"wellesse liquid calcium with vitamin d": "2",
 "womens pack": "2"}, "v": {"vi-daylin adc with iron": "2",
 "vitalize plus": "2",
 "vinate advanced": "2",
 "verotin-by": "2",
 "viactiv multi-vitamin": "2",
 "vi-zac": "2",
 "vigortol liquid": "2",
 "venatal fa": "2",
 "viactiv calcium flavor glides": "2",
 "vica-forte": "2",
 "vinate care": "2",
 "vitelle irospan": "2",
 "vinate good start": "2",
 "vitanatal ob plus dha": "2",
 "videx ec": "2",
 "vinate az extra": "2",
 "vi-daylin with iron drops": "2",
 "vinate ic": "2",
 "vinate ii": "2",
 "vanquish": "2",
 "videx": "2",
 "vioxx": "2",
 "vita-pms": "2",
 "vitaspire": "2",
 "vinate ultra": "2",
 "vinate 90": "2",
 "vitafol-ob+dha": "2",
 "vitaphil": "2",
 "vitelle nestabs otc": "2",
 "valdecoxib": "2",
 "verazinc": "2",
 "vi-daylin/f adc with iron": "2",
 "vol-nate": "2",
 "voltaren-xr": "2",
 "vicon forte": "2",
 "vi-stress with iron": "2",
 "vitamax": "2",
 "vinatal forte": "2",
 "vinate iii": "2",
 "vital-d": "2",
 "vitaphil plus dha": "2",
 "vitamed prenatal formula": "2",
 "vemavite prx 2": "2",
 "vimovo": "2",
 "vitagen forte": "2",
 "vol-plus": "2",
 "vitaphil aide": "2",
 "vitafol pn": "2",
 "vita-zinc": "2",
 "vita drops with iron": "2",
 "vicoprofen": "2",
 "vita zx": "2",
 "vinacal or": "2",
 "vitron-c": "2",
 "viactiv soft calcium chews": "2",
 "vernate": "2",
 "vi-daylin with iron chewable": "2",
 "vita-dec": "2",
 "vicon plus": "2",
 "vita-pms plus": "2",
 "vinate pn care": "2",
 "voltaren": "2",
 "vitatrum": "2",
 "vernate advanced": "2",
 "vimar with iron": "2",
 "vicap forte": "2",
 "vitagen advance": "2",
 "vinate one": "2",
 "vitafol-ob": "2",
 "viva dha": "2",
 "vicon-c": "2",
 "vol-tab rx": "2",
 "vita-min rx": "2",
 "vitatab mv": "2",
 "vynatal 1 plus 1": "2",
 "vi-daylin with iron": "2",
 "vinate az": "2",
 "v-c forte": "2",
 "vi-daylin/f plus iron": "2",
 "vita s forte": "2",
 "vinate c": "2",
 "vitacon forte": "2",
 "vinate m": "2",
 "vitafol": "2",
 "vinate calcium": "2",
 "vitaplex plus": "2",
 "vynatal fa": "2",
 "vitron-c-plus": "2",
 "viactiv multi-vitamin flavor glides": "2",
 "vinate gt": "2",
 "viogen-c": "2",
 "verotin-gr": "2",
 "vinatal 600": "2"}, "y": {"ysp aspirin": "2",
 "yieronia": "2"}, "z": {"zinc plus lozenges": "2",
 "zinca-pak": "2",
 "zatean-pn dha": "2",
 "zenate prenatal": "2",
 "zitamin": "2",
 "zinc 50 mg pink": "2",
 "zenate": "2",
 "zatean-pn": "2",
 "zantac 25 mg efferdose": "1",
 "zantac 300": "1",
 "zantac efferdose": "1",
 "z-gen": "2",
 "zantac": "1",
 "zinc-220": "2",
 "zenate advanced formula": "2",
 "zero-order release": "2",
 "zincate": "2",
 "zatean-pn plus": "2",
 "ze-plus": "2",
 "zantac geldose": "1",
 "zinc gluconate": "2",
 "zorprin": "2",
 "zipsor": "2",
 "zantac 75": "1",
 "zinc sulfate": "2",
 "z-bec": "2",
 "zincvit": "2",
 "zinc cr": "2",
 "zytaze": "2",
 "zatean-ch": "2",
 "zantac 150 efferdose": "1",
 "zantac 150": "1",
 "zinc acetate": "2",
 "zantac 300 geldose": "1",
 "zodeac-100": "2"}}];