interactions["alfuzosin,uroxatral"]=["alfuzosin,uroxatral", {"4": {"40 winks": "2"}, "a": {"aspirin/hydrocodone": "2",
 "atropine/phenobarbital": "2",
 "azithromycin dose pack": "2",
 "agenerase": "3",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aldoril 25": "2",
 "alfenta": "2",
 "aloxi": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "antispas": "2",
 "aler-dryl": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "adenocard": "2",
 "actiq": "2",
 "aspirin/oxycodone": "2",
 "apo-go pen": "2",
 "advil pm": "2",
 "artemether/lumefantrine": "3",
 "ambien cr": "2",
 "amitriptyline": "2",
 "accesspak for hiv pep expanded with kaletra": "3",
 "ambenyl": "2",
 "acetaminophen/hydrocodone": "2",
 "a-g tussin": "2",
 "aldoril": "2",
 "allfen cdx": "2",
 "amidrine": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "aldoril 15": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "alor 5/500": "2",
 "ami-rax": "2",
 "acetaminophen/caffeine/dihydrocodeine": "2",
 "atacand hct": "2",
 "apraclonidine ophthalmic": "2",
 "abarelix": "2",
 "allergy relief d": "2",
 "azilect": "2",
 "atazanavir": "3",
 "asthmacon": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "alahist lq": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "anhydrous calcium iodide/codeine": "2",
 "adriamycin rdf": "2",
 "accuretic": "2",
 "acetaminophen/butalbital": "2",
 "alprazolam": "2",
 "albuterol/ipratropium": "2",
 "adriamycin": "2",
 "atripla": "2",
 "accesspak for hiv pep expanded with viracept": "3",
 "ascomp with codeine": "2",
 "ambifed-g cd": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "acetaminophen/diphenhydramine/pseudoephedrine": "2",
 "alcohol": "2",
 "avelox": "3",
 "anergan 50": "2",
 "arformoterol": "2",
 "avinza": "2",
 "all day allergy-d": "2",
 "aquachloral supprettes": "2",
 "atenolol": "2",
 "axocet": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "accupril": "2",
 "aspirin/methocarbamol": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "allermax": "2",
 "accuneb": "2",
 "ambophen": "2",
 "albuterol": "2",
 "anoquan": "2",
 "atuss hd": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "afeditab cr": "2",
 "arcet": "2",
 "alagesic": "2",
 "arcapta": "2",
 "alkabel-sr": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "amobarbital": "2",
 "aldex-ct": "2",
 "aquatensen": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "atuss hs": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "aspirin/meprobamate": "2",
 "advair hfa": "2",
 "aralen": "2",
 "acetylcarbromal": "2",
 "aceon": "2",
 "asendin": "2",
 "atuss ex": "2",
 "anexsia": "2",
 "amiodarone": "3",
 "allfen cd": "2",
 "apomorphine": "2",
 "aspirin/butalbital/caffeine": "2",
 "amlodipine/benazepril": "2",
 "adriamycin pfs": "2",
 "airacof": "2",
 "accolate": "2",
 "atuss hx": "2",
 "acetaminophen/dextromethorphan/diphenhydramine": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "alidrin": "2",
 "astemizole": "2",
 "alprazolam intensol": "2",
 "abilify": "2",
 "acetaminophen/oxycodone": "2",
 "aldoril d50": "2",
 "amlobenz": "2",
 "amobarbital/secobarbital": "2",
 "ala-hist": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "asenapine": "2",
 "aspirin/diphenhydramine": "2",
 "aprepitant": "2",
 "aquacot": "2",
 "acetaminophen/dichloralphenazone/isometheptene mucate": "2",
 "ak-beta": "2",
 "adalat": "2",
 "atenolol/chlorthalidone": "2",
 "anacin p.m. aspirin free": "2",
 "antispasmodic": "2",
 "alka-seltzer pm": "2",
 "apokyn": "2",
 "adapin": "2",
 "altace": "2",
 "acetaminophen/codeine": "2",
 "advair diskus": "2",
 "amoxicillin/clarithromycin/lansoprazole": "3",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "antiflex": "2",
 "adalat cc": "2",
 "allergia-c": "2",
 "atamet": "2",
 "azithromycin/trovafloxacin": "2",
 "ambifed cd": "2",
 "alphen expectorant": "2",
 "amytal sodium": "2",
 "allerfrin with codeine": "2",
 "all day allergy children's": "2",
 "alahist dhc": "2",
 "a-cof dh": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "amifostine": "2",
 "alcohol and dextrose injections usp hypertonic": "2",
 "atarax": "2",
 "antrocol": "2",
 "aplenzin": "2",
 "aldoclor-250": "2",
 "atuss ms": "2",
 "apo-go": "2",
 "aceta w/ codeine": "2",
 "alfentanil": "2",
 "acetaminophen pm extra strength": "2",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/pseudoephedrine": "2",
 "atuss g": "2",
 "alphagan p": "1",
 "aldoclor-150": "2",
 "alupent": "2",
 "aspirin/carisoprodol/codeine": "2",
 "aripiprazole": "2",
 "adenosine": "2",
 "aralen phosphate": "2",
 "altaryl": "2",
 "acetaminophen/pentazocine": "2",
 "arsenic trioxide": "3",
 "aminophylline/amobarbital/ephedrine": "2",
 "amoxapine": "2",
 "actifed allergy day/night": "2",
 "ala-hist d": "2",
 "acetaminophen/propoxyphene": "2",
 "alphagan": "1",
 "avalide": "2",
 "aspirin/carisoprodol": "2",
 "acebutolol": "2",
 "ambi 5/15/100": "2",
 "aralen hydrochloride": "2",
 "alagesic lq": "2",
 "all day allergy": "2",
 "anaplex hd": "2",
 "amiloride/hydrochlorothiazide": "2",
 "ambifed-g cdx": "2",
 "astramorph pf": "2",
 "anhydrous calcium iodide/isoproterenol": "2",
 "apresazide": "2",
 "azdone": "2",
 "anafranil": "2",
 "adeno-jec": "2",
 "adenoscan": "2",
 "ambien": "2",
 "avelox i.v.": "3",
 "aventyl hydrochloride": "2",
 "armodafinil": "1",
 "amprenavir": "3",
 "aspirin/butalbital": "2",
 "atapryl": "2",
 "aquazide h": "2",
 "ativan": "2",
 "anzemet": "3",
 "amturnide": "2",
 "aspirin/codeine": "2",
 "airet": "2",
 "aldoril d30": "2",
 "aspirin/pentazocine": "2",
 "azithromycin": "2",
 "abstral": "2",
 "alcohol 5% in dextrose 5%": "2",
 "acetaminophen/diphenhydramine": "2",
 "ala-hist ac": "2",
 "aldactazide": "2",
 "adcirca": "2",
 "alleroff": "2",
 "americet": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "aler-tab": "2",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "2",
 "anolor 300": "2",
 "abilify discmelt": "2",
 "ambifed cdx": "2"}, "c": {"codeine/dexchlorpheniramine/phenylephrine": "2",
 "catapres": "2",
 "chlorothiazide/methyldopa": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "codiclear dh": "2",
 "cartia xt": "2",
 "compazine": "2",
 "chloral hydrate": "2",
 "chemdal expectorant": "2",
 "colrex compound": "2",
 "conivaptan": "3",
 "capozide 50/25": "2",
 "co-tussin": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "coldcough pd": "2",
 "calcidrine": "2",
 "cetirizine/pseudoephedrine": "2",
 "crixivan": "3",
 "cotab ax": "2",
 "codeine/pseudoephedrine": "2",
 "cipro i.v.": "2",
 "codahistine expectorant": "2",
 "cardizem cd": "2",
 "chlorpheniramine/hydrocodone/phenylephrine": "2",
 "chlorthalidone/reserpine": "2",
 "chlorpheniramine/hydrocodone": "2",
 "counteract pm extra strength": "2",
 "carbinoxamine/hydrocodone/pseudoephedrine": "2",
 "citalopram": "3",
 "capoten": "2",
 "cvs allergy &amp; sinus headache": "2",
 "codamine": "2",
 "cotrim": "1",
 "carbidopa/levodopa": "2",
 "cardizem sr": "2",
 "co-trimoxazole": "1",
 "co-gesic": "2",
 "cotuss v": "2",
 "cheracol with codeine": "2",
 "codimal dh": "2",
 "cheratussin dac": "2",
 "coreg cr": "2",
 "clotrimazole": "2",
 "corgard": "2",
 "chlorothiazide/reserpine": "2",
 "calan sr": "2",
 "carbex": "2",
 "cyndal hd": "2",
 "clozapine": "3",
 "carbetapentane/diphenhydramine": "2",
 "capital w/codeine": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "chlorphen hd": "2",
 "cardizem": "2",
 "cisapride": "3",
 "chlorthalidone/clonidine": "2",
 "clonidine er": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "cetirizine": "2",
 "combigan": "2",
 "cyclosporine": "2",
 "celexa": "3",
 "canges-xp": "2",
 "cipro": "2",
 "children's tylenol plus cold and allergy": "2",
 "carbacot": "2",
 "carbinoxamine/hydrocodone/phenylephrine": "2",
 "codafen": "2",
 "codeine/promethazine": "2",
 "conjugated estrogens/meprobamate": "2",
 "cardizem la": "2",
 "codafed": "2",
 "calan": "2",
 "complete allergy": "2",
 "corlopam": "2",
 "chlorpheniramine/guaifenesin/hydrocodone/pseudoephedrine": "2",
 "compazine spansule": "2",
 "codegest expectorant": "2",
 "carbidopa/entacapone/levodopa": "2",
 "catapres-tts": "2",
 "clorpres": "2",
 "cycofed pediatric expectorant": "2",
 "codal-dh syrup": "2",
 "chlordinium": "2",
 "chlordiazepoxide/clidinium": "2",
 "cerubidine": "2",
 "caprelsa": "3",
 "candesartan/hydrochlorothiazide": "2",
 "colrex": "2",
 "chlorpheniramine/hydrocodone/pseudoephedrine": "2",
 "cardura": "2",
 "clopine": "3",
 "cordarone": "3",
 "complera": "2",
 "clarithromycin": "3",
 "clozaril": "3",
 "condasin": "2",
 "carduran": "2",
 "cipro xr": "2",
 "cheratussin ac": "2",
 "capacet": "2",
 "cotabflu": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "clozapine synthon": "3",
 "chlorcyclizine/codeine": "2",
 "centussin dhc": "2",
 "cascor": "2",
 "cafatine pb": "2",
 "chlordiazepoxide": "2",
 "cardioquin": "3",
 "chlordiazepoxide/methscopolamine": "2",
 "cotrim ds": "1",
 "cytuss-hc nr": "2",
 "clonidine": "2",
 "capital with codeine suspension": "2",
 "calm-aid": "2",
 "compro": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "cosopt": "2",
 "co-histine dh": "2",
 "cotrim pediatric": "1",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "cycofed expectorant": "2",
 "codeine/phenylephrine": "2",
 "cocet plus": "2",
 "combivent": "2",
 "cordarone iv": "3",
 "clomipramine": "2",
 "ciprofloxacin": "2",
 "cordron-hc nr": "2",
 "corvert": "3",
 "cardizem monovial": "2",
 "codehist dh": "2",
 "capozide 25/15": "2",
 "chemdal hd": "2",
 "chlorpheniramine/codeine": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "chemtussin hc": "2",
 "chlorthalidone": "2",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "codotuss": "2",
 "chloroquine": "2",
 "cymbalta": "2",
 "cimetidine": "1",
 "chlorpromazine": "2",
 "codamine pediatric": "2",
 "canges-hc": "2",
 "combunox": "2",
 "cyndal expectorant": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "coldcough syrup": "2",
 "clorazepate": "2",
 "carvedilol": "2",
 "cvs allergy &amp; cold": "2",
 "cetiri d": "2",
 "capozide 50/15": "2",
 "combivent respimat": "2",
 "codimal ph": "2",
 "children's triacting night time": "2",
 "corzide": "2",
 "codahistine-dh elixir": "2",
 "cartrol": "2",
 "cosopt pf": "2",
 "clotrimazole troche": "2",
 "cardura xl": "2",
 "cycofed": "2",
 "compoz nighttime sleep aid": "2",
 "chlorzoxazone": "2",
 "co-histine expectorant": "2",
 "codeine/phenylephrine/promethazine": "2",
 "codafed pediatric": "2",
 "carozide": "2",
 "coartem": "3",
 "children's zyrtec": "2",
 "cephadyn": "2",
 "contac day and night allergy": "2",
 "captopril/hydrochlorothiazide": "2",
 "carteolol": "2",
 "chlormezanone": "2",
 "cocet": "2",
 "carisoprodol compound": "2",
 "captopril": "2",
 "comtussin hc": "2",
 "chemdal hd plus": "2",
 "carisoprodol": "2",
 "contac day and night cold and flu": "2",
 "carteolol ophthalmic": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "chlorgest hd": "2",
 "crantex hc": "2",
 "covera-hs": "2",
 "cytuss hc": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "codeine/guaifenesin": "2",
 "crizotinib": "3",
 "clobazam": "2",
 "codeprex": "2",
 "clonazepam": "2",
 "co-tuss v expectorant": "2",
 "corzide 80/5": "2",
 "cipro cystitis pack": "2",
 "codeine phosphate-promethazine hcl": "2",
 "chlorothiazide": "2",
 "chardonna-2": "2",
 "codituss dh": "2",
 "corzide 40/5": "2",
 "clindex": "2",
 "chlorphenesin": "2",
 "coldcough hcm": "2",
 "capozide": "2",
 "capozide 25/25": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "coricidin night time cold relief": "2",
 "canges-hc nr": "2",
 "codeine": "2",
 "coreg": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "coughtuss": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "cotab a": "2",
 "codeine/pseudoephedrine/triprolidine": "2",
 "cialis": "2",
 "cordron-hc": "2"}, "b": {"bellaphen-s": "2",
 "brevibloc": "2",
 "benadryl-d allergy plus sinus": "2",
 "brompheniramine/hydrocodone/phenylephrine": "2",
 "biaxin xl": "3",
 "butisol sodium": "2",
 "bitex liquid": "2",
 "brimonidine ophthalmic": "1",
 "betoptic": "2",
 "betagan c-cap": "2",
 "butorphanol": "2",
 "biaxin": "3",
 "brethine": "2",
 "benaphen plus": "2",
 "betoptic s": "2",
 "benzthiazide": "2",
 "brovana": "2",
 "bayer pm": "2",
 "bactrim": "1",
 "bromodiphenhydramine/codeine": "2",
 "benadryl": "2",
 "bitolterol": "2",
 "benazepril": "2",
 "buspirone": "2",
 "brovex hc": "2",
 "bel-phen-ergot": "2",
 "bystolic": "2",
 "butabarbital": "2",
 "betaxolol ophthalmic": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "betapace af": "3",
 "brethaire": "2",
 "brovex cbx": "2",
 "benadryl allergy plus cold": "2",
 "brovex pb cx": "2",
 "betapace": "3",
 "bactrim iv": "1",
 "bromplex hd": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "benadryl children's allergy and sinus": "2",
 "belladonna/butabarbital": "2",
 "bethaprim pediatric": "1",
 "benadryl allergy sinus": "2",
 "bricanyl": "2",
 "biotussin dac": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "butrans": "2",
 "budeprion sr": "2",
 "benahist-50": "2",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "buspar": "2",
 "benadryl allergy": "2",
 "betagan": "2",
 "balacet": "2",
 "bellaspas": "2",
 "brompheniramine/hydrocodone/pseudoephedrine": "2",
 "benadryl allergy plus sinus headache": "2",
 "bromph hd": "2",
 "boceprevir": "3",
 "buprenex": "2",
 "bethaprim": "1",
 "banflex": "2",
 "bellamine": "2",
 "bepridil": "3",
 "bel-tabs": "2",
 "belix": "2",
 "beldin": "2",
 "bendroflumethiazide": "2",
 "belladonna/opium": "2",
 "bendroflumethiazide/nadolol": "2",
 "bupropion": "2",
 "benahist-10": "2",
 "brovex cb": "2",
 "banophen": "2",
 "benylin multi-symptom": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "barbidonna": "2",
 "budeprion": "2",
 "benadryl severe allergy &amp; sinus headache": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "budesonide/formoterol": "2",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "butex forte": "2",
 "buprenorphine/naloxone": "2",
 "betimol": "2",
 "bydramine": "2",
 "brompheniramine/diphenhydramine": "2",
 "brompheniramine/codeine": "2",
 "bactrim pediatric": "1",
 "bisoprolol": "2",
 "brovex pb c": "2",
 "bupivacaine/hydromorphone": "2",
 "budeprion xl": "2",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "buprenorphine": "2",
 "betaxolol": "2",
 "bellergal-s": "2",
 "banaril": "2",
 "bellalphen": "2",
 "bromcomp hc": "2",
 "bellamine s": "2",
 "b-tuss": "2",
 "bellatal er": "2",
 "benadryl severe allergy plus sinus headache": "2",
 "blocadren": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "benazepril/hydrochlorothiazide": "2",
 "ben-tann": "2",
 "bronkometer": "2",
 "brontex": "2",
 "b &amp; o supprettes": "2",
 "belcomp-pb": "2",
 "bupap": "2",
 "bupivacaine/fentanyl": "2",
 "betaxon": "2",
 "butalbital compound": "2",
 "bpm pe hc": "2",
 "baclofen": "2",
 "butalbital": "2",
 "benoject-50": "2",
 "benicar hct": "2",
 "bellamor": "2",
 "benadryl children's allergy": "2",
 "bronkosol": "2",
 "busodium": "2",
 "buproban": "2",
 "butibel": "2",
 "brimonidine/timolol ophthalmic": "2",
 "brompheniramine/codeine/pseudoephedrine": "2",
 "bellatal": "2",
 "bactrim ds": "1",
 "bucet": "2",
 "benadryl cold": "2"}, "e": {"efasin-hd plus": "2",
 "endep": "2",
 "emsam": "2",
 "edurant": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "e.e.s.-400": "3",
 "endacof-ac": "2",
 "emend": "2",
 "eryped": "3",
 "erythromycin/sulfisoxazole": "3",
 "exetuss-hc": "2",
 "epoprostenol": "2",
 "endocet": "2",
 "embeda": "2",
 "exalgo": "2",
 "eperbel-s": "2",
 "exforge hct": "2",
 "elavil": "2",
 "endal hd": "2",
 "entuss-d": "2",
 "execlear-c": "2",
 "esidrix": "2",
 "erythrocot": "3",
 "ergocomp-pb": "2",
 "exo-tuss": "2",
 "erythromycin": "3",
 "esgic": "2",
 "entuss": "2",
 "entuss-d liquid": "2",
 "endacof hc": "2",
 "endacof xp": "2",
 "extendryl hc": "2",
 "enduron": "2",
 "elixiral": "2",
 "ezogabine": "2",
 "edarbyclor": "2",
 "erythrocin lactobionate": "3",
 "emend 2-day": "2",
 "excedrin pm": "2",
 "efasin-hd": "2",
 "enalapril/felodipine": "2",
 "endal expectorant": "2",
 "esmolol": "2",
 "execlear": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "emend 3-day": "2",
 "execof": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "endal cd": "2",
 "ethanol": "2",
 "e s p": "3",
 "e.e.s.-200": "3",
 "esimil": "2",
 "etrafon forte": "2",
 "ethyol": "2",
 "exna": "2",
 "endagen-hd": "2",
 "entuss expectorant": "2",
 "e-caff p-b": "2",
 "equaline acid reducer": "1",
 "endolor": "2",
 "ergocaf-pb": "2",
 "efavirenz": "2",
 "emend for injection": "2",
 "ethyl alcohol": "2",
 "enduronyl": "2",
 "emtricitabine/rilpivirine/tenofovir": "2",
 "emtricitabine/nelfinavir/tenofovir": "3",
 "effexor xr": "2",
 "endacof-dc": "2",
 "endacof-tab": "2",
 "exjade": "2",
 "epirubicin": "2",
 "endacof-dh": "2",
 "epidrin": "2",
 "e.e.s.-400 filmtab": "3",
 "eldepryl": "2",
 "entuss-d jr": "2",
 "endacof-plus": "2",
 "e-mycin": "3",
 "edluar": "2",
 "endocodone": "2",
 "excof": "2",
 "excof-sf": "2",
 "endodan": "2",
 "eth-oxydose": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "3",
 "eskalith": "2",
 "efasin expectorant sf": "2",
 "eskalith-cr": "2",
 "empirin with codeine": "2",
 "echotuss-hc": "2",
 "endotuss expectorant": "2",
 "enalapril": "2",
 "ezide": "2",
 "equagesic": "2",
 "ez iii": "2",
 "endotuss-hd": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "ellence": "2",
 "ery-tab": "3",
 "enditussin expectorant": "2",
 "etrafon": "2",
 "endacof-c": "2",
 "esgic-plus": "2",
 "estazolam": "2",
 "emblon": "2",
 "endal-hd plus": "2",
 "e.e.s. granules": "3",
 "eryc": "3",
 "equanil": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "effexor": "2",
 "etravirine": "2",
 "erythrocin": "3",
 "equate allergy &amp; sinus headache": "2",
 "erythrocin stearate filmtab": "3",
 "ed-tuss hc": "2",
 "enplus-hd": "2",
 "ezol": "2",
 "ergocaffpb": "2",
 "eryzole": "3",
 "enduronyl forte": "2",
 "ed-tlc": "2",
 "entex hc": "2",
 "eze ds": "2"}, "d": {"duratuss hd": "2",
 "duramorph pf": "2",
 "duratuss ac 12": "2",
 "diastat": "2",
 "desyrel": "2",
 "duragesic-75": "2",
 "daunorubicin": "2",
 "drotuss-cp": "2",
 "dronedarone": "3",
 "delavirdine": "3",
 "de-chlor g": "2",
 "doral": "2",
 "dizac": "2",
 "diuril": "2",
 "diphenydramine quick melt": "2",
 "duramorph": "2",
 "dezocine": "2",
 "dutasteride/tamsulosin": "2",
 "diltiazem/enalapril": "2",
 "diltiazem hydrochloride cd": "2",
 "duloxetine": "2",
 "diovan hct": "2",
 "dicopanol": "2",
 "daunoxome": "2",
 "dextromethorphan/quinidine": "3",
 "dutoprol": "2",
 "doxepin": "2",
 "dehydrated alcohol": "2",
 "dormin": "2",
 "demi-cof": "2",
 "donatuss dc": "2",
 "donatussin max": "2",
 "demi-regroton": "2",
 "donnatal extentabs": "2",
 "dexbrompheniramine/hydrocodone/phenylephrine": "2",
 "ditussin-hc": "2",
 "diphenhydramine": "2",
 "dolgic plus": "2",
 "diltiazem hydrochloride sr": "2",
 "diupres-500": "2",
 "duoneb": "2",
 "doloral": "2",
 "diltzac": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "duraclon": "2",
 "doans pm": "2",
 "dazidox": "2",
 "diphenadryl": "2",
 "detuss": "2",
 "duradrin": "2",
 "diacetazone": "2",
 "dolgic": "2",
 "diabetic tussin night time formula": "2",
 "dph": "2",
 "dytan-at": "2",
 "dolmar": "2",
 "darvon compound 32": "2",
 "duragesic-50": "2",
 "dolasetron": "3",
 "dynatuss hc": "2",
 "dolacet": "2",
 "dalfopristin/quinupristin": "2",
 "duradyne dhc": "2",
 "duohist dh": "2",
 "dihistine dh": "2",
 "doxorubicin liposomal": "2",
 "damason-p": "2",
 "dex-tuss": "2",
 "doxazosin": "2",
 "dihistine": "2",
 "diphenhydramine/phenylephrine": "2",
 "diphenmax": "2",
 "despec-pd": "2",
 "diphenhydramine/ibuprofen": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "diphen af": "2",
 "diphenyl": "2",
 "definity": "2",
 "dalgan": "2",
 "donnapine": "2",
 "degarelix": "2",
 "dilaudid-hp": "2",
 "diltiazem hydrochloride xt": "2",
 "diltiazem hydrochloride xr": "2",
 "dilaudid cough syrup": "2",
 "duragesic-25": "2",
 "doxepin topical": "2",
 "depodur": "2",
 "dihydro-pe": "2",
 "duragesic": "2",
 "d-tann": "2",
 "diphenhydramine/tripelennamine topical": "2",
 "dynex hd": "2",
 "de-chlor hd": "2",
 "de-chlor hc": "2",
 "droperidol/fentanyl": "3",
 "droperidol": "3",
 "decohistine dh": "2",
 "diphen": "2",
 "dilacor xr": "2",
 "dihydro-cp": "2",
 "duocet": "2",
 "diaqua": "2",
 "dilaudid": "2",
 "diphendryl": "2",
 "diphenylin": "2",
 "delsym children's night time cough &amp; cold": "2",
 "diphenmax d": "2",
 "deserpidine/methyclothiazide": "2",
 "decohistine expectorant": "2",
 "diurese": "2",
 "donnatal": "2",
 "duo-vil": "2",
 "deferasirox": "2",
 "dolagesic": "2",
 "dorzolamide/timolol ophthalmic": "2",
 "de-chlor mr": "2",
 "deconamine cx": "2",
 "darvon-n": "2",
 "dihistine expectorant": "2",
 "duragesic-100": "2",
 "dihydrocodeine/guaifenesin": "2",
 "d-tann at": "2",
 "dopar": "2",
 "dytan": "2",
 "diphenhydramine/guaifenesin": "2",
 "darvon": "2",
 "dytan-hc": "2",
 "diastat acudial": "2",
 "diuretic ap-es": "2",
 "dyazide": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "dasatinib": "2",
 "duragal-s": "2",
 "diucardin": "2",
 "diabetic tussin c": "2",
 "danocrine": "2",
 "detussin": "2",
 "darvon compound-65": "2",
 "danazol": "2",
 "diphentann-d": "2",
 "diazepam intensol": "2",
 "desyrel dividose": "2",
 "demerol": "2",
 "dulera": "2",
 "dihydrocodeine/guaifenesin/pseudoephedrine": "2",
 "d-tal": "2",
 "detussin expectorant": "2",
 "d-tann hc": "2",
 "dytan-d": "2",
 "dytan-dm": "2",
 "dibenzyline": "2",
 "doxorubicin": "2",
 "diphedryl": "2",
 "dihydrocodeine/guaifenesin/phenylephrine": "2",
 "dicomal-ph": "2",
 "darunavir": "3",
 "doxadura": "2",
 "duo-medihaler": "2",
 "deconsal c expectorant": "2",
 "denzapine": "3",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "d-tann dm": "2",
 "decotuss-hd": "2",
 "dolophine": "3",
 "doxil": "2",
 "diuril sodium": "2",
 "d-tann cd": "2",
 "diastat pediatric": "2",
 "darvocet-n 100": "2",
 "dihistine expectorant with codeine": "2",
 "dytuss": "2",
 "deserpidine/hydrochlorothiazide": "2",
 "dofetilide": "3",
 "d-tann ct": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diphenhist": "2",
 "dexchlorpheniramine/hydrocodone/phenylephrine": "2",
 "diutensen-r": "2",
 "diltiazem": "2",
 "duradal hd": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "2",
 "drituss hd": "2",
 "dicomal-dh": "2",
 "darvocet-n 50": "2",
 "dalmane": "2",
 "disopyramide": "3",
 "di-delamine": "2",
 "diazepam": "2",
 "duraganidin nr": "2",
 "diupres-250": "2",
 "doloral sirop": "2",
 "dolgic lq": "2",
 "diflucan": "2",
 "donnaphen": "2",
 "diphen cough": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "de-chlor nx": "2",
 "daunorubicin liposomal": "2",
 "duragesic-12": "2",
 "dihydro-gp": "2",
 "diltia xt": "2",
 "deproist with codeine": "2",
 "dihydrocodeine/phenylephrine": "2",
 "donatussin dc": "2",
 "desipramine": "2",
 "dytan-cd": "2",
 "desvenlafaxine": "2",
 "dilt-xr": "2",
 "dytan-cs": "2",
 "diphenhydramine/pseudoephedrine": "2",
 "drocon-cs": "2",
 "darvocet a500": "2"}, "g": {"guaifenesin/hydrocodone": "2",
 "genahist": "2",
 "gua hc": "2",
 "guaifen-c": "2",
 "gemifloxacin": "2",
 "gablofen": "2",
 "guaifenesin/hydrocodone/pseudoephedrine": "2",
 "guaitussin ac": "2",
 "guaifen ac": "2",
 "gantanol": "1",
 "genapap pm": "2",
 "guiatuss dac": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylephrine/phenylpropanolamine": "2",
 "gengraf": "2",
 "garlic oil": "1",
 "guiatussin with codeine": "2",
 "guaifenesin/hydrocodone/phenylephrine": "2",
 "geone": "2",
 "g-1": "2",
 "guiaplex hc": "2",
 "guaifenesin dac liquid": "2",
 "guai-co": "2",
 "gani-tuss nr": "2",
 "gatifloxacin": "3",
 "guiatussin dac": "2",
 "gua pc": "2",
 "gestuss-hc": "2",
 "giltuss ped-c": "2",
 "garlic": "1",
 "gentex hc": "2",
 "glydeine": "2",
 "gleevec": "2",
 "guiatuss ac": "2",
 "guaiatussin dac": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylpropanolamine/pyrilamine": "2",
 "guanethidine/hydrochlorothiazide": "2",
 "genox": "2",
 "geodon": "3",
 "g-tuss": "2",
 "granisetron": "2",
 "granisol": "2",
 "guaiatussin ac": "2",
 "guaifen dac": "2",
 "grepafloxacin": "3",
 "guaifenesin/hydromorphone": "2",
 "guiaphen hd": "2"}, "f": {"flolan": "2",
 "fenoldopam": "2",
 "fiortal": "2",
 "fentanyl/ropivacaine": "2",
 "formoterol/mometasone": "2",
 "firmagon": "2",
 "fiorinal with codeine iii": "2",
 "formoterol": "2",
 "flomax": "2",
 "fazaclo": "3",
 "fiorinal with codeine": "2",
 "fortabs": "2",
 "fentuss expectorant": "2",
 "flurazepam": "2",
 "fanapt": "3",
 "fioricet with codeine": "2",
 "flutuss hc": "2",
 "fentanyl": "2",
 "femcet": "2",
 "fosinopril": "2",
 "flecainide": "2",
 "fluconazole": "2",
 "forfivo xl": "2",
 "floxin": "2",
 "fiortal with codeine": "2",
 "fentora": "2",
 "flexoject": "2",
 "furazolidone": "2",
 "furoxone": "2",
 "flexon": "2",
 "factive": "2",
 "fluoxetine/olanzapine": "2",
 "fluphenazine": "2",
 "fortovase": "3",
 "fosamprenavir": "3",
 "fiormor": "2",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiorinal": "2",
 "fentanyl transdermal system": "2",
 "fosaprepitant": "2",
 "fluothane": "2",
 "fluticasone/salmeterol": "2",
 "farbital": "2",
 "floxin iv": "2",
 "foradil aerolizer": "2",
 "fareston": "3",
 "fosinopril/hydrochlorothiazide": "2",
 "fiorpap": "2",
 "flumezide": "2"}, "i": {"isoniazid/rifampin": "2",
 "indapamide": "2",
 "idamycin pfs": "2",
 "inderide": "2",
 "invega": "2",
 "ibutilide": "3",
 "invirase": "3",
 "isuprel mistometer": "2",
 "imatinib": "2",
 "iso-acetazone": "2",
 "iophen-c nr": "2",
 "isocom": "2",
 "incivek": "3",
 "ibuprofen/oxycodone": "2",
 "inapsine": "3",
 "isoniazid": "2",
 "isoptin": "2",
 "itraconazole": "3",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isocet": "2",
 "imipramine": "2",
 "iloprost": "2",
 "inderide la": "2",
 "ibudone": "2",
 "intermezzo": "2",
 "isoetharine": "2",
 "innopran xl": "2",
 "ilosone": "3",
 "inderal la": "2",
 "indacaterol": "2",
 "idamycin": "2",
 "iopidine": "2",
 "isuprel hcl": "2",
 "istodax": "2",
 "ide-cet": "2",
 "isonarif": "2",
 "indinavir": "3",
 "istalol": "2",
 "infumorph": "2",
 "iloperidone": "3",
 "isoproterenol": "2",
 "iotussin d liquid": "2",
 "iotussin hc": "2",
 "isoptin sr": "2",
 "inderal": "2",
 "iophen": "2",
 "intelence": "2",
 "invega sustenna": "2",
 "isocarboxazid": "2",
 "idarubicin": "2",
 "innovar": "3",
 "idenal": "2",
 "isuprel": "2",
 "iodal hd": "2",
 "isoptin iv": "2",
 "isoproterenol/phenylephrine": "2",
 "ionsys": "2",
 "ida": "2"}, "h": {"hydro-reserp": "2",
 "histex hc": "2",
 "hydrotussin hd": "2",
 "hycodan": "2",
 "headache formula pm": "2",
 "hydro-tussin exp": "2",
 "histinex hc": "2",
 "hycoclar tuss": "2",
 "hydrocodone hd": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydrap-es": "2",
 "hydex pd": "2",
 "hydrocodone/ibuprofen": "2",
 "hydrocodone/phenylephrine/pyrilamine": "2",
 "hydrodiuril": "2",
 "hyosophen": "2",
 "hydrocodone/phenylephrine": "2",
 "hydrostat ir": "2",
 "hydrophed": "2",
 "hydrocodone gf": "2",
 "hydrocodone/pseudoephedrine/triprolidine": "2",
 "hydroserpine 1": "2",
 "histussin hc liquid": "2",
 "hydrochlorothiazide/propranolol": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "hydrotuss hc": "2",
 "hydra-zide": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrocodone/potassium guaiacolsulfonate": "2",
 "hydrochlorothiazide/reserpine": "2",
 "hy-kxp": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydramine cough syrup": "2",
 "hytrin": "2",
 "hydrocof-hc": "2",
 "homatropine/hydrocodone": "2",
 "hydron ex": "2",
 "hydropres-25": "2",
 "hyoscyamine/phenobarbital": "2",
 "hydron pcs": "2",
 "hydro-tuss xp": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hytussin expectorant": "2",
 "hyzaar": "2",
 "hydrochlorothiazide/methyldopa": "2",
 "hyzine": "2",
 "hydropres-50": "2",
 "hycosin expectorant": "2",
 "hydrochlorothiazide/moexipril": "2",
 "h-c tussive-nr": "2",
 "histinex d": "2",
 "hycophen pediatric": "2",
 "hydrocod-gf": "2",
 "hycomal dh": "2",
 "hygroton": "2",
 "hycophen": "2",
 "hydrocodone/pseudoephedrine": "2",
 "hydromet": "2",
 "hydrotuss": "2",
 "hydromide": "2",
 "hydro-tussin hg": "2",
 "hycomine compound": "2",
 "hydro par": "2",
 "hydroxy compound": "2",
 "halothane": "2",
 "hydromorph contin": "2",
 "hi-tuss hc": "2",
 "histinex pv": "2",
 "hyrexin": "2",
 "hydro gp": "2",
 "hydro-pc ii": "2",
 "hydrocodone pa pediatric": "2",
 "hycomine": "2",
 "hycotuss expectorant": "2",
 "hytussin": "2",
 "haldol": "3",
 "hydrogesic": "2",
 "hyphed": "2",
 "halotussin dac": "2",
 "histussin d": "2",
 "hydrofed": "2",
 "halcion": "2",
 "hydroflumethiazide": "2",
 "hydron kgs": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hydrocodone cp": "2",
 "hydropane": "2",
 "hyphen-hd": "2",
 "haldol decanoate": "3",
 "hydrotropine": "2",
 "hydrocet": "2",
 "hismanal": "2",
 "hydro-dp": "2",
 "h-c tussive": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "halotussin ac": "2",
 "hy-phen": "2",
 "hydroserp": "2",
 "hydrochlorothiazide/timolol": "2",
 "hydroflumethiazide/reserpine": "2",
 "halofantrine": "3",
 "hydrophene dh": "2",
 "hydro-pc ii plus": "2",
 "hydron cp": "2",
 "hydrochlorothiazide": "2",
 "hair regrowth treatment for women": "2",
 "headache relief pm": "2",
 "hycet": "2",
 "hhr": "2",
 "haloperidol": "3",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrocodone": "2",
 "hydromorphone": "2",
 "hydramine compound": "2",
 "highland hc": "2",
 "hydroserpine": "2",
 "hydrochlorothiazide/losartan": "2",
 "h-c tussive d": "2",
 "hexatussin": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hycomine pediatric": "2",
 "hycoclear": "2",
 "hypamine": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydrocodone/potassium guaiacolsulfonate/pseudoephedrine": "2",
 "hyco-dh": "2",
 "hydrocodone/phenylpropanolamine": "2",
 "hydroxyzine": "2",
 "hydro-tussin dhc": "2",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "halfan": "3",
 "histussin hc syrup": "2",
 "hytan": "2",
 "hydramine": "2",
 "hydrocodone/pheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "hydralazine plus": "2",
 "halazepam": "2"}, "k": {"kadian": "2",
 "kaletra": "3",
 "kg-dal hd plus": "2",
 "kapvay": "2",
 "ketek": "3",
 "klonopin wafer": "2",
 "kgs-hc": "2",
 "klonopin": "2",
 "kg-fed pediatric expectorant": "2",
 "kg-tussin": "2",
 "kemstro": "2",
 "kg-dal hd": "2",
 "kg-tuss hd": "2",
 "ketoconazole": "3",
 "kg-fed expectorant": "2",
 "kwelcof": "2",
 "kerlone": "2",
 "kytril": "2",
 "ketek pak": "3",
 "kg-fed": "2"}, "j": {"jaycof-hc": "2",
 "j-max dhc": "2",
 "j-cof dhc": "2",
 "jalyn": "2",
 "j-tan d hc": "2",
 "jumex": "2",
 "jenloga": "2"}, "m": {"m-end wc": "2",
 "morphine sulfate er": "2",
 "maxifed cdx": "2",
 "metipranolol ophthalmic": "2",
 "metahydrin": "2",
 "m-oxy": "2",
 "micardis hct": "2",
 "myphetane dc": "2",
 "midazolam": "2",
 "maolate": "2",
 "magnacet": "2",
 "methyclothiazide/reserpine": "2",
 "methadone diskets": "3",
 "migracet-pb": "2",
 "minizide": "2",
 "m-phen": "2",
 "metaprel": "2",
 "mephobarbital": "2",
 "moduretic": "2",
 "morphine": "2",
 "mintuss nx": "2",
 "mar-cof bp": "2",
 "morphine liposomal": "2",
 "mycelex troche": "2",
 "monopril": "2",
 "m-clear": "2",
 "matzim la": "2",
 "migrin-a": "2",
 "mytussin ac": "2",
 "midodrine": "2",
 "morphine/naltrexone": "2",
 "multaq": "3",
 "metaproterenol": "2",
 "midol pm": "2",
 "modafinil": "1",
 "motrin pm": "2",
 "maxzide-25": "2",
 "mintex hc": "2",
 "ms/s": "2",
 "marplan": "2",
 "molindone": "2",
 "mintuss ms": "2",
 "morphine sulfate sr": "2",
 "msir": "2",
 "maxair": "2",
 "maxifed-g cdx": "2",
 "milnacipran": "2",
 "monte-g hc": "2",
 "marcof expectorant": "2",
 "meperitab": "2",
 "mefloquine": "2",
 "mykrox": "2",
 "miconazole": "2",
 "medent c": "2",
 "metolazone": "2",
 "methadose": "3",
 "methyclothiazide": "2",
 "metaxalone": "2",
 "maprotiline": "2",
 "minotal": "2",
 "mintuss g": "2",
 "mirtazapine": "2",
 "mio-rel": "2",
 "meperidine": "2",
 "morphine sulfate ir": "2",
 "maxi-tuss sa": "2",
 "mygracet": "2",
 "maxifed cd": "2",
 "ms contin": "2",
 "margesic": "2",
 "mapap pm": "2",
 "mitran": "2",
 "morphine rapi-ject": "2",
 "maxiflu cd": "2",
 "mintuss mr": "2",
 "maraviroc": "2",
 "maxiphen cd": "2",
 "maxifed-g cd": "2",
 "mellaril-s": "3",
 "medtuss hd": "2",
 "mitride": "2",
 "micrainin": "2",
 "meprobamate": "2",
 "morphine lp epidural": "2",
 "mepergan": "2",
 "migrazone": "2",
 "medigesic": "2",
 "midchlor": "2",
 "mibefradil": "2",
 "meprozine": "2",
 "mebaral": "2",
 "myolin": "2",
 "migratine": "2",
 "matulane": "2",
 "morphitec": "2",
 "m-clear wc": "2",
 "maxaquin": "2",
 "moduretic 5-50": "2",
 "maxi-tuss hcx": "2",
 "metoprolol succinate er": "2",
 "migquin": "2",
 "maxiflu cdx": "2",
 "methocarbamol": "2",
 "my-o-den": "2",
 "microzide": "2",
 "maxi-tuss hcg": "2",
 "metoprolol": "2",
 "minipress": "2",
 "m-end pe": "2",
 "micomp-pb": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "migrapap": "2",
 "maxi-tuss hc": "2",
 "mb-tab": "2",
 "methotrimeprazine": "2",
 "maxiphen cdx": "2",
 "moxifloxacin": "3",
 "mudrane gg": "2",
 "margesic h": "2",
 "meperidine/promethazine": "2",
 "medihaler-iso": "2",
 "maxzide": "2",
 "medcodin": "2",
 "midrin": "2",
 "marten-tab": "2",
 "max hc": "2",
 "miles nervine": "2",
 "monopril hct": "2",
 "minoxidil topical": "2",
 "m-eslon": "2",
 "monteflu hc": "2",
 "mytussin dac": "2",
 "mavik": "2",
 "methadone": "3",
 "marax df": "2",
 "migrex": "2",
 "mepergan fortis": "2",
 "maxidone": "2",
 "mudrane": "2",
 "m-end": "2",
 "marax": "2",
 "mellaril": "3",
 "metatensin 4": "2",
 "metatensin 2": "2",
 "moban": "2",
 "maxair autohaler": "2",
 "moexipril": "2",
 "methdilazine": "2",
 "miltown": "2",
 "mesoridazine": "3",
 "m o s": "2",
 "marpres": "2"}, "l": {"lortab asa": "2",
 "lorzone": "2",
 "luminal": "2",
 "liquitussin hc syrup": "2",
 "loqua": "2",
 "lotrel": "2",
 "lufyllin-epg": "2",
 "liquihistine cs": "2",
 "lortab 5/500": "2",
 "lortab 7.5/500": "2",
 "ludiomil": "2",
 "levrix": "2",
 "lorcet 10/650": "2",
 "lortab": "2",
 "loxitane c": "2",
 "larodopa": "2",
 "lomefloxacin": "2",
 "lisinopril": "2",
 "levsin with phenobarbital": "2",
 "lioresal intrathecal": "2",
 "lortab 2.5/500": "2",
 "lorcet plus": "2",
 "limbitrol": "2",
 "librax": "2",
 "levobunolol ophthalmic": "2",
 "lithonate": "2",
 "licorice": "2",
 "liquituss hd": "2",
 "levofloxacin": "2",
 "lozol": "2",
 "levall 5.0": "2",
 "liquicough hc": "2",
 "levaquin": "2",
 "lariam": "2",
 "lithium": "2",
 "lurasidone": "2",
 "levomethadyl acetate": "3",
 "levobetaxolol ophthalmic": "2",
 "levatol": "2",
 "lotensin": "2",
 "librium": "2",
 "loxitane": "2",
 "lorazepam": "2",
 "lorazepam intensol": "2",
 "liquicet": "2",
 "lorcet hd": "2",
 "lazanda": "2",
 "lopinavir/ritonavir": "3",
 "lioresal": "2",
 "linezolid": "2",
 "largon": "2",
 "levitra": "2",
 "labetalol": "2",
 "limbitrol ds": "2",
 "levo-dromoran": "2",
 "levaquin leva-pak": "2",
 "loxitane im": "2",
 "lortab 10/500": "2",
 "legatrin pm": "2",
 "levorphanol": "2",
 "lopressor": "2",
 "lapatinib": "2",
 "lotensin hct": "2",
 "lithobid": "2",
 "levocetirizine": "2",
 "lexxel": "2",
 "levodopa": "2",
 "lopressor hct": "2",
 "lortuss hc": "2",
 "laniroif": "2",
 "lorelco": "2",
 "loxapine": "2",
 "lithotabs": "2",
 "latuda": "2",
 "lexuss 210 liquid": "2",
 "lexiva": "3",
 "levoprome": "2",
 "levalbuterol": "2"}, "o": {"onfi": "2",
 "orphengesic": "2",
 "orphengesic forte": "2",
 "oreticyl forte": "2",
 "ocupress": "2",
 "oreticyl 50": "2",
 "oxycodone": "2",
 "oxecta": "2",
 "ormazine": "2",
 "opana": "2",
 "oxyir": "2",
 "optipranolol": "2",
 "oraverse": "2",
 "orbivan": "2",
 "onsolis": "2",
 "oxyfast": "2",
 "oxydose": "2",
 "orvaten": "2",
 "orfro": "2",
 "opium tincture, deodorized": "2",
 "oravig": "2",
 "orphenadrine": "2",
 "oms": "2",
 "oxycontin": "2",
 "oxymorphone": "2",
 "orphenate": "2",
 "ofloxacin": "2",
 "oreticyl 25": "2",
 "orap": "3",
 "opana er": "2",
 "oleptro": "2",
 "opium": "2",
 "oramorph sr": "2",
 "oxazepam": "2",
 "optison": "2",
 "orlaam": "3",
 "oxycet": "2",
 "oretic": "2",
 "opium deodorized": "2",
 "ondansetron": "2",
 "olanzapine": "2",
 "olopatadine nasal": "2"}, "n": {"nuedexta": "3",
 "nolvadex d": "2",
 "narvox": "2",
 "nucodine": "2",
 "nebivolol": "2",
 "novahistine expectorant": "2",
 "nu-med": "2",
 "nizoral": "3",
 "novahistine dh": "2",
 "norpramin": "2",
 "nucodine pediatric": "2",
 "nuco-tuss pediatric expectorant": "2",
 "nasatuss": "2",
 "nytol": "2",
 "norfloxacin": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "nariz hc": "2",
 "naldecon-cx adult": "2",
 "nebupent": "2",
 "numorphan": "2",
 "notuss-nxd": "2",
 "nuvigil": "1",
 "notuss-pe": "2",
 "nilotinib": "3",
 "norgesic forte": "2",
 "norvir": "3",
 "nazarin hc": "2",
 "normodyne": "2",
 "nalbuphine": "2",
 "norflex": "2",
 "nexavar": "2",
 "nytol caplet": "2",
 "nelfinavir": "3",
 "norflex injectable": "2",
 "notuss-ac": "2",
 "notuss-nx": "2",
 "noroxin": "2",
 "nonbac": "2",
 "naloxone/pentazocine": "2",
 "notuss": "2",
 "norisodrine with calcium iodine": "2",
 "novagest with codeine": "2",
 "nucochem": "2",
 "norpace": "3",
 "naturetin": "2",
 "night time pain": "2",
 "nalex ac": "2",
 "norvir soft gelatin": "3",
 "nalex expectorant": "2",
 "norpace cr": "3",
 "nortriptyline": "2",
 "naqua": "2",
 "niravam": "2",
 "nasotuss": "2",
 "nucofed pediatric expectorant": "2",
 "notuss pd": "2",
 "numorphan hcl": "2",
 "nolvadex": "2",
 "nifediac cc": "2",
 "nucodine expectorant": "2",
 "neo ac": "2",
 "neoral": "2",
 "novasus": "2",
 "novadyne dh": "2",
 "notuss-forte": "2",
 "nuco-tuss expectorant": "2",
 "nexiclon xr": "2",
 "neo hc": "2",
 "nydrazid": "2",
 "noxafil": "3",
 "nembutal sodium": "2",
 "nembutal": "2",
 "nifedical xl": "2",
 "nalex-dh": "2",
 "nadolol": "2",
 "nubain": "2",
 "nervine": "2",
 "nifedipine": "2",
 "naturetin-10": "2",
 "notuss-dc": "2",
 "navane": "2",
 "norgesic": "2",
 "nardil": "2",
 "nucofed expectorant": "2",
 "nightime sleepaid": "2",
 "nexterone": "3",
 "nucofed": "2",
 "novadyne expectorant": "2",
 "narcof": "2",
 "naturetin-5": "2",
 "nefazodone": "3",
 "norco": "2"}, "q": {"quinaretic": "2",
 "quinidine": "3",
 "qual-tussin dc": "2",
 "quinaglute dura-tabs": "3",
 "quin-g": "3",
 "quetiapine": "2",
 "quinine": "2",
 "quin-release": "3",
 "quinora": "3",
 "qualaquin": "2",
 "q-dryl a/f": "2",
 "quinapril": "2",
 "quenalin": "2",
 "quadrapax": "2",
 "qm-260": "2",
 "quindal hd": "2",
 "q-v tussin": "2",
 "quazepam": "2",
 "quadrinal": "2",
 "quindal hd plus": "2",
 "quinidex extentabs": "3",
 "q-dryl": "2"}, "p": {"pyridium plus": "2",
 "pneumotussin 2.5": "2",
 "poly-tussin ac": "2",
 "phrenilin forte": "2",
 "prudoxin": "2",
 "poly-histine cs": "2",
 "pediazole": "3",
 "prinzide": "2",
 "plenaxis": "2",
 "prograf": "2",
 "propatuss expectorant": "2",
 "phendal-hd": "2",
 "pentazocine": "2",
 "phenoxybenzamine": "2",
 "procof d": "2",
 "pyrelle hb": "2",
 "procainamide": "3",
 "pedituss": "2",
 "promacet": "2",
 "paral": "2",
 "pharmagesic": "2",
 "pindolol": "2",
 "procardia": "2",
 "phenhist expectorant": "2",
 "pancof hc": "2",
 "pharmorubicin rdf": "2",
 "paxipam": "2",
 "proair hfa": "2",
 "phenylhistine expectorant": "2",
 "phenaphen with codeine": "2",
 "pardryl": "2",
 "prolixin": "2",
 "pancof xp": "2",
 "phenadoz": "2",
 "phenazopyridine/sulfamethoxazole": "1",
 "polythiazide/prazosin": "2",
 "pirbuterol": "2",
 "probucol": "2",
 "procarbazine": "2",
 "paraflex": "2",
 "prochlorperazine": "2",
 "protriptyline": "2",
 "pitressin": "2",
 "phenylephrine/promethazine": "2",
 "promethazine with codeine": "2",
 "pseudodine c": "2",
 "pimozide": "3",
 "phenazine 50": "2",
 "pentobarbital": "2",
 "permitil": "2",
 "pediacare children's allergy": "2",
 "prolixin enanthate": "2",
 "parnate": "2",
 "pseudoephedrine/terfenadine": "2",
 "p-v-tussin": "2",
 "percodan": "2",
 "poly-tussin xp": "2",
 "pmb": "2",
 "procardia xl": "2",
 "pediacof": "2",
 "paliperidone": "2",
 "pb-hyos": "2",
 "parafon forte dsc": "2",
 "prominol": "2",
 "phrenilin with caffeine and codeine": "2",
 "posicor": "2",
 "phendacof plus": "2",
 "percogesic extra strength": "2",
 "poly hist dhc": "2",
 "polytine cs": "2",
 "percocet 10/325": "2",
 "poly hist hc": "2",
 "pentam 300": "2",
 "poly tussin ex": "2",
 "pediatex-ct": "2",
 "proamatine": "2",
 "promethazine with dm": "2",
 "percodan-demi": "2",
 "promethazine vc with codeine": "2",
 "poly cs": "2",
 "prolixin decanoate": "2",
 "pronestyl-sr": "3",
 "phentolamine": "2",
 "percocet 2.5/325": "2",
 "proventil": "2",
 "poly-tussin hd": "2",
 "primlev": "2",
 "poly-tussin dhc": "2",
 "pancof": "2",
 "penbutolol": "2",
 "propiomazine": "2",
 "percolone": "2",
 "phenaz plus": "2",
 "phenelzine": "2",
 "posaconazole": "3",
 "pseudatex hc": "2",
 "prosom": "2",
 "pentamidine": "2",
 "pro-clear": "2",
 "p-v-tussin syrup": "2",
 "procof": "2",
 "polythiazide/reserpine": "2",
 "pro-med": "2",
 "prezista": "3",
 "poly-tussin ex syrup": "2",
 "propranolol": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "paraldehyde": "2",
 "promethazine vc": "2",
 "pancof-pd": "2",
 "phenylhistine dh expectorant": "2",
 "parcopa": "2",
 "pharmorubicin pfs": "2",
 "propoxyphene compound 65": "2",
 "percocet 5/325": "2",
 "pacaps": "2",
 "perforomist": "2",
 "pristiq": "2",
 "phenflu cdx": "2",
 "panacet": "2",
 "pc-cap": "2",
 "prazosin": "2",
 "prinivil": "2",
 "palonosetron": "2",
 "percocet 10/650": "2",
 "priftin": "2",
 "provigil": "1",
 "pp-cap": "2",
 "phenazoforte plus": "2",
 "proventil hfa": "2",
 "pain relief pm extra strength": "2",
 "pamelor": "2",
 "pediacare children's allergy &amp; cold": "2",
 "paregoric": "2",
 "pce dispertab": "3",
 "pentacarinat": "2",
 "perindopril": "2",
 "patanase": "2",
 "pancof exp": "2",
 "procan sr": "3",
 "percocet 7.5/325": "2",
 "phenobarbital": "2",
 "promazine": "2",
 "phrenilin": "2",
 "pediatex hc": "2",
 "procot": "2",
 "percocet": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "pazopanib": "2",
 "panasal 5/500": "2",
 "phenoject-50": "2",
 "propoxyphene": "2",
 "pronestyl": "3",
 "palladone": "2",
 "phenergan fortis": "2",
 "phenergan with codeine": "2",
 "proquin xr": "2",
 "panlor dc": "2",
 "poly-tussin": "2",
 "pharbedryl": "2",
 "pentam": "2",
 "promethazine": "2",
 "polythiazide": "2",
 "pacerone": "3",
 "pain reliever pm": "2",
 "perloxx": "2",
 "panlor ss": "2",
 "propulsid": "3",
 "promethazine with dextromethorphan": "2",
 "pneumotussin hc": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenergan vc": "2",
 "pro-red ac": "2",
 "phenylhistine dh": "2",
 "perflutren": "2",
 "promethegan": "2",
 "promethazine hcl with codeine": "2",
 "procanbid": "3",
 "protuss-d": "2",
 "phenflu cd": "2",
 "pharbetol pm": "2",
 "paxarel": "2",
 "prolex dh": "2",
 "percocet 7.5/500": "2",
 "protuss": "2",
 "promethazine vc plain": "2",
 "propafenone": "2",
 "primalev": "2",
 "phenylephrine hd": "2",
 "percogesic original strength": "2",
 "phenergan with dextromethorphan": "2",
 "potiga": "2",
 "prevpac": "3",
 "perphenazine": "2",
 "polyhist nc": "2",
 "pneumotussin": "2",
 "promethazine vc w/codeine": "2"}, "s": {"su-tuss hd elixir": "2",
 "saluron": "2",
 "saquinavir": "3",
 "stalevo 150": "2",
 "sleep": "2",
 "selgene": "2",
 "seldane": "2",
 "sulfamethoxazole": "1",
 "septra": "1",
 "subutex": "2",
 "selegiline": "2",
 "serathide": "2",
 "septra iv": "1",
 "snooze fast": "2",
 "sinemet cr": "2",
 "sulfamethoxazole/trimethoprim": "1",
 "sporanox pulsepak": "3",
 "soltamox": "2",
 "synalgos-dc": "2",
 "sleep tab ii": "2",
 "sonata": "2",
 "subsys": "2",
 "symtan a": "2",
 "symtan": "2",
 "stelazine": "2",
 "serentil": "3",
 "sotalol hydrochloride af": "3",
 "sinemet": "2",
 "somnote": "2",
 "serevent diskus": "2",
 "siladryl": "2",
 "savella": "2",
 "synercid": "2",
 "sandimmune": "2",
 "soma": "2",
 "suttar-2": "2",
 "salutensin-demi": "2",
 "sulfimycin": "3",
 "stadol": "2",
 "src expectorant": "2",
 "serzone": "3",
 "suttar sf": "2",
 "sleepinal": "2",
 "skelaxin": "2",
 "spantuss hd": "2",
 "sparfloxacin": "3",
 "sominex pain relief formula": "2",
 "salutensin": "2",
 "seconal sodium": "2",
 "sleep-ettes": "2",
 "sudafed pe severe cold": "2",
 "stalevo 75": "2",
 "ser-ap-es": "2",
 "sublimaze": "2",
 "sustiva": "2",
 "symbicort": "2",
 "skelex": "2",
 "sominex maximum strength caplet": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "staxyn": "2",
 "somnicaps": "2",
 "siladryl das": "2",
 "simuc-hd": "2",
 "stalevo 200": "2",
 "sudafed sinus nighttime plus pain": "2",
 "selzentry": "2",
 "sominex": "2",
 "salmeterol": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "s-t forte": "2",
 "sparine": "2",
 "sunitinib": "2",
 "septra ds": "1",
 "seroquel": "2",
 "seroquel xr": "2",
 "soma compound with codeine": "2",
 "sancuso": "2",
 "sleep-ettes d": "2",
 "spastrin": "2",
 "seldane-d": "2",
 "s-t forte 2": "2",
 "simply sleep": "2",
 "sufentanil": "2",
 "scot-tussin allergy": "2",
 "surmontil": "2",
 "stalevo 100": "2",
 "sedapap": "2",
 "sufenta": "2",
 "sutent": "2",
 "serax": "2",
 "statuss green": "2",
 "silodosin": "2",
 "siladryl allergy": "2",
 "sleep tabs": "2",
 "smz-tmp ds": "1",
 "sildenafil": "2",
 "stagesic": "2",
 "sulfatrim": "1",
 "sporanox": "3",
 "serpex": "2",
 "sleepwell 2-nite": "2",
 "soma compound": "2",
 "sleep-eze-3": "2",
 "sprycel": "2",
 "seconal": "2",
 "sudafed pe nighttime cold": "2",
 "statex": "2",
 "saphris": "2",
 "spasmolin": "2",
 "silphen cough": "2",
 "sinequan": "2",
 "serpazide": "2",
 "suboxone": "2",
 "symbyax": "2",
 "spasquid": "2",
 "stalevo 50": "2",
 "strifon fort": "2",
 "stalevo 125": "2",
 "stalevo": "2",
 "sotalol": "3",
 "sorine": "3",
 "servira": "2",
 "silenor": "2",
 "siladyl sa": "2",
 "statuss": "2",
 "sulfatrim pediatric": "1",
 "sectral": "2",
 "sorafenib": "2",
 "seconal sodium pulvules": "2"}, "r": {"robaxisal": "2",
 "rms": "2",
 "reserpine/trichlormethiazide": "2",
 "roxicodone": "2",
 "remeron": "2",
 "risperdal m-tab": "2",
 "rolatuss": "2",
 "robitussin-ac": "2",
 "robafen ac": "2",
 "ryna-cx": "2",
 "ramipril": "2",
 "ritodrine": "2",
 "ronoxidil": "2",
 "robitussin-dac": "2",
 "robitussin night time cough, cold &amp; flu": "2",
 "revatio": "2",
 "rilpivirine": "2",
 "raxar": "3",
 "relaxazone": "2",
 "rindal-hd": "2",
 "romilar ac": "2",
 "roxanol 100": "2",
 "remular-s": "2",
 "rauzide": "2",
 "rythmol": "2",
 "remeron soltab": "2",
 "rogaine men's extra strength": "2",
 "reyataz": "3",
 "roxicet": "2",
 "roxanol-t": "2",
 "rogaine women's": "2",
 "ropivacaine/sufentanil": "2",
 "rifater": "2",
 "robimycin": "3",
 "renese-r": "2",
 "regroton": "2",
 "reprexain": "2",
 "rescudose": "2",
 "rogaine extra strength": "2",
 "rondameth": "2",
 "roxiprin": "2",
 "risperdal consta": "2",
 "ranexa": "2",
 "relacon-hc nr": "2",
 "rolatuss with hydrocodone": "2",
 "remifentanil": "2",
 "ritonavir": "3",
 "robitussin night time cough &amp; cold": "2",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "risperidone": "2",
 "ru-tuss with hydrocodone": "2",
 "roxilox": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "ryna-c": "2",
 "relacon-hc": "2",
 "respa c&amp;c": "2",
 "robichem ac": "2",
 "rindal hpd": "2",
 "remular": "2",
 "rasagiline": "2",
 "relasin-hc": "2",
 "restoril": "2",
 "repan": "2",
 "rapaflo": "2",
 "regitine": "2",
 "remodulin": "2",
 "relcof c": "2",
 "ranolazine": "2",
 "risperdal": "2",
 "robaxin": "2",
 "robaxin-750": "2",
 "rythmol sr": "2",
 "rezira": "2",
 "rindal hd plus": "2",
 "relasin-hcx": "2",
 "romidepsin": "2",
 "rescriptor": "3",
 "rogaine": "2",
 "respa sa": "2",
 "renese": "2",
 "re-pb hyos elixir": "2",
 "roxanol": "2",
 "roxicodone intensol": "2",
 "respirol": "2"}, "u": {"uni-lev 5.0": "2",
 "uni-tann": "2",
 "uni tuss hc": "2",
 "unisom with pain relief": "2",
 "uni-tricof hc": "2",
 "univasc": "2",
 "unipres": "2",
 "urelief plus": "2",
 "uroplus": "1",
 "uni serp": "2",
 "uni-cof": "2",
 "ultiva": "2",
 "uni-tann d": "2",
 "up and up all day allergy relief d": "2",
 "unisom sleepgels": "2",
 "uprima": "2",
 "uni-cof expectorant": "2",
 "unisom sleepmelts": "2",
 "uni-tann cs": "2",
 "uroplus ds": "1",
 "uniretic": "2"}, "t": {"tussionex pennkinetic": "2",
 "toprol-xl": "2",
 "tussiden c": "2",
 "tamoxifen": "2",
 "tizanidine": "2",
 "tyvaso": "2",
 "tekral": "2",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "tencet": "2",
 "terazosin": "2",
 "tri-vent hc": "2",
 "telzir": "3",
 "thiothixene": "2",
 "talwin nx": "2",
 "tylenol with codeine #2": "2",
 "timolol ophthalmic": "2",
 "tranylcypromine": "2",
 "tylenol with codeine #4": "2",
 "tusso-df": "2",
 "timoptic": "2",
 "tavist nighttime allergy": "2",
 "thiethylperazine": "2",
 "t- koff": "2",
 "tussirex sugar free": "2",
 "tranquil nighttime sleep aid": "2",
 "teveten hct": "2",
 "tenormin": "2",
 "tussafin liquid": "2",
 "temaril": "2",
 "tussafed-hcg": "2",
 "treprostinil": "2",
 "talacen": "2",
 "tussigon": "2",
 "troleandomycin": "3",
 "trihist-cs": "2",
 "tylenol sore throat nighttime": "2",
 "tussin-v": "2",
 "theomax df": "2",
 "tylenol with codeine": "2",
 "tranxene sd": "2",
 "trandolapril/verapamil": "2",
 "tridal": "2",
 "tetrabenazine": "2",
 "tussi-organidin nr": "2",
 "tenoretic": "2",
 "tussive hc": "2",
 "triant-hc": "2",
 "tuss-ds": "2",
 "tranxene": "2",
 "tornalate": "2",
 "twilite": "2",
 "trisenox": "3",
 "thioridazine": "3",
 "trifluoperazine": "2",
 "trichlormethiazide": "2",
 "telavancin": "2",
 "triazolam": "2",
 "t-gesic": "2",
 "tenoretic 50": "2",
 "thalitone": "2",
 "tylenol pm": "2",
 "tussgen expectorant": "2",
 "talwin": "2",
 "tussar sf": "2",
 "tussend expectorant": "2",
 "tussirex": "2",
 "trandate": "2",
 "tamone": "2",
 "tiazac": "2",
 "theracodophen low 90": "2",
 "theodrine": "2",
 "torecan": "2",
 "tofranil-pm": "2",
 "tusana-d": "2",
 "tussicle": "2",
 "tylox": "2",
 "timolide": "2",
 "total allergy": "2",
 "tuss-hc": "2",
 "tussadur-hd": "2",
 "tylenol allergy complete nighttime": "2",
 "tussend": "2",
 "telithromycin": "3",
 "timoptic-xe": "2",
 "tl-hist cd": "2",
 "temazepam": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "telaprevir": "3",
 "timoptic ocudose": "2",
 "thorazine": "2",
 "tuss-pd": "2",
 "tasigna": "3",
 "timolol": "2",
 "tussafin": "2",
 "tusso-c": "2",
 "trycet": "2",
 "theraflu warming relief sinus &amp; cold": "2",
 "tusdec-hc": "2",
 "tussicaps": "2",
 "trazodone": "2",
 "tequin": "3",
 "tl-hist cm": "2",
 "trandolapril": "2",
 "tenoretic 100": "2",
 "tranxene t-tab": "2",
 "triflupromazine": "2",
 "tusso-hc": "2",
 "triavil": "2",
 "theraflu thin strips multi symptom": "2",
 "terfenadine": "2",
 "tekturna hct": "2",
 "tamosin": "2",
 "tagamet": "1",
 "trimeprazine": "2",
 "trancopal": "2",
 "tamofen": "2",
 "timolide 10-25": "2",
 "tedrigen": "2",
 "tylenol with codeine #3": "2",
 "touro hc": "2",
 "tambocor": "2",
 "talwin compound": "2",
 "tequin teqpaq": "3",
 "tencon": "2",
 "triaminic night time cold &amp; cough": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "trimal dh": "2",
 "tikosyn": "3",
 "tolazoline": "2",
 "tenake": "2",
 "tofranil": "2",
 "triaprin": "2",
 "triafed &amp; codeine": "2",
 "tarka": "2",
 "tamoxifen hexal": "2",
 "terbutaline": "2",
 "trifed c": "2",
 "trezix": "2",
 "tadalafil": "2",
 "tri-hydroserpine": "2",
 "tao": "3",
 "trilafon": "2",
 "tussar-2": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "trimipramine": "2",
 "tricof": "2",
 "tylenol severe allergy": "2",
 "tussplex": "2",
 "tussinate": "2",
 "taztia xt": "2",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tusstat": "2",
 "tribenzor": "2",
 "triaminic thin strips allergy": "2",
 "toremifene": "3",
 "tussafed-hc": "2",
 "triad": "2",
 "triacin c": "2",
 "tamsulosin": "2",
 "teczem": "2",
 "tagamet hb": "1",
 "tuinal": "2",
 "trux-adryl": "2",
 "tacaryl": "2",
 "tussgen": "2",
 "tusscough dhc": "2",
 "tacrolimus": "2",
 "triaminic thin strips cough &amp; runny nose": "2",
 "tamoxen": "2",
 "tylenol allergy multi-symptom nighttime": "2",
 "tykerb": "2",
 "two-dyne": "2",
 "tussi-organidin-s nr": "2"}, "w": {"welltuss hc": "2",
 "wellbutrin xl": "2",
 "welltuss exp": "2",
 "wygesic": "2",
 "wal-nadol pm extra strength": "2",
 "wal-zyr d": "2",
 "wellbutrin sr": "2",
 "wellbutrin": "2"}, "v": {"vivactil": "2",
 "vibativ": "2",
 "versed": "2",
 "ventuss syrup": "2",
 "vanex-hd": "2",
 "vanex expectorant": "2",
 "vasopressin": "2",
 "vistaril": "2",
 "vitussin expectorant": "2",
 "vaprisol": "3",
 "verelan pm": "2",
 "vfend": "3",
 "vanspar": "2",
 "v-gan-50": "2",
 "vasotec": "2",
 "vetuss hc syrup": "2",
 "volmax": "2",
 "viracept": "3",
 "vospire er": "2",
 "vascor": "3",
 "vasotuss hc": "2",
 "vopac": "2",
 "viagra": "2",
 "vardenafil": "2",
 "vicodin": "2",
 "verelan": "2",
 "valu-dryl": "2",
 "vicodin es": "2",
 "vazotuss hc": "2",
 "victrelis": "3",
 "vanatrip": "2",
 "vanacon": "2",
 "ventolin": "2",
 "vi-q-tuss": "2",
 "verapamil": "2",
 "vicotuss": "2",
 "votrient": "2",
 "visudyne": "2",
 "vemurafenib": "3",
 "vicoclear": "2",
 "veletri": "2",
 "v-gan-25": "2",
 "venlafaxine": "2",
 "vicodin hp": "2",
 "valium": "2",
 "vanadom": "2",
 "vistazine": "2",
 "visvex": "2",
 "vandetanib": "3",
 "ventolin hfa": "2",
 "ventavis": "2",
 "voriconazole": "3",
 "vaseretic": "2",
 "vortex": "2",
 "valrelease": "2",
 "vanacof cd": "2",
 "vaseretic 10-25": "2",
 "vicoprofen": "2",
 "vaseretic 5-12.5": "2",
 "vicodin tuss": "2",
 "visken": "2",
 "verteporfin": "2"}, "y": {"yutopar": "2"}, "x": {"xopenex": "2",
 "xopenex hfa": "2",
 "xanax xr": "2",
 "xanax": "2",
 "xyzal": "2",
 "xolox": "2",
 "xpect-hc": "2",
 "xalkori": "3",
 "xopenex concentrate": "2",
 "xodol": "2",
 "xenazine": "2"}, "z": {"zagam respipac": "3",
 "zmax": "2",
 "z-cof hcx": "2",
 "zyrtec-d": "2",
 "zymine hc": "2",
 "zafirlukast": "2",
 "zodryl ac": "2",
 "zuplenz": "2",
 "zutripro": "2",
 "zyrtec hives": "2",
 "ztuss zt": "2",
 "zelboraf": "3",
 "z-cof hc": "2",
 "zyrtec-d 12 hour": "2",
 "zamicet": "2",
 "zithromax": "2",
 "zonalon": "2",
 "zebeta": "2",
 "zolpidem": "2",
 "ziprasidone": "3",
 "zolvit": "2",
 "zyvox": "2",
 "zyprexa intramuscular": "2",
 "zofran": "2",
 "zestoretic": "2",
 "zerlor": "2",
 "zodryl dac": "2",
 "zebutal": "2",
 "zodryl dec": "2",
 "z-tuss ac": "2",
 "zolpimist": "2",
 "zagam": "3",
 "z-tuss 2": "2",
 "zyban": "2",
 "zofran odt": "2",
 "zaponex": "3",
 "zelapar": "2",
 "zotex hc": "2",
 "zanaflex": "2",
 "zyrtec": "2",
 "zotex-c": "2",
 "zydone": "2",
 "zyprexa zydis": "2",
 "zestril": "2",
 "zaroxolyn": "2",
 "zyprexa relprevv": "2",
 "zetran": "2",
 "ziac": "2",
 "zyprexa": "2",
 "zaleplon": "2"}}];