interactions["aliskiren-amlodipine,tekamlo"]=["aliskiren-amlodipine,tekamlo", {"5": {"50 + companion": "2"}, "a": {"aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "aspirin/hydrocodone": "2",
 "anergan 50": "2",
 "anacin": "2",
 "agenerase": "2",
 "arduan": "2",
 "aspergum": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "1",
 "aristocort": "2",
 "aldoril 25": "1",
 "alfenta": "2",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "ascriptin enteric": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "advil liqui-gels": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "aflaxen": "2",
 "aricept": "2",
 "aldactone": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "actiq": "2",
 "aspirin/oxycodone": "2",
 "apo-go pen": "2",
 "advil pm": "2",
 "aspir-low": "2",
 "aspir-mox": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "ambenyl": "2",
 "alcalak": "2",
 "aldoril": "1",
 "allfen cdx": "2",
 "amlodipine/telmisartan": "2",
 "azdone": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "aldoril 15": "1",
 "atapryl": "2",
 "apraclonidine ophthalmic": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "alor 5/500": "2",
 "argesic-sa": "2",
 "alka-seltzer plus flu formula": "2",
 "arthritis pain formula": "2",
 "anacin advanced headache formula": "2",
 "aminatal plus new formula": "2",
 "addaprin": "2",
 "acetaminophen/caffeine/dihydrocodeine": "2",
 "anaflex": "2",
 "aspirin buffered": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "atropine/phenobarbital": "2",
 "atacand hct": "2",
 "aldoril d50": "1",
 "aminosyn ii with electrolytes": "2",
 "aminatal plus": "2",
 "amlodipine/atorvastatin": "2",
 "amlobenz": "2",
 "azilect": "2",
 "atazanavir": "2",
 "aspirin/pravastatin": "2",
 "aquadeks": "2",
 "advil cold and sinus liqui-gels": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "aldesleukin": "2",
 "aricept odt": "2",
 "atacand": "2",
 "anhydrous calcium iodide/codeine": "2",
 "acetaminophen/aspirin": "2",
 "a-hydrocort": "2",
 "accuretic": "2",
 "anaprox": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "aminosyn ii 4.25%-dextrose 25%,electrolyte,ca": "2",
 "alka-seltzer plus immunity complex": "2",
 "asenapine": "2",
 "aspirin/caffeine": "2",
 "abc to z": "2",
 "accesspak for hiv pep expanded with viracept": "2",
 "aspirin/dipyridamole": "2",
 "ambifed-g cd": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "ascomp with codeine": "2",
 "alka-seltzer extra strength": "2",
 "aminosyn ii 3.5%-dextrose 25%,electrolytes,ca": "2",
 "alkets": "2",
 "aliskiren/valsartan": "2",
 "advil children's allergy sinus": "2",
 "acetaminophen/aspirin/caffeine": "2",
 "aleve": "2",
 "amprenavir": "2",
 "adrenocot": "2",
 "aminosyn ii 4.25%-dextrose 20%,electrolyte,ca": "2",
 "adlone-40": "2",
 "adult strength": "2",
 "atenolol": "2",
 "aspirin/butalbital": "2",
 "aristospan": "2",
 "arthritis pain": "2",
 "aminate": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "ami-lac": "2",
 "accupril": "2",
 "aspirin/methocarbamol": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "arthriten": "2",
 "acthar": "2",
 "actemra": "2",
 "a-g profen": "2",
 "avapro": "2",
 "a-methapred": "2",
 "acetocot": "2",
 "alka-seltzer wake-up call!": "2",
 "aggrenox": "2",
 "alkabel-sr": "2",
 "advil allergy sinus": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "aquatensen": "1",
 "alka-seltzer original": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "antispas": "2",
 "aminatal plus one": "2",
 "abc plus senior": "2",
 "ascriptin maximum strength": "2",
 "aminosyn with electrolytes": "2",
 "amiloride": "2",
 "amigesic": "2",
 "aceon": "2",
 "aristocort for injection": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "aminate with 90 mg iron": "2",
 "antioxidant formula": "2",
 "alka-seltzer lemon-lime": "2",
 "allfen cd": "2",
 "apomorphine": "2",
 "advil children's cold": "2",
 "aspirin/butalbital/caffeine": "2",
 "arthropan": "2",
 "amlodipine/benazepril": "2",
 "amitone": "2",
 "aspirin/meprobamate": "2",
 "anectine": "2",
 "airacof": "2",
 "accolate": "2",
 "advance care plus": "2",
 "azmacort": "2",
 "advil migraine": "2",
 "all day relief": "2",
 "abilify": "2",
 "acetaminophen/oxycodone": "2",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "all day pain relief": "2",
 "amobarbital/secobarbital": "2",
 "aspirin/phenyltoloxamine": "2",
 "advil infant's concentrated drops": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "actiprofen": "2",
 "aprepitant": "2",
 "anectine flo-pack": "2",
 "actonel with calcium": "2",
 "ak-beta": "2",
 "alka-mints": "2",
 "alka-seltzer plus cold formula": "2",
 "antispasmodic": "2",
 "alka-seltzer pm": "2",
 "apokyn": "2",
 "aspirin/diphenhydramine": "2",
 "ambifed-g cdx": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "altace": "2",
 "acetaminophen/codeine": "2",
 "antrocol": "2",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "apetigen-plus": "2",
 "alkums": "2",
 "aspirin/carisoprodol/codeine": "2",
 "aspirin": "2",
 "acetaminophen/aspirin/phenylpropanolamine": "2",
 "alphen expectorant": "2",
 "adlone-80": "2",
 "allerfrin with codeine": "2",
 "aspirin/calcium carbonate": "2",
 "apresazide": "1",
 "alahist dhc": "2",
 "advanced am/pm": "2",
 "amifostine": "2",
 "aleve-d sinus &amp; cold": "2",
 "aplenzin": "2",
 "aldoclor-250": "1",
 "acuprin 81": "2",
 "azilsartan medoxomil": "2",
 "apo-go": "2",
 "aceta w/ codeine": "2",
 "azor": "2",
 "advil junior strength": "2",
 "anacin max strength": "2",
 "alfentanil": "2",
 "ambifed cd": "2",
 "ambophen": "2",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "aliskiren/hydrochlorothiazide": "1",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "adbeon": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "avail calcium intensive": "2",
 "aspirtab": "2",
 "atracurium": "2",
 "alphagan p": "1",
 "amiodarone": "2",
 "aldoclor-150": "1",
 "aminosyn ii with electrolytes sulfite-free": "2",
 "anaprox-ds": "2",
 "avinza": "2",
 "aspiritab": "2",
 "aripiprazole": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "aminosyn with electrolytes sulfite-free": "2",
 "acetaminophen/pentazocine": "2",
 "ascriptin": "2",
 "atripla": "2",
 "atenolol/chlorthalidone": "2",
 "actron": "2",
 "afinitor": "2",
 "ami-natal plus one improved": "2",
 "aspirin/carisoprodol": "2",
 "aristopak": "2",
 "acetaminophen/propoxyphene": "2",
 "atabex ec": "2",
 "alphagan": "1",
 "avalide": "2",
 "acebutolol": "2",
 "atorvastatin": "2",
 "aspirin/pseudoephedrine": "2",
 "apatate forte": "2",
 "arthrotec": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "aldoril d30": "1",
 "aquadeks pediatric": "2",
 "acthrel": "2",
 "amiloride/hydrochlorothiazide": "2",
 "advil": "2",
 "astramorph pf": "2",
 "adrenocot la": "2",
 "anhydrous calcium iodide/isoproterenol": "2",
 "acth": "2",
 "atamet": "2",
 "aspircaf": "2",
 "aquacot": "1",
 "atrosept": "2",
 "amlodipine/olmesartan": "2",
 "alka-seltzer gold": "2",
 "antioxidant ultra formula": "2",
 "armodafinil": "1",
 "acetylsalicylic acid": "2",
 "acid reducer + antacid dual action": "2",
 "adeks": "2",
 "aspirin lite coat": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "anemagen ob": "2",
 "aquazide h": "1",
 "aspir 81": "2",
 "anzemet": "3",
 "amturnide": "1",
 "aspirin/codeine": "2",
 "advil cold and sinus": "2",
 "aspirin/pentazocine": "2",
 "ansaid": "2",
 "aspirin low strength": "2",
 "abstral": "2",
 "aspir-mox ib": "2",
 "amlodipine/valsartan": "2",
 "ala-hist ac": "2",
 "aldactazide": "2",
 "advil children's": "2",
 "adcirca": "1",
 "aspirin/caffeine/salicylamide": "2",
 "arthritis foundation pain reliever": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "antioxid caplets": "2",
 "abilify discmelt": "2",
 "ambifed cdx": "2"}, "c": {"cycofed expectorant": "2",
 "calcitab": "2",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "cvs extra strength headache relief": "2",
 "chlorothiazide/methyldopa": "1",
 "calcium carbonate/risedronate": "2",
 "certa-vite senior plus lutein": "2",
 "compro": "2",
 "calcifolic-d": "2",
 "cartia xt": "2",
 "citracal kosher": "2",
 "cerebyx": "2",
 "centratex": "2",
 "chemdal expectorant": "2",
 "cal-nate": "2",
 "cycofed pediatric expectorant": "2",
 "century senior": "2",
 "capozide 50/25": "2",
 "cavan ec dha plus": "2",
 "calcium carbonate/fluoride": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "corticotropin": "2",
 "coldcough pd": "2",
 "calcidrine": "2",
 "calcarb with d": "2",
 "cotabflu": "2",
 "crixivan": "2",
 "conivaptan": "2",
 "cotab ax": "2",
 "calcionate": "2",
 "coreg": "2",
 "citracal regular": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "clozapine synthon": "2",
 "centavite": "2",
 "concept dha": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "cardizem cd": "2",
 "combunox": "2",
 "chlorthalidone/reserpine": "1",
 "citric acid/potassium citrate/sodium citrate": "2",
 "cozaar": "2",
 "companion multi": "2",
 "childrens ibuprofen berry": "2",
 "cytra-3": "2",
 "co natal fa": "2",
 "conceptionxr rhf": "2",
 "choline magnesium trisalicylate": "2",
 "cmt": "2",
 "compound 374": "2",
 "capoten": "2",
 "corzide 40/5": "2",
 "children's motrin": "2",
 "carbidopa/levodopa": "2",
 "cardizem sr": "2",
 "calcium oyster shell": "2",
 "cosopt": "2",
 "co-histine expectorant": "2",
 "cortenema": "2",
 "cheracol with codeine": "2",
 "corvita": "2",
 "cort-k": "2",
 "calcid": "2",
 "clotrimazole": "2",
 "cheratussin dac": "2",
 "corlopam": "2",
 "corvita 150": "2",
 "colrex compound": "2",
 "celestone phosphate": "2",
 "cortef": "2",
 "century-vite": "2",
 "corgard": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "calan sr": "2",
 "carbex": "2",
 "clozapine": "2",
 "completenate": "2",
 "clopine": "2",
 "capital w/codeine": "2",
 "carozide": "1",
 "cap-profen": "2",
 "cardizem": "2",
 "caduet": "2",
 "chlorothiazide/reserpine": "1",
 "carisoprodol compound": "2",
 "combigan": "2",
 "combiflex es": "2",
 "chloromycetin sodium succinate": "2",
 "cordarone": "2",
 "centrum silver": "2",
 "calcium phosphate, tribasic": "2",
 "calcium gluconate": "2",
 "chromagen ob": "2",
 "carenatal dha": "2",
 "citracal + d": "2",
 "cabergoline": "2",
 "citracal prenatal rx": "2",
 "cardizem la": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "caltrate plus": "2",
 "calan": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "cystex": "2",
 "caffeine/magnesium salicylate": "2",
 "chlorpheniramine/codeine": "2",
 "centrum performance": "2",
 "cosyntropin": "2",
 "caltrate colon health": "2",
 "centrum silver men's": "2",
 "comfort pac with naproxen": "2",
 "complete-rf": "2",
 "century": "2",
 "centrum special energy": "2",
 "cymbalta": "2",
 "compazine spansule": "2",
 "codahistine expectorant": "2",
 "carbidopa/entacapone/levodopa": "2",
 "clorpres": "1",
 "cerovite senior": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "certagen senior with lutein": "2",
 "cavan folate": "2",
 "coreg cr": "2",
 "citracal calcium gummies": "2",
 "corzide 80/5": "2",
 "citracal regular 250 mg + d": "2",
 "cortifoam": "2",
 "calcium carbonate/simethicone": "2",
 "candesartan/hydrochlorothiazide": "2",
 "colrex": "2",
 "centrum silver women's": "2",
 "calafol rx": "2",
 "calcium chloride": "2",
 "certavite with antioxidants": "2",
 "candesartan": "2",
 "cortrosyn": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "calcium gluceptate": "2",
 "circavite t": "2",
 "calcium lactate": "2",
 "centrum specialist vision": "2",
 "clozaril": "2",
 "codeine/pseudoephedrine/triprolidine": "2",
 "codegest expectorant": "2",
 "cerovite junior": "2",
 "certavite with lutein": "2",
 "caltrate 600+d": "2",
 "central": "2",
 "calcium glycerophosphate": "2",
 "caromega": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "cell-u-jec": "2",
 "chlorcyclizine/codeine": "2",
 "centrum silver ultra women's": "2",
 "cezin-s": "2",
 "citric acid/potassium bicarbonate": "2",
 "centussin dhc": "2",
 "centrum kids": "2",
 "cal-g": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "cardioquin": "2",
 "caltrate 600 plus": "2",
 "calcium carbonate/magnesium carbonate": "2",
 "chloromycetin": "2",
 "corvite": "2",
 "capital with codeine suspension": "2",
 "cocet plus": "2",
 "citrus calcium with vitamin d": "2",
 "clinoril": "2",
 "clarithromycin": "2",
 "certagen senior": "2",
 "citracal prenatal 90+dha": "2",
 "corvite 150": "2",
 "central-vite": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "clinalog": "2",
 "centrum cardio": "2",
 "co-histine dh": "2",
 "citrolith": "2",
 "citranatal harmony": "2",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "centrum": "2",
 "codeine/phenylephrine": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "centrum special heart": "2",
 "calcitrate with d": "2",
 "cognex": "2",
 "cisatracurium": "2",
 "cordarone iv": "2",
 "calcio del mar": "2",
 "caltrate 600 with d plus soy": "2",
 "cardizem monovial": "2",
 "cataflam": "2",
 "codehist dh": "2",
 "carbatrol": "2",
 "codeine/pseudoephedrine": "2",
 "capozide 25/15": "2",
 "citracal plus magnesium": "2",
 "cytra-k": "2",
 "centrum silver ultra men's": "2",
 "cal-gest": "2",
 "cortisone": "2",
 "caldolor": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "certavite": "2",
 "calcet": "2",
 "choline salicylate/magnesium salicylate": "2",
 "caltro with vitamin d": "2",
 "crizotinib": "2",
 "carteolol": "2",
 "combi rx": "2",
 "cimetidine": "2",
 "calcium carbonate": "2",
 "centrum jr with extra calcium": "2",
 "codimal ph": "2",
 "cal oys": "2",
 "cenogen ultra": "2",
 "carbamazepine": "2",
 "cyndal expectorant": "2",
 "childrens kaopectate": "2",
 "coldcough syrup": "2",
 "clinacort": "2",
 "carvedilol": "2",
 "calcium disodium versenate": "2",
 "clinimix e sulfite free": "2",
 "cena k": "2",
 "corticorelin": "2",
 "capozide 50/15": "2",
 "chewable calcium with vitamin d": "2",
 "cal-glu": "2",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "cyclosporine": "3",
 "codeprex": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "codahistine-dh elixir": "2",
 "cartrol": "2",
 "cosopt pf": "2",
 "clotrimazole troche": "2",
 "corvite free": "2",
 "calciquid": "2",
 "cotolone": "2",
 "citranatal assure": "2",
 "choline salicylate": "2",
 "calci mix": "2",
 "cycofed": "2",
 "citranatal dha": "2",
 "compazine": "2",
 "chloracol": "2",
 "celestone soluspan": "2",
 "codeine/phenylephrine/promethazine": "2",
 "covera-hs": "2",
 "codafed pediatric": "2",
 "cafgesic forte": "2",
 "complete natal dha": "2",
 "codeine/promethazine": "2",
 "cortone acetate": "2",
 "calcifol": "2",
 "captopril/hydrochlorothiazide": "2",
 "cf vite": "2",
 "chloramphenicol": "2",
 "citracal petites": "2",
 "calcium oyster": "2",
 "compete": "2",
 "cocet": "2",
 "cystemms-v": "2",
 "clusimar": "2",
 "calcarb": "2",
 "codeine phosphate-promethazine hcl": "2",
 "captopril": "2",
 "citric acid/potassium citrate": "2",
 "citranatal rx": "2",
 "calcium, magnesium and zinc": "2",
 "chlorpromazine": "2",
 "calcium acetate/magnesium carbonate": "2",
 "codafed": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "complete a-z": "2",
 "cerovite liquid": "2",
 "calcium/vitamin d": "2",
 "carteolol ophthalmic": "2",
 "cope": "2",
 "certa-vite": "2",
 "calcium concentrate": "2",
 "celestone": "2",
 "caltrate 600+d plus minerals": "2",
 "cheratussin ac": "2",
 "cavan-folate dha": "2",
 "colocort": "2",
 "conceptionxr msf": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "codeine/guaifenesin": "2",
 "citranatal b-calm": "2",
 "calvite p": "2",
 "calphron": "2",
 "calphosan": "2",
 "cavan-heme ob": "2",
 "citranatal 90 dha": "2",
 "citracal plus bone density builder": "2",
 "calcium glycerophosphate/calcium lactate": "2",
 "citracal maximum": "2",
 "citracal plus heart health": "2",
 "centrum ultra men's": "2",
 "chlorothiazide": "1",
 "chardonna-2": "2",
 "citracal slow release 1200": "2",
 "cialis": "1",
 "codafen": "2",
 "calcium 600 d": "2",
 "chlorthalidone": "1",
 "calcium acetate": "2",
 "citracal prenatal + dha": "2",
 "complete natal": "2",
 "calcium glubionate": "2",
 "corzide": "2",
 "capozide": "2",
 "capozide 25/25": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "calcium liquid softgel": "2",
 "concept ob": "2",
 "chlorthalidone/clonidine": "1",
 "certagen": "2",
 "codeine": "2",
 "centrum ultra women's": "2",
 "cavan one": "2",
 "calcium citrate": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "caltrate gummy bites": "2",
 "cotab a": "2",
 "caltrate": "2",
 "caltro": "2",
 "cerovite advanced formula": "2",
 "calci-chew": "2",
 "cambia": "2",
 "chooz": "2",
 "calcet plus": "2"}, "b": {"bellaphen-s": "2",
 "brevibloc": "2",
 "biaxin xl": "2",
 "butisol sodium": "2",
 "bitex liquid": "2",
 "betaxolol": "2",
 "bugs bunny complete": "2",
 "betoptic": "2",
 "betagan c-cap": "2",
 "butorphanol": "2",
 "biaxin": "2",
 "bystolic": "2",
 "betoptic s": "2",
 "benzthiazide": "1",
 "bayer pm": "2",
 "bayer aspirin extra strength plus": "2",
 "b c powder arthritis strength": "2",
 "bromodiphenhydramine/codeine": "2",
 "benicar hct": "2",
 "buspirone": "2",
 "bel-phen-ergot": "2",
 "brimonidine/timolol ophthalmic": "2",
 "bayer women's aspirin with calcium": "2",
 "buffasal": "2",
 "butabarbital": "2",
 "betaxolol ophthalmic": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "bacmin": "2",
 "betapace af": "2",
 "belladonna/butabarbital": "2",
 "bayer children's aspirin": "2",
 "brovex cbx": "2",
 "buspar": "2",
 "brovex pb cx": "2",
 "betapace": "2",
 "brovex cb": "2",
 "b c powder": "2",
 "biotin forte with zinc": "2",
 "bayer extra strength back &amp; body": "2",
 "beta-phos/ac": "2",
 "biotussin dac": "2",
 "buffered aspirin": "2",
 "butrans": "2",
 "budeprion sr": "2",
 "bupivacaine/hydromorphone": "2",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "beelith": "2",
 "becomax rx": "2",
 "buproban": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "betagan": "2",
 "bayer aspirin": "2",
 "balacet": "2",
 "b-nexa": "2",
 "bellaspas": "2",
 "betamethasone": "2",
 "boceprevir": "2",
 "bladder 2.2": "2",
 "bismatrol maximum strength": "2",
 "baycadron": "2",
 "bp multinatal plus chewables": "2",
 "bellamine": "2",
 "bufferin low dose": "2",
 "bayer select backache pain formula": "2",
 "bel-tabs": "2",
 "bendroflumethiazide": "1",
 "belladonna/opium": "2",
 "bendroflumethiazide/nadolol": "2",
 "bupropion": "2",
 "bismatrol": "2",
 "berocca plus": "2",
 "bayer advanced aspirin": "2",
 "bayer am": "2",
 "brimonidine ophthalmic": "1",
 "bosentan": "2",
 "bc headache": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "budeprion": "2",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bayer aspirin with heart advantage": "2",
 "budesonide/formoterol": "2",
 "butibel": "2",
 "bendroflumethiazide/rauwolfia serpentina": "1",
 "buffered salt": "2",
 "bromfenac": "2",
 "buprenorphine/naloxone": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "2",
 "betimol": "2",
 "brompheniramine/codeine": "2",
 "b-plex plus minerals": "2",
 "buprenex": "2",
 "bisoprolol": "2",
 "bismuth subsalicylate": "2",
 "brovex pb c": "2",
 "budeprion xl": "2",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "buprenorphine": "2",
 "betamed": "2",
 "bayer aspirin regimen": "2",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine s": "2",
 "bufferin": "2",
 "bellatal er": "2",
 "blocadren": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "bayer women's low dose plus calcium": "2",
 "benazepril/hydrochlorothiazide": "2",
 "bee-zee": "2",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "brontex": "2",
 "b &amp; o supprettes": "2",
 "brilinta": "1",
 "bupivacaine/fentanyl": "2",
 "betaxon": "2",
 "butalbital compound": "2",
 "bismarex": "2",
 "buffex": "2",
 "budesonide": "2",
 "benazepril": "2",
 "bellamor": "2",
 "bufferin arthritis strength": "2",
 "bufferin extra strength": "2",
 "bc fast pain relief": "2",
 "busodium": "2",
 "benicar": "2",
 "berplex plus": "2",
 "barbidonna": "2",
 "bright beginnings": "2",
 "bellatal": "2",
 "bubbli-pred": "2",
 "brompheniramine/codeine/pseudoephedrine": "2"}, "e": {"essentia": "2",
 "ecotrin maximum strength": "2",
 "entaprin": "2",
 "effer-k": "2",
 "emsam": "2",
 "equilet": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "ec-naprosyn": "2",
 "e.e.s.-400": "2",
 "eprosartan": "2",
 "emend": "2",
 "eryped": "2",
 "emagrin": "2",
 "enflurane": "2",
 "excedrin menstrual complete": "2",
 "epoprostenol": "2",
 "endocet": "2",
 "effervescent pain relief": "2",
 "embeda": "2",
 "exalgo": "2",
 "eperbel-s": "2",
 "exforge hct": "2",
 "execlear-c": "2",
 "esidrix": "1",
 "erythrocot": "2",
 "elemental iron-90": "2",
 "ed k+10": "2",
 "effervescent potassium": "2",
 "edarbi": "2",
 "erythromycin": "2",
 "ecotrin adult low strength": "2",
 "equi-natal plus": "2",
 "ellis tonic sherry": "2",
 "edge ob": "2",
 "erythrocin": "2",
 "easprin": "2",
 "endal expectorant": "2",
 "elixiral": "2",
 "edarbyclor": "2",
 "erythrocin lactobionate": "2",
 "elite ob with dha": "2",
 "emend 2-day": "2",
 "eldercaps": "2",
 "enalapril/felodipine": "2",
 "enduron": "1",
 "ecpirin": "2",
 "esmolol": "2",
 "exforge": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "emend 3-day": "2",
 "endal cd": "2",
 "e s p": "2",
 "e.e.s.-200": "2",
 "esimil": "1",
 "etrafon forte": "2",
 "ethyol": "2",
 "equi-natal care": "2",
 "exna": "1",
 "everolimus": "2",
 "equetro": "2",
 "equaline acid reducer": "2",
 "epitol": "2",
 "elixophyllin ki": "2",
 "equinatal 90": "2",
 "efavirenz": "2",
 "embrex 600": "2",
 "ecee plus": "2",
 "emend for injection": "2",
 "ecotrin": "2",
 "enduronyl": "1",
 "emtricitabine/nelfinavir/tenofovir": "2",
 "effexor xr": "2",
 "endacof-dc": "2",
 "exjade": "2",
 "effervescent potassium/chloride": "2",
 "endacof-dh": "2",
 "e.e.s.-400 filmtab": "2",
 "eldepryl": "2",
 "entocort ec": "2",
 "extra strength mylanta calci tabs": "2",
 "excedrin back &amp; body": "2",
 "elite ob 400": "2",
 "e-mycin": "2",
 "endocodone": "2",
 "exelon": "2",
 "endodan": "2",
 "eth-oxydose": "2",
 "entercote": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "eskalith": "2",
 "efasin expectorant sf": "2",
 "ezetimibe/simvastatin": "3",
 "ephedrine/potassium iodide": "2",
 "empirin with codeine": "2",
 "equi-natal rx": "2",
 "endotuss expectorant": "2",
 "excedrin migraine": "2",
 "enalapril": "2",
 "epiklor": "2",
 "ezide": "1",
 "equagesic": "2",
 "effexor": "2",
 "ez iii": "2",
 "eldertonic": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "encora": "2",
 "eliphos": "2",
 "ery-tab": "2",
 "excedrin extra strength": "2",
 "elppa daily": "2",
 "ethotoin": "2",
 "enditussin expectorant": "2",
 "etrafon": "2",
 "esomeprazole/naproxen": "2",
 "endacof-c": "2",
 "erythromycin/sulfisoxazole": "2",
 "e.e.s. granules": "2",
 "eryc": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "edetate calcium disodium": "2",
 "extra strength bayer": "2",
 "etravirine": "2",
 "endacof-ac": "2",
 "etodolac": "2",
 "erythrocin stearate filmtab": "2",
 "equi-natal z": "2",
 "ethrane": "2",
 "eskalith-cr": "2",
 "empirin": "2",
 "eye health formula": "2",
 "equi-natal m": "2",
 "eryzole": "2",
 "excedrin": "2",
 "enduronyl forte": "1",
 "elon matrix 5000 complete": "2"}, "d": {"diovan": "2",
 "duramorph pf": "2",
 "dialyvite 3000": "2",
 "diltzac": "2",
 "desflurane": "2",
 "duragesic-75": "2",
 "demi-regroton": "1",
 "dronedarone": "2",
 "delavirdine": "2",
 "duet dha ec": "2",
 "doral": "2",
 "diuril": "1",
 "duramorph": "2",
 "dep medalone 80": "2",
 "diltiazem hydrochloride cd": "2",
 "duloxetine": "2",
 "diovan hct": "2",
 "depo-medrol": "2",
 "disney winnie the pooh with extra c": "2",
 "dextromethorphan/quinidine": "2",
 "duo-vil": "2",
 "doan's pills": "2",
 "demi-cof": "2",
 "donatuss dc": "2",
 "deproist with codeine": "2",
 "dihydrocodeine/guaifenesin/phenylephrine": "2",
 "diupres-500": "1",
 "dostinex": "2",
 "di-gel mint": "2",
 "dical captabs": "2",
 "depmedalone": "2",
 "dextrose 5% and electrolyte no. 48 injection": "2",
 "doans pm": "2",
 "dazidox": "2",
 "daily combo": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "dicarbosil": "2",
 "decadron with xylocaine": "2",
 "dexamethasone/lidocaine": "2",
 "darvon compound 32": "2",
 "duragesic-50": "2",
 "dalalone la": "2",
 "docosavit": "2",
 "dalfopristin/quinupristin": "2",
 "dexone": "2",
 "daypro": "2",
 "duohist dh": "2",
 "dihistine dh": "2",
 "duet chewable": "2",
 "damason-p": "2",
 "diclofenac": "2",
 "dex-tuss": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "2",
 "dihistine": "2",
 "duralone": "2",
 "despec-pd": "2",
 "dexpak taperpak": "2",
 "diphenhydramine/ibuprofen": "2",
 "dexacort phosphate in turbinaire": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "disney winnie the pooh complete": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "darcalma": "2",
 "diupres-250": "1",
 "dilaudid-hp": "2",
 "diltiazem hydrochloride xt": "2",
 "diltiazem hydrochloride xr": "2",
 "dilaudid cough syrup": "2",
 "diaqua-2": "2",
 "duragesic-25": "2",
 "deltasone": "2",
 "diltiazem": "2",
 "dihydro-pe": "2",
 "duragesic": "2",
 "duragesic-100": "2",
 "dialyvite 800 ultra d": "2",
 "dexacort-la": "2",
 "dermavite": "2",
 "dolobid": "2",
 "dolomite": "2",
 "dexamethasone": "2",
 "decohistine dh": "2",
 "donepezil": "2",
 "dilacor xr": "2",
 "dihydro-cp": "2",
 "diaqua": "1",
 "dilaudid": "2",
 "dualvit ob": "2",
 "dyrenium": "2",
 "duet dha complete": "2",
 "dalalone dp": "2",
 "deserpidine/methyclothiazide": "1",
 "decohistine expectorant": "2",
 "dexasone": "2",
 "diurese": "1",
 "donnatal": "2",
 "dutoprol": "2",
 "doans pills extra strength": "2",
 "dual action complete": "2",
 "deferasirox": "2",
 "dical-d": "2",
 "darvon-n": "2",
 "darpaz": "2",
 "dihistine expectorant": "2",
 "delta-cortef": "2",
 "dihydrocodeine/guaifenesin": "2",
 "dialyvite 5000": "2",
 "daily multi-vitamins with minerals": "2",
 "dristan sinus": "2",
 "dopar": "2",
 "diurex": "2",
 "darvon": "2",
 "dolsed": "2",
 "diuretic ap-es": "1",
 "droperidol/fentanyl": "2",
 "daily multiple for men 50+": "2",
 "dexasone la": "2",
 "dasatinib": "2",
 "duragal-s": "2",
 "diavite plus": "2",
 "diabetic tussin c": "2",
 "danocrine": "2",
 "dyazide": "2",
 "darvon compound-65": "2",
 "danazol": "2",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "disalcid": "2",
 "dialyvite with zinc rx": "2",
 "dihydro-gp": "2",
 "decadron": "2",
 "dihydrocodeine/guaifenesin/pseudoephedrine": "2",
 "d-tal": "2",
 "de-sone la": "2",
 "diltia xt": "2",
 "duet dha": "2",
 "durabac forte": "2",
 "dexacort phosphate in respihaler": "2",
 "dewitt's pain reliever": "2",
 "dicomal-ph": "2",
 "duet": "2",
 "deconsal c expectorant": "2",
 "denzapine": "2",
 "depopred": "2",
 "dorzolamide/timolol ophthalmic": "2",
 "dolophine": "2",
 "disney winnie the pooh gummies": "2",
 "duexis": "2",
 "diuril sodium": "1",
 "di-gel lemon": "2",
 "dexamethasone intensol": "2",
 "doxacurium": "2",
 "darvocet-n 100": "2",
 "decadron-la": "2",
 "daily-vite weight control": "2",
 "daily multiple for women 50+": "2",
 "deserpidine/hydrochlorothiazide": "1",
 "daily multiple for women": "2",
 "donnatal extentabs": "2",
 "diutensen-r": "1",
 "dexacorten": "2",
 "dexacen-4": "2",
 "doloral": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "2",
 "diucardin": "1",
 "deponit": "2",
 "diatx zn": "2",
 "darvocet-n 50": "2",
 "dolasetron": "3",
 "decaject la": "2",
 "duract": "2",
 "duraganidin nr": "2",
 "diltiazem hydrochloride sr": "2",
 "doloral sirop": "2",
 "diflucan": "2",
 "donnaphen": "2",
 "dexone la": "2",
 "dialyvite 800 with zinc": "2",
 "decagen": "2",
 "dicalphos plus d": "2",
 "dalalone": "2",
 "duragesic-12": "2",
 "demerol": "2",
 "darunavir": "2",
 "dihydrocodeine/phenylephrine": "2",
 "dilantin": "2",
 "dihistine expectorant with codeine": "2",
 "diclofenac/misoprostol": "2",
 "desvenlafaxine": "2",
 "dilt-xr": "2",
 "duet dha with ferrazone": "2",
 "darvocet a500": "2",
 "dextrose 10% and electrolyte no 48": "2",
 "decaject": "2"}, "g": {"gevrabon": "2",
 "glu-k": "2",
 "guaifen-c": "2",
 "goody's extra-strength headache powders": "2",
 "gen-k": "2",
 "genpril": "2",
 "gevratonic": "2",
 "genprin": "2",
 "genace": "2",
 "guaitussin ac": "2",
 "guaifen ac": "2",
 "guaifenesin dac liquid": "2",
 "gynovite": "2",
 "guiatussin dac": "2",
 "guiatuss dac": "2",
 "guiatuss ac": "2",
 "gengraf": "3",
 "garlic oil": "1",
 "geri-tonic": "2",
 "generix-t": "2",
 "guiatussin with codeine": "2",
 "goody's body pain": "2",
 "gas-x with maalox extra strength": "2",
 "gesticare dha dr": "2",
 "glutofac-mx": "2",
 "gennin-fc": "2",
 "glutofac-zx": "2",
 "gilenya": "2",
 "gold age liquid vitamins and minerals": "2",
 "gua pc": "2",
 "guaiatussin dac": "2",
 "guai-co": "2",
 "guanethidine/hydrochlorothiazide": "1",
 "gani-tuss nr": "2",
 "galantamine": "2",
 "geritol extend": "2",
 "genacote": "2",
 "giltuss ped-c": "2",
 "garlic": "1",
 "goodys headache powders": "2",
 "glydeine": "2",
 "gleevec": "2",
 "gas-x with maalox": "2",
 "garfield complete vitamins": "2",
 "genasan": "2",
 "geritol complete": "2",
 "gesticare dha": "2",
 "geodon": "2",
 "goodys extra strength": "2",
 "gesticare": "2",
 "gerivite liquid": "2",
 "guaiatussin ac": "2",
 "guaifen dac": "2",
 "grepafloxacin": "2",
 "guaifenesin/hydromorphone": "2"}, "f": {"flolan": "2",
 "foltabs plus dha": "2",
 "fenoldopam": "2",
 "fiortal": "2",
 "fentanyl/ropivacaine": "2",
 "fosfree": "2",
 "fingolimod": "2",
 "furosemide": "2",
 "fiorinal with codeine iii": "2",
 "fem-natal": "2",
 "fortovase": "2",
 "ferrocite plus": "2",
 "formula twenty-one": "2",
 "foltabs prenatal": "2",
 "fluphenazine": "2",
 "folivan-prx dha": "2",
 "fazaclo": "2",
 "femecal ob plus dha": "2",
 "folcaps omega 3": "2",
 "fortabs": "2",
 "florinef acetate": "2",
 "fanapt": "2",
 "fioricet with codeine": "2",
 "fosamprenavir": "2",
 "fluvoxamine": "2",
 "fasprin": "2",
 "fentanyl": "2",
 "fosphenytoin": "2",
 "folcaps care one": "2",
 "feldene": "2",
 "farbital": "2",
 "florinef": "2",
 "fast acting mylanta": "2",
 "fluconazole": "2",
 "forfivo xl": "2",
 "foli-iron": "2",
 "fiortal with codeine": "2",
 "famotidine/ibuprofen": "2",
 "fentora": "2",
 "fiorinal with codeine": "2",
 "flo-pred": "2",
 "fenoprofen": "2",
 "femnatal": "2",
 "fosinopril": "2",
 "fluoxetine/olanzapine": "2",
 "folbecal": "2",
 "forane": "2",
 "flintstones complete": "2",
 "folivan-ec dha": "2",
 "folcal dha": "2",
 "flurbiprofen": "2",
 "fludrocortisone": "2",
 "foltabs 90 plus dha": "2",
 "folgard os": "2",
 "femecal ob": "2",
 "folpace rx": "2",
 "foltabs prenatal plus dha": "2",
 "fiormor": "2",
 "floricet with codeine": "2",
 "foltabs": "2",
 "flintstones gummies": "2",
 "fiorinal": "2",
 "fentanyl transdermal system": "2",
 "florical": "2",
 "flintstones with calcium": "2",
 "fluothane": "2",
 "femtabs": "2",
 "folivan-ob": "2",
 "furoxone": "2",
 "fosaprepitant": "2",
 "furazolidone": "2",
 "freamine iii with electrolytes": "2",
 "fosinopril/hydrochlorothiazide": "2",
 "ferrex pc forte": "2",
 "formula b plus": "2",
 "flumezide": "1",
 "folbee plus cz": "2"}, "i": {"iophen": "2",
 "isoniazid/rifampin": "2",
 "icare prenatal rx": "2",
 "isoptin": "2",
 "inderide": "2",
 "icaps lutein &amp; omega-3": "2",
 "istalol": "2",
 "invirase": "2",
 "isolyte p and 5% dextrose": "2",
 "irbesartan": "2",
 "imatinib": "2",
 "iophen-c nr": "2",
 "ibuprofen": "2",
 "icaps tr": "2",
 "ibuprofen pmr": "2",
 "idenal": "2",
 "isolyte e": "2",
 "incivek": "2",
 "ibuprofen/oxycodone": "2",
 "invega": "2",
 "i-vite": "2",
 "isoniazid": "2",
 "isolyte r and 5% dextrose": "2",
 "icar prenatal chewable calcium": "2",
 "i-vite protect": "2",
 "icaps plus": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "ionosol b and 5% dextrose": "2",
 "inatal advance": "2",
 "iloprost": "2",
 "inderide la": "2",
 "ibudone": "2",
 "ibuprofen/pseudoephedrine": "2",
 "ibu-tab": "2",
 "indapamide": "1",
 "itraconazole": "3",
 "innopran xl": "2",
 "indocin iv": "2",
 "ilosone": "2",
 "inderal la": "2",
 "inatal ultra": "2",
 "iopidine": "2",
 "ibu-200": "2",
 "indocin": "2",
 "icaps areds": "2",
 "icar prenatal": "2",
 "ionosol mb and 5% dextrose": "2",
 "indinavir": "2",
 "icaps with lutein and zeaxan": "2",
 "isoflurane": "2",
 "infumorph": "2",
 "isonarif": "2",
 "iloperidone": "2",
 "iosat": "2",
 "isocarboxazid": "2",
 "isoptin sr": "2",
 "isoptin iv": "2",
 "indocin sr": "2",
 "inderal": "2",
 "i-sense": "2",
 "intelence": "2",
 "ionosol t and 5% dextrose": "2",
 "invega sustenna": "2",
 "indomethacin": "2",
 "infanate dha": "2",
 "isolyte h and 5 % dextrose": "2",
 "icaps mv": "2",
 "ibu-4": "2",
 "i-fol plus": "2",
 "ibu-6": "2",
 "ibu-8": "2",
 "iodine/potassium iodide": "2",
 "isolyte m and 5% dextrose": "2",
 "innovar": "2",
 "ibu": "2",
 "ionsys": "2",
 "i-sense occushield": "2"}, "h": {"hydeltrasol": "2",
 "hhr": "1",
 "haloperidol": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hemocyte plus": "2",
 "halotussin dac": "2",
 "hydroserpine 1": "1",
 "hyzaar": "2",
 "helidac": "2",
 "hydro-tussin exp": "2",
 "hydro-reserp": "1",
 "hydrocortisone": "2",
 "hydrochlorothiazide/methyldopa": "1",
 "hydralazine/hydrochlorothiazide": "1",
 "hydrochlorothiazide/timolol": "2",
 "hydromorphone": "2",
 "hydrocortone phosphate": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydropres-50": "1",
 "hydrap-es": "1",
 "hydroserpine": "1",
 "hydroflumethiazide/reserpine": "1",
 "hydrochlorothiazide/losartan": "2",
 "halflytely and bisacodyl": "2",
 "hydroflumethiazide": "1",
 "hydrodiuril": "1",
 "hygroton": "1",
 "hydrochlorothiazide/metoprolol": "2",
 "hyosophen": "2",
 "hydrostat ir": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "halotussin ac": "2",
 "haldol decanoate": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "1",
 "hydeltra-tba": "2",
 "hydrochlorothiazide/moexipril": "2",
 "hyophen": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "hi-nate 90": "2",
 "hydrochlorothiazide/propranolol": "2",
 "halothane": "2",
 "h.p. acthar gel": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "hydromorph contin": "2",
 "hematinic plus": "2",
 "halfprin": "2",
 "hydrochlorothiazide": "1",
 "hydro-tussin dhc": "2",
 "hydra-zide": "1",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrocortone": "2",
 "hydrochlorothiazide/reserpine": "1",
 "hair booster": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydropres-25": "1",
 "hexadrol": "2",
 "hydrocodone/ibuprofen": "2",
 "heartline": "2",
 "high potency": "2",
 "hyoscyamine/phenobarbital": "2",
 "hydro par": "1",
 "hydralazine plus": "1",
 "haltran": "2",
 "hemax": "2",
 "haldol": "2",
 "hydroserp": "1"}, "k": {"kadian": "2",
 "kaon-ci": "2",
 "k-phos original": "2",
 "k-pek": "2",
 "klor-con m10": "2",
 "klor-con m15": "2",
 "kaopectate": "2",
 "k-dur 10": "2",
 "k+care et": "2",
 "k + potassium": "2",
 "kato": "2",
 "kapectolin": "2",
 "kolnatal dha": "2",
 "kg-fed": "2",
 "kenalog-10": "2",
 "kaopectate anti-diarrheal upset stomach reliever": "2",
 "key-pred": "2",
 "klor-con": "2",
 "ketoconazole": "2",
 "kaon": "2",
 "kaon-cl 10": "2",
 "k-lyte/cl": "2",
 "k-phos m.f.": "2",
 "k-phos no. 2": "2",
 "k-lor": "2",
 "kal potassium 99": "2",
 "k-tab": "2",
 "k-lyte/cl 50": "2",
 "k-effervescent": "2",
 "k-sol": "2",
 "kerlone": "2",
 "klor-con/ef": "2",
 "kay ciel": "2",
 "kenaject-40": "2",
 "klotrix": "2",
 "k-8": "2",
 "klor-con/25": "2",
 "kaochlor s-f": "2",
 "k-lyte ds": "2",
 "k-lyte": "2",
 "kalcinate": "2",
 "k-dur": "2",
 "kaochlor": "2",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "ken-jec 40": "2",
 "k-dur 20": "2",
 "kao-tin bismuth subsalicylate formula": "2",
 "kg-fed pediatric expectorant": "2",
 "klor-con m20": "2",
 "klor-con 10": "2",
 "k-vescent": "2",
 "kcl": "2",
 "kg-fed expectorant": "2",
 "korlym": "2",
 "kie": "2",
 "ketorolac": "2",
 "kaletra": "2",
 "kneerelief": "2",
 "k-norm": "2",
 "ketek": "2",
 "k-10": "2",
 "kaon-cl 20%": "2",
 "kaopectate extra strength": "2",
 "klor-con 8": "2",
 "k-lyte/cl 25": "2",
 "ketoprofen": "2",
 "k-phos neutral": "2",
 "ketek pak": "2"}, "j": {"j-max dhc": "2",
 "j-cof dhc": "2",
 "juvisync": "3",
 "jumex": "2"}, "m": {"monopril hct": "2",
 "mynatal ultracap": "2",
 "maxivision eye formula": "2",
 "metubine iodide": "2",
 "m-end wc": "2",
 "morphine sulfate er": "2",
 "maxivision whole body formula": "2",
 "marthritic": "2",
 "maxifed cdx": "2",
 "multivitamin, prenatal": "2",
 "metipranolol ophthalmic": "2",
 "metahydrin": "1",
 "m-oxy": "2",
 "medrol dosepak": "2",
 "mynatal rx": "2",
 "micardis hct": "2",
 "magsal": "2",
 "magnebind 400 rx": "2",
 "mycelex troche": "2",
 "mhp-a": "2",
 "microzide": "1",
 "myphetane dc": "2",
 "maxinate": "2",
 "magnacet": "2",
 "methyclothiazide/reserpine": "1",
 "methacort 40": "2",
 "my-a-multi": "2",
 "mynate 90 plus": "2",
 "mylanta ultra": "2",
 "midamor": "2",
 "multi-betic": "2",
 "mylanta gelcap": "2",
 "medique pain-off": "2",
 "minizide": "1",
 "midol extended relief": "2",
 "m-phen": "2",
 "morphine lp epidural": "2",
 "mynatal z": "2",
 "moduretic": "2",
 "monocal": "2",
 "maalox children's relief": "2",
 "mephenytoin": "2",
 "mar-cof bp": "2",
 "methylcotolone": "2",
 "milnacipran": "2",
 "maalox advanced maximum strength chewable": "2",
 "motrin infant drops": "2",
 "multilex": "2",
 "monopril": "2",
 "m-clear": "2",
 "methacort 80": "2",
 "motrin childrens cold": "2",
 "medicort": "2",
 "matzim la": "2",
 "magan": "2",
 "mobic": "2",
 "myadec": "2",
 "midol maximum strength cramp formula": "2",
 "methylcotol": "2",
 "maternity": "2",
 "multaq": "2",
 "mifeprex": "2",
 "mynatal pn forte": "2",
 "mynatal plus": "2",
 "morphine rapi-ject": "2",
 "maalox max quick dissolve": "2",
 "motrin pm": "2",
 "metoprolol succinate er": "2",
 "methylprednisolone": "2",
 "minitabs": "2",
 "midol traditional": "2",
 "mission prenatal fa": "2",
 "ms/s": "2",
 "marplan": "2",
 "millipred": "2",
 "molindone": "2",
 "multi-nate 30 kit": "2",
 "motrin ib sinus": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "mefenamic acid": "2",
 "mi-acid double strength": "2",
 "metocurine": "2",
 "morphine/naltrexone": "2",
 "maternity vitamin low iron": "2",
 "micardis": "2",
 "millipred dp": "2",
 "maxifed-g cdx": "2",
 "medrol": "2",
 "mediplex ultra": "2",
 "maternity-90": "2",
 "mynatal fc": "2",
 "magonate tablets": "2",
 "mission prenatal": "2",
 "mag-phen": "2",
 "meperitab": "2",
 "multifol plus": "2",
 "mycobutin": "2",
 "mifepristone": "2",
 "methoxyflurane": "2",
 "mefloquine": "2",
 "midol ib": "2",
 "mykrox": "1",
 "marnatal-f": "2",
 "medent c": "2",
 "magnebind 200": "2",
 "methadose": "2",
 "mission prenatal rx": "2",
 "mepergan fortis": "2",
 "methyclothiazide": "1",
 "mono-gesic": "2",
 "maxivision eye &amp; body formula": "2",
 "motrin junior strength": "2",
 "methylpred dp": "2",
 "mission prenatal hp": "2",
 "magnesium salicylate": "2",
 "motrin ib": "2",
 "maalox junior relief chewable": "2",
 "mi-c-t": "2",
 "meperidine": "2",
 "mag-sr with calcium": "2",
 "morphine sulfate ir": "2",
 "multi-day with calcium and extra iron": "2",
 "multi-nate dha": "2",
 "maxifed cd": "2",
 "ms contin": "2",
 "mobigesic": "2",
 "maalox regular strength": "2",
 "medidex la": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "myvitalife": "2",
 "maxiflu cd": "2",
 "maraviroc": "2",
 "maxiphen cd": "2",
 "minitran": "2",
 "migralex": "2",
 "maxifed-g cd": "2",
 "mesantoin": "2",
 "maternal 90": "2",
 "mylanta supreme": "2",
 "motrin": "2",
 "mst": "2",
 "morphine": "2",
 "micrainin": "2",
 "meclofenamate": "2",
 "motrin sinus headache": "2",
 "mynatal": "2",
 "meloxicam": "2",
 "methadone diskets": "2",
 "multinatal plus": "2",
 "mepergan": "2",
 "miconazole": "2",
 "mytussin ac": "2",
 "maalox quick dissolve extra strength": "2",
 "meprozine": "2",
 "marblen": "2",
 "metolazone": "1",
 "matulane": "2",
 "maxivision ocular formula": "2",
 "mylanta child": "2",
 "morphitec": "2",
 "m-vit": "2",
 "m-clear wc": "2",
 "moduretic 5-50": "2",
 "maxzide-25": "2",
 "magnebind 300": "2",
 "maxiflu cdx": "2",
 "medi-seltzer": "2",
 "momentum": "2",
 "metoprolol": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "m-end pe": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "multilex-t/m+minerals": "2",
 "mudrane gg": "2",
 "mellaril-s": "2",
 "micro-k 10": "2",
 "methotrimeprazine": "2",
 "maxiphen cdx": "2",
 "menadol": "2",
 "medralone": "2",
 "multi-nate 30 dha": "2",
 "medipred": "2",
 "m-prednisolone": "2",
 "mivacurium": "2",
 "medralone 80": "2",
 "multi-day plus minerals": "2",
 "meperidine/promethazine": "2",
 "morphine sulfate sr": "2",
 "magna-c-7 forte": "2",
 "marnatal-f plus": "2",
 "maxzide": "2",
 "mobidin": "2",
 "mynatal pn": "2",
 "myogesic": "2",
 "msp-blu": "2",
 "meticorten": "2",
 "mivacron": "2",
 "multivitamin with minerals": "2",
 "m-eslon": "2",
 "mytussin dac": "2",
 "mavik": "2",
 "mibefradil": "2",
 "methdilazine": "2",
 "motrin migraine pain": "2",
 "maternity plus beta carotene": "2",
 "multi-nate dha extra": "2",
 "medique medi-seltzer": "2",
 "mens pack": "2",
 "maalox total relief": "2",
 "mudrane": "2",
 "modafinil": "1",
 "mellaril": "2",
 "metatensin 4": "1",
 "motrin childrens": "2",
 "metatensin 2": "1",
 "medidex": "2",
 "moban": "2",
 "materna": "2",
 "m o s": "2",
 "multi-nate 30": "2",
 "megavite rx": "2",
 "meclomen": "2",
 "methylprednisolone dose pack": "2",
 "moexipril": "2",
 "methadone": "2",
 "msir": "2",
 "motrin cold and flu": "2",
 "mesoridazine": "2",
 "maximum strength stress": "2",
 "marpres": "1",
 "micro-k": "2"}, "l": {"litecoat aspirin": "2",
 "lvp solution with potassium": "2",
 "luminal": "2",
 "lodine": "2",
 "lotrel": "2",
 "lufyllin-epg": "2",
 "lithotabs": "2",
 "loxitane c": "2",
 "low dose asa": "2",
 "lanreotide": "2",
 "lyrica": "2",
 "levacet": "2",
 "larodopa": "2",
 "lisinopril": "2",
 "levsin with phenobarbital": "2",
 "leader naproxen sodium": "2",
 "liquid pred": "2",
 "lysiplex plus": "2",
 "levobunolol ophthalmic": "2",
 "lortab asa": "2",
 "licorice": "2",
 "lozol": "1",
 "labetalol": "2",
 "lariam": "2",
 "lithium": "2",
 "luvox": "2",
 "levobetaxolol ophthalmic": "2",
 "levatol": "2",
 "lotensin": "2",
 "lithonate": "2",
 "loxitane": "2",
 "lasix": "2",
 "lotensin hct": "2",
 "lazanda": "2",
 "lopinavir/ritonavir": "2",
 "linezolid": "2",
 "loqua": "1",
 "largon": "2",
 "levitra": "2",
 "l-tonic": "2",
 "lugol's": "2",
 "lansoprazole/naproxen": "2",
 "losartan": "2",
 "loxitane im": "2",
 "lactocal-f": "2",
 "lurasidone": "2",
 "lodine xl": "2",
 "lopressor": "2",
 "lipitor": "2",
 "lapatinib": "2",
 "lacosamide": "2",
 "lo-aqua": "2",
 "lithobid": "2",
 "lexxel": "2",
 "levodopa": "2",
 "lopressor hct": "2",
 "laniroif": "2",
 "loxapine": "2",
 "leg-gesic": "2",
 "luvox cr": "2",
 "liquihistine cs": "2",
 "lexuss 210 liquid": "2",
 "lexiva": "2",
 "levoprome": "2",
 "latuda": "2"}, "o": {"orphengesic": "2",
 "ormazine": "2",
 "one-a-day within": "2",
 "o-cal-d": "2",
 "os-cal ultra": "2",
 "oxycodone": "2",
 "oyster shell calcium with vitamin d": "2",
 "ob natal one": "2",
 "oreticyl forte": "1",
 "os-cal 500": "2",
 "one-a-day vitacraves": "2",
 "oxaprozin": "2",
 "os-cal 500 + d": "2",
 "onsolis": "2",
 "oyster cal 500": "2",
 "oyster-d": "2",
 "oysco d": "2",
 "oyster shell calcium": "2",
 "obnate 90": "2",
 "oxcarbazepine": "2",
 "oxycet": "2",
 "oretic": "1",
 "obtrex": "2",
 "o-cal fa": "2",
 "orasone": "2",
 "orudis kt": "2",
 "orudis": "2",
 "ocuvite preservision": "2",
 "ocuvite": "2",
 "optipranolol": "2",
 "one-a-day max": "2",
 "oyster cal": "2",
 "oystercal-d": "2",
 "ocuvite extra": "2",
 "one-a-day men 50 plus": "2",
 "opium tincture, deodorized": "2",
 "oravig": "2",
 "oms": "2",
 "oyst cal": "2",
 "o-cal prenatal": "2",
 "oyster shell": "2",
 "opium": "2",
 "olmesartan": "2",
 "optivite pmt": "2",
 "optilets-m-500": "2",
 "ocuvite lutein": "2",
 "obegyn": "2",
 "ob complete with dha": "2",
 "ocupress": "2",
 "oreticyl 50": "1",
 "optinate": "2",
 "ob complete premier": "2",
 "oxecta": "2",
 "oxyir": "2",
 "obtrex dha": "2",
 "one-a-day weightsmart": "2",
 "occuplex": "2",
 "oxyfast": "2",
 "one-a-day women": "2",
 "oysco 500": "2",
 "oruvail": "2",
 "ostiva": "2",
 "orapred": "2",
 "oyst-cal-d": "2",
 "opium deodorized": "2",
 "orphengesic forte": "2",
 "opti-gen": "2",
 "os-cal": "2",
 "oysco 500 with d": "2",
 "oysco d with calcium": "2",
 "one daily with minerals": "2",
 "one tab daily with minerals": "2",
 "octreotide": "2",
 "oyst cal 500": "2",
 "oxydose": "2",
 "oyster shell calcium 500": "2",
 "ob-20": "2",
 "oxycontin": "2",
 "ob complete": "2",
 "oyster": "2",
 "os-cal 500 + extra d": "2",
 "one-a-day women 50 plus": "2",
 "oreticyl 25": "1",
 "oramorph sr": "2",
 "ob complete 400": "2",
 "osteocit d plus": "2",
 "oyster calcium": "2",
 "one-a-day men pro edge": "2",
 "orapred odt": "2",
 "olanzapine": "2"}, "n": {"nutrispire": "2",
 "nuedexta": "2",
 "natalcare advanced": "2",
 "naprosyn": "2",
 "nitroglycerin": "2",
 "narvox": "2",
 "natalcare pic forte": "2",
 "natelle prefer": "2",
 "nucodine": "2",
 "nebivolol": "2",
 "nexcede": "2",
 "novahistine expectorant": "2",
 "nu-iron v": "2",
 "natalcare": "2",
 "niferex-pn": "2",
 "nitrek": "2",
 "naprelan": "2",
 "nizoral": "2",
 "nicotinamide zcf": "2",
 "novahistine dh": "2",
 "neevo": "2",
 "nitro td patch-a": "2",
 "natelle-ez": "2",
 "nata 29 ob": "2",
 "nucodine pediatric": "2",
 "nuco-tuss pediatric expectorant": "2",
 "natacaps": "2",
 "novastart": "2",
 "neutra-phos": "2",
 "nanovm": "2",
 "niacin/simvastatin": "3",
 "nucofed expectorant": "2",
 "nitrodisc": "2",
 "natelle one": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "nitroglyn e-r": "2",
 "nata 29 prenatal": "2",
 "novasal": "2",
 "nestabs rx": "2",
 "neoprofen": "2",
 "natalcare glosstabs": "2",
 "naldecon-cx adult": "2",
 "nydrazid": "2",
 "nestabs fa": "2",
 "notuss-nxd": "2",
 "nuvigil": "1",
 "natelle": "2",
 "notuss-pe": "2",
 "nilotinib": "2",
 "norgesic forte": "2",
 "norvir": "2",
 "nitrocot": "2",
 "nitro-dur": "2",
 "normodyne": "2",
 "nalbuphine": "2",
 "neutra-phos-k": "2",
 "natafolic-ob": "2",
 "nexavar": "2",
 "nucofed pediatric expectorant": "2",
 "nestabs": "2",
 "nitrogard": "2",
 "natalcare rx": "2",
 "nelfinavir": "2",
 "notuss-ac": "2",
 "natelle one dha": "2",
 "nuromax": "2",
 "notuss-nx": "2",
 "naloxone/pentazocine": "2",
 "nitrong": "2",
 "norisodrine with calcium iodine": "2",
 "novadyne expectorant": "2",
 "nucochem": "2",
 "nubain": "2",
 "natatab fa": "2",
 "nitro-bid": "2",
 "nutiifac zx": "2",
 "naturetin": "1",
 "nalex ac": "2",
 "norvir soft gelatin": "2",
 "natarex": "2",
 "naqua": "1",
 "nalfon": "2",
 "nasotuss": "2",
 "nitrolingual pumpspray": "2",
 "novanatal": "2",
 "natatab rx": "2",
 "nuprin": "2",
 "nitro-bid iv": "2",
 "nucodine expectorant": "2",
 "neo ac": "2",
 "neoral": "3",
 "nuprin backache caplet": "2",
 "nephro calci": "2",
 "novadyne dh": "2",
 "navane": "2",
 "nuco-tuss expectorant": "2",
 "nitrostat tablets": "2",
 "new advanced formula prenatal z": "2",
 "nitroquick": "2",
 "noxafil": "2",
 "neevo dha": "2",
 "naproxen sodium ds": "2",
 "natelle c": "2",
 "natatab cfe": "2",
 "nadolol": "2",
 "naturetin-5": "1",
 "nimbex": "2",
 "niferex pn forte": "2",
 "norcuron": "2",
 "natalcare advanced-rf": "2",
 "nic 750": "2",
 "naturetin-10": "1",
 "natalcare plus": "2",
 "natalins rx": "2",
 "neo-forte": "2",
 "nitrostat": "2",
 "naproxen/sumatriptan": "2",
 "norwich aspirin": "2",
 "nitro-time": "2",
 "notuss-dc": "2",
 "natachew": "2",
 "natelle plus with dha": "2",
 "natafolic-pn": "2",
 "nitrol": "2",
 "norgesic": "2",
 "nature's blend theratrum complete tablets 50 plus": "2",
 "nardil": "2",
 "natalfirst": "2",
 "novagest with codeine": "2",
 "naproxen": "2",
 "nutrinate": "2",
 "nitro-par": "2",
 "nicomide": "2",
 "nabumetone": "2",
 "nexterone": "2",
 "nexa select with dha": "2",
 "nestabs cbf": "2",
 "nucofed": "2",
 "neo-calglucon": "2",
 "nitrol appli-kit": "2",
 "nitromist": "2",
 "normosol-m and 5% dextrose": "2",
 "norlac rx": "2",
 "nutravance": "2",
 "natalcare pic": "2",
 "natalcare cfe 60": "2",
 "natalcare three": "2",
 "nefazodone": "2",
 "naproxen/pseudoephedrine": "2",
 "natafort": "2",
 "natalins": "2",
 "nicazel": "2"}, "q": {"quick-k": "2",
 "quin-release": "2",
 "quelicin": "2",
 "quinaretic": "2",
 "quinidex extentabs": "2",
 "quelicin chloride": "2",
 "quinora": "2",
 "quinidine": "2",
 "quinapril": "2",
 "quinaglute dura-tabs": "2",
 "quin-g": "2",
 "quazepam": "2",
 "quetiapine": "2",
 "q-profen": "2",
 "quadrinal": "2",
 "quadrapax": "2"}, "p": {"pyridium plus": "2",
 "phosphasal": "2",
 "pr natal 440": "2",
 "prostate 2.4": "2",
 "paire ob plus dha": "2",
 "poly-tussin ac": "2",
 "poly-histine cs": "2",
 "pamprin all day relief": "2",
 "parenteral nutrition solution w/electrolytes": "2",
 "predacort 50": "2",
 "prenatal low iron": "2",
 "potassium bicarbonate/potassium chloride": "2",
 "pan ob forte": "2",
 "pentazocine": "2",
 "primacare": "2",
 "prevacid naprapac": "2",
 "prevacid naprapac 375": "2",
 "pyrelle hb": "2",
 "potassium phosphate/sodium phosphate": "2",
 "pink bismuth": "2",
 "pedituss": "2",
 "potassium iodide": "2",
 "prinzide": "2",
 "pindolol": "2",
 "phenhist expectorant": "2",
 "pce dispertab": "2",
 "pulmicort nebuamp": "2",
 "pr natal 400 ec": "2",
 "predcor": "2",
 "prenazyme 1+1": "2",
 "potassium citrate": "2",
 "prenatabs cbf": "2",
 "potassium chloride": "2",
 "prednisolone": "2",
 "phenylhistine expectorant": "2",
 "phenaphen with codeine": "2",
 "predicort-50": "2",
 "posture-d h/p": "2",
 "prenafirst": "2",
 "prednicot": "2",
 "pepto children's": "2",
 "prolixin": "2",
 "promethazine with dm": "2",
 "prenatal-u": "2",
 "prevacid naprapac 500": "2",
 "propoxyphene compound 65": "2",
 "prefera ob-one": "2",
 "phospha 250 neutral": "2",
 "pancuronium": "2",
 "posture": "2",
 "pnv-total": "2",
 "phenadoz": "2",
 "phenergan vc": "2",
 "polythiazide/prazosin": "1",
 "potassium acetate": "2",
 "prelone": "2",
 "procarbazine": "2",
 "prenatabs fa": "2",
 "prenaplus": "2",
 "pamprin cramp menstrual pain relief": "2",
 "prochlorperazine": "2",
 "potassium phosphate": "2",
 "pima": "2",
 "pediazole": "2",
 "pnv-dha plus": "2",
 "phenylephrine/promethazine": "2",
 "predate-50": "2",
 "promethazine with codeine": "2",
 "pseudodine c": "2",
 "polycitra": "2",
 "primacare advantage": "2",
 "prelief": "2",
 "phenazine 50": "2",
 "prednicen-m": "2",
 "permitil": "2",
 "prenate dha": "2",
 "prenate 90": "2",
 "prolixin enanthate": "2",
 "parnate": "2",
 "pms balance": "2",
 "percodan": "2",
 "previte rx": "2",
 "phoslo gelcap": "2",
 "pediacof": "2",
 "paliperidone": "2",
 "pb-hyos": "2",
 "prosteon": "2",
 "phrenilin with caffeine and codeine": "2",
 "prenatabs obn": "2",
 "primacare one": "2",
 "predicort rp": "2",
 "prenatal mr 90": "2",
 "prenavite fc": "2",
 "poly hist dhc": "2",
 "polytine cs": "2",
 "percocet 10/325": "2",
 "poly tussin ex": "2",
 "pc-10": "2",
 "pepto-bismol": "2",
 "prenatal rx": "2",
 "prenatal 1 plus 1": "2",
 "percocet 2.5/325": "2",
 "prenate essential": "2",
 "percodan-demi": "2",
 "promethazine vc with codeine": "2",
 "poly cs": "2",
 "potassium bicarbonate/potassium citrate": "2",
 "polycitra-k": "2",
 "prolixin decanoate": "2",
 "premesis rx": "2",
 "posicor": "2",
 "potassium bicarbonate/sodium bicarbonate": "2",
 "par-f": "2",
 "pipecuronium": "2",
 "pc-cap": "2",
 "preterna": "2",
 "primlev": "2",
 "prefera ob plus dha": "2",
 "prenatal multivitamins": "2",
 "pnv select": "2",
 "pepcid complete": "2",
 "prenate gt": "2",
 "pancof": "2",
 "precare conceive": "2",
 "penbutolol": "2",
 "prenate ultra": "2",
 "phenytoin sodium, prompt": "2",
 "penthrane": "2",
 "propiomazine": "2",
 "prenate essential dha": "2",
 "pruet dha": "2",
 "percolone": "2",
 "phenaz plus": "2",
 "phenelzine": "2",
 "posaconazole": "2",
 "prenatal rx 1": "2",
 "protegra softgel": "2",
 "pacerone": "2",
 "p-a-c analgesic": "2",
 "phoslyra": "2",
 "prenate elite plus iron": "2",
 "pro-med": "2",
 "potassium iodide/theophylline": "2",
 "prenexa": "2",
 "prosight": "2",
 "poly-tussin ex syrup": "2",
 "priftin": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "preferaob": "2",
 "promethazine vc": "2",
 "peganone": "2",
 "prenate elite": "2",
 "pancof-pd": "2",
 "phenylhistine dh expectorant": "2",
 "prenatal z advanced formula": "2",
 "parcopa": "2",
 "potassium bicarbonate": "2",
 "prosed ds": "2",
 "pr natal 400": "2",
 "pepto-bismol maximum strength": "2",
 "potassium chloride/sodium chloride": "2",
 "percocet 5/325": "2",
 "propranolol": "2",
 "pristiq": "2",
 "phenflu cdx": "2",
 "prezista": "2",
 "phosenamine": "2",
 "prinivil": "2",
 "prenatal s": "2",
 "percocet 10/650": "2",
 "p-a-c": "2",
 "provigil": "1",
 "procycle multi vitamin with minerals": "2",
 "pp-cap": "2",
 "predaject-50": "2",
 "peptic relief": "2",
 "phenazoforte plus": "2",
 "pulmicort turbuhaler": "2",
 "ponstel": "2",
 "piroxicam": "2",
 "prenatal h": "2",
 "pediapred": "2",
 "predacorten": "2",
 "phenytoin": "2",
 "primethasone": "2",
 "paregoric": "2",
 "perindopril": "2",
 "prenate advance": "2",
 "pancof exp": "2",
 "percocet 7.5/325": "2",
 "phenobarbital": "2",
 "promazine": "2",
 "prenatabs rx": "2",
 "prenate advanced formula": "2",
 "pregabalin": "2",
 "predalone 50": "2",
 "potassium acid phosphate": "2",
 "prenavite": "2",
 "procot": "2",
 "potassium chloride in sodium chloride": "2",
 "percocet": "2",
 "prenatal mtr with selenium": "2",
 "potassium acetate/potassium bicarbonate/potassium citrate": "2",
 "pavulon": "2",
 "phenergan": "2",
 "panasal 5/500": "2",
 "prenatal plus with 27 mg iron": "2",
 "phenoject-50": "2",
 "propoxyphene": "2",
 "prenatal plus": "2",
 "promethazine dm": "2",
 "prenacare": "2",
 "prenatal mr 90 fe": "2",
 "prenatal elite": "2",
 "preque 10": "2",
 "palladone": "2",
 "polycitra-lc": "2",
 "pre-h-cal": "2",
 "phenergan fortis": "2",
 "prenexa with dha": "2",
 "phos-nak": "2",
 "prenate plus": "2",
 "panlor dc": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "polythiazide": "1",
 "precare": "2",
 "phenytek": "2",
 "prenatal plus with beta-carotene": "2",
 "prosed ec": "2",
 "pro-clear": "2",
 "potassium citrate/sodium citrate": "2",
 "perloxx": "2",
 "panlor ss": "2",
 "precare premier": "2",
 "prenavite pc": "2",
 "poly-tussin dhc": "2",
 "promethazine with dextromethorphan": "2",
 "potassium gluconate": "2",
 "pred-ject-50": "2",
 "proleukin": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenflu cd": "2",
 "painaid": "2",
 "pro-red ac": "2",
 "phenylhistine dh": "2",
 "procalamine": "2",
 "prednisone": "2",
 "plasma-lyte 56": "2",
 "promethazine hcl with codeine": "2",
 "phoslo": "2",
 "pr natal 430": "2",
 "polythiazide/reserpine": "1",
 "pulmicort flexhaler": "2",
 "pnv-dha": "2",
 "promethazine vc w/codeine": "2",
 "preservision": "2",
 "percocet 7.5/500": "2",
 "pramilet fa": "2",
 "promethazine vc plain": "2",
 "primalev": "2",
 "prenatal plus iron": "2",
 "pri-cortin 50": "2",
 "pamprin max menstrual pain relief": "2",
 "pravigard pac": "2",
 "probarimin qt": "2",
 "phenergan with dextromethorphan": "2",
 "plasma-lyte and 5% dextrose": "2",
 "prevpac": "2",
 "perphenazine": "2",
 "prenatal 19": "2",
 "pulmicort respules": "2",
 "promethegan": "2",
 "poly-citra k crystals": "2",
 "polyhist nc": "2",
 "prenatal ad": "2"}, "s": {"sulindac": "2",
 "saleto": "2",
 "saluron": "1",
 "surbex-750 with zinc": "2",
 "solurex": "2",
 "saquinavir": "2",
 "se-care conceive": "2",
 "sourcecf abdek": "2",
 "senetonic": "2",
 "surpass": "2",
 "stomach relief": "2",
 "sourcecf chewables": "2",
 "selgene": "2",
 "slow-k": "2",
 "saleto-800": "2",
 "subutex": "2",
 "stuart prenatal with beta carotene": "2",
 "selegiline": "2",
 "serathide": "1",
 "sufentanil": "2",
 "sinemet cr": "2",
 "strong iodine": "2",
 "sporanox pulsepak": "3",
 "st. joseph aspirin": "2",
 "synalgos-dc": "2",
 "sss": "2",
 "sski": "2",
 "subsys": "2",
 "stelazine": "2",
 "scot-tussin original": "2",
 "serentil": "2",
 "stress maximum strength": "2",
 "sotalol hydrochloride af": "2",
 "sinemet": "2",
 "selestoject": "2",
 "sojourn": "2",
 "stalevo 150": "2",
 "supac": "2",
 "stuartnatal plus 3": "2",
 "saleto-400": "2",
 "savella": "2",
 "strovite advance": "2",
 "sudafed 12 hour pressure+pain": "2",
 "synercid": "2",
 "sandimmune": "3",
 "suttar-2": "2",
 "salutensin-demi": "1",
 "super calcium": "2",
 "sevoflurane": "2",
 "solu-cortef": "2",
 "st. joseph 81 mg chewable aspirin": "2",
 "salsalate": "2",
 "serzone": "2",
 "suttar sf": "2",
 "statuss": "2",
 "stress formula with zinc": "2",
 "suprane": "2",
 "sandostatin": "2",
 "salutensin": "1",
 "seconal sodium": "2",
 "se-natal 16": "2",
 "sublimaze": "2",
 "stalevo 75": "2",
 "saleto-600": "2",
 "stresstabs with zinc": "2",
 "ser-ap-es": "1",
 "se-care": "2",
 "sourcecf multivitamins with a,b,d,e &amp; k plus zinc": "2",
 "simcor": "3",
 "se-natal 19": "2",
 "select-ob+dha": "2",
 "stress 600 with zinc": "2",
 "sustiva": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "symbicort": "2",
 "staxyn": "2",
 "st. john's wort": "1",
 "stalevo 200": "2",
 "spectravite cardio health": "2",
 "se-tan dha": "2",
 "selzentry": "2",
 "surpass extra strength": "2",
 "stanback fast pain relief": "2",
 "saleto-200": "2",
 "strovite": "2",
 "spectravite senior": "2",
 "sparine": "2",
 "sourcecf pediatric drops": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "strovite plus": "2",
 "stuartnatal plus": "2",
 "sedecal d": "2",
 "sulfimycin": "2",
 "support": "2",
 "spastrin": "2",
 "se-natal 90": "2",
 "soma compound with codeine": "2",
 "st. joseph 81 mg aspirin enteric safety-coated": "2",
 "sloprin": "2",
 "sourcecf softgels": "2",
 "stalevo 100": "2",
 "solurex la": "2",
 "sodium salicylate": "2",
 "soma compound": "2",
 "simvastatin/sitagliptin": "3",
 "somatuline depot": "2",
 "stanback analgesic": "2",
 "strongstart": "2",
 "seton et": "2",
 "select-ob": "2",
 "sildenafil": "2",
 "spironolactone": "2",
 "se-plete dha": "2",
 "sporanox": "3",
 "serpex": "1",
 "seton et-ec": "2",
 "strovite advance+d": "2",
 "sterapred": "2",
 "super theravite-m": "2",
 "super high vitamins and minerals": "2",
 "sprix": "2",
 "salflex": "2",
 "siderol": "2",
 "solu-medrol": "2",
 "stadol": "2",
 "sine-aid ib": "2",
 "support 500": "2",
 "sprycel": "2",
 "seconal": "2",
 "statex": "2",
 "saphris": "2",
 "spasmolin": "2",
 "sirolimus": "2",
 "serpazide": "1",
 "suboxone": "2",
 "symbyax": "2",
 "spasquid": "2",
 "se-natal one": "2",
 "simvastatin": "3",
 "stalevo 50": "2",
 "salsitab": "2",
 "stalevo 125": "2",
 "sandostatin lar depot": "2",
 "sesame st vitamins complete": "2",
 "sodium thiosalicylate": "2",
 "stalevo": "2",
 "sotalol": "2",
 "sorine": "2",
 "succinylcholine": "2",
 "servira": "2",
 "strovite one": "2",
 "sterapred ds": "2",
 "strovite forte": "2",
 "sufenta": "2",
 "sectral": "2",
 "sorafenib": "2",
 "seconal sodium pulvules": "2"}, "r": {"risperdal m-tab": "2",
 "robitussin-ac": "2",
 "rum-k": "2",
 "re dualvit f": "2",
 "robitussin-dac": "2",
 "rightstep": "2",
 "resource optisource": "2",
 "regroton": "1",
 "re dualvit plus": "2",
 "renaplex": "2",
 "rolaids extra strength softchews": "2",
 "renatabs with iron": "2",
 "rapacuronium": "2",
 "rolaids extra strength plus gas relief softchews": "2",
 "recal d": "2",
 "rifampin": "2",
 "rolaids regular strength": "2",
 "risacal-d": "2",
 "roxicet": "2",
 "rivastigmine": "2",
 "razadyne": "2",
 "rescriptor": "2",
 "req49+": "2",
 "renax 5.5": "2",
 "rms": "2",
 "roxicodone": "2",
 "rolatuss": "2",
 "ryna-cx": "2",
 "ramipril": "2",
 "raxar": "2",
 "rauzide": "1",
 "roxanol-t": "2",
 "raplon": "2",
 "rifater": "2",
 "robimycin": "2",
 "renese-r": "1",
 "rufen": "2",
 "renate dha extra": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "rovin-nv dha": "2",
 "ridactate": "2",
 "rifadin iv": "2",
 "recal fol d": "2",
 "rifadin": "2",
 "rapamune": "2",
 "relafen": "2",
 "re-pb hyos elixir": "2",
 "roxicodone intensol": "2",
 "robaxisal": "2",
 "rocuronium": "2",
 "re fac-x": "2",
 "revatio": "2",
 "razadyne er": "2",
 "rx support heartburn and acid reflux": "2",
 "rifabutin": "2",
 "re ob 90 plus dha": "2",
 "rondameth": "1",
 "rescudose": "2",
 "risanoid plus": "2",
 "risperdal consta": "2",
 "ritonavir": "2",
 "robichem ac": "2",
 "roxanol 100": "2",
 "roxiprin": "2",
 "remodulin": "2",
 "relcof c": "2",
 "rolaids extra strength": "2",
 "reserpine/trichlormethiazide": "1",
 "rectiv": "2",
 "robafen ac": "2",
 "renate": "2",
 "re ob plus dha": "2",
 "rimactane": "2",
 "romilar ac": "2",
 "ru-lets m 500": "2",
 "renax": "2",
 "ropivacaine/sufentanil": "2",
 "rexolate": "2",
 "reprexain": "2",
 "risperidone": "2",
 "rhinocaps": "2",
 "roxilox": "2",
 "reminyl": "2",
 "rolaids multi-symptom": "2",
 "renate dha": "2",
 "rasagiline": "2",
 "ryna-c": "2",
 "reocyte plus": "2",
 "risperdal": "2",
 "rovin-nv": "2",
 "reyataz": "2",
 "renese": "1",
 "roxanol": "2",
 "rezulin": "2"}, "u": {"uretron": "2",
 "uro-kp-neutral": "2",
 "urimax": "2",
 "ursinus": "2",
 "urocit-k": "2",
 "utrona-c": "2",
 "udamin": "2",
 "utrona": "2",
 "ultra mylanta calci tabs": "2",
 "upcal d": "2",
 "unicap senior": "2",
 "urised": "2",
 "uritact ds": "2",
 "urimar-t": "2",
 "urelief plus": "2",
 "ultra-natal": "2",
 "uretron ds": "2",
 "utira": "2",
 "unicomplex m": "2",
 "univasc": "2",
 "uni-fac zx": "2",
 "urapine": "2",
 "ultimatecare one": "2",
 "u-tri-lone": "2",
 "utira-c": "2",
 "ultane": "2",
 "udamin sp": "2",
 "uni serp": "1",
 "uritin": "2",
 "uni-cof": "2",
 "uta": "2",
 "usept": "2",
 "uni-cof expectorant": "2",
 "urisym": "2",
 "ultimatecare combo": "2",
 "unipres": "1",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "ultimatecare one nf": "2",
 "unicap t": "2",
 "uni-thera m with beta carotene": "2",
 "ustell": "2",
 "ultra natalcare": "2",
 "urelle": "2",
 "unicap m": "2",
 "ultimatecare advance": "2",
 "uprima": "2",
 "uribel": "2",
 "ultane pen": "2",
 "uniretic": "2"}, "t": {"toprol-xl": "2",
 "telmisartan": "2",
 "triamterene": "2",
 "tizanidine": "3",
 "tyvaso": "2",
 "treprostinil": "2",
 "troleandomycin": "2",
 "tolectin 600": "2",
 "thermotabs": "2",
 "titralac plus liquid": "2",
 "thiothixene": "2",
 "talwin nx": "2",
 "travert 10% and electrolyte no2": "2",
 "tylenol with codeine #2": "2",
 "theracal d4000": "2",
 "timolol ophthalmic": "2",
 "tri-k": "2",
 "tozal": "2",
 "tocilizumab": "2",
 "tricare dha one": "2",
 "titralac plus": "2",
 "triveen-one": "2",
 "timoptic": "2",
 "tubocurarine": "2",
 "tridil": "2",
 "tums kids": "2",
 "thiethylperazine": "2",
 "t- koff": "2",
 "tetra-mag": "2",
 "tussirex sugar free": "2",
 "teveten hct": "2",
 "tenormin": "2",
 "thera-m enhanced": "2",
 "temaril": "2",
 "trileptal": "2",
 "tacrine": "2",
 "trilisate": "2",
 "talacen": "2",
 "tegretol": "2",
 "trihist-cs": "2",
 "tolectin ds": "2",
 "theralith xr": "2",
 "theophylline ki": "2",
 "theravim m": "2",
 "therobec plus": "2",
 "tums ultra 1000": "2",
 "tums regular strength": "2",
 "tylenol with codeine": "2",
 "trandolapril/verapamil": "2",
 "tridal": "2",
 "tetrabenazine": "2",
 "t-lite": "2",
 "tussi-organidin nr": "2",
 "tenoretic": "2",
 "trilog": "2",
 "toradol": "2",
 "taron-prx plus dha": "2",
 "telzir": "2",
 "trinatal rx": "2",
 "tolectin": "2",
 "thioridazine": "2",
 "trifluoperazine": "2",
 "teveten": "2",
 "tums dual action": "2",
 "twynsta": "2",
 "trichlormethiazide": "1",
 "tab-a-vite maximum": "2",
 "tenoretic 50": "2",
 "thalitone": "1",
 "thera-m": "2",
 "talwin": "2",
 "tussar sf": "2",
 "tandem ob": "2",
 "toradol iv/im": "2",
 "travasol with electrolytes dual chamber": "2",
 "tussirex": "2",
 "trandate": "2",
 "tiazac": "2",
 "tussiden c": "2",
 "tykerb": "2",
 "theodrine": "2",
 "torecan": "2",
 "travert 5% and electrolyte no2": "2",
 "tricare": "2",
 "timolide": "2",
 "twin-k": "2",
 "telithromycin": "2",
 "torisel": "2",
 "timoptic-xe": "2",
 "tranylcypromine": "2",
 "trandolapril": "2",
 "t-gran plus minerals": "2",
 "tricof": "2",
 "telaprevir": "2",
 "timoptic ocudose": "2",
 "thorazine": "2",
 "therapy bayer": "2",
 "tricitrates": "2",
 "tasigna": "2",
 "timolol": "2",
 "tusal": "2",
 "theracal rapid repletion": "2",
 "trycet": "2",
 "tl g-fol os": "2",
 "tristoject": "2",
 "tl-hist cm": "2",
 "tums freshers": "2",
 "ternamar": "2",
 "tramacort-d": "2",
 "tl-hist cd": "2",
 "triacin c": "2",
 "theracal d2000": "2",
 "titralac": "2",
 "tenoretic 100": "2",
 "thera-vite m": "2",
 "triflupromazine": "2",
 "transderm-nitro": "2",
 "triavil": "2",
 "ten-k": "2",
 "tekturna hct": "1",
 "tums smoothies": "2",
 "tac 3": "2",
 "tagamet": "2",
 "trimeprazine": "2",
 "tuinal": "2",
 "trac tabs 2x": "2",
 "triadvance": "2",
 "timolide 10-25": "2",
 "tedrigen": "2",
 "tylenol with codeine #3": "2",
 "tylenol with codeine #4": "2",
 "ticagrelor": "1",
 "tandem dha": "2",
 "triam-forte": "2",
 "tums plus": "2",
 "tricosal": "2",
 "tab-a-vite weightslim": "2",
 "triamcot": "2",
 "triam-a": "2",
 "therems m": "2",
 "tegretol xr": "2",
 "terrell": "2",
 "travasol with electrolytes": "2",
 "triamonide 40": "2",
 "taron-c dha": "2",
 "triafed &amp; codeine": "2",
 "tri rx": "2",
 "tarka": "2",
 "taron-bc": "2",
 "theragran-m": "2",
 "trifed c": "2",
 "trezix": "2",
 "tadalafil": "1",
 "tri-hydroserpine": "1",
 "triamcinolone": "2",
 "theragener-m": "2",
 "tandem plus": "2",
 "thera hematinic": "2",
 "theragener-h": "2",
 "trilafon": "2",
 "tab-a-vite womens formula": "2",
 "tussar-2": "2",
 "tolmetin": "2",
 "tylox": "2",
 "trilone": "2",
 "taztia xt": "2",
 "tracleer": "2",
 "tribenzor": "2",
 "toradol im": "2",
 "troglitazone": "2",
 "tums extra strength 750": "2",
 "tri-buffered aspirin": "2",
 "trinate": "2",
 "taron-ec calc dha pack": "2",
 "triveen-prx rnf": "2",
 "trimesis rx": "2",
 "thyroshield": "2",
 "teczem": "2",
 "tagamet hb": "2",
 "treximet": "2",
 "tusso-c": "2",
 "tacaryl": "2",
 "tusscough dhc": "2",
 "talwin compound": "2",
 "therapeutic-m": "2",
 "tracrium": "2",
 "tao": "2",
 "tussi-organidin-s nr": "2",
 "temsirolimus": "2"}, "w": {"wellbutrin xl": "2",
 "welltuss exp": "2",
 "womens pack": "2",
 "wygesic": "2",
 "wellesse liquid calcium with vitamin d": "2",
 "wellbutrin sr": "2",
 "wellbutrin": "2"}, "v": {"vitalize plus": "2",
 "vinate advanced": "2",
 "verotin-by": "2",
 "viactiv multi-vitamin": "2",
 "vi-zac": "2",
 "vigortol liquid": "2",
 "vanspar": "2",
 "v-gan-50": "2",
 "venatal fa": "2",
 "viagra": "2",
 "vardenafil": "2",
 "viactiv calcium flavor glides": "2",
 "vica-forte": "2",
 "vinate care": "2",
 "victrelis": "2",
 "vinate good start": "2",
 "vimpat": "2",
 "vitanatal ob plus dha": "2",
 "vaseretic": "2",
 "vinate az extra": "2",
 "valturna": "2",
 "vinate ic": "2",
 "vanacof cd": "2",
 "vytorin": "3",
 "vinate ii": "2",
 "verteporfin": "1",
 "valsartan": "2",
 "vitaspire": "2",
 "vinate ultra": "2",
 "vinate 90": "2",
 "vitafol-ob+dha": "2",
 "verelan pm": "2",
 "vasotec": "2",
 "vitaphil": "2",
 "vitelle nestabs otc": "2",
 "viracept": "2",
 "vynatal fa": "2",
 "vol-nate": "2",
 "vitatab mv": "2",
 "voltaren-xr": "2",
 "vicon forte": "2",
 "voriconazole": "2",
 "venlafaxine": "2",
 "vaseretic 5-12.5": "2",
 "vitamax": "2",
 "vaseretic 10-25": "2",
 "vinatal forte": "2",
 "vanquish": "2",
 "vinate iii": "2",
 "visken": "2",
 "vital-d": "2",
 "vaprisol": "2",
 "vitaphil plus dha": "2",
 "vemavite prx 2": "2",
 "vimovo": "2",
 "vitamed prenatal formula": "2",
 "vol-plus": "2",
 "verelan": "2",
 "vitaphil aide": "2",
 "vitafol pn": "2",
 "vita-zinc": "2",
 "vecuronium": "2",
 "vicoprofen": "2",
 "vita zx": "2",
 "vinacal or": "2",
 "viactiv soft calcium chews": "2",
 "veripred 20": "2",
 "vernate": "2",
 "visudyne": "1",
 "v-gan-25": "2",
 "vita-dec": "2",
 "vicon plus": "2",
 "vinate pn care": "2",
 "voltaren": "2",
 "vitatrum": "2",
 "vernate advanced": "2",
 "vicap forte": "2",
 "vinate one": "2",
 "vitafol-ob": "2",
 "viva dha": "2",
 "vicon-c": "2",
 "vol-tab rx": "2",
 "vita-min rx": "2",
 "vfend": "2",
 "vynatal 1 plus 1": "2",
 "vinate az": "2",
 "v-c forte": "2",
 "vita s forte": "2",
 "vinate c": "2",
 "vitacon forte": "2",
 "vinate m": "2",
 "vitafol": "2",
 "vinate calcium": "2",
 "vitaplex plus": "2",
 "verapamil": "2",
 "vopac": "2",
 "viactiv multi-vitamin flavor glides": "2",
 "vinate gt": "2",
 "viogen-c": "2",
 "veletri": "2",
 "verotin-gr": "2",
 "vinatal 600": "2",
 "vis-phos n": "2",
 "ventavis": "2"}, "y": {"ysp aspirin": "2",
 "yodefan": "2"}, "x": {"xalkori": "2",
 "xenazine": "2",
 "xolox": "2"}, "z": {"zinc plus lozenges": "2",
 "zorprin": "2",
 "z-tuss ac": "2",
 "zatean-pn dha": "2",
 "zenate prenatal": "2",
 "zitamin": "2",
 "zenate": "2",
 "zatean-pn": "2",
 "zileuton": "1",
 "zocor": "3",
 "zyvox": "2",
 "zema pak": "2",
 "zyflo": "1",
 "z-gen": "2",
 "zenate advanced formula": "2",
 "zemuron": "2",
 "zero-order release": "2",
 "zebeta": "2",
 "zatean-pn plus": "2",
 "ziprasidone": "2",
 "ze-plus": "2",
 "zyprexa intramuscular": "2",
 "zodryl dec": "2",
 "zestoretic": "2",
 "zerlor": "2",
 "zipsor": "2",
 "zodryl dac": "2",
 "zincvit": "2",
 "z-bec": "2",
 "zafirlukast": "2",
 "zortress": "2",
 "zyflo cr": "1",
 "zyban": "2",
 "zaponex": "2",
 "zelapar": "2",
 "zanaflex": "3",
 "zodryl ac": "2",
 "zatean-ch": "2",
 "zyprexa": "2",
 "zotex-c": "2",
 "zyprexa zydis": "2",
 "zestril": "2",
 "zaroxolyn": "1",
 "zyprexa relprevv": "2",
 "ziac": "2",
 "zodeac-100": "2"}}];