interactions["altretamine,hexalen"]=["altretamine,hexalen", {"a": {"avelox": "2",
 "azathioprine": "2",
 "acetaminophen/butalbital": "2",
 "amoxapine": "3",
 "aminophylline/amobarbital/ephedrine": "2",
 "atropine/phenobarbital": "2",
 "acthib with dpt (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "amobarbital/secobarbital": "2",
 "aqua gem-e": "2",
 "aqua-e": "2",
 "alagesic lq": "2",
 "arava": "3",
 "antispas": "2",
 "antispasmodic": "2",
 "asthmacon": "2",
 "adapin": "3",
 "acam2000": "3",
 "amitriptyline/chlordiazepoxide": "3",
 "acthib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "amytal sodium": "2",
 "afluria": "2",
 "amitriptyline": "3",
 "axocet": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "arcalyst": "2",
 "avelox i.v.": "2",
 "aventyl hydrochloride": "3",
 "azithromycin/trovafloxacin": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "alefacept": "2",
 "aminoxin": "2",
 "anoquan": "2",
 "anafranil": "3",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "aspirin/butalbital/caffeine": "2",
 "aplitest": "2",
 "alagesic": "2",
 "antrocol": "2",
 "aspirin/butalbital": "2",
 "adalimumab": "3",
 "alkabel-sr": "2",
 "arcet": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "azasan": "2",
 "amobarbital": "2",
 "amitriptyline/perphenazine": "3",
 "acetaminophen/butalbital/caffeine": "2",
 "aquasol e": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "aplisol": "2",
 "agriflu": "2",
 "adacel": "2",
 "attenuvax": "3",
 "anthrax vaccine adsorbed": "2",
 "asendin": "3",
 "alemtuzumab": "2",
 "americet": "2",
 "aquavite-e": "2",
 "anakinra": "2",
 "amevive": "2",
 "amino-opti-e": "2",
 "anolor 300": "2",
 "acetaminophen/pamabrom/pyridoxine": "2",
 "alpha e": "2"}, "c": {"cervarix": "2",
 "cephadyn": "2",
 "canakinumab": "2",
 "cipro": "2",
 "cimetidine": "2",
 "ciprofloxacin": "2",
 "cipro i.v.": "2",
 "comvax (haemophilus b conjugate (prp-omp) vaccine/hepatitis b pediatric vaccine)": "2",
 "clomipramine": "3",
 "cinobac": "2",
 "cholera vaccine": "2",
 "cladribine novaplus": "2",
 "cladribine": "2",
 "clopine": "3",
 "coccidioidin skin test": "2",
 "cyanocobalamin/folic acid/pyridoxine/strontium gluconate": "2",
 "chardonna-2": "2",
 "clozaril": "3",
 "candin": "2",
 "cipro xr": "2",
 "capacet": "2",
 "clozapine synthon": "3",
 "cinoxacin": "2",
 "candida albicans extract": "2",
 "candida skin test": "2",
 "clozapine": "3",
 "cafatine pb": "2",
 "centrum singles-vitamin e": "2",
 "cipro cystitis pack": "2",
 "certolizumab": "3",
 "cytovene": "2",
 "cimzia": "3",
 "campath": "2"}, "b": {"bellaphen-s": "2",
 "bcg": "3",
 "busodium": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "butisol sodium": "2",
 "bellatal er": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "bupap": "2",
 "belcomp-pb": "2",
 "bonisara": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "butalbital compound": "2",
 "butex forte": "2",
 "butalbital": "2",
 "bellamor": "2",
 "bellaspas": "2",
 "boostrix": "2",
 "bel-phen-ergot": "2",
 "biothrax": "2",
 "butibel": "2",
 "butabarbital": "2",
 "barbidonna": "2",
 "biavax ii": "3",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine": "2",
 "bellatal": "2",
 "belladonna/butabarbital": "2",
 "bel-tabs": "2",
 "bucet": "2",
 "bellamine s": "2"}, "e": {"endep": "3",
 "e-gems": "2",
 "enoxacin": "2",
 "elixiral": "2",
 "e-600": "2",
 "etrafon": "3",
 "esgic-plus": "2",
 "e-400 clear": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "eperbel-s": "2",
 "engerix-b": "2",
 "etanercept": "3",
 "efalizumab": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ergocaffpb": "2",
 "ezol": "2",
 "ergocomp-pb": "2",
 "etrafon forte": "3",
 "elavil": "3",
 "e pherol": "2",
 "enbrel": "3",
 "e-caff p-b": "2",
 "engerix-b pediatric": "2",
 "equaline acid reducer": "2",
 "endolor": "2",
 "ergocaf-pb": "2",
 "esgic": "2"}, "d": {"dolmar": "2",
 "donnatal": "2",
 "duo-vil": "3",
 "daptacel": "2",
 "duragal-s": "2",
 "diphtheria toxoid/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "diphtheria toxoid/hepatitis b pediatric vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "diphtheria toxoid/tetanus toxoid": "2",
 "decavac": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diphtheria toxoid/haemophilus b conjugate": "2",
 "donnapine": "2",
 "doxepin": "3",
 "denosumab": "2",
 "deferiprone": "3",
 "diphtheria-tetanus toxoids, pediatric": "2",
 "dryvax": "3",
 "diphtheria and tetanus toxoids/pertussis, acellular": "2",
 "donnatal extentabs": "2",
 "doxepin topical": "3",
 "dolgic plus": "2",
 "dolgic lq": "2",
 "donnaphen": "2",
 "desipramine": "3",
 "diphtheria toxoid/pertussis, whole cell/tetanus toxoid": "2",
 "d-tal": "2",
 "diphtheria toxoid/pertussis, acellular/tetanus toxoid": "2",
 "dolgic": "2",
 "denzapine": "3"}, "g": {"gilenya": "2",
 "gatifloxacin": "2",
 "gemifloxacin": "2",
 "golimumab": "3",
 "ganciclovir": "2",
 "geone": "2",
 "gardasil": "2",
 "g-1": "2",
 "grepafloxacin": "2"}, "f": {"fiortal": "2",
 "fingolimod": "2",
 "fluzone intradermal": "2",
 "fiorinal with codeine iii": "2",
 "fazaclo": "3",
 "fiorinal with codeine": "2",
 "flushield": "2",
 "fortabs": "2",
 "fiorinal": "2",
 "fioricet with codeine": "2",
 "femcet": "2",
 "fluvirin": "2",
 "ferriprox": "3",
 "flulaval": "2",
 "floxin": "2",
 "fiortal with codeine": "2",
 "fluzone high-dose": "2",
 "flumist": "3",
 "filgrastim": "2",
 "factive": "2",
 "fluogen": "2",
 "fluarix": "2",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiormor": "2",
 "fluzone": "2",
 "farbital": "2",
 "floxin iv": "2",
 "fiorpap": "2"}, "i": {"influenza virus vaccine, inactivated": "2",
 "imovax rabies": "2",
 "imuran": "2",
 "influenza virus vaccine, h1n1, live": "3",
 "ilaris": "2",
 "imipramine": "3",
 "isocarboxazid": "3",
 "ide-cet": "2",
 "influenza virus vaccine, h1n1, inactivated": "2",
 "idenal": "2",
 "infliximab": "3",
 "isocet": "2",
 "ipol": "2",
 "influenza virus vaccine, live, trivalent": "3",
 "ixiaro": "2",
 "infanrix": "2"}, "h": {"havrix pediatric": "2",
 "hepatitis b pediatric vaccine": "2",
 "histolyn-cyl": "2",
 "haemophilus b conjugate": "2",
 "hepatitis a pediatric vaccine": "2",
 "histoplasmin": "2",
 "hyosophen": "2",
 "havrix": "2",
 "humira": "3",
 "hibtiter (haemophilus b conjugate (hboc) vaccine)": "2",
 "hiberix (haemophilus b conjugate (prp-t) vaccine)": "2",
 "hepatitis a adult vaccine/hepatitis b adult vaccine": "2",
 "histoplasmin diluted": "2",
 "hepatitis a adult vaccine": "2",
 "human papillomavirus vaccine": "2",
 "haponal": "2",
 "hepatitis b adult vaccine": "2",
 "hyoscyamine/phenobarbital": "2",
 "hycamtin": "2"}, "k": {"kineret": "2",
 "kepivance": "2",
 "kinrix": "2"}, "j": {"je-vax": "2",
 "japanese encephalitis virus vaccine sa14-14-2": "2",
 "japanese encephalitis virus vaccine nakayama": "2"}, "m": {"measles virus vaccine/mumps virus vaccine/rubella virus vaccine": "3",
 "marplan": "3",
 "mygracet": "2",
 "margesic": "2",
 "mumps virus vaccine/rubella virus vaccine": "3",
 "moxifloxacin": "2",
 "menomune": "2",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine/varicella virus vaccine": "3",
 "m-r-vax ii": "3",
 "mumps skin test antigen": "2",
 "mysoline": "2",
 "msta mumps skin test antigen": "2",
 "minotal": "2",
 "marten-tab": "2",
 "measles virus vaccine": "3",
 "menomune a/c/y/w-135": "2",
 "migracet-pb": "2",
 "meningococcal conjugate vaccine": "2",
 "mumps virus vaccine": "3",
 "mephobarbital": "2",
 "m-m-r ii": "3",
 "mudrane gg": "2",
 "medigesic": "2",
 "mumpsvax": "3",
 "menactra": "2",
 "mebaral": "2",
 "mono-vacc test": "2",
 "mixed respiratory vaccine": "2",
 "meruvax ii": "3",
 "metastron": "2",
 "meningococcal polysaccharide vaccine": "2",
 "multitest cmi": "2",
 "menveo": "2",
 "maxaquin": "2",
 "mrv": "2",
 "measles virus vaccine/rubella virus vaccine": "3",
 "mudrane": "2",
 "micomp-pb": "2"}, "l": {"lyme disease vaccine": "2",
 "levsin with phenobarbital": "2",
 "lomefloxacin": "2",
 "lufyllin-epg": "2",
 "luminal": "2",
 "leflunomide": "3",
 "leukine": "2",
 "levofloxacin": "2",
 "lymerix": "2",
 "leustatin": "2",
 "laniroif": "2",
 "limbitrol ds": "3",
 "levaquin": "2",
 "liquid pedvaxhib (haemophilus b conjugate (prp-omp) vaccine)": "2",
 "limbitrol": "3",
 "lurline pms": "2",
 "levaquin leva-pak": "2"}, "o": {"orbivan": "2",
 "ofloxacin": "2",
 "orimune": "3"}, "n": {"noroxin": "2",
 "nonbac": "2",
 "norfloxacin": "2",
 "norpramin": "3",
 "nortriptyline": "3",
 "natalizumab": "3",
 "nardil": "3",
 "neulasta": "2",
 "nembutal sodium": "2",
 "nembutal": "2",
 "nestrex": "2",
 "nutr-e-sol": "2",
 "neupogen": "2"}, "q": {"quadrinal": "2",
 "quadrapax": "2",
 "quadramet": "3"}, "p": {"pyridium plus": "2",
 "pentobarbital": "2",
 "phenobarbital": "2",
 "promacet": "2",
 "parnate": "3",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "pneumococcal 7-valent vaccine": "2",
 "pb-hyos": "2",
 "pedvaxhib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "prominol": "2",
 "pyrelle hb": "2",
 "pediarix": "2",
 "prevnar 13": "2",
 "poliovirus vaccine, live, trivalent": "3",
 "penetrex": "2",
 "pharmagesic": "2",
 "pneumococcal 23-polyvalent vaccine": "2",
 "pneumococcal 13-valent vaccine": "2",
 "phenazoforte plus": "2",
 "palifermin": "2",
 "plague vaccine": "2",
 "pyridoxine": "2",
 "pamelor": "3",
 "proquin xr": "2",
 "prolia": "2",
 "primidone": "2",
 "provenge": "2",
 "phrenilin forte": "2",
 "pegfilgrastim": "2",
 "poliovirus vaccine, inactivated": "2",
 "phrenilin": "2",
 "proquad": "3",
 "phenaz plus": "2",
 "phenelzine": "3",
 "pneumovax 23": "2",
 "prudoxin": "3",
 "prevnar": "2",
 "pentacel (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid)": "2",
 "protriptyline": "3"}, "s": {"strontium-89 chloride": "2",
 "staphage lysate": "2",
 "stelara": "2",
 "sodium phosphate p32": "2",
 "sipuleucel-t": "2",
 "spastrin": "2",
 "seconal": "2",
 "sargramostim": "2",
 "spasmolin": "2",
 "simponi": "3",
 "smallpox vaccine": "3",
 "sinequan": "3",
 "sparfloxacin": "2",
 "spasquid": "2",
 "seconal sodium": "2",
 "surmontil": "3",
 "samarium sm 153 lexidronam": "3",
 "sedapap": "2",
 "servira": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "silenor": "3",
 "spherulin": "2",
 "skin test antigens, multiple": "2",
 "sclavo test-ppd": "2",
 "seconal sodium pulvules": "2"}, "r": {"recombivax hb pediatric/adolescent": "2",
 "rabies vaccine, human diploid cell": "2",
 "repan": "2",
 "rilonacept": "2",
 "remicade": "3",
 "raptiva": "2",
 "rotarix": "3",
 "recombivax hb dialysis formulation": "2",
 "recombivax hb": "2",
 "rotavirus vaccine": "3",
 "raxar": "2",
 "rubella virus vaccine": "3",
 "rabies vaccine, purified chick embryo cell": "2",
 "rotateq": "3",
 "re-pb hyos elixir": "2",
 "recombivax hb adult": "2",
 "rotashield": "3",
 "rabavert": "2"}, "u": {"urelief plus": "2",
 "ustekinumab": "2"}, "t": {"tenake": "2",
 "tofranil": "3",
 "triaprin": "2",
 "tetanus toxoid adsorbed": "2",
 "tencet": "2",
 "tuberculin tine test": "2",
 "tuberculin purified protein derivative": "2",
 "tubersol": "2",
 "tequin": "2",
 "trimipramine": "3",
 "tripedia": "2",
 "tetanus toxoid": "2",
 "trihibit (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "theracys": "3",
 "tetanus toxoid for booster use only": "2",
 "tice bcg": "3",
 "typhoid vaccine, inactivated": "2",
 "trichophyton allergenic extracts": "2",
 "trovafloxacin": "2",
 "triavil": "3",
 "te anatoxal berna": "2",
 "tetramune (diphtheria toxoid/haemophilus b conjugate (hboc) vaccine/pertussis, whole cell/tetanus toxoid)": "2",
 "theodrine": "2",
 "tagamet": "2",
 "tofranil-pm": "3",
 "tuinal": "2",
 "twinrix": "2",
 "trichophyton skin test": "2",
 "trovan": "2",
 "typhoid vaccine, live": "3",
 "tranylcypromine": "3",
 "tedrigen": "2",
 "tysabri": "3",
 "tagamet hb": "2",
 "tequin teqpaq": "2",
 "thalomid": "3",
 "tencon": "2",
 "thalidomide": "3",
 "topotecan": "2",
 "typhim vi": "2",
 "tice bcg vaccine": "3",
 "triad": "2",
 "tetanus-diphtheria toxoids, adult": "2",
 "two-dyne": "2"}, "v": {"vaqta pediatric": "2",
 "vivactil": "3",
 "vita-plus e natural": "2",
 "valcyte": "2",
 "varivax": "3",
 "vitamin b6": "2",
 "vaqta": "2",
 "varicella virus vaccine": "3",
 "vitamin e": "2",
 "valganciclovir": "2",
 "vivotif berna vaccine": "3",
 "vanatrip": "3",
 "vivotif berna": "3"}, "y": {"yellow fever vaccine": "3",
 "yf-vax": "3"}, "x": {"xgeva": "2"}, "z": {"zagam respipac": "2",
 "zoster vaccine live": "3",
 "zostavax": "3",
 "zebutal": "2",
 "zagam": "2",
 "zonalon": "3",
 "zaponex": "3"}}];