interactions["alvimopan,entereg"]=["alvimopan,entereg", {"a": {"acetaminophen/pentazocine": "3",
 "airacof": "3",
 "aspirin/hydrocodone": "3",
 "acetaminophen/tramadol": "3",
 "aspirin/caffeine/dihydrocodeine": "3",
 "alahist dhc": "3",
 "atuss ms": "3",
 "acetaminophen/oxycodone": "3",
 "ambi 5/15/100": "3",
 "ambifed-g cd": "3",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "3",
 "avinza": "3",
 "aspirin/carisoprodol/codeine": "3",
 "ambophen": "3",
 "atuss hd": "3",
 "ambifed-g cdx": "3",
 "astramorph pf": "3",
 "actiq": "3",
 "aspirin/oxycodone": "3",
 "acetaminophen/codeine": "3",
 "azdone": "3",
 "acetaminophen/butalbital/caffeine/codeine": "3",
 "acetaminophen/hydrocodone": "3",
 "a-g tussin": "3",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "3",
 "aspirin/butalbital/caffeine/codeine": "3",
 "alphen expectorant": "3",
 "allfen cdx": "3",
 "allerfrin with codeine": "3",
 "acetaminophen/propoxyphene": "3",
 "a-cof dh": "3",
 "ascomp with codeine": "3",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "3",
 "aspirin/codeine": "3",
 "alor 5/500": "3",
 "aspirin/pentazocine": "3",
 "atuss hx": "3",
 "aceta w/ codeine": "3",
 "abstral": "3",
 "atuss hs": "3",
 "acetaminophen/caffeine/dihydrocodeine": "3",
 "anaplex hd": "3",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "3",
 "ala-hist ac": "3",
 "ambifed cd": "3",
 "atuss g": "3",
 "ambenyl": "3",
 "anexsia": "3",
 "allfen cd": "3",
 "acetaminophen/chlorpheniramine/codeine": "3",
 "aspirin/caffeine/propoxyphene": "3",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "3",
 "atuss ex": "3",
 "ambifed cdx": "3",
 "anhydrous calcium iodide/codeine": "3"}, "c": {"codeine/dexchlorpheniramine/phenylephrine": "3",
 "co-tussin": "3",
 "co-gesic": "3",
 "codiclear dh": "3",
 "chlorpheniramine/hydrocodone/phenylephrine": "3",
 "chemdal expectorant": "3",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "3",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "3",
 "coldcough pd": "3",
 "calcidrine": "3",
 "cotabflu": "3",
 "codegest expectorant": "3",
 "codahistine expectorant": "3",
 "combunox": "3",
 "chlorpheniramine/hydrocodone": "3",
 "chemdal hd plus": "3",
 "codamine": "3",
 "coughtuss": "3",
 "co-histine expectorant": "3",
 "cotuss v": "3",
 "cheracol with codeine": "3",
 "codimal dh": "3",
 "cheratussin dac": "3",
 "chlorcyclizine/codeine/pseudoephedrine": "3",
 "capital w/codeine": "3",
 "codeine/guaifenesin/pseudoephedrine": "3",
 "cheratussin ac": "3",
 "cocet plus": "3",
 "canges-xp": "3",
 "carbinoxamine/hydrocodone/phenylephrine": "3",
 "codafen": "3",
 "codeine/promethazine": "3",
 "codafed": "3",
 "chlorpheniramine/guaifenesin/hydrocodone/pseudoephedrine": "3",
 "codeine/pseudoephedrine": "3",
 "cycofed pediatric expectorant": "3",
 "codal-dh syrup": "3",
 "chlorphen hd": "3",
 "colrex": "3",
 "chlorpheniramine/hydrocodone/pseudoephedrine": "3",
 "coldcough hcm": "3",
 "condasin": "3",
 "cotab ax": "3",
 "codeine/dexbrompheniramine/pseudoephedrine": "3",
 "chlorcyclizine/codeine": "3",
 "centussin dhc": "3",
 "cytuss-hc nr": "3",
 "capital with codeine suspension": "3",
 "co-histine dh": "3",
 "chlorcyclizine/codeine/phenylephrine": "3",
 "cycofed expectorant": "3",
 "codeine/phenylephrine": "3",
 "codeine/phenylephrine/pyrilamine": "3",
 "codehist dh": "3",
 "chemdal hd": "3",
 "chlorpheniramine/codeine": "3",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "3",
 "chemtussin hc": "3",
 "codeine/guaifenesin/phenylpropanolamine": "3",
 "codotuss": "3",
 "codeine/guaifenesin/phenylephrine": "3",
 "codamine pediatric": "3",
 "canges-hc": "3",
 "cyndal expectorant": "3",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "3",
 "coldcough syrup": "3",
 "codimal ph": "3",
 "codeprex": "3",
 "codahistine-dh elixir": "3",
 "cyndal hd": "3",
 "cycofed": "3",
 "co-tuss v expectorant": "3",
 "codeine/phenylephrine/promethazine": "3",
 "codafed pediatric": "3",
 "cordron-hc nr": "3",
 "cocet": "3",
 "comtussin hc": "3",
 "carbinoxamine/hydrocodone/pseudoephedrine": "3",
 "colrex compound": "3",
 "chlorgest hd": "3",
 "crantex hc": "3",
 "cytuss hc": "3",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "3",
 "codeine/guaifenesin": "3",
 "codeine phosphate-promethazine hcl": "3",
 "codituss dh": "3",
 "codeine/pseudoephedrine/pyrilamine": "3",
 "canges-hc nr": "3",
 "codeine": "3",
 "codeine/diphenhydramine/phenylephrine": "3",
 "chlorpheniramine/codeine/pseudoephedrine": "3",
 "codeine/pheniramine/phenylephrine/sodium citrate": "3",
 "cotab a": "3",
 "codeine/pseudoephedrine/triprolidine": "3",
 "cordron-hc": "3",
 "conzip": "3"}, "b": {"brovex cb": "3",
 "brompheniramine/codeine/phenylephrine": "3",
 "brompheniramine/hydrocodone/phenylephrine": "3",
 "bromplex hd": "3",
 "bitex liquid": "3",
 "brovex cbx": "3",
 "brontex": "3",
 "balacet": "3",
 "bupivacaine/fentanyl": "3",
 "butrans": "3",
 "b-tuss": "3",
 "biotussin dac": "3",
 "buprenorphine/naloxone": "3",
 "brompheniramine/codeine/phenylpropanolamine": "3",
 "brompheniramine/dihydrocodeine/phenylephrine": "3",
 "bromph hd": "3",
 "b &amp; o supprettes": "3",
 "bromodiphenhydramine/codeine": "3",
 "brovex pb c": "3",
 "brompheniramine/hydrocodone/pseudoephedrine": "3",
 "bupivacaine/hydromorphone": "3",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "3",
 "brovex hc": "3",
 "brompheniramine/codeine": "3",
 "buprenorphine": "3",
 "buprenex": "3",
 "butorphanol": "3",
 "bromcomp hc": "3",
 "bpm pe hc": "3",
 "brovex pb cx": "3",
 "belladonna/opium": "3",
 "brompheniramine/codeine/pseudoephedrine": "3"}, "e": {"entuss-d liquid": "3",
 "efasin-hd plus": "3",
 "endacof hc": "3",
 "extendryl hc": "3",
 "endal expectorant": "3",
 "endacof-dc": "3",
 "endacof-tab": "3",
 "enditussin expectorant": "3",
 "endacof-dh": "3",
 "endacof-c": "3",
 "entuss-d jr": "3",
 "endacof-plus": "3",
 "endal-hd plus": "3",
 "endacof-ac": "3",
 "endocodone": "3",
 "endodan": "3",
 "excof-sf": "3",
 "excof": "3",
 "efasin-hd": "3",
 "execlear": "3",
 "endacof xp": "3",
 "efasin expectorant sf": "3",
 "ed-tuss hc": "3",
 "exetuss-hc": "3",
 "enplus-hd": "3",
 "empirin with codeine": "3",
 "execof": "3",
 "endal cd": "3",
 "echotuss-hc": "3",
 "embeda": "3",
 "exalgo": "3",
 "endotuss expectorant": "3",
 "entuss-d": "3",
 "endal hd": "3",
 "endagen-hd": "3",
 "entuss expectorant": "3",
 "eth-oxydose": "3",
 "ez iii": "3",
 "ed-tlc": "3",
 "exo-tuss": "3",
 "endotuss-hd": "3",
 "execlear-c": "3",
 "entex hc": "3",
 "entuss": "3",
 "endocet": "3"}, "d": {"duratuss hd": "3",
 "dihydrocodeine/phenylephrine/pyrilamine": "3",
 "darvon compound 32": "3",
 "duragesic-50": "3",
 "dolacet": "3",
 "dilaudid": "3",
 "duragesic-75": "3",
 "darvon-n": "3",
 "dolagesic": "3",
 "decotuss-hd": "3",
 "doloral": "3",
 "dihistine dh": "3",
 "darvocet-n 100": "3",
 "damason-p": "3",
 "duragesic": "3",
 "duramorph": "3",
 "de-chlor g": "3",
 "dihistine": "3",
 "dihistine expectorant": "3",
 "dexchlorpheniramine/hydrocodone/phenylephrine": "3",
 "duragesic-100": "3",
 "dezocine": "3",
 "despec-pd": "3",
 "duocet": "3",
 "duradal hd": "3",
 "dimetane dc": "3",
 "dalgan": "3",
 "drituss hd": "3",
 "diphenhydramine/hydrocodone/phenylephrine": "3",
 "darvon": "3",
 "dihydro-pe": "3",
 "dicomal-dh": "3",
 "droperidol/fentanyl": "3",
 "detussin expectorant": "3",
 "dilaudid cough syrup": "3",
 "demi-cof": "3",
 "donatuss dc": "3",
 "donatussin max": "3",
 "doloral sirop": "3",
 "duragesic-25": "3",
 "dexbrompheniramine/hydrocodone/phenylephrine": "3",
 "darvocet a500": "3",
 "ditussin-hc": "3",
 "diabetic tussin c": "3",
 "detussin": "3",
 "dihydrocodeine/guaifenesin/phenylephrine": "3",
 "dynatuss hc": "3",
 "darvon compound-65": "3",
 "duramorph pf": "3",
 "dihydrocodeine/guaifenesin": "3",
 "dytan-hc": "3",
 "duohist dh": "3",
 "dynex hd": "3",
 "duraganidin nr": "3",
 "de-chlor hd": "3",
 "de-chlor nx": "3",
 "dex-tuss": "3",
 "dilaudid-hp": "3",
 "de-chlor hc": "3",
 "dihydro-gp": "3",
 "dazidox": "3",
 "dihydrocodeine/guaifenesin/pseudoephedrine": "3",
 "deconsal c expectorant": "3",
 "detuss": "3",
 "demerol": "3",
 "duragesic-12": "3",
 "deproist with codeine": "3",
 "d-tann hc": "3",
 "dolophine": "3",
 "dihistine expectorant with codeine": "3",
 "donatussin dc": "3",
 "drotuss-cp": "3",
 "deconamine cx": "3",
 "duradyne dhc": "3",
 "darvocet-n 50": "3",
 "dicomal-ph": "3",
 "dihydro-cp": "3",
 "dronedarone": "2",
 "decohistine dh": "3",
 "de-chlor mr": "3",
 "dihydrocodeine/phenylephrine": "3",
 "drocon-cs": "3",
 "decohistine expectorant": "3"}, "g": {"guaifenesin/hydrocodone": "3",
 "guaifen-c": "3",
 "guaifenesin/hydrocodone/pseudoephedrine": "3",
 "guaitussin ac": "3",
 "guaifen ac": "3",
 "gua hc": "3",
 "guiatuss dac": "3",
 "guaifenesin/hydrocodone/pheniramine/phenylephrine/phenylpropanolamine": "3",
 "guiatussin with codeine": "3",
 "guaifenesin/hydrocodone/phenylephrine": "3",
 "guiaplex hc": "3",
 "guai-co": "3",
 "gani-tuss nr": "3",
 "guiatussin dac": "3",
 "gua pc": "3",
 "gestuss-hc": "3",
 "giltuss ped-c": "3",
 "gentex hc": "3",
 "glydeine": "3",
 "guiatuss ac": "3",
 "guaifenesin dac liquid": "3",
 "guaifenesin/hydrocodone/pheniramine/phenylpropanolamine/pyrilamine": "3",
 "g-tuss": "3",
 "genrx tramadol": "3",
 "guaiatussin ac": "3",
 "guaifen dac": "3",
 "guaiatussin dac": "3",
 "guaifenesin/hydromorphone": "3",
 "guiaphen hd": "3"}, "f": {"fentora": "3",
 "fiorinal with codeine": "3",
 "fentuss expectorant": "3",
 "fentanyl/ropivacaine": "3",
 "fioricet with codeine": "3",
 "fentanyl transdermal system": "3",
 "flutuss hc": "3",
 "fentanyl": "3",
 "fiorinal with codeine iii": "3",
 "floricet with codeine": "3",
 "fiortal with codeine": "3"}, "i": {"ibuprofen/oxycodone": "3",
 "innovar": "3",
 "iotussin d liquid": "3",
 "iotussin hc": "3",
 "iophen": "3",
 "ibudone": "3",
 "ionsys": "3",
 "iophen-c nr": "3",
 "iodal hd": "3",
 "infumorph": "3"}, "h": {"hydron pcs": "3",
 "hydro-tuss xp": "3",
 "histex hc": "3",
 "hytussin": "3",
 "halotussin dac": "3",
 "hycodan": "3",
 "histussin d": "3",
 "hydro-tussin exp": "3",
 "histinex hc": "3",
 "hydro-tussin hg": "3",
 "hycoclar tuss": "3",
 "hydromorphone": "3",
 "hydrocodone hd": "3",
 "hydrocodone/phenylephrine": "3",
 "hytan": "3",
 "hycosin expectorant": "3",
 "hydromide": "3",
 "highland hc": "3",
 "h-c tussive-nr": "3",
 "hydrofed": "3",
 "histinex d": "3",
 "hydrocodone/ibuprofen": "3",
 "hycophen pediatric": "3",
 "hydrocod-gf": "3",
 "h-c tussive d": "3",
 "hycomal dh": "3",
 "hycophen": "3",
 "hydrocodone cp": "3",
 "hexatussin": "3",
 "hydropane": "3",
 "hydrocodone/pseudoephedrine": "3",
 "hycomine pediatric": "3",
 "hyphen-hd": "3",
 "hydrocodone gf": "3",
 "hycoclear": "3",
 "hydromet": "3",
 "hydrotropine": "3",
 "hydrocet": "3",
 "hydrocodone/potassium guaiacolsulfonate": "3",
 "hydrotuss": "3",
 "hydrocodone/potassium guaiacolsulfonate/pseudoephedrine": "3",
 "hydro-dp": "3",
 "h-c tussive": "3",
 "hyco-dh": "3",
 "hycomine compound": "3",
 "hydrocodone/pseudoephedrine/triprolidine": "3",
 "hydrocodone/phenylpropanolamine": "3",
 "histussin hc liquid": "3",
 "halotussin ac": "3",
 "hy-phen": "3",
 "hytussin expectorant": "3",
 "hydrotuss hc": "3",
 "hi-tuss hc": "3",
 "histinex pv": "3",
 "hydro-tussin dhc": "3",
 "hypamine": "3",
 "hydex pd": "3",
 "hydrotussin hd": "3",
 "hydrocof-hc": "3",
 "hydro gp": "3",
 "hydron kgs": "3",
 "hydro-pc ii": "3",
 "hydrocodone pa pediatric": "3",
 "hydromorph contin": "3",
 "hydrostat ir": "3",
 "hy-kxp": "3",
 "hydrophene dh": "3",
 "histussin hc syrup": "3",
 "hydrocodone/phenylephrine/pyrilamine": "3",
 "hycomine": "3",
 "hyphed": "3",
 "hycotuss expectorant": "3",
 "hydron cp": "3",
 "hydrocodone": "3",
 "hydrocodone/pheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "3",
 "homatropine/hydrocodone": "3",
 "hydron ex": "3",
 "hydro-pc ii plus": "3",
 "hycet": "3",
 "hydrogesic": "3"}, "k": {"kadian": "3",
 "kgs-hc": "3",
 "kg-dal hd plus": "3",
 "kg-fed pediatric expectorant": "3",
 "kg-tussin": "3",
 "kg-dal hd": "3",
 "kg-tuss hd": "3",
 "kwelcof": "3",
 "kg-fed expectorant": "3",
 "kg-fed": "3"}, "j": {"j-max dhc": "3",
 "j-cof dhc": "3",
 "jaycof-hc": "3",
 "j-tan d hc": "3"}, "m": {"m-end max d": "3",
 "mar-cof cg": "3",
 "morphine rapi-ject": "3",
 "morphine sulfate ir": "3",
 "maxi-tuss sa": "3",
 "maxi-tuss hc": "3",
 "maxifed cd": "3",
 "ms contin": "3",
 "m-end wc": "3",
 "mintuss ms": "3",
 "maxiphen cdx": "3",
 "morphine sulfate er": "3",
 "meprozine": "3",
 "maxifed cdx": "3",
 "maxiflu cd": "3",
 "mintuss mr": "3",
 "mintex hc": "3",
 "maxiphen cd": "3",
 "margesic h": "3",
 "m-oxy": "3",
 "meperidine/promethazine": "3",
 "maxifed-g cd": "3",
 "morphine sulfate sr": "3",
 "medcodin": "3",
 "myphetane dc": "3",
 "maxifed-g cdx": "3",
 "morphine/naltrexone": "3",
 "magnacet": "3",
 "methadone diskets": "3",
 "m-eslon": "3",
 "monteflu hc": "3",
 "mytussin dac": "3",
 "m-phen": "3",
 "morphine lp epidural": "3",
 "mepergan": "3",
 "monte-g hc": "3",
 "marcof expectorant": "3",
 "meperitab": "3",
 "medent c": "3",
 "mepergan fortis": "3",
 "max hc": "3",
 "mar-cof bp": "3",
 "mintuss nx": "3",
 "m-end": "3",
 "multaq": "2",
 "morphitec": "3",
 "m-clear": "3",
 "morphine": "3",
 "methadose": "3",
 "m-clear wc": "3",
 "ms/s": "3",
 "maxi-tuss hcx": "3",
 "maxiflu cdx": "3",
 "mytussin ac": "3",
 "meperidine": "3",
 "maxidone": "3",
 "maxi-tuss hcg": "3",
 "methadone": "3",
 "medtuss hd": "3",
 "mintuss g": "3",
 "msir": "3",
 "m o s": "3",
 "m-end pe": "3"}, "l": {"lortab 10/500": "3",
 "lortab 2.5/500": "3",
 "lorcet plus": "3",
 "levorphanol": "3",
 "liquitussin hc syrup": "3",
 "levo-dromoran": "3",
 "lortab asa": "3",
 "liquicet": "3",
 "liquituss hd": "3",
 "lazanda": "3",
 "lortab 5/500": "3",
 "lorcet hd": "3",
 "lorcet 10/650": "3",
 "lortab": "3",
 "levall 5.0": "3",
 "liquicough hc": "3",
 "liquihistine cs": "3",
 "lexuss 210 liquid": "3",
 "lortuss hc": "3",
 "lortab 7.5/500": "3",
 "levomethadyl acetate": "3"}, "o": {"opana": "3",
 "oxycet": "3",
 "opana er": "3",
 "oxyir": "3",
 "opium": "3",
 "oramorph sr": "3",
 "oxydose": "3",
 "opium tincture, deodorized": "3",
 "orlaam": "3",
 "oms": "3",
 "oxycontin": "3",
 "oxymorphone": "3",
 "oxycodone": "3",
 "onsolis": "3",
 "opium deodorized": "3",
 "oxecta": "3",
 "oxyfast": "3"}, "n": {"naldecon-cx adult": "3",
 "nalex ac": "3",
 "notuss pd": "3",
 "nalex expectorant": "3",
 "numorphan": "3",
 "notuss-nxd": "3",
 "narvox": "3",
 "notuss-dc": "3",
 "nasotuss": "3",
 "nucodine": "3",
 "notuss-pe": "3",
 "novahistine expectorant": "3",
 "numorphan hcl": "3",
 "nazarin hc": "3",
 "novagest with codeine": "3",
 "nalbuphine": "3",
 "nucodine expectorant": "3",
 "nucofed expectorant": "3",
 "nucofed pediatric expectorant": "3",
 "neo ac": "3",
 "novahistine dh": "3",
 "novasus": "3",
 "novadyne dh": "3",
 "notuss-forte": "3",
 "nuco-tuss expectorant": "3",
 "nucofed": "3",
 "nucodine pediatric": "3",
 "neo hc": "3",
 "nuco-tuss pediatric expectorant": "3",
 "nucochem": "3",
 "narcof": "3",
 "notuss-ac": "3",
 "nasatuss": "3",
 "notuss-nx": "3",
 "nalex-dh": "3",
 "naloxone/pentazocine": "3",
 "notuss": "3",
 "nucochem pediatric expectorant": "3",
 "nucochem expectorant": "3",
 "novadyne expectorant": "3",
 "norco": "3",
 "nariz hc": "3",
 "nubain": "3"}, "q": {"q-v tussin": "3",
 "quindal hd": "3",
 "qual-tussin dc": "3",
 "quindal hd plus": "3"}, "p": {"pseudodine c": "3",
 "poly-tussin ex syrup": "3",
 "palladone": "3",
 "propacet 100": "3",
 "poly-tussin": "3",
 "phenergan vc with codeine": "3",
 "procof d": "3",
 "pancof-pd": "3",
 "panlor dc": "3",
 "phenylhistine dh expectorant": "3",
 "pediatex hc": "3",
 "p-v-tussin": "3",
 "pneumotussin 2.5": "3",
 "percodan": "3",
 "poly-tussin xp": "3",
 "phenergan with codeine": "3",
 "propatuss expectorant": "3",
 "pediacof": "3",
 "pentazocine": "3",
 "phenflu cdx": "3",
 "panacet": "3",
 "pc-cap": "3",
 "percocet 5/325": "3",
 "protuss": "3",
 "phendacof plus": "3",
 "percocet 10/650": "3",
 "propoxyphene": "3",
 "perloxx": "3",
 "pneumotussin": "3",
 "panlor ss": "3",
 "poly hist dhc": "3",
 "polytine cs": "3",
 "percocet 10/325": "3",
 "poly hist hc": "3",
 "pseudatex hc": "3",
 "poly tussin ex": "3",
 "pedituss": "3",
 "phenhist expectorant": "3",
 "pancof hc": "3",
 "phrenilin with caffeine and codeine": "3",
 "percodan-demi": "3",
 "promethazine vc with codeine": "3",
 "poly cs": "3",
 "phenylhistine dh": "3",
 "pneumotussin hc": "3",
 "phenylhistine expectorant": "3",
 "paregoric": "3",
 "phenaphen with codeine": "3",
 "percocet 2.5/325": "3",
 "promethazine hcl with codeine": "3",
 "protuss-d": "3",
 "poly-tussin ac": "3",
 "pancof exp": "3",
 "poly-tussin hd": "3",
 "primlev": "3",
 "pancof xp": "3",
 "prolex dh": "3",
 "poly-tussin dhc": "3",
 "pancof": "3",
 "propoxyphene compound 65": "3",
 "percocet 7.5/500": "3",
 "poly-histine cs": "3",
 "phendal-hd": "3",
 "phenflu cd": "3",
 "primalev": "3",
 "percolone": "3",
 "phenylephrine hd": "3",
 "percocet": "3",
 "pro-clear": "3",
 "p-v-tussin syrup": "3",
 "procof": "3",
 "pp-cap": "3",
 "panasal 5/500": "3",
 "promethazine hcl and codeine phosphate": "3",
 "percocet 7.5/325": "3",
 "pro-red ac": "3",
 "polyhist nc": "3",
 "promethazine with codeine": "3",
 "promethazine vc w/codeine": "3"}, "s": {"symtan": "3",
 "suttar sf": "3",
 "src expectorant": "3",
 "subsys": "3",
 "s-t forte": "3",
 "simuc-hd": "3",
 "suboxone": "3",
 "symtan a": "3",
 "sublimaze": "3",
 "suttar-2": "3",
 "stadol": "3",
 "spantuss hd": "3",
 "statuss": "3",
 "soma compound with codeine": "3",
 "stagesic": "3",
 "su-tuss hd elixir": "3",
 "s-t forte 2": "3",
 "statex": "3",
 "subutex": "3",
 "synalgos-dc": "3",
 "statuss green": "3"}, "r": {"rms": "3",
 "rybix odt": "3",
 "roxicodone": "3",
 "rolatuss": "3",
 "robitussin-ac": "3",
 "robafen ac": "3",
 "ryna-cx": "3",
 "robitussin-dac": "3",
 "romilar ac": "3",
 "rindal-hd": "3",
 "ryzolt": "3",
 "relasin-hcx": "3",
 "roxanol-t": "3",
 "ru-tuss with hydrocodone": "3",
 "reprexain": "3",
 "rescudose": "3",
 "relacon-hc nr": "3",
 "roxilox": "3",
 "relacon-hc": "3",
 "robichem ac": "3",
 "rindal hpd": "3",
 "roxanol 100": "3",
 "roxiprin": "3",
 "relasin-hc": "3",
 "rolatuss with hydrocodone": "3",
 "relcof c": "3",
 "roxicet": "3",
 "rybix": "3",
 "rindal hd plus": "3",
 "rezira": "3",
 "ryna-c": "3",
 "roxanol": "3",
 "roxicodone intensol": "3"}, "u": {"uni-tricof hc": "3",
 "uni tuss hc": "3",
 "ultram er": "3",
 "uni-cof": "3",
 "uni-lev 5.0": "3",
 "ultram": "3",
 "ultram odt": "3",
 "ultracet": "3",
 "uni-cof expectorant": "3"}, "t": {"tussar-2": "3",
 "triafed &amp; codeine": "3",
 "triant-hc": "3",
 "tylenol with codeine #4": "3",
 "tusdec-hc": "3",
 "tussionex pennkinetic": "3",
 "tramadol": "3",
 "tri-vent hc": "3",
 "tuss-ds": "3",
 "trifed c": "3",
 "tussive hc": "3",
 "talwin nx": "3",
 "tramahexal sr": "3",
 "trezix": "3",
 "tl-hist cm": "3",
 "tramal sr": "3",
 "tl-hist cd": "3",
 "touro hc": "3",
 "theracodophen low 90": "3",
 "tussiden c": "3",
 "tusso-df": "3",
 "tussigon": "3",
 "tussgen expectorant": "3",
 "trycet": "3",
 "talwin": "3",
 "tussinate": "3",
 "tussar sf": "3",
 "tussend expectorant": "3",
 "tussirex": "3",
 "tussplex": "3",
 "tramal": "3",
 "t- koff": "3",
 "t-gesic": "3",
 "tussirex sugar free": "3",
 "tramapap": "3",
 "tussafed-hc": "3",
 "tylox": "3",
 "tusso-c": "3",
 "tussafin liquid": "3",
 "tussafin": "3",
 "tusana-d": "3",
 "tussicle": "3",
 "tylenol with codeine #3": "3",
 "triacin c": "3",
 "talacen": "3",
 "tylenol with codeine #2": "3",
 "tuss-hc": "3",
 "tussadur-hd": "3",
 "trihist-cs": "3",
 "tussend": "3",
 "tussin-v": "3",
 "tusso-hc": "3",
 "tussicaps": "3",
 "tussgen": "3",
 "tusscough dhc": "3",
 "tramedo": "3",
 "tussafed-hcg": "3",
 "tylenol with codeine": "3",
 "tricof": "3",
 "trimal dh": "3",
 "tridal": "3",
 "tussi-organidin nr": "3",
 "talwin compound": "3",
 "tussi-organidin-s nr": "3",
 "tuss-pd": "3"}, "w": {"wygesic": "3",
 "welltuss hc": "3",
 "welltuss exp": "3"}, "v": {"vicoprofen": "3",
 "vicodin hp": "3",
 "vi-q-tuss": "3",
 "vetuss hc syrup": "3",
 "ventuss syrup": "3",
 "vanex-hd": "3",
 "vanex expectorant": "3",
 "vicotuss": "3",
 "vicodin es": "3",
 "vortex": "3",
 "vasotuss hc": "3",
 "vopac": "3",
 "visvex": "3",
 "vitussin expectorant": "3",
 "vicoclear": "3",
 "vanacof cd": "3",
 "vicodin": "3",
 "vazotuss hc": "3",
 "vicodin tuss": "3",
 "vanacon": "3"}, "x": {"xolox": "3",
 "xodol": "3",
 "xpect-hc": "3"}, "z": {"zymine hc": "3",
 "zutripro": "3",
 "zerlor": "3",
 "zamadol": "3",
 "zodryl dac": "3",
 "ztuss zt": "3",
 "zodryl dec": "3",
 "zotex-c": "3",
 "z-tuss ac": "3",
 "zydol": "3",
 "zodryl ac": "3",
 "zamicet": "3",
 "z-tuss 2": "3",
 "z-cof hc": "3",
 "zolvit": "3",
 "zotex hc": "3",
 "zydone": "3",
 "z-cof hcx": "3"}}];