interactions["amiloride,midamor"]=["amiloride,midamor", {"4": {"40 winks": "2"}, "a": {"aminophylline/amobarbital/ephedrine": "2",
 "adoxa ck": "1",
 "aristocort": "2",
 "alfenta": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "aspirin/diphenhydramine": "2",
 "advil liqui-gels": "2",
 "antispas": "2",
 "aflaxen": "2",
 "aler-dryl": "2",
 "aldactone": "3",
 "amlodipine/hydrochlorothiazide/valsartan": "3",
 "actiq": "2",
 "aspirin/oxycodone": "2",
 "apo-go pen": "2",
 "advil pm": "2",
 "ambien cr": "2",
 "amitriptyline": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "ambenyl": "2",
 "atrosept": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "allfen cdx": "2",
 "amlodipine/telmisartan": "3",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "amoxicot": "1",
 "ami-rax": "2",
 "angiografin": "2",
 "addaprin": "2",
 "acetaminophen/caffeine/dihydrocodeine": "2",
 "atacand hct": "3",
 "apraclonidine ophthalmic": "2",
 "ambien": "2",
 "alodox": "1",
 "aminosyn ii with electrolytes": "3",
 "allergy relief d": "2",
 "amoxicillin/clavulanate": "1",
 "amoxapine": "2",
 "azilsartan medoxomil": "3",
 "adoxa tt": "1",
 "advil cold and sinus liqui-gels": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "alahist lq": "2",
 "aldesleukin": "2",
 "amytal sodium": "2",
 "atacand": "3",
 "anhydrous calcium iodide/codeine": "2",
 "a-hydrocort": "2",
 "accuretic": "3",
 "anaprox": "2",
 "alprazolam": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "aminosyn ii 4.25%-dextrose 25%,electrolyte,ca": "3",
 "azmacort": "2",
 "asenapine": "2",
 "aristopak": "2",
 "aspirin/carisoprodol": "2",
 "achromycin v": "1",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "acetaminophen/diphenhydramine/pseudoephedrine": "2",
 "aminosyn ii 3.5%-dextrose 25%,electrolytes,ca": "3",
 "alcohol": "2",
 "aliskiren/valsartan": "3",
 "advil children's allergy sinus": "2",
 "aleve": "2",
 "anergan 50": "2",
 "adrenocot": "2",
 "aminosyn ii 4.25%-dextrose 20%,electrolyte,ca": "3",
 "adlone-40": "2",
 "aquachloral supprettes": "2",
 "avidoxy": "1",
 "azilsartan medoxomil/chlorthalidone": "3",
 "accupril": "3",
 "aspirin/methocarbamol": "2",
 "aliskiren/amlodipine": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "allermax": "2",
 "acthar": "2",
 "ambophen": "2",
 "a-g profen": "2",
 "avapro": "3",
 "a-methapred": "2",
 "acetocot": "2",
 "alkabel-sr": "2",
 "advil allergy sinus": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "amobarbital": "2",
 "aldex-ct": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "aspirin/meprobamate": "2",
 "amoclan": "1",
 "aminosyn with electrolytes": "3",
 "amoxicillin": "1",
 "aceon": "3",
 "aristocort for injection": "2",
 "asendin": "2",
 "atuss ex": "3",
 "allfen cd": "2",
 "apomorphine": "2",
 "advil children's cold": "2",
 "augmentin": "1",
 "amlodipine/benazepril": "3",
 "augmentin es-600": "1",
 "airacof": "2",
 "ambifed-g cdx": "2",
 "acetaminophen/dextromethorphan/diphenhydramine": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "advil migraine": "2",
 "ala-tet": "1",
 "all day relief": "2",
 "alprazolam intensol": "2",
 "abilify": "2",
 "acetaminophen/oxycodone": "2",
 "avidoxy dk": "1",
 "amlobenz": "3",
 "all day pain relief": "2",
 "amobarbital/secobarbital": "2",
 "ala-hist": "2",
 "angeliq": "2",
 "advil infant's concentrated drops": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "actiprofen": "2",
 "atropine/phenobarbital": "2",
 "avinza": "2",
 "anacin p.m. aspirin free": "2",
 "antispasmodic": "2",
 "alka-seltzer pm": "2",
 "actoplus met xr": "2",
 "adapin": "2",
 "altace": "3",
 "acetaminophen/codeine": "2",
 "antrocol": "2",
 "amoxicillin/clarithromycin/lansoprazole": "1",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "antiflex": "2",
 "aspirin/carisoprodol/codeine": "2",
 "allergia-c": "2",
 "atamet": "2",
 "ambifed cd": "2",
 "alphen expectorant": "2",
 "adlone-80": "2",
 "allerfrin with codeine": "2",
 "all day allergy children's": "2",
 "alahist dhc": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "amifostine": "2",
 "alcohol and dextrose injections usp hypertonic": "2",
 "atarax": "2",
 "aleve-d sinus &amp; cold": "2",
 "aplenzin": "2",
 "amoxil": "1",
 "apo-go": "2",
 "aceta w/ codeine": "2",
 "azor": "3",
 "advil junior strength": "2",
 "alfentanil": "2",
 "acetaminophen pm extra strength": "2",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "adbeon": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/pseudoephedrine": "2",
 "avandamet": "2",
 "ambifed-g cd": "2",
 "aminosyn ii with electrolytes sulfite-free": "3",
 "anaprox-ds": "2",
 "actisite": "1",
 "aripiprazole": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "altaryl": "2",
 "aminosyn with electrolytes sulfite-free": "3",
 "acetaminophen/pentazocine": "2",
 "augmentin xr": "1",
 "actron": "2",
 "actifed allergy day/night": "2",
 "ala-hist d": "2",
 "acetaminophen/propoxyphene": "2",
 "avalide": "3",
 "aliskiren": "2",
 "azilect": "2",
 "arthrotec": "2",
 "all day allergy": "2",
 "acthrel": "2",
 "advil": "2",
 "astramorph pf": "2",
 "actoplus met": "2",
 "adrenocot la": "2",
 "acth": "2",
 "allfen": "3",
 "anafranil": "2",
 "asthmacon": "2",
 "amlodipine/olmesartan": "3",
 "alka-seltzer gold": "3",
 "aventyl hydrochloride": "2",
 "apokyn": "2",
 "aristospan": "2",
 "atapryl": "2",
 "ativan": "2",
 "amturnide": "2",
 "aspirin/codeine": "2",
 "advil cold and sinus": "2",
 "aspirin/pentazocine": "2",
 "ansaid": "2",
 "abstral": "2",
 "alcohol 5% in dextrose 5%": "2",
 "acetaminophen/diphenhydramine": "2",
 "amlodipine/valsartan": "3",
 "all day allergy-d": "2",
 "ala-hist ac": "2",
 "aldactazide": "3",
 "adoxa": "1",
 "advil children's": "2",
 "adcirca": "1",
 "alleroff": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "3",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "aler-tab": "2",
 "abilify discmelt": "2",
 "ambifed cdx": "2"}, "c": {"cysto-conray": "2",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "cozaar": "3",
 "chloral hydrate": "2",
 "cardoxin": "1",
 "colrex compound": "2",
 "capozide 50/25": "3",
 "cytra-k": "3",
 "cholografin meglumine": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "carbetapentane/phenylephrine/phenylpropanolamine/potassium guaiacolsulfonate": "3",
 "coldcough pd": "2",
 "calcidrine": "2",
 "cetirizine/pseudoephedrine": "2",
 "cotab ax": "2",
 "codeine/pseudoephedrine": "2",
 "codahistine expectorant": "2",
 "combunox": "2",
 "citric acid/potassium citrate/sodium citrate": "3",
 "childrens ibuprofen berry": "2",
 "cytra-3": "3",
 "corticotropin": "2",
 "citalopram": "2",
 "capoten": "3",
 "cotrim": "2",
 "carbidopa/levodopa": "2",
 "corlopam": "2",
 "celecoxib": "2",
 "co-histine expectorant": "2",
 "cheracol with codeine": "2",
 "cort-k": "2",
 "cheratussin dac": "2",
 "celestone phosphate": "2",
 "conray": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "cyclosporine": "2",
 "carbex": "2",
 "clozapine": "2",
 "carbetapentane/diphenhydramine": "2",
 "capital w/codeine": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "cheratussin ac": "2",
 "cotrim pediatric": "2",
 "cortrosyn": "2",
 "cystografin-dilute": "2",
 "cetirizine": "2",
 "celexa": "2",
 "children's tylenol plus cold and allergy": "2",
 "carbacot": "2",
 "codafen": "2",
 "cysto-conray ii": "2",
 "cabergoline": "2",
 "codeine/promethazine": "2",
 "conjugated estrogens/meprobamate": "2",
 "codafed": "2",
 "celestone": "2",
 "conray-30": "2",
 "cortenema": "2",
 "comfort pac with naproxen": "2",
 "compazine spansule": "2",
 "camptosar": "2",
 "codegest expectorant": "2",
 "carbidopa/entacapone/levodopa": "2",
 "cycofed pediatric expectorant": "2",
 "chlordinium": "2",
 "chlordiazepoxide/clidinium": "2",
 "cortifoam": "2",
 "complete allergy": "2",
 "candesartan/hydrochlorothiazide": "3",
 "colrex": "2",
 "clopine": "2",
 "candesartan": "3",
 "compro": "2",
 "clozaril": "2",
 "citrolith": "3",
 "counteract pm extra strength": "2",
 "conray-400": "2",
 "cap-profen": "2",
 "cotabflu": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "cell-u-jec": "2",
 "chlorcyclizine/codeine": "2",
 "chardonna-2": "2",
 "centussin dhc": "2",
 "children's motrin": "2",
 "cypex-la": "3",
 "chlordiazepoxide": "2",
 "cardioquin": "3",
 "chlordiazepoxide/methscopolamine": "2",
 "cotrim ds": "2",
 "capital with codeine suspension": "2",
 "calm-aid": "2",
 "cystex": "2",
 "co-histine dh": "2",
 "carbetapentane/phenylephrine/potassium guaiacolsulfonate": "3",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "cycofed expectorant": "2",
 "codeine/phenylephrine": "2",
 "cocet plus": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "cortone acetate": "2",
 "cataflam": "2",
 "codehist dh": "2",
 "contac day and night allergy": "2",
 "capozide 25/15": "3",
 "clomipramine": "2",
 "caldolor": "2",
 "cortisone": "2",
 "chlorpheniramine/codeine": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "cena k": "3",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "cymbalta": "2",
 "cimetidine": "1",
 "chlorpromazine": "2",
 "cophene-x": "3",
 "clinalog": "2",
 "carbamazepine": "2",
 "cyndal expectorant": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "coldcough syrup": "2",
 "clorazepate": "2",
 "clinacort": "2",
 "corticorelin": "2",
 "cosyntropin": "2",
 "cvs allergy &amp; cold": "2",
 "cetiri d": "2",
 "capozide 50/15": "3",
 "carbatuss-cl": "3",
 "cvs allergy &amp; sinus headache": "2",
 "codimal ph": "2",
 "children's triacting night time": "2",
 "codahistine-dh elixir": "2",
 "cotolone": "2",
 "clozapine synthon": "2",
 "cycofed": "2",
 "compoz nighttime sleep aid": "2",
 "compazine": "2",
 "celestone soluspan": "2",
 "codeine/phenylephrine/promethazine": "2",
 "codafed pediatric": "2",
 "conray-43": "2",
 "children's zyrtec": "2",
 "clinoril": "2",
 "carbatrol": "2",
 "captopril/hydrochlorothiazide": "3",
 "clinimix e sulfite free": "3",
 "cocet": "2",
 "cystemms-v": "2",
 "carisoprodol compound": "2",
 "cystografin": "2",
 "captopril": "3",
 "codeine/guaifenesin/phenylephrine": "2",
 "carisoprodol": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "contac day and night cold and flu": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "colocort": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "codeine/guaifenesin": "2",
 "clobazam": "2",
 "codeine/pseudoephedrine/triprolidine": "2",
 "codeprex": "2",
 "clonazepam": "2",
 "codeine phosphate-promethazine hcl": "2",
 "citric acid/potassium bicarbonate": "3",
 "chemdal expectorant": "2",
 "citric acid/potassium citrate": "3",
 "clindex": "2",
 "capozide": "3",
 "capozide 25/25": "3",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "coricidin night time cold relief": "2",
 "cortef": "2",
 "codeine": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "cardiografin": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "cotab a": "2",
 "celebrex": "2",
 "cialis": "1",
 "cambia": "2",
 "co-trimoxazole": "2"}, "b": {"bellaphen-s": "2",
 "benadryl-d allergy plus sinus": "2",
 "butisol sodium": "2",
 "bitex liquid": "2",
 "brovex cbx": "2",
 "benahist-50": "2",
 "benaphen plus": "2",
 "butorphanol": "2",
 "bayer pm": "2",
 "bactrim": "2",
 "bromodiphenhydramine/codeine": "2",
 "benazepril": "3",
 "buspirone": "2",
 "bel-phen-ergot": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "1",
 "butabarbital": "2",
 "benadryl": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "belladonna/butabarbital": "2",
 "biomox": "1",
 "benadryl allergy plus cold": "2",
 "brovex pb cx": "2",
 "bactrim iv": "2",
 "brovex cb": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "benadryl children's allergy and sinus": "2",
 "bydureon": "2",
 "bethaprim pediatric": "2",
 "benadryl allergy sinus": "2",
 "biotussin dac": "2",
 "butrans": "2",
 "beyaz": "2",
 "budeprion sr": "2",
 "bupivacaine/hydromorphone": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "buspar": "2",
 "benadryl allergy": "2",
 "balacet": "2",
 "bellaspas": "2",
 "benadryl allergy plus sinus headache": "2",
 "betamethasone": "2",
 "bismuth subsalicylate/metronidazole/tetracycline": "1",
 "bethaprim": "2",
 "baycadron": "2",
 "banflex": "2",
 "bellamine": "2",
 "bel-tabs": "2",
 "belix": "2",
 "beldin": "2",
 "benicar": "3",
 "bupropion": "2",
 "benahist-10": "2",
 "buproban": "2",
 "banophen": "2",
 "benylin multi-symptom": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "budeprion": "2",
 "buprenex": "2",
 "benadryl severe allergy &amp; sinus headache": "2",
 "budesonide/formoterol": "2",
 "buffered salt": "3",
 "bromfenac": "2",
 "buprenorphine/naloxone": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "3",
 "bydramine": "2",
 "brompheniramine/diphenhydramine": "2",
 "brompheniramine/codeine": "2",
 "bactrim pediatric": "2",
 "b &amp; o supprettes": "2",
 "beta-phos/ac": "2",
 "brovex pb c": "2",
 "budeprion xl": "2",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "buprenorphine": "2",
 "bellergal-s": "2",
 "banaril": "2",
 "bellalphen": "2",
 "bellamine s": "2",
 "bellatal er": "2",
 "benadryl severe allergy plus sinus headache": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "benazepril/hydrochlorothiazide": "3",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "ben-tann": "2",
 "bactrim ds": "2",
 "brontex": "2",
 "benoject-50": "2",
 "bupivacaine/fentanyl": "2",
 "bextra": "2",
 "baclofen": "2",
 "byetta": "2",
 "budesonide": "2",
 "benicar hct": "3",
 "bellamor": "2",
 "benadryl children's allergy": "2",
 "busodium": "2",
 "belladonna/opium": "2",
 "butibel": "2",
 "barbidonna": "2",
 "benadryl cold": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "bellatal": "2",
 "bubbli-pred": "2",
 "brodspec": "1",
 "brompheniramine/codeine/pseudoephedrine": "2"}, "e": {"eplerenone": "3",
 "escitalopram": "2",
 "eprosartan": "3",
 "endep": "2",
 "emtet-500": "1",
 "effexor xr": "2",
 "endacof-dc": "2",
 "elixiral": "2",
 "enditussin expectorant": "2",
 "effervescent potassium/chloride": "3",
 "etrafon": "2",
 "execlear-c": "2",
 "endacof-dh": "2",
 "edarbyclor": "3",
 "exenatide": "2",
 "eldepryl": "2",
 "ethyl alcohol": "2",
 "entocort ec": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "3",
 "ec-naprosyn": "2",
 "endacof-ac": "2",
 "equanil": "2",
 "endacof-c": "2",
 "edluar": "2",
 "endocodone": "2",
 "endodan": "2",
 "exforge hct": "3",
 "excedrin pm": "2",
 "effexor": "2",
 "eth-oxydose": "2",
 "enalapril/felodipine": "3",
 "esomeprazole/naproxen": "2",
 "endal expectorant": "2",
 "etodolac": "2",
 "equate allergy &amp; sinus headache": "2",
 "eskalith": "3",
 "efasin expectorant sf": "2",
 "exforge": "3",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "eskalith-cr": "3",
 "empirin with codeine": "2",
 "epoprostenol": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "endal cd": "2",
 "ethanol": "2",
 "embeda": "2",
 "effer-k": "3",
 "exalgo": "2",
 "eperbel-s": "2",
 "endotuss expectorant": "2",
 "etrafon forte": "2",
 "ethyol": "2",
 "elavil": "2",
 "endal hd": "2",
 "enalapril": "3",
 "epiklor": "3",
 "equetro": "2",
 "entuss expectorant": "3",
 "equaline acid reducer": "1",
 "emsam": "2",
 "equagesic": "2",
 "ed k+10": "3",
 "ez iii": "2",
 "effervescent potassium": "3",
 "edarbi": "3",
 "eprosartan/hydrochlorothiazide": "3",
 "epitol": "2",
 "endocet": "2"}, "d": {"diovan": "3",
 "duramorph pf": "2",
 "diazepam intensol": "2",
 "diastat": "2",
 "desyrel": "2",
 "duragesic-75": "2",
 "doloral": "2",
 "digitoxin": "2",
 "dizac": "2",
 "diphenydramine quick melt": "2",
 "duramorph": "2",
 "doryx": "1",
 "dep medalone 80": "2",
 "diovan hct": "3",
 "dicopanol": "2",
 "dolsed": "2",
 "dextromethorphan/quinidine": "3",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "dehydrated alcohol": "2",
 "dormin": "2",
 "demi-cof": "2",
 "donatuss dc": "2",
 "diphenhydramine/guaifenesin": "2",
 "donnatal extentabs": "2",
 "diphenhydramine": "2",
 "dihydrocodeine/guaifenesin/phenylephrine": "2",
 "dispermox": "1",
 "depmedalone": "2",
 "dextrose 5% and electrolyte no. 48 injection": "3",
 "doans pm": "2",
 "dazidox": "2",
 "diphenadryl": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "decadron with xylocaine": "2",
 "drospirenone/estradiol": "2",
 "diabetic tussin night time formula": "2",
 "d-tann hc": "2",
 "dph": "2",
 "dexamethasone/lidocaine": "2",
 "dextromethorphan/guaifenesin/potassium guaiacolsulfonate": "3",
 "darvon compound 32": "2",
 "duragesic-50": "2",
 "dalalone la": "2",
 "diatrizoate": "2",
 "dytan-at": "2",
 "dexone": "2",
 "daypro": "2",
 "duohist dh": "2",
 "dihistine dh": "2",
 "duratuss ac 12": "2",
 "diclofenac": "2",
 "dex-tuss": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "2",
 "dihistine": "2",
 "diphenhydramine/phenylephrine": "2",
 "diphenmax": "2",
 "despec-pd": "2",
 "doxepin topical": "2",
 "dexpak taperpak": "2",
 "diphenhydramine/ibuprofen": "2",
 "dexacort phosphate in turbinaire": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "diphen af": "2",
 "dynacin": "1",
 "diphedryl": "2",
 "diphenyl": "2",
 "diltiazem/enalapril": "3",
 "donnapine": "2",
 "doxepin": "2",
 "darcalma": "2",
 "dilaudid-hp": "2",
 "digitek": "1",
 "dilaudid cough syrup": "2",
 "dolobid": "2",
 "duragesic-25": "2",
 "deltasone": "2",
 "di-delamine": "2",
 "dihydro-pe": "2",
 "duragesic": "2",
 "duragesic-100": "2",
 "d-tann": "2",
 "dexacort-la": "2",
 "diphenhydramine/tripelennamine topical": "2",
 "dytan-d": "2",
 "dexamethasone": "2",
 "decohistine dh": "2",
 "diphen": "2",
 "dihydro-cp": "2",
 "doxycycline/omega-3 polyunsaturated fatty acids": "1",
 "dolophine": "2",
 "dilaudid": "2",
 "diphendryl": "2",
 "diphenylin": "2",
 "delsym children's night time cough &amp; cold": "2",
 "diphenmax d": "2",
 "dyrenium": "3",
 "diatrizoate/iodipamide": "2",
 "dalalone dp": "2",
 "deproist with codeine": "2",
 "decohistine expectorant": "2",
 "dexasone": "2",
 "donnatal": "2",
 "duo-vil": "2",
 "doxy-caps": "1",
 "doxycycline": "1",
 "darvon-n": "2",
 "darpaz": "2",
 "doxy-d": "1",
 "dihistine expectorant": "2",
 "doxy 200": "1",
 "delta-cortef": "2",
 "dihydrocodeine/guaifenesin": "2",
 "d-tann at": "2",
 "dristan sinus": "2",
 "dopar": "2",
 "dytan": "2",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "darvon": "2",
 "diastat acudial": "2",
 "droperidol/fentanyl": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "dexasone la": "2",
 "duragal-s": "2",
 "demeclocycline": "1",
 "diabetic tussin c": "2",
 "dyazide": "3",
 "darvon compound-65": "2",
 "diphentann-d": "2",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "desyrel dividose": "2",
 "depo-medrol": "2",
 "dihydro-gp": "2",
 "decadron": "2",
 "dihydrocodeine/guaifenesin/pseudoephedrine": "2",
 "d-tal": "2",
 "de-sone la": "2",
 "duragesic-12": "2",
 "dytan-hc": "2",
 "dexamethasone intensol": "2",
 "dytan-dm": "2",
 "dexacort phosphate in respihaler": "2",
 "dihistine expectorant with codeine": "2",
 "dicomal-ph": "2",
 "deconsal c expectorant": "2",
 "denzapine": "2",
 "depopred": "2",
 "d-tann dm": "2",
 "doxy 100": "1",
 "drospirenone/ethinyl estradiol": "2",
 "duexis": "2",
 "duralone": "2",
 "d-tann cd": "2",
 "diastat pediatric": "2",
 "darvocet-n 100": "2",
 "decadron-la": "2",
 "dytuss": "2",
 "dofetilide": "2",
 "d-tann ct": "2",
 "diphenhist": "2",
 "dextromethorphan/potassium guaiacolsulfonate": "3",
 "diazepam": "2",
 "dexacorten": "2",
 "dexacen-4": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "2",
 "digoxin": "1",
 "doxycycline/salicylic acid topical": "1",
 "darvocet-n 50": "2",
 "dalmane": "2",
 "decaject la": "2",
 "duract": "2",
 "duraganidin nr": "2",
 "doloral sirop": "2",
 "donnaphen": "2",
 "diphen cough": "2",
 "dexone la": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "de-chlor nx": "3",
 "duloxetine": "2",
 "dalalone": "2",
 "diphenhydramine/pseudoephedrine": "2",
 "demerol": "2",
 "dihydrocodeine/phenylephrine": "2",
 "dostinex": "2",
 "dytan-cd": "2",
 "diclofenac/misoprostol": "2",
 "declomycin": "1",
 "desvenlafaxine": "2",
 "disposable enema": "3",
 "dytan-cs": "2",
 "darvocet a500": "2",
 "dextrose 10% and electrolyte no 48": "3",
 "decaject": "2"}, "g": {"genahist": "2",
 "guaifen-c": "2",
 "gen-k": "3",
 "genpril": "2",
 "gablofen": "2",
 "gengraf": "2",
 "guaitussin ac": "2",
 "glucophage xr": "2",
 "guaifen ac": "2",
 "genapap pm": "2",
 "glucophage": "2",
 "glu-k": "3",
 "garlic oil": "1",
 "guiatussin with codeine": "2",
 "guiadex dm": "3",
 "guaifenesin/potassium guaiacolsulfonate": "3",
 "gianvi": "2",
 "glipizide/metformin": "2",
 "guai-co": "2",
 "guiatuss dac": "2",
 "gani-tuss nr": "2",
 "guiatussin dac": "2",
 "gua pc": "2",
 "gestuss-hc": "2",
 "giltuss ped-c": "2",
 "garlic": "1",
 "glydeine": "2",
 "guiatuss ac": "2",
 "guaifenesin dac liquid": "2",
 "geodon": "2",
 "guaifenesin/hydromorphone": "2",
 "gastrografin": "2",
 "glucovance": "2",
 "guaifen dac": "2",
 "guaiatussin ac": "2",
 "guaiatussin dac": "2",
 "glumetza": "2",
 "glyburide/metformin": "2"}, "f": {"flolan": "2",
 "fenoldopam": "2",
 "fentanyl/ropivacaine": "2",
 "fortamet": "2",
 "fiorinal with codeine iii": "2",
 "furazolidone": "2",
 "fleet ez-prep": "3",
 "fazaclo": "2",
 "fiorinal with codeine": "2",
 "florinef acetate": "2",
 "flurazepam": "2",
 "fanapt": "2",
 "fioricet with codeine": "2",
 "fluvoxamine": "2",
 "fentanyl": "2",
 "fosinopril": "3",
 "feldene": "2",
 "florinef": "2",
 "forfivo xl": "2",
 "fiortal with codeine": "2",
 "famotidine/ibuprofen": "2",
 "fentora": "2",
 "flo-pred": "2",
 "fenoprofen": "2",
 "fluoxetine": "2",
 "flexon": "2",
 "fluoxetine/olanzapine": "2",
 "flexoject": "2",
 "fleet prep kit 1": "3",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "flurbiprofen": "2",
 "fludrocortisone": "2",
 "fleet enema extra": "3",
 "floricet with codeine": "2",
 "fluphenazine": "2",
 "fleet phospho soda": "3",
 "fentanyl transdermal system": "2",
 "fleet enema": "3",
 "furoxone": "2",
 "freamine iii with electrolytes": "3",
 "fosinopril/hydrochlorothiazide": "3"}, "i": {"isolyte p and 5% dextrose": "3",
 "iohexol": "2",
 "irbesartan": "3",
 "irinotecan": "2",
 "iopromide": "2",
 "iothalamate": "2",
 "isovue-370": "2",
 "isolyte h and 5 % dextrose": "3",
 "ibuprofen": "2",
 "iophen-c nr": "2",
 "ibuprofen pmr": "2",
 "isolyte m and 5% dextrose": "3",
 "ibuprofen/oxycodone": "2",
 "isovue-300": "2",
 "isovue-m-200": "2",
 "isolyte e": "3",
 "isovue-200": "2",
 "ionosol b and 5% dextrose": "3",
 "imipramine": "2",
 "iloprost": "2",
 "ioxaglate": "2",
 "invega": "2",
 "ibudone": "2",
 "ibuprofen/pseudoephedrine": "2",
 "intermezzo": "2",
 "iopamidol": "2",
 "indocin iv": "2",
 "innovar": "2",
 "iodamide": "2",
 "iopidine": "2",
 "ibu-200": "2",
 "iopamidol-370": "2",
 "inspra": "3",
 "indocin": "2",
 "ioxilan": "2",
 "ionsys": "2",
 "isolyte r and 5% dextrose": "3",
 "iodixanol": "2",
 "isovue-250": "2",
 "infumorph": "2",
 "iloperidone": "2",
 "isocarboxazid": "2",
 "ioversol": "2",
 "indocin sr": "2",
 "iophen": "2",
 "ionosol t and 5% dextrose": "3",
 "invega sustenna": "2",
 "ibu": "2",
 "iodipamide": "2",
 "ibu-tab": "2",
 "ibu-4": "2",
 "ibu-6": "2",
 "ibu-8": "2",
 "ionosol mb and 5% dextrose": "3",
 "isovue-128": "2",
 "indomethacin": "2",
 "isovue-m-300": "2"}, "h": {"hydeltrasol": "2",
 "haloperidol": "2",
 "hydrochlorothiazide/triamterene": "3",
 "halotussin dac": "2",
 "headache formula pm": "2",
 "helidac": "1",
 "hydro-tussin exp": "2",
 "hiprex": "2",
 "hydrocortisone": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hydroxyzine": "2",
 "hypaque": "2",
 "hydromorphone": "2",
 "hydrocortone phosphate": "2",
 "hyzine": "2",
 "hydrochlorothiazide/spironolactone": "3",
 "hyzaar": "3",
 "hydramine compound": "2",
 "hydrochlorothiazide/moexipril": "3",
 "hydro-dp": "2",
 "hydrochlorothiazide/valsartan": "3",
 "hydrochlorothiazide/losartan": "3",
 "halflytely and bisacodyl": "3",
 "hydrostat ir": "2",
 "hyrexin": "2",
 "hyoscyamine/methenamine": "2",
 "hydron kgs": "3",
 "hyosophen": "2",
 "haltran": "2",
 "hydrochlorothiazide/olmesartan": "3",
 "hydrophed": "2",
 "hypaque-76": "2",
 "haldol decanoate": "2",
 "hypaque-m": "2",
 "hydrocodone/potassium guaiacolsulfonate/pseudoephedrine": "3",
 "humibid la": "3",
 "hyophen": "2",
 "hydrochlorothiazide/irbesartan": "3",
 "hypaque meglumine": "2",
 "hydroxy compound": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "halotussin ac": "2",
 "h.p. acthar gel": "2",
 "hexabrix": "2",
 "hydromorph contin": "2",
 "hydrochlorothiazide/lisinopril": "3",
 "hydro-tussin dhc": "2",
 "humibid dm": "3",
 "haponal": "2",
 "hydrochlorothiazide/telmisartan": "3",
 "hydrocortone": "2",
 "hydrocodone/potassium guaiacolsulfonate": "3",
 "hypaque cysto": "2",
 "hypaque sodium": "2",
 "hy-kxp": "3",
 "hydrochlorothiazide/quinapril": "3",
 "hydramine cough syrup": "2",
 "hydramine": "2",
 "hexadrol": "2",
 "hydrocodone/ibuprofen": "2",
 "hyoscyamine/phenobarbital": "2",
 "hydron ex": "3",
 "hydeltra-tba": "2",
 "headache relief pm": "2",
 "haldol": "2"}, "k": {"klotrix": "3",
 "kadian": "2",
 "kaon-ci": "3",
 "k-phos original": "3",
 "kenalog-10": "2",
 "klor-con m10": "3",
 "kgs-pe": "3",
 "klor-con m15": "3",
 "ken-jec 40": "2",
 "k-dur 10": "3",
 "k+care et": "3",
 "k + potassium": "3",
 "kato": "3",
 "kg-fed": "2",
 "klor-con/25": "3",
 "klonopin": "2",
 "key-pred": "2",
 "klor-con": "3",
 "klor-con 8": "3",
 "kaon-cl 10": "3",
 "k-lyte/cl": "3",
 "k-phos m.f.": "3",
 "k-phos no. 2": "3",
 "k-lor": "3",
 "kal potassium 99": "3",
 "k-tab": "3",
 "k-lyte/cl 50": "3",
 "k-effervescent": "3",
 "k-sol": "3",
 "kemstro": "2",
 "klor-con/ef": "3",
 "kay ciel": "3",
 "kenaject-40": "2",
 "kgs-hc": "3",
 "k-8": "3",
 "kaochlor s-f": "3",
 "k-lyte ds": "3",
 "k-lyte": "3",
 "kaon": "3",
 "k-dur": "3",
 "kaochlor": "3",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "k-dur 20": "3",
 "kaon-cl 20%": "3",
 "kg-fed pediatric expectorant": "2",
 "klor-con m20": "3",
 "k-vescent": "3",
 "kcl": "3",
 "klonopin wafer": "2",
 "kombiglyze xr": "2",
 "kg-fed expectorant": "2",
 "ketorolac": "2",
 "k-norm": "3",
 "ketoprofen": "2",
 "k-10": "3",
 "k-lyte/cl 25": "3",
 "klor-con 10": "3",
 "k-phos neutral": "3"}, "j": {"j-max dhc": "2",
 "janumet xr": "2",
 "j-cof dhc": "2",
 "jumex": "2",
 "janumet": "2"}, "m": {"m-end wc": "2",
 "meridia": "2",
 "morphine sulfate er": "2",
 "maxifed cdx": "2",
 "m-oxy": "2",
 "medrol dosepak": "2",
 "micardis hct": "3",
 "metformin/sitagliptin": "2",
 "myelo-kit": "2",
 "motrin sinus headache": "2",
 "mhp-a": "2",
 "myphetane dc": "2",
 "midazolam": "2",
 "magnacet": "2",
 "methacort 40": "2",
 "midol extended relief": "2",
 "m-phen": "2",
 "morphine lp epidural": "2",
 "millipred dp": "2",
 "metformin/pioglitazone": "2",
 "mar-cof bp": "2",
 "methylcotolone": "2",
 "motrin infant drops": "2",
 "monopril": "3",
 "m-clear": "2",
 "miles nervine": "2",
 "methacort 80": "2",
 "md-76 r": "2",
 "medicort": "2",
 "monodox": "1",
 "metformin/rosiglitazone": "2",
 "mytussin ac": "2",
 "midol maximum strength cramp formula": "2",
 "methylcotol": "2",
 "morphine/naltrexone": "2",
 "motrin childrens cold": "2",
 "mitran": "2",
 "midol pm": "2",
 "motrin pm": "2",
 "methylprednisolone": "2",
 "moxatag": "1",
 "ms/s": "2",
 "marplan": "2",
 "millipred": "2",
 "molindone": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "mefenamic acid": "2",
 "msir": "2",
 "micardis": "3",
 "maxifed-g cdx": "2",
 "methenamine/sodium acid phosphate": "2",
 "milnacipran": "2",
 "marcof expectorant": "3",
 "md-gastroview": "2",
 "motrin ib": "2",
 "meperitab": "2",
 "methenamine": "2",
 "midol ib": "2",
 "micro-k 10": "3",
 "meprozine": "2",
 "methadose": "2",
 "minocin": "1",
 "motrin junior strength": "2",
 "methylpred dp": "2",
 "mudrane": "2",
 "mio-rel": "2",
 "meperidine": "2",
 "md-76": "2",
 "morphine sulfate ir": "2",
 "maxifed cd": "2",
 "ms contin": "2",
 "medidex la": "2",
 "mapap pm": "2",
 "mobic": "2",
 "morphine rapi-ject": "2",
 "maxiflu cd": "2",
 "maraviroc": "2",
 "maxiphen cd": "2",
 "metaglip": "2",
 "maxifed-g cd": "2",
 "motrin": "2",
 "micrainin": "2",
 "meclofenamate": "2",
 "meloxicam": "2",
 "metformin/saxagliptin": "2",
 "metformin": "2",
 "methadone diskets": "2",
 "mepergan": "2",
 "msp-blu": "2",
 "medent c": "2",
 "myolin": "2",
 "mintuss nx": "3",
 "matulane": "2",
 "morphitec": "2",
 "m-clear wc": "2",
 "methenamine/sodium biphosphate": "3",
 "motrin ib sinus": "2",
 "maxzide-25": "3",
 "moxilin": "1",
 "maxiflu cdx": "2",
 "methocarbamol": "2",
 "medrol": "2",
 "mandelamine": "2",
 "m-end pe": "2",
 "mirtazapine": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "mellaril-s": "2",
 "mb-tab": "2",
 "methotrimeprazine": "2",
 "maxiphen cdx": "2",
 "medralone": "2",
 "medipred": "2",
 "metformin/repaglinide": "2",
 "m-prednisolone": "2",
 "mudrane gg": "2",
 "medralone 80": "2",
 "meperidine/promethazine": "2",
 "morphine sulfate sr": "2",
 "maxzide": "3",
 "miltown": "2",
 "metrizamide": "2",
 "meticorten": "2",
 "monopril hct": "3",
 "m-eslon": "2",
 "mytussin dac": "2",
 "mavik": "3",
 "methadone": "2",
 "motrin migraine pain": "2",
 "marax df": "2",
 "myrac": "1",
 "mepergan fortis": "2",
 "maprotiline": "2",
 "minocycline": "1",
 "marax": "2",
 "mellaril": "2",
 "motrin childrens": "2",
 "morphine": "2",
 "medidex": "2",
 "moban": "2",
 "menadol": "2",
 "meclomen": "2",
 "methylprednisolone dose pack": "2",
 "moexipril": "3",
 "methdilazine": "2",
 "motrin cold and flu": "2",
 "mesoridazine": "2",
 "micro-k": "3",
 "m o s": "2",
 "meprobamate": "2"}, "l": {"ludiomil": "2",
 "lvp solution with potassium": "3",
 "luminal": "2",
 "lotrel": "3",
 "loxitane c": "2",
 "levrix": "2",
 "larodopa": "2",
 "lexapro": "2",
 "lisinopril": "3",
 "levsin with phenobarbital": "2",
 "lioresal intrathecal": "2",
 "leader naproxen sodium": "2",
 "liquid pred": "2",
 "lithonate": "3",
 "licorice": "2",
 "lorazepam intensol": "2",
 "losartan": "3",
 "lithium": "3",
 "lurasidone": "2",
 "lanoxin": "1",
 "limbitrol": "2",
 "luvox cr": "2",
 "lufyllin-epg": "2",
 "librium": "2",
 "loxitane": "2",
 "lorazepam": "2",
 "lotensin hct": "3",
 "loryna": "2",
 "lazanda": "2",
 "lioresal": "2",
 "linezolid": "2",
 "largon": "2",
 "lodine": "2",
 "limbitrol ds": "2",
 "librax": "2",
 "lansoprazole/naproxen": "2",
 "loxitane im": "2",
 "legatrin pm": "2",
 "lodine xl": "2",
 "lanoxicaps": "1",
 "lithobid": "3",
 "luvox": "2",
 "levocetirizine": "2",
 "lexxel": "3",
 "levodopa": "2",
 "lotensin": "3",
 "lidocaine/oxytetracycline": "1",
 "loxapine": "2",
 "lithotabs": "3",
 "liquihistine cs": "2",
 "lexuss 210 liquid": "2",
 "levoprome": "2",
 "latuda": "2"}, "o": {"onfi": "2",
 "orasone": "2",
 "orphengesic forte": "2",
 "ormazine": "2",
 "oxytetracycline": "1",
 "orphengesic": "2",
 "orudis kt": "2",
 "omnipaque 240 redi-unit": "2",
 "oxycodone": "2",
 "osmoprep": "3",
 "oraxyl": "1",
 "omnipaque 180 redi-unit": "2",
 "optiray 240": "2",
 "orudis": "2",
 "oxyir": "2",
 "optiray 320": "2",
 "oracea": "1",
 "omnipaque 350": "2",
 "optiray 300": "2",
 "oxaprozin": "2",
 "omnipaque 210": "2",
 "omnipaque 140": "2",
 "oxilan": "2",
 "onsolis": "2",
 "oxydose": "2",
 "orapred odt": "2",
 "omnipaque 180": "2",
 "orfro": "2",
 "optiray 160": "2",
 "opium tincture, deodorized": "2",
 "ocella": "2",
 "orphenadrine": "2",
 "oms": "2",
 "ocudox": "1",
 "oruvail": "2",
 "orphenate": "2",
 "orapred": "2",
 "oxyfast": "2",
 "olanzapine": "2",
 "oleptro": "2",
 "opium": "2",
 "olmesartan": "3",
 "oxazepam": "2",
 "oramorph sr": "2",
 "oxycontin": "2",
 "omnipaque flexipak": "2",
 "oxycet": "2",
 "oxytetracycline/phenazopyridine/sulfamethizole": "1",
 "oxecta": "2",
 "optiray 350": "2",
 "olopatadine nasal": "2",
 "opium deodorized": "2",
 "omnipaque 300": "2",
 "omnipaque 240": "2"}, "n": {"nervine": "2",
 "night time pain": "2",
 "naldecon-cx adult": "2",
 "nalex ac": "2",
 "nortriptyline": "2",
 "nalfon": "2",
 "norflex": "2",
 "novadyne expectorant": "2",
 "nytol": "2",
 "naprosyn": "2",
 "naproxen/sumatriptan": "2",
 "notuss-nxd": "2",
 "narvox": "2",
 "notuss-dc": "2",
 "nasotuss": "2",
 "nucodine": "2",
 "notuss-pe": "2",
 "nuedexta": "3",
 "norgesic forte": "2",
 "nexcede": "2",
 "novahistine expectorant": "2",
 "nuprin": "2",
 "norgesic": "2",
 "nardil": "2",
 "novagest with codeine": "2",
 "nu-med": "2",
 "naproxen": "2",
 "nalbuphine": "2",
 "naprelan": "2",
 "nucodine expectorant": "2",
 "nucofed expectorant": "2",
 "nightime sleepaid": "2",
 "neo ac": "2",
 "neoral": "2",
 "novahistine dh": "2",
 "nytol caplet": "2",
 "novadyne dh": "2",
 "navane": "2",
 "nuco-tuss expectorant": "2",
 "nucofed": "2",
 "nucodine pediatric": "2",
 "neutra-phos-k": "3",
 "nuco-tuss pediatric expectorant": "2",
 "norflex injectable": "2",
 "naproxen sodium ds": "2",
 "notuss-ac": "2",
 "neutra-phos": "3",
 "nutridox convenience kit": "1",
 "notuss-nx": "2",
 "normosol-m and 5% dextrose": "3",
 "naloxone/pentazocine": "2",
 "nabumetone": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "nefazodone": "2",
 "nucofed pediatric expectorant": "2",
 "niravam": "2",
 "naproxen/pseudoephedrine": "2",
 "nucochem": "2",
 "neoprofen": "2",
 "nubain": "2"}, "q": {"quenalin": "2",
 "quick-k": "3",
 "quin-release": "3",
 "quinaretic": "3",
 "quinidex extentabs": "3",
 "q-dryl": "2",
 "quinora": "3",
 "quinidine": "3",
 "quinapril": "3",
 "quinaglute dura-tabs": "3",
 "quin-g": "3",
 "quetiapine": "2",
 "q-profen": "2",
 "quadrinal": "2",
 "q-dryl a/f": "2",
 "quadrapax": "2"}, "p": {"pyridium plus": "2",
 "phosphasal": "2",
 "predicort-50": "2",
 "poly-tussin ac": "2",
 "perchloracap": "3",
 "pamprin all day relief": "2",
 "parenteral nutrition solution w/electrolytes": "3",
 "predacort 50": "2",
 "potassium bicarbonate/potassium chloride": "3",
 "pentazocine": "2",
 "phenylephrine/potassium guaiacolsulfonate": "3",
 "prevacid naprapac 375": "2",
 "pyrelle hb": "2",
 "potassium phosphate/sodium phosphate": "3",
 "potassium citrate": "3",
 "pedituss": "2",
 "prevacid naprapac 500": "2",
 "paral": "2",
 "prinzide": "3",
 "phenhist expectorant": "2",
 "prograf": "3",
 "pulmicort nebuamp": "2",
 "predcor": "2",
 "periostat": "1",
 "predacorten": "2",
 "prednisolone": "2",
 "phenylhistine expectorant": "2",
 "phenaphen with codeine": "2",
 "prednicot": "2",
 "pardryl": "2",
 "prolixin": "2",
 "panmycin": "1",
 "propoxyphene compound 65": "2",
 "prevacid naprapac": "2",
 "phospha 250 neutral": "3",
 "phenadoz": "2",
 "phenergan vc": "2",
 "potassium acetate": "3",
 "prelone": "2",
 "procarbazine": "2",
 "proloprim": "2",
 "prochlorperazine": "2",
 "potassium phosphate": "3",
 "polycitra-k": "3",
 "phenylephrine/promethazine": "2",
 "predate-50": "2",
 "promethazine with codeine": "2",
 "pseudodine c": "2",
 "polycitra": "3",
 "phenazine 50": "2",
 "prednicen-m": "2",
 "primsol": "2",
 "permitil": "2",
 "prosed ds": "2",
 "pediacare children's allergy": "2",
 "prolixin enanthate": "2",
 "parnate": "2",
 "paxil": "2",
 "percodan": "2",
 "phosphate laxative": "3",
 "pediacof": "2",
 "paliperidone": "2",
 "pb-hyos": "2",
 "phrenilin with caffeine and codeine": "2",
 "protuss": "3",
 "propiomazine": "2",
 "predicort rp": "2",
 "percogesic extra strength": "2",
 "primethasone": "2",
 "poly hist dhc": "2",
 "polytine cs": "2",
 "percocet 10/325": "2",
 "procof d": "3",
 "poly tussin ex": "2",
 "pc-10": "3",
 "pediatex-ct": "2",
 "promethazine with dm": "2",
 "percodan-demi": "2",
 "promethazine vc with codeine": "2",
 "poly cs": "2",
 "pristiq": "2",
 "potassium bicarbonate/potassium citrate": "3",
 "pedia-lax enema": "3",
 "potassium bicarbonate/sodium bicarbonate": "3",
 "percocet 2.5/325": "2",
 "potassium guaiacolsulfonate": "3",
 "pc-cap": "2",
 "primlev": "2",
 "pediapred": "2",
 "pancof": "2",
 "prolex dm": "3",
 "percolone": "2",
 "phenaz plus": "2",
 "phenelzine": "2",
 "pro-clear": "2",
 "pexeva": "2",
 "pro-med": "2",
 "procalamine": "3",
 "poly-tussin ex syrup": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "paraldehyde": "2",
 "promethazine vc": "2",
 "potassium chloride": "3",
 "pancof-pd": "2",
 "phenylhistine dh expectorant": "2",
 "parcopa": "2",
 "potassium bicarbonate": "3",
 "potassium chloride/sodium chloride": "3",
 "percocet 5/325": "2",
 "prozac weekly": "2",
 "polycitra-lc": "3",
 "phenflu cdx": "2",
 "phosenamine": "2",
 "prozac": "2",
 "prinivil": "3",
 "percocet 10/650": "2",
 "pp-cap": "2",
 "predaject-50": "2",
 "phenazoforte plus": "2",
 "pulmicort turbuhaler": "2",
 "ponstel": "2",
 "piroxicam": "2",
 "prandimet": "2",
 "pain relief pm extra strength": "2",
 "pamelor": "2",
 "pediacare children's allergy &amp; cold": "2",
 "paregoric": "2",
 "perindopril": "3",
 "patanase": "2",
 "pancof exp": "2",
 "percocet 7.5/325": "2",
 "phenobarbital": "2",
 "promazine": "2",
 "predalone 50": "2",
 "potassium acid phosphate": "3",
 "procot": "2",
 "potassium chloride in sodium chloride": "3",
 "percocet": "2",
 "phenylbutazone": "2",
 "potassium acetate/potassium bicarbonate/potassium citrate": "3",
 "promethazine dm": "2",
 "phenergan": "2",
 "phenoject-50": "2",
 "propoxyphene": "2",
 "paroxetine": "2",
 "palladone": "2",
 "pmb": "2",
 "phenergan fortis": "2",
 "phos-nak": "3",
 "panlor dc": "2",
 "pharbedryl": "2",
 "poly-histine cs": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "pain reliever pm": "2",
 "prosed ec": "2",
 "potassium citrate/sodium citrate": "3",
 "perloxx": "2",
 "panlor ss": "2",
 "prudoxin": "2",
 "poly-tussin dhc": "2",
 "promethazine with dextromethorphan": "2",
 "potassium gluconate": "3",
 "pred-ject-50": "2",
 "proleukin": "2",
 "promethazine hcl and codeine phosphate": "2",
 "paxil cr": "2",
 "pro-red ac": "2",
 "phenylhistine dh": "2",
 "prednisone": "2",
 "plasma-lyte 56": "3",
 "promethazine hcl with codeine": "2",
 "prolixin decanoate": "2",
 "protuss-d": "3",
 "phenflu cd": "2",
 "pharbetol pm": "2",
 "pylera": "1",
 "pulmicort flexhaler": "2",
 "prolex dh": "3",
 "percocet 7.5/500": "2",
 "promethazine vc plain": "2",
 "potassium perchlorate": "3",
 "primalev": "2",
 "pri-cortin 50": "2",
 "percogesic original strength": "2",
 "phenergan with dextromethorphan": "2",
 "procof": "3",
 "plasma-lyte and 5% dextrose": "3",
 "prevpac": "1",
 "perphenazine": "2",
 "pulmicort respules": "2",
 "promethegan": "2",
 "poly-citra k crystals": "3",
 "polyhist nc": "2",
 "promethazine vc w/codeine": "2"}, "s": {"sulindac": "2",
 "solurex": "2",
 "sertraline": "2",
 "stalevo 150": "2",
 "sleep": "2",
 "selgene": "2",
 "slow-k": "3",
 "septra": "2",
 "saleto-800": "2",
 "subutex": "2",
 "selegiline": "2",
 "septra iv": "2",
 "snooze fast": "2",
 "sinemet cr": "2",
 "sulfamethoxazole/trimethoprim": "2",
 "sulfatrim": "2",
 "synalgos-dc": "2",
 "sleep tab ii": "2",
 "sonata": "2",
 "subsys": "2",
 "stelazine": "2",
 "sumycin": "1",
 "serentil": "2",
 "sudafed 12 hour pressure+pain": "2",
 "sinemet": "2",
 "selestoject": "2",
 "somnote": "2",
 "saleto-400": "2",
 "siladryl": "2",
 "savella": "2",
 "solodyn": "1",
 "sandimmune": "2",
 "soma": "2",
 "suttar-2": "2",
 "solu-cortef": "2",
 "selfemra": "2",
 "samsca": "2",
 "serzone": "2",
 "suttar sf": "2",
 "sleepinal": "2",
 "safyral": "2",
 "sominex pain relief formula": "2",
 "suprep": "2",
 "seconal sodium": "2",
 "sleep-ettes": "2",
 "sibutramine": "2",
 "sudafed pe severe cold": "2",
 "stalevo 75": "2",
 "saleto-600": "2",
 "sublimaze": "2",
 "symbicort": "2",
 "skelex": "2",
 "sominex maximum strength caplet": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "somnicaps": "2",
 "siladryl das": "2",
 "stalevo 200": "2",
 "sprix": "2",
 "sudafed sinus nighttime plus pain": "2",
 "selzentry": "2",
 "sominex": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "saleto-200": "2",
 "sarafem": "2",
 "sparine": "2",
 "septra ds": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "sleep-ettes d": "2",
 "spastrin": "2",
 "soma compound with codeine": "2",
 "simply sleep": "2",
 "scot-tussin allergy": "2",
 "surmontil": "2",
 "stalevo 100": "2",
 "solurex la": "2",
 "soma compound": "2",
 "suprep bowel prep kit": "2",
 "syeda": "2",
 "serax": "2",
 "siladryl allergy": "2",
 "sleep tabs": "2",
 "smz-tmp ds": "2",
 "spironolactone": "3",
 "sinografin": "2",
 "sterapred": "2",
 "sleepwell 2-nite": "2",
 "solu-medrol": "2",
 "sleep-eze-3": "2",
 "sine-aid ib": "2",
 "seconal": "2",
 "sudafed pe nighttime cold": "2",
 "statex": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "sumycin 250": "1",
 "saphris": "2",
 "spasmolin": "2",
 "silphen cough": "2",
 "sinequan": "2",
 "suboxone": "2",
 "symbyax": "2",
 "spasquid": "2",
 "stalevo 50": "2",
 "stalevo 125": "2",
 "stalevo": "2",
 "servira": "2",
 "sterapred ds": "2",
 "silenor": "2",
 "siladyl sa": "2",
 "statuss": "2",
 "sulfatrim pediatric": "2",
 "stadol": "2",
 "seconal sodium pulvules": "2"}, "r": {"renografin-76": "2",
 "rms": "2",
 "robitet 500": "1",
 "roxicodone": "2",
 "remeron": "2",
 "risperdal m-tab": "2",
 "rolatuss": "2",
 "robitussin-ac": "2",
 "reno-30": "2",
 "ryna-cx": "2",
 "ramipril": "3",
 "rum-k": "3",
 "robitussin-dac": "2",
 "robitussin night time cough, cold &amp; flu": "2",
 "roxanol 100": "2",
 "reno-m-30": "2",
 "romilar ac": "2",
 "reno-dip": "2",
 "remeron soltab": "2",
 "rufen": "2",
 "rofecoxib": "2",
 "roxanol-t": "2",
 "robaxisal": "2",
 "reprexain": "2",
 "rescudose": "2",
 "renovist ii": "2",
 "robafen ac": "2",
 "risperdal consta": "2",
 "reno-60": "2",
 "renovist": "2",
 "roxiprin": "2",
 "robitussin night time cough &amp; cold": "2",
 "renografin-60": "2",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "risperidone": "2",
 "roxilox": "2",
 "ryna-c": "2",
 "roxicet": "2",
 "respa c&amp;c": "2",
 "robichem ac": "2",
 "reno-m-60": "2",
 "rindal hpd": "2",
 "restoril": "2",
 "renovue-65": "2",
 "rasagiline": "2",
 "relafen": "2",
 "reno-m-dip": "2",
 "remodulin": "2",
 "relcof c": "2",
 "risperdal": "2",
 "robaxin": "2",
 "renovue-dip": "2",
 "robaxin-750": "2",
 "riomet": "2",
 "rapiflux": "2",
 "respa sa": "2",
 "renocal-76": "2",
 "re-pb hyos elixir": "2",
 "roxanol": "2",
 "roxicodone intensol": "2"}, "u": {"uretron": "2",
 "ultravist": "2",
 "urimax": "2",
 "urocit-k": "3",
 "utrona-c": "2",
 "uroplus": "2",
 "uprima": "2",
 "urised": "2",
 "uro blue": "2",
 "uritact ds": "2",
 "unisom sleepmelts": "2",
 "uroplus ds": "2",
 "uni-tann": "2",
 "urimar-t": "2",
 "uretron ds": "2",
 "utira": "2",
 "univasc": "3",
 "uroqid-acid no2": "2",
 "up and up all day allergy relief d": "2",
 "utrona": "2",
 "urobiotic-250": "1",
 "urografin 325": "2",
 "utac": "2",
 "u-tri-lone": "2",
 "urapine": "2",
 "uritin": "2",
 "urelief plus": "2",
 "uni-tann cs": "2",
 "usept": "2",
 "uni-cof expectorant": "2",
 "urex": "2",
 "urisedamine": "2",
 "urisym": "2",
 "urovison": "2",
 "urogesic blue": "3",
 "uta": "2",
 "uracil": "1",
 "uritact-ec": "2",
 "uticap": "2",
 "unisom with pain relief": "2",
 "urografin 150": "2",
 "uni-cof": "2",
 "urografin 370": "2",
 "ustell": "2",
 "uni-tann d": "2",
 "urelle": "2",
 "uro-kp-neutral": "3",
 "unisom sleepgels": "2",
 "utira-c": "2",
 "uro-phosphate": "3",
 "uribel": "2",
 "uniretic": "3"}, "t": {"terramycin": "1",
 "telmisartan": "3",
 "tizanidine": "3",
 "tyvaso": "2",
 "tekral": "2",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "theomax df": "2",
 "tekamlo": "2",
 "tolectin 600": "2",
 "thermotabs": "3",
 "tetracap": "1",
 "talwin nx": "2",
 "travert 10% and electrolyte no2": "3",
 "tylenol with codeine #2": "2",
 "tri-k": "3",
 "tranylcypromine": "2",
 "trimethoprim": "2",
 "tramacort-d": "2",
 "tija": "1",
 "thiethylperazine": "2",
 "terramycin im": "1",
 "t- koff": "2",
 "tussirex sugar free": "2",
 "tranquil nighttime sleep aid": "2",
 "teveten hct": "3",
 "temaril": "2",
 "treprostinil": "2",
 "talacen": "2",
 "tegretol": "2",
 "trihist-cs": "2",
 "tolectin ds": "2",
 "tetracon": "1",
 "tranxene": "2",
 "tylenol with codeine": "2",
 "tranxene sd": "2",
 "trandolapril/verapamil": "3",
 "tridal": "2",
 "tetrabenazine": "2",
 "tussi-organidin nr": "2",
 "trilog": "2",
 "toradol": "2",
 "trimox": "1",
 "triaminic night time cold &amp; cough": "2",
 "twilite": "2",
 "tolectin": "2",
 "thioridazine": "2",
 "trifluoperazine": "2",
 "teveten": "3",
 "twynsta": "3",
 "tylenol pm": "2",
 "talwin": "2",
 "tussar sf": "2",
 "toradol iv/im": "2",
 "travasol with electrolytes dual chamber": "3",
 "tussirex": "2",
 "triaminic thin strips allergy": "2",
 "trimipramine": "2",
 "tolmetin": "2",
 "theodrine": "2",
 "torecan": "2",
 "tofranil-pm": "2",
 "travert 5% and electrolyte no2": "3",
 "tylox": "2",
 "total allergy": "2",
 "twin-k": "3",
 "tylenol allergy complete nighttime": "2",
 "tl-hist cd": "2",
 "temazepam": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "thorazine": "2",
 "tricitrates": "3",
 "thiothixene": "2",
 "trycet": "2",
 "theraflu warming relief sinus &amp; cold": "2",
 "tristoject": "2",
 "trazodone": "2",
 "tl-hist cm": "2",
 "trandolapril": "3",
 "tranxene t-tab": "2",
 "triflupromazine": "2",
 "triavil": "2",
 "theraflu thin strips multi symptom": "2",
 "tolvaptan": "2",
 "ten-k": "3",
 "tekturna hct": "2",
 "tac 3": "2",
 "tagamet": "1",
 "trimeprazine": "2",
 "tuinal": "2",
 "trac tabs 2x": "2",
 "triamterene": "3",
 "tedrigen": "2",
 "tylenol with codeine #3": "2",
 "tylenol with codeine #4": "2",
 "tavist nighttime allergy": "2",
 "talwin compound": "2",
 "triam-forte": "2",
 "triamcot": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "triam-a": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "tegretol xr": "2",
 "travasol with electrolytes": "3",
 "tikosyn": "2",
 "triamonide 40": "2",
 "tofranil": "2",
 "triafed &amp; codeine": "2",
 "tarka": "3",
 "trimpex": "2",
 "tylenol sore throat nighttime": "2",
 "trifed c": "2",
 "trezix": "2",
 "tadalafil": "1",
 "tussi-organidin-s nr": "2",
 "triamcinolone": "2",
 "trilafon": "2",
 "tussar-2": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "trilone": "2",
 "tricof": "2",
 "tylenol severe allergy": "2",
 "tussinate": "2",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tusstat": "2",
 "tribenzor": "3",
 "toradol im": "2",
 "tetracycline": "1",
 "triacin c": "2",
 "teczem": "3",
 "tagamet hb": "1",
 "treximet": "2",
 "tussiden c": "2",
 "tusso-c": "2",
 "trux-adryl": "2",
 "tacaryl": "2",
 "tusscough dhc": "2",
 "tacrolimus": "3",
 "triaminic thin strips cough &amp; runny nose": "2",
 "tekturna": "2",
 "tylenol allergy multi-symptom nighttime": "2"}, "w": {"wellbutrin xl": "2",
 "welltuss exp": "2",
 "wygesic": "2",
 "wymox": "1",
 "wal-nadol pm extra strength": "2",
 "wal-zyr d": "2",
 "wellbutrin sr": "2",
 "wellbutrin": "2"}, "v": {"versed": "2",
 "vistazine": "2",
 "vioxx": "2",
 "valsartan": "3",
 "vistaril": "2",
 "visipaque": "2",
 "vibra-tabs": "1",
 "vanspar": "2",
 "v-gan-50": "2",
 "vasotec": "3",
 "vilazodone": "2",
 "vimovo": "2",
 "voltaren": "2",
 "valdecoxib": "2",
 "vestura": "2",
 "valu-dryl": "2",
 "vanatrip": "2",
 "vicoprofen": "2",
 "voltaren-xr": "2",
 "vopac": "2",
 "vibramycin": "1",
 "visicol": "3",
 "veletri": "2",
 "v-gan-25": "2",
 "venlafaxine": "2",
 "viibryd": "2",
 "visqid aa": "2",
 "valium": "2",
 "vanadom": "2",
 "veripred 20": "2",
 "vis-phos n": "3",
 "ventavis": "2",
 "vaseretic": "3",
 "valturna": "3",
 "valrelease": "2",
 "vanacof cd": "2",
 "vaseretic 10-25": "3",
 "vaseretic 5-12.5": "3"}, "y": {"yodefan-nf": "3",
 "yasmin": "2",
 "yaz": "2"}, "x": {"xolox": "2",
 "xyzal": "2",
 "xanax xr": "2",
 "xenazine": "2",
 "xanax": "2"}, "z": {"zyrtec-d": "2",
 "z-tuss ac": "2",
 "zodryl ac": "2",
 "zarah": "2",
 "zyvox": "2",
 "zema pak": "2",
 "zyrtec hives": "2",
 "zyrtec-d 12 hour": "2",
 "zonalon": "2",
 "zolpidem": "2",
 "ziprasidone": "2",
 "zyprexa intramuscular": "2",
 "zestoretic": "3",
 "zerlor": "2",
 "zipsor": "2",
 "zodryl dac": "2",
 "zodryl dec": "2",
 "zolpimist": "2",
 "zaleplon": "2",
 "zyban": "2",
 "zaponex": "2",
 "zelapar": "2",
 "zanaflex": "3",
 "zyrtec": "2",
 "zotex-c": "2",
 "zoloft": "2",
 "zyprexa zydis": "2",
 "zestril": "3",
 "zyprexa relprevv": "2",
 "zetran": "2",
 "zyprexa": "2"}}];