interactions["aminophylline,truphylline"]=["aminophylline,truphylline", {"a": {"azithromycin dose pack": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "actimmune": "2",
 "adoxa ck": "2",
 "aristocort": "2",
 "ammonium chloride/chlorpheniramine/dextromethorphan/ephedrine/ipecac/phenylephrine": "1",
 "antispas": "2",
 "amethia": "2",
 "adlone-40": "2",
 "actidose-aqua": "2",
 "amytal sodium": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "activated charcoal": "2",
 "ami-rax": "1",
 "alyacen 7/7/7": "2",
 "alodox": "2",
 "aranelle": "2",
 "adoxa tt": "2",
 "alesse-21": "2",
 "alesse-28": "2",
 "a-hydrocort": "2",
 "acetaminophen/butalbital": "2",
 "albuterol/ipratropium": "2",
 "aerodiol": "2",
 "avonex prefilled syringe": "2",
 "aristopak": "2",
 "acebutolol": "3",
 "achromycin v": "2",
 "armour thyroid": "2",
 "adrenocot": "2",
 "alprazolam": "1",
 "amethyst": "2",
 "atenolol": "3",
 "anturane": "1",
 "axocet": "2",
 "advair diskus": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "accuneb": "2",
 "arformoterol": "2",
 "albuterol": "2",
 "anoquan": "2",
 "afeditab cr": "1",
 "aloprim": "1",
 "arcet": "2",
 "a-methapred": "2",
 "acetocot": "2",
 "arcapta": "2",
 "aggrenox": "2",
 "alkabel-sr": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "actidose with sorbitol": "2",
 "amobarbital": "2",
 "alagesic": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "alferon n": "2",
 "advair hfa": "2",
 "aristocort for injection": "2",
 "allopurinol": "1",
 "aspirin/butalbital/caffeine": "2",
 "adenocard": "2",
 "anectine": "2",
 "accolate": "2",
 "amitriptyline/chlordiazepoxide": "1",
 "ala-tet": "2",
 "alprazolam intensol": "1",
 "acid controller complete dual action": "2",
 "amobarbital/secobarbital": "2",
 "angeliq": "2",
 "adgyn estro": "2",
 "anectine flo-pack": "2",
 "alyacen 1/35": "2",
 "ak-beta": "3",
 "adalat": "1",
 "altavera": "2",
 "antispasmodic": "2",
 "actidose-aqua advance": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "antrocol": "2",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "arduan": "2",
 "aminoglutethimide": "2",
 "adalat cc": "1",
 "actidose plus sorbitol": "2",
 "activella": "2",
 "avonex": "2",
 "adlone-80": "2",
 "azithromycin/trovafloxacin": "2",
 "atropine/phenobarbital": "2",
 "aristospan": "2",
 "avidoxy dk": "2",
 "aplenzin": "3",
 "aspirin/dipyridamole": "2",
 "acyclovir": "1",
 "azurette": "2",
 "azmacort": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "agriflu": "1",
 "adbeon": "2",
 "axid ar": "2",
 "avidoxy": "2",
 "actisite": "2",
 "adenosine": "2",
 "azithromycin": "2",
 "atenolol/chlorthalidone": "3",
 "asthmacon": "2",
 "axid": "2",
 "apri": "2",
 "active carbon": "2",
 "alagesic lq": "2",
 "adrenocot la": "2",
 "anhydrous calcium iodide/isoproterenol": "2",
 "alesse": "2",
 "afluria": "1",
 "alora": "2",
 "adeno-jec": "2",
 "adenoscan": "2",
 "acetaminophen/tramadol": "3",
 "acid reducer + antacid dual action": "2",
 "acid controller original strength": "2",
 "aspirin/butalbital": "2",
 "amethia lo": "2",
 "ativan": "1",
 "airet": "2",
 "amiodarone": "2",
 "antabuse": "2",
 "adoxa": "2",
 "atracurium": "2",
 "alupent": "2",
 "aygestin": "2",
 "axid pulvules": "2",
 "americet": "2",
 "aviane": "2",
 "anolor 300": "2"}, "c": {"cartia xt": "2",
 "cerebyx": "2",
 "carbosorb x": "2",
 "cellcept": "1",
 "combigan": "3",
 "charcoaid 2000": "2",
 "chem mart nasal decongestant capsule": "2",
 "cipro i.v.": "3",
 "charcoal/simethicone": "2",
 "charcoaid-g": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "cardizem cd": "2",
 "cinobac": "2",
 "cortisone": "2",
 "cryselle": "2",
 "corzide 40/5": "3",
 "cardizem sr": "2",
 "cyclafem 1/35": "2",
 "charcotabs": "2",
 "cort-k": "2",
 "coreg cr": "3",
 "celestone phosphate": "2",
 "corgard": "3",
 "cinoxacin": "2",
 "calan sr": "2",
 "climodien": "2",
 "cortenema": "2",
 "climara": "2",
 "cytadren": "2",
 "cardizem": "2",
 "combivent": "2",
 "charcoaid": "2",
 "cipro": "3",
 "corzide": "3",
 "cardizem la": "2",
 "carteolol ophthalmic": "3",
 "celestone": "2",
 "careone acid reducer": "2",
 "char-flo with sorbitol": "2",
 "charcotrace": "2",
 "chlordinium": "1",
 "cilastatin/imipenem": "2",
 "chlordiazepoxide/clidinium": "1",
 "cortifoam": "2",
 "carbetapentane/chlorpheniramine/ephedrine/phenylephrine": "1",
 "camila": "2",
 "clarithromycin": "2",
 "cyclessa": "2",
 "cipro xr": "3",
 "clorazepate": "1",
 "capacet": "2",
 "charcocaps": "2",
 "cell-u-jec": "2",
 "cafatine pb": "2",
 "combipatch": "2",
 "chlordiazepoxide": "1",
 "cipro cystitis pack": "3",
 "chlordiazepoxide/methscopolamine": "1",
 "cortrosyn": "2",
 "cyclafem 7/7/7": "2",
 "climara pro": "2",
 "cosopt": "3",
 "colesevelam": "2",
 "cordarone": "2",
 "cognex": "2",
 "cisatracurium": "2",
 "cordarone iv": "2",
 "ciprofloxacin": "3",
 "cortone acetate": "2",
 "cardizem monovial": "2",
 "charcoal": "2",
 "carteolol": "3",
 "carbomix": "2",
 "clinalog": "2",
 "carbamazepine": "2",
 "clinacort": "2",
 "carvedilol": "3",
 "cosyntropin": "2",
 "cesia": "2",
 "combivent respimat": "2",
 "clinagen la 40": "2",
 "cartrol": "3",
 "caziant": "2",
 "cotolone": "2",
 "charcodote": "2",
 "celestone soluspan": "2",
 "charcoal/sorbitol": "2",
 "cephadyn": "2",
 "carbatrol": "2",
 "climaval": "2",
 "cimetidine": "2",
 "calan": "2",
 "chlorpheniramine/ephedrine/guaifenesin": "1",
 "colocort": "2",
 "covera-hs": "2",
 "camreselo": "2",
 "clobazam": "1",
 "charcoal plus ds": "2",
 "clonazepam": "1",
 "corzide 80/5": "3",
 "cytomel": "2",
 "chardonna-2": "2",
 "camrese": "2",
 "clindex": "1",
 "cosopt pf": "3",
 "cortef": "2",
 "coreg": "3",
 "conzip": "3"}, "b": {"budeprion sr": "3",
 "bellaphen-s": "2",
 "bellatal er": "2",
 "blocadren": "3",
 "belladonna/ergotamine/phenobarbital": "2",
 "buproban": "3",
 "beta-phos/ac": "2",
 "balziva": "2",
 "brethaire": "2",
 "betaxolol": "3",
 "bronkaid": "1",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "bricanyl": "2",
 "betapace af": "3",
 "betoptic": "3",
 "betagan c-cap": "3",
 "broncholate": "1",
 "biaxin": "2",
 "brevibloc": "3",
 "belcomp-pb": "2",
 "bronkometer": "2",
 "biaxin xl": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "broncho-dilate": "1",
 "brethine": "2",
 "betaxon": "3",
 "bubbli-pred": "2",
 "beyaz": "2",
 "betoptic s": "3",
 "butabarbital": "2",
 "betimol": "3",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "berkley and jensen acid controller maximum strength": "2",
 "brovana": "2",
 "butalbital compound": "2",
 "betaseron": "2",
 "bitolterol": "2",
 "budesonide/formoterol": "2",
 "bicarsim": "2",
 "bystolic": "3",
 "betagan": "3",
 "bisoprolol": "3",
 "butibel": "2",
 "budesonide": "2",
 "bellamor": "2",
 "bellaspas": "2",
 "budeprion xl": "3",
 "budeprion": "3",
 "bedol": "2",
 "butex forte": "2",
 "bronkosol": "2",
 "betamethasone": "2",
 "busodium": "2",
 "bel-phen-ergot": "2",
 "brimonidine/timolol ophthalmic": "3",
 "bronkotuss": "1",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "brevital sodium": "2",
 "barbidonna": "2",
 "betaxolol ophthalmic": "3",
 "bisoprolol/hydrochlorothiazide": "3",
 "bicarsim forte": "2",
 "baycadron": "2",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine": "2",
 "berkley and jensen acid reducer maximum strength": "2",
 "bellatal": "2",
 "butalbital": "2",
 "belladonna/butabarbital": "2",
 "bel-tabs": "2",
 "broncholate syrup": "1",
 "bucet": "2",
 "bellamine s": "2",
 "briellyn": "2",
 "bilberry/evening primrose/flax": "1",
 "butisol sodium": "2",
 "bio-throid": "2",
 "brodspec": "2",
 "bendroflumethiazide/nadolol": "3",
 "bupropion": "3",
 "bupap": "2",
 "brevicon": "2",
 "betapace": "3"}, "e": {"emtet-500": "2",
 "estragyn la 5": "2",
 "estrace": "2",
 "ephedrine/guaifenesin/theophylline": "1",
 "estraderm": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enpresse": "2",
 "e.e.s.-400": "2",
 "estrapatch": "2",
 "evamist": "2",
 "eryped": "2",
 "erythromycin/sulfisoxazole": "2",
 "estreva": "2",
 "ethinyl estradiol/etonogestrel": "2",
 "estradiol patch": "2",
 "elestrin": "2",
 "ethinyl estradiol/levonorgestrel": "2",
 "eutroxsig": "2",
 "erythrocot": "2",
 "ergocomp-pb": "2",
 "estro-la": "2",
 "erythromycin": "2",
 "esgic": "2",
 "etonogestrel": "2",
 "estradot": "2",
 "ethinyl estradiol": "2",
 "elixiral": "2",
 "ethinyl estradiol/ethynodiol": "2",
 "estinyl": "2",
 "ethmozine": "1",
 "estradot 100": "2",
 "estro-cyp": "2",
 "estradiol": "2",
 "enalapril/felodipine": "1",
 "ethinyl estradiol/norgestrel": "2",
 "esmolol": "3",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ethinyl estradiol/norethindrone": "2",
 "equaline heartburn relief": "2",
 "ephedrine/hydroxyzine/theophylline": "1",
 "evorel": "2",
 "e s p": "2",
 "e.e.s.-200": "2",
 "e-caff p-b": "2",
 "equetro": "2",
 "estrogen patches": "2",
 "equaline acid reducer": "2",
 "endolor": "2",
 "epitol": "2",
 "ergocaf-pb": "2",
 "estradot 50": "2",
 "estrasorb": "2",
 "esclim": "2",
 "estrofem": "2",
 "estra-v 40": "2",
 "ephedrine nasal": "1",
 "exjade": "3",
 "erythrocin lactobionate": "2",
 "e.e.s.-400 filmtab": "2",
 "entocort ec": "2",
 "estradiol g gam": "2",
 "e-mycin": "2",
 "ethinyl estradiol/norgestimate": "2",
 "estradot 37.5": "2",
 "eskalith": "2",
 "e.e.s. granules": "2",
 "ezchar": "2",
 "ephedrine/potassium iodide": "1",
 "eryzole": "2",
 "euthyrox": "2",
 "ephedrine": "1",
 "estrostep fe": "2",
 "estazolam": "1",
 "estradot 75": "2",
 "ethotoin": "2",
 "estradiol/norethindrone": "2",
 "estra-testrin": "2",
 "ery-tab": "2",
 "estrogel": "2",
 "enoxacin": "3",
 "ephedrine/guaifenesin": "1",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "estradiol/levonorgestrel": "2",
 "elleste solo": "2",
 "esgic-plus": "2",
 "eltroxin": "2",
 "ethinyl estradiol/norelgestromin": "2",
 "estradiol/medroxyprogesterone": "2",
 "eryc": "2",
 "eperbel-s": "2",
 "evotrox": "2",
 "extavia": "2",
 "erythrocin": "2",
 "estradiol/testosterone": "2",
 "erythrocin stearate filmtab": "2",
 "evening primrose oil": "1",
 "emoquette": "2",
 "eskalith-cr": "2",
 "errin": "2",
 "ezol": "2",
 "estro-span 40": "2",
 "estra-c": "2",
 "ergocaffpb": "2",
 "estradiol/norgestimate": "2",
 "evening primrose": "1",
 "eucarbon": "2"}, "d": {"dynacin": "2",
 "depoject-80": "2",
 "diastat": "1",
 "dutoprol": "3",
 "delidose": "2",
 "doral": "1",
 "dizac": "1",
 "depotestogen": "2",
 "dep medalone 80": "2",
 "diltiazem hydrochloride cd": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "demulen 1/50": "2",
 "donnatal extentabs": "2",
 "desogestrel/ethinyl estradiol": "2",
 "delatestadiol": "2",
 "dolgic plus": "2",
 "diltiazem hydrochloride sr": "2",
 "duoneb": "2",
 "dienogest/estradiol": "2",
 "diltzac": "2",
 "depmedalone": "2",
 "dep androgyn": "2",
 "daliresp": "1",
 "decadron with xylocaine": "2",
 "dolgic": "2",
 "doryx": "2",
 "dexamethasone/lidocaine": "2",
 "dolmar": "2",
 "dalalone la": "2",
 "dipyridamole": "2",
 "depogen": "2",
 "dynabac": "1",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "desogen": "2",
 "dasetta 1/35": "2",
 "dexpak taperpak": "2",
 "dexacort phosphate in turbinaire": "2",
 "duo-medihaler": "2",
 "dura-estrin": "2",
 "dura-dumone": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "diltiazem hydrochloride xt": "2",
 "drospirenone/estradiol": "2",
 "diltiazem hydrochloride xr": "2",
 "diaqua-2": "1",
 "diltiazem": "2",
 "dynabac d5-pak": "1",
 "duralone": "2",
 "dexacort-la": "2",
 "dioval 40": "2",
 "dexamethasone": "2",
 "dilacor xr": "2",
 "doxycycline/omega-3 polyunsaturated fatty acids": "2",
 "doxy 100": "2",
 "deprizine": "2",
 "dioval xx": "2",
 "dalalone dp": "2",
 "dexasone": "2",
 "donnatal": "2",
 "dual action complete": "2",
 "deferasirox": "3",
 "doxy-caps": "2",
 "doxycycline": "2",
 "dexone": "2",
 "doxy-d": "2",
 "dermestril": "2",
 "doxy 200": "2",
 "delta-cortef": "2",
 "demulen": "2",
 "diastat acudial": "1",
 "divigel": "2",
 "diltia xt": "2",
 "dexasone la": "2",
 "duragal-s": "2",
 "demeclocycline": "2",
 "duratestrin": "2",
 "diazepam intensol": "1",
 "decadron phosphate, injectable": "2",
 "depo-medrol": "2",
 "decadron": "2",
 "dulera": "2",
 "dirithromycin": "1",
 "d-tal": "2",
 "de-sone la": "2",
 "duo-cyp": "2",
 "dep gynogen": "2",
 "dexacort phosphate in respihaler": "2",
 "dasetta": "2",
 "depopred": "2",
 "dorzolamide/timolol ophthalmic": "3",
 "duragen": "2",
 "drospirenone/ethinyl estradiol": "2",
 "duexis": "2",
 "dexamethasone intensol": "2",
 "diastat pediatric": "1",
 "doxacurium": "2",
 "decadron-la": "2",
 "diazepam": "1",
 "delestrogen": "2",
 "dilantin": "2",
 "dermestril septem": "2",
 "dexacen-4": "2",
 "doxycycline/salicylic acid topical": "2",
 "demulen 1/35": "2",
 "dalmane": "1",
 "decaject la": "2",
 "depo-testadiol": "2",
 "diprivan": "1",
 "dolgic lq": "2",
 "donnaphen": "2",
 "dexone la": "2",
 "disulfiram": "2",
 "dalalone": "2",
 "dexacorten": "2",
 "dasetta 7/7/7": "2",
 "depo-estradiol": "2",
 "declomycin": "2",
 "disposable enema": "3",
 "dilt-xr": "2",
 "decaject": "2"}, "g": {"gianvi": "2",
 "gynogen la 20": "2",
 "generess fe": "2",
 "gynodiol": "2",
 "genrx tramadol": "3",
 "genora 1/35": "2",
 "genora 1/50": "2",
 "gildess fe 1.5/30": "2",
 "gildess fe 1/20": "2",
 "ginkgo": "2",
 "ginkgo biloba": "2",
 "grepafloxacin": "2",
 "geone": "2",
 "g-1": "2",
 "genora 0.5/35": "2"}, "f": {"femtran": "2",
 "fluxid": "2",
 "fiortal": "2",
 "femsept": "2",
 "fluvirin": "1",
 "fluzone intradermal": "1",
 "fiorinal with codeine iii": "2",
 "fioricet with codeine": "2",
 "femseven sequi phase i": "2",
 "formoterol": "2",
 "flatulex": "2",
 "fluphenazine": "2",
 "famotidine": "2",
 "fleet ez-prep": "3",
 "fiorinal with codeine": "2",
 "fleet phospho soda": "3",
 "fortabs": "2",
 "fluogen": "1",
 "florinef acetate": "2",
 "flurazepam": "1",
 "fiorinal": "2",
 "febuxostat": "2",
 "fluvoxamine": "2",
 "femseven": "2",
 "fosphenytoin": "2",
 "fluzone": "1",
 "femcet": "2",
 "florinef": "2",
 "farbital": "2",
 "femhrt": "2",
 "felodipine": "1",
 "flulaval": "1",
 "forfivo xl": "3",
 "fematrix": "2",
 "fiortal with codeine": "2",
 "famotidine/ibuprofen": "2",
 "femring": "2",
 "fluzone high-dose": "1",
 "flo-pred": "2",
 "flushield": "1",
 "formoterol/mometasone": "2",
 "fleet prep kit 1": "3",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "fludrocortisone": "2",
 "fempatch": "2",
 "fleet enema extra": "3",
 "fluarix": "1",
 "fleet enema": "3",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiormor": "2",
 "floxin": "2",
 "femtab": "2",
 "furosemide": "1",
 "fluothane": "3",
 "fluticasone/salmeterol": "2",
 "femtrace": "2",
 "floxin iv": "2",
 "foradil aerolizer": "2",
 "femcon fe": "2",
 "fiorpap": "2"}, "i": {"interferon alfacon-1": "2",
 "insta-char": "2",
 "intron a": "2",
 "iohexol": "3",
 "innopran xl": "3",
 "isuprel": "2",
 "insta-char with sorbitol": "2",
 "istalol": "3",
 "isuprel mistometer": "2",
 "implanon": "2",
 "isocet": "2",
 "interferon alfa-n3": "2",
 "interferon alfa-n1": "2",
 "inderal la": "3",
 "isoniazid": "2",
 "isovue-m-200": "3",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isovue-300": "3",
 "isuprel hcl": "2",
 "inderide la": "3",
 "isoptin": "2",
 "isovue-200": "3",
 "isoetharine": "2",
 "inderide": "3",
 "infergen": "2",
 "ilosone": "2",
 "isoniazid/rifampin": "2",
 "influenza virus vaccine, inactivated": "1",
 "indacaterol": "2",
 "isoproterenol": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "iopamidol-370": "3",
 "ide-cet": "2",
 "isonarif": "2",
 "interferon alfa-2b": "2",
 "interferon alfa-2a": "2",
 "interferon gamma-1b": "2",
 "isoptin sr": "2",
 "inderal": "3",
 "isovue-250": "3",
 "isovue-370": "3",
 "introvale": "2",
 "isoptin iv": "2",
 "idenal": "2",
 "interferon alfa-2b/ribavirin": "2",
 "iopamidol": "3",
 "isovue-128": "3",
 "isoproterenol/phenylephrine": "2",
 "isovue-m-300": "3"}, "h": {"hydeltrasol": "2",
 "helidac": "2",
 "hydrocortisone": "2",
 "hydrocortone phosphate": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "halcion": "1",
 "heather": "2",
 "healthstream activated charcoal": "2",
 "hydrochlorothiazide/metoprolol": "3",
 "hyosophen": "2",
 "hydrophed": "1",
 "hydrochlorothiazide/propranolol": "3",
 "hydeltra-tba": "2",
 "hydroxy compound": "1",
 "halothane": "3",
 "hydroxypropyl chitosan/terbinafine topical": "2",
 "hydrochlorothiazide/timolol": "3",
 "heartburn relief": "2",
 "haponal": "2",
 "hydrocortone": "2",
 "hexadrol": "2",
 "halazepam": "1",
 "hyoscyamine/phenobarbital": "2"}, "k": {"kelnor 1/35": "2",
 "ketamine": "2",
 "klonopin": "1",
 "kaletra": "2",
 "kenalog-10": "2",
 "kariva": "2",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "karbons": "2",
 "ken-jec 40": "2",
 "ketoconazole": "1",
 "ketalar": "2",
 "kerlone": "3",
 "klonopin wafer": "1",
 "kenaject-40": "2",
 "kie": "1",
 "key-pred": "2"}, "j": {"jolessa": "2",
 "jl bragg's medicinal charcoal": "2",
 "jenest": "2",
 "jinteli": "2",
 "junel 1.5/30": "2",
 "jevantique": "2",
 "junel fe 1/20": "2",
 "junel fe 1.5/30": "2",
 "junel 1/20": "2",
 "jolivette": "2"}, "m": {"mylanta ar": "2",
 "metubine iodide": "2",
 "ma huang": "1",
 "metipranolol ophthalmic": "3",
 "medrol dosepak": "2",
 "mexitil": "2",
 "marlissa": "2",
 "myelo-kit": "3",
 "midazolam": "1",
 "methacort 40": "2",
 "migracet-pb": "2",
 "metaprel": "2",
 "mephobarbital": "2",
 "medicoal": "2",
 "mephenytoin": "2",
 "methylcotolone": "2",
 "millipred dp": "2",
 "medidex la": "2",
 "medicort": "2",
 "monodox": "2",
 "matzim la": "2",
 "methimazole": "2",
 "methylcotol": "2",
 "mirena": "2",
 "metaproterenol": "2",
 "methylprednisolone": "2",
 "millipred": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "3",
 "my-o-den": "2",
 "mysoline": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "min-ovral 28": "2",
 "metocurine": "2",
 "min-ovral 21": "2",
 "mononessa": "2",
 "medrol": "2",
 "menorest": "2",
 "maxair": "2",
 "microgestin 1.5/30": "2",
 "mestranol/norethindrone": "2",
 "methohexital": "2",
 "methylpred dp": "2",
 "mircette": "2",
 "microgestin fe 1/20": "2",
 "mygracet": "2",
 "margesic": "2",
 "methacort 80": "2",
 "mitran": "1",
 "mesantoin": "2",
 "minotal": "2",
 "myfortic": "1",
 "mimvey": "2",
 "mexiletine": "2",
 "medigesic": "2",
 "myrac": "2",
 "menaval-20": "2",
 "mebaral": "2",
 "modicon": "2",
 "methenamine/sodium biphosphate": "3",
 "metoprolol succinate er": "3",
 "microgestin fe 1.5/30": "2",
 "menostar": "2",
 "metoprolol": "3",
 "mycophenolic acid": "1",
 "micomp-pb": "2",
 "mivacurium": "2",
 "minocin": "2",
 "menorest patch": "2",
 "medralone": "2",
 "medidiol 10": "2",
 "medipred": "2",
 "m-prednisolone": "2",
 "mudrane gg": "2",
 "medralone 80": "2",
 "medihaler-iso": "2",
 "mintezol": "2",
 "marten-tab": "2",
 "metrizamide": "3",
 "mivacron": "2",
 "mycophenolate mofetil": "1",
 "microgestin 1/20": "2",
 "myzilra": "2",
 "marax df": "1",
 "moricizine": "1",
 "mudrane": "2",
 "minocycline": "2",
 "marax": "1",
 "medidex": "2",
 "maxair autohaler": "2",
 "methylprednisolone dose pack": "2"}, "l": {"lybrel": "2",
 "lorazepam intensol": "1",
 "loestrin fe 1.5/30": "2",
 "levoxyl": "2",
 "low-ogestrel-28": "2",
 "loestrin 1/20": "2",
 "levothroid": "2",
 "loestrin 21 1/20": "2",
 "lexiscan": "2",
 "levotabs": "2",
 "lunelle": "2",
 "liqui-char with sorbitol": "2",
 "lo loestrin fe": "2",
 "levotec": "2",
 "levsin with phenobarbital": "2",
 "levo-t": "2",
 "l thyroxine roche": "2",
 "luvox cr": "2",
 "lansoprazole": "1",
 "lithonate": "2",
 "loestrin fe 1/20": "2",
 "levothyroxine": "2",
 "labetalol": "3",
 "lithium": "2",
 "luminal": "2",
 "lo/ovral-28": "2",
 "lindane topical": "2",
 "limbitrol": "1",
 "loestrin 24 fe": "2",
 "levobetaxolol ophthalmic": "3",
 "levatol": "3",
 "lufyllin-epg": "2",
 "lutera": "2",
 "librium": "1",
 "lasix": "1",
 "loestrin 21 1.5/30": "2",
 "lessina": "2",
 "loryna": "2",
 "leena": "2",
 "lamisil": "2",
 "levonest": "2",
 "levobunolol ophthalmic": "3",
 "limbitrol ds": "1",
 "librax": "1",
 "lansoprazole/naproxen": "1",
 "levora": "2",
 "liqui-char": "2",
 "low-ogestrel-21": "2",
 "lopressor": "3",
 "levothyrox": "2",
 "lopinavir/ritonavir": "2",
 "liothyronine": "2",
 "lo-aqua": "1",
 "lorazepam": "1",
 "lithobid": "2",
 "levlite": "2",
 "luvox": "2",
 "lexxel": "1",
 "lopressor hct": "3",
 "loseasonique": "2",
 "laniroif": "2",
 "lidocaine/oxytetracycline": "2",
 "lopurin": "1",
 "lithotabs": "2",
 "lo/ovral": "2",
 "levonorgestrel": "2",
 "levlen": "2",
 "leader acid reducer": "2",
 "liotrix": "2",
 "levalbuterol": "2"}, "o": {"onfi": "1",
 "ortho-prefest": "2",
 "organon oestradiol": "2",
 "oestrodose": "2",
 "oroxine": "2",
 "ocupress": "3",
 "ogestrel-28": "2",
 "omnipaque 240 redi-unit": "3",
 "ortho-novum 1/35": "2",
 "oestrogel pump-pack": "2",
 "omnipaque flexipak": "3",
 "oraxyl": "2",
 "omnipaque 180 redi-unit": "3",
 "ortho-novum 7/7/7": "2",
 "ortho evra": "2",
 "optipranolol": "3",
 "omnipaque 350": "3",
 "oxytetracycline": "2",
 "oestrogel": "2",
 "omnipaque 210": "3",
 "orbivan": "2",
 "omnipaque 140": "3",
 "osmoprep": "3",
 "optimum charcoal": "2",
 "omnipaque 180": "3",
 "oestradiol implants": "2",
 "ortho tri-cyclen": "2",
 "ocella": "2",
 "ovcon 35": "2",
 "ovcon 35 fe": "2",
 "ovrette": "2",
 "ovral": "2",
 "ocudox": "2",
 "ortho-novum 10/11": "2",
 "ofloxacin": "2",
 "orapred": "2",
 "ogestrel": "2",
 "ortho tri-cyclen lo": "2",
 "orsythia": "2",
 "ortho-novum 1/50": "2",
 "ortho-cept": "2",
 "oracea": "2",
 "ortho micronor": "2",
 "oesclim": "2",
 "ovcon 50": "2",
 "oxytetracycline/phenazopyridine/sulfamethizole": "2",
 "ovral-28": "2",
 "oromone": "2",
 "orapred odt": "2",
 "oxazepam": "1",
 "ortho cyclen": "2",
 "omnipaque 300": "3",
 "omnipaque 240": "3"}, "n": {"nifedipine": "1",
 "norethin 1/35 e": "2",
 "norethindrone": "2",
 "norvir soft gelatin": "2",
 "necon 0.5/35": "2",
 "norethin 1/50 m": "2",
 "nora-be": "2",
 "northyx": "2",
 "nisoldipine": "1",
 "nortrel 0.5/35": "2",
 "necon 10/11": "2",
 "next choice": "2",
 "nebivolol": "3",
 "nature-throid": "2",
 "norvir": "2",
 "nydrazid": "2",
 "necon 1/35": "2",
 "norinyl 1+35": "2",
 "normodyne": "3",
 "neggram": "2",
 "nifediac cc": "1",
 "nizoral": "1",
 "necon 7/7/7": "2",
 "necon 1/50": "2",
 "nelova 10/11": "2",
 "nexterone": "2",
 "norisodrine with calcium iodine": "2",
 "nalidixic acid": "2",
 "nuvaring": "2",
 "noroxin": "2",
 "nuvelle ts phase i": "2",
 "norit": "2",
 "norinyl 1+50": "2",
 "norplant system": "2",
 "niravam": "1",
 "nembutal sodium": "2",
 "nizatidine": "2",
 "nembutal": "2",
 "nordette-21": "2",
 "natazia": "2",
 "nuromax": "2",
 "nutridox convenience kit": "2",
 "nifedical xl": "1",
 "nexplanon": "2",
 "nonbac": "2",
 "nordette-28": "2",
 "norcuron": "2",
 "nadolol": "3",
 "nelova 0.5/35": "2",
 "norgestrel": "2",
 "norfloxacin": "2",
 "nordette": "2",
 "nimbex": "2",
 "nortrel 7/7/7": "2",
 "nelova 1/35": "2",
 "nortrel 1/35": "2",
 "nelova 1/50 m": "2",
 "nor-qd": "2"}, "q": {"quadratuss": "1",
 "quelicin": "2",
 "quad tann pediatric": "1",
 "quasense": "2",
 "quadrapax": "2",
 "quelidrine": "1",
 "quad tann": "1",
 "quazepam": "1",
 "quad tuss pediatric": "1",
 "quelicin chloride": "2",
 "quadrinal": "2",
 "quad-tuss": "1"}, "p": {"pyridium plus": "2",
 "primatene": "1",
 "predicort-50": "2",
 "phrenilin forte": "2",
 "pepcid ac maximum strength": "2",
 "preven ec": "2",
 "pediazole": "2",
 "predacort 50": "2",
 "proventil": "2",
 "prevacid otc": "1",
 "pyrelle hb": "2",
 "prevacid solutab": "1",
 "promacet": "2",
 "progynova": "2",
 "pharmagesic": "2",
 "pindolol": "3",
 "procardia": "1",
 "pce dispertab": "2",
 "pulmicort nebuamp": "2",
 "predcor": "2",
 "periostat": "2",
 "paxipam": "1",
 "proair hfa": "2",
 "primidone": "2",
 "pred-ject-50": "2",
 "prolixin": "2",
 "panmycin": "2",
 "prevacid naprapac": "1",
 "pancuronium": "2",
 "prelone": "2",
 "phosphate laxative": "3",
 "pepcid complete": "2",
 "predate-50": "2",
 "pentobarbital": "2",
 "permitil": "2",
 "prolixin enanthate": "2",
 "peginterferon alfa-2a": "2",
 "peginterferon alfa-2b": "2",
 "procardia xl": "1",
 "phenytek": "2",
 "pb-hyos": "2",
 "pirbuterol": "2",
 "prominol": "2",
 "pulmicort flexhaler": "2",
 "propofol": "1",
 "predicort rp": "2",
 "primethasone": "2",
 "persantine iv": "2",
 "prevacid naprapac 500": "1",
 "progynova ts": "2",
 "pretz-d": "1",
 "primaxin iv": "2",
 "pedia-lax enema": "3",
 "pipecuronium": "2",
 "pepcid ac chewable tablets": "2",
 "peganone": "2",
 "prevacid naprapac 375": "1",
 "primaxin im": "2",
 "penbutolol": "3",
 "phenytoin sodium, prompt": "2",
 "previfem": "2",
 "phenaz plus": "2",
 "pharmacia carbosorb": "2",
 "pacerone": "2",
 "pentothal": "2",
 "plan b one-step": "2",
 "propranolol": "3",
 "pepcid": "2",
 "primogyn depot": "2",
 "pri-cortin 50": "2",
 "pentoxifylline": "1",
 "persantine": "2",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "perforomist": "2",
 "pepcid rpd": "2",
 "pegintron": "2",
 "penetrex": "3",
 "predaject-50": "2",
 "prevacid 24hr": "1",
 "phenazoforte plus": "2",
 "pulmicort turbuhaler": "2",
 "proventil hfa": "2",
 "predacorten": "2",
 "phenytoin": "2",
 "prevacid": "1",
 "prosom": "1",
 "pulmicort respules": "2",
 "phrenilin": "2",
 "plan b": "2",
 "predalone 50": "2",
 "philith": "2",
 "pavulon": "2",
 "primatene dual action": "1",
 "pegasys": "2",
 "pediapred": "2",
 "plendil": "1",
 "pentoxil": "1",
 "proquin xr": "3",
 "phenobarbital": "2",
 "prefest": "2",
 "provames": "2",
 "propoven": "1",
 "pepcid oral suspension": "2",
 "prednisolone": "2",
 "pepcid ac": "2",
 "portia": "2",
 "prolixin decanoate": "2",
 "propylthiouracil": "2",
 "pylera": "2",
 "primrose oil": "1",
 "propafenone": "2",
 "prevacid iv": "1",
 "pepcid ac maximum strength tablets": "2",
 "prevpac": "2"}, "s": {"solodyn": "2",
 "spasmolin": "2",
 "suprep bowel prep kit": "3",
 "solurex": "2",
 "sulfinpyrazone": "1",
 "solu-medrol": "2",
 "solia": "2",
 "sunmark acid reducer maximum strength": "2",
 "sylatron": "2",
 "systen": "2",
 "solu-cortef": "2",
 "seconal": "2",
 "synthroid": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "symbicort": "2",
 "sumycin 250": "2",
 "safyral": "2",
 "spastrin": "2",
 "spasquid": "2",
 "sumycin": "2",
 "seconal sodium": "2",
 "sulfimycin": "2",
 "sprintec": "2",
 "sotalol": "3",
 "sorine": "3",
 "succinylcholine": "2",
 "sedapap": "2",
 "servira": "2",
 "sronyx": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "sandrena": "2",
 "solurex la": "2",
 "st. john's wort": "2",
 "suprep": "3",
 "serax": "1",
 "syeda": "2",
 "seasonique": "2",
 "sotalol hydrochloride af": "3",
 "sectral": "3",
 "selestoject": "2",
 "serevent diskus": "2",
 "seasonale": "2",
 "salmeterol": "2",
 "sular": "1",
 "seconal sodium pulvules": "2"}, "r": {"rybix odt": "3",
 "rocuronium": "2",
 "rythmol sr": "2",
 "rybix": "3",
 "raxar": "2",
 "rimactane": "2",
 "reclipsen": "2",
 "rythmol": "2",
 "rynatuss": "1",
 "ryzolt": "3",
 "rofecoxib": "2",
 "rilutek": "1",
 "raplon": "2",
 "rebif": "2",
 "rifater": "2",
 "robimycin": "2",
 "roferon-a": "2",
 "ritodrine": "2",
 "rentamine": "1",
 "rapacuronium": "2",
 "ritonavir": "2",
 "roflumilast": "1",
 "rifamate": "2",
 "rifampin": "2",
 "riluzole": "1",
 "regadenoson": "2",
 "robitet 500": "2",
 "repan": "2",
 "ranitidine": "2",
 "ranitidine bismuth citrate": "2",
 "rentamine pediatric": "1",
 "rifadin iv": "2",
 "rynatuss pediatric": "1",
 "rifadin": "2",
 "restoril": "1",
 "re-pb hyos elixir": "2",
 "respirol": "2",
 "rebetron": "2"}, "u": {"urogesic blue": "3",
 "unithroid": "2",
 "uracil": "2",
 "ultram er": "3",
 "u-tri-lone": "2",
 "urelief plus": "2",
 "uloric": "2",
 "ultram": "3",
 "ultram odt": "3",
 "ultracet": "3",
 "uro-phosphate": "3",
 "urobiotic-250": "2"}, "t": {"ticlid": "2",
 "terramycin": "2",
 "toprol-xl": "3",
 "thiopental": "2",
 "tramadol": "3",
 "troleandomycin": "2",
 "tencet": "2",
 "theomax df": "1",
 "tetracap": "2",
 "tapazole": "2",
 "timolol ophthalmic": "3",
 "tramal sr": "3",
 "thyrolar-1": "2",
 "thyrolar-2": "2",
 "thyrolar-3": "2",
 "tramacort-d": "2",
 "tocainide": "1",
 "timoptic": "3",
 "tija": "2",
 "trivora": "2",
 "tubocurarine": "2",
 "terramycin im": "2",
 "tuss tan": "1",
 "tenormin": "3",
 "tacrine": "2",
 "tegretol": "2",
 "trinessa lo": "2",
 "tetracon": "2",
 "tranxene": "1",
 "tranxene sd": "1",
 "trandolapril/verapamil": "2",
 "triphasil-28": "2",
 "thyroid desiccated": "2",
 "tramedo": "3",
 "triphasil-21": "2",
 "tenoretic": "3",
 "trilog": "2",
 "tears again hydrate": "1",
 "tornalate": "2",
 "terbinex with eco formula": "2",
 "tums dual action": "2",
 "ticlopidine": "2",
 "triazolam": "1",
 "thyroid porcine": "2",
 "tenoretic 50": "3",
 "tri-norinyl": "2",
 "trandate": "3",
 "trivora-28": "2",
 "tiazac": "2",
 "tramapap": "3",
 "theodrine": "2",
 "terbinafine": "2",
 "tuss tan pediatric": "1",
 "timolide": "3",
 "timoptic-xe": "3",
 "thyrolar-1/2": "2",
 "temazepam": "1",
 "tri-levlen": "2",
 "thyrolar-1/4": "2",
 "triad": "2",
 "triamonide 40": "2",
 "timolol": "3",
 "tri-previfem": "2",
 "tristoject": "2",
 "tirosint": "2",
 "tenoretic 100": "3",
 "triphasil": "2",
 "tri-legest fe": "2",
 "tranxene t-tab": "1",
 "triquilar 28": "2",
 "triquilar 21": "2",
 "trilone": "2",
 "teczem": "2",
 "tagamet": "2",
 "triostat": "2",
 "tuinal": "2",
 "timolide 10-25": "3",
 "tedrigen": "2",
 "triam-forte": "2",
 "tencon": "2",
 "triamcot": "2",
 "triam-a": "2",
 "thaissept": "2",
 "tri-sprintec": "2",
 "taladine": "2",
 "tri-lo-sprintec": "2",
 "tenake": "2",
 "triaprin": "2",
 "tarka": "2",
 "trental": "1",
 "tilia fe": "2",
 "terbutaline": "2",
 "tao": "2",
 "triamcinolone": "2",
 "tramahexal sr": "3",
 "trinessa": "2",
 "tritec": "2",
 "tonocard": "1",
 "taztia xt": "2",
 "thiabendazole": "2",
 "tramal": "3",
 "tetra tannate pediatric": "1",
 "tetracycline": "2",
 "tri-legest": "2",
 "timoptic ocudose": "3",
 "tac 3": "2",
 "tagamet hb": "2",
 "tegretol xr": "2",
 "thais": "2",
 "two-dyne": "2",
 "tracrium": "2",
 "thyrolar": "2"}, "w": {"westhroid": "2",
 "wellbutrin sr": "3",
 "welchol": "2",
 "wellbutrin xl": "3",
 "wellbutrin": "3"}, "v": {"versed": "1",
 "vioxx": "2",
 "vivelle-dot": "2",
 "vibra-tabs": "2",
 "verelan pm": "2",
 "valertest no 1": "2",
 "velivet": "2",
 "vestura": "2",
 "vospire er": "2",
 "verelan": "2",
 "vecuronium": "2",
 "ventolin": "2",
 "valergen": "2",
 "verapamil": "2",
 "vibramycin": "2",
 "visicol": "3",
 "valium": "1",
 "veripred 20": "2",
 "ventolin hfa": "2",
 "volmax": "2",
 "valrelease": "1",
 "vivelle": "2",
 "visken": "3"}, "y": {"yutopar": "2",
 "yasmin": "2",
 "yaz": "2"}, "x": {"xopenex": "2",
 "xopenex concentrate": "2",
 "xopenex hfa": "2",
 "xanax xr": "1",
 "xanax": "1"}, "z": {"zumenon": "2",
 "zantac 150 efferdose": "2",
 "zmax": "2",
 "zovia 1/50": "2",
 "zovirax": "1",
 "zafirlukast": "2",
 "zarah": "2",
 "zileuton": "2",
 "zantac 25 mg efferdose": "2",
 "zovia 1/35": "2",
 "zantac 300": "2",
 "zema pak": "2",
 "zyloprim": "1",
 "zantac efferdose": "2",
 "zantac": "2",
 "zemuron": "2",
 "zeosa": "2",
 "zithromax": "2",
 "zebeta": "3",
 "zantac geldose": "2",
 "zamadol": "3",
 "zantac 75": "2",
 "zebutal": "2",
 "zydol": "3",
 "zyflo cr": "2",
 "zyban": "3",
 "zyflo": "2",
 "zenchent fe": "2",
 "zenchent": "2",
 "zantac 150": "2",
 "zantac 300 geldose": "2",
 "zetran": "1",
 "ziac": "3",
 "zovia": "2"}}];