interactions["amlodipine-telmisartan,twynsta"]=["amlodipine-telmisartan,twynsta", {"5": {"50 + companion": "2"}, "4": {"40 winks": "2"}, "a": {"aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aristocort": "2",
 "alfenta": "2",
 "acetaminophen/dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "advil liqui-gels": "2",
 "antispas": "2",
 "aflaxen": "2",
 "adlone-40": "2",
 "antioxidant formula": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "1",
 "advil pm": "2",
 "ambien cr": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "alcalak": "2",
 "a-g tussin": "2",
 "amidrine": "2",
 "alka-seltzer gold": "3",
 "amitriptyline/perphenazine": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "advanced am/pm": "2",
 "aspirin buffered": "2",
 "aminosyn ii with electrolytes": "3",
 "advil cold and sinus liqui-gels": "2",
 "anhydrous calcium iodide/codeine": "2",
 "acetaminophen/aspirin": "2",
 "all day pain relief": "2",
 "acetaminophen/butalbital": "2",
 "acetaminophen/pamabrom/pyrilamine": "2",
 "azmacort": "2",
 "aristopak": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "acetaminophen/diphenhydramine/pseudoephedrine": "2",
 "alka-seltzer extra strength": "2",
 "aliskiren/valsartan": "2",
 "acetaminophen/aspirin/caffeine": "2",
 "anergan 50": "2",
 "adrenocot": "2",
 "aminosyn ii 4.25%-dextrose 20%,electrolyte,ca": "3",
 "alprazolam": "2",
 "arthriten": "2",
 "acthar": "2",
 "acebutolol": "2",
 "alagesic": "2",
 "amigesic": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "amobarbital": "2",
 "aldex-ct": "2",
 "a-methapred": "2",
 "amitone": "2",
 "abc plus senior": "2",
 "amiloride": "3",
 "acetylcarbromal": "2",
 "alka-seltzer lemon-lime": "2",
 "allfen cd": "2",
 "amlodipine/benazepril": "2",
 "atuss hx": "2",
 "ami-rax": "2",
 "aldoril d50": "1",
 "amobarbital/secobarbital": "2",
 "actiprofen": "2",
 "avinza": "2",
 "actron": "2",
 "axocet": "2",
 "alkums": "2",
 "aspirin": "2",
 "adlone-80": "2",
 "apresazide": "1",
 "aquacot": "1",
 "aristospan": "2",
 "alcohol and dextrose injections usp hypertonic": "2",
 "atarax": "2",
 "atuss ms": "2",
 "apo-go": "2",
 "advil junior strength": "2",
 "adbeon": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/pseudoephedrine": "2",
 "aripiprazole": "2",
 "amoxapine": "2",
 "actifed allergy day/night": "2",
 "alphagan": "1",
 "arthrotec": "2",
 "amiloride/hydrochlorothiazide": "3",
 "anhydrous calcium iodide/isoproterenol": "2",
 "acth": "2",
 "acid reducer + antacid dual action": "2",
 "adeks": "2",
 "advil cold and sinus": "2",
 "aspir-mox ib": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "ambifed cd": "2",
 "advil children's": "2",
 "alleroff": "2",
 "americet": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "anolor 300": "2",
 "abilify discmelt": "2",
 "anacin": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "aspergum": "2",
 "allertan": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "atrohist pediatric": "2",
 "aspirin/oxycodone": "2",
 "aspir-mox": "2",
 "amitriptyline": "2",
 "ambenyl": "2",
 "acetaminophen/hydrocodone": "2",
 "aspirin/phenyltoloxamine": "2",
 "aricept": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "aricept odt": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "atacand hct": "1",
 "allergy relief d": "2",
 "amlobenz": "2",
 "accuretic": "2",
 "alka-seltzer plus immunity complex": "2",
 "aspir 81": "2",
 "alcohol": "2",
 "asenapine": "2",
 "adult strength": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "a-g profen": "2",
 "acetocot": "2",
 "alkabel-sr": "2",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "asendin": "2",
 "anexsia": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "anectine": "2",
 "aldoril 25": "1",
 "alka-seltzer pm": "2",
 "advance care plus": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "advil migraine": "2",
 "all day relief": "2",
 "advanced formula di-gel": "2",
 "aquadeks": "2",
 "angeliq": "2",
 "advil infant's concentrated drops": "2",
 "acetaminophen/dichloralphenazone/isometheptene mucate": "2",
 "alka-mints": "2",
 "alka-seltzer plus cold formula": "2",
 "antispasmodic": "2",
 "ami-lac": "2",
 "apokyn": "2",
 "aspirin/diphenhydramine": "2",
 "acetaminophen/codeine": "2",
 "antrocol": "2",
 "arduan": "2",
 "antiflex": "2",
 "aspirin/carisoprodol/codeine": "2",
 "aquadeks pediatric": "2",
 "anafranil": "2",
 "a-cof dh": "2",
 "amifostine": "2",
 "acetaminophen/salicylamide": "2",
 "aceta w/ codeine": "2",
 "aldactazide": "3",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "aldex dm": "2",
 "atuss g": "2",
 "aldoclor-150": "1",
 "aminosyn with electrolytes sulfite-free": "3",
 "airacof": "2",
 "ascriptin": "2",
 "atenolol/chlorthalidone": "2",
 "asthmacon": "2",
 "alahist dhc": "2",
 "aliskiren": "2",
 "aldoril d30": "1",
 "allerfrin with codeine": "2",
 "advil": "2",
 "aspirtab": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "atazanavir": "2",
 "aventyl hydrochloride": "2",
 "aspirin/codeine": "2",
 "aspirin/pentazocine": "2",
 "alcohol 5% in dextrose 5%": "2",
 "acetaminophen/diphenhydramine": "2",
 "arthritis foundation pain reliever": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "1",
 "aldoclor-250": "1",
 "aspirin/hydrocodone": "2",
 "agenerase": "2",
 "aspir-low": "2",
 "aspirin/meprobamate": "2",
 "aler-dryl": "2",
 "aldactone": "3",
 "actiq": "2",
 "amytal sodium": "2",
 "allfen cdx": "2",
 "aldoril 15": "1",
 "aminatal plus new formula": "2",
 "addaprin": "2",
 "anaflex": "2",
 "apraclonidine ophthalmic": "2",
 "atuss ex": "2",
 "anaprox": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "acetaminophen/caffeine/pyrilamine": "2",
 "allermax": "2",
 "atripla": "2",
 "aquachloral supprettes": "2",
 "aminosyn ii 3.5%-dextrose 25%,electrolytes,ca": "3",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "2",
 "aspirin/methocarbamol": "2",
 "ambophen": "2",
 "arcet": "2",
 "aminatal plus one": "2",
 "a-tan 12x": "2",
 "arthropan": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "alka-seltzer original": "2",
 "apo-go pen": "2",
 "aminosyn with electrolytes": "3",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "acetylsalicylic acid": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "anacin advanced headache formula": "2",
 "acetaminophen/oxycodone": "2",
 "acid controller complete dual action": "2",
 "abc to z": "2",
 "anectine flo-pack": "2",
 "anacin p.m. aspirin free": "2",
 "adapin": "2",
 "altace": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "anacin max strength": "2",
 "apetigen-plus": "2",
 "atamet": "2",
 "alphen expectorant": "2",
 "acetaminophen/propoxyphene": "2",
 "aplenzin": "2",
 "aspirin/dipyridamole": "2",
 "acuprin 81": "2",
 "all day allergy-d": "2",
 "acetaminophen/phenyltoloxamine/salicylamide": "2",
 "alfentanil": "2",
 "acetaminophen pm extra strength": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "avail calcium intensive": "2",
 "ambifed-g cd": "2",
 "anaprox-ds": "2",
 "atrosept": "2",
 "altaryl": "2",
 "afinitor": "2",
 "atabex ec": "2",
 "ambi 5/15/100": "2",
 "azilect": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "anaplex hd": "2",
 "acthrel": "2",
 "anabar": "2",
 "astramorph pf": "2",
 "armodafinil": "1",
 "amprenavir": "2",
 "aspirin lite coat": "2",
 "atapryl": "2",
 "aquazide h": "1",
 "anzemet": "3",
 "amturnide": "2",
 "aldex d": "2",
 "alagesic lq": "2",
 "ansaid": "2",
 "aspirin low strength": "2",
 "aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "adrenocot la": "2",
 "ascriptin enteric": "2",
 "amrix": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "azdone": "2",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "2",
 "aspiritab": "2",
 "aldoril": "1",
 "apatate forte": "2",
 "ambien": "2",
 "adgan": "2",
 "alor 5/500": "2",
 "argesic-sa": "2",
 "alka-seltzer plus flu formula": "2",
 "abilify": "2",
 "acetaminophen/caffeine/dihydrocodeine": "2",
 "aspirin/pravastatin": "2",
 "arthritis pain": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "alahist lq": "2",
 "aldesleukin": "2",
 "a-hydrocort": "2",
 "aminosyn ii 4.25%-dextrose 25%,electrolyte,ca": "3",
 "aspirin/caffeine": "2",
 "accesspak for hiv pep expanded with viracept": "2",
 "ambifed-g cdx": "2",
 "advil children's allergy sinus": "2",
 "aleve": "2",
 "atenolol": "2",
 "aminate": "2",
 "azilsartan medoxomil/chlorthalidone": "1",
 "aminatal plus": "2",
 "accupril": "2",
 "aliskiren/amlodipine": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "actemra": "2",
 "anoquan": "2",
 "atuss hd": "2",
 "aquatensen": "1",
 "alka-seltzer wake-up call!": "2",
 "aggrenox": "2",
 "advil allergy sinus": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "3",
 "acetaminophen/butalbital/caffeine": "2",
 "atuss hs": "2",
 "aspirin/pseudoephedrine": "2",
 "ascriptin maximum strength": "2",
 "aceon": "2",
 "aristocort for injection": "2",
 "avalide": "1",
 "aminate with 90 mg iron": "2",
 "apomorphine": "2",
 "advil children's cold": "2",
 "aspirin/butalbital/caffeine": "2",
 "acetaminophen/dextromethorphan/diphenhydramine": "2",
 "alidrin": "2",
 "alprazolam intensol": "2",
 "arthritis pain formula": "2",
 "ala-hist": "2",
 "actonel with calcium": "2",
 "ak-beta": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "allergia-c": "2",
 "acetaminophen/aspirin/phenylpropanolamine": "2",
 "aspirin/calcium carbonate": "2",
 "all day allergy children's": "2",
 "aleve-d sinus &amp; cold": "2",
 "antioxid caplets": "2",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "alphagan p": "1",
 "adcirca": "1",
 "aspirin/caffeine/propoxyphene": "2",
 "acetaminophen/pentazocine": "2",
 "ami-natal plus one improved": "2",
 "ala-hist d": "2",
 "atropine/phenobarbital": "2",
 "aspirin/carisoprodol": "2",
 "all day allergy": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "aspircaf": "2",
 "antioxidant ultra formula": "2",
 "alkets": "2",
 "aspirin/butalbital": "2",
 "anemagen ob": "2",
 "ativan": "2",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "2",
 "abstral": "2",
 "ala-hist ac": "2",
 "atracurium": "2",
 "aminosyn ii with electrolytes sulfite-free": "3",
 "aspirin/caffeine/salicylamide": "2",
 "aler-tab": "2",
 "ambifed cdx": "2"}, "c": {"calcitab": "2",
 "calcium carbonate/risedronate": "2",
 "codiclear dh": "2",
 "calcifolic-d": "2",
 "c-tanna 12d": "2",
 "capozide 50/25": "2",
 "cytra-k": "3",
 "calcidrine": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "calcionate": "2",
 "concept dha": "2",
 "combunox": "2",
 "chlorthalidone/reserpine": "1",
 "citric acid/potassium citrate/sodium citrate": "3",
 "cytra-3": "3",
 "cortisone": "2",
 "compound 374": "2",
 "capoten": "2",
 "cvs allergy &amp; sinus headache": "2",
 "corzide 40/5": "2",
 "calcium oyster shell": "2",
 "calcid": "2",
 "co natal fa": "2",
 "celestone phosphate": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "clozapine": "2",
 "carbetapentane/diphenhydramine": "2",
 "capital w/codeine": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "cmt": "2",
 "cocet plus": "2",
 "children's tylenol plus cold and allergy": "2",
 "codeine/promethazine": "2",
 "cardizem la": "2",
 "celestone": "2",
 "calcium carbonate/simethicone": "2",
 "caltrate colon health": "2",
 "compazine spansule": "2",
 "carbidopa/entacapone/levodopa": "2",
 "cerovite senior": "2",
 "chlordinium": "2",
 "citracal calcium gummies": "2",
 "conceptionxr msf": "2",
 "centrum special energy": "2",
 "calafol rx": "2",
 "calcium gluceptate": "2",
 "calcium lactate": "2",
 "clorazepate": "2",
 "calcium glycerophosphate": "2",
 "caromega": "2",
 "cezin-s": "2",
 "centussin dhc": "2",
 "children's motrin": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "calcium carbonate/magnesium carbonate": "2",
 "clinoril": "2",
 "centrum cardio": "2",
 "co-histine dh": "2",
 "centrum silver": "2",
 "comtussin hc": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "cordron-hc nr": "2",
 "cardizem monovial": "2",
 "codehist dh": "2",
 "carbatrol": "2",
 "carenatal dha": "2",
 "centrum silver ultra men's": "2",
 "cal-gest": "2",
 "chlorpheniramine/codeine": "2",
 "chemtussin hc": "2",
 "calcet": "2",
 "carteolol": "2",
 "chlorpromazine": "2",
 "centrum jr with extra calcium": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "calcium disodium versenate": "2",
 "cotabflu": "2",
 "capozide 50/15": "2",
 "codeprex": "2",
 "codahistine-dh elixir": "2",
 "caffeine/magnesium salicylate": "2",
 "cell-u-jec": "2",
 "chlorzoxazone": "2",
 "codeine/phenylephrine/promethazine": "2",
 "cortone acetate": "2",
 "chewable calcium with vitamin d": "2",
 "chlormezanone": "2",
 "cocet": "2",
 "cystemms-v": "2",
 "clusimar": "2",
 "carisoprodol compound": "2",
 "choline salicylate/magnesium salicylate": "2",
 "colrex compound": "2",
 "cytuss hc": "2",
 "citracal plus bone density builder": "2",
 "citracal plus heart health": "2",
 "codituss dh": "2",
 "codituss dm": "2",
 "centrum": "2",
 "citric acid/potassium citrate": "3",
 "chlorphenesin": "2",
 "cenogen ultra": "2",
 "capozide 25/25": "2",
 "coricidin night time cold relief": "2",
 "certagen": "2",
 "citranatal 90 dha": "2",
 "calci-chew": "2",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "centratex": "2",
 "cardoxin": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "3",
 "calcium carbonate/fluoride": "2",
 "combi rx": "2",
 "chemdal hd plus": "2",
 "cotrim": "2",
 "cardizem sr": "2",
 "cerovite advanced formula": "2",
 "celecoxib": "2",
 "co-gesic": "2",
 "codimal dm": "2",
 "cort-k": "2",
 "codimal dh": "2",
 "cheratussin dac": "2",
 "corvita 150": "2",
 "chlorothiazide/reserpine": "1",
 "carbetapentane/phenylephrine/pyrilamine": "2",
 "carozide": "1",
 "citranatal harmony": "2",
 "cetirizine": "2",
 "cyclosporine": "2",
 "canges-xp": "2",
 "calcium phosphate, tribasic": "2",
 "calcium gluconate": "2",
 "chromagen ob": "2",
 "codafen": "2",
 "corzall plus": "2",
 "conjugated estrogens/meprobamate": "2",
 "codafed": "2",
 "carteolol ophthalmic": "2",
 "comfort pac with naproxen": "2",
 "complete-rf": "2",
 "codegest expectorant": "2",
 "corzide 80/5": "2",
 "colrex": "2",
 "centrum silver women's": "2",
 "coldcough hcm": "2",
 "certavite with antioxidants": "2",
 "compro": "2",
 "clozaril": "2",
 "chlorpheniramine/phenylephrine/pyrilamine": "2",
 "cerovite junior": "2",
 "caltrate 600+d": "2",
 "capacet": "2",
 "chlorcyclizine/codeine": "2",
 "centrum kids": "2",
 "cal-g": "2",
 "citracal maximum": "2",
 "caltrate 600 plus": "2",
 "cortrosyn": "2",
 "certagen senior": "2",
 "central-vite": "2",
 "carbetapentane/pyrilamine": "2",
 "cosopt": "2",
 "calcium 600 d": "2",
 "centrum special heart": "2",
 "coryza-dm": "2",
 "cisatracurium": "2",
 "chemdal hd": "2",
 "circavite t": "2",
 "completenate": "2",
 "cataflam": "2",
 "capozide 25/15": "2",
 "citracal plus magnesium": "2",
 "certavite": "2",
 "caldolor": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "codotuss": "2",
 "cope": "2",
 "centrum ultra men's": "2",
 "childrens kaopectate": "2",
 "coldcough syrup": "2",
 "cosyntropin": "2",
 "cetiri d": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "codal-dm syrup": "2",
 "cycofed": "2",
 "compazine": "2",
 "celestone soluspan": "2",
 "complete natal dha": "2",
 "counteract pm extra strength": "2",
 "citrus calcium with vitamin d": "2",
 "captopril/hydrochlorothiazide": "2",
 "calcarb": "2",
 "citranatal rx": "2",
 "complete a-z": "2",
 "cerovite liquid": "2",
 "calcium/vitamin d": "2",
 "certa-vite": "2",
 "calcium concentrate": "2",
 "colocort": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "clobazam": "2",
 "calphosan": "2",
 "calcifol": "2",
 "clonazepam": "2",
 "chardonna-2": "2",
 "coumadin": "1",
 "clindex": "2",
 "capozide": "2",
 "carbetapentane/pseudoephedrine/pyrilamine": "2",
 "corticorelin": "2",
 "calcium liquid softgel": "2",
 "cortef": "2",
 "centrum ultra women's": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "caltrate gummy bites": "2",
 "cotab a": "2",
 "celebrex": "2",
 "calcet plus": "2",
 "cambia": "2",
 "cvs extra strength headache relief": "2",
 "co-tussin": "2",
 "certa-vite senior plus lutein": "2",
 "citracal kosher": "2",
 "chloral hydrate": "2",
 "cal-nate": "2",
 "century senior": "2",
 "combigan": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "corvite free": "2",
 "cycofed pediatric expectorant": "2",
 "calcium chloride": "2",
 "cotab ax": "2",
 "centrum silver ultra women's": "2",
 "citracal regular": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "chlorpheniramine/hydrocodone/phenylephrine": "2",
 "chlorpheniramine/hydrocodone": "2",
 "cavan-heme ob": "2",
 "codamine": "2",
 "carbidopa/levodopa": "2",
 "corlopam": "2",
 "co-histine expectorant": "2",
 "cotuss v": "2",
 "cheracol with codeine": "2",
 "corticotropin": "2",
 "coreg cr": "2",
 "clotrimazole": "2",
 "century-vite": "2",
 "comfort pac with cyclobenzaprine": "2",
 "carbacot": "2",
 "cardizem": "2",
 "chlorthalidone/clonidine": "1",
 "citracal + d": "2",
 "citracal prenatal rx": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "centrum silver men's": "2",
 "candesartan/hydrochlorothiazide": "1",
 "clorpres": "1",
 "certagen senior with lutein": "2",
 "chlordiazepoxide/clidinium": "2",
 "chlorpheniramine/hydrocodone/pseudoephedrine": "2",
 "clopine": "2",
 "conivaptan": "2",
 "citrolith": "3",
 "chlorex-a 12": "2",
 "corvita": "2",
 "chlordiazepoxide/methscopolamine": "2",
 "corvite": "2",
 "citracal prenatal 90+dha": "2",
 "cystex": "2",
 "cotrim pediatric": "2",
 "combiflex": "2",
 "calcitrate with d": "2",
 "caltrate 600 with d plus soy": "2",
 "caltro with vitamin d": "2",
 "cymbalta": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "cal oys": "2",
 "carbamazepine": "2",
 "cyndal expectorant": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "carvedilol": "2",
 "cal-glu": "2",
 "codimal ph": "2",
 "children's triacting night time": "2",
 "cyndal hd": "2",
 "citranatal assure": "2",
 "calci mix": "2",
 "citranatal dha": "2",
 "clomipramine": "2",
 "codafed pediatric": "2",
 "cafgesic forte": "2",
 "cephadyn": "2",
 "century": "2",
 "covangesic": "2",
 "corvite 150": "2",
 "companion multi": "2",
 "captopril": "2",
 "calcium, magnesium and zinc": "2",
 "calcium acetate/magnesium carbonate": "2",
 "complete natal": "2",
 "contac day and night cold and flu": "2",
 "chlorgest hd": "2",
 "cavan-folate dha": "2",
 "codeine/guaifenesin": "2",
 "calvite p": "2",
 "calcium glycerophosphate/calcium lactate": "2",
 "codeine phosphate-promethazine hcl": "2",
 "chlorothiazide": "1",
 "calcium acetate": "2",
 "coughtuss": "2",
 "calcium glubionate": "2",
 "cosopt pf": "2",
 "concept ob": "2",
 "canges-hc nr": "2",
 "codeine": "2",
 "citracal petites": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "crizotinib": "2",
 "caltro": "2",
 "cialis": "1",
 "chooz": "2",
 "co-trimoxazole": "2",
 "chlorothiazide/methyldopa": "1",
 "centavite": "2",
 "cartia xt": "2",
 "cerebyx": "2",
 "chemdal expectorant": "2",
 "coldcough pd": "2",
 "cetirizine/pseudoephedrine": "2",
 "calcarb with d": "2",
 "codahistine expectorant": "2",
 "cardizem cd": "2",
 "cafgesic": "2",
 "childrens ibuprofen berry": "2",
 "carbinoxamine/hydrocodone/pseudoephedrine": "2",
 "choline magnesium trisalicylate": "2",
 "cordron-hc": "2",
 "corgard": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "carbex": "2",
 "cavan folate": "2",
 "centrum performance": "2",
 "cycofed expectorant": "2",
 "carbinoxamine/hydrocodone/phenylephrine": "2",
 "codeine/phenylephrine": "2",
 "cabergoline": "2",
 "caltrate plus": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "chlorpheniramine/guaifenesin/hydrocodone/pseudoephedrine": "2",
 "cortenema": "2",
 "codeine/pseudoephedrine": "2",
 "codal-dh syrup": "2",
 "chlorphen hd": "2",
 "citracal regular 250 mg + d": "2",
 "cortifoam": "2",
 "complete allergy": "2",
 "centrum specialist vision": "2",
 "condasin": "2",
 "cap-profen": "2",
 "central": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "clozapine synthon": "2",
 "cafatine pb": "2",
 "chlordiazepoxide": "2",
 "cotrim ds": "2",
 "cytuss-hc nr": "2",
 "capital with codeine suspension": "2",
 "calm-aid": "2",
 "cyclobenzaprine": "2",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "cognex": "2",
 "calcio del mar": "2",
 "calcium carbonate": "2",
 "canges-hc": "2",
 "clinalog": "2",
 "clinacort": "2",
 "cavan ec dha plus": "2",
 "cvs allergy &amp; cold": "2",
 "cena k": "3",
 "corzide": "2",
 "cartrol": "2",
 "clotrimazole troche": "2",
 "calciquid": "2",
 "cotolone": "2",
 "choline salicylate": "2",
 "compoz nighttime sleep aid": "2",
 "co-tuss v expectorant": "2",
 "children's zyrtec": "2",
 "contac day and night allergy": "2",
 "cf vite": "2",
 "clinimix e sulfite free": "3",
 "calcium oyster": "2",
 "conal": "2",
 "carisoprodol": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "codamine pediatric": "2",
 "certavite with lutein": "2",
 "caltrate 600+d plus minerals": "2",
 "cheratussin ac": "2",
 "crantex hc": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "citranatal b-calm": "2",
 "calphron": "2",
 "caltrate": "2",
 "conceptionxr rhf": "2",
 "citric acid/potassium bicarbonate": "3",
 "citracal slow release 1200": "2",
 "chlorthalidone": "1",
 "citracal prenatal + dha": "2",
 "combiflex es": "2",
 "coreg": "2",
 "cavan one": "2",
 "calcium citrate": "2",
 "compete": "2",
 "codeine/pseudoephedrine/triprolidine": "2"}, "b": {"bellaphen-s": "2",
 "betaxolol": "2",
 "benadryl-d allergy plus sinus": "2",
 "brompheniramine/hydrocodone/phenylephrine": "2",
 "butisol sodium": "2",
 "bitex liquid": "2",
 "brevibloc": "2",
 "bugs bunny complete": "2",
 "betoptic": "2",
 "betagan c-cap": "2",
 "butorphanol": "2",
 "bystolic": "2",
 "benaphen plus": "2",
 "bayer am": "2",
 "benzthiazide": "1",
 "by-ache": "2",
 "bayer pm": "2",
 "bayer aspirin extra strength plus": "2",
 "b c powder arthritis strength": "2",
 "bactrim": "2",
 "bromodiphenhydramine/codeine": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "benicar hct": "1",
 "buspirone": "2",
 "brovex hc": "2",
 "bel-phen-ergot": "2",
 "brimonidine/timolol ophthalmic": "2",
 "bayer women's aspirin with calcium": "2",
 "buffasal": "2",
 "butabarbital": "2",
 "betaxolol ophthalmic": "2",
 "benadryl": "2",
 "bpm pe hc": "2",
 "bacmin": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "betapace af": "2",
 "belladonna/butabarbital": "2",
 "bayer children's aspirin": "2",
 "bc headache": "2",
 "benadryl allergy plus cold": "2",
 "brovex pb cx": "2",
 "betapace": "2",
 "bactrim iv": "2",
 "bromplex hd": "2",
 "b c powder": "2",
 "biotin forte with zinc": "2",
 "bayer extra strength back &amp; body": "2",
 "benadryl children's allergy and sinus": "2",
 "bydureon": "2",
 "brovex cbx": "2",
 "bufferin arthritis strength": "2",
 "bethaprim pediatric": "2",
 "benadryl allergy sinus": "2",
 "biotussin dac": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "buffered aspirin": "2",
 "butrans": "2",
 "byetta": "2",
 "beyaz": "2",
 "budeprion sr": "2",
 "benahist-50": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "beelith": "2",
 "becomax rx": "2",
 "buspar": "2",
 "benadryl allergy": "2",
 "betagan": "2",
 "bayer aspirin": "2",
 "balacet": "2",
 "b-nexa": "2",
 "bellaspas": "2",
 "brompheniramine/hydrocodone/pseudoephedrine": "2",
 "benadryl allergy plus sinus headache": "2",
 "bromph hd": "2",
 "betamethasone": "2",
 "boceprevir": "2",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bethaprim": "2",
 "bismatrol maximum strength": "2",
 "baycadron": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bp multinatal plus chewables": "2",
 "bellamine": "2",
 "bufferin low dose": "2",
 "bayer select backache pain formula": "2",
 "bel-tabs": "2",
 "belix": "2",
 "beldin": "2",
 "bendroflumethiazide": "1",
 "belladonna/opium": "2",
 "bendroflumethiazide/nadolol": "2",
 "bupropion": "2",
 "bismatrol": "2",
 "berocca plus": "2",
 "benahist-10": "2",
 "bayer advanced aspirin": "2",
 "brovex cb": "2",
 "betoptic s": "2",
 "brimonidine ophthalmic": "1",
 "bosentan": "2",
 "banophen": "2",
 "benylin multi-symptom": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "budeprion": "2",
 "be-flex plus": "2",
 "bladder 2.2": "2",
 "benadryl severe allergy &amp; sinus headache": "2",
 "bayer aspirin with heart advantage": "2",
 "budesonide/formoterol": "2",
 "butibel": "2",
 "bendroflumethiazide/rauwolfia serpentina": "1",
 "buffered salt": "3",
 "bromfenac": "2",
 "butex forte": "2",
 "buprenorphine/naloxone": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "3",
 "betimol": "2",
 "bydramine": "2",
 "brompheniramine/diphenhydramine": "2",
 "brompheniramine/codeine": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "b-plex plus minerals": "2",
 "buprenex": "2",
 "bactrim pediatric": "2",
 "b &amp; o supprettes": "2",
 "bismuth subsalicylate": "2",
 "beta-phos/ac": "2",
 "brovex pb c": "2",
 "bupivacaine/hydromorphone": "2",
 "budeprion xl": "2",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "buprenorphine": "2",
 "betamed": "2",
 "bayer aspirin regimen": "2",
 "banflex": "2",
 "bellergal-s": "2",
 "banaril": "2",
 "bellalphen": "2",
 "bromcomp hc": "2",
 "bellamine s": "2",
 "b-tuss": "2",
 "bufferin": "2",
 "bellatal er": "2",
 "benadryl severe allergy plus sinus headache": "2",
 "blocadren": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "bayer women's low dose plus calcium": "2",
 "benazepril/hydrochlorothiazide": "2",
 "bee-zee": "2",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "ben-tann": "2",
 "bupap": "2",
 "brontex": "2",
 "bisoprolol": "2",
 "belcomp-pb": "2",
 "brilinta": "1",
 "bupivacaine/fentanyl": "2",
 "betaxon": "2",
 "butalbital compound": "2",
 "bismarex": "2",
 "bextra": "2",
 "baclofen": "2",
 "butalbital": "2",
 "buffex": "2",
 "benoject-50": "2",
 "budesonide": "2",
 "benazepril": "2",
 "bellamor": "2",
 "benadryl children's allergy": "2",
 "bufferin extra strength": "2",
 "bc fast pain relief": "2",
 "busodium": "2",
 "buproban": "2",
 "berplex plus": "2",
 "brompheniramine/codeine/pseudoephedrine": "2",
 "barbidonna": "2",
 "bright beginnings": "2",
 "bellatal": "2",
 "bactrim ds": "2",
 "bucet": "2",
 "bubbli-pred": "2",
 "benadryl cold": "2"}, "e": {"essentia": "2",
 "efasin-hd plus": "2",
 "ecotrin maximum strength": "2",
 "eplerenone": "2",
 "entaprin": "2",
 "effer-k": "3",
 "emsam": "2",
 "equilet": "2",
 "endep": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "ec-naprosyn": "2",
 "endacof-ac": "2",
 "endodan": "2",
 "excedrin pm": "2",
 "emagrin": "2",
 "enflurane": "2",
 "exetuss-hc": "2",
 "excedrin menstrual complete": "2",
 "epoprostenol": "2",
 "endocet": "2",
 "effervescent pain relief": "2",
 "embeda": "2",
 "exalgo": "2",
 "effexor": "2",
 "exforge hct": "1",
 "elavil": "2",
 "endal hd": "2",
 "entuss-d": "2",
 "execlear-c": "2",
 "esidrix": "1",
 "elemental iron-90": "2",
 "ed k+10": "3",
 "effervescent potassium": "3",
 "exo-tuss": "2",
 "esgic": "2",
 "ecotrin adult low strength": "2",
 "entuss": "2",
 "entuss-d liquid": "2",
 "endacof hc": "2",
 "ellis tonic sherry": "2",
 "edge ob": "2",
 "endacof xp": "2",
 "easprin": "2",
 "extendryl hc": "2",
 "enduron": "1",
 "elixiral": "2",
 "ergocomp-pb": "2",
 "edarbyclor": "1",
 "elite ob with dha": "2",
 "excedrin migraine": "2",
 "eldercaps": "2",
 "equitan pediatric": "2",
 "efasin-hd": "2",
 "enalapril/felodipine": "2",
 "endal expectorant": "2",
 "ecpirin": "2",
 "esmolol": "2",
 "execlear": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "3",
 "execof": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "endal cd": "2",
 "ethanol": "2",
 "entocort ec": "2",
 "etrafon forte": "2",
 "ethyol": "2",
 "equi-natal care": "2",
 "exna": "1",
 "endagen-hd": "2",
 "entuss expectorant": "2",
 "e-caff p-b": "2",
 "equetro": "2",
 "endolor": "2",
 "epitol": "2",
 "elixophyllin ki": "3",
 "equinatal 90": "2",
 "efavirenz": "2",
 "embrex 600": "2",
 "ecee plus": "2",
 "equi-natal plus": "2",
 "ecotrin": "2",
 "ethyl alcohol": "2",
 "enduronyl": "1",
 "emtricitabine/nelfinavir/tenofovir": "2",
 "effexor xr": "2",
 "endacof-dc": "2",
 "endacof-tab": "2",
 "effervescent potassium/chloride": "3",
 "endacof-dh": "2",
 "epidrin": "2",
 "exenatide": "2",
 "eldepryl": "2",
 "entuss-d jr": "2",
 "endacof-plus": "2",
 "extra strength mylanta calci tabs": "2",
 "excedrin back &amp; body": "2",
 "ed-flex": "2",
 "elite ob 400": "2",
 "edluar": "2",
 "endocodone": "2",
 "excof": "2",
 "excof-sf": "2",
 "exelon": "2",
 "esimil": "1",
 "eth-oxydose": "2",
 "entercote": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "eskalith": "2",
 "efasin expectorant sf": "2",
 "ezetimibe/simvastatin": "3",
 "ephedrine/potassium iodide": "3",
 "eperbel-s": "2",
 "empirin with codeine": "2",
 "equi-natal rx": "2",
 "echotuss-hc": "2",
 "ethchlorvynol": "2",
 "endotuss expectorant": "2",
 "everolimus": "2",
 "enalapril": "2",
 "epiklor": "3",
 "ezide": "1",
 "equagesic": "2",
 "ez iii": "2",
 "eldertonic": "2",
 "endotuss-hd": "2",
 "eprosartan/hydrochlorothiazide": "1",
 "encora": "2",
 "eliphos": "2",
 "exjade": "2",
 "excedrin extra strength": "2",
 "elppa daily": "2",
 "ethotoin": "2",
 "enditussin expectorant": "2",
 "etrafon": "2",
 "esomeprazole/naproxen": "2",
 "endacof-c": "2",
 "esgic-plus": "2",
 "ergocaf-pb": "2",
 "estazolam": "2",
 "endal-hd plus": "2",
 "equanil": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "edetate calcium disodium": "2",
 "extra strength bayer": "2",
 "etravirine": "2",
 "etodolac": "2",
 "equate allergy &amp; sinus headache": "2",
 "equi-natal z": "2",
 "ed-tuss hc": "2",
 "enplus-hd": "2",
 "ethrane": "2",
 "eskalith-cr": "2",
 "ezol": "2",
 "empirin": "2",
 "eye health formula": "2",
 "equi-natal m": "2",
 "ergocaffpb": "2",
 "excedrin": "2",
 "enduronyl forte": "1",
 "elon matrix 5000 complete": "2",
 "ed-tlc": "2",
 "entex hc": "2",
 "eze ds": "2"}, "d": {"duratuss hd": "2",
 "duramorph pf": "2",
 "dialyvite 3000": "2",
 "diazepam intensol": "2",
 "diastat": "2",
 "desflurane": "2",
 "duragesic-75": "2",
 "demi-regroton": "1",
 "drotuss-cp": "2",
 "dronedarone": "2",
 "delavirdine": "2",
 "duradal hd": "2",
 "duet dha ec": "2",
 "de-chlor g": "2",
 "doral": "2",
 "disney winnie the pooh complete": "2",
 "dizac": "2",
 "diuril": "1",
 "droperidol/fentanyl": "2",
 "diphenydramine quick melt": "2",
 "duramorph": "2",
 "dezocine": "2",
 "dolasetron": "3",
 "diltiazem/enalapril": "2",
 "dep medalone 80": "2",
 "diltiazem hydrochloride cd": "2",
 "duloxetine": "2",
 "diovan hct": "1",
 "dialyvite with zinc rx": "2",
 "dicopanol": "2",
 "disney winnie the pooh with extra c": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "desyrel": "2",
 "dexchlorpheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "dehydrated alcohol": "2",
 "dormin": "2",
 "diphedryl": "2",
 "demi-cof": "3",
 "donatuss dc": "2",
 "donatussin max": "2",
 "diphenhydramine/guaifenesin": "2",
 "donnatal extentabs": "2",
 "dexbrompheniramine/hydrocodone/phenylephrine": "2",
 "diphenhydramine/tripelennamine topical": "2",
 "ditussin-hc": "2",
 "diphenhydramine": "2",
 "dolgic plus": "2",
 "dihydrocodeine/guaifenesin/phenylephrine": "2",
 "diupres-500": "1",
 "dostinex": "2",
 "di-gel mint": "2",
 "dical captabs": "2",
 "depmedalone": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "dextrose 5% and electrolyte no. 48 injection": "3",
 "doans pm": "2",
 "dazidox": "2",
 "daily combo": "2",
 "diphenadryl": "2",
 "detuss": "2",
 "dicarbosil": "2",
 "decadron with xylocaine": "2",
 "dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "di-delamine": "2",
 "dextromethorphan/phenylephrine/pyrilamine": "2",
 "dolorex": "2",
 "duraganidin nr": "2",
 "dolgic": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "de-chlor mr": "2",
 "dph": "2",
 "dexamethasone/lidocaine": "2",
 "dolmar": "2",
 "darvon compound 32": "2",
 "duragesic-50": "2",
 "dalalone la": "2",
 "docosavit": "2",
 "dynatuss hc": "2",
 "dolacet": "2",
 "dalfopristin/quinupristin": "2",
 "dexone": "2",
 "daypro": "2",
 "duohist dh": "2",
 "dihistine dh": "2",
 "duet chewable": "2",
 "damason-p": "2",
 "diclofenac": "2",
 "dex-tuss": "2",
 "deconsal ct": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "2",
 "dihistine": "2",
 "diphenylin": "2",
 "diphenhydramine/phenylephrine": "2",
 "diphenmax": "2",
 "despec-pd": "2",
 "doxepin topical": "2",
 "dexpak taperpak": "2",
 "diphenhydramine/ibuprofen": "2",
 "dexacort phosphate in turbinaire": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "deconsal dm tannate": "2",
 "diacetazone": "2",
 "diphenyl": "2",
 "dalgan": "2",
 "donnapine": "2",
 "doxepin": "2",
 "darcalma": "2",
 "diupres-250": "1",
 "dilaudid-hp": "2",
 "diltiazem hydrochloride xt": "2",
 "digitek": "2",
 "diltiazem hydrochloride xr": "2",
 "diltiazem": "2",
 "dilaudid cough syrup": "2",
 "dolobid": "2",
 "diphen af": "2",
 "duragesic-25": "2",
 "deltasone": "2",
 "dytan-d": "2",
 "depodur": "2",
 "dihydro-pe": "2",
 "drospirenone/estradiol": "2",
 "duragesic": "2",
 "duragesic-100": "2",
 "d-tann": "2",
 "dexacort-la": "2",
 "durabac": "2",
 "duo-vil": "2",
 "dermavite": "2",
 "dialyvite 800 ultra d": "2",
 "dynex hd": "2",
 "dolomite": "2",
 "de-chlor hd": "2",
 "duet": "2",
 "de-chlor hc": "2",
 "dexamethasone": "2",
 "delhistine d": "2",
 "dialyvite 5000": "2",
 "diphen": "2",
 "donepezil": "2",
 "dilacor xr": "2",
 "diabetic tussin night time formula": "2",
 "duocet": "2",
 "diaqua": "1",
 "dilaudid": "2",
 "diphendryl": "2",
 "diltiazem hydrochloride sr": "2",
 "delsym children's night time cough &amp; cold": "2",
 "diphenmax d": "2",
 "dyrenium": "3",
 "duet dha complete": "2",
 "dalalone dp": "2",
 "deserpidine/methyclothiazide": "1",
 "decohistine expectorant": "2",
 "dexasone": "2",
 "diurese": "1",
 "donnatal": "2",
 "dutoprol": "2",
 "doans pills extra strength": "2",
 "dual action complete": "2",
 "deferasirox": "2",
 "dolagesic": "2",
 "dorzolamide/timolol ophthalmic": "2",
 "dical-d": "2",
 "duradrin": "2",
 "deconamine cx": "2",
 "darvon-n": "2",
 "darpaz": "2",
 "dihistine expectorant": "2",
 "dualvit ob": "2",
 "delta-cortef": "2",
 "dihydrocodeine/guaifenesin": "2",
 "d-tann at": "2",
 "daily multi-vitamins with minerals": "2",
 "dristan sinus": "2",
 "dopar": "2",
 "dytan": "2",
 "diurex": "2",
 "diltzac": "2",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "darvon": "2",
 "dolsed": "2",
 "dytan-hc": "2",
 "diastat acudial": "2",
 "diuretic ap-es": "1",
 "dexbrompheniramine/phenylephrine/pyrilamine": "2",
 "detussin expectorant": "2",
 "dexasone la": "2",
 "duradyne dhc": "2",
 "duragal-s": "2",
 "duratuss ac 12": "2",
 "diavite plus": "2",
 "dexamethasone intensol": "2",
 "detussin": "2",
 "dyazide": "3",
 "darvon compound-65": "2",
 "doan's pills": "2",
 "desipramine": "2",
 "diphentann-d": "2",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "disalcid": "2",
 "desyrel dividose": "2",
 "depo-medrol": "2",
 "dihydro-gp": "2",
 "decadron": "2",
 "dihydrocodeine/guaifenesin/pseudoephedrine": "2",
 "decohistine dh": "2",
 "d-tal": "2",
 "de-sone la": "2",
 "duragesic-12": "2",
 "daily multiple for men 50+": "2",
 "d-tann hc": "2",
 "duet dha": "2",
 "dytan-dm": "2",
 "durabac forte": "2",
 "dexmedetomidine": "2",
 "dexacort phosphate in respihaler": "2",
 "dewitt's pain reliever": "2",
 "dicomal-ph": "2",
 "dihydro-cp": "2",
 "delhist d": "2",
 "deconsal c expectorant": "2",
 "denzapine": "2",
 "depopred": "2",
 "d-tann dm": "2",
 "decotuss-hd": "2",
 "dolophine": "2",
 "duralone": "2",
 "disney winnie the pooh gummies": "2",
 "drospirenone/ethinyl estradiol": "2",
 "duexis": "2",
 "diuril sodium": "1",
 "di-gel lemon": "2",
 "d-tann cd": "2",
 "diastat pediatric": "2",
 "dytuss": "2",
 "doxacurium": "2",
 "darvocet-n 100": "2",
 "decadron-la": "2",
 "daily-vite weight control": "2",
 "daily multiple for women 50+": "2",
 "deserpidine/hydrochlorothiazide": "1",
 "daily multiple for women": "2",
 "dexbrompheniramine/pyrilamine": "2",
 "d-tann ct": "2",
 "deconsal ct tannate": "2",
 "diphenhist": "2",
 "dytan-at": "2",
 "dexchlorpheniramine/hydrocodone/phenylephrine": "2",
 "diutensen-r": "1",
 "dexacorten": "2",
 "dexacen-4": "2",
 "doloral": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "2",
 "diucardin": "1",
 "drituss hd": "2",
 "digoxin": "2",
 "duraxin": "2",
 "diabetic tussin c": "2",
 "dicomal-dh": "2",
 "deponit": "2",
 "diatx zn": "2",
 "darvocet-n 50": "2",
 "dalmane": "2",
 "decaject la": "2",
 "duract": "2",
 "diazepam": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "deconsal dm": "2",
 "doloral sirop": "2",
 "dolgic lq": "2",
 "diflucan": "2",
 "donnaphen": "2",
 "diphen cough": "2",
 "dexone la": "2",
 "dialyvite 800 with zinc": "2",
 "decagen": "2",
 "de-chlor nx": "2",
 "dicalphos plus d": "2",
 "dalalone": "2",
 "diphenhydramine/pseudoephedrine": "2",
 "demerol": "2",
 "diltia xt": "2",
 "deproist with codeine": "2",
 "dihydrocodeine/phenylephrine": "2",
 "dilantin": "2",
 "dihistine expectorant with codeine": "2",
 "donatussin dc": "2",
 "dytan-cd": "2",
 "diclofenac/misoprostol": "2",
 "desvenlafaxine": "2",
 "disposable enema": "3",
 "dilt-xr": "2",
 "duet dha with ferrazone": "2",
 "dytan-cs": "2",
 "darvocet a500": "2",
 "drocon-cs": "2",
 "dextrose 10% and electrolyte no 48": "3",
 "decaject": "2"}, "g": {"gilenya": "2",
 "gevrabon": "2",
 "genahist": "2",
 "glu-k": "3",
 "gua hc": "2",
 "guaifenesin/phenylephrine/pyrilamine": "2",
 "guaifen-c": "2",
 "goody's extra-strength headache powders": "2",
 "gen-k": "3",
 "genpril": "2",
 "gevratonic": "2",
 "genprin": "2",
 "gablofen": "2",
 "genace": "2",
 "guaifenesin/hydrocodone/pseudoephedrine": "2",
 "guaitussin ac": "2",
 "guaifen ac": "2",
 "guaifenesin dac liquid": "2",
 "gynovite": "2",
 "gestuss-hc": "2",
 "genapap pm": "2",
 "guiatuss dac": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylephrine/phenylpropanolamine": "2",
 "gengraf": "2",
 "garlic oil": "1",
 "geri-tonic": "2",
 "generix-t": "2",
 "guiatussin with codeine": "2",
 "goody's body pain": "2",
 "guaifenesin/hydrocodone/phenylephrine": "2",
 "guaifenesin/hydrocodone": "2",
 "gas-x with maalox extra strength": "2",
 "g-1": "2",
 "guiaplex hc": "2",
 "glutofac-mx": "2",
 "gennin-fc": "2",
 "glutofac-zx": "2",
 "gianvi": "2",
 "gold age liquid vitamins and minerals": "2",
 "gua pc": "2",
 "guaiatussin dac": "2",
 "guai-co": "2",
 "guanethidine/hydrochlorothiazide": "1",
 "gani-tuss nr": "2",
 "galantamine": "2",
 "gesticare dha dr": "2",
 "guiatuss ac": "2",
 "geritol extend": "2",
 "genacote": "2",
 "giltuss ped-c": "2",
 "garlic": "1",
 "gentex hc": "2",
 "geone": "2",
 "gleevec": "2",
 "gas-x with maalox": "2",
 "garfield complete vitamins": "2",
 "goodys headache powders": "2",
 "genasan": "2",
 "geritol complete": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylpropanolamine/pyrilamine": "2",
 "gesticare dha": "2",
 "glydeine": "2",
 "geodon": "2",
 "g-tuss": "2",
 "gelhist pediatric": "2",
 "goodys extra strength": "2",
 "gesticare": "2",
 "gerivite liquid": "2",
 "guaiatussin ac": "2",
 "guaifen dac": "2",
 "guiatussin dac": "2",
 "grepafloxacin": "2",
 "guaifenesin/hydromorphone": "2",
 "guiaphen hd": "2"}, "f": {"fingolimod": "2",
 "folgard os": "2",
 "femecal ob": "2",
 "ferrocite plus": "2",
 "fleet ez-prep": "3",
 "florinef acetate": "2",
 "fleet phospho soda": "3",
 "flutuss hc": "2",
 "fasprin": "2",
 "fentanyl": "2",
 "femcet": "2",
 "fosinopril": "2",
 "foltabs plus dha": "2",
 "flo-pred": "2",
 "fluoxetine/olanzapine": "2",
 "flintstones gummies": "2",
 "fexmid": "2",
 "fleet enema extra": "3",
 "folbee plus cz": "2",
 "foltabs prenatal plus dha": "2",
 "fioricet": "2",
 "folbecal": "2",
 "forane": "2",
 "furoxone": "2",
 "ferrex pc forte": "2",
 "flolan": "2",
 "fentanyl/ropivacaine": "2",
 "fiorinal with codeine iii": "2",
 "folivan-prx dha": "2",
 "femecal ob plus dha": "2",
 "folcaps omega 3": "2",
 "fentuss expectorant": "2",
 "flurazepam": "2",
 "fanapt": "2",
 "folivan-ec dha": "2",
 "feldene": "2",
 "florinef": "2",
 "fast acting mylanta": "2",
 "fluconazole": "2",
 "fentora": "2",
 "fosfree": "2",
 "fenoprofen": "2",
 "femnatal": "2",
 "fleet prep kit 1": "3",
 "foli-iron": "2",
 "foltabs": "2",
 "folcal dha": "2",
 "fortovase": "2",
 "frenadol": "2",
 "fiorinal": "2",
 "florical": "2",
 "femtabs": "2",
 "folivan-ob": "2",
 "formula b plus": "2",
 "flumezide": "1",
 "flexeril": "2",
 "fiortal": "2",
 "fem-natal": "2",
 "fosphenytoin": "2",
 "fioricet with codeine": "2",
 "fluvoxamine": "2",
 "fenoldopam": "2",
 "folcaps care one": "2",
 "famotidine/ibuprofen": "2",
 "furazolidone": "2",
 "flexon": "2",
 "folpace rx": "2",
 "fosamprenavir": "2",
 "floricet with codeine": "2",
 "fluphenazine": "2",
 "fluothane": "2",
 "farbital": "2",
 "freamine iii with electrolytes": "3",
 "fiorpap": "2",
 "foltabs prenatal": "2",
 "fazaclo": "2",
 "fiorinal with codeine": "2",
 "fortabs": "2",
 "forfivo xl": "2",
 "fiortal with codeine": "2",
 "formula twenty-one": "2",
 "flexoject": "2",
 "flintstones complete": "2",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "flurbiprofen": "2",
 "fludrocortisone": "2",
 "foltabs 90 plus dha": "2",
 "fiormor": "2",
 "fentanyl transdermal system": "2",
 "flintstones with calcium": "2",
 "fleet enema": "3",
 "fosinopril/hydrochlorothiazide": "2"}, "i": {"iophen": "2",
 "isoniazid/rifampin": "2",
 "icare prenatal rx": "2",
 "inderide": "2",
 "icaps lutein &amp; omega-3": "2",
 "istalol": "2",
 "invirase": "2",
 "isolyte p and 5% dextrose": "3",
 "imatinib": "2",
 "iophen-c nr": "2",
 "ibuprofen": "2",
 "icaps tr": "2",
 "ibuprofen pmr": "2",
 "idenal": "2",
 "iohist d": "2",
 "isolyte e": "3",
 "incivek": "2",
 "ibuprofen/oxycodone": "2",
 "invega": "2",
 "i-vite": "2",
 "isolyte r and 5% dextrose": "3",
 "icar prenatal chewable calcium": "2",
 "i-vite protect": "2",
 "icaps plus": "2",
 "isocom": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "ionosol b and 5% dextrose": "3",
 "isocet": "2",
 "imipramine": "2",
 "iloprost": "2",
 "inatal advance": "2",
 "inderide la": "2",
 "ibudone": "2",
 "ibuprofen/pseudoephedrine": "2",
 "ibu-tab": "2",
 "indapamide": "1",
 "itraconazole": "3",
 "intermezzo": "2",
 "iodine/potassium iodide": "3",
 "innopran xl": "2",
 "indocin iv": "2",
 "inderal la": "2",
 "inatal ultra": "2",
 "invega sustenna": "2",
 "iopidine": "2",
 "ibu-200": "2",
 "inspra": "2",
 "indocin": "2",
 "icaps areds": "2",
 "icar prenatal": "2",
 "isonarif": "2",
 "ionosol mb and 5% dextrose": "3",
 "icaps with lutein and zeaxan": "2",
 "isoflurane": "2",
 "infumorph": "2",
 "iloperidone": "2",
 "iosat": "3",
 "ide-cet": "2",
 "iotussin d liquid": "2",
 "iso-acetazone": "2",
 "iotussin hc": "2",
 "isocarboxazid": "2",
 "indocin sr": "2",
 "inderal": "2",
 "i-sense": "2",
 "intelence": "2",
 "ionosol t and 5% dextrose": "3",
 "innovar": "2",
 "indomethacin": "2",
 "infanate dha": "2",
 "isolyte h and 5 % dextrose": "3",
 "icaps mv": "2",
 "ibu-4": "2",
 "i-fol plus": "2",
 "ibu-6": "2",
 "ibu-8": "2",
 "iodal hd": "2",
 "isolyte m and 5% dextrose": "3",
 "ida": "2",
 "ibu": "2",
 "ionsys": "2",
 "i-sense occushield": "2"}, "h": {"hydeltrasol": "2",
 "hydro-reserp": "1",
 "histex hc": "2",
 "hemocyte plus": "2",
 "hydrotussin hd": "2",
 "hycodan": "2",
 "headache formula pm": "2",
 "hydro-tussin exp": "2",
 "hyophen": "2",
 "histinex hc": "2",
 "hycoclar tuss": "2",
 "hydrocodone hd": "2",
 "hydrochlorothiazide/spironolactone": "3",
 "hydrap-es": "1",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "hydex pd": "2",
 "hydrocodone/ibuprofen": "2",
 "hydrocodone/phenylephrine/pyrilamine": "2",
 "hydrodiuril": "1",
 "hyosophen": "2",
 "hydrocodone/phenylephrine": "2",
 "hydrostat ir": "2",
 "hydrophed": "2",
 "hydrocodone gf": "2",
 "hydrocodone/pseudoephedrine/triprolidine": "2",
 "histine-d": "2",
 "hydroserpine 1": "1",
 "hi-nate 90": "2",
 "histussin hc liquid": "2",
 "hydrochlorothiazide/propranolol": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "hydrotuss hc": "2",
 "hydra-zide": "1",
 "hydrochlorothiazide/telmisartan": "1",
 "hydrocodone/potassium guaiacolsulfonate": "2",
 "hydrochlorothiazide/reserpine": "1",
 "hy-kxp": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydramine cough syrup": "2",
 "hexadrol": "2",
 "homatropine/hydrocodone": "2",
 "hydron ex": "2",
 "hemax": "2",
 "hydropres-25": "1",
 "hyoscyamine/phenobarbital": "2",
 "hydron pcs": "2",
 "hydro-tuss xp": "2",
 "histalet forte": "2",
 "hydrochlorothiazide/triamterene": "3",
 "hytussin expectorant": "2",
 "hyzaar": "1",
 "helidac": "2",
 "hydrocortisone": "2",
 "hydrochlorothiazide/methyldopa": "1",
 "hydrocof-hc": "2",
 "hydropres-50": "1",
 "hycosin expectorant": "2",
 "hydrochlorothiazide/moexipril": "2",
 "h-c tussive-nr": "2",
 "histinex d": "2",
 "halflytely and bisacodyl": "3",
 "hycophen pediatric": "2",
 "hydrocod-gf": "2",
 "hycomal dh": "2",
 "hygroton": "1",
 "hycophen": "2",
 "hydrocodone/pseudoephedrine": "2",
 "hydromet": "2",
 "hydrotuss": "2",
 "hydromide": "2",
 "hydro-tussin hg": "2",
 "hycomine compound": "2",
 "hydro par": "1",
 "hydroxy compound": "2",
 "halothane": "2",
 "hydromorph contin": "2",
 "hematinic plus": "2",
 "hair booster": "2",
 "hi-tuss hc": "2",
 "histinex pv": "2",
 "hyrexin": "2",
 "hydro gp": "2",
 "hydro-pc ii": "2",
 "hydrocodone pa pediatric": "2",
 "hycomine": "2",
 "hycotuss expectorant": "2",
 "hytussin": "2",
 "haldol": "2",
 "hydrogesic": "2",
 "hyphed": "2",
 "halotussin dac": "2",
 "histussin d": "2",
 "hydrofed": "2",
 "halcion": "2",
 "hydroflumethiazide": "1",
 "hydron kgs": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hydrocodone cp": "2",
 "hydropane": "2",
 "hyphen-hd": "2",
 "haldol decanoate": "2",
 "hydrotropine": "2",
 "hydrocet": "2",
 "haltran": "2",
 "h-c tussive": "2",
 "hydrochlorothiazide/irbesartan": "1",
 "halotussin ac": "2",
 "h.p. acthar gel": "2",
 "hy-phen": "2",
 "halfprin": "2",
 "hydroserp": "1",
 "hydrochlorothiazide/timolol": "2",
 "hydroflumethiazide/reserpine": "1",
 "histatan": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hydrophene dh": "2",
 "hydro-pc ii plus": "2",
 "hydron cp": "2",
 "heartline": "2",
 "high potency": "2",
 "hydrochlorothiazide": "1",
 "hydro-dp": "2",
 "headache relief pm": "2",
 "hycet": "2",
 "hhr": "1",
 "haloperidol": "2",
 "hydralazine/hydrochlorothiazide": "1",
 "hydrocodone": "2",
 "hydromorphone": "2",
 "hydrocortone phosphate": "2",
 "hydramine compound": "2",
 "highland hc": "2",
 "hydroserpine": "1",
 "hyzine": "2",
 "hydrochlorothiazide/losartan": "1",
 "h-c tussive d": "2",
 "hexatussin": "2",
 "hydrochlorothiazide/olmesartan": "1",
 "hycomine pediatric": "2",
 "hycoclear": "2",
 "hypamine": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "1",
 "hydrocodone/potassium guaiacolsulfonate/pseudoephedrine": "2",
 "hydeltra-tba": "2",
 "hyco-dh": "2",
 "hydrocodone/phenylpropanolamine": "2",
 "hydroxyzine": "2",
 "hydro-tussin dhc": "2",
 "hydrochlorothiazide/valsartan": "1",
 "haponal": "2",
 "hydrocortone": "2",
 "histussin hc syrup": "2",
 "hytan": "2",
 "hydramine": "2",
 "hydrocodone/pheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "hydralazine plus": "1",
 "halazepam": "2"}, "k": {"klotrix": "3",
 "kadian": "2",
 "kaon-ci": "3",
 "k-phos original": "3",
 "k-pek": "2",
 "kg-tuss hd": "2",
 "klonopin": "2",
 "korlym": "2",
 "kg-dal hd": "2",
 "klor-con m15": "3",
 "kaopectate": "2",
 "k-dur 10": "3",
 "k+care et": "3",
 "k + potassium": "3",
 "kato": "3",
 "kneerelief": "2",
 "kapectolin": "2",
 "kolnatal dha": "2",
 "kg-fed": "2",
 "kenalog-10": "2",
 "kaopectate anti-diarrheal upset stomach reliever": "2",
 "key-pred": "2",
 "klor-con": "3",
 "ketoconazole": "2",
 "kaon": "3",
 "kaon-cl 10": "3",
 "k-lyte/cl": "3",
 "k-phos m.f.": "3",
 "k-phos no. 2": "3",
 "k-lor": "3",
 "kal potassium 99": "3",
 "k-tab": "3",
 "k-lyte/cl 50": "3",
 "k-effervescent": "3",
 "k-sol": "3",
 "k-tan": "2",
 "kerlone": "2",
 "klor-con/ef": "3",
 "kay ciel": "3",
 "kenaject-40": "2",
 "kemstro": "2",
 "k-8": "3",
 "klor-con/25": "3",
 "kaochlor s-f": "3",
 "kg-dal hd plus": "2",
 "k-lyte ds": "3",
 "k-lyte": "3",
 "kalcinate": "2",
 "k-dur": "3",
 "kaochlor": "3",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "ken-jec 40": "2",
 "k-dur 20": "3",
 "kao-tin bismuth subsalicylate formula": "2",
 "kg-fed pediatric expectorant": "2",
 "klor-con m20": "3",
 "klor-con 10": "3",
 "k-vescent": "3",
 "kcl": "3",
 "klonopin wafer": "2",
 "kwelcof": "2",
 "kg-fed expectorant": "2",
 "kgs-hc": "2",
 "kie": "3",
 "ketorolac": "2",
 "kaletra": "2",
 "kg-tussin": "2",
 "k-norm": "3",
 "ketek": "2",
 "k-10": "3",
 "kaon-cl 20%": "3",
 "kaopectate extra strength": "2",
 "kg-hist d": "2",
 "klor-con 8": "3",
 "k-lyte/cl 25": "3",
 "k-tan 4": "2",
 "ketoprofen": "2",
 "klor-con m10": "3",
 "k-phos neutral": "3",
 "ketek pak": "2"}, "j": {"juvisync": "3",
 "jaycof-hc": "2",
 "j-max dhc": "2",
 "jantoven": "1",
 "j-cof dhc": "2",
 "j-tan d hc": "2",
 "jumex": "2"}, "m": {"monopril hct": "2",
 "mynatal ultracap": "2",
 "maxivision eye formula": "2",
 "metubine iodide": "2",
 "m-end wc": "2",
 "morphine sulfate er": "2",
 "maxivision whole body formula": "2",
 "marthritic": "2",
 "maxifed cdx": "2",
 "multivitamin, prenatal": "2",
 "metipranolol ophthalmic": "2",
 "metahydrin": "1",
 "myci spray": "2",
 "m-oxy": "2",
 "medrol dosepak": "2",
 "mynatal rx": "2",
 "micardis hct": "1",
 "magsal": "2",
 "magnebind 400 rx": "2",
 "mycelex troche": "2",
 "mhp-a": "2",
 "microzide": "1",
 "myphetane dc": "2",
 "midazolam": "2",
 "maolate": "2",
 "maxinate": "2",
 "magnacet": "2",
 "methyclothiazide/reserpine": "1",
 "morphine": "2",
 "methacort 40": "2",
 "migracet-pb": "2",
 "mynate 90 plus": "2",
 "mylanta ultra": "2",
 "midamor": "3",
 "multi-betic": "2",
 "mylanta gelcap": "2",
 "medique pain-off": "2",
 "minizide": "1",
 "midol extended relief": "2",
 "m-phen": "2",
 "morphine lp epidural": "2",
 "mephobarbital": "2",
 "multi-day with calcium and extra iron": "2",
 "myhist-dm": "2",
 "moduretic": "3",
 "monocal": "2",
 "maalox children's relief": "2",
 "maprotiline": "2",
 "mephenytoin": "2",
 "motrin junior strength": "2",
 "mar-cof bp": "2",
 "methylcotolone": "2",
 "milnacipran": "2",
 "morphine liposomal": "2",
 "maalox advanced maximum strength chewable": "2",
 "motrin infant drops": "2",
 "multilex": "2",
 "monopril": "2",
 "motrin": "2",
 "m-clear": "2",
 "miles nervine": "2",
 "methacort 80": "2",
 "miconazole": "2",
 "motrin childrens cold": "2",
 "medicort": "2",
 "matzim la": "2",
 "magan": "2",
 "migrin-a": "2",
 "mobic": "2",
 "myadec": "2",
 "midol maximum strength cramp formula": "2",
 "methylcotol": "2",
 "maternity": "2",
 "multaq": "2",
 "mifeprex": "2",
 "mynatal pn forte": "2",
 "mynatal plus": "2",
 "metahistine d": "2",
 "mitran": "2",
 "midol pm": "2",
 "maalox max quick dissolve": "2",
 "motrin pm": "2",
 "metoprolol succinate er": "2",
 "multihistamine-d": "2",
 "methylprednisolone": "2",
 "minitabs": "2",
 "migquin": "2",
 "midol traditional": "2",
 "mission prenatal fa": "2",
 "ms/s": "2",
 "marplan": "2",
 "millipred": "2",
 "molindone": "2",
 "multi-nate 30 kit": "2",
 "mission prenatal": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "2",
 "motrin ib sinus": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "mefenamic acid": "2",
 "mi-acid double strength": "2",
 "metocurine": "2",
 "mintuss nx": "2",
 "morphine/naltrexone": "2",
 "maternity vitamin low iron": "2",
 "millipred dp": "2",
 "maxifed-g cdx": "2",
 "medrol": "2",
 "mediplex ultra": "2",
 "maternity-90": "2",
 "mynatal fc": "2",
 "magonate tablets": "2",
 "monte-g hc": "2",
 "marcof expectorant": "2",
 "mudrane gg": "2",
 "mag-phen": "2",
 "meperitab": "2",
 "multifol plus": "2",
 "mudrane": "3",
 "mycobutin": "2",
 "mifepristone": "2",
 "metoprolol": "2",
 "methoxyflurane": "2",
 "mynatal z": "2",
 "mefloquine": "2",
 "midol ib": "2",
 "mykrox": "1",
 "midol pms": "2",
 "marnatal-f": "2",
 "medent c": "2",
 "magnebind 200": "2",
 "methadose": "2",
 "mission prenatal rx": "2",
 "mepergan fortis": "2",
 "methyclothiazide": "1",
 "metaxalone": "2",
 "mono-gesic": "2",
 "mylanta supreme": "2",
 "maxivision eye &amp; body formula": "2",
 "max hc": "2",
 "methylpred dp": "2",
 "minotal": "2",
 "mission prenatal hp": "2",
 "magnesium salicylate": "2",
 "mirtazapine": "2",
 "motrin ib": "2",
 "maalox junior relief chewable": "2",
 "mi-c-t": "2",
 "mio-rel": "2",
 "meperidine": "2",
 "mag-sr with calcium": "2",
 "mst": "2",
 "morphine sulfate ir": "2",
 "maxi-tuss sa": "2",
 "multi-nate dha": "2",
 "maxifed cd": "2",
 "ms contin": "2",
 "margesic": "2",
 "mobigesic": "2",
 "maalox regular strength": "2",
 "medidex la": "2",
 "mapap pm": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "morphine rapi-ject": "2",
 "maxiflu cd": "2",
 "mintuss mr": "2",
 "maraviroc": "2",
 "maxiphen cd": "2",
 "minitran": "2",
 "migralex": "2",
 "maxifed-g cd": "2",
 "mesantoin": "2",
 "maternal 90": "2",
 "mellaril-s": "2",
 "mintex hc": "2",
 "medtuss hd": "2",
 "mitride": "2",
 "migratine": "2",
 "micrainin": "2",
 "meclofenamate": "2",
 "motrin sinus headache": "2",
 "myhist-pd": "2",
 "mynatal": "2",
 "meloxicam": "2",
 "methadone diskets": "2",
 "mintuss ms": "2",
 "multinatal plus": "2",
 "mepergan": "2",
 "migrazone": "2",
 "medigesic": "2",
 "mytussin ac": "2",
 "midchlor": "2",
 "maalox quick dissolve extra strength": "2",
 "meprozine": "2",
 "myolin": "2",
 "mebaral": "2",
 "mygracet": "2",
 "marblen": "2",
 "metolazone": "1",
 "matulane": "2",
 "maxivision ocular formula": "2",
 "mylanta child": "2",
 "morphitec": "2",
 "m-vit": "2",
 "m-clear wc": "2",
 "methenamine/sodium biphosphate": "3",
 "moduretic 5-50": "3",
 "maxi-tuss hcx": "2",
 "maxzide-25": "3",
 "magnebind 300": "2",
 "maxiflu cdx": "2",
 "methocarbamol": "2",
 "medi-seltzer": "2",
 "maxi-tuss hcg": "2",
 "momentum": "2",
 "menstrual pms": "2",
 "msir": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "m-end pe": "2",
 "micomp-pb": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "multilex-t/m+minerals": "2",
 "migrapap": "2",
 "maxi-tuss hc": "2",
 "mb-tab": "2",
 "my-a-multi": "2",
 "methotrimeprazine": "2",
 "maxiphen cdx": "2",
 "menadol": "2",
 "medralone": "2",
 "multi-nate 30 dha": "2",
 "medipred": "2",
 "m-prednisolone": "2",
 "multihistamine-d ped": "2",
 "mivacurium": "2",
 "medralone 80": "2",
 "margesic h": "2",
 "menstrual complete": "2",
 "multi-day plus minerals": "2",
 "midol pms maximum strength": "2",
 "meperidine/promethazine": "2",
 "morphine sulfate sr": "2",
 "magna-c-7 forte": "2",
 "marnatal-f plus": "2",
 "maxzide": "3",
 "mobidin": "2",
 "mynatal pn": "2",
 "medcodin": "2",
 "myogesic": "2",
 "midrin": "2",
 "marten-tab": "2",
 "micro-k 10": "3",
 "meticorten": "2",
 "mivacron": "2",
 "myvitalife": "2",
 "multivitamin with minerals": "2",
 "m-eslon": "2",
 "monteflu hc": "2",
 "mytussin dac": "2",
 "mavik": "2",
 "mibefradil": "2",
 "methdilazine": "2",
 "motrin migraine pain": "2",
 "marax df": "2",
 "maternity plus beta carotene": "2",
 "multi-nate dha extra": "2",
 "migrex": "2",
 "medique medi-seltzer": "2",
 "maxidone": "2",
 "midol maximum strength menstrual": "2",
 "maalox total relief": "2",
 "mintuss g": "2",
 "modafinil": "1",
 "m-end": "2",
 "mens pack": "2",
 "marax": "2",
 "mellaril": "2",
 "metatensin 4": "1",
 "motrin childrens": "2",
 "metatensin 2": "1",
 "medidex": "2",
 "moban": "2",
 "materna": "2",
 "m o s": "2",
 "multi-nate 30": "2",
 "megavite rx": "2",
 "meclomen": "2",
 "msp-blu": "2",
 "methylprednisolone dose pack": "2",
 "moexipril": "2",
 "methadone": "2",
 "miltown": "2",
 "motrin cold and flu": "2",
 "mesoridazine": "2",
 "micro-k": "3",
 "maximum strength stress": "2",
 "marpres": "1",
 "meprobamate": "2"}, "l": {"litecoat aspirin": "2",
 "lvp solution with potassium": "3",
 "l-tonic": "2",
 "lyrica": "2",
 "lorcet 10/650": "2",
 "lortab": "2",
 "lisinopril": "2",
 "lorcet plus": "2",
 "lariam": "2",
 "levatol": "2",
 "lopinavir/ritonavir": "2",
 "lodine": "2",
 "librax": "2",
 "lactocal-f": "2",
 "lithobid": "2",
 "levocetirizine": "2",
 "lorcet hd": "2",
 "lortuss hc": "2",
 "lufyllin-epg": "2",
 "limbitrol": "2",
 "lexuss 210 liquid": "2",
 "luminal": "2",
 "loqua": "1",
 "lodine xl": "2",
 "lysiplex plus": "2",
 "levobunolol ophthalmic": "2",
 "levall 5.0": "2",
 "lobac": "2",
 "librium": "2",
 "lazanda": "2",
 "lorzone": "2",
 "levorphanol": "2",
 "lanoxicaps": "2",
 "lithotabs": "2",
 "liqui-minic infant": "2",
 "levitra": "2",
 "liquitussin hc syrup": "2",
 "loxitane": "2",
 "larodopa": "2",
 "lortab 2.5/500": "2",
 "levsin with phenobarbital": "2",
 "leader naproxen sodium": "2",
 "licorice": "2",
 "liquituss hd": "2",
 "lorazepam intensol": "2",
 "lanoxin": "2",
 "levobetaxolol ophthalmic": "2",
 "lorazepam": "2",
 "lotensin hct": "2",
 "liquicet": "2",
 "lioresal": "2",
 "largon": "2",
 "lugol's": "3",
 "loxitane im": "2",
 "legatrin pm": "2",
 "lopressor": "2",
 "lapatinib": "2",
 "lexxel": "2",
 "laniroif": "2",
 "loxapine": "2",
 "liqui-histine-d": "2",
 "lexiva": "2",
 "latuda": "2",
 "ludiomil": "2",
 "lotrel": "2",
 "low dose asa": "2",
 "lortab 5/500": "2",
 "lortab 7.5/500": "2",
 "lanreotide": "2",
 "levrix": "2",
 "levacet": "2",
 "lioresal intrathecal": "2",
 "lortab asa": "2",
 "lozol": "1",
 "liquicough hc": "2",
 "labetalol": "2",
 "lithium": "2",
 "luvox": "2",
 "levomethadyl acetate": "2",
 "luvox cr": "2",
 "lithonate": "2",
 "loryna": "2",
 "linezolid": "2",
 "limbitrol ds": "2",
 "levo-dromoran": "2",
 "lansoprazole/naproxen": "2",
 "lortab 10/500": "2",
 "lurasidone": "2",
 "liquid pred": "2",
 "lacosamide": "2",
 "loxitane c": "2",
 "levodopa": "2",
 "lopressor hct": "2",
 "lotensin": "2",
 "leg-gesic": "2",
 "liquihistine cs": "2",
 "levoprome": "2"}, "o": {"orphengesic": "2",
 "ormazine": "2",
 "one-a-day within": "2",
 "o-cal-d": "2",
 "os-cal ultra": "2",
 "oxycodone": "2",
 "oyster shell calcium with vitamin d": "2",
 "ob natal one": "2",
 "oreticyl forte": "1",
 "os-cal 500": "2",
 "one-a-day vitacraves": "2",
 "oxaprozin": "2",
 "os-cal 500 + d": "2",
 "onsolis": "2",
 "orbivan": "2",
 "osmoprep": "3",
 "orfro": "2",
 "ocella": "2",
 "oysco d": "2",
 "oyster shell calcium": "2",
 "obnate 90": "2",
 "oxcarbazepine": "2",
 "oxycet": "2",
 "oretic": "1",
 "obtrex": "2",
 "o-cal fa": "2",
 "onfi": "2",
 "orasone": "2",
 "orudis kt": "2",
 "oxazepam": "2",
 "orudis": "2",
 "ocuvite preservision": "2",
 "ocuvite": "2",
 "optipranolol": "2",
 "one-a-day max": "2",
 "oyster cal": "2",
 "oystercal-d": "2",
 "ocuvite extra": "2",
 "one-a-day men 50 plus": "2",
 "opium tincture, deodorized": "2",
 "oravig": "2",
 "oms": "2",
 "optivite pmt": "2",
 "o-cal prenatal": "2",
 "opana er": "2",
 "oleptro": "2",
 "opium": "2",
 "oyst cal": "2",
 "optilets-m-500": "2",
 "ocuvite lutein": "2",
 "os-cal 500 + extra d": "2",
 "obegyn": "2",
 "ob complete with dha": "2",
 "ocupress": "2",
 "oreticyl 50": "1",
 "optinate": "2",
 "ob complete premier": "2",
 "oxecta": "2",
 "oxyir": "2",
 "oyster-d": "2",
 "obtrex dha": "2",
 "one-a-day weightsmart": "2",
 "occuplex": "2",
 "one-a-day women 50 plus": "2",
 "one-a-day women": "2",
 "oyster shell": "2",
 "oysco 500": "2",
 "oxymorphone": "2",
 "ostiva": "2",
 "orapred": "2",
 "oyst-cal-d": "2",
 "opium deodorized": "2",
 "oyster cal 500": "2",
 "olopatadine nasal": "2",
 "orphengesic forte": "2",
 "opti-gen": "2",
 "os-cal": "2",
 "oysco 500 with d": "2",
 "oysco d with calcium": "2",
 "opana": "2",
 "one daily with minerals": "2",
 "one tab daily with minerals": "2",
 "one-a-day men pro edge": "2",
 "octreotide": "2",
 "oyst cal 500": "2",
 "oxydose": "2",
 "oyster shell calcium 500": "2",
 "ob-20": "2",
 "orphenadrine": "2",
 "oxycontin": "2",
 "ob complete": "2",
 "orphenate": "2",
 "oyster": "2",
 "oxyfast": "2",
 "oreticyl 25": "1",
 "oramorph sr": "2",
 "ob complete 400": "2",
 "osteocit d plus": "2",
 "orlaam": "2",
 "oyster calcium": "2",
 "oruvail": "2",
 "orapred odt": "2",
 "olanzapine": "2"}, "n": {"nutrispire": "2",
 "natalcare advanced": "2",
 "nytol": "2",
 "naprosyn": "2",
 "nitroglycerin": "2",
 "narvox": "2",
 "natalcare pic forte": "2",
 "nitroquick": "2",
 "natelle prefer": "2",
 "nucodine": "2",
 "nebivolol": "2",
 "nexcede": "2",
 "novahistine expectorant": "2",
 "nu-iron v": "2",
 "natalcare": "2",
 "natarex": "2",
 "niferex-pn": "2",
 "nitrek": "2",
 "nu-med": "2",
 "naprelan": "2",
 "nizoral": "2",
 "natelle c": "2",
 "novahistine dh": "2",
 "neevo": "2",
 "nitro td patch-a": "2",
 "natelle-ez": "2",
 "nata 29 ob": "2",
 "norpramin": "2",
 "nucodine pediatric": "2",
 "norflex": "2",
 "nuco-tuss pediatric expectorant": "2",
 "natacaps": "2",
 "novastart": "2",
 "nasatuss": "2",
 "neutra-phos": "3",
 "nanovm": "2",
 "niacin/simvastatin": "3",
 "nucofed expectorant": "2",
 "nitrodisc": "2",
 "natelle one": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "nitroglyn e-r": "2",
 "nata 29 prenatal": "2",
 "novasal": "2",
 "nestabs rx": "2",
 "neoprofen": "2",
 "natalcare glosstabs": "2",
 "nariz hc": "2",
 "naldecon-cx adult": "2",
 "notuss pd": "2",
 "novadyne expectorant": "2",
 "nestabs fa": "2",
 "numorphan": "2",
 "notuss-nxd": "2",
 "nuvigil": "1",
 "natelle": "2",
 "notuss-pe": "2",
 "nilotinib": "2",
 "norgesic forte": "2",
 "norvir": "2",
 "nitrocot": "2",
 "nitro-dur": "2",
 "nazarin hc": "2",
 "normodyne": "2",
 "nalbuphine": "2",
 "neutra-phos-k": "3",
 "natafolic-ob": "2",
 "nucofed pediatric expectorant": "2",
 "nestabs": "2",
 "nytol caplet": "2",
 "nitrogard": "2",
 "natalcare rx": "2",
 "nelfinavir": "2",
 "norflex injectable": "2",
 "notuss-ac": "2",
 "natelle one dha": "2",
 "nuromax": "2",
 "notuss-nx": "2",
 "nonbac": "2",
 "naloxone/pentazocine": "2",
 "notuss": "2",
 "nitrong": "2",
 "norisodrine with calcium iodine": "2",
 "nitrol appli-kit": "2",
 "nucochem": "2",
 "nalex a 12": "2",
 "nubain": "2",
 "natatab fa": "2",
 "nitro-bid": "2",
 "nutiifac zx": "2",
 "naturetin": "1",
 "night time pain": "2",
 "nalex ac": "2",
 "norvir soft gelatin": "2",
 "nalex expectorant": "2",
 "nortriptyline": "2",
 "naqua": "1",
 "nalfon": "2",
 "nasotuss": "2",
 "nitrolingual pumpspray": "2",
 "novanatal": "2",
 "natatab rx": "2",
 "nuprin": "2",
 "numorphan hcl": "2",
 "nitro-bid iv": "2",
 "nucodine expectorant": "2",
 "neo ac": "2",
 "neoral": "2",
 "nuprin backache caplet": "2",
 "nephro calci": "2",
 "novadyne dh": "2",
 "navane": "2",
 "nuco-tuss expectorant": "2",
 "nitrostat tablets": "2",
 "new advanced formula prenatal z": "2",
 "neo hc": "2",
 "noxafil": "2",
 "neevo dha": "2",
 "naproxen sodium ds": "2",
 "nembutal sodium": "2",
 "nembutal": "2",
 "nicotinamide zcf": "2",
 "nalex-dh": "2",
 "natatab cfe": "2",
 "nadolol": "2",
 "naturetin-5": "1",
 "nimbex": "2",
 "niferex pn forte": "2",
 "norcuron": "2",
 "natalcare advanced-rf": "2",
 "nervine": "2",
 "nic 750": "2",
 "naturetin-10": "1",
 "natalcare plus": "2",
 "natalins rx": "2",
 "neo-forte": "2",
 "novasus": "2",
 "nitrostat": "2",
 "naproxen/sumatriptan": "2",
 "norwich aspirin": "2",
 "nitro-time": "2",
 "notuss-dc": "2",
 "natachew": "2",
 "notuss-forte": "2",
 "natelle plus with dha": "2",
 "natafolic-pn": "2",
 "nitrol": "2",
 "norgesic": "2",
 "nature's blend theratrum complete tablets 50 plus": "2",
 "nardil": "2",
 "natalfirst": "2",
 "novagest with codeine": "2",
 "naproxen": "2",
 "nutrinate": "2",
 "nitro-par": "2",
 "nicomide": "2",
 "nightime sleepaid": "2",
 "nabumetone": "2",
 "nexa select with dha": "2",
 "norco": "2",
 "nestabs cbf": "2",
 "nucofed": "2",
 "neo-calglucon": "2",
 "niravam": "2",
 "nitromist": "2",
 "normosol-m and 5% dextrose": "3",
 "norlac rx": "2",
 "nutravance": "2",
 "natalcare pic": "2",
 "narcof": "2",
 "natalcare cfe 60": "2",
 "natalcare three": "2",
 "nefazodone": "2",
 "naproxen/pseudoephedrine": "2",
 "natafort": "2",
 "natalins": "2",
 "nicazel": "2"}, "q": {"quenalin": "2",
 "quick-k": "3",
 "quelicin": "2",
 "quindal hd plus": "2",
 "quinapril": "2",
 "q-dryl": "2",
 "quadra-hist d pediatric": "2",
 "qual-tussin dc": "2",
 "quadra-hist d": "2",
 "quindal hd": "2",
 "quazepam": "2",
 "quetiapine": "2",
 "q-profen": "2",
 "quelicin chloride": "2",
 "q-v tussin": "2",
 "quadrinal": "3",
 "q-dryl a/f": "2",
 "quadrapax": "2",
 "quinaretic": "2"}, "p": {"paire ob plus dha": "2",
 "pramilet fa": "2",
 "predacort 50": "2",
 "poly hist hc": "2",
 "prevacid naprapac 375": "2",
 "pyrelle hb": "2",
 "potassium iodide": "3",
 "pharmagesic": "2",
 "pepto-bismol": "2",
 "prolixin": "2",
 "prohistine-d": "2",
 "prevacid naprapac": "2",
 "phospha 250 neutral": "3",
 "posture": "2",
 "phenadoz": "2",
 "procarbazine": "2",
 "prochlorperazine": "2",
 "protriptyline": "2",
 "parenteral nutrition solution w/electrolytes": "3",
 "prelief": "2",
 "phenazine 50": "2",
 "pentobarbital": "2",
 "pedia-lax enema": "3",
 "pmb": "2",
 "phoslo gelcap": "2",
 "pediacof": "3",
 "pb-hyos": "2",
 "pulmicort flexhaler": "2",
 "poly tussin ex": "2",
 "phoslo": "2",
 "promethazine vc with codeine": "2",
 "posicor": "2",
 "percocet 2.5/325": "2",
 "pyrilamine": "2",
 "poly-tussin hd": "2",
 "pnv select": "2",
 "peganone": "2",
 "prenate elite plus iron": "2",
 "precare conceive": "2",
 "procycle multi vitamin with minerals": "2",
 "phenelzine": "2",
 "pseudatex hc": "2",
 "protegra softgel": "2",
 "pheniramine/phenyltoloxamine/pyrilamine": "2",
 "propacet 100": "2",
 "poly tan": "2",
 "polytine d": "2",
 "potassium chloride": "3",
 "prenatal z advanced formula": "2",
 "prenate elite": "2",
 "potassium bicarbonate": "3",
 "pri-cortin 50": "2",
 "phrenilin with caffeine and codeine": "2",
 "poly hist dm": "2",
 "prenate advance": "2",
 "panacet": "2",
 "phosenamine": "2",
 "prinivil": "2",
 "pulmicort turbuhaler": "2",
 "pregabalin": "2",
 "prenexa with dha": "2",
 "preque 10": "2",
 "patanase": "2",
 "prenatabs rx": "2",
 "pavulon": "2",
 "phenergan": "2",
 "pediapred": "2",
 "propoxyphene": "2",
 "prenatal mr 90 fe": "2",
 "poly-histine-d": "2",
 "phos-nak": "3",
 "pyril dm": "2",
 "pharbedryl": "2",
 "propiomazine": "2",
 "prenate advanced formula": "2",
 "pamprin maximum pain": "2",
 "pred-ject-50": "2",
 "phenergan vc": "2",
 "painaid": "2",
 "polycitra": "3",
 "pr natal 430": "2",
 "percocet 7.5/500": "2",
 "pamprin multi-symptom menstrual relief": "2",
 "phenergan with dextromethorphan": "2",
 "plasma-lyte and 5% dextrose": "3",
 "perphenazine": "2",
 "prenatal 19": "2",
 "pneumotussin 2.5": "2",
 "prudoxin": "2",
 "pyrichlor pe": "2",
 "potassium bicarbonate/potassium chloride": "3",
 "potassium phosphate/sodium phosphate": "3",
 "prinzide": "2",
 "pindolol": "2",
 "phenhist expectorant": "2",
 "pancof hc": "2",
 "pr natal 400 ec": "2",
 "paxipam": "2",
 "prenafirst": "2",
 "pardryl": "2",
 "prenatal-u": "2",
 "propoxyphene compound 65": "2",
 "preterna": "2",
 "polythiazide/prazosin": "1",
 "proloprim": "2",
 "poly tan dm": "2",
 "potassium phosphate": "3",
 "prenate ultra": "2",
 "promethazine with codeine": "2",
 "primsol": "2",
 "pediatex hc": "2",
 "pms balance": "2",
 "phenoject-50": "2",
 "phosphate laxative": "3",
 "previte rx": "2",
 "precedex": "2",
 "protuss": "2",
 "predicort rp": "2",
 "prenatal mr 90": "2",
 "percogesic extra strength": "2",
 "polytine cs": "2",
 "percocet 10/325": "2",
 "pc-10": "3",
 "pediatex-ct": "2",
 "percodan-demi": "2",
 "potassium bicarbonate/sodium bicarbonate": "3",
 "primlev": "2",
 "prefera ob plus dha": "2",
 "penbutolol": "2",
 "phenaz plus": "2",
 "precare": "2",
 "p-a-c analgesic": "2",
 "prenexa": "2",
 "poly-tussin ex syrup": "2",
 "p-a-c": "2",
 "paraldehyde": "2",
 "promethazine vc": "2",
 "pancof-pd": "2",
 "pr natal 400": "2",
 "pacaps": "2",
 "propranolol": "2",
 "pristiq": "2",
 "prenatal s": "2",
 "peptic relief": "2",
 "pyril tann-12": "2",
 "prenatal h": "2",
 "pyrlex": "2",
 "prosed ec": "2",
 "pediacare children's allergy &amp; cold": "2",
 "poly-d": "2",
 "promethazine vc plain": "2",
 "percocet 7.5/325": "2",
 "predalone 50": "2",
 "potassium acid phosphate": "3",
 "potassium chloride in sodium chloride": "3",
 "promethazine dm": "2",
 "prenatal plus with 27 mg iron": "2",
 "prenacare": "2",
 "polycitra-lc": "3",
 "pre-h-cal": "2",
 "phenobarbital": "2",
 "propatuss expectorant": "2",
 "phenergan with codeine": "2",
 "polythiazide": "1",
 "preferaob": "2",
 "pneumotussin hc": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenflu cd": "2",
 "phenylhistine dh": "2",
 "prednisone": "2",
 "poly tan d": "2",
 "prenate essential dha": "2",
 "poly hist forte": "2",
 "percogesic original strength": "2",
 "pravigard pac": "2",
 "phosphasal": "2",
 "pr natal 440": "2",
 "predicort-50": "2",
 "poly-tussin ac": "2",
 "phrenilin forte": "2",
 "pamprin all day relief": "2",
 "panritis forte": "2",
 "phendal-hd": "2",
 "pan ob forte": "2",
 "pentazocine": "2",
 "primacare": "2",
 "pedituss": "3",
 "promacet": "2",
 "pulmicort nebuamp": "2",
 "prenatabs cbf": "2",
 "phenaphen with codeine": "2",
 "prednicot": "2",
 "pancuronium": "2",
 "pnv-total": "2",
 "prenatal low iron": "2",
 "potassium acetate": "3",
 "prelone": "2",
 "prenavite fc": "2",
 "prenatal multivitamins": "2",
 "pima": "3",
 "pepcid complete": "2",
 "pnv-dha plus": "2",
 "predate-50": "2",
 "primacare advantage": "2",
 "prolixin enanthate": "2",
 "percodan": "2",
 "poly-tussin xp": "2",
 "phenytek": "2",
 "prosteon": "2",
 "pseudodine c": "2",
 "poly hist dhc": "2",
 "par-f": "2",
 "prednicen-m": "2",
 "pheniramine/phenyltoloxamine/pseudoephedrine/pyrilamine": "2",
 "premesis rx": "2",
 "pyrlex pd": "2",
 "prenate gt": "2",
 "pancof": "2",
 "phenytoin sodium, prompt": "2",
 "penthrane": "2",
 "poly-histine": "2",
 "percolone": "2",
 "phena-s 12": "2",
 "prosom": "2",
 "pro-clear": "2",
 "phoslyra": "2",
 "pro-med": "2",
 "phenergan vc with codeine": "2",
 "probarimin qt": "2",
 "parcopa": "2",
 "pepto-bismol maximum strength": "2",
 "prosed ds": "2",
 "pc-cap": "2",
 "placidyl": "2",
 "pp-cap": "2",
 "phenytoin": "2",
 "paregoric": "2",
 "perindopril": "2",
 "pancof exp": "2",
 "pulmicort respules": "2",
 "prenatal ad": "2",
 "prenatal mtr with selenium": "2",
 "prenavite": "2",
 "prenatal plus": "2",
 "palladone": "2",
 "panlor dc": "2",
 "poly-tussin": "2",
 "promethazine": "2",
 "pheniramine/phenylpropanolamine/pyrilamine": "2",
 "perloxx": "2",
 "prenavite pc": "2",
 "promethazine with dextromethorphan": "2",
 "prenazyme 1+1": "2",
 "proleukin": "2",
 "pain reliever pm": "2",
 "plasma-lyte 56": "3",
 "protuss-d": "2",
 "pharbetol pm": "2",
 "polythiazide/reserpine": "1",
 "paxarel": "2",
 "prolex dh": "2",
 "preservision": "2",
 "primalev": "2",
 "prenatal plus iron": "2",
 "primacare one": "2",
 "poly-citra k crystals": "3",
 "pyridium plus": "2",
 "poly-histine cs": "2",
 "pamprin cramp menstrual pain relief": "2",
 "potassium citrate": "3",
 "paral": "2",
 "predcor": "2",
 "prednisolone": "2",
 "phenylhistine expectorant": "2",
 "pepto children's": "2",
 "promethazine with dm": "2",
 "pancof xp": "2",
 "pyril mal phenyl hcl": "2",
 "phenylhistine dh expectorant": "2",
 "pink bismuth": "2",
 "prenate plus": "2",
 "prenatabs fa": "2",
 "paraflex": "2",
 "phenylephrine/promethazine": "2",
 "permitil": "2",
 "prenate dha": "2",
 "pediacare children's allergy": "2",
 "prenate 90": "2",
 "parnate": "2",
 "p-v-tussin": "2",
 "premesyn pms": "2",
 "potassium citrate/sodium citrate": "3",
 "paliperidone": "2",
 "promethegan": "2",
 "parafon forte dsc": "2",
 "prominol": "2",
 "phendacof plus": "2",
 "primethasone": "2",
 "prostate 2.4": "2",
 "prevacid naprapac 500": "2",
 "prenatal rx": "2",
 "prenatal 1 plus 1": "2",
 "posture-d h/p": "2",
 "prenate essential": "2",
 "poly cs": "2",
 "potassium bicarbonate/potassium citrate": "3",
 "polycitra-k": "3",
 "pipecuronium": "2",
 "poly hist pd": "2",
 "potassium chloride/sodium chloride": "3",
 "pruet dha": "2",
 "procot": "2",
 "posaconazole": "2",
 "prenatal rx 1": "2",
 "p-v-tussin syrup": "2",
 "procof": "2",
 "potassium iodide/theophylline": "3",
 "phena-s": "2",
 "procalamine": "3",
 "p-hist": "2",
 "prosight": "2",
 "procof d": "2",
 "prefera ob-one": "2",
 "pnv-dha": "2",
 "pyril d": "2",
 "percocet 5/325": "2",
 "percocet 10/650": "2",
 "priftin": "2",
 "provigil": "1",
 "predaject-50": "2",
 "phenazoforte plus": "2",
 "ponstel": "2",
 "piroxicam": "2",
 "predacorten": "2",
 "pamelor": "2",
 "phenylephrine/pyrilamine": "2",
 "promazine": "2",
 "phrenilin": "2",
 "percocet": "2",
 "phenylbutazone": "2",
 "potassium acetate/potassium bicarbonate/potassium citrate": "3",
 "panasal 5/500": "2",
 "poly-tussin dhc": "2",
 "prenatal elite": "2",
 "pain relief pm extra strength": "2",
 "pms relief": "2",
 "phenergan fortis": "2",
 "prohist": "2",
 "precare premier": "2",
 "prenatal plus with beta-carotene": "2",
 "pseudoephedrine/pyrilamine": "2",
 "panlor ss": "2",
 "potassium gluconate": "3",
 "prenaplus": "2",
 "pro-red ac": "2",
 "pheniramine/phenylpropanolamine/phenyltoloxamine/pyrilamine": "2",
 "promethazine hcl with codeine": "2",
 "prolixin decanoate": "2",
 "phenflu cdx": "2",
 "phena-plus": "2",
 "pyrlex cb": "2",
 "prenatabs obn": "2",
 "phenylephrine hd": "2",
 "pamprin max menstrual pain relief": "2",
 "polyhist nc": "2",
 "pneumotussin": "2",
 "promethazine vc w/codeine": "2"}, "s": {"su-tuss hd elixir": "2",
 "skelaxin": "2",
 "saleto": "2",
 "saluron": "1",
 "surbex-750 with zinc": "2",
 "solurex": "2",
 "saquinavir": "2",
 "se-care conceive": "2",
 "sourcecf abdek": "2",
 "senetonic": "2",
 "sleep": "2",
 "surpass": "2",
 "stomach relief": "2",
 "succinylcholine": "2",
 "sourcecf chewables": "2",
 "selgene": "2",
 "sirolimus": "2",
 "slow-k": "3",
 "septra": "2",
 "saleto-800": "2",
 "subutex": "2",
 "stuart prenatal with beta carotene": "2",
 "selegiline": "2",
 "serathide": "1",
 "septra iv": "2",
 "snooze fast": "2",
 "sinemet cr": "2",
 "sulfamethoxazole/trimethoprim": "2",
 "strong iodine": "3",
 "sporanox pulsepak": "3",
 "st. joseph aspirin": "2",
 "synalgos-dc": "2",
 "sleep tab ii": "2",
 "sski": "3",
 "sonata": "2",
 "strongstart": "2",
 "subsys": "2",
 "symtan a": "2",
 "symtan": "2",
 "stelazine": "2",
 "scot-tussin original": "2",
 "serentil": "2",
 "stress maximum strength": "2",
 "sotalol hydrochloride af": "2",
 "sinemet": "2",
 "selestoject": "2",
 "sojourn": "2",
 "somnote": "2",
 "stalevo 150": "2",
 "supac": "2",
 "stuartnatal plus 3": "2",
 "saleto-400": "2",
 "siladryl": "2",
 "savella": "2",
 "strovite advance": "2",
 "sudafed 12 hour pressure+pain": "2",
 "synercid": "2",
 "sandimmune": "2",
 "soma": "2",
 "suttar-2": "2",
 "salutensin-demi": "1",
 "super calcium": "2",
 "sevoflurane": "2",
 "solu-cortef": "2",
 "st. joseph 81 mg chewable aspirin": "2",
 "salsalate": "2",
 "samsca": "2",
 "serzone": "2",
 "sulindac": "2",
 "suttar sf": "2",
 "sleepinal": "2",
 "safyral": "2",
 "stress formula with zinc": "2",
 "saleto-d": "2",
 "spantuss hd": "2",
 "suprane": "2",
 "sominex pain relief formula": "2",
 "sandostatin": "2",
 "salutensin": "1",
 "suprep": "2",
 "seconal sodium": "2",
 "sleep-ettes": "2",
 "se-natal 16": "2",
 "sublimaze": "2",
 "stalevo 75": "2",
 "saleto-600": "2",
 "stresstabs with zinc": "2",
 "ser-ap-es": "1",
 "se-care": "2",
 "sourcecf multivitamins with a,b,d,e &amp; k plus zinc": "2",
 "simcor": "3",
 "se-natal 19": "2",
 "select-ob+dha": "2",
 "skelex": "2",
 "stress 600 with zinc": "2",
 "sominex maximum strength caplet": "2",
 "sustiva": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "symbicort": "2",
 "staxyn": "2",
 "somnicaps": "2",
 "siladryl das": "2",
 "simuc-hd": "2",
 "stalevo 200": "2",
 "spectravite cardio health": "2",
 "sudafed sinus nighttime plus pain": "2",
 "se-tan dha": "2",
 "selzentry": "2",
 "super theravite-m": "2",
 "sominex": "2",
 "surpass extra strength": "2",
 "stanback fast pain relief": "2",
 "support": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "saleto-200": "2",
 "strovite": "2",
 "spectravite senior": "2",
 "s-t forte": "2",
 "sparine": "2",
 "smz-tmp ds": "2",
 "sourcecf pediatric drops": "2",
 "septra ds": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "strovite plus": "2",
 "stuartnatal plus": "2",
 "sedecal d": "2",
 "sleep-ettes d": "2",
 "sudafed pe severe cold": "2",
 "spastrin": "2",
 "se-natal 90": "2",
 "soma compound with codeine": "2",
 "st. joseph 81 mg aspirin enteric safety-coated": "2",
 "sterapred ds": "2",
 "s-t forte 2": "2",
 "sloprin": "2",
 "sourcecf softgels": "2",
 "simply sleep": "2",
 "sufentanil": "2",
 "scot-tussin allergy": "2",
 "surmontil": "2",
 "stalevo 100": "2",
 "sedapap": "2",
 "sodium salicylate": "2",
 "soma compound": "2",
 "suprep bowel prep kit": "2",
 "simvastatin/sitagliptin": "3",
 "somatuline depot": "2",
 "sufenta": "2",
 "stanback analgesic": "2",
 "serax": "2",
 "statuss green": "2",
 "seton et": "2",
 "siladryl allergy": "2",
 "sleep tabs": "2",
 "select-ob": "2",
 "sildenafil": "2",
 "syeda": "2",
 "spironolactone": "3",
 "stagesic": "2",
 "se-plete dha": "2",
 "sulfatrim": "2",
 "sporanox": "3",
 "serpex": "1",
 "seton et-ec": "2",
 "strovite advance+d": "2",
 "sterapred": "2",
 "sleepwell 2-nite": "2",
 "super high vitamins and minerals": "2",
 "sprix": "2",
 "salflex": "2",
 "siderol": "2",
 "solu-medrol": "2",
 "sleep-eze-3": "2",
 "sine-aid ib": "2",
 "support 500": "2",
 "seconal": "2",
 "sudafed pe nighttime cold": "2",
 "statex": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "saphris": "2",
 "spasmolin": "2",
 "silphen cough": "2",
 "sinequan": "2",
 "serpazide": "1",
 "suboxone": "2",
 "symbyax": "2",
 "spasquid": "2",
 "se-natal one": "2",
 "simvastatin": "3",
 "stalevo 50": "2",
 "salsitab": "2",
 "strifon fort": "2",
 "stalevo 125": "2",
 "sandostatin lar depot": "2",
 "sesame st vitamins complete": "2",
 "sodium thiosalicylate": "2",
 "stalevo": "2",
 "sotalol": "2",
 "sorine": "2",
 "src expectorant": "2",
 "stadol": "2",
 "servira": "2",
 "sss": "2",
 "strovite one": "2",
 "solurex la": "2",
 "strovite forte": "2",
 "silenor": "2",
 "siladyl sa": "2",
 "sodium oxybate": "2",
 "statuss": "2",
 "sulfatrim pediatric": "2",
 "sectral": "2",
 "seconal sodium pulvules": "2"}, "r": {"risperdal m-tab": "2",
 "robitussin-ac": "2",
 "rum-k": "3",
 "re dualvit f": "2",
 "robitussin-dac": "2",
 "rolaids regular strength": "2",
 "rexolate": "2",
 "regroton": "1",
 "re dualvit plus": "2",
 "renaplex": "2",
 "rolaids extra strength softchews": "2",
 "renatabs with iron": "2",
 "robitussin night time cough &amp; cold": "2",
 "rapacuronium": "2",
 "rolaids extra strength plus gas relief softchews": "2",
 "recal d": "2",
 "resperal": "2",
 "rifampin": "2",
 "ryna-12s": "2",
 "rhinatate pediatric": "2",
 "ryna-12x": "2",
 "remular": "2",
 "relasin-hc": "2",
 "rynesa 12s": "2",
 "risacal-d": "2",
 "roxicet": "2",
 "rivastigmine": "2",
 "robaxin-750": "2",
 "rhinogesic": "2",
 "rindal hd plus": "2",
 "razadyne": "2",
 "rescriptor": "2",
 "rimactane": "2",
 "req49+": "2",
 "renax 5.5": "2",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "rms": "2",
 "roxicodone": "2",
 "remeron": "2",
 "rolatuss": "2",
 "ryna-cx": "2",
 "ramipril": "2",
 "remifentanil": "2",
 "robitussin night time cough, cold &amp; flu": "2",
 "raxar": "2",
 "rauzide": "1",
 "rofecoxib": "2",
 "roxanol-t": "2",
 "raplon": "2",
 "rifater": "2",
 "renese-r": "1",
 "rufen": "2",
 "ryna-12": "2",
 "renate dha extra": "2",
 "r-tannamine": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "ry-t-12": "2",
 "ru-hist forte": "2",
 "rovin-nv dha": "2",
 "ridactate": "2",
 "rynatan-s pediatric": "2",
 "rifadin iv": "2",
 "relasin-hcx": "2",
 "r-tannic-s a/d": "2",
 "recal fol d": "2",
 "rifadin": "2",
 "rapamune": "2",
 "respa sa": "2",
 "restoril": "2",
 "re-pb hyos elixir": "2",
 "robaxin": "2",
 "robaxisal": "2",
 "rocuronium": "2",
 "re fac-x": "2",
 "revatio": "2",
 "razadyne er": "2",
 "rx support heartburn and acid reflux": "2",
 "rifabutin": "2",
 "roxanol 100": "2",
 "re ob 90 plus dha": "2",
 "r-tannate pediatric": "2",
 "rondameth": "1",
 "r-tannate": "2",
 "ru-tuss with hydrocodone": "2",
 "rescudose": "2",
 "risanoid plus": "2",
 "risperdal consta": "2",
 "risperidone": "2",
 "relacon-hc": "2",
 "robichem ac": "2",
 "rindal hpd": "2",
 "rightstep": "2",
 "roxiprin": "2",
 "r-tannamine pediatric": "2",
 "remodulin": "2",
 "relcof c": "2",
 "rolaids extra strength": "2",
 "rezira": "2",
 "reserpine/trichlormethiazide": "1",
 "reme hist dm": "2",
 "rectiv": "2",
 "robafen ac": "2",
 "renate": "2",
 "re ob plus dha": "2",
 "relaxazone": "2",
 "rindal-hd": "2",
 "romilar ac": "2",
 "remular-s": "2",
 "remeron soltab": "2",
 "reyataz": "2",
 "ropivacaine/sufentanil": "2",
 "resource optisource": "2",
 "reprexain": "2",
 "ru-lets m 500": "2",
 "relacon-hc nr": "2",
 "rhinatate": "2",
 "ritonavir": "2",
 "rhinocaps": "2",
 "roxilox": "2",
 "ryna-c": "2",
 "respa c&amp;c": "2",
 "reminyl": "2",
 "rolaids multi-symptom": "2",
 "renate dha": "2",
 "rasagiline": "2",
 "relafen": "2",
 "rolatuss with hydrocodone": "2",
 "reocyte plus": "2",
 "repan": "2",
 "risperdal": "2",
 "rovin-nv": "2",
 "roxicodone intensol": "2",
 "renax": "2",
 "renese": "1",
 "roxanol": "2",
 "rezulin": "2"}, "u": {"uretron": "2",
 "uro-kp-neutral": "3",
 "urimax": "2",
 "ursinus": "2",
 "urocit-k": "3",
 "utrona-c": "2",
 "uroplus": "2",
 "udamin": "2",
 "utrona": "2",
 "ultra mylanta calci tabs": "2",
 "upcal d": "2",
 "unicap senior": "2",
 "urised": "2",
 "uritact ds": "2",
 "unisom sleepmelts": "2",
 "uroplus ds": "2",
 "ultra-natal": "2",
 "uni-multihist d ped": "2",
 "urimar-t": "2",
 "urelief plus": "2",
 "uni-lev 5.0": "2",
 "uretron ds": "2",
 "ustell": "2",
 "uni-tann d": "2",
 "utira": "2",
 "unicomplex m": "2",
 "univasc": "2",
 "uni-fac zx": "2",
 "unisom sleepgels": "2",
 "urapine": "2",
 "ultimatecare one": "2",
 "u-tri-lone": "2",
 "utira-c": "2",
 "unicap m": "2",
 "udamin sp": "2",
 "uni-tann": "2",
 "uni serp": "1",
 "uritin": "2",
 "uni-cof": "2",
 "ultiva": "2",
 "usept": "2",
 "uni-cof expectorant": "2",
 "uta": "2",
 "urisym": "2",
 "ultimatecare combo": "2",
 "urogesic blue": "3",
 "url-tannate pediatric": "2",
 "unipres": "1",
 "uni tuss hc": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "unisom with pain relief": "2",
 "url-tannate": "2",
 "ultimatecare one nf": "2",
 "unicap t": "2",
 "urelle": "2",
 "uni-tricof hc": "2",
 "uni-thera m with beta carotene": "2",
 "uni-tann cs": "2",
 "ultra natalcare": "2",
 "up and up all day allergy relief d": "2",
 "ultane": "2",
 "ultimatecare advance": "2",
 "uprima": "2",
 "uro-phosphate": "3",
 "uribel": "2",
 "ultane pen": "2",
 "uniretic": "2"}, "t": {"tussionex pennkinetic": "2",
 "tl g-fol os": "2",
 "tricitrates": "3",
 "toprol-xl": "2",
 "tolmetin": "2",
 "triamterene": "3",
 "tizanidine": "3",
 "tyvaso": "2",
 "tekral": "2",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "tencet": "2",
 "temaril": "2",
 "tri-vent hc": "2",
 "tolectin 600": "2",
 "thermotabs": "3",
 "telzir": "2",
 "thiothixene": "2",
 "tannate 12d s": "2",
 "travert 10% and electrolyte no2": "3",
 "tylenol with codeine #2": "2",
 "theracal d4000": "2",
 "timolol ophthalmic": "2",
 "tri-k": "3",
 "tozal": "2",
 "tocilizumab": "2",
 "tylenol with codeine #4": "2",
 "trimethoprim": "2",
 "tylenol pm": "2",
 "tusso-df": "2",
 "titralac plus": "2",
 "trimesis rx": "2",
 "triveen-one": "2",
 "tanamine": "2",
 "timoptic": "2",
 "tekamlo": "2",
 "tri-gestan s": "2",
 "tridil": "2",
 "tums kids": "2",
 "thiethylperazine": "2",
 "t- koff": "2",
 "tetra-mag": "2",
 "tussirex sugar free": "2",
 "tranquil nighttime sleep aid": "2",
 "teveten hct": "1",
 "tenormin": "2",
 "thera-m enhanced": "2",
 "thera-m": "2",
 "trileptal": "2",
 "tacrine": "2",
 "tussafed-hcg": "2",
 "trilisate": "2",
 "treprostinil": "2",
 "talacen": "2",
 "tegretol": "2",
 "tusso-hc": "2",
 "trihist-cs": "2",
 "tolectin ds": "2",
 "theralith xr": "2",
 "theophylline ki": "3",
 "theravim m": "2",
 "therobec plus": "2",
 "triotann-s pediatric": "2",
 "theomax df": "2",
 "tums ultra 1000": "2",
 "triotann-s": "2",
 "tussin-v": "2",
 "tums regular strength": "2",
 "tanamine pediatric": "2",
 "tranxene sd": "2",
 "trandolapril/verapamil": "2",
 "tridal": "2",
 "tetrabenazine": "2",
 "t-lite": "2",
 "tussi-organidin nr": "2",
 "triaminic night time cold &amp; cough": "2",
 "tenoretic": "2",
 "trilog": "2",
 "toradol": "2",
 "tussive hc": "2",
 "triant-hc": "2",
 "taron-prx plus dha": "2",
 "tussirex": "2",
 "tri-tannate": "2",
 "tritan": "2",
 "tranxene": "2",
 "titralac plus liquid": "2",
 "twilite": "2",
 "trinatal rx": "2",
 "tolectin": "2",
 "thioridazine": "2",
 "trifluoperazine": "2",
 "talwin nx": "2",
 "tums dual action": "2",
 "trichlormethiazide": "1",
 "triazolam": "2",
 "tri-tannate pediatric": "2",
 "theracodophen low 90": "2",
 "tylenol with codeine": "2",
 "tab-a-vite maximum": "2",
 "tenoretic 50": "2",
 "thalitone": "1",
 "tricare dha one": "2",
 "tussgen expectorant": "2",
 "tylenol sore throat nighttime": "2",
 "talwin": "2",
 "tussar sf": "2",
 "tandem ob": "2",
 "toradol iv/im": "2",
 "travasol with electrolytes dual chamber": "3",
 "tussigon": "2",
 "trandate": "2",
 "tiazac": "2",
 "t-gesic": "2",
 "tussend expectorant": "2",
 "tykerb": "2",
 "theodrine": "2",
 "tussi-organidin-s nr": "2",
 "torecan": "2",
 "tofranil-pm": "2",
 "tri-histine": "2",
 "travert 5% and electrolyte no2": "3",
 "tusana-d": "2",
 "tanoral": "2",
 "tricare": "2",
 "timolide": "2",
 "total allergy": "2",
 "tuss-hc": "2",
 "tussadur-hd": "2",
 "tylenol allergy complete nighttime": "2",
 "tussend": "2",
 "telithromycin": "2",
 "tanoral pediatric": "2",
 "timoptic-xe": "2",
 "tuss-ds": "2",
 "tannihist-12d": "2",
 "trandolapril": "2",
 "t-gran plus minerals": "2",
 "temazepam": "2",
 "tussi-12d s": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "telaprevir": "2",
 "timoptic ocudose": "2",
 "talwin compound": "2",
 "therapy bayer": "2",
 "tenake": "2",
 "tasigna": "2",
 "timolol": "2",
 "tubocurarine": "2",
 "tussafin": "2",
 "tusal": "2",
 "theracal rapid repletion": "2",
 "trycet": "2",
 "theraflu warming relief sinus &amp; cold": "2",
 "tristoject": "2",
 "tusdec-hc": "2",
 "tussicaps": "2",
 "tussicle": "2",
 "trazodone": "2",
 "tl-hist cm": "2",
 "tums freshers": "2",
 "ternamar": "2",
 "tramacort-d": "2",
 "tl-hist cd": "2",
 "triacin c": "2",
 "theracal d2000": "2",
 "titralac": "2",
 "tenoretic 100": "2",
 "tri tann pediatric": "2",
 "thera-vite m": "2",
 "tranxene t-tab": "2",
 "triflupromazine": "2",
 "transderm-nitro": "2",
 "triplex ad": "2",
 "twin-k": "3",
 "triavil": "2",
 "theraflu thin strips multi symptom": "2",
 "tolvaptan": "2",
 "ten-k": "3",
 "tekturna hct": "2",
 "tums smoothies": "2",
 "tac 3": "2",
 "tussi-12d": "2",
 "trimeprazine": "2",
 "trancopal": "2",
 "trac tabs 2x": "2",
 "triadvance": "2",
 "timolide 10-25": "2",
 "tedrigen": "2",
 "tylenol with codeine #3": "2",
 "touro hc": "2",
 "tavist nighttime allergy": "2",
 "ticagrelor": "1",
 "tandem dha": "2",
 "triam-forte": "2",
 "triple tannate pediatric": "2",
 "tencon": "2",
 "tums plus": "2",
 "torisel": "2",
 "tab-a-vite weightslim": "2",
 "triamcot": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "triam-a": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "therems m": "2",
 "tusso-c": "2",
 "trimal dh": "2",
 "tegretol xr": "2",
 "terrell": "2",
 "travasol with electrolytes": "3",
 "triamonide 40": "2",
 "taron-c dha": "2",
 "tofranil": "2",
 "triaprin": "2",
 "triafed &amp; codeine": "2",
 "tri rx": "2",
 "tarka": "2",
 "trimpex": "2",
 "taron-bc": "2",
 "tusscough dhc": "2",
 "theragran-m": "2",
 "triad": "2",
 "triplex dm": "2",
 "trifed c": "2",
 "tuss-pd": "2",
 "trezix": "2",
 "tadalafil": "1",
 "tri-hydroserpine": "1",
 "triamcinolone": "2",
 "theragener-m": "2",
 "tandem plus": "2",
 "thera hematinic": "2",
 "theragener-h": "2",
 "trilafon": "2",
 "tab-a-vite womens formula": "2",
 "tussar-2": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "trimipramine": "2",
 "tylox": "2",
 "trilone": "2",
 "tricof": "2",
 "tylenol severe allergy": "2",
 "tussplex": "2",
 "tussinate": "2",
 "taztia xt": "2",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tracleer": "2",
 "tusstat": "2",
 "tribenzor": "1",
 "toradol im": "2",
 "tri-hist pediatric": "2",
 "troglitazone": "2",
 "tums extra strength 750": "2",
 "triotann": "2",
 "trihist-d": "2",
 "tussafed-hc": "2",
 "triotann pediatric": "2",
 "tri-buffered aspirin": "2",
 "tranylcypromine": "2",
 "trinate": "2",
 "taron-ec calc dha pack": "2",
 "triveen-prx rnf": "2",
 "tricosal": "2",
 "thyroshield": "3",
 "teczem": "2",
 "treximet": "2",
 "tussiden c": "2",
 "tannate v dm": "2",
 "tuinal": "2",
 "trux-adryl": "2",
 "tacaryl": "2",
 "tussgen": "2",
 "tussafin liquid": "2",
 "thorazine": "2",
 "therapeutic-m": "2",
 "triaminic thin strips cough &amp; runny nose": "2",
 "tekturna": "2",
 "tylenol allergy multi-symptom nighttime": "2",
 "tracrium": "2",
 "two-dyne": "2",
 "triaminic thin strips allergy": "2",
 "temsirolimus": "2"}, "w": {"welltuss hc": "2",
 "wellbutrin xl": "2",
 "wellbutrin sr": "2",
 "womens pack": "2",
 "warfarin": "1",
 "wellesse liquid calcium with vitamin d": "2",
 "wygesic": "2",
 "wal-nadol pm extra strength": "2",
 "wal-zyr d": "2",
 "welltuss exp": "2",
 "wellbutrin": "2"}, "v": {"vitalize plus": "2",
 "versed": "2",
 "vinate advanced": "2",
 "vistaril": "2",
 "verotin-by": "2",
 "viactiv multi-vitamin": "2",
 "vi-zac": "2",
 "vigortol liquid": "2",
 "vanspar": "2",
 "v-gan-50": "2",
 "venatal fa": "2",
 "vanex forte": "2",
 "viagra": "2",
 "vardenafil": "2",
 "valu-dryl": "2",
 "viactiv calcium flavor glides": "2",
 "vanacon": "2",
 "vica-forte": "2",
 "vinate care": "2",
 "victrelis": "2",
 "vinate good start": "2",
 "vimpat": "2",
 "vistazine": "2",
 "vicodin es": "2",
 "vitanatal ob plus dha": "2",
 "vaseretic": "2",
 "vortex": "2",
 "vinate az extra": "2",
 "valturna": "2",
 "vinate ic": "2",
 "vanacof cd": "2",
 "vytorin": "3",
 "vinate ii": "2",
 "verteporfin": "1",
 "ventuss syrup": "2",
 "viravan-p": "2",
 "viravan-s": "2",
 "vioxx": "2",
 "viravan-t": "2",
 "vitaspire": "2",
 "vinate ultra": "2",
 "vinate 90": "2",
 "vitafol-ob+dha": "2",
 "vicodin hp": "2",
 "vitaphil": "2",
 "vitelle nestabs otc": "2",
 "viracept": "2",
 "vasotuss hc": "2",
 "valdecoxib": "2",
 "vanatrip": "2",
 "vol-nate": "2",
 "vitatab mv": "2",
 "voltaren-xr": "2",
 "vicon forte": "2",
 "voriconazole": "2",
 "visvex": "2",
 "venlafaxine": "2",
 "viravan-dm": "2",
 "viratan-dm": "2",
 "valium": "2",
 "vanadom": "2",
 "vaseretic 5-12.5": "2",
 "vitamax": "2",
 "valrelease": "2",
 "vaseretic 10-25": "2",
 "vinatal forte": "2",
 "vanquish": "2",
 "vinate iii": "2",
 "visken": "2",
 "vivactil": "2",
 "vanex-hd": "2",
 "vicotuss": "2",
 "vital-d": "2",
 "vitussin expectorant": "2",
 "vaprisol": "2",
 "v-tan dm": "2",
 "vitaphil plus dha": "2",
 "vemavite prx 2": "2",
 "vimovo": "2",
 "vitamed prenatal formula": "2",
 "vestura": "2",
 "vol-plus": "2",
 "vitaphil aide": "2",
 "vazotuss hc": "2",
 "vita-zinc": "2",
 "vecuronium": "2",
 "vicoprofen": "2",
 "vita zx": "2",
 "vinacal or": "2",
 "viactiv soft calcium chews": "2",
 "veripred 20": "2",
 "vernate": "2",
 "visudyne": "1",
 "visicol": "3",
 "v-gan-25": "2",
 "vita-dec": "2",
 "vitafol pn": "2",
 "vicon plus": "2",
 "vinate pn care": "2",
 "voltaren": "2",
 "vitatrum": "2",
 "vernate advanced": "2",
 "vicap forte": "2",
 "vinate one": "2",
 "vanex expectorant": "2",
 "vitafol-ob": "2",
 "viva dha": "2",
 "vicon-c": "2",
 "vol-tab rx": "2",
 "vita-min rx": "2",
 "vfend": "2",
 "vynatal 1 plus 1": "2",
 "vetuss hc syrup": "2",
 "vinate az": "2",
 "v-c forte": "2",
 "vicodin": "2",
 "vinate c": "2",
 "vitacon forte": "2",
 "vinate m": "2",
 "vita s forte": "2",
 "vitafol": "2",
 "vinate calcium": "2",
 "vitaplex plus": "2",
 "vi-q-tuss": "2",
 "vynatal fa": "2",
 "vopac": "2",
 "viactiv multi-vitamin flavor glides": "2",
 "vinate gt": "2",
 "viogen-c": "2",
 "vicoclear": "2",
 "veletri": "2",
 "v-tann": "2",
 "vasotec": "2",
 "verotin-gr": "2",
 "vinatal 600": "2",
 "vis-phos n": "3",
 "ventavis": "2",
 "viravan-pdm": "2",
 "vicodin tuss": "2"}, "y": {"yodefan": "3",
 "ysp aspirin": "2",
 "yasmin": "2",
 "yaz": "2"}, "x": {"xanax xr": "2",
 "xanax": "2",
 "xyzal": "2",
 "xolox": "2",
 "xpect-hc": "2",
 "xalkori": "2",
 "xyrem": "2",
 "xodol": "2",
 "xenazine": "2"}, "z": {"zotex-12": "2",
 "zinc plus lozenges": "2",
 "z-cof hcx": "2",
 "zyrtec-d": "2",
 "zorprin": "2",
 "zyban": "2",
 "z-tuss ac": "2",
 "zatean-pn dha": "2",
 "zenate prenatal": "2",
 "zitamin": "2",
 "zenate": "2",
 "zatean-pn": "2",
 "zarah": "2",
 "zileuton": "1",
 "zocor": "3",
 "zyrtec": "2",
 "zyvox": "2",
 "zema pak": "2",
 "zutripro": "2",
 "zyflo": "1",
 "z-gen": "2",
 "zyrtec hives": "2",
 "ztuss zt": "2",
 "zyrtec-d 12 hour": "2",
 "zenate advanced formula": "2",
 "zemuron": "2",
 "zero-order release": "2",
 "zincvit": "2",
 "zamicet": "2",
 "zonalon": "2",
 "zebeta": "2",
 "zatean-pn plus": "2",
 "zestril": "2",
 "zolvit": "2",
 "ze-plus": "2",
 "zyprexa intramuscular": "2",
 "zodryl dec": "2",
 "zestoretic": "2",
 "zerlor": "2",
 "zipsor": "2",
 "zodryl dac": "2",
 "zebutal": "2",
 "z-bec": "2",
 "zymine hc": "2",
 "zolpidem": "2",
 "zortress": "2",
 "zyflo cr": "1",
 "zaleplon": "2",
 "z-tuss 2": "2",
 "ziprasidone": "2",
 "zaponex": "2",
 "zelapar": "2",
 "zotex hc": "2",
 "zanaflex": "3",
 "zodryl ac": "2",
 "zatean-ch": "2",
 "zyprexa": "2",
 "zotex-c": "2",
 "zotex-d": "2",
 "zydone": "2",
 "zyprexa zydis": "2",
 "z-cof hc": "2",
 "zaroxolyn": "1",
 "zyprexa relprevv": "2",
 "zetran": "2",
 "ziac": "2",
 "zodeac-100": "2",
 "zolpimist": "2"}}];