interactions["amlodipine-atorvastatin,caduet"]=["amlodipine-atorvastatin,caduet", {"5": {"50 + companion": "2"}, "8": {"8-mop": "2"}, "a": {"aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aristocort": "2",
 "alfenta": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "1",
 "advil liqui-gels": "2",
 "antispas": "2",
 "aflaxen": "2",
 "asenapine": "2",
 "antioxidant formula": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "1",
 "advil pm": "2",
 "accesspak for hiv pep expanded with kaletra": "3",
 "alcalak": "2",
 "acid gone": "1",
 "auranofin": "2",
 "amitriptyline/perphenazine": "2",
 "advanced am/pm": "2",
 "aspirin buffered": "2",
 "azilsartan medoxomil/chlorthalidone": "1",
 "aminosyn ii with electrolytes": "2",
 "aurolate": "2",
 "advil cold and sinus liqui-gels": "2",
 "anhydrous calcium iodide/codeine": "2",
 "acetaminophen/aspirin": "2",
 "all day pain relief": "2",
 "azmacort": "2",
 "avonex prefilled syringe": "2",
 "aristopak": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "alka-seltzer extra strength": "2",
 "aliskiren/valsartan": "2",
 "acetaminophen/aspirin/caffeine": "2",
 "anergan 50": "2",
 "adrenocot": "2",
 "aminosyn ii 4.25%-dextrose 20%,electrolyte,ca": "2",
 "aspir-low": "2",
 "apresoline": "2",
 "arthriten": "2",
 "acthar": "2",
 "acebutolol": "2",
 "afeditab cr": "2",
 "amigesic": "2",
 "aquatensen": "1",
 "amitone": "2",
 "abc plus senior": "2",
 "aluminum hydroxide/mineral oil": "1",
 "alka-seltzer lemon-lime": "2",
 "allfen cd": "2",
 "amlodipine/benazepril": "1",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "1",
 "aldroxicon i": "1",
 "aldoril d50": "1",
 "amobarbital/secobarbital": "2",
 "adgyn estro": "1",
 "actiprofen": "2",
 "avinza": "2",
 "alyacen 1/35": "1",
 "adalat": "2",
 "altavera": "1",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "1",
 "adcetris": "2",
 "amoxicillin/clarithromycin/lansoprazole": "3",
 "alkums": "2",
 "aspirin": "2",
 "adlone-80": "2",
 "apresazide": "2",
 "aquacot": "1",
 "aristospan": "2",
 "apo-go": "2",
 "advil junior strength": "2",
 "adbeon": "2",
 "aripiprazole": "2",
 "almacone": "1",
 "actron": "2",
 "alphagan": "1",
 "alamag plus": "1",
 "arthrotec": "2",
 "amiloride/hydrochlorothiazide": "1",
 "anhydrous calcium iodide/isoproterenol": "2",
 "acth": "2",
 "alesse": "1",
 "aluminum hydroxide/magnesium hydroxide": "1",
 "acid reducer + antacid dual action": "2",
 "adeks": "2",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "1",
 "advil cold and sinus": "2",
 "aspir-mox ib": "2",
 "ambifed cd": "2",
 "advil children's": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "abilify discmelt": "2",
 "azithromycin dose pack": "2",
 "anacin": "2",
 "aluminum hydroxide": "1",
 "accolate": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "aspirin/oxycodone": "2",
 "alu-tab": "1",
 "aspir-mox": "2",
 "ambenyl": "2",
 "atrosept": "2",
 "aralen hydrochloride": "2",
 "antara": "3",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "aricept odt": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "atacand hct": "1",
 "aranelle": "1",
 "amlobenz": "1",
 "azilect": "2",
 "accuretic": "1",
 "aerodiol": "1",
 "aurothioglucose": "2",
 "aspir 81": "2",
 "arava": "3",
 "advicor": "3",
 "acid gone antacid": "1",
 "adult strength": "2",
 "atapryl": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "a-g profen": "2",
 "aldroxicon ii": "1",
 "acetocot": "2",
 "adalimumab": "2",
 "alkabel-sr": "2",
 "almacone-2": "1",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "aralen": "2",
 "amethia": "1",
 "anectine": "2",
 "aldoril 25": "1",
 "alka-seltzer pm": "2",
 "advance care plus": "2",
 "advil migraine": "2",
 "all day relief": "2",
 "advanced formula di-gel": "2",
 "aquadeks": "2",
 "angeliq": "1",
 "advil infant's concentrated drops": "2",
 "alka-mints": "2",
 "alka-seltzer plus cold formula": "2",
 "antispasmodic": "2",
 "ami-lac": "2",
 "apokyn": "2",
 "aspirin/diphenhydramine": "2",
 "acetaminophen/codeine": "2",
 "antrocol": "2",
 "arduan": "2",
 "aspirin/carisoprodol/codeine": "2",
 "allerfrin with codeine": "2",
 "amifostine": "2",
 "aceta w/ codeine": "2",
 "aldactazide": "1",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "aldoclor-150": "1",
 "alu-cap": "1",
 "azithromycin": "2",
 "aminosyn with electrolytes sulfite-free": "2",
 "airacof": "2",
 "ascriptin": "2",
 "atenolol/chlorthalidone": "2",
 "aquest": "1",
 "apri": "1",
 "aliskiren": "2",
 "aldoril d30": "1",
 "aquadeks pediatric": "2",
 "advil": "2",
 "aspirtab": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "alora": "1",
 "atazanavir": "3",
 "aspirin/codeine": "2",
 "aspirin/pentazocine": "2",
 "antabuse": "2",
 "aloh-gel": "1",
 "aygestin": "1",
 "arthritis foundation pain reliever": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "1",
 "antioxid caplets": "2",
 "aspirin/hydrocodone": "2",
 "agenerase": "3",
 "aspirin/meprobamate": "2",
 "aricept": "2",
 "actiq": "2",
 "altocor": "2",
 "alternagel": "1",
 "aspergum": "2",
 "allfen cdx": "2",
 "aldoril 15": "1",
 "amphojel": "1",
 "aminatal plus new formula": "2",
 "addaprin": "2",
 "anaflex": "2",
 "apraclonidine ophthalmic": "2",
 "anaprox": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "atripla": "2",
 "abraxane": "2",
 "aminosyn ii 3.5%-dextrose 25%,electrolytes,ca": "2",
 "aspirin/methocarbamol": "2",
 "ambophen": "2",
 "amen": "1",
 "aminatal plus one": "2",
 "arthropan": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "alka-seltzer original": "2",
 "apo-go pen": "2",
 "aminosyn with electrolytes": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "acetylsalicylic acid": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "anacin advanced headache formula": "2",
 "acetaminophen/oxycodone": "2",
 "acid controller complete dual action": "2",
 "abc to z": "2",
 "anectine flo-pack": "2",
 "altace": "1",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "anacin max strength": "2",
 "apetigen-plus": "2",
 "atamet": "2",
 "activella": "1",
 "avonex": "2",
 "alahist dhc": "2",
 "acetaminophen/propoxyphene": "2",
 "aplenzin": "2",
 "aspirin/dipyridamole": "2",
 "acuprin 81": "2",
 "alfentanil": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "avail calcium intensive": "2",
 "ambifed-g cd": "2",
 "anaprox-ds": "2",
 "aralen phosphate": "2",
 "atabex ec": "2",
 "alamag": "1",
 "aspirin/phenyltoloxamine": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "acthrel": "2",
 "astramorph pf": "2",
 "armodafinil": "1",
 "amprenavir": "3",
 "aspirin lite coat": "2",
 "amethia lo": "1",
 "aquazide h": "1",
 "anzemet": "3",
 "amturnide": "2",
 "amiodarone": "2",
 "azithromycin/trovafloxacin": "2",
 "ansaid": "2",
 "aspirin low strength": "2",
 "abacavir/lamivudine/zidovudine": "2",
 "aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "adrenocot la": "2",
 "ascriptin enteric": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "azdone": "2",
 "aspiritab": "2",
 "aldoril": "1",
 "apatate forte": "2",
 "arranon": "2",
 "adgan": "2",
 "amethyst": "1",
 "alor 5/500": "2",
 "argesic-sa": "2",
 "alka-seltzer plus flu formula": "2",
 "abilify": "2",
 "acetaminophen/caffeine/dihydrocodeine": "2",
 "alyacen 7/7/7": "1",
 "aspirin/pravastatin": "2",
 "alesse-21": "1",
 "arthritis pain": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "aldesleukin": "2",
 "alesse-28": "1",
 "a-hydrocort": "2",
 "aminosyn ii 4.25%-dextrose 25%,electrolyte,ca": "2",
 "aspirin/caffeine": "2",
 "aptivus": "3",
 "accesspak for hiv pep expanded with viracept": "3",
 "ambifed-g cdx": "2",
 "advil children's allergy sinus": "2",
 "aleve": "2",
 "atenolol": "2",
 "aminate": "2",
 "altoprev": "2",
 "aminatal plus": "2",
 "accupril": "1",
 "aliskiren/amlodipine": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "actemra": "2",
 "a-methapred": "2",
 "alka-seltzer wake-up call!": "2",
 "aggrenox": "2",
 "advil allergy sinus": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "aspirin/pseudoephedrine": "2",
 "ascriptin maximum strength": "2",
 "aceon": "1",
 "aristocort for injection": "2",
 "avalide": "1",
 "aminate with 90 mg iron": "2",
 "apomorphine": "2",
 "advil children's cold": "2",
 "aspirin/butalbital/caffeine": "2",
 "anisindione": "1",
 "arthritis pain formula": "2",
 "alenic alka tablet": "1",
 "aprepitant": "2",
 "actonel with calcium": "2",
 "ak-beta": "2",
 "acid gone extra strength": "1",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "adalat cc": "2",
 "acetaminophen/aspirin/phenylpropanolamine": "2",
 "aspirin/calcium carbonate": "2",
 "aleve-d sinus &amp; cold": "2",
 "aldoclor-250": "1",
 "azurette": "1",
 "alka-seltzer plus immunity complex": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "alphagan p": "1",
 "adcirca": "1",
 "aspirin/caffeine/propoxyphene": "2",
 "acetaminophen/pentazocine": "2",
 "adlone-40": "2",
 "ami-natal plus one improved": "2",
 "atropine/phenobarbital": "2",
 "aspirin/carisoprodol": "2",
 "alphen expectorant": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "aspircaf": "2",
 "antioxidant ultra formula": "2",
 "alkets": "2",
 "aspirin/butalbital": "2",
 "anemagen ob": "2",
 "alenic alka": "1",
 "abstral": "2",
 "ala-hist ac": "2",
 "atracurium": "2",
 "aminosyn ii with electrolytes sulfite-free": "2",
 "atromid-s": "3",
 "aspirin/caffeine/salicylamide": "2",
 "aviane": "1",
 "ambifed cdx": "2"}, "c": {"calcitab": "2",
 "colcrys": "3",
 "calcium carbonate/risedronate": "2",
 "calcifolic-d": "2",
 "capozide 50/25": "1",
 "cerivastatin": "2",
 "calcidrine": "2",
 "calcionate": "2",
 "concept dha": "2",
 "combunox": "2",
 "chlorthalidone/reserpine": "1",
 "cortisone": "2",
 "compound 374": "2",
 "capoten": "1",
 "corzide 40/5": "2",
 "calcium oyster shell": "2",
 "colestid": "1",
 "calcid": "2",
 "co natal fa": "2",
 "celestone phosphate": "2",
 "cyclosporine": "3",
 "clozapine": "2",
 "capital w/codeine": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "cmt": "2",
 "colchicine/probenecid": "3",
 "cocet plus": "2",
 "codeine/promethazine": "2",
 "cardizem la": "2",
 "celestone": "2",
 "caltrate colon health": "2",
 "compazine spansule": "2",
 "colestid flavored": "1",
 "carbidopa/entacapone/levodopa": "2",
 "cerovite senior": "2",
 "coreg cr": "2",
 "citracal calcium gummies": "2",
 "combivir": "2",
 "conceptionxr msf": "2",
 "centrum special energy": "2",
 "calafol rx": "2",
 "calcium gluceptate": "2",
 "calcium lactate": "2",
 "calcium glycerophosphate": "2",
 "caromega": "2",
 "cezin-s": "2",
 "centussin dhc": "2",
 "children's motrin": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "citracal regular": "2",
 "calcium carbonate/magnesium carbonate": "2",
 "cyclafem 7/7/7": "1",
 "clinoril": "2",
 "climara pro": "1",
 "centrum cardio": "2",
 "co-histine dh": "2",
 "centrum silver": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "cardizem monovial": "2",
 "codehist dh": "2",
 "carbatrol": "2",
 "carenatal dha": "2",
 "centrum silver ultra men's": "2",
 "cal-gest": "2",
 "chlorpheniramine/codeine": "2",
 "conjugated estrogens/methyltestosterone": "1",
 "chloroquine": "2",
 "chlorpromazine": "2",
 "centrum jr with extra calcium": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "calcium disodium versenate": "2",
 "cotabflu": "2",
 "capozide 50/15": "1",
 "codeprex": "2",
 "codahistine-dh elixir": "2",
 "caffeine/magnesium salicylate": "2",
 "cell-u-jec": "2",
 "chloracol": "2",
 "codeine/phenylephrine/promethazine": "2",
 "cortone acetate": "2",
 "chewable calcium with vitamin d": "2",
 "cocet": "2",
 "cystemms-v": "2",
 "clusimar": "2",
 "carisoprodol compound": "2",
 "choline salicylate/magnesium salicylate": "2",
 "colrex compound": "2",
 "cryselle": "1",
 "covera-hs": "2",
 "cyclogest": "1",
 "citracal plus bone density builder": "2",
 "citracal plus heart health": "2",
 "certolizumab": "2",
 "centrum": "2",
 "camrese": "1",
 "cenogen ultra": "2",
 "capozide 25/25": "1",
 "certagen": "2",
 "citranatal 90 dha": "2",
 "calci-chew": "2",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "centratex": "2",
 "cardoxin": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "calcium carbonate/fluoride": "2",
 "combi rx": "2",
 "cabazitaxel": "2",
 "cardizem sr": "2",
 "cerovite advanced formula": "2",
 "cort-k": "2",
 "cheratussin dac": "2",
 "corvita 150": "2",
 "chlorothiazide/reserpine": "1",
 "calan sr": "2",
 "cortenema": "2",
 "climara": "1",
 "carozide": "1",
 "citranatal harmony": "2",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "calcium phosphate, tribasic": "2",
 "calcium gluconate": "2",
 "chromagen ob": "2",
 "codafen": "2",
 "conjugated estrogens/meprobamate": "1",
 "codafed": "2",
 "carteolol ophthalmic": "2",
 "cubicin": "2",
 "comfort pac with naproxen": "2",
 "complete-rf": "2",
 "codegest expectorant": "2",
 "corzide 80/5": "2",
 "colrex": "2",
 "centrum silver women's": "2",
 "certavite with antioxidants": "2",
 "chlorotrianisene": "1",
 "compro": "2",
 "clozaril": "2",
 "cerovite junior": "2",
 "caltrate 600+d": "2",
 "chlorcyclizine/codeine": "2",
 "centrum kids": "2",
 "cal-g": "2",
 "citracal maximum": "2",
 "caltrate 600 plus": "2",
 "chlorthalidone/clonidine": "1",
 "certagen senior": "2",
 "central-vite": "2",
 "cosopt": "2",
 "calcium 600 d": "2",
 "centrum special heart": "2",
 "cisatracurium": "2",
 "cordarone iv": "2",
 "circavite t": "2",
 "completenate": "2",
 "cataflam": "2",
 "capozide 25/15": "1",
 "citracal plus magnesium": "2",
 "certavite": "2",
 "caldolor": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "cope": "2",
 "carboplatin novaplus": "2",
 "childrens kaopectate": "2",
 "coldcough syrup": "2",
 "cosyntropin": "2",
 "cesia": "1",
 "caltrate 600 with iron and vitamin d": "2",
 "cycofed": "2",
 "compazine": "2",
 "celestone soluspan": "2",
 "complete natal dha": "2",
 "citrus calcium with vitamin d": "2",
 "captopril/hydrochlorothiazide": "1",
 "climaval": "1",
 "calcarb": "2",
 "citranatal rx": "2",
 "complete a-z": "2",
 "cerovite liquid": "2",
 "calcium/vitamin d": "2",
 "certa-vite": "2",
 "calcium concentrate": "2",
 "colocort": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "calphosan": "2",
 "calcifol": "2",
 "centrum ultra men's": "2",
 "covaryx hs": "1",
 "chardonna-2": "2",
 "coumadin": "1",
 "capozide": "1",
 "corticorelin": "2",
 "calcium liquid softgel": "2",
 "cortef": "2",
 "centrum ultra women's": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "caltrate gummy bites": "2",
 "cotab a": "2",
 "caltrate": "2",
 "cimzia": "2",
 "cvs extra strength headache relief": "2",
 "certa-vite senior plus lutein": "2",
 "citracal kosher": "2",
 "crestor": "2",
 "cal-nate": "2",
 "cambia": "2",
 "century senior": "2",
 "combigan": "2",
 "cisplatin": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "corvite free": "2",
 "cycofed pediatric expectorant": "2",
 "calcium chloride": "2",
 "cotab ax": "2",
 "centrum silver ultra women's": "2",
 "cholestyramine": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "clopidogrel": "2",
 "cavan-heme ob": "2",
 "carbidopa/levodopa": "2",
 "corlopam": "2",
 "co-histine expectorant": "2",
 "cheracol with codeine": "2",
 "corticotropin": "2",
 "clotrimazole": "2",
 "century-vite": "2",
 "chloromycetin sodium succinate": "2",
 "cardizem": "2",
 "cortrosyn": "2",
 "citracal + d": "2",
 "citracal prenatal rx": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "calan": "2",
 "centrum silver men's": "2",
 "candesartan/hydrochlorothiazide": "1",
 "clorpres": "1",
 "certagen senior with lutein": "2",
 "conivaptan": "3",
 "carboplatin": "2",
 "clopine": "2",
 "clarithromycin": "3",
 "clolar": "2",
 "corvita": "2",
 "corvite": "2",
 "citracal prenatal 90+dha": "2",
 "cystex": "2",
 "codeine/phenylephrine": "2",
 "calcitrate with d": "2",
 "caltrate 600 with d plus soy": "2",
 "cyclessa": "1",
 "colestipol": "1",
 "caltro with vitamin d": "2",
 "cymbalta": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "cal oys": "2",
 "carbamazepine": "2",
 "cyndal expectorant": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "carvedilol": "2",
 "cal-glu": "2",
 "codimal ph": "2",
 "clinagen la 40": "1",
 "caziant": "1",
 "citranatal assure": "2",
 "calci mix": "2",
 "citranatal dha": "2",
 "codafed pediatric": "2",
 "cafgesic forte": "2",
 "century": "2",
 "chloramphenicol": "2",
 "corvite 150": "2",
 "companion multi": "2",
 "captopril": "1",
 "calcium, magnesium and zinc": "2",
 "calcium acetate/magnesium carbonate": "2",
 "complete natal": "2",
 "cholestyramine light": "2",
 "cavan-folate dha": "2",
 "codeine/guaifenesin": "2",
 "calvite p": "2",
 "camreselo": "1",
 "calcium glycerophosphate/calcium lactate": "2",
 "codeine phosphate-promethazine hcl": "2",
 "chlorothiazide": "1",
 "calcium acetate": "2",
 "calcium glubionate": "2",
 "cosopt pf": "2",
 "concept ob": "2",
 "codeine": "2",
 "citracal petites": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "crizotinib": "2",
 "caltro": "2",
 "cialis": "1",
 "chooz": "2",
 "calcet plus": "2",
 "chlorothiazide/methyldopa": "1",
 "cascara sagrada/magnesium hydroxide": "1",
 "centavite": "2",
 "cartia xt": "2",
 "cerebyx": "2",
 "chemdal expectorant": "2",
 "coldcough pd": "2",
 "conjugated estrogens": "1",
 "cycrin": "1",
 "calcarb with d": "2",
 "crixivan": "3",
 "codahistine expectorant": "2",
 "cardizem cd": "2",
 "childrens ibuprofen berry": "2",
 "choline magnesium trisalicylate": "2",
 "cyclafem 1/35": "1",
 "corgard": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "carbex": "2",
 "climodien": "1",
 "cavan folate": "2",
 "centrum performance": "2",
 "cycofed expectorant": "2",
 "corzide": "2",
 "cabergoline": "2",
 "caltrate plus": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "covaryx": "1",
 "codeine/pseudoephedrine": "2",
 "citracal regular 250 mg + d": "2",
 "cortifoam": "2",
 "conjugated estrogens topical": "1",
 "calcium carbonate/simethicone": "2",
 "clofarabine": "2",
 "conjugated estrogens/medroxyprogesterone": "1",
 "camila": "1",
 "centrum specialist vision": "2",
 "cap-profen": "2",
 "central": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "clozapine synthon": "2",
 "combipatch": "1",
 "capital with codeine suspension": "2",
 "cordarone": "2",
 "cenestin": "1",
 "cognex": "2",
 "calcio del mar": "2",
 "colchicine": "3",
 "chloromycetin": "2",
 "calcium carbonate": "2",
 "clinalog": "2",
 "clinacort": "2",
 "cavan ec dha plus": "2",
 "calcet": "2",
 "cartrol": "2",
 "clotrimazole troche": "2",
 "calciquid": "2",
 "cotolone": "2",
 "choline salicylate": "2",
 "cf vite": "2",
 "carteolol": "2",
 "clinimix e sulfite free": "2",
 "calcium oyster": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "crinone": "1",
 "certavite with lutein": "2",
 "caltrate 600+d plus minerals": "2",
 "cheratussin ac": "2",
 "compete": "2",
 "curretab": "1",
 "citranatal b-calm": "2",
 "calphron": "2",
 "conceptionxr rhf": "2",
 "citracal slow release 1200": "2",
 "chlorthalidone": "1",
 "citracal prenatal + dha": "2",
 "combiflex es": "2",
 "coreg": "2",
 "cavan one": "2",
 "calcium citrate": "2",
 "clofibrate": "3",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "codeine/pseudoephedrine/triprolidine": "2"}, "b": {"bellaphen-s": "2",
 "betaxolol": "2",
 "biaxin xl": "3",
 "butisol sodium": "2",
 "bitex liquid": "2",
 "brevibloc": "2",
 "bugs bunny complete": "2",
 "betoptic": "2",
 "betagan c-cap": "2",
 "butorphanol": "2",
 "biaxin": "3",
 "bystolic": "2",
 "buffasal": "2",
 "betoptic s": "2",
 "benzthiazide": "1",
 "bayer pm": "2",
 "bayer aspirin extra strength plus": "2",
 "b c powder arthritis strength": "2",
 "bromodiphenhydramine/codeine": "2",
 "benicar hct": "1",
 "buspirone": "2",
 "bel-phen-ergot": "2",
 "brimonidine/timolol ophthalmic": "2",
 "bayer women's aspirin with calcium": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "beelith": "2",
 "betaxolol ophthalmic": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "bacmin": "2",
 "betapace af": "2",
 "belladonna/butabarbital": "2",
 "bayer children's aspirin": "2",
 "briellyn": "1",
 "buspar": "2",
 "brovex pb cx": "2",
 "betapace": "2",
 "b3-500-gr": "3",
 "b c powder": "2",
 "biotin forte with zinc": "2",
 "bayer extra strength back &amp; body": "2",
 "bortezomib": "2",
 "beta-phos/ac": "2",
 "brovex cbx": "2",
 "biotussin dac": "2",
 "buffered aspirin": "2",
 "butrans": "2",
 "beyaz": "1",
 "budeprion sr": "2",
 "bupivacaine/hydromorphone": "2",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "betaseron": "2",
 "becomax rx": "2",
 "bidil": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "betagan": "2",
 "bayer aspirin": "2",
 "balacet": "2",
 "b-nexa": "2",
 "bellaspas": "2",
 "black cohosh": "2",
 "betamethasone": "2",
 "boceprevir": "3",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismatrol maximum strength": "2",
 "baycadron": "2",
 "bp multinatal plus chewables": "2",
 "bellamine": "2",
 "bufferin low dose": "2",
 "bayer select backache pain formula": "2",
 "bel-tabs": "2",
 "bendroflumethiazide": "1",
 "belladonna/opium": "2",
 "bendroflumethiazide/nadolol": "2",
 "bupropion": "2",
 "bismatrol": "2",
 "berocca plus": "2",
 "bayer advanced aspirin": "2",
 "brovex cb": "2",
 "balziva": "1",
 "bayer am": "2",
 "brimonidine ophthalmic": "1",
 "bosentan": "2",
 "bc headache": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "budeprion": "2",
 "bladder 2.2": "2",
 "bayer aspirin with heart advantage": "2",
 "budesonide/formoterol": "2",
 "butibel": "2",
 "bendroflumethiazide/rauwolfia serpentina": "1",
 "brentuximab": "2",
 "bromfenac": "2",
 "buprenorphine/naloxone": "2",
 "betimol": "2",
 "brompheniramine/codeine": "2",
 "b-plex plus minerals": "2",
 "buprenex": "2",
 "b &amp; o supprettes": "2",
 "bismuth subsalicylate": "2",
 "brovex pb c": "2",
 "budeprion xl": "2",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "buprenorphine": "2",
 "betamed": "2",
 "bayer aspirin regimen": "2",
 "butabarbital": "2",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine s": "2",
 "bufferin": "2",
 "bellatal er": "2",
 "blocadren": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "bayer women's low dose plus calcium": "2",
 "benazepril/hydrochlorothiazide": "1",
 "bee-zee": "2",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "b-3-50": "3",
 "brontex": "2",
 "bisoprolol": "2",
 "brilinta": "1",
 "bupivacaine/fentanyl": "2",
 "betaxon": "2",
 "butalbital compound": "2",
 "bismarex": "2",
 "buffex": "2",
 "budesonide": "2",
 "benazepril": "1",
 "bellamor": "2",
 "bufferin arthritis strength": "2",
 "bedol": "1",
 "bufferin extra strength": "2",
 "bc fast pain relief": "2",
 "busodium": "2",
 "buproban": "2",
 "berplex plus": "2",
 "barbidonna": "2",
 "baycol": "2",
 "bexarotene": "1",
 "bright beginnings": "2",
 "bellatal": "2",
 "bubbli-pred": "2",
 "brompheniramine/codeine/pseudoephedrine": "2",
 "brevicon": "1"}, "e": {"essentia": "2",
 "ecotrin maximum strength": "2",
 "entaprin": "2",
 "estragyn la 5": "1",
 "estrace": "1",
 "emsam": "2",
 "estrofem": "1",
 "estraderm": "1",
 "equilet": "2",
 "ethinyl estradiol/levonorgestrel": "1",
 "ephedrine/phenobarbital/theophylline": "2",
 "enpresse": "1",
 "ec-naprosyn": "2",
 "e.e.s.-400": "3",
 "endacof-ac": "2",
 "emend": "2",
 "estrostep fe": "1",
 "estrace vaginal cream": "1",
 "estrapatch": "1",
 "evamist": "1",
 "ex-lax milk of magnesia": "1",
 "eryped": "3",
 "estro-a": "1",
 "estradiol": "1",
 "emagrin": "2",
 "enflurane": "2",
 "estreva": "1",
 "estratest": "1",
 "ezetimibe": "2",
 "ethinyl estradiol": "1",
 "etoposide": "2",
 "epoprostenol": "2",
 "endocet": "2",
 "estradiol patch": "1",
 "effervescent pain relief": "2",
 "elestrin": "1",
 "embeda": "2",
 "exalgo": "2",
 "eperbel-s": "2",
 "exforge hct": "1",
 "exelon": "2",
 "eemt": "1",
 "estrone aq": "1",
 "esidrix": "1",
 "erythrocot": "3",
 "elemental iron-90": "2",
 "extavia": "2",
 "estro-la": "1",
 "erythromycin": "3",
 "essian": "1",
 "estradot": "1",
 "ecotrin adult low strength": "2",
 "estratab": "1",
 "etopophos": "2",
 "equi-natal plus": "2",
 "ellis tonic sherry": "2",
 "edge ob": "2",
 "easprin": "2",
 "endal expectorant": "2",
 "elixiral": "2",
 "execlear-c": "2",
 "emoquette": "1",
 "estinyl": "1",
 "edarbyclor": "1",
 "eemt hs": "1",
 "estradot 100": "1",
 "estro-cyp": "1",
 "elite ob with dha": "2",
 "eloxatin": "2",
 "emend 2-day": "2",
 "eldercaps": "2",
 "enalapril/felodipine": "1",
 "enduron": "1",
 "ecpirin": "2",
 "esmolol": "2",
 "etanercept": "2",
 "etonogestrel": "1",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ethinyl estradiol/norethindrone": "1",
 "emend 3-day": "2",
 "estrasorb": "1",
 "endal cd": "2",
 "estratest h.s.": "1",
 "evorel": "1",
 "e s p": "3",
 "e.e.s.-200": "3",
 "esterified estrogens": "1",
 "eltrombopag": "2",
 "etrafon forte": "2",
 "ethyol": "2",
 "equi-natal care": "2",
 "exna": "1",
 "enbrel": "2",
 "endometrin": "1",
 "equetro": "2",
 "enalapril/hydrochlorothiazide": "1",
 "ethionamide": "2",
 "epitol": "2",
 "estradot 50": "1",
 "equinatal 90": "2",
 "efavirenz": "2",
 "embrex 600": "2",
 "ecee plus": "2",
 "emend for injection": "2",
 "esclim": "1",
 "estradiol/levonorgestrel": "1",
 "ecotrin": "2",
 "estra-v 40": "1",
 "enduronyl": "1",
 "emtricitabine/nelfinavir/tenofovir": "3",
 "eribulin": "2",
 "effexor xr": "2",
 "endacof-dc": "2",
 "exjade": "2",
 "estradiol topical": "1",
 "endacof-dh": "2",
 "e.e.s.-400 filmtab": "3",
 "eldepryl": "2",
 "eye health formula": "2",
 "estradiol/norethindrone topical": "1",
 "entocort ec": "2",
 "extra strength mylanta calci tabs": "2",
 "estra-c": "1",
 "excedrin back &amp; body": "2",
 "estradiol g gam": "1",
 "elite ob 400": "2",
 "e-mycin": "3",
 "endocodone": "2",
 "esomeprazole": "2",
 "essian h.s.": "1",
 "endodan": "2",
 "ethinyl estradiol/ethynodiol": "1",
 "esimil": "1",
 "eth-oxydose": "2",
 "estropipate topical": "1",
 "ethinyl estradiol/norgestimate": "1",
 "entercote": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "3",
 "eskalith": "2",
 "efasin expectorant sf": "2",
 "ezetimibe/simvastatin": "3",
 "estra-testrin": "1",
 "eskalith-cr": "2",
 "empirin with codeine": "2",
 "equi-natal rx": "2",
 "estrogen patches": "1",
 "endotuss expectorant": "2",
 "excedrin migraine": "2",
 "enalapril": "1",
 "estradot 75": "1",
 "ezide": "1",
 "equagesic": "2",
 "effexor": "2",
 "ez iii": "2",
 "eldertonic": "2",
 "estradiol/norethindrone": "1",
 "eprosartan/hydrochlorothiazide": "1",
 "encora": "2",
 "eliphos": "2",
 "ery-tab": "3",
 "excedrin extra strength": "2",
 "estrogel": "1",
 "elppa daily": "2",
 "enjuvia": "1",
 "ethotoin": "2",
 "enditussin expectorant": "2",
 "estradiol/norgestimate": "1",
 "etrafon": "2",
 "estradot 37.5": "1",
 "esomeprazole/naproxen": "2",
 "endacof-c": "2",
 "ethinyl estradiol/norelgestromin": "1",
 "erythromycin/sulfisoxazole": "3",
 "estradiol/medroxyprogesterone": "1",
 "erythrocin lactobionate": "3",
 "e.e.s. granules": "3",
 "eryc": "3",
 "esterified estrogens/methyltestosterone": "1",
 "elleste solo": "1",
 "ethambutol": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "estring": "1",
 "edetate calcium disodium": "2",
 "extra strength bayer": "2",
 "etravirine": "2",
 "erythrocin": "3",
 "etodolac": "2",
 "estradiol/testosterone": "1",
 "eemt ds": "1",
 "erythrocin stearate filmtab": "3",
 "equi-natal z": "2",
 "estrone": "1",
 "ethrane": "2",
 "estragyn 5": "1",
 "ethinyl estradiol/etonogestrel": "1",
 "errin": "1",
 "empirin": "2",
 "estro-span 40": "1",
 "equi-natal m": "2",
 "estropipate": "1",
 "excedrin menstrual complete": "2",
 "eryzole": "3",
 "excedrin": "2",
 "enduronyl forte": "1",
 "elon matrix 5000 complete": "2",
 "ethinyl estradiol/norgestrel": "1"}, "d": {"duramorph pf": "2",
 "dialyvite 3000": "2",
 "diltzac": "2",
 "desflurane": "2",
 "duragesic-75": "2",
 "demi-regroton": "1",
 "dronedarone": "2",
 "delavirdine": "2",
 "duet dha ec": "2",
 "delidose": "1",
 "di-gel": "1",
 "didanosine": "2",
 "dihistine expectorant with codeine": "2",
 "dimetane dc": "2",
 "diuril": "1",
 "depo-subq provera 104": "1",
 "depotestogen": "1",
 "dep medalone 80": "2",
 "diltiazem hydrochloride cd": "2",
 "duloxetine": "2",
 "diovan hct": "1",
 "dialyvite with zinc rx": "2",
 "disney winnie the pooh with extra c": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "1",
 "duo-vil": "2",
 "doan's pills": "2",
 "demi-cof": "2",
 "donatuss dc": "2",
 "demulen 1/50": "1",
 "deproist with codeine": "2",
 "desogestrel/ethinyl estradiol": "1",
 "delatestadiol": "1",
 "dialume": "1",
 "dihydrocodeine/guaifenesin/phenylephrine": "2",
 "diupres-500": "1",
 "dienogest/estradiol": "1",
 "dostinex": "2",
 "di-gel mint": "2",
 "dical captabs": "2",
 "depmedalone": "2",
 "dep androgyn": "1",
 "doans pm": "2",
 "dazidox": "2",
 "daily combo": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "dicarbosil": "2",
 "decadron with xylocaine": "2",
 "drospirenone/estradiol": "1",
 "dynacirc": "1",
 "dabigatran": "1",
 "dexamethasone/lidocaine": "2",
 "darvon compound 32": "2",
 "duragesic-50": "2",
 "dalalone la": "2",
 "docosavit": "2",
 "duo-cyp": "1",
 "dalfopristin/quinupristin": "2",
 "dexone": "2",
 "daypro": "2",
 "duohist dh": "2",
 "depogen": "1",
 "delta-lutin": "1",
 "duet chewable": "2",
 "damason-p": "2",
 "diclofenac": "2",
 "dex-tuss": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "2",
 "dihistine": "2",
 "diutensen-r": "1",
 "desogen": "1",
 "dasetta 1/35": "1",
 "duralone": "2",
 "despec-pd": "2",
 "dexpak taperpak": "2",
 "diphenhydramine/ibuprofen": "2",
 "dexacort phosphate in turbinaire": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "dura-estrin": "1",
 "disney winnie the pooh complete": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "darcalma": "2",
 "diupres-250": "1",
 "dilaudid-hp": "2",
 "diltiazem hydrochloride xt": "2",
 "digitek": "2",
 "diltiazem hydrochloride xr": "2",
 "dilaudid cough syrup": "2",
 "duragesic-25": "2",
 "deltasone": "2",
 "duramorph": "2",
 "diltiazem": "2",
 "dihydro-pe": "2",
 "duragesic": "2",
 "duragesic-100": "2",
 "dialyvite 800 ultra d": "2",
 "dexacort-la": "2",
 "dioval 40": "1",
 "dermavite": "2",
 "dolobid": "2",
 "dolomite": "2",
 "duet dha complete": "2",
 "duralutin": "1",
 "dexamethasone": "2",
 "donnaphen": "2",
 "decohistine dh": "2",
 "donepezil": "2",
 "dilacor xr": "2",
 "dihydro-cp": "2",
 "diaqua": "1",
 "dilaudid": "2",
 "dioval xx": "1",
 "dasetta": "1",
 "dualvit ob": "2",
 "dapsone": "2",
 "dalalone dp": "2",
 "deserpidine/methyclothiazide": "1",
 "decohistine expectorant": "2",
 "dexasone": "2",
 "diurese": "1",
 "donnatal": "2",
 "dutoprol": "2",
 "doans pills extra strength": "2",
 "dual action complete": "2",
 "deferasirox": "2",
 "dura-dumone": "1",
 "dical-d": "2",
 "duragen": "1",
 "darvon-n": "2",
 "darpaz": "2",
 "dermestril": "1",
 "dihistine expectorant": "2",
 "depo-provera": "1",
 "delta-cortef": "2",
 "dihydrocodeine/guaifenesin": "2",
 "disney winnie the pooh gummies": "2",
 "dialyvite 5000": "2",
 "daily multi-vitamins with minerals": "2",
 "dristan sinus": "2",
 "dopar": "2",
 "drospirenone/ethinyl estradiol": "1",
 "diurex": "2",
 "demulen": "1",
 "darvon": "2",
 "dolsed": "2",
 "dicumarol": "1",
 "diuretic ap-es": "2",
 "droperidol/fentanyl": "2",
 "daily multiple for men 50+": "2",
 "dexasone la": "2",
 "diuril sodium": "1",
 "dasatinib": "2",
 "duragal-s": "2",
 "diavite plus": "2",
 "diabetic tussin c": "2",
 "danocrine": "3",
 "dyazide": "1",
 "darvon compound-65": "2",
 "danazol": "3",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "disalcid": "2",
 "dihistine dh": "2",
 "docetaxel": "2",
 "depo-medrol": "2",
 "dihydro-gp": "2",
 "decadron": "2",
 "dihydrocodeine/guaifenesin/pseudoephedrine": "2",
 "d-tal": "2",
 "de-sone la": "2",
 "diltia xt": "2",
 "duet dha": "2",
 "durabac forte": "2",
 "dep gynogen": "1",
 "dexacort phosphate in respihaler": "2",
 "dewitt's pain reliever": "2",
 "dicomal-ph": "2",
 "duet": "2",
 "deconsal c expectorant": "2",
 "denzapine": "2",
 "depopred": "2",
 "dorzolamide/timolol ophthalmic": "2",
 "dolophine": "2",
 "daptomycin": "2",
 "diquinol": "2",
 "duexis": "2",
 "depo-provera contraceptive": "1",
 "di-gel lemon": "2",
 "dexamethasone intensol": "2",
 "divigel": "1",
 "doxacurium": "2",
 "darvocet-n 100": "2",
 "decadron-la": "2",
 "daily-vite weight control": "2",
 "daily multiple for women 50+": "2",
 "deserpidine/hydrochlorothiazide": "1",
 "daily multiple for women": "2",
 "donnatal extentabs": "2",
 "diclofenac/misoprostol": "2",
 "doral": "2",
 "delestrogen": "1",
 "dexacorten": "2",
 "dermestril septem": "1",
 "dexacen-4": "2",
 "doloral": "2",
 "dextromethorphan/promethazine": "2",
 "depade": "2",
 "diucardin": "1",
 "digoxin": "2",
 "deponit": "2",
 "duratestrin": "1",
 "diatx zn": "2",
 "darvocet-n 50": "2",
 "demulen 1/35": "1",
 "dolasetron": "3",
 "decaject la": "2",
 "duract": "2",
 "duraganidin nr": "2",
 "diltiazem hydrochloride sr": "2",
 "doloral sirop": "2",
 "diflucan": "3",
 "disulfiram": "2",
 "docefrez": "2",
 "dexone la": "2",
 "dialyvite 800 with zinc": "2",
 "decagen": "2",
 "dicalphos plus d": "2",
 "dalalone": "2",
 "dynacirc cr": "1",
 "duragesic-12": "2",
 "demerol": "2",
 "dienestrol topical": "1",
 "darunavir": "2",
 "dihydrocodeine/phenylephrine": "2",
 "dilantin": "2",
 "dasetta 7/7/7": "1",
 "dulcolax milk of magnesia": "1",
 "depo-estradiol": "1",
 "desvenlafaxine": "2",
 "depo-testadiol": "1",
 "dilt-xr": "2",
 "duet dha with ferrazone": "2",
 "darvocet a500": "2",
 "decaject": "2"}, "g": {"guaifenesin dac liquid": "2",
 "gilenya": "2",
 "gevrabon": "2",
 "gildess fe 1.5/30": "1",
 "gynodiol": "1",
 "guaifen-c": "2",
 "goody's extra-strength headache powders": "2",
 "gold age liquid vitamins and minerals": "2",
 "genpril": "2",
 "gevratonic": "2",
 "genprin": "2",
 "gaviscon regular strength tablets": "1",
 "guiatuss dac": "2",
 "genace": "2",
 "guaifen ac": "2",
 "guaitussin ac": "2",
 "gold sodium thiomalate": "2",
 "gaviscon regular strength liquid": "1",
 "genora 0.5/35": "1",
 "gaviscon extra strength liquid": "1",
 "gelusil": "1",
 "generess fe": "1",
 "guiatussin dac": "2",
 "guaiatussin ac": "2",
 "guiatuss ac": "2",
 "gengraf": "3",
 "garlic oil": "1",
 "geri-tonic": "2",
 "generix-t": "2",
 "guiatussin with codeine": "2",
 "goody's body pain": "2",
 "gani-tuss nr": "2",
 "gas-x with maalox extra strength": "2",
 "gesticare dha dr": "2",
 "gynovite": "2",
 "gaviscon extra relief formula": "1",
 "gemfibrozil": "3",
 "gennin-fc": "2",
 "glutofac-zx": "2",
 "gianvi": "1",
 "goodys headache powders": "2",
 "gua pc": "2",
 "guaiatussin dac": "2",
 "guai-co": "2",
 "gesticare dha": "2",
 "genaton": "1",
 "galantamine": "2",
 "geritol extend": "2",
 "gildess fe 1/20": "1",
 "genacote": "2",
 "giltuss ped-c": "2",
 "garlic": "1",
 "golimumab": "2",
 "glydeine": "2",
 "gleevec": "2",
 "gas-x with maalox": "2",
 "garfield complete vitamins": "2",
 "genasan": "2",
 "geritol complete": "2",
 "glutofac-mx": "2",
 "gaviscon-2": "1",
 "geodon": "2",
 "goodys extra strength": "2",
 "gesticare": "2",
 "genora 1/35": "1",
 "genora 1/50": "1",
 "guanethidine/hydrochlorothiazide": "1",
 "gerivite liquid": "2",
 "gynogen la 20": "1",
 "gestone": "1",
 "guaifen dac": "2",
 "gaviscon extra strength tablets": "1",
 "grepafloxacin": "2",
 "guaifenesin/hydromorphone": "2",
 "genaton chewable": "1"}, "f": {"fingolimod": "2",
 "folgard os": "2",
 "ferrocite plus": "2",
 "flagyl iv": "2",
 "florinef acetate": "2",
 "fiorinal": "2",
 "folbee plus cz": "2",
 "fasprin": "2",
 "fentanyl": "2",
 "fosinopril": "1",
 "femhrt": "1",
 "foltabs plus dha": "2",
 "femring": "1",
 "flo-pred": "2",
 "femseven": "1",
 "fludara": "2",
 "fluphenazine": "2",
 "fempatch": "1",
 "femecal ob": "2",
 "foltabs prenatal plus dha": "2",
 "folbecal": "2",
 "femtab": "1",
 "forane": "2",
 "furoxone": "2",
 "ferrex pc forte": "2",
 "flolan": "2",
 "first mouthwash blm": "1",
 "fentanyl/ropivacaine": "2",
 "femsept": "1",
 "fiorinal with codeine iii": "2",
 "femseven sequi phase i": "1",
 "formula twenty-one": "2",
 "folivan-prx dha": "2",
 "femecal ob plus dha": "2",
 "folcaps omega 3": "2",
 "fanapt": "2",
 "folivan-ec dha": "2",
 "feldene": "2",
 "florinef": "2",
 "fast acting mylanta": "2",
 "fluconazole": "3",
 "fematrix": "1",
 "fentora": "2",
 "fosfree": "2",
 "fenoprofen": "2",
 "femnatal": "2",
 "flintstones complete": "2",
 "foli-iron": "2",
 "foltabs": "2",
 "fortovase": "3",
 "flagyl": "2",
 "first progesterone mc10": "1",
 "florical": "2",
 "fenofibrate": "3",
 "femtabs": "2",
 "folivan-ob": "2",
 "fosaprepitant": "2",
 "fenoglide": "3",
 "femcon fe": "1",
 "formula b plus": "2",
 "flumezide": "1",
 "femtran": "1",
 "fiortal": "2",
 "fem-natal": "2",
 "folex pfs": "2",
 "fosphenytoin": "2",
 "fioricet with codeine": "2",
 "fluvoxamine": "2",
 "fenoldopam": "2",
 "folcaps care one": "2",
 "flagyl er": "2",
 "famotidine/ibuprofen": "2",
 "furazolidone": "2",
 "folpace rx": "2",
 "fosamprenavir": "3",
 "floricet with codeine": "2",
 "flintstones gummies": "2",
 "fluothane": "2",
 "farbital": "2",
 "freamine iii with electrolytes": "2",
 "furadantin": "2",
 "fibricor": "3",
 "fludarabine": "2",
 "foltabs prenatal": "2",
 "fazaclo": "2",
 "fiorinal with codeine": "2",
 "fortabs": "2",
 "first progesterone mc5": "1",
 "forfivo xl": "2",
 "fiortal with codeine": "2",
 "flagyl 375": "2",
 "fluvastatin": "2",
 "fenofibric acid": "3",
 "fluoxetine/olanzapine": "2",
 "folcal dha": "2",
 "flurbiprofen": "2",
 "fludrocortisone": "2",
 "fasigyn": "2",
 "foltabs 90 plus dha": "2",
 "fiormor": "2",
 "fentanyl transdermal system": "2",
 "flintstones with calcium": "2",
 "femtrace": "1",
 "fosinopril/hydrochlorothiazide": "1"}, "i": {"interferon alfacon-1": "2",
 "isradipine": "1",
 "iophen": "2",
 "intron a": "2",
 "isoniazid/rifampin": "2",
 "icare prenatal rx": "2",
 "isoptin": "2",
 "inderide": "2",
 "icaps lutein &amp; omega-3": "2",
 "invega": "2",
 "istalol": "2",
 "invirase": "3",
 "implanon": "1",
 "imatinib": "2",
 "iophen-c nr": "2",
 "ibuprofen": "2",
 "icaps tr": "2",
 "ibuprofen pmr": "2",
 "idenal": "2",
 "incivek": "3",
 "ixempra": "2",
 "ibuprofen/oxycodone": "2",
 "introvale": "1",
 "i-vite": "2",
 "isoniazid": "2",
 "icar prenatal chewable calcium": "2",
 "i-vite protect": "2",
 "icaps plus": "2",
 "itraconazole": "3",
 "isoniazid/pyrazinamide/rifampin": "2",
 "inatal advance": "2",
 "iloprost": "2",
 "inderide la": "2",
 "ibudone": "2",
 "ibuprofen/pseudoephedrine": "2",
 "ibu-tab": "2",
 "infliximab": "2",
 "indapamide": "1",
 "interferon alfa-2b/ribavirin": "2",
 "innopran xl": "2",
 "infergen": "2",
 "indocin iv": "2",
 "ilosone": "3",
 "inderal la": "2",
 "inatal ultra": "2",
 "iopidine": "2",
 "ibu-200": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "interferon alfa-2b": "2",
 "indocin": "2",
 "icaps areds": "2",
 "icar prenatal": "2",
 "isonarif": "2",
 "indinavir": "3",
 "icaps with lutein and zeaxan": "2",
 "interferon alfa-2a": "2",
 "ipilimumab": "2",
 "isoflurane": "2",
 "infumorph": "2",
 "iloperidone": "2",
 "isocarboxazid": "2",
 "interferon alfa-n1": "2",
 "iodoquinol": "2",
 "ixabepilone": "2",
 "isoptin sr": "2",
 "indocin sr": "2",
 "inderal": "2",
 "i-sense": "2",
 "intelence": "2",
 "invega sustenna": "2",
 "indomethacin": "2",
 "infanate dha": "2",
 "icaps mv": "2",
 "ibu-4": "2",
 "i-fol plus": "2",
 "ibu-6": "2",
 "ibu-8": "2",
 "isoptin iv": "2",
 "innovar": "2",
 "ibu": "2",
 "ionsys": "2",
 "i-sense occushield": "2"}, "h": {"hydeltrasol": "2",
 "hhr": "2",
 "haloperidol": "2",
 "hydrochlorothiazide/triamterene": "1",
 "hemocyte plus": "2",
 "halotussin dac": "2",
 "hydroserpine 1": "1",
 "hyzaar": "1",
 "helidac": "2",
 "hydro-tussin exp": "2",
 "hydro-reserp": "1",
 "hydrocortisone": "2",
 "hydrochlorothiazide/methyldopa": "1",
 "hydralazine/hydrochlorothiazide": "2",
 "hyosophen": "2",
 "hydrochlorothiazide/timolol": "2",
 "heartburn antacid extra strength": "1",
 "hydromorphone": "2",
 "hydrocortone phosphate": "2",
 "hydrochlorothiazide/spironolactone": "1",
 "hyprogesterone": "1",
 "hydropres-50": "1",
 "hydrap-es": "2",
 "hydroserpine": "1",
 "hydroflumethiazide/reserpine": "1",
 "heather": "1",
 "hydrocodone/ibuprofen": "2",
 "hydralazine": "2",
 "hydroflumethiazide": "1",
 "hydrodiuril": "1",
 "hygroton": "1",
 "hydrochlorothiazide/metoprolol": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hydrostat ir": "2",
 "hydrochlorothiazide/olmesartan": "1",
 "hylutin": "1",
 "halotussin ac": "2",
 "haldol decanoate": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "haltran": "2",
 "hydrochlorothiazide/moexipril": "1",
 "hyophen": "2",
 "hydrochlorothiazide/irbesartan": "1",
 "hi-nate 90": "2",
 "hydrochlorothiazide/propranolol": "2",
 "halothane": "2",
 "h.p. acthar gel": "2",
 "hydrochlorothiazide/lisinopril": "1",
 "hydromorph contin": "2",
 "hematinic plus": "2",
 "halfprin": "2",
 "hivid": "2",
 "haley's m-o": "1",
 "hydro-tussin dhc": "2",
 "halaven": "2",
 "hydra-zide": "2",
 "hydroxychloroquine": "2",
 "hydrochlorothiazide/valsartan": "1",
 "haponal": "2",
 "hydrochlorothiazide/telmisartan": "1",
 "hydrocortone": "2",
 "hydroxyprogesterone": "1",
 "hydrochlorothiazide/reserpine": "1",
 "hair booster": "2",
 "humira": "2",
 "hydralazine/isosorbide dinitrate": "2",
 "hydrochlorothiazide/quinapril": "1",
 "hydropres-25": "1",
 "hydrochlorothiazide/losartan": "1",
 "hydrochlorothiazide": "1",
 "hexadrol": "2",
 "heartline": "2",
 "high potency": "2",
 "hyoscyamine/phenobarbital": "2",
 "hydro par": "1",
 "hydralazine plus": "2",
 "hydeltra-tba": "2",
 "hemax": "2",
 "haldol": "2",
 "hydroserp": "1"}, "k": {"kadian": "2",
 "ken-jec 40": "2",
 "k-pek": "2",
 "kaopectate": "2",
 "kapectolin": "2",
 "kolnatal dha": "2",
 "kg-fed": "2",
 "kenalog-10": "2",
 "kaopectate anti-diarrheal upset stomach reliever": "2",
 "key-pred": "2",
 "kaolin/pectin": "2",
 "korlym": "2",
 "ketoconazole": "3",
 "kerlone": "2",
 "kao-spen": "2",
 "kenaject-40": "2",
 "kelnor 1/35": "1",
 "kalcinate": "2",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "kao-tin bismuth subsalicylate formula": "2",
 "kg-fed pediatric expectorant": "2",
 "kestrone 5": "1",
 "kg-fed expectorant": "2",
 "ketorolac": "2",
 "kaletra": "3",
 "kneerelief": "2",
 "kariva": "1",
 "ketek": "3",
 "kaodene nn suspension": "2",
 "kaopectate extra strength": "2",
 "ketoprofen": "2",
 "k-c suspension": "2",
 "ketek pak": "3"}, "j": {"jolessa": "1",
 "junel 1.5/30": "1",
 "jenest": "1",
 "juvisync": "3",
 "jinteli": "1",
 "j-max dhc": "2",
 "jantoven": "1",
 "jevantique": "1",
 "junel fe 1/20": "1",
 "j-cof dhc": "2",
 "jumex": "2",
 "junel fe 1.5/30": "1",
 "junel 1/20": "1",
 "jolivette": "1",
 "jevtana": "2"}, "m": {"monopril hct": "1",
 "mynatal ultracap": "2",
 "metocurine": "2",
 "maxivision eye formula": "2",
 "metubine iodide": "2",
 "m-end wc": "2",
 "mynatal pn forte": "2",
 "mylanta ultra": "2",
 "morphine sulfate er": "2",
 "maxivision whole body formula": "2",
 "marthritic": "2",
 "maternity": "2",
 "min-ovral 21": "1",
 "metipranolol ophthalmic": "2",
 "metahydrin": "1",
 "m-oxy": "2",
 "medrol dosepak": "2",
 "miradon": "1",
 "mynatal rx": "2",
 "micardis hct": "1",
 "maalox advanced maximum strength": "1",
 "marlissa": "1",
 "magsal": "2",
 "mestranol/norethindrone": "1",
 "magnebind 400 rx": "2",
 "mycelex troche": "2",
 "mhp-a": "2",
 "microzide": "1",
 "myphetane dc": "2",
 "midazolam": "2",
 "mi-acid ii": "1",
 "maxinate": "2",
 "magnacet": "2",
 "methyclothiazide/reserpine": "1",
 "methacort 40": "2",
 "my-a-multi": "2",
 "mynate 90 plus": "2",
 "motrin pm": "2",
 "multi-betic": "2",
 "mylanta gelcap": "2",
 "medique pain-off": "2",
 "minizide": "1",
 "midol extended relief": "2",
 "m-phen": "2",
 "morphine lp epidural": "2",
 "mynatal z": "2",
 "methoxsalen": "2",
 "monocal": "2",
 "maalox children's relief": "2",
 "mephenytoin": "2",
 "moduretic": "1",
 "mar-cof bp": "2",
 "methylcotolone": "2",
 "milnacipran": "2",
 "maalox advanced maximum strength chewable": "2",
 "menostar": "1",
 "motrin infant drops": "2",
 "microgestin 1/20": "1",
 "maalox max wild berry": "1",
 "monopril": "1",
 "montelukast": "2",
 "m-clear": "2",
 "methacort 80": "2",
 "motrin childrens cold": "2",
 "medicort": "2",
 "mylagen-ii": "1",
 "matzim la": "2",
 "magan": "2",
 "mobic": "2",
 "myadec": "2",
 "metryl": "2",
 "methylcotol": "2",
 "maxifed cdx": "2",
 "multaq": "2",
 "mintox extra strength": "1",
 "mifeprex": "2",
 "macrobid": "2",
 "multivitamin, prenatal": "2",
 "mirena": "1",
 "morphine rapi-ject": "2",
 "multilex": "2",
 "maalox max quick dissolve": "2",
 "morphine/naltrexone": "2",
 "metoprolol succinate er": "2",
 "methylprednisolone": "2",
 "minitabs": "2",
 "maalox": "1",
 "mesoridazine": "2",
 "milantex": "1",
 "mission prenatal fa": "2",
 "mynatal pn": "2",
 "ms/s": "2",
 "magnesium hydroxide/mineral oil": "1",
 "millipred": "2",
 "methotrexate": "2",
 "molindone": "2",
 "multi-nate 30 kit": "2",
 "menorest": "1",
 "motrin ib sinus": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "min-ovral 28": "1",
 "mefenamic acid": "2",
 "mi-acid double strength": "2",
 "mag-phen": "2",
 "magaant": "1",
 "maternity vitamin low iron": "2",
 "mononessa": "1",
 "millipred dp": "2",
 "maxifed-g cdx": "2",
 "medrol": "2",
 "mediplex ultra": "2",
 "maternity-90": "2",
 "mynatal fc": "2",
 "magonate tablets": "2",
 "midol maximum strength cramp formula": "2",
 "mintox": "1",
 "magnesium hydroxide": "1",
 "mudrane gg": "2",
 "maldroxal": "1",
 "meperitab": "2",
 "masanti ds": "1",
 "multifol plus": "2",
 "mykrox": "1",
 "mycobutin": "2",
 "microgestin 1.5/30": "1",
 "maalox plus extra strength": "1",
 "multinatal plus": "2",
 "mylanta maximum strength cherry": "1",
 "menopause formula progesterone": "1",
 "myochrysine": "2",
 "methoxyflurane": "2",
 "mefloquine": "2",
 "midol ib": "2",
 "maalox advanced regular strength": "1",
 "m-end pe": "2",
 "marnatal-f": "2",
 "medent c": "2",
 "magnebind 200": "2",
 "methadose": "2",
 "metro": "2",
 "mepergan fortis": "2",
 "maldroxal plus": "1",
 "methyclothiazide": "1",
 "mono-gesic": "2",
 "mylanta supreme": "2",
 "maxivision eye &amp; body formula": "2",
 "mifepristone": "2",
 "macrodantin": "2",
 "mission prenatal hp": "2",
 "magnesium salicylate": "2",
 "microgestin fe 1/20": "1",
 "motrin ib": "2",
 "maalox junior relief chewable": "2",
 "mi-c-t": "2",
 "menogen": "1",
 "meperidine": "2",
 "mag-sr with calcium": "2",
 "morphine sulfate ir": "2",
 "multi-day with calcium and extra iron": "2",
 "multi-nate dha": "2",
 "maxifed cd": "2",
 "ms contin": "2",
 "milantex maximum strength": "1",
 "mintox plus": "1",
 "mobigesic": "2",
 "maalox regular strength": "2",
 "medidex la": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "myvitalife": "2",
 "maxiflu cd": "2",
 "maraviroc": "2",
 "maxiphen cd": "2",
 "mylagen": "1",
 "minitran": "2",
 "migralex": "2",
 "maxifed-g cd": "2",
 "mesantoin": "2",
 "maternal 90": "2",
 "mintox maximum strength": "1",
 "myambutol": "2",
 "midol traditional": "2",
 "motrin": "2",
 "mst": "2",
 "medroxyprogesterone": "1",
 "morphine": "2",
 "micrainin": "2",
 "meclofenamate": "2",
 "motrin sinus headache": "2",
 "maalox plus": "1",
 "meloxicam": "2",
 "metronidazole": "2",
 "mimvey": "1",
 "methadone diskets": "2",
 "mission prenatal": "2",
 "mepergan": "2",
 "miconazole": "2",
 "mytussin ac": "2",
 "maalox quick dissolve extra strength": "2",
 "meprozine": "2",
 "menaval-20": "1",
 "mylanta ultimate strength": "1",
 "multi-nate 30 dha": "2",
 "marblen": "2",
 "metolazone": "1",
 "menogen hs": "1",
 "matulane": "2",
 "maxivision ocular formula": "2",
 "mylanta child": "2",
 "morphitec": "2",
 "modicon": "1",
 "m-vit": "2",
 "mission prenatal rx": "2",
 "m-clear wc": "2",
 "mynatal": "2",
 "moduretic 5-50": "1",
 "masanti": "1",
 "maxzide-25": "1",
 "magnebind 300": "2",
 "maxiflu cdx": "2",
 "microgestin fe 1.5/30": "1",
 "medi-seltzer": "2",
 "momentum": "2",
 "metoprolol": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "maalox tc": "1",
 "mi-acid": "1",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "multilex-t/m+minerals": "2",
 "marplan": "2",
 "mellaril-s": "2",
 "methotrimeprazine": "2",
 "maxiphen cdx": "2",
 "myzilra": "1",
 "menadol": "2",
 "medralone": "2",
 "medidiol 10": "1",
 "medipred": "2",
 "m-prednisolone": "2",
 "mivacurium": "2",
 "medralone 80": "2",
 "mylanta fast acting": "1",
 "methotrexate lpf sodium": "2",
 "meperidine/promethazine": "2",
 "morphine sulfate sr": "2",
 "magna-c-7 forte": "2",
 "marnatal-f plus": "2",
 "maxzide": "1",
 "mobidin": "2",
 "metro iv": "2",
 "multi-day plus minerals": "2",
 "myogesic": "2",
 "msp-blu": "2",
 "meticorten": "2",
 "mivacron": "2",
 "milk of magnesia": "1",
 "mylanta ds fast acting": "1",
 "maalox max": "1",
 "multivitamin with minerals": "2",
 "m-eslon": "2",
 "mylanta maximum strength": "1",
 "methylpred dp": "2",
 "mytussin dac": "2",
 "mavik": "1",
 "mibefradil": "3",
 "mylanta": "1",
 "methdilazine": "2",
 "motrin migraine pain": "2",
 "maalox antacid antigas regular strength": "1",
 "makena": "1",
 "maternity plus beta carotene": "2",
 "multi-nate dha extra": "2",
 "medique medi-seltzer": "2",
 "menopause support": "2",
 "maalox total relief": "2",
 "mircette": "1",
 "menorest patch": "1",
 "modafinil": "1",
 "mens pack": "2",
 "motrin junior strength": "2",
 "mellaril": "2",
 "metatensin 4": "1",
 "motrin childrens": "2",
 "metatensin 2": "1",
 "medidex": "2",
 "moban": "2",
 "materna": "2",
 "m o s": "2",
 "mynatal plus": "2",
 "multi-nate 30": "2",
 "mintox tablets": "1",
 "megavite rx": "2",
 "meclomen": "2",
 "mevacor": "2",
 "methylprednisolone dose pack": "2",
 "moexipril": "1",
 "methadone": "2",
 "msir": "2",
 "motrin cold and flu": "2",
 "maalox hrf": "1",
 "mudrane": "2",
 "maximum strength stress": "2",
 "marpres": "2",
 "menest": "1"}, "l": {"litecoat aspirin": "2",
 "loestrin 1/20": "1",
 "lipofen": "3",
 "lo loestrin fe": "1",
 "lisinopril": "1",
 "lariam": "2",
 "levatol": "2",
 "lessina": "1",
 "leena": "1",
 "levonest": "1",
 "lodine": "2",
 "lactocal-f": "2",
 "low-ogestrel-21": "1",
 "low-ogestrel-28": "1",
 "lithobid": "2",
 "lufyllin-epg": "2",
 "lescol xl": "2",
 "lexuss 210 liquid": "2",
 "loestrin 21 1/20": "1",
 "loestrin fe 1.5/30": "1",
 "loqua": "1",
 "lamivudine/zidovudine": "2",
 "liquid pred": "2",
 "lysiplex plus": "2",
 "levobunolol ophthalmic": "2",
 "leflunomide": "3",
 "lipidil micro": "3",
 "lazanda": "2",
 "lipidil supra": "3",
 "lofibra": "3",
 "lo/ovral": "1",
 "lopinavir/ritonavir": "3",
 "levlen": "1",
 "lanoxicaps": "2",
 "lipidil ez": "3",
 "loestrin 21 1.5/30": "1",
 "lithotabs": "2",
 "loestrin 24 fe": "1",
 "levitra": "2",
 "loxitane": "2",
 "larodopa": "2",
 "levsin with phenobarbital": "2",
 "leader naproxen sodium": "2",
 "lescol": "2",
 "luminal": "2",
 "licorice": "2",
 "locholest": "2",
 "lovastatin/niacin": "3",
 "lanoxin": "2",
 "levobetaxolol ophthalmic": "2",
 "lutera": "1",
 "lotensin hct": "1",
 "lovastatin": "2",
 "largon": "2",
 "liraglutide": "1",
 "loxitane im": "2",
 "lopressor": "2",
 "lapatinib": "2",
 "lybrel": "1",
 "lexxel": "1",
 "laniroif": "2",
 "loxapine": "2",
 "lo/ovral-28": "1",
 "lexiva": "3",
 "latuda": "2",
 "livalo": "2",
 "lotrel": "1",
 "low dose asa": "2",
 "lanreotide": "2",
 "levlite": "1",
 "levacet": "2",
 "lansoprazole": "2",
 "lortab asa": "2",
 "loestrin fe 1/20": "1",
 "lozol": "1",
 "labetalol": "2",
 "lithium": "2",
 "luvox": "2",
 "luvox cr": "2",
 "lunelle": "1",
 "lithonate": "2",
 "loryna": "1",
 "locholest light": "2",
 "lopid": "3",
 "linezolid": "2",
 "l-tonic": "2",
 "lansoprazole/naproxen": "2",
 "levora": "1",
 "levonorgestrel": "1",
 "lurasidone": "2",
 "lodine xl": "2",
 "lacosamide": "2",
 "loxitane c": "2",
 "levodopa": "2",
 "lopressor hct": "2",
 "loseasonique": "1",
 "lotensin": "1",
 "leg-gesic": "2",
 "liquihistine cs": "2",
 "levoprome": "2"}, "o": {"orphengesic": "2",
 "ormazine": "2",
 "one-a-day within": "2",
 "o-cal-d": "2",
 "os-cal ultra": "2",
 "oxycodone": "2",
 "oyster shell calcium with vitamin d": "2",
 "ob natal one": "2",
 "oreticyl forte": "1",
 "os-cal 500": "2",
 "one-a-day vitacraves": "2",
 "oxaprozin": "2",
 "organon oestradiol": "1",
 "orapred": "2",
 "onsolis": "2",
 "ogen vaginal cream": "1",
 "ortho-est": "1",
 "onxol": "2",
 "oyster cal 500": "2",
 "oyster-d": "2",
 "oyster cal": "2",
 "ocella": "1",
 "ovcon 35 fe": "1",
 "oysco d": "2",
 "ortho evra": "1",
 "oyster shell calcium": "2",
 "ortho tri-cyclen lo": "1",
 "ovcon 35": "1",
 "obnate 90": "2",
 "ortho-novum 1/35": "1",
 "oxcarbazepine": "2",
 "oxycet": "2",
 "oretic": "1",
 "obtrex": "2",
 "oxaliplatin": "2",
 "ortho-prefest": "1",
 "o-cal fa": "2",
 "orasone": "2",
 "orudis kt": "2",
 "ortho-novum 1/50": "1",
 "omeprazole/sodium bicarbonate": "2",
 "orudis": "2",
 "ocuvite preservision": "2",
 "ocuvite": "2",
 "optipranolol": "2",
 "ogestrel-28": "1",
 "one-a-day max": "2",
 "omeprazole": "2",
 "oystercal-d": "2",
 "ocuvite extra": "2",
 "ogen": "1",
 "ortho tri-cyclen": "1",
 "opium tincture, deodorized": "2",
 "oravig": "2",
 "oms": "2",
 "optivite pmt": "2",
 "o-cal prenatal": "2",
 "oyster shell": "2",
 "opium": "2",
 "oyst cal": "2",
 "ortho-cept": "1",
 "optilets-m-500": "2",
 "ovcon 50": "1",
 "oforta": "2",
 "ocuvite lutein": "2",
 "os-cal 500 + extra d": "2",
 "ortho cyclen": "1",
 "obegyn": "2",
 "ob complete with dha": "2",
 "oxsoralen-ultra": "2",
 "oestrodose": "1",
 "ocupress": "2",
 "oreticyl 50": "1",
 "optinate": "2",
 "ob complete premier": "2",
 "oxecta": "2",
 "oxyir": "2",
 "os-cal 500 + d": "2",
 "oxyfast": "2",
 "obtrex dha": "2",
 "one-a-day weightsmart": "2",
 "occuplex": "2",
 "ogestrel": "1",
 "oxydose": "2",
 "oestradiol implants": "1",
 "one-a-day women": "2",
 "ovral": "1",
 "ortho-novum 10/11": "1",
 "ostiva": "2",
 "oromone": "1",
 "orsythia": "1",
 "oyst-cal-d": "2",
 "ortho micronor": "1",
 "opium deodorized": "2",
 "oysco 500": "2",
 "orphengesic forte": "2",
 "opti-gen": "2",
 "ogen 1.25": "1",
 "os-cal": "2",
 "oysco 500 with d": "2",
 "omesec": "2",
 "oestrogel pump-pack": "1",
 "oysco d with calcium": "2",
 "ortho-novum 7/7/7": "1",
 "one daily with minerals": "2",
 "one tab daily with minerals": "2",
 "ogen 0.625": "1",
 "oestrogel": "1",
 "ovral-28": "1",
 "octreotide": "2",
 "oyst cal 500": "2",
 "oruvail": "2",
 "ogen 2.5": "1",
 "oyster shell calcium 500": "2",
 "ob-20": "2",
 "ovrette": "1",
 "ortho dienestrol": "1",
 "oxycontin": "2",
 "ob complete": "2",
 "oyster": "2",
 "one-a-day women 50 plus": "2",
 "oncovin": "2",
 "oreticyl 25": "1",
 "oramorph sr": "2",
 "ob complete 400": "2",
 "osteocit d plus": "2",
 "oesclim": "1",
 "oyster calcium": "2",
 "one-a-day men pro edge": "2",
 "orapred odt": "2",
 "one-a-day men 50 plus": "2",
 "olanzapine": "2"}, "n": {"nutrispire": "2",
 "natalcare advanced": "2",
 "necon 0.5/35": "1",
 "nora-be": "1",
 "nicotinex": "3",
 "naprosyn": "2",
 "norethin 1/35 e": "1",
 "nitroglycerin": "2",
 "nexium": "2",
 "necon 10/11": "1",
 "narvox": "2",
 "natalcare pic forte": "2",
 "natelle prefer": "2",
 "nucodine": "2",
 "niacin": "3",
 "nicolar": "3",
 "nebivolol": "2",
 "nexcede": "2",
 "novahistine expectorant": "2",
 "nu-iron v": "2",
 "natalcare": "2",
 "niferex-pn": "2",
 "nitrek": "2",
 "naprelan": "2",
 "nizoral": "3",
 "necon 7/7/7": "1",
 "nelova 10/11": "1",
 "natalcare cfe 60": "2",
 "neevo": "2",
 "nitro td patch-a": "2",
 "natelle-ez": "2",
 "nata 29 ob": "2",
 "norethin 1/50 m": "1",
 "nucodine pediatric": "2",
 "nuvaring": "1",
 "nuco-tuss pediatric expectorant": "2",
 "niacor": "3",
 "natacaps": "2",
 "novastart": "2",
 "nanovm": "2",
 "niacin/simvastatin": "3",
 "natazia": "1",
 "nitrodisc": "2",
 "natelle one": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "nelova 0.5/35": "1",
 "nitroglyn e-r": "2",
 "nata 29 prenatal": "2",
 "nitrofurantoin": "2",
 "nestabs rx": "2",
 "neoprofen": "2",
 "natalcare glosstabs": "2",
 "naldecon-cx adult": "2",
 "nydrazid": "2",
 "nestabs fa": "2",
 "nevirapine": "2",
 "notuss-nxd": "2",
 "nuvigil": "1",
 "natelle": "2",
 "nifediac cc": "2",
 "notuss-pe": "2",
 "nilotinib": "2",
 "norgesic forte": "2",
 "norvir": "3",
 "nicotinic acid": "3",
 "necon 1/35": "1",
 "nitrocot": "2",
 "nitro-dur": "2",
 "normodyne": "2",
 "nalbuphine": "2",
 "natafolic-ob": "2",
 "nucofed pediatric expectorant": "2",
 "next choice": "1",
 "nestabs": "2",
 "nitrogard": "2",
 "natalcare rx": "2",
 "nelfinavir": "3",
 "nitro-bid": "2",
 "nordette-28": "1",
 "notuss-ac": "2",
 "novasal": "2",
 "natelle one dha": "2",
 "nordette-21": "1",
 "nucofed expectorant": "2",
 "notuss-nx": "2",
 "naloxone/pentazocine": "2",
 "nitrong": "2",
 "norgestrel": "1",
 "novadyne expectorant": "2",
 "nucochem": "2",
 "nelova 1/35": "1",
 "nubain": "2",
 "natatab fa": "2",
 "nuprin": "2",
 "niaspan": "3",
 "nutiifac zx": "2",
 "naturetin": "1",
 "niacor b3": "3",
 "nalex ac": "2",
 "nifedipine": "2",
 "natarex": "2",
 "naqua": "1",
 "nalfon": "2",
 "nortrel 0.5/35": "1",
 "nicotinamide zcf": "2",
 "nasotuss": "2",
 "nitrolingual pumpspray": "2",
 "novanatal": "2",
 "natatab rx": "2",
 "naltrexone": "2",
 "nico-400": "3",
 "nitro-bid iv": "2",
 "nucodine expectorant": "2",
 "necon 1/50": "1",
 "nuromax": "2",
 "neo ac": "2",
 "neoral": "3",
 "nuprin backache caplet": "2",
 "nephro calci": "2",
 "norisodrine with calcium iodine": "2",
 "navane": "2",
 "nuco-tuss expectorant": "2",
 "nitrostat tablets": "2",
 "new advanced formula prenatal z": "2",
 "nitroquick": "2",
 "noxafil": "3",
 "neevo dha": "2",
 "naproxen sodium ds": "2",
 "natelle c": "2",
 "nifedical xl": "2",
 "norinyl 1+50": "1",
 "natatab cfe": "2",
 "nicobid tempules": "3",
 "nadolol": "2",
 "naturetin-5": "1",
 "nor-qd": "1",
 "nimbex": "2",
 "novahistine dh": "2",
 "nortrel 7/7/7": "1",
 "niferex pn forte": "2",
 "norcuron": "2",
 "nortrel 1/35": "1",
 "nelova 1/50 m": "1",
 "natalcare advanced-rf": "2",
 "nic 750": "2",
 "naturetin-10": "1",
 "natalcare plus": "2",
 "natalins rx": "2",
 "neo-forte": "2",
 "nitrostat": "2",
 "novadyne dh": "2",
 "naproxen/sumatriptan": "2",
 "norethindrone": "1",
 "norwich aspirin": "2",
 "nitro-time": "2",
 "notuss-dc": "2",
 "natachew": "2",
 "natelle plus with dha": "2",
 "natafolic-pn": "2",
 "nexium iv": "2",
 "nitrol": "2",
 "nelarabine": "2",
 "norgesic": "2",
 "nature's blend theratrum complete tablets 50 plus": "2",
 "nardil": "2",
 "natalfirst": "2",
 "novagest with codeine": "2",
 "niacin sr": "3",
 "naproxen": "2",
 "nutrinate": "2",
 "nitro-par": "2",
 "nicomide": "2",
 "nabumetone": "2",
 "nuvelle ts phase i": "1",
 "nexterone": "2",
 "nexa select with dha": "2",
 "nestabs cbf": "2",
 "nitro macro": "2",
 "nucofed": "2",
 "neo-calglucon": "2",
 "norplant system": "1",
 "nitrol appli-kit": "2",
 "nitromist": "2",
 "nephrox": "1",
 "norlac rx": "2",
 "nutravance": "2",
 "norinyl 1+35": "1",
 "natalcare pic": "2",
 "nexplanon": "1",
 "navelbine": "2",
 "natalcare three": "2",
 "nefazodone": "3",
 "norvir soft gelatin": "3",
 "nordette": "1",
 "naproxen/pseudoephedrine": "2",
 "natafort": "2",
 "natalins": "2",
 "nicazel": "2"}, "q": {"quelicin": "2",
 "quasense": "1",
 "quineprox": "2",
 "quelicin chloride": "2",
 "questran light": "2",
 "quinapril": "1",
 "quinestrol": "1",
 "quazepam": "2",
 "quetiapine": "2",
 "questran": "2",
 "q-profen": "2",
 "quadrinal": "2",
 "quadrapax": "2",
 "quinaretic": "1"}, "p": {"pyridium plus": "2",
 "phosphasal": "2",
 "prempro": "1",
 "pr natal 440": "2",
 "pravastatin": "2",
 "paire ob plus dha": "2",
 "poly-tussin ac": "2",
 "probenecid and colchicine": "3",
 "poly-histine cs": "2",
 "pamprin all day relief": "2",
 "parenteral nutrition solution w/electrolytes": "2",
 "predacort 50": "2",
 "prenatal low iron": "2",
 "pseudodine c": "2",
 "pan ob forte": "2",
 "pentazocine": "2",
 "primacare": "2",
 "prevacid naprapac": "2",
 "prevacid naprapac 375": "2",
 "pyrelle hb": "2",
 "progestasert system": "1",
 "plavix": "2",
 "prevacid solutab": "2",
 "pedituss": "2",
 "pradaxa": "1",
 "progynova": "1",
 "premphase": "1",
 "pindolol": "2",
 "procardia": "2",
 "pantoprazole": "2",
 "phenhist expectorant": "2",
 "pce dispertab": "3",
 "prograf": "2",
 "pri-cortin 50": "2",
 "pulmicort nebuamp": "2",
 "pr natal 400 ec": "2",
 "predcor": "2",
 "prochlorperazine": "2",
 "promethazine with dm": "2",
 "prenatabs cbf": "2",
 "prednisolone": "2",
 "procot": "2",
 "phenylhistine expectorant": "2",
 "phenaphen with codeine": "2",
 "predicort-50": "2",
 "posture-d h/p": "2",
 "prenafirst": "2",
 "prednicot": "2",
 "pepto children's": "2",
 "preferaob": "2",
 "prolixin": "2",
 "plaquenil": "2",
 "prenatal-u": "2",
 "propoxyphene compound 65": "2",
 "prefera ob-one": "2",
 "pink bismuth": "2",
 "pancuronium": "2",
 "posture": "2",
 "pnv-total": "2",
 "phenadoz": "2",
 "phenergan vc": "2",
 "polythiazide/prazosin": "1",
 "prenatabs fa": "2",
 "prelone": "2",
 "paclitaxel": "2",
 "procarbazine": "2",
 "progesterone": "1",
 "prenaplus": "2",
 "phillips' haleys m-o": "1",
 "pamprin cramp menstrual pain relief": "2",
 "platinol-aq": "2",
 "pediazole": "3",
 "pnv-dha plus": "2",
 "phenylephrine/promethazine": "2",
 "predate-50": "2",
 "promethazine with codeine": "2",
 "prevacid otc": "2",
 "primacare advantage": "2",
 "prelief": "2",
 "phenazine 50": "2",
 "permitil": "2",
 "prenate dha": "2",
 "prenate 90": "2",
 "prolixin enanthate": "2",
 "parnate": "2",
 "pms balance": "2",
 "percodan": "2",
 "peginterferon alfa-2a": "2",
 "peginterferon alfa-2b": "2",
 "previte rx": "2",
 "prilosec": "2",
 "phenytek": "2",
 "pediacof": "2",
 "paliperidone": "2",
 "pb-hyos": "2",
 "prosteon": "2",
 "phrenilin with caffeine and codeine": "2",
 "prenatabs obn": "2",
 "primacare one": "2",
 "predicort rp": "2",
 "prenatal mr 90": "2",
 "prenavite fc": "2",
 "poly hist dhc": "2",
 "polytine cs": "2",
 "percocet 10/325": "2",
 "propranolol": "2",
 "provera": "1",
 "poly tussin ex": "2",
 "prevacid naprapac 500": "2",
 "pepto-bismol": "2",
 "prenatal rx": "2",
 "prenatal 1 plus 1": "2",
 "percocet 2.5/325": "2",
 "prenate essential": "2",
 "percodan-demi": "2",
 "promethazine vc with codeine": "2",
 "poly cs": "2",
 "prednicen-m": "2",
 "platinol": "2",
 "premesis rx": "2",
 "posicor": "3",
 "par-f": "2",
 "prenatal plus with 27 mg iron": "2",
 "pipecuronium": "2",
 "phosenamine": "2",
 "preterna": "2",
 "primlev": "2",
 "protonix iv": "2",
 "prefera ob plus dha": "2",
 "prenatal multivitamins": "2",
 "pnv select": "2",
 "pepcid complete": "2",
 "prenate gt": "2",
 "pancof": "2",
 "precare conceive": "2",
 "penbutolol": "2",
 "prenate ultra": "2",
 "pmb": "1",
 "phenytoin sodium, prompt": "2",
 "penthrane": "2",
 "propiomazine": "2",
 "prenate essential dha": "2",
 "protonix": "2",
 "previfem": "1",
 "prenatal s": "2",
 "percolone": "2",
 "phenaz plus": "2",
 "phenelzine": "2",
 "posaconazole": "3",
 "prenatal rx 1": "2",
 "protegra softgel": "2",
 "prolixin decanoate": "2",
 "pacerone": "2",
 "p-a-c analgesic": "2",
 "prenacare": "2",
 "prosed ec": "2",
 "phoslyra": "2",
 "prodrox": "1",
 "pro-med": "2",
 "prenatal mtr with selenium": "2",
 "plan b one-step": "1",
 "prenexa": "2",
 "prosight": "2",
 "poly-tussin ex syrup": "2",
 "pylera": "2",
 "priftin": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "pitavastatin": "2",
 "promethazine vc": "2",
 "peganone": "2",
 "prenate elite": "2",
 "pancof-pd": "2",
 "phenylhistine dh expectorant": "2",
 "prenatal z advanced formula": "2",
 "parcopa": "2",
 "prosed ds": "2",
 "pr natal 400": "2",
 "pepto-bismol maximum strength": "2",
 "prenate elite plus iron": "2",
 "percocet 5/325": "2",
 "plan b": "1",
 "pristiq": "2",
 "phenflu cdx": "2",
 "pc-cap": "2",
 "prinivil": "1",
 "paraplatin": "2",
 "percocet 10/650": "2",
 "progynova ts": "1",
 "p-a-c": "2",
 "pegintron": "2",
 "provigil": "1",
 "procycle multi vitamin with minerals": "2",
 "pp-cap": "2",
 "predaject-50": "2",
 "peptic relief": "2",
 "phenazoforte plus": "2",
 "pulmicort turbuhaler": "2",
 "ponstel": "2",
 "piroxicam": "2",
 "prinzide": "1",
 "prenatal h": "2",
 "pediapred": "2",
 "predacorten": "2",
 "phenytoin": "2",
 "prostate 2.4": "2",
 "primethasone": "2",
 "paregoric": "2",
 "prevacid": "2",
 "pravachol": "2",
 "prevalite": "2",
 "perindopril": "1",
 "prenate advance": "2",
 "pancof exp": "2",
 "pectin": "2",
 "percocet 7.5/325": "2",
 "phenobarbital": "2",
 "promazine": "2",
 "pruet dha": "2",
 "prenatabs rx": "2",
 "premphase 14/14": "1",
 "premarin vaginal": "1",
 "prenate advanced formula": "2",
 "predalone 50": "2",
 "primalev": "2",
 "prenavite": "2",
 "philith": "1",
 "percocet": "2",
 "proben-c": "3",
 "pavulon": "2",
 "phenergan": "2",
 "panasal 5/500": "2",
 "pegasys": "2",
 "phenoject-50": "2",
 "propoxyphene": "2",
 "prenatal plus": "2",
 "promethazine dm": "2",
 "premarin intravenous": "1",
 "prenatal mr 90 fe": "2",
 "prenatal elite": "2",
 "preque 10": "2",
 "palladone": "2",
 "paclitaxel protein-bound": "2",
 "pre-h-cal": "2",
 "pulmicort flexhaler": "2",
 "phenergan fortis": "2",
 "prenexa with dha": "2",
 "procardia xl": "2",
 "prenate plus": "2",
 "panlor dc": "2",
 "prefest": "1",
 "provames": "1",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "polythiazide": "1",
 "precare": "2",
 "phoslo gelcap": "2",
 "prenatal plus with beta-carotene": "2",
 "progest": "1",
 "pro-clear": "2",
 "pedia-lax chewable tablets": "1",
 "premarin": "1",
 "prochieve": "1",
 "perloxx": "2",
 "protostat": "2",
 "panlor ss": "2",
 "precare premier": "2",
 "prenavite pc": "2",
 "poly-tussin dhc": "2",
 "promethazine with dextromethorphan": "2",
 "prenazyme 1+1": "2",
 "pred-ject-50": "2",
 "promacta": "2",
 "proleukin": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenflu cd": "2",
 "painaid": "2",
 "pro-red ac": "2",
 "phenylhistine dh": "2",
 "portia": "1",
 "primogyn depot": "1",
 "prednisone": "2",
 "promethazine hcl with codeine": "2",
 "phoslo": "2",
 "pr natal 430": "2",
 "polythiazide/reserpine": "1",
 "procalamine": "2",
 "prilosec otc": "2",
 "pnv-dha": "2",
 "promethazine vc w/codeine": "2",
 "preservision": "2",
 "percocet 7.5/500": "2",
 "pramilet fa": "2",
 "promethazine vc plain": "2",
 "prevacid iv": "2",
 "prenatal plus iron": "2",
 "preven ec": "1",
 "prevacid 24hr": "2",
 "pamprin max menstrual pain relief": "2",
 "pravigard pac": "2",
 "probarimin qt": "2",
 "phenergan with dextromethorphan": "2",
 "prezista": "2",
 "prevpac": "3",
 "perphenazine": "2",
 "prenatal 19": "2",
 "pulmicort respules": "2",
 "promethegan": "2",
 "polyhist nc": "2",
 "phillips' milk of magnesia": "1",
 "prometrium": "1",
 "prenatal ad": "2"}, "s": {"sronyx": "1",
 "sulindac": "2",
 "saleto": "2",
 "saluron": "1",
 "surbex-750 with zinc": "2",
 "solurex": "2",
 "saquinavir": "3",
 "se-care conceive": "2",
 "sourcecf abdek": "2",
 "senetonic": "2",
 "surpass": "2",
 "stomach relief": "2",
 "sourcecf chewables": "2",
 "selgene": "2",
 "solganal": "2",
 "syntest ds": "1",
 "singulair": "2",
 "subutex": "2",
 "stuart prenatal with beta carotene": "2",
 "selegiline": "2",
 "serathide": "2",
 "sufentanil": "2",
 "sinemet cr": "2",
 "sporanox pulsepak": "3",
 "st. joseph aspirin": "2",
 "synalgos-dc": "2",
 "sss": "2",
 "subsys": "2",
 "stelazine": "2",
 "scot-tussin original": "2",
 "serentil": "2",
 "stress maximum strength": "2",
 "sotalol hydrochloride af": "2",
 "sinemet": "2",
 "selestoject": "2",
 "sojourn": "2",
 "stalevo 150": "2",
 "seasonale": "1",
 "stuartnatal plus 3": "2",
 "saleto-400": "2",
 "sylatron": "2",
 "supac": "2",
 "savella": "2",
 "strovite advance": "2",
 "sudafed 12 hour pressure+pain": "2",
 "synercid": "2",
 "sandimmune": "3",
 "suttar-2": "2",
 "salutensin-demi": "1",
 "solia": "1",
 "super calcium": "2",
 "sevoflurane": "2",
 "solu-cortef": "2",
 "st. joseph 81 mg chewable aspirin": "2",
 "salsalate": "2",
 "serzone": "3",
 "suttar sf": "2",
 "statuss": "2",
 "safyral": "1",
 "stress formula with zinc": "2",
 "suprane": "2",
 "sandostatin": "2",
 "salutensin": "1",
 "seconal sodium": "2",
 "se-natal 16": "2",
 "sublimaze": "2",
 "stalevo 75": "2",
 "saleto-600": "2",
 "stresstabs with zinc": "2",
 "ser-ap-es": "2",
 "se-care": "2",
 "sourcecf multivitamins with a,b,d,e &amp; k plus zinc": "2",
 "simcor": "3",
 "se-natal 19": "2",
 "select-ob+dha": "2",
 "stress 600 with zinc": "2",
 "sustiva": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "sandrena": "1",
 "symbicort": "2",
 "staxyn": "2",
 "st. john's wort": "2",
 "stalevo 200": "2",
 "synthetic conjugated estrogens a": "1",
 "spectravite cardio health": "2",
 "se-tan dha": "2",
 "selzentry": "2",
 "surpass extra strength": "2",
 "stanback fast pain relief": "2",
 "saleto-200": "2",
 "strovite": "2",
 "saleto-800": "2",
 "spectravite senior": "2",
 "sparine": "2",
 "sourcecf pediatric drops": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "systen": "1",
 "strovite plus": "2",
 "stuartnatal plus": "2",
 "sedecal d": "2",
 "sulfimycin": "3",
 "support": "2",
 "syntest hs": "1",
 "simponi": "2",
 "se-natal 90": "2",
 "soma compound with codeine": "2",
 "sloprin": "2",
 "sourcecf softgels": "2",
 "slo-niacin": "3",
 "stalevo 100": "2",
 "solurex la": "2",
 "sprintec": "1",
 "sodium salicylate": "2",
 "soma compound": "2",
 "spastrin": "2",
 "simvastatin/sitagliptin": "3",
 "somatuline depot": "2",
 "syeda": "1",
 "stanback analgesic": "2",
 "strongstart": "2",
 "seton et": "2",
 "seasonique": "1",
 "select-ob": "2",
 "sildenafil": "2",
 "st. joseph 81 mg aspirin enteric safety-coated": "2",
 "se-plete dha": "2",
 "sporanox": "3",
 "serpex": "2",
 "seton et-ec": "2",
 "strovite advance+d": "2",
 "sterapred": "2",
 "super theravite-m": "2",
 "super high vitamins and minerals": "2",
 "sprix": "2",
 "salflex": "2",
 "siderol": "2",
 "solu-medrol": "2",
 "stadol": "2",
 "sine-aid ib": "2",
 "support 500": "2",
 "sprycel": "2",
 "seconal": "2",
 "statex": "2",
 "saphris": "2",
 "spasmolin": "2",
 "sirolimus": "2",
 "serpazide": "2",
 "suboxone": "2",
 "symbyax": "2",
 "spasquid": "2",
 "se-natal one": "2",
 "simvastatin": "3",
 "stalevo 50": "2",
 "salsitab": "2",
 "stalevo 125": "2",
 "sandostatin lar depot": "2",
 "sesame st vitamins complete": "2",
 "sodium thiosalicylate": "2",
 "stalevo": "2",
 "stavudine": "2",
 "sotalol": "2",
 "sorine": "2",
 "succinylcholine": "2",
 "servira": "2",
 "strovite one": "2",
 "sterapred ds": "2",
 "strovite forte": "2",
 "sufenta": "2",
 "sectral": "2",
 "seconal sodium pulvules": "2"}, "r": {"ropivacaine/sufentanil": "2",
 "risperdal m-tab": "2",
 "robitussin-ac": "2",
 "re dualvit f": "2",
 "robitussin-dac": "2",
 "roxanol 100": "2",
 "reclipsen": "1",
 "resource optisource": "2",
 "regroton": "1",
 "re dualvit plus": "2",
 "renaplex": "2",
 "rosuvastatin": "2",
 "rolaids extra strength softchews": "2",
 "renatabs with iron": "2",
 "rulox plus": "1",
 "rapacuronium": "2",
 "rolaids extra strength plus gas relief softchews": "2",
 "recal d": "2",
 "rifampin": "2",
 "rolaids regular strength": "2",
 "risacal-d": "2",
 "roxicet": "2",
 "rivastigmine": "2",
 "razadyne": "2",
 "rescriptor": "2",
 "req49+": "2",
 "renax 5.5": "2",
 "rheumatrex dose pack": "2",
 "roxicodone": "2",
 "rolatuss": "2",
 "ryna-cx": "2",
 "ramipril": "1",
 "raxar": "2",
 "rauzide": "1",
 "roxanol-t": "2",
 "raplon": "2",
 "rifater": "2",
 "robimycin": "3",
 "renese-r": "1",
 "rufen": "2",
 "red yeast rice": "2",
 "renate dha extra": "2",
 "rulox 1": "1",
 "rifamate": "2",
 "rifapentine": "2",
 "ridaura": "2",
 "rovin-nv dha": "2",
 "ridactate": "2",
 "rifadin iv": "2",
 "recal fol d": "2",
 "rifadin": "2",
 "rapamune": "2",
 "relafen": "2",
 "re-pb hyos elixir": "2",
 "remicade": "2",
 "roxicodone intensol": "2",
 "robaxisal": "2",
 "rocuronium": "2",
 "rms": "2",
 "re fac-x": "2",
 "revatio": "2",
 "razadyne er": "2",
 "rx support heartburn and acid reflux": "2",
 "rifabutin": "2",
 "re ob 90 plus dha": "2",
 "rondameth": "1",
 "retrovir": "2",
 "roferon-a": "2",
 "rescudose": "2",
 "risanoid plus": "2",
 "risperdal consta": "2",
 "ritonavir": "3",
 "robichem ac": "2",
 "rightstep": "2",
 "roxiprin": "2",
 "remodulin": "2",
 "relcof c": "2",
 "rolaids extra strength": "2",
 "rebetron": "2",
 "reserpine/trichlormethiazide": "1",
 "rectiv": "2",
 "revia": "2",
 "robafen ac": "2",
 "renate": "2",
 "re ob plus dha": "2",
 "rimactane": "2",
 "romilar ac": "2",
 "ru-lets m 500": "2",
 "renax": "2",
 "rebif": "2",
 "rexolate": "2",
 "reprexain": "2",
 "risperidone": "2",
 "rhinocaps": "2",
 "roxilox": "2",
 "ryna-c": "2",
 "reminyl": "2",
 "rolaids multi-symptom": "2",
 "renate dha": "2",
 "rasagiline": "2",
 "rulox": "1",
 "reocyte plus": "2",
 "risperdal": "2",
 "rovin-nv": "2",
 "reyataz": "3",
 "renese": "1",
 "roxanol": "2",
 "rezulin": "2"}, "u": {"uretron": "2",
 "urimax": "2",
 "ursinus": "2",
 "utira": "2",
 "utrona-c": "2",
 "udamin": "2",
 "utrona": "2",
 "ultra mylanta calci tabs": "2",
 "upcal d": "2",
 "unicap senior": "2",
 "urised": "2",
 "urban ds": "1",
 "uritact ds": "2",
 "uni-lan ii": "1",
 "urimar-t": "2",
 "urelief plus": "2",
 "ultra-natal": "2",
 "uretron ds": "2",
 "urapine": "2",
 "unicomplex m": "2",
 "univasc": "1",
 "uni-fac zx": "2",
 "urban": "1",
 "uni-lan": "1",
 "ultimatecare one": "2",
 "u-tri-lone": "2",
 "utira-c": "2",
 "ultane": "2",
 "udamin sp": "2",
 "uni serp": "2",
 "uritin": "2",
 "uni-cof": "2",
 "uta": "2",
 "usept": "2",
 "uni-cof expectorant": "2",
 "urisym": "2",
 "ultimatecare combo": "2",
 "unipres": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "ultimatecare one nf": "2",
 "unicap t": "2",
 "uvadex": "2",
 "uni-thera m with beta carotene": "2",
 "ustell": "2",
 "ultra natalcare": "2",
 "urelle": "2",
 "unicap m": "2",
 "ultimatecare advance": "2",
 "uprima": "2",
 "uribel": "2",
 "ultane pen": "2",
 "uniretic": "1"}, "t": {"toprol-xl": "2",
 "tussiden c": "2",
 "trivora": "1",
 "trizivir": "2",
 "tizanidine": "3",
 "tyvaso": "2",
 "treprostinil": "2",
 "troleandomycin": "3",
 "triglide": "3",
 "tolectin 600": "2",
 "telzir": "3",
 "thiothixene": "2",
 "talwin nx": "2",
 "tylenol with codeine #2": "2",
 "theracal d4000": "2",
 "timolol ophthalmic": "2",
 "tozal": "2",
 "tocilizumab": "2",
 "tricare dha one": "2",
 "titralac plus": "2",
 "trimesis rx": "2",
 "triveen-one": "2",
 "timoptic": "2",
 "tekamlo": "2",
 "tubocurarine": "2",
 "tridil": "2",
 "telbivudine": "2",
 "thiethylperazine": "2",
 "t- koff": "2",
 "tetra-mag": "2",
 "tussirex sugar free": "2",
 "teniposide": "2",
 "teveten hct": "1",
 "tenormin": "2",
 "tipranavir": "3",
 "thera-m enhanced": "2",
 "temaril": "2",
 "trileptal": "2",
 "tacrine": "2",
 "trilisate": "2",
 "talacen": "2",
 "tegretol": "2",
 "trihist-cs": "2",
 "trinessa lo": "1",
 "tolectin ds": "2",
 "theralith xr": "2",
 "theravim m": "2",
 "therobec plus": "2",
 "tums ultra 1000": "2",
 "tums regular strength": "2",
 "tylenol with codeine": "2",
 "trandolapril/verapamil": "2",
 "triphasil-28": "1",
 "tridal": "2",
 "tetrabenazine": "2",
 "t-lite": "2",
 "tussi-organidin nr": "2",
 "triphasil-21": "1",
 "tenoretic": "2",
 "trilog": "2",
 "toradol": "2",
 "taron-prx plus dha": "2",
 "timoptic-xe": "2",
 "titralac plus liquid": "2",
 "thioguanine": "2",
 "trilipix": "3",
 "tolectin": "2",
 "thioridazine": "2",
 "trifluoperazine": "2",
 "tums dual action": "2",
 "tabloid": "2",
 "trichlormethiazide": "1",
 "tinidazole": "2",
 "tab-a-vite maximum": "2",
 "tenoretic 50": "2",
 "thalitone": "1",
 "thera-m": "2",
 "tri-norinyl": "1",
 "talwin": "2",
 "tussar sf": "2",
 "tandem ob": "2",
 "toradol iv/im": "2",
 "travasol with electrolytes dual chamber": "2",
 "tussirex": "2",
 "trandate": "2",
 "trivora-28": "1",
 "tiazac": "2",
 "tykerb": "2",
 "tempo": "1",
 "theodrine": "2",
 "torecan": "2",
 "trinatal rx": "2",
 "targretin": "1",
 "tricare": "2",
 "timolide": "2",
 "telithromycin": "3",
 "torisel": "2",
 "thaissept": "1",
 "trecator": "2",
 "tranylcypromine": "2",
 "taxol": "2",
 "trandolapril": "1",
 "t-gran plus minerals": "2",
 "tricof": "2",
 "tri-levlen": "1",
 "telaprevir": "3",
 "timoptic ocudose": "2",
 "triamonide 40": "2",
 "thorazine": "2",
 "therapy bayer": "2",
 "tasigna": "2",
 "timolol": "2",
 "tyzeka": "2",
 "titralac": "2",
 "tusal": "2",
 "theracal rapid repletion": "2",
 "trycet": "2",
 "tl g-fol os": "2",
 "tristoject": "2",
 "tl-hist cm": "2",
 "tums freshers": "2",
 "ternamar": "2",
 "tramacort-d": "2",
 "tl-hist cd": "2",
 "triacin c": "2",
 "theracal d2000": "2",
 "taxotere": "2",
 "tenoretic 100": "2",
 "triphasil": "1",
 "tri-legest fe": "1",
 "thera-vite m": "2",
 "triflupromazine": "2",
 "triquilar 28": "1",
 "triveen-prx rnf": "2",
 "transderm-nitro": "2",
 "triquilar 21": "1",
 "triavil": "2",
 "trilone": "2",
 "tekturna hct": "2",
 "tums smoothies": "2",
 "tac 3": "2",
 "trimeprazine": "2",
 "tuinal": "2",
 "trac tabs 2x": "2",
 "triadvance": "2",
 "timolide 10-25": "2",
 "tedrigen": "2",
 "tylenol with codeine #3": "2",
 "tylenol with codeine #4": "2",
 "trecator-sc": "2",
 "ticagrelor": "1",
 "tandem dha": "2",
 "talwin compound": "2",
 "triam-forte": "2",
 "tums plus": "2",
 "tricor": "3",
 "tab-a-vite weightslim": "2",
 "triamcot": "2",
 "triam-a": "2",
 "thalomid": "2",
 "therems m": "2",
 "tusso-c": "2",
 "tegretol xr": "2",
 "terrell": "2",
 "travasol with electrolytes": "2",
 "tri-lo-sprintec": "1",
 "taron-c dha": "2",
 "triafed &amp; codeine": "2",
 "tri rx": "2",
 "tarka": "2",
 "taron-bc": "2",
 "tilia fe": "1",
 "theragran-m": "2",
 "trifed c": "2",
 "trezix": "2",
 "tadalafil": "1",
 "tri-hydroserpine": "2",
 "triamcinolone": "2",
 "theragener-m": "2",
 "tandem plus": "2",
 "thera hematinic": "2",
 "theragener-h": "2",
 "trilafon": "2",
 "tab-a-vite womens formula": "2",
 "tussar-2": "2",
 "tolmetin": "2",
 "tylox": "2",
 "tums kids": "2",
 "taztia xt": "2",
 "tindamax": "2",
 "tracleer": "2",
 "tribenzor": "1",
 "toradol im": "2",
 "troglitazone": "2",
 "tums extra strength 750": "2",
 "toposar": "2",
 "tri-legest": "1",
 "tri-buffered aspirin": "2",
 "trinate": "2",
 "taron-ec calc dha pack": "2",
 "tace": "1",
 "tricosal": "2",
 "teczem": "2",
 "tri-previfem": "1",
 "treximet": "2",
 "tussi-organidin-s nr": "2",
 "thalidomide": "2",
 "tacaryl": "2",
 "trinessa": "1",
 "thais": "1",
 "tusscough dhc": "2",
 "tacrolimus": "2",
 "therapeutic-m": "2",
 "tekturna": "2",
 "trexall": "2",
 "tracrium": "2",
 "tao": "3",
 "tri-sprintec": "1",
 "temsirolimus": "2"}, "w": {"wellbutrin xl": "2",
 "welltuss exp": "2",
 "womens pack": "2",
 "warfarin": "1",
 "wygesic": "2",
 "wellesse liquid calcium with vitamin d": "2",
 "wellbutrin sr": "2",
 "wellbutrin": "2"}, "v": {"vitalize plus": "2",
 "versed": "2",
 "vivelle-dot": "1",
 "vinate advanced": "2",
 "verotin-by": "2",
 "viactiv multi-vitamin": "2",
 "vi-zac": "2",
 "vigortol liquid": "2",
 "vanspar": "2",
 "valertest no 1": "1",
 "v-gan-50": "2",
 "venatal fa": "2",
 "vumon": "2",
 "viagra": "2",
 "vardenafil": "2",
 "viactiv calcium flavor glides": "2",
 "vica-forte": "2",
 "vinate care": "2",
 "victrelis": "3",
 "vinate good start": "2",
 "vimpat": "2",
 "vepesid": "2",
 "vincristine": "2",
 "vitanatal ob plus dha": "2",
 "vaseretic": "1",
 "videx ec": "2",
 "vinate az extra": "2",
 "valturna": "2",
 "vinate ic": "2",
 "vanacof cd": "2",
 "vytorin": "3",
 "vinate ii": "2",
 "verteporfin": "2",
 "videx": "2",
 "vitaspire": "2",
 "vinate ultra": "2",
 "vinate 90": "2",
 "vitafol-ob+dha": "2",
 "verelan pm": "2",
 "vasotec": "1",
 "vitaphil": "2",
 "vitelle nestabs otc": "2",
 "viracept": "3",
 "velivet": "1",
 "vitatrum": "2",
 "vynatal fa": "2",
 "valergen": "1",
 "vol-nate": "2",
 "vitatab mv": "2",
 "voltaren-xr": "2",
 "vicon forte": "2",
 "voriconazole": "2",
 "viramune": "2",
 "velcade": "2",
 "venlafaxine": "2",
 "vaseretic 5-12.5": "1",
 "vincasar pfs": "2",
 "vitamax": "2",
 "vaseretic 10-25": "1",
 "vinatal forte": "2",
 "vanquish": "2",
 "vinate iii": "2",
 "visken": "2",
 "vital-d": "2",
 "vaprisol": "3",
 "vitaphil plus dha": "2",
 "viramune xr": "2",
 "vemavite prx 2": "2",
 "vimovo": "2",
 "vinorelbine": "2",
 "vitamed prenatal formula": "2",
 "vestura": "1",
 "vol-plus": "2",
 "verelan": "2",
 "vitaphil aide": "2",
 "vitafol pn": "2",
 "vita-zinc": "2",
 "vecuronium": "2",
 "vicoprofen": "2",
 "vita zx": "2",
 "vinacal or": "2",
 "viactiv soft calcium chews": "2",
 "veripred 20": "2",
 "vernate": "2",
 "visudyne": "2",
 "v-gan-25": "2",
 "vita-dec": "2",
 "vicon plus": "2",
 "vinate pn care": "2",
 "voltaren": "2",
 "vagifem": "1",
 "vernate advanced": "2",
 "vicap forte": "2",
 "vivitrol": "2",
 "vinate one": "2",
 "vitafol-ob": "2",
 "vinblastine": "2",
 "viva dha": "2",
 "vicon-c": "2",
 "vol-tab rx": "2",
 "victoza": "1",
 "vita-min rx": "2",
 "vfend": "2",
 "vynatal 1 plus 1": "2",
 "vinate az": "2",
 "v-c forte": "2",
 "vita s forte": "2",
 "vinate c": "2",
 "vitacon forte": "2",
 "vinate m": "2",
 "vitafol": "2",
 "vinate calcium": "2",
 "vitaplex plus": "2",
 "velban": "2",
 "verapamil": "2",
 "vopac": "2",
 "viactiv multi-vitamin flavor glides": "2",
 "vinate gt": "2",
 "viogen-c": "2",
 "veletri": "2",
 "vivelle": "1",
 "verotin-gr": "2",
 "vinatal 600": "2",
 "ventavis": "2"}, "y": {"yervoy": "2",
 "yodoxin": "2",
 "ysp aspirin": "2",
 "yasmin": "1",
 "yaz": "1"}, "x": {"xalkori": "2",
 "xenazine": "2",
 "xolox": "2"}, "z": {"zinc plus lozenges": "2",
 "zmax": "2",
 "zorprin": "2",
 "zovia 1/50": "1",
 "z-tuss ac": "2",
 "zatean-pn dha": "2",
 "zenate prenatal": "2",
 "zitamin": "2",
 "zenate": "2",
 "zyprexa zydis": "2",
 "zatean-pn": "2",
 "zarah": "1",
 "zileuton": "1",
 "zocor": "3",
 "zovia 1/35": "1",
 "zema pak": "2",
 "zumenon": "1",
 "zestoretic": "1",
 "z-gen": "2",
 "zyvox": "2",
 "zenate advanced formula": "2",
 "zemuron": "2",
 "zeosa": "1",
 "zero-order release": "2",
 "zidovudine": "2",
 "zithromax": "2",
 "zyprexa": "2",
 "zebeta": "2",
 "zatean-pn plus": "2",
 "ziprasidone": "2",
 "ze-plus": "2",
 "zyprexa intramuscular": "2",
 "zodryl dec": "2",
 "zerit": "2",
 "zegerid otc": "2",
 "zerlor": "2",
 "zipsor": "2",
 "zodryl dac": "2",
 "zincvit": "2",
 "z-bec": "2",
 "zerit xr": "2",
 "zafirlukast": "2",
 "zyflo cr": "1",
 "zodryl ac": "2",
 "zyban": "2",
 "zaponex": "2",
 "zyflo": "1",
 "zelapar": "2",
 "zenchent fe": "1",
 "zanaflex": "3",
 "zegerid": "2",
 "zatean-ch": "2",
 "zenchent": "1",
 "zotex-c": "2",
 "zovia": "1",
 "zalcitabine": "2",
 "zestril": "1",
 "zaroxolyn": "1",
 "zyprexa relprevv": "2",
 "ziac": "2",
 "zodeac-100": "2",
 "zetia": "2"}}];