interactions["amoxicillin-clarithromycin-lansoprazole,prevpac"]=["amoxicillin-clarithromycin-lansoprazole,prevpac", {"a": {"aspirin/butalbital/caffeine/codeine": "1",
 "ascorbic acid/ferrous sulfate": "2",
 "aspirin/hydrocodone": "1",
 "azithromycin dose pack": "2",
 "anacin": "1",
 "amphotericin b liposomal": "2",
 "agenerase": "1",
 "aspir-low": "1",
 "aspergum": "1",
 "adoxa ck": "2",
 "aristocort": "2",
 "abiraterone": "2",
 "alfenta": "3",
 "alavert": "1",
 "alyacen 7/7/7": "2",
 "aloxi": "2",
 "allergy &amp; congestion relief": "1",
 "aspirin/caffeine/orphenadrine": "1",
 "ascriptin enteric": "1",
 "allergy relief d 24 hour": "1",
 "ampicillin": "2",
 "azurette": "2",
 "amphotericin b lipid complex": "2",
 "aspirin/chlorpheniramine/phenylephrine": "1",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "aflaxen": "2",
 "alprazolam": "2",
 "aminatal plus new formula": "2",
 "adenocard": "2",
 "actiq": "3",
 "aspirin/oxycodone": "1",
 "apo-go pen": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "altocor": "3",
 "ambien cr": "1",
 "aspir-mox": "2",
 "amitriptyline": "2",
 "agoral": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "aristopak": "2",
 "aspircaf": "1",
 "aspiritab": "1",
 "amethyst": "2",
 "anaflex": "1",
 "aldoril": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aralen hydrochloride": "2",
 "aricept": "1",
 "ambien": "1",
 "aldoril 15": "2",
 "alimta": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "allegra odt": "1",
 "alor 5/500": "1",
 "ami-rax": "2",
 "argesic-sa": "1",
 "alka-seltzer plus flu formula": "1",
 "adderall xr": "2",
 "anacin advanced headache formula": "1",
 "acetohexamide": "2",
 "allegra allergy": "1",
 "aerospan hfa": "2",
 "aspirin buffered": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "1",
 "allens junior cough": "2",
 "abarelix": "2",
 "alodox": "2",
 "atacand hct": "2",
 "aldoril d50": "2",
 "amlodipine/atorvastatin": "3",
 "amikacin": "2",
 "anemagen fa": "2",
 "atazanavir": "3",
 "anhydrous calcium iodide/isoproterenol": "2",
 "adoxa tt": "2",
 "alesse-21": "2",
 "arthritis pain": "1",
 "aspirin/pravastatin": "1",
 "amphocin": "2",
 "alesse-28": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "adriamycin rdf": "2",
 "acetaminophen/aspirin": "1",
 "a-hydrocort": "2",
 "accuretic": "2",
 "anaprox": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "1",
 "aerolate iii": "2",
 "amikin pediatric": "2",
 "albuterol/ipratropium": "2",
 "azithromycin": "2",
 "adriamycin": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "azmacort": "2",
 "aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "1",
 "avonex prefilled syringe": "2",
 "aspirin/caffeine": "1",
 "amphotericin b": "2",
 "accesspak for hiv pep expanded with viracept": "3",
 "achromycin v": "2",
 "ambrisentan": "1",
 "antinaus 50": "2",
 "abraxane": "2",
 "asbron g": "2",
 "ascomp with codeine": "1",
 "alka-seltzer extra strength": "1",
 "avelox": "3",
 "aliskiren/valsartan": "2",
 "advicor": "3",
 "acetaminophen/aspirin/caffeine": "1",
 "aleve": "2",
 "anergan 50": "2",
 "adrenocot": "2",
 "aerobid": "2",
 "adlone-40": "2",
 "anaprox-ds": "2",
 "adult strength": "1",
 "anemagen": "2",
 "apri": "2",
 "aminate": "2",
 "altoprev": "3",
 "aminatal plus": "2",
 "advair diskus": "3",
 "aspirin/methocarbamol": "1",
 "aliskiren/amlodipine": "2",
 "ascorbic acid/iron polysaccharide": "2",
 "arthriten": "1",
 "allbee-c 800 with iron": "2",
 "accuneb": "2",
 "amikin": "2",
 "arformoterol": "2",
 "albuterol": "2",
 "avandaryl": "2",
 "allanderm-t": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "afeditab cr": "2",
 "aloprim": "1",
 "aldroxicon ii": "2",
 "a-methapred": "2",
 "acetocot": "2",
 "arcapta": "2",
 "alka-seltzer wake-up call!": "1",
 "aggrenox": "1",
 "arthritis pain formula": "2",
 "aricept odt": "1",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "aralen phosphate": "2",
 "aerobid-m": "2",
 "alka-seltzer original": "1",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "aspirin/meprobamate": "1",
 "aminatal plus one": "2",
 "almacone-2": "2",
 "advair hfa": "3",
 "amethia": "2",
 "amiloride": "1",
 "amigesic": "1",
 "allegra hives": "1",
 "a-cillin": "1",
 "aristocort for injection": "2",
 "acetaminophen/caffeine/magnesium salicylate": "1",
 "aminophylline": "2",
 "aminate with 90 mg iron": "2",
 "aspirin/citric acid/sodium bicarbonate": "1",
 "allopurinol": "1",
 "alka-seltzer lemon-lime": "1",
 "apomorphine": "2",
 "acetylsalicylic acid": "1",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "aspirin/butalbital/caffeine": "1",
 "arthropan": "1",
 "avidoxy": "2",
 "adriamycin pfs": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2",
 "aldoril 25": "2",
 "amphotericin b cholesteryl sulfate": "2",
 "advance care plus": "2",
 "arsenic trioxide": "3",
 "alfuzosin": "3",
 "aspirin/caffeine/dihydrocodeine": "1",
 "ala-tet": "2",
 "all day relief": "2",
 "astemizole": "3",
 "alprazolam intensol": "2",
 "abilify": "2",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "all day pain relief": "2",
 "apokyn": "2",
 "avelox i.v.": "3",
 "aspirin low strength": "1",
 "asenapine": "2",
 "aspirin/diphenhydramine": "1",
 "aprepitant": "2",
 "abstral": "3",
 "alyacen 1/35": "2",
 "adalat": "2",
 "aspir-mox ib": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "altavera": "2",
 "alka-seltzer plus cold formula": "1",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "alka-seltzer pm": "1",
 "actoplus met xr": "2",
 "adapin": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "1",
 "amphotec": "2",
 "artemether/lumefantrine": "3",
 "adcetris": "2",
 "alosetron": "2",
 "ampicillin/sulbactam": "2",
 "anacin max strength": "1",
 "azdone": "1",
 "adalat cc": "2",
 "aspirin": "1",
 "acetaminophen/aspirin/phenylpropanolamine": "1",
 "allegra-d 12 hour": "1",
 "avonex": "2",
 "amphetamine/dextroamphetamine": "2",
 "adlone-80": "2",
 "azithromycin/trovafloxacin": "2",
 "aspirin/calcium carbonate": "1",
 "apresazide": "2",
 "anafranil": "2",
 "atrosept": "1",
 "aristospan": "2",
 "allerclear d-24 hour": "1",
 "aerolate sr": "2",
 "aquaphyllin": "2",
 "aldoclor-250": "2",
 "acuprin 81": "1",
 "apo-go": "2",
 "anemagen forte": "2",
 "ascriptin maximum strength": "2",
 "aerolate jr": "2",
 "aminophylline/guaifenesin": "2",
 "alfentanil": "3",
 "alvesco": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "adbeon": "2",
 "aspirin/chlorpheniramine/dextromethorphan": "1",
 "aspirtab": "1",
 "almotriptan": "2",
 "aspirin/phenyltoloxamine": "1",
 "aldoclor-150": "2",
 "alupent": "2",
 "ampicillin/probenecid": "2",
 "actisite": "2",
 "aspirin/carisoprodol/codeine": "1",
 "aripiprazole": "2",
 "adenosine": "2",
 "asmalix": "2",
 "adderall": "2",
 "asendin": "2",
 "aspirin/pseudoephedrine": "1",
 "allegra": "1",
 "avalide": "2",
 "almacone": "2",
 "atripla": "2",
 "atenolol/chlorthalidone": "2",
 "amaryl": "2",
 "afinitor": "3",
 "ami-natal plus one improved": "2",
 "allergy relief tablets": "1",
 "aptivus": "2",
 "acetaminophen/propoxyphene": "2",
 "atabex ec": "2",
 "alamag": "2",
 "alamag plus": "2",
 "aspirin/carisoprodol": "1",
 "aliskiren": "2",
 "atorvastatin": "3",
 "ambisome": "2",
 "ari sodium iodide (i123) 100-750 mbq": "2",
 "avodart": "2",
 "ari sodium iodide (i123) 1-12 mbq": "2",
 "aer witch hazel": "2",
 "armodafinil": "1",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "1",
 "aldoril d30": "2",
 "amoxapine": "2",
 "amethia lo": "2",
 "amiloride/hydrochlorothiazide": "2",
 "aranelle": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "1",
 "aralen": "2",
 "actoplus met": "2",
 "adrenocot la": "2",
 "actos": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "alesse": "2",
 "aquacot": "2",
 "adeno-jec": "2",
 "asthmacon": "2",
 "adenoscan": "2",
 "avidoxy dk": "2",
 "alavert d-12 hour allergy and sinus": "1",
 "ascorbic acid/ferrous fumarate": "2",
 "aventyl hydrochloride": "2",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "aqualax forte": "2",
 "acid reducer + antacid dual action": "2",
 "amprenavir": "1",
 "aspirin lite coat": "1",
 "aspirin/butalbital": "1",
 "aldroxicon i": "2",
 "aquazide h": "2",
 "aspir 81": "1",
 "ascriptin": "2",
 "anzemet": "3",
 "amturnide": "2",
 "aspirin/codeine": "1",
 "airet": "2",
 "amiodarone": "3",
 "aspirin/pentazocine": "1",
 "alophen": "2",
 "abelcet": "2",
 "abacavir/lamivudine/zidovudine": "1",
 "apetimar with iron": "2",
 "amphetamine": "2",
 "altabax": "1",
 "aldactazide": "2",
 "adoxa": "2",
 "aleve-d sinus &amp; cold": "2",
 "adcirca": "2",
 "anisindione": "3",
 "aspirin/caffeine/salicylamide": "1",
 "arthritis foundation pain reliever": "1",
 "anemagen ob": "2",
 "allegra-d 24 hour": "1",
 "amersham indium (111in) oxine": "2",
 "aviane": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "1",
 "aspirin/dipyridamole": "1",
 "axert": "2",
 "abilify discmelt": "2",
 "aquatensen": "2"}, "c": {"colcrys": "3",
 "cvs extra strength headache relief": "1",
 "chlorothiazide/methyldopa": "2",
 "cascara sagrada/magnesium hydroxide": "2",
 "cartia xt": "2",
 "colchicine/probenecid": "3",
 "cerebyx": "1",
 "cardoxin": "2",
 "cal-nate": "2",
 "citrate of magnesia": "2",
 "cellcept": "2",
 "capozide 50/25": "2",
 "cerivastatin": "3",
 "cobal 1000": "1",
 "cisplatin": "2",
 "cyclafem 7/7/7": "2",
 "caffeine/ergotamine": "3",
 "carbonyl iron": "2",
 "ciclesonide": "2",
 "combi rx": "2",
 "crixivan": "2",
 "cephulac": "2",
 "cipro i.v.": "2",
 "citracal prenatal + dha": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "clozapine synthon": "2",
 "concept dha": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "cardizem cd": "2",
 "chlorthalidone/reserpine": "2",
 "cortisone": "2",
 "claritin": "1",
 "cobolin-m": "1",
 "clopidogrel": "2",
 "choline magnesium trisalicylate": "1",
 "citalopram": "3",
 "cryselle": "2",
 "cavan-heme ob": "2",
 "cyanocobalamin/folic acid/pyridoxine/strontium gluconate": "1",
 "corzide 40/5": "2",
 "cafergot": "3",
 "cotrim": "1",
 "cardizem sr": "2",
 "co-trimoxazole": "1",
 "cortenema": "2",
 "clavulanate/ticarcillin": "1",
 "cefditoren": "2",
 "claritin hives relief": "1",
 "cort-k": "2",
 "co natal fa": "2",
 "cafetrate": "3",
 "capastat": "2",
 "celestone phosphate": "2",
 "corgard": "1",
 "chlorothiazide/reserpine": "2",
 "calan sr": "2",
 "colace glycerin suppositories": "2",
 "chronulac syrup": "2",
 "clozapine": "2",
 "completenate": "2",
 "cavan folate": "2",
 "clearlax": "2",
 "cycloset": "2",
 "carozide": "2",
 "cardizem": "2",
 "cisapride": "3",
 "caduet": "3",
 "chirocaine": "2",
 "citranatal harmony": "2",
 "choledyl": "2",
 "cholecalciferol/genistein/zinc chelazome": "1",
 "clobazam": "2",
 "chocolaxed": "2",
 "cyclosporine": "3",
 "celexa": "3",
 "cipro": "2",
 "chromagen ob": "2",
 "corzide": "2",
 "cortifoam": "2",
 "cabergoline": "3",
 "citracal prenatal rx": "2",
 "cardizem la": "2",
 "cascara sagrada": "2",
 "calan": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "carafate": "2",
 "cyanoject": "1",
 "chromagen forte": "2",
 "comfort pac with naproxen": "2",
 "complete-rf": "2",
 "cloxapen": "1",
 "clofarabine": "2",
 "compazine spansule": "2",
 "cholac": "2",
 "clorpres": "2",
 "cyomin": "1",
 "chlordinium": "2",
 "casanthranol": "2",
 "ceo-two": "2",
 "chlordiazepoxide/clidinium": "2",
 "cerubidine": "2",
 "claritin-d 24 hour": "1",
 "caprelsa": "3",
 "candesartan/hydrochlorothiazide": "2",
 "chronulac": "2",
 "cinacalcet": "2",
 "clopine": "2",
 "carboplatin": "2",
 "conivaptan": "3",
 "constulose": "2",
 "correctol": "2",
 "complera": "3",
 "cyanocobalamin": "1",
 "compro": "2",
 "choledyl sa": "2",
 "clozaril": "2",
 "constilac": "2",
 "cefuroxime": "2",
 "cipro xr": "2",
 "colazal": "2",
 "clorazepate": "2",
 "cascara sagrada/phenolphthalein": "2",
 "cell-u-jec": "2",
 "chromagen fa": "2",
 "cortef": "2",
 "cafatine pb": "3",
 "clear-atadine children's": "1",
 "chlordiazepoxide": "2",
 "cardioquin": "2",
 "chlordiazepoxide/methscopolamine": "2",
 "casanthranol/docusate": "2",
 "chlorthalidone/clonidine": "2",
 "combivir": "1",
 "chlorpropamide": "2",
 "citracal prenatal 90+dha": "2",
 "cystex": "1",
 "contrin": "2",
 "cotrim pediatric": "1",
 "cordarone": "3",
 "cafatine": "3",
 "combivent": "2",
 "capozide 25/15": "2",
 "children's claritin allergy": "1",
 "cordarone iv": "3",
 "clomipramine": "2",
 "ciprofloxacin": "2",
 "colchicine": "3",
 "corvert": "3",
 "cardizem monovial": "2",
 "chromagen": "2",
 "cyclafem 1/35": "2",
 "cilostazol": "2",
 "carenatal dha": "2",
 "chromatinic": "2",
 "conison": "2",
 "calomist": "1",
 "chlorthalidone": "2",
 "castor oil": "2",
 "carbenicillin": "1",
 "clindex": "2",
 "chloroquine": "2",
 "cymbalta": "1",
 "cimetidine": "1",
 "capastat sulfate": "2",
 "cope": "1",
 "carboplatin novaplus": "2",
 "carbamazepine": "3",
 "cidomycin": "2",
 "cmt": "1",
 "clinacort": "2",
 "ceftin": "2",
 "cavan ec dha plus": "2",
 "complete natal dha": "2",
 "crystamine": "1",
 "capozide 50/15": "2",
 "cesia": "2",
 "combivent respimat": "2",
 "cefpodoxime": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "colax": "2",
 "caziant": "2",
 "caffeine/magnesium salicylate": "1",
 "cotolone": "2",
 "corvite fe": "2",
 "citranatal assure": "2",
 "choline salicylate": "1",
 "chem-sol": "2",
 "claritin-d": "1",
 "citranatal dha": "2",
 "ciclesonide nasal": "2",
 "clolar": "2",
 "cetuximab": "2",
 "celestone soluspan": "2",
 "codeine/phenylephrine/promethazine": "2",
 "cafgesic forte": "1",
 "coartem": "3",
 "codeine/promethazine": "2",
 "cortone acetate": "2",
 "carbatrol": "3",
 "captopril/hydrochlorothiazide": "2",
 "claritin reditabs": "1",
 "carter's little pills": "2",
 "cystemms-v": "1",
 "cevimeline": "2",
 "carisoprodol compound": "1",
 "clear-atadine-d": "1",
 "cloxacillin": "1",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "1",
 "chlorpromazine": "2",
 "complete natal": "2",
 "crystal b-12": "1",
 "choline salicylate/magnesium salicylate": "1",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "celestone": "2",
 "cavan-folate dha": "2",
 "colocort": "2",
 "citranatal rx": "2",
 "covera-hs": "2",
 "citranatal b-calm": "2",
 "clear-atadine": "1",
 "camreselo": "2",
 "capreomycin": "2",
 "cabazitaxel": "2",
 "claritin-d 12 hour": "1",
 "clonazepam": "2",
 "corzide 80/5": "2",
 "cipro cystitis pack": "2",
 "codeine phosphate-promethazine hcl": "2",
 "clinalog": "2",
 "chlorothiazide": "2",
 "claritin 24 hour allergy": "1",
 "compazine": "2",
 "crysti-12": "1",
 "camrese": "2",
 "citroma": "2",
 "cenogen ultra": "2",
 "capozide": "2",
 "capozide 25/25": "2",
 "concept ob": "2",
 "combiflex es": "1",
 "cholecalciferol/genistein/zinc glycinate": "1",
 "cavan one": "2",
 "cotrim ds": "1",
 "crizotinib": "3",
 "citranatal 90 dha": "2",
 "cyclessa": "2",
 "cialis": "2",
 "coumadin": "3",
 "caroid laxative": "2"}, "b": {"bellaphen-s": "3",
 "buffasal": "1",
 "briellyn": "2",
 "bisacodyl uniserts": "2",
 "bisacodyl/magnesium citrate": "2",
 "bayer am": "1",
 "benzthiazide": "2",
 "brovana": "2",
 "bisacodyl": "2",
 "bayer pm": "1",
 "bayer aspirin extra strength plus": "1",
 "b c powder arthritis strength": "1",
 "bactrim": "1",
 "bitolterol": "2",
 "benicar hct": "2",
 "buspirone": "2",
 "bisco-lax": "2",
 "bel-phen-ergot": "3",
 "bromocriptine": "2",
 "bronchial": "2",
 "bayer women's aspirin with calcium": "1",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "bifera": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "b-12 dots": "1",
 "betapace af": "3",
 "bisa-lax": "2",
 "brethaire": "2",
 "bayer children's aspirin": "1",
 "buspar": "2",
 "bumex": "2",
 "beclovent": "2",
 "betapace": "3",
 "brondelate": "2",
 "bactrim iv": "1",
 "b c powder": "1",
 "bayer extra strength back &amp; body": "1",
 "bortezomib": "2",
 "beta-phos/ac": "2",
 "bethaprim pediatric": "1",
 "bricanyl": "2",
 "buffered aspirin": "1",
 "bonisara": "1",
 "butrans": "2",
 "beyaz": "2",
 "baraclude": "2",
 "bisac-evac": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "2",
 "betaseron": "2",
 "bayer aspirin": "1",
 "balacet": "2",
 "b-nexa": "2",
 "bactocill": "1",
 "bellaspas": "3",
 "black cohosh": "2",
 "beepen-vk": "1",
 "betamethasone": "2",
 "benemid": "1",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bethaprim": "1",
 "boots cough syrup 3 months plus": "2",
 "baycadron": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "3",
 "bp multinatal plus chewables": "2",
 "bellamine": "3",
 "bepridil": "3",
 "bayer select backache pain formula": "1",
 "bel-tabs": "3",
 "bronkometer": "2",
 "bendroflumethiazide": "2",
 "brethine": "2",
 "bendroflumethiazide/nadolol": "2",
 "broncodur": "2",
 "balsalazide": "2",
 "bayer advanced aspirin": "1",
 "balziva": "2",
 "bosentan": "2",
 "bc headache": "1",
 "bisolax": "2",
 "broncomar gg": "2",
 "bufferin extra strength": "1",
 "buprenex": "2",
 "bayer aspirin with heart advantage": "1",
 "budesonide/formoterol": "2",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "brentuximab": "2",
 "buprenorphine/naloxone": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "2",
 "big shot b-12": "1",
 "black draught": "2",
 "bactrim pediatric": "1",
 "boceprevir": "2",
 "bandi s15": "2",
 "buprenorphine": "2",
 "bayer aspirin regimen": "1",
 "bellergal-s": "3",
 "bronkodyl": "2",
 "bellamine s": "3",
 "bufferin low dose": "1",
 "bufferin": "1",
 "belladonna/ergotamine/phenobarbital": "3",
 "bayer women's low dose plus calcium": "1",
 "benazepril/hydrochlorothiazide": "2",
 "benzoic acid/methenamine/sodium salicylate": "1",
 "bactimicina allergy": "1",
 "bicillin l-a": "1",
 "bisa-plex": "2",
 "belcomp-pb": "3",
 "brilinta": "3",
 "bupivacaine/fentanyl": "3",
 "brevicon": "2",
 "butalbital compound": "1",
 "bextra": "2",
 "balsam peru/castor oil/trypsin topical": "2",
 "bicillin c-r 900/300": "1",
 "bumetanide": "2",
 "buffex": "1",
 "budesonide": "2",
 "bellamor": "3",
 "bufferin arthritis strength": "1",
 "b-12 resin": "1",
 "bronkosol": "2",
 "bc fast pain relief": "1",
 "biferarx": "2",
 "bugs bunny with iron chewable": "2",
 "benefiber": "2",
 "bacampicillin": "2",
 "baycol": "3",
 "bexarotene": "2",
 "bright beginnings": "2",
 "benzathine penicillin/procaine penicillin": "1",
 "bactrim ds": "1",
 "bicillin c-r": "1",
 "bubbli-pred": "2",
 "brodspec": "2",
 "beclomethasone": "2",
 "balsam peru/castor oil topical": "2"}, "e": {"eplerenone": "3",
 "escitalopram": "2",
 "ecotrin maximum strength": "1",
 "effient": "1",
 "entaprin": "1",
 "ergonovine": "3",
 "elidel": "1",
 "ex-lax ultra": "2",
 "espotabs": "2",
 "ethinyl estradiol/levonorgestrel": "2",
 "edurant": "3",
 "endep": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enpresse": "2",
 "ec-naprosyn": "2",
 "e.e.s.-400": "3",
 "ex-lax maximum relief formula": "2",
 "emend": "2",
 "emtet-500": "2",
 "eryped": "3",
 "emagrin": "1",
 "ethinyl estradiol/etonogestrel": "2",
 "excedrin menstrual complete": "1",
 "equi-cyte f": "2",
 "enulose": "2",
 "effervescent pain relief": "1",
 "embeda": "2",
 "exforge hct": "2",
 "elavil": "2",
 "ephedrine/guaifenesin/theophylline": "2",
 "extra strength bayer": "1",
 "ezfe": "2",
 "estazolam": "2",
 "erythrocot": "3",
 "elemental iron-90": "2",
 "extavia": "2",
 "evac-u-gen": "2",
 "equi-roca plus": "2",
 "equibron g": "2",
 "equicyte plus": "2",
 "ecotrin adult low strength": "1",
 "ex-lax extra gentle": "2",
 "equi-natal plus": "2",
 "ergotrate": "3",
 "edge ob": "2",
 "easprin": "1",
 "ethinyl estradiol/norgestrel": "2",
 "ezide": "2",
 "ercaf": "3",
 "edecrin": "2",
 "emoquette": "2",
 "estinyl": "2",
 "emulsoil": "2",
 "edarbyclor": "2",
 "elite ob with dha": "2",
 "evoxac": "2",
 "emend 2-day": "2",
 "ezogabine": "2",
 "enalapril/felodipine": "2",
 "erythromycin": "3",
 "eszopiclone": "2",
 "enduron": "2",
 "ecpirin": "1",
 "ethacrynic acid": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ethinyl estradiol/norethindrone": "2",
 "emend 3-day": "2",
 "entecavir": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "ed-bron g": "2",
 "e s p": "3",
 "e.e.s.-200": "3",
 "esimil": "2",
 "etrafon forte": "2",
 "equi-natal care": "2",
 "exna": "2",
 "everolimus": "3",
 "e-caff p-b": "3",
 "equetro": "3",
 "enalapril/hydrochlorothiazide": "2",
 "equaline acid reducer": "1",
 "epitol": "3",
 "elixophyllin ki": "2",
 "evalose": "2",
 "equinatal 90": "2",
 "efavirenz": "2",
 "emend for injection": "2",
 "ecotrin": "1",
 "ex-lax gentle strength": "2",
 "enduronyl": "2",
 "emtricitabine/rilpivirine/tenofovir": "3",
 "emtricitabine/nelfinavir/tenofovir": "3",
 "eribulin": "2",
 "exjade": "2",
 "epirubicin": "2",
 "erythrocin lactobionate": "3",
 "e.e.s.-400 filmtab": "3",
 "ethinyl estradiol": "2",
 "evac-q-kwik": "2",
 "entocort ec": "2",
 "e-mycin": "3",
 "excedrin back &amp; body": "1",
 "elite ob 400": "2",
 "edluar": "1",
 "endodan": "1",
 "ex-lax chocolated": "2",
 "ethinyl estradiol/norgestimate": "2",
 "entercote": "1",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "eskalith": "2",
 "ergomar": "3",
 "e.e.s. granules": "3",
 "eskalith-cr": "2",
 "empirin with codeine": "1",
 "equi-natal rx": "2",
 "ergocomp-pb": "3",
 "estrostep fe": "2",
 "excedrin migraine": "1",
 "esidrix": "2",
 "equagesic": "1",
 "ex-lax milk of magnesia": "2",
 "enablex": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "ed cyte f": "2",
 "ellence": "2",
 "elixophyllin": "2",
 "ery-tab": "3",
 "ergotamine": "3",
 "excedrin extra strength": "1",
 "ethinyl estradiol/ethynodiol": "2",
 "ethotoin": "1",
 "etrafon": "2",
 "ex-lax gentle nature": "2",
 "erbitux": "2",
 "esomeprazole/naproxen": "2",
 "erlotinib": "2",
 "ergocaf-pb": "3",
 "ex-lax regular strength pills": "2",
 "emblon": "2",
 "ex-lax": "2",
 "eryc": "3",
 "efavirenz/emtricitabine/tenofovir": "2",
 "eperbel-s": "3",
 "erythromycin/sulfisoxazole": "3",
 "etravirine": "2",
 "erythrocin": "3",
 "ezetimibe/simvastatin": "3",
 "ethinyl estradiol/norelgestromin": "2",
 "erythrocin stearate filmtab": "3",
 "ella": "1",
 "equi-natal z": "2",
 "elixophyllin gg": "2",
 "ergotrate maleate": "3",
 "empirin": "1",
 "equi-natal m": "2",
 "elemental iron": "2",
 "ergocaffpb": "3",
 "eryzole": "3",
 "excedrin": "1",
 "enduronyl forte": "2",
 "eletriptan": "3"}, "d": {"diazepam intensol": "2",
 "diastat": "2",
 "dr caldwell laxative": "2",
 "desyrel": "2",
 "duragesic-75": "3",
 "daunorubicin": "2",
 "dronedarone": "3",
 "delavirdine": "2",
 "duet dha ec": "2",
 "dalalone dp": "2",
 "daily-vite with iron": "2",
 "doxy 100": "2",
 "di-gel": "2",
 "demadex": "2",
 "dutasteride": "2",
 "detrol": "2",
 "diuril": "2",
 "depacon": "2",
 "dolasetron": "3",
 "doryx": "2",
 "docu soft plus": "2",
 "dep medalone 80": "2",
 "diltiazem hydrochloride cd": "2",
 "diovan hct": "2",
 "dolsed": "1",
 "daunoxome": "2",
 "dextromethorphan/quinidine": "2",
 "doxidan tablet": "2",
 "duo-vil": "2",
 "doan's pills": "1",
 "doxepin": "2",
 "dok plus": "2",
 "dioctolose": "2",
 "dizac": "2",
 "dostinex": "3",
 "demi-regroton": "2",
 "desogestrel/ethinyl estradiol": "2",
 "docucal-p": "2",
 "diltiazem hydrochloride sr": "2",
 "diupres-500": "2",
 "duoneb": "2",
 "divalproex sodium": "2",
 "dialose plus": "2",
 "dermuspray": "2",
 "di-gel mint": "2",
 "diltzac": "2",
 "depmedalone": "2",
 "doans pm": "1",
 "dificid": "1",
 "dutoprol": "2",
 "decadron with xylocaine": "2",
 "dulcogen": "2",
 "duphalac": "2",
 "depakote er": "2",
 "dexilant": "2",
 "dexamethasone/lidocaine": "2",
 "darvon compound 32": "2",
 "duragesic-50": "3",
 "dalalone la": "2",
 "docosavit": "2",
 "dalfopristin/quinupristin": "2",
 "depakene": "2",
 "diatx fe": "2",
 "duet chewable": "2",
 "damason-p": "1",
 "doral": "2",
 "diocto-c": "2",
 "dymelor": "2",
 "desogen": "2",
 "dasetta 1/35": "2",
 "ducodyl": "2",
 "dexpak taperpak": "2",
 "dexacort phosphate in turbinaire": "2",
 "diphenhydramine/magnesium salicylate": "1",
 "dynacin": "2",
 "docusate/phenolphthalein": "2",
 "dsmc compound plain": "2",
 "definity": "2",
 "diltiazem/enalapril": "2",
 "degarelix": "2",
 "darcalma": "1",
 "doxycycline/omega-3 polyunsaturated fatty acids": "2",
 "diltiazem hydrochloride xt": "2",
 "digitek": "2",
 "diltiazem hydrochloride xr": "2",
 "darifenacin": "2",
 "diaqua-2": "2",
 "duragesic-25": "3",
 "deltasone": "2",
 "diltiazem": "2",
 "dynapen": "1",
 "duragesic": "3",
 "duragesic-100": "3",
 "dss plus": "2",
 "dexacort-la": "2",
 "dexamethasone": "2",
 "docusate/senna": "2",
 "dihydroergotamine": "3",
 "donepezil": "1",
 "dilacor xr": "2",
 "dayalets plus iron": "2",
 "dexlansoprazole": "2",
 "diaqua": "2",
 "dasetta": "2",
 "dexone": "2",
 "dulcolax bowel cleansing": "2",
 "duragal-s": "3",
 "dosaflex": "2",
 "docusate/ferrous fumarate": "2",
 "duet dha complete": "2",
 "dabigatran": "1",
 "deserpidine/methyclothiazide": "2",
 "duloxetine": "1",
 "dexasone": "2",
 "diurese": "2",
 "dimetapp children's nd non-drowsy allergy": "1",
 "doans pills extra strength": "1",
 "dual action complete": "2",
 "deferasirox": "2",
 "doxy-caps": "2",
 "doxycycline": "2",
 "darvon-n": "2",
 "darpaz": "1",
 "doxy-d": "2",
 "doxy 200": "2",
 "dualvit ob": "2",
 "delta-cortef": "2",
 "drospirenone/ethinyl estradiol": "2",
 "diurex": "1",
 "demulen": "2",
 "darvon": "2",
 "depakote": "2",
 "diastat acudial": "2",
 "diuretic ap-es": "2",
 "droperidol/fentanyl": "3",
 "diltia xt": "2",
 "dexasone la": "2",
 "dasatinib": "3",
 "diabinese": "2",
 "demeclocycline": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "diucardin": "2",
 "dicumarol": "3",
 "decadron-la": "2",
 "droperidol": "3",
 "dyazide": "2",
 "darvon compound-65": "2",
 "diocto-k plus": "2",
 "desipramine": "2",
 "dulcolax laxative": "2",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "disalcid": "1",
 "desyrel dividose": "2",
 "docetaxel": "2",
 "depo-medrol": "2",
 "decadron": "2",
 "dulera": "2",
 "dycill": "1",
 "dirithromycin": "1",
 "depo-cobolin": "1",
 "de-sone la": "2",
 "doxorubicin liposomal": "2",
 "doxidan softgel laxative plus stool softener": "2",
 "duet dha": "2",
 "doxorubicin": "2",
 "dexacort phosphate in respihaler": "2",
 "dewitt's pain reliever": "1",
 "duet": "2",
 "dialyvite": "2",
 "denzapine": "2",
 "depopred": "2",
 "dolophine": "3",
 "doxil": "2",
 "diuril sodium": "2",
 "di-gel lemon": "2",
 "dexamethasone intensol": "2",
 "diastat pediatric": "2",
 "diabeta": "2",
 "duo-medihaler": "2",
 "darvocet-n 100": "2",
 "demulen 1/50": "2",
 "duralone": "2",
 "deserpidine/hydrochlorothiazide": "2",
 "detrol la": "2",
 "dofetilide": "3",
 "diazepam": "2",
 "diutensen-r": "2",
 "dexacorten": "2",
 "demadex iv": "2",
 "duetact": "2",
 "depakote sprinkles": "2",
 "doculax": "2",
 "dextromethorphan/promethazine": "2",
 "depade": "2",
 "digoxin": "2",
 "doculax plus": "2",
 "doxycycline/salicylic acid topical": "2",
 "durabac forte": "1",
 "demulen 1/35": "2",
 "dalmane": "2",
 "disopyramide": "3",
 "decaject la": "2",
 "dutasteride/tamsulosin": "3",
 "diupres-250": "2",
 "dexacen-4": "2",
 "dynabac d5-pak": "1",
 "diflucan": "1",
 "docefrez": "2",
 "dexone la": "2",
 "doc-q-lax": "2",
 "daunorubicin liposomal": "2",
 "dalalone": "2",
 "dulcolax": "2",
 "duragesic-12": "3",
 "digitoxin": "2",
 "d.h.e. 45": "3",
 "darunavir": "2",
 "dilantin": "1",
 "dasetta 7/7/7": "2",
 "dulcolax milk of magnesia": "2",
 "dynabac": "1",
 "declomycin": "2",
 "darvocet-n 50": "2",
 "dicloxacillin": "1",
 "dilt-xr": "2",
 "duet dha with ferrazone": "2",
 "doxidan": "2",
 "darvocet a500": "2",
 "decaject": "2"}, "g": {"guaifenesin/oxtriphylline": "2",
 "gildess fe 1.5/30": "2",
 "guaifenesin/theophylline": "2",
 "gentlax": "2",
 "gentle iron": "2",
 "goody's extra-strength headache powders": "1",
 "goodys headache powders": "1",
 "glycerin/witch hazel topical": "2",
 "genprin": "1",
 "geravim": "2",
 "glycron": "2",
 "gentlax s": "2",
 "genace": "1",
 "geocillin": "1",
 "glimepiride/rosiglitazone": "2",
 "genora 0.5/35": "2",
 "gantanol": "1",
 "good sense children's vitamins with iron": "2",
 "gelusil": "2",
 "generess fe": "2",
 "glucotrol": "2",
 "glucovance": "2",
 "glipizide": "2",
 "goody's body pain": "1",
 "gengraf": "3",
 "gemifloxacin": "2",
 "glyceryl t": "2",
 "glipizide xl": "2",
 "glycerin": "2",
 "gesticare dha dr": "2",
 "gentle laxative": "2",
 "gen lax": "2",
 "gennin-fc": "1",
 "gianvi": "2",
 "glipizide/metformin": "2",
 "glyburide": "2",
 "giazo": "2",
 "goodys extra strength": "1",
 "guanethidine/hydrochlorothiazide": "2",
 "glycerin suppositories maximum strength": "2",
 "garfield vitamin with iron": "2",
 "galantamine": "2",
 "gatifloxacin": "3",
 "gefitinib": "2",
 "generlac": "2",
 "granulex": "2",
 "gildess fe 1/20": "2",
 "genacote": "1",
 "gavilax": "2",
 "glycerol": "2",
 "granumed": "2",
 "gleevec": "2",
 "gentlax tablet": "2",
 "glynase": "2",
 "glycolax": "2",
 "genasan": "1",
 "glucotrol xl": "2",
 "glimepiride/pioglitazone": "2",
 "gesticare dha": "2",
 "genox": "2",
 "geodon": "3",
 "geri-tabs": "2",
 "geritol": "2",
 "genasoft plus": "2",
 "genora 1/35": "2",
 "genora 1/50": "2",
 "gentamicin": "2",
 "glynase prestab": "2",
 "glimepiride": "2",
 "gesticare": "2",
 "guar gum": "2",
 "granisetron": "2",
 "garamycin": "2",
 "grepafloxacin": "3",
 "generet-500 with folic acid": "2",
 "glyburide/metformin": "2",
 "granulderm": "2",
 "granisol": "2",
 "glycerin/phenol topical": "2"}, "f": {"fer-iron": "2",
 "femiron multi with iron": "2",
 "ferro-caps": "2",
 "ferrex 150 forte": "2",
 "fesoterodine": "2",
 "formoterol": "2",
 "flomax": "3",
 "fematrol": "2",
 "florinef acetate": "2",
 "fiorinal": "1",
 "floxin iv": "2",
 "ferrous fumarate": "2",
 "fasprin": "1",
 "fentanyl": "3",
 "ferrovite fa": "2",
 "foltrin": "2",
 "femhrt": "2",
 "felodipine": "2",
 "fetrin": "2",
 "ferrex-150": "2",
 "floxin": "2",
 "foltabs plus dha": "2",
 "ferrous fumarate/folic acid": "2",
 "ferate": "2",
 "feminine lax": "2",
 "fluoxetine": "2",
 "ferra t.d. caps": "2",
 "ferrocite f": "2",
 "ferrous ds": "2",
 "flonase": "2",
 "ferralet": "2",
 "fe-tinic 150 forte": "2",
 "fleet bisacodyl": "2",
 "femecal ob": "2",
 "foltabs prenatal plus dha": "2",
 "formoterol/mometasone": "2",
 "ferrousal": "2",
 "ferocon": "2",
 "folbecal": "2",
 "foscavir": "2",
 "fruity chews with iron": "2",
 "ferrex 28": "2",
 "fluticasone/salmeterol": "3",
 "ferbee": "2",
 "fero-gradumet filmtab": "2",
 "ferretts ips": "2",
 "flovent hfa": "2",
 "fe-stool": "2",
 "ferro-time": "2",
 "ferrex pc forte": "2",
 "first mouthwash blm": "2",
 "fentanyl/ropivacaine": "3",
 "fer-gen-sol": "2",
 "fletchers castoria": "2",
 "ferrous sulfate": "2",
 "fiorinal with codeine iii": "1",
 "ferotrinsic": "2",
 "folivan-prx dha": "2",
 "femintrol": "2",
 "femecal ob plus dha": "2",
 "folcaps omega 3": "2",
 "furosemide": "2",
 "flurazepam": "2",
 "fanapt": "3",
 "folivan-ec dha": "2",
 "ferus pic-150": "2",
 "florinef": "2",
 "fast acting mylanta": "2",
 "ferro-sequels": "2",
 "fluconazole": "1",
 "fe 50": "2",
 "ferosul": "2",
 "fentora": "3",
 "fortabs": "1",
 "ferralet 90": "2",
 "femnatal": "2",
 "fidaxomicin": "1",
 "fluoxetine/olanzapine": "2",
 "foltabs": "2",
 "flovent diskus": "2",
 "folcal dha": "2",
 "ferro-dss": "2",
 "fortovase": "3",
 "ferretts": "2",
 "fletchers child laxative cherry": "2",
 "ferrocite": "2",
 "femiron": "2",
 "fosaprepitant": "2",
 "feosol": "2",
 "folivan-ob": "2",
 "foradil aerolizer": "2",
 "femcon fe": "2",
 "flumezide": "2",
 "ferocyl": "2",
 "fiortal": "1",
 "ferra-td": "2",
 "femilax": "2",
 "fem-natal": "2",
 "fe-40": "2",
 "flo-pred": "2",
 "folex pfs": "3",
 "ferrous fumarate/folic acid/iron polysaccharide": "2",
 "fosphenytoin": "1",
 "fungizone": "2",
 "ferrous fumarate/iron polysaccharide": "2",
 "fluvoxamine": "2",
 "ferragen": "2",
 "ferrovite forte": "2",
 "folivan-plus": "2",
 "folcaps care one": "2",
 "flecainide": "2",
 "feen-a-mint": "2",
 "feostat": "2",
 "feratab": "2",
 "fexofenadine": "1",
 "firmagon": "2",
 "ferrex 150 plus": "2",
 "fe caps": "2",
 "fumasorb": "2",
 "ferrogels forte": "2",
 "foltabs 90 plus dha": "2",
 "fleet liquid glycerin suppositories": "2",
 "fosamprenavir": "2",
 "ferra-cap": "2",
 "foscarnet": "2",
 "ferrous gluconate": "2",
 "fluphenazine": "2",
 "feosol iron": "2",
 "fexofenadine/pseudoephedrine": "1",
 "fero-grad-500": "2",
 "fluothane": "2",
 "farbital": "1",
 "ferrimin 150": "2",
 "flovent rotadisk": "2",
 "fosteum": "1",
 "ferotrin": "2",
 "ferrospace": "2",
 "flintstones with iron chewable": "2",
 "fe c tab plus": "2",
 "ferrets": "2",
 "fe-tinic 150": "2",
 "ferro-bob": "2",
 "fergon": "2",
 "fungizone for tissue culture": "2",
 "foltabs prenatal": "2",
 "flovent": "2",
 "feosol caplet": "2",
 "fazaclo": "2",
 "fiorinal with codeine": "1",
 "feogen": "2",
 "fero-folic 500": "2",
 "fluticasone nasal": "2",
 "fluticasone": "2",
 "fleet glycerin suppositories pediatric": "2",
 "folitab 500": "2",
 "folivan-f": "2",
 "fiortal with codeine": "1",
 "ferrex 150 forte plus": "2",
 "factive": "2",
 "fleet prep kit 1": "2",
 "ferroflex-150 forte": "2",
 "fleet prep kit 3": "2",
 "fleet prep kit 2": "2",
 "fludrocortisone": "2",
 "feocyte": "2",
 "ferrovite": "2",
 "ferro basic": "2",
 "fiormor": "1",
 "fumatinic": "2",
 "fentanyl transdermal system": "3",
 "flunisolide": "2",
 "ferraplus": "2",
 "fer-in-sol": "2",
 "ferrous sulfate/folic acid": "2",
 "fareston": "3",
 "fosinopril/hydrochlorothiazide": "2",
 "fleet glycerin suppositories adult": "2"}, "i": {"ixempra": "2",
 "iron polysaccharide": "2",
 "isoniazid/rifampin": "2",
 "i-l-x": "2",
 "idamycin pfs": "2",
 "inderide": "2",
 "inatal ultra": "2",
 "ibutilide": "3",
 "iromin g": "2",
 "invirase": "3",
 "isuprel mistometer": "2",
 "imatinib": "2",
 "isoptin": "2",
 "isuprel": "2",
 "iberet liquid": "2",
 "intelence": "2",
 "incivek": "2",
 "indium oxyquinoline in-111": "2",
 "innovar": "3",
 "inapsine": "3",
 "indinavir": "2",
 "isoptin iv": "2",
 "itraconazole": "2",
 "iressa": "2",
 "inatal advance": "2",
 "iron sulfate": "2",
 "irofol": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isoject permapen": "1",
 "isuprel hcl": "2",
 "imipramine": "2",
 "intrinsitinic": "2",
 "inderide la": "2",
 "icare prenatal rx": "2",
 "iron gluconate": "2",
 "indapamide": "2",
 "innerclean": "2",
 "icar-c plus": "2",
 "intermezzo": "1",
 "isoetharine": "2",
 "iberet-500": "2",
 "iferex 150 forte": "2",
 "invega": "2",
 "ilosone": "3",
 "iodotope": "2",
 "indacaterol": "2",
 "idamycin": "2",
 "irospan 24/6": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "integra f": "2",
 "istodax": "2",
 "iberet-folic-500": "2",
 "iro-plex": "2",
 "icar": "2",
 "icar prenatal": "2",
 "iron protein succinylate": "2",
 "isonarif": "2",
 "iron fumarate": "2",
 "iberet": "2",
 "icaps": "2",
 "ixabepilone": "2",
 "iferex 150": "2",
 "iloperidone": "3",
 "isoproterenol": "2",
 "ibc 500": "2",
 "integra plus": "2",
 "iron-150": "2",
 "iron chews": "2",
 "isoptin sr": "2",
 "i-l-x and b12": "2",
 "invega sustenna": "2",
 "introvale": "2",
 "idarubicin": "2",
 "infanate dha": "2",
 "idenal": "1",
 "icar-c plus sr": "2",
 "ircon": "2",
 "inspra": "3",
 "ircon-fa": "2",
 "isoproterenol/phenylephrine": "2",
 "ionsys": "3",
 "integra": "2"}, "h": {"hydeltrasol": "2",
 "hhr": "2",
 "haloperidol": "3",
 "hemocyte-f": "2",
 "hemocyte-c": "2",
 "hydroserpine 1": "2",
 "hyzaar": "2",
 "hydroflumethiazide/reserpine": "2",
 "helidac": "2",
 "hydro-reserp": "2",
 "hemocyte": "2",
 "hydrochlorothiazide/methyldopa": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hydro par": "2",
 "heptalac": "2",
 "hydrochlorothiazide/timolol": "2",
 "hydrocortone phosphate": "2",
 "heme iron polypeptide/iron polysaccharide": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydropres-50": "2",
 "hydrap-es": "2",
 "hydroserpine": "2",
 "halcion": "2",
 "hydrochlorothiazide/losartan": "2",
 "halflytely and bisacodyl": "2",
 "hydrochlorothiazide/reserpine": "2",
 "hydrodiuril": "2",
 "hygroton": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hematogen fa": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hemocyte-f elixir": "2",
 "hydrophed": "2",
 "hematogen forte": "2",
 "hydrochlorothiazide/propranolol": "2",
 "haldol decanoate": "3",
 "hemaspan": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydroserp": "2",
 "hydeltra-tba": "2",
 "hytinic": "2",
 "hydrochlorothiazide/moexipril": "2",
 "hyophen": "1",
 "hydrochlorothiazide/irbesartan": "2",
 "hi-nate 90": "2",
 "hydroxy compound": "2",
 "halothane": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "halfprin": "1",
 "haley's m-o": "2",
 "hematinic with folic acid": "2",
 "halaven": "2",
 "hydra-zide": "2",
 "hydrochlorothiazide/valsartan": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrocortone": "2",
 "hygenic cleansing pad": "2",
 "halfan": "3",
 "hydrocortisone": "2",
 "halofantrine": "3",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "1",
 "hydrochlorothiazide/quinapril": "2",
 "hismanal": "3",
 "hydropres-25": "2",
 "hematogen": "2",
 "hydrochlorothiazide": "2",
 "hexadrol": "2",
 "heartline": "1",
 "haldol": "3",
 "hemorrhoidal hygiene pads": "2",
 "hydralazine plus": "2",
 "hydroflumethiazide": "2",
 "halazepam": "2",
 "humatin": "2"}, "k": {"klonopin": "2",
 "ken-jec 40": "2",
 "kenalog-10": "2",
 "kionex": "2",
 "kondremul with phenolphtalein": "2",
 "kolnatal dha": "2",
 "kelnor 1/35": "2",
 "kalexate": "2",
 "key-pred": "2",
 "korlym": "1",
 "ketoconazole": "2",
 "kenaject-40": "2",
 "kapidex": "2",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "klonopin wafer": "2",
 "kombiglyze xr": "2",
 "kristalose": "2",
 "kefurox": "2",
 "kayexalate": "2",
 "kaletra": "2",
 "kneerelief": "1",
 "kariva": "2",
 "kantrex": "2",
 "ketek": "2",
 "kanamycin": "2",
 "kytril": "2",
 "ketek pak": "2"}, "j": {"jolessa": "2",
 "junel 1.5/30": "2",
 "jakafi": "3",
 "jenest": "2",
 "juvisync": "3",
 "jinteli": "2",
 "junel 1/20": "2",
 "jantoven": "3",
 "jevantique": "2",
 "junel fe 1/20": "2",
 "jalyn": "3",
 "junel fe 1.5/30": "2",
 "jevtana": "2"}, "m": {"mynatal ultracap": "2",
 "mezlin": "1",
 "martinic": "2",
 "mykidz iron": "2",
 "magic bullet": "2",
 "meridia": "1",
 "my-o-den": "2",
 "myferon 150 forte": "2",
 "marthritic": "1",
 "maternity": "2",
 "min-ovral 21": "2",
 "modafinil": "1",
 "metahydrin": "2",
 "medrol dosepak": "2",
 "miradon": "3",
 "mynatal rx": "2",
 "micardis hct": "2",
 "multivitamin with iron": "2",
 "maalox advanced maximum strength": "2",
 "marlissa": "2",
 "magsal": "1",
 "mestranol/norethindrone": "2",
 "mhp-a": "1",
 "microzide": "2",
 "midazolam": "2",
 "mi-acid ii": "2",
 "maxinate": "2",
 "methyclothiazide/reserpine": "2",
 "methacort 40": "2",
 "migracet-pb": "3",
 "mynate 90 plus": "2",
 "mylanta ultra": "2",
 "medilax": "2",
 "medique pain-off": "1",
 "minizide": "2",
 "midol extended relief": "2",
 "m-phen": "2",
 "metaprel": "2",
 "mynatal z": "2",
 "moduretic": "2",
 "mission prenatal hp": "2",
 "metformin/pioglitazone": "2",
 "mephenytoin": "1",
 "methysergide maleate": "3",
 "methylcotolone": "2",
 "maalox max wild berry": "2",
 "millipred dp": "2",
 "methacort 80": "2",
 "mynatal pn forte": "2",
 "medicort": "2",
 "mylagen-ii": "2",
 "monodox": "2",
 "matzim la": "2",
 "magan": "1",
 "myogesic": "1",
 "multi-nate 30": "2",
 "methylcotol": "2",
 "morphine/naltrexone": "2",
 "multaq": "3",
 "mifeprex": "1",
 "mudrane gg-2": "2",
 "mynatal plus": "2",
 "maxaron forte": "2",
 "metaproterenol": "2",
 "mylagen": "2",
 "migralex": "1",
 "multi-delyn with iron": "2",
 "moxifloxacin": "3",
 "methylprednisolone": "2",
 "minitabs": "1",
 "maalox": "2",
 "midol traditional": "1",
 "milantex": "2",
 "myzilra": "2",
 "magnesium hydroxide/mineral oil": "2",
 "millipred": "2",
 "methotrexate": "3",
 "multi-nate 30 kit": "2",
 "mission prenatal": "2",
 "modane": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "min-ovral 28": "2",
 "mevacor": "3",
 "mi-acid double strength": "2",
 "mag-phen": "1",
 "magaant": "2",
 "maternity vitamin low iron": "2",
 "mononessa": "2",
 "medrol": "2",
 "midamor": "1",
 "maternity-90": "2",
 "mynatal fc": "2",
 "mintox extra strength": "2",
 "mintox": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "maxair": "2",
 "masanti ds": "2",
 "multifol plus": "2",
 "methergine": "3",
 "mykrox": "2",
 "mycobutin": "2",
 "microgestin 1.5/30": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "multi vita bets and fluoride and iron": "2",
 "mycifradin": "2",
 "mefloquine": "2",
 "maalox advanced regular strength": "2",
 "multigen": "2",
 "marnatal-f": "2",
 "meprozine": "2",
 "metolazone": "2",
 "methadose": "3",
 "mission prenatal rx": "2",
 "medique medi-seltzer": "1",
 "maldroxal plus": "2",
 "methyclothiazide": "2",
 "minocin": "2",
 "mycophenolate mofetil": "2",
 "micronase": "2",
 "mono-gesic": "1",
 "mylanta supreme": "2",
 "mifepristone": "1",
 "methylpred dp": "2",
 "magnesium salicylate": "1",
 "methylergonovine": "3",
 "microgestin fe 1/20": "2",
 "multi-nate dha": "2",
 "milantex maximum strength": "2",
 "mintox plus": "2",
 "mobigesic": "1",
 "medidex la": "2",
 "magnesium salicylate/phenyltoloxamine": "1",
 "mykidz iron 10": "2",
 "maraviroc": "3",
 "micomp-pb": "3",
 "metaglip": "2",
 "medi-pad": "2",
 "mesantoin": "1",
 "maternal 90": "2",
 "mintox maximum strength": "2",
 "multiret folic 500": "2",
 "mst": "1",
 "multivitamin with iron and fluoride": "2",
 "micrainin": "1",
 "myfortic": "2",
 "maalox plus": "2",
 "mitran": "2",
 "miralax": "2",
 "metformin/saxagliptin": "2",
 "mynatal": "2",
 "myferon 150": "2",
 "methadone diskets": "3",
 "multinatal plus": "2",
 "mepergan": "2",
 "migergot": "3",
 "msp-blu": "1",
 "mibefradil": "2",
 "multigen plus": "2",
 "multi-nate dha extra": "2",
 "mylanta ultimate strength": "2",
 "multi-nate 30 dha": "2",
 "multivitamin, prenatal": "2",
 "modane plus": "2",
 "modicon": "2",
 "mylanta ds fast acting": "2",
 "menopause support": "2",
 "maxaquin": "2",
 "moduretic 5-50": "2",
 "masanti": "2",
 "maxzide-25": "2",
 "magnesium citrate": "2",
 "microgestin fe 1.5/30": "2",
 "medi-seltzer": "1",
 "momentum": "1",
 "mol-iron": "2",
 "mycophenolic acid": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "maalox tc": "2",
 "mi-acid": "2",
 "mylanta": "2",
 "mellaril-s": "3",
 "multibret folic 500": "2",
 "methotrimeprazine": "2",
 "medralone": "2",
 "methicillin": "1",
 "medipred": "2",
 "metformin/repaglinide": "2",
 "m-prednisolone": "2",
 "mudrane gg": "2",
 "medralone 80": "2",
 "multigen folic": "2",
 "mykidz iron fl": "2",
 "mylanta fast acting": "2",
 "methotrexate lpf sodium": "3",
 "meperidine/promethazine": "2",
 "mult-ferr folic": "2",
 "marnatal-f plus": "2",
 "maxzide": "2",
 "mobidin": "1",
 "mynatal pn": "2",
 "milk of magnesia": "2",
 "meticorten": "2",
 "monopril hct": "2",
 "migranal": "3",
 "maalox max": "2",
 "microgestin 1/20": "2",
 "mylanta maximum strength": "2",
 "mezlocillin": "1",
 "mission prenatal fa": "2",
 "methdilazine": "2",
 "maalox antacid antigas regular strength": "2",
 "marax df": "2",
 "medihaler-iso": "2",
 "maternity plus beta carotene": "2",
 "myrac": "2",
 "mepergan fortis": "2",
 "maprotiline": "2",
 "mircette": "2",
 "minocycline": "2",
 "maalox hrf": "2",
 "marax": "2",
 "multifol": "2",
 "mellaril": "3",
 "metatensin 4": "2",
 "metatensin 2": "2",
 "medidex": "2",
 "materna": "2",
 "maxair autohaler": "2",
 "mintox tablets": "2",
 "mineral oil/phenolphthalein": "2",
 "methylprednisolone dose pack": "2",
 "mylanta gelcap": "2",
 "methadone": "3",
 "mesoridazine": "3",
 "mudrane": "2",
 "marpres": "2"}, "l": {"litecoat aspirin": "1",
 "loratadine/pseudoephedrine": "1",
 "lo loestrin fe": "2",
 "letairis": "1",
 "livitrinsic-f": "2",
 "lariam": "2",
 "lasix": "2",
 "lessina": "2",
 "leena": "2",
 "levonest": "2",
 "loestrin 1/20": "2",
 "librax": "2",
 "levaquin leva-pak": "2",
 "lactocal-f": "2",
 "low-ogestrel-21": "2",
 "lipitor": "3",
 "low-ogestrel-28": "2",
 "lithobid": "2",
 "lidocaine/oxytetracycline": "2",
 "levomethadyl acetate": "3",
 "levlen": "2",
 "loestrin 21 1/20": "2",
 "loestrin fe 1.5/30": "2",
 "loqua": "2",
 "lamivudine/zidovudine": "1",
 "ledercillin vk": "1",
 "loratadine reditab": "1",
 "leader allergy relief d-24": "1",
 "liquid pred": "2",
 "levaquin": "2",
 "librium": "2",
 "lazanda": "3",
 "levitra": "2",
 "loratadine": "1",
 "loso prep bowel cleansing system": "2",
 "lopinavir/ritonavir": "2",
 "lorelco": "2",
 "lanoxicaps": "2",
 "levlite": "2",
 "loestrin 21 1.5/30": "2",
 "lithotabs": "2",
 "levalbuterol": "2",
 "loestrin 24 fe": "2",
 "lactulose": "2",
 "lopurin": "1",
 "lomefloxacin": "2",
 "leader naproxen sodium": "2",
 "lydia e. pinkham": "2",
 "lovastatin/niacin": "3",
 "laxative gentle suppositories": "2",
 "lanoxin": "2",
 "lutera": "2",
 "lotensin hct": "2",
 "lovastatin": "3",
 "la-12": "1",
 "largon": "2",
 "lapatinib": "2",
 "lo-aqua": "2",
 "lybrel": "2",
 "lexxel": "2",
 "laniroif": "1",
 "lo/ovral-28": "2",
 "lexiva": "2",
 "latuda": "3",
 "ludiomil": "2",
 "low dose asa": "1",
 "levacet": "1",
 "lexapro": "2",
 "lydia pinkham": "2",
 "levobupivacaine": "2",
 "lortab asa": "1",
 "levofloxacin": "2",
 "loestrin fe 1/20": "2",
 "lozol": "2",
 "liquiprep": "2",
 "lithium": "2",
 "luvox": "2",
 "limbitrol": "2",
 "loratadine-d 24 hour": "1",
 "luvox cr": "2",
 "lotronex": "2",
 "lithonate": "2",
 "loryna": "2",
 "lunesta": "2",
 "limbitrol ds": "2",
 "lansoprazole/naproxen": "2",
 "levora": "2",
 "lurasidone": "3",
 "laxacin": "2",
 "lopressor hct": "2",
 "loseasonique": "2",
 "lo/ovral": "2",
 "levoprome": "2"}, "o": {"onfi": "2",
 "orasone": "2",
 "obegyn": "2",
 "ob complete with dha": "2",
 "oxytetracycline": "2",
 "onglyza": "2",
 "orphengesic": "1",
 "oxacillin": "1",
 "oreticyl 50": "2",
 "optinate": "2",
 "ob complete premier": "2",
 "oreticyl forte": "2",
 "oxcarbazepine": "2",
 "omesec": "1",
 "omeprazole/sodium bicarbonate": "1",
 "ortho-novum 1/50": "2",
 "omnipen-n": "2",
 "ob natal one": "2",
 "obtrex dha": "2",
 "omnipen": "2",
 "ortho-novum 7/7/7": "2",
 "ortho evra": "2",
 "oracea": "2",
 "oxytetracycline/phenazopyridine/sulfamethizole": "2",
 "octycine": "2",
 "ogestrel-28": "2",
 "oraxyl": "2",
 "ovcon 35": "2",
 "omeprazole": "1",
 "ohm allergy relief": "1",
 "onsolis": "3",
 "one tab daily with iron": "2",
 "onxol": "2",
 "orinase": "2",
 "optase": "2",
 "ob-20": "2",
 "omnaris": "2",
 "ortho tri-cyclen": "2",
 "ortho cyclen": "2",
 "ocella": "2",
 "orphengesic forte": "1",
 "ovcon 35 fe": "2",
 "ovral": "2",
 "ocudox": "2",
 "ortho-novum 10/11": "2",
 "orsythia": "2",
 "ob complete": "2",
 "oxtriphylline": "2",
 "osmoglyn": "2",
 "ofloxacin": "2",
 "o-cal prenatal": "2",
 "orapred": "2",
 "ogestrel": "2",
 "orap": "3",
 "ortho tri-cyclen lo": "2",
 "oleptro": "2",
 "oreticyl 25": "2",
 "ob complete 400": "2",
 "obnate 90": "2",
 "optison": "2",
 "ortho-novum 1/35": "2",
 "orlaam": "3",
 "ovcon 50": "2",
 "oretic": "2",
 "ovral-28": "2",
 "obtrex": "2",
 "orapred odt": "2",
 "ortho-cept": "2",
 "ondansetron": "2",
 "oncovin": "3",
 "ormazine": "2"}, "n": {"nutrispire": "2",
 "nuedexta": "2",
 "natalcare advanced": "2",
 "necon 0.5/35": "2",
 "nolvadex d": "2",
 "naprosyn": "2",
 "norethin 1/35 e": "2",
 "necon 10/11": "2",
 "natalcare pic forte": "2",
 "natelle prefer": "2",
 "natalcare": "2",
 "niferex-pn": "2",
 "naprelan": "2",
 "nizoral": "2",
 "necon 7/7/7": "2",
 "nutridox convenience kit": "2",
 "nelova 10/11": "2",
 "natalcare cfe 60": "2",
 "neevo": "2",
 "nascobal": "1",
 "natelle-ez": "2",
 "nata 29 ob": "2",
 "norpramin": "2",
 "niferex elixir": "2",
 "nuvaring": "2",
 "natacaps": "2",
 "novastart": "2",
 "niacin/simvastatin": "3",
 "natelle one": "2",
 "nu-iron": "2",
 "nephro-fer": "2",
 "nelova 0.5/35": "2",
 "norfloxacin": "2",
 "nata 29 prenatal": "2",
 "novasal": "1",
 "nestabs rx": "2",
 "natalcare glosstabs": "2",
 "nu-iron plus": "2",
 "neo-tab": "2",
 "nuprin backache caplet": "1",
 "nebupent": "2",
 "natures remedy": "2",
 "neoloid": "2",
 "nestabs fa": "2",
 "nevirapine": "2",
 "niferex": "2",
 "nuvigil": "1",
 "natelle": "2",
 "neomycin": "2",
 "nilotinib": "3",
 "norgesic forte": "1",
 "novaferrum": "2",
 "norvir": "2",
 "necon 1/35": "2",
 "nu-iron 150": "2",
 "natafolic-ob": "2",
 "nexavar": "2",
 "nestabs": "2",
 "nallpen": "1",
 "natalcare rx": "2",
 "netromycin": "2",
 "nordette-28": "2",
 "nelfinavir": "3",
 "natelle one dha": "2",
 "nordette-21": "2",
 "noroxin": "2",
 "niferex-150 forte": "2",
 "norisodrine with calcium iodine": "2",
 "nelova 1/35": "2",
 "natatab fa": "2",
 "niferex-150": "2",
 "nebcin": "2",
 "naturetin": "2",
 "nifedipine": "2",
 "natarex": "2",
 "norpace cr": "3",
 "nortriptyline": "2",
 "naqua": "2",
 "norethin 1/50 m": "2",
 "nortrel 0.5/35": "2",
 "naropin novaplus": "1",
 "novanatal": "2",
 "naropin polyamp": "1",
 "natatab rx": "2",
 "naltrexone": "2",
 "neo-fradin": "2",
 "nolvadex": "2",
 "nifediac cc": "2",
 "necon 1/50": "2",
 "neoral": "3",
 "new advanced formula prenatal z": "2",
 "noxafil": "2",
 "neevo dha": "2",
 "naproxen sodium ds": "2",
 "nephro-fer rx": "2",
 "natelle c": "2",
 "nifedical xl": "2",
 "norinyl 1+50": "2",
 "natatab cfe": "2",
 "nephro-vite with fe": "2",
 "nadolol": "1",
 "naturetin-5": "2",
 "neuroforte-r": "1",
 "nortrel 7/7/7": "2",
 "niferex pn forte": "2",
 "nortrel 1/35": "2",
 "nelova 1/50 m": "2",
 "natalcare advanced-rf": "2",
 "nephron-fa": "2",
 "naturetin-10": "2",
 "natalcare plus": "2",
 "natalins rx": "2",
 "neo-forte": "2",
 "naproxen/sumatriptan": "2",
 "norwich aspirin": "1",
 "natachew": "2",
 "natelle plus with dha": "2",
 "natafolic-pn": "2",
 "norgesic": "1",
 "natalfirst": "2",
 "naproxen": "2",
 "nutrinate": "2",
 "niferex gold": "2",
 "nebcin pediatric": "2",
 "naropin": "1",
 "nexterone": "3",
 "nexa select with dha": "2",
 "nestabs cbf": "2",
 "niravam": "2",
 "netilmicin": "2",
 "norlac rx": "2",
 "norinyl 1+35": "2",
 "nafcillin": "1",
 "natalcare pic": "2",
 "navelbine": "3",
 "natalcare three": "2",
 "nefazodone": "2",
 "norvir soft gelatin": "2",
 "nordette": "2",
 "naproxen/pseudoephedrine": "2",
 "natafort": "2",
 "natalins": "2",
 "naropin sdv": "1",
 "norpace": "3"}, "q": {"quibron": "2",
 "quibron 300": "2",
 "quasense": "2",
 "quinidex extentabs": "2",
 "quinidine": "2",
 "quinora": "2",
 "quinaretic": "2",
 "qm-260": "3",
 "quinaglute dura-tabs": "2",
 "quin-g": "2",
 "quazepam": "2",
 "quetiapine": "2",
 "quinine": "3",
 "quin-release": "2",
 "qualaquin": "3",
 "quibron-t/sr": "2",
 "quadrinal": "2",
 "q-b": "2",
 "qvar": "2",
 "quibron-t": "2"}, "p": {"prozac weekly": "2",
 "phosphasal": "1",
 "promazine": "2",
 "poly iron forte": "2",
 "pr natal 440": "2",
 "prenatal-u": "2",
 "paire ob plus dha": "2",
 "peg3350": "2",
 "prenavite pc": "2",
 "prenatal low iron": "2",
 "pamprin all day relief": "2",
 "pediazole": "3",
 "predacort 50": "2",
 "prograf": "2",
 "prevacid naprapac 375": "2",
 "pan ob forte": "2",
 "prenatal mtr with selenium": "2",
 "primacare": "2",
 "pimecrolimus topical": "1",
 "proventil": "2",
 "prevacid naprapac": "2",
 "polysaccharide iron": "2",
 "procainamide": "3",
 "plavix": "2",
 "prenaplus": "2",
 "pradaxa": "1",
 "promar": "2",
 "prinzide": "2",
 "pronemia": "2",
 "procardia": "2",
 "pletal": "2",
 "pce dispertab": "3",
 "pharmorubicin rdf": "2",
 "pulmicort nebuamp": "2",
 "pr natal 400 ec": "2",
 "panitumumab": "2",
 "periostat": "2",
 "paxipam": "2",
 "prenatabs cbf": "2",
 "prednisolone": "2",
 "prenatal 1 plus 1": "2",
 "peri-ds": "2",
 "prandimet": "2",
 "predicort-50": "2",
 "prenafirst": "2",
 "phyllocontin": "2",
 "procot": "2",
 "prolixin": "2",
 "poly-vi-sol with iron drops": "2",
 "prenatal s": "2",
 "probenecid and colchicine": "3",
 "panmycin": "2",
 "propoxyphene compound 65": "2",
 "preterna": "2",
 "paromomycin": "2",
 "pnv-total": "2",
 "phenadoz": "2",
 "phenergan vc": "2",
 "polythiazide/prazosin": "2",
 "psyllium/senna": "2",
 "prenatabs fa": "2",
 "prelone": "2",
 "paclitaxel": "2",
 "peri-dos": "2",
 "phillips' haleys m-o": "2",
 "pamprin cramp menstrual pain relief": "1",
 "proquin xr": "2",
 "platinol-aq": "2",
 "protriptyline": "2",
 "pepcid complete": "2",
 "pitressin": "2",
 "propoxyphene": "2",
 "phenylephrine/promethazine": "2",
 "predate-50": "2",
 "poly-vi-sol with iron": "2",
 "penicillin g procaine": "1",
 "primacare advantage": "2",
 "phenazine 50": "2",
 "portia": "2",
 "pen-v": "1",
 "permitil": "2",
 "prenate dha": "2",
 "probenecid": "1",
 "prenate 90": "2",
 "prolixin enanthate": "2",
 "paxil": "2",
 "percodan": "1",
 "prenate plus": "2",
 "previte rx": "2",
 "prilosec": "1",
 "phenytek": "1",
 "prenavite fc": "2",
 "penicillin": "1",
 "paliperidone": "2",
 "promethegan": "2",
 "pirbuterol": "2",
 "pulmicort flexhaler": "2",
 "posicor": "2",
 "phenolphthalein": "2",
 "predicort rp": "2",
 "poly-vi-flor with iron": "2",
 "primethasone": "2",
 "pentam 300": "2",
 "prevacid naprapac 500": "2",
 "procaine penicillin": "1",
 "prenatal rx": "2",
 "poly vitamin with fluoride with iron": "2",
 "promethazine with dm": "2",
 "prenate essential": "2",
 "percodan-demi": "1",
 "promethazine vc with codeine": "2",
 "prochlorperazine": "2",
 "prednicen-m": "2",
 "platinol": "2",
 "proderm": "2",
 "premesis rx": "2",
 "pfizerpen": "1",
 "primatene dual action": "2",
 "par-f": "2",
 "prenatal plus with 27 mg iron": "2",
 "prosom": "2",
 "phosenamine": "1",
 "piperacillin": "1",
 "prulet": "2",
 "preque 10": "2",
 "prozac": "2",
 "pen-vee k": "1",
 "prenatal multivitamins": "2",
 "pnv select": "2",
 "peganone": "1",
 "prenate gt": "2",
 "prenate elite plus iron": "2",
 "precare conceive": "2",
 "pemetrexed": "2",
 "pnv-dha plus": "2",
 "pc pen vk": "1",
 "phenytoin sodium, prompt": "1",
 "prenatal plus with beta-carotene": "2",
 "propiomazine": "2",
 "phenolax": "2",
 "previfem": "2",
 "paraplatin": "2",
 "philith": "2",
 "posaconazole": "2",
 "prenatal rx 1": "2",
 "prolixin decanoate": "2",
 "pentamidine": "2",
 "p-a-c analgesic": "1",
 "profe": "2",
 "pexeva": "2",
 "polythiazide/reserpine": "2",
 "prefera ob plus dha": "2",
 "pro-med": "2",
 "potassium iodide/theophylline": "2",
 "prenexa": "2",
 "pylera": "2",
 "perdiem overnight": "2",
 "pronestyl-sr": "3",
 "phenergan vc with codeine": "2",
 "precare": "2",
 "principen": "2",
 "promethazine vc": "2",
 "prefera ob-one": "2",
 "prenatal z advanced formula": "2",
 "prenate elite": "2",
 "promethazine with codeine": "2",
 "prosed ds": "1",
 "pr natal 400": "2",
 "pharmorubicin pfs": "2",
 "pri-cortin 50": "2",
 "procardia xl": "2",
 "perforomist": "2",
 "phillips gel": "2",
 "prenate advance": "2",
 "pc-cap": "2",
 "provigil": "1",
 "pre-h-cal": "2",
 "palonosetron": "2",
 "pruvate 21/7": "2",
 "p-a-c": "1",
 "penicillin vk": "1",
 "propulsid": "3",
 "pp-cap": "2",
 "predaject-50": "2",
 "pulmicort turbuhaler": "2",
 "proventil hfa": "2",
 "pedia-lax liquid glycerin suppositories": "2",
 "prenatal h": "2",
 "prasugrel": "1",
 "pediapred": "2",
 "predacorten": "2",
 "pamelor": "2",
 "perdiem": "2",
 "pimozide": "3",
 "priftin": "2",
 "pentacarinat": "2",
 "preven ec": "2",
 "procan sr": "3",
 "pulmicort respules": "2",
 "prenatal ad": "2",
 "piperacillin/tazobactam": "1",
 "pruet dha": "2",
 "prenatabs rx": "2",
 "paricalcitol": "2",
 "prenate advanced formula": "2",
 "pedia-lax glycerin suppositories": "2",
 "perestan": "2",
 "pseudoephedrine/terfenadine": "3",
 "predcor": "2",
 "prenavite": "2",
 "prenatal plus iron": "2",
 "pipracil": "1",
 "pedia-lax quick dissolve strips": "2",
 "proben-c": "3",
 "purge": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "proair hfa": "2",
 "pazopanib": "3",
 "panasal 5/500": "1",
 "predalone 50": "2",
 "pronestyl": "3",
 "phenoject-50": "2",
 "plendil": "2",
 "prenatal plus": "2",
 "prenacare": "2",
 "prenatal mr 90 fe": "2",
 "prenatal elite": "2",
 "paroxetine": "2",
 "paclitaxel protein-bound": "2",
 "pioglitazone": "2",
 "phenytoin": "1",
 "phenergan fortis": "2",
 "prenexa with dha": "2",
 "pentam": "2",
 "poly iron": "2",
 "plenaxis": "2",
 "purelax": "2",
 "paromycin": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "polythiazide": "2",
 "pacerone": "3",
 "prandin": "2",
 "paxil cr": "2",
 "prosed ec": "1",
 "pedia-lax chewable tablets": "2",
 "propacet 100": "2",
 "prenate ultra": "2",
 "phluorivit with iron": "2",
 "perphenazine": "2",
 "polyethylene glycol 3350": "2",
 "precare premier": "2",
 "parlodel": "2",
 "preferaob": "2",
 "promethazine with dextromethorphan": "2",
 "prenazyme 1+1": "2",
 "pred-ject-50": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenazopyridine/sulfamethoxazole": "1",
 "painaid": "1",
 "poly iron 150 forte": "2",
 "perflutren": "2",
 "prednisone": "2",
 "procanbid": "3",
 "promethazine hcl with codeine": "2",
 "primacare one": "2",
 "potassium bitartrate/sodium bicarbonate": "2",
 "pr natal 430": "2",
 "prednicot": "2",
 "prenate essential dha": "2",
 "prilosec otc": "1",
 "pnv-dha": "2",
 "pramilet fa": "2",
 "promethazine vc plain": "2",
 "propafenone": "2",
 "prenatabs obn": "2",
 "peri-colace": "2",
 "probucol": "2",
 "pamprin max menstrual pain relief": "1",
 "pravigard pac": "1",
 "phenergan with dextromethorphan": "2",
 "proferrin-forte": "2",
 "potiga": "2",
 "prezista": "2",
 "prenatal mr 90": "2",
 "prenatal 19": "2",
 "phillips' milk of magnesia": "2",
 "promethazine vc w/codeine": "2"}, "s": {"sronyx": "2",
 "sesame st. vitamins plus iron": "2",
 "saleto": "1",
 "saluron": "2",
 "solurex": "2",
 "sertraline": "2",
 "suplevit": "2",
 "saquinavir": "3",
 "se-care conceive": "2",
 "senokot": "2",
 "slow release iron": "2",
 "senilezol": "2",
 "senna": "2",
 "slo-phyllin": "2",
 "sibutramine": "1",
 "senna concentrate": "2",
 "sulfamethoxazole": "1",
 "septra": "1",
 "smz-tmp ds": "1",
 "sparfloxacin": "3",
 "stuart prenatal with beta carotene": "2",
 "serathide": "2",
 "septra iv": "1",
 "sprintec": "2",
 "sporanox pulsepak": "2",
 "st. joseph aspirin": "1",
 "soltamox": "2",
 "sotalol hydrochloride af": "3",
 "symbyax": "2",
 "slow fe with folic acid": "2",
 "stavzor": "2",
 "subsys": "3",
 "stelazine": "2",
 "scot-tussin original": "1",
 "serentil": "3",
 "sudafed 12 hour pressure+pain": "2",
 "sancuso": "2",
 "selestoject": "2",
 "stanback fast pain relief": "1",
 "serevent diskus": "3",
 "seasonale": "2",
 "senosol": "2",
 "seasonique": "2",
 "synercid": "2",
 "solodyn": "2",
 "sandimmune": "3",
 "sani-clens": "2",
 "salutensin-demi": "2",
 "solia": "2",
 "sucralfate": "2",
 "sirolimus": "3",
 "solu-cortef": "2",
 "senexon-s": "2",
 "senokot child": "2",
 "selfemra": "2",
 "salsalate": "1",
 "samsca": "3",
 "serzone": "2",
 "sodium iodide i-123": "2",
 "safyral": "2",
 "solu-phyllin gg": "2",
 "sennaprompt": "2",
 "staphcillin": "1",
 "sennalax-s": "2",
 "salutensin": "2",
 "slo-phyllin 80": "2",
 "solifenacin": "2",
 "se-natal 16": "2",
 "sublimaze": "3",
 "stuartnatal plus 3": "2",
 "sani-pads with aloe": "2",
 "seldane": "3",
 "ser-ap-es": "2",
 "se-care": "2",
 "senosol-x": "2",
 "simcor": "3",
 "se-natal 19": "2",
 "select-ob+dha": "2",
 "sansert": "3",
 "sustiva": "2",
 "symbicort": "2",
 "staxyn": "2",
 "sunmark clearlax": "2",
 "senosol-ss": "2",
 "se-tan dha": "2",
 "selzentry": "3",
 "salmeterol": "3",
 "senna plus": "2",
 "senna lax": "2",
 "slo-phyllin 125": "2",
 "sarafem": "2",
 "simron": "2",
 "sparine": "2",
 "subutex": "2",
 "sunitinib": "2",
 "septra ds": "1",
 "seroquel": "2",
 "seroquel xr": "2",
 "stuartnatal plus": "2",
 "spectracef": "2",
 "soma compound with codeine": "1",
 "seton et": "2",
 "sulfimycin": "3",
 "spastrin": "3",
 "se-natal 90": "2",
 "seldane-d": "3",
 "slo-phyllin gg": "2",
 "sterapred ds": "2",
 "sloprin": "1",
 "sufentanil": "2",
 "sodium edecrin": "2",
 "surmontil": "2",
 "senokotxtra": "2",
 "sodium salicylate": "1",
 "solu-medrol": "2",
 "simvastatin/sitagliptin": "3",
 "sufenta": "2",
 "sutent": "2",
 "stanback analgesic": "1",
 "strongstart": "2",
 "silodosin": "3",
 "sani-supp": "2",
 "select-ob": "2",
 "sildenafil": "3",
 "syeda": "2",
 "st. joseph 81 mg aspirin enteric safety-coated": "1",
 "se-plete dha": "2",
 "sulfatrim": "1",
 "sporanox": "2",
 "serpex": "2",
 "seton et-ec": "2",
 "sterapred": "2",
 "senokot direct relief": "2",
 "senna-gen": "2",
 "salflex": "1",
 "spectrobid": "2",
 "slo-bid gyrocaps": "2",
 "septopal": "2",
 "synalgos-dc": "1",
 "strong caps": "2",
 "sprycel": "3",
 "saxagliptin": "2",
 "senolax": "2",
 "senna s": "2",
 "sorafenib": "2",
 "sytobex": "1",
 "sunkist child chewable with iron": "2",
 "stresstabs with iron": "2",
 "saphris": "2",
 "sinequan": "2",
 "serpazide": "2",
 "suboxone": "2",
 "soma compound": "1",
 "se-natal one": "2",
 "simvastatin": "3",
 "sumycin": "2",
 "se-vate": "2",
 "salsitab": "1",
 "senokot s": "2",
 "stress formula with iron": "2",
 "sodium polystyrene sulfonate": "2",
 "sotalol": "3",
 "sorine": "3",
 "st. joseph 81 mg chewable aspirin": "1",
 "supac": "1",
 "sss tonic": "2",
 "sumycin 250": "2",
 "solurex la": "2",
 "silenor": "2",
 "senexon": "2",
 "surbex-750 with iron": "2",
 "sensipar": "2",
 "slow fe": "2",
 "sulfatrim pediatric": "1",
 "sulfamethoxazole/trimethoprim": "1",
 "sodium iodide-i-131": "2",
 "streptomycin": "2"}, "r": {"robaxisal": "1",
 "rheumatrex dose pack": "3",
 "robitet 500": "2",
 "reserpine/trichlormethiazide": "2",
 "risperdal m-tab": "2",
 "rythmol sr": "2",
 "revia": "2",
 "renate": "2",
 "repliva 21/7": "2",
 "repaglinide": "2",
 "rythmol": "2",
 "revatio": "3",
 "razadyne er": "2",
 "raxar": "3",
 "rexavite 150": "2",
 "rimactane": "2",
 "retrovir": "1",
 "roxiprin": "1",
 "retapamulin topical": "1",
 "reclipsen": "2",
 "rifabutin": "2",
 "rauzide": "2",
 "rulox": "2",
 "re ob 90 plus dha": "2",
 "rezulin": "2",
 "rebif": "2",
 "rolaids regular strength": "2",
 "romidepsin": "2",
 "rifater": "2",
 "robimycin": "3",
 "respbid": "2",
 "renese-r": "2",
 "regroton": "2",
 "ramelteon": "2",
 "rondameth": "2",
 "resource benefiber": "2",
 "risperdal consta": "2",
 "ranexa": "3",
 "red yeast rice": "3",
 "ritodrine": "2",
 "rozerem": "2",
 "rovin-nv dha": "2",
 "renate dha extra": "2",
 "ritonavir": "2",
 "ruxolitinib": "3",
 "risperidone": "2",
 "rhinocaps": "1",
 "ropivacaine/sufentanil": "2",
 "rulox 1": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "rifampin": "2",
 "revina nlt": "2",
 "reminyl": "2",
 "rolaids multi-symptom": "2",
 "rightstep": "2",
 "renate dha": "2",
 "ravin": "2",
 "rubesol-1000": "1",
 "renese": "2",
 "rapaflo": "3",
 "ropivacaine": "1",
 "rulox plus": "2",
 "ranolazine": "3",
 "risperdal": "2",
 "rovin-nv": "2",
 "rifadin iv": "2",
 "rolaids extra strength": "2",
 "rapiflux": "2",
 "rexavite 150 forte": "2",
 "reyataz": "3",
 "razadyne": "2",
 "rescriptor": "2",
 "royvac bowel evacuant": "2",
 "rifadin": "2",
 "rapamune": "3",
 "rivaroxaban": "2",
 "rilpivirine": "3",
 "relpax": "3",
 "respirol": "2",
 "re ob plus dha": "2"}, "u": {"uretron": "1",
 "urimax": "1",
 "unicap with iron": "2",
 "ursinus": "1",
 "unilax": "2",
 "utrona-c": "1",
 "uroplus": "1",
 "uni-cenna": "2",
 "utrona": "1",
 "uprima": "2",
 "unipen": "1",
 "urised": "1",
 "urban ds": "2",
 "uroplus ds": "1",
 "utira": "1",
 "uni-dur": "2",
 "uni-lan ii": "2",
 "uticap": "1",
 "urimar-t": "1",
 "ultra-natal": "2",
 "uretron ds": "1",
 "uni bronchial": "2",
 "uritact ds": "1",
 "urban": "2",
 "uni-lan": "2",
 "urobiotic-250": "2",
 "ultimatecare one": "2",
 "u-tri-lone": "2",
 "urapine": "1",
 "uni serp": "2",
 "uritin": "1",
 "uta": "1",
 "usept": "1",
 "uro blue": "1",
 "uni-daily plus iron": "2",
 "urisym": "1",
 "ultimatecare combo": "2",
 "uni kar plus c sr": "2",
 "unipres": "2",
 "uracil": "2",
 "uritact-ec": "1",
 "uniphyl": "2",
 "ulcerease": "2",
 "uroxatral": "3",
 "unasyn": "2",
 "ultimatecare one nf": "2",
 "ustell": "1",
 "ultra natalcare": "2",
 "urelle": "1",
 "ulipristal": "1",
 "ultimatecare advance": "2",
 "utira-c": "1",
 "uribel": "1",
 "uniretic": "2"}, "t": {"theolair-sr": "2",
 "ticarcillin": "1",
 "terramycin": "2",
 "tamoxifen": "2",
 "tamofen": "2",
 "tizanidine": "2",
 "theocon": "2",
 "troleandomycin": "1",
 "theomax df": "2",
 "telzir": "2",
 "tarceva": "2",
 "theo-dur": "2",
 "tobi": "2",
 "trilisate": "1",
 "twelve resin-k": "1",
 "tri-sprintec": "2",
 "triamcinolone ophthalmic": "2",
 "tol-tab": "2",
 "tramacort-d": "2",
 "trimesis rx": "2",
 "triveen-one": "2",
 "trisenox": "3",
 "triadvance": "2",
 "tekamlo": "2",
 "tobramycin": "2",
 "ticagrelor": "3",
 "tavist nd": "1",
 "thiethylperazine": "2",
 "terramycin im": "2",
 "tetra-mag": "1",
 "theoclear-80": "2",
 "trivaris": "2",
 "teveten hct": "2",
 "tipranavir": "2",
 "temaril": "2",
 "trileptal": "2",
 "truphylline": "2",
 "tbc": "2",
 "tridate": "2",
 "tegretol": "3",
 "tucks": "2",
 "trinessa lo": "2",
 "tetracon": "2",
 "trimagen": "2",
 "tranxene": "2",
 "theo-dur sprinkles": "2",
 "trichlormethiazide": "2",
 "theragran hematinic": "2",
 "tranxene sd": "2",
 "theolair": "2",
 "triphasil-28": "2",
 "tetrabenazine": "2",
 "triphasil-21": "2",
 "tenoretic": "2",
 "trilog": "2",
 "taron-prx plus dha": "2",
 "theoclear la-260": "2",
 "theolate": "2",
 "trinsicon": "2",
 "triamcot": "2",
 "tornalate": "2",
 "trinatal rx": "2",
 "tri-hydroserpine": "2",
 "thioridazine": "3",
 "trifluoperazine": "2",
 "torsemide": "2",
 "tums dual action": "2",
 "theo g": "2",
 "theocon elixir": "2",
 "triazolam": "2",
 "tolterodine": "2",
 "tenoretic 50": "2",
 "thalitone": "2",
 "tricare dha one": "2",
 "tandem f": "2",
 "tri-norinyl": "2",
 "trazodone": "2",
 "tandem ob": "2",
 "trigels f": "2",
 "tamone": "2",
 "trandolapril/verapamil": "2",
 "tiazac": "2",
 "therems h": "2",
 "tempo": "2",
 "theodrine": "2",
 "torecan": "2",
 "tofranil-pm": "2",
 "theovent": "2",
 "targretin": "2",
 "trihemic 600": "2",
 "tolinase": "2",
 "tricare": "2",
 "timolide": "2",
 "tixylix baby syrup": "2",
 "tetracap": "2",
 "tac 3": "2",
 "trivora": "2",
 "telithromycin": "2",
 "torisel": "2",
 "tegopen": "1",
 "taxol": "2",
 "tri-levlen": "2",
 "tri vites with fluoride and iron": "2",
 "triesence": "2",
 "telaprevir": "2",
 "toremifene": "3",
 "triamonide 40": "2",
 "tri-vi-sol with iron": "2",
 "talwin compound": "1",
 "therapy bayer": "1",
 "theo-24": "2",
 "tasigna": "3",
 "theobid": "2",
 "tl icon": "2",
 "truxcillin vk": "1",
 "trycet": "2",
 "tri-previfem": "2",
 "tristoject": "2",
 "toviaz": "2",
 "tl-fol 500": "2",
 "tequin": "3",
 "trimipramine": "2",
 "trimagen fa": "2",
 "ternamar": "2",
 "taxotere": "2",
 "tenoretic 100": "2",
 "triphasil": "2",
 "tri-legest fe": "2",
 "tranxene t-tab": "2",
 "triflupromazine": "2",
 "triquilar 28": "2",
 "tolfrinic": "2",
 "triquilar 21": "2",
 "trizivir": "1",
 "triavil": "2",
 "t-phyl": "2",
 "tolvaptan": "3",
 "theoclear la-130": "2",
 "terfenadine": "3",
 "tekturna hct": "2",
 "tamosin": "2",
 "tagamet": "1",
 "trimeprazine": "2",
 "tandem": "2",
 "trac tabs 2x": "1",
 "theo-time": "2",
 "timolide 10-25": "2",
 "theophylline ki": "2",
 "tedrigen": "2",
 "trinessa": "2",
 "tija": "2",
 "theophyll-gg": "2",
 "tambocor": "2",
 "tandem dha": "2",
 "triam-forte": "2",
 "tequin teqpaq": "3",
 "timentin": "1",
 "tricosal": "1",
 "taron forte": "2",
 "triam-a": "2",
 "telavancin": "2",
 "theocap": "2",
 "tegretol xr": "3",
 "tikosyn": "3",
 "tri-lo-sprintec": "2",
 "taron-c dha": "2",
 "tofranil": "2",
 "theophylline": "2",
 "tarka": "2",
 "trivora-28": "2",
 "tamoxifen hexal": "2",
 "taron-bc": "2",
 "tilia fe": "2",
 "terbutaline": "2",
 "tri-vi-flor with iron": "2",
 "tri rx": "2",
 "tadalafil": "2",
 "theo-x": "2",
 "trilone": "2",
 "triamcinolone": "2",
 "tao": "1",
 "totacillin-n": "2",
 "tricon": "2",
 "tolazamide": "2",
 "truxophyllin": "2",
 "tab-a-vite with iron": "2",
 "ticar": "1",
 "trimagen forte": "2",
 "taztia xt": "2",
 "triferex 150 forte": "2",
 "tracleer": "2",
 "tribenzor": "2",
 "tolbutamide": "2",
 "troglitazone": "2",
 "theochron": "2",
 "tetracycline": "2",
 "tri-legest": "2",
 "theomar gg": "2",
 "tri-buffered aspirin": "1",
 "trinate": "2",
 "taron-ec calc dha pack": "2",
 "triveen-prx rnf": "2",
 "tamsulosin": "3",
 "teczem": "2",
 "tagamet hb": "1",
 "treximet": "2",
 "tacaryl": "2",
 "trilafon": "2",
 "tacrolimus": "2",
 "thorazine": "2",
 "tamoxen": "2",
 "tekturna": "2",
 "trexall": "3",
 "typhoid vaccine, live": "2",
 "tykerb": "2",
 "temsirolimus": "2"}, "w": {"wygesic": "2",
 "wycillin": "1",
 "wigraine": "3",
 "warfarin": "3",
 "wal-itin": "1"}, "v": {"vi-daylin adc with iron": "2",
 "versed": "2",
 "vascor": "3",
 "vinate advanced": "2",
 "verotin-by": "2",
 "vinate az extra": "2",
 "vytorin": "3",
 "vibra-tabs": "2",
 "vanspar": "2",
 "v-gan-50": "2",
 "venatal fa": "2",
 "viagra": "3",
 "vardenafil": "2",
 "vospire er": "2",
 "vi-daylin with iron": "2",
 "vinate care": "2",
 "vitelle irospan": "2",
 "vibramycin": "2",
 "victrelis": "2",
 "vinate good start": "2",
 "vesicare": "2",
 "vincristine": "3",
 "vi-daylin/f adc with iron": "2",
 "vectibix": "2",
 "vaseretic": "2",
 "valturna": "2",
 "vinate ic": "2",
 "vinate ii": "2",
 "vanquish": "1",
 "venelex": "2",
 "vita-pms": "2",
 "vibal": "1",
 "vitaspire": "2",
 "vinate ultra": "2",
 "vinate 90": "2",
 "vitafol-ob+dha": "2",
 "verelan pm": "2",
 "veracolate": "2",
 "vitaphil": "2",
 "vitelle nestabs otc": "2",
 "vitabee 12": "1",
 "viracept": "3",
 "velivet": "2",
 "valdecoxib": "2",
 "volmax": "2",
 "vanatrip": "2",
 "v-cillin k": "1",
 "vol-nate": "2",
 "voriconazole": "2",
 "viramune": "2",
 "velcade": "2",
 "vemurafenib": "3",
 "vivotif berna": "2",
 "vitanatal ob plus dha": "2",
 "valium": "2",
 "vi-stress with iron": "2",
 "vincasar pfs": "3",
 "valproic acid": "2",
 "vilazodone": "2",
 "valrelease": "2",
 "vaseretic 10-25": "2",
 "vinatal forte": "2",
 "veramyst": "2",
 "vinate iii": "2",
 "vivactil": "2",
 "vibativ": "2",
 "vimovo": "2",
 "vasopressin": "2",
 "vaseretic 5-12.5": "2",
 "vaprisol": "3",
 "vitaphil plus dha": "2",
 "viibryd": "2",
 "viramune xr": "2",
 "vitamed prenatal formula": "2",
 "vemavite prx 2": "2",
 "vanceril ds": "2",
 "vinorelbine": "3",
 "vitagen forte": "2",
 "vestura": "2",
 "vol-plus": "2",
 "verelan": "2",
 "votrient": "3",
 "vitaphil aide": "2",
 "vitafol pn": "2",
 "vita drops with iron": "2",
 "ventolin": "2",
 "vinacal or": "2",
 "vitron-c": "2",
 "vasolex": "2",
 "veripred 20": "2",
 "vernate": "2",
 "vanceril": "2",
 "vynatal fa": "2",
 "vi-daylin with iron chewable": "2",
 "v-gan-25": "2",
 "ventolin hfa": "2",
 "vitamin b12": "1",
 "vinate pn care": "2",
 "vernate advanced": "2",
 "vimar with iron": "2",
 "vivitrol": "2",
 "vitagen advance": "2",
 "vinate one": "2",
 "vitafol-ob": "2",
 "vinblastine": "3",
 "viva dha": "2",
 "vita-pms plus": "2",
 "vol-tab rx": "2",
 "vfend": "2",
 "vynatal 1 plus 1": "2",
 "vinate az": "2",
 "vi-daylin/f plus iron": "2",
 "vinate c": "2",
 "vinate m": "2",
 "vinate calcium": "2",
 "vi-daylin with iron drops": "2",
 "velban": "3",
 "verapamil": "2",
 "vitron-c-plus": "2",
 "vicks formula 44 custom care throat spray": "2",
 "vinate gt": "2",
 "vantin": "2",
 "verotin-gr": "2",
 "vinatal 600": "2",
 "vandetanib": "3",
 "vivotif berna vaccine": "2",
 "veetids": "1",
 "vita #12": "1"}, "y": {"yutopar": "2",
 "ysp aspirin": "1",
 "yasmin": "2",
 "yieronia": "2",
 "yaz": "2"}, "x": {"xopenex": "2",
 "xopenex hfa": "2",
 "xanax xr": "2",
 "xanax": "2",
 "xarelto": "2",
 "xenaderm": "2",
 "x-prep": "2",
 "xalkori": "3",
 "xopenex concentrate": "2",
 "xenazine": "2"}, "z": {"zagam respipac": "3",
 "zmax": "2",
 "zovia 1/50": "2",
 "zatean-pn dha": "2",
 "zenate prenatal": "2",
 "zosyn": "1",
 "zitamin": "2",
 "zenate": "2",
 "zatean-pn": "2",
 "zarah": "2",
 "zocor": "3",
 "zovia 1/35": "2",
 "zema pak": "2",
 "zyloprim": "1",
 "zovia": "2",
 "zelboraf": "3",
 "zenate advanced formula": "2",
 "zeosa": "2",
 "zero-order release": "1",
 "zonisamide": "2",
 "zithromax": "2",
 "zatean-pn plus": "2",
 "ziprasidone": "3",
 "zetonna": "2",
 "zuplenz": "2",
 "zytiga": "2",
 "zorprin": "1",
 "zegerid otc": "1",
 "zemplar": "2",
 "zofran": "2",
 "zolpidem": "1",
 "zortress": "3",
 "zagam": "3",
 "zofran odt": "2",
 "zaponex": "2",
 "zestoretic": "2",
 "zenchent fe": "2",
 "zanaflex": "2",
 "zegerid": "1",
 "zatean-ch": "2",
 "zenchent": "2",
 "zonegran": "2",
 "zoloft": "2",
 "zidovudine": "1",
 "zinacef": "2",
 "zaroxolyn": "2",
 "zetran": "2",
 "ziac": "2",
 "zolpimist": "1"}}];