interactions["anastrozole,arimidex"]=["anastrozole,arimidex", {"a": {"activella": "2",
 "alyacen 7/7/7": "2",
 "amethia": "2",
 "altavera": "2",
 "aviane": "2",
 "amethia lo": "2",
 "apri": "2",
 "azathioprine": "2",
 "aerodiol": "2",
 "amethyst": "2",
 "alesse-21": "2",
 "alesse": "2",
 "angeliq": "2",
 "aquest": "2",
 "alora": "2",
 "adgyn estro": "2",
 "azasan": "2",
 "alesse-28": "2",
 "azurette": "2",
 "aranelle": "2",
 "alyacen 1/35": "2"}, "c": {"cyclafem 7/7/7": "2",
 "climara pro": "2",
 "climaval": "2",
 "conjugated estrogens/meprobamate": "2",
 "cenestin": "2",
 "conjugated estrogens": "2",
 "conjugated estrogens/medroxyprogesterone": "2",
 "cyclessa": "2",
 "covaryx": "2",
 "covaryx hs": "2",
 "combipatch": "2",
 "conjugated estrogens/methyltestosterone": "2",
 "camreselo": "2",
 "conjugated estrogens topical": "2",
 "cryselle": "2",
 "chlorotrianisene": "2",
 "cyclafem 1/35": "2",
 "camrese": "2",
 "cesia": "2",
 "clinagen la 40": "2",
 "caziant": "2",
 "climodien": "2",
 "climara": "2"}, "b": {"bedol": "2",
 "brevicon": "2",
 "briellyn": "2",
 "beyaz": "2",
 "balziva": "2"}, "e": {"estrofem": "2",
 "estra-v 40": "2",
 "estratest h.s.": "2",
 "estrogel": "2",
 "evorel": "2",
 "estragyn la 5": "2",
 "ethinyl estradiol/norgestrel": "2",
 "estrace": "2",
 "enjuvia": "2",
 "estradiol g gam": "2",
 "estinyl": "2",
 "emoquette": "2",
 "estraderm": "2",
 "elleste solo": "2",
 "estramustine": "2",
 "ethinyl estradiol": "2",
 "ethinyl estradiol/norelgestromin": "2",
 "eemt hs": "2",
 "estradiol/norethindrone topical": "2",
 "emblon": "2",
 "estradiol/medroxyprogesterone": "2",
 "enpresse": "2",
 "estradiol topical": "2",
 "esterified estrogens/methyltestosterone": "2",
 "estro-cyp": "2",
 "emcyt": "2",
 "estrace vaginal cream": "2",
 "evamist": "2",
 "estradiol": "2",
 "essian h.s.": "2",
 "estrapatch": "2",
 "ethinyl estradiol/ethynodiol": "2",
 "estropipate topical": "2",
 "ethinyl estradiol/norgestimate": "2",
 "estro-a": "2",
 "estradot 37.5": "2",
 "estradiol/testosterone": "2",
 "eemt ds": "2",
 "estradot": "2",
 "estreva": "2",
 "estrone": "2",
 "estratest": "2",
 "ethinyl estradiol/norethindrone": "2",
 "estragyn 5": "2",
 "ethinyl estradiol/etonogestrel": "2",
 "estradiol patch": "2",
 "estring": "2",
 "elestrin": "2",
 "estrogen patches": "2",
 "ethinyl estradiol/levonorgestrel": "2",
 "estro-span 40": "2",
 "estra-c": "2",
 "esterified estrogens": "2",
 "estrostep fe": "2",
 "estradot 100": "2",
 "estropipate": "2",
 "eemt": "2",
 "estrone aq": "2",
 "estradot 75": "2",
 "estradiol/norgestimate": "2",
 "estradiol/levonorgestrel": "2",
 "estradiol/norethindrone": "2",
 "estro-la": "2",
 "estradot 50": "2",
 "essian": "2",
 "estrasorb": "2",
 "estra-testrin": "2",
 "estratab": "2",
 "esclim": "2"}, "d": {"dura-dumone": "2",
 "duragen": "2",
 "drospirenone/ethinyl estradiol": "2",
 "depogen": "2",
 "delidose": "2",
 "dermestril": "2",
 "desogen": "2",
 "dasetta 1/35": "2",
 "delestrogen": "2",
 "dermestril septem": "2",
 "dura-estrin": "2",
 "demulen": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "divigel": "2",
 "drospirenone/estradiol": "2",
 "demulen 1/35": "2",
 "demulen 1/50": "2",
 "desogestrel/ethinyl estradiol": "2",
 "delatestadiol": "2",
 "duratestrin": "2",
 "dioval 40": "2",
 "dienogest/estradiol": "2",
 "dep androgyn": "2",
 "depotestogen": "2",
 "diethylstilbestrol": "2",
 "dienestrol topical": "2",
 "duo-cyp": "2",
 "dasetta 7/7/7": "2",
 "dioval xx": "2",
 "depo-estradiol": "2",
 "dep gynogen": "2",
 "depo-testadiol": "2",
 "dasetta": "2"}, "g": {"gianvi": "2",
 "gynogen la 20": "2",
 "generess fe": "2",
 "gynodiol": "2",
 "genora 1/35": "2",
 "genora 1/50": "2",
 "gildess fe 1.5/30": "2",
 "genox": "2",
 "gildess fe 1/20": "2",
 "genora 0.5/35": "2"}, "f": {"femtran": "2",
 "femring": "2",
 "femtab": "2",
 "femsept": "2",
 "femseven": "2",
 "femseven sequi phase i": "2",
 "femtrace": "2",
 "femhrt": "2",
 "femcon fe": "2",
 "fematrix": "2",
 "fempatch": "2"}, "i": {"imuran": "2",
 "introvale": "2"}, "k": {"kelnor 1/35": "2",
 "kestrone 5": "2",
 "kariva": "2"}, "j": {"jolessa": "2",
 "junel 1.5/30": "2",
 "jenest": "2",
 "jinteli": "2",
 "jevantique": "2",
 "junel 1/20": "2",
 "junel fe 1/20": "2",
 "junel fe 1.5/30": "2"}, "m": {"menogen": "2",
 "modicon": "2",
 "myzilra": "2",
 "marlissa": "2",
 "menorest": "2",
 "mestranol/norethindrone": "2",
 "min-ovral 28": "2",
 "microgestin fe 1/20": "2",
 "menorest patch": "2",
 "min-ovral 21": "2",
 "menaval-20": "2",
 "microgestin fe 1.5/30": "2",
 "medidiol 10": "2",
 "microgestin 1.5/30": "2",
 "menostar": "2",
 "mononessa": "2",
 "mircette": "2",
 "microgestin 1/20": "2",
 "mimvey": "2",
 "menogen hs": "2",
 "menest": "2"}, "l": {"loestrin fe 1.5/30": "2",
 "lybrel": "2",
 "lo loestrin fe": "2",
 "loestrin fe 1/20": "2",
 "lunelle": "2",
 "lutera": "2",
 "lessina": "2",
 "loryna": "2",
 "leena": "2",
 "levonest": "2",
 "loestrin 1/20": "2",
 "lo/ovral-28": "2",
 "levora": "2",
 "low-ogestrel-21": "2",
 "low-ogestrel-28": "2",
 "levlite": "2",
 "loseasonique": "2",
 "loestrin 21 1.5/30": "2",
 "lo/ovral": "2",
 "loestrin 21 1/20": "2",
 "levlen": "2",
 "loestrin 24 fe": "2"}, "o": {"ortho-prefest": "2",
 "organon oestradiol": "2",
 "oestrodose": "2",
 "ogen 1.25": "2",
 "ogestrel-28": "2",
 "ortho-novum 1/50": "2",
 "ortho-novum 1/35": "2",
 "oestrogel pump-pack": "2",
 "ortho-novum 7/7/7": "2",
 "ortho evra": "2",
 "ogen 0.625": "2",
 "oestrogel": "2",
 "ogen vaginal cream": "2",
 "ortho-est": "2",
 "ogen 2.5": "2",
 "oestradiol implants": "2",
 "ortho tri-cyclen": "2",
 "ocella": "2",
 "ovcon 35 fe": "2",
 "ortho dienestrol": "2",
 "ortho-novum 10/11": "2",
 "oromone": "2",
 "ogestrel": "2",
 "ortho tri-cyclen lo": "2",
 "ogen": "2",
 "orsythia": "2",
 "ovcon 35": "2",
 "ortho-cept": "2",
 "oesclim": "2",
 "ovcon 50": "2",
 "ovral-28": "2",
 "ortho cyclen": "2",
 "ovral": "2"}, "n": {"norethin 1/35 e": "2",
 "nuvaring": "2",
 "necon 0.5/35": "2",
 "norethin 1/50 m": "2",
 "natazia": "2",
 "nolvadex d": "2",
 "nortrel 0.5/35": "2",
 "necon 10/11": "2",
 "necon 1/35": "2",
 "nolvadex": "2",
 "necon 7/7/7": "2",
 "necon 1/50": "2",
 "nelova 10/11": "2",
 "nuvelle ts phase i": "2",
 "nordette-28": "2",
 "nordette-21": "2",
 "norinyl 1+35": "2",
 "norinyl 1+50": "2",
 "nelova 0.5/35": "2",
 "nordette": "2",
 "nortrel 7/7/7": "2",
 "nelova 1/35": "2",
 "nortrel 1/35": "2",
 "nelova 1/50 m": "2"}, "q": {"quinestrol": "2",
 "quasense": "2"}, "p": {"portia": "2",
 "premarin": "2",
 "progynova": "2",
 "philith": "2",
 "premphase": "2",
 "primogyn depot": "2",
 "provames": "2",
 "prefest": "2",
 "preven ec": "2",
 "pmb": "2",
 "previfem": "2",
 "prempro": "2",
 "premphase 14/14": "2",
 "premarin vaginal": "2",
 "premarin intravenous": "2",
 "progynova ts": "2"}, "s": {"soltamox": "2",
 "stilphostrol": "2",
 "syeda": "2",
 "syntest hs": "2",
 "sronyx": "2",
 "synthetic conjugated estrogens a": "2",
 "seasonique": "2",
 "safyral": "2",
 "solia": "2",
 "systen": "2",
 "seasonale": "2",
 "sprintec": "2",
 "syntest ds": "2",
 "sandrena": "2"}, "r": {"reclipsen": "2"}, "t": {"tamoxifen": "2",
 "tamoxifen hexal": "2",
 "tilia fe": "2",
 "tri-previfem": "2",
 "trinessa": "2",
 "tace": "2",
 "tri-sprintec": "2",
 "tri-legest fe": "2",
 "tri-norinyl": "2",
 "triquilar 28": "2",
 "trivora": "2",
 "triquilar 21": "2",
 "tamone": "2",
 "tri-legest": "2",
 "tamofen": "2",
 "triphasil": "2",
 "tamosin": "2",
 "trinessa lo": "2",
 "thalidomide": "3",
 "thaissept": "2",
 "thais": "2",
 "thalomid": "3",
 "tri-levlen": "2",
 "tamoxen": "2",
 "trivora-28": "2",
 "triphasil-28": "2",
 "triphasil-21": "2",
 "tri-lo-sprintec": "2"}, "v": {"valertest no 1": "2",
 "vivelle-dot": "2",
 "velivet": "2",
 "valergen": "2",
 "vagifem": "2",
 "vestura": "2",
 "vivelle": "2"}, "y": {"yasmin": "2",
 "yaz": "2"}, "z": {"zumenon": "2",
 "zenchent fe": "2",
 "zovia": "2",
 "zovia 1/50": "2",
 "zenchent": "2",
 "zeosa": "2",
 "zarah": "2",
 "zovia 1/35": "2"}}];