interactions["antivenin-crotalidae-polyvalent,crofab"]=["antivenin-crotalidae-polyvalent,crofab", {"a": {"acebutolol": "2",
 "ak-beta": "2",
 "atenolol/chlorthalidone": "2",
 "atenolol": "2"}, "c": {"carteolol": "2",
 "cosopt pf": "2",
 "corgard": "2",
 "cartrol": "2",
 "coreg": "2",
 "corzide 40/5": "2",
 "corzide": "2",
 "cosopt": "2",
 "combigan": "2",
 "carvedilol": "2",
 "coreg cr": "2",
 "carteolol ophthalmic": "2",
 "corzide 80/5": "2"}, "b": {"brevibloc": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "bystolic": "2",
 "betaxolol": "2",
 "bisoprolol": "2",
 "betapace af": "2",
 "betaxon": "2",
 "blocadren": "2",
 "betoptic s": "2",
 "betagan": "2",
 "betimol": "2",
 "bendroflumethiazide/nadolol": "2",
 "betaxolol ophthalmic": "2",
 "betoptic": "2",
 "betagan c-cap": "2",
 "brimonidine/timolol ophthalmic": "2",
 "betapace": "2"}, "e": {"esmolol": "2"}, "d": {"dutoprol": "2",
 "dorzolamide/timolol ophthalmic": "2"}, "i": {"inderal la": "2",
 "innopran xl": "2",
 "inderal": "2",
 "inderide la": "2",
 "istalol": "2",
 "inderide": "2"}, "h": {"hydrochlorothiazide/propranolol": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hydrochlorothiazide/timolol": "2"}, "k": {"kerlone": "2"}, "m": {"metoprolol": "2",
 "metoprolol succinate er": "2",
 "metipranolol ophthalmic": "2"}, "l": {"levobetaxolol ophthalmic": "2",
 "levatol": "2",
 "lopressor": "2",
 "levobunolol ophthalmic": "2",
 "lopressor hct": "2",
 "labetalol": "2"}, "o": {"ocupress": "2",
 "optipranolol": "2"}, "n": {"nadolol": "2",
 "nebivolol": "2",
 "normodyne": "2"}, "p": {"pindolol": "2",
 "penbutolol": "2",
 "propranolol": "2"}, "s": {"sotalol hydrochloride af": "2",
 "sotalol": "2",
 "sorine": "2",
 "sectral": "2"}, "t": {"tenoretic": "2",
 "timolol ophthalmic": "2",
 "trandate": "2",
 "timolol": "2",
 "timoptic-xe": "2",
 "tenoretic 100": "2",
 "tenormin": "2",
 "tenoretic 50": "2",
 "toprol-xl": "2",
 "timoptic ocudose": "2",
 "timolide 10-25": "2",
 "timoptic": "2",
 "timolide": "2"}, "v": {"visken": "2"}, "z": {"ziac": "2",
 "zebeta": "2"}}];