interactions["ardeparin,normiflo"]=["ardeparin,normiflo", {"a": {"aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "3",
 "aspirin/hydrocodone": "3",
 "anacin": "3",
 "aspergum": "3",
 "abciximab": "3",
 "ascriptin enteric": "3",
 "argatroban": "3",
 "aspirin/diphenhydramine": "3",
 "advil liqui-gels": "3",
 "aspirin/chlorpheniramine/phenylephrine": "3",
 "aspirin/meprobamate": "3",
 "aflaxen": "3",
 "aspirin/oxycodone": "3",
 "advil pm": "3",
 "aspir-mox": "3",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "2",
 "antithrombin": "3",
 "alteplase": "3",
 "acular pf": "2",
 "aspirin/caffeine/orphenadrine": "3",
 "aspirin/phenyltoloxamine": "3",
 "arixtra 7.5 mg/dose": "3",
 "ascomp with codeine": "3",
 "aspirin/diphenhydramine/phenylpropanolamine": "3",
 "alor 5/500": "3",
 "arixtra 5 mg/dose": "3",
 "argesic-sa": "2",
 "alka-seltzer plus flu formula": "3",
 "addaprin": "3",
 "anaflex": "2",
 "aspirin buffered": "3",
 "acetaminophen/aspirin/caffeine/salicylamide": "3",
 "arthritis pain formula": "3",
 "aspirin/pravastatin": "3",
 "arixtra 10 mg/dose": "3",
 "advil cold and sinus liqui-gels": "3",
 "acetaminophen/aspirin": "3",
 "all day pain relief": "3",
 "anaprox": "3",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "acular ls": "2",
 "aspirin/butalbital/caffeine/codeine": "3",
 "aspirin/caffeine": "3",
 "aptivus": "3",
 "aspirin/carisoprodol": "3",
 "aqua-e": "2",
 "aspir 81": "3",
 "alka-seltzer extra strength": "3",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "2",
 "atryn (antithrombin (recombinant))": "3",
 "advil children's allergy sinus": "3",
 "acetaminophen/aspirin/caffeine": "3",
 "aleve": "3",
 "aspir-low": "3",
 "adult strength": "3",
 "arixtra": "3",
 "anturane": "3",
 "arthritis pain": "3",
 "aspirin/methocarbamol": "3",
 "arthriten": "2",
 "anistreplase": "3",
 "a-g profen": "3",
 "alka-seltzer wake-up call!": "3",
 "aggrenox": "3",
 "arthropan": "2",
 "advil allergy sinus": "3",
 "alka-seltzer original": "3",
 "acuvail": "2",
 "ascriptin maximum strength": "3",
 "atrosept": "2",
 "amigesic": "2",
 "alka-seltzer lemon-lime": "3",
 "alpha e": "2",
 "advil children's cold": "3",
 "aspirin/butalbital/caffeine": "3",
 "aquasol e": "2",
 "anisindione": "3",
 "advil migraine": "3",
 "all day relief": "3",
 "atnativ": "3",
 "anacin advanced headache formula": "3",
 "antithrombin iii": "3",
 "advil infant's concentrated drops": "3",
 "aspirin/caffeine/dihydrocodeine": "3",
 "actiprofen": "3",
 "acular": "2",
 "angiomax": "3",
 "alka-seltzer plus cold formula": "3",
 "alka-seltzer pm": "3",
 "abbokinase": "3",
 "aspirin/chlorpheniramine/phenylpropanolamine": "3",
 "aspirin/pseudoephedrine": "3",
 "acetaminophen/salicylamide": "2",
 "anacin max strength": "3",
 "azdone": "3",
 "aspirin/carisoprodol/codeine": "3",
 "aspirin": "3",
 "acetaminophen/aspirin/phenylpropanolamine": "3",
 "ari sodium iodide (i123) 1-12 mbq": "2",
 "aspirin/calcium carbonate": "3",
 "aleve-d sinus &amp; cold": "3",
 "aspirin/dipyridamole": "3",
 "acuprin 81": "3",
 "aggrastat": "3",
 "aspirin/citric acid/sodium bicarbonate": "3",
 "acetaminophen/phenyltoloxamine/salicylamide": "2",
 "advil junior strength": "3",
 "agrylin": "3",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "3",
 "aspirin/chlorpheniramine/dextromethorphan": "3",
 "anaprox-ds": "3",
 "aspiritab": "3",
 "aspirin/caffeine/propoxyphene": "3",
 "aquavite-e": "2",
 "ascriptin": "3",
 "actron": "3",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "aqua gem-e": "2",
 "ari sodium iodide (i123) 100-750 mbq": "2",
 "arthrotec": "3",
 "abbokinase open-cath": "3",
 "anabar": "2",
 "advil": "3",
 "anagrelide": "3",
 "aspirtab": "3",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "3",
 "aspircaf": "3",
 "acetylsalicylic acid": "3",
 "aspirin lite coat": "3",
 "aspirin/butalbital": "3",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "3",
 "aspirin/codeine": "3",
 "advil cold and sinus": "3",
 "aspirin/pentazocine": "3",
 "acova": "3",
 "ansaid": "3",
 "aspirin low strength": "3",
 "activase": "3",
 "aspir-mox ib": "3",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "advil children's": "3",
 "aspirin/caffeine/salicylamide": "3",
 "arthritis foundation pain reliever": "3",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "amino-opti-e": "2"}, "c": {"cafgesic forte": "2",
 "clinoril": "3",
 "cystex": "2",
 "celexa": "2",
 "collagenase clostridium histolyticum": "2",
 "cvs extra strength headache relief": "3",
 "cystemms-v": "2",
 "carisoprodol compound": "3",
 "combiflex": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "clove": "1",
 "chamomile": "1",
 "comfort pac with naproxen": "3",
 "cataflam": "3",
 "cope": "3",
 "choline salicylate/magnesium salicylate": "2",
 "caldolor": "3",
 "combunox": "3",
 "cathflo activase": "3",
 "childrens ibuprofen berry": "3",
 "cilostazol": "3",
 "cymbalta": "2",
 "clopidogrel": "3",
 "choline magnesium trisalicylate": "2",
 "citalopram": "2",
 "childrens kaopectate": "2",
 "celecoxib": "2",
 "cafgesic": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "3",
 "cmt": "2",
 "capsicum": "1",
 "combiflex es": "2",
 "ceprotin": "2",
 "children's motrin": "3",
 "caffeine/magnesium salicylate": "2",
 "centrum singles-vitamin e": "2",
 "choline salicylate": "2",
 "celebrex": "2",
 "coumadin": "3",
 "cap-profen": "3",
 "cambia": "3"}, "b": {"bexxar dosimetric": "3",
 "bromday": "2",
 "b c powder": "3",
 "bayer extra strength back &amp; body": "3",
 "by-ache": "2",
 "bayer advanced aspirin": "3",
 "bismarex": "2",
 "bc headache": "3",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "bufferin extra strength": "3",
 "be-flex plus": "2",
 "buffered aspirin": "3",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismatrol": "2",
 "bayer aspirin with heart advantage": "3",
 "butalbital compound": "3",
 "bayer am": "3",
 "bromfenac": "3",
 "bufferin": "3",
 "bextra": "2",
 "bayer women's low dose plus calcium": "3",
 "bayer pm": "3",
 "bayer aspirin extra strength plus": "3",
 "b c powder arthritis strength": "3",
 "buffex": "3",
 "bexxartherapeutic": "3",
 "bayer aspirin": "3",
 "bismuth subsalicylate": "2",
 "bufferin arthritis strength": "3",
 "brilinta": "3",
 "bexxar": "3",
 "bc fast pain relief": "3",
 "bromfenac ophthalmic": "2",
 "bayer women's aspirin with calcium": "3",
 "buffasal": "3",
 "bayer aspirin regimen": "3",
 "bivalirudin": "3",
 "bismatrol maximum strength": "2",
 "bufferin low dose": "3",
 "bayer select backache pain formula": "2",
 "bayer children's aspirin": "3"}, "e": {"escitalopram": "2",
 "ecotrin": "3",
 "ecotrin maximum strength": "3",
 "excedrin extra strength": "3",
 "e-gems": "2",
 "easprin": "3",
 "effient": "3",
 "effervescent pain relief": "3",
 "exjade": "3",
 "effexor xr": "2",
 "etodolac": "3",
 "e-600": "2",
 "elmiron": "2",
 "e-400 clear": "2",
 "ec-naprosyn": "3",
 "excedrin back &amp; body": "3",
 "ed-flex": "2",
 "excedrin migraine": "3",
 "endodan": "3",
 "effexor": "2",
 "extra strength bayer": "3",
 "entercote": "3",
 "ecpirin": "3",
 "emagrin": "3",
 "empirin with codeine": "3",
 "epoprostenol": "3",
 "entaprin": "3",
 "empirin": "3",
 "eminase": "3",
 "excedrin menstrual complete": "3",
 "e pherol": "2",
 "excedrin": "3",
 "equagesic": "3",
 "esomeprazole/naproxen": "3",
 "eptifibatide": "3",
 "ecotrin adult low strength": "3"}, "d": {"darvon compound 32": "3",
 "dextran-hm": "3",
 "duexis": "3",
 "doans pills extra strength": "2",
 "deferasirox": "3",
 "daypro": "3",
 "dong quai": "2",
 "dextran 70 6% in 0.9% sodium chloride": "3",
 "damason-p": "3",
 "diclofenac": "3",
 "dipyridamole": "3",
 "darpaz": "2",
 "diflunisal": "3",
 "dexfenfluramine": "2",
 "durabac forte": "2",
 "durabac": "2",
 "dolorex": "2",
 "diphenhydramine/ibuprofen": "3",
 "dristan sinus": "3",
 "dextran, low molecular weight": "3",
 "duloxetine": "2",
 "diurex": "2",
 "dolsed": "2",
 "darcalma": "2",
 "diclofenac topical": "2",
 "dicumarol": "3",
 "doan's pills": "2",
 "dasatinib": "3",
 "duract": "3",
 "dextran 40 in 5% dextrose": "3",
 "dolobid": "3",
 "darvon compound-65": "3",
 "duraxin": "2",
 "desirudin": "3",
 "disalcid": "2",
 "doans pm": "2",
 "dextran 70 6% in 5% dextrose": "3",
 "dextran 40": "3",
 "diclofenac ophthalmic": "2",
 "diclofenac/misoprostol": "3",
 "dewitt's pain reliever": "2",
 "dextran, high molecular weight": "3",
 "desvenlafaxine": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "drotrecogin alfa": "3",
 "dextran 40 in 0.9% sodium chloride": "3",
 "danaparoid": "3",
 "dextran 1": "3",
 "dabigatran": "3"}, "g": {"gentran 40 with 0.9% sodium chloride": "3",
 "gentran 40": "3",
 "goody's body pain": "3",
 "gentran 70": "3",
 "goodys headache powders": "3",
 "ginger": "2",
 "goodys extra strength": "3",
 "ginseng": "2",
 "genpril": "3",
 "goody's extra-strength headache powders": "3",
 "garlic oil": "2",
 "genprin": "3",
 "genacote": "3",
 "ginkgo": "2",
 "ginkgo biloba": "2",
 "garlic": "2",
 "genace": "3",
 "gentran 40 with 5% dextrose": "3",
 "ginger root": "2",
 "genasan": "3",
 "gennin-fc": "3"}, "f": {"flolan": "3",
 "fiortal": "3",
 "fiorinal with codeine iii": "3",
 "fiorinal with codeine": "3",
 "fortabs": "3",
 "fiorinal": "3",
 "fluvoxamine": "2",
 "fasprin": "3",
 "feldene": "3",
 "fenfluramine": "2",
 "fondaparinux": "3",
 "fiortal with codeine": "3",
 "famotidine/ibuprofen": "3",
 "fenugreek": "1",
 "fenoprofen": "3",
 "fluoxetine": "2",
 "fluoxetine/olanzapine": "2",
 "flurbiprofen": "3",
 "feverfew": "1",
 "flurbiprofen ophthalmic": "2",
 "flector patch": "2",
 "frenadol": "2",
 "fiormor": "3",
 "farbital": "3"}, "i": {"iodine i 131 tositumomab": "3",
 "ibuprofen": "3",
 "ibuprofen pmr": "3",
 "idenal": "3",
 "iprivask": "3",
 "ibuprofen/oxycodone": "3",
 "ibudone": "3",
 "iloprost": "3",
 "iodotope": "2",
 "ibuprofen/pseudoephedrine": "3",
 "integrilin": "3",
 "indocin iv": "3",
 "ibu-200": "3",
 "indocin": "3",
 "in-111 zevalin": "3",
 "indocin sr": "3",
 "ibritumomab": "3",
 "ibu": "3",
 "ibu-tab": "3",
 "ibu-4": "3",
 "ibu-6": "3",
 "ibu-8": "3",
 "indomethacin": "3"}, "h": {"heparin": "3",
 "hyophen": "2",
 "hydrocodone/ibuprofen": "3",
 "hofels ginger one a day": "2",
 "helidac": "2",
 "halfprin": "3",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hyskon": "3",
 "heartline": "3",
 "heparin sodium": "3",
 "hemin": "2",
 "haltran": "3"}, "k": {"kaopectate anti-diarrheal upset stomach reliever": "2",
 "kinlytic": "3",
 "kneerelief": "2",
 "k-pek": "2",
 "ketoprofen": "3",
 "ketorolac ophthalmic": "2",
 "kao-tin bismuth subsalicylate formula": "2",
 "kaopectate extra strength": "2",
 "kaopectate": "2",
 "korlym": "3",
 "kabikinase": "3",
 "kapectolin": "2",
 "ketorolac": "3"}, "j": {"jakafi": "3",
 "jantoven": "3"}, "m": {"motrin cold and flu": "3",
 "mst": "2",
 "migralex": "3",
 "mobic": "3",
 "minitabs": "3",
 "meridia": "2",
 "mobigesic": "2",
 "midol traditional": "3",
 "marthritic": "2",
 "miradon": "3",
 "motrin ib": "3",
 "magsal": "2",
 "mobidin": "2",
 "mefenamic acid": "3",
 "motrin": "3",
 "mhp-a": "2",
 "motrin migraine pain": "3",
 "micrainin": "3",
 "meclofenamate": "3",
 "motrin sinus headache": "3",
 "msp-blu": "2",
 "medi-seltzer": "3",
 "meloxicam": "3",
 "milnacipran": "2",
 "momentum": "3",
 "medique pain-off": "3",
 "macrodex": "3",
 "midol extended relief": "3",
 "motrin pm": "3",
 "mifeprex": "3",
 "mag-phen": "2",
 "motrin infant drops": "3",
 "medique medi-seltzer": "3",
 "mifepristone": "3",
 "maalox total relief": "2",
 "midol ib": "3",
 "motrin junior strength": "3",
 "motrin childrens": "3",
 "mithracin": "3",
 "magnaprin": "3",
 "motrin childrens cold": "3",
 "menadol": "3",
 "meclomen": "3",
 "mono-gesic": "2",
 "magan": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "myogesic": "2",
 "midol maximum strength cramp formula": "3",
 "motrin ib sinus": "3",
 "magnesium salicylate": "2",
 "maximum strength stress": "2"}, "l": {"litecoat aspirin": "3",
 "leader naproxen sodium": "3",
 "lodine xl": "3",
 "luvox": "2",
 "lodine": "3",
 "lortab asa": "3",
 "lepirudin": "3",
 "low dose asa": "3",
 "lmd with 0.9% sodium chloride": "3",
 "laniroif": "3",
 "lmd with 5% dextrose": "3",
 "levacet": "3",
 "luvox cr": "2",
 "lansoprazole/naproxen": "3",
 "lexapro": "2",
 "lobac": "2"}, "o": {"orphengesic": "3",
 "orphengesic forte": "3",
 "orudis": "3",
 "oxaprozin": "3",
 "orudis kt": "3",
 "oruvail": "3",
 "ocufen": "2",
 "orgaran": "3"}, "n": {"nutr-e-sol": "2",
 "nuprin backache caplet": "2",
 "norgesic forte": "3",
 "nexcede": "3",
 "norgesic": "3",
 "nuprin": "3",
 "norwich aspirin": "3",
 "nalfon": "3",
 "novasal": "2",
 "naprosyn": "3",
 "naproxen sodium ds": "3",
 "naproxen/pseudoephedrine": "3",
 "naproxen": "3",
 "naprelan": "3",
 "naproxen/sumatriptan": "3",
 "neoprofen": "3",
 "nabumetone": "3",
 "nepafenac ophthalmic": "2",
 "nevanac": "2"}, "q": {"q-profen": "3"}, "p": {"paroxetine": "2",
 "phosphasal": "2",
 "prosed ds": "2",
 "protein c": "2",
 "paxil": "2",
 "pamprin all day relief": "3",
 "panritis forte": "2",
 "pepto-bismol maximum strength": "2",
 "pondimin": "2",
 "persantine": "3",
 "prozac weekly": "2",
 "panhematin": "2",
 "paxil cr": "2",
 "prosed ec": "2",
 "phenylbutazone": "3",
 "pc-cap": "3",
 "prozac": "2",
 "prasugrel": "3",
 "pennsaid": "2",
 "plavix": "3",
 "p-a-c": "3",
 "pradaxa": "3",
 "persantine iv": "3",
 "prevacid naprapac 500": "3",
 "pepto-bismol": "2",
 "peptic relief": "2",
 "pletal": "3",
 "ponstel": "3",
 "percodan-demi": "3",
 "painaid": "3",
 "pristiq": "2",
 "protexel": "2",
 "phosenamine": "2",
 "promit": "3",
 "profenal": "2",
 "prevacid naprapac 375": "3",
 "propoxyphene compound 65": "3",
 "prevacid naprapac": "3",
 "pink bismuth": "2",
 "piroxicam": "3",
 "pamprin max menstrual pain relief": "3",
 "pravigard pac": "3",
 "p-a-c analgesic": "3",
 "pamprin cramp menstrual pain relief": "2",
 "pexeva": "2",
 "panasal 5/500": "3",
 "percodan": "3",
 "pentosan polysulfate sodium": "2",
 "plicamycin": "3"}, "s": {"saleto-200": "3",
 "sulindac": "3",
 "saleto": "3",
 "sarafem": "2",
 "sertraline": "2",
 "sulfinpyrazone": "3",
 "soma compound": "3",
 "sine-aid ib": "3",
 "sprycel": "3",
 "streptokinase": "3",
 "stomach relief": "2",
 "suprofen ophthalmic": "2",
 "sutent": "2",
 "selfemra": "2",
 "sibutramine": "2",
 "salsalate": "2",
 "salflex": "2",
 "saleto-800": "3",
 "saleto-d": "2",
 "soma compound with codeine": "3",
 "st. joseph 81 mg aspirin enteric safety-coated": "3",
 "sloprin": "3",
 "symbyax": "2",
 "streptase": "3",
 "solaraze": "2",
 "st. joseph aspirin": "3",
 "salsitab": "2",
 "synalgos-dc": "3",
 "saleto-600": "3",
 "sodium iodide i-123": "2",
 "sodium thiosalicylate": "2",
 "st. joseph 81 mg chewable aspirin": "3",
 "supac": "3",
 "sodium salicylate": "2",
 "sunitinib": "2",
 "stanback analgesic": "3",
 "scot-tussin original": "2",
 "stress maximum strength": "2",
 "sprix": "3",
 "stanback fast pain relief": "3",
 "sodium iodide-i-131": "2",
 "saleto-400": "3",
 "savella": "2",
 "sudafed 12 hour pressure+pain": "3"}, "r": {"robaxisal": "3",
 "remodulin": "3",
 "roxiprin": "3",
 "reopro": "3",
 "rapiflux": "2",
 "rofecoxib": "2",
 "ruxolitinib": "3",
 "rufen": "3",
 "rhinocaps": "3",
 "retavase half-kit": "3",
 "refludan": "3",
 "rexolate": "2",
 "retavase": "3",
 "reprexain": "3",
 "rhinogesic": "2",
 "rivaroxaban": "3",
 "rheomacrodex": "3",
 "relafen": "3",
 "redux": "2",
 "reteplase": "3"}, "u": {"uretron": "2",
 "urimax": "2",
 "ursinus": "3",
 "utrona-c": "2",
 "utira-c": "2",
 "uritact ds": "2",
 "urimar-t": "2",
 "urised": "2",
 "utira": "2",
 "utrona": "2",
 "uretron ds": "2",
 "urapine": "2",
 "uritin": "2",
 "usept": "2",
 "urisym": "2",
 "uta": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "urokinase": "3",
 "ustell": "2",
 "urelle": "2",
 "uribel": "2"}, "t": {"ticlid": "3",
 "toradol": "3",
 "tusal": "2",
 "tyvaso": "3",
 "treprostinil": "3",
 "tolectin 600": "3",
 "tolectin": "3",
 "tositumomab": "3",
 "ticlopidine": "3",
 "tenecteplase": "3",
 "tolmetin": "3",
 "toradol iv/im": "3",
 "thrombate iii": "3",
 "tetra-mag": "2",
 "toradol im": "3",
 "tipranavir": "3",
 "trac tabs 2x": "2",
 "tirofiban": "3",
 "trilisate": "2",
 "ticagrelor": "3",
 "treximet": "3",
 "tolectin ds": "3",
 "torisel": "3",
 "tricosal": "2",
 "tnkase": "3",
 "turmeric": "1",
 "tri-buffered aspirin": "3",
 "therapy bayer": "3",
 "talwin compound": "3",
 "temsirolimus": "3"}, "w": {"warfarin": "3"}, "v": {"vicoprofen": "3",
 "viibryd": "2",
 "vitamin e": "2",
 "vita-plus e natural": "2",
 "vilazodone": "2",
 "vimovo": "3",
 "vioxx": "2",
 "ventavis": "3",
 "voltaren-xr": "3",
 "voltaren": "3",
 "valdecoxib": "2",
 "veletri": "3",
 "venlafaxine": "2",
 "voltaren ophthalmic": "2",
 "voltaren gel": "2",
 "vanquish": "3",
 "visudyne": "2",
 "verteporfin": "2"}, "y": {"ysp aspirin": "3",
 "y-90 zevalin": "3"}, "x": {"xigris": "3",
 "xarelto": "3",
 "xiaflex": "2",
 "xibrom": "2"}, "z": {"zero-order release": "3",
 "zorprin": "3",
 "zevalin": "3",
 "zipsor": "3",
 "zoloft": "2"}}];