interactions["atovaquone,mepron"]=["atovaquone,mepron", {"a": {"avonex": "2",
 "arava": "3",
 "ari sodium iodide (i123) 1-12 mbq": "2",
 "ala-tet": "2",
 "actisite": "2",
 "avonex prefilled syringe": "2",
 "atripla": "2",
 "achromycin v": "2",
 "abacavir/lamivudine/zidovudine": "1",
 "ari sodium iodide (i123) 100-750 mbq": "2"}, "c": {"cotrim pediatric": "1",
 "clofarabine": "2",
 "cotrim": "1",
 "co-trimoxazole": "1",
 "crixivan": "2",
 "clolar": "2",
 "cotrim ds": "1",
 "combivir": "1"}, "b": {"bactrim iv": "1",
 "bactrim pediatric": "1",
 "bactrim": "1",
 "bactrim ds": "1",
 "brodspec": "2",
 "bethaprim pediatric": "1",
 "betaseron": "2",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "bethaprim": "1",
 "black cohosh": "2"}, "e": {"emtet-500": "2",
 "efavirenz": "2",
 "etoposide": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "embeda": "2",
 "extavia": "2",
 "etopophos": "2"}, "d": {"didanosine": "1",
 "depade": "2"}, "g": {"gantanol": "1"}, "f": {"folex pfs": "2"}, "i": {"isoniazid/rifampin": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "iodotope": "2",
 "isonarif": "2",
 "indinavir": "2",
 "isoniazid/pyrazinamide/rifampin": "2"}, "h": {"helidac": "2"}, "m": {"menopause support": "2",
 "metoclopramide": "2",
 "metozolv odt": "2",
 "mycobutin": "2",
 "morphine/naltrexone": "2",
 "methotrexate": "2",
 "methotrexate lpf sodium": "2",
 "maxolon": "2"}, "l": {"lamivudine/zidovudine": "1",
 "leflunomide": "3"}, "n": {"naltrexone": "2"}, "p": {"proloprim": "1",
 "primsol": "1",
 "priftin": "2",
 "pylera": "2",
 "panmycin": "2",
 "phenazopyridine/sulfamethoxazole": "1"}, "s": {"sulfatrim pediatric": "1",
 "sulfamethoxazole": "1",
 "sodium iodide i-123": "2",
 "septra": "1",
 "smz-tmp ds": "1",
 "sulfamethoxazole/trimethoprim": "1",
 "sustiva": "2",
 "sodium iodide-i-131": "2",
 "septra ds": "1",
 "septra iv": "1",
 "sumycin 250": "2",
 "sumycin": "2",
 "sulfatrim": "1"}, "r": {"reglan": "2",
 "rebif": "2",
 "rheumatrex dose pack": "2",
 "revia": "2",
 "retrovir": "1",
 "rifadin iv": "2",
 "rifater": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "rifampin": "2",
 "rifadin": "2",
 "rimactane": "2",
 "robitet 500": "2",
 "rifabutin": "2"}, "u": {"uroplus ds": "1",
 "uroplus": "1"}, "t": {"tabloid": "2",
 "tetracap": "2",
 "toposar": "2",
 "tetracon": "2",
 "trexall": "2",
 "trizivir": "1",
 "trimethoprim": "1",
 "tetracycline": "2",
 "thioguanine": "2",
 "typhoid vaccine, live": "2",
 "trimpex": "1"}, "v": {"videx": "1",
 "vepesid": "2",
 "vivotif berna vaccine": "2",
 "videx ec": "1",
 "vivotif berna": "2",
 "vivitrol": "2"}, "z": {"zidovudine": "1"}}];