interactions["azilsartan-medoxomil,edarbi"]=["azilsartan-medoxomil,edarbi", {"4": {"40 winks": "2"}, "a": {"aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "2",
 "aspirin/hydrocodone": "2",
 "anacin": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "aspir-low": "2",
 "aspergum": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aristocort": "2",
 "atrosept": "2",
 "alfenta": "2",
 "allertan": "2",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "ascriptin enteric": "2",
 "atrohist pediatric": "2",
 "acetaminophen/dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "amrix": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "advil liqui-gels": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "antispas": "2",
 "aflaxen": "2",
 "aler-dryl": "2",
 "aldactone": "3",
 "actiq": "2",
 "aspirin/oxycodone": "2",
 "apo-go pen": "2",
 "advil pm": "2",
 "ambien cr": "2",
 "aspir-mox": "2",
 "amitriptyline": "2",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "2",
 "atuss g": "2",
 "ambenyl": "2",
 "acetaminophen/hydrocodone": "2",
 "a-g tussin": "2",
 "allfen cdx": "2",
 "all day relief": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "apraclonidine ophthalmic": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "alor 5/500": "2",
 "ami-rax": "2",
 "argesic-sa": "2",
 "alka-seltzer plus flu formula": "2",
 "anacin advanced headache formula": "2",
 "addaprin": "2",
 "acetaminophen/caffeine/dihydrocodeine": "2",
 "anaflex": "2",
 "aspirin buffered": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "ambien": "2",
 "aminosyn ii with electrolytes": "3",
 "aspirin/chlorpheniramine/dextromethorphan": "2",
 "arthritis pain formula": "2",
 "azilect": "2",
 "aspirin/pravastatin": "2",
 "advil cold and sinus liqui-gels": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "alahist lq": "2",
 "aldesleukin": "2",
 "amytal sodium": "2",
 "atuss ex": "2",
 "anhydrous calcium iodide/codeine": "2",
 "acetaminophen/aspirin": "2",
 "a-hydrocort": "2",
 "accuretic": "2",
 "acetaminophen/butalbital": "2",
 "anaprox": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "alprazolam": "2",
 "acetaminophen/pamabrom/pyrilamine": "2",
 "acetaminophen/caffeine/pyrilamine": "2",
 "arthriten": "2",
 "aminosyn ii 4.25%-dextrose 25%,electrolyte,ca": "3",
 "azmacort": "2",
 "asenapine": "2",
 "aspirin/caffeine": "2",
 "aristopak": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "acetaminophen/diphenhydramine/pseudoephedrine": "2",
 "alka-seltzer extra strength": "2",
 "aminosyn ii 3.5%-dextrose 25%,electrolytes,ca": "3",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "2",
 "aliskiren/valsartan": "2",
 "advil children's allergy sinus": "2",
 "atuss hd": "2",
 "acetaminophen/aspirin/caffeine": "2",
 "aleve": "2",
 "anergan 50": "2",
 "adrenocot": "2",
 "anafranil": "2",
 "aminosyn ii 4.25%-dextrose 20%,electrolyte,ca": "3",
 "adlone-40": "2",
 "aquachloral supprettes": "2",
 "adult strength": "2",
 "aspirin/butalbital": "2",
 "arthritis pain": "2",
 "axocet": "2",
 "accupril": "2",
 "aspirin/methocarbamol": "2",
 "aliskiren/amlodipine": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "allermax": "2",
 "acthar": "2",
 "ambophen": "2",
 "anoquan": "2",
 "a-g profen": "2",
 "ativan": "2",
 "arcet": "2",
 "a-methapred": "2",
 "acetocot": "2",
 "a-tan 12x": "2",
 "alka-seltzer wake-up call!": "2",
 "aggrenox": "2",
 "alkabel-sr": "2",
 "advil allergy sinus": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "3",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "amobarbital": "2",
 "aldex-ct": "2",
 "alagesic": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "alka-seltzer original": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "aspirin/meprobamate": "2",
 "atuss hs": "2",
 "ascriptin maximum strength": "2",
 "aminosyn with electrolytes": "3",
 "amiloride": "3",
 "amigesic": "2",
 "acetylcarbromal": "2",
 "aceon": "2",
 "aristocort for injection": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "azdone": "2",
 "anexsia": "2",
 "alcohol": "2",
 "alka-seltzer lemon-lime": "2",
 "allfen cd": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "advil children's cold": "2",
 "aspirin/butalbital/caffeine": "2",
 "arthropan": "2",
 "amlodipine/benazepril": "2",
 "airacof": "2",
 "ambifed-g cdx": "2",
 "atuss hx": "2",
 "acetaminophen/dextromethorphan/diphenhydramine": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "advil migraine": "2",
 "alidrin": "2",
 "alprazolam intensol": "2",
 "abilify": "2",
 "acetaminophen/oxycodone": "2",
 "amlobenz": "2",
 "all day pain relief": "2",
 "amobarbital/secobarbital": "2",
 "ala-hist": "2",
 "angeliq": "2",
 "advil infant's concentrated drops": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "actiprofen": "2",
 "atropine/phenobarbital": "2",
 "avinza": "2",
 "acetaminophen/dichloralphenazone/isometheptene mucate": "2",
 "aspirin/codeine": "2",
 "anacin p.m. aspirin free": "2",
 "alka-seltzer plus cold formula": "2",
 "antispasmodic": "2",
 "alka-seltzer pm": "2",
 "apokyn": "2",
 "adapin": "2",
 "atamet": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "2",
 "altace": "2",
 "acetaminophen/codeine": "2",
 "acetaminophen/salicylamide": "2",
 "anacin max strength": "2",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "antiflex": "2",
 "aspirin/carisoprodol/codeine": "2",
 "allergia-c": "2",
 "acetaminophen/aspirin/phenylpropanolamine": "2",
 "ambifed cd": "2",
 "alphen expectorant": "2",
 "adlone-80": "2",
 "allerfrin with codeine": "2",
 "aspirin/calcium carbonate": "2",
 "alahist dhc": "2",
 "a-cof dh": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "amifostine": "2",
 "alcohol and dextrose injections usp hypertonic": "2",
 "atarax": "2",
 "aleve-d sinus &amp; cold": "2",
 "aplenzin": "2",
 "aspirin/dipyridamole": "2",
 "acuprin 81": "2",
 "apo-go": "2",
 "aceta w/ codeine": "2",
 "acetaminophen/phenyltoloxamine/salicylamide": "2",
 "advil junior strength": "2",
 "alfentanil": "2",
 "acetaminophen pm extra strength": "2",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "adbeon": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/pseudoephedrine": "2",
 "aldex dm": "2",
 "aspirtab": "2",
 "aspirin/pseudoephedrine": "2",
 "ambifed-g cd": "2",
 "aminosyn ii with electrolytes sulfite-free": "3",
 "anaprox-ds": "2",
 "aspiritab": "2",
 "aripiprazole": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "aspirin": "2",
 "altaryl": "2",
 "aminosyn with electrolytes sulfite-free": "3",
 "acetaminophen/pentazocine": "2",
 "ascriptin": "2",
 "aspirin/caffeine/salicylamide": "2",
 "actron": "2",
 "afinitor": "2",
 "actifed allergy day/night": "2",
 "ala-hist d": "2",
 "acetaminophen/propoxyphene": "2",
 "atuss ms": "2",
 "asendin": "2",
 "aspirin/carisoprodol": "2",
 "aliskiren": "2",
 "ambi 5/15/100": "2",
 "aspirin/phenyltoloxamine": "2",
 "arthrotec": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "2",
 "alagesic lq": "2",
 "amoxapine": "2",
 "anaplex hd": "2",
 "acthrel": "2",
 "amiloride/hydrochlorothiazide": "3",
 "advil": "2",
 "astramorph pf": "2",
 "adrenocot la": "2",
 "antrocol": "2",
 "acth": "2",
 "aspircaf": "2",
 "amidrine": "2",
 "asthmacon": "2",
 "alka-seltzer gold": "3",
 "apomorphine": "2",
 "aventyl hydrochloride": "2",
 "aspirin/diphenhydramine": "2",
 "acetylsalicylic acid": "2",
 "aspirin lite coat": "2",
 "aristospan": "2",
 "atapryl": "2",
 "aspir 81": "2",
 "amturnide": "2",
 "aldex d": "2",
 "advil cold and sinus": "2",
 "aspirin/pentazocine": "2",
 "ansaid": "2",
 "aspirin low strength": "2",
 "abstral": "2",
 "aspir-mox ib": "2",
 "alcohol 5% in dextrose 5%": "2",
 "acetaminophen/diphenhydramine": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "ala-hist ac": "2",
 "aldactazide": "3",
 "advil children's": "2",
 "adcirca": "1",
 "anabar": "2",
 "arthritis foundation pain reliever": "2",
 "americet": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "aler-tab": "2",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "2",
 "anolor 300": "2",
 "abilify discmelt": "2",
 "ambifed cdx": "2"}, "c": {"codeine/dexchlorpheniramine/phenylephrine": "2",
 "cvs extra strength headache relief": "2",
 "co-tussin": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "codiclear dh": "2",
 "chlorpheniramine/hydrocodone/phenylephrine": "2",
 "compazine": "2",
 "chloral hydrate": "2",
 "c-tanna 12d": "2",
 "colrex compound": "2",
 "capozide 50/25": "2",
 "cytra-k": "3",
 "clinoril": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "2",
 "coldcough pd": "2",
 "calcidrine": "2",
 "condasin": "2",
 "cotab ax": "2",
 "codeine/pseudoephedrine": "2",
 "codahistine expectorant": "2",
 "combiflex es": "2",
 "combunox": "2",
 "cafgesic": "2",
 "citric acid/potassium citrate/sodium citrate": "3",
 "chlorpheniramine/hydrocodone": "2",
 "childrens ibuprofen berry": "2",
 "cytra-3": "3",
 "corticotropin": "2",
 "chemdal hd plus": "2",
 "choline magnesium trisalicylate": "2",
 "capoten": "2",
 "codamine": "2",
 "cotrim": "2",
 "carbidopa/levodopa": "2",
 "corlopam": "2",
 "celecoxib": "2",
 "co-gesic": "2",
 "cortenema": "2",
 "cheracol with codeine": "2",
 "codimal dm": "2",
 "cort-k": "2",
 "codimal dh": "2",
 "cheratussin dac": "2",
 "celestone phosphate": "2",
 "cortef": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "carbex": "2",
 "clozapine": "2",
 "carbetapentane/phenylephrine/pyrilamine": "2",
 "capital w/codeine": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "cheratussin ac": "2",
 "cortrosyn": "2",
 "cocet plus": "2",
 "comfort pac with cyclobenzaprine": "2",
 "canges-xp": "2",
 "children's tylenol plus cold and allergy": "2",
 "carbacot": "2",
 "carbinoxamine/hydrocodone/phenylephrine": "2",
 "codafen": "2",
 "cabergoline": "2",
 "corzall plus": "2",
 "codeine/promethazine": "2",
 "conjugated estrogens/meprobamate": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "codafed": "2",
 "celestone": "2",
 "chlorpheniramine/guaifenesin/hydrocodone/pseudoephedrine": "2",
 "carbetapentane/diphenhydramine": "2",
 "comfort pac with naproxen": "2",
 "compazine spansule": "2",
 "codegest expectorant": "2",
 "carbidopa/entacapone/levodopa": "2",
 "cycofed pediatric expectorant": "2",
 "codal-dh syrup": "2",
 "chlordinium": "2",
 "combiflex": "2",
 "chlorphen hd": "2",
 "cortifoam": "2",
 "complete allergy": "2",
 "colrex": "2",
 "chlorpheniramine/hydrocodone/pseudoephedrine": "2",
 "clopine": "2",
 "coldcough hcm": "2",
 "compro": "2",
 "clozaril": "2",
 "chlorpheniramine/phenylephrine/pyrilamine": "2",
 "citrolith": "3",
 "counteract pm extra strength": "2",
 "chlorex-a 12": "2",
 "cap-profen": "2",
 "capacet": "2",
 "cotabflu": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "cell-u-jec": "2",
 "chlorcyclizine/codeine": "2",
 "citric acid/potassium bicarbonate": "3",
 "centussin dhc": "2",
 "children's motrin": "2",
 "cafatine pb": "2",
 "chlordiazepoxide": "2",
 "chlordiazepoxide/methscopolamine": "2",
 "cotrim ds": "2",
 "cortone acetate": "2",
 "capital with codeine suspension": "2",
 "calm-aid": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "cystex": "2",
 "carbetapentane/pyrilamine": "2",
 "cyclobenzaprine": "2",
 "co-histine dh": "2",
 "cotrim pediatric": "2",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "cycofed expectorant": "2",
 "codeine/phenylephrine": "2",
 "coryza-dm": "2",
 "clomipramine": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "cordron-hc nr": "2",
 "chlorpromazine": "2",
 "cataflam": "2",
 "codehist dh": "2",
 "capozide 25/15": "2",
 "chemdal hd": "2",
 "cortisone": "2",
 "chlorpheniramine/codeine": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "chemtussin hc": "2",
 "cena k": "3",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "codotuss": "2",
 "cymbalta": "2",
 "caldolor": "2",
 "codamine pediatric": "2",
 "canges-hc": "2",
 "clinalog": "2",
 "cyndal expectorant": "2",
 "chlorpheniramine/dihydrocodeine/pseudoephedrine": "2",
 "coldcough syrup": "2",
 "clorazepate": "2",
 "clinacort": "2",
 "cosyntropin": "2",
 "cotuss v": "2",
 "cvs allergy &amp; cold": "2",
 "corticorelin": "2",
 "capozide 50/15": "2",
 "cvs allergy &amp; sinus headache": "2",
 "codimal ph": "2",
 "cyclosporine": "2",
 "capozide 25/25": "2",
 "children's triacting night time": "2",
 "chlordiazepoxide/clidinium": "2",
 "codahistine-dh elixir": "2",
 "cyndal hd": "2",
 "covangesic": "2",
 "caffeine/magnesium salicylate": "2",
 "cotolone": "2",
 "cmt": "2",
 "codal-dm syrup": "2",
 "choline salicylate": "2",
 "clozapine synthon": "2",
 "cycofed": "2",
 "compoz nighttime sleep aid": "2",
 "chlorzoxazone": "2",
 "co-histine expectorant": "2",
 "celestone soluspan": "2",
 "codeine/phenylephrine/promethazine": "2",
 "codafed pediatric": "2",
 "cafgesic forte": "2",
 "codeprex": "2",
 "cephadyn": "2",
 "contac day and night allergy": "2",
 "captopril/hydrochlorothiazide": "2",
 "clinimix e sulfite free": "3",
 "chlormezanone": "2",
 "cocet": "2",
 "cystemms-v": "2",
 "conal": "2",
 "carisoprodol compound": "2",
 "captopril": "2",
 "comtussin hc": "2",
 "carbinoxamine/hydrocodone/pseudoephedrine": "2",
 "carisoprodol": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "contac day and night cold and flu": "2",
 "cope": "2",
 "choline salicylate/magnesium salicylate": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "3",
 "chlorgest hd": "2",
 "colocort": "2",
 "crantex hc": "2",
 "cytuss hc": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "codeine/guaifenesin": "2",
 "clobazam": "2",
 "codeine/pseudoephedrine/triprolidine": "2",
 "clonazepam": "2",
 "co-tuss v expectorant": "2",
 "codeine phosphate-promethazine hcl": "2",
 "chardonna-2": "2",
 "codituss dh": "2",
 "codituss dm": "2",
 "chemdal expectorant": "2",
 "citric acid/potassium citrate": "3",
 "clindex": "2",
 "chlorphenesin": "2",
 "capozide": "2",
 "carbetapentane/pseudoephedrine/pyrilamine": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "coricidin night time cold relief": "2",
 "canges-hc nr": "2",
 "codeine": "2",
 "cytuss-hc nr": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "coughtuss": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "cotab a": "2",
 "celebrex": "2",
 "cialis": "1",
 "cordron-hc": "2",
 "cambia": "2",
 "co-trimoxazole": "2"}, "b": {"bellaphen-s": "2",
 "benadryl-d allergy plus sinus": "2",
 "brompheniramine/hydrocodone/phenylephrine": "2",
 "butisol sodium": "2",
 "bitex liquid": "2",
 "brovex cbx": "2",
 "benahist-50": "2",
 "butorphanol": "2",
 "benaphen plus": "2",
 "bayer am": "2",
 "bufferin": "2",
 "by-ache": "2",
 "bayer pm": "2",
 "bayer aspirin extra strength plus": "2",
 "b c powder arthritis strength": "2",
 "bactrim": "2",
 "bromodiphenhydramine/codeine": "2",
 "benazepril": "2",
 "buspirone": "2",
 "brovex hc": "2",
 "bel-phen-ergot": "2",
 "bayer women's aspirin with calcium": "2",
 "buffasal": "2",
 "butabarbital": "2",
 "benadryl": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "belladonna/butabarbital": "2",
 "bayer children's aspirin": "2",
 "bc headache": "2",
 "benadryl allergy plus cold": "2",
 "brovex pb cx": "2",
 "bactrim iv": "2",
 "bromplex hd": "2",
 "b c powder": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "bayer extra strength back &amp; body": "2",
 "benadryl children's allergy and sinus": "2",
 "bydureon": "2",
 "bethaprim pediatric": "2",
 "benadryl allergy sinus": "2",
 "biotussin dac": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "buffered aspirin": "2",
 "butrans": "2",
 "byetta": "2",
 "beyaz": "2",
 "budeprion sr": "2",
 "bupivacaine/hydromorphone": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "buspar": "2",
 "benadryl allergy": "2",
 "bayer aspirin": "2",
 "balacet": "2",
 "bellaspas": "2",
 "brompheniramine/hydrocodone/pseudoephedrine": "2",
 "benadryl allergy plus sinus headache": "2",
 "betamethasone": "2",
 "bufferin arthritis strength": "2",
 "bethaprim": "2",
 "baycadron": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bellamine": "2",
 "bufferin low dose": "2",
 "bayer select backache pain formula": "2",
 "bel-tabs": "2",
 "belix": "2",
 "beldin": "2",
 "bpm pe hc": "2",
 "belladonna/opium": "2",
 "bupropion": "2",
 "benahist-10": "2",
 "bayer advanced aspirin": "2",
 "brovex cb": "2",
 "banophen": "2",
 "benylin multi-symptom": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "budeprion": "2",
 "be-flex plus": "2",
 "buprenex": "2",
 "benadryl severe allergy &amp; sinus headache": "2",
 "bayer aspirin with heart advantage": "2",
 "budesonide/formoterol": "2",
 "buffered salt": "3",
 "bromfenac": "2",
 "butex forte": "2",
 "buprenorphine/naloxone": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "3",
 "bydramine": "2",
 "brompheniramine/diphenhydramine": "2",
 "brompheniramine/codeine": "2",
 "bactrim pediatric": "2",
 "b &amp; o supprettes": "2",
 "beta-phos/ac": "2",
 "brovex pb c": "2",
 "budeprion xl": "2",
 "brompheniramine/dihydrocodeine/pseudoephedrine": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "buprenorphine": "2",
 "bayer aspirin regimen": "2",
 "banflex": "2",
 "bellergal-s": "2",
 "banaril": "2",
 "bellalphen": "2",
 "bromcomp hc": "2",
 "bellamine s": "2",
 "b-tuss": "2",
 "bellatal er": "2",
 "benadryl severe allergy plus sinus headache": "2",
 "bromph hd": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "bayer women's low dose plus calcium": "2",
 "benazepril/hydrochlorothiazide": "2",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "ben-tann": "2",
 "bupap": "2",
 "brontex": "2",
 "belcomp-pb": "2",
 "bufferin extra strength": "2",
 "bupivacaine/fentanyl": "2",
 "butalbital compound": "2",
 "bextra": "2",
 "baclofen": "2",
 "butalbital": "2",
 "buffex": "2",
 "benoject-50": "2",
 "budesonide": "2",
 "bellamor": "2",
 "benadryl children's allergy": "2",
 "bc fast pain relief": "2",
 "busodium": "2",
 "buproban": "2",
 "butibel": "2",
 "barbidonna": "2",
 "brompheniramine/codeine/pseudoephedrine": "2",
 "bellatal": "2",
 "bactrim ds": "2",
 "bucet": "2",
 "bubbli-pred": "2",
 "benadryl cold": "2"}, "e": {"efasin-hd plus": "2",
 "ecotrin maximum strength": "2",
 "eplerenone": "2",
 "effervescent pain relief": "2",
 "effer-k": "3",
 "emsam": "2",
 "endep": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "ec-naprosyn": "2",
 "endacof-ac": "2",
 "endodan": "2",
 "emagrin": "2",
 "exetuss-hc": "2",
 "excedrin menstrual complete": "2",
 "endocet": "2",
 "entaprin": "2",
 "embeda": "2",
 "exalgo": "2",
 "eperbel-s": "2",
 "elavil": "2",
 "endal hd": "2",
 "entuss-d": "2",
 "execlear-c": "2",
 "enalapril": "2",
 "ergocomp-pb": "2",
 "ed k+10": "3",
 "effervescent potassium": "3",
 "exo-tuss": "2",
 "esgic": "2",
 "ecotrin adult low strength": "2",
 "entuss": "2",
 "entuss-d liquid": "2",
 "endacof hc": "2",
 "easprin": "2",
 "extendryl hc": "2",
 "endacof xp": "2",
 "elixiral": "2",
 "excedrin migraine": "2",
 "excedrin pm": "2",
 "equitan pediatric": "2",
 "efasin-hd": "2",
 "enalapril/felodipine": "2",
 "endal expectorant": "2",
 "ecpirin": "2",
 "execlear": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "3",
 "execof": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "endal cd": "2",
 "ethanol": "2",
 "entocort ec": "2",
 "etrafon forte": "2",
 "ethyol": "2",
 "endagen-hd": "2",
 "entuss expectorant": "2",
 "e-caff p-b": "2",
 "endolor": "2",
 "esomeprazole/naproxen": "2",
 "ergocaf-pb": "2",
 "ecotrin": "2",
 "ethyl alcohol": "2",
 "effexor xr": "2",
 "endacof-dc": "2",
 "endacof-tab": "2",
 "effervescent potassium/chloride": "3",
 "endacof-dh": "2",
 "epidrin": "2",
 "exenatide": "2",
 "eldepryl": "2",
 "entuss-d jr": "2",
 "endacof-plus": "2",
 "excedrin back &amp; body": "2",
 "ed-flex": "2",
 "edluar": "2",
 "endocodone": "2",
 "excof": "2",
 "excof-sf": "2",
 "eth-oxydose": "2",
 "entercote": "2",
 "eskalith": "2",
 "efasin expectorant sf": "2",
 "eskalith-cr": "2",
 "empirin with codeine": "2",
 "echotuss-hc": "2",
 "ethchlorvynol": "2",
 "endotuss expectorant": "2",
 "everolimus": "2",
 "estazolam": "2",
 "epiklor": "3",
 "equagesic": "2",
 "ez iii": "2",
 "endotuss-hd": "2",
 "excedrin extra strength": "2",
 "enditussin expectorant": "2",
 "etrafon": "2",
 "endacof-c": "2",
 "esgic-plus": "2",
 "elixophyllin ki": "3",
 "endal-hd plus": "2",
 "equanil": "2",
 "effexor": "2",
 "extra strength bayer": "2",
 "etodolac": "2",
 "equate allergy &amp; sinus headache": "2",
 "ed-tuss hc": "2",
 "enplus-hd": "2",
 "ephedrine/potassium iodide": "3",
 "ezol": "2",
 "empirin": "2",
 "ergocaffpb": "2",
 "excedrin": "2",
 "ed-tlc": "2",
 "entex hc": "2",
 "eze ds": "2"}, "d": {"duratuss hd": "2",
 "duramorph pf": "2",
 "diazepam intensol": "2",
 "diastat": "2",
 "desyrel": "2",
 "duragesic-75": "2",
 "decohistine dh": "2",
 "drotuss-cp": "2",
 "doloral": "2",
 "duradal hd": "2",
 "de-chlor g": "2",
 "doral": "2",
 "durabac": "2",
 "dizac": "2",
 "durabac forte": "2",
 "droperidol/fentanyl": "2",
 "diphenydramine quick melt": "2",
 "duramorph": "2",
 "dezocine": "2",
 "diltiazem/enalapril": "2",
 "dep medalone 80": "2",
 "dicopanol": "2",
 "dolsed": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "dexchlorpheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "dehydrated alcohol": "2",
 "dormin": "2",
 "demi-cof": "3",
 "donatuss dc": "2",
 "donatussin max": "2",
 "diphenhydramine/guaifenesin": "2",
 "donnatal extentabs": "2",
 "dexbrompheniramine/hydrocodone/phenylephrine": "2",
 "ditussin-hc": "2",
 "diphenhydramine": "2",
 "dolgic plus": "2",
 "dihydrocodeine/guaifenesin/phenylephrine": "2",
 "dytan-dm": "2",
 "depmedalone": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "dextrose 5% and electrolyte no. 48 injection": "3",
 "doans pm": "2",
 "dazidox": "2",
 "diphenadryl": "2",
 "detuss": "2",
 "decadron with xylocaine": "2",
 "dextromethorphan/pseudoephedrine/pyrilamine": "2",
 "di-delamine": "2",
 "diacetazone": "2",
 "dolgic": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "de-chlor mr": "2",
 "dph": "2",
 "dexamethasone/lidocaine": "2",
 "dolmar": "2",
 "darvon compound 32": "2",
 "duragesic-50": "2",
 "dalalone la": "2",
 "dolacet": "2",
 "dextromethorphan/phenylephrine/pyrilamine": "2",
 "dexone": "2",
 "daypro": "2",
 "duohist dh": "2",
 "dihistine dh": "2",
 "damason-p": "2",
 "diclofenac": "2",
 "dex-tuss": "2",
 "deconsal ct": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diflunisal": "2",
 "dihistine": "2",
 "diphenhydramine/phenylephrine": "2",
 "diphenmax": "2",
 "despec-pd": "2",
 "doxepin topical": "2",
 "dexpak taperpak": "2",
 "diphenhydramine/ibuprofen": "2",
 "dexacort phosphate in turbinaire": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "deconsal dm tannate": "2",
 "diphedryl": "2",
 "diphenyl": "2",
 "dalgan": "2",
 "donnapine": "2",
 "doxepin": "2",
 "darcalma": "2",
 "dilaudid-hp": "2",
 "dynatuss hc": "2",
 "drospirenone/estradiol": "2",
 "dilaudid cough syrup": "2",
 "dolobid": "2",
 "diphen af": "2",
 "duragesic-25": "2",
 "deltasone": "2",
 "depodur": "2",
 "dihydro-pe": "2",
 "duragesic": "2",
 "duragesic-100": "2",
 "d-tann": "2",
 "dexacort-la": "2",
 "diphenhydramine/tripelennamine topical": "2",
 "dynex hd": "2",
 "de-chlor hd": "2",
 "de-chlor hc": "2",
 "dexamethasone": "2",
 "delhistine d": "2",
 "dolorex": "2",
 "diphen": "2",
 "diabetic tussin night time formula": "2",
 "duocet": "2",
 "dolophine": "2",
 "dilaudid": "2",
 "diphendryl": "2",
 "diphenylin": "2",
 "delsym children's night time cough &amp; cold": "2",
 "diphenmax d": "2",
 "dyrenium": "3",
 "dalalone dp": "2",
 "deproist with codeine": "2",
 "decohistine expectorant": "2",
 "dexasone": "2",
 "donnatal": "2",
 "doans pills extra strength": "2",
 "duo-vil": "2",
 "dolagesic": "2",
 "duradrin": "2",
 "deconamine cx": "2",
 "darvon-n": "2",
 "darpaz": "2",
 "dihistine expectorant": "2",
 "delta-cortef": "2",
 "dihydrocodeine/guaifenesin": "2",
 "d-tann at": "2",
 "dristan sinus": "2",
 "dopar": "2",
 "dytan": "2",
 "diurex": "2",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "darvon": "2",
 "dytan-hc": "2",
 "diastat acudial": "2",
 "dexbrompheniramine/phenylephrine/pyrilamine": "2",
 "detussin expectorant": "2",
 "dexasone la": "2",
 "duradyne dhc": "2",
 "duragal-s": "2",
 "duratuss ac 12": "2",
 "d-tann cd": "2",
 "detussin": "2",
 "dyazide": "3",
 "darvon compound-65": "2",
 "doan's pills": "2",
 "desipramine": "2",
 "diphentann-d": "2",
 "depoject-80": "2",
 "decadron phosphate, injectable": "2",
 "disalcid": "2",
 "desyrel dividose": "2",
 "depo-medrol": "2",
 "dihydro-gp": "2",
 "decadron": "2",
 "dihydrocodeine/guaifenesin/pseudoephedrine": "2",
 "d-tal": "2",
 "de-sone la": "2",
 "duragesic-12": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "d-tann hc": "2",
 "dytan-d": "2",
 "dexmedetomidine": "2",
 "dexacort phosphate in respihaler": "2",
 "dewitt's pain reliever": "2",
 "dicomal-ph": "2",
 "dihydro-cp": "2",
 "delhist d": "2",
 "deconsal c expectorant": "2",
 "denzapine": "2",
 "depopred": "2",
 "d-tann dm": "2",
 "decotuss-hd": "2",
 "drospirenone/ethinyl estradiol": "2",
 "duexis": "2",
 "donatussin dc": "2",
 "duralone": "2",
 "dexamethasone intensol": "2",
 "diastat pediatric": "2",
 "darvocet-n 100": "2",
 "decadron-la": "2",
 "dytuss": "2",
 "deconsal ct tannate": "2",
 "dexbrompheniramine/pyrilamine": "2",
 "d-tann ct": "2",
 "diphenhist": "2",
 "dytan-at": "2",
 "dexchlorpheniramine/hydrocodone/phenylephrine": "2",
 "dexacorten": "2",
 "dexacen-4": "2",
 "dostinex": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "2",
 "drituss hd": "2",
 "duraxin": "2",
 "diabetic tussin c": "2",
 "dicomal-dh": "2",
 "darvocet-n 50": "2",
 "dalmane": "2",
 "decaject la": "2",
 "duract": "2",
 "diazepam": "2",
 "duraganidin nr": "2",
 "deconsal dm": "2",
 "doloral sirop": "2",
 "dolgic lq": "2",
 "donnaphen": "2",
 "diphen cough": "2",
 "dexone la": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "de-chlor nx": "2",
 "duloxetine": "2",
 "dalalone": "2",
 "diphenhydramine/pseudoephedrine": "2",
 "demerol": "2",
 "dihydrocodeine/phenylephrine": "2",
 "dihistine expectorant with codeine": "2",
 "dytan-cd": "2",
 "diclofenac/misoprostol": "2",
 "desvenlafaxine": "2",
 "disposable enema": "3",
 "dytan-cs": "2",
 "darvocet a500": "2",
 "drocon-cs": "2",
 "dextrose 10% and electrolyte no 48": "3",
 "decaject": "2"}, "g": {"guaifenesin/hydrocodone": "2",
 "genahist": "2",
 "glu-k": "3",
 "gua hc": "2",
 "guaifenesin/phenylephrine/pyrilamine": "2",
 "guaifen-c": "2",
 "goody's extra-strength headache powders": "2",
 "gen-k": "3",
 "genpril": "2",
 "genprin": "2",
 "gablofen": "2",
 "genace": "2",
 "guaifenesin/hydrocodone/pseudoephedrine": "2",
 "guaitussin ac": "2",
 "guaifen ac": "2",
 "genapap pm": "2",
 "guiatuss dac": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylephrine/phenylpropanolamine": "2",
 "gengraf": "2",
 "garlic oil": "1",
 "guiatussin with codeine": "2",
 "goody's body pain": "2",
 "guaifenesin/hydrocodone/phenylephrine": "2",
 "geone": "2",
 "g-1": "2",
 "guiaplex hc": "2",
 "gennin-fc": "2",
 "gianvi": "2",
 "goodys headache powders": "2",
 "guai-co": "2",
 "gani-tuss nr": "2",
 "guiatuss ac": "2",
 "gua pc": "2",
 "gestuss-hc": "2",
 "giltuss ped-c": "2",
 "garlic": "1",
 "gentex hc": "2",
 "glydeine": "2",
 "genasan": "2",
 "guaifenesin dac liquid": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylpropanolamine/pyrilamine": "2",
 "genacote": "2",
 "geodon": "2",
 "g-tuss": "2",
 "gelhist pediatric": "2",
 "goodys extra strength": "2",
 "guaiatussin ac": "2",
 "guaifen dac": "2",
 "guiatussin dac": "2",
 "guaiatussin dac": "2",
 "guaifenesin/hydromorphone": "2",
 "guiaphen hd": "2"}, "f": {"fenoldopam": "2",
 "fiortal": "2",
 "fentanyl/ropivacaine": "2",
 "fiorinal with codeine iii": "2",
 "flexeril": "2",
 "furazolidone": "2",
 "fluphenazine": "2",
 "fleet ez-prep": "3",
 "fazaclo": "2",
 "fiorinal with codeine": "2",
 "fleet phospho soda": "3",
 "fortabs": "2",
 "fentuss expectorant": "2",
 "flurazepam": "2",
 "fanapt": "2",
 "fioricet with codeine": "2",
 "flutuss hc": "2",
 "fasprin": "2",
 "fentanyl": "2",
 "femcet": "2",
 "fosinopril": "2",
 "feldene": "2",
 "fleet enema": "3",
 "florinef": "2",
 "fiorinal": "2",
 "forfivo xl": "2",
 "fiortal with codeine": "2",
 "famotidine/ibuprofen": "2",
 "fentora": "2",
 "flo-pred": "2",
 "fenoprofen": "2",
 "flexon": "2",
 "fluoxetine/olanzapine": "2",
 "flexoject": "2",
 "fleet prep kit 1": "3",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "flurbiprofen": "2",
 "fludrocortisone": "2",
 "fexmid": "2",
 "florinef acetate": "2",
 "fleet enema extra": "3",
 "frenadol": "2",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiormor": "2",
 "fentanyl transdermal system": "2",
 "farbital": "2",
 "furoxone": "2",
 "freamine iii with electrolytes": "3",
 "fosinopril/hydrochlorothiazide": "2",
 "fiorpap": "2"}, "i": {"isolyte p and 5% dextrose": "3",
 "ionsys": "2",
 "iosat": "3",
 "ibuprofen": "2",
 "iophen-c nr": "2",
 "ibuprofen pmr": "2",
 "iodine/potassium iodide": "3",
 "iohist d": "2",
 "isolyte m and 5% dextrose": "3",
 "ibuprofen/oxycodone": "2",
 "isolyte e": "3",
 "iso-acetazone": "2",
 "isocom": "2",
 "ionosol b and 5% dextrose": "3",
 "isocet": "2",
 "imipramine": "2",
 "iloprost": "2",
 "invega": "2",
 "ibudone": "2",
 "ibuprofen/pseudoephedrine": "2",
 "idenal": "2",
 "intermezzo": "2",
 "isocarboxazid": "2",
 "indocin iv": "2",
 "innovar": "2",
 "iopidine": "2",
 "ibu-200": "2",
 "inspra": "2",
 "indocin": "2",
 "ide-cet": "2",
 "ionosol mb and 5% dextrose": "3",
 "isolyte r and 5% dextrose": "3",
 "infumorph": "2",
 "iloperidone": "2",
 "iotussin d liquid": "2",
 "iotussin hc": "2",
 "indocin sr": "2",
 "iophen": "2",
 "ionosol t and 5% dextrose": "3",
 "invega sustenna": "2",
 "ibu": "2",
 "isolyte h and 5 % dextrose": "3",
 "ibu-tab": "2",
 "ibu-4": "2",
 "ibu-6": "2",
 "ibu-8": "2",
 "iodal hd": "2",
 "indomethacin": "2",
 "ida": "2"}, "h": {"hydeltrasol": "2",
 "hyophen": "2",
 "histex hc": "2",
 "hydrotussin hd": "2",
 "hycodan": "2",
 "headache formula pm": "2",
 "hydro-tussin exp": "2",
 "histinex hc": "2",
 "hycoclar tuss": "2",
 "hydrocodone hd": "2",
 "hydrochlorothiazide/spironolactone": "3",
 "hydromide": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "hydex pd": "2",
 "hydrocodone/ibuprofen": "2",
 "hydrocodone/phenylephrine/pyrilamine": "2",
 "hyosophen": "2",
 "hydrocodone/phenylephrine": "2",
 "hydrostat ir": "2",
 "hydrophed": "2",
 "hydrocodone gf": "2",
 "headache relief pm": "2",
 "hydrocodone/potassium guaiacolsulfonate": "2",
 "histine-d": "2",
 "histussin hc liquid": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "hydrotuss hc": "2",
 "hydrocodone/pseudoephedrine/triprolidine": "2",
 "hy-kxp": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydramine cough syrup": "2",
 "hydrocof-hc": "2",
 "homatropine/hydrocodone": "2",
 "hydron ex": "2",
 "hyoscyamine/phenobarbital": "2",
 "hydron pcs": "2",
 "hydro-tuss xp": "2",
 "histalet forte": "2",
 "hydrochlorothiazide/triamterene": "3",
 "hytussin expectorant": "2",
 "hydrocortisone": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hexadrol": "2",
 "hycosin expectorant": "2",
 "hydrochlorothiazide/moexipril": "2",
 "h-c tussive-nr": "2",
 "histinex d": "2",
 "halflytely and bisacodyl": "3",
 "hycophen pediatric": "2",
 "hydrocod-gf": "2",
 "hycomal dh": "2",
 "hycophen": "2",
 "hydrocodone/pseudoephedrine": "2",
 "hydromet": "2",
 "hydrotuss": "2",
 "hydro-tussin hg": "2",
 "hycomine compound": "2",
 "hydroxy compound": "2",
 "hydromorph contin": "2",
 "hi-tuss hc": "2",
 "histinex pv": "2",
 "hyrexin": "2",
 "hydro gp": "2",
 "hydro-pc ii": "2",
 "hydrocodone pa pediatric": "2",
 "hycomine": "2",
 "hycotuss expectorant": "2",
 "hytussin": "2",
 "haldol": "2",
 "hydrogesic": "2",
 "hyphed": "2",
 "halotussin dac": "2",
 "histussin d": "2",
 "hydrofed": "2",
 "halcion": "2",
 "hydron kgs": "2",
 "hydrocodone cp": "2",
 "hydropane": "2",
 "hyphen-hd": "2",
 "haldol decanoate": "2",
 "hydrotropine": "2",
 "hydrocet": "2",
 "haltran": "2",
 "h-c tussive": "2",
 "halotussin ac": "2",
 "h.p. acthar gel": "2",
 "hy-phen": "2",
 "halfprin": "2",
 "histatan": "2",
 "hydrophene dh": "2",
 "hydro-pc ii plus": "2",
 "hydron cp": "2",
 "heartline": "2",
 "hydro-dp": "2",
 "hydrocodone/phenylpropanolamine": "2",
 "hycet": "2",
 "haloperidol": "2",
 "hydrocodone": "2",
 "hydromorphone": "2",
 "hydrocortone phosphate": "2",
 "hydramine compound": "2",
 "highland hc": "2",
 "hyzine": "2",
 "h-c tussive d": "2",
 "hexatussin": "2",
 "hycomine pediatric": "2",
 "hycoclear": "2",
 "hypamine": "2",
 "hydrocodone/potassium guaiacolsulfonate/pseudoephedrine": "2",
 "hydeltra-tba": "2",
 "hyco-dh": "2",
 "hydroxyzine": "2",
 "hydro-tussin dhc": "2",
 "haponal": "2",
 "hydrocortone": "2",
 "histussin hc syrup": "2",
 "hytan": "2",
 "hydramine": "2",
 "hydrocodone/pheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "2",
 "halazepam": "2"}, "k": {"klotrix": "3",
 "kadian": "2",
 "kaon-ci": "3",
 "k-phos original": "3",
 "kenalog-10": "2",
 "kg-tuss hd": "2",
 "klonopin": "2",
 "klor-con m15": "3",
 "ken-jec 40": "2",
 "k-dur 10": "3",
 "k+care et": "3",
 "k + potassium": "3",
 "kato": "3",
 "kneerelief": "2",
 "kg-fed": "2",
 "klor-con/25": "3",
 "key-pred": "2",
 "klor-con": "3",
 "klor-con 8": "3",
 "kaon-cl 10": "3",
 "k-lyte/cl": "3",
 "k-phos m.f.": "3",
 "k-phos no. 2": "3",
 "k-lor": "3",
 "kal potassium 99": "3",
 "k-tab": "3",
 "k-lyte/cl 50": "3",
 "k-effervescent": "3",
 "k-sol": "3",
 "k-tan": "2",
 "klor-con/ef": "3",
 "kay ciel": "3",
 "kenaject-40": "2",
 "kemstro": "2",
 "k-8": "3",
 "kaochlor s-f": "3",
 "kg-dal hd plus": "2",
 "k-lyte ds": "3",
 "k-lyte": "3",
 "kaon": "3",
 "k-dur": "3",
 "kaochlor": "3",
 "kenalog-40": "2",
 "key-pred sp": "2",
 "kgs-hc": "2",
 "k-dur 20": "3",
 "kaon-cl 20%": "3",
 "kg-fed pediatric expectorant": "2",
 "klor-con m20": "3",
 "k-vescent": "3",
 "kcl": "3",
 "klonopin wafer": "2",
 "kwelcof": "2",
 "kg-fed expectorant": "2",
 "kie": "3",
 "ketorolac": "2",
 "kg-tussin": "2",
 "k-norm": "3",
 "ketoprofen": "2",
 "k-10": "3",
 "kg-hist d": "2",
 "k-lyte/cl 25": "3",
 "k-tan 4": "2",
 "klor-con 10": "3",
 "klor-con m10": "3",
 "k-phos neutral": "3",
 "kg-dal hd": "2"}, "j": {"j-max dhc": "2",
 "j-cof dhc": "2",
 "jaycof-hc": "2",
 "jumex": "2",
 "j-tan d hc": "2"}, "m": {"m-end wc": "2",
 "morphine sulfate er": "2",
 "myolin": "2",
 "marthritic": "2",
 "maxifed cdx": "2",
 "mintuss nx": "2",
 "myci spray": "2",
 "m-oxy": "2",
 "medrol dosepak": "2",
 "miles nervine": "2",
 "magsal": "2",
 "motrin sinus headache": "2",
 "mhp-a": "2",
 "myphetane dc": "2",
 "midazolam": "2",
 "maolate": "2",
 "magnacet": "2",
 "methacort 40": "2",
 "migracet-pb": "2",
 "medique pain-off": "2",
 "midol extended relief": "2",
 "m-phen": "2",
 "morphine lp epidural": "2",
 "mephobarbital": "2",
 "myhist-dm": "2",
 "moduretic": "3",
 "millipred dp": "2",
 "maprotiline": "2",
 "motrin junior strength": "2",
 "mar-cof bp": "2",
 "methylcotolone": "2",
 "milnacipran": "2",
 "morphine liposomal": "2",
 "motrin infant drops": "2",
 "monopril": "2",
 "m-clear": "2",
 "methacort 80": "2",
 "motrin childrens cold": "2",
 "medicort": "2",
 "magan": "2",
 "migrin-a": "2",
 "mobic": "2",
 "myogesic": "2",
 "midol maximum strength cramp formula": "2",
 "methylcotol": "2",
 "morphine/naltrexone": "2",
 "motrin": "2",
 "metahistine d": "2",
 "mitran": "2",
 "midol pm": "2",
 "migralex": "2",
 "motrin pm": "2",
 "multihistamine-d": "2",
 "methylprednisolone": "2",
 "minitabs": "2",
 "midol traditional": "2",
 "ms/s": "2",
 "marplan": "2",
 "millipred": "2",
 "molindone": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "2",
 "medralone 40": "2",
 "med-jec-40": "2",
 "mefenamic acid": "2",
 "msir": "2",
 "maxifed-g cdx": "2",
 "medrol": "2",
 "midamor": "3",
 "maxi-tuss hcg": "2",
 "monte-g hc": "2",
 "marcof expectorant": "2",
 "mag-phen": "2",
 "meperitab": "2",
 "mudrane": "3",
 "midol ib": "2",
 "midol pms": "2",
 "micro-k 10": "3",
 "medent c": "2",
 "methadose": "2",
 "medique medi-seltzer": "2",
 "metaxalone": "2",
 "mono-gesic": "2",
 "max hc": "2",
 "methylpred dp": "2",
 "minotal": "2",
 "magnesium salicylate": "2",
 "mirtazapine": "2",
 "motrin ib": "2",
 "motrin ib sinus": "2",
 "mio-rel": "2",
 "meperidine": "2",
 "mst": "2",
 "morphine sulfate ir": "2",
 "maxi-tuss sa": "2",
 "mygracet": "2",
 "maxifed cd": "2",
 "ms contin": "2",
 "margesic": "2",
 "mobigesic": "2",
 "medidex la": "2",
 "mapap pm": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "morphine rapi-ject": "2",
 "maxiflu cd": "2",
 "mintuss mr": "2",
 "maraviroc": "2",
 "maxiphen cd": "2",
 "maxifed-g cd": "2",
 "mellaril-s": "2",
 "mintex hc": "2",
 "medtuss hd": "2",
 "mitride": "2",
 "micrainin": "2",
 "meclofenamate": "2",
 "myhist-pd": "2",
 "meloxicam": "2",
 "methadone diskets": "2",
 "mintuss ms": "2",
 "mepergan": "2",
 "migrazone": "2",
 "medigesic": "2",
 "mytussin ac": "2",
 "midchlor": "2",
 "meprozine": "2",
 "mebaral": "2",
 "menstrual complete": "2",
 "migratine": "2",
 "matulane": "2",
 "morphitec": "2",
 "m-clear wc": "2",
 "methenamine/sodium biphosphate": "3",
 "moduretic 5-50": "3",
 "maxi-tuss hcx": "2",
 "maxzide-25": "3",
 "migquin": "2",
 "maxiflu cdx": "2",
 "methocarbamol": "2",
 "medi-seltzer": "2",
 "menstrual pms": "2",
 "momentum": "2",
 "magnaprin": "2",
 "m-end pe": "2",
 "micomp-pb": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "migrapap": "2",
 "maxi-tuss hc": "2",
 "mb-tab": "2",
 "methotrimeprazine": "2",
 "maxiphen cdx": "2",
 "medralone": "2",
 "medipred": "2",
 "m-prednisolone": "2",
 "mudrane gg": "2",
 "medralone 80": "2",
 "margesic h": "2",
 "midol pms maximum strength": "2",
 "meperidine/promethazine": "2",
 "morphine sulfate sr": "2",
 "maxzide": "3",
 "mobidin": "2",
 "medcodin": "2",
 "midrin": "2",
 "marten-tab": "2",
 "meticorten": "2",
 "monopril hct": "2",
 "m-eslon": "2",
 "monteflu hc": "2",
 "mytussin dac": "2",
 "mavik": "2",
 "methdilazine": "2",
 "motrin migraine pain": "2",
 "marax df": "2",
 "migrex": "2",
 "mepergan fortis": "2",
 "maxidone": "2",
 "midol maximum strength menstrual": "2",
 "mintuss g": "2",
 "m-end": "2",
 "marax": "2",
 "mellaril": "2",
 "motrin childrens": "2",
 "morphine": "2",
 "medidex": "2",
 "moban": "2",
 "multihistamine-d ped": "2",
 "menadol": "2",
 "meclomen": "2",
 "msp-blu": "2",
 "methylprednisolone dose pack": "2",
 "moexipril": "2",
 "methadone": "2",
 "miltown": "2",
 "motrin cold and flu": "2",
 "mesoridazine": "2",
 "micro-k": "3",
 "m o s": "2",
 "meprobamate": "2"}, "l": {"litecoat aspirin": "2",
 "lortab asa": "2",
 "lugol's": "3",
 "lvp solution with potassium": "3",
 "luminal": "2",
 "liquitussin hc syrup": "2",
 "lodine": "2",
 "lotrel": "2",
 "lufyllin-epg": "2",
 "lodine xl": "2",
 "low dose asa": "2",
 "lortab 5/500": "2",
 "lortab 7.5/500": "2",
 "ludiomil": "2",
 "lyrica": "2",
 "lorcet 10/650": "2",
 "lortab": "2",
 "loxitane c": "2",
 "levacet": "2",
 "larodopa": "2",
 "lortab 2.5/500": "2",
 "liqui-minic infant": "2",
 "levsin with phenobarbital": "2",
 "lioresal intrathecal": "2",
 "leader naproxen sodium": "2",
 "lorcet plus": "2",
 "liquid pred": "2",
 "levo-dromoran": "2",
 "lithonate": "2",
 "licorice": "2",
 "liquituss hd": "2",
 "levall 5.0": "2",
 "liquicough hc": "2",
 "lisinopril": "2",
 "lurasidone": "2",
 "lobac": "2",
 "limbitrol": "2",
 "lotensin hct": "2",
 "lotensin": "2",
 "librium": "2",
 "loxitane": "2",
 "lorazepam": "2",
 "lorazepam intensol": "2",
 "liquicet": "2",
 "lorcet hd": "2",
 "lazanda": "2",
 "loryna": "2",
 "lioresal": "2",
 "linezolid": "2",
 "largon": "2",
 "lorzone": "2",
 "lithotabs": "2",
 "limbitrol ds": "2",
 "librax": "2",
 "lansoprazole/naproxen": "2",
 "liquihistine cs": "2",
 "loxitane im": "2",
 "lortab 10/500": "2",
 "lithium": "2",
 "legatrin pm": "2",
 "levorphanol": "2",
 "lithobid": "2",
 "lexxel": "2",
 "levodopa": "2",
 "lortuss hc": "2",
 "laniroif": "2",
 "loxapine": "2",
 "liqui-histine-d": "2",
 "levomethadyl acetate": "2",
 "lexuss 210 liquid": "2",
 "levoprome": "2",
 "latuda": "2"}, "o": {"onfi": "2",
 "orasone": "2",
 "orphengesic forte": "2",
 "ormazine": "2",
 "orphengesic": "2",
 "orudis kt": "2",
 "oxazepam": "2",
 "oxycodone": "2",
 "oxecta": "2",
 "opana": "2",
 "orudis": "2",
 "oxyir": "2",
 "oxaprozin": "2",
 "orbivan": "2",
 "onsolis": "2",
 "oxydose": "2",
 "osmoprep": "3",
 "orfro": "2",
 "opium tincture, deodorized": "2",
 "ocella": "2",
 "orphenadrine": "2",
 "oms": "2",
 "oxycontin": "2",
 "oruvail": "2",
 "orphenate": "2",
 "orapred": "2",
 "oxyfast": "2",
 "opana er": "2",
 "oleptro": "2",
 "opium": "2",
 "oramorph sr": "2",
 "orlaam": "2",
 "oxycet": "2",
 "oxymorphone": "2",
 "orapred odt": "2",
 "opium deodorized": "2",
 "olanzapine": "2"}, "n": {"nervine": "2",
 "night time pain": "2",
 "naldecon-cx adult": "2",
 "nalex ac": "2",
 "notuss pd": "2",
 "nalex expectorant": "2",
 "nortriptyline": "2",
 "norwich aspirin": "2",
 "nalfon": "2",
 "norflex": "2",
 "niravam": "2",
 "nytol": "2",
 "naprosyn": "2",
 "numorphan": "2",
 "naproxen/sumatriptan": "2",
 "notuss-nxd": "2",
 "nonbac": "2",
 "narvox": "2",
 "notuss-dc": "2",
 "nasotuss": "2",
 "notuss-forte": "2",
 "notuss-ac": "2",
 "nazarin hc": "2",
 "notuss-pe": "2",
 "norgesic forte": "2",
 "nexcede": "2",
 "novahistine expectorant": "2",
 "nuprin": "2",
 "norgesic": "2",
 "numorphan hcl": "2",
 "nardil": "2",
 "nucodine": "2",
 "novagest with codeine": "2",
 "nu-med": "2",
 "naproxen": "2",
 "nalbuphine": "2",
 "naprelan": "2",
 "nucodine expectorant": "2",
 "nucochem": "2",
 "nucofed expectorant": "2",
 "nightime sleepaid": "2",
 "nabumetone": "2",
 "neoral": "2",
 "novahistine dh": "2",
 "neutra-phos-k": "3",
 "nuprin backache caplet": "2",
 "novasus": "2",
 "novadyne dh": "2",
 "navane": "2",
 "nuco-tuss expectorant": "2",
 "norpramin": "2",
 "nucodine pediatric": "2",
 "neo hc": "2",
 "nuco-tuss pediatric expectorant": "2",
 "norflex injectable": "2",
 "narcof": "2",
 "nembutal sodium": "2",
 "novadyne expectorant": "2",
 "nembutal": "2",
 "nasatuss": "2",
 "neutra-phos": "3",
 "notuss-nx": "2",
 "nucofed": "2",
 "nytol caplet": "2",
 "nalex-dh": "2",
 "normosol-m and 5% dextrose": "3",
 "naloxone/pentazocine": "2",
 "notuss": "2",
 "neo ac": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "nefazodone": "2",
 "nucofed pediatric expectorant": "2",
 "naproxen sodium ds": "2",
 "naproxen/pseudoephedrine": "2",
 "norco": "2",
 "novasal": "2",
 "nalex a 12": "2",
 "neoprofen": "2",
 "nariz hc": "2",
 "nubain": "2"}, "q": {"quenalin": "2",
 "quick-k": "3",
 "quinapril": "2",
 "quindal hd plus": "2",
 "quinaretic": "2",
 "q-dryl": "2",
 "quadra-hist d pediatric": "2",
 "qual-tussin dc": "2",
 "quadra-hist d": "2",
 "quindal hd": "2",
 "quazepam": "2",
 "quetiapine": "2",
 "q-profen": "2",
 "q-v tussin": "2",
 "quadrinal": "3",
 "q-dryl a/f": "2",
 "quadrapax": "2"}, "p": {"pyridium plus": "2",
 "phosphasal": "2",
 "pyril mal phenyl hcl": "2",
 "predicort-50": "2",
 "poly-tussin ac": "2",
 "phrenilin forte": "2",
 "prudoxin": "2",
 "poly-histine cs": "2",
 "pamprin all day relief": "2",
 "panritis forte": "2",
 "predacort 50": "2",
 "phendal-hd": "2",
 "pentazocine": "2",
 "prevacid naprapac 375": "2",
 "pyrelle hb": "2",
 "potassium phosphate/sodium phosphate": "3",
 "potassium citrate": "3",
 "potassium chloride/sodium chloride": "3",
 "pedituss": "3",
 "potassium iodide": "3",
 "paral": "2",
 "pseudatex hc": "2",
 "pharmagesic": "2",
 "phenhist expectorant": "2",
 "pancof hc": "2",
 "pulmicort nebuamp": "2",
 "predcor": "2",
 "promethazine vc": "2",
 "paxipam": "2",
 "prednisolone": "2",
 "pred-ject-50": "2",
 "phenylhistine expectorant": "2",
 "phenaphen with codeine": "2",
 "prednicot": "2",
 "pardryl": "2",
 "prolixin": "2",
 "promethazine with dm": "2",
 "pancof xp": "2",
 "precedex": "2",
 "prevacid naprapac 500": "2",
 "prohistine-d": "2",
 "prevacid naprapac": "2",
 "phospha 250 neutral": "3",
 "phenadoz": "2",
 "phenflu cd": "2",
 "potassium acetate": "3",
 "prelone": "2",
 "procarbazine": "2",
 "proloprim": "2",
 "poly tan dm": "2",
 "phenoject-50": "2",
 "paraflex": "2",
 "prochlorperazine": "2",
 "potassium phosphate": "3",
 "pima": "3",
 "polycitra-k": "3",
 "parenteral nutrition solution w/electrolytes": "3",
 "phenylephrine/promethazine": "2",
 "predate-50": "2",
 "promethazine with codeine": "2",
 "promethazine vc plain": "2",
 "polycitra": "3",
 "phenazine 50": "2",
 "prednicen-m": "2",
 "pentobarbital": "2",
 "primsol": "2",
 "permitil": "2",
 "prosed ds": "2",
 "pediacare children's allergy": "2",
 "prolixin enanthate": "2",
 "parnate": "2",
 "p-v-tussin": "2",
 "percodan": "2",
 "poly-tussin xp": "2",
 "phosphate laxative": "3",
 "premesyn pms": "2",
 "pediacof": "3",
 "potassium bicarbonate/potassium chloride": "3",
 "paliperidone": "2",
 "pb-hyos": "2",
 "parafon forte dsc": "2",
 "prominol": "2",
 "phrenilin with caffeine and codeine": "2",
 "protuss": "2",
 "phendacof plus": "2",
 "predicort rp": "2",
 "percogesic extra strength": "2",
 "primethasone": "2",
 "poly hist dhc": "2",
 "polytine cs": "2",
 "percocet 10/325": "2",
 "poly hist hc": "2",
 "pamprin cramp menstrual pain relief": "2",
 "poly tussin ex": "2",
 "pc-10": "3",
 "pediatex-ct": "2",
 "promethazine hcl with codeine": "2",
 "percodan-demi": "2",
 "promethazine vc with codeine": "2",
 "promacet": "2",
 "poly cs": "2",
 "pristiq": "2",
 "potassium bicarbonate/potassium citrate": "3",
 "pedia-lax enema": "3",
 "protriptyline": "2",
 "potassium bicarbonate/sodium bicarbonate": "3",
 "percocet 2.5/325": "2",
 "phosenamine": "2",
 "pyrilamine": "2",
 "poly-tussin hd": "2",
 "poly hist pd": "2",
 "pyrlex pd": "2",
 "poly-tussin dhc": "2",
 "pancof": "2",
 "pseudodine c": "2",
 "propiomazine": "2",
 "poly-histine": "2",
 "pseudoephedrine/pyrilamine": "2",
 "percolone": "2",
 "phenaz plus": "2",
 "phenelzine": "2",
 "phena-s 12": "2",
 "pneumotussin 2.5": "2",
 "primlev": "2",
 "prosom": "2",
 "p-a-c analgesic": "2",
 "p-v-tussin syrup": "2",
 "procof": "2",
 "pheniramine/phenyltoloxamine/pyrilamine": "2",
 "pro-med": "2",
 "potassium iodide/theophylline": "3",
 "phena-s": "2",
 "procalamine": "3",
 "p-hist": "2",
 "poly-tussin ex syrup": "2",
 "pyrichlor pe": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "paraldehyde": "2",
 "polytine d": "2",
 "potassium chloride": "3",
 "pancof-pd": "2",
 "phenylhistine dh expectorant": "2",
 "parcopa": "2",
 "potassium bicarbonate": "3",
 "poly hist forte": "2",
 "pyril d": "2",
 "percocet 5/325": "2",
 "pacaps": "2",
 "pms relief": "2",
 "phenflu cdx": "2",
 "panacet": "2",
 "pc-cap": "2",
 "placidyl": "2",
 "prinivil": "2",
 "percocet 10/650": "2",
 "p-a-c": "2",
 "pp-cap": "2",
 "predaject-50": "2",
 "phenazoforte plus": "2",
 "pulmicort turbuhaler": "2",
 "polycitra-lc": "3",
 "ponstel": "2",
 "piroxicam": "2",
 "prinzide": "2",
 "pyrlex": "2",
 "pain relief pm extra strength": "2",
 "pamelor": "2",
 "pediacare children's allergy &amp; cold": "2",
 "phenylephrine/pyrilamine": "2",
 "paregoric": "2",
 "perindopril": "2",
 "pancof exp": "2",
 "pyril tann-12": "2",
 "percocet 7.5/325": "2",
 "phenobarbital": "2",
 "promazine": "2",
 "phrenilin": "2",
 "poly tan": "2",
 "pediatex hc": "2",
 "pregabalin": "2",
 "predalone 50": "2",
 "potassium acid phosphate": "3",
 "primalev": "2",
 "procot": "2",
 "potassium chloride in sodium chloride": "3",
 "percocet": "2",
 "phenylbutazone": "2",
 "potassium acetate/potassium bicarbonate/potassium citrate": "3",
 "promethazine dm": "2",
 "phenergan": "2",
 "panasal 5/500": "2",
 "pediapred": "2",
 "propoxyphene": "2",
 "propatuss expectorant": "2",
 "predacorten": "2",
 "palladone": "2",
 "pmb": "2",
 "phenergan fortis": "2",
 "poly-histine-d": "2",
 "phos-nak": "3",
 "panlor dc": "2",
 "pyril dm": "2",
 "procof d": "2",
 "poly-tussin": "2",
 "pharbedryl": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "pheniramine/phenylpropanolamine/pyrilamine": "2",
 "prohist": "2",
 "pain reliever pm": "2",
 "prosed ec": "2",
 "pro-clear": "2",
 "potassium citrate/sodium citrate": "3",
 "perloxx": "2",
 "panlor ss": "2",
 "pamprin maximum pain": "2",
 "poly hist dm": "2",
 "promethazine with dextromethorphan": "2",
 "potassium gluconate": "3",
 "pneumotussin hc": "2",
 "proleukin": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenergan vc": "2",
 "painaid": "2",
 "pro-red ac": "2",
 "phenylhistine dh": "2",
 "pheniramine/phenylpropanolamine/phenyltoloxamine/pyrilamine": "2",
 "prednisone": "2",
 "plasma-lyte 56": "3",
 "poly tan d": "2",
 "propoxyphene compound 65": "2",
 "prolixin decanoate": "2",
 "protuss-d": "2",
 "pharbetol pm": "2",
 "paxarel": "2",
 "pulmicort flexhaler": "2",
 "prolex dh": "2",
 "phena-plus": "2",
 "pyrlex cb": "2",
 "percocet 7.5/500": "2",
 "poly-d": "2",
 "pamprin multi-symptom menstrual relief": "2",
 "pheniramine/phenyltoloxamine/pseudoephedrine/pyrilamine": "2",
 "phenylephrine hd": "2",
 "pri-cortin 50": "2",
 "pamprin max menstrual pain relief": "2",
 "percogesic original strength": "2",
 "pravigard pac": "2",
 "phenergan with dextromethorphan": "2",
 "plasma-lyte and 5% dextrose": "3",
 "perphenazine": "2",
 "pulmicort respules": "2",
 "promethegan": "2",
 "poly-citra k crystals": "3",
 "polyhist nc": "2",
 "pneumotussin": "2",
 "promethazine vc w/codeine": "2"}, "s": {"su-tuss hd elixir": "2",
 "skelaxin": "2",
 "saleto": "2",
 "solurex": "2",
 "stalevo 150": "2",
 "sleep": "2",
 "selgene": "2",
 "sirolimus": "2",
 "slow-k": "3",
 "septra": "2",
 "saleto-800": "2",
 "subutex": "2",
 "selegiline": "2",
 "sloprin": "2",
 "septra iv": "2",
 "snooze fast": "2",
 "sinemet cr": "2",
 "sulfamethoxazole/trimethoprim": "2",
 "strong iodine": "3",
 "sulfatrim": "2",
 "st. joseph aspirin": "2",
 "synalgos-dc": "2",
 "sleep tab ii": "2",
 "sski": "3",
 "sonata": "2",
 "subsys": "2",
 "symtan a": "2",
 "symtan": "2",
 "stelazine": "2",
 "scot-tussin original": "2",
 "serentil": "2",
 "sudafed 12 hour pressure+pain": "2",
 "sinemet": "2",
 "selestoject": "2",
 "stanback fast pain relief": "2",
 "somnote": "2",
 "saleto-400": "2",
 "siladryl": "2",
 "savella": "2",
 "sandimmune": "2",
 "soma": "2",
 "suttar-2": "2",
 "sudafed pe severe cold": "2",
 "solu-cortef": "2",
 "salsalate": "2",
 "samsca": "2",
 "serzone": "2",
 "sulindac": "2",
 "suttar sf": "2",
 "sleepinal": "2",
 "safyral": "2",
 "saleto-d": "2",
 "spantuss hd": "2",
 "sominex pain relief formula": "2",
 "suprep": "2",
 "seconal sodium": "2",
 "sleep-ettes": "2",
 "sublimaze": "2",
 "stalevo 75": "2",
 "saleto-600": "2",
 "st. joseph 81 mg chewable aspirin": "2",
 "symbicort": "2",
 "skelex": "2",
 "sominex maximum strength caplet": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "somnicaps": "2",
 "siladryl das": "2",
 "simuc-hd": "2",
 "stalevo 200": "2",
 "sprix": "2",
 "sudafed sinus nighttime plus pain": "2",
 "selzentry": "2",
 "sominex": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "saleto-200": "2",
 "supac": "2",
 "s-t forte": "2",
 "sparine": "2",
 "septra ds": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "syeda": "2",
 "sleep-ettes d": "2",
 "spastrin": "2",
 "soma compound with codeine": "2",
 "st. joseph 81 mg aspirin enteric safety-coated": "2",
 "sterapred ds": "2",
 "s-t forte 2": "2",
 "simply sleep": "2",
 "sufentanil": "2",
 "scot-tussin allergy": "2",
 "surmontil": "2",
 "stalevo 100": "2",
 "sedapap": "2",
 "sodium salicylate": "2",
 "soma compound": "2",
 "suprep bowel prep kit": "2",
 "sufenta": "2",
 "stanback analgesic": "2",
 "serax": "2",
 "statuss green": "2",
 "siladryl allergy": "2",
 "sleep tabs": "2",
 "smz-tmp ds": "2",
 "spironolactone": "3",
 "stagesic": "2",
 "sterapred": "2",
 "sleepwell 2-nite": "2",
 "salflex": "2",
 "solu-medrol": "2",
 "sleep-eze-3": "2",
 "sine-aid ib": "2",
 "seconal": "2",
 "sudafed pe nighttime cold": "2",
 "statex": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "saphris": "2",
 "spasmolin": "2",
 "silphen cough": "2",
 "sinequan": "2",
 "suboxone": "2",
 "symbyax": "2",
 "spasquid": "2",
 "stalevo 50": "2",
 "salsitab": "2",
 "strifon fort": "2",
 "stalevo 125": "2",
 "sodium thiosalicylate": "2",
 "stalevo": "2",
 "src expectorant": "2",
 "servira": "2",
 "solurex la": "2",
 "silenor": "2",
 "siladyl sa": "2",
 "sodium oxybate": "2",
 "statuss": "2",
 "sulfatrim pediatric": "2",
 "stadol": "2",
 "seconal sodium pulvules": "2"}, "r": {"robaxisal": "2",
 "rms": "2",
 "ryna-c": "2",
 "reme hist dm": "2",
 "remeron": "2",
 "risperdal m-tab": "2",
 "rolatuss": "2",
 "robitussin-ac": "2",
 "robafen ac": "2",
 "ryna-cx": "2",
 "ramipril": "2",
 "rum-k": "3",
 "ryna-12x": "2",
 "robitussin-dac": "2",
 "robitussin night time cough, cold &amp; flu": "2",
 "relaxazone": "2",
 "roxanol-t": "2",
 "rindal-hd": "2",
 "roxicodone": "2",
 "romilar ac": "2",
 "roxanol 100": "2",
 "remular-s": "2",
 "remeron soltab": "2",
 "rufen": "2",
 "r-tannate pediatric": "2",
 "rezira": "2",
 "rofecoxib": "2",
 "r-tannamine pediatric": "2",
 "ropivacaine/sufentanil": "2",
 "r-tannate": "2",
 "rexolate": "2",
 "ru-tuss with hydrocodone": "2",
 "reprexain": "2",
 "rescudose": "2",
 "ru-hist forte": "2",
 "roxiprin": "2",
 "risperdal consta": "2",
 "relacon-hc nr": "2",
 "ryna-12": "2",
 "rhinatate": "2",
 "remifentanil": "2",
 "robitussin night time cough &amp; cold": "2",
 "rynatan-s pediatric": "2",
 "r-tannamine": "2",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "risperidone": "2",
 "rhinocaps": "2",
 "robichem ac": "2",
 "roxilox": "2",
 "resperal": "2",
 "ry-t-12": "2",
 "relacon-hc": "2",
 "respa c&amp;c": "2",
 "rhinatate pediatric": "2",
 "rindal hpd": "2",
 "remular": "2",
 "rasagiline": "2",
 "relasin-hc": "2",
 "restoril": "2",
 "rynesa 12s": "2",
 "rolatuss with hydrocodone": "2",
 "relcof c": "2",
 "repan": "2",
 "risperdal": "2",
 "robaxin": "2",
 "roxicet": "2",
 "robaxin-750": "2",
 "rhinogesic": "2",
 "rindal hd plus": "2",
 "relasin-hcx": "2",
 "ryna-12s": "2",
 "r-tannic-s a/d": "2",
 "rapamune": "2",
 "respa sa": "2",
 "relafen": "2",
 "re-pb hyos elixir": "2",
 "roxanol": "2",
 "roxicodone intensol": "2"}, "u": {"uretron": "2",
 "uro-kp-neutral": "3",
 "urimax": "2",
 "ursinus": "2",
 "urocit-k": "3",
 "utrona-c": "2",
 "uroplus": "2",
 "uprima": "2",
 "urised": "2",
 "uritact ds": "2",
 "unisom sleepmelts": "2",
 "uroplus ds": "2",
 "url-tannate": "2",
 "uni-multihist d ped": "2",
 "urimar-t": "2",
 "uni-lev 5.0": "2",
 "uretron ds": "2",
 "ustell": "2",
 "utira": "2",
 "univasc": "2",
 "utrona": "2",
 "u-tri-lone": "2",
 "urapine": "2",
 "uni-tann": "2",
 "uritin": "2",
 "urelief plus": "2",
 "ultiva": "2",
 "usept": "2",
 "uni-cof expectorant": "2",
 "uta": "2",
 "urisym": "2",
 "urogesic blue": "3",
 "url-tannate pediatric": "2",
 "uni tuss hc": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "unisom with pain relief": "2",
 "uni-cof": "2",
 "uni-tricof hc": "2",
 "uni-tann cs": "2",
 "uni-tann d": "2",
 "urelle": "2",
 "unisom sleepgels": "2",
 "utira-c": "2",
 "uro-phosphate": "3",
 "uribel": "2",
 "uniretic": "2"}, "t": {"tussionex pennkinetic": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "tizanidine": "3",
 "tekral": "2",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "tencet": "2",
 "theomax df": "2",
 "tri-vent hc": "2",
 "tolectin 600": "2",
 "thermotabs": "3",
 "tannate 12d s": "2",
 "travert 10% and electrolyte no2": "3",
 "tylenol with codeine #2": "2",
 "tri-k": "3",
 "tranylcypromine": "2",
 "tylenol with codeine #4": "2",
 "trimethoprim": "2",
 "tusso-df": "2",
 "tramacort-d": "2",
 "tanamine": "2",
 "tavist nighttime allergy": "2",
 "tri-gestan s": "2",
 "thiethylperazine": "2",
 "t- koff": "2",
 "tetra-mag": "2",
 "tussirex sugar free": "2",
 "tranquil nighttime sleep aid": "2",
 "tussafed-hc": "2",
 "tussafin liquid": "2",
 "temaril": "2",
 "tussafed-hcg": "2",
 "trilisate": "2",
 "talacen": "2",
 "trihist-cs": "2",
 "tolectin ds": "2",
 "trihist-d": "2",
 "theophylline ki": "3",
 "triotann-s pediatric": "2",
 "tranxene": "2",
 "tussin-v": "2",
 "tanamine pediatric": "2",
 "tranxene sd": "2",
 "trandolapril/verapamil": "2",
 "tridal": "2",
 "tetrabenazine": "2",
 "tussi-organidin nr": "2",
 "trilog": "2",
 "toradol": "2",
 "tussive hc": "2",
 "triant-hc": "2",
 "tuss-ds": "2",
 "tri-tannate": "2",
 "tritan": "2",
 "triaminic night time cold &amp; cough": "2",
 "twilite": "2",
 "tolectin": "2",
 "thioridazine": "2",
 "trifluoperazine": "2",
 "talwin nx": "2",
 "triazolam": "2",
 "tri-tannate pediatric": "2",
 "t-gesic": "2",
 "tylenol with codeine": "2",
 "tussigon": "2",
 "tylenol pm": "2",
 "tussgen expectorant": "2",
 "talwin": "2",
 "tussar sf": "2",
 "triotann-s": "2",
 "toradol iv/im": "2",
 "travasol with electrolytes dual chamber": "3",
 "tussirex": "2",
 "triaminic thin strips allergy": "2",
 "theracodophen low 90": "2",
 "tussend expectorant": "2",
 "torecan": "2",
 "theodrine": "2",
 "tofranil-pm": "2",
 "tri-histine": "2",
 "travert 5% and electrolyte no2": "3",
 "tusana-d": "2",
 "tanoral": "2",
 "tylox": "2",
 "tri tann pediatric": "2",
 "total allergy": "2",
 "tuss-hc": "2",
 "tussadur-hd": "2",
 "tylenol allergy complete nighttime": "2",
 "tussend": "2",
 "torisel": "2",
 "tannihist-12d": "2",
 "tl-hist cd": "2",
 "temazepam": "2",
 "tussi-12d s": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "tri-buffered aspirin": "2",
 "thorazine": "2",
 "therapy bayer": "2",
 "tricitrates": "3",
 "thiothixene": "2",
 "tussafin": "2",
 "tusal": "2",
 "tusso-c": "2",
 "trycet": "2",
 "theraflu warming relief sinus &amp; cold": "2",
 "tristoject": "2",
 "tusdec-hc": "2",
 "tussicaps": "2",
 "tussicle": "2",
 "trazodone": "2",
 "tl-hist cm": "2",
 "trandolapril": "2",
 "tranxene t-tab": "2",
 "triflupromazine": "2",
 "tusso-hc": "2",
 "triplex ad": "2",
 "twin-k": "3",
 "triavil": "2",
 "theraflu thin strips multi symptom": "2",
 "tolvaptan": "2",
 "ten-k": "3",
 "tekturna hct": "2",
 "tac 3": "2",
 "trimeprazine": "2",
 "trancopal": "2",
 "trac tabs 2x": "2",
 "triamterene": "3",
 "tedrigen": "2",
 "tylenol with codeine #3": "2",
 "touro hc": "2",
 "tekamlo": "2",
 "triam-forte": "2",
 "triple tannate pediatric": "2",
 "tencon": "2",
 "tanoral pediatric": "2",
 "triamcot": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "triam-a": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "trimal dh": "2",
 "travasol with electrolytes": "3",
 "triamonide 40": "2",
 "tenake": "2",
 "tofranil": "2",
 "triaprin": "2",
 "triafed &amp; codeine": "2",
 "tarka": "2",
 "trimpex": "2",
 "tylenol sore throat nighttime": "2",
 "triplex dm": "2",
 "trifed c": "2",
 "trezix": "2",
 "tadalafil": "1",
 "tussi-organidin-s nr": "2",
 "triamcinolone": "2",
 "triotann": "2",
 "tussi-12d": "2",
 "trilafon": "2",
 "tussar-2": "2",
 "tolmetin": "2",
 "trimipramine": "2",
 "trilone": "2",
 "tricof": "2",
 "tylenol severe allergy": "2",
 "tussplex": "2",
 "tussinate": "2",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tusstat": "2",
 "toradol im": "2",
 "tri-hist pediatric": "2",
 "triotann pediatric": "2",
 "triad": "2",
 "triacin c": "2",
 "tricosal": "2",
 "thyroshield": "3",
 "teczem": "2",
 "treximet": "2",
 "tussiden c": "2",
 "tannate v dm": "2",
 "tuinal": "2",
 "trux-adryl": "2",
 "tacaryl": "2",
 "tussgen": "2",
 "tusscough dhc": "2",
 "talwin compound": "2",
 "triaminic thin strips cough &amp; runny nose": "2",
 "tekturna": "2",
 "tylenol allergy multi-symptom nighttime": "2",
 "tuss-pd": "2",
 "two-dyne": "2",
 "temsirolimus": "2"}, "w": {"welltuss hc": "2",
 "wellbutrin xl": "2",
 "welltuss exp": "2",
 "wygesic": "2",
 "wal-nadol pm extra strength": "2",
 "wellbutrin sr": "2",
 "wellbutrin": "2"}, "v": {"vivactil": "2",
 "versed": "2",
 "ventuss syrup": "2",
 "vanex-hd": "2",
 "vanex expectorant": "2",
 "vioxx": "2",
 "viravan-t": "2",
 "vistaril": "2",
 "venlafaxine": "2",
 "vitussin expectorant": "2",
 "v-tan dm": "2",
 "viravan-pdm": "2",
 "vanspar": "2",
 "v-gan-50": "2",
 "vasotec": "2",
 "vetuss hc syrup": "2",
 "vanex forte": "2",
 "viravan-p": "2",
 "vimovo": "2",
 "vasotuss hc": "2",
 "voltaren": "2",
 "vopac": "2",
 "valdecoxib": "2",
 "vestura": "2",
 "vicodin": "2",
 "valu-dryl": "2",
 "vazotuss hc": "2",
 "vanatrip": "2",
 "vanacon": "2",
 "vicodin es": "2",
 "vi-q-tuss": "2",
 "viravan-s": "2",
 "voltaren-xr": "2",
 "vicotuss": "2",
 "visvex": "2",
 "visicol": "3",
 "vicoclear": "2",
 "v-gan-25": "2",
 "v-tann": "2",
 "vicodin hp": "2",
 "viravan-dm": "2",
 "viratan-dm": "2",
 "valium": "2",
 "vanadom": "2",
 "veripred 20": "2",
 "vis-phos n": "3",
 "vistazine": "2",
 "ventavis": "2",
 "vaseretic": "2",
 "vortex": "2",
 "valturna": "2",
 "valrelease": "2",
 "vanacof cd": "2",
 "vaseretic 10-25": "2",
 "vicoprofen": "2",
 "vaseretic 5-12.5": "2",
 "vicodin tuss": "2",
 "vanquish": "2"}, "y": {"yodefan": "3",
 "ysp aspirin": "2",
 "yasmin": "2",
 "yaz": "2"}, "x": {"xanax xr": "2",
 "xanax": "2",
 "xolox": "2",
 "xenazine": "2",
 "xyrem": "2",
 "xodol": "2",
 "xpect-hc": "2"}, "z": {"zotex-12": "2",
 "z-cof hcx": "2",
 "zorprin": "2",
 "zymine hc": "2",
 "z-tuss ac": "2",
 "zodryl ac": "2",
 "zarah": "2",
 "zyvox": "2",
 "zema pak": "2",
 "zutripro": "2",
 "ztuss zt": "2",
 "zero-order release": "2",
 "z-cof hc": "2",
 "zamicet": "2",
 "zonalon": "2",
 "zolpidem": "2",
 "ziprasidone": "2",
 "zolvit": "2",
 "zyprexa intramuscular": "2",
 "zydone": "2",
 "zestoretic": "2",
 "zerlor": "2",
 "zipsor": "2",
 "zodryl dac": "2",
 "zebutal": "2",
 "zodryl dec": "2",
 "zolpimist": "2",
 "zortress": "2",
 "zaleplon": "2",
 "z-tuss 2": "2",
 "zyban": "2",
 "zaponex": "2",
 "zelapar": "2",
 "zanaflex": "3",
 "zotex-c": "2",
 "zotex-d": "2",
 "zyprexa zydis": "2",
 "zestril": "2",
 "zyprexa relprevv": "2",
 "zetran": "2",
 "zotex hc": "2",
 "zyprexa": "2"}}];