interactions["bendamustine"]=["bendamustine", {"3": {"357 hr magnum": "2"}, "a": {"aspirin/caffeine/salicylamide": "2",
 "acetaminophen/butalbital": "2",
 "anacin": "2",
 "asthmacon": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "aspirin/caffeine/dihydrocodeine": "2",
 "acetaminophen/caffeine/isometheptene mucate": "2",
 "acetaminophen/caffeine/pyrilamine": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "acetaminophen/caffeine/chlorpheniramine/phenylpropanolamine": "2",
 "acthib with dpt (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "albendazole": "2",
 "aspirin/caffeine": "2",
 "aspirin/caffeine/orphenadrine": "2",
 "aqua gem-e": "2",
 "aqua-e": "2",
 "aplisol": "2",
 "attenuvax": "3",
 "ascomp with codeine": "2",
 "alagesic lq": "2",
 "arava": "3",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "2",
 "amobarbital/secobarbital": "2",
 "acetaminophen/aspirin/caffeine": "2",
 "antispasmodic": "2",
 "anagrelide": "2",
 "alemtuzumab": "2",
 "albenza": "2",
 "acam2000": "3",
 "acthib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "adult strength": "2",
 "amytal sodium": "2",
 "afluria": "2",
 "antrocol": "2",
 "anacin max strength": "2",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "2",
 "axocet": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "aspircaf": "2",
 "arthriten": "2",
 "acetaminophen/caffeine/guaifenesin/phenylephrine": "2",
 "alefacept": "2",
 "arcalyst": "2",
 "anoquan": "2",
 "aspirin/butalbital": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "anakinra": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "aplitest": "2",
 "alagesic": "2",
 "aspirin/butalbital/caffeine": "2",
 "alka-seltzer wake-up call!": "2",
 "adalimumab": "3",
 "alkabel-sr": "2",
 "arcet": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "amino-opti-e": "2",
 "amobarbital": "2",
 "alert": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "aquasol e": "2",
 "acetaminophen/caffeine/dihydrocodeine": "2",
 "antispas": "2",
 "anacin advanced headache formula": "2",
 "agriflu": "2",
 "adacel": "2",
 "agrylin": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "anthrax vaccine adsorbed": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "atropine/phenobarbital": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "acetaminophen/caffeine/phenyltoloxamine": "2",
 "amiodarone": "2",
 "americet": "2",
 "aquavite-e": "2",
 "acetaminophen/caffeine": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "amevive": "2",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "2",
 "anolor 300": "2",
 "alpha e": "2"}, "c": {"cervarix": "2",
 "cafgesic forte": "2",
 "cephadyn": "2",
 "carbatrol": "2",
 "cimetidine": "2",
 "cipro": "2",
 "comvax (haemophilus b conjugate (prp-omp) vaccine/hepatitis b pediatric vaccine)": "2",
 "caffeine/sodium benzoate": "2",
 "cvs extra strength headache relief": "2",
 "cordarone": "2",
 "canakinumab": "2",
 "combiflex": "2",
 "cafatine": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "caffeine/ergotamine": "2",
 "cordarone iv": "2",
 "clozapine": "3",
 "ciprofloxacin": "2",
 "cipro i.v.": "2",
 "caffeine": "2",
 "cholera vaccine": "2",
 "cafgesic": "2",
 "cladribine novaplus": "2",
 "cladribine": "2",
 "cope": "2",
 "clopine": "3",
 "coccidioidin skin test": "2",
 "cafergot": "2",
 "candida skin test": "2",
 "cafcit": "2",
 "clozaril": "3",
 "candin": "2",
 "carbamazepine": "2",
 "cipro xr": "2",
 "cafetrate": "2",
 "capacet": "2",
 "caffedrine": "2",
 "clozapine synthon": "3",
 "combiflex es": "2",
 "candida albicans extract": "2",
 "chardonna-2": "2",
 "caffeine/magnesium salicylate": "2",
 "cafatine pb": "2",
 "centrum singles-vitamin e": "2",
 "cipro cystitis pack": "2",
 "certolizumab": "3",
 "cytovene": "2",
 "cimzia": "3",
 "campath": "2"}, "b": {"bellaphen-s": "2",
 "bcg": "3",
 "busodium": "2",
 "b c powder": "2",
 "bayer extra strength back &amp; body": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "butisol sodium": "2",
 "bc headache": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "bupap": "2",
 "belcomp-pb": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bellatal er": "2",
 "bayer am": "2",
 "butex forte": "2",
 "butalbital compound": "2",
 "butalbital": "2",
 "b c powder arthritis strength": "2",
 "bellamor": "2",
 "bellaspas": "2",
 "bc fast pain relief": "2",
 "boostrix": "2",
 "bel-phen-ergot": "2",
 "biothrax": "2",
 "butibel": "2",
 "butabarbital": "2",
 "barbidonna": "2",
 "biavax ii": "3",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine": "2",
 "bellatal": "2",
 "belladonna/butabarbital": "2",
 "bel-tabs": "2",
 "bucet": "2",
 "bellamine s": "2"}, "e": {"exjade": "2",
 "excedrin extra strength": "2",
 "e-gems": "2",
 "enoxacin": "2",
 "elixiral": "2",
 "ercaf": "2",
 "e-600": "2",
 "esomeprazole/naproxen": "2",
 "esgic-plus": "2",
 "e-400 clear": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "excedrin migraine": "2",
 "esomeprazole": "2",
 "eperbel-s": "2",
 "engerix-b": "2",
 "emagrin": "2",
 "etanercept": "3",
 "efalizumab": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "emagrin forte": "2",
 "excedrin menstrual complete": "2",
 "enerjets": "2",
 "ezol": "2",
 "ergocomp-pb": "2",
 "ergocaffpb": "2",
 "excedrin quick tab": "2",
 "e pherol": "2",
 "enbrel": "3",
 "e-caff p-b": "2",
 "equetro": "2",
 "engerix-b pediatric": "2",
 "equaline acid reducer": "2",
 "endolor": "2",
 "epitol": "2",
 "ergocaf-pb": "2",
 "excedrin": "2",
 "excedrin tension headache": "2",
 "esgic": "2"}, "d": {"dolmar": "2",
 "darvon compound 32": "2",
 "donnatal": "2",
 "daptacel": "2",
 "deferasirox": "2",
 "diphtheria toxoid/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "diphtheria toxoid/hepatitis b pediatric vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "diphtheria toxoid/tetanus toxoid": "2",
 "decavac": "2",
 "delta-lutin": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "durabac": "2",
 "diphtheria toxoid/haemophilus b conjugate": "2",
 "durabac forte": "2",
 "diurex": "2",
 "donnapine": "2",
 "denosumab": "2",
 "deferiprone": "3",
 "diphtheria-tetanus toxoids, pediatric": "2",
 "dryvax": "3",
 "diphtheria and tetanus toxoids/pertussis, acellular": "2",
 "duragal-s": "2",
 "donnatal extentabs": "2",
 "dolgic plus": "2",
 "dolgic lq": "2",
 "darvon compound-65": "2",
 "donnaphen": "2",
 "diurex maximum relief water caps": "2",
 "duralutin": "2",
 "diphtheria toxoid/pertussis, whole cell/tetanus toxoid": "2",
 "d-tal": "2",
 "diphtheria toxoid/pertussis, acellular/tetanus toxoid": "2",
 "diurex ultra": "2",
 "dolgic": "2",
 "denzapine": "3"}, "g": {"gilenya": "2",
 "goodys headache powders": "2",
 "goody's extra-strength headache powders": "2",
 "golimumab": "3",
 "goodys extra strength": "2",
 "ganciclovir": "2",
 "genace": "2",
 "geone": "2",
 "gardasil": "2",
 "g-1": "2",
 "genasan": "2",
 "grepafloxacin": "2"}, "f": {"fiortal": "2",
 "fingolimod": "2",
 "fluzone intradermal": "2",
 "fiorinal with codeine iii": "2",
 "flextra plus": "2",
 "fazaclo": "3",
 "fiorinal with codeine": "2",
 "flushield": "2",
 "fortabs": "2",
 "fiorinal": "2",
 "fioricet with codeine": "2",
 "fastlene": "2",
 "fluvoxamine": "2",
 "femcet": "2",
 "fluvirin": "2",
 "ferriprox": "3",
 "flulaval": "2",
 "fiortal with codeine": "2",
 "fluzone high-dose": "2",
 "flumist": "3",
 "fluogen": "2",
 "fluarix": "2",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiormor": "2",
 "flextra": "2",
 "fluzone": "2",
 "farbital": "2",
 "filgrastim": "2",
 "fiorpap": "2"}, "i": {"isoniazid/rifampin": "2",
 "influenza virus vaccine, inactivated": "2",
 "imovax rabies": "2",
 "isoniazid": "2",
 "influenza virus vaccine, h1n1, live": "3",
 "isoniazid/pyrazinamide/rifampin": "2",
 "ilaris": "2",
 "ipol": "2",
 "ide-cet": "2",
 "influenza virus vaccine, h1n1, inactivated": "2",
 "idenal": "2",
 "infliximab": "3",
 "isocet": "2",
 "influenza virus vaccine, live, trivalent": "3",
 "ixiaro": "2",
 "infanrix": "2",
 "isonarif": "2"}, "h": {"hepatitis a pediatric vaccine": "2",
 "human papillomavirus vaccine": "2",
 "histolyn-cyl": "2",
 "havrix": "2",
 "histoplasmin diluted": "2",
 "hibtiter (haemophilus b conjugate (hboc) vaccine)": "2",
 "hyprogesterone": "2",
 "hylutin": "2",
 "havrix pediatric": "2",
 "haemophilus b conjugate": "2",
 "hyosophen": "2",
 "hycamtin": "2",
 "hepatitis b adult vaccine": "2",
 "hepatitis b pediatric vaccine": "2",
 "hycomine compound": "2",
 "histoplasmin": "2",
 "hepatitis a adult vaccine/hepatitis b adult vaccine": "2",
 "hepatitis a adult vaccine": "2",
 "haponal": "2",
 "hiberix (haemophilus b conjugate (prp-t) vaccine)": "2",
 "hydroxyprogesterone": "2",
 "humira": "3",
 "hyoscyamine/phenobarbital": "2"}, "k": {"kineret": "2",
 "kneerelief": "2",
 "keep going": "2",
 "kinrix": "2",
 "keep alert": "2",
 "kepivance": "2"}, "j": {"je-vax": "2",
 "japanese encephalitis virus vaccine sa14-14-2": "2",
 "japanese encephalitis virus vaccine nakayama": "2"}, "m": {"measles virus vaccine/mumps virus vaccine/rubella virus vaccine": "3",
 "mudrane gg": "2",
 "mygracet": "2",
 "margesic": "2",
 "migralam": "2",
 "mumps virus vaccine/rubella virus vaccine": "3",
 "midol traditional": "2",
 "menomune": "2",
 "mibefradil": "2",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine/varicella virus vaccine": "3",
 "m-r-vax ii": "3",
 "menactra": "2",
 "molie": "2",
 "mumps skin test antigen": "2",
 "mexitil": "2",
 "mysoline": "2",
 "msta mumps skin test antigen": "2",
 "minotal": "2",
 "mintezol": "2",
 "marten-tab": "2",
 "measles virus vaccine": "3",
 "menomune a/c/y/w-135": "2",
 "migracet-pb": "2",
 "meningococcal conjugate vaccine": "2",
 "medique pain-off": "2",
 "mumps virus vaccine": "3",
 "mephobarbital": "2",
 "m-m-r ii": "3",
 "migergot": "2",
 "medigesic": "2",
 "mumpsvax": "3",
 "makena": "2",
 "migraten": "2",
 "mebaral": "2",
 "mono-vacc test": "2",
 "midol maximum strength menstrual": "2",
 "menstrual complete": "2",
 "mixed respiratory vaccine": "2",
 "meruvax ii": "3",
 "metastron": "2",
 "meningococcal polysaccharide vaccine": "2",
 "multitest cmi": "2",
 "menveo": "2",
 "mrv": "2",
 "mexiletine": "2",
 "measles virus vaccine/rubella virus vaccine": "3",
 "mudrane": "2",
 "micomp-pb": "2"}, "l": {"lyme disease vaccine": "2",
 "levsin with phenobarbital": "2",
 "luvox cr": "2",
 "lufyllin-epg": "2",
 "lucidex": "2",
 "leflunomide": "3",
 "leukine": "2",
 "luminal": "2",
 "lymerix": "2",
 "leustatin": "2",
 "laniroif": "2",
 "levacet": "2",
 "liquid pedvaxhib (haemophilus b conjugate (prp-omp) vaccine)": "2",
 "luvox": "2"}, "o": {"orphengesic": "2",
 "orphengesic forte": "2",
 "omesec": "2",
 "overtime": "2",
 "orbivan": "2",
 "orimune": "3",
 "omeprazole/sodium bicarbonate": "2",
 "omeprazole": "2"}, "n": {"niclosamide": "2",
 "noroxin": "2",
 "nonbac": "2",
 "nalidixic acid": "2",
 "norgesic forte": "2",
 "nydrazid": "2",
 "norfloxacin": "2",
 "niclocide": "2",
 "norgesic": "2",
 "nexium": "2",
 "natalizumab": "3",
 "neulasta": "2",
 "nodoz maximum strength": "2",
 "nembutal sodium": "2",
 "nodoz": "2",
 "nembutal": "2",
 "nutr-e-sol": "2",
 "neggram": "2",
 "nexterone": "2",
 "nexium iv": "2",
 "neupogen": "2"}, "q": {"quadrinal": "2",
 "quadrapax": "2",
 "quadramet": "3"}, "p": {"pyridium plus": "2",
 "p-a-c": "2",
 "primaquine": "2",
 "pentobarbital": "2",
 "phrenilin forte": "2",
 "panlor dc": "2",
 "promacet": "2",
 "propoxyphene compound 65": "2",
 "prilosec": "2",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "pneumococcal 7-valent vaccine": "2",
 "pb-hyos": "2",
 "pedvaxhib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "pc-cap": "2",
 "pyrelle hb": "2",
 "pediarix": "2",
 "prevnar 13": "2",
 "plague vaccine": "2",
 "panlor ss": "2",
 "poliovirus vaccine, live, trivalent": "3",
 "penetrex": "2",
 "pharmagesic": "2",
 "pneumococcal 23-polyvalent vaccine": "2",
 "pneumococcal 13-valent vaccine": "2",
 "phenazoforte plus": "2",
 "prodrin": "2",
 "palifermin": "2",
 "painaid": "2",
 "proquin xr": "2",
 "prolia": "2",
 "primidone": "2",
 "posicor": "2",
 "prominol": "2",
 "provenge": "2",
 "phenobarbital": "2",
 "prilosec otc": "2",
 "pegfilgrastim": "2",
 "poliovirus vaccine, inactivated": "2",
 "phrenilin": "2",
 "pep-back ultra": "2",
 "prevnar": "2",
 "propafenone": "2",
 "proquad": "3",
 "pep-back peak performance": "2",
 "phenaz plus": "2",
 "pneumovax 23": "2",
 "pamprin max menstrual pain relief": "2",
 "pacerone": "2",
 "p-a-c analgesic": "2",
 "pentacel (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid)": "2",
 "prodrox": "2"}, "s": {"strontium-89 chloride": "2",
 "staphage lysate": "2",
 "saleto": "2",
 "stay awake": "2",
 "stelara": "2",
 "sodium phosphate p32": "2",
 "sipuleucel-t": "2",
 "simponi": "3",
 "seconal": "2",
 "samarium sm 153 lexidronam": "3",
 "spasmolin": "2",
 "saleto-d": "2",
 "spastrin": "2",
 "smallpox vaccine": "3",
 "spasquid": "2",
 "seconal sodium": "2",
 "sargramostim": "2",
 "synalgos-dc": "2",
 "sedapap": "2",
 "servira": "2",
 "solfoton": "2",
 "secobarbital": "2",
 "spherulin": "2",
 "scot-tussin original": "2",
 "stat awake": "2",
 "supac": "2",
 "sinapils": "2",
 "stanback fast pain relief": "2",
 "skin test antigens, multiple": "2",
 "stay alert": "2",
 "sclavo test-ppd": "2",
 "seconal sodium pulvules": "2"}, "r": {"recombivax hb dialysis formulation": "2",
 "raxar": "2",
 "rimactane": "2",
 "rotateq": "3",
 "rotashield": "3",
 "recombivax hb adult": "2",
 "rythmol": "2",
 "rofecoxib": "2",
 "raptiva": "2",
 "rifater": "2",
 "rubella virus vaccine": "3",
 "rabies vaccine, human diploid cell": "2",
 "rotavirus vaccine": "3",
 "rythmol sr": "2",
 "rotarix": "3",
 "rifamate": "2",
 "rifampin": "2",
 "rabavert": "2",
 "repan": "2",
 "rilonacept": "2",
 "rifadin iv": "2",
 "recombivax hb pediatric/adolescent": "2",
 "recombivax hb": "2",
 "rifadin": "2",
 "rabies vaccine, purified chick embryo cell": "2",
 "re-pb hyos elixir": "2",
 "remicade": "3"}, "u": {"urelief plus": "2",
 "ustekinumab": "2"}, "t": {"tenake": "2",
 "ticlid": "2",
 "triaprin": "2",
 "tetanus toxoid adsorbed": "2",
 "tencet": "2",
 "tuberculin tine test": "2",
 "tuberculin purified protein derivative": "2",
 "trezix": "2",
 "tubersol": "2",
 "ticlopidine": "2",
 "tripedia": "2",
 "tetanus toxoid": "2",
 "trihibit (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "theracys": "3",
 "tetanus toxoid for booster use only": "2",
 "tice bcg": "3",
 "typhoid vaccine, inactivated": "2",
 "trichophyton allergenic extracts": "2",
 "thiabendazole": "2",
 "te anatoxal berna": "2",
 "tetramune (diphtheria toxoid/haemophilus b conjugate (hboc) vaccine/pertussis, whole cell/tetanus toxoid)": "2",
 "theodrine": "2",
 "tagamet": "2",
 "tuinal": "2",
 "twinrix": "2",
 "trichophyton skin test": "2",
 "typhoid vaccine, live": "3",
 "tedrigen": "2",
 "tegretol": "2",
 "tysabri": "3",
 "tagamet hb": "2",
 "tegretol xr": "2",
 "topotecan": "2",
 "typhim vi": "2",
 "tencon": "2",
 "tice bcg vaccine": "3",
 "triad": "2",
 "tetanus-diphtheria toxoids, adult": "2",
 "two-dyne": "2"}, "w": {"wakespan": "2",
 "wigraine": "2"}, "v": {"vaqta": "2",
 "vemurafenib": "2",
 "vita-plus e natural": "2",
 "vaqta pediatric": "2",
 "vioxx": "2",
 "valcyte": "2",
 "vimovo": "2",
 "vivarin": "2",
 "varivax": "3",
 "valentine": "2",
 "valorin extra": "2",
 "valganciclovir": "2",
 "vitamin e": "2",
 "varicella virus vaccine": "3",
 "verv": "2",
 "vivotif berna vaccine": "3",
 "vivotif berna": "3",
 "vanquish": "2"}, "y": {"yellow fever vaccine": "3",
 "yf-vax": "3"}, "x": {"xgeva": "2"}, "z": {"zegerid otc": "2",
 "zerlor": "2",
 "zoster vaccine live": "3",
 "zostavax": "3",
 "zegerid": "2",
 "zebutal": "2",
 "zelboraf": "2",
 "zaponex": "3"}}];