interactions["benzphetamine"]=["benzphetamine", {"a": {"aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "3",
 "alacol": "2",
 "alumadrine": "3",
 "aluminum hydroxide": "2",
 "acetaminophen/brompheniramine/phenylpropanolamine": "3",
 "ammonium chloride/chlorpheniramine/dextromethorphan/ephedrine/ipecac/phenylephrine": "2",
 "allertan": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "2",
 "adipex-p": "3",
 "accuhist la": "2",
 "alka-seltzer plus cold &amp; flu": "2",
 "ami-tex la": "3",
 "atrohist pediatric": "2",
 "ascor l nc": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/scopolamine": "2",
 "adrenaclick": "2",
 "aspirin/chlorpheniramine/phenylephrine": "2",
 "acetaminophen/chlorpheniramine/guaifenesin/phenylpropanolamine": "3",
 "antispas": "1",
 "aspirin buffered": "2",
 "ambi 40/1000/60": "2",
 "acetaminophen/dextromethorphan/guaifenesin/phenylpropanolamine": "3",
 "aminophylline/amobarbital/ephedrine": "2",
 "alu-tab": "2",
 "aspir-mox": "2",
 "amitriptyline": "2",
 "acetaminophen/dextromethorphan/guaifenesin/phenylephrine": "2",
 "alternagel": "2",
 "alka-seltzer plus night cold formula liquid": "2",
 "andecon pediatric drops": "3",
 "alcalak": "2",
 "ah-chew ultra tannate": "2",
 "alahist dm": "2",
 "ah-chew d": "2",
 "alenaze-d nr": "2",
 "ah-chew": "2",
 "aldex": "2",
 "ascorbic acid/iron polysaccharide": "2",
 "alka-seltzer gold": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "amphojel": "2",
 "ami-rax": "2",
 "alka-seltzer plus flu formula": "2",
 "arthritis pain formula": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenyltoloxamine": "2",
 "acetaminophen/chlorpheniramine/phenylpropanolamine": "3",
 "acetaminophen/guaifenesin/phenylephrine": "2",
 "actifed cold and allergy": "2",
 "alenaze-d": "2",
 "acutrim 16 hour": "3",
 "ambi 40/1000": "2",
 "acerola": "2",
 "allerx dose pack": "2",
 "aridex-d": "2",
 "alka-seltzer plus cold &amp; cough formula liquid": "2",
 "asthmacon": "2",
 "alahist lq": "2",
 "alkets": "2",
 "allerx pe": "2",
 "alka-seltzer heartburn relief": "2",
 "asthmahaler": "2",
 "adreview": "2",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "albatussin pediatric drops": "2",
 "acetaminophen/dextromethorphan/doxylamine/phenylephrine": "2",
 "atrohist plus": "3",
 "accuhist pdx syrup": "2",
 "aerokid": "2",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "adrenalin chloride": "2",
 "ah-chew ii": "2",
 "alka-seltzer plus cold and sinus": "2",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "3",
 "alacol dm": "2",
 "acetaminophen/dextromethorphan/phenylephrine": "2",
 "ascorbic acid quick melts": "2",
 "allergy dn pe": "2",
 "anergan 50": "2",
 "allerest 12 hour": "3",
 "acid gone antacid": "2",
 "acetaminophen/phenylephrine": "2",
 "acid gone": "2",
 "aquatab c": "2",
 "amitex la": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "acetaminophen/caffeine/guaifenesin/phenylephrine": "2",
 "anatuss": "3",
 "acutrim ii, maximum strength": "3",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "1",
 "aldroxicon ii": "2",
 "amitone": "2",
 "a-tan 12x": "2",
 "alka-seltzer plus night cold formula liquid gels": "2",
 "alkabel-sr": "1",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "allergy multi-symptom relief": "2",
 "aldex-ct": "2",
 "alka-seltzer original": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "alka-mints": "2",
 "alka-seltzer plus cold &amp; cough formula liquid gels": "2",
 "ascriptin maximum strength": "2",
 "aluminum hydroxide/mineral oil": "2",
 "aridex-d pediatric": "2",
 "articaine/epinephrine": "2",
 "aerohist plus": "2",
 "allanhist pdx syrup": "2",
 "aridex": "2",
 "alka-seltzer lemon-lime": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "3",
 "adipost": "3",
 "allerest pe": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2",
 "aldroxicon i": "2",
 "alka-seltzer plus cold": "2",
 "appecon": "3",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "antispasmodic": "1",
 "atuss dm": "2",
 "acetaminophen/caffeine/chlorpheniramine/phenylpropanolamine": "3",
 "albatussin": "2",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "aquatab d": "2",
 "alenic alka tablet": "2",
 "alka-seltzer plus day &amp; night cold formula (night cold) liquid gels": "2",
 "aprepitant": "2",
 "adrenalin": "2",
 "actonel with calcium": "2",
 "altatapp": "3",
 "ascorbic acid": "2",
 "acid gone extra strength": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "3",
 "anorex-sr": "3",
 "alka-seltzer plus cold formula": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "ami-lac": "2",
 "aluminum carbonate": "2",
 "adapin": "2",
 "aramine": "2",
 "alka-seltzer plus day &amp; night cold formula (day cold) liquid gels": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/phenylpropanolamine": "3",
 "ami-tex": "3",
 "alka-seltzer plus severe sinus congestion &amp; cough": "2",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "allerhist-d": "3",
 "alkums": "2",
 "allan tannate pediatric": "2",
 "acetaminophen/aspirin/phenylpropanolamine": "3",
 "ala-hist d": "2",
 "acid relief": "2",
 "aspirin/calcium carbonate": "2",
 "allerx pe dose pack": "2",
 "anafranil": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "alcohol and dextrose injections usp hypertonic": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/phenylpropanolamine/scopolamine": "3",
 "antrocol": "1",
 "altex liquid": "3",
 "almacone-2": "2",
 "aspirin/citric acid/sodium bicarbonate": "2",
 "ascor l 500": "2",
 "ascot": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "aldex dm": "2",
 "atuss g": "2",
 "arm allergy relief": "3",
 "albatussin pediatric": "2",
 "alu-cap": "2",
 "acetaminophen/pheniramine/phenylephrine": "2",
 "ascocid": "2",
 "airacof": "2",
 "ascriptin": "2",
 "almacone": "2",
 "amoxapine": "2",
 "acetaminophen/chlorpheniramine/phenylephrine": "2",
 "alahist dhc": "2",
 "atuss ms": "2",
 "alamag": "2",
 "alamag plus": "2",
 "ala-hist pe": "2",
 "alphen expectorant": "3",
 "ambi 5/15/100": "2",
 "acetaminophen/chlorpheniramine/dextromethorphan/phenylephrine": "2",
 "ah-chew ultra": "2",
 "azilect": "2",
 "ascorbic acid/ferrous sulfate": "2",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "3",
 "asendin": "2",
 "ammonium chloride": "2",
 "acetaminophen/dextromethorphan/phenylpropanolamine": "3",
 "aspirin/diphenhydramine/phenylpropanolamine": "3",
 "atropine/phenobarbital": "1",
 "ana-guard": "2",
 "anhydrous calcium iodide/isoproterenol": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "ana-kit": "2",
 "acta-tabs pe": "2",
 "articadent": "2",
 "acutuss dm pediatric": "3",
 "alka-seltzer plus day non-drowsy cold formula liquid gels": "2",
 "atuss dr": "2",
 "ascorbic acid/ferrous fumarate": "2",
 "aventyl hydrochloride": "2",
 "acetaminophen/tramadol": "3",
 "acid reducer + antacid dual action": "2",
 "atapryl": "3",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "2",
 "aldex d": "2",
 "aldex g": "2",
 "alka-seltzer extra strength": "2",
 "acutrim late day": "3",
 "alenic alka": "2",
 "amidal": "2",
 "aspir-mox ib": "2",
 "aloh-gel": "2",
 "alcohol 5% in dextrose 5%": "2",
 "alcohol": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "ala-hist ac": "2",
 "amilon": "3",
 "anextuss": "2",
 "aplenzin": "3",
 "allerx": "2",
 "acetaminophen/caffeine/chlorpheniramine/hydrocodone/phenylephrine": "2"}, "c": {"calcitab": "2",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "calcium carbonate/risedronate": "2",
 "chlorpheniramine/hydrocodone/phenylephrine": "2",
 "chlorpheniramine/methscopolamine/phenylpropanolamine": "3",
 "c-tanna 12d": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "cevi-bid": "2",
 "compazine spansule": "2",
 "calcium carbonate/fluoride": "2",
 "congespirin aspirin free": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine/phenylpropanolamine": "3",
 "carbetapentane/phenylephrine/phenylpropanolamine/potassium guaiacolsulfonate": "3",
 "coldcough pd": "2",
 "coryza-d": "2",
 "c phen drops": "2",
 "cascara sagrada/magnesium hydroxide": "2",
 "calcarb with d": "2",
 "comtrex nighttime cold &amp; cough": "2",
 "citracal regular": "2",
 "cemill 1000": "2",
 "chlor-mes": "2",
 "cpm-pe-msc": "2",
 "carbetapentane/phenylephrine": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "cytra-k": "2",
 "crantex la tablets": "2",
 "chlorthalidone/reserpine": "2",
 "cyntex liquid": "3",
 "citric acid/potassium citrate/sodium citrate": "2",
 "cytra-3": "2",
 "chlorpheniramine/guaifenesin/phenylephrine": "2",
 "chlorex a": "2",
 "chemdal hd plus": "2",
 "citalopram": "3",
 "coldtuss-dr": "2",
 "contac cold+flu non-drowsy maximum strength": "2",
 "codral cold and flu + cough day and night": "2",
 "codamine": "3",
 "coughtuss": "2",
 "calcium oyster shell": "2",
 "chemdal expectorant": "3",
 "chest congestion relief pe": "2",
 "citra ph": "2",
 "codimal dm": "2",
 "crantex la capsules": "2",
 "calcid": "2",
 "codimal dh": "2",
 "colrex compound": "2",
 "cold head congestion": "2",
 "chlorothiazide/reserpine": "2",
 "ceron": "2",
 "carbex": "3",
 "cp dec-dm drops": "2",
 "contac 12 hour": "3",
 "carbetapentane/phenylephrine/pyrilamine": "2",
 "centrum singles-vitamin c": "2",
 "chlorphen hd": "2",
 "cyndal hd": "2",
 "chlortox": "2",
 "cytra-2": "2",
 "citric acid/glucono-delta-lactone/magnesium carbonate topical": "2",
 "coldex": "2",
 "carbetaplex ts": "2",
 "chlorpheniramine/phenylpropanolamine": "3",
 "coldloc-la": "3",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "3",
 "celexa": "3",
 "children's tylenol plus cold and allergy": "2",
 "chlornade": "3",
 "carbinoxamine/hydrocodone/phenylephrine": "2",
 "comtussin hc": "2",
 "citracal + d": "2",
 "codeine/promethazine": "2",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "clemastine/phenylpropanolamine": "3",
 "coryza-dm": "2",
 "citrocarbonate": "2",
 "cold &amp; cough childrens": "2",
 "caltrate colon health": "2",
 "chlor-mes d": "2",
 "carbetapentane/chlorpheniramine/phenylephrine": "2",
 "codegest expectorant": "3",
 "c phen": "2",
 "codal-dh syrup": "2",
 "citracal calcium gummies": "2",
 "ceo-two": "2",
 "c-phen dm drops": "2",
 "citracal regular 250 mg + d": "2",
 "contac complete cough, cold &amp; flu extra strength": "2",
 "cemill": "2",
 "calcium carbonate/simethicone": "2",
 "cp dec dm": "2",
 "carbetapentane/chlorpheniramine/ephedrine/phenylephrine": "2",
 "colrex": "2",
 "cough &amp; cold relief": "2",
 "certuss-d": "2",
 "chlor-mes jr": "2",
 "codeine phosphate-promethazine hcl": "2",
 "crantex er": "2",
 "chlorpheniramine/phenindamine/phenylpropanolamine": "3",
 "cp dec drops": "2",
 "comtrex cold and flu maximum strength": "3",
 "cemill 500": "2",
 "compro": "2",
 "chlorpheniramine/phenylephrine/pyrilamine": "2",
 "comtrex non drowsy liquigel": "3",
 "carbaphen 12": "2",
 "carbetapentane/dexchlorpheniramine/phenylephrine": "2",
 "ceron drops": "2",
 "chlorex-a 12": "2",
 "caltrate 600+d": "2",
 "corfen-dm": "2",
 "chlorgest hd": "2",
 "centergy dm": "2",
 "chardonna-2": "1",
 "centussin dhc": "2",
 "chlorpheniramine/dextromethorphan/guaifenesin/phenylephrine": "2",
 "comhist la": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "comtrex severe cold &amp; sinus": "2",
 "citracal maximum": "2",
 "citanest forte": "2",
 "calcium carbonate/magnesium carbonate": "2",
 "chlor-trimeton sinus": "3",
 "cytuss-hc nr": "2",
 "corzall-pe": "2",
 "contac-d": "2",
 "cecon": "2",
 "c-phen dm": "2",
 "chlo tuss": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "comtrex cold &amp; cough": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "cee-500": "2",
 "carbinoxamine/phenylephrine": "2",
 "carbetapentane/phenylephrine/potassium guaiacolsulfonate": "2",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "codeine/phenylephrine": "2",
 "chlorpheniramine/phenylephrine/phenyltoloxamine": "2",
 "calcitrate with d": "2",
 "comtrex maximum strength cold relief": "3",
 "chemdal hd": "2",
 "calcio del mar": "2",
 "caltrate 600 with d plus soy": "2",
 "c-hist-sr": "2",
 "citrolith": "2",
 "carbetapentane/guaifenesin/phenylephrine": "2",
 "cal-gest": "2",
 "chemdal": "2",
 "calcium carbonate": "2",
 "carbatuss": "2",
 "chlorpheniramine/dihydrocodeine/phenylephrine": "2",
 "chemtussin hc": "2",
 "calcet": "2",
 "codeine/guaifenesin/phenylpropanolamine": "3",
 "caltro with vitamin d": "2",
 "children's triacting daytime": "2",
 "comhist": "2",
 "coldonyl": "2",
 "chlorpromazine": "2",
 "codamine pediatric": "3",
 "canges-hc": "2",
 "cophene-x": "3",
 "cal oys": "2",
 "cyndal expectorant": "3",
 "chlorpheniramine/phenylephrine": "2",
 "chlorpheniramine/dextromethorphan/phenylephrine": "2",
 "ceron-dm": "2",
 "cold multi-symptom severe": "2",
 "contac severe cold and flu maximum stength": "3",
 "citric acid/simethicone/sodium bicarbonate": "2",
 "cvs allergy &amp; cold": "2",
 "chlophedianol/phenylephrine/triprolidine": "2",
 "chlophedianol/guaifenesin/phenylephrine": "2",
 "cheracol plus": "3",
 "chlorpheniramine/dextromethorphan/phenylpropanolamine": "3",
 "chewable calcium with vitamin d": "2",
 "cvs allergy &amp; sinus headache": "2",
 "codimal ph": "2",
 "cardec": "2",
 "children's triacting night time": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "codituss dm": "2",
 "chlorpheniramine/epinephrine": "2",
 "cerose dm": "2",
 "crantex": "2",
 "chlorpheniramine/dextromethorphan/guaifenesin/methscopolamine/phenylephrine": "2",
 "chlorpheniramine/methscopolamine/phenylephrine": "2",
 "cp dec": "2",
 "codal-dm syrup": "2",
 "calci mix": "2",
 "chlophedianol/dexbrompheniramine/phenylephrine": "2",
 "compazine": "2",
 "codeine/phenylephrine/promethazine": "2",
 "clomipramine": "2",
 "control": "3",
 "cardec dm": "2",
 "citrus calcium with vitamin d": "2",
 "cymbalta": "3",
 "cenolate": "2",
 "comtrex cold &amp; cough day night": "2",
 "calcium oyster": "2",
 "covangesic": "3",
 "citric acid/sodium citrate": "2",
 "conal": "2",
 "calcarb": "2",
 "c/rose hips": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "calcium acetate/magnesium carbonate": "2",
 "contac cold+flu maximum strength": "2",
 "condrin": "3",
 "citrate-phos-dex": "2",
 "calcium/vitamin d": "2",
 "carbatab-12": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine/phenyltoloxamine": "3",
 "chlordex gp": "2",
 "chlorpheniramine/ephedrine/guaifenesin": "2",
 "calcium concentrate": "2",
 "ceron-dm drops": "2",
 "cold &amp; cough pe multi-symptom": "2",
 "crantex hc": "2",
 "cardec drops": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "cytuss hc": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "3",
 "calvite p": "2",
 "chlorcyclizine/phenylephrine": "2",
 "cardec dm drops": "2",
 "coldloc": "3",
 "carbetaplex": "2",
 "citracal plus bone density builder": "2",
 "caltro": "2",
 "coricidin d": "3",
 "citracal plus heart health": "2",
 "carbatuss-cl": "2",
 "codituss dh": "2",
 "chlorpheniramine/guaifenesin/methscopolamine/phenylephrine": "2",
 "carbinoxamine/dextromethorphan/phenylephrine": "2",
 "citracal slow release 1200": "2",
 "calcium 600 d": "2",
 "citric acid/potassium citrate": "2",
 "comtrex cold and cough maximum strength": "2",
 "comtrex flu therapy": "2",
 "carbetapentane/carbinoxamine/phenylephrine": "2",
 "chlortan d": "2",
 "chlorpheniramine/phenylephrine/phenylpropanolamine": "3",
 "calcium liquid softgel": "2",
 "canges-hc nr": "2",
 "citracal petites": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "caltrate gummy bites": "2",
 "caltrate": "2",
 "c-time": "2",
 "caramiphen/phenylpropanolamine": "3",
 "calci-chew": "2",
 "chooz": "2",
 "conzip": "3"}, "b": {"bellaphen-s": "1",
 "benadryl-d allergy plus sinus": "2",
 "brompheniramine/hydrocodone/phenylephrine": "2",
 "brovex-d": "2",
 "benzocaine/phenylephrine/phenylpropanolamine": "3",
 "bromfenex pe": "2",
 "b-vex d": "2",
 "brompheniramine/chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "bicitra": "2",
 "brompheniramine/dextromethorphan/guaifenesin/phenylpropanolamine": "3",
 "baros": "2",
 "brovex pb": "2",
 "bell/ans": "2",
 "brovex peb dm": "2",
 "bel-phen-ergot": "1",
 "betac": "2",
 "bromfed": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "benadryl allergy plus cold": "2",
 "brovex pb cx": "2",
 "bupivacaine/epinephrine": "2",
 "bromfed-pd capsules": "2",
 "brom tann pe": "2",
 "balacall dm": "2",
 "budeprion sr": "3",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "brompheniramine/codeine/phenylpropanolamine": "3",
 "bromatan-dm": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "bromhist-pdx": "2",
 "bellaspas": "1",
 "benadryl allergy plus sinus headache": "2",
 "bronitin": "2",
 "bromfenex pe pediatric": "2",
 "bellamine": "1",
 "basaljel": "2",
 "brompheniramine/dextromethorphan/guaifenesin/phenylephrine": "2",
 "broncho-dilate": "2",
 "bpm pe hc": "2",
 "bupropion": "3",
 "brompheniramine/phenylpropanolamine": "3",
 "bronkaid": "2",
 "budeprion": "3",
 "betatan": "2",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "2",
 "brovex pb dm": "2",
 "beechams all-in-one": "2",
 "brompheniramine/phenylephrine": "2",
 "broncholate syrup": "2",
 "brovex pb c": "2",
 "budeprion xl": "3",
 "brompheniramine/dextromethorphan/phenylephrine": "2",
 "brompheniramine/dihydrocodeine/phenylephrine": "2",
 "broncotron-d": "2",
 "bronkids": "2",
 "brompheniramine/dextromethorphan/phenylpropanolamine": "3",
 "bronkotuss": "2",
 "bellergal-s": "1",
 "bontril pdm": "3",
 "bellalphen": "1",
 "bromaphedrine d": "2",
 "bellamine s": "1",
 "b-tuss": "2",
 "bilberry/evening primrose/flax": "1",
 "broncopectol": "2",
 "banex": "3",
 "bellatal er": "1",
 "benadryl severe allergy plus sinus headache": "2",
 "bpm pe": "2",
 "belladonna/ergotamine/phenobarbital": "1",
 "bayer women's low dose plus calcium": "2",
 "bel-tabs": "1",
 "broncholate": "2",
 "brovex adt": "2",
 "bronkaid mist": "2",
 "brovex peb": "2",
 "bronchial mist with pump": "2",
 "bp allergy dm": "2",
 "banex-la": "3",
 "bellamor": "1",
 "bellahist-d la": "2",
 "bromtuss dm": "2",
 "buproban": "3",
 "barbidonna": "1",
 "brompheniramine/phenylephrine/phenylpropanolamine": "3",
 "bexarotene": "1",
 "bpm pe dm": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "bontril slow release": "3",
 "bellatal": "1",
 "brompheniramine/carbetapentane/phenylephrine": "2",
 "bp allergy jr": "2"}, "e": {"efasin-hd plus": "2",
 "escitalopram": "3",
 "endep": "2",
 "epipen": "2",
 "epinephrine": "2",
 "ephedrine/guaifenesin/theophylline": "2",
 "emsam": "3",
 "endacon dm": "2",
 "epinephrine/lidocaine": "2",
 "equilet": "2",
 "enomine la": "3",
 "ephedrine/phenobarbital/theophylline": "2",
 "excedrin sinus headache": "2",
 "emend": "2",
 "endacof-pd": "2",
 "ex-lax milk of magnesia": "2",
 "exetuss": "2",
 "exetuss-hc": "2",
 "emagrin forte": "2",
 "epi ez pen": "2",
 "effervescent pain relief": "2",
 "eperbel-s": "1",
 "elavil": "2",
 "endal hd": "2",
 "extendryl": "2",
 "exo-tuss": "2",
 "epipen 2-pak": "2",
 "entex er": "2",
 "ephensin-la": "3",
 "elixiral": "1",
 "ethosuximide": "1",
 "equi-tex": "3",
 "emend 2-day": "2",
 "epinephrine/prilocaine": "2",
 "equitan pediatric": "2",
 "efasin-hd": "2",
 "endacon": "2",
 "endal expectorant": "3",
 "extendryl gcp": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "emend 3-day": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "endal cd": "2",
 "ethanol": "2",
 "esimil": "2",
 "etrafon forte": "2",
 "endagen-hd": "2",
 "execof er": "2",
 "e-z-gas ii": "2",
 "entac": "3",
 "epinephrine/etidocaine": "2",
 "extendryl seniors": "2",
 "entex la": "2",
 "epipen jr auto-injector": "2",
 "emend for injection": "2",
 "ethyl alcohol": "2",
 "enduronyl": "2",
 "extendryl pem": "2",
 "effexor xr": "3",
 "extendryl sr": "2",
 "ed a-hist": "2",
 "endal": "2",
 "extendryl jr": "2",
 "endacof-dh": "2",
 "eldepryl": "3",
 "epipen auto-injector": "2",
 "endacof-plus": "2",
 "extra strength mylanta calci tabs": "2",
 "excof": "2",
 "excof-sf": "2",
 "ex-tuss": "3",
 "eskalith": "1",
 "efasin expectorant sf": "3",
 "eskalith-cr": "1",
 "ephedrine": "2",
 "echotuss-hc": "2",
 "endotuss expectorant": "3",
 "extendryl g": "2",
 "exetuss-dm": "2",
 "endotuss-hd": "2",
 "enomine": "3",
 "entre-b": "2",
 "ed a-hist dm": "2",
 "ed a-hist la": "2",
 "evening primrose": "1",
 "ephedrine/guaifenesin": "2",
 "enditussin expectorant": "3",
 "etrafon": "2",
 "exratuss": "2",
 "exgest la": "3",
 "ed dm": "2",
 "ex-histine": "2",
 "endal-hd plus": "2",
 "exetuss-gp": "2",
 "ent": "3",
 "effexor": "3",
 "epipen jr 2-pak": "2",
 "equate allergy &amp; sinus headache": "2",
 "epipen jr": "2",
 "evening primrose oil": "1",
 "ed-tuss hc": "2",
 "enplus-hd": "2",
 "efasin": "2",
 "ephedrine/potassium iodide": "2",
 "empro": "3",
 "enduronyl forte": "2",
 "ester-c": "2",
 "equi-nade": "3",
 "ed-tlc": "2",
 "extendryl chews": "2",
 "ed chlorped d": "2"}, "d": {"duratuss hd": "2",
 "dexbrompheniramine/phenylephrine": "2",
 "didanosine": "2",
 "dytan-d": "2",
 "deconex dm": "2",
 "dayhist-d": "3",
 "drize": "2",
 "demi-regroton": "2",
 "duratuss": "2",
 "delavirdine": "2",
 "dimaphen elixir": "2",
 "donatussin dm suspension": "2",
 "donnatal": "1",
 "de-chlor g": "2",
 "di-gel": "2",
 "deconsal ii": "2",
 "dextromethorphan/pheniramine/phenylephrine": "2",
 "dynatuss hc": "2",
 "deconhist la": "3",
 "duraphen forte": "2",
 "durahist pe": "2",
 "deserpidine": "2",
 "duraphen 1000": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine": "2",
 "delsym night time multi-symptom": "2",
 "dexchlorpheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "dehydrated alcohol": "2",
 "duraphen ii dm": "2",
 "demi-cof": "2",
 "dobutrex": "2",
 "donatussin max": "2",
 "dextromethorphan/guaifenesin/phenylpropanolamine": "3",
 "dexatrim": "3",
 "despec nr drops": "2",
 "dexbrompheniramine/hydrocodone/phenylephrine": "2",
 "ditussin-hc": "2",
 "dewees carminative": "2",
 "dexatrim caffeine free": "3",
 "diupres-500": "2",
 "dexchlorpheniramine/phenylephrine": "2",
 "dynatuss ex": "2",
 "di-gel mint": "2",
 "dical captabs": "2",
 "da ii": "2",
 "drihist": "2",
 "donatussin pediatric": "2",
 "dec-chlorphen drops": "2",
 "dihydrocodeine/phenylephrine/pyrilamine": "2",
 "dicarbosil": "2",
 "dobutamine": "2",
 "despec-sf": "2",
 "dexbrompheniramine/dextromethorphan/phenylephrine/pyrilamine": "2",
 "deconex ir": "2",
 "de-chlor mr": "2",
 "donatussin drops": "2",
 "dacex-a": "2",
 "dopamine": "2",
 "dura-vent/a": "3",
 "duohist dh": "2",
 "duadacin": "3",
 "dehistine": "2",
 "duravent da": "2",
 "duradryl chewable": "2",
 "duravent": "2",
 "duomax": "2",
 "deconsal ct": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "dristan cold multi symptom formula": "2",
 "diphenhydramine/phenylephrine": "2",
 "despec-pd": "2",
 "dimetapp children's cold &amp; chest congestion": "2",
 "dallergy pe": "2",
 "decongex-3": "3",
 "duo-medihaler": "2",
 "deconsal dm tannate": "2",
 "daytime cold &amp; flu": "2",
 "dextromethorphan/phenylephrine": "2",
 "donatussin": "2",
 "donnapine": "1",
 "doxepin": "2",
 "dexphen m": "2",
 "dexall": "2",
 "diupres-250": "2",
 "dacex-pe": "2",
 "dm cold and cough": "3",
 "dimetapp children's multi-symptom cold &amp; flu": "2",
 "desoxyn": "3",
 "dicomal-ph": "2",
 "doxepin topical": "2",
 "drotuss-cp": "2",
 "dihydro-pe": "2",
 "duradryl jr": "2",
 "d-tann": "2",
 "duratuss-a": "2",
 "duo-vil": "2",
 "d-phen 1000": "2",
 "dexcon-pe": "2",
 "dull-c": "2",
 "dimaphen dm": "2",
 "de-chlor hd": "2",
 "dmax": "2",
 "de-chlor hc": "2",
 "delhistine d": "3",
 "dmax pediatric": "2",
 "duragal-s": "1",
 "dihydroxyaluminum sodium carbonate": "2",
 "delhistine dm": "3",
 "decon-a": "2",
 "delsym children's night time cough &amp; cold": "2",
 "diphenmax d": "2",
 "duraphen dm": "2",
 "demazin": "3",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "deserpidine/methyclothiazide": "2",
 "duloxetine": "3",
 "dm-pe-chlor": "2",
 "dual action complete": "2",
 "dime time extended release": "3",
 "dical-d": "2",
 "despec": "2",
 "deconex dmx": "2",
 "duratuss pe": "2",
 "dexcon-dm": "2",
 "dulcolax milk of magnesia": "2",
 "despec cr": "3",
 "duraphen ii": "2",
 "diethylpropion": "3",
 "duradryl": "2",
 "despec dm syrup": "2",
 "duratex": "3",
 "da chewable": "2",
 "dexbrompheniramine/phenylephrine/pyrilamine": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "duratan pe": "2",
 "dallergy": "2",
 "dec-chlorphen": "2",
 "durahistine dm": "3",
 "duradryl sr": "2",
 "dibrom": "3",
 "dryphen": "2",
 "dimetapp children's cold &amp; allergy": "2",
 "desipramine": "2",
 "dec-chlorphen dm": "2",
 "duratuss ac 12": "2",
 "diuretic ap-es": "2",
 "dextromethorphan/phenylpropanolamine": "3",
 "duranest-mpf-epinephrine": "2",
 "denaze": "2",
 "d-tal": "1",
 "dytan-hc": "2",
 "d-tann hc": "2",
 "d-tab": "2",
 "dytan-dm": "2",
 "dcp drops": "2",
 "duramax": "2",
 "delhist d": "3",
 "dexchlorpheniramine/methscopolamine/phenylephrine": "2",
 "dallergy jr": "2",
 "d-tann dm": "2",
 "donatuss dc": "2",
 "di-gel lemon": "2",
 "d-tann cd": "2",
 "diphentann-d": "2",
 "dmax syrup": "2",
 "dimetapp children's cold &amp; cough": "2",
 "desoxyn gradumet": "3",
 "dihydrocodeine/guaifenesin/phenylephrine": "2",
 "deserpidine/hydrochlorothiazide": "2",
 "deconsal ct tannate": "2",
 "dimetapp toddler's drops decongestant plus cough": "2",
 "d-tann ct": "2",
 "dallergy er": "2",
 "donnatal extentabs": "1",
 "dexchlorpheniramine/hydrocodone/phenylephrine": "2",
 "de-chlor dr": "2",
 "drysec": "2",
 "diutensen-r": "2",
 "dilantin": "1",
 "dexfenfluramine": "3",
 "datscan": "2",
 "duradal hd": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "3",
 "dimetapp children's nighttime flu": "2",
 "duravent dpb": "2",
 "duratan dm": "2",
 "dicomal-dh": "2",
 "de-chlor dm": "2",
 "dialume": "2",
 "donatussin dm drops": "2",
 "dallergy syrup": "2",
 "drihist sr": "2",
 "deconex": "2",
 "duratuss gp": "2",
 "deconsal pediatric": "2",
 "deconsal dm": "2",
 "dimetane decongestant": "2",
 "donnaphen": "1",
 "dihydrocodeine/phenylephrine": "2",
 "dallergy drops": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "donatussin syrup": "2",
 "dimetapp toddler's drops decongestant": "2",
 "dicalphos plus d": "2",
 "donatussin dm": "2",
 "dynex la": "2",
 "dex pc": "2",
 "dextromethorphan/phenylephrine/pyrilamine": "2",
 "dexchlorpheniramine/dextromethorphan/phenylephrine": "2",
 "dec-chlorphen dm drops": "2",
 "donatussin dc": "2",
 "dextromethorphan/guaifenesin/phenylephrine": "2",
 "dytan-cd": "2",
 "dur-tann dm": "2",
 "desvenlafaxine": "3",
 "disposable enema": "3",
 "dura-gest": "3",
 "dytan-cs": "2",
 "dmax pediatric drops": "2",
 "dacex-dm": "2"}, "g": {"guaifenex ppa 75": "3",
 "g-phen dm": "2",
 "guaiphen-d 600": "2",
 "guaifenesin/phenylephrine/pyrilamine": "2",
 "gilphex tr": "2",
 "gilchew ir": "2",
 "guaphenyl la": "2",
 "gaviscon regular strength tablets": "2",
 "gencold": "3",
 "guanethidine": "2",
 "guaivent": "3",
 "gendecon": "2",
 "gaviscon regular strength liquid": "2",
 "guaifed pd": "2",
 "guaifenesin/phenylpropanolamine": "3",
 "genexa la": "2",
 "gaviscon extra strength liquid": "2",
 "gelusil": "2",
 "guaifenesin/hydrocodone/pheniramine/phenylephrine/phenylpropanolamine": "3",
 "genamin expectorant": "3",
 "gelpirin-ccf": "3",
 "guaifed caps": "2",
 "guaifenesin/hydrocodone/phenylephrine": "2",
 "guaifenesin/phenylephrine/phenylpropanolamine": "3",
 "gas-x with maalox extra strength": "2",
 "guiaplex hc": "2",
 "gaviscon extra relief formula": "2",
 "guaipax": "3",
 "guaifenex": "3",
 "glutamic acid": "2",
 "guaiphen-pd": "2",
 "genaton": "2",
 "gentex lq": "2",
 "guanethidine/hydrochlorothiazide": "2",
 "guiadex pd": "2",
 "giltuss tr": "2",
 "guaifenesin/phenylephrine": "2",
 "gestuss-hc": "2",
 "giltuss ped-c": "2",
 "guiatex": "3",
 "ginkgo biloba": "2",
 "gentex hc": "2",
 "guaphen ii dm": "2",
 "guiatuss cf": "3",
 "guiavent er": "3",
 "gas-x with maalox": "2",
 "guanadrel": "2",
 "gentex la": "2",
 "guiatex la": "3",
 "genamin": "3",
 "guaifenesin/hydrocodone/pheniramine/phenylpropanolamine/pyrilamine": "3",
 "gaviscon-2": "2",
 "guaiphen-d 1200": "2",
 "guiatussin-cf": "3",
 "gdp-ex": "2",
 "gelhist pediatric": "2",
 "ginkgo": "2",
 "genrx tramadol": "3",
 "g-vent": "3",
 "guaifen pe": "2",
 "guaphen forte": "2",
 "genelan nf": "2",
 "gentex 30": "2",
 "gaviscon extra strength tablets": "2",
 "guiaphen hd": "2",
 "guiatex pe": "2",
 "genaton chewable": "2"}, "f": {"first mouthwash blm": "2",
 "fruit c": "2",
 "fe-tinic 150": "2",
 "flu &amp; severe cold &amp; cough daytime powder": "2",
 "fenesin pe ir": "2",
 "fleet ez-prep": "3",
 "fleet phospho soda": "3",
 "flutuss hc": "2",
 "fenfluramine": "3",
 "fast acting mylanta": "2",
 "forfivo xl": "3",
 "furazolidone": "3",
 "ferrex 150 plus": "2",
 "fluoxetine": "3",
 "fleet prep kit 1": "3",
 "fosaprepitant": "2",
 "fluoxetine/olanzapine": "3",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "fentex": "3",
 "father john's medicine plus": "2",
 "fleet enema extra": "3",
 "fluphenazine": "2",
 "florical": "2",
 "fastin": "3",
 "fero-grad-500": "2",
 "fleet enema": "3",
 "furoxone": "3",
 "fluvoxamine": "3",
 "flumezide": "2"}, "i": {"iohexol": "3",
 "iobenguane i 123": "2",
 "isuprel": "2",
 "iohist d": "3",
 "icar prenatal chewable calcium": "2",
 "isovue-m-200": "3",
 "isovue-300": "3",
 "imipramine": "2",
 "isovue-200": "3",
 "isocarboxazid": "3",
 "isoproterenol": "2",
 "isuprel mistometer": "2",
 "isuprel hcl": "2",
 "iopamidol-370": "3",
 "iodal hd": "2",
 "iohist dm": "3",
 "ionamin": "3",
 "intropin": "2",
 "iosopan": "2",
 "isovue-128": "3",
 "ismelin": "2",
 "iotussin hc": "2",
 "isovue-250": "3",
 "isovue-370": "3",
 "iopamidol": "3",
 "ioflupane i 123": "2",
 "isoproterenol/phenylephrine": "2",
 "ipsatol cough formula": "3",
 "isovue-m-300": "3"}, "h": {"hhr": "2",
 "haloperidol": "2",
 "hycomal dh": "2",
 "hemocyte-c": "2",
 "hydroserpine 1": "2",
 "hyphen-hd": "2",
 "hydroxy compound": "2",
 "highland dm": "3",
 "histalet forte": "3",
 "histinex hc": "2",
 "hydro-reserp": "2",
 "hycophen": "3",
 "hemorid maximum strength": "2",
 "heartburn antacid extra strength": "2",
 "hydrocodone hd": "2",
 "hydrocodone/phenylephrine": "2",
 "hydropres-25": "2",
 "hydropres-50": "2",
 "hydrap-es": "2",
 "highland hc": "2",
 "h-c tussive-nr": "2",
 "hydrofed": "2",
 "hydex pd": "2",
 "halflytely and bisacodyl": "2",
 "hycophen pediatric": "3",
 "hot lemon cough and colds relief dm": "2",
 "hemorid ointment": "2",
 "histamaxd": "2",
 "hista-vadrin": "3",
 "hydrocodone cp": "2",
 "hycomine pediatric": "3",
 "hydrophed": "2",
 "haldol decanoate": "2",
 "hypamine": "3",
 "hemaspan": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydroserp": "2",
 "hydro-dp": "2",
 "h-c tussive": "2",
 "hemorid cream": "2",
 "hyco-dh": "2",
 "hycomine compound": "2",
 "hista-vent da": "2",
 "heb allergy": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "histussin hc liquid": "2",
 "hydroserpine": "2",
 "histatab ph": "2",
 "hi-tuss hc": "2",
 "hyosophen": "1",
 "haley's m-o": "2",
 "hydroflumethiazide/reserpine": "2",
 "haponal": "1",
 "histatan": "2",
 "hydro gp": "2",
 "hydrochlorothiazide/reserpine": "2",
 "hydro-pc ii": "2",
 "hydrocodone pa pediatric": "3",
 "histadecdm": "2",
 "hylorel": "2",
 "histatab plus": "2",
 "hydrophene dh": "2",
 "histussin hc syrup": "2",
 "hydrocodone/phenylephrine/pyrilamine": "2",
 "histinex dm": "3",
 "hycomine": "3",
 "hydrocodone/phenylpropanolamine": "3",
 "hydron cp": "2",
 "harmonyl": "2",
 "hyoscyamine/phenobarbital": "1",
 "hydrocodone/pheniramine/phenylephrine/phenylpropanolamine/pyrilamine": "3",
 "histine-d": "3",
 "hydro-pc ii plus": "2",
 "haldol": "2",
 "histadec": "2"}, "k": {"k-phos original": "2",
 "k-lyte ds": "2",
 "k-lyte": "2",
 "kophane": "3",
 "kgs-pe": "2",
 "kg-hist d": "3",
 "kg-dal hd": "2",
 "k-tan 4": "2",
 "k-tan": "2",
 "kg-dal hd plus": "2",
 "kg hist dm": "3",
 "kie": "2"}, "j": {"j-tan d sr": "2",
 "j-max": "2",
 "jumex": "3",
 "j-tan d": "2"}, "m": {"mydex": "2",
 "meridia": "3",
 "ma huang": "3",
 "maoson": "2",
 "maalox advanced maximum strength": "2",
 "magnesium oxide": "2",
 "milantex maximum strength": "2",
 "myphetane dc": "3",
 "mi-acid ii": "2",
 "methyclothiazide/reserpine": "2",
 "magaldrate plus suspension": "2",
 "m-phen": "2",
 "magnesium carbonate": "2",
 "mapap sinus congestion and pain": "2",
 "myhist-dm": "2",
 "magaldrate": "2",
 "monocal": "2",
 "mega-trim": "3",
 "medihaler-epi": "2",
 "maalox advanced maximum strength chewable": "2",
 "maalox max wild berry": "2",
 "mylagen-ii": "2",
 "maggel": "2",
 "myci spray": "2",
 "mintox extra strength": "2",
 "metahistine d": "3",
 "mag-200": "2",
 "mylagen": "2",
 "maalox max quick dissolve": "2",
 "mucinex children's multi-symptom cold": "2",
 "mephentermine": "2",
 "maalox": "2",
 "medent-pei": "2",
 "montecough": "2",
 "milantex": "2",
 "mazanor": "3",
 "magnesium hydroxide/mineral oil": "2",
 "mylanta maximum strength": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "3",
 "mi-acid double strength": "2",
 "mucus relief pe": "2",
 "magaant": "2",
 "mucus relief complete": "2",
 "methenamine/sodium acid phosphate": "2",
 "montephen": "2",
 "milnacipran": "3",
 "methscopolamine/phenylephrine": "2",
 "methamphetamine": "3",
 "mintox": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "maxiphen dm": "2",
 "masanti ds": "2",
 "mag-carb": "2",
 "maalox plus extra strength": "2",
 "melfiat": "3",
 "maxcosin la": "3",
 "maalox advanced regular strength": "2",
 "mintox maximum strength": "2",
 "mylanta ultra": "2",
 "meprozine": "2",
 "magnebind 200": "2",
 "myelo-kit": "3",
 "medique medi-seltzer": "2",
 "maldroxal plus": "2",
 "mylanta fast acting": "2",
 "mucus relief plus": "2",
 "maxiphen-g dm": "2",
 "milk of magnesia": "2",
 "maalox tc": "2",
 "mintuss g": "2",
 "maalox junior relief chewable": "2",
 "mylanta maximum strength cherry": "2",
 "maxi-tuss sa": "2",
 "mintox plus": "2",
 "maalox regular strength": "2",
 "mintuss mr": "2",
 "mintuss ms": "2",
 "maxiphen cd": "2",
 "mylanta": "2",
 "miraphen pe": "2",
 "mellaril-s": "2",
 "mazindol": "3",
 "mylanta supreme": "2",
 "myhist-pd": "2",
 "maalox plus": "2",
 "mag-ox": "2",
 "multihistamine-d": "3",
 "mepergan": "2",
 "mag-caps": "2",
 "medex-la": "3",
 "miraphen la": "3",
 "maxiphen cdx": "2",
 "multihistamine-d ped": "3",
 "mylanta ultimate strength": "2",
 "marblen": "2",
 "metaraminol": "2",
 "matulane": "3",
 "maalox children's relief": "2",
 "mylanta ds fast acting": "2",
 "mega-c/a plus": "2",
 "methenamine/sodium biphosphate": "3",
 "masanti": "2",
 "maxi-tuss hcx": "2",
 "magnebind 300": "2",
 "maxiphen adt": "2",
 "mucinex cold for kids": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "mag-ox 400": "2",
 "m-end pe": "2",
 "mi-acid": "2",
 "marplan": "3",
 "maxi-tuss hc": "2",
 "marcaine hcl with epinephrine": "2",
 "methotrimeprazine": "2",
 "mapap cold formula": "2",
 "methoxamine": "2",
 "mudrane gg": "2",
 "meperidine/promethazine": "2",
 "medihaler-iso": "2",
 "metrizamide": "3",
 "mag-oxide": "2",
 "maxichlor peh dm": "2",
 "maalox max": "2",
 "monteflu hc": "2",
 "maalox quick dissolve extra strength": "2",
 "maxiphen": "2",
 "maalox antacid antigas regular strength": "2",
 "marax df": "2",
 "medent-pe": "2",
 "mepergan fortis": "2",
 "max hc": "2",
 "mudrane": "2",
 "myphetapp": "3",
 "maalox hrf": "2",
 "marax": "2",
 "mellaril": "2",
 "mintuss dr": "2",
 "metatensin 4": "2",
 "metatensin 2": "2",
 "mylanta child": "2",
 "mintox tablets": "2",
 "magaldrate/simethicone": "2",
 "mylanta gelcap": "2",
 "methdilazine": "2",
 "mesoridazine": "2",
 "mucus relief sinus": "2",
 "marpres": "2"}, "l": {"l-all 12 nf": "2",
 "luminal": "1",
 "levall": "2",
 "linhist-l.a.": "2",
 "liquituss r-dm": "2",
 "levophed bitartrate": "2",
 "lidosite": "2",
 "lusonex plus": "2",
 "levall-12": "2",
 "lowsium plus": "2",
 "luvox": "3",
 "liquibid-pd": "2",
 "lexapro": "3",
 "levsin with phenobarbital": "1",
 "little colds decongestant/cough": "2",
 "l-glutamic acid": "2",
 "little colds multi-symptom": "2",
 "liquihistine dm": "3",
 "liquitussin hc syrup": "2",
 "lohist-dm": "2",
 "lidocaine/sodium bicarbonate": "2",
 "levall 5.0": "2",
 "liquibid-d": "2",
 "levophed": "2",
 "little colds decongestant": "2",
 "lindane topical": "2",
 "limbitrol": "2",
 "liqui-dual citra": "2",
 "lantex-la": "3",
 "losospan plus": "2",
 "lithonate": "1",
 "liquibid-d 1200": "2",
 "luvox cr": "3",
 "liquibid d-r": "2",
 "liquicough hc": "2",
 "linezolid": "3",
 "largon": "2",
 "lowsium": "2",
 "lithotabs": "1",
 "limbitrol ds": "2",
 "l-all 12": "2",
 "lortuss hc": "2",
 "lithium": "1",
 "lithobid": "1",
 "losospan": "2",
 "liquibid pd-r": "2",
 "levoprome": "2",
 "lufyllin-epg": "2",
 "lusonex": "2",
 "liqui-histine-d": "3",
 "liquihistine cs": "3",
 "lusonal": "2",
 "liqui-allergy": "2",
 "liqui-minic infant": "3"}, "o": {"oreticyl forte": "2",
 "oyster shell calcium 500": "2",
 "oyst cal": "2",
 "o-cal-d": "2",
 "omnipaque 240 redi-unit": "3",
 "omnihist l.a.": "2",
 "oysco 500 with d": "2",
 "oracit": "2",
 "omeprazole/sodium bicarbonate": "2",
 "oysco d with calcium": "2",
 "omnipaque 180 redi-unit": "3",
 "ormazine": "2",
 "os-cal 500": "2",
 "oby-cap": "3",
 "os-cal 500 + extra d": "2",
 "os-cal 500 + d": "2",
 "omnipaque 350": "3",
 "omnipaque 210": "3",
 "ordrine at": "3",
 "oyster shell calcium with vitamin d": "2",
 "omnipaque 140": "3",
 "oyster cal": "2",
 "oyst cal 500": "2",
 "osmoprep": "3",
 "omnipaque 180": "3",
 "oyster-d": "2",
 "oyster cal 500": "2",
 "obezine": "3",
 "oyster shell": "2",
 "oysco d": "2",
 "oby-trim": "3",
 "oyster shell calcium": "2",
 "or-phen-ade": "3",
 "ordrine": "3",
 "oyster": "2",
 "oysco 500": "2",
 "ornade spansules": "3",
 "oratuss 12": "2",
 "oreticyl 25": "2",
 "oreticyl 50": "2",
 "orabloc": "2",
 "osteocit d plus": "2",
 "omnihist ii la": "2",
 "omnipaque flexipak": "3",
 "oyster calcium": "2",
 "os-cal": "2",
 "oystercal-d": "2",
 "oyst-cal-d": "2",
 "obephen": "3",
 "omnipaque 300": "3",
 "omnipaque 240": "3",
 "obenix": "3"}, "n": {"neo dm drops": "2",
 "naldecon-cx adult": "3",
 "nuhist": "2",
 "nohist pe": "2",
 "nasohist-dm": "2",
 "nasex-g": "2",
 "novahistine elixir": "2",
 "neut": "2",
 "nohist-dmx": "2",
 "nohist-a": "2",
 "noxafil": "2",
 "nasop12": "2",
 "nephrox": "2",
 "naldecon-dx adult": "3",
 "naldex": "2",
 "nariz": "2",
 "nalex-a sr": "2",
 "nucynta": "3",
 "nazarin hc": "2",
 "neotuss plus": "2",
 "nazarin": "2",
 "naldecon-dx pediatric": "3",
 "nolamine": "3",
 "notuss pd": "2",
 "norel sd": "2",
 "nohist plus": "2",
 "norel ex": "2",
 "nardil": "3",
 "naldelate": "3",
 "norel la": "2",
 "naldelate dx pediatric": "3",
 "nortriptyline": "2",
 "nescon-pd": "2",
 "naldecon-dx childrens": "3",
 "nortuss-de": "2",
 "nephro calci": "2",
 "nalex-a": "2",
 "n ice with vitamin c": "2",
 "nalspan": "3",
 "nalgest": "3",
 "naldecon": "3",
 "norpramin": "2",
 "neo hc": "2",
 "nohist-pdx": "2",
 "non-pseudo sinus pain &amp; pressure": "2",
 "naldelate dx childrens": "3",
 "norel dm": "2",
 "nucynta er": "3",
 "norepinephrine": "2",
 "nalex-dh": "2",
 "nasohist pediatric": "2",
 "nexphen pd": "2",
 "nasatuss": "2",
 "nasex": "2",
 "nasotuss": "2",
 "nasahist la": "3",
 "nalphen dx childrens": "3",
 "nasop": "2",
 "nohist plus jr": "2",
 "nasal decongestant pe": "2",
 "nalda-relief pediatric": "3",
 "nalgestic pediatric": "3",
 "notuss-pe": "2",
 "nalphen dx pediatric": "3",
 "nohist": "2",
 "neocitran non drowsy extra strength cold and flu": "2",
 "nalphen": "3",
 "norel sr": "2",
 "novahistine": "2",
 "norisodrine with calcium iodine": "2",
 "novahistine dh": "2",
 "non-pseudo cold relief": "2",
 "naldecon-ex pediatric": "3",
 "ny-tannic": "2",
 "nalex a 12": "2",
 "norel": "3",
 "nariz hc": "2",
 "neo-synephrine": "2",
 "niferex-150": "2"}, "q": {"quindal": "2",
 "qv-allergy": "2",
 "quadratuss": "2",
 "quelidrine": "2",
 "quindal hd plus": "2",
 "quad tann pediatric": "2",
 "quadrapax": "1",
 "quintex": "2",
 "quad-tuss": "2",
 "q-tussin cf": "2",
 "qual-tussin dc": "2",
 "q-hist la": "2",
 "quad tann": "2",
 "quindal hd": "2",
 "qual-tussin pediatric": "2",
 "quartuss dm": "2",
 "quadrinal": "2",
 "qual-tussin": "2",
 "quad tuss pediatric": "2",
 "quartuss": "2"}, "p": {"protid": "2",
 "pheniramine/phenylephrine nasal": "2",
 "primatene": "2",
 "phillips' cramp-free": "2",
 "phenavent la": "2",
 "poly-tussin ac": "2",
 "poly-histine cs": "3",
 "plegine": "3",
 "prolex pd": "2",
 "pediacon dx": "3",
 "phendal-hd": "2",
 "prelu-2": "3",
 "pe-hist dm": "2",
 "phenylephrine/potassium guaiacolsulfonate": "2",
 "prohist lq": "2",
 "phlemex forte": "2",
 "panshape m": "3",
 "pedituss": "2",
 "promethazine with codeine": "2",
 "prolex d": "2",
 "pcm": "2",
 "primatene mist": "2",
 "preparation h cream with maximum strength pain relief": "2",
 "prochlorperazine": "2",
 "phenavent": "2",
 "promethazine vc": "2",
 "posture-d h/p": "2",
 "phenabid dm": "2",
 "pepto children's": "2",
 "phenyl 15/12mg": "2",
 "prolixin": "2",
 "promethazine with dm": "2",
 "pyril mal phenyl hcl": "2",
 "phenylpropanolamine": "3",
 "prohistine-d": "3",
 "pdm gg": "2",
 "potassium citrate": "2",
 "pd-hist d": "2",
 "phenadoz": "2",
 "phenflu cd": "2",
 "potassium citrate/sodium citrate": "2",
 "phenyl-t": "2",
 "phenflu dm": "2",
 "procarbazine": "3",
 "phenylfenesin la": "3",
 "poly tan dm": "2",
 "poly dm": "3",
 "phillips' haleys m-o": "2",
 "phenylfenesin": "3",
 "promethazine hcl with codeine": "2",
 "pepcid complete": "2",
 "phenylephrine/promethazine": "2",
 "pendex": "2",
 "polycitra": "2",
 "phenazine 50": "2",
 "phenavent d": "2",
 "permitil": "2",
 "protuss tablet": "3",
 "polycitra-k": "2",
 "poly histine dm": "3",
 "prohistine dm": "3",
 "parnate": "3",
 "paxil": "3",
 "phentermine": "3",
 "phosphate laxative": "3",
 "pe-guai": "2",
 "phenytek": "1",
 "pediacof": "2",
 "pb-hyos": "1",
 "phendiet-105": "3",
 "pondimin": "3",
 "phendacof plus": "2",
 "potassium acetate/potassium bicarbonate/potassium citrate": "2",
 "potassium bicarbonate/sodium bicarbonate": "2",
 "poly hist dhc": "2",
 "polytine cs": "3",
 "poly hist hc": "2",
 "poly tussin ex": "2",
 "pediatex-ct": "2",
 "poly tan d": "2",
 "pristiq": "3",
 "promethazine vc with codeine": "2",
 "poly cs": "3",
 "phenadex": "3",
 "pedia-lax enema": "3",
 "p chlor gg": "2",
 "protriptyline": "2",
 "prehist d": "2",
 "phentex": "3",
 "pro-fast sr": "3",
 "potassium bitartrate/sodium bicarbonate": "2",
 "prelu-2 tr": "3",
 "poly-tussin hd": "2",
 "poly hist pd": "2",
 "profen la": "3",
 "pyrlex pd": "2",
 "poly-tussin dhc": "2",
 "pro-fast sa": "3",
 "pd-cof": "2",
 "phenylephrine/pramoxine topical": "2",
 "phenytoin sodium, prompt": "1",
 "propiomazine": "2",
 "pd-hist d drops": "2",
 "procot": "2",
 "phenelzine": "3",
 "phena-s 12": "2",
 "posaconazole": "2",
 "ppa-gg cr": "3",
 "prop-a-hist": "3",
 "pexeva": "3",
 "polythiazide/reserpine": "2",
 "pro-med": "2",
 "phena-s": "2",
 "p-hist": "2",
 "poly-tussin ex syrup": "2",
 "phendimetrazine": "3",
 "pyrichlor pe": "2",
 "phenergan vc with codeine": "2",
 "polytine d": "3",
 "pancof-pd": "2",
 "phenylephrine": "2",
 "propagest": "3",
 "poly hist forte": "2",
 "pyril d": "2",
 "prozac weekly": "3",
 "poly hist dm": "2",
 "phenflu cdx": "2",
 "prozac": "3",
 "phentride": "3",
 "pediacare children's multi-symptom cold": "2",
 "pediacare children's decongestant": "2",
 "phencarb gg": "2",
 "phentercot": "3",
 "pyril tann-12": "2",
 "pamelor": "2",
 "pediacare children's allergy &amp; cold": "2",
 "phenylephrine/pyrilamine": "2",
 "poly-d": "3",
 "promethazine vc plain": "2",
 "prograf": "2",
 "phenyl 7.5/6mg": "2",
 "pd-cof drops": "2",
 "promazine": "2",
 "prolixin enanthate": "2",
 "polytine dm": "3",
 "potassium acid phosphate": "2",
 "phenylhistine": "2",
 "panatuss dxp": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "primatene dual action": "2",
 "phenoject-50": "2",
 "paroxetine": "3",
 "polycitra-lc": "2",
 "p chlor dm": "2",
 "propan": "3",
 "phenergan fortis": "2",
 "poly-histine-d": "3",
 "pcm allergy": "2",
 "phenobarbital": "1",
 "potassium bicarbonate/potassium citrate": "2",
 "poly-tussin": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "pheniramine/phenylpropanolamine/pyrilamine": "3",
 "prohist": "2",
 "protexin": "2",
 "paxil cr": "3",
 "pedia-lax chewable tablets": "2",
 "partuss-la": "3",
 "phenyldrine": "3",
 "perphenazine": "2",
 "prudoxin": "2",
 "promethazine with dextromethorphan": "2",
 "pyrroxate": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenergan vc": "2",
 "pro-red ac": "2",
 "p-tann d": "2",
 "pheniramine/phenylpropanolamine/phenyltoloxamine/pyrilamine": "3",
 "phenchlor tannate pediatric": "2",
 "promethegan": "2",
 "phenavent ped": "2",
 "prolixin decanoate": "2",
 "poly-tussin dm": "2",
 "phenytoin": "1",
 "pediatan d": "2",
 "primrose oil": "1",
 "pro-fast hs": "3",
 "phena-plus": "2",
 "pyril dm": "2",
 "poly-citra k crystals": "2",
 "phlemex-pe": "2",
 "pulmari": "2",
 "phenylephrine hd": "2",
 "phentex-la": "3",
 "phenergan with dextromethorphan": "2",
 "phendiet": "3",
 "phenylephrine/triprolidine": "2",
 "prohist cd": "2",
 "phillips' milk of magnesia": "2",
 "promethazine vc w/codeine": "2"}, "s": {"sitrex": "2",
 "sertraline": "3",
 "sildec-pe dm": "2",
 "surpass": "2",
 "sildec-pe drops": "2",
 "selgene": "3",
 "sinequan": "2",
 "sinus congestion &amp; pain": "2",
 "sudafed pe children's nasal decongestant": "2",
 "selegiline": "3",
 "serathide": "2",
 "sparine": "2",
 "sodium lactate": "2",
 "sodium citrate": "2",
 "sanorex": "3",
 "sinupan": "2",
 "sympak dm": "2",
 "stelazine": "2",
 "scot-tussin original": "2",
 "sudafed pe cold &amp; cough": "2",
 "serentil": "2",
 "savella": "3",
 "sympak ii": "2",
 "sudafed pe children's cold &amp; cough": "2",
 "sina-12x": "2",
 "salutensin-demi": "2",
 "super calcium": "2",
 "sudogest pe": "2",
 "selfemra": "3",
 "sudafed pe non-drying sinus": "2",
 "statuss": "3",
 "saleto-d": "3",
 "salutensin": "2",
 "suprep": "3",
 "sildec-pe": "2",
 "statobex": "3",
 "sibutramine": "3",
 "sudafed pe severe cold": "2",
 "ser-ap-es": "2",
 "spec-t sore throat/decongestant lozenges": "3",
 "solfoton": "1",
 "sinulin": "3",
 "sudafed pe sinus headache": "2",
 "sitrex pd": "2",
 "sensorcaine with epinephrine": "2",
 "simuc": "2",
 "sinutuss dm": "2",
 "simuc-hd": "2",
 "surpass extra strength": "2",
 "sudafed pe nasal decongestant": "2",
 "scopohist-pe": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "seradex-la": "2",
 "sympak": "2",
 "sympak pdx": "2",
 "s-t forte": "3",
 "sarafem": "3",
 "sunkist vitamin c": "2",
 "sonahist-dm": "2",
 "scopohist syrup": "2",
 "sodium bicarbonate/tartaric acid": "2",
 "sinucon": "3",
 "sildec-pe dm drops": "2",
 "spastrin": "1",
 "surmontil": "2",
 "sodium bicarbonate": "2",
 "suprenza": "3",
 "sinus congestion and pain daytime cool ice": "2",
 "suprep bowel prep kit": "3",
 "simuc-gp": "2",
 "sinus &amp; allergy pe": "2",
 "statuss green": "3",
 "sinucon pediatric": "3",
 "serpex": "2",
 "septocaine": "2",
 "sedecal d": "2",
 "sinuvent pe": "2",
 "seradex": "2",
 "sudafed pe nighttime cold": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "sus-phrine injection": "2",
 "sinuvent": "3",
 "spasmolin": "1",
 "sirolimus": "2",
 "sudex": "2",
 "sensorcaine-mpf with epinephrine": "2",
 "serpazide": "2",
 "sudafed pe triple action": "2",
 "symbyax": "3",
 "spasquid": "1",
 "safetussin cd": "2",
 "sudafed pe sinus &amp; allergy": "2",
 "sonahist": "2",
 "servira": "1",
 "sodium acetate": "2",
 "silenor": "2",
 "sodium bicarbonate/sodium citrate": "2",
 "stamoist la": "3",
 "sinapils": "3",
 "sinodec": "2",
 "suphedrine pe": "2"}, "r": {"ri-mag": "2",
 "robafen cf": "2",
 "re-drylex": "2",
 "ron-acid plus": "2",
 "rolaids regular strength": "2",
 "ricobid nr": "2",
 "refenesen chest congestion relief pe": "2",
 "rauwolfia 1x": "2",
 "riopan plus": "2",
 "robitussin peak cold nasal relief": "2",
 "renacidin irrgiation": "2",
 "riopan": "2",
 "regroton": "2",
 "rondameth": "2",
 "robitussin peak cold multi-symptom cold": "2",
 "resaid": "3",
 "rhinolar": "3",
 "rescon-mx": "2",
 "rulox plus": "2",
 "robitussin night time cough &amp; cold": "2",
 "rolaids extra strength plus gas relief softchews": "2",
 "resperal": "2",
 "relcof pe": "2",
 "ryna-12s": "2",
 "rhinatate pediatric": "2",
 "ryna-12x": "2",
 "rauwolfemms": "2",
 "rynatuss": "2",
 "relasin-hc": "2",
 "rynesa 12s": "2",
 "risacal-d": "2",
 "rhinabid pd": "2",
 "rondex-dm": "2",
 "re all 12": "2",
 "rhinogesic": "2",
 "rindal hd plus": "2",
 "rescriptor": "2",
 "riopan plus 2": "2",
 "ron acid": "2",
 "rhinatate-nf": "2",
 "redur-pcm": "2",
 "rhinolar-ex 12": "3",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "rybix odt": "3",
 "relahist-dm": "2",
 "rolatuss": "2",
 "respahist ii": "2",
 "relcof dn pe": "2",
 "respa-pe": "2",
 "robitussin night time cough, cold &amp; flu": "2",
 "rescon-gg": "2",
 "rauzide": "2",
 "rhinacon a": "2",
 "renese-r": "2",
 "relera": "2",
 "renacidin": "2",
 "ryna-12": "2",
 "r-tannamine": "2",
 "robitussin children's cough &amp; cold cf": "2",
 "rulox 1": "2",
 "reme tussin dm": "2",
 "ru-hist forte": "2",
 "rhinabid": "2",
 "rynatan-s pediatric": "2",
 "rentamine pediatric": "2",
 "respa c&amp;c": "2",
 "r-tannic-s a/d": "2",
 "rescon-jr": "2",
 "robitussin cough &amp; cold cf": "2",
 "ralix": "2",
 "re-pb hyos elixir": "1",
 "rhinolar-ex": "3",
 "rondec-dm": "2",
 "rondec": "2",
 "rondex": "2",
 "rexavite 150": "2",
 "r-tannate pediatric": "2",
 "r-tannate": "2",
 "ru-tuss with hydrocodone": "3",
 "reserpine": "2",
 "re-drylex jr": "2",
 "robitussin peak cold nighttime nasal relief": "2",
 "rentamine": "2",
 "rolatuss with hydrocodone": "3",
 "relacon-hc": "2",
 "rhindecon": "3",
 "rindal hpd": "2",
 "r-tannamine pediatric": "2",
 "rapamune": "2",
 "rinate pediatric": "2",
 "rybix": "3",
 "rymed-tr": "3",
 "rolaids extra strength": "2",
 "ricotuss": "2",
 "rynatuss pediatric": "2",
 "rondex-dm drops": "2",
 "rolaids extra strength softchews": "2",
 "rondex drops": "2",
 "rescon": "2",
 "reserpine/trichlormethiazide": "2",
 "reme hist dm": "2",
 "rynatan": "2",
 "ry-tann": "2",
 "rindal-hd": "2",
 "rolatuss-sr": "3",
 "ryzolt": "3",
 "rhinahist": "2",
 "ry-t-12": "2",
 "riopan plus double strength": "2",
 "relacon-hc nr": "2",
 "rhinatate": "2",
 "reluri": "2",
 "rhinocaps": "3",
 "re dcp drops": "2",
 "rauwolfia serpentina": "2",
 "rolaids multi-symptom": "2",
 "rasagiline": "2",
 "rulox": "2",
 "r-tanna": "2",
 "ricobid-d": "2",
 "rapiflux": "3",
 "rynatan pediatric": "2",
 "redux": "3"}, "u": {"urocit-k": "2",
 "ultram": "3",
 "ultram odt": "3",
 "ultra mylanta calci tabs": "2",
 "upcal d": "2",
 "urban ds": "2",
 "url-tannate": "2",
 "uni-multihist d ped": "3",
 "uni-lan ii": "2",
 "ultram er": "3",
 "uni decon": "3",
 "uni-hist pdx syrup": "2",
 "uni all 12": "2",
 "uni-lev 5.0": "2",
 "ultracet": "3",
 "uroqid-acid no2": "2",
 "urban": "2",
 "uni-lan": "2",
 "utac": "2",
 "uni multihist dm": "3",
 "uni serp": "2",
 "unipres": "2",
 "uni tussin cf": "3",
 "ulr-la": "3",
 "urogesic blue": "3",
 "url-tannate pediatric": "2",
 "uni tuss hc": "2",
 "uro-mag": "2",
 "uni-tricof hc": "2",
 "uni-tann cs": "2",
 "uni-tann d": "2",
 "uro-phosphate": "3",
 "uni-tuss dm": "2"}, "t": {"theraflu warming relief daytime severe cough &amp; cold": "2",
 "tenuate dospan": "3",
 "tusso-dm": "2",
 "trital dm": "2",
 "tylenol plus children's flu": "2",
 "tramadol": "3",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "trihist-d": "3",
 "theomax df": "2",
 "tricitrasol": "2",
 "titralac plus liquid": "2",
 "tannate 12d s": "2",
 "tylenol cold multi-symptom daytime": "2",
 "twinject": "2",
 "tri-k": "2",
 "tramal sr": "3",
 "tranylcypromine": "3",
 "t-diet": "3",
 "tylenol cold head congestion severe": "2",
 "tanamine": "2",
 "tusdec-dm": "2",
 "tri-gestan s": "2",
 "thiethylperazine": "2",
 "trexbrom": "2",
 "t- koff": "3",
 "tricodene forte": "3",
 "tylenol cold head congestion daytime": "2",
 "tuss tan": "2",
 "tums extra strength 750": "2",
 "tussafed-hc": "2",
 "tussall": "2",
 "tepanil": "3",
 "temaril": "2",
 "tussafed-ex drops": "2",
 "tussirex sugar free": "2",
 "tricodene nn": "3",
 "tavist-d": "3",
 "tylenol cold multi-symptom severe": "2",
 "trihist-cs": "3",
 "tylenol sinus congestion &amp; pain daytime": "2",
 "tl-hist dm": "2",
 "therahist": "3",
 "triotann-s pediatric": "2",
 "tears again hydrate": "1",
 "teramine er": "3",
 "triple tannate pediatric": "2",
 "tanamine pediatric": "2",
 "trituss-a": "2",
 "tridal": "2",
 "tuss-ds": "2",
 "tylenol plus children's cold": "2",
 "tramedo": "3",
 "triac expectorant": "3",
 "trituss-er": "2",
 "tussive hc": "2",
 "triant-hc": "2",
 "tums freshers": "2",
 "tri-tannate": "2",
 "tritan": "2",
 "tylenol cold head congestion nighttime": "2",
 "triaminic chest &amp; nasal congestion": "2",
 "tri-hydroserpine": "2",
 "trifluoperazine": "2",
 "tums dual action": "2",
 "tussbid": "2",
 "tums regular strength": "2",
 "tri-tannate pediatric": "2",
 "trihist dm": "3",
 "tylenol cold multi-symptom nighttime": "2",
 "theraflu warming relief cold and chest congestion": "2",
 "trituss-a drops": "2",
 "theraflu thin strips daytime cold and cough": "2",
 "tussplex dm": "2",
 "tylenol plus children's cold &amp; cough": "2",
 "triotann-s": "2",
 "tussirex": "2",
 "trimipramine": "2",
 "tempo": "2",
 "trituss": "2",
 "tramapap": "3",
 "torecan": "2",
 "triaminic": "3",
 "tofranil-pm": "2",
 "threamine dm": "3",
 "tricodene pediatric": "3",
 "theraflu cold &amp; sore throat": "2",
 "targretin": "1",
 "tusana-d": "2",
 "tanoral": "2",
 "tanahist-d": "2",
 "tri tann pediatric": "2",
 "tuss-hc": "2",
 "triphenicol": "3",
 "triaminic cold &amp; allergy": "2",
 "tanoral pediatric": "2",
 "tannihist-12d": "2",
 "tussafed-hcg": "2",
 "tums ultra 1000": "2",
 "triaminic thin strips cold with stuffy nose": "2",
 "tussi-12d s": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "thorazine": "2",
 "triac": "3",
 "triaminic day time cold &amp; cough": "2",
 "tricitrates": "2",
 "tussex": "2",
 "tanabid sr": "2",
 "tromethamine": "2",
 "theraflu warming relief sinus &amp; cold": "2",
 "tusdec-hc": "2",
 "theraflu multi-symptom severe cold": "2",
 "theraflu nighttime severe cold &amp; cough caplets": "2",
 "theraflu warming relief caplets nighttime multi-symptom cold": "2",
 "tuss tan pediatric": "2",
 "theraflu cold &amp; cough": "2",
 "titralac plus": "2",
 "tl-hist cd": "2",
 "tenuate": "3",
 "titralac": "2",
 "tannate pediatric": "2",
 "theraflu flu &amp; sore throat": "2",
 "triplex ad": "2",
 "triflupromazine": "2",
 "teramine": "3",
 "twin-k": "2",
 "triavil": "2",
 "tapentadol": "3",
 "tusso-dmr": "2",
 "teldrin": "3",
 "trimeprazine": "2",
 "tylenol cough &amp; severe congestion daytime": "2",
 "tedrigen": "2",
 "tusso-xr": "2",
 "tham": "2",
 "theraflu daytime severe cold &amp; cough": "2",
 "tussin cf": "2",
 "tylenol sinus congestion &amp; pain severe": "2",
 "tanni-hist 12 rf": "2",
 "tums plus": "2",
 "tylenol plus children's multi-symptom cold": "2",
 "triaminic night time cold &amp; cough": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "tri-vent dpc": "2",
 "trimal dh": "2",
 "tannate-12": "2",
 "trital sr": "2",
 "tofranil": "2",
 "tylenol cold multi-symptom nighttime liquid": "2",
 "tussar dm": "2",
 "tylenol sinus congestion &amp; pain nighttime": "2",
 "theodrine": "2",
 "triplex dm": "2",
 "tylenol cold head congestion day and night": "2",
 "tussall-er": "2",
 "tylenol allergy multi-symptom": "2",
 "triaminic thin strips day time cold &amp; cough": "2",
 "tramahexal sr": "3",
 "thioridazine": "2",
 "twinject auto-injector two pack": "2",
 "triotann": "2",
 "tussi-12d": "2",
 "trilafon": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "tums kids": "2",
 "triall": "2",
 "tussplex": "2",
 "tussinate": "2",
 "tylenol cold &amp; flu severe": "2",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tramal": "3",
 "tetra tannate pediatric": "2",
 "tri-hist pediatric": "2",
 "tussidex": "2",
 "triotann pediatric": "2",
 "tylenol plus children's cold &amp; stuffy nose": "2",
 "tums smoothies": "2",
 "theraflu sinus &amp; cold": "2",
 "tannate v dm": "2",
 "tacaryl": "2",
 "theraflu warming relief caplets daytime multi-symptom cold": "2",
 "tusscough dhc": "2",
 "tacrolimus": "2",
 "twinject auto-injector": "2",
 "tri-dec": "3",
 "tylenol allergy multi-symptom nighttime": "2",
 "tuss-pd": "2",
 "tussafed-ex": "2"}, "w": {"wellbutrin xl": "3",
 "we allergy": "2",
 "westrim": "3",
 "wellbid-d 1200": "2",
 "wellbutrin sr": "3",
 "wyamine sulfate injection": "2",
 "wellesse liquid calcium with vitamin d": "2",
 "wellbid-d": "2",
 "west-decon m": "2",
 "westrim la": "3",
 "wellbutrin": "3",
 "west-decon": "3"}, "v": {"vazotan": "2",
 "vivactil": "2",
 "videx": "2",
 "ventuss syrup": "2",
 "vanex-hd": "2",
 "viravan-s": "2",
 "vazotab": "2",
 "viravan-t": "2",
 "vazobid-pd": "2",
 "vitamin c": "2",
 "vazobid": "2",
 "v-tan dm": "2",
 "visonex": "2",
 "v-gan-50": "2",
 "viibryd": "3",
 "vetuss hc syrup": "3",
 "vanex forte": "3",
 "vilazodone": "3",
 "v-cof": "2",
 "vasotuss hc": "2",
 "vanex-la": "3",
 "vasoxyl": "2",
 "vivacaine": "2",
 "vazotuss hc": "2",
 "venlafaxine": "3",
 "vanatrip": "2",
 "vitamin c with rose hips": "2",
 "vita-c": "2",
 "visqid aa": "2",
 "vanex forte-r": "3",
 "vitron-c": "2",
 "vitamin c tr": "2",
 "vitelle irospan": "2",
 "vitron-c-plus": "2",
 "vicks dayquil sinus": "2",
 "vicks dayquil cold &amp; flu symptom relief plus vitamin c": "2",
 "v-gan-25": "2",
 "v-tann": "2",
 "viravan-dm": "2",
 "viratan-dm": "2",
 "vicks formula 44d cough &amp; sinus congestion relief": "2",
 "vicks dayquil cold &amp; flu relief": "2",
 "vicks formula 44 custom care congestion": "2",
 "v-hist": "2",
 "videx ec": "2",
 "vazol-d": "2",
 "vanacof cd": "2",
 "visicol": "3",
 "vicks vitamin c drops": "2"}, "y": {"y-cof dm": "2"}, "x": {"xylocaine-mpf-epinephrine": "2",
 "xedec": "2",
 "x-hist dm": "2",
 "xiratuss": "2",
 "x-hist": "2",
 "xirahistdm": "2",
 "xirahist": "2",
 "xpect-pe": "2",
 "xedec ii": "2",
 "xylocaine with epinephrine": "2",
 "xylocaine hcl with epinephrine": "2",
 "xylocaine with epinephrine dental cartridges": "2"}, "z": {"zotex-12": "2",
 "zyrphen": "2",
 "zotex gpx": "2",
 "zotex pediatric": "2",
 "zyvox": "3",
 "zonalon": "2",
 "zotex-gp": "2",
 "zegerid otc": "2",
 "zamadol": "3",
 "zotex lax": "2",
 "zantryl": "3",
 "zydol": "3",
 "zotex-ex": "2",
 "zotex-pe": "2",
 "zarontin": "1",
 "zyban": "3",
 "z-dex": "2",
 "zelapar": "3",
 "zotex-dm": "2",
 "zegerid": "2",
 "z-dex 12 d": "2",
 "zotex-c": "2",
 "zoloft": "3",
 "z-cof hc": "2",
 "zotex-12d": "2",
 "zotex hc": "2",
 "z-tuss dm": "2",
 "zotex": "2"}}];