interactions["bitolterol,tornalate"]=["bitolterol,tornalate", {"a": {"azithromycin dose pack": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aristocort": "1",
 "atacand hct": "2",
 "aloxi": "2",
 "adlone-40": "1",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "alfuzosin": "2",
 "artemether/lumefantrine": "2",
 "amitriptyline": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "aldoril": "2",
 "aralen hydrochloride": "2",
 "aldoril 15": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "aerospan hfa": "1",
 "abarelix": "2",
 "atomoxetine": "2",
 "asbron g": "2",
 "adriamycin rdf": "2",
 "a-hydrocort": "1",
 "accuretic": "2",
 "aerolate iii": "2",
 "adriamycin": "2",
 "azmacort": "1",
 "aristopak": "1",
 "acebutolol": "2",
 "antinaus 50": "2",
 "avelox": "2",
 "anergan 50": "2",
 "adrenocot": "1",
 "aerobid": "1",
 "asenapine": "2",
 "atenolol": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "acthar": "1",
 "asmanex twisthaler": "1",
 "a-methapred": "1",
 "acetocot": "1",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "azithromycin": "2",
 "aerobid-m": "1",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "advair hfa": "1",
 "aralen": "2",
 "aristocort for injection": "1",
 "asendin": "2",
 "aminophylline": "2",
 "apomorphine": "2",
 "adriamycin pfs": "2",
 "aldoril 25": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "astemizole": "2",
 "ami-rax": "2",
 "aldoril d50": "2",
 "acetazolamide": "2",
 "ak-beta": "3",
 "advair diskus": "1",
 "asthmacon": "2",
 "apokyn": "2",
 "adapin": "2",
 "apo-go pen": "2",
 "asmalix": "2",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "adlone-80": "1",
 "azithromycin/trovafloxacin": "2",
 "apresazide": "2",
 "aquacot": "2",
 "aristospan": "1",
 "aerolate sr": "2",
 "aquaphyllin": "2",
 "aldoclor-250": "2",
 "apo-go": "2",
 "aerolate jr": "2",
 "alvesco": "1",
 "aliskiren/hydrochlorothiazide": "2",
 "adbeon": "1",
 "aldoclor-150": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "aralen phosphate": "2",
 "arsenic trioxide": "2",
 "avalide": "2",
 "atenolol/chlorthalidone": "2",
 "amoxapine": "2",
 "acetaminophen/propoxyphene": "2",
 "aminophylline/guaifenesin": "2",
 "aridol": "2",
 "azilect": "2",
 "aldoril d30": "2",
 "acthrel": "1",
 "amiloride/hydrochlorothiazide": "2",
 "adrenocot la": "1",
 "acth": "1",
 "anafranil": "2",
 "avelox i.v.": "2",
 "aventyl hydrochloride": "2",
 "atapryl": "2",
 "aquazide h": "2",
 "anzemet": "2",
 "amturnide": "2",
 "amiodarone": "2",
 "aldactazide": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "aquatensen": "2"}, "c": {"chlorthalidone/clonidine": "2",
 "cortrosyn": "1",
 "cortef": "1",
 "chlorothiazide/methyldopa": "2",
 "codeine/promethazine": "2",
 "comtan": "2",
 "compro": "2",
 "captopril/hydrochlorothiazide": "2",
 "cipro": "2",
 "chloroquine": "2",
 "cosopt": "3",
 "coreg": "3",
 "corzide": "3",
 "cortifoam": "1",
 "capozide 50/25": "2",
 "choledyl": "2",
 "carteolol ophthalmic": "3",
 "celestone": "1",
 "chlorpromazine": "2",
 "cordarone iv": "2",
 "ciclesonide": "1",
 "ciprofloxacin": "2",
 "cortone acetate": "1",
 "corvert": "2",
 "cotolone": "1",
 "cipro i.v.": "2",
 "clozapine synthon": "2",
 "cymbalta": "2",
 "compazine spansule": "2",
 "combigan": "3",
 "capozide 25/15": "2",
 "clomipramine": "2",
 "carbidopa/entacapone/levodopa": "2",
 "cosopt pf": "3",
 "clorpres": "2",
 "colocort": "1",
 "chlorthalidone/reserpine": "2",
 "chlorthalidone": "2",
 "capozide 50/15": "2",
 "choledyl sa": "2",
 "cerubidine": "2",
 "cortisone": "1",
 "carteolol": "3",
 "corgard": "3",
 "caprelsa": "2",
 "copd": "2",
 "candesartan/hydrochlorothiazide": "2",
 "corzide 80/5": "3",
 "cipro cystitis pack": "2",
 "clinalog": "1",
 "corzide 40/5": "3",
 "clopine": "2",
 "chlorothiazide": "2",
 "cordarone": "2",
 "complera": "2",
 "clinacort": "1",
 "clarithromycin": "2",
 "carvedilol": "3",
 "clozaril": "2",
 "cosyntropin": "1",
 "cort-k": "1",
 "celestone phosphate": "1",
 "corticotropin": "1",
 "cipro xr": "2",
 "compazine": "2",
 "coartem": "2",
 "capozide": "2",
 "capozide 25/25": "2",
 "corticorelin": "1",
 "cell-u-jec": "1",
 "cartrol": "3",
 "chlorothiazide/reserpine": "2",
 "carbex": "2",
 "clozapine": "2",
 "cortenema": "1",
 "coreg cr": "3",
 "crizotinib": "2",
 "cardioquin": "2",
 "codeine phosphate-promethazine hcl": "2",
 "carozide": "2",
 "celestone soluspan": "1",
 "codeine/phenylephrine/promethazine": "2",
 "cisapride": "2"}, "b": {"brondelate": "2",
 "betaxolol": "2",
 "blocadren": "3",
 "beta-phos/ac": "1",
 "biaxin xl": "2",
 "brevibloc": "2",
 "bisoprolol": "2",
 "broncodur": "2",
 "broncomar gg": "2",
 "betoptic": "2",
 "betagan c-cap": "3",
 "biaxin": "2",
 "budesonide/formoterol": "1",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "betoptic s": "2",
 "benzthiazide": "2",
 "betimol": "3",
 "bumetanide": "2",
 "beclovent": "1",
 "betagan": "3",
 "balacet": "2",
 "budesonide": "1",
 "benazepril/hydrochlorothiazide": "2",
 "benicar hct": "2",
 "betamethasone": "1",
 "bronchial": "2",
 "bystolic": "2",
 "brimonidine/timolol ophthalmic": "3",
 "betaxolol ophthalmic": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "baycadron": "1",
 "betapace af": "3",
 "bepridil": "2",
 "bronkodyl": "2",
 "bubbli-pred": "1",
 "bendroflumethiazide": "2",
 "bumex": "2",
 "bendroflumethiazide/nadolol": "3",
 "beclomethasone": "1",
 "betapace": "3"}, "e": {"ery-tab": "2",
 "endep": "2",
 "ezide": "2",
 "enduronyl": "2",
 "emtricitabine/rilpivirine/tenofovir": "2",
 "eribulin": "2",
 "effexor xr": "2",
 "ephedrine/guaifenesin/theophylline": "2",
 "emsam": "2",
 "edecrin": "2",
 "etrafon": "2",
 "epirubicin": "2",
 "ezogabine": "2",
 "erythrocin lactobionate": "2",
 "edarbyclor": "2",
 "edurant": "2",
 "eldepryl": "2",
 "emblon": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "e.e.s.-400": "2",
 "eryc": "2",
 "e.e.s.-400 filmtab": "2",
 "e-mycin": "2",
 "effexor": "2",
 "esimil": "2",
 "equibron g": "2",
 "erythrocin": "2",
 "enduron": "2",
 "eryped": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "eskalith": "2",
 "erythromycin/sulfisoxazole": "2",
 "e.e.s. granules": "2",
 "erythrocin stearate filmtab": "2",
 "entacapone": "2",
 "ethacrynic acid": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "eskalith-cr": "2",
 "esmolol": "2",
 "eryzole": "2",
 "elixophyllin gg": "2",
 "ephedrine/hydroxyzine/theophylline": "2",
 "ed-bron g": "2",
 "e s p": "2",
 "e.e.s.-200": "2",
 "exforge hct": "2",
 "entocort ec": "1",
 "etrafon forte": "2",
 "elavil": "2",
 "exna": "2",
 "esidrix": "2",
 "enduronyl forte": "2",
 "exubera": "2",
 "erythrocot": "2",
 "elixophyllin ki": "2",
 "erythromycin": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "ellence": "2",
 "elixophyllin": "2"}, "d": {"doxepin topical": "2",
 "dilor-g": "2",
 "dutoprol": "2",
 "daunorubicin": "2",
 "dronedarone": "2",
 "dyphylline gg": "2",
 "demadex": "2",
 "diuril": "2",
 "d-g": "2",
 "dep medalone 80": "1",
 "diovan hct": "2",
 "dyphylline gg es": "2",
 "daunoxome": "2",
 "dextromethorphan/quinidine": "2",
 "degarelix": "2",
 "dilex-g": "2",
 "demi-regroton": "2",
 "diamox sequels": "2",
 "diupres-500": "2",
 "depmedalone": "1",
 "dilor": "2",
 "decadron with xylocaine": "1",
 "difil g": "2",
 "diamox": "2",
 "dyline gg": "2",
 "dexamethasone/lidocaine": "1",
 "dyfilin gg": "2",
 "darvon compound 32": "2",
 "dalalone la": "1",
 "dexone": "1",
 "doxorubicin liposomal": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "dilex-g 200": "2",
 "dexpak taperpak": "1",
 "dexacort phosphate in turbinaire": "1",
 "definity": "2",
 "doxepin": "2",
 "diaqua-2": "2",
 "deltasone": "1",
 "duralone": "1",
 "dexacort-la": "1",
 "dy-g": "2",
 "dyphylline/guaifenesin": "2",
 "dexamethasone": "1",
 "dilor-400": "2",
 "diaqua": "2",
 "dyphylline": "2",
 "dalalone dp": "1",
 "deserpidine/methyclothiazide": "2",
 "duloxetine": "2",
 "dexasone": "1",
 "diurese": "2",
 "duo-vil": "2",
 "dylix": "2",
 "darvon-n": "2",
 "daranide": "2",
 "delta-cortef": "1",
 "dyflex-g": "2",
 "darvon": "2",
 "diuretic ap-es": "2",
 "droperidol/fentanyl": "2",
 "dexasone la": "1",
 "dasatinib": "2",
 "diucardin": "2",
 "droperidol": "2",
 "dyazide": "2",
 "darvon compound-65": "2",
 "desipramine": "2",
 "depoject-80": "1",
 "decadron phosphate, injectable": "1",
 "depo-medrol": "1",
 "decadron": "1",
 "dulera": "1",
 "de-sone la": "1",
 "doxorubicin": "2",
 "dexacort phosphate in respihaler": "1",
 "dichlorphenamide": "2",
 "denzapine": "2",
 "depopred": "1",
 "dorzolamide/timolol ophthalmic": "3",
 "dolophine": "2",
 "doxil": "2",
 "diuril sodium": "2",
 "dexamethasone intensol": "1",
 "darvocet-n 100": "2",
 "decadron-la": "1",
 "deserpidine/hydrochlorothiazide": "2",
 "dofetilide": "2",
 "diutensen-r": "2",
 "dexacorten": "1",
 "demadex iv": "2",
 "difil-g forte": "2",
 "dexacen-4": "1",
 "dextromethorphan/promethazine": "2",
 "darvocet-n 50": "2",
 "dolasetron": "2",
 "disopyramide": "2",
 "decaject la": "1",
 "dyphyl gg": "2",
 "diupres-250": "2",
 "diflucan": "2",
 "dyphyllin-gg": "2",
 "dexone la": "1",
 "daunorubicin liposomal": "2",
 "dalalone": "1",
 "dilex-g 400": "2",
 "desvenlafaxine": "2",
 "decaject": "1",
 "darvocet a500": "2"}, "g": {"guanethidine/hydrochlorothiazide": "2",
 "genox": "2",
 "granisol": "2",
 "geodon": "2",
 "guaifenesin/theophylline": "2",
 "granisetron": "2",
 "gatifloxacin": "2",
 "gemifloxacin": "2",
 "glauctabs": "2",
 "guaifenesin/oxtriphylline": "2",
 "grepafloxacin": "2",
 "glyceryl t": "2"}, "f": {"firmagon": "2",
 "fazaclo": "2",
 "florinef acetate": "1",
 "fanapt": "2",
 "fluticasone": "1",
 "fosinopril/hydrochlorothiazide": "2",
 "flecainide": "2",
 "florinef": "1",
 "furosemide": "2",
 "fluconazole": "2",
 "floxin": "2",
 "flo-pred": "1",
 "furazolidone": "2",
 "furoxone": "2",
 "factive": "2",
 "flovent diskus": "1",
 "fludrocortisone": "1",
 "fortovase": "2",
 "fluphenazine": "2",
 "formoterol/mometasone": "1",
 "flunisolide": "1",
 "flovent": "1",
 "fluothane": "2",
 "fluticasone/salmeterol": "1",
 "floxin iv": "2",
 "flovent hfa": "1",
 "fareston": "2",
 "flovent rotadisk": "1",
 "flumezide": "2"}, "i": {"indapamide": "2",
 "idamycin pfs": "2",
 "innopran xl": "3",
 "invega": "2",
 "ibutilide": "2",
 "invirase": "2",
 "istodax": "2",
 "innovar": "2",
 "inapsine": "2",
 "imipramine": "2",
 "inderide la": "3",
 "insulin inhalation, rapid acting": "2",
 "isocarboxazid": "2",
 "ilosone": "2",
 "inderal la": "3",
 "idamycin": "2",
 "istalol": "3",
 "iloperidone": "2",
 "inderal": "3",
 "invega sustenna": "2",
 "idarubicin": "2",
 "inderide": "3"}, "h": {"hydeltrasol": "1",
 "hhr": "2",
 "haloperidol": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hydroserpine 1": "2",
 "hyzaar": "2",
 "hydro-reserp": "2",
 "hydrocortisone": "1",
 "hydrochlorothiazide/methyldopa": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrochlorothiazide/timolol": "3",
 "hydrocortone phosphate": "1",
 "hydrochlorothiazide/spironolactone": "2",
 "hydropres-50": "2",
 "hydrap-es": "2",
 "hydroserpine": "2",
 "hydroflumethiazide/reserpine": "2",
 "hydrochlorothiazide/losartan": "2",
 "hydrochlorothiazide/reserpine": "2",
 "hydrodiuril": "2",
 "hygroton": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hydrophed": "2",
 "hydrochlorothiazide/propranolol": "3",
 "haldol decanoate": "2",
 "hismanal": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydeltra-tba": "1",
 "hydrochlorothiazide/moexipril": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "hydrochlorothiazide": "2",
 "hydroxy compound": "2",
 "halothane": "2",
 "h.p. acthar gel": "1",
 "hydrochlorothiazide/lisinopril": "2",
 "hydroserp": "2",
 "halaven": "2",
 "hydra-zide": "2",
 "hydrochlorothiazide/valsartan": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrocortone": "1",
 "halfan": "2",
 "halofantrine": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydropres-25": "2",
 "hexadrol": "1",
 "hydro par": "2",
 "hydralazine plus": "2",
 "hydroflumethiazide": "2",
 "haldol": "2"}, "k": {"key-pred": "1",
 "kaletra": "2",
 "kenalog-10": "1",
 "ketek": "2",
 "kenalog-40": "1",
 "key-pred sp": "1",
 "ketek pak": "2",
 "ken-jec 40": "1",
 "kerlone": "2",
 "kytril": "2",
 "kenaject-40": "1"}, "j": {"jay-phyl": "2",
 "jumex": "2"}, "m": {"mannitol": "2",
 "mannitol/sorbitol topical": "2",
 "metipranolol ophthalmic": "3",
 "mellaril-s": "2",
 "metoprolol succinate er": "2",
 "metahydrin": "2",
 "methotrimeprazine": "2",
 "meridia": "2",
 "methylprednisolone dose pack": "1",
 "medralone": "1",
 "medidex la": "1",
 "medipred": "1",
 "moxifloxacin": "2",
 "m-prednisolone": "1",
 "metolazone": "2",
 "marplan": "2",
 "medralone 80": "1",
 "medrol dosepak": "1",
 "micardis hct": "2",
 "maxzide": "2",
 "med-jec-40": "1",
 "mometasone": "1",
 "microzide": "2",
 "monopril hct": "2",
 "meticorten": "1",
 "millipred dp": "1",
 "methyclothiazide/reserpine": "2",
 "methylprednisolone": "1",
 "meperidine/promethazine": "2",
 "milnacipran": "2",
 "millipred": "1",
 "multaq": "2",
 "methacort 40": "1",
 "m-phen": "2",
 "mepergan": "2",
 "methdilazine": "2",
 "mudrane gg": "2",
 "marax df": "2",
 "metatensin 4": "2",
 "mykrox": "2",
 "moduretic 5-50": "2",
 "mepergan fortis": "2",
 "moduretic": "2",
 "maprotiline": "2",
 "methylcotolone": "1",
 "mudrane": "2",
 "methazolamide": "2",
 "mzm": "2",
 "mefloquine": "2",
 "methylpred dp": "1",
 "matulane": "2",
 "marax": "2",
 "methadose": "2",
 "mellaril": "2",
 "meprozine": "2",
 "metatensin 2": "2",
 "medidex": "1",
 "methacort 80": "1",
 "maxaquin": "2",
 "methyclothiazide": "2",
 "medicort": "1",
 "maxzide-25": "2",
 "methadone diskets": "2",
 "medrol": "1",
 "medralone 40": "1",
 "methadone": "2",
 "methylcotol": "1",
 "metoprolol": "2",
 "mesoridazine": "2",
 "minizide": "2",
 "marpres": "2",
 "mudrane gg-2": "2"}, "l": {"ludiomil": "2",
 "loqua": "2",
 "lufyllin-gg": "2",
 "lomefloxacin": "2",
 "liquid pred": "1",
 "levobunolol ophthalmic": "3",
 "lufyllin": "2",
 "levofloxacin": "2",
 "lozol": "2",
 "lufyllin-400": "2",
 "levaquin": "2",
 "lariam": "2",
 "lithium": "2",
 "limbitrol": "2",
 "levatol": "3",
 "lithonate": "2",
 "lasix": "2",
 "lotensin hct": "2",
 "lgg": "2",
 "lopinavir/ritonavir": "2",
 "linezolid": "2",
 "largon": "2",
 "levitra": "2",
 "labetalol": "3",
 "limbitrol ds": "2",
 "levaquin leva-pak": "2",
 "lopressor": "2",
 "lapatinib": "2",
 "lo-aqua": "2",
 "lithobid": "2",
 "lopressor hct": "2",
 "lufyllin-epg": "2",
 "lorelco": "2",
 "lithotabs": "2",
 "levomethadyl acetate": "2",
 "levoprome": "2"}, "o": {"orap": "2",
 "orasone": "1",
 "oreticyl 25": "2",
 "optipranolol": "3",
 "optison": "2",
 "ocupress": "3",
 "oxtriphylline": "2",
 "orlaam": "2",
 "oreticyl 50": "2",
 "oretic": "2",
 "orapred odt": "1",
 "osmitrol": "2",
 "ondansetron": "2",
 "ormazine": "2",
 "ofloxacin": "2",
 "orapred": "1",
 "oreticyl forte": "2"}, "n": {"naturetin": "2",
 "naturetin-10": "2",
 "nucynta": "2",
 "nuedexta": "2",
 "nebupent": "2",
 "norpace cr": "2",
 "nortriptyline": "2",
 "naqua": "2",
 "nolvadex d": "2",
 "nebivolol": "2",
 "nilotinib": "2",
 "nolvadex": "2",
 "nardil": "2",
 "normodyne": "3",
 "nexavar": "2",
 "nexterone": "2",
 "norpramin": "2",
 "noxafil": "2",
 "noroxin": "2",
 "neothylline": "2",
 "naturetin-5": "2",
 "norfloxacin": "2",
 "nadolol": "3",
 "nucynta er": "2",
 "neptazane": "2",
 "norpace": "2"}, "q": {"quibron": "2",
 "quibron 300": "2",
 "quinaretic": "2",
 "quinidex extentabs": "2",
 "quinora": "2",
 "quinidine": "2",
 "qm-260": "2",
 "quinaglute dura-tabs": "2",
 "quin-g": "2",
 "quetiapine": "2",
 "quinine": "2",
 "quin-release": "2",
 "qualaquin": "2",
 "quibron-t/sr": "2",
 "quadrinal": "2",
 "q-b": "2",
 "qvar": "1",
 "quibron-t": "2"}, "p": {"predicort-50": "1",
 "prudoxin": "2",
 "pediazole": "2",
 "predacort 50": "1",
 "procainamide": "2",
 "prinzide": "2",
 "pindolol": "3",
 "pce dispertab": "2",
 "pharmorubicin rdf": "2",
 "pulmicort nebuamp": "1",
 "predcor": "1",
 "panfil g": "2",
 "proquin xr": "2",
 "prednisolone": "1",
 "phyllocontin": "2",
 "prolixin": "2",
 "phenadoz": "2",
 "polythiazide/prazosin": "2",
 "probucol": "2",
 "procarbazine": "2",
 "prelone": "1",
 "prochlorperazine": "2",
 "protriptyline": "2",
 "pitressin": "2",
 "phenylephrine/promethazine": "2",
 "predate-50": "1",
 "promethazine with codeine": "2",
 "phenazine 50": "2",
 "permitil": "2",
 "prolixin enanthate": "2",
 "parnate": "2",
 "pseudoephedrine/terfenadine": "2",
 "phenoject-50": "2",
 "paliperidone": "2",
 "promethegan": "2",
 "pulmicort flexhaler": "1",
 "predicort rp": "1",
 "primethasone": "1",
 "pentam 300": "2",
 "promethazine with dm": "2",
 "promethazine vc with codeine": "2",
 "prednicen-m": "1",
 "pronestyl-sr": "2",
 "pediapred": "1",
 "pri-cortin 50": "1",
 "penbutolol": "3",
 "propiomazine": "2",
 "procot": "2",
 "phenelzine": "2",
 "posaconazole": "2",
 "pentamidine": "2",
 "polythiazide/reserpine": "2",
 "pro-med": "2",
 "potassium iodide/theophylline": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "promethazine vc": "2",
 "pharmorubicin pfs": "2",
 "propoxyphene compound 65": "2",
 "propranolol": "3",
 "pristiq": "2",
 "pc-cap": "2",
 "palonosetron": "2",
 "pp-cap": "2",
 "predaject-50": "1",
 "pulmicort turbuhaler": "1",
 "predacorten": "1",
 "pamelor": "2",
 "pimozide": "2",
 "pentacarinat": "2",
 "promethazine vc plain": "2",
 "prograf": "2",
 "pulmicort respules": "1",
 "promazine": "2",
 "predalone 50": "1",
 "promethazine dm": "2",
 "phenergan": "2",
 "pazopanib": "2",
 "primatene dual action": "2",
 "promethazine vc w/codeine": "2",
 "propoxyphene": "2",
 "phenergan fortis": "2",
 "pentam": "2",
 "plenaxis": "2",
 "pronestyl": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "polythiazide": "2",
 "pacerone": "2",
 "perphenazine": "2",
 "propulsid": "2",
 "promethazine with dextromethorphan": "2",
 "pred-ject-50": "1",
 "phenergan vc": "2",
 "perflutren": "2",
 "prednisone": "1",
 "procanbid": "2",
 "promethazine hcl with codeine": "2",
 "prolixin decanoate": "2",
 "prednicot": "1",
 "propafenone": "2",
 "procan sr": "2",
 "phenergan with dextromethorphan": "2",
 "potiga": "2",
 "prevpac": "2",
 "promethazine hcl and codeine phosphate": "2"}, "s": {"slo-phyllin 125": "2",
 "sotalol hydrochloride af": "3",
 "saluron": "2",
 "sodium edecrin": "2",
 "stalevo 100": "2",
 "sparine": "2",
 "slo-bid gyrocaps": "2",
 "saquinavir": "2",
 "solu-medrol": "1",
 "sunitinib": "2",
 "stalevo 150": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "solu-cortef": "1",
 "sterapred ds": "1",
 "slo-phyllin": "2",
 "selgene": "2",
 "seldane": "2",
 "sinequan": "2",
 "symbicort": "1",
 "slo-phyllin gg": "2",
 "saphris": "2",
 "solurex": "1",
 "solu-phyllin gg": "2",
 "staxyn": "2",
 "seldane-d": "2",
 "selegiline": "2",
 "sparfloxacin": "2",
 "serpazide": "2",
 "soltamox": "2",
 "serathide": "2",
 "salutensin": "2",
 "slo-phyllin 80": "2",
 "sibutramine": "2",
 "surmontil": "2",
 "stalevo 125": "2",
 "stalevo 75": "2",
 "strattera": "2",
 "sulfimycin": "2",
 "ser-ap-es": "2",
 "stalevo": "2",
 "sotalol": "3",
 "sorine": "3",
 "salutensin-demi": "2",
 "solurex la": "1",
 "silenor": "2",
 "sutent": "2",
 "stelazine": "2",
 "stalevo 50": "2",
 "serentil": "2",
 "stalevo 200": "2",
 "sancuso": "2",
 "sectral": "2",
 "selestoject": "1",
 "sorafenib": "2",
 "serpex": "2",
 "savella": "2",
 "sterapred": "1",
 "sprycel": "2"}, "r": {"rauzide": "2",
 "rythmol": "2",
 "rasagiline": "2",
 "rythmol sr": "2",
 "ranolazine": "2",
 "risperdal m-tab": "2",
 "risperdal": "2",
 "risperdal consta": "2",
 "risperidone": "2",
 "romidepsin": "2",
 "robimycin": "2",
 "respbid": "2",
 "renese-r": "2",
 "regroton": "2",
 "reserpine/trichlormethiazide": "2",
 "rilpivirine": "2",
 "raxar": "2",
 "rondameth": "2",
 "resectisol": "2",
 "renese": "2",
 "ranexa": "2"}, "u": {"unipres": "2",
 "uniphyl": "2",
 "u-tri-lone": "1",
 "uroxatral": "2",
 "uni serp": "2",
 "uni-dur": "2",
 "uprima": "2",
 "uni bronchial": "2",
 "uniretic": "2"}, "t": {"theolair-sr": "2",
 "toprol-xl": "2",
 "tamoxifen": "2",
 "tamofen": "2",
 "tizanidine": "2",
 "theocon": "2",
 "theomax df": "2",
 "theolair": "2",
 "theo-dur": "2",
 "timolol ophthalmic": "3",
 "tranylcypromine": "2",
 "tramacort-d": "1",
 "timoptic": "3",
 "thiethylperazine": "2",
 "theoclear-80": "2",
 "teveten hct": "2",
 "tenormin": "2",
 "temaril": "2",
 "truphylline": "2",
 "theophylline ki": "2",
 "theo-dur sprinkles": "2",
 "tetrabenazine": "2",
 "tenoretic": "2",
 "trilog": "1",
 "theoclear la-260": "2",
 "theolate": "2",
 "tolcapone": "2",
 "trisenox": "2",
 "thioridazine": "2",
 "trifluoperazine": "2",
 "torsemide": "2",
 "theo g": "2",
 "theocon elixir": "2",
 "tenoretic 50": "2",
 "thalitone": "2",
 "trandate": "3",
 "tamone": "2",
 "theodrine": "2",
 "torecan": "2",
 "tofranil-pm": "2",
 "theovent": "2",
 "timolide": "3",
 "telithromycin": "2",
 "timoptic-xe": "3",
 "theomar gg": "2",
 "thorazine": "2",
 "tykerb": "2",
 "tasigna": "2",
 "timolol": "3",
 "theobid": "2",
 "trycet": "2",
 "tristoject": "1",
 "tequin": "2",
 "trimipramine": "2",
 "tenoretic 100": "2",
 "triflupromazine": "2",
 "triavil": "2",
 "t-phyl": "2",
 "tapentadol": "2",
 "theoclear la-130": "2",
 "terfenadine": "2",
 "tekturna hct": "2",
 "tac 3": "1",
 "trimeprazine": "2",
 "theo-time": "2",
 "timolide 10-25": "3",
 "tedrigen": "2",
 "theophyll-gg": "2",
 "tambocor": "2",
 "triam-forte": "1",
 "tequin teqpaq": "2",
 "triamcot": "1",
 "triam-a": "1",
 "telavancin": "2",
 "tasmar": "2",
 "theocap": "2",
 "tikosyn": "2",
 "triamonide 40": "1",
 "theo-24": "2",
 "tofranil": "2",
 "theophylline": "2",
 "tamoxifen hexal": "2",
 "tri-hydroserpine": "2",
 "triamcinolone": "1",
 "trilafon": "2",
 "truxophyllin": "2",
 "theo-x": "2",
 "trilone": "1",
 "tribenzor": "2",
 "theochron": "2",
 "toremifene": "2",
 "timoptic ocudose": "3",
 "trichlormethiazide": "2",
 "tamosin": "2",
 "tacaryl": "2",
 "tacrolimus": "2",
 "tamoxen": "2"}, "w": {"wygesic": "2"}, "v": {"veripred 20": "1",
 "v-gan-50": "2",
 "vibativ": "2",
 "venlafaxine": "2",
 "vascor": "2",
 "vaseretic 5-12.5": "2",
 "votrient": "2",
 "vanceril ds": "1",
 "vivactil": "2",
 "voriconazole": "2",
 "vanceril": "1",
 "vaseretic": "2",
 "vemurafenib": "2",
 "vardenafil": "2",
 "visken": "3",
 "vasopressin": "2",
 "v-gan-25": "2",
 "vaseretic 10-25": "2",
 "vandetanib": "2",
 "vanatrip": "2",
 "vfend": "2"}, "x": {"xalkori": "2",
 "xenazine": "2"}, "z": {"zelapar": "2",
 "zelboraf": "2",
 "zagam respipac": "2",
 "zmax": "2",
 "zanaflex": "2",
 "zema pak": "1",
 "zyvox": "2",
 "zofran": "2",
 "zebeta": "2",
 "zuplenz": "2",
 "zagam": "2",
 "zonalon": "2",
 "zaroxolyn": "2",
 "zestoretic": "2",
 "ziprasidone": "2",
 "zaponex": "2",
 "ziac": "2",
 "zofran odt": "2",
 "zithromax": "2"}}];