interactions["bivalirudin"]=["bivalirudin", {"a": {"argesic-sa": "2",
 "all day pain relief": "2",
 "anaprox": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "acular ls": "2",
 "advil migraine": "2",
 "aptivus": "3",
 "all day relief": "2",
 "advil infant's concentrated drops": "2",
 "abciximab": "2",
 "aspirin/dipyridamole": "2",
 "actiprofen": "2",
 "acular": "2",
 "acetaminophen/phenyltoloxamine/salicylamide": "2",
 "argatroban": "3",
 "arthrotec": "2",
 "abbokinase open-cath": "3",
 "ari sodium iodide (i123) 100-750 mbq": "2",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "2",
 "aflaxen": "2",
 "advil children's allergy sinus": "2",
 "advil": "2",
 "aleve": "2",
 "actron": "2",
 "anagrelide": "2",
 "abbokinase": "3",
 "advil pm": "2",
 "anaprox-ds": "2",
 "aqua gem-e": "2",
 "arixtra": "3",
 "anafranil": "2",
 "acetaminophen/salicylamide": "2",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "2",
 "alteplase": "3",
 "ardeparin": "3",
 "acular pf": "2",
 "arthriten": "2",
 "aqua-e": "2",
 "anistreplase": "3",
 "ari sodium iodide (i123) 1-12 mbq": "2",
 "arixtra 5 mg/dose": "3",
 "a-g profen": "2",
 "arixtra 7.5 mg/dose": "3",
 "advil liqui-gels": "2",
 "aspirin/caffeine/salicylamide": "2",
 "aleve-d sinus &amp; cold": "2",
 "amigesic": "2",
 "advil cold and sinus": "2",
 "arthropan": "2",
 "acova": "3",
 "aggrastat": "2",
 "ansaid": "2",
 "activase": "3",
 "advil junior strength": "2",
 "addaprin": "2",
 "acuvail": "2",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "2",
 "acetaminophen/aspirin/caffeine/salicylamide": "2",
 "agrylin": "2",
 "advil children's": "2",
 "atrosept": "2",
 "anaflex": "2",
 "anabar": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "anturane": "2",
 "arixtra 10 mg/dose": "3",
 "aggrenox": "2",
 "advil cold and sinus liqui-gels": "2",
 "aquavite-e": "2",
 "advil children's cold": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "amino-opti-e": "2",
 "aquasol e": "2",
 "anisindione": "3",
 "alpha e": "2",
 "advil allergy sinus": "2"}, "c": {"cafgesic forte": "2",
 "clinoril": "2",
 "cystex": "2",
 "celexa": "2",
 "cymbalta": "2",
 "cystemms-v": "2",
 "collagenase clostridium histolyticum": "2",
 "combiflex": "2",
 "clexane forte": "3",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "2",
 "clove": "1",
 "chamomile": "1",
 "comfort pac with naproxen": "2",
 "cataflam": "2",
 "clexane": "3",
 "choline salicylate/magnesium salicylate": "2",
 "clomipramine": "2",
 "caldolor": "2",
 "combunox": "2",
 "cathflo activase": "3",
 "childrens ibuprofen berry": "2",
 "cilostazol": "2",
 "clopidogrel": "2",
 "choline magnesium trisalicylate": "2",
 "citalopram": "2",
 "childrens kaopectate": "2",
 "celecoxib": "2",
 "cafgesic": "2",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "2",
 "cmt": "2",
 "capsicum": "1",
 "combiflex es": "2",
 "ceprotin": "2",
 "children's motrin": "2",
 "caffeine/magnesium salicylate": "2",
 "centrum singles-vitamin e": "2",
 "choline salicylate": "2",
 "celebrex": "2",
 "coumadin": "3",
 "cap-profen": "2",
 "cambia": "2"}, "b": {"b c powder arthritis strength": "2",
 "bexxar dosimetric": "3",
 "bismatrol maximum strength": "2",
 "bexxartherapeutic": "3",
 "bismatrol": "2",
 "b c powder": "2",
 "by-ache": "2",
 "bayer select backache pain formula": "2",
 "bismarex": "2",
 "bromfenac": "2",
 "bromfenac ophthalmic": "2",
 "bextra": "2",
 "bc headache": "2",
 "benzoic acid/methenamine/sodium salicylate": "2",
 "bc fast pain relief": "2",
 "bismuth subsalicylate": "2",
 "bromday": "2",
 "bexxar": "3",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "brilinta": "2",
 "be-flex plus": "2"}, "e": {"elmiron": "2",
 "e-400 clear": "2",
 "eminase": "3",
 "enoxaparin": "3",
 "emagrin": "2",
 "e pherol": "2",
 "e-gems": "2",
 "effient": "3",
 "exjade": "3",
 "escitalopram": "2",
 "ed-flex": "2",
 "effexor xr": "2",
 "ec-naprosyn": "2",
 "epoprostenol": "2",
 "etodolac": "2",
 "e-600": "2",
 "effexor": "2",
 "esomeprazole/naproxen": "2",
 "eptifibatide": "2"}, "d": {"duexis": "2",
 "doans pills extra strength": "2",
 "deferasirox": "3",
 "diclofenac ophthalmic": "2",
 "dong quai": "2",
 "diclofenac": "2",
 "dipyridamole": "2",
 "darpaz": "2",
 "diflunisal": "2",
 "dexfenfluramine": "2",
 "durabac forte": "2",
 "durabac": "2",
 "dolorex": "2",
 "diphenhydramine/ibuprofen": "2",
 "dristan sinus": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "diurex": "2",
 "dolsed": "2",
 "darcalma": "2",
 "diclofenac topical": "2",
 "dicumarol": "3",
 "doan's pills": "2",
 "dasatinib": "3",
 "duract": "2",
 "dolobid": "2",
 "daypro": "2",
 "duraxin": "2",
 "desirudin": "3",
 "disalcid": "2",
 "doans pm": "2",
 "duloxetine": "2",
 "dalteparin": "3",
 "diclofenac/misoprostol": "2",
 "dewitt's pain reliever": "2",
 "desvenlafaxine": "2",
 "drotrecogin alfa": "3",
 "danaparoid": "3",
 "dabigatran": "3"}, "g": {"ginseng": "2",
 "genpril": "2",
 "garlic oil": "2",
 "ginger": "2",
 "ginkgo": "2",
 "ginkgo biloba": "2",
 "garlic": "2",
 "ginger root": "2"}, "f": {"flolan": "2",
 "fenugreek": "1",
 "fenoprofen": "2",
 "fluoxetine": "2",
 "fluvoxamine": "2",
 "fragmin": "3",
 "fluoxetine/olanzapine": "2",
 "feldene": "2",
 "flurbiprofen": "2",
 "fenfluramine": "2",
 "flurbiprofen ophthalmic": "2",
 "fondaparinux": "3",
 "feverfew": "1",
 "frenadol": "2",
 "flector patch": "2",
 "famotidine/ibuprofen": "2"}, "i": {"iodine i 131 tositumomab": "3",
 "ibuprofen": "2",
 "ibuprofen pmr": "2",
 "ipilimumab": "3",
 "iprivask": "3",
 "ibuprofen/oxycodone": "2",
 "ibudone": "2",
 "iloprost": "2",
 "iodotope": "2",
 "ibuprofen/pseudoephedrine": "2",
 "integrilin": "2",
 "indocin iv": "2",
 "innohep": "3",
 "ibu-200": "2",
 "indocin": "2",
 "in-111 zevalin": "3",
 "indocin sr": "2",
 "ibritumomab": "3",
 "ibu": "2",
 "ibu-tab": "2",
 "ibu-4": "2",
 "ibu-6": "2",
 "ibu-8": "2",
 "indomethacin": "2"}, "h": {"heparin": "3",
 "hyophen": "2",
 "hydrocodone/ibuprofen": "2",
 "hofels ginger one a day": "2",
 "helidac": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "heparin sodium": "3",
 "hemin": "2",
 "haltran": "2"}, "k": {"kaopectate anti-diarrheal upset stomach reliever": "2",
 "kinlytic": "3",
 "kneerelief": "2",
 "k-pek": "2",
 "ketoprofen": "2",
 "ketorolac ophthalmic": "2",
 "kao-tin bismuth subsalicylate formula": "2",
 "kaopectate extra strength": "2",
 "kaopectate": "2",
 "korlym": "3",
 "kabikinase": "3",
 "kapectolin": "2",
 "ketorolac": "2"}, "j": {"jantoven": "3"}, "m": {"motrin cold and flu": "2",
 "mst": "2",
 "mobic": "2",
 "meridia": "2",
 "mobigesic": "2",
 "marthritic": "2",
 "miradon": "3",
 "motrin ib": "2",
 "magsal": "2",
 "mobidin": "2",
 "mefenamic acid": "2",
 "motrin": "2",
 "mhp-a": "2",
 "motrin migraine pain": "2",
 "meclofenamate": "2",
 "motrin sinus headache": "2",
 "msp-blu": "2",
 "meloxicam": "2",
 "milnacipran": "2",
 "midol extended relief": "2",
 "motrin pm": "2",
 "mag-phen": "2",
 "motrin infant drops": "2",
 "mifepristone": "3",
 "maalox total relief": "2",
 "midol ib": "2",
 "motrin junior strength": "2",
 "motrin childrens": "2",
 "maximum strength stress": "2",
 "motrin childrens cold": "2",
 "menadol": "2",
 "meclomen": "2",
 "mono-gesic": "2",
 "magan": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "myogesic": "2",
 "midol maximum strength cramp formula": "2",
 "motrin ib sinus": "2",
 "magnesium salicylate": "2",
 "mifeprex": "3"}, "l": {"leader naproxen sodium": "2",
 "lodine xl": "2",
 "luvox": "2",
 "luvox cr": "2",
 "lepirudin": "3",
 "lovenox": "3",
 "lexapro": "2",
 "lodine": "2",
 "levacet": "2",
 "lovenox hp": "3",
 "lansoprazole/naproxen": "2",
 "lobac": "2"}, "o": {"orudis": "2",
 "oxaprozin": "2",
 "orudis kt": "2",
 "oruvail": "2",
 "ocufen": "2",
 "orgaran": "3"}, "n": {"nuprin backache caplet": "2",
 "nexcede": "2",
 "nutr-e-sol": "2",
 "nuprin": "2",
 "nalfon": "2",
 "novasal": "2",
 "naprosyn": "2",
 "naproxen sodium ds": "2",
 "naproxen/pseudoephedrine": "2",
 "naproxen": "2",
 "naprelan": "2",
 "normiflo": "3",
 "naproxen/sumatriptan": "2",
 "neoprofen": "2",
 "nabumetone": "2",
 "nepafenac ophthalmic": "2",
 "nevanac": "2"}, "q": {"q-profen": "2"}, "p": {"paroxetine": "2",
 "phosphasal": "2",
 "protexel": "2",
 "protein c": "2",
 "paxil": "2",
 "pamprin all day relief": "2",
 "panritis forte": "2",
 "pepto-bismol maximum strength": "2",
 "prosed ds": "2",
 "persantine": "2",
 "prozac weekly": "2",
 "panhematin": "2",
 "paxil cr": "2",
 "prosed ec": "2",
 "phosenamine": "2",
 "prozac": "2",
 "prasugrel": "3",
 "pennsaid": "2",
 "plavix": "2",
 "pradaxa": "3",
 "persantine iv": "2",
 "prevacid naprapac 500": "2",
 "pepto-bismol": "2",
 "peptic relief": "2",
 "pletal": "2",
 "ponstel": "2",
 "piroxicam": "2",
 "painaid": "2",
 "pristiq": "2",
 "pondimin": "2",
 "profenal": "2",
 "prevacid naprapac 375": "2",
 "prevacid naprapac": "2",
 "pink bismuth": "2",
 "phenylbutazone": "2",
 "pamprin cramp menstrual pain relief": "2",
 "pexeva": "2",
 "pentosan polysulfate sodium": "2"}, "s": {"saleto-200": "2",
 "sulindac": "2",
 "saleto": "2",
 "sarafem": "2",
 "sertraline": "2",
 "sulfinpyrazone": "2",
 "sine-aid ib": "2",
 "sprycel": "3",
 "streptokinase": "3",
 "stomach relief": "2",
 "suprofen ophthalmic": "2",
 "sutent": "2",
 "selfemra": "2",
 "sibutramine": "2",
 "salsalate": "2",
 "salflex": "2",
 "saleto-800": "2",
 "saleto-d": "2",
 "symbyax": "2",
 "streptase": "3",
 "solaraze": "2",
 "salsitab": "2",
 "saleto-600": "2",
 "sodium iodide i-123": "2",
 "sodium thiosalicylate": "2",
 "sodium salicylate": "2",
 "sunitinib": "2",
 "scot-tussin original": "2",
 "stress maximum strength": "2",
 "sprix": "2",
 "stanback fast pain relief": "2",
 "sodium iodide-i-131": "2",
 "saleto-400": "2",
 "savella": "2",
 "sudafed 12 hour pressure+pain": "2"}, "r": {"remodulin": "2",
 "reopro": "2",
 "rapiflux": "2",
 "rofecoxib": "2",
 "rufen": "2",
 "retavase half-kit": "3",
 "refludan": "3",
 "rexolate": "2",
 "retavase": "3",
 "reprexain": "2",
 "rhinogesic": "2",
 "rivaroxaban": "3",
 "relafen": "2",
 "redux": "2",
 "reteplase": "3"}, "u": {"uretron": "2",
 "urimax": "2",
 "utrona-c": "2",
 "utira-c": "2",
 "uritact ds": "2",
 "urimar-t": "2",
 "urised": "2",
 "utira": "2",
 "utrona": "2",
 "uretron ds": "2",
 "urapine": "2",
 "uritin": "2",
 "usept": "2",
 "urisym": "2",
 "uta": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "urokinase": "3",
 "ustell": "2",
 "urelle": "2",
 "uribel": "2"}, "t": {"ticlid": "2",
 "toradol": "2",
 "tusal": "2",
 "tyvaso": "2",
 "treprostinil": "2",
 "tolectin 600": "2",
 "tolectin": "2",
 "tositumomab": "3",
 "ticlopidine": "2",
 "tenecteplase": "3",
 "tolmetin": "2",
 "toradol iv/im": "2",
 "tetra-mag": "2",
 "toradol im": "2",
 "tipranavir": "3",
 "trac tabs 2x": "2",
 "tirofiban": "2",
 "treximet": "2",
 "trilisate": "2",
 "ticagrelor": "2",
 "tinzaparin": "3",
 "tolectin ds": "2",
 "torisel": "3",
 "tricosal": "2",
 "tnkase": "3",
 "turmeric": "1",
 "temsirolimus": "3"}, "w": {"warfarin": "3"}, "v": {"viibryd": "2",
 "vitamin e": "2",
 "vita-plus e natural": "2",
 "vilazodone": "2",
 "vimovo": "2",
 "vioxx": "2",
 "ventavis": "2",
 "voltaren-xr": "2",
 "voltaren": "2",
 "valdecoxib": "2",
 "veletri": "2",
 "venlafaxine": "2",
 "voltaren ophthalmic": "2",
 "voltaren gel": "2",
 "verteporfin": "2",
 "visudyne": "2",
 "vicoprofen": "2"}, "y": {"yervoy": "3",
 "y-90 zevalin": "3"}, "x": {"xigris": "3",
 "xarelto": "3",
 "xiaflex": "2",
 "xibrom": "2"}, "z": {"zevalin": "3",
 "zipsor": "2",
 "zoloft": "2"}}];