interactions["bortezomib,velcade"]=["bortezomib,velcade", {"a": {"alkeran": "1",
 "agenerase": "2",
 "antispas": "2",
 "aminophylline/amobarbital/ephedrine": "2",
 "altocor": "2",
 "amytal sodium": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "aralen hydrochloride": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "arranon": "2",
 "auranofin": "2",
 "acetohexamide": "2",
 "amlodipine/atorvastatin": "2",
 "aurolate": "2",
 "aspirin/pravastatin": "2",
 "acetaminophen/butalbital": "2",
 "avonex prefilled syringe": "2",
 "atripla": "2",
 "aspirin/carisoprodol": "1",
 "aurothioglucose": "2",
 "aqua-e": "2",
 "abraxane": "2",
 "arava": "3",
 "avandia": "2",
 "advicor": "2",
 "amaryl": "2",
 "adrenocot": "2",
 "anturane": "2",
 "altoprev": "2",
 "apresoline": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "actemra": "2",
 "anoquan": "2",
 "afeditab cr": "2",
 "arcet": "2",
 "alagesic": "2",
 "adalimumab": "2",
 "alkabel-sr": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "amobarbital": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "aralen": "2",
 "alpha e": "2",
 "aspirin/butalbital/caffeine": "2",
 "aquasol e": "2",
 "accolate": "2",
 "amobarbital/secobarbital": "2",
 "aprepitant": "2",
 "adalat": "2",
 "avandaryl": "2",
 "antispasmodic": "2",
 "actoplus met xr": "2",
 "adcetris": "2",
 "antrocol": "2",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "aminoglutethimide": "2",
 "adalat cc": "2",
 "atamet": "2",
 "avonex": "2",
 "apresazide": "2",
 "axocet": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "avandamet": "2",
 "aspirin/carisoprodol/codeine": "1",
 "aralen phosphate": "2",
 "aquavite-e": "2",
 "asthmacon": "2",
 "atropine/phenobarbital": "2",
 "accesspak for hiv pep expanded with viracept": "2",
 "atorvastatin": "2",
 "aqua gem-e": "2",
 "alagesic lq": "2",
 "actoplus met": "2",
 "adrenocot la": "2",
 "actos": "2",
 "atazanavir": "2",
 "amprenavir": "2",
 "aspirin/butalbital": "2",
 "amiodarone": "2",
 "acarbose": "2",
 "antabuse": "2",
 "accretropin": "2",
 "americet": "2",
 "atovaquone/proguanil": "1",
 "amino-opti-e": "2",
 "anolor 300": "2"}, "c": {"caduet": "2",
 "colchicine/probenecid": "2",
 "colcrys": "2",
 "cisplatin": "2",
 "chlorpropamide": "2",
 "cephadyn": "2",
 "carbatrol": "2",
 "cartia xt": "2",
 "celexa": "1",
 "cerebyx": "2",
 "chloramphenicol": "2",
 "clotrimazole troche": "2",
 "conivaptan": "2",
 "cordarone": "2",
 "carisoprodol compound": "1",
 "cardizem la": "2",
 "calan": "2",
 "cordarone iv": "2",
 "carisoprodol": "1",
 "crixivan": "2",
 "colchicine": "2",
 "cardizem monovial": "2",
 "clopine": "1",
 "carbidopa/entacapone/levodopa": "2",
 "cardizem cd": "2",
 "covera-hs": "2",
 "cilostazol": "2",
 "clobazam": "1",
 "chloroquine": "2",
 "cimetidine": "2",
 "clofarabine": "2",
 "citalopram": "1",
 "cinacalcet": "2",
 "cabazitaxel": "2",
 "carboplatin novaplus": "2",
 "carboplatin": "2",
 "carbamazepine": "2",
 "chloromycetin sodium succinate": "2",
 "carbidopa/levodopa": "2",
 "cardizem sr": "2",
 "clarithromycin": "2",
 "crestor": "2",
 "clozaril": "1",
 "cytadren": "2",
 "capacet": "2",
 "clotrimazole": "2",
 "clozapine synthon": "1",
 "chloromycetin": "2",
 "calan sr": "2",
 "chardonna-2": "2",
 "cimzia": "2",
 "clozapine": "1",
 "cyclosporine": "2",
 "cafatine pb": "2",
 "centrum singles-vitamin e": "2",
 "crizotinib": "2",
 "cerivastatin": "2",
 "certolizumab": "2",
 "coumadin": "1",
 "clolar": "2",
 "chloracol": "2",
 "cardizem": "2"}, "b": {"boceprevir": "2",
 "bellaphen-s": "2",
 "bellatal er": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "biaxin xl": "2",
 "butisol sodium": "2",
 "bosentan": "2",
 "bexarotene": "2",
 "bupap": "2",
 "biaxin": "2",
 "belcomp-pb": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "butibel": "2",
 "brentuximab": "2",
 "butex forte": "2",
 "butalbital compound": "2",
 "betaseron": "2",
 "butalbital": "2",
 "bidil": "2",
 "bellamor": "2",
 "bellaspas": "2",
 "black cohosh": "2",
 "busodium": "2",
 "bel-phen-ergot": "2",
 "baycadron": "2",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "butabarbital": "2",
 "barbidonna": "2",
 "baycol": "2",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine": "2",
 "bellatal": "2",
 "belladonna/butabarbital": "2",
 "bel-tabs": "2",
 "bucet": "2",
 "bellamine s": "2"}, "e": {"ery-tab": "2",
 "e-gems": "2",
 "emtricitabine/nelfinavir/tenofovir": "2",
 "eribulin": "2",
 "elixiral": "2",
 "exjade": "2",
 "e-600": "2",
 "erythrocin lactobionate": "2",
 "e.e.s.-400 filmtab": "2",
 "esgic-plus": "2",
 "e-400 clear": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "emend 2-day": "2",
 "e.e.s.-400": "2",
 "eryc": "2",
 "eloxatin": "2",
 "e-mycin": "2",
 "ethambutol": "2",
 "emend": "2",
 "etoposide": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "esomeprazole": "1",
 "eperbel-s": "2",
 "etravirine": "2",
 "esomeprazole/naproxen": "1",
 "ethionamide": "2",
 "erythrocin": "2",
 "eryped": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "erythromycin/sulfisoxazole": "2",
 "e.e.s. granules": "2",
 "erythrocin stearate filmtab": "2",
 "etanercept": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "emend 3-day": "2",
 "eryzole": "2",
 "ezol": "2",
 "embeda": "2",
 "e s p": "2",
 "e.e.s.-200": "2",
 "ergocomp-pb": "2",
 "ergocaffpb": "2",
 "e pherol": "2",
 "enbrel": "2",
 "e-caff p-b": "2",
 "equetro": "2",
 "extavia": "2",
 "equaline acid reducer": "2",
 "erythrocot": "2",
 "endolor": "2",
 "epitol": "2",
 "ergocaf-pb": "2",
 "erythromycin": "2",
 "esgic": "2",
 "efavirenz": "2",
 "ezetimibe/simvastatin": "2",
 "emend for injection": "2",
 "etopophos": "2"}, "d": {"dexamethasone/lidocaine": "2",
 "dexasone": "2",
 "dronedarone": "2",
 "donnatal": "2",
 "didanosine": "2",
 "diltzac": "2",
 "dalalone la": "2",
 "diastat": "1",
 "dexone la": "2",
 "dexacen-4": "2",
 "dalfopristin/quinupristin": "2",
 "deferasirox": "2",
 "dexamethasone intensol": "2",
 "delavirdine": "2",
 "diabeta": "2",
 "dymelor": "2",
 "decadron-la": "2",
 "dexone": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "dizac": "1",
 "dolmar": "2",
 "diquinol": "2",
 "diazepam": "1",
 "duetact": "2",
 "dexpak taperpak": "2",
 "dexacorten": "2",
 "dexacort phosphate in turbinaire": "2",
 "dopar": "2",
 "diltiazem hydrochloride cd": "2",
 "depakote sprinkles": "1",
 "depade": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "deferiprone": "3",
 "depakote": "1",
 "diastat acudial": "1",
 "diuretic ap-es": "2",
 "diabinese": "2",
 "diltiazem hydrochloride xt": "2",
 "diltia xt": "2",
 "dexasone la": "2",
 "decadron": "2",
 "dasatinib": "2",
 "decaject la": "2",
 "donnatal extentabs": "2",
 "diltiazem": "2",
 "dolgic lq": "2",
 "danocrine": "2",
 "dolgic plus": "2",
 "diltiazem hydrochloride sr": "2",
 "diflucan": "2",
 "dexacort-la": "2",
 "divalproex sodium": "1",
 "diltiazem hydrochloride xr": "2",
 "danazol": "2",
 "diastat pediatric": "1",
 "diazepam intensol": "1",
 "decadron phosphate, injectable": "2",
 "disulfiram": "2",
 "docetaxel": "2",
 "dexamethasone": "2",
 "dalalone": "2",
 "donnaphen": "2",
 "d-tal": "2",
 "de-sone la": "2",
 "decadron with xylocaine": "2",
 "dilacor xr": "2",
 "darunavir": "2",
 "dilantin": "2",
 "docefrez": "2",
 "depakote er": "1",
 "dexacort phosphate in respihaler": "2",
 "duragal-s": "2",
 "dolgic": "2",
 "dilt-xr": "2",
 "dapsone": "2",
 "dalalone dp": "2",
 "denzapine": "1",
 "decaject": "2"}, "g": {"griseofulicin": "2",
 "glynase prestab": "2",
 "golimumab": "2",
 "glycron": "2",
 "gold sodium thiomalate": "2",
 "glucophage xr": "2",
 "glimepiride/rosiglitazone": "2",
 "glucotrol": "2",
 "glucophage": "2",
 "glipizide": "2",
 "grisactin ultra": "2",
 "gengraf": "2",
 "glyset": "2",
 "glucotrol xl": "2",
 "glipizide xl": "2",
 "geone": "2",
 "glyburide": "2",
 "glipizide/metformin": "2",
 "griseofulvin": "2",
 "glimepiride": "2",
 "griseofulvic": "2",
 "grifulvin v": "2",
 "genotropin": "2",
 "gleevec": "2",
 "glynase": "2",
 "grisactin 250": "2",
 "g-1": "2",
 "glimepiride/pioglitazone": "2",
 "gris-peg": "2",
 "grisactin 500": "2",
 "glucovance": "2",
 "grepafloxacin": "2",
 "glumetza": "2",
 "glyburide/metformin": "2"}, "f": {"fulvicin u/f": "2",
 "fiortal": "2",
 "fortamet": "2",
 "fiorinal with codeine iii": "2",
 "fortovase": "2",
 "fludarabine": "2",
 "folex pfs": "2",
 "flagyl iv": "2",
 "fazaclo": "1",
 "fiorinal with codeine": "2",
 "fortabs": "2",
 "fiorinal": "2",
 "fioricet with codeine": "2",
 "fluvoxamine": "2",
 "femcet": "2",
 "fulvicin p/g": "2",
 "fluconazole": "2",
 "flagyl er": "2",
 "fiortal with codeine": "2",
 "flagyl 375": "2",
 "fluvastatin": "2",
 "fosaprepitant": "2",
 "fludara": "2",
 "fasigyn": "2",
 "felbamate": "2",
 "flagyl": "2",
 "fosamprenavir": "2",
 "ferriprox": "3",
 "fosphenytoin": "2",
 "floricet with codeine": "2",
 "fioricet": "2",
 "fiormor": "2",
 "furadantin": "2",
 "farbital": "2",
 "filgrastim": "2",
 "felbatol": "2",
 "fiorpap": "2"}, "i": {"interferon alfacon-1": "2",
 "intron a": "2",
 "innopran xl": "1",
 "invirase": "2",
 "imatinib": "2",
 "isocet": "2",
 "interferon alfa-n1": "2",
 "ixempra": "2",
 "inderal la": "1",
 "isoniazid": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "inderide la": "1",
 "isoptin": "2",
 "incivek": "2",
 "itraconazole": "2",
 "inderide": "1",
 "infergen": "2",
 "infliximab": "2",
 "ilosone": "2",
 "isoniazid/rifampin": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "ide-cet": "2",
 "ixabepilone": "2",
 "isonarif": "2",
 "indinavir": "2",
 "interferon alfa-2b": "2",
 "interferon alfa-2a": "2",
 "iodoquinol": "2",
 "isoptin sr": "2",
 "inderal": "1",
 "intelence": "2",
 "ipilimumab": "2",
 "isoptin iv": "2",
 "idenal": "2",
 "interferon alfa-2b/ribavirin": "2"}, "h": {"hhr": "2",
 "helidac": "2",
 "halaven": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrap-es": "2",
 "hydralazine": "2",
 "hyosophen": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "humatrope": "2",
 "hydrochlorothiazide/propranolol": "1",
 "hivid": "2",
 "hydroxypropyl chitosan/terbinafine topical": "1",
 "hydra-zide": "2",
 "hydroxychloroquine": "2",
 "haponal": "2",
 "hycamtin": "2",
 "humira": "2",
 "humatropen": "2",
 "hydralazine/isosorbide dinitrate": "2",
 "hexadrol": "2",
 "hydralazine plus": "2",
 "hyoscyamine/phenobarbital": "2"}, "k": {"kaletra": "2",
 "ketek": "2",
 "ketek pak": "2",
 "korlym": "2",
 "ketoconazole": "2",
 "kombiglyze xr": "2",
 "kepivance": "2"}, "j": {"janumet": "2",
 "janumet xr": "2",
 "jantoven": "1",
 "juvisync": "2",
 "jevtana": "2"}, "m": {"malarone pediatric": "1",
 "mygracet": "2",
 "margesic": "2",
 "montelukast": "2",
 "medidex la": "2",
 "metformin/repaglinide": "2",
 "morphine/naltrexone": "2",
 "micronase": "2",
 "mudrane gg": "2",
 "methotrexate": "2",
 "methotrexate lpf sodium": "2",
 "metaglip": "2",
 "mysoline": "2",
 "mesantoin": "1",
 "metformin/sitagliptin": "2",
 "metro iv": "2",
 "minotal": "2",
 "marten-tab": "2",
 "myambutol": "2",
 "migracet-pb": "2",
 "metronidazole": "2",
 "melphalan": "1",
 "metformin": "2",
 "metryl": "2",
 "mephobarbital": "2",
 "miglitol": "2",
 "medigesic": "2",
 "mibefradil": "2",
 "metformin/pioglitazone": "2",
 "mebaral": "2",
 "mifepristone": "2",
 "metformin/saxagliptin": "2",
 "metastron": "2",
 "mycelex troche": "2",
 "myochrysine": "2",
 "miconazole": "2",
 "medidex": "2",
 "metro": "2",
 "menopause support": "2",
 "mycobutin": "2",
 "matzim la": "2",
 "marpres": "2",
 "metformin/rosiglitazone": "2",
 "mevacor": "2",
 "macrodantin": "2",
 "mephenytoin": "1",
 "malarone": "1",
 "multaq": "2",
 "mudrane": "2",
 "mifeprex": "2",
 "macrobid": "2",
 "micomp-pb": "2"}, "l": {"livalo": "2",
 "lanreotide": "2",
 "larodopa": "2",
 "levsin with phenobarbital": "2",
 "lescol": "2",
 "luminal": "2",
 "lovastatin/niacin": "2",
 "luvox": "2",
 "laniroif": "2",
 "leflunomide": "3",
 "luvox cr": "2",
 "lopinavir/ritonavir": "2",
 "lovastatin": "2",
 "lamisil": "1",
 "linezolid": "2",
 "lipitor": "2",
 "lapatinib": "2",
 "leukine": "2",
 "levodopa": "2",
 "lufyllin-epg": "2",
 "lescol xl": "2",
 "lexiva": "2"}, "o": {"onfi": "1",
 "orinase": "2",
 "oravig": "2",
 "oxcarbazepine": "2",
 "oforta": "2",
 "orbivan": "2",
 "octreotide": "2",
 "oncovin": "2",
 "omnitrope": "2",
 "onxol": "2",
 "oxaliplatin": "2"}, "n": {"nifedipine": "2",
 "norvir soft gelatin": "2",
 "nevirapine": "2",
 "nitrofurantoin": "2",
 "nexium iv": "1",
 "nilotinib": "2",
 "naltrexone": "2",
 "nelarabine": "2",
 "nexium": "1",
 "nifediac cc": "2",
 "nizoral": "2",
 "norditropin nordiflex": "2",
 "nutr-e-sol": "2",
 "neoral": "2",
 "nexterone": "2",
 "nutropin": "2",
 "nutropin depot": "2",
 "nitro macro": "2",
 "norditropin": "2",
 "nutropin aq": "2",
 "nydrazid": "2",
 "nelfinavir": "2",
 "neulasta": "2",
 "nembutal sodium": "2",
 "noxafil": "2",
 "nembutal": "2",
 "niacin/simvastatin": "2",
 "neupogen": "2",
 "nifedical xl": "2",
 "nonbac": "2",
 "navelbine": "2",
 "norditropin flexpro": "2",
 "nateglinide": "2",
 "nefazodone": "2",
 "norvir": "2"}, "q": {"quineprox": "2",
 "quadrinal": "2",
 "quadrapax": "2",
 "quadramet": "3"}, "p": {"proguanil": "1",
 "priftin": "2",
 "paclitaxel protein-bound": "2",
 "pentobarbital": "2",
 "pletal": "2",
 "pyridium plus": "2",
 "phenobarbital": "2",
 "promacet": "2",
 "parcopa": "2",
 "primethasone": "2",
 "pediazole": "2",
 "peginterferon alfa-2a": "2",
 "peginterferon alfa-2b": "2",
 "procardia xl": "2",
 "phenytek": "2",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "propranolol": "1",
 "pitavastatin": "2",
 "pb-hyos": "2",
 "prominol": "2",
 "protonix iv": "1",
 "pyrelle hb": "2",
 "paraplatin": "2",
 "pravigard pac": "2",
 "prandin": "2",
 "pravastatin": "2",
 "pegintron": "2",
 "pharmagesic": "2",
 "procardia": "2",
 "pantoprazole": "1",
 "phenazoforte plus": "2",
 "pce dispertab": "2",
 "palifermin": "2",
 "phenytoin": "2",
 "platinol": "2",
 "primidone": "2",
 "pioglitazone": "2",
 "posicor": "2",
 "prandimet": "2",
 "pravachol": "2",
 "probenecid and colchicine": "2",
 "pylera": "2",
 "plaquenil": "2",
 "phrenilin forte": "2",
 "pegfilgrastim": "2",
 "phrenilin": "2",
 "phenytoin sodium, prompt": "2",
 "precose": "2",
 "protonix": "1",
 "phenaz plus": "2",
 "paclitaxel": "2",
 "posaconazole": "2",
 "proben-c": "2",
 "pacerone": "2",
 "phenylbutazone": "2",
 "protropin": "2",
 "platinol-aq": "2",
 "prevpac": "2",
 "pegasys": "2",
 "protostat": "2",
 "prezista": "2"}, "s": {"strontium-89 chloride": "2",
 "solurex la": "2",
 "sandimmune": "2",
 "singulair": "2",
 "soma": "1",
 "solganal": "2",
 "somatrem": "2",
 "saquinavir": "2",
 "soma compound": "1",
 "sodium phosphate p32": "2",
 "synercid": "2",
 "stalevo 150": "2",
 "sulfinpyrazone": "2",
 "spastrin": "2",
 "seconal": "2",
 "stalevo 75": "2",
 "spasmolin": "2",
 "sargramostim": "2",
 "serzone": "2",
 "solurex": "2",
 "simponi": "2",
 "soma compound with codeine": "1",
 "serathide": "2",
 "sinemet cr": "2",
 "serpazide": "2",
 "simvastatin": "2",
 "stalevo 50": "2",
 "seconal sodium": "2",
 "saizen": "2",
 "stalevo 125": "2",
 "sandostatin lar depot": "2",
 "samarium sm 153 lexidronam": "3",
 "sulfimycin": "2",
 "ser-ap-es": "2",
 "stalevo": "2",
 "stavudine": "2",
 "stalevo 100": "2",
 "simcor": "2",
 "sustiva": "2",
 "sedapap": "2",
 "servira": "2",
 "solfoton": "2",
 "sandostatin": "2",
 "secobarbital": "2",
 "simvastatin/sitagliptin": "2",
 "somatuline depot": "2",
 "st. john's wort": "2",
 "spasquid": "2",
 "serostim": "2",
 "sensipar": "2",
 "sprycel": "2",
 "stalevo 200": "2",
 "sinemet": "2",
 "sporanox pulsepak": "2",
 "sporanox": "2",
 "serpex": "2",
 "starlix": "2",
 "sylatron": "2",
 "somatropin": "2",
 "seconal sodium pulvules": "2"}, "r": {"rheumatrex dose pack": "2",
 "revia": "2",
 "repaglinide": "2",
 "raxar": "2",
 "rimactane": "2",
 "rosiglitazone": "2",
 "rifabutin": "2",
 "rezulin": "2",
 "rebif": "2",
 "rifater": "2",
 "robimycin": "2",
 "roferon-a": "2",
 "red yeast rice": "2",
 "rosuvastatin": "2",
 "ritonavir": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "rifampin": "2",
 "ridaura": "2",
 "repan": "2",
 "rifadin iv": "2",
 "riomet": "2",
 "reyataz": "2",
 "rescriptor": "2",
 "rifadin": "2",
 "re-pb hyos elixir": "2",
 "remicade": "2",
 "rebetron": "2"}, "u": {"uni serp": "2",
 "urelief plus": "2",
 "unipres": "2"}, "t": {"tenake": "2",
 "triaprin": "2",
 "tasigna": "2",
 "tarka": "2",
 "tuinal": "2",
 "troleandomycin": "2",
 "tencet": "2",
 "thioguanine": "2",
 "telzir": "2",
 "terbinex with eco formula": "1",
 "tri-hydroserpine": "2",
 "tao": "2",
 "tabloid": "2",
 "tracleer": "2",
 "tocilizumab": "2",
 "tinidazole": "2",
 "taxotere": "2",
 "tol-tab": "2",
 "tyzeka": "2",
 "taztia xt": "2",
 "troglitazone": "2",
 "telbivudine": "2",
 "trandolapril/verapamil": "2",
 "tiazac": "2",
 "teniposide": "2",
 "tolbutamide": "2",
 "theodrine": "2",
 "tagamet": "2",
 "toposar": "2",
 "terbinafine": "1",
 "trileptal": "2",
 "targretin": "2",
 "triad": "2",
 "tolinase": "2",
 "tedrigen": "2",
 "trecator-sc": "2",
 "tegretol": "2",
 "teczem": "2",
 "tagamet hb": "2",
 "telithromycin": "2",
 "thalidomide": "2",
 "thalomid": "2",
 "tegretol xr": "2",
 "trecator": "2",
 "taxol": "2",
 "topotecan": "2",
 "tolazamide": "2",
 "tindamax": "2",
 "tencon": "2",
 "telaprevir": "2",
 "trexall": "2",
 "tev-tropin": "2",
 "two-dyne": "2",
 "tykerb": "2"}, "w": {"warfarin": "1"}, "v": {"videx": "2",
 "vinblastine": "2",
 "vaprisol": "2",
 "vitamin e": "2",
 "verelan pm": "2",
 "vfend": "2",
 "vemurafenib": "2",
 "vita-plus e natural": "2",
 "viramune xr": "2",
 "viracept": "2",
 "vimovo": "1",
 "vumon": "2",
 "vinorelbine": "2",
 "valium": "1",
 "verelan": "2",
 "velban": "2",
 "verapamil": "2",
 "viramune": "2",
 "victrelis": "2",
 "vanadom": "1",
 "vepesid": "2",
 "vincristine": "2",
 "vincasar pfs": "2",
 "voriconazole": "2",
 "videx ec": "2",
 "valrelease": "1",
 "vytorin": "2",
 "vivitrol": "2"}, "y": {"yervoy": "2",
 "yodoxin": "2"}, "x": {"xalkori": "2"}, "z": {"zema pak": "2",
 "zorbtive": "2",
 "zerit": "2",
 "zebutal": "2",
 "zelboraf": "2",
 "zafirlukast": "2",
 "zerit xr": "2",
 "zalcitabine": "2",
 "zaponex": "1",
 "zocor": "2",
 "zetran": "1",
 "zyvox": "2"}}];