interactions["botulism-immune-globulin,babybig"]=["botulism-immune-globulin,babybig", {"a": {"aspirin/chlorpheniramine/dextromethorphan/phenylpropanolamine": "3",
 "aspirin/hydrocodone": "3",
 "anacin": "3",
 "amphotericin b liposomal": "3",
 "aspergum": "3",
 "amphotericin b lipid complex": "3",
 "aspirin/caffeine/orphenadrine": "3",
 "ascriptin enteric": "3",
 "attenuvax": "2",
 "advil liqui-gels": "3",
 "aspirin/chlorpheniramine/phenylephrine": "3",
 "aspirin/meprobamate": "3",
 "aflaxen": "3",
 "aspirin/oxycodone": "3",
 "advil pm": "3",
 "aspir-mox": "3",
 "acetaminophen/caffeine/phenyltoloxamine/salicylamide": "3",
 "aspirin/caffeine/dihydrocodeine": "3",
 "aspiritab": "3",
 "aspirin/phenyltoloxamine": "3",
 "ascomp with codeine": "3",
 "aspirin/diphenhydramine/phenylpropanolamine": "3",
 "alor 5/500": "3",
 "argesic-sa": "3",
 "alka-seltzer plus flu formula": "3",
 "addaprin": "3",
 "anaflex": "3",
 "aspirin buffered": "3",
 "acetaminophen/aspirin/caffeine/salicylamide": "3",
 "amikacin": "3",
 "aspirin/pravastatin": "3",
 "acetaminophen/caffeine/magnesium salicylate": "3",
 "arthritis pain": "3",
 "asacol": "3",
 "amphocin": "3",
 "amphotericin b cholesteryl sulfate": "3",
 "acetaminophen/aspirin": "3",
 "all day pain relief": "3",
 "anaprox": "3",
 "acetaminophen/magnesium salicylate/pamabrom": "3",
 "aspirin/butalbital/caffeine/codeine": "3",
 "aspirin/caffeine": "3",
 "amphotericin b": "3",
 "accesspak for hiv pep expanded with viracept": "3",
 "aspir 81": "3",
 "alka-seltzer extra strength": "3",
 "acetaminophen/caffeine/phenylpropanolamine/salicylamide": "3",
 "advil children's allergy sinus": "3",
 "acetaminophen/aspirin/caffeine": "3",
 "aleve": "3",
 "azulfidine": "3",
 "aspir-low": "3",
 "adult strength": "3",
 "advil cold and sinus liqui-gels": "3",
 "aspirin/methocarbamol": "3",
 "arthriten": "3",
 "amikin": "3",
 "a-g profen": "3",
 "alka-seltzer wake-up call!": "3",
 "aggrenox": "3",
 "arthropan": "3",
 "advil allergy sinus": "3",
 "alka-seltzer original": "3",
 "aspirin/pseudoephedrine": "3",
 "ascriptin maximum strength": "3",
 "amigesic": "3",
 "ambisome": "3",
 "alka-seltzer lemon-lime": "3",
 "aredia": "3",
 "aspirin/butalbital/caffeine": "3",
 "acetylsalicylic acid": "3",
 "advil migraine": "3",
 "all day relief": "3",
 "anacin advanced headache formula": "3",
 "arthritis pain formula": "3",
 "aspirin low strength": "3",
 "advil infant's concentrated drops": "3",
 "actiprofen": "3",
 "alka-seltzer plus cold formula": "3",
 "alka-seltzer pm": "3",
 "aspirin/diphenhydramine": "3",
 "acam2000": "2",
 "aspirin/chlorpheniramine/phenylpropanolamine": "3",
 "acetaminophen/salicylamide": "3",
 "anacin max strength": "3",
 "azdone": "3",
 "asacol hd": "3",
 "aspirin": "3",
 "acetaminophen/aspirin/phenylpropanolamine": "3",
 "aclasta": "3",
 "aspirin/calcium carbonate": "3",
 "aleve-d sinus &amp; cold": "3",
 "aspirin/dipyridamole": "3",
 "acuprin 81": "3",
 "aspirin/citric acid/sodium bicarbonate": "3",
 "acetaminophen/phenyltoloxamine/salicylamide": "3",
 "advil junior strength": "3",
 "azulfidine en-tabs": "3",
 "accesspak for hiv pep expanded with kaletra": "3",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "3",
 "aspirin/chlorpheniramine/dextromethorphan": "3",
 "amikin pediatric": "3",
 "anaprox-ds": "3",
 "aspirin/carisoprodol/codeine": "3",
 "aspirin/caffeine/propoxyphene": "3",
 "ascriptin": "3",
 "atripla": "3",
 "actron": "3",
 "amphotec": "3",
 "aspirin/carisoprodol": "3",
 "arthrotec": "3",
 "aspirin/brompheniramine/dextromethorphan/phenylpropanolamine": "3",
 "anabar": "3",
 "advil": "3",
 "aspirtab": "3",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "3",
 "adefovir": "3",
 "aspircaf": "3",
 "atrosept": "3",
 "advil children's cold": "3",
 "aspirin lite coat": "3",
 "aspirin/butalbital": "3",
 "accesspak for hiv pep basic": "3",
 "aspirin/codeine": "3",
 "advil cold and sinus": "3",
 "aspirin/pentazocine": "3",
 "ansaid": "3",
 "abelcet": "3",
 "aspir-mox ib": "3",
 "acetaminophen/chlorpheniramine/phenylephrine/salicylamide": "3",
 "advil children's": "3",
 "apriso": "3",
 "aspirin/caffeine/salicylamide": "3",
 "arthritis foundation pain reliever": "3",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "3"}, "c": {"cafgesic forte": "3",
 "cisplatin": "3",
 "cystex": "3",
 "cerebyx": "2",
 "cvs extra strength headache relief": "3",
 "cystemms-v": "3",
 "carisoprodol compound": "3",
 "combiflex": "3",
 "clinoril": "3",
 "caffeine/pheniramine/phenylephrine/sodium citrate/sodium salicylate": "3",
 "capastat sulfate": "3",
 "cidofovir": "3",
 "chlorpheniramine/ibuprofen/pseudoephedrine": "3",
 "comfort pac with naproxen": "3",
 "cataflam": "3",
 "cope": "3",
 "choline salicylate/magnesium salicylate": "3",
 "caldolor": "3",
 "combunox": "3",
 "cafgesic": "3",
 "childrens ibuprofen berry": "3",
 "capreomycin": "3",
 "canasa pac": "3",
 "choline magnesium trisalicylate": "3",
 "canasa": "3",
 "coly mycin m": "3",
 "colazal": "3",
 "cidomycin": "3",
 "complera": "3",
 "celecoxib": "3",
 "colistimethate": "3",
 "capastat": "3",
 "combiflex es": "3",
 "cyclosporine": "3",
 "children's motrin": "3",
 "caffeine/magnesium salicylate": "3",
 "cmt": "3",
 "choline salicylate": "3",
 "celebrex": "3",
 "cap-profen": "3",
 "cambia": "3"}, "b": {"balsalazide": "3",
 "bcg": "2",
 "b c powder": "3",
 "bayer extra strength back &amp; body": "3",
 "bacitracin": "3",
 "bayer advanced aspirin": "3",
 "bydureon": "2",
 "bc headache": "3",
 "benzoic acid/methenamine/sodium salicylate": "3",
 "be-flex plus": "3",
 "buffered aspirin": "3",
 "boniva": "3",
 "bayer aspirin with heart advantage": "3",
 "butalbital compound": "3",
 "bayer am": "3",
 "bromfenac": "3",
 "bufferin": "3",
 "bextra": "3",
 "baci-rx": "3",
 "bayer pm": "3",
 "bayer aspirin extra strength plus": "3",
 "b c powder arthritis strength": "3",
 "buffex": "3",
 "bayer women's low dose plus calcium": "3",
 "bayer aspirin": "3",
 "byetta": "2",
 "bufferin arthritis strength": "3",
 "bufferin extra strength": "3",
 "bc fast pain relief": "3",
 "bayer women's aspirin with calcium": "3",
 "buffasal": "3",
 "bayer aspirin regimen": "3",
 "biavax ii": "2",
 "bufferin low dose": "3",
 "bayer select backache pain formula": "3",
 "bayer children's aspirin": "3",
 "baciim": "3",
 "by-ache": "3"}, "e": {"ecotrin": "3",
 "ecotrin maximum strength": "3",
 "excedrin extra strength": "3",
 "emtricitabine/rilpivirine/tenofovir": "3",
 "easprin": "3",
 "effervescent pain relief": "3",
 "emtricitabine/nelfinavir/tenofovir": "3",
 "ethotoin": "2",
 "etodolac": "3",
 "exjade": "3",
 "exenatide": "2",
 "ec-naprosyn": "3",
 "excedrin back &amp; body": "3",
 "ed-flex": "3",
 "excedrin migraine": "3",
 "endodan": "3",
 "efavirenz/emtricitabine/tenofovir": "3",
 "extra strength bayer": "3",
 "entercote": "3",
 "etidronate": "3",
 "ecpirin": "3",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "3",
 "eskalith": "3",
 "emagrin": "3",
 "eskalith-cr": "3",
 "empirin with codeine": "3",
 "entaprin": "3",
 "empirin": "3",
 "emtricitabine/tenofovir": "3",
 "excedrin menstrual complete": "3",
 "excedrin": "3",
 "equagesic": "3",
 "esomeprazole/naproxen": "3",
 "ecotrin adult low strength": "3"}, "d": {"darvon compound 32": "3",
 "duexis": "3",
 "doans pills extra strength": "3",
 "dryvax": "2",
 "deferasirox": "3",
 "daypro": "3",
 "damason-p": "3",
 "diclofenac": "3",
 "darpaz": "3",
 "diflunisal": "3",
 "durabac forte": "3",
 "durabac": "3",
 "dolorex": "3",
 "dilantin": "2",
 "dristan sinus": "3",
 "diphenhydramine/magnesium salicylate": "3",
 "diurex": "3",
 "dolsed": "3",
 "darcalma": "3",
 "doan's pills": "3",
 "duract": "3",
 "dolobid": "3",
 "darvon compound-65": "3",
 "dipentum": "3",
 "duraxin": "3",
 "disalcid": "3",
 "doans pm": "3",
 "didronel": "3",
 "diphenhydramine/ibuprofen": "3",
 "diclofenac/misoprostol": "3",
 "dewitt's pain reliever": "3",
 "didronel iv": "3"}, "g": {"gentamicin": "3",
 "giazo": "3",
 "goodys extra strength": "3",
 "goody's extra-strength headache powders": "3",
 "gengraf": "3",
 "genpril": "3",
 "genprin": "3",
 "genacote": "3",
 "garamycin": "3",
 "goody's body pain": "3",
 "goodys headache powders": "3",
 "genace": "3",
 "gallium nitrate": "3",
 "ganite": "3",
 "genasan": "3",
 "gennin-fc": "3"}, "f": {"fiortal": "3",
 "fiorinal with codeine iii": "3",
 "folex pfs": "3",
 "fiorinal with codeine": "3",
 "fungizone": "3",
 "fortabs": "3",
 "fiorinal": "3",
 "fasprin": "3",
 "feldene": "3",
 "fiv-asa": "3",
 "famotidine/ibuprofen": "3",
 "fosphenytoin": "2",
 "fenoprofen": "3",
 "flumist": "2",
 "flurbiprofen": "3",
 "foscarnet": "3",
 "frenadol": "3",
 "fiormor": "3",
 "foscavir": "3",
 "farbital": "3",
 "fiortal with codeine": "3",
 "fungizone for tissue culture": "3"}, "i": {"ibuprofen/oxycodone": "3",
 "ibudone": "3",
 "ibu-200": "3",
 "indocin sr": "3",
 "influenza virus vaccine, h1n1, live": "2",
 "indomethacin": "3",
 "indocin": "3",
 "ibu-8": "3",
 "ibuprofen/pseudoephedrine": "3",
 "ibu-tab": "3",
 "ibu-4": "3",
 "ibu-6": "3",
 "ibuprofen": "3",
 "ibandronate": "3",
 "influenza virus vaccine, live, trivalent": "2",
 "ibuprofen pmr": "3",
 "idenal": "3",
 "ibu": "3",
 "indocin iv": "3"}, "h": {"hyophen": "3",
 "hepsera": "3",
 "hydrocodone/ibuprofen": "3",
 "halfprin": "3",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "3",
 "heartline": "3",
 "haltran": "3"}, "k": {"kanamycin": "3",
 "kantrex": "3",
 "ketorolac": "3",
 "kneerelief": "3",
 "ketoprofen": "3"}, "m": {"motrin cold and flu": "3",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine": "2",
 "mst": "3",
 "migralex": "3",
 "mobic": "3",
 "mycifradin": "3",
 "meruvax ii": "2",
 "minitabs": "3",
 "mobigesic": "3",
 "midol traditional": "3",
 "marthritic": "3",
 "methotrexate": "3",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine/varicella virus vaccine": "2",
 "measles virus vaccine": "2",
 "motrin ib": "3",
 "mesantoin": "2",
 "magsal": "3",
 "mobidin": "3",
 "mefenamic acid": "3",
 "methotrexate lpf sodium": "3",
 "mhp-a": "3",
 "motrin migraine pain": "3",
 "mumps virus vaccine/rubella virus vaccine": "2",
 "micrainin": "3",
 "meclofenamate": "3",
 "motrin sinus headache": "3",
 "msp-blu": "3",
 "medi-seltzer": "3",
 "meloxicam": "3",
 "mumps virus vaccine": "2",
 "mesasal enteric coated": "3",
 "momentum": "3",
 "medique pain-off": "3",
 "midol maximum strength cramp formula": "3",
 "midol extended relief": "3",
 "motrin pm": "3",
 "m-m-r ii": "2",
 "mag-phen": "3",
 "mumpsvax": "2",
 "mesalamine": "3",
 "motrin infant drops": "3",
 "medique medi-seltzer": "3",
 "motrin junior strength": "3",
 "methoxyflurane": "3",
 "m-r-vax ii": "2",
 "midol ib": "3",
 "motrin childrens": "3",
 "mephenytoin": "2",
 "motrin ib sinus": "3",
 "motrin childrens cold": "3",
 "menadol": "3",
 "meclomen": "3",
 "mono-gesic": "3",
 "magan": "3",
 "magnesium salicylate/phenyltoloxamine": "3",
 "myogesic": "3",
 "measles virus vaccine/rubella virus vaccine": "2",
 "motrin": "3",
 "magnesium salicylate": "3",
 "magnaprin": "3"}, "l": {"litecoat aspirin": "3",
 "leader naproxen sodium": "3",
 "lodine xl": "3",
 "lithonate": "3",
 "lodine": "3",
 "lithobid": "3",
 "lialda": "3",
 "low dose asa": "3",
 "lortab asa": "3",
 "lyphocin": "3",
 "laniroif": "3",
 "lithotabs": "3",
 "levacet": "3",
 "lithium": "3",
 "lansoprazole/naproxen": "3",
 "lobac": "3"}, "o": {"orphengesic": "3",
 "orphengesic forte": "3",
 "orudis": "3",
 "oxaprozin": "3",
 "orudis kt": "3",
 "oruvail": "3",
 "orimune": "2",
 "olsalazine": "3"}, "n": {"nebcin": "3",
 "nuprin backache caplet": "3",
 "nebupent": "3",
 "nalfon": "3",
 "naprosyn": "3",
 "naproxen/sumatriptan": "3",
 "norwich aspirin": "3",
 "neomycin": "3",
 "norgesic forte": "3",
 "nexcede": "3",
 "nuprin": "3",
 "neo-fradin": "3",
 "norgesic": "3",
 "naproxen": "3",
 "naprelan": "3",
 "nebcin pediatric": "3",
 "nabumetone": "3",
 "neoral": "3",
 "netromycin": "3",
 "naproxen sodium ds": "3",
 "netilmicin": "3",
 "naproxen/pseudoephedrine": "3",
 "novasal": "3",
 "neoprofen": "3",
 "neo-tab": "3"}, "q": {"q-profen": "3"}, "p": {"phosphasal": "3",
 "pentasa": "3",
 "pamprin all day relief": "3",
 "panritis forte": "3",
 "pentam": "3",
 "phenytek": "2",
 "pravigard pac": "3",
 "p-a-c analgesic": "3",
 "pc-cap": "3",
 "prevacid naprapac 375": "3",
 "p-a-c": "3",
 "poliovirus vaccine, live, trivalent": "2",
 "pentam 300": "3",
 "prevacid naprapac 500": "3",
 "prograf": "3",
 "ponstel": "3",
 "percodan-demi": "3",
 "painaid": "3",
 "prosed ec": "3",
 "phenytoin": "2",
 "prosed ds": "3",
 "platinol": "3",
 "pentacarinat": "3",
 "phosenamine": "3",
 "proquad": "2",
 "peganone": "2",
 "propoxyphene compound 65": "3",
 "prevacid naprapac": "3",
 "phenytoin sodium, prompt": "2",
 "penthrane": "3",
 "piroxicam": "3",
 "pamprin max menstrual pain relief": "3",
 "pentamidine": "3",
 "phenylbutazone": "3",
 "pamidronate": "3",
 "pamprin cramp menstrual pain relief": "3",
 "platinol-aq": "3",
 "panasal 5/500": "3",
 "percodan": "3",
 "polymyxin b": "3"}, "s": {"saleto-200": "3",
 "sandimmune": "3",
 "saleto": "3",
 "salflex": "3",
 "soma compound": "3",
 "sine-aid ib": "3",
 "sulindac": "3",
 "soma compound with codeine": "3",
 "salsalate": "3",
 "saleto-800": "3",
 "saleto-d": "3",
 "smallpox vaccine": "2",
 "sirolimus": "3",
 "sloprin": "3",
 "salofalk": "3",
 "st. joseph aspirin": "3",
 "salsitab": "3",
 "synalgos-dc": "3",
 "saleto-600": "3",
 "sodium thiosalicylate": "3",
 "st. joseph 81 mg chewable aspirin": "3",
 "supac": "3",
 "sodium salicylate": "3",
 "septopal": "3",
 "stanback analgesic": "3",
 "scot-tussin original": "3",
 "sudafed 12 hour pressure+pain": "3",
 "sprix": "3",
 "stanback fast pain relief": "3",
 "st. joseph 81 mg aspirin enteric safety-coated": "3",
 "sulfasalazine": "3",
 "saleto-400": "3",
 "sulfazine": "3",
 "streptomycin": "3"}, "r": {"robaxisal": "3",
 "reclast": "3",
 "rotavirus vaccine": "2",
 "rufen": "3",
 "rheumatrex dose pack": "3",
 "rofecoxib": "3",
 "rowasa sulfite free": "3",
 "rowasa": "3",
 "rhinocaps": "3",
 "rotarix": "2",
 "rhinogesic": "3",
 "rexolate": "3",
 "reprexain": "3",
 "rubella virus vaccine": "2",
 "rapamune": "3",
 "rotateq": "2",
 "relafen": "3",
 "roxiprin": "3",
 "rotashield": "2"}, "u": {"uretron": "3",
 "urimax": "3",
 "ursinus": "3",
 "utrona-c": "3",
 "utira-c": "3",
 "uritact ds": "3",
 "urimar-t": "3",
 "urised": "3",
 "utira": "3",
 "utrona": "3",
 "uretron ds": "3",
 "urapine": "3",
 "uritin": "3",
 "usept": "3",
 "urisym": "3",
 "uta": "3",
 "uro blue": "3",
 "uritact-ec": "3",
 "uticap": "3",
 "ustell": "3",
 "urelle": "3",
 "uribel": "3"}, "t": {"toradol": "3",
 "tobramycin": "3",
 "tusal": "3",
 "tolectin 600": "3",
 "tolectin": "3",
 "tobi": "3",
 "trexall": "3",
 "tolmetin": "3",
 "theracys": "2",
 "tice bcg": "2",
 "truvada": "3",
 "toradol iv/im": "3",
 "tenofovir": "3",
 "tetra-mag": "3",
 "toradol im": "3",
 "trac tabs 2x": "3",
 "typhoid vaccine, live": "2",
 "trilisate": "3",
 "treximet": "3",
 "tolectin ds": "3",
 "torisel": "3",
 "tricosal": "3",
 "tacrolimus": "3",
 "telavancin": "3",
 "tice bcg vaccine": "2",
 "tri-buffered aspirin": "3",
 "temsirolimus": "3",
 "talwin compound": "3",
 "therapy bayer": "3"}, "v": {"vancocin hcl": "3",
 "voltaren-xr": "3",
 "vancomycin": "3",
 "voltaren": "3",
 "vancocin hcl pulvules": "3",
 "vioxx": "3",
 "vimovo": "3",
 "varivax": "2",
 "vivotif berna vaccine": "2",
 "valdecoxib": "3",
 "varicella virus vaccine": "2",
 "vibativ": "3",
 "vancocin": "3",
 "vistide": "3",
 "vicoprofen": "3",
 "viread": "3",
 "vivotif berna": "2",
 "vanquish": "3"}, "y": {"yellow fever vaccine": "2",
 "ysp aspirin": "3",
 "yf-vax": "2"}, "z": {"zorprin": "3",
 "zipsor": "3",
 "zostavax": "2",
 "zometa": "3",
 "zoster vaccine live": "2",
 "zero-order release": "3",
 "zoledronic acid": "3"}}];