interactions["cabergoline"]=["cabergoline", {"a": {"aldoril 25": "2",
 "avalide": "2",
 "accuretic": "2",
 "azithromycin dose pack": "2",
 "atenolol/chlorthalidone": "2",
 "amoxapine": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "acetaminophen/propoxyphene": "3",
 "abilify": "2",
 "atacand hct": "2",
 "aldoril d50": "2",
 "amlobenz": "2",
 "amyl nitrite/sodium nitrite/sodium thiosulfate": "2",
 "amturnide": "2",
 "apokyn": "2",
 "acebutolol": "2",
 "antinaus 50": "2",
 "adalat": "2",
 "aldoril d30": "2",
 "alcohol": "2",
 "aliskiren/valsartan": "2",
 "amiloride/hydrochlorothiazide": "2",
 "aldactone": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "anergan 50": "2",
 "amyl nitrite": "2",
 "atacand": "2",
 "asenapine": "2",
 "altace": "2",
 "apo-go pen": "2",
 "atenolol": "2",
 "amoxicillin/clarithromycin/lansoprazole": "3",
 "azilsartan medoxomil/chlorthalidone": "2",
 "amlodipine/olmesartan": "2",
 "accupril": "2",
 "adalat cc": "2",
 "aliskiren/amlodipine": "2",
 "aldoril": "2",
 "azithromycin/trovafloxacin": "2",
 "amlodipine/telmisartan": "2",
 "apresazide": "2",
 "aquazide h": "2",
 "aldoril 15": "2",
 "afeditab cr": "2",
 "avapro": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "amlodipine": "2",
 "arfonad": "2",
 "aldoclor-250": "2",
 "alcohol and dextrose injections usp hypertonic": "2",
 "apo-go": "2",
 "azor": "2",
 "alcohol 5% in dextrose 5%": "2",
 "amlodipine/valsartan": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "aldactazide": "2",
 "amiloride": "2",
 "azilsartan medoxomil": "2",
 "amlodipine/atorvastatin": "2",
 "aceon": "2",
 "asendin": "2",
 "aldoclor-150": "2",
 "aspirin/caffeine/propoxyphene": "3",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "apomorphine": "2",
 "aripiprazole": "2",
 "apresoline": "2",
 "azithromycin": "2",
 "amlodipine/benazepril": "2",
 "abilify discmelt": "2"}, "c": {"caduet": "2",
 "chlorthalidone/clonidine": "2",
 "clonidine er": "2",
 "catapres": "2",
 "chlorothiazide/methyldopa": "2",
 "codeine/promethazine": "2",
 "compro": "2",
 "cardene sr": "2",
 "cozaar": "2",
 "captopril/hydrochlorothiazide": "2",
 "clonidine": "2",
 "compazine spansule": "2",
 "corzide": "2",
 "capozide 50/25": "2",
 "cardizem la": "2",
 "captopril": "2",
 "calan": "2",
 "cascor": "2",
 "cardizem monovial": "2",
 "cardene": "2",
 "cleviprex": "2",
 "capozide 25/15": "2",
 "catapres-tts": "2",
 "clorpres": "2",
 "cardizem cd": "2",
 "cartia xt": "2",
 "chlorthalidone/reserpine": "2",
 "covera-hs": "2",
 "chlorthalidone": "2",
 "capozide 50/15": "2",
 "chlorpromazine": "2",
 "candesartan/hydrochlorothiazide": "2",
 "corzide 80/5": "2",
 "capoten": "2",
 "clopine": "2",
 "corzide 40/5": "2",
 "candesartan": "2",
 "chlorothiazide": "2",
 "cyanide antidote kit": "2",
 "cardizem sr": "2",
 "clarithromycin": "3",
 "carvedilol": "2",
 "clozaril": "2",
 "clevidipine": "2",
 "carduran": "2",
 "cardene iv": "2",
 "compazine": "2",
 "capozide": "2",
 "capozide 25/25": "2",
 "clozapine synthon": "2",
 "chlorothiazide/reserpine": "2",
 "calan sr": "2",
 "coreg": "2",
 "cardura": "2",
 "clozapine": "2",
 "coreg cr": "2",
 "cardura xl": "2",
 "corgard": "2",
 "codeine phosphate-promethazine hcl": "2",
 "carozide": "2",
 "cardizem": "2",
 "codeine/phenylephrine/promethazine": "2"}, "b": {"betaxolol": "2",
 "blocadren": "2",
 "benazepril/hydrochlorothiazide": "2",
 "biaxin xl": "3",
 "brevibloc": "2",
 "bisoprolol": "2",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "benzthiazide": "2",
 "biaxin": "3",
 "bumetanide": "2",
 "bidil": "2",
 "balacet": "3",
 "benicar hct": "2",
 "bystolic": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "betapace af": "2",
 "bepridil": "2",
 "bendroflumethiazide": "2",
 "bumex": "2",
 "benicar": "2",
 "bendroflumethiazide/nadolol": "2",
 "betapace": "2"}, "e": {"eplerenone": "2",
 "ery-tab": "3",
 "ethyl alcohol": "2",
 "ezide": "2",
 "edecrin": "2",
 "etrafon": "2",
 "erythrocin lactobionate": "3",
 "edarbyclor": "2",
 "esmolol": "2",
 "enalapril/hydrochlorothiazide": "2",
 "e.e.s.-400": "3",
 "eprosartan": "2",
 "eryc": "3",
 "e.e.s.-400 filmtab": "3",
 "e-mycin": "3",
 "enalapril/felodipine": "2",
 "erythrocin": "3",
 "eryped": "3",
 "erythromycin/sulfisoxazole": "3",
 "e.e.s. granules": "3",
 "erythrocin stearate filmtab": "3",
 "exforge": "2",
 "ethacrynic acid": "2",
 "eryzole": "3",
 "ethanol": "2",
 "e s p": "3",
 "e.e.s.-200": "3",
 "exforge hct": "2",
 "esimil": "2",
 "etrafon forte": "2",
 "exna": "2",
 "enalapril": "2",
 "esidrix": "2",
 "erythrocot": "3",
 "edarbi": "2",
 "erythromycin": "3",
 "eprosartan/hydrochlorothiazide": "2"}, "d": {"diovan": "2",
 "darvon compound 32": "3",
 "diuril sodium": "2",
 "demi-regroton": "2",
 "darvocet-n 100": "3",
 "demadex": "2",
 "dibenzyline": "2",
 "darvon-n": "3",
 "dilatrate-sr": "2",
 "deserpidine/hydrochlorothiazide": "2",
 "doxazosin": "2",
 "diuril": "2",
 "diucardin": "2",
 "dutasteride/tamsulosin": "2",
 "demadex iv": "2",
 "diltiazem hydrochloride cd": "2",
 "datscan": "2",
 "diovan hct": "2",
 "dextromethorphan/promethazine": "2",
 "diltiazem/enalapril": "2",
 "darvon": "3",
 "duo-vil": "2",
 "diuretic ap-es": "2",
 "dehydrated alcohol": "2",
 "diltiazem hydrochloride xt": "2",
 "deponit": "2",
 "diltiazem hydrochloride xr": "2",
 "diaqua-2": "2",
 "diltiazem": "2",
 "diupres-250": "2",
 "dyrenium": "2",
 "diltiazem hydrochloride sr": "2",
 "diupres-500": "2",
 "dyazide": "2",
 "darvon compound-65": "3",
 "diltzac": "2",
 "duraclon": "2",
 "droperidol/fentanyl": "2",
 "dynacirc cr": "2",
 "droperidol": "2",
 "dutoprol": "2",
 "demerol": "2",
 "dilacor xr": "2",
 "diltia xt": "2",
 "diaqua": "2",
 "diazoxide": "2",
 "darvocet-n 50": "3",
 "dilt-xr": "2",
 "doxadura": "2",
 "dynacirc": "2",
 "denzapine": "2",
 "darvocet a500": "3"}, "g": {"guanethidine/hydrochlorothiazide": "2",
 "geodon": "2",
 "guanethidine": "2"}, "f": {"fluphenazine": "2",
 "fanapt": "2",
 "furosemide": "2",
 "fluoxetine/olanzapine": "2",
 "fosinopril": "2",
 "felodipine": "2",
 "fosinopril/hydrochlorothiazide": "2",
 "flomax": "2",
 "flumezide": "2",
 "fazaclo": "2"}, "i": {"isosorbide mononitrate": "2",
 "isradipine": "2",
 "indapamide": "2",
 "innopran xl": "2",
 "irbesartan": "2",
 "isdn": "2",
 "isordil tembids": "2",
 "innovar": "2",
 "inapsine": "2",
 "imdur": "2",
 "inderide la": "2",
 "isordil titradose": "2",
 "invega": "2",
 "isoptin": "2",
 "isordil": "2",
 "inderide": "2",
 "ilosone": "3",
 "inderal la": "2",
 "inspra": "2",
 "isochron": "2",
 "isosorbide dinitrate": "2",
 "iloperidone": "2",
 "ismelin": "2",
 "isoptin sr": "2",
 "inderal": "2",
 "invega sustenna": "2",
 "isoptin iv": "2",
 "ismo": "2",
 "ioflupane i 123": "2",
 "isoditrate": "2"}, "h": {"hhr": "2",
 "haloperidol": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hydroserpine 1": "2",
 "hyperstat iv": "2",
 "hydro-reserp": "2",
 "hydrochlorothiazide/methyldopa": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrochlorothiazide/timolol": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydropres-50": "2",
 "hydrap-es": "2",
 "hydroserpine": "2",
 "hydroflumethiazide/reserpine": "2",
 "hydrochlorothiazide/losartan": "2",
 "hydralazine": "2",
 "hydroflumethiazide": "2",
 "hydrodiuril": "2",
 "hygroton": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hyzaar": "2",
 "haldol decanoate": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydrochlorothiazide/moexipril": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "hydro par": "2",
 "hydrochlorothiazide/propranolol": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "hyperstat": "2",
 "hydroserp": "2",
 "hydra-zide": "2",
 "hydrochlorothiazide/valsartan": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrochlorothiazide/reserpine": "2",
 "hydralazine/isosorbide dinitrate": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydropres-25": "2",
 "hydrochlorothiazide": "2",
 "hydralazine plus": "2",
 "haldol": "2"}, "k": {"kerlone": "2",
 "kapvay": "2",
 "kava": "2"}, "j": {"jalyn": "2",
 "jenloga": "2"}, "m": {"meperidine": "2",
 "minoxidil": "2",
 "mellaril-s": "2",
 "mavik": "2",
 "metoprolol succinate er": "2",
 "methotrimeprazine": "2",
 "monopril": "2",
 "molindone": "2",
 "meperidine/promethazine": "2",
 "micardis hct": "2",
 "maxzide": "2",
 "micardis": "2",
 "monopril hct": "2",
 "midamor": "2",
 "minitran": "2",
 "minizide": "2",
 "m-phen": "2",
 "mepergan": "2",
 "metoclopramide": "2",
 "meperitab": "2",
 "mibefradil": "2",
 "monoket": "2",
 "mepergan fortis": "2",
 "moduretic": "2",
 "mykrox": "2",
 "maxolon": "2",
 "mellaril": "2",
 "meprozine": "2",
 "metolazone": "2",
 "moban": "2",
 "memantine": "1",
 "maxzide-25": "2",
 "metozolv odt": "2",
 "matzim la": "2",
 "microzide": "2",
 "moexipril": "2",
 "methdilazine": "2",
 "moduretic 5-50": "2",
 "metoprolol": "2",
 "mesoridazine": "2",
 "minipress": "2",
 "marpres": "2"}, "l": {"lozol": "2",
 "losartan": "2",
 "lotensin hct": "2",
 "loqua": "2",
 "lurasidone": "2",
 "lopressor": "2",
 "loxitane im": "2",
 "loxitane": "2",
 "lasix": "2",
 "lo-aqua": "2",
 "lotrel": "2",
 "loxitane c": "2",
 "loniten": "2",
 "lexxel": "2",
 "lopressor hct": "2",
 "largon": "2",
 "loxapine": "2",
 "labetalol": "2",
 "lisinopril": "2",
 "levoprome": "2",
 "latuda": "2"}, "o": {"orap": "2",
 "oreticyl 25": "2",
 "olmesartan": "2",
 "oraverse": "2",
 "oreticyl 50": "2",
 "oretic": "2",
 "olanzapine": "2",
 "ormazine": "2",
 "oreticyl forte": "2"}, "n": {"nifedipine": "2",
 "naturetin": "2",
 "naturetin-10": "2",
 "nitrolingual pumpspray": "2",
 "nitrostat": "2",
 "nicardipine": "2",
 "nitroglycerin": "2",
 "nitropress": "2",
 "nitro-time": "2",
 "namenda": "1",
 "nitroprusside": "2",
 "nebivolol": "2",
 "namenda xr": "1",
 "nitrol": "2",
 "nitrocot": "2",
 "nitro-dur": "2",
 "normodyne": "2",
 "nitrek": "2",
 "nifediac cc": "2",
 "nitro-par": "2",
 "norvasc": "2",
 "nimodipine": "2",
 "navane": "2",
 "nitrogard": "2",
 "nitrostat tablets": "2",
 "nexiclon xr": "2",
 "nitro-bid iv": "2",
 "nitroquick": "2",
 "nitrol appli-kit": "2",
 "nitromist": "2",
 "nitrodisc": "2",
 "nimotop": "2",
 "nitro td patch-a": "2",
 "nifedical xl": "2",
 "naturetin-5": "2",
 "nadolol": "2",
 "nitroglyn e-r": "2",
 "nisoldipine": "2",
 "nitrong": "2",
 "nitro-bid": "2"}, "q": {"quetiapine": "2",
 "quinapril": "2",
 "quinaretic": "2"}, "p": {"proglycem": "2",
 "phenazine 50": "2",
 "prolixin": "2",
 "phenergan vc with codeine": "2",
 "phenergan fortis": "2",
 "permitil": "2",
 "procardia xl": "2",
 "prolixin enanthate": "2",
 "pediazole": "3",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "polythiazide": "2",
 "propranolol": "2",
 "paliperidone": "2",
 "propacet 100": "3",
 "pc-cap": "3",
 "prazosin": "2",
 "posicor": "2",
 "prinzide": "2",
 "propoxyphene": "3",
 "perphenazine": "2",
 "pp-cap": "3",
 "promethazine with dextromethorphan": "2",
 "pindolol": "2",
 "procardia": "2",
 "pce dispertab": "3",
 "phenergan vc": "2",
 "promethazine vc with codeine": "2",
 "promethazine vc": "2",
 "propiomazine": "2",
 "promethegan": "2",
 "phentolamine": "2",
 "pimozide": "2",
 "promethazine hcl with codeine": "2",
 "prolixin decanoate": "2",
 "perindopril": "2",
 "promethazine vc plain": "2",
 "phenoxybenzamine": "2",
 "promethazine with dm": "2",
 "promazine": "2",
 "promethazine vc w/codeine": "2",
 "propoxyphene compound 65": "3",
 "prinivil": "2",
 "phenadoz": "2",
 "pro-med": "2",
 "polythiazide/prazosin": "2",
 "procot": "2",
 "phenergan with dextromethorphan": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "prochlorperazine": "2",
 "prevpac": "3",
 "promethazine hcl and codeine phosphate": "2",
 "polythiazide/reserpine": "2",
 "phenoject-50": "2",
 "plendil": "2",
 "phenylephrine/promethazine": "2",
 "promethazine with codeine": "2"}, "s": {"saluron": "2",
 "sparine": "2",
 "salutensin-demi": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "saphris": "2",
 "serathide": "2",
 "symbyax": "2",
 "serpazide": "2",
 "salutensin": "2",
 "sodium edecrin": "2",
 "sulfimycin": "3",
 "ser-ap-es": "2",
 "sotalol": "2",
 "sorine": "2",
 "sorbitrate": "2",
 "stelazine": "2",
 "sodium oxybate": "3",
 "serentil": "2",
 "silodosin": "2",
 "sotalol hydrochloride af": "2",
 "sectral": "2",
 "spironolactone": "2",
 "serpex": "2",
 "sular": "2"}, "r": {"rapaflo": "2",
 "rauzide": "2",
 "risperidone": "2",
 "rectiv": "2",
 "risperdal m-tab": "2",
 "reglan": "2",
 "risperdal": "2",
 "ramipril": "2",
 "regitine": "2",
 "renese-r": "2",
 "regroton": "2",
 "risperdal consta": "2",
 "rondameth": "2",
 "renese": "2",
 "robimycin": "3"}, "u": {"uni serp": "2",
 "uprima": "2",
 "unipres": "2",
 "univasc": "2",
 "uniretic": "2"}, "t": {"tenoretic": "2",
 "thiothixene": "2",
 "timolol": "2",
 "tri-hydroserpine": "2",
 "tarka": "2",
 "telmisartan": "2",
 "tizanidine": "2",
 "troleandomycin": "3",
 "trandate": "2",
 "thioridazine": "2",
 "tao": "3",
 "trifluoperazine": "2",
 "torsemide": "2",
 "teveten": "2",
 "twynsta": "2",
 "trilafon": "2",
 "trandolapril": "2",
 "tenoretic 100": "2",
 "tenoretic 50": "2",
 "thalitone": "2",
 "triflupromazine": "2",
 "tekamlo": "2",
 "transderm-nitro": "2",
 "taztia xt": "2",
 "tridil": "2",
 "triavil": "2",
 "thiethylperazine": "2",
 "tiazac": "2",
 "tribenzor": "2",
 "tekturna hct": "2",
 "teveten hct": "2",
 "tenormin": "2",
 "torecan": "2",
 "trimeprazine": "2",
 "temaril": "2",
 "triamterene": "2",
 "timolide 10-25": "2",
 "timolide": "2",
 "tamsulosin": "2",
 "teczem": "2",
 "toprol-xl": "2",
 "tacaryl": "2",
 "trycet": "3",
 "trandolapril/verapamil": "2",
 "trimethaphan camsylate": "2",
 "thorazine": "2"}, "w": {"wygesic": "3"}, "v": {"v-gan-50": "2",
 "vasotec": "2",
 "verapamil": "2",
 "verelan pm": "2",
 "vascor": "2",
 "valsartan": "2",
 "vaseretic": "2",
 "valturna": "2",
 "verelan": "2",
 "v-gan-25": "2",
 "vaseretic 10-25": "2",
 "vaseretic 5-12.5": "2",
 "visken": "2"}, "x": {"xyrem": "3"}, "z": {"zestoretic": "2",
 "zyprexa relprevv": "2",
 "zmax": "2",
 "zanaflex": "2",
 "zyprexa intramuscular": "2",
 "zaroxolyn": "2",
 "zyprexa zydis": "2",
 "zestril": "2",
 "zithromax": "2",
 "zebeta": "2",
 "ziprasidone": "2",
 "zaponex": "2",
 "ziac": "2",
 "zyprexa": "2"}}];