interactions["calcitriol,calcijex"]=["calcitriol,calcijex", {"1": {"1000 bc": "3"}, "5": {"50 + companion": "3"}, "a": {"aminophylline/amobarbital/ephedrine": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aldroxicon i": "2",
 "atacand hct": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "2",
 "acnepril": "3",
 "alendronate/cholecalciferol": "3",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "antioxidant formula": "3",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "alli": "1",
 "allbee-c": "3",
 "amytal sodium": "2",
 "aspir-mox": "2",
 "aldoril": "2",
 "apatate": "3",
 "apatate forte": "3",
 "aspirin buffered": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "aldoril 15": "2",
 "apetimar with iron": "3",
 "allantex": "3",
 "almora": "2",
 "aminatal plus new formula": "3",
 "adeflor m": "3",
 "aldoril d50": "2",
 "anemagen fa": "3",
 "accuretic": "2",
 "acetaminophen/butalbital": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "allbee-c 800": "3",
 "abc to z": "3",
 "animal shape vitamins": "3",
 "abidec": "3",
 "acid gone antacid": "2",
 "acid gone": "2",
 "anemagen": "3",
 "aminate": "3",
 "azilsartan medoxomil/chlorthalidone": "2",
 "aminatal plus": "3",
 "arthriten": "2",
 "allbee-c 800 with iron": "3",
 "anoquan": "2",
 "aldroxicon ii": "2",
 "alagesic": "2",
 "aminatal plus one": "3",
 "alkabel-sr": "2",
 "arcet": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "amobarbital": "2",
 "aquatensen": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "antispas": "2",
 "abc plus senior": "3",
 "ascriptin maximum strength": "2",
 "aluminum hydroxide/mineral oil": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "aminate with 90 mg iron": "3",
 "alpha keri": "2",
 "aspirin/butalbital/caffeine": "2",
 "antispasmodic": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2",
 "aldoril 25": "2",
 "advance care plus": "3",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "aquadeks": "3",
 "amobarbital/secobarbital": "2",
 "alphabath": "2",
 "alenic alka tablet": "2",
 "acid gone extra strength": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "antrocol": "2",
 "apetigen-plus": "3",
 "ascriptin": "2",
 "aquadeks pediatric": "3",
 "apresazide": "2",
 "aquacot": "2",
 "advanced am/pm": "3",
 "axocet": "2",
 "almacone-2": "2",
 "aldoclor-250": "2",
 "anemagen forte": "3",
 "alka-seltzer plus immunity complex": "3",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "avail calcium intensive": "3",
 "aldoclor-150": "2",
 "allbee with c": "3",
 "avalide": "2",
 "almacone": "2",
 "atenolol/chlorthalidone": "2",
 "asthmacon": "2",
 "ami-natal plus one improved": "3",
 "atropine/phenobarbital": "2",
 "atabex ec": "3",
 "alamag": "2",
 "alamag plus": "2",
 "alagesic lq": "2",
 "amiloride/hydrochlorothiazide": "2",
 "arthritis pain formula": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "americet": "2",
 "antioxidant ultra formula": "3",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "ascomp with codeine": "2",
 "acid reducer + antacid dual action": "2",
 "adeks": "3",
 "aspirin/butalbital": "2",
 "anemagen ob": "3",
 "aquazide h": "2",
 "alz-nac": "3",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "2",
 "amturnide": "2",
 "aldoril d30": "2",
 "apetigen": "3",
 "alenic alka": "2",
 "aspir-mox ib": "2",
 "aldactazide": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "antioxid caplets": "3",
 "anolor 300": "2"}, "c": {"chlorothiazide/methyldopa": "2",
 "cascara sagrada/magnesium hydroxide": "2",
 "certa-vite senior plus lutein": "3",
 "calcifolic-d": "3",
 "choline salicylate/magnesium salicylate": "2",
 "cerebyx": "2",
 "centratex": "3",
 "cardoxin": "2",
 "cal-nate": "3",
 "century senior": "3",
 "citrate of magnesia": "2",
 "capozide 50/25": "2",
 "corvite free": "3",
 "cerovite senior": "3",
 "calcarb with d": "3",
 "centrum silver ultra women's": "3",
 "citracal regular": "3",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "centavite": "3",
 "concept dha": "3",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "3",
 "chlorthalidone/reserpine": "2",
 "citracal petites": "3",
 "childrens chewable multivitamins": "3",
 "calcium 600 d": "3",
 "choline magnesium trisalicylate": "2",
 "cmt": "2",
 "centrum 8400": "3",
 "cavan-heme ob": "3",
 "cholecalciferol": "3",
 "corzide 40/5": "2",
 "calcipotriene topical": "2",
 "calcitrene": "2",
 "cerovite advanced formula": "3",
 "co natal fa": "3",
 "corvita 150": "3",
 "century-vite": "3",
 "chlorothiazide/reserpine": "2",
 "cholinoid": "3",
 "cavan folate": "3",
 "carozide": "2",
 "chloromag": "2",
 "centrum performance": "3",
 "centrum kids": "3",
 "chlorthalidone/clonidine": "2",
 "citric acid/glucono-delta-lactone/magnesium carbonate topical": "2",
 "citranatal harmony": "3",
 "cholecalciferol/genistein/zinc chelazome": "3",
 "cerefolin": "3",
 "chromagen ob": "3",
 "carenatal dha": "3",
 "citracal + d": "3",
 "citracal prenatal rx": "3",
 "citranatal rx": "3",
 "caltrate plus": "3",
 "calcium carbonate/magnesium hydroxide": "2",
 "caltrate colon health": "3",
 "centrum silver men's": "3",
 "complete-rf": "3",
 "centrum special energy": "3",
 "citracal plus bone density builder": "3",
 "clorpres": "2",
 "certagen senior with lutein": "3",
 "citracal calcium gummies": "3",
 "citracal regular 250 mg + d": "3",
 "candesartan/hydrochlorothiazide": "2",
 "combgen": "3",
 "centrum silver women's": "3",
 "calafol rx": "3",
 "combi rx": "3",
 "certavite with antioxidants": "3",
 "combiflex es": "2",
 "calcifediol": "3",
 "circavite t": "3",
 "conceptionxr msf": "3",
 "centrum specialist vision": "3",
 "cerovite junior": "3",
 "caltrate 600+d": "3",
 "central": "3",
 "caromega": "3",
 "chromagen fa": "3",
 "cezin-s": "3",
 "chardonna-2": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "carlson d": "3",
 "citracal maximum": "3",
 "cod liver oil mint": "3",
 "caltrate 600 plus": "3",
 "calcium carbonate/magnesium carbonate": "2",
 "corzide": "2",
 "corvite": "3",
 "calcitriol topical": "2",
 "citrus calcium with vitamin d": "3",
 "calciferol": "3",
 "certagen senior": "3",
 "citracal prenatal 90+dha": "3",
 "central-vite": "3",
 "centrum cardio": "3",
 "cota-b-plex": "3",
 "calderol": "3",
 "colesevelam": "2",
 "centrum silver": "3",
 "centrum special heart": "3",
 "calcitrate with d": "3",
 "citracal plus magnesium": "3",
 "calcio del mar": "3",
 "caltrate 600 with d plus soy": "3",
 "completenate": "3",
 "chromagen": "3",
 "century": "3",
 "capozide 25/15": "2",
 "chromatinic": "3",
 "centrum silver ultra men's": "3",
 "certavite": "3",
 "calcet": "3",
 "caltro with vitamin d": "3",
 "conison": "3",
 "centrum jr with extra calcium": "3",
 "centrum ultra men's": "3",
 "carbamazepine": "2",
 "cavan ec dha plus": "3",
 "chlorthalidone": "2",
 "capozide 50/15": "2",
 "caltrate 600 with iron and vitamin d": "3",
 "cardiotek rx": "3",
 "caffeine/magnesium salicylate": "2",
 "cholidase": "3",
 "corvite fe": "3",
 "citranatal assure": "3",
 "chewable-vite": "3",
 "citranatal dha": "3",
 "cafgesic forte": "2",
 "complete natal dha": "3",
 "cephadyn": "2",
 "calcifol": "3",
 "chromagen forte": "3",
 "captopril/hydrochlorothiazide": "2",
 "cf vite": "3",
 "cernevit-12": "3",
 "chewable calcium with vitamin d": "3",
 "calcidol": "3",
 "clusimar": "3",
 "corvite 150": "3",
 "companion multi": "3",
 "calcium, magnesium and zinc": "3",
 "calcium acetate/magnesium carbonate": "2",
 "complete a-z": "3",
 "cerovite liquid": "3",
 "cod liver oil": "3",
 "calcium/vitamin d": "3",
 "certa-vite": "3",
 "cafatine pb": "2",
 "carbatrol": "2",
 "certavite with lutein": "3",
 "caltrate 600+d plus minerals": "3",
 "cavan-folate dha": "3",
 "cerefolin nac": "3",
 "compete": "3",
 "citranatal b-calm": "3",
 "calvite p": "3",
 "contrin": "3",
 "cardiotek": "3",
 "chelated magnesium": "2",
 "corzide 80/5": "2",
 "cholecalciferol/genistein/zinc glycinate": "3",
 "citracal plus heart health": "3",
 "chlorothiazide": "2",
 "cefol": "3",
 "capacet": "2",
 "citracal slow release 1200": "3",
 "corvita": "3",
 "centrum": "3",
 "citracal prenatal + dha": "3",
 "complete natal": "3",
 "citroma": "2",
 "cenogen ultra": "3",
 "capozide": "2",
 "capozide 25/25": "2",
 "conceptionxr rhf": "3",
 "concept ob": "3",
 "certagen": "3",
 "centrum ultra women's": "3",
 "cavan one": "3",
 "caltrate gummy bites": "3",
 "citranatal 90 dha": "3",
 "cernevit": "3",
 "calcet plus": "3"}, "b": {"bellaphen-s": "2",
 "b-plex plus": "3",
 "bucet": "2",
 "balanced b-150": "3",
 "baby vitamin drop": "3",
 "bee-comp with c": "3",
 "becomject-100": "3",
 "benazepril/hydrochlorothiazide": "2",
 "balanced b-100": "3",
 "beminal": "3",
 "bee-zee": "3",
 "balanced b-50": "3",
 "bellatal er": "2",
 "bee with c": "3",
 "b-plex": "3",
 "biotin forte": "3",
 "bugs bunny complete": "3",
 "bupap": "2",
 "b-50 complex": "3",
 "bounty bear vitamins": "3",
 "betamethasone/calcipotriene topical": "2",
 "belcomp-pb": "2",
 "bladder 2.2": "3",
 "butibel": "2",
 "butabarbital": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "bellamine s": "2",
 "bisacodyl/magnesium citrate": "2",
 "beminal-500": "3",
 "b-complex with b-12": "3",
 "benzthiazide": "2",
 "bp multinatal plus chewables": "3",
 "beminal with c fortis": "3",
 "belladonna/ergotamine/phenobarbital": "2",
 "butalbital compound": "2",
 "beelith": "3",
 "becomax rx": "3",
 "biotin forte with zinc": "3",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "berocca": "3",
 "b-plex plus minerals": "3",
 "bugs bunny multiple vitamins": "3",
 "bugs bunny with iron chewable": "3",
 "b-nexa": "3",
 "benicar hct": "2",
 "bellamor": "2",
 "bellaspas": "2",
 "butisol sodium": "2",
 "butex forte": "2",
 "busodium": "2",
 "bel-phen-ergot": "2",
 "biferarx": "3",
 "betamed": "3",
 "berplex plus": "3",
 "b complex 50": "3",
 "barbidonna": "2",
 "bellergal-s": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "bacmin": "3",
 "b-scorbic": "3",
 "bellalphen": "2",
 "b-complex sr": "3",
 "bendroflumethiazide/nadolol": "2",
 "b complex 100": "3",
 "bayer select backache pain formula": "2",
 "butalbital": "2",
 "belladonna/butabarbital": "2",
 "bel-tabs": "2",
 "bellatal": "2",
 "berocca plus": "3",
 "bellamine": "2",
 "bendroflumethiazide": "2",
 "b-stress": "3",
 "b 100 complex": "3",
 "bright beginnings": "3",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "b-ject 100": "3",
 "bugs bunny with extra c": "3"}, "e": {"equi-natal plus": "3",
 "essentia": "3",
 "ellis tonic sherry": "3",
 "edge ob": "3",
 "enduronyl": "2",
 "elppa daily": "3",
 "evac-q-kwik": "2",
 "elixiral": "2",
 "endolor": "2",
 "ergocalciferol": "3",
 "essential balance": "3",
 "enfamil d-vi-sol": "3",
 "edarbyclor": "2",
 "esgic-plus": "2",
 "epsom salt": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "enfolast": "3",
 "equaline one daily essential": "3",
 "elite ob with dha": "3",
 "elite ob 400": "3",
 "essentiale": "3",
 "eldercaps": "3",
 "eperbel-s": "2",
 "ex-lax milk of magnesia": "2",
 "equi-natal z": "3",
 "enduron": "2",
 "enfolast-n": "3",
 "ergocomp-pb": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "estroven": "3",
 "ergocaffpb": "2",
 "ezol": "2",
 "ecee plus": "3",
 "equi-natal rx": "3",
 "elon matrix 5000 complete": "3",
 "eye health formula": "3",
 "equi-natal m": "3",
 "equicyte plus": "3",
 "exforge hct": "2",
 "esimil": "2",
 "equi-natal care": "3",
 "exna": "2",
 "esidrix": "2",
 "e-caff p-b": "2",
 "equetro": "2",
 "ezide": "2",
 "elemental iron-90": "3",
 "epitol": "2",
 "ergocaf-pb": "2",
 "eldertonic": "3",
 "equi-roca plus": "3",
 "equinatal 90": "3",
 "esgic": "2",
 "enduronyl forte": "2",
 "embrex 600": "3",
 "encora": "3"}, "d": {"dialyvite 3000": "3",
 "delta d3": "3",
 "demi-regroton": "2",
 "daily vite": "3",
 "duet dha ec": "3",
 "daily-vite with iron": "3",
 "di-gel": "2",
 "diuril": "2",
 "diovan hct": "2",
 "dayalets": "3",
 "daily-vite men's formula": "3",
 "dutoprol": "2",
 "doan's pills": "2",
 "donnatal extentabs": "2",
 "dewees carminative": "2",
 "dolgic plus": "2",
 "diupres-500": "2",
 "di-gel mint": "2",
 "dical captabs": "3",
 "doans pm": "2",
 "daily combo": "3",
 "diatx zn": "3",
 "dolgic": "2",
 "dolmar": "2",
 "duragal-s": "2",
 "diatx fe": "3",
 "duet chewable": "3",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "d3-5": "3",
 "dialyvite 800 with zinc": "3",
 "digitoxin": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "disney winnie the pooh complete": "3",
 "donnapine": "2",
 "digitek": "2",
 "dialyvite 800": "3",
 "dialyvite 800 ultra d": "3",
 "dermavite": "3",
 "dolomite": "3",
 "dyazide": "2",
 "dayalets plus iron": "3",
 "disney winnie the pooh with extra c": "3",
 "dualvit ob": "3",
 "doxercalciferol": "3",
 "duet dha complete": "3",
 "deserpidine/methyclothiazide": "2",
 "diurese": "2",
 "donnatal": "2",
 "doans pills extra strength": "2",
 "dual action complete": "2",
 "dical-d": "3",
 "dialyvite rx": "3",
 "d3-50": "3",
 "daily multiple vitamins": "3",
 "dialyvite 5000": "3",
 "daily multi-vitamins with minerals": "3",
 "diurex": "2",
 "dihydrotachysterol": "3",
 "dovonex": "2",
 "diuretic ap-es": "2",
 "daily multiple for men 50+": "3",
 "diucardin": "2",
 "dulcolax bowel cleansing": "2",
 "dulcolax milk of magnesia": "2",
 "d400": "3",
 "dialyvite with zinc rx": "3",
 "d-tal": "2",
 "duet dha": "3",
 "dewitt's pain reliever": "2",
 "dht intensol": "3",
 "duet": "3",
 "dialyvite": "3",
 "diaqua": "2",
 "disney winnie the pooh gummies": "3",
 "drisdol": "3",
 "diuril sodium": "2",
 "di-gel lemon": "2",
 "daily-vite weight control": "3",
 "daily multiple for women 50+": "3",
 "deserpidine/hydrochlorothiazide": "2",
 "daily multiple for women": "3",
 "d2000": "3",
 "diutensen-r": "2",
 "dilantin": "2",
 "diavite plus": "3",
 "digoxin": "2",
 "dovobet": "2",
 "dht": "3",
 "durabac forte": "2",
 "d 1000 iu": "3",
 "diatx": "3",
 "diupres-250": "2",
 "dolgic lq": "2",
 "daflon": "3",
 "donnaphen": "2",
 "d-400 international units": "3",
 "decagen": "3",
 "dicalphos plus d": "3",
 "dexfol": "3",
 "duet dha with ferrazone": "3",
 "docosavit": "3"}, "g": {"gevrabon": "3",
 "garfield vitamins": "3",
 "geravine": "3",
 "gentle iron": "3",
 "gold age liquid vitamins and minerals": "3",
 "gevratonic": "3",
 "gaviscon regular strength tablets": "2",
 "gaviscon regular strength liquid": "2",
 "gaviscon extra strength liquid": "2",
 "gelusil": "2",
 "glutofac": "3",
 "geri-tonic": "3",
 "generix-t": "3",
 "geone": "2",
 "g-1": "2",
 "gynovite": "3",
 "gaviscon extra relief formula": "2",
 "glutofac-mx": "3",
 "glutofac-zx": "3",
 "gesticare dha": "3",
 "genaton": "2",
 "geravim": "3",
 "gesticare dha dr": "3",
 "garfield vitamin with iron": "3",
 "geritol extend": "3",
 "gnc women's hair, skin &amp; nails formula": "3",
 "guanethidine/hydrochlorothiazide": "2",
 "garfield complete vitamins": "3",
 "geritol complete": "3",
 "gaviscon-2": "2",
 "geri-tabs": "3",
 "geritol": "3",
 "gesticare": "3",
 "good sense children's vitamins with iron": "3",
 "gerivite liquid": "3",
 "gaviscon extra strength tablets": "2",
 "generet-500 with folic acid": "3",
 "genaton chewable": "2"}, "f": {"femiron multi with iron": "3",
 "folgard os": "3",
 "ferrex 150 forte": "3",
 "ferrocite plus": "3",
 "fiorinal": "2",
 "folbalin": "3",
 "formula b plus": "3",
 "femcet": "2",
 "ferrovite fa": "3",
 "foltrin": "3",
 "fetrin": "3",
 "flintstones with c multivitamins": "3",
 "foltabs plus dha": "3",
 "fruity chews with iron": "3",
 "folbic": "3",
 "fe-tinic 150 forte": "3",
 "femecal ob": "3",
 "foltabs prenatal plus dha": "3",
 "ferocon": "3",
 "fioricet": "2",
 "folbecal": "3",
 "ferrex 28": "3",
 "ferbee": "3",
 "felbatol": "2",
 "foltabs 800": "3",
 "folast": "3",
 "ferrex pc forte": "3",
 "first mouthwash blm": "2",
 "folmor": "3",
 "fiorinal with codeine iii": "2",
 "ferotrinsic": "3",
 "folivan-prx dha": "3",
 "femecal ob plus dha": "3",
 "folcaps omega 3": "3",
 "folivan-ec dha": "3",
 "foltx": "3",
 "folnate plus": "3",
 "fast acting mylanta": "2",
 "foleve": "3",
 "fosfree": "3",
 "fortabs": "2",
 "ferralet 90": "3",
 "femnatal": "3",
 "foltabs": "3",
 "foli-iron": "3",
 "fosteum": "3",
 "femtabs": "3",
 "folivan-ob": "3",
 "fruity chew": "3",
 "flumezide": "2",
 "ferrovite forte": "3",
 "fiortal": "2",
 "farbee with c": "3",
 "fem-natal": "3",
 "foltabs 90 plus dha": "3",
 "fleet mineral oil enema": "2",
 "folbalin plus": "3",
 "fosphenytoin": "2",
 "formula b": "3",
 "folic acid xtra": "3",
 "fioricet with codeine": "2",
 "ferragen": "3",
 "folcaps": "3",
 "folivan-plus": "3",
 "folcaps care one": "3",
 "folbee": "3",
 "folitab 500": "3",
 "folpace rx": "3",
 "ferrogels forte": "3",
 "folgard rx 2.2": "3",
 "felbamate": "2",
 "floricet with codeine": "2",
 "flintstones gummies": "3",
 "farbital": "2",
 "fiorpap": "2",
 "ferotrin": "3",
 "flintstones with iron chewable": "3",
 "fe c tab plus": "3",
 "folplex": "3",
 "folbee plus cz": "3",
 "foltabs prenatal": "3",
 "fluorabon basic": "3",
 "folivan-f": "3",
 "fiorinal with codeine": "2",
 "feogen": "3",
 "fero-folic 500": "3",
 "folbee plus": "3",
 "folplex 2.2": "3",
 "folgard": "3",
 "foleve plus": "3",
 "fabb": "3",
 "flintstones multivitamins": "3",
 "fiortal with codeine": "2",
 "formula twenty-one": "3",
 "ferrex 150 forte plus": "3",
 "flintstones complete": "3",
 "ferroflex-150 forte": "3",
 "folcal dha": "3",
 "foltrate": "3",
 "folamin": "3",
 "feocyte": "3",
 "ferrovite": "3",
 "fosamax plus d": "3",
 "folgard rx": "3",
 "folnate": "3",
 "fiormor": "2",
 "fumatinic": "3",
 "fletanol": "3",
 "ferraplus": "3",
 "flintstones with calcium": "3",
 "fosinopril/hydrochlorothiazide": "2"}, "i": {"isoniazid/rifampin": "2",
 "i-l-x": "3",
 "inderide": "2",
 "icaps lutein &amp; omega-3": "3",
 "iromin g": "3",
 "icar c": "3",
 "isocet": "2",
 "icaps tr": "3",
 "iberet liquid": "3",
 "i-vite": "3",
 "isoniazid": "2",
 "i-sense": "3",
 "icaps plus": "3",
 "irofol": "3",
 "isoniazid/pyrazinamide/rifampin": "2",
 "inatal advance": "3",
 "intrinsitinic": "3",
 "inderide la": "2",
 "icare prenatal rx": "3",
 "idenal": "2",
 "indapamide": "2",
 "integra f": "3",
 "icar-c plus": "3",
 "iberet-500": "3",
 "iferex 150 forte": "3",
 "ivites rx": "3",
 "infuvite pediatric": "3",
 "inatal ultra": "3",
 "irospan 24/6": "3",
 "iberet-folic-500": "3",
 "iro-plex": "3",
 "icaps areds": "3",
 "icar prenatal": "3",
 "isonarif": "2",
 "infuvite": "3",
 "iberet": "3",
 "icaps": "3",
 "icaps with lutein and zeaxan": "3",
 "ide-cet": "2",
 "ibc 500": "3",
 "integra plus": "3",
 "iron-150": "3",
 "i-vite protect": "3",
 "i-l-x and b12": "3",
 "infanate dha": "3",
 "icaps mv": "3",
 "icar-c plus sr": "3",
 "i-fol plus": "3",
 "integra": "3",
 "i-sense occushield": "3"}, "h": {"hhr": "2",
 "hydro-reserp": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hemocyte plus": "3",
 "hydroserpine 1": "2",
 "hyzaar": "2",
 "high potency b complex with b12 and c": "3",
 "hydrochlorothiazide/methyldopa": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrochlorothiazide/timolol": "2",
 "heartburn antacid extra strength": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydropres-50": "2",
 "hi-nate 90": "3",
 "hydrap-es": "2",
 "hydroserpine": "2",
 "hydroflumethiazide/reserpine": "2",
 "hydrochlorothiazide/losartan": "2",
 "hytakerol": "3",
 "hydroflumethiazide": "2",
 "hydrodiuril": "2",
 "hygroton": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hyosophen": "2",
 "hematogen fa": "3",
 "hydrochlorothiazide/olmesartan": "2",
 "hematogen forte": "3",
 "hydrochlorothiazide/propranolol": "2",
 "high potency b+c": "3",
 "hydrochlorothiazide/moexipril": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "hexavitamin": "3",
 "high b complex": "3",
 "hydrochlorothiazide/lisinopril": "2",
 "hematinic plus": "3",
 "health aid multivitamin": "3",
 "haley's m-o": "2",
 "hydra-zide": "2",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrochlorothiazide/reserpine": "2",
 "hair booster": "3",
 "hydrochlorothiazide/quinapril": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydropres-25": "2",
 "hematogen": "3",
 "hydrochlorothiazide": "2",
 "hemocyte-f elixir": "3",
 "high potency": "3",
 "hydro par": "2",
 "hydralazine plus": "2",
 "hectorol": "3",
 "hemax": "3",
 "hyoscyamine/phenobarbital": "2",
 "hydroserp": "2"}, "k": {"kneerelief": "2",
 "kondremul": "2",
 "kondremul plain": "2",
 "kenwood therapeutic": "3",
 "kondremul with phenolphtalein": "2",
 "kolnatal dha": "3"}, "j": {"jetepar": "3"}, "m": {"mynatal ultracap": "3",
 "maxivision eye formula": "3",
 "martinic": "3",
 "maxivision whole body formula": "3",
 "maternity": "3",
 "multivitamin, prenatal": "3",
 "metahydrin": "2",
 "mvi-12": "3",
 "mynatal rx": "3",
 "micardis hct": "2",
 "magdelay": "2",
 "maalox advanced maximum strength": "2",
 "magnesium oxide": "2",
 "magsal": "2",
 "milantex maximum strength": "2",
 "magnebind 400 rx": "3",
 "mi-acid ii": "2",
 "maxinate": "3",
 "methyclothiazide/reserpine": "2",
 "mykidz iron": "3",
 "migracet-pb": "2",
 "mynate 90 plus": "3",
 "multi-betic": "3",
 "minizide": "2",
 "mynatal": "3",
 "magnesium carbonate": "2",
 "mephobarbital": "2",
 "muri-lube": "2",
 "mynatal z": "3",
 "moduretic": "2",
 "multi-nate dha": "3",
 "mylanta maximum strength": "2",
 "mag-g": "2",
 "multilex": "3",
 "mylanta fast acting": "2",
 "maalox max wild berry": "2",
 "multivitamin with iron": "3",
 "myferon 150 forte": "3",
 "mvc-fluoride": "3",
 "mynatal pn forte": "3",
 "mylagen-ii": "2",
 "maggel": "2",
 "magan": "2",
 "myogesic": "2",
 "mykrox": "2",
 "mag-sr": "2",
 "mission prenatal hp": "3",
 "mynatal plus": "3",
 "maxaron forte": "3",
 "mag-200": "2",
 "mylagen": "2",
 "multi vita bets and fluoride": "3",
 "myadec": "3",
 "maalox": "2",
 "milantex": "2",
 "magnesium hydroxide/mineral oil": "2",
 "magonate natal": "2",
 "multi-nate 30 kit": "3",
 "mission prenatal": "3",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "2",
 "mysoline": "2",
 "multifol": "3",
 "multi-delyn with iron": "3",
 "mi-acid double strength": "2",
 "mag-phen": "2",
 "mag-tab sr": "2",
 "magaant": "2",
 "maternity vitamin low iron": "3",
 "mediplex ultra": "3",
 "maternity-90": "3",
 "magnesiocard": "2",
 "magonate tablets": "3",
 "mintox extra strength": "2",
 "mg plus protein": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "masanti ds": "2",
 "multifol plus": "3",
 "mycobutin": "2",
 "mag-carb": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "multi vita bets and fluoride and iron": "3",
 "mylanta ultra": "2",
 "maginex ds": "2",
 "maalox advanced regular strength": "2",
 "multigen": "3",
 "marnatal-f": "3",
 "magnebind 200": "2",
 "mission prenatal rx": "3",
 "maldroxal plus": "2",
 "magnesium gluconate": "2",
 "magnesium sulfate": "2",
 "male formula": "3",
 "maxivision eye &amp; body formula": "3",
 "milk of magnesia": "2",
 "multi-nate 30": "3",
 "mega b": "3",
 "minotal": "2",
 "magnesium salicylate": "2",
 "menopause relief with lifenol": "3",
 "micomp-pb": "2",
 "metanx": "3",
 "mag-sr with calcium": "3",
 "maximum d3": "3",
 "multigen folic": "3",
 "milkinol": "2",
 "margesic": "2",
 "mintox plus": "2",
 "mobigesic": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "myvitalife": "3",
 "multi-delyn": "3",
 "mynatal fc": "3",
 "magnesium aspartate": "2",
 "magnesium amino acids chelate": "2",
 "maternal 90": "3",
 "mintox maximum strength": "2",
 "multiret folic 500": "3",
 "maginex": "2",
 "mst": "2",
 "multivitamin with iron and fluoride": "3",
 "maalox plus": "2",
 "mag-ox": "2",
 "multi-nate 30 dha": "3",
 "multinatal plus": "3",
 "mag-caps": "2",
 "medigesic": "2",
 "multigen plus": "3",
 "multi-nate dha extra": "3",
 "mebaral": "2",
 "mygracet": "2",
 "mylanta ultimate strength": "2",
 "marblen": "2",
 "metolazone": "2",
 "maxivision ocular formula": "3",
 "m-vit": "3",
 "mylanta ds fast acting": "2",
 "moduretic 5-50": "2",
 "masanti": "2",
 "maxzide-25": "2",
 "magnebind 300": "2",
 "magnesium citrate": "2",
 "mult-ferr folic": "3",
 "microzide": "2",
 "methyclothiazide": "2",
 "mvi pediatric": "3",
 "masanti supreme": "2",
 "magnaprin": "2",
 "mag-ox 400": "2",
 "maalox tc": "2",
 "mi-acid": "2",
 "multilex-t/m+minerals": "3",
 "mylanta": "2",
 "multibret folic 500": "3",
 "megavite rx": "3",
 "multi vits with beta carotene": "3",
 "mudrane gg": "2",
 "magtrate": "2",
 "mykidz iron fl": "3",
 "mtx support": "3",
 "multi-day plus minerals": "3",
 "magna-c-7 forte": "3",
 "marnatal-f plus": "3",
 "maxzide": "2",
 "mobidin": "2",
 "mynatal pn": "3",
 "marten-tab": "2",
 "mag-oxide": "2",
 "monopril hct": "2",
 "mylanta supreme": "2",
 "multivitamin with fluoride": "3",
 "maalox max": "2",
 "multivitamin with minerals": "3",
 "magnesium chloride": "2",
 "mvi adult": "3",
 "my-a-multi": "3",
 "mission prenatal fa": "3",
 "maalox antacid antigas regular strength": "2",
 "mintox": "2",
 "magonate": "2",
 "maternity plus beta carotene": "3",
 "mens pack": "3",
 "mvc sdv": "3",
 "mudrane": "2",
 "metatensin 4": "2",
 "metatensin 2": "2",
 "materna": "3",
 "mintox tablets": "2",
 "magnesium lactate": "2",
 "mineral oil": "2",
 "mineral oil/phenolphthalein": "2",
 "mag 64": "2",
 "mylanta gelcap": "2",
 "magmin": "2",
 "multivitamin": "3",
 "multi-day with calcium and extra iron": "3",
 "maalox hrf": "2",
 "mi-c-t": "3",
 "marpres": "2"}, "l": {"lipogen": "3",
 "luminal": "2",
 "loqua": "2",
 "lanolin/mineral oil topical": "2",
 "lysiplex": "3",
 "l-methylfolate ca, me-cbl nac": "3",
 "liponol": "3",
 "levsin with phenobarbital": "2",
 "lydia pinkham": "3",
 "lysiplex plus": "3",
 "livitrinsic-f": "3",
 "lozol": "2",
 "lipoflavonoid": "3",
 "lanoxin": "2",
 "lufyllin-epg": "2",
 "lotensin hct": "2",
 "l-tonic": "3",
 "loso prep bowel cleansing system": "2",
 "lactocal-f": "3",
 "l-methylfolate ca, p-5-p, me-cbl": "3",
 "lanoxicaps": "2",
 "lopressor hct": "2",
 "liquiprep": "2",
 "laniroif": "2",
 "leg-gesic": "3",
 "liqui doss": "2",
 "lipotriad": "3"}, "o": {"obegyn": "3",
 "ob complete with dha": "3",
 "one-a-day within": "3",
 "opti-gen": "3",
 "oystercal-d": "3",
 "o-cal-d": "3",
 "oreticyl 50": "2",
 "optinate": "3",
 "ob complete premier": "3",
 "oreticyl forte": "2",
 "oyster shell calcium with vitamin d": "3",
 "oysco d with calcium": "3",
 "ob natal one": "3",
 "obtrex dha": "3",
 "one-a-day men's health formula": "3",
 "oyster-d": "3",
 "ocuvite preservision": "3",
 "one daily with minerals": "3",
 "ocuvite": "3",
 "one tab daily with minerals": "3",
 "one-a-day vitacraves": "3",
 "os-cal 500 + d": "3",
 "optimum magnesium gluconate": "2",
 "one-a-day max": "3",
 "one-a-day weightsmart": "3",
 "one-a-day women 50 plus": "3",
 "occuplex": "3",
 "ocuvite extra": "3",
 "one tab daily with iron": "3",
 "ob-20": "3",
 "orlistat": "1",
 "os-cal 500 + extra d": "3",
 "one-a-day women": "3",
 "omega q plus": "3",
 "oysco d": "3",
 "optivite pmt": "3",
 "oyster shell calcium": "3",
 "ob complete": "3",
 "ostiva": "3",
 "one-a-day men 50 plus": "3",
 "o-cal prenatal": "3",
 "oysco 500 with d": "3",
 "oncovite": "3",
 "os-cal ultra": "3",
 "one-a-day 50+": "3",
 "orbivan": "2",
 "oreticyl 25": "2",
 "ob complete 400": "3",
 "obnate 90": "3",
 "oyst-cal-d": "3",
 "optilets-m-500": "3",
 "osteocit d plus": "3",
 "oxcarbazepine": "2",
 "oretic": "2",
 "one-a-day men pro edge": "3",
 "obtrex": "3",
 "ocuvite lutein": "3",
 "optilets-500": "3",
 "one tab daily": "3",
 "one-a-day essentials": "3",
 "o-cal fa": "3"}, "n": {"nutrispire": "3",
 "natalcare advanced": "3",
 "nephrocaps": "3",
 "nufol": "3",
 "neurobion": "3",
 "natalcare pic forte": "3",
 "natelle prefer": "3",
 "nu-iron v": "3",
 "natalcare": "3",
 "niferex-pn": "3",
 "nicotinamide zcf": "3",
 "nephron-fa": "3",
 "nutrinate": "3",
 "natelle-ez": "3",
 "nata 29 ob": "3",
 "natacaps": "3",
 "novastart": "3",
 "nanovm": "3",
 "natelle one": "3",
 "novaferrum": "3",
 "nata 29 prenatal": "3",
 "novasal": "2",
 "nestabs rx": "3",
 "natalcare glosstabs": "3",
 "nu-iron plus": "3",
 "nuprin backache caplet": "2",
 "nephronex": "3",
 "nydrazid": "2",
 "nestabs fa": "3",
 "natelle c": "3",
 "nephro-vite rx": "3",
 "natelle": "3",
 "nat-rul b-125": "3",
 "natafolic-ob": "3",
 "nestabs": "3",
 "nephplex rx": "3",
 "natalcare rx": "3",
 "natelle one dha": "3",
 "new advanced formula prenatal z": "3",
 "nonbac": "2",
 "neurodep": "3",
 "niferex-150 forte": "3",
 "natatab fa": "3",
 "nutiifac zx": "3",
 "naturetin": "2",
 "natarex": "3",
 "naqua": "2",
 "neevo": "3",
 "nephrocaps qt": "3",
 "natatab rx": "3",
 "niferex gold": "3",
 "neevo dha": "3",
 "nembutal sodium": "2",
 "nembutal": "2",
 "novanatal": "3",
 "natatab cfe": "3",
 "nephro-vite with fe": "3",
 "naturetin-5": "2",
 "niferex pn forte": "3",
 "natalcare advanced-rf": "3",
 "neurpath-b": "3",
 "nic 750": "3",
 "naturetin-10": "2",
 "natalcare plus": "3",
 "natalins rx": "3",
 "neuroforte-six": "3",
 "neo-forte": "3",
 "natachew": "3",
 "nephrolan rx": "3",
 "natelle plus with dha": "3",
 "natafolic-pn": "3",
 "nature's blend theratrum complete tablets 50 plus": "3",
 "natalfirst": "3",
 "nicomide": "3",
 "nexa select with dha": "3",
 "nestabs cbf": "3",
 "nephrox": "2",
 "norlac rx": "3",
 "nutravance": "3",
 "natalcare pic": "3",
 "natalcare cfe 60": "3",
 "natalcare three": "3",
 "natafort": "3",
 "natalins": "3",
 "nicazel": "3",
 "nephro-vite": "3"}, "q": {"quadrinal": "2",
 "quadrapax": "2",
 "quinaretic": "2"}, "p": {"pyridium plus": "2",
 "poly iron forte": "3",
 "pr natal 440": "3",
 "phillips' cramp-free": "2",
 "prosteon": "3",
 "paire ob plus dha": "3",
 "phrenilin forte": "2",
 "prevital": "3",
 "prenatal low iron": "3",
 "pamprin cramp menstrual pain relief": "2",
 "pramilet fa": "3",
 "pan ob forte": "3",
 "prenatal mtr with selenium": "3",
 "primacare": "3",
 "pyrelle hb": "2",
 "promacet": "2",
 "poly vit drops": "3",
 "pharmagesic": "2",
 "pr natal 400 ec": "3",
 "prenatabs cbf": "3",
 "primidone": "2",
 "poly vitamin with fluoride with iron": "3",
 "prenafirst": "3",
 "poly-vi-sol with iron drops": "3",
 "prenatal-u": "3",
 "preterna": "3",
 "prenavite": "3",
 "pnv-total": "3",
 "polythiazide/prazosin": "2",
 "prenatabs fa": "3",
 "prenavite fc": "3",
 "phillips' haleys m-o": "2",
 "phluorivit": "3",
 "prenatal multivitamins": "3",
 "pepcid complete": "2",
 "pnv-dha plus": "3",
 "promar": "3",
 "poly-vi-sol with iron": "3",
 "primacare advantage": "3",
 "pentobarbital": "2",
 "prenate dha": "3",
 "poly-vi-flor": "3",
 "prenate 90": "3",
 "pms balance": "3",
 "previte rx": "3",
 "phenytek": "2",
 "pb-hyos": "2",
 "prominol": "2",
 "prenatabs obn": "3",
 "prenatal mr 90": "3",
 "prostate 2.4": "3",
 "prenatal rx": "3",
 "prenatal 1 plus 1": "3",
 "posture-d h/p": "3",
 "prenate essential": "3",
 "poly-vi-flor with iron": "3",
 "premesis rx": "3",
 "par-f": "3",
 "prefera ob plus dha": "3",
 "pnv select": "3",
 "prenate gt": "3",
 "prenate elite plus iron": "3",
 "precare conceive": "3",
 "prenate ultra": "3",
 "phenytoin sodium, prompt": "2",
 "pruet dha": "3",
 "phenaz plus": "2",
 "prenatal rx 1": "3",
 "precare": "3",
 "protegra softgel": "3",
 "protegra cardio": "3",
 "poly-vi-sol drops": "3",
 "poly iron 150 forte": "3",
 "polythiazide/reserpine": "2",
 "prenexa": "3",
 "prosight": "3",
 "prefera ob-one": "3",
 "prenatal z advanced formula": "3",
 "prenate elite": "3",
 "pr natal 400": "3",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "prenate advance": "3",
 "prenatal s": "3",
 "prinzide": "2",
 "pruvate 21/7": "3",
 "priftin": "2",
 "procycle multi vitamin with minerals": "3",
 "phenazoforte plus": "2",
 "prenatal h": "3",
 "primaplex": "3",
 "preque 10": "3",
 "phenytoin": "2",
 "poly-vit chew": "3",
 "prenatal ad": "3",
 "prenatabs rx": "3",
 "paricalcitol": "3",
 "phrenilin": "2",
 "prenatal plus with 27 mg iron": "3",
 "prenatal plus": "3",
 "prenacare": "3",
 "prenatal mr 90 fe": "3",
 "prenatal elite": "3",
 "pre-h-cal": "3",
 "prenexa with dha": "3",
 "poly vitamin with fluoride": "3",
 "phenobarbital": "2",
 "poly-vi-sol": "3",
 "precare premier": "3",
 "polythiazide": "2",
 "prenatal plus with beta-carotene": "3",
 "pedia-lax chewable tablets": "2",
 "phluorivit with iron": "3",
 "prenate advanced formula": "3",
 "prenavite pc": "3",
 "preferaob": "3",
 "prenazyme 1+1": "3",
 "prenate plus": "3",
 "prenaplus": "3",
 "pronemia": "3",
 "pr natal 430": "3",
 "prenate essential dha": "3",
 "pnv-dha": "3",
 "poly-vi-sol chewable": "3",
 "preservision": "3",
 "protegra": "3",
 "prenatal plus iron": "3",
 "probarimin qt": "3",
 "proferrin-forte": "3",
 "primacare one": "3",
 "prenatal 19": "3",
 "phillips' milk of magnesia": "2"}, "s": {"sesame st. vitamins plus iron": "3",
 "saluron": "2",
 "surbex-750 with zinc": "3",
 "suplevit": "3",
 "se-care conceive": "3",
 "super b-50": "3",
 "senetonic": "3",
 "senilezol": "3",
 "sunkist child chewable": "3",
 "sourcecf chewables": "3",
 "super b-100 td": "3",
 "surbex filmtab": "3",
 "stuartnatal plus": "3",
 "serathide": "2",
 "super high vitamins and minerals": "3",
 "soluvite f": "3",
 "stress b with c": "3",
 "sss": "3",
 "scotts emulsion": "3",
 "sourcecf abdek": "3",
 "stress formula 600": "3",
 "stresstabs": "3",
 "stuartnatal plus 3": "3",
 "strovite advance": "3",
 "slow-mag": "2",
 "salutensin-demi": "2",
 "serpex": "2",
 "stress formula": "3",
 "surbex with c": "3",
 "stress formula with zinc": "3",
 "salutensin": "2",
 "suprep": "2",
 "seconal sodium": "2",
 "sorilux": "2",
 "se-natal 16": "3",
 "sesame st vitamins with extra c": "3",
 "stresstabs with zinc": "3",
 "ser-ap-es": "2",
 "se-care": "3",
 "superplex-t": "3",
 "sourcecf multivitamins with a,b,d,e &amp; k plus zinc": "3",
 "se-natal 19": "3",
 "select-ob+dha": "3",
 "seton et-ec": "3",
 "solfoton": "2",
 "secobarbital": "2",
 "surbex": "3",
 "support 500": "3",
 "se-tan dha": "3",
 "strovite": "3",
 "spectravite senior": "3",
 "sourcecf pediatric drops": "3",
 "strovite plus": "3",
 "stuart prenatal with beta carotene": "3",
 "seton et": "3",
 "support": "3",
 "spastrin": "2",
 "se-natal 90": "3",
 "sourcecf softgels": "3",
 "surbex-t": "3",
 "sss tonic": "3",
 "sigtab": "3",
 "suprep bowel prep kit": "2",
 "sunkist child chewable with c": "3",
 "strongstart": "3",
 "select-ob": "3",
 "super b complex": "3",
 "se-plete dha": "3",
 "stress-600": "3",
 "stress 600 with zinc": "3",
 "strovite advance+d": "3",
 "super theravite-m": "3",
 "spectravite cardio health": "3",
 "sedecal d": "3",
 "siderol": "3",
 "super plenamins": "3",
 "seconal": "2",
 "stresstabs with iron": "3",
 "spasmolin": "2",
 "sulfamag": "2",
 "serpazide": "2",
 "spasquid": "2",
 "se-natal one": "3",
 "se-vate": "3",
 "stress formula with iron": "3",
 "sesame st vitamins complete": "3",
 "sunkist child chewable with iron": "3",
 "servira": "2",
 "strovite one": "3",
 "sedapap": "2",
 "strovite forte": "3",
 "surbex-750 with iron": "3",
 "seconal sodium pulvules": "2"}, "r": {"reserpine/trichlormethiazide": "2",
 "rolaids regular strength": "2",
 "re fac-x": "3",
 "renate": "3",
 "repliva 21/7": "3",
 "royvac bowel evacuant": "2",
 "rena-vite": "3",
 "renatabs": "3",
 "renaphro": "3",
 "rimactane": "2",
 "rx support heartburn and acid reflux": "3",
 "rifabutin": "2",
 "ru-lets m 500": "3",
 "rauzide": "2",
 "re ob 90 plus dha": "3",
 "rulox": "2",
 "rifater": "2",
 "renacidin irrgiation": "2",
 "resource optisource": "3",
 "renese-r": "2",
 "regroton": "2",
 "re dualvit plus": "3",
 "renacidin": "2",
 "risanoid plus": "3",
 "renaplex": "3",
 "rifapentine": "2",
 "renatabs with iron": "3",
 "renal caps": "3",
 "renate dha extra": "3",
 "recal d": "3",
 "rondameth": "2",
 "rulox 1": "2",
 "rifamate": "2",
 "reno caps": "3",
 "rifampin": "2",
 "re dualvit f": "3",
 "rolaids multi-symptom": "2",
 "rightstep": "3",
 "renate dha": "3",
 "req49+": "3",
 "rovin-cf": "3",
 "risacal-d": "3",
 "rovin-nv dha": "3",
 "reocyte plus": "3",
 "renax 5.5": "3",
 "rulox plus": "2",
 "repan": "2",
 "rovin-nv": "3",
 "rifadin iv": "2",
 "rolaids extra strength": "2",
 "rexavite 150 forte": "3",
 "renax": "3",
 "rena-vite rx": "3",
 "recal fol d": "3",
 "rifadin": "2",
 "renese": "2",
 "re-pb hyos elixir": "2",
 "re ob plus dha": "3"}, "u": {"unicap capsule": "3",
 "unicap with iron": "3",
 "udamin": "3",
 "unicap jr": "3",
 "upcal d": "3",
 "unicap senior": "3",
 "urban ds": "2",
 "uni-lan ii": "2",
 "uro-mag": "2",
 "ultra-natal": "3",
 "unicomplex m": "3",
 "uni-fac zx": "3",
 "urban": "2",
 "uni-lan": "2",
 "ultimatecare one": "3",
 "udamin sp": "3",
 "uni serp": "2",
 "urelief plus": "2",
 "uni-daily plus iron": "3",
 "ultimatecare combo": "3",
 "uni kar plus c sr": "3",
 "unipres": "2",
 "unicap": "3",
 "unichem multivitamin": "3",
 "uni multi with fluoride": "3",
 "ultimatecare one nf": "3",
 "unicap t": "3",
 "uni-thera m with beta carotene": "3",
 "ultra natalcare": "3",
 "unicap m": "3",
 "ultimatecare advance": "3",
 "uniretic": "2"}, "t": {"tencet": "2",
 "triphluorivit": "3",
 "theracal d4000": "3",
 "tozal": "3",
 "tri-vitamin with fluoride": "3",
 "triveen-one": "3",
 "triadvance": "3",
 "tetra-mag": "2",
 "teveten hct": "2",
 "tri-vi-flor": "3",
 "thera-m enhanced": "3",
 "thera-m": "3",
 "trileptal": "2",
 "trilisate": "2",
 "tri-vitamin": "3",
 "tegretol": "2",
 "theralith xr": "3",
 "theravim m": "3",
 "therobec plus": "3",
 "theragran hematinic": "3",
 "trimagen": "3",
 "topfit vitamin b complex forte": "3",
 "t-lite": "3",
 "tenoretic": "2",
 "taron-prx plus dha": "3",
 "thera-plus": "3",
 "trinsicon": "3",
 "t-bmp": "3",
 "trinatal rx": "3",
 "tri-hydroserpine": "2",
 "tums dual action": "2",
 "trichlormethiazide": "2",
 "taclonex scalp": "2",
 "tab-a-vite maximum": "3",
 "tenoretic 50": "2",
 "thalitone": "2",
 "tricare dha one": "3",
 "theragran": "3",
 "tandem ob": "3",
 "trigels f": "3",
 "tempo": "2",
 "theodrine": "2",
 "tricare": "3",
 "tridate": "2",
 "trihemic 600": "3",
 "timolide": "2",
 "tri vita-bets with fluoride": "3",
 "thera-tabs": "3",
 "thera derm": "2",
 "t-gran plus minerals": "3",
 "tri vites with fluoride and iron": "3",
 "triad": "2",
 "tricon": "3",
 "tri-vi-sol with iron": "3",
 "tenake": "2",
 "theragenerix": "3",
 "taclonex": "2",
 "tl icon": "3",
 "theracal rapid repletion": "3",
 "thex forte": "3",
 "tl g-fol os": "3",
 "triveen-cf": "3",
 "tri-vit drops": "3",
 "tl-fol 500": "3",
 "tri-vit with fluoride": "3",
 "ternamar": "3",
 "taron-ec calc dha pack": "3",
 "theracal d2000": "3",
 "tenoretic 100": "2",
 "thera": "3",
 "t-vites": "3",
 "thera-vite m": "3",
 "tolfrinic": "3",
 "therobec": "3",
 "tekturna hct": "2",
 "tuinal": "2",
 "tab-a-vite": "3",
 "tedrigen": "2",
 "tandem dha": "3",
 "tencon": "2",
 "tricosal": "2",
 "tab-a-vite weightslim": "3",
 "taron forte": "3",
 "timolide 10-25": "2",
 "therems m": "3",
 "therems h": "3",
 "taron-c dha": "3",
 "therems": "3",
 "triaprin": "2",
 "tri rx": "3",
 "trimagen fa": "3",
 "taron-bc": "3",
 "theragran-m": "3",
 "topfit vitamin b complex": "3",
 "theravite": "3",
 "tri-vi-flor with iron": "3",
 "theragener-m": "3",
 "tandem plus": "3",
 "thera hematinic": "3",
 "theragener-h": "3",
 "tab-a-vite womens formula": "3",
 "tab-a-vite with iron": "3",
 "trimagen forte": "3",
 "triferex 150 forte": "3",
 "tribenzor": "2",
 "tender age vitamin adc": "3",
 "triphro": "3",
 "tl gard": "3",
 "trinate": "3",
 "tri-vi-sol": "3",
 "triveen-prx rnf": "3",
 "trimesis rx": "3",
 "tri-vit": "3",
 "tegretol xr": "2",
 "therapeutic-m": "3",
 "two-dyne": "2"}, "w": {"wellesse vitamin d3": "3",
 "welchol": "2",
 "womens pack": "3",
 "wellesse liquid calcium with vitamin d": "3",
 "watkins harvest": "3",
 "wellesse sugar free childrens multivitamin gummies": "3"}, "v": {"vi-daylin adc with iron": "3",
 "vitalize plus": "3",
 "vitamin daily liquid": "3",
 "vitamin b compound strong": "3",
 "vi-daylin": "3",
 "vinate advanced": "3",
 "verotin-by": "3",
 "viactiv multi-vitamin": "3",
 "vi-zac": "3",
 "vigortol liquid": "3",
 "venatal fa": "3",
 "vitamin a, d": "3",
 "viactiv calcium flavor glides": "3",
 "vita-plus g": "3",
 "vica-forte": "3",
 "vinate care": "3",
 "vitaplex": "3",
 "vitamin c, e, and rose hips": "3",
 "vita drop": "3",
 "vi-daylin/f adc": "3",
 "vi-daylin/f": "3",
 "vi-daylin chewable": "3",
 "vinate good start": "3",
 "vol-care rx": "3",
 "vitanatal ob plus dha": "3",
 "vitamin b complex 100": "3",
 "vaseretic": "2",
 "vinate az extra": "3",
 "vitaplex plus": "3",
 "vinate ic": "3",
 "vimar": "3",
 "vinate ii": "3",
 "vita-pms": "3",
 "vi-daylin adc": "3",
 "vitaspire": "3",
 "vinate ultra": "3",
 "vinate 90": "3",
 "vi-stress": "3",
 "vitafol-ob+dha": "3",
 "vitamins": "3",
 "vitelle nestabs otc": "3",
 "vita-respa": "3",
 "vi-daylin/f adc with iron": "3",
 "vol-nate": "3",
 "vicon forte": "3",
 "vi-stress with iron": "3",
 "vectical": "2",
 "vitamax": "3",
 "vesselvite": "3",
 "vaseretic 10-25": "2",
 "vinatal forte": "3",
 "vinate iii": "3",
 "vi-daylin drops": "3",
 "vital-d": "3",
 "vaseretic 5-12.5": "2",
 "vitaphil plus dha": "3",
 "vitamed prenatal formula": "3",
 "vemavite prx 2": "3",
 "vitagen forte": "3",
 "vol-plus": "3",
 "vitaphil aide": "3",
 "vitafol pn": "3",
 "vita-zinc": "3",
 "vita drops with iron": "3",
 "vita zx": "3",
 "vinacal or": "3",
 "viactiv soft calcium chews": "3",
 "vitamin d2": "3",
 "vernate": "3",
 "vi-daylin with iron chewable": "3",
 "vita-dec": "3",
 "vicon plus": "3",
 "vita-pms plus": "3",
 "vinate pn care": "3",
 "vitatrum": "3",
 "vol-tab rx": "3",
 "vernate advanced": "3",
 "vimar with iron": "3",
 "vicap forte": "3",
 "vitagen advance": "3",
 "vinate one": "3",
 "vitafol-ob": "3",
 "viva dha": "3",
 "vicon-c": "3",
 "vitamin b-100": "3",
 "vita-min rx": "3",
 "vitatab mv": "3",
 "vynatal 1 plus 1": "3",
 "vi-daylin with iron": "3",
 "vinate az": "3",
 "v-c forte": "3",
 "vitamin b-50": "3",
 "vi-daylin/f plus iron": "3",
 "vita s forte": "3",
 "vinate c": "3",
 "vitacon forte": "3",
 "vinate m": "3",
 "vitafol": "3",
 "vinate calcium": "3",
 "vi-daylin with iron drops": "3",
 "vitabee with c": "3",
 "vynatal fa": "3",
 "vitamin a and d concentrate": "3",
 "viactiv multi-vitamin flavor glides": "3",
 "vitamin b-100 t/r": "3",
 "vinate gt": "3",
 "viogen-c": "3",
 "vigomar forte": "3",
 "vitaphil": "3",
 "verotin-gr": "3",
 "vinatal 600": "3",
 "vitamin d3": "3",
 "vitamins for hair": "3"}, "x": {"xenical": "1"}, "z": {"zestoretic": "2",
 "zinc plus lozenges": "3",
 "zycose": "3",
 "ziac": "2",
 "zemplar": "3",
 "z-gen": "3",
 "zitamin": "3",
 "zatean-ch": "3",
 "zymacap": "3",
 "z-bec": "3",
 "zaroxolyn": "2",
 "zenate advanced formula": "3",
 "zatean-pn dha": "3",
 "zenate prenatal": "3",
 "zebutal": "2",
 "zenate": "3",
 "zatean-pn": "3",
 "zatean-pn plus": "3",
 "ze-plus": "3",
 "zodeac-100": "3",
 "zincvit": "3"}}];