interactions["carbidopa-levodopa,sinemet"]=["carbidopa-levodopa,sinemet", {"5": {"5-hydroxytryptophan": "2",
 "50 + companion": "2",
 "5-htp": "2"}, "4": {"40 winks": "2"}, "a": {"anaspaz": "2",
 "atropine/difenoxin": "2",
 "aluminum hydroxide": "1",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "ascorbic acid/iron polysaccharide": "2",
 "aldoril 25": "2",
 "atacand hct": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "1",
 "allerx pe": "2",
 "accuhist la": "2",
 "amdry-d": "2",
 "akineton": "2",
 "amdry-c": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/scopolamine": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "1",
 "aler-dryl": "2",
 "aldactone": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "advil pm": "2",
 "altocor": "2",
 "alu-tab": "1",
 "aspir-mox": "1",
 "amitriptyline": "1",
 "alternagel": "1",
 "amylase/cellulase/hyoscyamine/lipase/phenyltoloxamine/protease": "2",
 "alcalak": "1",
 "ah-chew ultra tannate": "2",
 "aldoril": "2",
 "apatate forte": "2",
 "ah-chew": "2",
 "amlodipine/telmisartan": "2",
 "alka-seltzer gold": "1",
 "aldoril 15": "2",
 "arranon": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "atropine": "2",
 "amphojel": "1",
 "amlobenz": "2",
 "aminatal plus new formula": "2",
 "aspirin buffered": "1",
 "azilsartan medoxomil/chlorthalidone": "2",
 "aldoril d50": "2",
 "amlodipine/atorvastatin": "2",
 "aurolate": "2",
 "anturol": "2",
 "allerx dose pack": "2",
 "azilect": "2",
 "apetimar with iron": "2",
 "aspirin/pravastatin": "2",
 "alahist lq": "2",
 "alkets": "1",
 "atropine/diphenoxylate": "2",
 "alka-seltzer heartburn relief": "1",
 "atacand": "2",
 "aventyl hydrochloride": "1",
 "accuretic": "2",
 "ami-lac": "1",
 "allergy dn ii": "2",
 "a-spaz": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "alka-seltzer plus immunity complex": "2",
 "asenapine": "2",
 "aldomet": "1",
 "aerokid": "2",
 "abc to z": "2",
 "acebutolol": "2",
 "atrohist plus": "2",
 "antinaus 50": "2",
 "abraxane": "2",
 "acetaminophen/diphenhydramine/pseudoephedrine": "2",
 "ah-chew ii": "2",
 "arava": "2",
 "alcohol": "2",
 "aliskiren/valsartan": "2",
 "advicor": "2",
 "allergy dn pe": "2",
 "anergan 50": "2",
 "acid gone antacid": "1",
 "acid gone": "1",
 "anemagen": "2",
 "aminate": "2",
 "altoprev": "2",
 "aminatal plus": "2",
 "accupril": "2",
 "apresoline": "2",
 "aliskiren/amlodipine": "2",
 "allermax": "2",
 "allbee-c 800 with iron": "2",
 "actemra": "2",
 "aspirin/caffeine/propoxyphene": "3",
 "afeditab cr": "2",
 "avapro": "2",
 "aldroxicon ii": "1",
 "aquatensen": "2",
 "aminatal plus one": "2",
 "adalimumab": "2",
 "alkabel-sr": "2",
 "acetaminophen/dextromethorphan/diphenhydramine/phenylephrine": "2",
 "aldex-ct": "2",
 "aspir-mox ib": "1",
 "alka-seltzer original": "1",
 "apo-go pen": "2",
 "alka-mints": "1",
 "amitone": "1",
 "abc plus senior": "2",
 "ascriptin maximum strength": "1",
 "aluminum hydroxide/mineral oil": "1",
 "amiloride": "2",
 "aralen": "2",
 "aceon": "2",
 "aerohist plus": "2",
 "asendin": "2",
 "aminate with 90 mg iron": "2",
 "antioxidant formula": "2",
 "alka-seltzer lemon-lime": "1",
 "apomorphine": "2",
 "amlodipine/benazepril": "2",
 "acetaminophen/pamabrom/pyridoxine": "2",
 "alprazolam": "2",
 "antispasmodic": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "1",
 "atropine/chlorpheniramine/hyoscyamine/pseudoephedrine/scopolamine": "2",
 "accolate": "2",
 "a-spas s/l": "2",
 "atenolol": "2",
 "advance care plus": "2",
 "acetaminophen/dextromethorphan/diphenhydramine": "2",
 "alfuzosin": "2",
 "alprazolam intensol": "2",
 "abilify": "2",
 "advanced formula di-gel": "1",
 "acid controller complete dual action": "1",
 "aquadeks": "2",
 "ala-hist": "2",
 "alenic alka tablet": "1",
 "aspirin/diphenhydramine": "2",
 "actonel with calcium": "1",
 "atapryl": "2",
 "adalat": "2",
 "antabuse": "2",
 "acid gone extra strength": "1",
 "anacin p.m. aspirin free": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "1",
 "alka-seltzer pm": "2",
 "aluminum carbonate": "1",
 "acetazolamide": "2",
 "adapin": "1",
 "altace": "2",
 "adcetris": "2",
 "antrocol": "2",
 "acetaminophen/diphenhydramine/phenylephrine": "2",
 "alkums": "1",
 "adalat cc": "2",
 "allergia-c": "2",
 "ascriptin": "1",
 "acid relief": "1",
 "aquadeks pediatric": "2",
 "aminoxin": "2",
 "allerx pe dose pack": "2",
 "anafranil": "1",
 "advanced am/pm": "2",
 "alcohol and dextrose injections usp hypertonic": "2",
 "atropine/chlorpheniramine/hyoscyamine/phenylephrine/phenylpropanolamine/scopolamine": "2",
 "amlodipine": "2",
 "arfonad": "2",
 "almacone-2": "1",
 "aldoclor-250": "2",
 "apo-go": "2",
 "anemagen forte": "2",
 "aspirin/citric acid/sodium bicarbonate": "1",
 "azor": "2",
 "allergy dn": "2",
 "acetaminophen pm extra strength": "2",
 "apetigen-plus": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "1",
 "acetaminophen/dextromethorphan/diphenhydramine/pseudoephedrine": "2",
 "avail calcium intensive": "2",
 "amiodarone": "2",
 "aldoclor-150": "2",
 "atrosept": "2",
 "aripiprazole": "2",
 "allerx df dose pack": "2",
 "alu-cap": "1",
 "aralen phosphate": "2",
 "altaryl": "2",
 "aerohist": "2",
 "airacof": "2",
 "avalide": "2",
 "almacone": "1",
 "atenolol/chlorthalidone": "2",
 "amoxapine": "2",
 "ami-natal plus one improved": "2",
 "actifed allergy day/night": "2",
 "ala-hist d": "2",
 "acetaminophen/propoxyphene": "3",
 "atabex ec": "2",
 "alamag": "1",
 "alamag plus": "1",
 "atorvastatin": "2",
 "allepak": "2",
 "aurothioglucose": "2",
 "ah-chew ultra": "2",
 "aralen hydrochloride": "2",
 "antispas": "2",
 "ascorbic acid/ferrous sulfate": "2",
 "aldoril d30": "2",
 "amiloride/hydrochlorothiazide": "2",
 "aspirin/diphenhydramine/phenylpropanolamine": "2",
 "atropine/phenobarbital": "2",
 "aspirin/calcium carbonate": "1",
 "arthritis pain formula": "1",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "1",
 "apresazide": "2",
 "atropine/edrophonium": "2",
 "aquacot": "2",
 "anemagen fa": "2",
 "amlodipine/olmesartan": "2",
 "azilsartan medoxomil": "2",
 "ascorbic acid/ferrous fumarate": "2",
 "antioxidant ultra formula": "2",
 "aluminum hydroxide/magnesium hydroxide": "1",
 "apokyn": "2",
 "atnaa": "2",
 "acid reducer + antacid dual action": "1",
 "adeks": "2",
 "aldroxicon i": "1",
 "aquazide h": "2",
 "ativan": "2",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "1",
 "amturnide": "2",
 "alka-seltzer extra strength": "1",
 "akineton hcl": "2",
 "auranofin": "2",
 "alenic alka": "1",
 "allergy am-pm dose pack": "2",
 "allerx df": "2",
 "aloh-gel": "1",
 "alcohol 5% in dextrose 5%": "2",
 "acetaminophen/diphenhydramine": "2",
 "amlodipine/valsartan": "2",
 "allerx-d": "2",
 "atropen": "2",
 "aldactazide": "2",
 "atropine/pralidoxime": "2",
 "anemagen ob": "2",
 "aplenzin": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "artane": "2",
 "aler-tab": "2",
 "antioxid caplets": "2",
 "abilify discmelt": "2",
 "atreza": "2"}, "c": {"completenate": "2",
 "calcitab": "1",
 "colcrys": "2",
 "catapres": "2",
 "chlorothiazide/methyldopa": "2",
 "calcium carbonate/risedronate": "1",
 "certa-vite senior plus lutein": "2",
 "calcifolic-d": "2",
 "cardene sr": "2",
 "colchicine/probenecid": "2",
 "cerebyx": "2",
 "centratex": "2",
 "citric acid/simethicone/sodium bicarbonate": "1",
 "cal-nate": "2",
 "century senior": "2",
 "chem-sol": "2",
 "capozide 50/25": "2",
 "cavan ec dha plus": "2",
 "calcium carbonate/fluoride": "1",
 "cisplatin": "2",
 "corvite free": "2",
 "coryza-d": "2",
 "cerovite senior": "2",
 "carbetapentane/diphenhydramine/phenylephrine": "2",
 "calcarb with d": "1",
 "cogentin": "2",
 "centrum silver ultra women's": "2",
 "citracal regular": "1",
 "colidrops": "2",
 "citracal prenatal 90+dha": "2",
 "cpm-pe-msc": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "1",
 "clozapine synthon": "2",
 "centavite": "2",
 "concept dha": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "cardizem cd": "2",
 "cartia xt": "2",
 "chlorthalidone/reserpine": "2",
 "chlorpheniramine/methscopolamine/pseudoephedrine": "2",
 "centrum kids": "2",
 "counteract pm extra strength": "2",
 "cuvposa": "2",
 "complete natal": "2",
 "capoten": "2",
 "cyanocobalamin/folic acid/pyridoxine/strontium gluconate": "2",
 "corzide 40/5": "2",
 "cystospaz-m": "2",
 "cardizem sr": "2",
 "calcium oyster shell": "1",
 "covera-hs": "2",
 "corvita": "2",
 "clidinium": "2",
 "calcid": "1",
 "chlorpheniramine/methscopolamine/phenylpropanolamine": "2",
 "co natal fa": "2",
 "chlordinium": "2",
 "corvite 150": "2",
 "century-vite": "2",
 "corgard": "2",
 "chlorothiazide/reserpine": "2",
 "calan sr": "2",
 "carbex": "2",
 "cardene": "2",
 "clozapine": "2",
 "carbetapentane/diphenhydramine": "2",
 "cavan folate": "2",
 "cerivastatin": "2",
 "carozide": "2",
 "cardizem": "2",
 "coldamine": "2",
 "caduet": "2",
 "citric acid/glucono-delta-lactone/magnesium carbonate topical": "1",
 "clonidine er": "2",
 "citranatal harmony": "2",
 "century": "2",
 "chloromycetin sodium succinate": "2",
 "centrum silver": "2",
 "chloroquine": "2",
 "children's tylenol plus cold and allergy": "2",
 "chromagen ob": "2",
 "corzide": "2",
 "citracal + d": "1",
 "citracal prenatal rx": "2",
 "cardizem la": "2",
 "citranatal rx": "2",
 "caltrate plus": "2",
 "calan": "2",
 "calcium carbonate/magnesium hydroxide": "1",
 "complete allergy": "2",
 "combi rx": "2",
 "centrum performance": "2",
 "citrocarbonate": "1",
 "caltrate colon health": "1",
 "centrum silver men's": "2",
 "complete-rf": "2",
 "centrum special energy": "2",
 "cleviprex": "2",
 "clonazepam": "2",
 "carbidopa/entacapone/levodopa": "1",
 "catapres-tts": "2",
 "clorpres": "2",
 "certagen senior with lutein": "2",
 "corvita 150": "2",
 "clevidipine": "2",
 "carbonyl iron": "2",
 "citracal calcium gummies": "1",
 "ceo-two": "1",
 "chlordiazepoxide/clidinium": "2",
 "citracal regular 250 mg + d": "1",
 "calcium carbonate/simethicone": "1",
 "candesartan/hydrochlorothiazide": "2",
 "centrum silver women's": "2",
 "calafol rx": "2",
 "clopine": "2",
 "carboplatin": "2",
 "candesartan": "2",
 "circavite t": "2",
 "certavite with antioxidants": "2",
 "centrum specialist vision": "2",
 "clozaril": "2",
 "cerovite junior": "2",
 "carduran": "2",
 "cozaar": "2",
 "caltrate 600+d": "1",
 "central": "2",
 "conceptionxr msf": "2",
 "caromega": "2",
 "citranatal dha": "2",
 "chloromycetin": "2",
 "cezin-s": "2",
 "cardura": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "1",
 "chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "chlordiazepoxide": "2",
 "citracal maximum": "1",
 "caltrate 600 plus": "2",
 "calcium carbonate/magnesium carbonate": "1",
 "chlordiazepoxide/methscopolamine": "2",
 "carbinoxamine/methscopolamine/pseudoephedrine": "2",
 "clonidine": "2",
 "chlorthalidone/clonidine": "2",
 "citrus calcium with vitamin d": "1",
 "calm-aid": "2",
 "compro": "2",
 "certagen senior": "2",
 "chlor-mes": "2",
 "central-vite": "2",
 "centrum cardio": "2",
 "compazine spansule": "2",
 "chlor-mes d": "2",
 "contrin": "2",
 "cordarone": "2",
 "centrum": "2",
 "centrum special heart": "2",
 "calcitrate with d": "1",
 "cordarone iv": "2",
 "citracal plus magnesium": "2",
 "calcio del mar": "1",
 "caltrate 600 with d plus soy": "1",
 "colchicine": "2",
 "chlorpromazine": "2",
 "cardizem monovial": "2",
 "chromagen": "2",
 "cantil": "2",
 "carenatal dha": "2",
 "chromatinic": "2",
 "cavan-heme ob": "2",
 "centrum silver ultra men's": "2",
 "cal-gest": "1",
 "coreg cr": "2",
 "calcium carbonate": "1",
 "certavite": "2",
 "calcet": "1",
 "caltro with vitamin d": "1",
 "contac day and night allergy": "2",
 "conison": "2",
 "carteolol": "2",
 "chlorpheniramine/methscopolamine": "2",
 "centrum jr with extra calcium": "2",
 "cf vite": "2",
 "coreg": "2",
 "cal oys": "1",
 "carboplatin novaplus": "2",
 "comtan": "1",
 "clorazepate": "2",
 "carvedilol": "2",
 "cafatine pb": "2",
 "cvs allergy &amp; cold": "2",
 "chlorthalidone": "2",
 "capozide 50/15": "2",
 "chewable calcium with vitamin d": "1",
 "cvs allergy &amp; sinus headache": "2",
 "children's triacting night time": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "cartrol": "2",
 "citranatal assure": "2",
 "chlorpheniramine/dextromethorphan/guaifenesin/methscopolamine/phenylephrine": "2",
 "ceraxon": "1",
 "chlorpheniramine/methscopolamine/phenylephrine": "2",
 "corvite fe": "2",
 "citicoline": "1",
 "cardura xl": "2",
 "calci mix": "1",
 "compoz nighttime sleep aid": "2",
 "compazine": "2",
 "chloracol": "2",
 "coricidin night time cold relief": "2",
 "codeine/phenylephrine/promethazine": "2",
 "clomipramine": "1",
 "chromagen fa": "2",
 "complete natal dha": "2",
 "codeine/promethazine": "2",
 "calcifol": "2",
 "chromagen forte": "2",
 "captopril/hydrochlorothiazide": "2",
 "cascara sagrada/magnesium hydroxide": "1",
 "chloramphenicol": "2",
 "crestor": "2",
 "citracal petites": "1",
 "calcium oyster": "1",
 "cystemms-v": "2",
 "clusimar": "2",
 "calcarb": "1",
 "codeine phosphate-promethazine hcl": "2",
 "captopril": "2",
 "companion multi": "2",
 "calcium, magnesium and zinc": "2",
 "cascor": "2",
 "calcium acetate/magnesium carbonate": "1",
 "complete a-z": "2",
 "cerovite liquid": "2",
 "contac day and night cold and flu": "2",
 "calcium/vitamin d": "1",
 "cellulase/hyoscyamine/pancrelipase/phenyltoloxamine": "2",
 "certa-vite": "2",
 "calcium concentrate": "1",
 "certavite with lutein": "2",
 "caltrate 600+d plus minerals": "2",
 "cavan-folate dha": "2",
 "compete": "2",
 "citranatal b-calm": "2",
 "calvite p": "1",
 "clobazam": "2",
 "cabazitaxel": "2",
 "citranatal 90 dha": "2",
 "citracal plus bone density builder": "1",
 "corzide 80/5": "2",
 "chlorpheniramine/dextromethorphan/methscopolamine": "2",
 "citracal plus heart health": "1",
 "centrum ultra men's": "2",
 "chlorothiazide": "2",
 "chardonna-2": "2",
 "chlorpheniramine/guaifenesin/methscopolamine/phenylephrine": "2",
 "cystospaz": "2",
 "citracal slow release 1200": "1",
 "certolizumab": "2",
 "calcium 600 d": "1",
 "citracal prenatal + dha": "2",
 "cardene iv": "2",
 "clindex": "2",
 "capozide 25/15": "2",
 "cenogen ultra": "2",
 "capozide": "2",
 "capozide 25/25": "2",
 "calcium liquid softgel": "1",
 "concept ob": "2",
 "conceptionxr rhf": "2",
 "certagen": "2",
 "centrum ultra women's": "2",
 "cavan one": "2",
 "corvite": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "caltrate gummy bites": "1",
 "crizotinib": "2",
 "caltrate": "1",
 "caltro": "1",
 "cerovite advanced formula": "2",
 "calci-chew": "1",
 "cimzia": "2",
 "chooz": "1",
 "calcet plus": "2"}, "b": {"bellaphen-s": "2",
 "betaxolol": "2",
 "benadryl-d allergy plus sinus": "2",
 "brevibloc": "2",
 "bugs bunny complete": "2",
 "benahist-50": "2",
 "brompheniramine/chlorpheniramine/methscopolamine/phenylephrine/pseudoephedrine": "2",
 "benaphen plus": "2",
 "byclomine": "2",
 "benzthiazide": "2",
 "baros": "1",
 "bayer pm": "2",
 "benadryl": "2",
 "benicar hct": "2",
 "bemote": "2",
 "bel-phen-ergot": "2",
 "bystolic": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "bifera": "2",
 "benadryl-d children's allergy &amp; sinus": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "bacmin": "2",
 "belladonna tincture": "2",
 "bumetanide": "2",
 "belladonna/butabarbital": "2",
 "benadryl allergy plus cold": "2",
 "bumex": "2",
 "biotin forte with zinc": "2",
 "bortezomib": "2",
 "benadryl children's allergy and sinus": "2",
 "benadryl allergy sinus": "2",
 "brompheniramine/diphenhydramine/phenylephrine": "2",
 "bonisara": "2",
 "budeprion sr": "2",
 "beelith": "2",
 "becomax rx": "2",
 "bidil": "2",
 "benadryl allergy": "2",
 "bentyl": "2",
 "balacet": "3",
 "b-nexa": "2",
 "bellaspas": "2",
 "benadryl allergy plus sinus headache": "2",
 "bladder 2.2": "2",
 "bp multinatal plus chewables": "2",
 "bellamine": "2",
 "basaljel": "1",
 "bel-tabs": "2",
 "belix": "2",
 "beldin": "2",
 "bendroflumethiazide": "2",
 "benicar": "2",
 "bendroflumethiazide/nadolol": "2",
 "bupropion": "2",
 "berocca plus": "2",
 "benahist-10": "2",
 "buproban": "2",
 "banophen": "2",
 "benylin multi-symptom": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "budeprion": "2",
 "benztropine": "2",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "benadryl severe allergy &amp; sinus headache": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "butibel": "2",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "brentuximab": "2",
 "bisacodyl/polyethylene glycol 3350/potassium chloride/sodium bicarbonate/sodium chloride": "1",
 "bydramine": "2",
 "brompheniramine/diphenhydramine": "2",
 "b-plex plus minerals": "2",
 "b &amp; o supprettes": "2",
 "biperiden": "2",
 "budeprion xl": "2",
 "betamed": "2",
 "bellergal-s": "2",
 "banaril": "2",
 "bellalphen": "2",
 "bellamine s": "2",
 "bell/ans": "1",
 "bellatal er": "2",
 "benadryl severe allergy plus sinus headache": "2",
 "blocadren": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "bayer women's low dose plus calcium": "1",
 "benazepril/hydrochlorothiazide": "2",
 "bee-zee": "2",
 "ben-tann": "2",
 "bisoprolol": "2",
 "benoject-50": "2",
 "belladonna": "2",
 "baclofen": "2",
 "belcomp-pb": "2",
 "benazepril": "2",
 "bellamor": "2",
 "bellahist-d la": "2",
 "benadryl children's allergy": "2",
 "belladonna/opium": "2",
 "biferarx": "2",
 "berplex plus": "2",
 "bugs bunny with iron chewable": "2",
 "barbidonna": "2",
 "baycol": "2",
 "bright beginnings": "2",
 "bellatal": "2",
 "benadryl cold": "2"}, "e": {"essentia": "2",
 "eplerenone": "2",
 "endep": "1",
 "ecee plus": "2",
 "emsam": "2",
 "equilet": "1",
 "esidrix": "2",
 "enalapril/hydrochlorothiazide": "2",
 "eprosartan": "2",
 "ex-tuss": "2",
 "ex-lax milk of magnesia": "1",
 "excedrin pm": "2",
 "etoposide": "2",
 "equi-cyte f": "2",
 "ed cyte f": "2",
 "exforge hct": "2",
 "extendryl pse": "2",
 "elavil": "1",
 "endal hd": "2",
 "extendryl dm": "2",
 "extendryl": "2",
 "ezfe": "2",
 "enalapril": "2",
 "ergocomp-pb": "2",
 "equi-roca plus": "2",
 "edarbi": "2",
 "equicyte plus": "2",
 "ezetimibe/simvastatin": "2",
 "e-z-gas ii": "1",
 "etopophos": "2",
 "equi-natal plus": "2",
 "ellis tonic sherry": "2",
 "edge ob": "2",
 "ed-spaz": "2",
 "elixiral": "2",
 "edecrin": "2",
 "edarbyclor": "2",
 "elite ob with dha": "2",
 "eloxatin": "2",
 "eldercaps": "2",
 "enalapril/felodipine": "2",
 "enduron": "2",
 "esmolol": "2",
 "etanercept": "2",
 "eprosartan/hydrochlorothiazide": "2",
 "ethacrynic acid": "2",
 "endal cd": "2",
 "ethanol": "2",
 "esimil": "2",
 "etrafon forte": "2",
 "equi-natal care": "2",
 "exna": "2",
 "enbrel": "2",
 "e-caff p-b": "2",
 "ethionamide": "2",
 "ergocaf-pb": "2",
 "extendryl seniors": "2",
 "equinatal 90": "2",
 "embrex 600": "2",
 "effervescent pain relief": "1",
 "enlon-plus": "2",
 "ethyl alcohol": "2",
 "enduronyl": "2",
 "extendryl pem": "2",
 "eribulin": "2",
 "extendryl sr": "2",
 "extendryl jr": "2",
 "eldepryl": "2",
 "extra strength mylanta calci tabs": "1",
 "elite ob 400": "2",
 "entacapone": "1",
 "equi-natal rx": "2",
 "estazolam": "2",
 "ezide": "2",
 "enablex": "2",
 "eldertonic": "2",
 "exforge": "2",
 "encora": "2",
 "elppa daily": "2",
 "etrafon": "2",
 "ex-histine": "2",
 "ethambutol": "2",
 "eperbel-s": "2",
 "etravirine": "2",
 "equate allergy &amp; sinus headache": "2",
 "equi-natal z": "2",
 "elemental iron-90": "2",
 "eye health formula": "2",
 "equi-natal m": "2",
 "elemental iron": "2",
 "ergocaffpb": "2",
 "enduronyl forte": "2",
 "elon matrix 5000 complete": "2",
 "extendryl chews": "2"}, "d": {"diovan": "2",
 "dialyvite 3000": "2",
 "diltzac": "2",
 "diastat": "2",
 "drize": "2",
 "demi-regroton": "2",
 "dualvit ob": "2",
 "duet dha ec": "2",
 "daily-vite with iron": "2",
 "duradryl chewable": "2",
 "di-gel": "1",
 "demadex": "2",
 "disney winnie the pooh complete": "2",
 "detrol": "2",
 "diuril": "2",
 "diphenydramine quick melt": "2",
 "deconhist la": "2",
 "durahist pe": "2",
 "deserpidine": "2",
 "diltiazem hydrochloride cd": "2",
 "diovan hct": "2",
 "dicopanol": "2",
 "disney winnie the pooh with extra c": "2",
 "duo-vil": "2",
 "dehydrated alcohol": "2",
 "dizac": "2",
 "di-delamine": "2",
 "diphenhydramine/guaifenesin": "2",
 "donnatal extentabs": "2",
 "diphenhydramine/tripelennamine topical": "2",
 "dialume": "1",
 "diamox sequels": "2",
 "diupres-500": "2",
 "duodote": "2",
 "ditropan": "2",
 "di-gel mint": "1",
 "dical captabs": "1",
 "da ii": "2",
 "di-spaz": "2",
 "dilomine": "2",
 "duraclon": "2",
 "doans pm": "2",
 "daily combo": "2",
 "diphenadryl": "2",
 "drihist": "2",
 "ditropan xl": "2",
 "dicarbosil": "1",
 "diamox": "2",
 "duravent": "2",
 "dynacirc": "2",
 "diabetic tussin night time formula": "2",
 "dph": "2",
 "dytan-at": "2",
 "darvon compound 32": "3",
 "docosavit": "2",
 "duragal-s": "2",
 "dehistine": "2",
 "diatx fe": "2",
 "duet chewable": "2",
 "duravent da": "2",
 "doral": "2",
 "dallergy pse": "2",
 "doxazosin": "2",
 "dicyclomine": "2",
 "diphenhydramine/phenylephrine": "2",
 "diphenmax": "2",
 "dialyvite 800 with zinc": "2",
 "dallergy pe": "2",
 "diphenhydramine/ibuprofen": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "diphenyl": "2",
 "diltiazem/enalapril": "2",
 "donnapine": "2",
 "doxepin": "1",
 "darcalma": "2",
 "diupres-250": "2",
 "dichlorphenamide": "2",
 "diltiazem hydrochloride xt": "2",
 "diltiazem hydrochloride xr": "2",
 "didanosine": "2",
 "dexchlorpheniramine/methscopolamine/pseudoephedrine": "2",
 "darifenacin": "2",
 "diaqua-2": "2",
 "diltiazem": "2",
 "dialyvite 800 ultra d": "2",
 "dermavite": "2",
 "d-tann": "2",
 "dolomite": "2",
 "dytan-d": "2",
 "droperidol/fentanyl": "2",
 "droperidol": "2",
 "dialyvite 5000": "2",
 "diphen": "2",
 "dilacor xr": "2",
 "dayalets plus iron": "2",
 "diaqua": "2",
 "dihydroxyaluminum sodium carbonate": "1",
 "docefrez": "2",
 "denzapine": "2",
 "diphenylin": "2",
 "delsym children's night time cough &amp; cold": "2",
 "diphenmax d": "2",
 "docusate/ferrous fumarate": "2",
 "dapsone": "2",
 "deserpidine/methyclothiazide": "2",
 "dexodryl": "2",
 "diurese": "2",
 "donnatal": "2",
 "dutoprol": "2",
 "dicyclocot": "2",
 "dual action complete": "1",
 "durahist d": "2",
 "dical-d": "1",
 "darvon-n": "3",
 "darpaz": "2",
 "daranide": "2",
 "disulfiram": "2",
 "dexphen m": "2",
 "duradryl jr": "2",
 "duradryl": "2",
 "diphenhydramine": "2",
 "d-tann at": "2",
 "daily multi-vitamins with minerals": "2",
 "digex": "2",
 "dytan": "2",
 "d-hist d": "2",
 "darvon": "3",
 "dolsed": "2",
 "dytan-hc": "2",
 "diastat acudial": "2",
 "da chewable": "2",
 "dyazide": "2",
 "dextromethorphan/diphenhydramine/phenylephrine": "2",
 "duratan pe": "2",
 "duratuss ac 12": "2",
 "diavite plus": "2",
 "diphen af": "2",
 "darvon compound-65": "3",
 "donnamar": "2",
 "desipramine": "1",
 "diphentann-d": "2",
 "diazepam intensol": "2",
 "diuretic ap-es": "2",
 "docetaxel": "2",
 "dialyvite with zinc rx": "2",
 "dormin": "2",
 "denaze": "2",
 "d-tal": "2",
 "daily multiple for men 50+": "2",
 "d-tann hc": "2",
 "duet dha": "2",
 "dytan-dm": "2",
 "diazoxide": "2",
 "diphedryl": "2",
 "doxadura": "2",
 "duet": "2",
 "dialyvite": "2",
 "dexchlorpheniramine/methscopolamine/phenylephrine": "2",
 "diphenhydramine/hydrocodone/phenylephrine": "2",
 "d-tann dm": "2",
 "disney winnie the pooh gummies": "2",
 "diquinol": "2",
 "diuril sodium": "2",
 "di-gel lemon": "1",
 "d-tann cd": "2",
 "diastat pediatric": "2",
 "dytuss": "2",
 "darvocet-n 100": "3",
 "daily-vite weight control": "2",
 "digex nf": "2",
 "daily multiple for women 50+": "2",
 "deserpidine/hydrochlorothiazide": "2",
 "daily multiple for women": "2",
 "diphendryl": "2",
 "d-tann ct": "2",
 "detrol la": "2",
 "dallergy er": "2",
 "diazepam": "2",
 "drysec": "2",
 "diutensen-r": "2",
 "dilantin": "2",
 "demadex iv": "2",
 "dibent": "2",
 "dextromethorphan/promethazine": "2",
 "diucardin": "2",
 "diphenhist": "2",
 "duradryl sr": "2",
 "dewees carminative": "1",
 "diatx zn": "2",
 "drihist sr": "2",
 "dalmane": "2",
 "dutasteride/tamsulosin": "2",
 "diltiazem hydrochloride sr": "2",
 "durahist": "2",
 "dyrenium": "2",
 "donnaphen": "2",
 "dexodryl suspension": "2",
 "diphen cough": "2",
 "drymax": "2",
 "dimetapp children's nighttime cold &amp; congestion": "2",
 "decagen": "2",
 "dicalphos plus d": "1",
 "dynacirc cr": "2",
 "demerol": "2",
 "diltia xt": "2",
 "duet dha complete": "2",
 "dulcolax milk of magnesia": "1",
 "dytan-cd": "2",
 "darvocet-n 50": "3",
 "dilt-xr": "2",
 "duet dha with ferrazone": "2",
 "dytan-cs": "2",
 "diphenhydramine/pseudoephedrine": "2",
 "darvocet a500": "3"}, "g": {"gevrabon": "2",
 "genahist": "2",
 "gentle iron": "2",
 "gold age liquid vitamins and minerals": "2",
 "gevratonic": "2",
 "golimumab": "2",
 "gaviscon regular strength tablets": "1",
 "gablofen": "2",
 "glycopyrrolate": "2",
 "gold sodium thiomalate": "2",
 "gaviscon regular strength liquid": "1",
 "gaviscon extra strength liquid": "1",
 "gelusil": "1",
 "guanethidine": "1",
 "genapap pm": "2",
 "gastrinex": "2",
 "geri-tonic": "2",
 "generix-t": "2",
 "gas-x with maalox extra strength": "1",
 "gesticare dha dr": "2",
 "guanfacine": "2",
 "gaviscon extra relief formula": "1",
 "glutofac-mx": "2",
 "glutofac-zx": "2",
 "guanabenz": "2",
 "gesticare dha": "2",
 "genaton": "1",
 "geravim": "2",
 "garfield vitamin with iron": "2",
 "geritol extend": "2",
 "gestuss-hc": "2",
 "guanethidine/hydrochlorothiazide": "2",
 "gas-x with maalox": "1",
 "garfield complete vitamins": "2",
 "gynovite": "2",
 "geritol complete": "2",
 "geri-tabs": "2",
 "gaviscon-2": "1",
 "geodon": "2",
 "gastrosed": "2",
 "gelnique": "2",
 "geritol": "2",
 "gesticare": "2",
 "good sense children's vitamins with iron": "2",
 "gerivite liquid": "2",
 "glauctabs": "2",
 "gaviscon extra strength tablets": "1",
 "generet-500 with folic acid": "2",
 "genaton chewable": "1"}, "f": {"fer-iron": "2",
 "femiron multi with iron": "2",
 "flintstones gummies": "2",
 "ferro-caps": "2",
 "folgard os": "2",
 "ferrex 150 forte": "2",
 "ferrocite plus": "2",
 "flagyl iv": "2",
 "ferrous fumarate": "2",
 "formula b plus": "2",
 "ferrovite fa": "2",
 "felodipine": "2",
 "fetrin": "2",
 "ferrex-150": "2",
 "foltabs plus dha": "2",
 "ferrous fumarate/folic acid": "2",
 "ferrocite": "2",
 "ferra t.d. caps": "2",
 "ferrocite f": "2",
 "ferrous ds": "2",
 "fludara": "2",
 "ferralet": "2",
 "fe-tinic 150 forte": "2",
 "fruity chews with iron": "2",
 "femecal ob": "2",
 "foltabs prenatal plus dha": "2",
 "ferrousal": "2",
 "ferocon": "2",
 "flavoxate": "2",
 "folbecal": "2",
 "ferrex 28": "2",
 "ferbee": "2",
 "fero-gradumet filmtab": "2",
 "ferretts ips": "2",
 "furoxone": "3",
 "fe-stool": "2",
 "ferro-time": "2",
 "ferrex pc forte": "2",
 "first mouthwash blm": "1",
 "fer-gen-sol": "2",
 "ferrous sulfate": "2",
 "formula twenty-one": "2",
 "ferotrinsic": "2",
 "folivan-prx dha": "2",
 "femecal ob plus dha": "2",
 "folcaps omega 3": "2",
 "flomax": "2",
 "flurazepam": "2",
 "fanapt": "2",
 "fluphenazine": "2",
 "folivan-ec dha": "2",
 "foltrin": "2",
 "fast acting mylanta": "1",
 "ferro-sequels": "2",
 "fe 50": "2",
 "ferosul": "2",
 "fosfree": "2",
 "ferralet 90": "2",
 "femnatal": "2",
 "fluoxetine/olanzapine": "2",
 "foli-iron": "2",
 "foltabs": "2",
 "ferro-dss": "2",
 "flagyl": "2",
 "ferretts": "2",
 "florical": "1",
 "femiron": "2",
 "feosol": "2",
 "femtabs": "2",
 "folivan-ob": "2",
 "flumezide": "2",
 "ferocyl": "2",
 "ferra-td": "2",
 "ferate": "2",
 "fem-natal": "2",
 "fe-40": "2",
 "fosinopril": "2",
 "ferrous fumarate/folic acid/iron polysaccharide": "2",
 "fosphenytoin": "2",
 "ferrous fumarate/iron polysaccharide": "2",
 "ferragen": "2",
 "ferrovite forte": "2",
 "folivan-plus": "2",
 "folcaps care one": "2",
 "ferra-cap": "2",
 "feostat": "2",
 "feratab": "2",
 "furosemide": "2",
 "furazolidone": "3",
 "ferrex 150 plus": "2",
 "fe caps": "2",
 "folpace rx": "2",
 "fumasorb": "2",
 "ferrogels forte": "2",
 "foltabs 90 plus dha": "2",
 "forfivo xl": "2",
 "ferrous gluconate": "2",
 "flagyl er": "2",
 "feosol iron": "2",
 "fero-grad-500": "2",
 "ferus pic-150": "2",
 "ferrimin 150": "2",
 "furadantin": "2",
 "ferotrin": "2",
 "ferrospace": "2",
 "flintstones with iron chewable": "2",
 "fe c tab plus": "2",
 "ferrets": "2",
 "fe-tinic 150": "2",
 "ferro-bob": "2",
 "fludarabine": "2",
 "fergon": "2",
 "foltabs prenatal": "2",
 "flintstones with calcium": "2",
 "feosol caplet": "2",
 "fazaclo": "2",
 "folbee plus cz": "2",
 "feogen": "2",
 "fero-folic 500": "2",
 "folitab 500": "2",
 "folivan-f": "2",
 "flagyl 375": "2",
 "fluvastatin": "2",
 "ferrex 150 forte plus": "2",
 "flintstones complete": "2",
 "ferroflex-150 forte": "2",
 "folcal dha": "2",
 "fasigyn": "2",
 "feocyte": "2",
 "ferrovite": "2",
 "ferro basic": "2",
 "fumatinic": "2",
 "ferraplus": "2",
 "fer-in-sol": "2",
 "ferrous sulfate/folic acid": "2",
 "fosinopril/hydrochlorothiazide": "2"}, "i": {"isradipine": "2",
 "icare prenatal rx": "2",
 "innopran xl": "2",
 "icaps lutein &amp; omega-3": "2",
 "icaps with lutein and zeaxan": "2",
 "iberet liquid": "2",
 "icar prenatal chewable calcium": "1",
 "isoniazid/pyrazinamide/rifampin": "2",
 "intrinsitinic": "2",
 "indapamide": "2",
 "inatal ultra": "2",
 "iron protein succinylate": "2",
 "icar": "2",
 "icar prenatal": "2",
 "ismelin": "1",
 "intelence": "2",
 "isocarboxazid": "3",
 "isoptin iv": "2",
 "icaps mv": "2",
 "icar-c plus sr": "2",
 "integra": "2",
 "i-l-x and b12": "2",
 "ixempra": "2",
 "inapsine": "2",
 "i-vite": "2",
 "imipramine": "1",
 "invega": "2",
 "isoptin": "2",
 "icar-c plus": "2",
 "iberet-500": "2",
 "iferex 150 forte": "2",
 "iberet": "2",
 "ixabepilone": "2",
 "iron fumarate": "2",
 "iferex 150": "2",
 "integra plus": "2",
 "inderal": "2",
 "ipilimumab": "2",
 "interferon alfa-2b/ribavirin": "2",
 "i-sense occushield": "2",
 "ircon": "2",
 "ib-stat": "2",
 "interferon alfacon-1": "2",
 "iron polysaccharide": "2",
 "i-l-x": "2",
 "inderide": "2",
 "iromin g": "2",
 "interferon alfa-n1": "2",
 "inderal la": "2",
 "icaps plus": "2",
 "inatal advance": "2",
 "infergen": "2",
 "isoniazid/rifampin": "2",
 "iro-plex": "2",
 "icaps areds": "2",
 "irospan 24/6": "2",
 "interferon alfa-2b": "2",
 "interferon alfa-2a": "2",
 "ibc 500": "2",
 "iron-150": "2",
 "iron chews": "2",
 "intuniv": "2",
 "invega sustenna": "2",
 "infanate dha": "2",
 "i-fol plus": "2",
 "intron a": "2",
 "irbesartan": "2",
 "icaps tr": "2",
 "iron gluconate": "2",
 "innovar": "2",
 "isoniazid": "2",
 "i-sense": "2",
 "iron sulfate": "2",
 "irofol": "2",
 "inderide la": "2",
 "infliximab": "2",
 "integra f": "2",
 "inspra": "2",
 "iberet-folic-500": "2",
 "isonarif": "2",
 "icaps": "2",
 "iloperidone": "2",
 "iosopan": "1",
 "iodoquinol": "2",
 "isoptin sr": "2",
 "i-vite protect": "2",
 "ircon-fa": "2"}, "h": {"hydro-reserp": "2",
 "hemocyte plus": "2",
 "hycodan": "2",
 "headache formula pm": "2",
 "histatab ph": "2",
 "heme iron polypeptide/iron polysaccharide": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydrap-es": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "2",
 "hyomax sr": "2",
 "hydrodiuril": "2",
 "hyoscyamine/phenyltoloxamine": "2",
 "hyomax sl": "2",
 "hydroserpine 1": "2",
 "hyophen": "2",
 "hista-vent da": "2",
 "hydrochlorothiazide/propranolol": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "hyosyne": "2",
 "haley's m-o": "1",
 "hydra-zide": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrochlorothiazide/reserpine": "2",
 "humira": "2",
 "hydramine cough syrup": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydralazine/isosorbide dinitrate": "2",
 "hytrin": "2",
 "homatropine/hydrocodone": "2",
 "hyoscyamine/phenobarbital": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hyzaar": "2",
 "helidac": "2",
 "hydrochlorothiazide/methyldopa": "2",
 "hyomax ft": "2",
 "hydropres-50": "2",
 "hydrochlorothiazide/moexipril": "2",
 "halflytely and bisacodyl": "1",
 "hyospaz": "2",
 "hista-vent pse": "2",
 "hygroton": "2",
 "hematogen forte": "2",
 "hydromet": "2",
 "hydromide": "2",
 "hydrochlorothiazide": "2",
 "hematinic plus": "2",
 "hemax": "2",
 "hivid": "2",
 "hyrexin": "2",
 "hair booster": "2",
 "hyoscyamine": "2",
 "hyosol": "2",
 "hyoscyamine/methenamine": "2",
 "hemocyte-f": "2",
 "hemocyte-c": "2",
 "hemocyte": "2",
 "hyosophen": "2",
 "hyomax dt": "2",
 "halcion": "2",
 "hematogen fa": "2",
 "hydroflumethiazide": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hydropane": "2",
 "haldol decanoate": "2",
 "hydrotropine": "2",
 "hemaspan": "2",
 "hydro-dp": "2",
 "hytinic": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "heme iron polypeptide": "2",
 "histatab": "2",
 "hydroserp": "2",
 "halaven": "2",
 "hydrochlorothiazide/timolol": "2",
 "hydroflumethiazide/reserpine": "2",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "2",
 "hydropres-25": "2",
 "hematogen": "2",
 "hyomax": "2",
 "hemocyte-f elixir": "2",
 "high potency": "2",
 "hydro par": "2",
 "headache relief pm": "2",
 "haldol": "2",
 "hhr": "2",
 "haloperidol": "2",
 "hyperstat iv": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "heartburn antacid extra strength": "1",
 "hydramine compound": "2",
 "hi-nate 90": "2",
 "hydroserpine": "2",
 "hydrochlorothiazide/losartan": "2",
 "hydralazine": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hyperstat": "2",
 "hematinic with folic acid": "2",
 "hydroxychloroquine": "2",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "histatab d": "2",
 "hydramine": "2",
 "harmonyl": "2",
 "hydralazine plus": "2",
 "halazepam": "2"}, "k": {"klonopin": "2",
 "kapvay": "2",
 "kava": "2",
 "klonopin wafer": "2",
 "kemstro": "2",
 "kuvan": "2",
 "kerlone": "2",
 "kemadrin": "2",
 "kolnatal dha": "2"}, "j": {"juvisync": "2",
 "jumex": "2",
 "jalyn": "2",
 "jevtana": "2",
 "jenloga": "2"}, "m": {"mynatal ultracap": "2",
 "maxivision eye formula": "2",
 "martinic": "2",
 "maxivision whole body formula": "2",
 "maternity": "2",
 "multivitamin, prenatal": "2",
 "metahydrin": "2",
 "mynatal rx": "2",
 "maoson": "1",
 "multivitamin with iron": "2",
 "maalox advanced maximum strength": "1",
 "magnesium oxide": "1",
 "milantex maximum strength": "1",
 "magnebind 400 rx": "2",
 "maldemar": "2",
 "mhp-a": "2",
 "midazolam": "2",
 "mi-acid ii": "1",
 "maxinate": "2",
 "methyclothiazide/reserpine": "2",
 "mykidz iron": "2",
 "migracet-pb": "2",
 "mynate 90 plus": "2",
 "magaldrate plus suspension": "1",
 "multi-betic": "2",
 "mylanta gelcap": "1",
 "minizide": "2",
 "m-phen": "2",
 "magnesium carbonate": "1",
 "mynatal z": "2",
 "magaldrate": "1",
 "moduretic": "2",
 "monocal": "1",
 "m-vit": "2",
 "multi-nate dha": "2",
 "mescolor": "2",
 "mirapex": "2",
 "maalox advanced maximum strength chewable": "1",
 "maalox max wild berry": "1",
 "monopril": "2",
 "montelukast": "2",
 "miles nervine": "2",
 "myferon 150 forte": "2",
 "mynatal pn forte": "2",
 "mylagen-ii": "1",
 "maggel": "1",
 "matzim la": "2",
 "multi-delyn with iron": "2",
 "midamor": "2",
 "metryl": "2",
 "motofen": "2",
 "mykrox": "2",
 "mintox extra strength": "1",
 "mission prenatal hp": "2",
 "macrobid": "2",
 "minoxidil": "2",
 "maxaron forte": "2",
 "mag-200": "1",
 "midol pm": "2",
 "maalox max quick dissolve": "1",
 "motrin pm": "2",
 "metoprolol succinate er": "2",
 "myadec": "2",
 "maalox": "1",
 "metozolv odt": "2",
 "milantex": "1",
 "mission prenatal fa": "2",
 "magnesium hydroxide/mineral oil": "1",
 "molindone": "2",
 "multi-nate 30 kit": "2",
 "methyldopa": "1",
 "multifol": "2",
 "mevacor": "2",
 "mi-acid double strength": "1",
 "metoclopramide": "2",
 "magaant": "1",
 "maternity vitamin low iron": "2",
 "micardis": "2",
 "mediplex ultra": "2",
 "maternity-90": "2",
 "mynatal fc": "2",
 "magonate tablets": "2",
 "methscopolamine/phenylephrine": "2",
 "magnesium hydroxide": "1",
 "maldroxal": "1",
 "meperitab": "2",
 "masanti ds": "1",
 "multifol plus": "2",
 "mag-carb": "1",
 "maalox plus extra strength": "1",
 "multinatal plus": "2",
 "mylanta maximum strength cherry": "1",
 "myochrysine": "2",
 "multi vita bets and fluoride and iron": "2",
 "mylanta ultra": "1",
 "maalox advanced regular strength": "1",
 "multigen": "2",
 "marnatal-f": "2",
 "meprozine": "2",
 "minipress": "2",
 "magnebind 200": "1",
 "metro": "2",
 "mepergan fortis": "2",
 "maldroxal plus": "1",
 "methyclothiazide": "2",
 "mylanta fast acting": "1",
 "mylanta supreme": "1",
 "maxivision eye &amp; body formula": "2",
 "milk of magnesia": "1",
 "macrodantin": "2",
 "multibret folic 500": "2",
 "micomp-pb": "2",
 "maalox junior relief chewable": "1",
 "mi-c-t": "2",
 "mynatal plus": "2",
 "mag-sr with calcium": "2",
 "multigen folic": "2",
 "mepenzolate": "2",
 "mintox plus": "1",
 "maalox regular strength": "1",
 "mapap pm": "2",
 "mitran": "2",
 "mykidz iron 10": "2",
 "metolazone": "2",
 "mylagen": "1",
 "mylanta": "1",
 "maternal 90": "2",
 "mintox maximum strength": "1",
 "myambutol": "2",
 "multiret folic 500": "2",
 "multivitamin with iron and fluoride": "2",
 "maalox plus": "1",
 "mag-ox": "1",
 "metronidazole": "2",
 "myferon 150": "2",
 "multi-nate 30 dha": "2",
 "mission prenatal": "2",
 "mepergan": "2",
 "mag-caps": "1",
 "msp-blu": "2",
 "maalox quick dissolve extra strength": "1",
 "multigen plus": "2",
 "multi-nate dha extra": "2",
 "mylanta ultimate strength": "1",
 "micardis hct": "2",
 "marblen": "1",
 "methazolamide": "2",
 "matulane": "3",
 "maxivision ocular formula": "2",
 "maalox children's relief": "1",
 "mission prenatal rx": "2",
 "mynatal": "2",
 "moduretic 5-50": "2",
 "masanti": "1",
 "mirapex er": "2",
 "maxzide-25": "2",
 "magnebind 300": "1",
 "mult-ferr folic": "2",
 "microzide": "2",
 "mol-iron": "2",
 "metoprolol": "2",
 "masanti supreme": "1",
 "magnaprin": "1",
 "mag-ox 400": "1",
 "maalox tc": "1",
 "mi-acid": "1",
 "meperidine": "2",
 "multilex-t/m+minerals": "2",
 "marplan": "3",
 "mellaril-s": "2",
 "my-a-multi": "2",
 "methotrimeprazine": "2",
 "methscopolamine/pseudoephedrine": "2",
 "magaldrate/simethicone": "1",
 "mykidz iron fl": "2",
 "multi-day plus minerals": "2",
 "meperidine/promethazine": "2",
 "magna-c-7 forte": "2",
 "marnatal-f plus": "2",
 "mens pack": "2",
 "metro iv": "2",
 "mag-oxide": "1",
 "monopril hct": "2",
 "myvitalife": "2",
 "mylanta ds fast acting": "1",
 "maalox max": "1",
 "multivitamin with minerals": "2",
 "multilex": "2",
 "mylanta maximum strength": "1",
 "mavik": "2",
 "mibefradil": "2",
 "maalox antacid antigas regular strength": "1",
 "mintox": "1",
 "maternity plus beta carotene": "2",
 "medique medi-seltzer": "1",
 "maxzide": "2",
 "mzm": "2",
 "mesoridazine": "2",
 "maxolon": "2",
 "mellaril": "2",
 "metatensin 4": "2",
 "methscopolamine": "2",
 "metatensin 2": "2",
 "mylanta child": "1",
 "moban": "2",
 "materna": "2",
 "memantine": "1",
 "multi-nate 30": "2",
 "mintox tablets": "1",
 "megavite rx": "2",
 "mynatal pn": "2",
 "moexipril": "2",
 "methdilazine": "2",
 "multi-day with calcium and extra iron": "2",
 "maalox hrf": "1",
 "marpres": "2"}, "l": {"losospan plus": "1",
 "livalo": "2",
 "lomotil": "2",
 "loqua": "2",
 "lotrel": "2",
 "levsin": "2",
 "loxitane c": "2",
 "lowsium plus": "1",
 "lonox": "2",
 "lisinopril": "2",
 "levsin with phenobarbital": "2",
 "lioresal intrathecal": "2",
 "levsin sl": "2",
 "lydia e. pinkham": "2",
 "lydia pinkham": "2",
 "lysiplex plus": "2",
 "lescol": "2",
 "lurline pms": "2",
 "livitrinsic-f": "2",
 "loniten": "2",
 "lozol": "2",
 "lidocaine/sodium bicarbonate": "1",
 "lorazepam intensol": "2",
 "labetalol": "2",
 "levsinex": "2",
 "limbitrol": "2",
 "levatol": "2",
 "librium": "2",
 "leflunomide": "2",
 "lasix": "2",
 "lotensin hct": "2",
 "lomocot": "2",
 "lioresal": "2",
 "linezolid": "3",
 "largon": "2",
 "lowsium": "1",
 "l-tonic": "2",
 "levbid": "2",
 "limbitrol ds": "2",
 "lomanate": "2",
 "librax": "2",
 "losartan": "2",
 "loxitane im": "2",
 "lactocal-f": "2",
 "legatrin pm": "2",
 "lovastatin/niacin": "2",
 "lopressor": "2",
 "lovastatin": "2",
 "lipitor": "2",
 "lurasidone": "2",
 "lo-aqua": "2",
 "lorazepam": "2",
 "loxitane": "2",
 "logen": "2",
 "losospan": "1",
 "lexxel": "2",
 "lactobacillus acidophilus/methscopolamine": "2",
 "lopressor hct": "2",
 "liqui-allergy": "2",
 "lotensin": "2",
 "lescol xl": "2",
 "loxapine": "2",
 "leg-gesic": "2",
 "levsinex sr": "2",
 "levoprome": "2",
 "latuda": "2"}, "o": {"onfi": "2",
 "oystercal-d": "1",
 "obegyn": "2",
 "ob complete with dha": "2",
 "oxytrol": "2",
 "one-a-day within": "2",
 "opti-gen": "2",
 "oyst cal": "1",
 "oyster": "1",
 "o-cal-d": "1",
 "oreticyl 50": "2",
 "optinate": "2",
 "ob complete premier": "2",
 "oreticyl forte": "2",
 "oyster-d": "1",
 "omeprazole/sodium bicarbonate": "1",
 "oysco d with calcium": "1",
 "os-cal": "1",
 "ob natal one": "2",
 "obtrex dha": "2",
 "oxybutynin": "2",
 "os-cal 500": "1",
 "ocuvite preservision": "2",
 "one daily with minerals": "2",
 "ocuvite": "2",
 "omnihist l.a.": "2",
 "one-a-day vitacraves": "2",
 "os-cal ultra": "2",
 "os-cal 500 + d": "1",
 "one-a-day men pro edge": "2",
 "one-a-day max": "2",
 "one-a-day weightsmart": "2",
 "oyster cal": "1",
 "oyst cal 500": "1",
 "occuplex": "2",
 "ocuvite extra": "2",
 "one tab daily with iron": "2",
 "onxol": "2",
 "oxaliplatin": "2",
 "oyster cal 500": "1",
 "oyster shell calcium 500": "1",
 "ob-20": "2",
 "one-a-day women": "2",
 "oxazepam": "2",
 "oysco d": "1",
 "optivite pmt": "2",
 "ob complete": "2",
 "ostiva": "2",
 "one-a-day men 50 plus": "2",
 "oyster shell calcium with vitamin d": "1",
 "o-cal prenatal": "2",
 "oysco 500 with d": "1",
 "one-a-day women 50 plus": "2",
 "orap": "2",
 "oyster shell calcium": "1",
 "oyster shell": "1",
 "oncovin": "2",
 "oreticyl 25": "2",
 "olmesartan": "2",
 "ob complete 400": "2",
 "obnate 90": "2",
 "oyst-cal-d": "1",
 "optilets-m-500": "2",
 "osteocit d plus": "1",
 "omnihist ii la": "2",
 "oyster calcium": "1",
 "one tab daily with minerals": "2",
 "oretic": "2",
 "oforta": "2",
 "obtrex": "2",
 "ocuvite lutein": "2",
 "os-cal 500 + extra d": "1",
 "olanzapine": "2",
 "ormazine": "2",
 "oysco 500": "1",
 "o-cal fa": "2"}, "n": {"nutrispire": "2",
 "natalcare advanced": "2",
 "nytol": "2",
 "nitrofurantoin": "2",
 "natalcare pic forte": "2",
 "nu-iron 150": "2",
 "natelle prefer": "2",
 "nitroprusside": "2",
 "nebivolol": "2",
 "nu-iron v": "2",
 "natalcare": "2",
 "nulev": "2",
 "niferex-pn": "2",
 "nu-med": "2",
 "nestrex": "2",
 "nicotinamide zcf": "2",
 "natalcare cfe 60": "2",
 "nephron-fa": "2",
 "nutrinate": "2",
 "natelle-ez": "2",
 "nata 29 ob": "2",
 "norpramin": "1",
 "niferex elixir": "2",
 "natacaps": "2",
 "novastart": "2",
 "neut": "1",
 "nanovm": "2",
 "niacin/simvastatin": "2",
 "natelle one": "2",
 "nephro-fer": "2",
 "niferex": "2",
 "novaferrum": "2",
 "nata 29 prenatal": "2",
 "nestabs rx": "2",
 "natalcare glosstabs": "2",
 "nu-iron plus": "2",
 "nohist pe": "2",
 "nohist ext": "2",
 "nestabs fa": "2",
 "nohist plus": "2",
 "nitropress": "2",
 "natelle": "2",
 "nu-iron": "2",
 "namenda": "1",
 "normodyne": "2",
 "natafolic-ob": "2",
 "nestabs": "2",
 "nytol caplet": "2",
 "natalcare rx": "2",
 "natelle one dha": "2",
 "new advanced formula prenatal z": "2",
 "niferex-150 forte": "2",
 "natatab fa": "2",
 "neptazane": "2",
 "niferex-150": "2",
 "nutiifac zx": "2",
 "naturetin": "2",
 "night time pain": "2",
 "nifedipine": "2",
 "natarex": "2",
 "nortriptyline": "1",
 "naqua": "2",
 "nicardipine": "2",
 "neevo": "2",
 "novanatal": "2",
 "natatab rx": "2",
 "nydrazid": "2",
 "nacon": "2",
 "nifediac cc": "2",
 "norvasc": "2",
 "nephro calci": "1",
 "navane": "2",
 "nexiclon xr": "2",
 "neevo dha": "2",
 "nephro-fer rx": "2",
 "natelle c": "2",
 "nohist plus jr": "2",
 "nifedical xl": "2",
 "natatab cfe": "2",
 "norel sd": "2",
 "nephro-vite with fe": "2",
 "nadolol": "2",
 "naturetin-5": "2",
 "niferex pn forte": "2",
 "natalcare advanced-rf": "2",
 "nervine": "2",
 "nic 750": "2",
 "naturetin-10": "2",
 "natalcare plus": "2",
 "natalins rx": "2",
 "neo-forte": "2",
 "nisoldipine": "2",
 "natachew": "2",
 "natelle plus with dha": "2",
 "natafolic-pn": "2",
 "namenda xr": "1",
 "nelarabine": "2",
 "nature's blend theratrum complete tablets 50 plus": "2",
 "nardil": "3",
 "natalfirst": "2",
 "niferex gold": "2",
 "nicomide": "2",
 "nightime sleepaid": "2",
 "nexterone": "2",
 "nexa select with dha": "2",
 "nestabs cbf": "2",
 "nitro macro": "2",
 "niravam": "2",
 "nephrox": "1",
 "norlac rx": "2",
 "nutravance": "2",
 "natalcare pic": "2",
 "navelbine": "2",
 "natalcare three": "2",
 "natafort": "2",
 "natalins": "2",
 "nicazel": "2"}, "q": {"quenalin": "2",
 "quinaretic": "2",
 "q-dryl": "2",
 "quinapril": "2",
 "qv-allergy": "2",
 "quazepam": "2",
 "quetiapine": "2",
 "quarzan": "2",
 "quineprox": "2",
 "q-dryl a/f": "2",
 "quadrapax": "2"}, "p": {"pyridium plus": "2",
 "phosphasal": "2",
 "poly iron forte": "2",
 "pr natal 440": "2",
 "prostate 2.4": "2",
 "phillips' cramp-free": "1",
 "paire ob plus dha": "2",
 "probenecid and colchicine": "2",
 "prenatal low iron": "2",
 "prenatal multivitamins": "2",
 "pramilet fa": "2",
 "pan ob forte": "2",
 "prenatal mtr with selenium": "2",
 "primacare": "2",
 "polysaccharide iron": "2",
 "pyrelle hb": "2",
 "proferrin-es": "2",
 "pseudox m": "2",
 "promar": "2",
 "prinzide": "2",
 "pronemia": "2",
 "pindolol": "2",
 "procardia": "2",
 "pyridoxine": "2",
 "pcm": "2",
 "pr natal 400 ec": "2",
 "promethazine with dm": "2",
 "paxipam": "2",
 "prenatabs cbf": "2",
 "prenatal 1 plus 1": "2",
 "prenafirst": "2",
 "pardryl": "2",
 "prolixin": "2",
 "poly-vi-sol with iron drops": "2",
 "plaquenil": "2",
 "prenatal-u": "2",
 "propoxyphene compound 65": "3",
 "preterna": "2",
 "prenavite": "2",
 "pnv-total": "2",
 "phenadoz": "2",
 "prenate plus": "2",
 "polythiazide/prazosin": "2",
 "prenatabs fa": "2",
 "paclitaxel": "2",
 "procarbazine": "3",
 "prenavite fc": "2",
 "phillips' haleys m-o": "1",
 "platinol-aq": "2",
 "protriptyline": "1",
 "pepcid complete": "1",
 "pnv-dha plus": "2",
 "phenylephrine/promethazine": "2",
 "prenexa with dha": "2",
 "poly-vi-sol with iron": "2",
 "primacare advantage": "2",
 "phenazine 50": "2",
 "permitil": "2",
 "prenate dha": "2",
 "protuss tablet": "2",
 "pediacare children's allergy": "2",
 "prenate 90": "2",
 "prolixin enanthate": "2",
 "parnate": "3",
 "pms balance": "2",
 "phenoject-50": "2",
 "peginterferon alfa-2a": "2",
 "peginterferon alfa-2b": "2",
 "previte rx": "2",
 "phenytek": "2",
 "paliperidone": "2",
 "pb-hyos": "2",
 "prosteon": "2",
 "prehist d": "2",
 "prenatabs obn": "2",
 "poly-vi-flor with iron": "2",
 "percogesic extra strength": "2",
 "pravastatin": "2",
 "pediatex-ct": "2",
 "prenatal rx": "2",
 "poly vitamin with fluoride with iron": "2",
 "posture-d h/p": "1",
 "prenate essential": "2",
 "promethazine vc with codeine": "2",
 "prochlorperazine": "2",
 "platinol": "2",
 "premesis rx": "2",
 "posicor": "2",
 "potassium bicarbonate/sodium bicarbonate": "1",
 "par-f": "2",
 "prenatal plus with 27 mg iron": "2",
 "pc-cap": "3",
 "prefera ob plus dha": "2",
 "pnv select": "2",
 "prenate gt": "2",
 "prenate elite plus iron": "2",
 "precare conceive": "2",
 "penbutolol": "2",
 "prenate ultra": "2",
 "phenytoin sodium, prompt": "2",
 "prenatal plus with beta-carotene": "2",
 "propiomazine": "2",
 "propoxyphene": "3",
 "pruet dha": "2",
 "prenatal s": "2",
 "phenaz plus": "2",
 "phenelzine": "3",
 "prenatal rx 1": "2",
 "prolixin decanoate": "2",
 "pacerone": "2",
 "protegra softgel": "2",
 "poly iron 150 forte": "2",
 "polythiazide/reserpine": "2",
 "pro-med": "2",
 "prenexa": "2",
 "prosight": "2",
 "pylera": "2",
 "propacet 100": "3",
 "phenergan vc with codeine": "2",
 "pitavastatin": "2",
 "pro-banthine": "2",
 "promethazine vc": "2",
 "propantheline": "2",
 "prefera ob-one": "2",
 "prenatal z advanced formula": "2",
 "prenate elite": "2",
 "promethazine with codeine": "2",
 "pr natal 400": "2",
 "profe": "2",
 "pcm-la": "2",
 "procardia xl": "2",
 "propranolol": "2",
 "prenate advance": "2",
 "phosenamine": "2",
 "preservision": "2",
 "prazosin": "2",
 "prinivil": "2",
 "paraplatin": "2",
 "pruvate 21/7": "2",
 "pegintron": "2",
 "procycle multi vitamin with minerals": "2",
 "pp-cap": "3",
 "phenazoforte plus": "2",
 "prenatal h": "2",
 "pain relief pm extra strength": "2",
 "pamelor": "1",
 "pannaz": "2",
 "pediacare children's allergy &amp; cold": "2",
 "pimozide": "2",
 "pramipexole": "2",
 "protostat": "2",
 "procyclidine": "2",
 "perindopril": "2",
 "promethazine vc plain": "2",
 "prosom": "2",
 "prenatal ad": "2",
 "promazine": "2",
 "pseudo cm tr": "2",
 "prenatabs rx": "2",
 "proglycem": "2",
 "prosed ds": "2",
 "procot": "2",
 "proben-c": "2",
 "promethazine dm": "2",
 "phenergan": "2",
 "pegasys": "2",
 "pamine forte": "2",
 "promethazine vc w/codeine": "2",
 "plendil": "2",
 "prenatal plus": "2",
 "prenacare": "2",
 "prenatal mr 90 fe": "2",
 "prenatal elite": "2",
 "preque 10": "2",
 "paclitaxel protein-bound": "2",
 "pre-h-cal": "2",
 "phenytoin": "2",
 "phenergan fortis": "2",
 "pamine fq": "2",
 "pcm allergy": "2",
 "poly iron": "2",
 "pharbedryl": "2",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "polythiazide": "2",
 "precare": "2",
 "preferaob": "2",
 "pain reliever pm": "2",
 "prosed ec": "2",
 "pedia-lax chewable tablets": "1",
 "pamine": "2",
 "perphenazine": "2",
 "prenate advanced formula": "2",
 "precare premier": "2",
 "prenavite pc": "2",
 "promethazine with dextromethorphan": "2",
 "prenazyme 1+1": "2",
 "pravachol": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenergan vc": "2",
 "prenaplus": "2",
 "pannaz s": "2",
 "promethegan": "2",
 "promethazine hcl with codeine": "2",
 "primacare one": "2",
 "potassium bitartrate/sodium bicarbonate": "1",
 "pr natal 430": "2",
 "pharbetol pm": "2",
 "prenate essential dha": "2",
 "pnv-dha": "2",
 "pepto children's": "1",
 "phluorivit with iron": "2",
 "prenatal plus iron": "2",
 "percogesic original strength": "2",
 "pravigard pac": "2",
 "probarimin qt": "2",
 "phenergan with dextromethorphan": "2",
 "proferrin-forte": "2",
 "prenatal mr 90": "2",
 "prenatal 19": "2",
 "phillips' milk of magnesia": "1"}, "s": {"sesame st. vitamins plus iron": "2",
 "saluron": "2",
 "surbex-750 with zinc": "2",
 "singulair": "2",
 "sympak pdx": "2",
 "suplevit": "2",
 "se-care conceive": "2",
 "sourcecf abdek": "2",
 "senetonic": "2",
 "sleep": "2",
 "surpass": "1",
 "slow release iron": "2",
 "senilezol": "2",
 "sapropterin": "2",
 "symax fastab": "2",
 "sourcecf chewables": "2",
 "selgene": "2",
 "scot-tussin allergy": "2",
 "stuart prenatal with beta carotene": "2",
 "selegiline": "2",
 "serathide": "2",
 "snooze fast": "2",
 "super high vitamins and minerals": "2",
 "scopace": "2",
 "symbyax": "2",
 "slow fe with folic acid": "2",
 "sleep tab ii": "2",
 "sympak dm": "2",
 "strongstart": "2",
 "stelazine": "2",
 "serentil": "2",
 "stalevo 150": "1",
 "stuartnatal plus 3": "2",
 "siladryl": "2",
 "sal-tropine": "2",
 "strovite advance": "2",
 "solifenacin": "2",
 "sympak ii": "2",
 "solganal": "2",
 "symax duotab": "2",
 "salutensin-demi": "2",
 "super calcium": "1",
 "spastrin": "2",
 "sleepinal": "2",
 "stress formula with zinc": "2",
 "sominex pain relief formula": "2",
 "salutensin": "2",
 "sanctura": "2",
 "sleep-ettes": "2",
 "se-natal 16": "2",
 "sudafed pe severe cold": "2",
 "stalevo 75": "1",
 "stresstabs with zinc": "2",
 "ser-ap-es": "2",
 "se-care": "2",
 "sourcecf multivitamins with a,b,d,e &amp; k plus zinc": "2",
 "simcor": "2",
 "se-natal 19": "2",
 "select-ob+dha": "2",
 "stress 600 with zinc": "2",
 "sominex maximum strength caplet": "2",
 "sanctura xr": "2",
 "sodium bicarbonate/tartaric acid": "1",
 "somnicaps": "2",
 "siladryl das": "2",
 "stalevo 200": "1",
 "spectravite cardio health": "2",
 "sudafed sinus nighttime plus pain": "2",
 "se-tan dha": "2",
 "scopolamine": "2",
 "sominex": "2",
 "surpass extra strength": "1",
 "support": "2",
 "scopohist-pe": "2",
 "sudafed pe nighttime nasal decongestant": "2",
 "sympak": "2",
 "strovite": "2",
 "spectravite senior": "2",
 "simron": "2",
 "sparine": "2",
 "sourcecf pediatric drops": "2",
 "seroquel": "2",
 "seroquel xr": "2",
 "strovite plus": "2",
 "stuartnatal plus": "2",
 "scopohist syrup": "2",
 "seton et": "2",
 "sleep-ettes d": "2",
 "simponi": "2",
 "se-natal 90": "2",
 "sourcecf softgels": "2",
 "simply sleep": "2",
 "spasdel": "2",
 "sodium edecrin": "2",
 "surmontil": "1",
 "stalevo 100": "1",
 "sodium bicarbonate": "1",
 "simvastatin/sitagliptin": "2",
 "stahist": "2",
 "serax": "2",
 "siladryl allergy": "2",
 "sleep tabs": "2",
 "select-ob": "2",
 "spironolactone": "2",
 "se-plete dha": "2",
 "serpex": "2",
 "seton et-ec": "2",
 "strovite advance+d": "2",
 "sular": "2",
 "sleepwell 2-nite": "2",
 "symax sr": "2",
 "support 500": "2",
 "super theravite-m": "2",
 "sedecal d": "1",
 "siderol": "2",
 "sleep-eze-3": "2",
 "sudafed pe nighttime cold": "2",
 "symax sl": "2",
 "stresstabs with iron": "2",
 "saphris": "2",
 "spasmolin": "2",
 "silphen cough": "2",
 "sinequan": "1",
 "serpazide": "2",
 "sylatron": "2",
 "spasquid": "2",
 "se-natal one": "2",
 "simvastatin": "2",
 "stalevo 50": "1",
 "scopohist": "2",
 "se-vate": "2",
 "stalevo 125": "1",
 "stress formula with iron": "2",
 "sesame st vitamins complete": "2",
 "stalevo": "1",
 "stavudine": "2",
 "sunkist child chewable with iron": "2",
 "servira": "2",
 "sss": "2",
 "strovite one": "2",
 "sss tonic": "2",
 "strovite forte": "2",
 "silenor": "1",
 "siladyl sa": "2",
 "sodium oxybate": "3",
 "sudatrate": "2",
 "surbex-750 with iron": "2",
 "slow fe": "2",
 "sodium bicarbonate/sodium citrate": "1",
 "sectral": "2",
 "sinodec": "2"}, "r": {"rhinaclear": "2",
 "ri-mag": "1",
 "relcof pse": "2",
 "risperdal m-tab": "2",
 "re-drylex": "2",
 "re dualvit f": "2",
 "ru-tuss": "2",
 "ron-acid plus": "1",
 "rauwolfemms": "2",
 "rauwolfia 1x": "2",
 "riopan plus": "1",
 "renacidin irrgiation": "1",
 "riopan": "1",
 "regroton": "2",
 "renaplex": "2",
 "rosuvastatin": "2",
 "rhinolar": "2",
 "renatabs with iron": "2",
 "rulox plus": "1",
 "robitussin night time cough &amp; cold": "2",
 "rolaids extra strength plus gas relief softchews": "1",
 "recal d": "2",
 "relcof pe": "2",
 "rolaids regular strength": "1",
 "risacal-d": "1",
 "rexavite 150 forte": "2",
 "regurin": "2",
 "riopan plus 2": "1",
 "ron acid": "1",
 "req49+": "2",
 "renax 5.5": "2",
 "robitussin peak cold nighttime multi-symptom cold": "2",
 "reglan": "2",
 "ramipril": "2",
 "robitussin night time cough, cold &amp; flu": "2",
 "rauzide": "2",
 "rifater": "2",
 "renese-r": "2",
 "renacidin": "1",
 "red yeast rice": "2",
 "renate dha extra": "2",
 "rulox 1": "1",
 "rifamate": "2",
 "redur-pcm": "2",
 "ridaura": "2",
 "rovin-nv dha": "2",
 "ralix": "2",
 "respa c&amp;c": "2",
 "recal fol d": "2",
 "respa sa": "2",
 "restoril": "2",
 "relcof cpm": "2",
 "remicade": "2",
 "robinul forte": "2",
 "re fac-x": "2",
 "rexavite 150": "2",
 "rx support heartburn and acid reflux": "2",
 "re ob 90 plus dha": "2",
 "rondameth": "2",
 "relcof dn pse": "2",
 "roferon-a": "2",
 "risperdal consta": "2",
 "re-drylex jr": "2",
 "reserpine": "1",
 "risanoid plus": "2",
 "relcof dn pe": "2",
 "risperidone": "2",
 "rindal hpd": "2",
 "rightstep": "2",
 "rolaids extra strength": "1",
 "respa-ar": "2",
 "rolaids extra strength softchews": "1",
 "respivent df": "2",
 "rebetron": "2",
 "rescon": "2",
 "reserpine/trichlormethiazide": "2",
 "renate": "2",
 "repliva 21/7": "2",
 "re ob plus dha": "2",
 "ru-lets m 500": "2",
 "rolatuss-sr": "2",
 "resource optisource": "2",
 "re dualvit plus": "2",
 "ryneze": "2",
 "riopan plus double strength": "1",
 "respivent-d": "2",
 "rauwolfia serpentina": "2",
 "rolaids multi-symptom": "1",
 "renate dha": "2",
 "rasagiline": "2",
 "rulox": "1",
 "reocyte plus": "2",
 "re-pb hyos elixir": "2",
 "risperdal": "2",
 "rovin-nv": "2",
 "renax": "2",
 "renese": "2",
 "robinul": "2"}, "u": {"uretron": "2",
 "urimax": "2",
 "unicap with iron": "2",
 "utira": "2",
 "utrona-c": "2",
 "udamin": "2",
 "utrona": "2",
 "ultra mylanta calci tabs": "1",
 "upcal d": "1",
 "unicap senior": "2",
 "urban ds": "1",
 "unisom sleepmelts": "2",
 "uni-tann": "2",
 "uritact ds": "2",
 "uni-lan ii": "1",
 "uro-mag": "1",
 "urimar-t": "2",
 "urotrol": "2",
 "ultra-natal": "2",
 "urised": "2",
 "uta": "2",
 "ultra natalcare": "2",
 "urapine": "2",
 "unicomplex m": "2",
 "univasc": "2",
 "uni-fac zx": "2",
 "urisedamine": "2",
 "urban": "1",
 "uni-lan": "1",
 "ultimatecare one": "2",
 "uretron ds": "2",
 "utira-c": "2",
 "unisom sleepgels": "2",
 "udamin sp": "2",
 "uni serp": "2",
 "uritin": "2",
 "urelief plus": "2",
 "uni-tann cs": "2",
 "usept": "2",
 "urispas": "2",
 "uni-daily plus iron": "2",
 "urisym": "2",
 "ultimatecare combo": "2",
 "uni kar plus c sr": "2",
 "urogesic blue": "2",
 "unipres": "2",
 "uro blue": "2",
 "uritact-ec": "2",
 "uticap": "2",
 "unisom with pain relief": "2",
 "uroxatral": "2",
 "ultimatecare one nf": "2",
 "unicap t": "2",
 "uni-thera m with beta carotene": "2",
 "ustell": "2",
 "uni-tann d": "2",
 "urelle": "2",
 "unicap m": "2",
 "ultimatecare advance": "2",
 "uprima": "2",
 "uribel": "2",
 "uniretic": "2"}, "t": {"tenex": "2",
 "toprol-xl": "2",
 "telmisartan": "2",
 "tizanidine": "2",
 "tekral": "2",
 "theraflu warming relief nighttime severe cold &amp; cough": "2",
 "terazosin": "2",
 "titralac plus liquid": "1",
 "tolterodine": "2",
 "theracal d4000": "2",
 "tussigon": "2",
 "tozal": "2",
 "tocilizumab": "2",
 "tylenol pm": "2",
 "titralac plus": "1",
 "trimesis rx": "2",
 "triveen-one": "2",
 "triadvance": "2",
 "tavist nighttime allergy": "2",
 "telbivudine": "2",
 "thiethylperazine": "2",
 "trihexyphenidyl": "2",
 "teniposide": "2",
 "trospium": "2",
 "tranquil nighttime sleep aid": "2",
 "teveten hct": "2",
 "tenormin": "2",
 "thera-m enhanced": "2",
 "temaril": "2",
 "trihexane": "2",
 "tylenol sore throat nighttime": "2",
 "theralith xr": "2",
 "theravim m": "2",
 "therobec plus": "2",
 "tranxene": "2",
 "tums regular strength": "1",
 "theragran hematinic": "2",
 "tranxene sd": "2",
 "trandolapril/verapamil": "2",
 "trimagen": "2",
 "theraflu warming relief sinus &amp; cold": "2",
 "t-lite": "2",
 "tenoretic": "2",
 "taron-prx plus dha": "2",
 "transderm-scop": "2",
 "trinsicon": "2",
 "triaminic night time cold &amp; cough": "2",
 "twilite": "2",
 "tolcapone": "1",
 "thioridazine": "2",
 "trifluoperazine": "2",
 "torsemide": "2",
 "teveten": "2",
 "tums dual action": "1",
 "twynsta": "2",
 "trichlormethiazide": "2",
 "triazolam": "2",
 "tinidazole": "2",
 "tasmar": "1",
 "tab-a-vite maximum": "2",
 "tenoretic 50": "2",
 "thalitone": "2",
 "tricare dha one": "2",
 "tandem ob": "2",
 "trigels f": "2",
 "trandate": "2",
 "tiazac": "2",
 "tempo": "1",
 "torecan": "2",
 "tricare": "2",
 "tofranil-pm": "1",
 "tetrabenazine": "2",
 "trihemic 600": "2",
 "timolide": "2",
 "total allergy": "2",
 "tylenol allergy complete nighttime": "2",
 "trimagen fa": "2",
 "thalomid": "2",
 "trecator": "2",
 "tranylcypromine": "3",
 "taxol": "2",
 "tums ultra 1000": "1",
 "t-gran plus minerals": "2",
 "temazepam": "2",
 "tri vites with fluoride and iron": "2",
 "tylenol plus children's cold &amp; allergy": "2",
 "tricon": "2",
 "tri-vi-sol with iron": "2",
 "thorazine": "2",
 "thiothixene": "2",
 "timolol": "2",
 "tyzeka": "2",
 "titralac": "1",
 "tl icon": "2",
 "theracal rapid repletion": "2",
 "trycet": "3",
 "tl g-fol os": "2",
 "tl-fol 500": "2",
 "trimipramine": "1",
 "tums freshers": "1",
 "ternamar": "2",
 "trandolapril": "2",
 "tums smoothies": "1",
 "theracal d2000": "2",
 "taxotere": "2",
 "tenoretic 100": "2",
 "thera-vite m": "2",
 "tranxene t-tab": "2",
 "triflupromazine": "2",
 "tolfrinic": "2",
 "triavil": "2",
 "theraflu thin strips multi symptom": "2",
 "tekturna hct": "2",
 "trimeprazine": "2",
 "tandem": "2",
 "trac tabs 2x": "2",
 "triamterene": "2",
 "timolide 10-25": "2",
 "tekamlo": "2",
 "trecator-sc": "2",
 "tandem dha": "2",
 "tums plus": "1",
 "tab-a-vite weightslim": "2",
 "taron forte": "2",
 "theraflu warming relief flu &amp; sore throat": "2",
 "theraflu nighttime severe cold &amp; cough": "2",
 "therems m": "2",
 "tandem f": "2",
 "therems h": "2",
 "trinatal rx": "2",
 "taron-c dha": "2",
 "tofranil": "1",
 "tri rx": "2",
 "tarka": "2",
 "taron-bc": "2",
 "trimagen forte": "2",
 "theragran-m": "2",
 "tri-vi-flor with iron": "2",
 "tri-hydroserpine": "2",
 "theragener-m": "2",
 "tandem plus": "2",
 "thera hematinic": "2",
 "theragener-h": "2",
 "trilafon": "2",
 "tab-a-vite womens formula": "2",
 "theraflu thin strips nighttime cold and cough": "2",
 "tab-a-vite with iron": "2",
 "tums kids": "1",
 "therapeutic-m": "2",
 "triall": "2",
 "tylenol severe allergy": "2",
 "tussinate": "2",
 "taztia xt": "2",
 "triferex 150 forte": "2",
 "triaminic thin strips night time cold &amp; cough": "2",
 "tusstat": "2",
 "tribenzor": "2",
 "time-hist qd": "2",
 "tums extra strength 750": "1",
 "toposar": "2",
 "trinate": "2",
 "taron-ec calc dha pack": "2",
 "triveen-prx rnf": "2",
 "tamsulosin": "2",
 "trihexy": "2",
 "teczem": "2",
 "thalidomide": "2",
 "trux-adryl": "2",
 "tacaryl": "2",
 "thera-m": "2",
 "triaminic thin strips cough &amp; runny nose": "2",
 "tindamax": "2",
 "tylenol allergy multi-symptom nighttime": "2",
 "trimethaphan camsylate": "2",
 "triaminic thin strips allergy": "2"}, "w": {"wellbutrin xl": "2",
 "we allergy": "2",
 "wellbutrin sr": "2",
 "womens pack": "2",
 "wal-nadol pm extra strength": "2",
 "wytensin": "2",
 "wygesic": "3",
 "wellesse liquid calcium with vitamin d": "1",
 "wellbutrin": "2"}, "v": {"vi-daylin adc with iron": "2",
 "vitalize plus": "2",
 "versed": "2",
 "vinate advanced": "2",
 "verotin-by": "2",
 "viactiv multi-vitamin": "2",
 "vi-zac": "2",
 "vitaplex plus": "2",
 "vigortol liquid": "2",
 "vi-atro": "2",
 "v-gan-50": "2",
 "venatal fa": "2",
 "visrx dose pack": "2",
 "vumon": "2",
 "valu-dryl": "2",
 "viactiv calcium flavor glides": "2",
 "vi-daylin with iron": "2",
 "vinate care": "2",
 "vitelle irospan": "2",
 "vinate good start": "2",
 "vesicare": "2",
 "vepesid": "2",
 "vincristine": "2",
 "vi-daylin/f adc with iron": "2",
 "vaseretic": "2",
 "videx ec": "2",
 "vinate az extra": "2",
 "vitamin b6": "2",
 "valturna": "2",
 "vinate ic": "2",
 "vytorin": "2",
 "vinate ii": "2",
 "videx": "2",
 "vita-pms": "2",
 "valsartan": "2",
 "vitaspire": "2",
 "vinate ultra": "2",
 "vinate 90": "2",
 "vitafol-ob+dha": "2",
 "verelan pm": "2",
 "vasotec": "2",
 "vitaphil": "2",
 "vitelle nestabs otc": "2",
 "vynatal fa": "2",
 "vanatrip": "1",
 "vol-nate": "2",
 "vicon forte": "2",
 "velcade": "2",
 "vitanatal ob plus dha": "2",
 "valium": "2",
 "vi-stress with iron": "2",
 "vincasar pfs": "2",
 "vitamax": "2",
 "valrelease": "2",
 "vaseretic 10-25": "2",
 "vinatal forte": "2",
 "vinate iii": "2",
 "visken": "2",
 "vivactil": "1",
 "vital-d": "2",
 "vaseretic 5-12.5": "2",
 "vitaphil plus dha": "2",
 "vitamed prenatal formula": "2",
 "vemavite prx 2": "2",
 "vinorelbine": "2",
 "vitagen forte": "2",
 "vol-plus": "2",
 "verelan": "2",
 "vitaphil aide": "2",
 "vitafol pn": "2",
 "vita-zinc": "2",
 "vita drops with iron": "2",
 "vita zx": "2",
 "vinacal or": "2",
 "vitron-c": "2",
 "viactiv soft calcium chews": "2",
 "vernate": "2",
 "vi-daylin with iron chewable": "2",
 "v-gan-25": "2",
 "vita-dec": "2",
 "vicon plus": "2",
 "vita-pms plus": "2",
 "vinate pn care": "2",
 "vitatrum": "2",
 "vernate advanced": "2",
 "vimar with iron": "2",
 "vicap forte": "2",
 "vitagen advance": "2",
 "vinate one": "2",
 "vitafol-ob": "2",
 "vinblastine": "2",
 "viva dha": "2",
 "vicon-c": "2",
 "vol-tab rx": "2",
 "vita-min rx": "2",
 "vitatab mv": "2",
 "vynatal 1 plus 1": "2",
 "vica-forte": "2",
 "vinate az": "2",
 "v-c forte": "2",
 "vi-daylin/f plus iron": "2",
 "vita s forte": "2",
 "vinate c": "2",
 "vitacon forte": "2",
 "vinate m": "2",
 "vitafol": "2",
 "vinate calcium": "2",
 "vi-daylin with iron drops": "2",
 "velban": "2",
 "verapamil": "2",
 "vitron-c-plus": "2",
 "viactiv multi-vitamin flavor glides": "2",
 "vinate gt": "2",
 "viogen-c": "2",
 "verotin-gr": "2",
 "vinatal 600": "2"}, "y": {"yervoy": "2",
 "yodoxin": "2",
 "yieronia": "2"}, "x": {"xanax xr": "2",
 "xanax": "2",
 "xiral sr": "2",
 "xalkori": "2",
 "xyrem": "3",
 "xenazine": "2"}, "z": {"zinc plus lozenges": "2",
 "zafirlukast": "2",
 "zatean-pn dha": "2",
 "zenate prenatal": "2",
 "zitamin": "2",
 "zalcitabine": "2",
 "zatean-pn": "2",
 "zocor": "2",
 "zyvox": "3",
 "zestoretic": "2",
 "z-gen": "2",
 "zenate advanced formula": "2",
 "zyprexa zydis": "2",
 "zebeta": "2",
 "zatean-pn plus": "2",
 "ziprasidone": "2",
 "ze-plus": "2",
 "zyprexa intramuscular": "2",
 "zerit": "2",
 "zegerid otc": "1",
 "zincvit": "2",
 "z-bec": "2",
 "zerit xr": "2",
 "zyban": "2",
 "zaponex": "2",
 "zelapar": "2",
 "zanaflex": "2",
 "zegerid": "1",
 "zatean-ch": "2",
 "zyprexa": "2",
 "zenate": "2",
 "zestril": "2",
 "zaroxolyn": "2",
 "zyprexa relprevv": "2",
 "zetran": "2",
 "ziac": "2",
 "zodeac-100": "2"}}];