interactions["cefoxitin,mefoxin"]=["cefoxitin,mefoxin", {"a": {"alimta": "2",
 "alyacen 7/7/7": "2",
 "amethia": "2",
 "altavera": "2",
 "amikacin": "2",
 "apri": "2",
 "amethia lo": "2",
 "amersham indium (111in) oxine": "2",
 "amikin pediatric": "2",
 "amethyst": "2",
 "alesse-21": "2",
 "ampicillin/probenecid": "1",
 "alesse": "2",
 "aviane": "2",
 "amikin": "2",
 "azurette": "2",
 "alesse-28": "2",
 "anisindione": "2",
 "aranelle": "2",
 "alyacen 1/35": "2"}, "c": {"camreselo": "2",
 "cesia": "2",
 "cyclafem 7/7/7": "2",
 "cholecalciferol/genistein/zinc chelazome": "1",
 "chloromycetin": "1",
 "cryselle": "2",
 "colchicine/probenecid": "1",
 "cholecalciferol/genistein/zinc glycinate": "1",
 "chloromycetin sodium succinate": "1",
 "caziant": "2",
 "chloramphenicol": "1",
 "cidomycin": "2",
 "cellcept": "2",
 "cyclafem 1/35": "2",
 "coumadin": "2",
 "chloracol": "1",
 "camrese": "2",
 "cyclessa": "2"}, "b": {"brevicon": "2",
 "beyaz": "2",
 "baraclude": "2",
 "briellyn": "2",
 "balziva": "2",
 "bumex": "2",
 "benemid": "1",
 "bumetanide": "2"}, "e": {"ethinyl estradiol/norelgestromin": "2",
 "ethinyl estradiol/norgestrel": "2",
 "ethinyl estradiol": "2",
 "enpresse": "2",
 "ethacrynic acid": "2",
 "ethinyl estradiol/norethindrone": "2",
 "ethinyl estradiol/etonogestrel": "2",
 "ethinyl estradiol/ethynodiol": "2",
 "entecavir": "2",
 "edecrin": "2",
 "emoquette": "2",
 "estinyl": "2",
 "ethinyl estradiol/levonorgestrel": "2",
 "estrostep fe": "2",
 "ethinyl estradiol/norgestimate": "2"}, "d": {"demulen 1/35": "2",
 "desogen": "2",
 "dasetta 1/35": "2",
 "demulen 1/50": "2",
 "diaqua-2": "2",
 "desogestrel/ethinyl estradiol": "2",
 "demadex iv": "2",
 "drospirenone/ethinyl estradiol": "2",
 "dasetta 7/7/7": "2",
 "demulen": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "dicumarol": "2",
 "demadex": "2",
 "dasetta": "2"}, "g": {"gianvi": "2",
 "generess fe": "2",
 "gildess fe 1.5/30": "2",
 "genora 1/35": "2",
 "genora 1/50": "2",
 "gentamicin": "2",
 "gildess fe 1/20": "2",
 "garamycin": "2",
 "genora 0.5/35": "2"}, "f": {"fosteum": "1",
 "femcon fe": "2",
 "furosemide": "2",
 "femhrt": "2"}, "i": {"introvale": "2",
 "indium oxyquinoline in-111": "2"}, "h": {"heparin": "1",
 "heparin sodium": "1"}, "k": {"kanamycin": "2",
 "kantrex": "2",
 "kariva": "2",
 "kelnor 1/35": "2"}, "j": {"jolessa": "2",
 "junel 1.5/30": "2",
 "jenest": "2",
 "jinteli": "2",
 "junel 1/20": "2",
 "jantoven": "2",
 "jevantique": "2",
 "junel fe 1/20": "2",
 "junel fe 1.5/30": "2"}, "m": {"modicon": "2",
 "myzilra": "2",
 "marlissa": "2",
 "mestranol/norethindrone": "2",
 "min-ovral 28": "2",
 "mycophenolic acid": "2",
 "min-ovral 21": "2",
 "microgestin fe 1.5/30": "2",
 "myfortic": "2",
 "microgestin 1.5/30": "2",
 "mycophenolate mofetil": "2",
 "mircette": "2",
 "microgestin 1/20": "2",
 "mononessa": "2",
 "microgestin fe 1/20": "2",
 "mycifradin": "2",
 "miradon": "2"}, "l": {"loestrin fe 1.5/30": "2",
 "lybrel": "2",
 "lo loestrin fe": "2",
 "loestrin fe 1/20": "2",
 "lutera": "2",
 "lasix": "2",
 "lessina": "2",
 "loryna": "2",
 "leena": "2",
 "levonest": "2",
 "loestrin 1/20": "2",
 "lo/ovral-28": "2",
 "levora": "2",
 "low-ogestrel-21": "2",
 "lo-aqua": "2",
 "low-ogestrel-28": "2",
 "levlite": "2",
 "loseasonique": "2",
 "loestrin 21 1.5/30": "2",
 "lo/ovral": "2",
 "loestrin 21 1/20": "2",
 "levlen": "2",
 "loestrin 24 fe": "2"}, "o": {"ovcon 50": "2",
 "ortho tri-cyclen lo": "2",
 "ortho-novum 7/7/7": "2",
 "orsythia": "2",
 "ortho evra": "2",
 "ovcon 35": "2",
 "ortho-cept": "2",
 "ocella": "2",
 "ogestrel-28": "2",
 "ovcon 35 fe": "2",
 "ortho tri-cyclen": "2",
 "ortho-novum 1/50": "2",
 "ortho-novum 1/35": "2",
 "ortho-novum 10/11": "2",
 "ovral-28": "2",
 "ortho cyclen": "2",
 "ovral": "2",
 "ogestrel": "2"}, "n": {"nebcin": "2",
 "norethin 1/35 e": "2",
 "nuvaring": "2",
 "neo-fradin": "2",
 "necon 0.5/35": "2",
 "norethin 1/50 m": "2",
 "nortrel 0.5/35": "2",
 "necon 10/11": "2",
 "neomycin": "2",
 "necon 1/35": "2",
 "nebcin pediatric": "2",
 "necon 7/7/7": "2",
 "necon 1/50": "2",
 "nelova 10/11": "2",
 "nimodipine": "2",
 "netromycin": "2",
 "nordette-28": "2",
 "netilmicin": "2",
 "nordette-21": "2",
 "norinyl 1+35": "2",
 "nimotop": "2",
 "norinyl 1+50": "2",
 "nelova 0.5/35": "2",
 "nordette": "2",
 "nortrel 7/7/7": "2",
 "nelova 1/35": "2",
 "nortrel 1/35": "2",
 "nelova 1/50 m": "2",
 "neo-tab": "2"}, "q": {"quasense": "2"}, "p": {"portia": "2",
 "previfem": "2",
 "philith": "2",
 "proben-c": "1",
 "probenecid": "1",
 "probenecid and colchicine": "1",
 "preven ec": "2",
 "pemetrexed": "2"}, "s": {"sodium edecrin": "2",
 "syeda": "2",
 "sronyx": "2",
 "seasonique": "2",
 "safyral": "2",
 "solia": "2",
 "septopal": "2",
 "seasonale": "2",
 "sprintec": "2",
 "streptomycin": "2"}, "r": {"reclipsen": "2"}, "t": {"tri-sprintec": "2",
 "trivora": "2",
 "trinessa lo": "2",
 "tri-previfem": "2",
 "trinessa": "2",
 "tobramycin": "2",
 "triquilar 28": "2",
 "tri-legest": "2",
 "triphasil": "2",
 "tilia fe": "2",
 "tri-legest fe": "2",
 "typhoid vaccine, live": "2",
 "tri-levlen": "2",
 "triquilar 21": "2",
 "trivora-28": "2",
 "triphasil-28": "2",
 "tri-norinyl": "2",
 "tobi": "2",
 "torsemide": "2",
 "triphasil-21": "2",
 "tri-lo-sprintec": "2"}, "w": {"warfarin": "2"}, "v": {"vestura": "2",
 "velivet": "2",
 "vivotif berna": "2",
 "vivotif berna vaccine": "2"}, "y": {"yasmin": "2",
 "yaz": "2"}, "z": {"zenchent fe": "2",
 "zovia": "2",
 "zovia 1/50": "2",
 "zenchent": "2",
 "zeosa": "2",
 "zarah": "2",
 "zovia 1/35": "2"}}];