interactions["certolizumab"]=["certolizumab", {"a": {"adriamycin rdf": "3",
 "accolate": "2",
 "a-hydrocort": "3",
 "alkeran": "3",
 "anti-thymocyte globulin": "3",
 "afinitor": "3",
 "aristocort": "3",
 "adriamycin": "3",
 "acthib with dpt (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "atorvastatin": "2",
 "atgam (lymphocyte immune globulin, anti-thy (equine))": "3",
 "aristopak": "3",
 "arzerra": "3",
 "aqua gem-e": "1",
 "aurothioglucose": "2",
 "aqua-e": "1",
 "aplisol": "2",
 "aralen hydrochloride": "2",
 "abraxane": "3",
 "acth": "3",
 "arava": "3",
 "alefacept": "2",
 "acthrel": "3",
 "advicor": "2",
 "azathioprine": "3",
 "adrucil": "3",
 "adrenocot": "3",
 "adrenocot la": "3",
 "asparaginase escherichia coli": "3",
 "acam2000": "3",
 "adlone-40": "3",
 "acthib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "altocor": "2",
 "adcetris": "3",
 "afluria": "2",
 "azasan": "3",
 "altoprev": "2",
 "apresoline": "2",
 "atamet": "2",
 "azacitidine": "3",
 "acthar": "3",
 "adlone-80": "3",
 "actemra": "3",
 "arcalyst": "3",
 "apresazide": "2",
 "arranon": "3",
 "aristospan": "3",
 "adacel": "2",
 "aplitest": "2",
 "a-methapred": "3",
 "acetocot": "3",
 "adalimumab": "3",
 "auranofin": "2",
 "aralen phosphate": "2",
 "abacavir/lamivudine/zidovudine": "3",
 "antabuse": "2",
 "aquasol e": "1",
 "aurolate": "2",
 "altretamine": "3",
 "agriflu": "2",
 "abatacept": "3",
 "attenuvax": "3",
 "adbeon": "3",
 "aralen": "2",
 "amlodipine/atorvastatin": "2",
 "anthrax vaccine adsorbed": "2",
 "aristocort for injection": "3",
 "amiodarone": "2",
 "azmacort": "3",
 "aspirin/pravastatin": "2",
 "alemtuzumab": "2",
 "alimta": "3",
 "aquavite-e": "1",
 "anakinra": "3",
 "amevive": "2",
 "amino-opti-e": "1",
 "aldesleukin": "3",
 "adriamycin pfs": "3",
 "alpha e": "1"}, "c": {"caduet": "2",
 "cerubidine": "3",
 "cervarix": "2",
 "cisplatin": "3",
 "cholecalciferol/genistein/zinc chelazome": "1",
 "cortone acetate": "3",
 "cytarabine": "3",
 "chloromycetin sodium succinate": "2",
 "colchicine/probenecid": "2",
 "cerivastatin": "2",
 "cyclophosphamide": "3",
 "chloramphenicol": "2",
 "cosyntropin": "3",
 "cholecalciferol/genistein/zinc glycinate": "1",
 "cat's claw": "1",
 "cellcept": "3",
 "cordarone": "2",
 "canakinumab": "3",
 "celestone": "3",
 "cytoxan": "3",
 "cordarone iv": "2",
 "clozapine synthon": "3",
 "cytoxan lyophilized": "3",
 "colchicine": "2",
 "chloromycetin": "2",
 "cortrosyn": "3",
 "chlorambucil": "3",
 "combivir": "3",
 "cosmegen": "3",
 "camptosar": "3",
 "carbidopa/entacapone/levodopa": "2",
 "colocort": "3",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/zinc sulfate": "1",
 "cholera vaccine": "2",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/selenium/zinc sulfate": "1",
 "cladribine novaplus": "3",
 "cytovene": "3",
 "cotolone": "3",
 "cladribine": "3",
 "capecitabine": "3",
 "cortisone": "3",
 "chloroquine": "2",
 "cortifoam": "3",
 "chromic chloride hexahydrate/copper sulfate/manganese sulfate/selenium/sodium iodide/zinc sulfate": "1",
 "clofarabine": "3",
 "colcrys": "2",
 "cabazitaxel": "3",
 "cytosar-u": "3",
 "carboplatin novaplus": "3",
 "carboplatin": "3",
 "clinalog": "3",
 "comvax (haemophilus b conjugate (prp-omp) vaccine/hepatitis b pediatric vaccine)": "2",
 "carbidopa/levodopa": "2",
 "clinacort": "3",
 "coccidioidin skin test": "2",
 "clozaril": "3",
 "candin": "2",
 "cort-k": "3",
 "conte-pak-4": "1",
 "corticotropin": "3",
 "cyclosporine": "3",
 "celestone phosphate": "3",
 "corticorelin": "3",
 "cell-u-jec": "3",
 "cortef": "3",
 "candida albicans extract": "2",
 "candida skin test": "2",
 "carmustine": "3",
 "clozapine": "3",
 "cortenema": "3",
 "clopine": "3",
 "centrum singles-vitamin e": "1",
 "crizotinib": "2",
 "ceenu": "3",
 "cytosar": "3",
 "crestor": "2",
 "clolar": "3",
 "chloracol": "2",
 "celestone soluspan": "3",
 "campath": "2"}, "b": {"bexxar dosimetric": "3",
 "bortezomib": "2",
 "basiliximab": "3",
 "bexxartherapeutic": "3",
 "beta-phos/ac": "3",
 "bioflavonoids/zinc glycinate": "1",
 "busulfan": "3",
 "busulfex": "3",
 "biothrax": "2",
 "belatacept": "3",
 "budesonide/formoterol": "3",
 "brentuximab": "3",
 "benlysta": "3",
 "bidil": "2",
 "bleomycin": "3",
 "blenoxane": "3",
 "budesonide": "3",
 "belimumab": "3",
 "bexxar": "3",
 "betamethasone": "3",
 "boostrix": "2",
 "biavax ii": "3",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "bendamustine": "3",
 "baycol": "2",
 "bexarotene": "3",
 "bcg": "3",
 "bubbli-pred": "3",
 "baycadron": "3",
 "bicnu": "3"}, "e": {"e-gems": "1",
 "eribulin": "3",
 "e-600": "1",
 "epirubicin": "3",
 "e-400 clear": "1",
 "entocort ec": "3",
 "echinacea": "1",
 "eloxatin": "3",
 "ethambutol": "2",
 "ergamisol": "3",
 "etravirine": "2",
 "engerix-b": "2",
 "elspar": "3",
 "etanercept": "3",
 "efalizumab": "2",
 "etoposide": "3",
 "ezetimibe/simvastatin": "2",
 "everolimus": "3",
 "e pherol": "1",
 "enbrel": "3",
 "engerix-b pediatric": "2",
 "ethionamide": "2",
 "ellence": "3",
 "etopophos": "3"}, "d": {"dexamethasone/lidocaine": "3",
 "dexasone": "3",
 "dacogen": "3",
 "dalalone la": "3",
 "diquinol": "2",
 "dexone la": "3",
 "dexacen-4": "3",
 "daptacel": "2",
 "daunorubicin": "3",
 "dexamethasone intensol": "3",
 "diphtheria and tetanus toxoids/pertussis, acellular": "2",
 "doxorubicin liposomal": "3",
 "decadron-la": "3",
 "diphtheria toxoid/hepatitis b pediatric vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "diphtheria toxoid/tetanus toxoid": "2",
 "decavac": "2",
 "dexone": "3",
 "didanosine": "2",
 "diphtheria toxoid/haemophilus b conjugate": "2",
 "delta-cortef": "3",
 "dexpak taperpak": "3",
 "dexacorten": "3",
 "dexacort phosphate in turbinaire": "3",
 "dep medalone 80": "3",
 "doxil": "3",
 "daclizumab": "3",
 "diuretic ap-es": "2",
 "daunoxome": "3",
 "denosumab": "2",
 "deferiprone": "3",
 "diphtheria-tetanus toxoids, pediatric": "2",
 "dexamethasone": "3",
 "dexasone la": "3",
 "decadron": "3",
 "dasatinib": "3",
 "decaject la": "3",
 "deltasone": "3",
 "diphtheria toxoid/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid": "2",
 "dryvax": "3",
 "dactinomycin": "3",
 "duralone": "3",
 "dexacort-la": "3",
 "docefrez": "3",
 "depoject-80": "3",
 "decadron phosphate, injectable": "3",
 "dtic-dome": "3",
 "disulfiram": "2",
 "docetaxel": "3",
 "depo-medrol": "3",
 "droxia": "3",
 "daunorubicin liposomal": "3",
 "dalalone": "3",
 "diphtheria toxoid/pertussis, whole cell/tetanus toxoid": "2",
 "de-sone la": "3",
 "decadron with xylocaine": "3",
 "dacarbazine": "3",
 "depmedalone": "3",
 "diphtheria toxoid/pertussis, acellular/tetanus toxoid": "2",
 "doxorubicin": "3",
 "dexacort phosphate in respihaler": "3",
 "denileukin diftitox": "3",
 "depopred": "3",
 "dopar": "2",
 "dapsone": "2",
 "decitabine": "3",
 "dalalone dp": "3",
 "denzapine": "3",
 "decaject": "3"}, "g": {"gilenya": "3",
 "gemzar": "3",
 "gemcitabine": "3",
 "gliadel": "3",
 "gengraf": "3",
 "galzin": "1",
 "golimumab": "3",
 "ganciclovir": "3",
 "gold sodium thiomalate": "2",
 "gleevec": "3",
 "gardasil": "2",
 "gemtuzumab": "3"}, "f": {"fingolimod": "3",
 "fluzone intradermal": "2",
 "fludarabine": "3",
 "folex pfs": "3",
 "flagyl iv": "2",
 "fazaclo": "3",
 "flagyl 375": "2",
 "flushield": "2",
 "flagyl": "2",
 "florinef acetate": "3",
 "ferriprox": "3",
 "fluvirin": "2",
 "florinef": "3",
 "floxuridine": "3",
 "flulaval": "2",
 "flagyl er": "2",
 "fluzone high-dose": "2",
 "flo-pred": "3",
 "fluvastatin": "2",
 "fluorouracil": "3",
 "flumist": "3",
 "fludara": "3",
 "fludrocortisone": "3",
 "fasigyn": "2",
 "fluogen": "2",
 "fluarix": "2",
 "fudr": "3",
 "furadantin": "2",
 "folotyn": "3",
 "fluzone": "2",
 "fosteum": "1"}, "i": {"interferon alfacon-1": "2",
 "intron a": "2",
 "influenza virus vaccine, h1n1, live": "3",
 "iodine i 131 tositumomab": "3",
 "idamycin pfs": "3",
 "ipol": "2",
 "imatinib": "3",
 "idamycin": "3",
 "in-111 zevalin": "3",
 "interferon alfa-n1": "2",
 "ixempra": "3",
 "intelence": "2",
 "isoniazid": "2",
 "ifex": "3",
 "infliximab": "3",
 "influenza virus vaccine, live, trivalent": "3",
 "ixiaro": "2",
 "infergen": "2",
 "ifosfamide": "3",
 "influenza virus vaccine, inactivated": "2",
 "imuran": "3",
 "istodax": "3",
 "isoniazid/rifampin": "2",
 "ixabepilone": "3",
 "influenza virus vaccine, h1n1, inactivated": "2",
 "isonarif": "2",
 "interferon alfa-2b": "2",
 "interferon alfa-2a": "2",
 "iodoquinol": "2",
 "ifosfamide/mesna": "3",
 "ilaris": "3",
 "ibritumomab": "3",
 "ipilimumab": "2",
 "idarubicin": "3",
 "irinotecan": "3",
 "imovax rabies": "2",
 "interferon alfa-2b/ribavirin": "2",
 "ifex/mesnex": "3",
 "infanrix": "2",
 "isoniazid/pyrazinamide/rifampin": "2"}, "h": {"hydeltrasol": "3",
 "hepatitis a pediatric vaccine": "2",
 "histolyn-cyl": "2",
 "hhr": "2",
 "helidac": "2",
 "human papillomavirus vaccine": "2",
 "histoplasmin diluted": "2",
 "hydrocortisone": "3",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrocortone phosphate": "3",
 "hydrap-es": "2",
 "havrix pediatric": "2",
 "haemophilus b conjugate": "2",
 "hibtiter (haemophilus b conjugate (hboc) vaccine)": "2",
 "hydrocortone": "3",
 "hydroxyurea": "3",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hepatitis b adult vaccine": "2",
 "hexalen": "3",
 "hydeltra-tba": "3",
 "hepatitis b pediatric vaccine": "2",
 "histoplasmin": "2",
 "h.p. acthar gel": "3",
 "hydrea": "3",
 "hepatitis a adult vaccine/hepatitis b adult vaccine": "2",
 "hivid": "2",
 "hepatitis a adult vaccine": "2",
 "halaven": "3",
 "hydra-zide": "2",
 "hydroxychloroquine": "2",
 "hiberix (haemophilus b conjugate (prp-t) vaccine)": "2",
 "havrix": "2",
 "hycamtin": "3",
 "humira": "3",
 "hydralazine": "2",
 "hydralazine/isosorbide dinitrate": "2",
 "herceptin": "3",
 "hexadrol": "3",
 "hydralazine plus": "2"}, "k": {"key-pred": "3",
 "kenalog-10": "3",
 "kineret": "3",
 "kenalog-40": "3",
 "key-pred sp": "3",
 "ken-jec 40": "3",
 "kinrix": "2",
 "kenaject-40": "3"}, "j": {"jakafi": "3",
 "juvisync": "2",
 "je-vax": "2",
 "japanese encephalitis virus vaccine nakayama": "2",
 "japanese encephalitis virus vaccine sa14-14-2": "2",
 "jevtana": "3"}, "m": {"measles virus vaccine/mumps virus vaccine/rubella virus vaccine/varicella virus vaccine": "3",
 "measles virus vaccine": "3",
 "medrol dosepak": "3",
 "meticorten": "3",
 "msta mumps skin test antigen": "2",
 "myambutol": "2",
 "methacort 40": "3",
 "melphalan": "3",
 "myleran": "3",
 "mumpsvax": "3",
 "mono-vacc test": "2",
 "methylcotolone": "3",
 "menveo": "2",
 "millipred dp": "3",
 "methacort 80": "3",
 "mithracin": "3",
 "medicort": "3",
 "mutamycin": "3",
 "mitomycin": "3",
 "metryl": "2",
 "methylcotol": "3",
 "mte-6": "1",
 "mte-7": "1",
 "mte-4": "1",
 "mte-5": "1",
 "macrobid": "2",
 "measles virus vaccine/mumps virus vaccine/rubella virus vaccine": "3",
 "multiple trace element neonatal": "1",
 "methylprednisolone": "3",
 "multe-pak-4": "1",
 "multe-pak-5": "1",
 "menomune": "2",
 "millipred": "3",
 "methotrexate": "3",
 "muromonab-cd3": "3",
 "medralone 40": "3",
 "med-jec-40": "3",
 "mevacor": "2",
 "mumps virus vaccine/rubella virus vaccine": "3",
 "mylocel": "3",
 "medrol": "3",
 "mar-zinc": "1",
 "multitrace-4 pediatric": "1",
 "multitrace-4 concentrate": "1",
 "myochrysine": "2",
 "mixed respiratory vaccine": "2",
 "meningococcal polysaccharide vaccine": "2",
 "mylotarg": "3",
 "metro": "2",
 "methylpred dp": "3",
 "montelukast": "2",
 "medidex la": "3",
 "multiple trace element": "1",
 "mumps skin test antigen": "2",
 "myfortic": "3",
 "menomune a/c/y/w-135": "2",
 "meningococcal conjugate vaccine": "2",
 "metronidazole": "2",
 "multitrace-4 neonatal": "1",
 "mustargen": "3",
 "meruvax ii": "3",
 "matulane": "3",
 "multitrace-5 concentrate": "1",
 "mte-4 concentrated": "1",
 "measles virus vaccine/rubella virus vaccine": "3",
 "mycophenolic acid": "3",
 "medralone": "3",
 "medipred": "3",
 "m-prednisolone": "3",
 "medralone 80": "3",
 "methotrexate lpf sodium": "3",
 "micro-zn": "1",
 "metro iv": "2",
 "multitrace-5": "1",
 "multitrace-4": "1",
 "mycophenolate mofetil": "3",
 "mte-5 concentrated": "1",
 "mumps virus vaccine": "3",
 "mechlorethamine": "3",
 "macrodantin": "2",
 "mercaptopurine": "3",
 "m-m-r ii": "3",
 "menactra": "2",
 "m-r-vax ii": "3",
 "multitest cmi": "2",
 "medidex": "3",
 "mrv": "2",
 "mitoxantrone": "3",
 "methylprednisolone dose pack": "3",
 "marpres": "2"}, "l": {"livalo": "2",
 "lamivudine/zidovudine": "3",
 "levamisole": "3",
 "larodopa": "2",
 "lymerix": "2",
 "lomustine": "3",
 "lyme disease vaccine": "2",
 "liquid pred": "3",
 "lescol": "2",
 "lymphocyte immune globulin, anti-thy": "3",
 "limbrel 250": "1",
 "leustatin": "3",
 "lovastatin/niacin": "2",
 "leflunomide": "3",
 "lovastatin": "2",
 "linezolid": "3",
 "liquid pedvaxhib (haemophilus b conjugate (prp-omp) vaccine)": "2",
 "lipitor": "2",
 "lenalidomide": "3",
 "leukeran": "3",
 "limbrel 500": "1",
 "levodopa": "2",
 "lescol xl": "2"}, "o": {"orasone": "3",
 "ofatumumab": "3",
 "orencia": "3",
 "ontak": "3",
 "orthoclone okt3": "3",
 "orazinc": "1",
 "oforta": "3",
 "orapred odt": "3",
 "orimune": "3",
 "oxaliplatin": "3",
 "oncovin": "3",
 "onxol": "3",
 "orapred": "3"}, "n": {"novantrone": "3",
 "nilotinib": "3",
 "nulojix": "3",
 "nitro macro": "2",
 "niacin/simvastatin": "2",
 "nelarabine": "3",
 "nydrazid": "2",
 "neutrexin": "3",
 "neosar": "3",
 "natalizumab": "3",
 "navelbine": "3",
 "nitrofurantoin": "2",
 "nutr-e-sol": "1",
 "neotrace-4": "1",
 "neoral": "3",
 "nipent": "3",
 "nexterone": "2"}, "q": {"quineprox": "2"}, "p": {"pentostatin": "3",
 "pedtrace-4": "1",
 "purinethol": "3",
 "paclitaxel protein-bound": "3",
 "pitavastatin": "2",
 "predicort-50": "3",
 "pneumovax 23": "2",
 "poliovirus vaccine, live, trivalent": "3",
 "parcopa": "2",
 "prolia": "2",
 "peginterferon alfa-2a": "2",
 "peginterferon alfa-2b": "2",
 "prograf": "3",
 "pedte-pak-4": "1",
 "pravigard pac": "2",
 "pneumococcal 7-valent vaccine": "2",
 "primaquine": "3",
 "pedvaxhib (haemophilus b conjugate (prp-t) vaccine)": "2",
 "pulmicort flexhaler": "3",
 "pralatrexate": "3",
 "paraplatin": "3",
 "predicort rp": "3",
 "pulmicort respules": "3",
 "primethasone": "3",
 "pravastatin": "2",
 "pegintron": "2",
 "proben-c": "2",
 "predaject-50": "3",
 "pneumococcal 23-polyvalent vaccine": "2",
 "pneumococcal 13-valent vaccine": "2",
 "pred-ject-50": "3",
 "pulmicort turbuhaler": "3",
 "pharmorubicin rdf": "3",
 "pulmicort nebuamp": "3",
 "phytase/zinc citrate": "1",
 "predcor": "3",
 "plague vaccine": "2",
 "predacorten": "3",
 "prednicen-m": "3",
 "platinol": "3",
 "prednisolone": "3",
 "prednisone": "3",
 "pravachol": "2",
 "procanbid": "3",
 "prednicot": "3",
 "provenge": "2",
 "procan sr": "3",
 "pte-5": "1",
 "pte-4": "1",
 "plaquenil": "2",
 "probenecid and colchicine": "2",
 "proleukin": "3",
 "pri-cortin 50": "3",
 "poliovirus vaccine, inactivated": "2",
 "pemetrexed": "3",
 "predalone 50": "3",
 "prevnar": "2",
 "proquad": "3",
 "pediarix": "2",
 "pylera": "2",
 "prelone": "3",
 "paclitaxel": "3",
 "procarbazine": "3",
 "protostat": "2",
 "pacerone": "2",
 "prevnar 13": "2",
 "pentacel (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/poliovirus vaccine, inactivated/tetanus toxoid)": "2",
 "plicamycin": "3",
 "platinol-aq": "3",
 "pronestyl-sr": "3",
 "pegasys": "2",
 "pronestyl": "3",
 "pediapred": "3",
 "procainamide": "3",
 "predacort 50": "3",
 "predate-50": "3",
 "pharmorubicin pfs": "3"}, "s": {"sandimmune": "3",
 "staphage lysate": "2",
 "singulair": "2",
 "stelara": "3",
 "solu-medrol": "3",
 "streptozocin": "3",
 "stalevo 150": "2",
 "sipuleucel-t": "2",
 "sprycel": "3",
 "solu-cortef": "3",
 "simvastatin/sitagliptin": "2",
 "symbicort": "3",
 "solurex": "3",
 "simponi": "3",
 "smallpox vaccine": "3",
 "sirolimus": "3",
 "sterapred ds": "3",
 "serpazide": "2",
 "sinemet cr": "2",
 "serathide": "2",
 "simvastatin": "2",
 "stalevo 50": "2",
 "stalevo 125": "2",
 "stalevo 75": "2",
 "ser-ap-es": "2",
 "stalevo": "2",
 "stavudine": "2",
 "stalevo 100": "2",
 "simcor": "2",
 "solurex la": "3",
 "solganal": "2",
 "spherulin": "2",
 "stalevo 200": "2",
 "simulect": "3",
 "sinemet": "2",
 "selestoject": "3",
 "skin test antigens, multiple": "2",
 "serpex": "2",
 "sylatron": "2",
 "sclavo test-ppd": "2",
 "sterapred": "3"}, "r": {"rheumatrex dose pack": "3",
 "rituxan": "3",
 "recombivax hb dialysis formulation": "2",
 "rebetron": "2",
 "rotateq": "3",
 "revlimid": "3",
 "recombivax hb adult": "2",
 "retrovir": "3",
 "raptiva": "2",
 "rifater": "2",
 "rotashield": "3",
 "roferon-a": "2",
 "rubella virus vaccine": "3",
 "rabies vaccine, human diploid cell": "2",
 "red yeast rice": "2",
 "rosuvastatin": "2",
 "rotavirus vaccine": "3",
 "ruxolitinib": "3",
 "rapamune": "3",
 "rotarix": "3",
 "rifamate": "2",
 "rabavert": "2",
 "rituximab": "3",
 "ridaura": "2",
 "rilonacept": "3",
 "recombivax hb pediatric/adolescent": "2",
 "recombivax hb": "2",
 "romidepsin": "3",
 "rabies vaccine, purified chick embryo cell": "2",
 "remicade": "3"}, "u": {"u-tri-lone": "3",
 "uni serp": "2",
 "uracil mustard": "3",
 "unipres": "2",
 "ustekinumab": "3"}, "t": {"tripedia": "2",
 "trilog": "3",
 "trihibit (diphtheria toxoid/haemophilus b conjugate (prp-t) vaccine/pertussis, acellular/tetanus toxoid)": "2",
 "tasigna": "3",
 "tyzeka": "2",
 "trizivir": "3",
 "tetanus toxoid adsorbed": "2",
 "treanda": "3",
 "thymoglobulin (anti-thymocyte globulin (rabbit))": "3",
 "thioguanine": "3",
 "tuberculin tine test": "2",
 "tramacort-d": "3",
 "trastuzumab": "3",
 "temozolomide": "3",
 "tositumomab": "3",
 "tri-hydroserpine": "2",
 "taxol": "3",
 "tubersol": "2",
 "tuberculin purified protein derivative": "2",
 "triam-a": "3",
 "tabloid": "3",
 "tetanus toxoid": "2",
 "thiotepa": "3",
 "tinidazole": "2",
 "taxotere": "3",
 "theracys": "3",
 "tristoject": "3",
 "tetanus toxoid for booster use only": "2",
 "tice bcg": "3",
 "typhoid vaccine, inactivated": "2",
 "trichophyton allergenic extracts": "2",
 "telbivudine": "2",
 "te anatoxal berna": "2",
 "triamcinolone": "3",
 "trilone": "3",
 "teniposide": "3",
 "tetramune (diphtheria toxoid/haemophilus b conjugate (hboc) vaccine/pertussis, whole cell/tetanus toxoid)": "2",
 "trichophyton skin test": "2",
 "tarabine pfs": "3",
 "toposar": "3",
 "twinrix": "2",
 "targretin": "3",
 "tysabri": "3",
 "trecator-sc": "2",
 "typhim vi": "2",
 "trace metals": "1",
 "tac 3": "3",
 "triam-forte": "3",
 "thalidomide": "3",
 "thalomid": "3",
 "trimetrexate": "3",
 "trecator": "2",
 "torisel": "3",
 "triamcot": "3",
 "tacrolimus": "3",
 "topotecan": "3",
 "tocilizumab": "3",
 "thioplex": "3",
 "tindamax": "2",
 "trexall": "3",
 "tice bcg vaccine": "3",
 "typhoid vaccine, live": "3",
 "triamonide 40": "3",
 "tetanus-diphtheria toxoids, adult": "2",
 "temodar": "3",
 "temsirolimus": "3"}, "v": {"videx": "2",
 "valcyte": "3",
 "vinblastine": "3",
 "varicella virus vaccine": "3",
 "vumon": "3",
 "vitamin e": "1",
 "vaqta pediatric": "2",
 "velban": "3",
 "varivax": "3",
 "vinorelbine": "3",
 "valganciclovir": "3",
 "verazinc": "1",
 "vidaza": "3",
 "vivotif berna": "3",
 "vita-plus e natural": "1",
 "velcade": "2",
 "veripred 20": "3",
 "vepesid": "3",
 "vincristine": "3",
 "vincasar pfs": "3",
 "vivotif berna vaccine": "3",
 "vaqta": "2",
 "videx ec": "2",
 "vytorin": "2"}, "y": {"yervoy": "2",
 "yellow fever vaccine": "3",
 "y-90 zevalin": "3",
 "yf-vax": "3",
 "yodoxin": "2"}, "x": {"xalkori": "2",
 "xeloda": "3",
 "xgeva": "2"}, "z": {"zostavax": "3",
 "zinca-pak": "1",
 "zinc chloride": "1",
 "zafirlukast": "2",
 "zinc 50 mg pink": "1",
 "zinc acetate": "1",
 "zocor": "2",
 "zyvox": "3",
 "zema pak": "3",
 "zoster vaccine live": "3",
 "zinc-220": "1",
 "zincate": "1",
 "zidovudine": "3",
 "zanosar": "3",
 "zinc gluconate": "1",
 "zerit": "2",
 "zinc sulfate": "1",
 "zerit xr": "2",
 "zortress": "3",
 "zinc cr": "1",
 "zaponex": "3",
 "zytaze": "1",
 "zenapax": "3",
 "zevalin": "3",
 "zalcitabine": "2"}}];