interactions["chenodeoxycholic-acid"]=["chenodeoxycholic-acid", {"a": {"aldroxicon i": "2",
 "almacone": "2",
 "atripla": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "aluminum hydroxide": "2",
 "aquest": "2",
 "apri": "2",
 "alu-tab": "2",
 "aerodiol": "2",
 "alamag plus": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "2",
 "avonex prefilled syringe": "2",
 "angeliq": "2",
 "adgyn estro": "2",
 "alenic alka tablet": "2",
 "alyacen 1/35": "2",
 "aspir-mox ib": "2",
 "arava": "3",
 "acid gone extra strength": "2",
 "altavera": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "aluminum carbonate": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "acid gone antacid": "2",
 "alesse": "2",
 "aspir-mox": "2",
 "alora": "2",
 "alternagel": "2",
 "acid gone": "2",
 "ascriptin": "2",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "activella": "2",
 "avonex": "2",
 "acid relief": "2",
 "antara": "2",
 "amethia lo": "2",
 "aldroxicon ii": "2",
 "amethyst": "2",
 "amphojel": "2",
 "alyacen 7/7/7": "2",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "2",
 "alenic alka": "2",
 "ascriptin maximum strength": "2",
 "azurette": "2",
 "alamag": "2",
 "amethia": "2",
 "aloh-gel": "2",
 "aspirin buffered": "2",
 "almacone-2": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "aluminum hydroxide/mineral oil": "2",
 "atromid-s": "2",
 "aranelle": "2",
 "arthritis pain formula": "2",
 "alesse-21": "2",
 "aviane": "2",
 "alu-cap": "2",
 "alesse-28": "2",
 "anisindione": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2"}, "c": {"cyclafem 7/7/7": "2",
 "climara pro": "2",
 "climaval": "2",
 "colesevelam": "2",
 "conjugated estrogens/meprobamate": "2",
 "conjugated estrogens/methyltestosterone": "2",
 "cenestin": "2",
 "conjugated estrogens": "2",
 "carafate": "2",
 "conjugated estrogens/medroxyprogesterone": "2",
 "cyclessa": "2",
 "cholestyramine light": "2",
 "cholestyramine": "2",
 "covaryx": "2",
 "covaryx hs": "2",
 "colestid flavored": "2",
 "combipatch": "2",
 "colestipol": "2",
 "camreselo": "2",
 "conjugated estrogens topical": "2",
 "clofarabine": "2",
 "cryselle": "2",
 "chlorotrianisene": "2",
 "colestid": "2",
 "cyclafem 1/35": "2",
 "camrese": "2",
 "cesia": "2",
 "clinagen la 40": "2",
 "caziant": "2",
 "climodien": "2",
 "clofibrate": "2",
 "climara": "2",
 "coumadin": "2",
 "clolar": "2"}, "b": {"basaljel": "2",
 "beyaz": "2",
 "balziva": "2",
 "black cohosh": "2",
 "bedol": "2",
 "briellyn": "2",
 "betaseron": "2",
 "brevicon": "2"}, "e": {"estrofem": "2",
 "estra-v 40": "2",
 "estratest h.s.": "2",
 "estrogel": "2",
 "evorel": "2",
 "estragyn la 5": "2",
 "ethinyl estradiol/norgestrel": "2",
 "estrace": "2",
 "enjuvia": "2",
 "estradiol g gam": "2",
 "emoquette": "2",
 "estinyl": "2",
 "ezetimibe": "2",
 "elleste solo": "2",
 "ethinyl estradiol": "2",
 "ethinyl estradiol/norelgestromin": "2",
 "extavia": "2",
 "eemt hs": "2",
 "estradiol/norethindrone topical": "2",
 "estradot 100": "2",
 "estradiol/medroxyprogesterone": "2",
 "enpresse": "2",
 "estradiol topical": "2",
 "ethinyl estradiol/levonorgestrel": "2",
 "esterified estrogens/methyltestosterone": "2",
 "estro-cyp": "2",
 "estrace vaginal cream": "2",
 "evamist": "2",
 "estradiol": "2",
 "essian h.s.": "2",
 "estrapatch": "2",
 "ethinyl estradiol/ethynodiol": "2",
 "essian": "2",
 "estropipate topical": "2",
 "ethinyl estradiol/norgestimate": "2",
 "estro-a": "2",
 "estreva": "2",
 "estradot 37.5": "2",
 "estradiol/testosterone": "2",
 "eemt ds": "2",
 "estradot": "2",
 "efavirenz/emtricitabine/tenofovir": "2",
 "estrone": "2",
 "estratest": "2",
 "ethinyl estradiol/norethindrone": "2",
 "estragyn 5": "2",
 "ethinyl estradiol/etonogestrel": "2",
 "estradiol patch": "2",
 "estring": "2",
 "elestrin": "2",
 "estrogen patches": "2",
 "embeda": "2",
 "estro-span 40": "2",
 "estra-c": "2",
 "estra-testrin": "2",
 "estrostep fe": "2",
 "estropipate": "2",
 "estraderm": "2",
 "eemt": "2",
 "estrone aq": "2",
 "estradot 75": "2",
 "estradiol/norgestimate": "2",
 "estradiol/levonorgestrel": "2",
 "estradiol/norethindrone": "2",
 "estro-la": "2",
 "estradot 50": "2",
 "efavirenz": "2",
 "estrasorb": "2",
 "esterified estrogens": "2",
 "ezetimibe/simvastatin": "2",
 "estratab": "2",
 "esclim": "2"}, "d": {"dura-dumone": "2",
 "duragen": "2",
 "drospirenone/ethinyl estradiol": "2",
 "dihydroxyaluminum sodium carbonate": "2",
 "depogen": "2",
 "delidose": "2",
 "di-gel": "2",
 "dermestril": "2",
 "desogen": "2",
 "dasetta 1/35": "2",
 "delestrogen": "2",
 "dermestril septem": "2",
 "dura-estrin": "2",
 "depade": "2",
 "demulen": "2",
 "drospirenone/ethinyl estradiol/levomefolate calcium": "2",
 "dicumarol": "2",
 "divigel": "2",
 "drospirenone/estradiol": "2",
 "duratestrin": "2",
 "demulen 1/35": "2",
 "demulen 1/50": "2",
 "desogestrel/ethinyl estradiol": "2",
 "delatestadiol": "2",
 "dialume": "2",
 "dioval 40": "2",
 "dienogest/estradiol": "2",
 "dep androgyn": "2",
 "depotestogen": "2",
 "diethylstilbestrol": "2",
 "dienestrol topical": "2",
 "duo-cyp": "2",
 "dasetta 7/7/7": "2",
 "dioval xx": "2",
 "depo-estradiol": "2",
 "dep gynogen": "2",
 "depo-testadiol": "2",
 "dasetta": "2"}, "g": {"gelusil": "2",
 "gaviscon-2": "2",
 "generess fe": "2",
 "genora 1/35": "2",
 "gianvi": "2",
 "gynodiol": "2",
 "genaton chewable": "2",
 "genaton": "2",
 "genora 1/50": "2",
 "gildess fe 1.5/30": "2",
 "gaviscon regular strength tablets": "2",
 "genora 0.5/35": "2",
 "gildess fe 1/20": "2",
 "gynogen la 20": "2",
 "gaviscon extra strength tablets": "2",
 "gaviscon regular strength liquid": "2",
 "gaviscon extra relief formula": "2",
 "gemfibrozil": "2",
 "gaviscon extra strength liquid": "2"}, "f": {"femtran": "2",
 "femring": "2",
 "first mouthwash blm": "2",
 "femtab": "2",
 "femsept": "2",
 "femseven": "2",
 "fenofibrate": "2",
 "femseven sequi phase i": "2",
 "femtrace": "2",
 "femhrt": "2",
 "fibricor": "2",
 "fenoglide": "2",
 "folex pfs": "2",
 "femcon fe": "2",
 "fematrix": "2",
 "fempatch": "2",
 "fenofibric acid": "2"}, "i": {"iosopan": "2",
 "interferon beta-1a": "2",
 "interferon beta-1b": "2",
 "introvale": "2"}, "h": {"heartburn antacid extra strength": "2"}, "k": {"kelnor 1/35": "2",
 "kaolin/pectin": "2",
 "kariva": "2",
 "k-c suspension": "2",
 "kaodene nn suspension": "2",
 "kestrone 5": "2",
 "kaolin": "2",
 "kapectolin": "2",
 "kao-spen": "2"}, "j": {"jolessa": "2",
 "junel 1.5/30": "2",
 "jenest": "2",
 "jinteli": "2",
 "junel 1/20": "2",
 "jantoven": "2",
 "jevantique": "2",
 "junel fe 1/20": "2",
 "junel fe 1.5/30": "2"}, "m": {"menogen": "2",
 "mylagen": "2",
 "mylanta": "2",
 "mylagen-ii": "2",
 "mintox plus": "2",
 "menorest patch": "2",
 "maalox": "2",
 "modicon": "2",
 "medidiol 10": "2",
 "milantex": "2",
 "morphine/naltrexone": "2",
 "min-ovral 21": "2",
 "methotrexate": "2",
 "methotrexate lpf sodium": "2",
 "mononessa": "2",
 "miradon": "2",
 "maoson": "2",
 "maalox advanced maximum strength": "2",
 "marlissa": "2",
 "mintox maximum strength": "2",
 "mestranol/norethindrone": "2",
 "min-ovral 28": "2",
 "mylanta ultimate strength": "2",
 "magaant": "2",
 "mi-acid ii": "2",
 "maalox plus": "2",
 "mylanta ds fast acting": "2",
 "maalox max": "2",
 "magaldrate plus suspension": "2",
 "microgestin 1/20": "2",
 "mimvey": "2",
 "magaldrate": "2",
 "mintox extra strength": "2",
 "myzilra": "2",
 "menorest": "2",
 "maldroxal": "2",
 "maalox antacid antigas regular strength": "2",
 "masanti ds": "2",
 "mintox": "2",
 "mylanta maximum strength": "2",
 "menaval-20": "2",
 "microgestin 1.5/30": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "menogen hs": "2",
 "maalox advanced regular strength": "2",
 "maalox max wild berry": "2",
 "milantex maximum strength": "2",
 "menopause support": "2",
 "maldroxal plus": "2",
 "microgestin fe 1/20": "2",
 "masanti": "2",
 "mintox tablets": "2",
 "magaldrate/simethicone": "2",
 "mylanta fast acting": "2",
 "microgestin fe 1.5/30": "2",
 "menostar": "2",
 "menest": "2",
 "mircette": "2",
 "maalox hrf": "2",
 "magnaprin": "2",
 "maalox tc": "2",
 "mi-acid": "2"}, "l": {"losospan plus": "2",
 "lofibra": "2",
 "loestrin fe 1.5/30": "2",
 "lybrel": "2",
 "lipofen": "2",
 "lipidil ez": "2",
 "lowsium plus": "2",
 "lo loestrin fe": "2",
 "loestrin fe 1/20": "2",
 "locholest": "2",
 "losospan": "2",
 "lunelle": "2",
 "lutera": "2",
 "leflunomide": "3",
 "lipidil micro": "2",
 "lessina": "2",
 "lipidil supra": "2",
 "locholest light": "2",
 "lopid": "2",
 "leena": "2",
 "levonest": "2",
 "loestrin 1/20": "2",
 "lowsium": "2",
 "lo/ovral": "2",
 "levora": "2",
 "low-ogestrel-21": "2",
 "lorelco": "2",
 "low-ogestrel-28": "2",
 "levlite": "2",
 "loryna": "2",
 "loseasonique": "2",
 "loestrin 21 1.5/30": "2",
 "lo/ovral-28": "2",
 "loestrin 21 1/20": "2",
 "levlen": "2",
 "loestrin 24 fe": "2"}, "o": {"ortho-prefest": "2",
 "organon oestradiol": "2",
 "oestrodose": "2",
 "ogen 1.25": "2",
 "ogestrel-28": "2",
 "ortho-novum 1/50": "2",
 "ortho-novum 1/35": "2",
 "oestrogel pump-pack": "2",
 "ortho-novum 7/7/7": "2",
 "ortho evra": "2",
 "ogen 0.625": "2",
 "oestrogel": "2",
 "ogen vaginal cream": "2",
 "ortho-est": "2",
 "ogen 2.5": "2",
 "oestradiol implants": "2",
 "ortho tri-cyclen": "2",
 "ocella": "2",
 "ovcon 35 fe": "2",
 "ortho dienestrol": "2",
 "ortho-novum 10/11": "2",
 "oromone": "2",
 "ogestrel": "2",
 "ortho tri-cyclen lo": "2",
 "ogen": "2",
 "orsythia": "2",
 "ovcon 35": "2",
 "ortho-cept": "2",
 "oesclim": "2",
 "ovcon 50": "2",
 "ovral-28": "2",
 "ortho cyclen": "2",
 "ovral": "2"}, "n": {"norethin 1/35 e": "2",
 "nuvaring": "2",
 "necon 0.5/35": "2",
 "norethin 1/50 m": "2",
 "nortrel 0.5/35": "2",
 "necon 10/11": "2",
 "naltrexone": "2",
 "necon 1/35": "2",
 "natazia": "2",
 "necon 7/7/7": "2",
 "necon 1/50": "2",
 "nelova 10/11": "2",
 "nuvelle ts phase i": "2",
 "nordette-28": "2",
 "nephrox": "2",
 "nordette-21": "2",
 "norinyl 1+35": "2",
 "norinyl 1+50": "2",
 "nelova 0.5/35": "2",
 "nordette": "2",
 "nortrel 7/7/7": "2",
 "nelova 1/35": "2",
 "nortrel 1/35": "2",
 "nelova 1/50 m": "2"}, "q": {"questran light": "2",
 "questran": "2",
 "quinestrol": "2",
 "quasense": "2"}, "p": {"portia": "2",
 "premarin": "2",
 "progynova": "2",
 "philith": "2",
 "premphase": "2",
 "prevalite": "2",
 "primogyn depot": "2",
 "provames": "2",
 "probucol": "2",
 "prefest": "2",
 "preven ec": "2",
 "pmb": "2",
 "previfem": "2",
 "prempro": "2",
 "premphase 14/14": "2",
 "premarin vaginal": "2",
 "premarin intravenous": "2",
 "progynova ts": "2"}, "s": {"sronyx": "2",
 "stilphostrol": "2",
 "syeda": "2",
 "syntest hs": "2",
 "syntest ds": "2",
 "synthetic conjugated estrogens a": "2",
 "seasonique": "2",
 "safyral": "2",
 "solia": "2",
 "sustiva": "2",
 "sucralfate": "2",
 "seasonale": "2",
 "systen": "2",
 "sprintec": "2",
 "sandrena": "2"}, "r": {"rheumatrex dose pack": "2",
 "rulox plus": "2",
 "ri-mag": "2",
 "revia": "2",
 "riopan plus double strength": "2",
 "riopan plus": "2",
 "rebif": "2",
 "rulox 1": "2",
 "riopan": "2",
 "ron-acid plus": "2",
 "riopan plus 2": "2",
 "ron acid": "2",
 "reclipsen": "2",
 "rulox": "2"}, "u": {"urban": "2",
 "uni-lan": "2",
 "uni-lan ii": "2",
 "urban ds": "2"}, "t": {"trivora": "2",
 "tilia fe": "2",
 "triglide": "2",
 "tri-previfem": "2",
 "tabloid": "2",
 "trinessa": "2",
 "trexall": "2",
 "tace": "2",
 "tri-sprintec": "2",
 "tri-legest fe": "2",
 "tri-norinyl": "2",
 "triquilar 28": "2",
 "triquilar 21": "2",
 "tempo": "2",
 "tri-legest": "2",
 "triphasil": "2",
 "trinessa lo": "2",
 "tricor": "2",
 "thaissept": "2",
 "thais": "2",
 "thioguanine": "2",
 "tri-levlen": "2",
 "trivora-28": "2",
 "triphasil-28": "2",
 "trilipix": "2",
 "triphasil-21": "2",
 "tri-lo-sprintec": "2"}, "w": {"welchol": "2",
 "warfarin": "2"}, "v": {"valertest no 1": "2",
 "vivelle-dot": "2",
 "velivet": "2",
 "valergen": "2",
 "vagifem": "2",
 "vestura": "2",
 "vytorin": "2",
 "vivelle": "2",
 "vivitrol": "2"}, "y": {"yasmin": "2",
 "yaz": "2"}, "z": {"zumenon": "2",
 "zenchent fe": "2",
 "zetia": "2",
 "zovia": "2",
 "zovia 1/50": "2",
 "zenchent": "2",
 "zeosa": "2",
 "zarah": "2",
 "zovia 1/35": "2"}}];