interactions["chloroquine,aralen"]=["chloroquine,aralen", {"a": {"azithromycin dose pack": "2",
 "aluminum hydroxide": "2",
 "aldroxicon i": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "2",
 "aloxi": "2",
 "ampicillin": "2",
 "aricept": "1",
 "adenocard": "2",
 "amitriptyline/chlordiazepoxide": "2",
 "altocor": "2",
 "alu-tab": "2",
 "aspir-mox": "2",
 "amitriptyline": "2",
 "accesspak for hiv pep expanded with kaletra": "2",
 "ambenyl": "2",
 "alcalak": "2",
 "allfen cdx": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "arranon": "2",
 "adgan": "2",
 "amitriptyline/perphenazine": "2",
 "amphojel": "2",
 "agalsidase beta": "3",
 "aspirin buffered": "2",
 "aricept odt": "1",
 "abarelix": "2",
 "amlodipine/atorvastatin": "2",
 "aurolate": "3",
 "arthritis pain formula": "2",
 "aspirin/pravastatin": "2",
 "acetaminophen/chlorpheniramine/codeine": "2",
 "atomoxetine": "2",
 "anhydrous calcium iodide/codeine": "2",
 "adriamycin rdf": "2",
 "accuretic": "2",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "albuterol/ipratropium": "2",
 "adriamycin": "2",
 "asenapine": "2",
 "acebutolol": "1",
 "aurothioglucose": "3",
 "acetaminophen/codeine/guaifenesin/phenylephrine": "2",
 "antinaus 50": "2",
 "abraxane": "2",
 "arava": "2",
 "acid reducer + antacid dual action": "2",
 "advicor": "2",
 "anergan 50": "2",
 "acid gone antacid": "2",
 "acid gone": "2",
 "altoprev": "2",
 "accupril": "2",
 "apresoline": "2",
 "acetaminophen/chlorpheniramine/codeine/phenylephrine": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "accuneb": "2",
 "actemra": "2",
 "albuterol": "2",
 "aspirin/caffeine/propoxyphene": "2",
 "aldroxicon ii": "2",
 "amitone": "2",
 "arcapta": "2",
 "adalimumab": "2",
 "apo-go pen": "2",
 "alka-mints": "2",
 "almacone-2": "2",
 "advair hfa": "2",
 "aluminum hydroxide/mineral oil": "2",
 "asendin": "2",
 "arformoterol": "2",
 "allfen cd": "2",
 "apomorphine": "2",
 "adriamycin pfs": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2",
 "accolate": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "alfuzosin": "2",
 "astemizole": "2",
 "abilify": "2",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "alenic alka tablet": "2",
 "anectine flo-pack": "1",
 "actonel with calcium": "2",
 "advair diskus": "2",
 "aspir-mox ib": "2",
 "acid gone extra strength": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "ami-lac": "2",
 "apokyn": "2",
 "adapin": "2",
 "atamet": "2",
 "artemether/lumefantrine": "3",
 "acetaminophen/codeine": "2",
 "ampicillin/sulbactam": "2",
 "amoxicillin/clarithromycin/lansoprazole": "2",
 "alkums": "2",
 "aspirin/carisoprodol/codeine": "2",
 "adcetris": "2",
 "ascriptin": "2",
 "alphen expectorant": "2",
 "ari sodium iodide (i123) 1-12 mbq": "2",
 "allerfrin with codeine": "2",
 "aspirin/calcium carbonate": "2",
 "apresazide": "2",
 "anafranil": "2",
 "ammonium chloride/chlorpheniramine/codeine/phenylephrine": "2",
 "aplenzin": "3",
 "apo-go": "2",
 "aceta w/ codeine": "2",
 "ambophen": "2",
 "acetaminophen/codeine/guaifenesin/pseudoephedrine": "2",
 "alternagel": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "ambifed-g cd": "2",
 "ampicillin/probenecid": "2",
 "atrosept": "1",
 "aripiprazole": "2",
 "adenosine": "2",
 "alu-cap": "2",
 "azithromycin": "2",
 "airacof": "2",
 "arsenic trioxide": "3",
 "almacone": "2",
 "aldurazyme": "1",
 "amoxapine": "2",
 "acetaminophen/propoxyphene": "2",
 "alamag": "2",
 "alamag plus": "2",
 "atorvastatin": "2",
 "ari sodium iodide (i123) 100-750 mbq": "2",
 "azithromycin/trovafloxacin": "2",
 "ambifed-g cdx": "2",
 "anhydrous calcium iodide/isoproterenol": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "adeno-jec": "2",
 "adenoscan": "2",
 "avelox i.v.": "3",
 "aventyl hydrochloride": "2",
 "acetaminophen/tramadol": "3",
 "alkets": "2",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "2",
 "anzemet": "3",
 "aspirin/codeine": "2",
 "airet": "2",
 "amiodarone": "3",
 "auranofin": "3",
 "alenic alka": "2",
 "abacavir/lamivudine/zidovudine": "2",
 "antabuse": "2",
 "aloh-gel": "2",
 "avelox": "3",
 "ala-hist ac": "2",
 "ambifed cd": "2",
 "atracurium": "1",
 "alupent": "2",
 "ascriptin maximum strength": "2",
 "anectine": "1",
 "abilify discmelt": "2",
 "ambifed cdx": "2"}, "c": {"calcitab": "2",
 "codeine/dexchlorpheniramine/phenylephrine": "2",
 "cisplatin": "2",
 "calcium carbonate/risedronate": "2",
 "colchicine/probenecid": "2",
 "colcrys": "2",
 "chemdal expectorant": "2",
 "chlorpheniramine/codeine/phenylephrine/potassium iodide": "2",
 "combigan": "2",
 "cerivastatin": "2",
 "calcium carbonate/fluoride": "2",
 "calcidrine": "2",
 "cascara sagrada/magnesium hydroxide": "2",
 "calcarb with d": "2",
 "cotab ax": "2",
 "codeine/pseudoephedrine": "2",
 "cipro i.v.": "2",
 "citracal regular": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "calcium carbonate/cholecalciferol/ferrous fumarate": "2",
 "citalopram": "3",
 "cabazitaxel": "2",
 "cotrim": "1",
 "carbidopa/levodopa": "2",
 "calcium oyster shell": "2",
 "celecoxib": "2",
 "co-histine expectorant": "2",
 "cheracol with codeine": "2",
 "calcid": "2",
 "cheratussin dac": "2",
 "chlorcyclizine/codeine/pseudoephedrine": "2",
 "chloromycetin sodium succinate": "2",
 "clozapine": "3",
 "clopine": "3",
 "capital w/codeine": "2",
 "codeine/guaifenesin/pseudoephedrine": "2",
 "cheratussin ac": "2",
 "cisapride": "3",
 "caduet": "2",
 "citracal regular 250 mg + d": "2",
 "cocet plus": "2",
 "cordarone": "3",
 "cyclosporine": "2",
 "celexa": "3",
 "cipro": "2",
 "codafen": "2",
 "citracal + d": "2",
 "codeine/promethazine": "2",
 "codafed": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "calcium carbonate/simethicone": "2",
 "caltrate colon health": "2",
 "crizotinib": "3",
 "compazine spansule": "2",
 "codegest expectorant": "2",
 "carbidopa/entacapone/levodopa": "2",
 "cycofed pediatric expectorant": "2",
 "coreg cr": "1",
 "citracal calcium gummies": "2",
 "combivir": "2",
 "cerubidine": "2",
 "caprelsa": "3",
 "colrex": "2",
 "calcio del mar": "2",
 "carboplatin": "2",
 "citracal maximum": "2",
 "complera": "2",
 "clarithromycin": "2",
 "clozaril": "3",
 "codeine/pseudoephedrine/triprolidine": "2",
 "cipro xr": "2",
 "caltrate 600+d": "2",
 "cotabflu": "2",
 "codeine/dexbrompheniramine/pseudoephedrine": "2",
 "clozapine synthon": "3",
 "chlorcyclizine/codeine": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "cipro cystitis pack": "2",
 "certolizumab": "2",
 "calcium carbonate/magnesium carbonate": "2",
 "cuprimine": "2",
 "cotrim ds": "1",
 "capital with codeine suspension": "2",
 "compro": "2",
 "codeine/guaifenesin/phenylephrine": "2",
 "codeine/phenylephrine/pyrilamine": "2",
 "cosopt": "2",
 "co-histine dh": "2",
 "cotrim pediatric": "1",
 "chlorcyclizine/codeine/phenylephrine": "2",
 "cycofed expectorant": "2",
 "codeine/phenylephrine": "2",
 "colrex compound": "2",
 "combivent": "2",
 "calcitrate with d": "2",
 "cisatracurium": "1",
 "cordarone iv": "3",
 "ciprofloxacin": "2",
 "caltrate 600 with d plus soy": "2",
 "colchicine": "2",
 "corvert": "3",
 "chloromycetin": "2",
 "codehist dh": "2",
 "clomipramine": "2",
 "codahistine expectorant": "2",
 "cal-gest": "2",
 "chlorpheniramine/codeine": "2",
 "calcet": "2",
 "codeine/guaifenesin/phenylpropanolamine": "2",
 "caltro with vitamin d": "2",
 "cymbalta": "2",
 "calcium carbonate": "2",
 "cal oys": "2",
 "carboplatin novaplus": "2",
 "cyndal expectorant": "2",
 "codeine/pseudoephedrine/pyrilamine": "2",
 "carvedilol": "1",
 "chewable calcium with vitamin d": "2",
 "combivent respimat": "2",
 "codimal ph": "2",
 "codeprex": "2",
 "caltrate 600 with iron and vitamin d": "2",
 "codahistine-dh elixir": "2",
 "calci mix": "2",
 "cycofed": "2",
 "compazine": "2",
 "chloracol": "2",
 "codeine/phenylephrine/promethazine": "2",
 "codafed pediatric": "2",
 "coartem": "3",
 "citrus calcium with vitamin d": "2",
 "codeine": "2",
 "cimetidine": "2",
 "chloramphenicol": "2",
 "coreg": "1",
 "calcium oyster": "2",
 "cocet": "2",
 "cystemms-v": "1",
 "cevimeline": "2",
 "calcarb": "2",
 "codeine phosphate-promethazine hcl": "2",
 "chlorpromazine": "2",
 "calcium acetate/magnesium carbonate": "2",
 "calcium/vitamin d": "2",
 "calcium concentrate": "2",
 "codeine/pheniramine/phenylephrine/sodium citrate": "2",
 "chlorpheniramine/codeine/phenylephrine/phenylpropanolamine": "2",
 "codeine/guaifenesin": "2",
 "calvite p": "2",
 "celebrex": "2",
 "citracal plus bone density builder": "2",
 "cardioquin": "3",
 "citracal plus heart health": "2",
 "citracal slow release 1200": "2",
 "crestor": "2",
 "calcium 600 d": "2",
 "cosopt pf": "2",
 "calcium liquid softgel": "2",
 "citric acid/glucono-delta-lactone/magnesium carbonate topical": "2",
 "citracal petites": "2",
 "codeine/diphenhydramine/phenylephrine": "2",
 "chlorpheniramine/codeine/pseudoephedrine": "2",
 "caltrate gummy bites": "2",
 "cotab a": "2",
 "caltrate": "2",
 "caltro": "2",
 "calci-chew": "2",
 "conzip": "3",
 "cimzia": "2",
 "chooz": "2",
 "co-trimoxazole": "1"}, "b": {"bactrim iv": "1",
 "brovex cb": "2",
 "blocadren": "1",
 "bortezomib": "2",
 "bayer women's low dose plus calcium": "2",
 "biaxin xl": "2",
 "bitex liquid": "2",
 "brovex cbx": "2",
 "bethaprim pediatric": "1",
 "bricanyl": "2",
 "bronkometer": "2",
 "biotussin dac": "2",
 "biaxin": "2",
 "bupropion": "3",
 "budeprion": "3",
 "budesonide/formoterol": "2",
 "brethine": "2",
 "brentuximab": "2",
 "budeprion sr": "3",
 "brontex": "2",
 "betimol": "2",
 "bisacodyl/sodium biphosphate/sodium phosphate": "3",
 "brompheniramine/codeine/phenylpropanolamine": "2",
 "brovana": "2",
 "brompheniramine/codeine": "2",
 "brovex pb c": "2",
 "bidil": "2",
 "bactrim": "1",
 "bactrim pediatric": "1",
 "balacet": "2",
 "bromodiphenhydramine/codeine": "2",
 "bitolterol": "2",
 "budeprion xl": "3",
 "bronkosol": "2",
 "buproban": "3",
 "bismuth subsalicylate/metronidazole/tetracycline": "2",
 "bismuth subcitrate potassium/metronidazole/tetracycline": "2",
 "bethaprim": "1",
 "brimonidine/timolol ophthalmic": "2",
 "baycol": "2",
 "betapace af": "3",
 "bepridil": "3",
 "brethaire": "2",
 "bactrim ds": "1",
 "bilberry/evening primrose/flax": "1",
 "brovex pb cx": "2",
 "brompheniramine/codeine/phenylephrine": "2",
 "betapace": "3",
 "brompheniramine/codeine/pseudoephedrine": "2",
 "biltricide": "2"}, "e": {"endacof-ac": "2",
 "endep": "2",
 "emtricitabine/rilpivirine/tenofovir": "2",
 "ery-tab": "2",
 "eribulin": "2",
 "endacof-dc": "2",
 "evening primrose": "1",
 "enditussin expectorant": "2",
 "etrafon": "2",
 "epirubicin": "2",
 "ezogabine": "2",
 "erythrocin lactobionate": "2",
 "equilet": "2",
 "endacof-c": "2",
 "edurant": "2",
 "ez iii": "2",
 "emblon": "2",
 "extra strength mylanta calci tabs": "2",
 "e.e.s.-400": "2",
 "efasin expectorant sf": "2",
 "eryc": "2",
 "e.e.s.-400 filmtab": "2",
 "eloxatin": "2",
 "e-mycin": "2",
 "ethambutol": "2",
 "etoposide": "2",
 "evening primrose oil": "1",
 "etravirine": "2",
 "erythrocin": "2",
 "endal expectorant": "2",
 "eryped": "2",
 "emtricitabine/lopinavir/ritonavir/tenofovir": "2",
 "eskalith": "2",
 "erythromycin/sulfisoxazole": "2",
 "e.e.s. granules": "2",
 "erythrocin stearate filmtab": "2",
 "etanercept": "2",
 "ezetimibe/simvastatin": "2",
 "eskalith-cr": "2",
 "empirin with codeine": "2",
 "endal cd": "2",
 "e s p": "2",
 "e.e.s.-200": "2",
 "endotuss expectorant": "2",
 "etrafon forte": "2",
 "elavil": "2",
 "eryzole": "2",
 "enbrel": "2",
 "execlear-c": "2",
 "equaline acid reducer": "2",
 "erythrocot": "2",
 "ethionamide": "2",
 "ex-lax milk of magnesia": "2",
 "enablex": "2",
 "evoxac": "2",
 "erythromycin": "2",
 "ellence": "2",
 "etopophos": "2"}, "d": {"di-gel lemon": "2",
 "darvon compound 32": "2",
 "doxepin": "2",
 "didanosine": "2",
 "diquinol": "2",
 "docetaxel": "2",
 "dual action complete": "2",
 "daunorubicin": "2",
 "disopyramide": "3",
 "dical-d": "2",
 "di-gel": "2",
 "darvocet-n 100": "2",
 "dihistine expectorant with codeine": "2",
 "darvon-n": "2",
 "darpaz": "1",
 "detrol la": "1",
 "dofetilide": "3",
 "detrol": "1",
 "doxorubicin liposomal": "2",
 "dihistine expectorant": "2",
 "dulcolax milk of magnesia": "2",
 "dihistine": "2",
 "depen": "2",
 "dextromethorphan/promethazine": "2",
 "dimetane dc": "2",
 "definity": "2",
 "dolsed": "1",
 "dutoprol": "1",
 "daunoxome": "2",
 "degarelix": "2",
 "darcalma": "1",
 "deferiprone": "3",
 "duo-vil": "2",
 "darvon": "2",
 "dicalphos plus d": "2",
 "dialume": "2",
 "duloxetine": "2",
 "dextromethorphan/quinidine": "3",
 "demi-cof": "2",
 "dolasetron": "3",
 "dasatinib": "2",
 "darifenacin": "2",
 "disposable enema": "3",
 "darvocet a500": "2",
 "duraganidin nr": "2",
 "diabetic tussin c": "2",
 "dewees carminative": "2",
 "diflucan": "2",
 "darvon compound-65": "2",
 "desipramine": "2",
 "di-gel mint": "2",
 "dical captabs": "2",
 "diuretic ap-es": "2",
 "disulfiram": "2",
 "dihistine dh": "2",
 "dex-tuss": "2",
 "dorzolamide/timolol ophthalmic": "2",
 "daunorubicin liposomal": "2",
 "dulera": "2",
 "droperidol": "3",
 "deconsal c expectorant": "2",
 "doxil": "2",
 "droperidol/fentanyl": "3",
 "dicarbosil": "2",
 "donepezil": "1",
 "duo-medihaler": "2",
 "dolophine": "3",
 "docefrez": "2",
 "depen titratabs": "2",
 "doxorubicin": "2",
 "duoneb": "2",
 "darvocet-n 50": "2",
 "dicomal-ph": "2",
 "dopar": "2",
 "dapsone": "2",
 "dronedarone": "3",
 "decohistine dh": "2",
 "deproist with codeine": "2",
 "denzapine": "3",
 "decohistine expectorant": "2"}, "g": {"guaifen-c": "2",
 "golimumab": "2",
 "gaviscon regular strength tablets": "2",
 "ginkgo biloba": "2",
 "guaifen ac": "2",
 "guaitussin ac": "2",
 "gold sodium thiomalate": "3",
 "gaviscon regular strength liquid": "2",
 "gantanol": "1",
 "gaviscon extra strength liquid": "2",
 "gelusil": "2",
 "guiatussin dac": "2",
 "guiatuss dac": "2",
 "gengraf": "2",
 "gemifloxacin": "2",
 "guiatussin with codeine": "2",
 "genaton": "2",
 "gas-x with maalox extra strength": "2",
 "gaviscon extra relief formula": "2",
 "guaifenesin dac liquid": "2",
 "guai-co": "2",
 "gani-tuss nr": "2",
 "galantamine": "2",
 "gatifloxacin": "3",
 "gua pc": "2",
 "ginkgo": "2",
 "glydeine": "2",
 "gleevec": "2",
 "gas-x with maalox": "2",
 "guiatuss ac": "2",
 "guaiatussin dac": "2",
 "gaviscon-2": "2",
 "genox": "2",
 "geodon": "3",
 "giltuss ped-c": "2",
 "genrx tramadol": "3",
 "granisetron": "2",
 "granisol": "2",
 "guaiatussin ac": "2",
 "guaifen dac": "2",
 "gaviscon extra strength tablets": "2",
 "grepafloxacin": "3",
 "genaton chewable": "2"}, "f": {"first mouthwash blm": "2",
 "firmagon": "2",
 "fiorinal with codeine iii": "2",
 "fludarabine": "2",
 "fesoterodine": "2",
 "folex pfs": "1",
 "formoterol": "2",
 "fosrenol": "2",
 "flagyl iv": "2",
 "fleet ez-prep": "3",
 "fazaclo": "3",
 "fiorinal with codeine": "2",
 "flagyl": "2",
 "fanapt": "3",
 "fioricet with codeine": "2",
 "foradil aerolizer": "2",
 "flecainide": "2",
 "fast acting mylanta": "2",
 "fluconazole": "2",
 "flagyl er": "2",
 "fabrazyme": "3",
 "fiortal with codeine": "2",
 "flagyl 375": "2",
 "fluvastatin": "2",
 "factive": "2",
 "fleet prep kit 1": "3",
 "fleet prep kit 3": "3",
 "fleet prep kit 2": "3",
 "fludara": "2",
 "fasigyn": "2",
 "fortovase": "3",
 "fleet enema extra": "3",
 "forfivo xl": "3",
 "ferriprox": "3",
 "formoterol/mometasone": "2",
 "floricet with codeine": "2",
 "fluphenazine": "2",
 "fleet phospho soda": "3",
 "floxin": "2",
 "florical": "2",
 "fluothane": "2",
 "fluticasone/salmeterol": "2",
 "fleet enema": "3",
 "floxin iv": "2",
 "fareston": "3",
 "furadantin": "2"}, "i": {"interferon alfacon-1": "2",
 "intron a": "2",
 "isoniazid/rifampin": "2",
 "idamycin pfs": "2",
 "innopran xl": "1",
 "invega": "2",
 "ibutilide": "3",
 "invirase": "3",
 "isuprel mistometer": "2",
 "imatinib": "2",
 "istalol": "2",
 "iophen-c nr": "2",
 "isuprel": "2",
 "interferon alfa-n1": "2",
 "ixempra": "2",
 "innovar": "3",
 "inapsine": "3",
 "isoniazid": "2",
 "icar prenatal chewable calcium": "2",
 "isovue-m-200": "3",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isovue-300": "3",
 "imipramine": "2",
 "inderide la": "1",
 "iodotope": "2",
 "isovue-200": "3",
 "infliximab": "2",
 "iohexol": "3",
 "isoetharine": "2",
 "inderide": "1",
 "infergen": "2",
 "isovue-370": "3",
 "ilosone": "2",
 "inderal la": "1",
 "indacaterol": "2",
 "idamycin": "2",
 "isoproterenol": "2",
 "isuprel hcl": "2",
 "istodax": "2",
 "iopamidol-370": "3",
 "ixabepilone": "2",
 "isonarif": "2",
 "interferon alfa-2b": "2",
 "interferon alfa-2a": "2",
 "iloperidone": "3",
 "iosopan": "2",
 "iodoquinol": "2",
 "inderal": "1",
 "iophen": "2",
 "intelence": "2",
 "isovue-250": "3",
 "invega sustenna": "2",
 "ipilimumab": "2",
 "idarubicin": "2",
 "imovax rabies": "2",
 "interferon alfa-2b/ribavirin": "2",
 "iopamidol": "3",
 "isovue-128": "3",
 "isoproterenol/phenylephrine": "2",
 "isovue-m-300": "3"}, "h": {"hhr": "2",
 "haloperidol": "3",
 "halotussin dac": "2",
 "helidac": "2",
 "hyophen": "1",
 "hydroxypropyl chitosan/terbinafine topical": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrochlorothiazide/timolol": "1",
 "heartburn antacid extra strength": "2",
 "hydrap-es": "2",
 "hyoscyamine/methenamine/methylene blue/sodium biphosphate": "3",
 "hydralazine": "2",
 "hydrochlorothiazide/metoprolol": "1",
 "hyoscyamine/methenamine/methylene blue/phenyl salicylate": "1",
 "halotussin ac": "2",
 "haldol decanoate": "3",
 "hismanal": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydrochlorothiazide/propranolol": "1",
 "halothane": "2",
 "hivid": "2",
 "haley's m-o": "2",
 "halaven": "2",
 "hydra-zide": "2",
 "hydroxychloroquine": "2",
 "halfan": "3",
 "humira": "2",
 "halofantrine": "3",
 "hydralazine/isosorbide dinitrate": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydralazine plus": "2",
 "haldol": "3"}, "k": {"kaletra": "2",
 "k-c suspension": "2",
 "kaolin/pectin": "2",
 "kaodene nn suspension": "2",
 "kg-fed pediatric expectorant": "2",
 "kaolin": "2",
 "ketek": "2",
 "kg-fed expectorant": "2",
 "kapectolin": "2",
 "kytril": "2",
 "kao-spen": "2",
 "ketek pak": "2",
 "kg-fed": "2"}, "j": {"juvisync": "2",
 "jevtana": "2"}, "m": {"maalox tc": "2",
 "m-end wc": "2",
 "maxifed cdx": "2",
 "maoson": "2",
 "maalox advanced maximum strength": "2",
 "magnesium oxide": "2",
 "milantex maximum strength": "2",
 "mhp-a": "1",
 "myphetane dc": "2",
 "mi-acid ii": "2",
 "myambutol": "2",
 "methadone diskets": "3",
 "magaldrate plus suspension": "2",
 "m-phen": "2",
 "metaprel": "2",
 "magaldrate": "2",
 "monocal": "2",
 "magnesium carbonate": "2",
 "mar-cof bp": "2",
 "maalox advanced maximum strength chewable": "2",
 "maalox max wild berry": "2",
 "montelukast": "2",
 "m-clear": "2",
 "mylagen-ii": "2",
 "maggel": "2",
 "maxaquin": "2",
 "mytussin ac": "2",
 "metryl": "2",
 "multaq": "3",
 "macrobid": "2",
 "mag-200": "2",
 "mylagen": "2",
 "maalox max quick dissolve": "2",
 "maalox": "2",
 "milantex": "2",
 "magnesium hydroxide/mineral oil": "2",
 "methotrexate": "1",
 "mylanta maximum strength": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "3",
 "mevacor": "2",
 "mi-acid double strength": "2",
 "magaant": "2",
 "maxifed-g cdx": "2",
 "mintox extra strength": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "maxair": "2",
 "masanti ds": "2",
 "mag-carb": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "metoprolol": "1",
 "mefloquine": "2",
 "maalox advanced regular strength": "2",
 "mylanta ultra": "2",
 "meprozine": "2",
 "magnebind 200": "2",
 "methadose": "3",
 "metro": "2",
 "maldroxal plus": "2",
 "mylanta fast acting": "2",
 "milk of magnesia": "2",
 "macrodantin": "2",
 "maalox junior relief chewable": "2",
 "maxifed cd": "2",
 "myochrysine": "3",
 "mintox plus": "2",
 "maalox regular strength": "2",
 "metaproterenol": "2",
 "maxiflu cd": "2",
 "maxiphen cd": "2",
 "maxifed-g cd": "2",
 "mintox maximum strength": "2",
 "mylanta supreme": "2",
 "maalox plus": "2",
 "mag-ox": "2",
 "metronidazole": "2",
 "mepergan": "2",
 "mag-caps": "2",
 "msp-blu": "1",
 "maalox quick dissolve extra strength": "2",
 "medent c": "2",
 "mylanta ultimate strength": "2",
 "marblen": "2",
 "maalox children's relief": "2",
 "mylanta ds fast acting": "2",
 "m-clear wc": "2",
 "methenamine/sodium biphosphate": "3",
 "masanti": "2",
 "metoprolol succinate er": "1",
 "magnebind 300": "2",
 "maxiflu cdx": "2",
 "my-o-den": "2",
 "methylene blue": "1",
 "masanti supreme": "2",
 "magnaprin": "2",
 "mag-ox 400": "2",
 "m-end pe": "2",
 "mi-acid": "2",
 "m-end max d": "2",
 "mar-cof cg": "2",
 "mylanta": "2",
 "mellaril-s": "3",
 "myelo-kit": "3",
 "methotrimeprazine": "2",
 "maxiphen cdx": "2",
 "moxifloxacin": "3",
 "mivacurium": "1",
 "methotrexate lpf sodium": "1",
 "meperidine/promethazine": "2",
 "medihaler-iso": "2",
 "metro iv": "2",
 "metrizamide": "3",
 "mag-oxide": "2",
 "mivacron": "1",
 "maalox max": "2",
 "mytussin dac": "2",
 "methadone": "3",
 "maalox antacid antigas regular strength": "2",
 "mintox": "2",
 "mepergan fortis": "2",
 "maprotiline": "2",
 "maalox hrf": "2",
 "mellaril": "3",
 "mylanta child": "2",
 "maxair autohaler": "2",
 "mintox tablets": "2",
 "magaldrate/simethicone": "2",
 "mylanta gelcap": "2",
 "methdilazine": "2",
 "mesoridazine": "3",
 "marpres": "2"}, "l": {"losospan plus": "2",
 "ludiomil": "2",
 "livalo": "2",
 "liquihistine cs": "2",
 "lamivudine/zidovudine": "2",
 "lowsium plus": "2",
 "larodopa": "2",
 "lomefloxacin": "2",
 "lescol": "2",
 "lorelco": "2",
 "lanthanum carbonate": "2",
 "levofloxacin": "2",
 "labetalol": "1",
 "lariam": "2",
 "lithium": "2",
 "losospan": "2",
 "lindane topical": "2",
 "levomethadyl acetate": "3",
 "levatol": "1",
 "lithonate": "2",
 "leflunomide": "2",
 "lopinavir/ritonavir": "2",
 "lovastatin": "2",
 "lamisil": "2",
 "linezolid": "2",
 "laronidase": "1",
 "largon": "2",
 "levitra": "2",
 "levaquin": "2",
 "limbitrol ds": "2",
 "lowsium": "2",
 "levaquin leva-pak": "2",
 "lopressor": "1",
 "lipitor": "2",
 "lapatinib": "2",
 "lithobid": "2",
 "lovastatin/niacin": "2",
 "levodopa": "2",
 "lopressor hct": "1",
 "lescol xl": "2",
 "lithotabs": "2",
 "limbitrol": "2",
 "lexuss 210 liquid": "2",
 "levoprome": "2",
 "levalbuterol": "2"}, "o": {"omnipen-n": "2",
 "ormazine": "2",
 "oyster shell calcium 500": "2",
 "o-cal-d": "2",
 "omnipaque 240 redi-unit": "3",
 "os-cal": "2",
 "oysco 500 with d": "2",
 "oyster-d": "2",
 "oyster shell calcium with vitamin d": "2",
 "oysco d with calcium": "2",
 "omnipaque 180 redi-unit": "3",
 "os-cal 500": "2",
 "os-cal 500 + extra d": "2",
 "os-cal 500 + d": "2",
 "omnipaque 350": "3",
 "omnipaque 210": "3",
 "omnipaque 140": "3",
 "oyster cal": "2",
 "oyst cal 500": "2",
 "onxol": "2",
 "oxaliplatin": "2",
 "osmoprep": "3",
 "omnipaque 180": "3",
 "omnipen": "2",
 "oyster cal 500": "2",
 "oysco d": "2",
 "oysco 500": "2",
 "ofloxacin": "2",
 "oyster": "2",
 "orap": "3",
 "oyster shell calcium": "2",
 "oyster shell": "2",
 "omnipaque 300": "3",
 "oyst cal": "2",
 "optison": "2",
 "osteocit d plus": "2",
 "orlaam": "3",
 "omnipaque flexipak": "3",
 "oyster calcium": "2",
 "oforta": "2",
 "oystercal-d": "2",
 "oyst-cal-d": "2",
 "ondansetron": "2",
 "oncovin": "2",
 "omnipaque 240": "3"}, "n": {"norvir soft gelatin": "2",
 "naldecon-cx adult": "2",
 "nalex ac": "2",
 "nebupent": "2",
 "norpace cr": "3",
 "nortriptyline": "2",
 "nolvadex d": "2",
 "notuss-nxd": "2",
 "nitrofurantoin": "2",
 "notuss-dc": "2",
 "nasotuss": "2",
 "nuedexta": "3",
 "nucodine": "2",
 "nuco-tuss expectorant": "2",
 "notuss-pe": "2",
 "nilotinib": "3",
 "novahistine expectorant": "2",
 "norvir": "2",
 "nelarabine": "2",
 "nolvadex": "2",
 "normodyne": "1",
 "novagest with codeine": "2",
 "nucofed": "2",
 "nucodine expectorant": "2",
 "nexavar": "2",
 "nucofed pediatric expectorant": "2",
 "neo ac": "2",
 "neoral": "2",
 "nexterone": "3",
 "nephro calci": "2",
 "novadyne dh": "2",
 "nitro macro": "2",
 "norpramin": "2",
 "nucodine pediatric": "2",
 "nydrazid": "2",
 "noxafil": "2",
 "navelbine": "2",
 "novadyne expectorant": "2",
 "nuco-tuss pediatric expectorant": "2",
 "notuss-ac": "2",
 "nephrox": "2",
 "niacin/simvastatin": "2",
 "nucofed expectorant": "2",
 "notuss-nx": "2",
 "noroxin": "2",
 "norfloxacin": "2",
 "nucochem pediatric expectorant": "2",
 "nucochem expectorant": "2",
 "norisodrine with calcium iodine": "2",
 "nimbex": "1",
 "nucochem": "2",
 "norcuron": "1",
 "norpace": "3"}, "q": {"quin-release": "3",
 "quelicin": "1",
 "quinaretic": "2",
 "quinidex extentabs": "3",
 "quelicin chloride": "1",
 "quinora": "3",
 "quinidine": "3",
 "qm-260": "2",
 "quinaglute dura-tabs": "3",
 "quin-g": "3",
 "quineprox": "2",
 "quetiapine": "2",
 "quinine": "2",
 "qualaquin": "2",
 "quinapril": "2"}, "p": {"phosphasal": "1",
 "phillips' cramp-free": "2",
 "poly-tussin ac": "2",
 "probenecid and colchicine": "2",
 "poly-histine cs": "2",
 "pediazole": "2",
 "prograf": "2",
 "pseudodine c": "2",
 "proventil": "2",
 "procainamide": "3",
 "pedituss": "2",
 "proben-c": "2",
 "pancuronium": "1",
 "phenhist expectorant": "2",
 "pce dispertab": "2",
 "pharmorubicin rdf": "2",
 "phenergan vc": "2",
 "prochlorperazine": "2",
 "proair hfa": "2",
 "phenylhistine expectorant": "2",
 "phenaphen with codeine": "2",
 "pepto children's": "2",
 "prolixin": "2",
 "promethazine with dm": "2",
 "plaquenil": "2",
 "praziquantel": "2",
 "phenadoz": "2",
 "phenflu cd": "2",
 "probucol": "2",
 "paclitaxel": "2",
 "phosphate laxative": "3",
 "phillips' haleys m-o": "2",
 "platinol-aq": "2",
 "protriptyline": "2",
 "pepcid complete": "2",
 "pitressin": "2",
 "phenylephrine/promethazine": "2",
 "promethazine with codeine": "2",
 "phenazine 50": "2",
 "permitil": "2",
 "prolixin enanthate": "2",
 "pseudoephedrine/terfenadine": "2",
 "phenoject-50": "2",
 "peginterferon alfa-2a": "2",
 "peginterferon alfa-2b": "2",
 "pediacof": "2",
 "paliperidone": "2",
 "pirbuterol": "2",
 "pravastatin": "2",
 "polytine cs": "2",
 "propranolol": "1",
 "pentam 300": "2",
 "posture-d h/p": "2",
 "promethazine vc with codeine": "2",
 "poly cs": "2",
 "pedia-lax enema": "3",
 "platinol": "2",
 "pc-cap": "2",
 "propoxyphene compound 65": "2",
 "penbutolol": "1",
 "propiomazine": "2",
 "paraplatin": "2",
 "procot": "2",
 "posaconazole": "2",
 "protostat": "2",
 "pentamidine": "2",
 "pro-clear": "2",
 "pro-med": "2",
 "propacet 100": "2",
 "phenergan vc with codeine": "2",
 "pitavastatin": "2",
 "principen": "2",
 "promethazine vc": "2",
 "phenylhistine dh expectorant": "2",
 "parcopa": "2",
 "pharmorubicin pfs": "2",
 "prosed ds": "1",
 "phrenilin with caffeine and codeine": "2",
 "perforomist": "2",
 "phenflu cdx": "2",
 "phosenamine": "1",
 "palonosetron": "2",
 "pegintron": "2",
 "pp-cap": "2",
 "proventil hfa": "2",
 "prosed ec": "1",
 "pamelor": "2",
 "penicillamine": "2",
 "pimozide": "3",
 "pravachol": "2",
 "pentacarinat": "2",
 "promethazine vc plain": "2",
 "procan sr": "3",
 "promazine": "2",
 "pavulon": "1",
 "phenergan": "2",
 "pazopanib": "2",
 "pronestyl-sr": "3",
 "pegasys": "2",
 "promethazine vc w/codeine": "2",
 "propoxyphene": "2",
 "promethazine dm": "2",
 "paclitaxel protein-bound": "2",
 "phenergan fortis": "2",
 "pentam": "2",
 "proquin xr": "2",
 "plenaxis": "2",
 "pronestyl": "3",
 "phenergan with codeine": "2",
 "promethazine": "2",
 "pacerone": "3",
 "pedia-lax chewable tablets": "2",
 "perphenazine": "2",
 "propulsid": "3",
 "promethazine with dextromethorphan": "2",
 "promethazine hcl and codeine phosphate": "2",
 "phenazopyridine/sulfamethoxazole": "1",
 "pro-red ac": "2",
 "phenylhistine dh": "2",
 "perflutren": "2",
 "promethegan": "2",
 "promethazine hcl with codeine": "2",
 "prolixin decanoate": "2",
 "pylera": "2",
 "primrose oil": "1",
 "propafenone": "2",
 "pravigard pac": "2",
 "phenergan with dextromethorphan": "2",
 "potiga": "2",
 "prevpac": "2",
 "procanbid": "3",
 "polyhist nc": "2",
 "phillips' milk of magnesia": "2"}, "s": {"sandimmune": "2",
 "sedecal d": "2",
 "singulair": "2",
 "stalevo 100": "2",
 "sparine": "2",
 "solganal": "3",
 "suttar-2": "2",
 "saquinavir": "3",
 "sulfamethoxazole/trimethoprim": "1",
 "sunitinib": "2",
 "sulfimycin": "2",
 "super calcium": "2",
 "septra ds": "1",
 "seroquel": "2",
 "seroquel xr": "2",
 "surpass": "2",
 "sodium biphosphate/sodium phosphate": "3",
 "stalevo 125": "2",
 "soma compound with codeine": "2",
 "seldane": "2",
 "sinequan": "2",
 "sulfamethoxazole": "1",
 "statuss": "2",
 "saphris": "2",
 "smz-tmp ds": "1",
 "sabril": "3",
 "simponi": "2",
 "staxyn": "2",
 "seldane-d": "2",
 "sparfloxacin": "3",
 "serathide": "2",
 "septra iv": "1",
 "sinemet cr": "2",
 "serpazide": "2",
 "simvastatin": "2",
 "stalevo 50": "2",
 "sulfatrim": "1",
 "soltamox": "2",
 "surmontil": "2",
 "sotalol hydrochloride af": "3",
 "stalevo 75": "2",
 "strattera": "2",
 "sodium iodide i-123": "2",
 "ser-ap-es": "2",
 "stalevo": "2",
 "stavudine": "2",
 "sotalol": "3",
 "sorine": "3",
 "simcor": "2",
 "succinylcholine": "1",
 "surpass extra strength": "2",
 "suprep bowel prep kit": "3",
 "simvastatin/sitagliptin": "2",
 "silenor": "2",
 "suttar sf": "2",
 "sutent": "2",
 "stelazine": "2",
 "suprep": "3",
 "septra": "1",
 "serentil": "3",
 "stalevo 200": "2",
 "sancuso": "2",
 "sinemet": "2",
 "sectral": "1",
 "symbicort": "2",
 "sulfatrim pediatric": "1",
 "sodium iodide-i-131": "2",
 "serevent diskus": "2",
 "stalevo 150": "2",
 "sorafenib": "2",
 "serpex": "2",
 "salmeterol": "2",
 "sylatron": "2",
 "sprycel": "2"}, "r": {"rheumatrex dose pack": "1",
 "rybix odt": "3",
 "ri-mag": "2",
 "risperdal m-tab": "2",
 "rolatuss": "2",
 "robitussin-ac": "2",
 "robafen ac": "2",
 "rabavert": "2",
 "ryna-cx": "2",
 "robitussin-dac": "2",
 "ron-acid plus": "2",
 "rocuronium": "1",
 "razadyne er": "2",
 "raxar": "3",
 "romilar ac": "2",
 "robimycin": "2",
 "rythmol": "2",
 "ryzolt": "3",
 "riopan plus": "2",
 "retrovir": "2",
 "romidepsin": "2",
 "rifater": "2",
 "renacidin irrgiation": "2",
 "roferon-a": "2",
 "riopan": "2",
 "renacidin": "2",
 "risperdal consta": "2",
 "risacal-d": "2",
 "rabies vaccine, human diploid cell": "2",
 "red yeast rice": "2",
 "ritodrine": "2",
 "rolaids extra strength softchews": "2",
 "rulox plus": "2",
 "ritonavir": "2",
 "rolaids extra strength plus gas relief softchews": "2",
 "risperidone": "2",
 "rythmol sr": "2",
 "rulox 1": "2",
 "rifamate": "2",
 "robichem ac": "2",
 "reminyl": "2",
 "rolaids multi-symptom": "2",
 "rolaids regular strength": "2",
 "rulox": "2",
 "ridaura": "3",
 "ranexa": "2",
 "relcof c": "2",
 "ranolazine": "2",
 "risperdal": "2",
 "rybix": "3",
 "riopan plus double strength": "2",
 "rolaids extra strength": "2",
 "rosuvastatin": "2",
 "razadyne": "2",
 "riopan plus 2": "2",
 "rabies vaccine, purified chick embryo cell": "2",
 "ron acid": "2",
 "rilpivirine": "2",
 "ryna-c": "2",
 "remicade": "2",
 "respirol": "2",
 "rebetron": "2"}, "u": {"uretron": "1",
 "urimax": "1",
 "utrona-c": "1",
 "uroplus": "1",
 "ultram": "3",
 "ultram odt": "3",
 "utrona": "1",
 "ultra mylanta calci tabs": "2",
 "upcal d": "2",
 "urban ds": "2",
 "uroplus ds": "1",
 "urolene blue": "1",
 "uritact ds": "1",
 "uni-lan ii": "2",
 "ultram er": "3",
 "urimar-t": "1",
 "urised": "1",
 "ultracet": "3",
 "utira": "1",
 "urban": "2",
 "uni-lan": "2",
 "uretron ds": "1",
 "utira-c": "1",
 "urapine": "1",
 "uni serp": "2",
 "uritin": "1",
 "uta": "1",
 "usept": "1",
 "urisym": "1",
 "uro-mag": "2",
 "urogesic blue": "3",
 "unipres": "2",
 "uro blue": "1",
 "uritact-ec": "1",
 "uticap": "1",
 "uroxatral": "2",
 "unasyn": "2",
 "ustell": "1",
 "urelle": "1",
 "uprima": "2",
 "uro-phosphate": "3",
 "uribel": "1"}, "t": {"toprol-xl": "1",
 "tamoxifen": "2",
 "trizivir": "2",
 "tizanidine": "2",
 "tramadol": "3",
 "titralac plus liquid": "2",
 "tolterodine": "1",
 "timolol ophthalmic": "2",
 "tramal sr": "3",
 "tocilizumab": "2",
 "titralac plus": "2",
 "timoptic": "2",
 "telbivudine": "2",
 "thiethylperazine": "2",
 "t- koff": "2",
 "tussirex sugar free": "2",
 "teniposide": "2",
 "tums extra strength 750": "2",
 "temaril": "2",
 "trihist-cs": "2",
 "tears again hydrate": "1",
 "tums regular strength": "2",
 "tylenol with codeine": "2",
 "tridal": "2",
 "tetrabenazine": "2",
 "tussi-organidin nr": "2",
 "tramedo": "3",
 "tums freshers": "2",
 "tornalate": "2",
 "trisenox": "3",
 "terbinex with eco formula": "2",
 "thioridazine": "3",
 "trifluoperazine": "2",
 "tums dual action": "2",
 "telavancin": "2",
 "tinidazole": "2",
 "tussar sf": "2",
 "tussirex": "2",
 "trandate": "1",
 "tamone": "2",
 "tl-hist cm": "2",
 "tramapap": "3",
 "tempo": "2",
 "torecan": "2",
 "tofranil-pm": "2",
 "terbinafine": "2",
 "timolide": "1",
 "telithromycin": "2",
 "timoptic-xe": "2",
 "trecator": "2",
 "taxol": "2",
 "tums ultra 1000": "2",
 "timoptic ocudose": "2",
 "thorazine": "2",
 "tykerb": "2",
 "tasigna": "3",
 "timolol": "1",
 "tyzeka": "2",
 "taxotere": "2",
 "trycet": "2",
 "toviaz": "2",
 "tequin": "3",
 "trimipramine": "2",
 "tl-hist cd": "2",
 "tums smoothies": "2",
 "titralac": "2",
 "triflupromazine": "2",
 "triavil": "2",
 "totacillin-n": "2",
 "terfenadine": "2",
 "tagamet": "2",
 "trimeprazine": "2",
 "tusso-c": "2",
 "trac tabs 2x": "1",
 "tamofen": "2",
 "timolide 10-25": "1",
 "tylenol with codeine #2": "2",
 "tylenol with codeine #3": "2",
 "tylenol with codeine #4": "2",
 "trecator-sc": "2",
 "tambocor": "2",
 "tequin teqpaq": "3",
 "tums plus": "2",
 "thalomid": "2",
 "tikosyn": "3",
 "tofranil": "2",
 "triafed &amp; codeine": "2",
 "tamoxifen hexal": "2",
 "terbutaline": "2",
 "trifed c": "2",
 "tussi-organidin-s nr": "2",
 "tramahexal sr": "3",
 "tri-hydroserpine": "2",
 "trilafon": "2",
 "tussar-2": "2",
 "tussiden c": "2",
 "tums kids": "2",
 "tramal": "3",
 "toposar": "2",
 "toremifene": "3",
 "triacin c": "2",
 "tamosin": "2",
 "tagamet hb": "2",
 "thalidomide": "2",
 "tacaryl": "2",
 "tacrolimus": "2",
 "tamoxen": "2",
 "tindamax": "2",
 "trexall": "1",
 "typhoid vaccine, live": "2",
 "tracrium": "1"}, "w": {"wygesic": "2",
 "wellbutrin sr": "3",
 "wellesse liquid calcium with vitamin d": "2",
 "wellbutrin xl": "3",
 "wellbutrin": "3"}, "v": {"vivactil": "2",
 "videx": "2",
 "vasopressin": "2",
 "vytorin": "2",
 "vivotif berna vaccine": "2",
 "vigabatrin": "3",
 "vfend": "2",
 "v-gan-50": "2",
 "vascor": "3",
 "vumon": "2",
 "vinorelbine": "2",
 "vardenafil": "2",
 "vospire er": "2",
 "votrient": "2",
 "vecuronium": "1",
 "vivotif berna": "2",
 "ventolin": "2",
 "velban": "2",
 "vinblastine": "2",
 "vopac": "2",
 "voriconazole": "2",
 "velcade": "2",
 "vemurafenib": "3",
 "visicol": "3",
 "vibativ": "2",
 "v-gan-25": "2",
 "vepesid": "2",
 "ventolin hfa": "2",
 "vincristine": "2",
 "vincasar pfs": "2",
 "vanatrip": "2",
 "volmax": "2",
 "videx ec": "2",
 "vanacof cd": "2",
 "vandetanib": "3"}, "y": {"yervoy": "2",
 "yutopar": "2",
 "yodoxin": "2"}, "x": {"xopenex": "2",
 "xalkori": "3",
 "xopenex hfa": "2",
 "xopenex concentrate": "2",
 "xenazine": "2"}, "z": {"zagam respipac": "3",
 "zmax": "2",
 "z-tuss ac": "2",
 "zodryl ac": "2",
 "zalcitabine": "2",
 "zocor": "2",
 "zuplenz": "2",
 "zelboraf": "3",
 "zemuron": "1",
 "zithromax": "2",
 "ziprasidone": "3",
 "zyvox": "2",
 "zofran": "2",
 "zerit": "2",
 "zamadol": "3",
 "zodryl dac": "2",
 "zodryl dec": "2",
 "zydol": "3",
 "zerit xr": "2",
 "zafirlukast": "2",
 "zagam": "3",
 "zyban": "3",
 "zofran odt": "2",
 "zaponex": "3",
 "zanaflex": "2",
 "zotex-c": "2",
 "zidovudine": "2"}}];