interactions["cholecalciferol"]=["cholecalciferol", {"a": {"aminophylline/amobarbital/ephedrine": "2",
 "aliskiren/amlodipine/hydrochlorothiazide": "2",
 "aldroxicon i": "2",
 "atacand hct": "2",
 "alginic acid/aluminum hydroxide/magnesium carbonate": "2",
 "antispas": "2",
 "amlodipine/hydrochlorothiazide/valsartan": "2",
 "alli": "1",
 "amytal sodium": "2",
 "aspir-mox": "2",
 "aldoril": "2",
 "acetaminophen/butalbital/caffeine/codeine": "2",
 "ascomp with codeine": "2",
 "almora": "2",
 "aspirin buffered": "2",
 "aldoril d50": "2",
 "arthritis pain formula": "2",
 "acetaminophen/caffeine/magnesium salicylate": "2",
 "accuretic": "2",
 "acetaminophen/butalbital": "2",
 "acetaminophen/magnesium salicylate/pamabrom": "2",
 "arthriten": "2",
 "acid gone antacid": "2",
 "acid gone": "2",
 "azilsartan medoxomil/chlorthalidone": "2",
 "aspirin/butalbital/caffeine/codeine": "2",
 "anoquan": "2",
 "arcet": "2",
 "alagesic": "2",
 "alkabel-sr": "2",
 "aldroxicon ii": "2",
 "aminophylline/ephedrine/phenobarbital/potassium iodide": "2",
 "amobarbital": "2",
 "aquatensen": "2",
 "acetaminophen/butalbital/caffeine": "2",
 "aminophylline/ephedrine/guaifenesin/phenobarbital": "2",
 "almacone-2": "2",
 "ascriptin maximum strength": "2",
 "aluminum hydroxide/mineral oil": "2",
 "avalide": "2",
 "alpha keri": "2",
 "aspirin/butalbital/caffeine": "2",
 "antispasmodic": "2",
 "aluminum hydroxide/diphenhydramine/lidocaine/magnesium hydroxide/simethicone topical": "2",
 "aldoril 25": "2",
 "aluminum hydroxide/calcium carbonate/magnesium hydroxide/simethicone": "2",
 "advanced formula di-gel": "2",
 "acid controller complete dual action": "2",
 "amobarbital/secobarbital": "2",
 "alphabath": "2",
 "alenic alka tablet": "2",
 "acid gone extra strength": "2",
 "aluminum hydroxide/magnesium hydroxide/simethicone": "2",
 "antrocol": "2",
 "ascriptin": "2",
 "apresazide": "2",
 "aquacot": "2",
 "axocet": "2",
 "aldoclor-250": "2",
 "atropine/hyoscyamine/phenobarbital/scopolamine": "2",
 "aliskiren/hydrochlorothiazide": "2",
 "acetaminophen/aluminum hydroxide/aspirin/caffeine/magnesium hydroxide": "2",
 "aldoclor-150": "2",
 "almacone": "2",
 "atenolol/chlorthalidone": "2",
 "asthmacon": "2",
 "atropine/phenobarbital": "2",
 "alamag": "2",
 "alamag plus": "2",
 "alagesic lq": "2",
 "amiloride/hydrochlorothiazide": "2",
 "aluminum hydroxide/aspirin/calcium carbonate/magnesium hydroxide": "2",
 "americet": "2",
 "aluminum hydroxide/magnesium hydroxide": "2",
 "aldoril 15": "2",
 "acid reducer + antacid dual action": "2",
 "aspirin/butalbital": "2",
 "aquazide h": "2",
 "alginic acid/aluminum hydroxide/magnesium trisilicate": "2",
 "amturnide": "2",
 "aldoril d30": "2",
 "alenic alka": "2",
 "aspir-mox ib": "2",
 "aldactazide": "2",
 "amlodipine/hydrochlorothiazide/olmesartan": "2",
 "acetaminophen/caffeine/magnesium salicylate/phenyltoloxamine": "2",
 "anolor 300": "2"}, "c": {"chlorthalidone/clonidine": "2",
 "calcitriol topical": "2",
 "cafgesic forte": "2",
 "chlorothiazide/methyldopa": "2",
 "calcijex": "3",
 "cephadyn": "2",
 "carbatrol": "2",
 "captopril/hydrochlorothiazide": "2",
 "cardoxin": "2",
 "corzide": "2",
 "citrate of magnesia": "2",
 "colesevelam": "2",
 "capozide 50/25": "2",
 "calcium carbonate/magnesium hydroxide": "2",
 "cascara sagrada/magnesium hydroxide": "2",
 "calcium acetate/magnesium carbonate": "2",
 "cholestyramine light": "2",
 "cholestyramine": "2",
 "choline magnesium trisalicylate": "2",
 "choline salicylate/magnesium salicylate": "2",
 "calcium carbonate/famotidine/magnesium hydroxide": "2",
 "capozide 25/15": "2",
 "colestid flavored": "2",
 "clorpres": "2",
 "combiflex es": "2",
 "chlorthalidone/reserpine": "2",
 "chlorthalidone": "2",
 "citric acid/glucono-delta-lactone/magnesium carbonate topical": "2",
 "cerebyx": "2",
 "candesartan/hydrochlorothiazide": "2",
 "chelated magnesium": "2",
 "corzide 80/5": "2",
 "corzide 40/5": "2",
 "calcipotriene topical": "2",
 "chlorothiazide": "2",
 "calcitrene": "2",
 "colestid": "2",
 "calcitriol": "3",
 "cafatine pb": "2",
 "carbamazepine": "2",
 "colestipol": "2",
 "capozide 50/15": "2",
 "citroma": "2",
 "cmt": "2",
 "capacet": "2",
 "capozide": "2",
 "capozide 25/25": "2",
 "chlorothiazide/reserpine": "2",
 "chardonna-2": "2",
 "caffeine/magnesium salicylate": "2",
 "calcium carbonate/magnesium hydroxide/simethicone": "2",
 "chloromag": "2",
 "calcium carbonate/magnesium carbonate": "2",
 "carozide": "2"}, "b": {"bellaphen-s": "2",
 "bayer select backache pain formula": "2",
 "belladonna/ergotamine/phenobarbital": "2",
 "benazepril/hydrochlorothiazide": "2",
 "butisol sodium": "2",
 "bellatal er": "2",
 "butabarbital/hyoscyamine/phenazopyridine": "2",
 "bupap": "2",
 "betamethasone/calcipotriene topical": "2",
 "belcomp-pb": "2",
 "belladonna/caffeine/ergotamine/pentobarbital": "2",
 "butibel": "2",
 "bendroflumethiazide/rauwolfia serpentina": "2",
 "butalbital compound": "2",
 "benzthiazide": "2",
 "butalbital": "2",
 "benicar hct": "2",
 "bellamor": "2",
 "bellaspas": "2",
 "butex forte": "2",
 "busodium": "2",
 "bel-phen-ergot": "2",
 "bisacodyl/magnesium citrate": "2",
 "butabarbital": "2",
 "barbidonna": "2",
 "bisoprolol/hydrochlorothiazide": "2",
 "bellergal-s": "2",
 "bellalphen": "2",
 "bellamine": "2",
 "bellatal": "2",
 "belladonna/butabarbital": "2",
 "bel-tabs": "2",
 "bucet": "2",
 "bellamine s": "2",
 "bendroflumethiazide": "2",
 "bendroflumethiazide/nadolol": "2"}, "e": {"enduronyl forte": "2",
 "enduronyl": "2",
 "evac-q-kwik": "2",
 "elixiral": "2",
 "ergocomp-pb": "2",
 "edarbyclor": "2",
 "esgic-plus": "2",
 "epsom salt": "2",
 "ephedrine/phenobarbital/theophylline": "2",
 "enalapril/hydrochlorothiazide": "2",
 "eperbel-s": "2",
 "ex-lax milk of magnesia": "2",
 "enduron": "2",
 "ephedrine/phenobarbital/potassium iodide/theophylline": "2",
 "ezol": "2",
 "exforge hct": "2",
 "esimil": "2",
 "ergocaffpb": "2",
 "exna": "2",
 "esidrix": "2",
 "e-caff p-b": "2",
 "equetro": "2",
 "ezide": "2",
 "endolor": "2",
 "epitol": "2",
 "ergocaf-pb": "2",
 "esgic": "2",
 "eprosartan/hydrochlorothiazide": "2"}, "d": {"dolmar": "2",
 "diurese": "2",
 "donnatal": "2",
 "donnapine": "2",
 "doans pills extra strength": "2",
 "diuril sodium": "2",
 "di-gel lemon": "2",
 "di-gel": "2",
 "deserpidine/hydrochlorothiazide": "2",
 "dyphylline/ephedrine/guaifenesin/phenobarbital": "2",
 "diuril": "2",
 "diutensen-r": "2",
 "digitoxin": "2",
 "dilantin": "2",
 "diphenhydramine/magnesium salicylate": "2",
 "diovan hct": "2",
 "diurex": "2",
 "durabac forte": "2",
 "digoxin": "2",
 "dual action complete": "2",
 "doan's pills": "2",
 "diuretic ap-es": "2",
 "dyazide": "2",
 "digitek": "2",
 "dulcolax bowel cleansing": "2",
 "demi-regroton": "2",
 "donnatal extentabs": "2",
 "diucardin": "2",
 "diupres-250": "2",
 "dewees carminative": "2",
 "dolgic plus": "2",
 "dolgic lq": "2",
 "diupres-500": "2",
 "donnaphen": "2",
 "dovobet": "2",
 "dulcolax milk of magnesia": "2",
 "di-gel mint": "2",
 "doans pm": "2",
 "dovonex": "2",
 "dutoprol": "2",
 "d-tal": "2",
 "diaqua": "2",
 "doxercalciferol": "3",
 "dewitt's pain reliever": "2",
 "duragal-s": "2",
 "dolgic": "2",
 "deserpidine/methyclothiazide": "2"}, "g": {"gelusil": "2",
 "gaviscon-2": "2",
 "genaton chewable": "2",
 "genaton": "2",
 "guanethidine/hydrochlorothiazide": "2",
 "gaviscon regular strength tablets": "2",
 "gaviscon extra strength tablets": "2",
 "geone": "2",
 "g-1": "2",
 "gaviscon regular strength liquid": "2",
 "gaviscon extra relief formula": "2",
 "gaviscon extra strength liquid": "2"}, "f": {"fiorinal with codeine": "2",
 "floricet with codeine": "2",
 "first mouthwash blm": "2",
 "fioricet": "2",
 "fiortal": "2",
 "fiormor": "2",
 "fiorinal": "2",
 "fioricet with codeine": "2",
 "fast acting mylanta": "2",
 "fortabs": "2",
 "femcet": "2",
 "fiorinal with codeine iii": "2",
 "flumezide": "2",
 "farbital": "2",
 "fleet mineral oil enema": "2",
 "felbatol": "2",
 "felbamate": "2",
 "fosinopril/hydrochlorothiazide": "2",
 "fiorpap": "2",
 "fiortal with codeine": "2",
 "fosphenytoin": "2"}, "i": {"inderide la": "2",
 "isoniazid": "2",
 "isoniazid/rifampin": "2",
 "indapamide": "2",
 "inderide": "2",
 "ide-cet": "2",
 "idenal": "2",
 "isocet": "2",
 "isoniazid/pyrazinamide/rifampin": "2",
 "isonarif": "2"}, "h": {"hhr": "2",
 "hydro-reserp": "2",
 "hydrochlorothiazide/triamterene": "2",
 "hydroserpine 1": "2",
 "hyzaar": "2",
 "hydrochlorothiazide/methyldopa": "2",
 "hydralazine/hydrochlorothiazide": "2",
 "hydrochlorothiazide/timolol": "2",
 "heartburn antacid extra strength": "2",
 "hydrochlorothiazide/spironolactone": "2",
 "hydropres-50": "2",
 "hydrap-es": "2",
 "hydroserpine": "2",
 "hydroflumethiazide/reserpine": "2",
 "hydrochlorothiazide/losartan": "2",
 "hydroflumethiazide": "2",
 "hydrodiuril": "2",
 "hygroton": "2",
 "hydrochlorothiazide/metoprolol": "2",
 "hyosophen": "2",
 "hydrochlorothiazide/olmesartan": "2",
 "hydralazine/hydrochlorothiazide/reserpine": "2",
 "hydrochlorothiazide/moexipril": "2",
 "hydrochlorothiazide/irbesartan": "2",
 "hydro par": "2",
 "hydrochlorothiazide/propranolol": "2",
 "hydrochlorothiazide/lisinopril": "2",
 "haley's m-o": "2",
 "hydra-zide": "2",
 "hydrochlorothiazide/valsartan": "2",
 "haponal": "2",
 "hydrochlorothiazide/telmisartan": "2",
 "hydrochlorothiazide/reserpine": "2",
 "hydrochlorothiazide/quinapril": "2",
 "hydropres-25": "2",
 "hydrochlorothiazide": "2",
 "hydralazine plus": "2",
 "hectorol": "3",
 "hyoscyamine/phenobarbital": "2",
 "hydroserp": "2"}, "k": {"kondremul plain": "2",
 "kneerelief": "2",
 "kondremul": "2",
 "kondremul with phenolphtalein": "2"}, "m": {"metahydrin": "2",
 "micardis hct": "2",
 "magdelay": "2",
 "maalox advanced maximum strength": "2",
 "magnesium oxide": "2",
 "magsal": "2",
 "milantex maximum strength": "2",
 "mi-acid ii": "2",
 "methyclothiazide/reserpine": "2",
 "migracet-pb": "2",
 "minizide": "2",
 "magnesium carbonate": "2",
 "mephobarbital": "2",
 "muri-lube": "2",
 "moduretic": "2",
 "mag-g": "2",
 "maalox max wild berry": "2",
 "mylagen-ii": "2",
 "maggel": "2",
 "magan": "2",
 "myogesic": "2",
 "mykrox": "2",
 "mag-sr": "2",
 "milkinol": "2",
 "mag-200": "2",
 "mylagen": "2",
 "maalox": "2",
 "milantex": "2",
 "magnesium hydroxide/mineral oil": "2",
 "magonate natal": "2",
 "mylanta maximum strength": "2",
 "magnesium sulfate/potassium sulfate/sodium sulfate": "2",
 "mysoline": "2",
 "mi-acid double strength": "2",
 "mag-phen": "2",
 "mag-tab sr": "2",
 "magaant": "2",
 "magnesiocard": "2",
 "mintox extra strength": "2",
 "mg plus protein": "2",
 "magnesium hydroxide": "2",
 "maldroxal": "2",
 "masanti ds": "2",
 "mycobutin": "2",
 "mag-carb": "2",
 "maalox plus extra strength": "2",
 "mylanta maximum strength cherry": "2",
 "maginex ds": "2",
 "maalox advanced regular strength": "2",
 "mylanta ultra": "2",
 "metolazone": "2",
 "maldroxal plus": "2",
 "methyclothiazide": "2",
 "magnesium sulfate": "2",
 "milk of magnesia": "2",
 "magnesium salicylate": "2",
 "mi-acid": "2",
 "mygracet": "2",
 "margesic": "2",
 "mintox plus": "2",
 "mobigesic": "2",
 "magnesium salicylate/phenyltoloxamine": "2",
 "magnesium aspartate": "2",
 "magnesium amino acids chelate": "2",
 "mintox maximum strength": "2",
 "mylanta supreme": "2",
 "minotal": "2",
 "mst": "2",
 "maalox plus": "2",
 "mag-ox": "2",
 "mag-caps": "2",
 "medigesic": "2",
 "mebaral": "2",
 "mylanta ultimate strength": "2",
 "marblen": "2",
 "magnebind 200": "2",
 "mylanta ds fast acting": "2",
 "moduretic 5-50": "2",
 "masanti": "2",
 "maxzide-25": "2",
 "magnebind 300": "2",
 "magnesium citrate": "2",
 "microzide": "2",
 "magnesium gluconate": "2",
 "masanti supreme": "2",
 "magnaprin": "2",
 "mag-ox 400": "2",
 "maalox tc": "2",
 "micomp-pb": "2",
 "mylanta": "2",
 "mudrane gg": "2",
 "magtrate": "2",
 "mylanta fast acting": "2",
 "magonate": "2",
 "maxzide": "2",
 "mobidin": "2",
 "marten-tab": "2",
 "mag-oxide": "2",
 "monopril hct": "2",
 "maalox max": "2",
 "magnesium chloride": "2",
 "maginex": "2",
 "maalox antacid antigas regular strength": "2",
 "mintox": "2",
 "mudrane": "2",
 "metatensin 4": "2",
 "metatensin 2": "2",
 "mintox tablets": "2",
 "magnesium lactate": "2",
 "mineral oil": "2",
 "mineral oil/phenolphthalein": "2",
 "mag 64": "2",
 "mylanta gelcap": "2",
 "magmin": "2",
 "maalox hrf": "2",
 "marpres": "2"}, "l": {"levsin with phenobarbital": "2",
 "lotensin hct": "2",
 "lufyllin-epg": "2",
 "luminal": "2",
 "loqua": "2",
 "lanoxicaps": "2",
 "lozol": "2",
 "locholest light": "2",
 "lanolin/mineral oil topical": "2",
 "lopressor hct": "2",
 "liquiprep": "2",
 "loso prep bowel cleansing system": "2",
 "laniroif": "2",
 "locholest": "2",
 "liqui doss": "2",
 "lanoxin": "2"}, "o": {"orlistat": "1",
 "oreticyl forte": "2",
 "oretic": "2",
 "oxcarbazepine": "2",
 "oreticyl 50": "2",
 "optimum magnesium gluconate": "2",
 "orbivan": "2",
 "oreticyl 25": "2"}, "n": {"naturetin": "2",
 "naturetin-10": "2",
 "nuprin backache caplet": "2",
 "naturetin-5": "2",
 "naqua": "2",
 "nydrazid": "2",
 "nonbac": "2",
 "nembutal sodium": "2",
 "nembutal": "2",
 "novasal": "2",
 "nephrox": "2"}, "q": {"quadrinal": "2",
 "questran light": "2",
 "quadrapax": "2",
 "questran": "2",
 "quinaretic": "2"}, "p": {"pyridium plus": "2",
 "pentobarbital": "2",
 "phillips' cramp-free": "2",
 "phrenilin forte": "2",
 "pamprin cramp menstrual pain relief": "2",
 "polythiazide": "2",
 "phrenilin with caffeine and codeine": "2",
 "pacaps": "2",
 "phenytek": "2",
 "pb-hyos": "2",
 "prominol": "2",
 "pedia-lax chewable tablets": "2",
 "pyrelle hb": "2",
 "prinzide": "2",
 "priftin": "2",
 "promacet": "2",
 "pharmagesic": "2",
 "phenazoforte plus": "2",
 "phenytoin": "2",
 "primidone": "2",
 "prevalite": "2",
 "phenobarbital": "2",
 "paricalcitol": "3",
 "phrenilin": "2",
 "phenytoin sodium, prompt": "2",
 "polythiazide/prazosin": "2",
 "phenaz plus": "2",
 "phillips' haleys m-o": "2",
 "polythiazide/reserpine": "2",
 "pepcid complete": "2",
 "phillips' milk of magnesia": "2"}, "s": {"slow-mag": "2",
 "salutensin-demi": "2",
 "seconal": "2",
 "saluron": "2",
 "solfoton": "2",
 "spasmolin": "2",
 "spastrin": "2",
 "sulfamag": "2",
 "serathide": "2",
 "spasquid": "2",
 "serpazide": "2",
 "salutensin": "2",
 "suprep": "2",
 "seconal sodium": "2",
 "sorilux": "2",
 "ser-ap-es": "2",
 "sedapap": "2",
 "servira": "2",
 "suprep bowel prep kit": "2",
 "secobarbital": "2",
 "serpex": "2",
 "seconal sodium pulvules": "2"}, "r": {"reserpine/trichlormethiazide": "2",
 "royvac bowel evacuant": "2",
 "rimactane": "2",
 "rifabutin": "2",
 "rauzide": "2",
 "renese-r": "2",
 "rifater": "2",
 "renacidin irrgiation": "2",
 "rocaltrol": "3",
 "regroton": "2",
 "renacidin": "2",
 "rondameth": "2",
 "rulox plus": "2",
 "rulox 1": "2",
 "rifamate": "2",
 "rifapentine": "2",
 "rifampin": "2",
 "rolaids multi-symptom": "2",
 "rolaids regular strength": "2",
 "rulox": "2",
 "repan": "2",
 "rifadin iv": "2",
 "rolaids extra strength": "2",
 "rifadin": "2",
 "renese": "2",
 "re-pb hyos elixir": "2"}, "u": {"urban": "2",
 "unipres": "2",
 "uni-lan ii": "2",
 "uro-mag": "2",
 "uni serp": "2",
 "urelief plus": "2",
 "uni-lan": "2",
 "urban ds": "2",
 "uniretic": "2"}, "t": {"tenake": "2",
 "tenoretic": "2",
 "triaprin": "2",
 "taclonex": "2",
 "tencet": "2",
 "tri-hydroserpine": "2",
 "trilisate": "2",
 "tums dual action": "2",
 "trichlormethiazide": "2",
 "taclonex scalp": "2",
 "tenoretic 100": "2",
 "tenoretic 50": "2",
 "thalitone": "2",
 "tetra-mag": "2",
 "tribenzor": "2",
 "tekturna hct": "2",
 "tempo": "2",
 "teveten hct": "2",
 "theodrine": "2",
 "tridate": "2",
 "tuinal": "2",
 "trileptal": "2",
 "timolide 10-25": "2",
 "tedrigen": "2",
 "timolide": "2",
 "tegretol": "2",
 "tricosal": "2",
 "tegretol xr": "2",
 "thera derm": "2",
 "tencon": "2",
 "triad": "2",
 "two-dyne": "2"}, "w": {"welchol": "2"}, "v": {"vaseretic 10-25": "2",
 "vaseretic": "2",
 "vaseretic 5-12.5": "2",
 "vectical": "2"}, "x": {"xenical": "1"}, "z": {"zebutal": "2",
 "zestoretic": "2",
 "ziac": "2",
 "zemplar": "3",
 "zaroxolyn": "2"}}];